// Generated by scripts/port-interview-prepper.mjs from the interview-prepper catalogue.
// Server-only reference solutions. Never import from client code.
// English is the source of truth; Czech copy lives in the sibling *.cs.ts overlay.

import type { CodingSolution } from '../types';

export const JAVASCRIPT_SOLUTIONS: Record<string, CodingSolution> = {
  "js-double-numbers": { solution: "const double = numbers => numbers.map(number => number * 2);" },
  "js-even-numbers": { solution: "const evens = numbers => numbers.filter(number => number % 2 === 0);" },
  "js-sum-array": { solution: "const sum = numbers => numbers.reduce((total, number) => total + number, 0);" },
  "js-longest-word": {
    solution: "const longest = words => words.reduce((best, word) => word.length > best.length ? word : best, \"\");",
  },
  "js-count-vowels": {
    solution: "const countVowels = text => [...text.toLowerCase()].filter(letter => \"aeiou\".includes(letter)).length;",
  },
  "js-reverse-string": { solution: "const reverse = text => [...text].reverse().join(\"\");" },
  "js-positive-numbers": { solution: "const positives = numbers => numbers.filter(number => number > 0);" },
  "js-square-numbers": { solution: "const squares = numbers => numbers.map(number => number ** 2);" },
  "js-largest-number": { solution: "const largest = numbers => Math.max(...numbers);" },
  "js-fizz-values": {
    solution: "const fizz = n => Array.from({length: n}, (_, index) => index + 1).map(number => number % 3 === 0 ? \"Fizz\" : number);",
  },
  "js-countdown": {
    solution: "const countDown = n => { const result = []; while (n > 0) result.push(n--); return result; };",
  },
  "js-first-letters": { solution: "const firstLetters = words => words.map(word => word[0]);" },
  "js-has-adult": { solution: "const hasAdult = ages => ages.some(age => age >= 18);" },
  "js-all-positive": { solution: "const allPositive = numbers => numbers.every(number => number > 0);" },
  "js-total-price": { solution: "const total = items => items.reduce((sum, item) => sum + item.price, 0);" },
  "js-capitalize": { solution: "const capitalize = word => word ? word[0].toUpperCase() + word.slice(1) : \"\";" },
  "js-unique-values": { solution: "const unique = values => [...new Set(values)];" },
  "js-word-count": {
    solution: "const wordCount = sentence => sentence.trim() ? sentence.trim().split(/\\s+/).length : 0;",
  },
  "js-find-user": { solution: "const findUser = (users, name) => users.find(user => user.name === name);" },
  "js-odd-sum": {
    solution: "const oddSum = numbers => numbers.filter(number => number % 2 !== 0).reduce((sum, number) => sum + number, 0);",
  },
  "js-repeat-word": { solution: "const repeat = (word, n) => Array.from({length: n}, () => word).join(\" \");" },
  "js-number-range": {
    solution: "const range = (start, end) => Array.from({length: end - start + 1}, (_, index) => start + index);",
  },
  "js-average": {
    solution: "const average = numbers => numbers.length ? numbers.reduce((sum, number) => sum + number, 0) / numbers.length : 0;",
  },
  "js-short-words": { solution: "const shortWords = words => words.filter(word => word.length < 5);" },
  "js-object-keys": { solution: "const keys = object => Object.keys(object);" },
  "js-object-values": { solution: "const values = object => Object.values(object);" },
  "js-activate-user": { solution: "const activate = user => ({...user, active: true});" },
  "js-palindrome": { solution: "const isPalindrome = word => word === [...word].reverse().join(\"\");" },
  "js-letter-counts": {
    solution: "const countLetters = text => [...text].reduce((counts, letter) => ({...counts, [letter]: (counts[letter] ?? 0) + 1}), {});",
  },
  "js-flatten-arrays": {
    solution: "const flatten = arrays => arrays.reduce((result, array) => [...result, ...array], []);",
  },
  "js-call-once": {
    solution: "const once = fn => { let called = false, value; return (...args) => { if (!called) { called = true; value = fn(...args); } return value; }; };",
  },
  "js-counter-object": {
    solution: "const makeCounter = () => { let count = 0; const counter = {increment: () => (count += 1, counter), reset: () => (count = 0, counter), value: () => count}; return counter; };",
  },
  "js-debounce-calls": {
    solution: "const debounce = (fn, ms) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); }; };",
  },
  "js-throttle-calls": {
    solution: "const throttle = (fn, ms) => { let last = -Infinity; return (...args) => { if (Date.now() - last >= ms) { last = Date.now(); fn(...args); } }; };",
  },
  "js-sleep": { solution: "const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));" },
  "js-retry-on-failure": {
    solution: "const retry = async (fn, attempts) => { let lastError; for (let attempt = 0; attempt < attempts; attempt += 1) { try { return await fn(); } catch (error) { lastError = error; } } throw lastError; };",
  },
  "js-clone-promise-all": {
    solution: "const promiseAll = promises => new Promise((resolve, reject) => { const results = []; let settled = 0; if (!promises.length) resolve(results); promises.forEach((promise, index) => Promise.resolve(promise).then(value => { results[index] = value; settled += 1; if (settled === promises.length) resolve(results); }, reject)); });",
  },
  "js-run-tasks-in-order": {
    solution: "const runSequentially = async tasks => { const results = []; for (const task of tasks) results.push(await task()); return results; };",
  },
  "js-chunk-an-array": {
    solution: "const chunk = (array, size) => Array.from({length: Math.ceil(array.length / size)}, (_, index) => array.slice(index * size, index * size + size));",
  },
  "js-group-by-key": {
    solution: "const groupBy = (array, keyFn) => array.reduce((groups, item) => { const key = keyFn(item); (groups[key] ??= []).push(item); return groups; }, {});",
  },
  "js-memoize-results": {
    solution: "const memoize = fn => { const cache = new Map(); return (...args) => { if (!cache.has(args[0])) cache.set(args[0], fn(...args)); return cache.get(args[0]); }; };",
  },
  "js-event-emitter": {
    solution: "const createEmitter = () => { const listeners = {}; const emitter = {on: (name, listener) => ((listeners[name] ??= []).push(listener), emitter), off: (name, listener) => (listeners[name] = listener ? (listeners[name] ?? []).filter(one => one !== listener) : [], emitter), emit: (name, payload) => (listeners[name] ?? []).map(listener => listener(payload))}; return emitter; };",
  },
  "js-lru-cache": {
    solution: "const LRUCache = strArr => { const cache = []; for (const letter of strArr) { const at = cache.indexOf(letter); if (at !== -1) cache.splice(at, 1); cache.push(letter); if (cache.length > 5) cache.shift(); } return cache.join(\"-\"); };",
  },
};
