// Generated by scripts/port-interview-prepper.mjs from the interview-prepper catalogue.
// Server-only reference solutions. Never import from client code.
// English is the source of truth; Czech copy lives in the sibling *.cs.ts overlay.

import type { CodingSolution } from '../types';

export const TYPESCRIPT_SOLUTIONS: Record<string, CodingSolution> = {
  "ts-typed-slug": {
    solution: "const toSlug = (title: string): string => title.trim().toLowerCase().split(/\\s+/).filter(Boolean).join(\"-\");",
    junior: `const toSlug = (title: string): string => {
  const words = title.trim().split(" ");
  let slug = "";
  for (const word of words) {
    if (word === "") {
      continue;
    }
    if (slug !== "") {
      slug += "-";
    }
    slug += word.toLowerCase();
  }
  return slug;
};`,
    senior: `const toSlug = (title: string): string => title.trim().toLowerCase().replace(/\\s+/g, "-");`,
    hiddenTests: [
      { call: "toSlug(\"My   First Post\")", expected: "my-first-post" },
      { call: "toSlug(\"   \")", expected: "" },
      { call: "toSlug(\"TypeScript\")", expected: "typescript" },
      { call: "toSlug(\" Learn TS Today \")", expected: "learn-ts-today" },
    ],
  },
  "ts-top-three-scores": {
    solution: "const topThree = (scores: number[]): number[] => [...scores].sort((one, other) => other - one).slice(0, 3);",
    junior: `const topThree = (scores: number[]): number[] => {
  const sorted: number[] = [];
  for (const score of scores) {
    sorted.push(score);
  }
  sorted.sort((a, b) => b - a);
  const best: number[] = [];
  for (let i = 0; i < sorted.length && i < 3; i += 1) {
    best.push(sorted[i]);
  }
  return best;
};`,
    senior: `const topThree = (scores: number[]): number[] =>
  // Carry only the current best three, so the whole list is never sorted.
  scores.reduce<number[]>((best, score) => [...best, score].sort((one, other) => other - one).slice(0, 3), []);`,
    hiddenTests: [
      { call: "topThree([10,50,20,40,30])", expected: [50, 40, 30] },
      { call: "topThree([100,9,20])", expected: [100, 20, 9] },
      { call: "topThree([2,8])", expected: [8, 2] },
      { call: "topThree([7,7,3,7])", expected: [7, 7, 7] },
      { call: "(() => { const scores = [1,3,2]; topThree(scores); return scores; })()", expected: [1, 3, 2] },
    ],
  },
  "ts-greeting-with-a-default": {
    solution: "const greet = (name: string, greeting = \"Hello\"): string => `${greeting}, ${name}!`;",
    junior: `const greet = (name: string, greeting?: string): string => {
  let opener: string;
  if (greeting === undefined) {
    opener = "Hello";
  } else {
    opener = greeting;
  }
  return opener + ", " + name + "!";
};`,
    senior: `const greet = (name: string, greeting?: string): string => {
  // ?? treats only undefined as missing, so an explicit "" is kept as a blank opener.
  const opener = greeting ?? "Hello";
  return \`\${opener}, \${name}!\`;
};`,
    hiddenTests: [
      { call: "greet(\"Eve\", \"Welcome\")", expected: "Welcome, Eve!" },
      { call: "greet(\"Fay\")", expected: "Hello, Fay!" },
      { call: "greet(\"Ivy\", \"\")", expected: ", Ivy!" },
    ],
  },
  "ts-person-interface": {
    solution: `interface Person {
  first: string;
  last: string;
}

const fullName = (person: Person): string => [person.first, person.last].filter(Boolean).join(" ");`,
    junior: `interface Person {
  first: string;
  last: string;
}

const fullName = (person: Person): string => {
  if (person.first === "") {
    return person.last;
  }
  if (person.last === "") {
    return person.first;
  }
  return person.first + " " + person.last;
};`,
    senior: `interface Person {
  first: string;
  last: string;
}

// A missing half leaves one stray space at an end, which trim() removes.
const fullName = ({ first, last }: Person): string => \`\${first} \${last}\`.trim();`,
    hiddenTests: [
      { call: "fullName({first:\"Grace\",last:\"Hopper\"})", expected: "Grace Hopper" },
      { call: "fullName({first:\"\",last:\"Prince\"})", expected: "Prince" },
      { call: "fullName({first:\"Madonna\",last:\"\"})", expected: "Madonna" },
    ],
  },
  "ts-optional-nickname": {
    solution: `interface User {
  name: string;
  nickname?: string;
}

const displayName = (user: User): string => user.nickname ?? user.name;`,
    junior: `interface User {
  name: string;
  nickname?: string;
}

const displayName = (user: User): string => {
  if (user.nickname !== undefined) {
    return user.nickname;
  }
  return user.name;
};`,
    senior: `interface User {
  name: string;
  nickname?: string;
}

const displayName = (user: User): string => {
  // A destructuring default only fills in for undefined, so "" stays a deliberate blank.
  const { name, nickname = name } = user;
  return nickname;
};`,
    hiddenTests: [
      { call: "displayName({name:\"Eve\",nickname:\"Evie\"})", expected: "Evie" },
      { call: "displayName({name:\"Fay\"})", expected: "Fay" },
      { call: "displayName({name:\"Gus\",nickname:\"\"})", expected: "" },
    ],
  },
  "ts-padded-id": {
    solution: "const idText = (id: string | number): string => (typeof id === \"number\" ? String(id).padStart(4, \"0\") : id);",
    junior: `const idText = (id: string | number): string => {
  if (typeof id === "string") {
    return id;
  }
  let text = String(id);
  while (text.length < 4) {
    text = "0" + text;
  }
  return text;
};`,
    senior: `const idText = (id: string | number): string => {
  if (typeof id === "string") return id;
  return id.toString().padStart(4, "0");
};`,
    hiddenTests: [
      { call: "idText(42)", expected: "0042" },
      { call: "idText(0)", expected: "0000" },
      { call: "idText(\"7\")", expected: "7" },
      { call: "idText(99999)", expected: "99999" },
    ],
  },
  "ts-shipping-speed": {
    solution: `type Speed = "standard" | "express" | "overnight";

const shippingDays = (speed: Speed, weekend: boolean): number => {
  const base = speed === "standard" ? 5 : speed === "express" ? 2 : 1;
  return weekend ? base + 1 : base;
};`,
    junior: `type Speed = "standard" | "express" | "overnight";

const shippingDays = (speed: Speed, weekend: boolean): number => {
  let days = 0;
  if (speed === "standard") {
    days = 5;
  } else if (speed === "express") {
    days = 2;
  } else {
    days = 1;
  }
  if (weekend) {
    days = days + 1;
  }
  return days;
};`,
    senior: `type Speed = "standard" | "express" | "overnight";

// Record<Speed, number> refuses a missing entry, so adding a speed is a one-line change here.
const BASE_DAYS: Record<Speed, number> = { standard: 5, express: 2, overnight: 1 };

const shippingDays = (speed: Speed, weekend: boolean): number => BASE_DAYS[speed] + (weekend ? 1 : 0);`,
    hiddenTests: [
      { call: "shippingDays(\"express\", true)", expected: 3 },
      { call: "[\"standard\",\"express\",\"overnight\"].map(speed => shippingDays(speed, true))", expected: [6, 3, 2] },
      { call: "[\"standard\",\"express\",\"overnight\"].map(speed => shippingDays(speed, false))", expected: [5, 2, 1] },
    ],
  },
  "ts-split-a-name": {
    solution: `const splitName = (text: string): [string, string] => {
  const space = text.indexOf(" ");
  return space === -1 ? [text, ""] : [text.slice(0, space), text.slice(space + 1)];
};`,
    junior: `const splitName = (text: string): [string, string] => {
  let spaceAt = -1;
  for (let i = 0; i < text.length; i += 1) {
    if (text[i] === " ") {
      spaceAt = i;
      break;
    }
  }
  if (spaceAt === -1) {
    return [text, ""];
  }
  const first = text.slice(0, spaceAt);
  const rest = text.slice(spaceAt + 1);
  return [first, rest];
};`,
    senior: `const splitName = (text: string): [string, string] => {
  // Rest destructuring takes the first word and keeps everything after it, spaces included.
  const [first, ...rest] = text.split(" ");
  return [first, rest.join(" ")];
};`,
    hiddenTests: [
      { call: "splitName(\"Grace Brewster Murray Hopper\")", expected: ["Grace", "Brewster Murray Hopper"] },
      { call: "splitName(\"Cher\")", expected: ["Cher", ""] },
      { call: "splitName(\"Jo  Smith\")", expected: ["Jo", " Smith"] },
      { call: "splitName(\"A B\")", expected: ["A", "B"] },
    ],
  },
  "ts-tally-votes": {
    solution: "const tally = (votes: string[]): Record<string, number> => votes.reduce<Record<string, number>>((counts, vote) => ({...counts, [vote]: (counts[vote] ?? 0) + 1}), {});",
    junior: `const tally = (votes: string[]): Record<string, number> => {
  const counts: Record<string, number> = {};
  for (const vote of votes) {
    if (counts[vote] === undefined) {
      counts[vote] = 1;
    } else {
      counts[vote] = counts[vote] + 1;
    }
  }
  return counts;
};`,
    senior: `const tally = (votes: string[]): Record<string, number> => {
  const counts = new Map<string, number>();
  for (const vote of votes) counts.set(vote, (counts.get(vote) ?? 0) + 1);
  return Object.fromEntries(counts);
};`,
    hiddenTests: [
      { call: "tally([\"yes\",\"no\",\"yes\",\"yes\"])", expected: { yes: 3, no: 1 } },
      { call: "tally([\"b\",\"a\",\"b\"])", expected: { b: 2, a: 1 } },
      { call: "tally([\"x\",\"y\",\"z\",\"x\",\"y\",\"x\"])", expected: { x: 3, y: 2, z: 1 } },
    ],
  },
  "ts-rotate-a-list": {
    solution: "const rotate = (items: readonly string[]): string[] => (items.length === 0 ? [] : [...items.slice(1), items[0]]);",
    junior: `const rotate = (items: readonly string[]): string[] => {
  if (items.length === 0) {
    return [];
  }
  const moved: string[] = [];
  for (let i = 1; i < items.length; i += 1) {
    moved.push(items[i]);
  }
  moved.push(items[0]);
  return moved;
};`,
    senior: `// Each slot takes the next item, and the modulo wraps the last slot back to the first.
const rotate = (items: readonly string[]): string[] => items.map((_, index) => items[(index + 1) % items.length]);`,
    hiddenTests: [
      { call: "rotate([\"x\",\"y\",\"z\",\"w\"])", expected: ["y", "z", "w", "x"] },
      { call: "(() => { const items = [\"p\",\"q\",\"r\"]; const rotated = rotate(items); return [rotated, items]; })()", expected: [["q", "r", "p"], ["p", "q", "r"]] },
      { call: "rotate([\"solo\"])", expected: ["solo"] },
    ],
  },
  "ts-describe-a-value": {
    solution: `const describeValue = (value: unknown): string => {
  if (value === null || value === undefined) return "nothing";
  if (Array.isArray(value)) return "a list";
  if (typeof value === "string") return "text";
  if (typeof value === "number") return "a number";
  return "something else";
};`,
    junior: `const describeValue = (value: unknown): string => {
  let label = "";
  if (value === null || value === undefined) {
    label = "nothing";
  } else if (Array.isArray(value)) {
    label = "a list";
  } else if (typeof value === "string") {
    label = "text";
  } else if (typeof value === "number") {
    label = "a number";
  } else {
    label = "something else";
  }
  return label;
};`,
    senior: `const describeValue = (value: unknown): string => {
  if (value == null) return "nothing"; // == null covers undefined as well
  if (Array.isArray(value)) return "a list";
  switch (typeof value) {
    case "string":
      return "text";
    case "number":
      return "a number";
    default:
      return "something else";
  }
};`,
    hiddenTests: [
      { call: "describeValue(0)", expected: "a number" },
      { call: "describeValue(\"\")", expected: "text" },
      { call: "describeValue([])", expected: "a list" },
      { call: "describeValue(true)", expected: "something else" },
    ],
  },
  "ts-first-item": {
    solution: "const first = <T>(items: T[]): T | undefined => items[0];",
    junior: `const first = <T>(items: T[]): T | undefined => {
  if (items.length === 0) {
    return undefined;
  }
  return items[0];
};`,
    senior: `// at(0) is typed T | undefined, so an empty list needs no separate branch.
const first = <T>(items: T[]): T | undefined => items.at(0);`,
    hiddenTests: [
      { call: "first([false,true])", expected: false },
      { call: "first([\"only\"])", expected: "only" },
      { call: "first([{id:7},{id:8}])", expected: { id: 7 } },
    ],
  },
  "ts-fall-back-to-a-default": {
    solution: "const orDefault = <T>(value: T | null | undefined, fallback: T): T => value ?? fallback;",
    junior: `const orDefault = <T>(value: T | null | undefined, fallback: T): T => {
  if (value === null) {
    return fallback;
  }
  if (value === undefined) {
    return fallback;
  }
  return value;
};`,
    senior: `const orDefault = <T>(value: T | null | undefined, fallback: T): T => {
  // Loose equality with null matches undefined too and nothing else, so 0 and "" survive.
  if (value == null) return fallback;
  return value;
};`,
    hiddenTests: [
      { call: "orDefault(false, true)", expected: false },
      { call: "orDefault(undefined, 0)", expected: 0 },
      { call: "orDefault(\"set\", \"fallback\")", expected: "set" },
      { call: "orDefault(null, [1])", expected: [1] },
    ],
  },
  "ts-transform-a-list": {
    solution: "const transform = <T, R>(items: T[], change: (item: T) => R): R[] => items.map(item => change(item));",
    junior: `const transform = <T, R>(items: T[], change: (item: T) => R): R[] => {
  const changed: R[] = [];
  for (let i = 0; i < items.length; i += 1) {
    const item = items[i];
    const result = change(item);
    changed.push(result);
  }
  return changed;
};`,
    senior: `// Array.from takes a mapper of its own, so the new list is built in one pass without a wrapper arrow.
const transform = <T, R>(items: T[], change: (item: T) => R): R[] => Array.from(items, change);`,
    hiddenTests: [
      { call: "transform([3,4], n => n * n)", expected: [9, 16] },
      { call: "transform([\"x\",\"yy\",\"zzz\"], s => s.length)", expected: [1, 2, 3] },
      { call: "transform([{a:1},{a:2}], item => item.a)", expected: [1, 2] },
      { call: "transform([true,false], flag => !flag)", expected: [false, true] },
    ],
  },
  "ts-sort-by-name": {
    solution: "const sortByName = <T extends {name: string}>(items: T[]): T[] => [...items].sort((one, other) => one.name.localeCompare(other.name));",
    junior: `const sortByName = <T extends { name: string }>(items: T[]): T[] => {
  const copy: T[] = [];
  for (const item of items) {
    copy.push(item);
  }
  copy.sort((one, other) => {
    if (one.name < other.name) {
      return -1;
    }
    if (one.name > other.name) {
      return 1;
    }
    return 0;
  });
  return copy;
};`,
    senior: `// toSorted() returns a sorted copy, so the caller's list is never reordered under them.
const sortByName = <T extends { name: string }>(items: T[]): T[] => items.toSorted((one, other) => one.name.localeCompare(other.name));`,
    hiddenTests: [
      { call: "sortByName([{name:\"Cy\"},{name:\"Ada\"},{name:\"Bo\"}])", expected: [{ name: "Ada" }, { name: "Bo" }, { name: "Cy" }] },
      { call: "(() => { const people = [{name:\"Zoe\"},{name:\"Amy\"}]; const sorted = sortByName(people); return [sorted.map(person => person.name), people.map(person => person.name)]; })()", expected: [["Amy", "Zoe"], ["Zoe", "Amy"]] },
      { call: "sortByName([{name:\"Bea\",score:3},{name:\"Al\",score:9}])", expected: [{ name: "Al", score: 9 }, { name: "Bea", score: 3 }] },
    ],
  },
  "ts-pluck-a-property": {
    solution: "const pluck = <T, K extends keyof T>(items: T[], key: K): T[K][] => items.map(item => item[key]);",
    junior: `const pluck = <T, K extends keyof T>(items: T[], key: K): T[K][] => {
  const values: T[K][] = [];
  for (const item of items) {
    const value = item[key];
    values.push(value);
  }
  return values;
};`,
    senior: `// A computed key in the parameter pattern pulls out just the property asked for, typed T[K].
const pluck = <T, K extends keyof T>(items: T[], key: K): T[K][] => items.map(({ [key]: value }) => value);`,
    hiddenTests: [
      { call: "pluck([{x:1,y:2},{x:3,y:4}], \"y\")", expected: [2, 4] },
      { call: "pluck([], \"id\")", expected: [] },
      { call: "pluck([{tags:[\"a\"]},{tags:[]}], \"tags\")", expected: [["a"], []] },
      { call: "pluck([{ok:true},{ok:false}], \"ok\")", expected: [true, false] },
    ],
  },
  "ts-apply-a-patch": {
    solution: `interface Settings {
  theme: string;
  fontSize: number;
}

const applyPatch = (settings: Settings, patch: Partial<Settings>): Settings => ({...settings, ...patch});`,
    junior: `interface Settings {
  theme: string;
  fontSize: number;
}

const applyPatch = (settings: Settings, patch: Partial<Settings>): Settings => {
  let theme = settings.theme;
  if (patch.theme !== undefined) {
    theme = patch.theme;
  }
  let fontSize = settings.fontSize;
  if (patch.fontSize !== undefined) {
    fontSize = patch.fontSize;
  }
  return { theme: theme, fontSize: fontSize };
};`,
    senior: `interface Settings {
  theme: string;
  fontSize: number;
}

const applyPatch = (settings: Settings, patch: Partial<Settings>): Settings => {
  // A key the patch sets to undefined must not blank the setting, so those entries are dropped before the merge.
  const defined = Object.fromEntries(Object.entries(patch).filter(([, value]) => value !== undefined));
  return { ...settings, ...defined };
};`,
    hiddenTests: [
      { call: "(() => { const settings = {theme:\"dark\",fontSize:14}; const next = applyPatch(settings, {fontSize:20}); return [settings, next, next === settings]; })()", expected: [{ theme: "dark", fontSize: 14 }, { theme: "dark", fontSize: 20 }, false] },
      { call: "applyPatch({theme:\"light\",fontSize:10}, {theme:\"solarized\"})", expected: { theme: "solarized", fontSize: 10 } },
      { call: "applyPatch({theme:\"x\",fontSize:1}, {theme:\"\",fontSize:0})", expected: { theme: "", fontSize: 0 } },
    ],
  },
  "ts-hide-the-password": {
    solution: `interface Account {
  id: number;
  email: string;
  password: string;
}

const publicUser = (account: Account): Omit<Account, "password"> => {
  const {password, ...rest} = account;
  return rest;
};`,
    junior: `interface Account {
  id: number;
  email: string;
  password: string;
}

const publicUser = (account: Account): Omit<Account, "password"> => {
  const safe = {
    id: account.id,
    email: account.email,
  };
  return safe;
};`,
    senior: `interface Account {
  id: number;
  email: string;
  password: string;
}

// A generic omit keeps the "strip one key" rule in one place, typed so the removed key is gone for callers too.
const omit = <T extends object, K extends keyof T>(source: T, key: K): Omit<T, K> => {
  const copy = { ...source };
  delete copy[key];
  return copy;
};

const publicUser = (account: Account): Omit<Account, "password"> => omit(account, "password");`,
    hiddenTests: [
      { call: "publicUser({id:5,email:\"lin@example.dev\",password:\"pw\"})", expected: { id: 5, email: "lin@example.dev" } },
      { call: "(() => { const account = {id:6,email:\"x@example.dev\",password:\"keep\"}; publicUser(account); return account; })()", expected: { id: 6, email: "x@example.dev", password: "keep" } },
      { call: "\"password\" in publicUser({id:7,email:\"y@example.dev\",password:\"z\"})", expected: false },
    ],
  },
  "ts-area-of-a-shape": {
    solution: `type Shape =
  | {kind: "square"; side: number}
  | {kind: "rectangle"; width: number; height: number}
  | {kind: "triangle"; base: number; height: number};

const area = (shape: Shape): number => {
  if (shape.kind === "square") return shape.side * shape.side;
  if (shape.kind === "rectangle") return shape.width * shape.height;
  return (shape.base * shape.height) / 2;
};`,
    junior: `type Shape =
  | { kind: "square"; side: number }
  | { kind: "rectangle"; width: number; height: number }
  | { kind: "triangle"; base: number; height: number };

const area = (shape: Shape): number => {
  let result = 0;
  if (shape.kind === "square") {
    result = shape.side * shape.side;
  } else if (shape.kind === "rectangle") {
    result = shape.width * shape.height;
  } else {
    result = (shape.base * shape.height) / 2;
  }
  return result;
};`,
    senior: `type Shape =
  | { kind: "square"; side: number }
  | { kind: "rectangle"; width: number; height: number }
  | { kind: "triangle"; base: number; height: number };

const area = (shape: Shape): number => {
  switch (shape.kind) {
    case "square":
      return shape.side ** 2;
    case "rectangle":
      return shape.width * shape.height;
    case "triangle":
      return (shape.base * shape.height) / 2;
    default: {
      // A new kind added to Shape fails to compile here instead of returning NaN at runtime.
      const unreachable: never = shape;
      return unreachable;
    }
  }
};`,
    hiddenTests: [
      { call: "area({kind:\"rectangle\",width:1.5,height:4})", expected: 6 },
      { call: "area({kind:\"square\",side:2.5})", expected: 6.25 },
      { call: "area({kind:\"triangle\",base:10,height:0})", expected: 0 },
      { call: "area({kind:\"triangle\",base:5,height:2})", expected: 5 },
    ],
  },
  "ts-only-the-strings": {
    solution: `const isString = (value: unknown): value is string => typeof value === "string";

const onlyStrings = (values: unknown[]): string[] => values.filter(isString);`,
    junior: `const isString = (value: unknown): value is string => {
  if (typeof value === "string") {
    return true;
  }
  return false;
};

const onlyStrings = (values: unknown[]): string[] => {
  const words: string[] = [];
  for (const value of values) {
    if (isString(value)) {
      words.push(value);
    }
  }
  return words;
};`,
    senior: `const isString = (value: unknown): value is string => typeof value === "string";

// flatMap doubles as a typed filter: the guard narrows value, and an empty array drops it.
const onlyStrings = (values: unknown[]): string[] => values.flatMap((value) => (isString(value) ? [value] : []));`,
    hiddenTests: [
      { call: "onlyStrings([1,\"one\",true,\"two\",{}])", expected: ["one", "two"] },
      { call: "onlyStrings([\"\",0,false])", expected: [""] },
      { call: "onlyStrings([[\"a\"],\"b\"])", expected: ["b"] },
      { call: "[isString(\"x\"), isString(5), isString(null)]", expected: [true, false, false] },
    ],
  },
};
