// Generated by scripts/port-interview-prepper.mjs from the interview-prepper catalogue.
// Server-only reference solutions. Never import from client code.
// English is the source of truth; Czech copy lives in the sibling *.cs.ts overlay.

import type { CodingSolution } from '../types';

export const TYPESCRIPT_SOLUTIONS: Record<string, CodingSolution> = {
  "ts-typed-slug": {
    solution: "const toSlug = (title: string): string => title.trim().toLowerCase().split(/\\s+/).filter(Boolean).join(\"-\");",
  },
  "ts-top-three-scores": {
    solution: "const topThree = (scores: number[]): number[] => [...scores].sort((one, other) => other - one).slice(0, 3);",
  },
  "ts-greeting-with-a-default": {
    solution: "const greet = (name: string, greeting = \"Hello\"): string => `${greeting}, ${name}!`;",
  },
  "ts-person-interface": {
    solution: `interface Person {
  first: string;
  last: string;
}

const fullName = (person: Person): string => [person.first, person.last].filter(Boolean).join(" ");`,
  },
  "ts-optional-nickname": {
    solution: `interface User {
  name: string;
  nickname?: string;
}

const displayName = (user: User): string => user.nickname ?? user.name;`,
  },
  "ts-padded-id": {
    solution: "const idText = (id: string | number): string => (typeof id === \"number\" ? String(id).padStart(4, \"0\") : id);",
  },
  "ts-shipping-speed": {
    solution: `type Speed = "standard" | "express" | "overnight";

const shippingDays = (speed: Speed, weekend: boolean): number => {
  const base = speed === "standard" ? 5 : speed === "express" ? 2 : 1;
  return weekend ? base + 1 : base;
};`,
  },
  "ts-split-a-name": {
    solution: `const splitName = (text: string): [string, string] => {
  const space = text.indexOf(" ");
  return space === -1 ? [text, ""] : [text.slice(0, space), text.slice(space + 1)];
};`,
  },
  "ts-tally-votes": {
    solution: "const tally = (votes: string[]): Record<string, number> => votes.reduce<Record<string, number>>((counts, vote) => ({...counts, [vote]: (counts[vote] ?? 0) + 1}), {});",
  },
  "ts-rotate-a-list": {
    solution: "const rotate = (items: readonly string[]): string[] => (items.length === 0 ? [] : [...items.slice(1), items[0]]);",
  },
  "ts-describe-a-value": {
    solution: `const describeValue = (value: unknown): string => {
  if (value === null || value === undefined) return "nothing";
  if (Array.isArray(value)) return "a list";
  if (typeof value === "string") return "text";
  if (typeof value === "number") return "a number";
  return "something else";
};`,
  },
  "ts-first-item": { solution: "const first = <T>(items: T[]): T | undefined => items[0];" },
  "ts-fall-back-to-a-default": {
    solution: "const orDefault = <T>(value: T | null | undefined, fallback: T): T => value ?? fallback;",
  },
  "ts-transform-a-list": {
    solution: "const transform = <T, R>(items: T[], change: (item: T) => R): R[] => items.map(item => change(item));",
  },
  "ts-sort-by-name": {
    solution: "const sortByName = <T extends {name: string}>(items: T[]): T[] => [...items].sort((one, other) => one.name.localeCompare(other.name));",
  },
  "ts-pluck-a-property": {
    solution: "const pluck = <T, K extends keyof T>(items: T[], key: K): T[K][] => items.map(item => item[key]);",
  },
  "ts-apply-a-patch": {
    solution: `interface Settings {
  theme: string;
  fontSize: number;
}

const applyPatch = (settings: Settings, patch: Partial<Settings>): Settings => ({...settings, ...patch});`,
  },
  "ts-hide-the-password": {
    solution: `interface Account {
  id: number;
  email: string;
  password: string;
}

const publicUser = (account: Account): Omit<Account, "password"> => {
  const {password, ...rest} = account;
  return rest;
};`,
  },
  "ts-area-of-a-shape": {
    solution: `type Shape =
  | {kind: "square"; side: number}
  | {kind: "rectangle"; width: number; height: number}
  | {kind: "triangle"; base: number; height: number};

const area = (shape: Shape): number => {
  if (shape.kind === "square") return shape.side * shape.side;
  if (shape.kind === "rectangle") return shape.width * shape.height;
  return (shape.base * shape.height) / 2;
};`,
  },
  "ts-only-the-strings": {
    solution: `const isString = (value: unknown): value is string => typeof value === "string";

const onlyStrings = (values: unknown[]): string[] => values.filter(isString);`,
  },
};
