export interface Question {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  category: 'react' | 'typescript' | 'git';
  explanation: string;
}

export const questions: Question[] = [
  // REACT - useState
  {
    id: '1',
    question: 'What does useState return?',
    options: ['A single value', 'An array with value and setter', 'An object with value and setter', 'A promise'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useState returns an array with exactly two elements: the current state value and a function to update it. This pattern allows for easy destructuring like [count, setCount].',
  },
  {
    id: '2',
    question: 'What happens when you call the setter function from useState?',
    options: ['Nothing', 'Component re-renders', 'Page refreshes', 'State updates without re-render'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Calling the setter function schedules a re-render of the component with the new state value. React batches multiple state updates for performance.',
  },
  {
    id: '3',
    question: 'How do you update state based on previous state?',
    options: ['setState(state + 1)', 'setState(prev => prev + 1)', 'setState(this.state + 1)', 'state++'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'When the new state depends on the previous state, use the functional update form: setState(prev => prev + 1). This ensures you always work with the latest state value.',
  },
  {
    id: '4',
    question: 'What is the initial value parameter in useState used for?',
    options: ['Default value on every render', 'Initial value only on first render', 'Fallback value', 'Validation'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'The initial value is only used during the first render. On subsequent renders, React ignores this parameter and uses the current state value.',
  },
  {
    id: '5',
    question: 'Can useState hold objects?',
    options: ['No, only primitives', 'Yes, but they are immutable', 'Yes, any value type', 'Only arrays'],
    correctAnswer: 2,
    category: 'react',
    explanation: 'useState can hold any JavaScript value including objects, arrays, strings, numbers, and booleans. However, you should treat state as immutable and create new objects when updating.',
  },

  // REACT - useEffect
  {
    id: '6',
    question: 'When does useEffect run by default?',
    options: ['Only on mount', 'After every render', 'Before every render', 'Only on unmount'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Without a dependency array, useEffect runs after every render (initial render and all updates). This is rarely what you want, so always consider adding dependencies.',
  },
  {
    id: '7',
    question: 'What does an empty dependency array in useEffect do?',
    options: ['Runs on every render', 'Runs only on mount', 'Runs only on unmount', 'Disables the effect'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'An empty dependency array [] tells React the effect has no dependencies, so it only runs once after the initial render (mount). This is useful for one-time setup like fetching data.',
  },
  {
    id: '8',
    question: 'What does the return function in useEffect do?',
    options: ['Returns a value', 'Cleanup function', 'Error handler', 'Nothing'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'The return function is a cleanup function that runs before the component unmounts and before every re-run of the effect. Use it to clean up subscriptions, timers, or event listeners.',
  },
  {
    id: '9',
    question: 'When is the cleanup function in useEffect called?',
    options: ['Before the effect runs and on unmount', 'Only on mount', 'Only when dependencies change', 'Never automatically'],
    correctAnswer: 0,
    category: 'react',
    explanation: 'The cleanup function runs before each re-execution of the effect (when dependencies change) and when the component unmounts. This prevents memory leaks and stale closures.',
  },
  {
    id: '10',
    question: 'What happens if you omit the dependency array in useEffect?',
    options: ['Effect never runs', 'Effect runs once', 'Effect runs after every render', 'Compilation error'],
    correctAnswer: 2,
    category: 'react',
    explanation: 'Omitting the dependency array causes the effect to run after every single render, which can lead to performance issues or infinite loops if the effect updates state.',
  },

  // REACT - useCallback
  {
    id: '11',
    question: 'What is the purpose of useCallback?',
    options: ['To call functions', 'To memoize callback functions', 'To create callbacks', 'To handle async operations'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useCallback returns a memoized version of a callback that only changes when its dependencies change. This helps prevent unnecessary re-renders when passing callbacks to optimized child components.',
  },
  {
    id: '12',
    question: 'When should you use useCallback?',
    options: ['For all functions', 'When passing callbacks to optimized child components', 'Never', 'Only for async functions'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Use useCallback when passing callbacks to child components wrapped in React.memo, or when a callback is a dependency of other hooks. Overusing it can actually hurt performance.',
  },
  {
    id: '13',
    question: 'What does useCallback return?',
    options: ['The result of the callback', 'A memoized version of the callback', 'A new function every time', 'A promise'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useCallback returns the same function reference between renders as long as its dependencies haven\'t changed. This referential equality is what enables optimization.',
  },
  {
    id: '14',
    question: 'What is the second argument to useCallback?',
    options: ['The callback function', 'The return value', 'Dependency array', 'Options object'],
    correctAnswer: 2,
    category: 'react',
    explanation: 'The second argument is a dependency array. The callback is only recreated when values in this array change. Omitting dependencies can lead to stale closures.',
  },
  {
    id: '15',
    question: 'useCallback(fn, deps) is equivalent to which useMemo call?',
    options: ['useMemo(fn, deps)', 'useMemo(() => fn, deps)', 'useMemo(fn(), deps)', 'useMemo(() => fn(), deps)'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useCallback(fn, deps) is syntactic sugar for useMemo(() => fn, deps). Both memoize the function reference, but useCallback is more readable for this specific use case.',
  },

  // REACT - useMemo
  {
    id: '16',
    question: 'What is the purpose of useMemo?',
    options: ['To memorize values', 'To memoize expensive calculations', 'To create memos', 'To store data permanently'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useMemo caches the result of an expensive calculation between re-renders. It only recomputes when dependencies change, avoiding unnecessary recalculations.',
  },
  {
    id: '17',
    question: 'When does useMemo recompute its value?',
    options: ['Every render', 'Never', 'When dependencies change', 'Only on mount'],
    correctAnswer: 2,
    category: 'react',
    explanation: 'useMemo recomputes the memoized value only when one of its dependencies changes. If dependencies stay the same, it returns the cached value from the previous render.',
  },
  {
    id: '18',
    question: 'What does useMemo return?',
    options: ['A function', 'The memoized value', 'A ref object', 'A setter function'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useMemo returns the memoized result of calling the provided function. Unlike useCallback which returns a function, useMemo returns whatever your function returns.',
  },
  {
    id: '19',
    question: 'Should you use useMemo for all computed values?',
    options: ['Yes, always', 'No, only for expensive computations', 'Only for objects', 'Only for arrays'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Only use useMemo for genuinely expensive computations. For simple calculations, the overhead of useMemo itself can outweigh the benefits. Profile before optimizing.',
  },
  {
    id: '20',
    question: 'What happens if useMemo dependencies are empty []?',
    options: ['Value computed every render', 'Value computed once on mount', 'Value is undefined', 'Error is thrown'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'An empty dependency array means the value is computed only once during the initial render and never recomputed, similar to how useEffect with [] runs only on mount.',
  },

  // REACT - useRef
  {
    id: '21',
    question: 'What does useRef return?',
    options: ['A mutable ref object', 'A DOM element', 'A state value', 'A callback function'],
    correctAnswer: 0,
    category: 'react',
    explanation: 'useRef returns a mutable ref object with a .current property. This object persists for the full lifetime of the component and can hold any value.',
  },
  {
    id: '22',
    question: 'Does changing useRef.current trigger a re-render?',
    options: ['Yes', 'No', 'Only if connected to state', 'Only on mount'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Mutating ref.current does NOT trigger a re-render. This makes refs perfect for storing values you need to persist but don\'t want to cause updates when changed.',
  },
  {
    id: '23',
    question: 'What property holds the value in a ref object?',
    options: ['value', 'current', 'ref', 'data'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'The ref object has a single property called "current" that holds the actual value. Access it as myRef.current to read or write the stored value.',
  },
  {
    id: '24',
    question: 'What is a common use case for useRef?',
    options: ['Managing form state', 'Accessing DOM elements', 'Fetching data', 'Routing'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'A primary use case for useRef is accessing DOM elements directly, like focusing an input or measuring element dimensions. Pass the ref to an element\'s ref attribute.',
  },
  {
    id: '25',
    question: 'How do you attach a ref to a DOM element?',
    options: ['ref={myRef.current}', 'ref={myRef}', 'useRef={myRef}', 'current={myRef}'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Pass the ref object directly to the ref attribute: ref={myRef}. React will set myRef.current to the DOM element when it mounts and to null when it unmounts.',
  },

  // REACT - React Router
  {
    id: '26',
    question: 'Which hook returns the current URL location in React Router?',
    options: ['useHistory', 'useLocation', 'useRoute', 'useURL'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useLocation returns the current location object containing pathname, search, hash, and state. It updates whenever the URL changes.',
  },
  {
    id: '27',
    question: 'What hook is used for programmatic navigation in React Router v6?',
    options: ['useHistory', 'useNavigate', 'useRouter', 'useRedirect'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'In React Router v6, useNavigate replaced useHistory. Call navigate("/path") to navigate programmatically, or navigate(-1) to go back.',
  },
  {
    id: '28',
    question: 'How do you access URL parameters in React Router?',
    options: ['useQuery', 'useParams', 'useURLParams', 'useSearch'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useParams returns an object of key/value pairs of URL parameters from the current route. For route "/users/:id", useParams() returns { id: "123" }.',
  },
  {
    id: '29',
    question: 'What component is used to define routes in React Router v6?',
    options: ['Switch', 'Routes', 'Router', 'Route'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'In v6, Routes (plural) replaced Switch. It wraps Route components and renders the first matching route. Route components go inside Routes.',
  },
  {
    id: '30',
    question: 'How do you create a link in React Router?',
    options: ['<a href="/">', '<Link to="/">', '<Route to="/">', '<Navigate to="/">'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Use the Link component for navigation without page reloads. Unlike <a> tags, Link handles client-side routing and preserves React state.',
  },
  {
    id: '31',
    question: 'What does the Outlet component do in React Router?',
    options: ['Creates a new route', 'Renders child routes', 'Redirects users', 'Handles 404 errors'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Outlet is a placeholder that renders the matching child route. It enables nested routing where parent layouts wrap child content.',
  },
  {
    id: '32',
    question: 'How do you handle 404 pages in React Router v6?',
    options: ['<Route notFound>', '<Route path="*">', '<Route 404>', '<NotFound>'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Use path="*" to match any URL that hasn\'t matched other routes. Place this route last in your Routes component to catch all unmatched paths.',
  },
  {
    id: '33',
    question: 'What hook gives you access to search/query parameters?',
    options: ['useParams', 'useSearchParams', 'useQuery', 'useLocation'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useSearchParams returns the current URL search params and a function to update them. It works like useState but syncs with the URL query string.',
  },

  // REACT - React Hook Form
  {
    id: '34',
    question: 'What hook is the main entry point for React Hook Form?',
    options: ['useForm', 'useFormState', 'useController', 'useWatch'],
    correctAnswer: 0,
    category: 'react',
    explanation: 'useForm is the primary hook that returns methods like register, handleSubmit, and formState. It manages the entire form state and validation.',
  },
  {
    id: '35',
    question: 'How do you register an input with React Hook Form?',
    options: ['register prop', 'name prop only', 'ref prop', '{...register("fieldName")}'],
    correctAnswer: 3,
    category: 'react',
    explanation: 'Spread the register function onto your input: {...register("fieldName")}. This adds the necessary ref and onChange handlers to track the input.',
  },
  {
    id: '36',
    question: 'What function handles form submission in React Hook Form?',
    options: ['onSubmit', 'handleSubmit', 'submit', 'processForm'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'handleSubmit wraps your submit handler, validates the form first, and only calls your function if validation passes. Use it like onSubmit={handleSubmit(onSubmit)}.',
  },
  {
    id: '37',
    question: 'How do you access form errors in React Hook Form?',
    options: ['errors object from useForm', 'formState.errors', 'getErrors()', 'useErrors()'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Access errors through formState.errors from the useForm hook. Each field\'s error is available as formState.errors.fieldName with message and type properties.',
  },
  {
    id: '38',
    question: 'What does the watch function do in React Hook Form?',
    options: ['Validates inputs', 'Watches for form submission', 'Subscribes to input changes', 'Resets the form'],
    correctAnswer: 2,
    category: 'react',
    explanation: 'watch subscribes to input changes and returns their values. Use it for conditional rendering based on form values or to react to specific field changes.',
  },
  {
    id: '39',
    question: 'How do you set default values in React Hook Form?',
    options: ['defaultValue prop', 'defaultValues in useForm', 'initial prop', 'value prop'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Pass defaultValues to useForm: useForm({ defaultValues: { name: "John" } }). This sets initial values and is used when reset() is called.',
  },
  {
    id: '40',
    question: 'What does reset() do in React Hook Form?',
    options: ['Clears errors only', 'Resets form to default values', 'Submits the form', 'Validates all fields'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'reset() restores the form to its default values and clears all errors. You can also pass new default values to reset to specific values.',
  },

  // REACT - General
  {
    id: '41',
    question: 'What is the purpose of React.memo?',
    options: ['To memoize values', 'To prevent unnecessary re-renders of components', 'To create memos', 'To store data'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'React.memo is a higher-order component that memoizes the rendered output. It skips re-rendering if props haven\'t changed, improving performance.',
  },
  {
    id: '42',
    question: 'What is a controlled component in React?',
    options: ['A component with refs', 'A component whose value is controlled by React state', 'A class component', 'A pure component'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'A controlled component has its form value controlled by React state. The input\'s value comes from state, and onChange updates that state.',
  },
  {
    id: '43',
    question: 'What is the virtual DOM?',
    options: ['A copy of the real DOM in memory', 'A browser feature', 'A JavaScript engine', 'A CSS framework'],
    correctAnswer: 0,
    category: 'react',
    explanation: 'The virtual DOM is a lightweight JavaScript representation of the real DOM. React uses it to compute the minimal set of changes needed, then batches updates to the real DOM.',
  },
  {
    id: '44',
    question: 'What is the purpose of keys in React lists?',
    options: ['Styling', 'Help React identify which items changed', 'Security', 'Performance only'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Keys help React identify which items have changed, been added, or removed. Use stable, unique identifiers as keys—avoid using array indexes when items can reorder.',
  },
  {
    id: '45',
    question: 'What hook would you use to access context?',
    options: ['useState', 'useContext', 'useReducer', 'useRef'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'useContext reads and subscribes to context. Pass the context object (from createContext) to useContext to get the current context value.',
  },
  {
    id: '46',
    question: 'What is prop drilling?',
    options: ['A performance technique', 'Passing props through multiple levels', 'A testing method', 'A build process'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Prop drilling is passing props through intermediate components that don\'t need them, just to reach deeply nested components. Context or state management libraries can help avoid this.',
  },
  {
    id: '47',
    question: 'What is the StrictMode component used for?',
    options: ['Production optimization', 'Highlighting potential problems', 'Security', 'Styling'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'StrictMode activates additional checks and warnings in development. It intentionally double-renders components to help detect side effects and deprecated APIs.',
  },
  {
    id: '48',
    question: 'What is a React Fragment used for?',
    options: ['Breaking components', 'Grouping elements without adding extra DOM nodes', 'Creating partial renders', 'Code splitting'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Fragments let you group multiple elements without adding an extra wrapper div to the DOM. Use <></> or <Fragment> when you need to return multiple elements.',
  },
  {
    id: '49',
    question: 'What is the difference between state and props?',
    options: ['No difference', 'State is mutable, props are read-only', 'Props are mutable, state is read-only', 'Both are immutable'],
    correctAnswer: 1,
    category: 'react',
    explanation: 'Props are passed from parent to child and are read-only. State is managed within a component and can be updated. Both trigger re-renders when they change.',
  },
  {
    id: '50',
    question: 'What does lifting state up mean?',
    options: ['Moving state to a higher component', 'Increasing state value', 'Optimizing state', 'Removing state'],
    correctAnswer: 0,
    category: 'react',
    explanation: 'Lifting state up means moving shared state to the closest common ancestor of the components that need it. This enables sibling components to share and sync data.',
  },

  // TYPESCRIPT
  {
    id: '51',
    question: 'How do you define an optional property in TypeScript?',
    options: ['property?: type', 'property: type?', 'optional property: type', 'property: type | undefined'],
    correctAnswer: 0,
    category: 'typescript',
    explanation: 'Use the question mark after the property name: property?: type. This makes the property optional, meaning it can be omitted when creating objects of that type.',
  },
  {
    id: '52',
    question: 'What is the correct way to define a typed array?',
    options: ['Array<string>', 'string[]', 'Both A and B', 'string{}'],
    correctAnswer: 2,
    category: 'typescript',
    explanation: 'Both Array<string> and string[] are valid and equivalent ways to define an array of strings. The choice is mostly stylistic preference.',
  },
  {
    id: '53',
    question: 'What does the "as" keyword do?',
    options: ['Creates an alias', 'Type assertion', 'Type declaration', 'Creates a new type'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'The "as" keyword performs type assertion, telling TypeScript to treat a value as a specific type. Use it when you know more about a type than TypeScript can infer.',
  },
  {
    id: '54',
    question: 'What is an interface in TypeScript?',
    options: ['A class', 'A contract that defines object shape', 'A function', 'A module'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'An interface defines the shape of an object—what properties and methods it should have. It\'s a compile-time contract that doesn\'t exist in the JavaScript output.',
  },
  {
    id: '55',
    question: 'How do you define a union type?',
    options: ['type A && B', 'type A | B', 'type A + B', 'type A & B'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'The pipe operator | creates a union type: string | number means the value can be either a string or a number. The ampersand & creates an intersection type.',
  },
  {
    id: '56',
    question: 'What is the "never" type used for?',
    options: ['Variables never used', 'Functions that never return', 'Optional parameters', 'Nullable types'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'The never type represents values that never occur. It\'s used for functions that always throw errors or have infinite loops—they never return normally.',
  },
  {
    id: '57',
    question: 'What is the difference between interface and type?',
    options: ['No difference', 'Interfaces can be extended, types cannot', 'Types are more flexible, interfaces can be merged', 'Types are older'],
    correctAnswer: 2,
    category: 'typescript',
    explanation: 'Types are more flexible (unions, intersections, mapped types), while interfaces support declaration merging (multiple declarations combine). Both can be extended.',
  },
  {
    id: '58',
    question: 'What does the readonly modifier do?',
    options: ['Makes property optional', 'Prevents property modification', 'Makes property private', 'Makes property static'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'The readonly modifier prevents a property from being reassigned after initialization. It\'s a compile-time check that helps prevent accidental mutations.',
  },
  {
    id: '59',
    question: 'What is a generic in TypeScript?',
    options: ['A general type', 'A type parameter that allows reusable components', 'A basic type', 'An any type'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Generics are type parameters (like <T>) that let you create reusable components that work with multiple types while maintaining type safety.',
  },
  {
    id: '60',
    question: 'How do you type a function that returns nothing?',
    options: ['null', 'undefined', 'void', 'never'],
    correctAnswer: 2,
    category: 'typescript',
    explanation: 'Use void for functions that don\'t return a value or return undefined implicitly. Use never for functions that never return (throw or infinite loop).',
  },
  {
    id: '61',
    question: 'What is the unknown type?',
    options: ['Same as any', 'A type-safe any', 'An error type', 'A null type'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'unknown is like any but type-safe. You must narrow the type before using an unknown value, making it safer for values of uncertain type.',
  },
  {
    id: '62',
    question: 'What is an intersection type?',
    options: ['A | B', 'A & B', 'A + B', 'A - B'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'The ampersand & creates an intersection type that combines multiple types. A & B means the value must satisfy both type A AND type B.',
  },
  {
    id: '63',
    question: 'What does Partial<T> do?',
    options: ['Makes all properties required', 'Makes all properties optional', 'Removes all properties', 'Adds new properties'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Partial<T> constructs a type with all properties of T set to optional. It\'s useful for update functions where you only want to change some properties.',
  },
  {
    id: '64',
    question: 'What does Required<T> do?',
    options: ['Makes all properties optional', 'Makes all properties required', 'Removes all properties', 'Validates properties'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Required<T> constructs a type with all properties of T set to required, removing optional modifiers. It\'s the opposite of Partial<T>.',
  },
  {
    id: '65',
    question: 'What does Pick<T, K> do?',
    options: ['Removes properties K from T', 'Creates a type with only properties K from T', 'Adds properties K to T', 'Validates K in T'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Pick<T, K> constructs a type by picking only the specified properties K from T. Pick<User, "name" | "email"> creates a type with just name and email.',
  },
  {
    id: '66',
    question: 'What does Omit<T, K> do?',
    options: ['Creates a type with only K', 'Creates a type without properties K', 'Adds K to T', 'Validates T'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Omit<T, K> constructs a type by removing the specified properties K from T. It\'s the opposite of Pick. Omit<User, "password"> removes the password property.',
  },
  {
    id: '67',
    question: 'How do you type an object with dynamic keys?',
    options: ['{ key: value }', '{ [key: string]: value }', '{ any: value }', '{ dynamic: value }'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Index signatures like { [key: string]: value } define the type for dynamic keys. This allows any string key with values of the specified type.',
  },
  {
    id: '68',
    question: 'What is a type guard?',
    options: ['A security feature', 'A way to narrow types', 'A type validator', 'A compiler option'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Type guards are expressions that narrow types at runtime. Using typeof, instanceof, or custom type predicates helps TypeScript understand the specific type in a block.',
  },
  {
    id: '69',
    question: 'What does the "keyof" operator return?',
    options: ['All values of an object', 'All keys of a type as a union', 'The first key', 'A boolean'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'keyof produces a union type of all property names (keys) of a type. keyof { name: string; age: number } produces "name" | "age".',
  },
  {
    id: '70',
    question: 'What is a tuple in TypeScript?',
    options: ['A dynamic array', 'A fixed-length array with specific types', 'An object', 'A map'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'A tuple is a fixed-length array where each element has a specific type. [string, number] defines a two-element tuple with a string first and number second.',
  },
  {
    id: '71',
    question: 'How do you make a property non-nullable?',
    options: ['property!', 'NonNullable<property>', 'property!!', 'Required<property>'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'NonNullable<T> removes null and undefined from T. The ! operator (non-null assertion) tells TypeScript a value is not null, but doesn\'t create a new type.',
  },
  {
    id: '72',
    question: 'What is the typeof operator used for in TypeScript?',
    options: ['Runtime type checking only', 'Getting the type of a variable', 'Creating new types', 'Both B and C'],
    correctAnswer: 3,
    category: 'typescript',
    explanation: 'In TypeScript, typeof works both at runtime (JavaScript behavior) and at the type level to extract a type from a variable. type T = typeof myVariable creates a type.',
  },
  {
    id: '73',
    question: 'What does Record<K, V> create?',
    options: ['An array', 'An object type with keys K and values V', 'A tuple', 'A map'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'Record<K, V> constructs an object type with keys of type K and values of type V. Record<string, number> means any string key with number values.',
  },
  {
    id: '74',
    question: 'What is the ReturnType<T> utility type?',
    options: ['Returns function parameters', 'Returns the return type of a function', 'Returns void', 'Returns never'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'ReturnType<T> extracts the return type of a function type T. ReturnType<() => string> produces string. Useful for inferring types from existing functions.',
  },
  {
    id: '75',
    question: 'What is a discriminated union?',
    options: ['A union with no common properties', 'A union with a common literal property', 'An intersection type', 'A generic type'],
    correctAnswer: 1,
    category: 'typescript',
    explanation: 'A discriminated union has a common property with literal types that TypeScript can use to narrow the type. A "type" or "kind" field often serves as the discriminant.',
  },

  // GIT
  {
    id: '76',
    question: 'What does git init do?',
    options: ['Clones a repository', 'Creates a new Git repository', 'Initializes a branch', 'Starts git daemon'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git init creates a new Git repository in the current directory by creating a .git subdirectory with all necessary repository files.',
  },
  {
    id: '77',
    question: 'What does git clone do?',
    options: ['Creates a new branch', 'Copies a repository', 'Merges branches', 'Deletes a repository'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git clone creates a local copy of a remote repository, including all files, branches, and commit history. It also sets up the remote tracking.',
  },
  {
    id: '78',
    question: 'What does git add do?',
    options: ['Commits changes', 'Stages changes for commit', 'Pushes changes', 'Creates a branch'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git add stages changes for the next commit. It moves changes from the working directory to the staging area (index), preparing them to be committed.',
  },
  {
    id: '79',
    question: 'What does git commit -m do?',
    options: ['Merges branches', 'Creates a commit with a message', 'Pushes to remote', 'Creates a branch'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git commit -m creates a new commit with staged changes and the provided message. The -m flag lets you write the commit message inline.',
  },
  {
    id: '80',
    question: 'What does git push do?',
    options: ['Downloads changes', 'Uploads local commits to remote', 'Creates a branch', 'Merges branches'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git push uploads local commits to the remote repository. It updates the remote branch to match your local branch.',
  },
  {
    id: '81',
    question: 'What does git pull do?',
    options: ['Uploads changes', 'Fetches and merges remote changes', 'Creates a branch', 'Deletes a branch'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git pull is a combination of git fetch and git merge. It downloads changes from the remote and automatically merges them into your current branch.',
  },
  {
    id: '82',
    question: 'What is the difference between git fetch and git pull?',
    options: ['No difference', 'Fetch downloads without merging, pull downloads and merges', 'Pull downloads without merging', 'Fetch uploads changes'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git fetch downloads commits from the remote but doesn\'t merge them. git pull does both—it fetches and then merges. Fetch is safer for reviewing changes first.',
  },
  {
    id: '83',
    question: 'What does git merge do?',
    options: ['Splits a branch', 'Combines branches', 'Deletes a branch', 'Creates a branch'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git merge combines the histories of two branches. It creates a merge commit (unless fast-forward) that has two parent commits.',
  },
  {
    id: '84',
    question: 'What does git rebase do?',
    options: ['Deletes commits', 'Moves commits to a new base', 'Merges branches', 'Creates a branch'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git rebase moves or replays your commits onto a different base commit. It rewrites history to create a linear sequence of commits.',
  },
  {
    id: '85',
    question: 'What is the main difference between merge and rebase?',
    options: ['No difference', 'Merge creates a merge commit, rebase rewrites history', 'Rebase creates a merge commit', 'Merge rewrites history'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'Merge preserves history by creating a merge commit. Rebase rewrites history by moving commits, creating a cleaner but altered history. Never rebase public branches.',
  },
  {
    id: '86',
    question: 'What does git branch do without arguments?',
    options: ['Creates a branch', 'Lists branches', 'Deletes a branch', 'Switches branch'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'Running git branch without arguments lists all local branches. The current branch is marked with an asterisk (*). Use -a to see remote branches too.',
  },
  {
    id: '87',
    question: 'How do you create and switch to a new branch?',
    options: ['git branch new', 'git checkout -b new', 'git switch new', 'Both B and C'],
    correctAnswer: 3,
    category: 'git',
    explanation: 'Both "git checkout -b branch" and "git switch -c branch" create and switch to a new branch. switch is newer and more intuitive for branch operations.',
  },
  {
    id: '88',
    question: 'What does git stash do?',
    options: ['Deletes changes', 'Temporarily saves changes', 'Commits changes', 'Pushes changes'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git stash temporarily saves uncommitted changes and reverts to a clean working directory. Useful when you need to switch branches but aren\'t ready to commit.',
  },
  {
    id: '89',
    question: 'How do you apply stashed changes?',
    options: ['git stash apply', 'git stash pop', 'Both A and B', 'git stash get'],
    correctAnswer: 2,
    category: 'git',
    explanation: 'Both apply and pop restore stashed changes. The difference: pop removes the stash after applying, while apply keeps it in the stash list for potential reuse.',
  },
  {
    id: '90',
    question: 'What does git reset --hard do?',
    options: ['Soft reset', 'Discards all changes and resets to specified commit', 'Creates a commit', 'Merges branches'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git reset --hard discards ALL changes (staged and unstaged) and resets your working directory to match the specified commit. Use with caution—changes are lost.',
  },
  {
    id: '91',
    question: 'What does git reset --soft do?',
    options: ['Discards all changes', 'Moves HEAD but keeps changes staged', 'Creates a branch', 'Deletes commits'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git reset --soft moves HEAD to the specified commit but keeps all changes staged. Useful for combining multiple commits into one.',
  },
  {
    id: '92',
    question: 'What does git revert do?',
    options: ['Deletes a commit', 'Creates a new commit that undoes changes', 'Resets to previous state', 'Merges branches'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git revert creates a new commit that undoes the changes from a specific commit. Unlike reset, it doesn\'t rewrite history, making it safe for shared branches.',
  },
  {
    id: '93',
    question: 'What is HEAD in Git?',
    options: ['The first commit', 'A pointer to the current commit', 'The remote repository', 'A branch name'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'HEAD is a pointer to the current commit you\'re working on, usually pointing to the tip of the current branch. It moves when you commit or checkout.',
  },
  {
    id: '94',
    question: 'What does git log show?',
    options: ['Staged files', 'Commit history', 'Remote branches', 'Stashed changes'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git log displays the commit history, showing commit hashes, authors, dates, and messages. Use flags like --oneline or --graph for different formats.',
  },
  {
    id: '95',
    question: 'What does git status show?',
    options: ['Commit history', 'Working tree status', 'Remote URL', 'Branch list'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git status shows the state of your working directory and staging area. It lists staged, unstaged, and untracked files.',
  },
  {
    id: '96',
    question: 'What does git diff show?',
    options: ['Commit history', 'Changes between commits or working tree', 'Branch differences', 'Remote status'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git diff shows the differences between various Git states—working directory vs staging, staging vs last commit, or between any two commits.',
  },
  {
    id: '97',
    question: 'How do you delete a local branch?',
    options: ['git branch -d branchname', 'git delete branchname', 'git remove branchname', 'git branch --delete-remote'],
    correctAnswer: 0,
    category: 'git',
    explanation: 'Use "git branch -d branchname" to delete a local branch. Use -D (uppercase) to force delete an unmerged branch.',
  },
  {
    id: '98',
    question: 'How do you delete a remote branch?',
    options: ['git branch -d origin/branch', 'git push origin --delete branch', 'git delete remote branch', 'git remote delete branch'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'Use "git push origin --delete branchname" to delete a remote branch. This removes the branch from the remote repository.',
  },
  {
    id: '99',
    question: 'What is a Git conflict?',
    options: ['A bug in Git', 'When changes in different branches affect the same lines', 'A network error', 'A permission issue'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'A merge conflict occurs when Git can\'t automatically merge changes because different branches modified the same lines. You must manually resolve these conflicts.',
  },
  {
    id: '100',
    question: 'What does git cherry-pick do?',
    options: ['Deletes a commit', 'Applies a specific commit to current branch', 'Creates a branch', 'Merges all commits'],
    correctAnswer: 1,
    category: 'git',
    explanation: 'git cherry-pick applies the changes from a specific commit to your current branch. It\'s useful for selectively bringing changes without merging entire branches.',
  },
];

// Fisher-Yates shuffle algorithm
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// Simple signing for session data (in production, use proper JWT)
const SECRET = process.env.SESSION_SECRET || 'quiz-secret-key-change-in-production';

export function encodeSession(data: { questionId: string; correctAnswer: number }[]): string {
  const payload = JSON.stringify(data);
  const encoded = Buffer.from(payload).toString('base64');
  const signature = Buffer.from(SECRET + encoded).toString('base64').slice(0, 16);
  return `${encoded}.${signature}`;
}

export function decodeSession(token: string): { questionId: string; correctAnswer: number }[] | null {
  try {
    const [encoded, signature] = token.split('.');
    const expectedSig = Buffer.from(SECRET + encoded).toString('base64').slice(0, 16);
    if (signature !== expectedSig) return null;
    const payload = Buffer.from(encoded, 'base64').toString('utf-8');
    return JSON.parse(payload);
  } catch {
    return null;
  }
}
