// Offline data layer. Reads the bundled dataset (generated by
// scripts/generate-mobile-offline.ts) and reproduces, on-device, what the API
// returns: the roadmap structure, a roadmap level/checkpoint's questions, and an
// offline quiz (local selection + grading). This is what makes the app fully
// usable with no network from first launch.

import offlineData from './offline-data';
import {
  LEVEL_PASS,
  CHECKPOINT_PASS,
  LEVELS_PER_CHECKPOINT,
} from '../lib/roadmapProgress';
import type {
  RoadmapStructure,
  RoadmapPlayable,
  RoadmapQuestion,
  RoadmapTopic,
} from '../lib/roadmapApi';
import type { CategoryType, DifficultyMode, Question, QuizResult } from '../types';

interface OfflineQuestion {
  id: string;
  tags: string[];
  introduction: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  category: CategoryType;
  difficulty: 1 | 2 | 3 | 4 | 5;
  // Optional: present in newer bundles so selection can weight by importance.
  importance?: number;
}
interface OfflineData {
  generatedAt: string;
  questionsPerLevel: number;
  structure: RoadmapStructure;
  questions: OfflineQuestion[];
}

const DATA = offlineData as OfflineData;

// Mirrors lib/roadmap.ts ID_PREFIX so we can resolve a level's question ids the
// same way the server does (questions are stored rm-<prefix>-<n>, 8 per level).
const ID_PREFIX: Record<RoadmapTopic, string> = {
  javascript: 'rm-js',
  typescript: 'rm-ts',
  react: 'rm-react',
  nextjs: 'rm-next',
  nodejs: 'rm-node',
  html: 'rm-html',
  css: 'rm-css',
  git: 'rm-git',
  dsa: 'rm-dsa',
  algorithms: 'rm-algorithms',
  abbreviations: 'rm-abbr',
  general: 'rm-general',
  ai: 'rm-ai',
  'rhf-zod': 'rm-rhf',
  'cool-stuff': 'rm-cool',
};
const PER_LEVEL = DATA.questionsPerLevel || 8;

const byId = new Map(DATA.questions.map((q) => [q.id, q]));

const levelIds = (topic: RoadmapTopic, level: number): string[] => {
  const start = (level - 1) * PER_LEVEL + 1;
  return Array.from({ length: PER_LEVEL }, (_, i) => `${ID_PREFIX[topic]}-${start + i}`);
};
const checkpointIds = (topic: RoadmapTopic, checkpoint: number): string[] => {
  const first = (checkpoint - 1) * LEVELS_PER_CHECKPOINT + 1;
  const ids: string[] = [];
  for (let lvl = first; lvl < first + LEVELS_PER_CHECKPOINT; lvl++) ids.push(...levelIds(topic, lvl));
  return ids;
};

const toRoadmapQuestion = (q: OfflineQuestion): RoadmapQuestion => ({
  id: q.id,
  tags: q.tags,
  introduction: q.introduction,
  question: q.question,
  options: q.options,
  correctAnswer: q.correctAnswer,
  explanation: q.explanation,
  category: q.category,
  difficulty: q.difficulty,
});

/* ──── roadmap ──────────────────────────────────────────────────────────── */

export function offlineRoadmapStructure(): RoadmapStructure {
  return DATA.structure;
}

export function offlineRoadmapLevel(topic: RoadmapTopic, level: number): RoadmapPlayable {
  const meta = DATA.structure.structure[topic]?.levels.find((l) => l.level === level);
  const questions = levelIds(topic, level)
    .map((id) => byId.get(id))
    .filter((q): q is OfflineQuestion => Boolean(q))
    .map(toRoadmapQuestion);
  return {
    kind: 'level',
    topic,
    ref: level,
    title: meta?.title ?? `Level ${level}`,
    difficulty: meta?.difficulty,
    passPct: LEVEL_PASS,
    questions,
  };
}

export function offlineRoadmapCheckpoint(topic: RoadmapTopic, checkpoint: number): RoadmapPlayable {
  const meta = DATA.structure.structure[topic]?.checkpoints.find((c) => c.checkpoint === checkpoint);
  const questions = checkpointIds(topic, checkpoint)
    .map((id) => byId.get(id))
    .filter((q): q is OfflineQuestion => Boolean(q))
    .map(toRoadmapQuestion);
  return {
    kind: 'checkpoint',
    topic,
    ref: checkpoint,
    title: meta?.title ?? `Checkpoint ${checkpoint}`,
    passPct: meta?.passPct ?? CHECKPOINT_PASS,
    questions,
  };
}

/* ──── offline quiz (local selection + grading) ─────────────────────────── */

const OFFLINE_PREFIX = 'offline:';
// Holds the answer key for each in-flight offline quiz, keyed by its synthetic
// session id, so grading stays server-shaped (questions are handed out without
// answers; the key lives here until submit).
const sessions = new Map<string, OfflineQuestion[]>();
let seq = 0;

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Importance-weighted sample without replacement (Efraimidis–Spirakis), mirroring
// the server's quiz selection so low-importance "fillers" surface less often.
// Returns the chosen items in random order. Falls back to a plain shuffle when
// the bundle predates importance scores.
function weightedSample(items: OfflineQuestion[], count: number): OfflineQuestion[] {
  if (count >= items.length) return shuffle(items);
  const keyed = items.map((item) => {
    const w = Math.max(0.0001, item.importance ?? 5);
    const u = Math.random() || 1e-9; // (0,1]
    return { item, key: Math.log(u) / w }; // larger key (closer to 0) = higher priority
  });
  keyed.sort((a, b) => b.key - a.key);
  return shuffle(keyed.slice(0, count).map((k) => k.item));
}

// Mirrors the server's /api/quiz/questions difficulty selection (importance-weighted).
function selectByDifficulty(pool: OfflineQuestion[], mode: DifficultyMode, count: number): OfflineQuestion[] {
  if (mode === 'easy') return weightedSample(pool.filter((q) => q.difficulty <= 2), count);
  if (mode === 'advanced') return weightedSample(pool.filter((q) => q.difficulty >= 3), count);
  if (mode === 'basics') {
    const basics = pool.filter((q) => q.tags.includes('Terminology'));
    if (basics.length > 0) return weightedSample(basics, count);
    const sorted = [...pool].sort((a, b) => a.difficulty - b.difficulty);
    const easiest = sorted[0]?.difficulty ?? 1;
    return weightedSample(sorted.filter((q) => q.difficulty === easiest), count);
  }
  if (mode === 'mixed') return weightedSample(pool, count);
  // zero-to-hero: progressive — fill across difficulty buckets, then top up.
  const perBucket = Math.ceil(count / 5);
  const buckets: OfflineQuestion[] = [];
  for (let d = 1; d <= 5; d++) buckets.push(...weightedSample(pool.filter((q) => q.difficulty === d), perBucket));
  if (buckets.length < count) {
    const ids = new Set(buckets.map((q) => q.id));
    buckets.push(...weightedSample(pool.filter((q) => !ids.has(q.id)), count - buckets.length));
  }
  return buckets.slice(0, count);
}

export interface OfflineQuizArgs {
  count: number;
  difficulty: DifficultyMode;
  categories: CategoryType[];
}

/** Build an offline quiz session — same shape as GET /api/quiz/questions. */
export function offlineQuizSelect(args: OfflineQuizArgs): { sessionId: string; questions: Question[] } {
  const pool = DATA.questions.filter((q) => args.categories.includes(q.category));
  const selected = selectByDifficulty(pool, args.difficulty, args.count);
  const sessionId = `${OFFLINE_PREFIX}${Date.now()}:${seq++}`;
  sessions.set(sessionId, selected);
  const questions: Question[] = selected.map((q) => ({
    id: q.id,
    tags: q.tags,
    introduction: q.introduction,
    question: q.question,
    options: q.options,
    category: q.category,
    difficulty: q.difficulty,
  }));
  return { sessionId, questions };
}

export const isOfflineSession = (sessionId: string): boolean => sessionId.startsWith(OFFLINE_PREFIX);

/** Grade an offline quiz session — same shape as POST /api/quiz/submit. */
export function offlineGrade(sessionId: string, answers: Record<string, number>): QuizResult {
  const selected = sessions.get(sessionId) ?? [];
  const results = selected.map((q) => {
    const selectedIndex = answers[q.id] ?? -1;
    return {
      questionId: q.id,
      selectedIndex,
      correctAnswer: q.correctAnswer,
      isCorrect: selectedIndex === q.correctAnswer,
      explanation: q.explanation,
    };
  });
  const correctAnswers = results.filter((r) => r.isCorrect).length;
  const totalQuestions = selected.length;
  sessions.delete(sessionId);
  return {
    totalQuestions,
    correctAnswers,
    percentage: totalQuestions ? Math.round((correctAnswers / totalQuestions) * 100) : 0,
    results,
  };
}
