// Generated by scripts/build-curation-registry.ts from docs/audit/devshark-content-ledger.json. Do not edit by hand.
// One row per reviewed item: the hash of the exact content the decision was made about, the
// scores, and the decision. Rationale and evidence stay in the ledger.

import type { RegistryEntry } from '../shared/curation';

export const REGISTRY_AUDITED_ON = "2026-09-09";

export const REVIEW_REGISTRY: readonly RegistryEntry[] = [

];
