import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations of quiz questions, keyed by question id.
//
// Only the text fields are translated; `options` arrays MUST keep the same
// order as the English source so the stored correctAnswer index stays valid.
// Questions without an entry here fall back to English automatically.
//
// Batches are filled in incrementally. Current coverage: APT (791-890).
export const questionTranslationsCs: Record<string, QuestionTranslation> = {
  '791': {
    introduction: 'Apetee Reborn běží v režimu jedna instalace na restauraci a celý systém nastavení formuje jedno základní pravidlo.',
    question: 'Jaké je ústřední pravidlo, kvůli kterému v Apetee Reborn existuje „Systémové nastavení“?',
    options: [
      'Nic specifické pro klienta (texty, barvy, e-maily, pravidla, přepínače modulů) není natvrdo v kódu; všechno je v databázi a edituje se z administrace',
      'Každá restaurace sdílí jeden globální řádek v databázi, ze kterého čtou všechny instalace',
      'Veškerá konfigurace se při buildu zakompiluje do bundle kvůli výkonu',
      'Nastavení lze měnit jen novým nasazením aplikace',
    ],
    explanation: 'Princip je „jedna instalace = jedna restaurace“ a nic specifické pro klienta není natvrdo v kódu. Texty, barvy, e-maily, pravidla i přepínače modulů jsou v databázi a editují se z administrace.',
  },
  '792': {
    introduction: 'Jedna myšlenka je popsána jako srdce celého systému nastavení.',
    question: 'Jaká je „hlavní myšlenka“ konfigurace řízené schématem (schema-driven)?',
    options: [
      'Nastavení definuješ jednou ve schématu a z něj se automaticky odvodí tři věci: typy, formulář v UI a validace',
      'Formulář, typy i validaci píšeš ručně pro každé nastavení, aby zůstaly oddělené',
      'Schémata se ukládají do databáze, aby se dala měnit za běhu',
      'Každé nastavení vyžaduje vlastní React komponentu a Zod soubor',
    ],
    explanation: 'Schema-driven konfigurace znamená: definuj jednou ve schématu a pak se z něj automaticky odvodí (a) typy, (b) formulář v UI a (c) validace. Formuláře nepíšeš ručně.',
  },
  '793': {
    introduction: 'Codebase dodržuje jeden konzistentní strukturní styl pro modely, services, config i validátory.',
    question: 'Jak je codebase Apetee Reborn stylisticky strukturovaný?',
    options: [
      'Class-based: každý model, service, config, validátor i integrace je export class se statickými metodami',
      'Funkcionálně: samostatné exportované funkce a prosté objektové literály',
      'Objektově s instančními metodami a kontejnery pro dependency injection',
      'Smíšeně, kde modely jsou třídy, ale config jsou prosté funkce',
    ],
    explanation: 'Celý codebase je class-based. Každý model, service, config, validátor i integrace je export class se statickými metodami. Nejsou tu volné funkce ani objektové literály; SystemConfig.get(...) je volání statické metody.',
  },
  '794': {
    introduction: 'Data tečou striktně oddělenými vrstvami, každá má jednu zodpovědnost.',
    question: 'Jaké je správné pořadí vrstev zápisové cesty odshora dolů?',
    options: [
      'UI (SettingsForm) -> actions.ts -> Services -> SystemConfig -> Setting model -> DB tabulka settings',
      'UI -> SystemConfig -> Services -> actions.ts -> Setting model -> DB',
      'UI -> Setting model -> Services -> SystemConfig -> actions.ts -> DB',
      'UI -> Services -> SystemConfig -> actions.ts -> Setting model -> DB',
    ],
    explanation: 'Tok je: UI formulář -> server action (validace přes ZodSchemaBuilder) -> Service (business logika) -> SystemConfig (brána pro serializaci/deserializaci) -> Setting model (jediné SQL) -> tabulka settings.',
  },
  '795': {
    introduction: 'Z jedné definice pole systém odvozuje tři artefakty, každý ve svém souboru.',
    question: 'Který soubor odvozuje ze schématu TypeScriptové TYPY?',
    options: [
      'lib/config/derive/keys.ts',
      'lib/config/derive/ui.ts',
      'lib/config/derive/zod.ts',
      'lib/config/SystemConfig.ts',
    ],
    explanation: 'derive/keys.ts odvozuje typy (SettingKey, SettingValue<K>). derive/ui.ts staví UI metadata (ConfigUiHelper) a derive/zod.ts staví validaci (ZodSchemaBuilder).',
  },
  '796': {
    introduction: 'Každý derive soubor má jasně danou zodpovědnost.',
    question: 'Co produkuje lib/config/derive/ui.ts (ConfigUiHelper)?',
    options: [
      'UI metadata pro formulář plus převody hodnot (převod jednotek, rozdělení multiselectu, zanořený tvar)',
      'TypeScriptový union všech klíčů nastavení',
      'Zod validační schéma pro každou sekci',
      'SQL dotazy použité pro čtení nastavení',
    ],
    explanation: 'ConfigUiHelper v derive/ui.ts mění schéma na metadata formuláře a řeší převody mezi storage tvarem a form tvarem (např. sekundy<->hodiny, čárkou oddělený string<->pole).',
  },
  '797': {
    introduction: 'Validace je pro většinu nastavení generovaná, ne psaná ručně.',
    question: 'Co generuje lib/config/derive/zod.ts (ZodSchemaBuilder)?',
    options: [
      'Zod validační schémata (min/max, povinnost, formát e-mailu) použitá shodně na klientovi i na serveru',
      'Výchozí hodnoty zobrazené ve formuláři',
      'Seznam aktivních jazyků zjištěných při buildu',
      'Šifrovací klíče pro SMTP heslo',
    ],
    explanation: 'ZodSchemaBuilder odvozuje Zod schéma ze schématu sekce. Stejná definice pohání validaci na klientovi (přeložené hlášky) i na serveru (obecné hlášky).',
  },
  '798': {
    introduction: 'ConfigField je diskriminovaný union rozlišený podle vlastnosti „type“.',
    question: 'Který seznam správně vyjmenovává osm typů ConfigField?',
    options: [
      'checkbox, number, text, password, email, image, select, multiselect',
      'boolean, int, string, secret, mail, file, dropdown, tags',
      'switch, range, input, hidden, email, upload, combobox, list',
      'checkbox, number, text, password, email, date, select, radio',
    ],
    explanation: 'Osm typů polí je checkbox, number, text, password, email, image, select a multiselect. Vlastnost „type“ je diskriminátor unionu.',
  },
  '799': {
    introduction: 'Jen jeden typ pole podporuje převod jednotek mezi uložením a zobrazením.',
    question: 'Které speciální vlastnosti podporuje pole „number“ pro převod jednotek?',
    options: [
      'storageUnit a displayUnit (plus min a max)',
      'options a filterByKey',
      'secret a encrypted',
      'jen min a step',
    ],
    explanation: 'Pole number může deklarovat min, max, storageUnit a displayUnit. Dvojice jednotek řídí převod, např. uložení v sekundách, ale editace v hodinách.',
  },
  '800': {
    introduction: 'Select pole mohou záviset na hodnotě jiného pole.',
    question: 'Která vlastnost způsobí, že select pole filtruje své možnosti podle jiného pole?',
    options: [
      'filterByKey',
      'visibleWhen',
      'dependsOn',
      'optionsFrom',
    ],
    explanation: 'Select pole používá options plus filterByKey pro závislé filtrování. Například i18n.frontend.defaultLocale má filterByKey: "i18n.activeLocales", takže se nabídnou jen aktivní jazyky.',
  },
  '801': {
    introduction: 'multiselect má neobvyklou uloženou reprezentaci.',
    question: 'Jak se ukládá a typuje hodnota „multiselect“?',
    options: [
      'Jako jeden čárkou oddělený string',
      'Jako JSON pole v databázi',
      'Jako více řádků, jeden na každou vybranou možnost',
      'Jako boolean pro každou možnost',
    ],
    explanation: 'multiselect se v UI vykreslí jako několik přepínačů, ale jeho typ hodnoty je jeden čárkou oddělený string (např. "cs,en,de"). Ve formuláři se z něj stane pole a při uložení se zase spojí.',
  },
  '802': {
    introduction: 'Drobný, ale důležitý fakt o polích label a description.',
    question: 'Co obsahují vlastnosti label, description a groupLabel?',
    options: [
      'i18n klíče (např. "settings.auth.totp.required"), které se v UI přeloží přes t(...)',
      'Hotový čitelný text v angličtině',
      'HTML fragmenty vykreslené přímo',
      'Názvy sloupců v databázi',
    ],
    explanation: 'label, description, groupLabel atd. NEJSOU hotové texty; jsou to i18n klíče přeložené v UI přes t(...). Právě to umožňuje vícejazyčnost.',
  },
  '803': {
    introduction: 'Podmíněná viditelnost se na poli vyjadřuje deklarativně.',
    question: 'Co dělá vlastnost visibleWhen?',
    options: [
      'Ukáže nebo skryje pole podle hodnoty jiného pole, např. { key: "auth.rateLimit.enabled", equals: true }',
      'Označí pole jako povinné jen za určité podmínky',
      'Pole zakáže, ale ponechá viditelné',
      'Řídí, které oprávnění pole vidí',
    ],
    explanation: 'visibleWhen způsobí, že se pole objeví, jen když jiné pole má danou hodnotu. auth.rateLimit.maxAttempts se ukáže jen když auth.rateLimit.enabled === true.',
  },
  '804': {
    introduction: 'Vlastnost key má dvojí roli.',
    question: 'Co je zvláštního na „key“ pole ConfigField jako "smtp.host"?',
    options: [
      'Je to unikátní identifikátor pole A ZÁROVEŇ doslovný klíč uložený v databázi',
      'Používá se jen v UI a nikdy se neukládá',
      'Mapuje se na dedikovaný sloupec v databázi',
      'Generuje se z labelu automaticky při buildu',
    ],
    explanation: 'key je zároveň unikátní identifikátor pole i přesný klíč použitý v tabulce settings. Struktura je zakódovaná v samotném tečkovém klíči.',
  },
  '805': {
    introduction: 'Pole se sdružují do sekcí, sekce do modulů.',
    question: 'Co v ConfigSchema (sekci) reprezentuje vlastnost „slug“?',
    options: [
      'Identifikátor sekce, např. "auth" nebo "smtp", podle kterého kód sekci vyhledá',
      'i18n nadpis zobrazený nad formulářem',
      'Vyžadovaný řetězec oprávnění',
      'Název databázové tabulky pro tu sekci',
    ],
    explanation: 'slug je identifikátor sekce (auth, smtp, ...). Kód se vždy řídí podle slug, ne podle názvu souboru. label je i18n nadpis a permission je vyžadované oprávnění.',
  },
  '806': {
    introduction: 'Každá systémová sekce deklaruje oprávnění.',
    question: 'Které oprávnění vyžadují všechny sekce systémového nastavení?',
    options: [
      'settings.system',
      'settings.general',
      'admin.superuser',
      'system.write',
    ],
    explanation: 'Každé ConfigSchema v modulu system deklaruje permission: "settings.system", což odpovídá oprávnění definovanému v Setting.permissions.ts.',
  },
  '807': {
    introduction: 'Sekce řídí, jak jsou jejich pole uspořádaná.',
    question: 'Jaká je výchozí hodnota vlastnosti „layout“ v ConfigSchema a která sekce ji přepíše na "row"?',
    options: [
      'Výchozí "stack"; sekce formatting používá "row"',
      'Výchozí "row"; sekce auth používá "stack"',
      'Výchozí "grid"; sekce smtp používá "row"',
      'Výchozí "stack"; sekce restaurant používá "row"',
    ],
    explanation: 'layout je výchozí "stack". Sekce formatting (dateFormat/timeFormat/currency) používá layout "row".',
  },
  '808': {
    introduction: 'Všechny sekce se sdruží a pak zaregistrují.',
    question: 'Co je systemSchema a kde žije?',
    options: [
      'ModuleSchema sdružující všechny systémové sekce (modules, restaurant, locales, logo, auth, smtp, logs, ui, formatting, phone) v schema/system/index.ts',
      'Databázová tabulka ukládající definice sekcí',
      'React kontext poskytující nastavení komponentám',
      'Zod schéma validující celou tabulku settings',
    ],
    explanation: 'systemSchema (v schema/system/index.ts) je ModuleSchema s modulem "system", který sdružuje všechny systémové sekce do jednoho záznamu registru.',
  },
  '809': {
    introduction: 'Jeden TypeScriptový detail je popsán jako kritický pro celý derive engine.',
    question: 'Proč je u definic schémat nutné „as const“?',
    options: [
      'Bez něj by TypeScript rozšířil literály (např. type na string) a odvození typů v keys.ts by se zhroutilo',
      'Za běhu zmrazí objekty, aby zabránil mutaci',
      'Umožní tree-shaking nepoužitých polí',
      'Zaregistruje schéma do databáze',
    ],
    explanation: 'as const zachová přesné literály (např. type je doslova "checkbox", ne string). Bez něj by odvození SettingKey/SettingValue v keys.ts spadlo na string.',
  },
  '810': {
    introduction: 'Tři moduly se spojí do jednoho vrcholového registru.',
    question: 'Které tři moduly tvoří registr SystemSettings?',
    options: [
      'system, reservations, sales',
      'system, auth, smtp',
      'admin, frontend, shared',
      'core, modules, integrations',
    ],
    explanation: 'SystemSettings (schema/index.ts) sdružuje schémata modulů system, reservations a sales do jednoho registru, kořene veškerého odvození typů.',
  },
  '811': {
    introduction: 'Pomocná třída najde sekci podle slug.',
    question: 'Co dělá SchemaLookup.findSection(slug)?',
    options: [
      'Projde všechny moduly a sekce a vrátí odpovídající ConfigSchema (nebo undefined)',
      'Vytvoří novou sekci v databázi',
      'Vrátí Zod schéma pro slug',
      'Vypíše všechna oprávnění sekce',
    ],
    explanation: 'SchemaLookup.findSection(slug) iteruje přes každý modul a sekci a vrátí ConfigSchema, jehož slug odpovídá, nebo undefined.',
  },
  '812': {
    introduction: 'Všechna systémová nastavení se ukládají do jediné záměrně jednoduché tabulky.',
    question: 'Jaký je tvar tabulky settings?',
    options: [
      'Plochý key/value store: key (varchar PK), value (text, nullable), updated_at (timestamp)',
      'Klasický EAV se sloupci module, group a locale',
      'Jeden sloupec na každé nastavení, přidávaný migracemi',
      'JSON dokument sloupec klíčovaný podle slug sekce',
    ],
    explanation: 'settings je plochý key/value store. key je primární klíč (varchar 255), value je nullable text, updated_at je timestamptz s defaultem now(). Veškerá struktura je zakódovaná v tečkovém klíči.',
  },
  '813': {
    introduction: 'Sloupec value má jeden pevný typ bez ohledu na logický typ.',
    question: 'Jak se v tabulce settings ukládá boolean jako true nebo číslo jako 604800?',
    options: [
      'Jako text: "true"/"false" a "604800"; sloupec value je vždy text',
      'Jako nativní boolean a integer sloupce',
      'Jako JSON-zakódované primitivy',
      'Jako base64-zakódované bloby',
    ],
    explanation: 'value je vždy text. Booleany jsou stringy "true"/"false" a čísla jsou číselné stringy. Převod na skutečný typ se děje o vrstvu výš v SystemConfig.',
  },
  '814': {
    introduction: 'Existuje několik podobně pojmenovaných tabulek, které se nesmí plést.',
    question: 'Jak se sdílená tabulka „settings“ liší od „reservation_settings“ a „sales_settings“?',
    options: [
      'settings je globální systémová konfigurace; ostatní jsou per-room EAV pro nastavení rezervací/prodeje',
      'Jsou to identické tabulky s jiným názvem',
      'settings je per-room; ostatní jsou globální',
      'reservation_settings nahrazuje settings pro modul rezervací',
    ],
    explanation: 'Sdílená tabulka settings je globální systémová konfigurace. reservation_settings a sales_settings jsou per-room EAV tabulky pro tyto moduly. Nepleť si je.',
  },
  '815': {
    introduction: 'Jeden model je jediným strážcem SQL nad tabulkou settings.',
    question: 'Co je unikátní na modelu Setting ohledně přístupu k databázi?',
    options: [
      'Je to jediné místo v celém codebase, které spouští SQL nad tabulkou settings',
      'Cachuje všechna nastavení do Redisu před každým dotazem',
      'Vystavuje gettery a settery pro každé jednotlivé nastavení',
      'Validuje hodnoty přes Zod před zápisem',
    ],
    explanation: 'Setting je jediné místo, které sahá na tabulku settings přes SQL. Má jen dvě hromadné metody, getByKeys a setMany, a nedělá žádnou serializaci ani typování.',
  },
  '816': {
    introduction: 'getByKeys garantuje předvídatelný tvar návratu.',
    question: 'Co vrátí Setting.getByKeys pro požadovaný klíč, který v databázi chybí?',
    options: [
      'null pro ten klíč (vrátí záznam pro každý požadovaný klíč)',
      'Klíč z výsledku úplně vynechá',
      'undefined pro ten klíč',
      'Výchozí hodnotu ze schématu',
    ],
    explanation: 'getByKeys iteruje přes POŽADOVANÉ klíče a každému nastaví jeho DB hodnotu, nebo null když chybí. Defaulty se aplikují později v SystemConfig, ne tady.',
  },
  '817': {
    introduction: 'Zápisy jsou hromadné upserty.',
    question: 'Jak Setting.setMany ukládá více záznamů v Postgresu?',
    options: [
      'Jediným insertem s ON CONFLICT (key) DO UPDATE nastavujícím value = excluded.value a updatedAt',
      'Cyklem vydávajícím jeden UPDATE na klíč',
      'DELETE všech klíčů následovaný hromadným INSERT',
      'Příkazem MERGE spuštěným uvnitř uložené procedury',
    ],
    explanation: 'setMany vloží všechny dvojice a použije onConflictDoUpdate na primárním klíči key, nastaví value na excluded.value a obnoví updatedAt. Je to upsert.',
  },
  '818': {
    introduction: 'Obě metody Setting zkratují na prázdném vstupu.',
    question: 'Co se stane, když je Setting.getByKeys zavoláno s prázdným polem?',
    options: [
      'Vrátí prázdný objekt {} bez jakéhokoli databázového dotazu',
      'Vyhodí chybu kvůli neplatnému vstupu',
      'Vrátí null',
      'Vrátí všechny řádky v tabulce',
    ],
    explanation: 'getByKeys vrátí {} okamžitě pro prázdný vstup (bez dotazu). setMany se podobně předčasně vrátí, když nejsou žádné dvojice.',
  },
  '819': {
    introduction: 'Model Setting doprovázejí dvě oprávnění.',
    question: 'Která dvě oprávnění jsou definována v Setting.permissions.ts?',
    options: [
      'settings.general a settings.system (obě modul "shared", s view + edit)',
      'settings.read a settings.write',
      'admin.view a admin.edit',
      'system.config a system.audit',
    ],
    explanation: 'Setting.permissions.ts definuje settings.general a settings.system, obě v modulu "shared" s operacemi view a edit. Schémata se odkazují na settings.system.',
  },
  '820': {
    introduction: 'Dva soubory schémat mají slug odlišný od názvu souboru.',
    question: 'Které dva soubory schémat mají slug, který NEODPOVÍDÁ názvu souboru?',
    options: [
      'phone.schema.ts -> slug "phonePrefix"; locales.schema.ts -> slug "languages"',
      'auth.schema.ts -> slug "security"; smtp.schema.ts -> slug "mail"',
      'logo.schema.ts -> slug "branding"; ui.schema.ts -> slug "admin"',
      'modules.schema.ts -> slug "features"; logs.schema.ts -> slug "audit"',
    ],
    explanation: 'phone.schema.ts má slug "phonePrefix" a locales.schema.ts má slug "languages". Kód se vždy řídí podle slug, nikdy podle názvu souboru.',
  },
  '821': {
    introduction: 'keys.ts je mezi zdrojovými soubory neobvyklý.',
    question: 'Co platí o lib/config/derive/keys.ts?',
    options: [
      'Neobsahuje žádný běžící kód, jen TypeScriptové typy (SettingKey, SettingValue<K>, SettingValues)',
      'Běží při startu, aby zaregistroval klíče do databáze',
      'Exportuje funkce, které čtou nastavení synchronně',
      'Definuje Zod schémata pro každý klíč',
    ],
    explanation: 'keys.ts nemá žádný běžící kód. Jsou to čistě typy: SettingKey (union všech klíčů), SettingValue<K> (přesný typ hodnoty pro klíč) a SettingValues (pytlík pro zápis více hodnot).',
  },
  '822': {
    introduction: 'SettingValue<K> mapuje každý typ pole na typ hodnoty.',
    question: 'Na jaký typ hodnoty mapuje v keys.ts pole „select“?',
    options: [
      'Union jeho povolených hodnot z options',
      'Prostý string bez zúžení',
      'boolean',
      'Pole stringů',
    ],
    explanation: 'checkbox -> boolean, number -> number, select -> union povolených hodnot z options, multiselect -> string (čárkou oddělený) a text/password/email/image -> string.',
  },
  '823': {
    introduction: 'Silné typování zachytí chyby ještě před během.',
    question: 'Co se stane, když napíšeš SystemConfig.get("auth.totp.requiredd") s překlepem?',
    options: [
      'TypeScript nahlásí chybu při kompilaci, protože klíč není součástí SettingKey',
      'Za běhu vrátí null',
      'Tiše vytvoří v databázi nový klíč',
      'Vrátí výchozí hodnotu nejbližšího odpovídajícího klíče',
    ],
    explanation: 'Protože klíče se odvozují do unionu SettingKey, překlep odmítne kompilátor. Správný klíč jako auth.totp.required navíc vrátí přesný typ boolean.',
  },
  '824': {
    introduction: 'ConfigUiHelper přemosťuje dva různé tvary hodnot.',
    question: 'Co dělá ConfigUiHelper.buildDefaultValues?',
    options: [
      'Mění plochý storage tvar na zanořený objekt formuláře, aplikuje defaulty, převod jednotek a rozdělení multiselectu',
      'Mění zanořený objekt formuláře zpět na ploché storage hodnoty',
      'Validuje hodnoty formuláře přes Zod',
      'Čte defaulty přímo z databáze',
    ],
    explanation: 'buildDefaultValues mapuje storage tvar na zanořený form tvar: aplikuje defaulty ze schématu, převádí jednotky (sekundy na hodiny) a rozděluje multiselect stringy na pole.',
  },
  '825': {
    introduction: 'K buildDefaultValues existuje opačná funkce.',
    question: 'Co dělá ConfigUiHelper.buildStorageValues?',
    options: [
      'Převede zanořený objekt formuláře na plochý storage tvar (hodiny na sekundy, pole na čárkou oddělené stringy)',
      'Postaví výchozí hodnoty pro prázdný formulář',
      'Seskupí pole podle jejich vlastnosti group',
      'Vrátí props číselného inputu pro element Input',
    ],
    explanation: 'buildStorageValues je opačný směr: zanořený formulář -> plochý storage tvar, mění zobrazovací jednotky zpět na storage jednotky a pole na čárkou oddělené stringy.',
  },
  '826': {
    introduction: 'Převod jednotek používá pevné faktory.',
    question: 'Které převodní faktory používá ConfigUiHelper pro displayUnit "hours" a "minutes"?',
    options: [
      '3600 pro hodiny a 60 pro minuty (a 1, když není jednotka nastavena)',
      '60 pro hodiny a 1 pro minuty',
      '1000 pro hodiny a 60 pro minuty',
      '24 pro hodiny a 60 pro minuty',
    ],
    explanation: 'Faktor je 3600 pro hodiny, 60 pro minuty a 1 (žádný převod), když pole jednotku nemá. Převádějí se i meze: toDisplayMin zaokrouhluje nahoru, toDisplayMax dolů.',
  },
  '827': {
    introduction: 'Konkrétní příklad převodu jednotek v praxi.',
    question: 'auth.sessionMaxAge ukládá v DB 604800. Co uživatel edituje ve formuláři?',
    options: [
      '168 (hodin), protože displayUnit je "hours" a 604800 / 3600 = 168',
      '604800 (sekund), beze změny',
      '7 (dní)',
      '10080 (minut)',
    ],
    explanation: 'sessionMaxAge má storageUnit seconds a displayUnit hours. 604800 sekund / 3600 = 168 hodin, což uživatel vidí a edituje. Při uložení se to zase vynásobí.',
  },
  '828': {
    introduction: 'Pomocná funkce normalizuje čárkou oddělený vstup.',
    question: 'Co vrátí ConfigUiHelper.splitCommaString(" cs, en ,,de ", { allowed })?',
    options: [
      '["cs", "en", "de"] (oříznuté, prázdné vyhozené, filtrované na povolené hodnoty)',
      '[" cs", " en ", "", "de "] (jen syrové rozdělení)',
      '"cs,en,de" (vyčištěný string)',
      'Chybu kvůli prázdnému segmentu',
    ],
    explanation: 'splitCommaString ořízne každý segment, vyhodí prázdné a filtruje na povolené hodnoty, čímž vznikne ["cs","en","de"].',
  },
  '829': {
    introduction: 'Tečkové klíče se mapují na zanořené objekty.',
    question: 'Co dělají getNestedValue(obj, "a.b.c") a setNestedValue?',
    options: [
      'Čtou a zapisují hodnotu uvnitř zanořeného objektu pomocí tečkové cesty',
      'Čtou a zapisují řádky v tabulce settings',
      'Převádějí zanořený objekt na plochý',
      'Validují tečkový klíč proti schématu',
    ],
    explanation: 'getNestedValue a setNestedValue čtou/zapisují do zanořeného objektu podle tečkového klíče jako "a.b.c", což je způsob, jakým se ploché storage klíče mapují na zanořený objekt formuláře.',
  },
  '830': {
    introduction: 'ZodSchemaBuilder nabízí dvě stavěcí metody.',
    question: 'Jaký je rozdíl mezi ZodSchemaBuilder.build(slug) a buildNestedSchema(slug, messages)?',
    options: [
      'build vyrobí PLOCHÉ serverové schéma s obecnými hláškami; buildNestedSchema vyrobí ZANOŘENÉ klientské schéma s přeloženými hláškami',
      'build je pro klienta; buildNestedSchema pro server',
      'build validuje čísla; buildNestedSchema validuje stringy',
      'Jsou to aliasy s identickým výstupem',
    ],
    explanation: 'build(slug) vyrobí ploché (tečkové klíče) schéma použité na serveru bez přeložených hlášek. buildNestedSchema(slug, messages) zrcadlí tvar formuláře a používá vstříknuté přeložené hlášky na klientovi.',
  },
  '831': {
    introduction: 'Validační hlášky následují projektovou konvenci.',
    question: 'Jak se ZodSchemaBuilderu předávají validační hlášky?',
    options: [
      'Vstřikují se zvenčí přes rozhraní SettingsValidationMessages (nikdy nejsou natvrdo ve validátoru)',
      'Jsou natvrdo jako anglické stringy uvnitř builderu',
      'Čtou se z databáze při každém requestu',
      'Generují se automaticky z klíče pole',
    ],
    explanation: 'Hlášky se vstřikují přes SettingsValidationMessages (required, invalidEmail, min(n), max(n)). min/max jsou funkce, protože mez je u každého pole jiná. Díky tomu běží stejné schéma přeložené na klientovi a bez hlášek na serveru.',
  },
  '832': {
    introduction: 'Pole password má záměrnou validační zvláštnost.',
    question: 'Jak fieldToZod validuje pole „password“?',
    options: [
      'Jako z.string(), které se nikdy nevaliduje na délku, ani když je pole povinné',
      'Jako z.string().min(8) pro vynucení minimální délky',
      'Jako z.string().email()',
      'Z validace se úplně vyloučí',
    ],
    explanation: 'password mapuje na z.string() a nikdy se nevaliduje na délku, ani když je povinné. Je to proto, že prázdné odeslání hesla znamená „ponechat stávající“.',
  },
  '833': {
    introduction: 'Validace e-mailu se přizpůsobí tomu, zda je pole povinné.',
    question: 'Jak se validuje nepovinné pole „email“?',
    options: [
      'z.string().email(), které navíc povolí prázdný string',
      'z.string().email(), které prázdné stringy odmítne',
      'z.string() bez kontroly e-mailu',
      'z.optional() bez validace',
    ],
    explanation: 'email mapuje na z.string().email(); když není povinné, navíc povolí prázdný string, takže nepovinné kontaktní e-maily lze nechat prázdné.',
  },
  '834': {
    introduction: 'Každý typ pole mapuje na nějaký Zod typ.',
    question: 'Jak fieldToZod mapuje pole „select“?',
    options: [
      'z.enum([...povolené hodnoty])',
      'z.string() bez zúžení',
      'z.array(z.string())',
      'z.union booleanů',
    ],
    explanation: 'select mapuje na z.enum([...povolené hodnoty]). multiselect je na serveru z.string() (čárkou oddělené) a ve formuláři z.array(z.enum([...])).',
  },
  '835': {
    introduction: 'SystemConfig sedí mezi typovaným kódem aplikace a netypovaným úložištěm.',
    question: 'Jaká je hlavní zodpovědnost SystemConfig?',
    options: [
      'Serializace (typ -> string při zápisu) a deserializace (string -> typ při čtení) mezi aplikací a key/value store',
      'Spouštění SQL dotazů nad tabulkou settings',
      'Vykreslování formuláře nastavení',
      'Šifrování a dešifrování SMTP hesla',
    ],
    explanation: 'SystemConfig je brána, která serializuje typy na stringy při zápisu a deserializuje stringy na typy při čtení. SQL deleguje na model Setting.',
  },
  '836': {
    introduction: 'SystemConfig si při startu staví interní lookup.',
    question: 'Co je privátní fieldMap uvnitř SystemConfig?',
    options: [
      'Plochá mapa key -> ConfigField napříč všemi moduly/sekcemi, pro rychlé nalezení typu a defaultu každého klíče',
      'Cache databázových hodnot klíčovaná podle klíče nastavení',
      'Mapa oprávnění na sekce',
      'Registr Zod schémat',
    ],
    explanation: 'fieldMap je plochá mapa key -> ConfigField sestavená ze všech modulů a sekcí, aby SystemConfig rychle našel typ pole a default pro libovolný klíč.',
  },
  '837': {
    introduction: 'SystemConfig.get je plně typovaný.',
    question: 'Jaký je návratový typ SystemConfig.get("auth.totp.required")?',
    options: [
      'Promise<boolean> (přesný přes SettingValue<K>)',
      'Promise<string>',
      'Promise<string | null>',
      'Promise<unknown>',
    ],
    explanation: 'get<K> vrací SettingValue<K>, takže auth.totp.required dává Promise<boolean>, ne obecný string. Hodnota se deserializuje z uloženého stringu.',
  },
  '838': {
    introduction: 'Existuje úniková cesta pro klíče mimo schéma.',
    question: 'Kdy bys měl použít SystemConfig.getRaw(key) místo get(key)?',
    options: [
      'Když klíč není v žádném schématu (např. dynamické klíče) nebo chceš syrový string bez deserializace',
      'Když chceš typovanou, deserializovanou hodnotu',
      'Když zapisuješ více hodnot najednou',
      'Když potřebuješ obejít oprávnění',
    ],
    explanation: 'getRaw vrací syrový string bez deserializace. Použij ho pro dynamické klíče, které nejsou v žádném schématu (např. log_entity_*_enabled), nebo pro rychlý check.',
  },
  '839': {
    introduction: 'Celou sekci lze načíst najednou.',
    question: 'Co vrací SystemConfig.getSection(slug)?',
    options: [
      'Plochou mapu key -> typovaná hodnota pro celou sekci, načtenou jedním dotazem a deserializovanou po poli',
      'Zanořený objekt formuláře pro sekci',
      'Zod schéma sekce',
      'Syrové stringy bez deserializace',
    ],
    explanation: 'getSection načte celou sekci jedním dotazem a deserializuje každé pole, vrací plochou mapu key -> typovaná hodnota (storage tvar).',
  },
  '840': {
    introduction: 'Zápisy procházejí jednou metodou.',
    question: 'Jak SystemConfig.setValues řeší undefined hodnoty a serializaci?',
    options: [
      'Vyhodí undefined, vše převede přes String(...) a výsledek předá Setting.setMany',
      'Vyhodí chybu, když je nějaká hodnota undefined',
      'Uloží undefined jako string "undefined"',
      'Zapíše každou hodnotu vlastním SQL UPDATE',
    ],
    explanation: 'setValues zahodí undefined záznamy, zbytek serializuje přes String(...) a předá mapu Setting.setMany pro jediný upsert.',
  },
  '841': {
    introduction: 'Deserializace řeší chybějící hodnotu speciálně.',
    question: 'Co vrátí SystemConfig.deserialize, když je syrová hodnota null?',
    options: [
      'Výchozí hodnotu pole (defaultValue) ze schématu',
      'null',
      'Prázdný string',
      'Vyhozenou chybu',
    ],
    explanation: 'Když je raw null (nic v DB), deserialize vrátí defaultValue pole deklarovanou ve schématu.',
  },
  '842': {
    introduction: 'Deserializace čísla je defenzivní.',
    question: 'Jak deserialize řeší pole „number“, jehož uložený string selže na parseInt?',
    options: [
      'Vrátí defaultValue pole, když je výsledek parsování NaN',
      'Vrátí 0',
      'Vyhodí chybu parsování',
      'Vrátí syrový string',
    ],
    explanation: 'U number polí parseIntuje v základu 10 a vrátí default, když je výsledek NaN, čímž se chrání před poškozenými hodnotami.',
  },
  '843': {
    introduction: 'SystemConfig se drží mimo šifrování.',
    question: 'Jak SystemConfig deserializuje pole „password“?',
    options: [
      'Jako syrový zašifrovaný string; dešifrování proběhne později v SmtpSettingsService.getAll, ne tady',
      'Okamžitě se dešifruje na plaintext',
      'Pro bezpečnost se nahradí prázdným stringem',
      'Před vrácením se zahashuje',
    ],
    explanation: 'password se deserializuje jako syrový zašifrovaný string. SystemConfig o šifrování nic neví; dešifrování se děje v SmtpSettingsService.getAll.',
  },
  '844': {
    introduction: 'Zdokumentovaná odchylka od konvencí projektu.',
    question: 'Co dokumentace říká o cachování v SystemConfig?',
    options: [
      'NEMÁ žádné cachování; každé čtení jde rovnou do DB, což se odchyluje od konvence unstable_cache/revalidateTag',
      'Používá unstable_cache s revalidateTag při každém čtení',
      'Cachuje vše do Redisu s TTL 60 s',
      'Cachuje čtení, ale ne zápisy',
    ],
    explanation: 'Přestože konvence CLAUDE.md říká používat unstable_cache + revalidateTag, SystemConfig necachuje; každé čtení jde do DB přes Setting.getByKeys. Je to označeno jako budoucí optimalizace.',
  },
  '845': {
    introduction: 'better-auth potřebuje hodnotu synchronně, bez await.',
    question: 'Proč AuthConfig drží expiraci reset hesla ve statické proměnné v paměti?',
    options: [
      'protože better-auth ji musí číst synchronně (bez await), takže nemůže v okamžiku volání dotazovat DB',
      'protože databáze je pro jakékoli čtení příliš pomalá',
      'protože se hodnota po nasazení nikdy nemění',
      'protože je zašifrovaná a nelze ji číst asynchronně',
    ],
    explanation: 'better-auth potřebuje platnost reset tokenu synchronně. AuthConfig ji cachuje ve statické proměnné, aby ji getPasswordResetExpirySecondsSync() vrátil bez volání DB.',
  },
  '846': {
    introduction: 'Cachovaná expirace se musí udržovat čerstvá.',
    question: 'Co dělá AuthConfig.reloadPasswordResetExpiry() a kdy se volá?',
    options: [
      'Načte auth.passwordResetTokenExpiryMinutes z DB, převede minuty na sekundy, uloží do paměti; volá se při startu a z AuthSettingsService.update',
      'Vymaže hodnotu z paměti, aby další čtení šlo do DB',
      'Vrátí všechna auth nastavení na defaulty',
      'Invaliduje všechny aktivní session',
    ],
    explanation: 'reloadPasswordResetExpiry načte hodnotu v minutách, převede na sekundy a uloží do cache. Musí běžet při startu a při změně nastavení (volá ji AuthSettingsService.update).',
  },
  '847': {
    introduction: 'Pro reset expiraci existuje rozumný default.',
    question: 'Jakou výchozí expiraci reset hesla vrací getPasswordResetExpirySecondsSync()?',
    options: [
      '1800 sekund (30 minut)',
      '3600 sekund (60 minut)',
      '300 sekund (5 minut)',
      '604800 sekund (7 dní)',
    ],
    explanation: 'Default je 1800 sekund = 30 minut, což odpovídá výchozí hodnotě 30 ze schématu pro auth.passwordResetTokenExpiryMinutes.',
  },
  '848': {
    introduction: 'Logování entit funguje na principu opt-out.',
    question: 'Jak LogsConfig.isEntityEnabled interpretuje dynamický klíč log_entity_${entity}_enabled?',
    options: [
      'Opt-out: když není nastaveno (null), logování je ZAPNUTÉ; vypne ho jen explicitní "false"',
      'Opt-in: když není nastaveno, logování je VYPNUTÉ, dokud se explicitně nenastaví na "true"',
      'Vyhodí chybu, když klíč chybí',
      'Vždy vrátí true bez ohledu na hodnotu',
    ],
    explanation: 'isEntityEnabled čte dynamický klíč přes getRaw (není v žádném schématu). Logika je opt-out: null znamená zapnuto; vypne ho jen explicitní "false".',
  },
  '849': {
    introduction: 'Audit logy mají konfigurovatelnou retenci.',
    question: 'Co vrací LogsConfig.getRetentionMonths() ve výchozím stavu?',
    options: [
      '12 (default logs.retentionMonths)',
      '1',
      '6',
      '120',
    ],
    explanation: 'getRetentionMonths vrací logs.retentionMonths, jehož default je 12 (min 1, max 120 měsíců).',
  },
  '850': {
    introduction: 'Možnosti stránkování v adminu pocházejí z dynamického JSON klíče.',
    question: 'Co dělá AdminUiConfig.getPageSizeOptions(), když ui.pageSizeOptions chybí nebo je rozbitý?',
    options: [
      'Vrátí default [10, 20, 50, 100, 200]',
      'Vrátí prázdné pole',
      'Vyhodí konfigurační chybu',
      'Vrátí jen [20]',
    ],
    explanation: 'getPageSizeOptions čte dynamický JSON klíč ui.pageSizeOptions a vrátí default [10, 20, 50, 100, 200], když chybí nebo je nerozparsovatelný.',
  },
  '851': {
    introduction: 'Výchozí velikost stránky se ověřuje proti možnostem.',
    question: 'Co vrátí AdminUiConfig.getDefaultPageSize(), když ui.defaultPageSize není jednou z povolených možností?',
    options: [
      'První dostupnou možnost',
      'Tu hodnotu i tak, ignoruje možnosti',
      'Vždy 20',
      'null',
    ],
    explanation: 'getDefaultPageSize vrátí ui.defaultPageSize (default 20) jen pokud je mezi povolenými možnostmi; jinak vrátí první možnost.',
  },
  '852': {
    introduction: 'Podporované jazyky se zjišťují při buildu.',
    question: 'Odkud v LocaleConfig pochází seznam podporovaných jazyků?',
    options: [
      'Z env proměnných při buildu (DISCOVERED_ADMIN_LOCALES, DISCOVERED_FRONTEND_LOCALES), s defaultem "cs"',
      'Z databázové tabulky locales',
      'Z hlavičky prohlížeče Accept-Language',
      'Z natvrdo zadaného pole v komponentě',
    ],
    explanation: 'Podporované jazyky se vstřikují při buildu z env proměnných DISCOVERED_ADMIN_LOCALES a DISCOVERED_FRONTEND_LOCALES; výchozí jazyk je "cs".',
  },
  '853': {
    introduction: 'LocaleConfig.getSettings vrací normalizovaný objekt.',
    question: 'Co vrací LocaleConfig.getSettings()?',
    options: [
      '{ activeLocales, adminDefaultLocale, frontendDefaultLocale }, s aktivními filtrovanými na podporované a ověřenými defaulty (fallback "cs")',
      'Syrový čárkou oddělený string jazyků',
      'Celou sekci languages ze systemSchema',
      'Jen výchozí admin jazyk',
    ],
    explanation: 'getSettings vrací activeLocales (filtrované na podporované), adminDefaultLocale a frontendDefaultLocale (ověřené přes resolveScopeDefault s fallbackem na "cs").',
  },
  '854': {
    introduction: 'Jedna metoda záměrně obchází jakoukoli mezivrstvu.',
    question: 'Proč LocaleConfig vystavuje getAdminDefaultLocaleFresh()?',
    options: [
      'Čte přímo ze Setting, takže právě uložená hodnota funguje hned (používá ji proxy runtime a redirect na /settings/system)',
      'Cachuje hodnotu na jednu hodinu',
      'Vrací jen výchozí hodnotu z buildu',
      'Validuje jazyk proti Zod',
    ],
    explanation: 'getAdminDefaultLocaleFresh je necachovaná verze jdoucí přímo na Setting, takže právě uložený jazyk se hned projeví pro proxy runtime a redirect na nastavení.',
  },
  '855': {
    introduction: 'actions.ts používá metodu LocaleConfig jako transform.',
    question: 'Co dělá LocaleConfig.fromStorageValues(data)?',
    options: [
      'Převede plochý form tvar na objekt LocaleSettings (používá ho actions.ts jako transform krok)',
      'Uloží nastavení jazyků do databáze',
      'Načte jazyky z env proměnných',
      'Spojí aktivní jazyky do čárkou odděleného stringu',
    ],
    explanation: 'fromStorageValues transformuje plochý form tvar na objekt LocaleSettings. actions.ts ho předává jako volitelný transform před validací. Samotné ukládání dělá update() (spojuje pole čárkami).',
  },
  '856': {
    introduction: 'Jeden config je úplně jiného druhu.',
    question: 'Kam TranslationOverrideConfig ukládá přepisy překladů?',
    options: [
      'Do JSON souborů na disku v languages/{admin|frontend}/overrides/{locale}-overrides.json, s in-memory Map cache',
      'Do tabulky settings jako všechno ostatní',
      'Do dedikované databázové tabulky translations',
      'Do localStorage prohlížeče',
    ],
    explanation: 'Přepisy překladů nejsou v DB. Jsou to JSON soubory na disku v languages/{admin|frontend}/overrides/, s in-memory Map cache zapisovanou při uložení.',
  },
  '857': {
    introduction: 'Klíče přepisů pro admin dostávají prefix.',
    question: 'Jak se ukládají versus zobrazují klíče přepisů pro oblast „admin“?',
    options: [
      'Ukládají se s prefixem "admin.", který přidá toStorageKey; prefix odstraní toDisplayKey při zobrazení',
      'Ukládají se bez prefixu; UI přidá "admin." jen kvůli řazení',
      'Ukládají se s prefixem "frontend." pro obě oblasti',
      'Ukládají se jako číselná id a překládají na klíče při čtení',
    ],
    explanation: 'Admin klíče se ukládají s prefixem "admin." (toStorageKey ho přidá) a zobrazují bez něj (toDisplayKey ho odstraní).',
  },
  '858': {
    introduction: 'Některá nastavení mají reálné běhové efekty jinde v aplikaci.',
    question: 'Co se stane, když je auth.totp.required vypnuté celosystémově?',
    options: [
      'lib/auth/auth.ts přeskočí TOTP krok přepsáním twoFactorEnabled na false při čtení uživatele',
      'TOTP secrety všech uživatelů se smažou z databáze',
      'Přihlašovací stránka se trvale nahradí formulářem jen s heslem',
      'Nic; nastavení je jen informativní',
    ],
    explanation: 'auth.ts čte auth.totp.required; když je 2FA celosystémově vypnuté, better-auth přeskočí TOTP krok přepsáním twoFactorEnabled na false při čtení uživatele.',
  },
  '859': {
    introduction: 'Rate limiter čte vlastní nastavení a má chybový režim.',
    question: 'Co dělá rate limiter, když selže čtení svých nastavení?',
    options: [
      'Selže „fail-open“ (rate limiting vypnutý), takže chyba čtení nezablokuje všechny',
      'Selže „fail-closed“ (zablokuje všechna přihlášení) kvůli bezpečnosti',
      'Vyhodí chybu a shodí přihlašovací route',
      'Použije natvrdo daný limit 3 pokusů',
    ],
    explanation: 'rate-limiter.ts čte auth.rateLimit.enabled/maxAttempts/lockoutSeconds a při chybě čtení selže fail-open (rate limit vypnutý), čímž se vyhne globálnímu zablokování.',
  },
  '860': {
    introduction: 'Přepínače modulů ovlivňují navigaci.',
    question: 'Která service používá modules.reservations.enabled a modules.sales.enabled?',
    options: [
      'AdminNavbarService, pro skrytí nebo zobrazení položek admin menu (zohledňuje i oprávnění)',
      'SmtpSettingsService, pro rozhodnutí, zda posílat e-maily',
      'AuthConfig, pro nastavení délky session',
      'LogsConfig, pro rozhodnutí o retenci',
    ],
    explanation: 'AdminNavbarService čte přepínače modulů (plus oprávnění) pro skrytí nebo zobrazení položek v levém admin menu.',
  },
  '861': {
    introduction: 'Uložení auth nastavení dělá víc než jen uložení hodnot.',
    question: 'Jaké je v AuthSettingsService.update správné pořadí vedlejších efektů po SystemConfig.setValues?',
    options: [
      'Vyčistit rate limit pokud vypnutý -> nastavit TOTP enabled u všech uživatelů -> přenačíst AuthConfig expiraci reset hesla',
      'Přenačíst AuthConfig -> nastavit TOTP u všech uživatelů -> vyčistit rate limit',
      'Nastavit TOTP u všech uživatelů -> přenačíst AuthConfig -> vyčistit rate limit',
      'Jen uložit hodnoty; žádné vedlejší efekty nejsou',
    ],
    explanation: 'update: (1) SystemConfig.setValues; (2) pokud se vypnul rate limit, RateLimiter.clearAll(); (3) User.setTotpEnabledForAll(...); (4) AuthConfig.reloadPasswordResetExpiry().',
  },
  '862': {
    introduction: 'Zapnutí 2FA spustí potvrzovací flow.',
    question: 'Co vrací AuthSettingsService.getTotpWarning() a proč?',
    options: [
      '{ count, items } uživatelů bez TOTP (items max ~10 jmen) pro potvrzovací dialog „vynutit 2FA?“',
      'Boolean, zda je TOTP vyžadováno',
      'Seznam všech uživatelů, kteří už TOTP mají',
      'Počet neúspěšných pokusů o přihlášení',
    ],
    explanation: 'getTotpWarning najde uživatele bez TOTP (User.getUsersWithoutTotp) a vrátí { count, items } (prvních ~10 jmen) pro potvrzovací dialog zobrazený při vynucování 2FA.',
  },
  '863': {
    introduction: 'SMTP heslo se při uložení řeší opatrně.',
    question: 'Co se stane v SmtpSettingsService.update, když je pole hesla odesláno prázdné?',
    options: [
      'Klíč smtp.password se z dat odstraní, takže se stávající uložené heslo nepřepíše',
      'Uložené heslo se smaže na prázdný string',
      'Update se odmítne jako neplatný',
      'Vygeneruje se a uloží náhodné heslo',
    ],
    explanation: 'Prázdné heslo znamená „ponechat stávající“: update odstraní smtp.password z dat. Vyplněná hodnota se zašifruje (encryptWithMasterSecret) a uloží jako šifrový text, nikdy plaintext.',
  },
  '864': {
    introduction: 'getAll přetvaruje a dešifruje sekci.',
    question: 'Co vrací SmtpSettingsService.getAll()?',
    options: [
      'Sekci smtp s odstřiženým prefixem "smtp." a dešifrovaným heslem, např. { host, port, encryption, user, password, fromName, fromEmail }',
      'Syrovou sekci smtp se zašifrovaným heslem a tečkovými klíči',
      'Jen host a port',
      'Boolean, zda je SMTP nakonfigurováno',
    ],
    explanation: 'getAll načte getSection("smtp"), dešifruje heslo (decryptWithMasterSecret) a vrátí objekt s odstřiženým prefixem smtp.',
  },
  '865': {
    introduction: 'Odeslání testovacího e-mailu nejdřív udělá levný precheck.',
    question: 'Co dělá SmtpSettingsService.sendTest jako první?',
    options: [
      'Levný check přes SystemConfig.getRaw("smtp.host"); když host není, vyhodí errors.smtp.notConfigured',
      'Okamžitě otevře SMTP spojení pro ověření přihlašovacích údajů',
      'Dešifruje heslo a zaloguje ho',
      'Zapíše testovací záznam do databáze',
    ],
    explanation: 'sendTest nejdřív čte smtp.host přes getRaw; chybějící host vyhodí errors.smtp.notConfigured. Pak resolvuje EmailProvider a pošle, při chybě vyhodí errors.smtp.sendFailed.',
  },
  '866': {
    introduction: 'Typ SmtpSettings je odvozený, ne psaný ručně.',
    question: 'Co se stane s typem SmtpSettings, když přidáš pole do smtp.schema.ts?',
    options: [
      'Typ se automaticky rozšíří, protože SmtpSettings je odvozený ze schématu (s odstřiženým prefixem)',
      'Nic; typ musíš aktualizovat ručně',
      'Build selže, dokud pole nesmažeš',
      'Nové pole se za běhu ignoruje',
    ],
    explanation: 'SmtpSettings je odvozený ze smtp.schema.ts (s odstřiženým prefixem smtp.), takže přidání pole do schématu typ automaticky rozšíří.',
  },
  '867': {
    introduction: 'Pro příjemce testovacího e-mailu existuje samostatný validátor.',
    question: 'Jak se SmtpTestValidator chová na serveru versus na klientovi?',
    options: [
      'Klient: volán s přeloženou hláškou invalidEmail; Server: volán bez argumentů, s defaultem "errors.generic"',
      'Vždy používá natvrdo dané anglické hlášky',
      'Běží jen na klientovi; server ho přeskočí',
      'Validuje tělo e-mailu, ne adresu',
    ],
    explanation: 'SmtpTestValidator.createSchema bere vstříknuté hlášky. Na klientovi dostane přeloženou invalidEmail; na serveru se volá bez argumentů a použije default { invalidEmail: "errors.generic" }.',
  },
  '868': {
    introduction: 'Samostatné validátory jsou výjimka, ne pravidlo.',
    question: 'Proč většina nastavení NEMÁ samostatnou třídu Validator?',
    options: [
      'Jejich validaci generuje ZodSchemaBuilder ze schématu; samostatné validátory existují jen tam, kde validace nevyplývá ze schématu',
      'Validace je pro většinu nastavení vypnutá',
      'Validují jen na klientovi a nikdy na serveru',
      'Validuje je Drizzle na úrovni databáze',
    ],
    explanation: 'Většina nastavení dostane generovanou validaci z ZodSchemaBuilder. Samostatné validátory existují jen tam, kde validace nevyplývá ze schématu: test e-mail, nastavení locale, přepisy překladů.',
  },
  '869': {
    introduction: 'Integrace používají vzor abstraktního provideru.',
    question: 'Jaká je jediná metoda kontraktu na abstraktní třídě EmailProvider?',
    options: [
      'send(input: SendEmailInput): Promise<void>',
      'connect(): Promise<Transport>',
      'configure(settings): void',
      'validate(email): boolean',
    ],
    explanation: 'EmailProvider je abstraktní s jedinou metodou kontraktu send(input). SendEmailInput má to, subject, html a volitelné text.',
  },
  '870': {
    introduction: 'Výběr provideru se děje za běhu.',
    question: 'Co aktuálně dělá EmailProvider.resolve()?',
    options: [
      'Dynamicky importuje a vrátí nový SmtpEmailProvider, takže se nodemailer nenačítá zbytečně',
      'Čte název provideru z nastavení a instancuje ho',
      'Vrátí singleton sdílený napříč requesty',
      'Vyhodí chybu, protože ve výchozím stavu není nakonfigurován žádný provider',
    ],
    explanation: 'resolve() dynamicky importuje SmtpEmailProvider a vrátí novou instanci. Dynamický import drží nodemailer mimo bundle, dokud není potřeba, a mezivrstva umožní budoucí výběr provideru.',
  },
  '871': {
    introduction: 'Transport flagy nodemaileru závisí na nastavení encryption.',
    question: 'Jak SmtpEmailProvider mapuje encryption "ssl" na možnosti transportu?',
    options: [
      'secure: true (implicitní TLS, typicky port 465)',
      'requireTLS: true (STARTTLS upgrade)',
      'ignoreTLS: true (žádné šifrování)',
      'rejectUnauthorized: false',
    ],
    explanation: 'encryption "ssl" -> secure: true (implicitní TLS, port 465). "tls" -> requireTLS: true (STARTTLS). "none" -> ignoreTLS: true. auth se nastaví jen když je vyplněný user.',
  },
  '872': {
    introduction: 'Autentizace je podmíněná.',
    question: 'Kdy SmtpEmailProvider nastaví transportní možnost „auth“?',
    options: [
      'Jen když je vyplněné pole user',
      'Vždy, i s prázdným user',
      'Jen když je encryption "ssl"',
      'Nikdy; auth se řeší jinde',
    ],
    explanation: 'Možnost auth se nastaví jen když je vyplněný SMTP user, což podporuje otevřené relaye nebo lokální MTA, které přihlašovací údaje nepotřebují.',
  },
  '873': {
    introduction: 'K environment proměnným se přistupuje přes helper.',
    question: 'Co dělá EnvHelper.require(name)?',
    options: [
      'Přečte process.env[name] a vyhodí chybu, když chybí nebo je prázdná, jinak vrátí hodnotu',
      'Vrátí undefined, když proměnná chybí',
      'Přečte hodnotu z tabulky settings',
      'Cachuje všechny env proměnné v paměti při startu',
    ],
    explanation: 'EnvHelper.require(name) vrátí process.env[name], nebo vyhodí chybu když chybí/je prázdná. betterAuthSecret() je zkratka pro require("BETTER_AUTH_SECRET").',
  },
  '874': {
    introduction: 'SMTP heslo se šifruje pomocí master secretu.',
    question: 'Jaký klíč a algoritmus šifrují SMTP heslo?',
    options: [
      'Klíč BETTER_AUTH_SECRET, přes symetrické šifrování z better-auth/crypto (encrypt/decryptWithMasterSecret)',
      'Per-user AES-256-GCM klíč odvozený z hesla',
      'RSA pár veřejného/privátního klíče',
      'Náhodný klíč uložený vedle šifrového textu',
    ],
    explanation: 'encryptWithMasterSecret/decryptWithMasterSecret používají klíč BETTER_AUTH_SECRET se symetrickým šifrováním z better-auth/crypto.',
  },
  '875': {
    introduction: 'Ve stejném souboru jsou dva páry šifrovacích helperů.',
    question: 'Co v totp-encryption.ts odlišuje encryptSecret/decryptSecret od encrypt/decryptWithMasterSecret?',
    options: [
      'encryptSecret (AES-256-GCM) je pro TOTP secrety; master-secret pár je pro SMTP heslo',
      'Jsou to identické aliasy',
      'encryptSecret je pro SMTP; master-secret pár je pro TOTP',
      'encryptSecret je asymetrický; druhý je symetrický',
    ],
    explanation: 'encryptSecret/decryptSecret (AES-256-GCM) řeší TOTP secrety. encrypt/decryptWithMasterSecret řeší SMTP heslo. Nepleť si je.',
  },
  '876': {
    introduction: 'Vstupní bod /settings dělá skoro nic.',
    question: 'Co dělá settings/page.tsx?',
    options: [
      'Je to server komponenta, která přesměruje /settings na /settings/system (s ohledem na výchozí jazyk admina)',
      'Vykreslí všechny formuláře nastavení přímo',
      'Načte každou sekci přes Promise.all',
      'Je to klientská komponenta se záložkami',
    ],
    explanation: 'settings/page.tsx je server komponenta, která jednoduše přesměruje /settings na /settings/system, s ohledem na výchozí jazyk admina. Žádná data, žádný formulář.',
  },
  '877': {
    introduction: 'Hlavní stránka nastavení nejdřív ověří oprávnění a načte data.',
    question: 'Co dělá settings/system/page.tsx jako první?',
    options: [
      'Ověří oprávnění: pokud ne PermissionService.hasPermission("settings", "view"), zavolá notFound()',
      'Načte SMTP heslo, aby ho zobrazila',
      'Přesměruje na přihlašovací stránku',
      'Vykreslí spinner načítání navždy',
    ],
    explanation: 'Stránka nejdřív ověří oprávnění settings/view a zavolá notFound(), pokud chybí, pak načte všechny sekce přes Promise.all a vykreslí formuláře.',
  },
  '878': {
    introduction: 'Stránka chrání SMTP heslo.',
    question: 'Jak settings/system/page.tsx řeší SMTP heslo před vykreslením?',
    options: [
      'Zamaskuje ho: smtpFormValues = { ...smtp, "smtp.password": "" }, takže se heslo do prohlížeče nikdy nedostane',
      'Pošle dešifrované heslo, aby bylo pole předvyplněné',
      'Pošle do formuláře šifrový text',
      'Zahashuje heslo na klientovi',
    ],
    explanation: 'Stránka přepíše smtp.password prázdným stringem před předáním hodnot do formuláře, takže se heslo do prohlížeče nikdy neposílá. Prázdné odeslání ponechá uloženou hodnotu.',
  },
  '879': {
    introduction: 'Všechny mutace v actions.ts procházejí dvěma privátními pomocníky.',
    question: 'Jaká je kanonická posloupnost uvnitř runSettingsMutation?',
    options: [
      'Ověření oprávnění -> volitelný transform -> Zod validace -> persist v try/catch, vrací TypeActionResult<null>',
      'Nejdřív persist -> pak validace -> pak ověření oprávnění',
      'Validace jen na klientovi -> persist na serveru',
      'Transform -> persist -> validace',
    ],
    explanation: 'runSettingsMutation dělá oprávnění -> (volitelný transform) -> Zod validace -> persist v try/catch, vrací TypeActionResult<null>. writeSettingsSection staví ploché serverové schéma přes ZodSchemaBuilder.build(slug).',
  },
  '880': {
    introduction: 'Některé akce procházejí service kvůli vedlejším efektům.',
    question: 'Která akce persistuje přes SmtpSettingsService.update (řeší šifrování hesla)?',
    options: [
      'updateSmtpSettings',
      'updateAuthSettings',
      'updateRestaurantSettings',
      'updateFormattingSettings',
    ],
    explanation: 'updateSmtpSettings persistuje přes SmtpSettingsService.update (šifrování hesla). updateAuthSettings používá AuthSettingsService.update (vedlejší efekty). updateLanguageSettings používá LocaleConfig.update s transformem.',
  },
  '881': {
    introduction: 'Validace běží na dvou místech.',
    question: 'Proč se validace nastavení provádí na klientovi i na serveru?',
    options: [
      'Klient používá zanořené schéma s přeloženými hláškami; server znovu validuje ploché schéma (errors.generic) a nikdy nevěří klientovi',
      'Klientská validace je jen dekorativní; záleží jen na serveru',
      'Je to chyba; validace by měla běžet jen jednou',
      'Server validuje jen e-maily, klient validuje vše ostatní',
    ],
    explanation: 'Klientská validace používá zanořené schéma s přeloženými hláškami kvůli UX; server nezávisle znovu validuje ploché schéma (hlášky se sbalí na errors.generic). Server se nikdy nespoléhá na klienta.',
  },
  '882': {
    introduction: 'Jeden generický formulář pohání každou sekci.',
    question: 'Co přijímá a dělá generická komponenta SettingsForm?',
    options: [
      'Přijímá schema, storageValues a onSubmit; staví hlášky, zanořené Zod schéma, výchozí hodnoty, seskupí pole a vykreslí SettingsField na pole',
      'Přijímá seznam HTML stringů k doslovnému vykreslení',
      'Natvrdo má samostatný JSX blok pro každou sekci',
      'Načte schéma ze serveru při mountu',
    ],
    explanation: 'SettingsForm je jeden formulář pro všechny sekce. Staví přeložené hlášky, zanořené schéma (buildNestedSchema), výchozí hodnoty (buildDefaultValues), seskupí pole a vykreslí SettingsField na každé pole.',
  },
  '883': {
    introduction: 'Odeslání převede tvary a může vyžádat potvrzení.',
    question: 'Jak SettingsForm při odeslání připraví hodnoty před voláním onSubmit?',
    options: [
      'ConfigUiHelper.buildStorageValues převede zanořený formulář zpět na plochý storage tvar, pak (volitelný potvrzovací dialog) onSubmit(saveValues)',
      'Pošle zanořený objekt přímo do server akce',
      'Nejdřív znovu načte hodnoty z databáze',
      'Celý formulář JSON.stringifyne do jednoho pole',
    ],
    explanation: 'Odeslání volá buildStorageValues pro zploštění a převod jednotek zpět, volitelně ukáže potvrzovací dialog, pak zavolá onSubmit(saveValues). Při úspěchu dělá form.reset(), router.refresh() a toast.',
  },
  '884': {
    introduction: 'Potvrzovací dialog hlídá nebezpečné změny.',
    question: 'Kdy se spustí dialog SettingsConfirmation?',
    options: [
      'Jen když hodnota přechází do „nebezpečné“ hodnoty (např. auth.totp.required false->true) a getWarning() vrátí počet > 0',
      'Při každém uložení jakékoli sekce',
      'Kdykoli se změní jakékoli číselné pole',
      'Jen když má formulář validační chyby',
    ],
    explanation: 'Potvrzení se spustí jen při přechodu do nebezpečné hodnoty (např. zapnutí vynuceného 2FA), když getWarning() vrátí počet větší než nula.',
  },
  '885': {
    introduction: 'Jedna komponenta vykreslí správný widget podle typu pole.',
    question: 'Jak SettingsField vykreslí pole „multiselect“?',
    options: [
      'Jeden Switch na každou možnost, kde hodnota je pole zachovávající pořadí možností',
      'Nativní multi-select rozbalovací seznam',
      'Čárkou oddělený textový input',
      'Skupinu checkboxů navázaných na JSON string',
    ],
    explanation: 'SettingsField je switch podle field.type. multiselect vykreslí jeden Switch na každou možnost a hodnota je pole zachovávající pořadí možností.',
  },
  '886': {
    introduction: 'Pole image nenahrávají na server.',
    question: 'Jak ImageDropzone vyrobí hodnotu pro pole „image“?',
    options: [
      'Převede vybraný soubor na base64 data URL přes FileReader a předá string přes onChange (žádné nahrávání na server), limit 512 KB',
      'Nahraje soubor na S3 a uloží URL',
      'Uloží objekt File přímo do formuláře',
      'Zkomprimuje obrázek do WebP ve worker vlákně',
    ],
    explanation: 'ImageDropzone přečte soubor jako base64 data URL přes FileReader a předá string do onChange. Žádné nahrávání na server; velikost je omezená na 512 KB a ověřuje, že jde o obrázek.',
  },
  '887': {
    introduction: 'V průchodu daty existují tři odlišné tvary dat.',
    question: 'Jaké tři tvary dat nabývá hodnota nastavení napříč systémem?',
    options: [
      'DB/storage string -> storage typed (plochý, tečkové klíče) -> form/display (zanořený, zobrazovací jednotky)',
      'JSON -> XML -> YAML',
      'Zašifrovaný -> zahashovaný -> plaintext',
      'Klient -> edge cache -> databáze',
    ],
    explanation: 'Tři tvary jsou: DB string (např. "720000"), plochý typovaný storage (např. { "auth.sessionMaxAge": 720000 }) a zanořený display form (např. { auth: { sessionMaxAge: 200 } }). ConfigUiHelper mezi nimi převádí.',
  },
  '888': {
    introduction: 'Sleduj hodnotu zápisovou cestou.',
    question: 'Uživatel zadá 200 hodin pro sessionMaxAge. Co se nakonec zapíše do sloupce value v DB?',
    options: [
      'String "720000" (200 * 3600 sekund, serializováno přes String())',
      'Číslo 200',
      'String "200"',
      'Objekt { sessionMaxAge: 200 }',
    ],
    explanation: '200 hodin * 3600 = 720000 sekund (storage tvar), pak SystemConfig.setValues serializuje přes String(720000) = "720000", upsertnuto přes Setting.setMany.',
  },
  '889': {
    introduction: 'Texty ve schématu jsou klíče, řešené z JSON souborů.',
    question: 'Kde jsou uložené skutečné přeložené texty pro i18n klíče nastavení?',
    options: [
      'V languages/admin/{cs,en}/settings.json (a chyby v errors.json), řešené přes t(...) z useTranslations',
      'Inline ve schématech jako výchozí stringy',
      'V databázové tabulce settings vedle každého klíče',
      'Natvrdo v SettingsField.tsx',
    ],
    explanation: 'label/description ve schématu jsou i18n klíče; skutečné texty žijí v languages/admin/{cs,en}/settings.json (chyby v errors.json) a řeší se přes t(...) v UI.',
  },
  '890': {
    introduction: 'Pár souhrnných faktů o kompletním inventáři stojí za zapamatování.',
    question: 'Které tvrzení o kompletním inventáři nastavení je správné?',
    options: [
      'Povinné jsou jen i18n.activeLocales a phone.defaultPrefix; smtp.password je jediné šifrované pole; seskupení se používá jen v sekci auth',
      'Každé pole je povinné a seskupení se používá ve všech sekcích',
      'visibleWhen se používá ve většině sekcí a žádné pole není šifrované',
      'Převod jednotek platí pro všechna číselná pole',
    ],
    explanation: 'Povinné: jen i18n.activeLocales a phone.defaultPrefix. Šifrované: jen smtp.password. visibleWhen: jen dvě rate-limit pole. filterByKey: jen i18n.frontend.defaultLocale. Převod jednotek: jen sessionMaxAge a lockoutSeconds. Seskupení: jen sekce auth.',
  },
  '76': {
    introduction: 'Git příkazy jsou základ verzování. Pochopení toho, co každý příkaz dělá, je klíčové pro práci s Gitem.',
    question: 'Co dělá git init?\n\n```bash\n$ git init\nInitialized empty Git repository in /project/.git/\n```',
    options: ['Naklonuje repozitář', 'Vytvoří nový Git repozitář', 'Inicializuje větev', 'Spustí git daemon'],
    explanation: 'git init vytvoří nový Git repozitář v aktuálním adresáři tím, že založí podadresář .git se všemi potřebnými soubory repozitáře.',
  },
  '77': {
    introduction: 'Git nabízí příkazy pro práci se vzdálenými repozitáři. Tohle je jeden z prvních příkazů, které se při spolupráci naučíš.',
    question: 'Co dělá git clone?\n\n```bash\n$ git clone https://github.com/user/repo.git\nCloning into \'repo\'...\n```',
    options: ['Vytvoří novou větev', 'Zkopíruje repozitář', 'Sloučí větve', 'Smaže repozitář'],
    explanation: 'git clone vytvoří lokální kopii vzdáleného repozitáře včetně všech souborů, větví a historie commitů. Zároveň nastaví sledování vzdáleného repozitáře.',
  },
  '78': {
    introduction: 'git add přesune změny z pracovního adresáře do staging area, aby mohly být zahrnuty do dalšího commitu.',
    question: 'Co dělá git add?\n\n```bash\n$ git add file.txt      # Stage specific file\n$ git add .             # Stage all changes\n```',
    options: ['Commitne změny', 'Připraví změny ke commitu (staging)', 'Pushne změny', 'Vytvoří větev'],
    explanation: 'git add připraví změny pro další commit. Přesune změny z pracovního adresáře do staging area (indexu) a připraví je k zacommitování.',
  },
  '79': {
    introduction: 'git commit -m zaznamená připravené změny jako nový commit se zprávou zadanou inline, čímž se vyhne interaktivnímu editoru.',
    question: 'Co dělá git commit -m?\n\n```bash\n$ git commit -m "Add new feature"\n[main abc1234] Add new feature\n 2 files changed, 50 insertions(+)\n```',
    options: ['Sloučí větve', 'Vytvoří commit se zprávou', 'Pushne na remote', 'Vytvoří větev'],
    explanation: 'git commit -m vytvoří nový commit s připravenými změnami a zadanou zprávou. Přepínač -m umožní napsat zprávu commitu inline.',
  },
  '80': {
    introduction: 'git push nahraje tvé lokální commity do vzdáleného repozitáře a sdílí tvou práci s ostatními.',
    question: 'Co dělá git push?\n\n```bash\n$ git push origin main\nCounting objects: 5, done.\nTo github.com:user/repo.git\n   abc1234..def5678  main -> main\n```',
    options: ['Stáhne změny', 'Nahraje lokální commity na remote', 'Vytvoří větev', 'Sloučí větve'],
    explanation: 'git push nahraje lokální commity do vzdáleného repozitáře. Aktualizuje vzdálenou větev, aby odpovídala tvé lokální větvi.',
  },
  '81': {
    introduction: 'git pull je kombinovaný příkaz, který stáhne vzdálené změny a sloučí je do tvé lokální větve.',
    question: 'Co dělá git pull?\n\n```bash\n$ git pull origin main\nremote: Counting objects: 3, done.\nFrom github.com:user/repo\n   abc1234..def5678  main -> origin/main\nUpdating abc1234..def5678\n```',
    options: ['Nahraje změny', 'Stáhne a sloučí vzdálené změny', 'Vytvoří větev', 'Smaže větev'],
    explanation: 'git pull je kombinace git fetch a git merge. Stáhne změny z remote a automaticky je sloučí do tvé aktuální větve.',
  },
  '82': {
    introduction: 'Pochopení rozdílu mezi fetch a pull ti dá kontrolu nad tím, kdy a jak se vzdálené změny integrují.',
    question: 'Jaký je rozdíl mezi git fetch a git pull?\n\n```bash\n$ git fetch origin        # Downloads, no merge\n$ git pull origin main    # Downloads AND merges\n```',
    options: ['Žádný rozdíl', 'Fetch stáhne bez sloučení, pull stáhne a sloučí', 'Pull stáhne bez sloučení', 'Fetch nahraje změny'],
    explanation: 'git fetch stáhne commity z remote, ale nesloučí je. git pull dělá obojí — stáhne a pak sloučí. Fetch je bezpečnější pro předchozí kontrolu změn.',
  },
  '83': {
    introduction: 'git merge spojí historii dvou větví a přenese změny z jedné větve do druhé.',
    question: 'Co dělá git merge?\n\n```bash\n$ git checkout main\n$ git merge feature-branch\nMerge made by the \'recursive\' strategy.\n```',
    options: ['Rozdělí větev', 'Spojí větve', 'Smaže větev', 'Vytvoří větev'],
    explanation: 'git merge spojí historie dvou větví. Vytvoří merge commit (pokud nejde o fast-forward), který má dva rodičovské commity.',
  },
  '84': {
    introduction: 'git rebase přepisuje historii commitů tím, že přesune tvé commity na nový základ a vytvoří lineární historii.',
    question: 'Co dělá git rebase?\n\n```bash\n$ git checkout feature\n$ git rebase main\nFirst, rewinding head to replay your work...\nApplying: Add feature\n```',
    options: ['Smaže commity', 'Přesune commity na nový základ', 'Sloučí větve', 'Vytvoří větev'],
    explanation: 'git rebase přesune nebo přehraje tvé commity na jiný základní commit. Přepíše historii a vytvoří lineární sled commitů.',
  },
  '85': {
    introduction: 'Volba mezi merge a rebase ovlivňuje, jak vypadá historie projektu a jak se změny integrují.',
    question: 'Jaký je hlavní rozdíl mezi merge a rebase?\n\n```bash\n# Merge: preserves history\n$ git merge feature    # Creates merge commit\n\n# Rebase: rewrites history\n$ git rebase main      # Replays commits\n```',
    options: ['Žádný rozdíl', 'Merge vytvoří merge commit, rebase přepíše historii', 'Rebase vytvoří merge commit', 'Merge přepíše historii'],
    explanation: 'Merge zachovává historii tím, že vytvoří merge commit. Rebase přepisuje historii přesunem commitů a vytváří čistší, ale pozměněnou historii. Nikdy nerebasuj veřejné větve.',
  },
  '86': {
    introduction: 'Příkaz git branch je základ pro správu větví — umožní vypsat, vytvořit nebo smazat větve.',
    question: 'Co dělá git branch bez argumentů?\n\n```bash\n$ git branch\n  feature\n* main\n  bugfix\n```',
    options: ['Vytvoří větev', 'Vypíše větve', 'Smaže větev', 'Přepne větev'],
    explanation: 'Spuštění git branch bez argumentů vypíše všechny lokální větve. Aktuální větev je označená hvězdičkou (*). Pomocí -a uvidíš i vzdálené větve.',
  },
  '87': {
    introduction: 'Git nabízí více příkazů pro vytváření a přepínání větví, přičemž novější alternativy jsou intuitivnější.',
    question: 'Jak vytvoříš novou větev a přepneš se na ni?\n\n```bash\n$ git checkout -b feature\nSwitched to a new branch \'feature\'\n\n$ git switch -c feature   # Modern alternative\nSwitched to a new branch \'feature\'\n```',
    options: ['git branch new', 'git checkout -b new', 'git switch -c new', 'Jak checkout -b, tak switch -c'],
    explanation: 'Jak "git checkout -b branch", tak "git switch -c branch" vytvoří novou větev a přepne se na ni. switch je novější a pro práci s větvemi intuitivnější.',
  },
  '88': {
    introduction: 'git stash umožní dočasně uložit nezacommitované změny, abys mohl přepnout kontext bez commitu.',
    question: 'Co dělá git stash?\n\n```bash\n$ git stash\nSaved working directory and index state WIP on main\n\n$ git stash list\nstash@{0}: WIP on main: abc1234 Last commit\n```',
    options: ['Smaže změny', 'Dočasně uloží změny', 'Commitne změny', 'Pushne změny'],
    explanation: 'git stash dočasně uloží nezacommitované změny a vrátí pracovní adresář do čistého stavu. Užitečné, když potřebuješ přepnout větev, ale nejsi připravený commitnout.',
  },
  '89': {
    introduction: 'Po stashnutí změn je můžeš obnovit přes apply nebo pop, každý s jiným chováním.',
    question: 'Jak aplikuješ stashnuté změny?\n\n```bash\n$ git stash apply   # Applies and keeps stash\n$ git stash pop     # Applies and removes stash\n```',
    options: ['Jen git stash apply', 'Jen git stash pop', 'Jak apply, tak pop', 'git stash get'],
    explanation: 'Jak apply, tak pop obnoví stashnuté změny. Rozdíl: pop po aplikaci stash odstraní, zatímco apply ho ponechá v seznamu stashů pro případné znovupoužití.',
  },
  '90': {
    introduction: 'git reset --hard je mocný, ale destruktivní příkaz, který zahodí změny a resetuje pracovní adresář.',
    question: 'Co dělá git reset --hard?\n\n```bash\n$ git reset --hard HEAD~1\nHEAD is now at abc1234 Previous commit\n# WARNING: All changes are lost!\n```',
    options: ['Soft reset', 'Zahodí všechny změny a resetuje na zadaný commit', 'Vytvoří commit', 'Sloučí větve'],
    explanation: 'git reset --hard zahodí VŠECHNY změny (staged i unstaged) a resetuje pracovní adresář, aby odpovídal zadanému commitu. Používej opatrně — změny jsou ztracené.',
  },
  '91': {
    introduction: 'git reset --soft posune HEAD, ale ponechá tvé změny ve staging, což je užitečné pro spojování nebo úpravu commitů.',
    question: 'Co dělá git reset --soft?\n\n```bash\n$ git reset --soft HEAD~1\n# HEAD moves back, but changes stay staged\n$ git status\nChanges to be committed:\n  modified: file.txt\n```',
    options: ['Zahodí všechny změny', 'Posune HEAD, ale ponechá změny ve staging', 'Vytvoří větev', 'Smaže commity'],
    explanation: 'git reset --soft posune HEAD na zadaný commit, ale ponechá všechny změny ve staging. Užitečné pro spojení více commitů do jednoho.',
  },
  '92': {
    introduction: 'git revert je bezpečný způsob, jak vrátit změny, protože vytvoří nový commit místo přepsání historie.',
    question: 'Co dělá git revert?\n\n```bash\n$ git revert abc1234\n[main def5678] Revert "Add feature"\n 1 file changed, 5 deletions(-)\n```',
    options: ['Smaže commit', 'Vytvoří nový commit, který vrátí změny', 'Resetuje na předchozí stav', 'Sloučí větve'],
    explanation: 'git revert vytvoří nový commit, který vrátí změny z konkrétního commitu. Na rozdíl od resetu nepřepisuje historii, takže je bezpečný pro sdílené větve.',
  },
  '93': {
    introduction: 'HEAD je speciální ukazatel v Gitu, který určuje, na kterém commitu právě pracuješ.',
    question: 'Co je HEAD v Gitu?\n\n```bash\n$ cat .git/HEAD\nref: refs/heads/main\n\n$ git log -1 HEAD\ncommit abc1234 (HEAD -> main)\n```',
    options: ['První commit', 'Ukazatel na aktuální commit', 'Vzdálený repozitář', 'Název větve'],
    explanation: 'HEAD je ukazatel na aktuální commit, na kterém pracuješ, obvykle míří na špičku aktuální větve. Posune se, když commitneš nebo přepneš (checkout).',
  },
  '94': {
    introduction: 'git log zobrazuje historii commitů a pomáhá ti pochopit vývoj projektu.',
    question: 'Co zobrazuje git log?\n\n```bash\n$ git log --oneline\nabc1234 (HEAD -> main) Add feature\ndef5678 Fix bug\nghi9012 Initial commit\n```',
    options: ['Staged soubory', 'Historii commitů', 'Vzdálené větve', 'Stashnuté změny'],
    explanation: 'git log zobrazuje historii commitů — hashe commitů, autory, data a zprávy. Pomocí přepínačů jako --oneline nebo --graph dostaneš různé formáty.',
  },
  '95': {
    introduction: 'git status je tvůj základní příkaz pro pochopení aktuálního stavu repozitáře.',
    question: 'Co zobrazuje git status?\n\n```bash\n$ git status\nOn branch main\nChanges to be committed:\n  modified: app.js\nUntracked files:\n  newfile.txt\n```',
    options: ['Historii commitů', 'Stav pracovního stromu', 'URL remote', 'Seznam větví'],
    explanation: 'git status zobrazuje stav pracovního adresáře a staging area. Vypíše staged, unstaged a nesledované (untracked) soubory.',
  },
  '96': {
    introduction: 'git diff ti přesně ukáže, co se změnilo, a pomáhá ti zkontrolovat úpravy před commitem.',
    question: 'Co zobrazuje git diff?\n\n```bash\n$ git diff\n-const old = "value";\n+const new = "updated";\n\n$ git diff --staged   # Staged changes\n```',
    options: ['Historii commitů', 'Změny mezi commity nebo pracovním stromem', 'Rozdíly mezi větvemi', 'Stav remote'],
    explanation: 'git diff zobrazuje rozdíly mezi různými stavy Gitu — pracovní adresář vs staging, staging vs poslední commit, nebo mezi libovolnými dvěma commity.',
  },
  '97': {
    introduction: 'Mazání větví pomáhá udržet repozitář čistý poté, co jsou funkce sloučené nebo opuštěné.',
    question: 'Jak smažeš lokální větev?\n\n```bash\n$ git branch -d feature\nDeleted branch feature (was abc1234).\n\n$ git branch -D feature   # Force delete\n```',
    options: ['git branch -d branchname', 'git delete branchname', 'git remove branchname', 'git branch --delete-remote'],
    explanation: 'Pro smazání lokální větve použij "git branch -d branchname". Pro vynucené smazání nesloučené větve použij -D (velké).',
  },
  '98': {
    introduction: 'Mazání vzdálených větví je běžný úklid po sloučení funkce. Znalost přesné syntaxe zabrání zásahu do špatného remote.',
    question: 'Jak smažeš vzdálenou větev?\n\n```bash\n$ git push origin --delete feature\nTo github.com:user/repo.git\n - [deleted]  feature\n```',
    options: ['git branch -d origin/branch', 'git push origin --delete branch', 'git delete remote branch', 'git remote delete branch'],
    explanation: 'Pro smazání vzdálené větve použij "git push origin --delete branchname". Tím se větev odstraní ze vzdáleného repozitáře.',
  },
  '99': {
    introduction: 'Merge konflikty nastanou, když Git nedokáže automaticky sladit změny mezi větvemi. Pochopení, co je spouští, je klíč k jejich sebevědomému řešení.',
    question: 'Co je Git konflikt?\n\n```bash\n$ git merge feature\nCONFLICT (content): Merge conflict in app.js\n<<<<<<< HEAD\nconst a = 1;\n=======\nconst a = 2;\n>>>>>>> feature\n```',
    options: ['Chyba v Gitu', 'Když změny v různých větvích zasáhnou stejné řádky', 'Síťová chyba', 'Problém s oprávněním'],
    explanation: 'Merge konflikt nastane, když Git nedokáže automaticky sloučit změny, protože různé větve upravily stejné řádky. Tyto konflikty musíš vyřešit ručně.',
  },
  '100': {
    introduction: 'git cherry-pick umožní aplikovat jediný commit z jedné větve do druhé, bez slučování všeho ostatního kolem.',
    question: 'Co dělá git cherry-pick?\n\n```bash\n$ git cherry-pick abc1234\n[main def5678] Add specific feature\n 1 file changed, 10 insertions(+)\n```',
    options: ['Smaže commit', 'Aplikuje konkrétní commit na aktuální větev', 'Vytvoří větev', 'Sloučí všechny commity'],
    explanation: 'git cherry-pick aplikuje změny z konkrétního commitu na tvou aktuální větev. Hodí se pro selektivní přenesení změn bez slučování celých větví.',
  },
  '101': {
    introduction: 'Konflikty v package-lock.json jsou v týmových projektech běžné. Správné řešení zajistí konzistentní závislosti.',
    question: 'Jak vyřešíš konflikty v package-lock.json?\n\n```bash\n$ git checkout --ours package-lock.json\n$ npm install\n$ git add package-lock.json\n```',
    options: ['Ručně upravit lock soubor', 'Smazat a znovu vygenerovat přes npm install', 'Vždy použít --theirs', 'Soubor ignorovat'],
    explanation: 'Nejbezpečnější způsob řešení konfliktů v package-lock.json je přijmout jednu verzi (obvykle --ours) a pak spustit npm install, který vygeneruje validní lock soubor podle package.json.',
  },
  '102': {
    introduction: 'Git nabízí přepínače pro řešení merge konfliktů volbou jedné verze nad druhou. Pojmenování může být matoucí.',
    question: 'Co znamená --ours v git checkout?\n\n```bash\n$ git checkout --ours package-lock.json\n# vs\n$ git checkout --theirs package-lock.json\n```',
    options: ['Vzdálená verze', 'Verze tvé aktuální větve', 'Základní verze', 'Nejnovější verze'],
    explanation: '--ours odkazuje na verzi z TVÉ aktuální větve (té, do které slučuješ). --theirs odkazuje na verzi z větve, kterou slučuješ. Při rebase jsou ale prohozené!',
  },
  '103': {
    introduction: 'package-lock.json je automaticky generován npm a neměl by se ručně upravovat, aby se nerozbilo řešení závislostí.',
    question: 'Proč bys nikdy neměl ručně upravovat package-lock.json?\n\n```json\n// package-lock.json has thousands of lines\n{\n  "lockfileVersion": 3,\n  "packages": { /* complex dependency tree */ }\n}\n```',
    options: ['Je read-only', 'Je automaticky generovaný a složitý', 'Nic neovlivňuje', 'npm ho odmítne'],
    explanation: 'package-lock.json je automaticky generovaný npm a obsahuje složitá data o řešení závislostí. Ruční úpravy mohou rozbít kontrolní součty a způsobit selhání instalace.',
  },
  '104': {
    introduction: 'Při řešení merge konfliktů v package-lock.json ho musíš správně znovu vygenerovat, ne ručně upravovat.',
    question: 'Jaký příkaz znovu vygeneruje package-lock.json po konfliktu?\n\n```bash\n$ git checkout --ours package-lock.json\n$ ???\n$ git add package-lock.json\n```',
    options: ['npm update', 'npm install', 'npm ci', 'npm rebuild'],
    explanation: 'npm install načte package.json a znovu vygeneruje validní package-lock.json. npm ci vyžaduje existující validní lock soubor, takže při řešení konfliktu nefunguje.',
  },
  '201': {
    introduction: 'Při práci s Gitem často potřebuješ spolupracovat s ostatními a synchronizovat kód se serverem, jako je GitHub.',
    question: 'Co je „remote“ v Gitu?',
    options: ['Lokální záloha', 'Odkaz na repozitář hostovaný jinde (např. GitHub)', 'Smazaná větev', 'Typ commitu'],
    explanation: 'Remote je odkaz na repozitář hostovaný na serveru (jako GitHub, GitLab). Umožní ti pushovat/pullovat změny mezi lokálním repozitářem a vzdáleným serverem.',
  },
  '202': {
    introduction: 'Po naklonování repozitáře Git automaticky nastaví spojení s místem, odkud jsi klonoval.',
    question: 'Na co obvykle odkazuje „origin“ v Gitu?',
    options: ['První commit vůbec', 'Výchozí název tvého vzdáleného repozitáře', 'Hlavní větev', 'Tvůj lokální repozitář'],
    explanation: 'Origin je konvenční výchozí název vzdáleného repozitáře, který se nastaví při klonování nebo přidání remote. Je to jen zkratka pro URL.',
  },
  '203': {
    introduction: 'V Gitu týmy potřebují způsob, jak pracovat na funkcích nezávisle, aniž by si navzájem zasahovaly do kódu.',
    question: 'Co je „branch“ (větev) v Gitu?',
    options: ['Kopie celého repozitáře', 'Ukazatel na konkrétní commit umožňující paralelní vývoj', 'Záloha tvého kódu', 'Typ sloučení'],
    explanation: 'Větev je lehký pohyblivý ukazatel na commit. Umožní, aby probíhalo více vývojových linií paralelně, aniž by se navzájem ovlivňovaly.',
  },
  '204': {
    introduction: 'Git sleduje změny v projektu tím, že je ukládá do diskrétních jednotek, mezi kterými lze navigovat a vracet je.',
    question: 'Co je „commit“ v Gitu?',
    options: ['Uložený soubor', 'Snímek repozitáře v konkrétním okamžiku', 'Název větve', 'Vzdálený server'],
    explanation: 'Commit je snímek všech sledovaných souborů v daném okamžiku. Každý commit má unikátní ID (SHA hash), zprávu, informace o autorovi a odkazuje na svůj rodičovský commit.',
  },
  '205': {
    introduction: 'Git potřebuje sledovat, kde se právě nacházíš v historii projektu, jak navigujš mezi commity a větvemi.',
    question: 'Na co odkazuje „HEAD“ v Gitu?',
    options: ['Na první commit', 'Ukazatel na aktuální větev/commit, na kterém jsi', 'Hlavní větev', 'Vzdálený repozitář'],
    explanation: 'HEAD je ukazatel, který odkazuje na aktuální větev (a její nejnovější commit), nebo na konkrétní commit ve stavu „detached HEAD“. Reprezentuje, kde se v historii Gitu nacházíš.',
  },
  '276': {
    introduction: 'Někdy chceš integrovat změny z jiné větve a zároveň udržet čistou, lineární historii.',
    question: 'Co znamená „rebase“ v Gitu?',
    options: ['Smazat všechny commity', 'Přesunout commity na nový základní commit a přepsat historii', 'Vytvořit zálohu', 'Sloučit dva repozitáře'],
    explanation: 'Rebasování přesune nebo zkombinuje commity na nový základní commit. Přepíše historii commitů do lineárního průběhu, na rozdíl od merge, který zachovává historii větví.',
  },
  '731': {
    introduction: 'Interaktivní rebase umožní commity upravovat, přeskupovat, slučovat (squash) nebo zahazovat.',
    question: 'Jaký je při interaktivním rebase rozdíl mezi příkazy `squash` a `fixup`?\n\n```bash\n$ git rebase -i HEAD~3\npick a1b2c3d Add feature\nsquash d4e5f6a Fix typo\nfixup  7g8h9i0 More fixes\n```',
    options: ['`squash` spojí commit a otevře editor pro sloučení zpráv; `fixup` spojí commit a jeho zprávu zahodí', '`squash` zahodí zprávu commitu; `fixup` ponechá obě zprávy', 'Jsou to identické aliasy pro stejnou operaci', '`squash` funguje jen na nejnovějším commitu; `fixup` na libovolném'],
    explanation: 'Oba sloučí commit do předchozího, ale `squash` tě vyzve ke spojení zpráv commitů, zatímco `fixup` zprávu sloučeného commitu tiše zahodí a ponechá jen zprávu rodiče.',
  },
  '732': {
    introduction: '`git commit --fixup` se přirozeně pojí s `rebase --autosquash`.',
    question: 'Vytvořil jsi commity přes `git commit --fixup=<sha>`. Který rebase příkaz je automaticky přeskupí a označí jako fixupy?\n\n```bash\n$ git commit --fixup=a1b2c3d\n$ git rebase ???\n```',
    options: ['git rebase -i --autosquash HEAD~5', 'git rebase --squash HEAD~5', 'git rebase --fixup HEAD~5', 'git rebase --auto HEAD~5'],
    explanation: '`--autosquash` (s `-i`) rozpozná commity s prefixem `fixup!` nebo `squash!` a automaticky je umístí vedle jejich cílových commitů se správnou akcí.',
  },
  '733': {
    introduction: '`git rebase --onto` umožní přesadit commity na nový základ.',
    question: 'Větev `feature` jsi odbočil z `old-base`, ale chceš přesunout jen commity unikátní pro `feature` na `main`. Který příkaz to udělá?\n\n```bash\n$ git log --oneline --graph\n* feature: C\n* feature: B\n* old-base: A\n* main: M\n```',
    options: ['git rebase --onto main old-base feature', 'git rebase --onto feature main old-base', 'git rebase main feature --onto old-base', 'git rebase old-base main feature'],
    explanation: 'Syntaxe je `git rebase --onto <newbase> <upstream> <branch>`. Přehraje commity dostupné z `feature`, ale ne z `old-base`, na `main`.',
  },
  '734': {
    introduction: 'Merge i rebase integrují změny, ale produkují různou historii.',
    question: 'Které tvrzení o merge vs rebase je správné pro sdílenou/veřejnou větev?',
    options: ['Rebasování větve, kterou ostatní stáhli, přepíše historii a donutí je obnovovat svou práci', 'Merge vždy ztrácí commity; rebase je zachovává', 'Rebase je na sdílených větvích bezpečnější než merge, protože se vyhne merge commitům', 'Merge commity nelze nikdy vytvořit s fast-forward integrací'],
    explanation: 'Zlaté pravidlo rebasování: nikdy nerebasuj větve, na kterých ostatní postavili práci, protože přepsání SHA commitů donutí spolupracovníky řešit rozcházející se historie.',
  },
  '735': {
    introduction: 'Reflog lokálně zaznamenává každou změnu HEAD.',
    question: 'Omylem jsi spustil `git reset --hard HEAD~3` a ztratil commity. Jak je obnovíš?\n\n```bash\n$ git reflog\nabc1234 HEAD@{0}: reset: moving to HEAD~3\ndef5678 HEAD@{1}: commit: Important work\n```',
    options: ['git reset --hard HEAD@{1}', 'git revert HEAD~3', 'git pull --force', 'git checkout --recover'],
    explanation: 'Reflog ukládá předchozí pozice HEAD. Reset na `HEAD@{1}` (stav před destruktivním resetem) obnoví ztracené commity.',
  },
  '736': {
    introduction: '`git stash` ukládá změny bez commitu.',
    question: 'Máš upravené sledované soubory a několik nových nesledovaných souborů, které chceš taky stashnout. Který příkaz stashne obojí?\n\n```bash\n$ git status\nmodified:   src/app.js\nUntracked: src/new.js\n```',
    options: ['git stash push --include-untracked', 'git stash push --tracked-only', 'git stash save --no-untracked', 'git stash --keep-untracked'],
    explanation: 'Ve výchozím stavu `git stash` stashne jen sledované, upravené soubory. `--include-untracked` (nebo `-u`) stashne i nové soubory. `--all` (`-a`) zahrne i ignorované.',
  },
  '737': {
    introduction: '`pop` a `apply` se liší v tom, co se stane se stash záznamem.',
    question: 'Jaký je rozdíl mezi `git stash pop` a `git stash apply`?',
    options: ['`pop` aplikuje stash a odstraní ho ze seznamu; `apply` ho aplikuje, ale ponechá na zásobníku', '`pop` obnoví jen sledované soubory; `apply` obnoví vše', '`apply` stash odstraní; `pop` ho ponechá', 'Chovají se stejně; `pop` je jen zastaralý alias'],
    explanation: '`pop` se rovná `apply` následovanému `drop` (pokud apply uspěje). `apply` je bezpečnější, když bys mohl chtít stash znovu použít jinde nebo se zotavit z konfliktu.',
  },
  '738': {
    introduction: 'Git podporuje dva druhy tagů.',
    question: 'Které tvrzení správně rozlišuje lightweight a annotated tagy?',
    options: ['Annotated tagy jsou plné objekty ukládající taggera, datum a zprávu; lightweight tagy jsou jen ref ukazující na commit', 'Lightweight tagy lze podepsat; annotated tagy ne', 'Annotated tagy jsou jen lokální; lightweight tagy se pushují automaticky', 'Lightweight tagy ukládají metadata; annotated tagy jsou jen reference'],
    explanation: 'Annotated tagy (`git tag -a`) se ukládají jako plné objekty v databázi s informacemi o taggerovi a zprávou a lze je GPG podepsat. Lightweight tagy jsou prostě pojmenovaný ukazatel na commit.',
  },
  '739': {
    introduction: '`git push` ve výchozím stavu tagy nepushuje.',
    question: 'Vytvořil jsi tag lokálně. Který příkaz pushne jen annotated tagy na remote (bez lightweight tagů)?\n\n```bash\n$ git tag -a v1.0 -m \'Release 1.0\'\n$ git push ???\n```',
    options: ['git push --follow-tags origin main', 'git push --tags origin', 'git push --all-tags origin', 'git push origin v1.0 --lightweight'],
    explanation: '`--follow-tags` pushne jen annotated tagy dostupné z pushovaných commitů. `--tags` pushne všechny tagy včetně lightweight.',
  },
  '740': {
    introduction: 'Submoduly vkládají jeden repozitář do druhého na zafixovaném commitu.',
    question: 'Po naklonování repozitáře, který obsahuje submoduly, jsou jejich adresáře prázdné. Který příkaz je naplní?\n\n```bash\n$ git clone https://example.com/repo.git\n$ ls submodule-dir/  # empty\n```',
    options: ['git submodule update --init --recursive', 'git submodule fetch --all', 'git submodule checkout', 'git clone --submodules'],
    explanation: '`git submodule update --init --recursive` inicializuje lokální konfiguraci každého submodulu a stáhne/checkoutne zafixovaný commit, rekurzivně i do vnořených submodulů. (Klonování s `--recurse-submodules` to udělá už při klonování.)',
  },
  '741': {
    introduction: '`git worktree` umožní mít více pracovních adresářů z jednoho repozitáře.',
    question: 'Potřebuješ otestovat hotfix větev bez narušení rozpracované práce na `feature`. Který příkaz vytvoří nový pracovní adresář pro `hotfix`?\n\n```bash\n$ git worktree ???\n```',
    options: ['git worktree add ../hotfix-wt hotfix', 'git worktree clone ../hotfix-wt hotfix', 'git worktree branch hotfix ../hotfix-wt', 'git worktree checkout hotfix --path ../hotfix-wt'],
    explanation: '`git worktree add <path> <branch>` vytvoří propojený pracovní strom na zadané cestě s checkoutnutou danou větví, sdílející stejnou databázi objektů `.git`.',
  },
  '742': {
    introduction: '`git bisect` provádí binární vyhledávání pro nalezení regrese.',
    question: 'Spustil jsi bisect a označil jeden commit jako good a jiný jako bad. Git checkoutnul prostřední commit a chyba tam NENÍ. Co spustíš dál?\n\n```bash\n$ git bisect start\n$ git bisect bad HEAD\n$ git bisect good v1.0\n# Bisecting: 50 revisions left\n```',
    options: ['git bisect good', 'git bisect next', 'git bisect skip', 'git bisect continue'],
    explanation: 'Aktuální checkout označíš `good` (chyba chybí), aby git zúžil hledání k prvnímu špatnému commitu. `skip` použij jen když daný commit nejde otestovat (např. nesestaví se).',
  },
  '743': {
    introduction: '`git blame` ke každému řádku připíše commit, který ho naposledy upravil.',
    question: 'Který přepínač `git blame` ignoruje změny jen v bílých znacích při určování původního commitu pro každý řádek?',
    options: ['git blame -w file.js', 'git blame --no-whitespace file.js', 'git blame --ignore-ws file.js', 'git blame --skip-blank file.js'],
    explanation: '`-w` řekne blame, aby při přiřazování ignoroval změny v bílých znacích, takže přeformátovací commity nezakryjí skutečného autora logiky.',
  },
  '744': {
    introduction: 'Přepínač `-S` (pickaxe) hledá commity, které mění výskyty řetězce.',
    question: 'Chceš najít commit, který do codebase přidal nebo z ní odebral funkci `parseConfig`. Které volání `git log` to udělá?',
    options: ['git log -S\'parseConfig\'', 'git log --grep=\'parseConfig\'', 'git log --search=\'parseConfig\'', 'git log --contains=\'parseConfig\''],
    explanation: '`-S<string>` (pickaxe) najde commity, kde se změnil počet výskytů `<string>`. `--grep` hledá ve zprávách commitů, ne v diffech.',
  },
  '745': {
    introduction: '`git log` podporuje mnoho kombinací filtrů.',
    question: 'Který příkaz zobrazí commity od autora „alice“ se zprávami zmiňujícími „fix“ od 1. ledna 2025?',
    options: ['git log --author=alice --grep=fix --since=2025-01-01', 'git log --user=alice --message=fix --after=2025-01-01', 'git log --by=alice --search=fix --from=2025-01-01', 'git log --committer=alice --contains=fix --date=2025-01-01'],
    explanation: '`--author` porovnává pole autora, `--grep` filtruje podle zprávy commitu a `--since` (alias `--after`) omezuje podle data. Ve výchozím stavu jsou kombinovány AND, kromě vzorů `--grep`, které se OR.',
  },
  '746': {
    introduction: '`git diff` má několik rozsahů.',
    question: 'Připravil jsi (staged) nějaké změny a udělal další úpravy. Který příkaz zobrazí jen změny, které jsi připravil (mezi indexem a HEAD)?',
    options: ['git diff --cached', 'git diff', 'git diff HEAD', 'git diff --unstaged'],
    explanation: '`git diff --cached` (nebo `--staged`) zobrazí index vs HEAD. Samotný `git diff` zobrazí pracovní strom vs index (unstaged) a `git diff HEAD` pracovní strom vs HEAD (staged + unstaged).',
  },
  '747': {
    introduction: '`git reset` posouvá HEAD se třemi možnými efekty na index a pracovní strom.',
    question: 'Chceš vrátit poslední commit, ale ponechat všechny jeho změny ve staging (v indexu). Který příkaz použiješ?\n\n```bash\n$ git log --oneline\nabc1234 (HEAD) Bad commit\ndef5678 Previous commit\n```',
    options: ['git reset --soft HEAD~1', 'git reset --mixed HEAD~1', 'git reset --hard HEAD~1', 'git revert HEAD'],
    explanation: '`--soft` posune HEAD, ale ponechá index a pracovní strom beze změny, takže změny commitu zůstanou ve staging. `--mixed` (výchozí) je z indexu odebere; `--hard` je zahodí.',
  },
  '748': {
    introduction: 'Moderní Git rozdělil `checkout` na `switch` a `restore`.',
    question: 'Který příkaz zahodí nestagované změny v `file.js` v pracovním stromě a obnoví ho do stavu odpovídajícího indexu?\n\n```bash\n$ git restore ???\n```',
    options: ['git restore file.js', 'git restore --staged file.js', 'git restore --source=HEAD --staged file.js', 'git checkout HEAD -- file.js'],
    explanation: '`git restore <file>` má výchozí `--worktree` a obnoví pracovní strom z indexu (zahodí nestagované změny). `--staged` by odebral ze staging obnovou indexu z HEAD.',
  },
  '749': {
    introduction: '`git pull` je `fetch` plus integrace.',
    question: 'Chceš aktualizovat aktuální větev tím, že stáhneš z origin a rebasuješ své lokální commity na špičku remote (místo vytvoření merge commitu). Který příkaz to udělá?',
    options: ['git pull --rebase', 'git fetch --rebase', 'git pull --merge', 'git pull --no-ff'],
    explanation: '`git pull --rebase` stáhne remote a rebasuje lokální commity na staženou špičku. Můžeš to nastavit jako výchozí přes `pull.rebase=true`.',
  },
  '750': {
    introduction: 'Force-push je někdy nutný po přepsání historie.',
    question: 'Proč je `git push --force-with-lease` bezpečnější než `git push --force`?',
    options: ['Odmítne přepsat vzdálený ref, pokud od tvého posledního fetche někdo pushnul nové commity', 'Šifruje obsah pushe během přenosu', 'Automaticky sloučí vzdálené změny místo přepsání', 'Před přepsáním vytvoří na serveru zálohovací tag'],
    explanation: '`--force-with-lease` ověří, že vzdálený ref stále odpovídá tomu, co jsi naposledy fetchnul. Pokud kolega mezitím pushnul, push se odmítne a zabrání se náhodné ztrátě jeho práce.',
  },
  '751': {
    introduction: 'Remote-tracking větve mohou zastarat, když se vzdálené větve smažou.',
    question: 'Který příkaz odstraní lokální remote-tracking reference pro větve, které na `origin` už neexistují?',
    options: ['git fetch --prune origin', 'git remote clean origin', 'git branch --remote --delete-stale', 'git gc --prune-remotes'],
    explanation: '`git fetch --prune` (nebo `git remote prune origin`) smaže záznamy `refs/remotes/origin/*` pro větve smazané na upstreamu. Nastav `fetch.prune=true` pro automatické provádění.',
  },
  '752': {
    introduction: 'Git hooky spouští skripty v konkrétních bodech git workflow.',
    question: 'Který hook se spustí lokálně před vytvořením commitu, umožní commit zrušit (např. pro linting), a kde standardně leží?',
    options: ['pre-commit, v .git/hooks/pre-commit', 'pre-push, v .git/hooks/pre-push', 'commit-msg, v .githooks/commit-msg', 'prepare-commit, v .git/config'],
    explanation: 'Hook `pre-commit` běží před vyžádáním zprávy commitu. Nenulový návratový kód commit zruší. Standardně leží v `.git/hooks/` (nebo kde ukazuje `core.hooksPath`).',
  },
  '753': {
    introduction: 'Mělké (shallow) klony zmenšují velikost stahování zkrácením historie.',
    question: 'Který příkaz naklonuje jen nejnovější commit větve `main` a vynechá starší historii?',
    options: ['git clone --depth 1 --branch main https://example.com/repo.git', 'git clone --shallow main https://example.com/repo.git', 'git clone --no-history https://example.com/repo.git', 'git clone --recent 1 https://example.com/repo.git'],
    explanation: '`--depth 1` vytvoří mělký klon jen se špičkovým commitem. V kombinaci s `--branch main` (nebo `--single-branch`) minimalizuje přenos dat, což se hodí pro CI buildy.',
  },
  '754': {
    introduction: 'Sparse-checkout umožní naplnit jen podmnožinu pracovního stromu.',
    question: 'Která sekvence zapne cone-mode sparse-checkout, aby se naplnil jen adresář `apps/web`?',
    options: ['git sparse-checkout init --cone && git sparse-checkout set apps/web', 'git sparse-checkout enable --path apps/web', 'git config core.sparseCheckout apps/web', 'git checkout --sparse apps/web'],
    explanation: '`sparse-checkout init --cone` zapne optimalizované cone-mode porovnávání vzorů, pak `set apps/web` naplní jen tento adresář (a potřebné kořenové soubory). Moderní git používá `git sparse-checkout set --cone` přímo.',
  },
  '755': {
    introduction: 'Checkout konkrétního commitu (ne větve) tě dostane do stavu detached HEAD.',
    question: 'Jsi v detached HEAD na commitu `abc1234` a udělal jsi experimentální commity. Který příkaz spustíš, abys je zachoval jako větev, než se vrátíš na `main`?\n\n```bash\n$ git status\nHEAD detached at abc1234\n```',
    options: ['git switch -c experiment', 'git checkout main --save', 'git stash --branch experiment', 'git branch HEAD experiment'],
    explanation: '`git switch -c experiment` (nebo `git checkout -b experiment`) vytvoří novou větev na aktuálním detached HEAD a zachová experimentální commity, než je opustíš jako nedosažitelné.',
  },
  '1009': {
    introduction: 'Otázka na řádový odhad. Vyber nejbližší odpověď.',
    question: 'Kolik dat zhruba přenese typické domácí připojení 100 Mb/s za 1 sekundu?',
    options: ['~1 MB', '~12 MB', '~100 MB', '~1 GB'],
    explanation: '100 Mb/s = 100 megabitů za sekundu ≈ 12,5 megabajtu za sekundu (dělíme 8). Číslo v nabídce tvého ISP je v bitech, velikosti souborů jsou v bajtech — častý chyták při plánování velikosti HTTP přenosů.',
  },
};
