// React roadmap questions — set B (100). A second question per level theme,
// distinct from set A. Combined with set A this gives 8 questions per level so
// each 5-level checkpoint has a full 40-question test. 25 levels × 4.

import type { Seed } from './roadmap-build';

export const reactSeedsB: Seed[] = [
  // ── Level 1 — JSX Basics ───────────────────────────────────────────────
  { q: 'What does this render?\n\n```jsx\n<p>{["a", "b"]}</p>;\n```', opts: ['"a,b"', '"ab"', '["a", "b"]', 'an error'], a: 1, e: 'React renders an array child by rendering each item in order, so the two strings become adjacent text nodes and the paragraph reads ab. Converting the array to a string would give a,b, but React never does that: it treats the array as a list of children, which is also why arrays of elements need keys.', intro: 'An array in braces is not converted to a string first. Think about what React does with each item in turn.', tags: ['JSX'] },
  { q: 'What does this render?\n\n```jsx\n<p>{true}</p>;\n```', opts: ['"true"', 'nothing', '1', 'an error'], a: 1, e: 'React ignores boolean, null and undefined children, so {true} produces no output and the p stays empty. It is not converted to the text true (only strings and numbers become text) and it is not an error; this rule is what makes the condition && <Element /> pattern work.', intro: 'Ask which kinds of values React turns into text and which it silently skips; true belongs to one of those groups.', tags: ['JSX'] },
  { q: 'What does this render?\n\n```jsx\n<p>{null}</p>;\n```', opts: ['"null"', 'nothing', 'null', 'an error'], a: 1, e: 'null, undefined and booleans are skipped as children, so {null} renders nothing and the p stays empty. React does not stringify it into the text null, and embedding or returning null is not an error; components commonly return null to render nothing at all.', intro: 'Compare null with a string: React converts only some kinds of children into visible text.', tags: ['JSX'] },
  { q: 'This JSX does not compile. What is wrong?\n\n```jsx\n<img src="a.png">\n```', opts: ['The tag must be closed', 'img cannot be used in JSX', 'src must be written in braces', 'The tag name must be capitalised'], a: 0, e: 'JSX requires every element to be closed, so a void element such as img must be written <img src="a.png" /> (or with an explicit closing tag); leaving it open is a syntax error in the JSX compiler. img is an ordinary lowercase DOM tag and string attributes use quotes, so the other options are not the problem.', intro: 'A browser\'s HTML parser forgives shortcuts that the JSX compiler does not. Think about what a strict, XML-like syntax expects from every tag.', tags: ['JSX'] },

  // ── Level 2 — Components ───────────────────────────────────────────────
  { q: 'Is this a valid component?\n\n```jsx\nconst App = () => <p>Hi</p>;\n```', opts: ['Yes; any function that returns JSX can be a component', 'No; components must use the function keyword', 'No; components must be classes', 'No; the JSX must be inside an explicit return statement'], a: 0, e: 'A component is a function that takes props and returns JSX (or null); an arrow function with a concise body returns <p>Hi</p> implicitly, so App is a valid function component. The function keyword and classes are not required (classes are legacy), and an explicit return is needed only when the arrow body uses braces.', intro: 'An arrow function with no braces returns its expression. Ask what React requires from a component beyond that.', tags: ['Components'] },
  { q: 'What renders in React 19?\n\n```jsx\nfunction App() {\n  <p>Hi</p>;\n}\n```', opts: ['<p>Hi</p>', 'Nothing', 'An error about a missing return', 'The text Hi'], a: 1, e: 'Without a return statement App returns undefined, and since React 18 a component may return undefined, which renders nothing (React 17 threw an error here). The <p>Hi</p> line is evaluated and discarded because nothing returns it. The fix is return <p>Hi</p>; a missing return is a common cause of a silently blank component.', intro: 'The JSX on line 2 is an expression statement. Check whether anything actually leaves the function.', tags: ['Components'] },
  { q: 'Writing <Welcome /> tells React to:', opts: ['create an element that React renders by calling Welcome', 'call Welcome immediately and insert its return value', 'register Welcome as a custom HTML tag', 'copy the JSX from Welcome into App at build time'], a: 0, e: '<Welcome /> compiles to jsx(Welcome, {}), which returns a lightweight element object describing what to render; React calls Welcome itself during rendering so it can manage its state and hooks. Calling Welcome() directly would run it as a plain function outside React\'s control, and only lowercase tags are treated as HTML tags; nothing is inlined at build time.', intro: 'JSX compiles to a createElement call. Ask what that call returns, and whether Welcome has run at that point.', tags: ['Components'] },
  { q: 'Header and Main are components defined elsewhere. What renders?\n\n```jsx\nfunction App() {\n  return (\n    <div>\n      <Header />\n      <Main />\n    </div>\n  );\n}\n```', opts: ['a div containing the output of Header and then Main', 'the div only; nested components are ignored', 'the output of Header and Main with no div', 'an error, because a component can return only one component'], a: 0, e: 'App returns a div element with two component children; React renders Header and Main and places their output inside the div, in order. Nested components are not ignored, the wrapping div is real DOM, and a component may contain any number of child components as long as it returns a single root node.', intro: 'Treat each capitalised tag as a placeholder for what that component returns, then read the tree from the outside in.', tags: ['Components'] },

  // ── Level 3 — Props ────────────────────────────────────────────────────
  { q: 'What value is passed to the p element as its child before React renders it?\n\n```jsx\nfunction B({ a, b }) {\n  return <p>{a + b}</p>;\n}\n<B a={2} b={3} />;\n```', opts: ['The number 5', 'The string "23"', 'The string "5"', 'A TypeError'], a: 0, e: 'a={2} and b={3} pass numbers (braces keep the JavaScript type), so a + b is the number 5, which is what the p receives; React converts it to text only when it renders. "23" would need string props such as a="2" b="3", where + concatenates, and adding two numbers never throws.', intro: 'Check what kind of values the braces in a={2} and b={3} pass, then apply the normal JavaScript + rule.', tags: ['Props'] },
  { q: 'In React, props are:', opts: ['mutable by the component', 'read-only', 'always optional', 'global'], a: 1, e: 'Props are owned by the parent: a component receives them as a read-only snapshot and must not modify them, because React expects components to be pure and will replace the props on the next render anyway. When a value needs to change, the parent passes new props or the child keeps its own state. Props can be required or optional and are passed explicitly, never shared globally.', intro: 'Think about who owns a prop\'s value and what React does with it when that owner re-renders.', tags: ['Props'] },
  { q: 'What is the value of disabled?\n\n```jsx\n<Btn label="Save" disabled />;\n```', opts: ['"disabled"', 'true', 'false', 'undefined'], a: 1, e: 'JSX treats a bare attribute as boolean shorthand: disabled compiles to disabled: true, so Btn receives the boolean true, not the string "disabled". Omitting the prop entirely would give undefined, and false must be passed explicitly as disabled={false}.', intro: 'A prop written with no value is not left empty. Recall the value JSX assigns in that case, as with a checked or disabled attribute in HTML.', tags: ['Props'] },
  { q: 'What does spreading props do?\n\n```jsx\n<Input {...props} />;\n```', opts: ['passes each property of props as a separate prop', 'passes the whole object as one prop named props', 'passes only the props that Input declares', 'passes the object as children'], a: 0, e: 'JSX builds a props object, and {...props} spreads every own property of props into it, so <Input {...props} /> is the same as writing each attribute by hand. Nothing is filtered by what Input expects, the object is not wrapped as a single prop, and children come only from content nested between the tags or an explicit children prop.', intro: 'The braces contain object spread. Think about what spread does inside an object literal, then apply it to the props object JSX builds.', tags: ['Props', 'Spread'] },

  // ── Level 4 — Rendering Lists ──────────────────────────────────────────
  { q: 'What is rendered?\n\n```jsx\n{[1, 2, 3].map(n => <li key={n}>{n * n}</li>)}\n```', opts: ['1, 2, 3', '1, 4, 9', '3 empty items', 'an error'], a: 1, e: 'map calls the arrow function once per element with n = 1, 2, 3 and each li renders n * n, so the items show 1, 4, 9. The key uses n, which is unique here, so there is no warning, and the items are not empty because the expression inside each li produces a number.', intro: 'Each callback call receives one number as n. Evaluate n * n for each before deciding what the three items show.', tags: ['Lists', 'map'] },
  { q: 'A list key should be:', opts: ['stable across renders and unique among its siblings', 'unique across the whole application', 'the array index in every case', 'a new random value on every render'], a: 0, e: 'React uses keys to match list items between renders, so a key must stay the same for the same item and must not repeat among its siblings; ids from your data are typical. Keys need not be globally unique, only within one list. Index keys break when items are inserted, removed or reordered, and random keys change every render, forcing React to recreate every item and lose its state.', intro: 'Keys exist so React can match a rendered item with the same item on the next render. Ask what property a key needs to make that match reliable.', tags: ['Lists', 'key'] },
  { q: 'Which is the best key here?\n\n```jsx\n{users.map(u => <Row key={???} name={u.name} />)}\n```', opts: ['the array index', 'u.id', 'u.name', 'Math.random()'], a: 1, e: 'u.id is stable and unique per user, so React can keep each Row matched to the same user when the list changes. The array index shifts when items are inserted, removed or reordered, which can attach state to the wrong row; u.name may repeat or change; and Math.random() changes every render, so React recreates every Row and discards its state.', intro: 'Imagine a user being removed from the middle of the list or renamed. Pick the value that still identifies the same row afterwards.', tags: ['Lists', 'key'] },
  { q: 'What renders?\n\n```jsx\nconst listItems = [<li key="1">A</li>, <li key="2">B</li>];\n<ul>{listItems}</ul>;\n```', opts: ['only the first', 'both list items', 'nothing', 'an error'], a: 1, e: 'React accepts an array of elements as a child and renders every entry in order, so both li elements appear inside the ul. The elements already carry unique keys, so there is no warning; storing JSX in a variable or array before rendering is ordinary practice and not an error.', intro: 'An array of elements can be placed in braces just like the result of map. Consider how React treats each entry.', tags: ['Lists'] },

  // ── Level 5 — Conditional Rendering ────────────────────────────────────
  { q: 'When error is truthy, what renders?\n\n```jsx\n{error ? <Err /> : <Ok />}\n```', opts: ['<Ok />', '<Err />', 'both', 'nothing'], a: 1, e: 'A truthy condition renders the first branch, <Err />.', tags: ['Conditional'] },
  { q: 'When items is [], what renders?\n\n```jsx\n{items.length === 0 ? <Empty /> : <List />}\n```', opts: ['<List />', '<Empty />', 'nothing', 'an error'], a: 1, e: 'An empty array has length 0, so items.length === 0 is true and the ternary renders its first branch, <Empty />. <List /> is the false branch, a ternary always produces one of its two branches so nothing is not possible here, and reading length on [] is safe. This is the standard empty-state pattern.', intro: 'Start with the comparison: what is the length of an empty array, and what does === 0 give for it?', tags: ['Conditional'] },
  { q: 'When isLoading is false, what renders?\n\n```jsx\n{isLoading && <Spinner />}\n```', opts: ['<Spinner />', 'nothing', '"false"', 'an error'], a: 1, e: 'A false left-hand side makes && render nothing.', tags: ['Conditional', 'Short-circuit'] },
  { q: 'When user is null, what renders?\n\n```jsx\n{user ? `Hi ${user.name}` : "Guest"}\n```', opts: ['"Hi undefined"', '"Guest"', 'an error', 'nothing'], a: 1, e: 'null is falsy, so the ternary takes the second branch and renders "Guest"; the template literal in the first branch is never evaluated, so user.name is not read and no TypeError occurs. "Hi undefined" would need the first branch to run with a user lacking a name, and a ternary always renders one of its branches.', intro: 'The condition is checked before user.name is ever touched. Decide which branch runs when user is null.', tags: ['Conditional'] },

  // ── Level 6 — useState: Basics ─────────────────────────────────────────
  { q: 'What is the initial value of v?\n\n```jsx\nconst [v, setV] = useState(() => 5);\n```', opts: ['a function', '5', 'undefined', '0'], a: 1, e: 'When useState receives a function, React calls it once during the first render and uses its return value as the initial state, so v is 5; the function itself is not stored. This lazy initializer form is useful when computing the initial value is expensive, because the function is not re-run on later renders.', intro: 'useState treats a function argument differently from other values. Think about whether React stores the function or what it returns.', tags: ['useState'] },
  { q: 'Calling useState several times in one component is:', opts: ['allowed; each call keeps its own independent value', 'allowed only if every call stores the same type', 'allowed only inside a custom hook', 'not allowed; a component can hold one state value'], a: 0, e: 'A component may call useState as many times as it needs; React tracks each call by its position in the sequence of hook calls, so each holds its own value and setter, for example separate name and age states. There is no type restriction and no need for a custom hook. The only rule is that hooks are called unconditionally at the top level so the order stays the same on every render.', intro: 'Think about how React identifies each useState call: by the order of calls within the component, not by a name.', tags: ['useState'] },
  { q: 'What is a?\n\n```jsx\nconst [a] = useState([]);\n```', opts: ['undefined', 'an empty array', 'null', 'useState'], a: 1, e: 'The initial state is the empty array passed in.', tags: ['useState'] },
  { q: 'What does the handler log the first time the button is clicked?\n\n```jsx\nfunction Counter() {\n  const [v, setV] = useState(0);\n  function handleClick() {\n    setV(10);\n    console.log(v);\n  }\n  return <button onClick={handleClick}>Go</button>;\n}\n```', opts: ['0', '10', 'undefined', 'It throws an error'], a: 0, e: 'setV(10) asks React to re-render Counter with the new value; it does not change the v variable in the current closure, so console.log(v) prints the value from this render, 0. On the next click v is 10, because Counter has run again and useState returned the updated state. Updating state inside an event handler is normal and never throws; an unconditional setter call in the component body is what loops and throws.', intro: 'Ask when v can get a new value: at the moment setV is called, or only when Counter runs again.', tags: ['useState'] },

  // ── Level 7 — Event Handling ───────────────────────────────────────────
  { q: 'When is handle called?\n\n```jsx\n<button onClick={handle}>Go</button>;\n```', opts: ['On every render of the component', 'When the user clicks the button', 'Never, because it is not called with ()', 'Once, right after the component mounts'], a: 1, e: 'onClick={handle} hands React the function itself, and React calls it when the click happens; nothing runs during render because handle is never invoked there. Writing onClick={handle()} would call it on every render instead. It is not skipped for lacking parentheses: a function reference is exactly what an event prop expects.', intro: 'handle is written without parentheses. Decide whether React is being handed a function to call later or the result of calling it now.', tags: ['Events'] },
  { q: 'Which form runs during render (a bug)?', opts: ['onClick={() => doIt()}', 'onClick={doIt()}', 'onClick={doIt}', 'onClick={() => doIt}'], a: 1, e: 'onClick={doIt()} calls doIt while the component renders and hands React its return value (usually undefined) as the handler, so the click does nothing and the work repeats on every render. onClick={doIt} passes the function itself, and onClick={() => doIt()} passes a new function that calls doIt only when the click happens; both defer the call correctly. onClick={() => doIt} defers it too far: it returns doIt instead of calling it, so the click does nothing.', intro: 'Parentheses call a function at the point where they appear. For each option, ask whether doIt is called while the JSX is being built or later, on the click.', tags: ['Events', 'Gotchas'] },
  { q: 'In React, when does onChange on a text input fire?', opts: ['Once, after the input loses focus (blur)', 'Every time the value changes, on each keystroke', 'Only when the surrounding form is submitted', 'Only when the value is set programmatically'], a: 1, e: 'In React, onChange fires immediately whenever the user changes the value, so for a text input that means every keystroke; that is what lets a controlled input re-render with each character. The native DOM change event fires only when the field loses focus, which is where the blur misconception comes from. Submit is a separate event on the form, and programmatic value changes do not fire onChange at all.', intro: 'React\'s onChange is not the browser\'s change event. Think about what a controlled input needs in order to show each character as it is typed.', tags: ['Events', 'Forms'] },
  { q: 'What does the onSubmit handler receive?\n\n```jsx\n<form onSubmit={handleSubmit}>\n```', opts: ['Nothing; it is called with no arguments', 'The submit event object', 'An object with the form\'s field values', 'A boolean saying whether the form is valid'], a: 1, e: 'Like every React event handler, handleSubmit is called with the event object: a submit event whose target is the form and on which you usually call e.preventDefault() to stop the full-page reload. The form values are not passed in; you read them from state or from new FormData(e.target). Only the React 19 action={fn} prop is called with FormData instead of an event.', intro: 'Think about what every React event handler is given as its first argument, whether it is onClick, onChange or onSubmit.', tags: ['Events', 'Forms'] },

  // ── Level 8 — Updating State ───────────────────────────────────────────
  { q: 'What does this update do to the items state?\n\n```jsx\nsetItems(items => [...items, newItem]);\n```', opts: ['Pushes newItem onto the existing array in place', 'Stores a new array with newItem added at the end', 'Replaces the array with an array containing only newItem', 'Throws, because state arrays cannot be spread'], a: 1, e: 'The spread copies the current items into a brand-new array and adds newItem after them; the old array is untouched, so React sees a new reference and re-renders. The updater form appends to the latest queued value rather than to a possibly stale closure. push would mutate the array in place and hand React the same reference, which is the bug this pattern avoids.', intro: 'Look at what the updater returns: is it the same array it received, or something built from it?', tags: ['useState', 'Arrays'] },
  { q: 'Called 3 times from 0, where does count end?\n\n```jsx\nsetCount(c => c + 1);\nsetCount(c => c + 1);\nsetCount(c => c + 1);\n```', opts: ['1', '2', '3', '0'], a: 2, e: 'Functional updates chain off the latest value: 0 → 1 → 2 → 3.', tags: ['useState'] },
  { q: 'What is user after this?\n\n```jsx\n// user was { name: "A", age: 1 }\nsetUser({ name: "B" });\n```', opts: ['{ name: "B", age: 1 }', '{ name: "B" }', '{ age: 1 }', 'an error'], a: 1, e: 'A useState setter replaces the entire state value with what you pass, so user becomes { name: "B" } and age is gone. Merging only happens with this.setState in class components, which is where the { name: "B", age: 1 } expectation comes from; to keep age you would write setUser({ ...user, name: "B" }). Nothing here throws.', intro: 'Ask whether a useState setter merges the new object into the old one or swaps the whole value.', tags: ['useState', 'Objects'] },
  { q: 'Inside an event handler, what happens when you call a state setter such as setCount(1)?', opts: ['count changes immediately, so the next line of the handler already sees 1', 'React queues the update and re-renders once after the handler, batching other setter calls', 'React re-renders synchronously at that line, before the rest of the handler runs', 'React waits for the browser to be idle and may drop the update if it is busy'], a: 1, e: 'Calling a setter does not change the variable in the running handler; it tells React what the next render should use. React waits until the handler has finished, then applies all queued updates in one re-render (batching), so three setter calls cost one render. It is not synchronous at the call site, and updates are never dropped; the only way to force an immediate re-render is flushSync, which is rare.', intro: 'Think about what count holds on the very next line after setCount(1), and how many re-renders happen if one handler calls three setters.', tags: ['useState'] },

  // ── Level 9 — State with Objects/Arrays ────────────────────────────────
  { q: 'What does this update do to the list state?\n\n```jsx\nsetList(list.map(x => (x.id === id ? { ...x, done: !x.done } : x)));\n```', opts: ['Flips done on the matching item by mutating it in place', 'Builds a new array in which only the matching item is replaced by a toggled copy', 'Removes the matching item and keeps the rest', 'Flips done on every item in the list'], a: 1, e: 'map always returns a new array. For the element whose id matches, the callback returns a fresh copy with done inverted; every other element is returned as the same object, so the new array holds one toggled copy plus the unchanged items. Nothing is mutated, nothing is removed, and only the matching item changes.', intro: 'Follow one element through the callback: what comes back when its id matches, and what comes back when it does not?', tags: ['useState', 'Arrays'] },
  { q: 'What does this produce?\n\n```jsx\nsetObj({ ...obj, count: obj.count + 1 });\n```', opts: ['mutates obj', 'a new object with count incremented', 'removes count', 'an error'], a: 1, e: 'Spreading then overriding count yields a new object with count + 1.', tags: ['useState', 'Objects'] },
  { q: 'Why must a state update create a new object instead of changing the one already in state?', opts: ['Copying makes each update faster for React to process', 'React compares the new value with Object.is and skips the render when it is the same object', 'React throws an error if you assign to a property of a state object', 'The copy is what makes the update apply synchronously'], a: 1, e: 'useState compares the next value with the current one using Object.is. Mutating the stored object and passing it back gives React the same reference, so it bails out and the screen keeps the old markup; a fresh object is a different reference, so React re-renders. Speed is not the reason — copying costs a little — and React never throws when you mutate state, which is what makes this bug easy to miss.', intro: 'Ask what React can notice when the setter hands back the very same object it stored last time.', tags: ['useState', 'Immutability'] },
  { q: 'What does this leave in state?\n\n```jsx\nsetArr([...arr.slice(0, i), ...arr.slice(i + 1)]);\n```', opts: ['A new array with the item at index i removed', 'A new array with the item at index i duplicated', 'The same array with the item at index i set to undefined', 'A new array holding only the items after index i'], a: 0, e: 'slice(0, i) takes everything before i and slice(i + 1) everything after it, so spreading both into one array skips index i. The result is a new array and arr itself is untouched, which is what a state update needs. Nothing is duplicated, and slice(i + 1) on its own would also drop the earlier items.', intro: 'Write out the index ranges each slice covers for a four-item array, then compare them with the original.', tags: ['useState', 'Arrays'] },

  // ── Level 10 — Derived State ───────────────────────────────────────────
  { q: 'A component holds a list and a search query in state and shows the matching rows. Where should the filtered rows come from?', opts: ['A third piece of state, updated wherever the list or the query changes', 'An expression evaluated during render from the list and the query', 'A ref that is rewritten whenever the query changes', 'An effect that filters after each render and stores the result in state'], a: 1, e: 'Filtering during render rebuilds the rows whenever the list or the query changes, so they cannot disagree with their source. A third state — set directly or from an effect — duplicates data that has to be re-synced at every change, and the effect version commits one render with the stale rows before the update lands. A ref does not trigger a render at all, so the list on screen would not update.', intro: 'The rows are fully determined by two values the component already holds. Ask what a stored copy would have to be kept in step with.', tags: ['Derived state'] },
  { q: 'How should you think about total?\n\n```jsx\nconst total = items.reduce((s, i) => s + i.price, 0);\n```', opts: ['A value recomputed from items on every render', 'A piece of state that must be updated whenever items changes', 'A value that only becomes correct after the next effect runs', 'A cached value React reuses until something invalidates it'], a: 0, e: 'The component body runs on every render, so total is rebuilt from the current items each time and cannot fall behind them. Holding it in state would mean updating it everywhere items changes, and no effect is involved — the value is already correct by the time the render is committed. React does not cache a plain const between renders either; useMemo is what does that, and only as an optimization.', intro: 'The line sits in the component body. Ask how often that body runs and what total is built from each time.', tags: ['Derived state'] },
  { q: 'What is isValid?\n\n```jsx\nconst isValid = name.length > 0 && email.includes("@");\n```', opts: ['state', 'a derived boolean from the inputs', 'a side effect', 'an error'], a: 1, e: 'It is computed from existing values, so it should be derived, not stored.', tags: ['Derived state'] },
  { q: 'What is true of this line in a component body?\n\n```jsx\nconst sorted = [...items].sort((a, b) => a - b);\n```', opts: ['It sorts items in place, so React sees no change', 'It sorts a copy, and rebuilds that copy on every render', 'It sorts a copy once and reuses it on later renders', 'It has to be moved into an effect, because sort mutates'], a: 1, e: 'The spread creates a new array, so .sort() reorders the copy and items keeps its order — sorting items directly would mutate state React still holds and the re-render could be skipped. The copy is rebuilt on every render, which is fine for small lists and worth wrapping in useMemo once the list is large enough to notice. Sorting is a pure computation, so nothing here belongs in an effect.', intro: 'The spread runs before .sort() does. Then ask how often a line in the component body runs.', tags: ['Derived state'] },

  // ── Level 11 — useEffect: Basics ───────────────────────────────────────
  { q: 'When does this run?\n\n```jsx\nuseEffect(() => {\n  console.log("hi");\n}, []);\n```', opts: ['every render', 'once after mount', 'before render', 'never'], a: 1, e: 'An empty dependency array runs the effect once after the first render.', tags: ['useEffect'] },
  { q: 'When does an effect run, relative to the render that scheduled it?', opts: ['While React is calling the component function', 'After React has applied that render to the DOM', 'Before React applies the render, so the effect can cancel it', 'After the first render only, never after updates'], a: 1, e: 'React calls the component function to work out the markup, commits it to the DOM, and only then runs the effects — which is why an effect can measure or subscribe to the node that render produced. During render that node is not in the DOM yet, and React gives the effect no way to cancel a render that is already committed. Effects also run after updates, not just the first render, unless the dependency array rules them out.', intro: 'Ask whether the effect can read the DOM node the component just returned.', tags: ['useEffect'] },
  { q: 'roomId changes but serverUrl stays the same. What does React do?\n\n```jsx\nuseEffect(connect, [serverUrl, roomId]);\n```', opts: ['Re-runs the effect, because one listed value changed', 'Skips the effect, because serverUrl is unchanged', 'Re-runs the effect only once both values have changed', 'Re-runs the effect on every render, whatever the array holds'], a: 0, e: 'React compares the array entry by entry against the previous commit and re-runs the effect if any entry differs, so a changed roomId is enough on its own. Waiting for both would leave the component connected to the old room. The array is also what prevents the every-render behavior you get when it is omitted.', intro: 'React checks the entries one at a time. Ask how many of them have to differ before it re-runs.', tags: ['useEffect'] },
  { q: 'Returning a function from useEffect:', opts: ['registers a cleanup', 'runs the effect twice', 'is ignored', 'is an error'], a: 0, e: 'The returned function is the effect’s cleanup.', tags: ['useEffect', 'Cleanup'] },

  // ── Level 12 — Effect Dependencies ─────────────────────────────────────
  { q: 'An empty dependency array means the effect:', opts: ['runs every render', 'runs once and not again on updates', 'never runs', 'runs only on unmount'], a: 1, e: '[] means run on mount only; it does not re-run on later renders.', tags: ['useEffect', 'Dependencies'] },
  { q: 'What does this effect do as the component re-renders?\n\n```jsx\nfunction Panel({ id }) {\n  const load = () => fetch(`/api/${id}`);\n  useEffect(() => { load(); }, [load]);\n}\n```', opts: ['It runs after every render, because load is a new function each time', 'It runs only when id changes, because load closes over id', 'It runs once, because the function body is identical on every render', 'It never runs, because a function is not a valid dependency'], a: 0, e: 'Every render creates a new function object, and Object.is treats two distinct functions as different even when their source is identical, so the dependency looks changed on every render — a fetch per render here. Wrapping load in useCallback with [id] keeps its identity stable between renders, or move the function inside the effect and depend on id instead.', intro: 'load is created again each time the component body runs. Ask how two separately created functions compare.', tags: ['useEffect', 'Dependencies'] },
  { q: 'Which values does the exhaustive-deps lint rule expect in an effect\'s dependency array?', opts: ['Props, state, and any value computed from them in the component body', 'Only the state variables the effect reads', 'Only the props the component receives', 'Only values that arrive from outside React, such as a fetch result'], a: 0, e: 'React calls props, state and anything derived from them in the component body "reactive": they can differ between renders, so the effect has to list them to stay in step. Listing only props or only state leaves the other kind stale. Values that cannot change between renders — a module-level constant, or the setter returned by useState — do not need to be listed.', intro: 'The rule is about values that can differ from one render to the next. Ask which of those the effect body reads.', tags: ['useEffect', 'Dependencies'] },
  { q: 'Omitting a dependency that changes leads to:', opts: ['fresh values', 'stale values inside the effect', 'an infinite loop', 'a syntax error'], a: 1, e: 'The effect closes over outdated values when a real dependency is missing.', tags: ['useEffect', 'Dependencies'] },

  // ── Level 13 — Cleanup Functions ───────────────────────────────────────
  { q: 'An effect subscribes to a data source when it runs. What should the effect function return?', opts: ['the data', 'an unsubscribe function', 'a promise', 'nothing'], a: 1, e: 'React accepts exactly one return value from an effect: a cleanup function. It calls that function before the effect runs again and once at unmount, so returning the unsubscribe closes the subscription. Returning the data or nothing leaves the subscription alive after the component is gone, and returning a promise (what an async effect function gives you) makes React warn: \'useEffect must not return anything besides a function, which is used for clean-up.\'', intro: 'React does exactly one thing with whatever an effect returns. Work out what that one thing is before deciding what to hand back.', tags: ['useEffect', 'Cleanup'] },
  { q: 'When does cleanup run?', opts: ['only on mount, before the effect body runs', 'before the next effect run and on unmount', 'only on unmount, after the last effect run', 'on every render, whether or not deps changed'], a: 1, e: 'React calls the cleanup returned by an effect before it runs that effect again, and once more when the component unmounts, so a subscription or timer is never doubled up or left dangling. \'Only on unmount\' is the usual misreading: it would leave the previous run active every time a dependency changes. In development Strict Mode React also runs setup, cleanup, setup once on mount to expose effects that cannot be run twice.', intro: 'A dependency change makes this effect run a second time with new values. Ask what the first run left behind, and when that gets dealt with.', tags: ['useEffect', 'Cleanup'] },
  { q: 'An effect calls setInterval and returns no cleanup. After the component unmounts, what happens?', opts: ['nothing - React clears timers for you at unmount', 'the callback keeps firing after the component unmounts', 'the interval stops after its first tick', 'React throws a warning and stops the interval'], a: 1, e: 'The interval id lives in the browser, not in React, and cleanup is the only place it gets cleared - so without clearInterval the callback keeps running, holding the old closure and its state alive and doing work for a component nobody can see. React never clears timers for you; it only calls the function your effect returns. Return () => clearInterval(id) and the timer stops the moment the component goes away.', intro: 'Ask which part of the system is keeping track of the interval, and whether React unmounting a component says anything to it.', tags: ['useEffect', 'Cleanup'] },
  { q: 'When deps are [id] and id changes, React:', opts: ['skips the cleanup and starts the new effect right away', 'runs the cleanup for the old id, then the effect for the new id', 'runs the effect for the new id, then the cleanup for the old id', 'waits until unmount to run the cleanup for the old id'], a: 1, e: 'When a dependency changes React tears down the previous run before starting the next one: cleanup for the old id, then the effect for the new id. The reverse order would leave two subscriptions live at the same moment, and skipping cleanup would leak the old one for the lifetime of the component. Measured order across an id change and an unmount: subscribe:1, unsubscribe:1, subscribe:2, unsubscribe:2.', intro: 'When id changes there is work to do for the old id and work to do for the new one. Ask which of the two React does first.', tags: ['useEffect', 'Cleanup'] },

  // ── Level 14 — useRef ──────────────────────────────────────────────────
  { q: 'A useRef value:', opts: ['triggers a re-render when changed', 'persists across renders without causing re-renders', 'resets each render', 'is the same as state'], a: 1, e: 'Refs hold a mutable value that survives renders but does not trigger them.', tags: ['useRef'] },
  { q: 'Inside an event handler you write ref.current = 5. That update is:', opts: ['asynchronous - the new value appears on the next render', 'synchronous - the value changes at once and no render is scheduled', 'batched with state updates and applied at the end of the event', 'ignored unless it happens inside an effect'], a: 1, e: 'ref.current = 5 is an ordinary property assignment, so the new value is readable on the very next line, and because React is never told about it no render is scheduled. State setters are the opposite: they are queued and batched, and the state variable you already hold keeps its old value until the next render. Nothing about a ref write is asynchronous, batched, or restricted to effects - only reading and writing during render is discouraged.', intro: 'Compare it with calling a state setter in the same handler: which of the two does React have to schedule?', tags: ['useRef'] },
  { q: 'What is a ref to a DOM node normally used for?', opts: ['re-rendering a component from outside React', 'calling a DOM method such as input.focus() imperatively', 'holding derived state that the rendered output depends on', 'passing a value to a child without going through props'], a: 1, e: 'React sets ref.current to the DOM node once it is on the screen, so a ref is how you reach browser APIs that JSX cannot express: focus(), scrollIntoView(), measuring a node, play() on a video. Moving focus deliberately after opening a dialog or failing validation is part of keyboard accessibility, which is why this is the common case. Derived state should be computed during render instead, and passing values down is what props and context are for.', intro: 'Some things the browser owns cannot be expressed as JSX output. Ask which of those you would need the actual node for.', tags: ['useRef', 'DOM'] },
  { q: 'value is a prop. During a render, what does prev.current hold?\n\n```jsx\nconst prev = useRef();\nuseEffect(() => { prev.current = value; });\n```', opts: ['the value from the current render', 'the value from the previous render', 'undefined on every render', 'every past value, as an array'], a: 1, e: 'The effect has no dependency array, so it runs after every render - but it runs after the render is committed, so while a render is in progress prev.current still holds what was written at the end of the previous one. On the very first render it is undefined, because nothing has been assigned yet. Only one value is kept: each run overwrites the last, so there is no history.', intro: 'The effect body runs after React has committed this render. Ask when the assignment happens relative to the read.', tags: ['useRef'] },

  // ── Level 15 — Forms & Inputs ──────────────────────────────────────────
  { q: 'A controlled input keeps its value in:', opts: ['the DOM only', 'React state', 'a ref only', 'localStorage'], a: 1, e: 'Controlled inputs are driven by React state via value + onChange.', tags: ['Forms'] },
  { q: 'What kind of select is this?\n\n```jsx\n<select value={v} onChange={onChange}>\n  <option value="a">A</option>\n  <option value="b">B</option>\n</select>\n```', opts: ['uncontrolled - the DOM decides which option is selected', 'controlled - React state decides which option is selected', 'read-only - a select cannot be driven by React state', 'invalid - the selection must be set with selected on an option'], a: 1, e: 'value on the <select> plus onChange makes React the owner of the selection, the same contract as a controlled text input. React deliberately differs from plain HTML here: you set the selection with value (or defaultValue) on the select, not with selected on an option - do that and React warns \'Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.\' Drop the value prop and the select becomes uncontrolled, with the DOM keeping the selection.', intro: 'Compare this with a plain HTML select, where the browser tracks the selection on its own. Ask what the extra props change here.', tags: ['Forms'] },
  { q: 'You have ten controlled inputs in one form. The usual way to hold their values is:', opts: ['one state variable shared by the whole application', 'one state object keyed by each input\'s name attribute', 'no state at all - read the DOM when the form is submitted', 'a separate ref for each input, written in onChange'], a: 1, e: 'One object in state plus one handler scales: setValues(v => ({ ...v, [e.target.name]: e.target.value })) uses the input\'s name as the key, so a new field costs one line of JSX and no new state. Ten separate state variables and ten handlers do the same job with ten times the code. Reading the DOM at submit time is the uncontrolled approach - valid, but a different design from the controlled inputs the question assumes - and refs give up re-rendering on each keystroke, so validation-as-you-type stops working.', intro: 'Picture adding an eleventh input next week. Ask how much of the existing code each of these four approaches would make you touch.', tags: ['Forms'] },
  { q: 'e.preventDefault() in onSubmit:', opts: ['submits twice', 'stops the default page reload', 'clears the form', 'focuses an input'], a: 1, e: 'It prevents the browser’s default form submission (full-page reload).', tags: ['Forms'] },

  // ── Level 16 — Lifting State Up ────────────────────────────────────────
  { q: 'Two siblings need the same value. You should:', opts: ['duplicate it in each', 'lift it to their common parent', 'use a ref', 'use a global variable'], a: 1, e: 'Lift shared state up to the closest common parent and pass it down.', tags: ['Lifting state'] },
  { q: 'A parent passes value and onChange to a child that renders an input. The child is:', opts: ['the owner of the value, since it renders the input', 'controlled by the parent, which owns the value', 'uncontrolled, because it never calls useState itself', 'unable to change the value at all'], a: 1, e: 'A component is controlled when both the value it shows and the way that value changes come from above: the parent holds the state, passes value down, and receives requests through onChange. Rendering the input does not make the child the owner. Nor does the absence of useState make it uncontrolled - uncontrolled means the DOM keeps the value, and here React does.', intro: 'Two different questions hide here: who holds the value, and whether React or the DOM is the source of truth. Answer both before choosing.', tags: ['Lifting state'] },
  { q: 'After lifting state, the child updates it by:', opts: ['calling setState directly', 'calling the callback prop from the parent', 'mutating props', 'using a ref'], a: 1, e: 'The child invokes the parent-provided callback to request a state change.', tags: ['Lifting state'] },
  { q: 'Lifting state too far up tends to cause:', opts: ['faster renders, because fewer components hold state', 'props threaded through components that never use them', 'state that resets whenever an intermediate child unmounts', 'duplicate state, because each child keeps its own copy'], a: 1, e: 'State placed higher than it needs to be has to be handed down through every component in between, none of which care about it - that is prop drilling. It also widens the re-render: a change at the top re-renders the whole subtree, so \'faster renders\' is backwards. The two usual fixes are to lower the state to the closest component that actually needs it, or to keep it high and reach consumers with context instead of props.', intro: 'Nothing here breaks and nothing resets. Ask what over-lifting costs you instead: in code you have to write, and in what re-renders.', tags: ['Lifting state'] },

  // ── Level 17 — useMemo ─────────────────────────────────────────────────
  { q: 'What does this do?\n\n```jsx\nconst r = useMemo(() => compute(a), [a]);\n```', opts: ['runs compute every render', 'caches compute(a) until a changes', 'never runs', 'is asynchronous'], a: 1, e: 'useMemo recomputes only when a dependency changes; otherwise it reuses the cached value.', tags: ['useMemo'] },
  { q: 'useMemo is intended for:', opts: ['running side effects after the component renders', 'caching expensive results and keeping references stable', 'subscribing to an external store and cleaning up afterwards', 'storing a value that must survive renders without causing one'], a: 1, e: 'useMemo runs during render and caches a value: either a computation too expensive to repeat, or an object or array whose identity must stay stable so a memo child or another hook\'s dependency list does not see a change. Side effects and subscriptions belong to useEffect, which runs after the commit and can clean up. A value that must survive renders without causing one is a ref. Treat useMemo as an optimization - React may discard the cache.', intro: 'Each wrong option is another hook\'s job. Ask which of these kinds of work happens during render.', tags: ['useMemo'] },
  { q: 'Omitting a dependency the computation uses gives you:', opts: ['an always-fresh value, because React tracks what the calculation reads', 'a stale value, kept until a listed dependency changes', 'an infinite render loop the next time state changes', 'a runtime warning from React on the next render'], a: 1, e: 'useMemo re-runs only when an entry in the dependency list changes, so a value the calculation reads but the list omits can change with the cache none the wiser, and the component renders a result computed from old inputs. React does not track reads and says nothing at runtime; only the exhaustive-deps ESLint rule catches it, which is why it pays to spot by eye. It cannot loop either: unlike an effect, a memo calculation never schedules an update.', intro: 'React compares only what is in the list. Ask what happens to a value the list never mentions.', tags: ['useMemo'] },
  { q: 'obj is passed to a memo-wrapped child. What does useMemo keep stable here?\n\n```jsx\nconst obj = useMemo(() => ({ id }), [id]);\n```', opts: ['nothing - an object literal is rebuilt on every render', 'the object\'s identity, until id changes', 'the value of id, which can no longer change', 'the child\'s props, even when id changes'], a: 1, e: 'Without the memo every render would build a new { id }, and a new object is never === the previous one, so a memo child or a dependency list would see a changed value each time. useMemo returns the same object until id changes, which is what lets the child skip re-rendering; when id does change you get a new object, as you should. It does not freeze id, and react.dev warns React may discard the cache, so treat the stability as an optimization, not a guarantee.', intro: 'Two object literals with identical contents are still different objects. Ask what that costs the child.', tags: ['useMemo'] },

  // ── Level 18 — useCallback ─────────────────────────────────────────────
  { q: 'What does useCallback return?', opts: ['the function’s result', 'a memoized callback stable until deps change', 'undefined', 'a new function each render'], a: 1, e: 'It returns a cached function that stays the same reference until a dependency changes.', tags: ['useCallback'] },
  { q: 'The main reason to use useCallback is to:', opts: ['make the function body itself run faster', 'keep the same function reference between renders', 'run side effects after the component renders', 'create state the component can update'], a: 1, e: 'useCallback does nothing to how fast the function body runs; it only keeps the same function object across renders. That matters to whoever compares it: a memo child re-renders when a prop changes by identity, and an effect re-runs when a function in its dependency list is new. With no such consumer the wrapper is pure overhead - the arrow is still created on every render, and React then compares dependencies on top of that.', intro: 'The function does exactly the same work either way. Ask what changes for the components and hooks that receive it.', tags: ['useCallback'] },
  { q: 'Passing a memoized callback to a React.memo child:', opts: ['forces the child to re-render on every parent render', 'lets the child skip re-rendering while its other props are unchanged', 'has no effect, because memo compares props deeply', 'makes memo compare the function\'s body instead of its identity'], a: 1, e: 'memo skips a re-render when every prop is === what it was last time. Functions are objects, so an inline arrow is a new prop on every parent render and defeats memo completely, while a useCallback hands over the same function and leaves the child to re-render only when something else really changed. Measured: with a useCallback prop the memo child rendered once across two parent updates; with an inline arrow it rendered three times. The comparison is shallow and by identity - never deep, and never of the function\'s body.', intro: 'memo compares this render\'s props against the last ones. Ask how two inline arrows would compare.', tags: ['useCallback', 'Performance'] },
  { q: 'A useCallback with empty deps that reads state:', opts: ['always sees current state', 'captures the initial state (stale)', 'errors', 're-renders'], a: 1, e: 'Empty deps freeze the closure on the first render’s state.', tags: ['useCallback', 'Gotchas'] },

  // ── Level 19 — useReducer ──────────────────────────────────────────────
  { q: 'What does dispatch({ type: "reset" }) do?', opts: ['reads state', 'sends an action; the reducer returns the next state', 're-renders only', 'is an error'], a: 1, e: 'dispatch passes the action to the reducer, which computes the next state.', tags: ['useReducer'] },
  { q: 'A reducer’s signature is:', opts: ['(action) => state', '(state, action) => newState', '() => state', '(state) => action'], a: 1, e: 'A reducer is a pure function of the current state and the action: (state, action) => newState - the same shape as the callback given to Array.prototype.reduce, which is where the name comes from. Without the state it could not build the next value; without the action it could not know what happened. It returns state and never an action, and it must not mutate the state it receives - return a new object or value instead.', intro: 'The same shape turns up in Array.prototype.reduce and in Redux. Recall what those callbacks are given and what they return.', tags: ['useReducer'] },
  { q: 'useReducer returns:', opts: ['[state, setState]', '[state, dispatch]', '[dispatch]', '{ state, dispatch }'], a: 1, e: 'useReducer returns a two-element array: the current state and a dispatch function you call with an action. [state, setState] is useState\'s shape, and the difference matters: with a reducer you never hand React the next state directly, you describe what happened and the reducer computes it. Because it is an array you destructure by position, so { state, dispatch } would not work.', intro: 'You never compute the next state at the call site here: you send an action and let the reducer decide. What does the hook hand you to send it with?', tags: ['useReducer'] },
  { q: 'What must a reducer function do?', opts: ['Return the next state, computed only from its arguments', 'Update the existing state object and return nothing', 'Await the server response before returning the new state', 'Call the hooks it needs to read the latest values'], a: 0, e: 'React calls the reducer with the current state and an action and expects the next state back, derived only from those two arguments. It may call it more than once for the same action: in Strict Mode React runs the reducer twice in development to expose impurity, so fetching, mutating or reading the clock inside it gives different results each run. Mutating the old state and returning it is the most common version of the mistake, and React then sees the same object, decides nothing changed and skips the re-render.', intro: 'React may run this function twice for the same action while you develop. What has to be true of it for both runs to agree?', tags: ['useReducer'] },

  // ── Level 20 — useContext ──────────────────────────────────────────────
  { q: 'What does useContext(MyContext) return?', opts: ['a [value, setValue] pair for that context', 'the nearest Provider\'s value, or the createContext default', 'a ref object that tracks the Provider\'s value', 'undefined until a Provider mounts above the component'], a: 1, e: 'useContext reads: React walks up from the component to the nearest matching Provider and returns its value, falling back to the argument given to createContext when there is no Provider above. It never returns a setter or a ref, because changing the value is the Provider\'s job, usually state in the component that renders it. Reading also subscribes the component, so it re-renders whenever that value changes.', intro: 'It gives you read access only. Decide which value it reads when the component happens to sit outside every Provider.', tags: ['useContext'] },
  { q: 'What happens when the value passed to a Provider changes?', opts: ['Every component reading that context re-renders', 'Only the Provider itself re-renders, not its children', 'Only children that take the value as a prop re-render', 'Nothing changes until a consumer reads the context again'], a: 0, e: 'Reading a context subscribes the component, so when the Provider\'s value changes every consumer below re-renders, including one wrapped in React.memo, because the update arrives through the context rather than through props. A component that reads nothing from the context gets no update from the context itself, though it still re-renders if its own parent does. This is also why passing a fresh object literal as the value re-renders all consumers on every parent render, and why that value is worth memoizing when the tree is large.', intro: 'Some components between the Provider and a consumer never read this context. Decide whether React has any reason to update those.', tags: ['useContext'] },
  { q: 'Context is best suited for:', opts: ['Theme, locale and the current user', 'The text of a single form input', 'A value that changes on every animation frame', 'A DOM node you need to focus'], a: 0, e: 'Context fits data that a large part of the tree reads and that changes rarely: theme, locale, the signed-in user. Because every consumer re-renders on each value change, a value that moves on every keystroke or animation frame turns one small edit into a tree-wide render. A single input\'s text belongs in the component that owns it, and a DOM node is what a ref is for.', intro: 'Every consumer re-renders when the value changes. Weigh each option by how much of the app reads it and how often it changes.', tags: ['useContext'] },
  { q: 'With no Provider, a consumer gets:', opts: ['undefined', 'the createContext default value', 'an error', 'null always'], a: 1, e: 'Without a Provider, useContext returns the default passed to createContext.', tags: ['useContext'] },

  // ── Level 21 — Custom Hooks ────────────────────────────────────────────
  { q: 'A custom hook’s name must:', opts: ['start with "use"', 'be capitalized', 'return JSX', 'be a class'], a: 0, e: 'Hooks must be named use* so the linter and React can enforce the rules of hooks.', tags: ['Custom hooks'] },
  { q: 'What does a useWindowWidth() hook that returns a number do for the components that call it?', opts: ['Packages stateful logic that many components can reuse', 'Renders the current width into the page', 'Creates a context so callers share one value', 'Turns the component that calls it into a hook'], a: 0, e: 'A custom hook exists to lift stateful logic out of a component so others can call it: useWindowWidth owns the resize listener and the state and returns just the number. It renders nothing itself, which is what separates a hook from a component, and it sets up no context: each caller runs its own copy of the logic and holds its own state. What is shared is the code, not the value.', intro: 'It returns a number and renders nothing. Ask whether calling it twice would give you one value or two.', tags: ['Custom hooks'] },
  { q: 'Two components each call useCounter(). What do they share?', opts: ['The logic; each keeps its own count', 'One count value, kept in sync between them', 'Nothing at all, since hooks are per component', 'The count, unless one of them resets it'], a: 0, e: 'Calling a custom hook runs its body inside the calling component, so each component gets its own useState cell: the code is shared, the state is not. Expecting the opposite is a common source of counters that will not stay in sync. When you do want one shared value, lift it into a common parent or a Provider and let the hook read it from there.', intro: 'Think about what happens the second time useState runs, inside a different component.', tags: ['Custom hooks'] },
  { q: 'Which hooks may a custom hook call?', opts: ['Any hook, including other custom hooks', 'Only useState and useEffect', 'Any hook, but only inside a conditional', 'No hooks; it is a plain helper'], a: 0, e: 'A custom hook may call any hook, built-in or another custom hook, and composing them is the whole point. The restriction is on placement, not on the list: every call must sit at the top level of the hook, never inside a condition, loop or early return, so the calls run in the same order on every render. A function that calls no hooks at all is just a helper.', intro: 'A custom hook follows the same rules as a component. Ask whether those rules limit which hooks you may call, or where you may call them.', tags: ['Custom hooks'] },

  // ── Level 22 — Keys & Reconciliation ───────────────────────────────────
  { q: 'React uses keys to:', opts: ['style elements', 'match elements between renders', 'sort lists', 'nothing'], a: 1, e: 'Keys identify which items changed, were added, or removed across renders.', tags: ['Keys'] },
  { q: 'Using Math.random() as a key:', opts: ['Unmounts and remounts every item on each render', 'Guarantees uniqueness, which is what keys need', 'Only matters once the list is re-sorted', 'Triggers a duplicate key warning in development'], a: 0, e: 'Random keys are unique, but uniqueness is only half of the job: a key must also be the same value on the next render. Every render produces new keys, so React matches none of them to the previous list, unmounts every row and mounts a replacement. Typed text, focus, scroll position and any per-row state are lost each time, and the DOM work becomes the worst case rather than the best.', intro: 'The value is different on every render. Ask what React concludes when none of the new keys matches any of the old ones.', tags: ['Keys', 'Gotchas'] },
  { q: 'Stable keys preserve:', opts: ['nothing', 'component state and DOM across reorders', 'only styles', 'random data'], a: 1, e: 'With stable keys, React keeps each item’s state and DOM even when the list reorders.', tags: ['Keys', 'Reconciliation'] },
  { q: 'What happens when two siblings in a list share the same key?', opts: ['React warns and can update the wrong sibling', 'React falls back to the array index for those items', 'React appends a suffix to make the keys unique', 'Nothing, as long as the keys are unique across the app'], a: 0, e: 'Keys have to be unique only among siblings, but within one list they must be. When two share a key React cannot tell them apart: it warns in development, "Encountered two children with the same key", and on the next update it can carry state or a DOM node over to the wrong sibling, or duplicate and omit children. React does not repair the keys for you, and uniqueness across the whole app was never required.', intro: 'Two siblings are claiming the same identity. Ask how React decides which one to update when only one of them changed.', tags: ['Keys'] },

  // ── Level 23 — Performance Patterns ────────────────────────────────────
  { q: 'React.memo(Comp) re-renders only when:', opts: ['its state changes', 'its props change (shallow compare)', 'always', 'never'], a: 1, e: 'memo skips re-render unless the props shallowly differ.', tags: ['Performance', 'memo'] },
  { q: 'Wrapping every component in memo:', opts: ['always makes it faster', 'can add overhead without real benefit', 'is required', 'removes all re-renders'], a: 1, e: 'Memoization has its own cost; apply it where it actually helps.', tags: ['Performance'] },
  { q: 'To keep a callback stable for a memoized child, use:', opts: ['useState', 'useCallback', 'useRef', 'useEffect'], a: 1, e: 'useCallback caches the function and returns the identical object until a dependency changes, so the memoized child sees the same onClick prop and skips its re-render. useEffect returns nothing you could pass down, and useState hands back a setter that is stable but is not the handler you wrote. A ref can hold a function, but it has no dependency array, so the closure it stores goes stale as soon as the values it captured change. Without useCallback the inline handler is a new object each render and memo compares it as changed.', intro: 'The handler is a fresh function object on every render. Which hook is built to hand the same function back until its dependencies change?', tags: ['Performance', 'useCallback'] },
  { q: 'The React DevTools Profiler helps you:', opts: ['See which components re-rendered and how long they took', 'See which network requests each component made', 'See the final HTML that React produced', 'Step through your component code line by line'], a: 0, e: 'The Profiler records a commit and shows which components re-rendered and how long each took, so you can confirm a suspicion instead of guessing. That is the step before reaching for memo: without it you optimize components that were never the problem and pay the comparison cost for nothing. Network requests belong to the browser\'s Network panel, the produced DOM to its Elements panel, and stepping line by line to the debugger.', intro: 'The Profiler records what happened during a commit. Ask which of these facts only exists inside React\'s own render cycle.', tags: ['Performance'] },

  // ── Level 24 — Common Pitfalls ─────────────────────────────────────────
  { q: 'Calling a hook inside a loop or condition:', opts: ['is fine', 'breaks the Rules of Hooks', 'is faster', 'needs a key'], a: 1, e: 'Hooks must be called in the same order every render — never conditionally.', tags: ['Pitfalls', 'Rules of hooks'] },
  { q: 'What happens when you mutate state in place, as in state.x = 1?', opts: ['The data changes but the screen may not update', 'React notices the write and re-renders', 'React throws, because state objects are frozen', 'The next render replays the mutation'], a: 0, e: 'React compares the previous state with the next one using Object.is. Mutating in place leaves both pointing at the same object, so the comparison reports no change and React skips the render even though the data did change, which is why the screen goes stale rather than crashing. Build a new object or array instead, {...state, x: 1}, which is also what lets memo and effect dependencies notice the change.', intro: 'The write succeeds: the object really does hold the new value. Ask what React has to compare to decide it should render again.', tags: ['Pitfalls', 'Immutability'] },
  { q: 'Why is this a problem?\n\n```jsx\nuseEffect(async () => {\n  await load();\n}, []);\n```', opts: ['it is fine', 'effect callbacks must not be async — define an inner async function', 'it needs deps', 'always errors'], a: 1, e: 'An async function returns a promise, but an effect must return undefined or a cleanup.', tags: ['Pitfalls', 'useEffect'] },
  { q: 'Calling setState unconditionally during render:', opts: ['renders once', 'causes an infinite render loop', 'does nothing', 'is caught automatically'], a: 1, e: 'Each render schedules another, looping forever.', tags: ['Pitfalls'] },

  // ── Level 25 — Mixed Mastery ───────────────────────────────────────────
  { q: 'How does results stay up to date?\n\n```jsx\nfunction Search({ items }) {\n  const [q, setQ] = useState("");\n  const results = items.filter(i => i.includes(q));\n\n  return (\n    <>\n      <input value={q} onChange={e => setQ(e.target.value)} />\n      <ul>{results.map(r => <li key={r}>{r}</li>)}</ul>\n    </>\n  );\n}\n```', opts: ['It is recomputed on every render from q and items', 'It is stored in state and refreshed by an effect', 'It updates when items changes but not when q does', 'It updates when the user submits the search form'], a: 0, e: 'results is a plain value computed while the component renders, so each keystroke updates q, the component re-renders, and the filter runs again against the current query. Keeping it in state instead would need an effect, a second render for every keystroke, and there would be a moment where the list disagrees with the input. Derive what you can from what you already have, and store only what you cannot compute.', intro: 'results is an ordinary const in the component body. Ask what happens to it the next time the component renders.', tags: ['Mastery'] },
  { q: 'What does this implement?\n\n```jsx\nuseEffect(() => {\n  const t = setTimeout(cb, 500);\n  return () => clearTimeout(t);\n}, [cb]);\n```', opts: ['Calls cb 500ms after the last change to cb', 'Calls cb immediately and again every 500ms', 'Calls cb 500ms after mount and never again', 'Calls cb on every render, 500ms behind'], a: 0, e: 'Whenever cb changes, React runs the cleanup first, cancelling the timeout that was still pending, and then schedules a new one, so cb only ever runs once cb has stopped changing for 500ms: that is a debounce. With an empty dependency array the same code would fire once, 500ms after mount, and never restart. The cleanup is also what keeps it safe on unmount, since a cancelled timeout cannot call into a component that is gone.', intro: 'The dependency array lists cb, and the effect returns a function. Ask what React does with both when cb changes.', tags: ['Mastery'] },
  { q: 'What is this?\n\n```jsx\nfunction useToggle() {\n  const [on, set] = useState(false);\n  return [on, () => set(o => !o)];\n}\n```', opts: ['a component', 'a reusable boolean-toggle custom hook', 'a context', 'invalid'], a: 1, e: 'It packages toggle state and logic into a reusable hook.', tags: ['Mastery'] },
  { q: 'When does value recompute?\n\n```jsx\nconst value = useMemo(() => expensive(a, b), [a, b]);\n```', opts: ['When a or b changes between renders', 'On every render, since the arrow is recreated', 'Only on the first render, then never again', 'Whenever any state in the component changes'], a: 0, e: 'useMemo keeps the value alongside the dependency array and compares each entry with Object.is on the next render; when they all match it hands back the stored value and never calls expensive. The inline arrow really is created on every render, but React does not call it unless a dependency changed. The trap is a dependency that is itself a new object or array each render, since it always compares as different and the memo then costs more than it saves.', intro: 'The arrow really is a new function on every render. Ask whether React calling it is the same thing as creating it.', tags: ['Mastery'] },
];
