import type { QuestionTranslation } from './quiz-data';

export const rulesTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Šachovnice ──────────────────────────────────────────
  'rm-rules-1': { introduction: 'Vzpomeň si na rozměry standardní šachovnice.', question: 'Kolik polí je na standardní šachovnici?', options: ['32', '48', '64', '100'], explanation: 'Šachovnice je mřížka 8×8, což je 8 krát 8, tedy 64 polí.' },
  'rm-rules-2': { introduction: 'Šachovnice je čtvercová mřížka.', question: 'Šachovnice je mřížka kolika řad krát kolik sloupců?', options: ['8 krát 8', '6 krát 6', '10 krát 10', '9 krát 9'], explanation: 'Šachovnice má 8 řad a 8 sloupců, což dává celkem 64 polí.' },
  'rm-rules-3': { introduction: 'Zaměř se na dvě barvy polí.', question: 'Jaké dvě barvy mají pole na šachovnici?', options: ['Červená a černá', 'Světlá a tmavá', 'Modrá a žlutá', 'Všechna jedné barvy'], explanation: 'Pole se pravidelně střídají mezi světlou a tmavou barvou po celé šachovnici.' },
  'rm-rules-4': { introduction: 'Přemýšlej o vzoru polí.', question: 'Střídají se pole na šachovnici v barvě?', options: ['Ne, jsou náhodná', 'Ano, střídají se', 'Jen na okrajích', 'Jen ve středu'], explanation: 'Světlá a tmavá pole se střídají tak, aby dvě pole stejné barvy nesousedila.' },
  'rm-rules-5': { introduction: 'Spočítej figury jednoho hráče.', question: 'S kolika figurami začíná každý hráč hru?', options: ['12', '16', '20', '8'], explanation: 'Každá strana začíná s 16 figurami: 8 pěšci a 8 dalšími figurami.' },
  'rm-rules-6': { introduction: 'Sečti figury obou hráčů.', question: 'Kolik figur je celkem na šachovnici na začátku hry?', options: ['24', '16', '32', '64'], explanation: 'Oba hráči dohromady začínají s 32 figurami, 16 každý.' },
  'rm-rules-7': { introduction: 'Jaký geometrický tvar má šachovnice?', question: 'Jaký tvar má šachovnice?', options: ['Kruh', 'Čtverec', 'Trojúhelník', 'Šestiúhelník'], explanation: 'Šachovnice je čtverec s 8 poli podél každé strany.' },
  'rm-rules-8': { introduction: 'Kolik stran hraje partii?', question: 'Kolik barev figur je v šachové partii?', options: ['Dvě', 'Tři', 'Čtyři', 'Jedna'], explanation: 'Jeden hráč ovládá bílé figury a druhý ovládá černé figury.' },

  // ── Úroveň 2 — Rozestavení figur ───────────────────────────────────
  'rm-rules-9': { introduction: 'Kde stojí bílí pěšci na začátku?', question: 'Na které řadě začínají bílí pěšci?', options: ['Na 1. řadě', 'Na 2. řadě', 'Na 3. řadě', 'Na 4. řadě'], explanation: 'Osm bílých pěšců se řadí podél 2. řady na začátku hry.' },
  'rm-rules-10': { introduction: 'Kde stojí černí pěšci na začátku?', question: 'Na které řadě začínají černí pěšci?', options: ['Na 8. řadě', 'Na 6. řadě', 'Na 7. řadě', 'Na 5. řadě'], explanation: 'Osm černých pěšců se řadí podél 7. řady na začátku.' },
  'rm-rules-11': { introduction: 'Kolik pěšců naplní celou řadu?', question: 'Kolik pěšců má každá strana na začátku?', options: ['6', '8', '10', '16'], explanation: 'Každý hráč začíná s 8 pěšci, kteří naplní celou řadu.' },
  'rm-rules-12': { introduction: 'Která figura obsazuje rohová pole?', question: 'Která figura stojí v každém rohu šachovnice na začátku?', options: ['Věž', 'Jezdec', 'Střelec', 'Dáma'], explanation: 'Věž obsazuje každé ze čtyř rohových polí v základním postavení.' },
  'rm-rules-13': { introduction: 'Zaměř se na pořadí figur na základní řadě od sloupce a.', question: 'Jaké je správné pořadí bílých figur na základní řadě od sloupce a?', options: ['Věž, střelec, jezdec, dáma, král, jezdec, střelec, věž', 'Věž, jezdec, střelec, dáma, král, střelec, jezdec, věž', 'Věž, jezdec, střelec, král, dáma, střelec, jezdec, věž', 'Jezdec, věž, střelec, dáma, král, střelec, věž, jezdec'], explanation: 'Základní řada jde od sloupce a takto: věž, jezdec, střelec, dáma, král, střelec, jezdec, věž.' },
  'rm-rules-14': { introduction: 'Na kterém poli stojí bílý král?', question: 'Na kterém poli začíná bílý král?', options: ['d1', 'e1', 'c1', 'f1'], explanation: 'Bílý král začíná na e1 a dáma stojí vedle něj na d1.' },
  'rm-rules-15': { introduction: 'Na kterém poli stojí bílá dáma?', question: 'Na kterém poli začíná bílá dáma?', options: ['e1', 'c1', 'd1', 'd2'], explanation: 'Bílá dáma začíná na d1, což je světlé pole (dáma na své barvě).' },
  'rm-rules-16': { introduction: 'Kde stojí jezdci v základním postavení?', question: 'Vedle které figury stojí jezdci v základním postavení?', options: ['Vedle věží v rozích', 'Jen vedle krále', 'Jen vedle dámy', 'Ve středu'], explanation: 'Každý jezdec stojí hned vedle rohové věže, mezi věží a střelcem.' },

  // ── Úroveň 3 — Světlá a tmavá pole ─────────────────────────────────
  'rm-rules-17': { introduction: 'Vzpomeň si na pravidlo o pravém rohu.', question: 'Jakou barvu má při správném rozestavení blízké pravé rohové pole každého hráče?', options: ['Tmavou', 'Světlou', 'Mění se to', 'Zelenou'], explanation: 'Pravidlo „bílé napravo“ znamená, že v blízkém pravém rohu každého hráče je světlé pole.' },
  'rm-rules-18': { introduction: 'Jaká je barva pole h1?', question: 'Jakou barvu má pole h1?', options: ['Světlou', 'Tmavou', 'Červenou', 'Žádnou'], explanation: 'h1 je světlé pole, které leží v blízkém pravém rohu bílého.' },
  'rm-rules-19': { introduction: 'Jaká je barva pole a1?', question: 'Jakou barvu má pole a1?', options: ['Světlou', 'Tmavou', 'Modrou', 'Bílou'], explanation: 'a1 je tmavé pole v blízkém levém rohu bílého.' },
  'rm-rules-20': { introduction: 'Na jaké barvě začíná bílá dáma?', question: 'Na poli jaké barvy začíná bílá dáma?', options: ['Na tmavém poli', 'Na světlém poli', 'Na červeném poli', 'Nemá barvu'], explanation: 'Bílá dáma začíná na d1, což je světlé pole, podle pravidla „dáma na své barvě“.' },
  'rm-rules-21': { introduction: 'Na jaké barvě začíná černá dáma?', question: 'Na poli jaké barvy začíná černá dáma?', options: ['Na světlém poli', 'Na tmavém poli', 'Na zeleném poli', 'Na stejné jako král'], explanation: 'Černá dáma začíná na d8, což je tmavé pole odpovídající její barvě.' },
  'rm-rules-22': { introduction: 'Rozděl 64 polí rovnoměrně.', question: 'Kolik světlých polí je na šachovnici?', options: ['30', '32', '34', '16'], explanation: '64 polí se dělí rovnoměrně, takže je 32 světlých a 32 tmavých polí.' },
  'rm-rules-23': { introduction: 'Střelec zůstává na jedné barvě.', question: 'Na která pole se může pohnout střelec, který začíná na světlém poli?', options: ['Jen na světlá pole', 'Jen na tmavá pole', 'Na jakékoli pole', 'Jen na svůj sloupec'], explanation: 'Střelec zůstává po celou hru na jedné barvě, takže střelec ze světlého pole dosáhne jen na světlá pole.' },
  'rm-rules-24': { introduction: 'Přemýšlej o polích, která se dotýkají rohem.', question: 'Jaké jsou vždy dvě pole, která se dotýkají pouze rohem?', options: ['Různých barev', 'Stejné barvy', 'Obě světlá', 'Obě tmavá'], explanation: 'Úhlopříčně sousedící pole (dotýkající se rohem) jsou vždy stejné barvy.' },

  // ── Úroveň 4 — Řady, sloupce a diagonály ───────────────────────────
  'rm-rules-25': { introduction: 'Co znamená pojem „řada“?', question: 'Co je to „řada“ na šachovnici?', options: ['Sloupec', 'Vodorovná řada', 'Diagonální linie', 'Jedno pole'], explanation: 'Řada je vodorovná linie polí, číslovaná od 1 do 8.' },
  'rm-rules-26': { introduction: 'Co znamená pojem „sloupec“?', question: 'Co je to „sloupec“ na šachovnici?', options: ['Svislý sloupec', 'Vodorovná řada', 'Diagonála', 'Roh'], explanation: 'Sloupec je svislá linie polí, značená písmeny a až h.' },
  'rm-rules-27': { introduction: 'Jak se značí řady?', question: 'Jak jsou označeny řady?', options: ['Písmeny a–h', 'Čísly 1–8', 'Římskými číslicemi', 'Barvami'], explanation: 'Řady jsou vodorovné linie, číslované od 1 do 8.' },
  'rm-rules-28': { introduction: 'Jak se značí sloupce?', question: 'Jak jsou označeny sloupce?', options: ['Čísly 1–8', 'Písmeny a–h', 'Čísly 0–7', 'Symboly'], explanation: 'Sloupce jsou svislé linie, značené písmeny a až h.' },
  'rm-rules-29': { introduction: 'Z čeho se skládá diagonála?', question: 'Z čeho se skládá diagonála?', options: ['Z polí střídavých barev', 'Z polí stejné barvy', 'Jen z okrajových polí', 'Z řady osmi řad'], explanation: 'Diagonála je šikmá linie polí, která jsou všechna stejné barvy.' },
  'rm-rules-30': { introduction: 'Kolik polí má jeden sloupec?', question: 'Kolik polí je ve sloupci a?', options: ['6', '7', '8', '9'], explanation: 'Každý sloupec vede přes celou výšku šachovnice, takže obsahuje 8 polí.' },
  'rm-rules-31': { introduction: 'Rozlož zápis pole e4.', question: 'Na kterém sloupci a řadě leží pole e4?', options: ['Sloupec e, řada 4', 'Sloupec 4, řada e', 'Sloupec a, řada 4', 'Sloupec e, řada 1'], explanation: 'V algebraické notaci je písmeno sloupec a číslo řada, takže e4 je sloupec e, řada 4.' },
  'rm-rules-32': { introduction: 'Nejdelší diagonály vedou od rohu k rohu.', question: 'Kolik polí obsahují nejdelší diagonály na šachovnici?', options: ['6', '7', '8', '9'], explanation: 'Obě dlouhé diagonály od rohu k rohu se táhnou přes 8 polí.' },

  // ── Úroveň 5 — Cíl hry ─────────────────────────────────────────────
  'rm-rules-33': { introduction: 'Jaký je hlavní smysl šachové partie?', question: 'Jaký je hlavní cíl šachové partie?', options: ['Sebrat nejvíce figur', 'Dát soupeřovu králi mat', 'Dostat se na druhou stranu', 'Sebrat dámu'], explanation: 'Cílem šachu je dát nepřátelskému králi mat, ne pouze získat materiál.' },
  'rm-rules-34': { introduction: 'Bere se král ke konci hry?', question: 'Sebereš krále, abys vyhrál?', options: ['Ano, odstraníš ho', 'Ne, dáš mu mat', 'Jen v bleskovce', 'Záleží jen na dámě'], explanation: 'Král se nikdy nebere; hra končí, když je matován (chycen v šachu).' },
  'rm-rules-35': { introduction: 'Co přesně znamená „mat“?', question: 'Co znamená „mat“?', options: ['Král je v šachu bez legálního úniku', 'Král je sebrán', 'Je dohodnuta remíza', 'Pěšec dosáhne konce'], explanation: 'Mat nastává, když je král v šachu a neexistuje žádný legální tah, kterým by unikl.' },
  'rm-rules-36': { introduction: 'Kterou figuru musíš chránit nade vše?', question: 'Kterou figuru musíš chránit nade vše ostatní?', options: ['Dámu', 'Krále', 'Věž', 'Pěšce'], explanation: 'Král je nejdůležitější figura; pokud dostane mat, partie je prohraná.' },
  'rm-rules-37': { introduction: 'Jak se nazývá partie bez matu?', question: 'Jak se nazývá partie, která skončí, aniž by některá strana mohla dát mat?', options: ['Výhra', 'Prohra', 'Remíza', 'Kontumace'], explanation: 'Partie, která skončí bez matu, například patem, je remíza.' },
  'rm-rules-38': { introduction: 'Zvaž různé způsoby ukončení partie.', question: 'Který z těchto je způsob, jak může partie skončit?', options: ['Mat', 'Vzdání', 'Remíza', 'Všechny tyto'], explanation: 'Partie může skončit matem, vzdáním, remízou i jinými způsoby.' },
  'rm-rules-39': { introduction: 'Co znamená, když se hráč vzdá?', question: 'Co se stane, když se hráč vzdá?', options: ['Partie je remíza', 'Tento hráč prohrává', 'Partie se restartuje', 'Nic se nemění'], explanation: 'Vzdání znamená uznání porážky, takže vzdávající se hráč prohrává.' },
  'rm-rules-40': { introduction: 'Je sebrání více figur totéž co výhra?', question: 'Je sebrání více figur totéž co vítězství v partii?', options: ['Ano, vyhrává nejvíce figur', 'Ne, vyhrává jen mat', 'Ano, pokud sebereš dámu', 'Jen v koncovce'], explanation: 'Materiálová převaha pomáhá, ale partie se vyhraje jedině dáním matu.' },

  // ── Úroveň 6 — Tahy a pravidlo „dotknuto – táhnuto“ ─────────────────
  'rm-rules-41': { introduction: 'Která barva zahajuje?', question: 'Která barva táhne vždy jako první?', options: ['Černá', 'Bílá', 'Hráč, který si vybere', 'Ten, kdo je starší'], explanation: 'Bílá vždy provádí první tah partie.' },
  'rm-rules-42': { introduction: 'Kolik figur táhne v jednom tahu?', question: 'Kolik figur můžeš pohnout v jednom tahu (nepočítáme-li rošádu)?', options: ['Jednu', 'Dvě', 'Kolik chceš', 'Žádnou'], explanation: 'Normální tah je přesně jeden pohyb jedné figury; rošáda je zvláštní výjimka.' },
  'rm-rules-43': { introduction: 'Kdo je na tahu po bílé?', question: 'Kdo je na tahu poté, co táhne bílá?', options: ['Zase bílá', 'Černá', 'Kterýkoli hráč', 'Nikdo'], explanation: 'Hráči se přísně střídají, takže po bílé táhne černá.' },
  'rm-rules-44': { introduction: 'Můžeš svůj tah vynechat?', question: 'Můžeš vynechat svůj tah, pokud se ti nelíbí tvé možnosti?', options: ['Ano, kdykoli', 'Ne, musíš táhnout', 'Jen jednou za partii', 'Jen v šachu'], explanation: 'Vynechání tahu není povoleno; na tahu musíš provést legální tah.' },
  'rm-rules-45': { introduction: 'Co znamená dotknout se vlastní figury?', question: 'Co se stane podle pravidla „dotknuto – táhnuto“, když se dotkneš vlastní figury?', options: ['Nic', 'Musíš s ní táhnout, pokud má legální tah', 'Prohráváš partii', 'Musíš táhnout pěšcem'], explanation: 'Pokud se úmyslně dotkneš vlastní figury a ta může legálně táhnout, musíš s ní táhnout.' },
  'rm-rules-46': { introduction: 'Co znamená dotknout se soupeřovy figury?', question: 'Co se stane podle pravidla „dotknuto – táhnuto“, když se dotkneš soupeřovy figury?', options: ['Musíš ji sebrat, pokud je to legálně možné', 'Nic se nestane', 'Přijdeš o dámu', 'Musíš táhnout králem'], explanation: 'Dotek nepřátelské figury tě zavazuje ji sebrat, pokud existuje legální braní.' },
  'rm-rules-47': { introduction: 'Jak dáš najevo, že chceš jen urovnat figuru?', question: 'Jak dáš najevo, že chceš urovnat figuru, aniž bys byl nucen s ní táhnout?', options: ['Urovnat nelze', 'Nejprve řekni „upravuji“ (j\'adoube)', 'Rychle ji vrať zpět', 'Požádej rozhodčího, ať s ní pohne'], explanation: 'Oznámení „upravuji“ nebo „j\'adoube“ před dotekem ti umožní urovnat figuru bez závazku „dotknuto – táhnuto“.' },
  'rm-rules-48': { introduction: 'Kdy je tah dokončen při hře s hodinami?', question: 'Kdy je tah považován za dokončený v partii s hodinami?', options: ['Když řekneš „hotovo“', 'Když pustíš figuru (a stiskneš hodiny)', 'Když soupeř odpoví', 'Nikdy není konečný'], explanation: 'Tah je dokončen, jakmile pustíš figuru na jejím novém poli; poté stiskneš hodiny.' },

  // ── Úroveň 7 — Základy braní ───────────────────────────────────────
  'rm-rules-49': { introduction: 'Jak většina figur bere?', question: 'Jak většina figur bere nepřátelskou figuru?', options: ['Přeskočením přes ni', 'Postavením se na její pole', 'Dotekem', 'Brát nelze'], explanation: 'Beroucí figura se postaví na pole obsazené nepřátelskou figurou a tu odstraní.' },
  'rm-rules-50': { introduction: 'Co se stane se sebranou figurou?', question: 'Co se stane se sebranou figurou?', options: ['Zůstane na šachovnici', 'Je odstraněna ze šachovnice', 'Změní barvu', 'Vrátí se příští tah'], explanation: 'Sebraná figura je odstraněna ze šachovnice a už se hry neúčastní.' },
  'rm-rules-51': { introduction: 'Můžeš brát vlastní figury?', question: 'Můžeš sebrat vlastní figuru?', options: ['Ano', 'Ne', 'Jen pěšce', 'Jen dámu'], explanation: 'Vlastní figury nikdy brát nesmíš; braní se týká pouze nepřátelských figur.' },
  'rm-rules-52': { introduction: 'Je braní ve standardních šachách povinné?', question: 'Je braní ve standardních šachách někdy povinné?', options: ['Ano, vždy', 'Ne, braní je dobrovolné', 'Jen pěšci', 'Jen v šachu'], explanation: 'Na rozdíl od některých her šachy braní nikdy nevynucují; je to tvá volba.' },
  'rm-rules-53': { introduction: 'Jak bere pěšec?', question: 'Jak bere pěšec?', options: ['Přímo vpřed', 'Jedno pole úhlopříčně vpřed', 'Do strany', 'Vzad'], explanation: 'Pěšec táhne přímo, ale bere jedno pole úhlopříčně vpřed.' },
  'rm-rules-54': { introduction: 'Která figura umí přeskakovat?', question: 'Která figura může při tahu nebo braní přeskočit přes jiné figury?', options: ['Věž', 'Střelec', 'Jezdec', 'Dáma'], explanation: 'Jezdec je jediná figura, která umí přeskočit přes jiné figury.' },
  'rm-rules-55': { introduction: 'Může pěšec brát figuru přímo před sebou?', question: 'Může pěšec sebrat figuru stojící přímo před ním?', options: ['Ano', 'Ne', 'Jen krále', 'Jen jiného pěšce'], explanation: 'Pěšec bere pouze úhlopříčně, takže figuru blokující ho přímo vpředu sebrat nemůže.' },
  'rm-rules-56': { introduction: 'Kolik figur použiješ k jednomu braní?', question: 'Pokud by dvě tvé figury mohly obě sebrat tutéž nepřátelskou figuru, kolik jich použiješ?', options: ['Obě najednou', 'Jen jednu, je to jeden tah', 'Žádnou', 'Musíš použít tu hodnotnější'], explanation: 'Braní je jediný tah, takže si vybereš přesně jednu figuru, která ho provede.' },

  // ── Úroveň 8 — Základy šachu ────────────────────────────────────────
  'rm-rules-57': { introduction: 'Co znamená, že je král „v šachu“?', question: 'Co znamená, když je král „v šachu“?', options: ['Je navždy uvězněn', 'Je napaden a mohl by být příští tah sebrán', 'Byl sebrán', 'Nikdy už nemůže táhnout'], explanation: 'Šach znamená, že král je napaden nepřátelskou figurou a musí být okamžitě zabezpečen.' },
  'rm-rules-58': { introduction: 'Co musíš udělat, když je král v šachu?', question: 'Co musíš udělat, když je tvůj král v šachu?', options: ['Ignorovat to', 'Vyvést krále ze šachu tímto tahem', 'Vzdát se', 'Vynechat tah'], explanation: 'Na šach jsi povinen reagovat hned svým následujícím tahem.' },
  'rm-rules-59': { introduction: 'Jak lze reagovat na šach?', question: 'Který z těchto je legální způsob, jak odpovědět na šach?', options: ['Přesunout krále do bezpečí', 'Zaclonit šach', 'Sebrat šachující figuru', 'Všechny tyto'], explanation: 'Ze šachu můžeš uniknout pohybem krále, zacloněním útoku, nebo sebráním útočníka.' },
  'rm-rules-60': { introduction: 'Smíš nechat vlastního krále v šachu?', question: 'Můžeš provést tah, kterým necháš vlastního krále v šachu?', options: ['Ano', 'Ne, je to nelegální', 'Jen pěšcem', 'Jen jednou'], explanation: 'Jakýkoli tah, který ponechá nebo uvede vlastního krále do šachu, je nelegální.' },
  'rm-rules-61': { introduction: 'Je šach totéž co prohra?', question: 'Je být v šachu totéž co prohrát partii?', options: ['Ano', 'Ne, prohrává jen mat', 'Jen když šachuje dáma', 'Jen v koncovce'], explanation: 'Šach je jen útok na krále; prohráváš teprve tehdy, když se z něj stane mat.' },
  'rm-rules-62': { introduction: 'Smí král vstoupit na napadené pole?', question: 'Může král vstoupit na pole napadené nepřátelskou figurou?', options: ['Ano, volně', 'Ne, to by znamenalo vstoupit do šachu', 'Jen aby bral', 'Jen na základní řadě'], explanation: 'Král nikdy nesmí vstoupit na pole, kde by byl v šachu.' },
  'rm-rules-63': { introduction: 'Lze zaclonit šach od jezdce?', question: 'Můžeš zaclonit šach daný jezdcem?', options: ['Ano, vždy', 'Ne, šach jezdcem nelze zaclonit', 'Jen pěšcem', 'Jen dámou'], explanation: 'Protože jezdci přeskakují, není mezi útočníkem a králem žádné pole k zaclonění, takže musíš táhnout králem nebo jezdce sebrat.' },
  'rm-rules-64': { introduction: 'Musíš táhnout, když je to jediný legální tah?', question: 'Pokud je tvou jedinou legální odpovědí na šach sebrat útočníka, musíš tak učinit?', options: ['Ne, můžeš vynechat tah', 'Ano, musíš provést legální tah', 'Můžeš se jen vzdát', 'Automaticky prohráváš'], explanation: 'Musíš zahrát legální tah, který unikne ze šachu; pokud je jediným braní, právě to zahraješ.' },

  // ── Úroveň 9 — Nelegální tahy a etiketa ────────────────────────────
  'rm-rules-65': { introduction: 'Který z tahů je nelegální?', question: 'Který z těchto tahů je nelegální?', options: ['Rošáda', 'Tah jezdcem do tvaru L', 'Ponechání vlastního krále v šachu', 'Sebrání pěšce'], explanation: 'Tah, který ponechá vlastního krále v šachu, je vždy nelegální.' },
  'rm-rules-66': { introduction: 'Co dělat, když padne nelegální tah?', question: 'Co bys měl udělat, když si všimneš, že byl zahrán nelegální tah?', options: ['Ignorovat to', 'Vzít tah zpět a opravit postavení', 'Okamžitě vyhrát', 'Vyměnit figuru'], explanation: 'Nelegální tah musí být vzat zpět a místo něj zahrán legální tah.' },
  'rm-rules-67': { introduction: 'Jaký je zdvořilý zvyk na začátku a konci vážné partie?', question: 'Jaký je zdvořilý zvyk na začátku a konci vážné partie?', options: ['Podat si ruce', 'Nic neříkat', 'Sebrat figuru', 'Stisknout hodiny'], explanation: 'Hráči si tradičně podávají ruce před partií i po ní jako projev úcty.' },
  'rm-rules-68': { introduction: 'Je slušné vyrušovat soupeře?', question: 'Je dobrou etiketou mluvit nebo rozptylovat soupeře během jeho tahu?', options: ['Ano', 'Ne', 'Jen v šachu', 'Jen o počasí'], explanation: 'Rozptylování nebo vyrušování soupeře je považováno za špatnou etiketu a nedoporučuje se.' },
  'rm-rules-69': { introduction: 'Jak se tradičně u šachovnice ukazuje vzdání?', question: 'Jak se tradičně u šachovnice ukazuje vzdání?', options: ['Převrácením šachovnice', 'Položením vlastního krále nebo nabídnutím ruky', 'Odstraněním všech pěšců', 'Zvoláním „šach“'], explanation: 'Hráč se často vzdává tím, že jemně položí svého krále nebo nabídne ruku k potřesení.' },
  'rm-rules-70': { introduction: 'Kdy je vhodné nabídnout remízu?', question: 'Kdy je vhodné nabídnout remízu?', options: ['Ve vlastním tahu, poté co jej provedeš', 'Během soupeřova přemýšlení', 'Jen v šachu', 'Nikdy'], explanation: 'Správná etiketa je nabídnout remízu poté, co jsi provedl svůj tah, ještě před stisknutím hodin.' },
  'rm-rules-71': { introduction: 'Lze vzít tah zpět po puštění figury?', question: 'Můžeš vzít tah zpět, jakmile jsi pustil figuru?', options: ['Ano, kdykoli', 'Ne, tah platí', 'Jen tahy pěšcem', 'Jen svůj první tah'], explanation: 'Jakmile pustíš figuru na jejím poli, tah je dokončen a nelze jej vzít zpět.' },
  'rm-rules-72': { introduction: 'Je nutné hlásit šach nahlas?', question: 'Hlásit „šach“ nahlas je čím z následujícího?', options: ['Vyžadováno pravidly', 'Zdvořilost, ve formální hře není nutná', 'Nelegální', 'Jen pro dámu'], explanation: 'Říkat „šach“ je přátelská zdvořilost, ale podle oficiálních turnajových pravidel se nevyžaduje.' },

  // ── Úroveň 10 — Mistrovství pravidel ───────────────────────────────
  'rm-rules-73': { introduction: 'Začátečník má v blízkém pravém rohu tmavé pole.', question: 'Začátečník postaví šachovnici s tmavým polem v blízkém pravém rohu. Co je špatně?', options: ['Nic, tak je to správně', 'Šachovnice je otočená; do blízkého pravého rohu patří světlé pole', 'Chybí pěšci', 'Král a dáma jsou v pořádku'], explanation: 'Pravidlo „bílé napravo“ vyžaduje světlé pole v blízkém pravém rohu každého hráče, takže šachovnici je třeba otočit.' },
  'rm-rules-74': { introduction: 'Bílá dáma stojí na tmavém poli.', question: 'Hráč postaví dámy na d1 a d8, ale prohodí je, takže bílá dáma stojí na tmavém poli. Co je špatně?', options: ['Dámy mohou stát kdekoli', 'Dáma musí začínat na své barvě, takže bílá dáma patří na světlé d1', 'Králové jsou špatně umístěni', 'Nic není špatně'], explanation: '„Dáma na své barvě“ znamená, že bílá dáma musí stát na světlém poli d1, ne na tmavém.' },
  'rm-rules-75': { introduction: 'Bílý je v šachu od střelce, mezi nimi je prázdné pole.', question: 'Bílý je v šachu od střelce na diagonále, mezi nimi je prázdné pole. Co NENÍ způsob úniku?', options: ['Přesunout krále z diagonály', 'Zaclonit na poli mezi nimi', 'Sebrat střelce', 'Ohlásit vynechání tahu a nic neudělat'], explanation: 'Vynechání tahu není nikdy legální; ze šachu musíš uniknout pohybem krále, zacloněním, nebo braním.' },
  'rm-rules-76': { introduction: 'Jediná legální odpověď na šach je sebrat věž králem.', question: 'Je na tahu černý a jeho jedinou legální odpovědí na šach je sebrat útočící věž králem. Co musí nastat?', options: ['Černý se může místo tahu vzdát', 'Černý musí provést toto braní', 'Je to pat', 'Černý vynechá tah'], explanation: 'Existuje-li jediný legální tah k úniku ze šachu, hráč je povinen jej provést.' },
  'rm-rules-77': { introduction: 'Hráč se dotkl jezdce, který má legální tah.', question: 'V turnajové partii se hráč dotkne svého jezdce, který má legální tah. Poté chce místo něj táhnout střelcem. Je to dovoleno?', options: ['Ano, vždy', 'Ne, pravidlo „dotknuto – táhnuto“ ho nutí táhnout jezdcem', 'Jen když se omluví', 'Jen když je šach'], explanation: 'Podle pravidla „dotknuto – táhnuto“ musí být úmyslně dotknutá figura s legálním tahem tou, která táhne.' },
  'rm-rules-78': { introduction: 'Jezdec na f3 dává šach králi u pole g1.', question: 'Jezdec na f3 dává šach králi v okolí pole g1. Proč nelze tento šach nikdy zaclonit?', options: ['Jezdci se pohybují příliš rychle', 'Jezdec přeskakuje, takže nezbývá pole k vloženému zaclonění', 'Jezdci nemohou dávat šach', 'Král je vázán'], explanation: 'Protože jezdec přeskakuje přes pole, není žádná linie, kam vložit clonu, takže král musí táhnout, nebo musí být jezdec sebrán.' },
  'rm-rules-79': { introduction: 'Které tvrzení o cíli šachu je nejpřesnější?', question: 'Které tvrzení o cíli šachu je nejpřesnější?', options: ['Vyhráváš sebráním nepřátelského krále', 'Vyhráváš dáním matu nepřátelskému králi', 'Vyhráváš získáním nejvíce materiálu', 'Vyhráváš proměnou pěšce'], explanation: 'Král se nikdy skutečně nebere; partie se vyhraje matem, tedy chycením krále v šachu.' },
  'rm-rules-80': { introduction: 'Pěšec na e5 chce brát pěšce přímo na e6.', question: 'Pěšec na e5 chce sebrat nepřátelského pěšce stojícího přímo na e6. Může?', options: ['Ano, pěšci berou přímo vpřed', 'Ne, pěšci berou jen úhlopříčně, takže je zablokován', 'Jen pokud je bílý', 'Jen přeskočením'], explanation: 'Pěšci táhnou přímo, ale berou úhlopříčně, takže pěšec nemůže sebrat figuru přímo před sebou.' },
};
