import type { Seed } from './roadmap-build';

// The World Wars — 10 levels × 8 questions, easiest → hardest.
export const worldwarsSeeds: Seed[] = [
  // ── Level 1 — The Road to WWI ──
  {
    q: 'In which year did World War I begin?',
    opts: ['1914', '1916', '1912', '1918'],
    a: 0,
    e: 'World War I began in the summer of 1914 following the assassination of Archduke Franz Ferdinand.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'Whose assassination in Sarajevo triggered the outbreak of World War I?',
    opts: ['Kaiser Wilhelm II', 'Archduke Franz Ferdinand', 'Tsar Nicholas II', 'Otto von Bismarck'],
    a: 1,
    e: 'The assassination of Archduke Franz Ferdinand of Austria-Hungary in June 1914 set off the chain of events leading to war.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'In which city was Archduke Franz Ferdinand assassinated?',
    opts: ['Vienna', 'Belgrade', 'Sarajevo', 'Budapest'],
    a: 2,
    e: 'Franz Ferdinand was shot in Sarajevo, the capital of Bosnia, then part of Austria-Hungary.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'What were the two main opposing alliances in World War I called?',
    opts: ['Axis and Allies', 'Union and Confederacy', 'Warsaw Pact and NATO', 'Central Powers and Allied Powers'],
    a: 3,
    e: 'The Central Powers (led by Germany and Austria-Hungary) fought the Allied Powers (including France, Britain, and Russia).',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'Which country was NOT one of the Central Powers?',
    opts: ['Germany', 'Austria-Hungary', 'Ottoman Empire', 'France'],
    a: 3,
    e: 'France was one of the Allied Powers; the Central Powers included Germany, Austria-Hungary, and the Ottoman Empire.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'Who was the German monarch (Kaiser) during World War I?',
    opts: ['Frederick III', 'Otto von Bismarck', 'Wilhelm II', 'Ludwig II'],
    a: 2,
    e: 'Kaiser Wilhelm II ruled the German Empire from 1888 until his abdication in 1918.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'The Serbian nationalist who assassinated Franz Ferdinand belonged to a group nicknamed what?',
    opts: ['The Red Hand', 'The Black Hand', 'The Iron Guard', 'The Green Legion'],
    a: 1,
    e: 'Gavrilo Princip was linked to the Black Hand, a secret Serbian nationalist society.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'A system of military agreements pledging nations to defend one another is called what?',
    opts: ['The alliance system', 'Colonialism', 'Nationalism', 'Isolationism'],
    a: 0,
    e: 'The alliance system meant a conflict between two nations could quickly pull in many others, helping turn a local dispute into a world war.',
    tags: ['world wars', 'wwi'],
  },

  // ── Level 2 — World War I: The Great War ──
  {
    q: 'What name was commonly given to World War I before the Second World War occurred?',
    opts: ['The Great War', 'The Long War', 'The Cold War', 'The Total War'],
    a: 0,
    e: 'Contemporaries called it the Great War, often hoping it would be the war to end all wars.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'The German plan to quickly defeat France before turning east against Russia was known as what?',
    opts: ['The Maginot Plan', 'The Schlieffen Plan', 'The Barbarossa Plan', 'The Anaconda Plan'],
    a: 1,
    e: 'The Schlieffen Plan aimed for a rapid knockout of France through Belgium before Russia could fully mobilize.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'Germany violated the neutrality of which country when it invaded in 1914, helping bring Britain into the war?',
    opts: ['Switzerland', 'Netherlands', 'Belgium', 'Denmark'],
    a: 2,
    e: 'Germany invaded neutral Belgium, and Britain had guaranteed Belgian neutrality by treaty.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'In which year did the United States enter World War I?',
    opts: ['1915', '1916', '1919', '1917'],
    a: 3,
    e: 'The United States declared war on Germany in April 1917.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'The 1916 Battle of Verdun was fought primarily between which two nations?',
    opts: ['Britain and Germany', 'Russia and Austria-Hungary', 'Italy and Austria-Hungary', 'France and Germany'],
    a: 3,
    e: 'Verdun was one of the longest and bloodiest battles of the war, fought between France and Germany.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'The sinking of which passenger liner in 1915 outraged American public opinion?',
    opts: ['The Titanic', 'The Bismarck', 'The Lusitania', 'The Maine'],
    a: 2,
    e: 'A German U-boat sank the Lusitania in 1915, killing many civilians including Americans.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'What underwater weapon did Germany use in its campaign of unrestricted submarine warfare?',
    opts: ['The dreadnought', 'The U-boat', 'The torpedo boat', 'The frigate'],
    a: 1,
    e: 'German U-boats (submarines) attacked merchant and passenger shipping in the Atlantic.',
    tags: ['world wars', 'wwi'],
  },
  {
    q: 'The 1916 Battle of the Somme is remembered especially for what?',
    opts: ['Enormous casualties for little territorial gain', 'A decisive quick victory', 'The first use of atomic weapons', 'Ending the war in a single day'],
    a: 0,
    e: 'The Somme saw over a million casualties across both sides while front lines barely moved.',
    tags: ['world wars', 'wwi'],
  },

  // ── Level 3 — Trench Warfare & Technology ──
  {
    q: 'The area of open ground between opposing trench lines was called what?',
    opts: ["No man's land", 'The kill zone', 'The dead zone', 'The front porch'],
    a: 0,
    e: "No man's land was the exposed, often cratered ground between enemy trenches.",
    tags: ['world wars', 'trench warfare'],
  },
  {
    q: 'Which poison gas, causing severe blistering, was widely used in World War I?',
    opts: ['Helium', 'Mustard gas', 'Carbon dioxide', 'Nitrous oxide'],
    a: 1,
    e: 'Mustard gas blistered skin and lungs and became one of the war\'s most feared chemical weapons.',
    tags: ['world wars', 'trench warfare'],
  },
  {
    q: 'Which new armored vehicle first appeared on the battlefield during World War I?',
    opts: ['The half-track', 'The jeep', 'The tank', 'The armored car'],
    a: 2,
    e: 'Britain introduced the tank in 1916 to help break the deadlock of trench warfare.',
    tags: ['world wars', 'trench warfare', 'technology'],
  },
  {
    q: 'Which weapon, capable of rapid sustained fire, made frontal assaults across open ground extremely deadly?',
    opts: ['The crossbow', 'The revolver', 'The blunderbuss', 'The machine gun'],
    a: 3,
    e: 'The machine gun allowed defenders to mow down advancing infantry, reinforcing trench stalemate.',
    tags: ['world wars', 'trench warfare', 'technology'],
  },
  {
    q: 'A common ailment of the feet caused by prolonged exposure to cold, wet trench conditions was called what?',
    opts: ['Frostbite fever', 'Marsh rot', 'Cold burn', 'Trench foot'],
    a: 3,
    e: 'Trench foot resulted from soldiers standing in cold, waterlogged trenches for long periods.',
    tags: ['world wars', 'trench warfare'],
  },
  {
    q: 'What term described the widespread psychological trauma soldiers suffered from prolonged combat?',
    opts: ['Battle fatigue syndrome', 'Combat sickness', 'Shell shock', 'War fever'],
    a: 2,
    e: 'Shell shock was the era\'s term for what is now understood as combat-related psychological trauma.',
    tags: ['world wars', 'trench warfare'],
  },
  {
    q: 'Airplanes in early World War I were used primarily for what role before becoming fighters?',
    opts: ['Strategic bombing of cities', 'Reconnaissance and observation', 'Transporting troops', 'Dropping supplies'],
    a: 1,
    e: 'Aircraft first served as scouts to observe enemy positions before dedicated fighters were developed.',
    tags: ['world wars', 'technology'],
  },
  {
    q: 'Large hydrogen-filled airships that Germany used for bombing raids over Britain were known as what?',
    opts: ['Zeppelins', 'Blimps', 'Gliders', 'Biplanes'],
    a: 0,
    e: 'German Zeppelins carried out some of the first aerial bombing raids on British cities.',
    tags: ['world wars', 'technology'],
  },

  // ── Level 4 — The Russian Revolution ──
  {
    q: 'Who was the Tsar of Russia forced to abdicate in 1917?',
    opts: ['Nicholas II', 'Alexander III', 'Peter the Great', 'Ivan IV'],
    a: 0,
    e: 'Tsar Nicholas II abdicated in March 1917 amid mounting unrest and wartime hardship.',
    tags: ['world wars', 'russian revolution'],
  },
  {
    q: 'Which revolutionary leader headed the Bolsheviks during the 1917 October Revolution?',
    opts: ['Joseph Stalin', 'Vladimir Lenin', 'Leon Trotsky', 'Alexander Kerensky'],
    a: 1,
    e: 'Vladimir Lenin led the Bolsheviks to power in the October Revolution of 1917.',
    tags: ['world wars', 'russian revolution'],
  },
  {
    q: 'The Bolshevik slogan promising an end to hardship was "Peace, Land, and ___."',
    opts: ['Liberty', 'Order', 'Bread', 'Glory'],
    a: 2,
    e: 'The slogan "Peace, Land, and Bread" appealed to war-weary soldiers, peasants, and hungry workers.',
    tags: ['world wars', 'russian revolution'],
  },
  {
    q: 'The 1918 treaty in which Russia exited World War I was signed at which town?',
    opts: ['Versailles', 'Rapallo', 'Locarno', 'Brest-Litovsk'],
    a: 3,
    e: 'The Treaty of Brest-Litovsk in 1918 ended Russia\'s participation in the war on harsh terms.',
    tags: ['world wars', 'russian revolution'],
  },
  {
    q: 'What was the name of the workers\' and soldiers\' councils that formed during the Russian Revolution?',
    opts: ['Dumas', 'Politburos', 'Zemstvos', 'Soviets'],
    a: 3,
    e: 'Soviets were councils of workers and soldiers that became key institutions of the revolution.',
    tags: ['world wars', 'russian revolution'],
  },
  {
    q: 'The Russian Civil War that followed the revolution was fought mainly between which two sides?',
    opts: ['North and South', 'The Blues and the Greens', 'The Reds and the Whites', 'East and West'],
    a: 2,
    e: 'The Bolshevik Reds fought the anti-communist Whites in a bloody civil war from 1917 to the early 1920s.',
    tags: ['world wars', 'russian revolution'],
  },
  {
    q: 'What new state was formally established in 1922 out of the former Russian Empire?',
    opts: ['The Russian Federation', 'The Soviet Union (USSR)', 'The Commonwealth of Russia', 'The Slavic Republic'],
    a: 1,
    e: 'The Union of Soviet Socialist Republics (USSR) was formally created in 1922.',
    tags: ['world wars', 'russian revolution'],
  },
  {
    q: 'The revolutionary who organized and led the Red Army during the civil war was:',
    opts: ['Leon Trotsky', 'Grigory Rasputin', 'Nikita Khrushchev', 'Leonid Brezhnev'],
    a: 0,
    e: 'Leon Trotsky founded and commanded the Red Army during the Russian Civil War.',
    tags: ['world wars', 'russian revolution'],
  },

  // ── Level 5 — Treaty of Versailles & Aftermath ──
  {
    q: 'The Treaty of Versailles, ending World War I, was signed in which year?',
    opts: ['1919', '1917', '1918', '1921'],
    a: 0,
    e: 'The Treaty of Versailles was signed in June 1919, months after the November 1918 armistice.',
    tags: ['world wars', 'versailles'],
  },
  {
    q: 'Which clause of the Treaty of Versailles forced Germany to accept blame for causing the war?',
    opts: ['The reparations clause', 'The war guilt clause', 'The disarmament clause', 'The territorial clause'],
    a: 1,
    e: 'The "war guilt clause" (Article 231) assigned responsibility for the war to Germany and its allies.',
    tags: ['world wars', 'versailles'],
  },
  {
    q: 'What financial burden did the Treaty of Versailles impose on Germany?',
    opts: ['A trade embargo', 'A gold ban', 'Reparations payments', 'Forced loans to France'],
    a: 2,
    e: 'Germany was required to pay heavy reparations to the Allied nations for war damages.',
    tags: ['world wars', 'versailles'],
  },
  {
    q: 'The international organization created after World War I to promote peace was called what?',
    opts: ['The United Nations', 'The Concert of Europe', 'The Allied Council', 'The League of Nations'],
    a: 3,
    e: 'The League of Nations was founded in 1920 to help prevent future conflicts.',
    tags: ['world wars', 'versailles'],
  },
  {
    q: 'Which major power notably did NOT join the League of Nations despite its president proposing it?',
    opts: ['France', 'Britain', 'Italy', 'The United States'],
    a: 3,
    e: 'The U.S. Senate rejected membership, so the United States never joined the League despite Wilson\'s advocacy.',
    tags: ['world wars', 'versailles'],
  },
  {
    q: 'U.S. President Woodrow Wilson\'s program of peace principles was known as the:',
    opts: ['Four Freedoms', 'Marshall Plan', 'Fourteen Points', 'Monroe Doctrine'],
    a: 2,
    e: 'Wilson\'s Fourteen Points outlined his vision for postwar peace and self-determination.',
    tags: ['world wars', 'versailles'],
  },
  {
    q: 'Restrictions in the Treaty of Versailles sharply limited the size of which German institution?',
    opts: ['The civil service', 'The military', 'The universities', 'The railways'],
    a: 1,
    e: 'The treaty sharply limited the German army, banned certain weapons, and restricted the navy and air force.',
    tags: ['world wars', 'versailles'],
  },
  {
    q: 'The new democratic German government established after the war was known as the:',
    opts: ['Weimar Republic', 'Prussian Republic', 'Rhineland Republic', 'Bonn Republic'],
    a: 0,
    e: 'The Weimar Republic governed Germany from 1919 until the Nazi seizure of power in 1933.',
    tags: ['world wars', 'versailles'],
  },

  // ── Level 6 — The Interwar Years ──
  {
    q: 'The severe economic downturn beginning in 1929 that spread worldwide is called the:',
    opts: ['Great Depression', 'Great Recession', 'Long Panic', 'Dust Crash'],
    a: 0,
    e: 'The Great Depression, triggered by the 1929 stock market crash, brought mass unemployment across the globe.',
    tags: ['world wars', 'interwar'],
  },
  {
    q: 'The catastrophic German currency crisis of the early 1920s is remembered as a period of extreme what?',
    opts: ['Deflation', 'Hyperinflation', 'Stagnation', 'Surplus'],
    a: 1,
    e: 'Hyperinflation in 1923 made the German mark nearly worthless, wiping out savings.',
    tags: ['world wars', 'interwar'],
  },
  {
    q: 'Which leader rose to power in Italy during the interwar years, founding the Fascist movement?',
    opts: ['Francisco Franco', 'Adolf Hitler', 'Benito Mussolini', 'Miklos Horthy'],
    a: 2,
    e: 'Benito Mussolini became Italy\'s Fascist dictator after the March on Rome in 1922.',
    tags: ['world wars', 'interwar', 'fascism'],
  },
  {
    q: 'Which policy did Joseph Stalin pursue to rapidly industrialize the Soviet Union?',
    opts: ['Laissez-faire capitalism', 'The New Deal', 'The Marshall Plan', 'The Five-Year Plans'],
    a: 3,
    e: 'Stalin\'s Five-Year Plans forced rapid industrialization and collectivization in the USSR.',
    tags: ['world wars', 'interwar'],
  },
  {
    q: 'The 1929 event widely seen as sparking the Great Depression was the crash of what?',
    opts: ['The London gold market', 'The Berlin bond market', 'The Paris franc', 'The New York stock market'],
    a: 3,
    e: 'The Wall Street crash of October 1929 helped trigger the global Great Depression.',
    tags: ['world wars', 'interwar'],
  },
  {
    q: 'Japan\'s 1931 invasion and occupation targeted which region of China?',
    opts: ['Tibet', 'Hong Kong', 'Manchuria', 'Xinjiang'],
    a: 2,
    e: 'Japan invaded Manchuria in 1931 and set up the puppet state of Manchukuo, defying the League of Nations.',
    tags: ['world wars', 'interwar'],
  },
  {
    q: 'The Spanish Civil War of the late 1930s ended with the victory of which nationalist leader?',
    opts: ['Antonio Salazar', 'Francisco Franco', 'Juan Peron', 'Manuel Azana'],
    a: 1,
    e: 'General Francisco Franco\'s Nationalists defeated the Republicans, and he ruled Spain as dictator.',
    tags: ['world wars', 'interwar'],
  },
  {
    q: 'The League of Nations largely failed to stop aggression in the 1930s partly because it lacked what?',
    opts: ['Its own military force to enforce decisions', 'A permanent headquarters', 'Any member states', 'A written charter'],
    a: 0,
    e: 'The League had no armed force of its own and relied on members to act, undermining its ability to deter aggressors.',
    tags: ['world wars', 'interwar'],
  },

  // ── Level 7 — Rise of Fascism ──
  {
    q: 'Adolf Hitler became Chancellor of Germany in which year?',
    opts: ['1933', '1929', '1931', '1936'],
    a: 0,
    e: 'Hitler was appointed Chancellor in January 1933, beginning the Nazi consolidation of power.',
    tags: ['world wars', 'fascism'],
  },
  {
    q: 'What was the name of Hitler\'s political party?',
    opts: ['The Fascist Party', 'The National Socialist (Nazi) Party', 'The Communist Party', 'The Social Democratic Party'],
    a: 1,
    e: 'Hitler led the National Socialist German Workers\' Party, commonly called the Nazi Party.',
    tags: ['world wars', 'fascism'],
  },
  {
    q: 'The 1935 laws that stripped Jewish citizens in Germany of their rights were called the:',
    opts: ['Weimar Laws', 'Reichstag Laws', 'Nuremberg Laws', 'Munich Laws'],
    a: 2,
    e: 'The Nuremberg Laws of 1935 institutionalized antisemitic discrimination, stripping Jews of citizenship and rights.',
    tags: ['world wars', 'fascism'],
  },
  {
    q: 'The November 1938 wave of coordinated anti-Jewish violence in Germany is known as:',
    opts: ['The Beer Hall Putsch', 'The Night of the Long Knives', 'The Anschluss', 'Kristallnacht'],
    a: 3,
    e: 'Kristallnacht ("Night of Broken Glass") saw synagogues burned and Jewish businesses destroyed across Germany.',
    tags: ['world wars', 'fascism'],
  },
  {
    q: 'What title did Adolf Hitler take, meaning "leader," to describe his absolute authority?',
    opts: ['Duce', 'Caudillo', 'Chancellor-General', 'Fuhrer'],
    a: 3,
    e: 'Hitler styled himself the Fuhrer, claiming total leadership over the German state and people.',
    tags: ['world wars', 'fascism'],
  },
  {
    q: 'The 1938 German annexation of Austria was known as the:',
    opts: ['Sudetenland', 'Blitzkrieg', 'Anschluss', 'Lebensraum'],
    a: 2,
    e: 'The Anschluss was Germany\'s annexation of Austria in March 1938.',
    tags: ['world wars', 'fascism'],
  },
  {
    q: 'At the 1938 Munich Conference, Britain and France agreed to let Germany take which territory?',
    opts: ['Alsace-Lorraine', 'The Sudetenland', 'The Rhineland', 'Danzig'],
    a: 1,
    e: 'The Munich Agreement allowed Germany to annex the Sudetenland of Czechoslovakia in a policy of appeasement.',
    tags: ['world wars', 'fascism'],
  },
  {
    q: 'The Nazi concept of "Lebensraum" referred to what goal?',
    opts: ['Living space to be gained through eastward expansion', 'Racial purity laws', 'A national labor program', 'A youth education system'],
    a: 0,
    e: 'Lebensraum ("living space") was the Nazi aim of expanding German territory eastward for settlement.',
    tags: ['world wars', 'fascism'],
  },

  // ── Level 8 — World War II: Outbreak ──
  {
    q: 'World War II in Europe began when Germany invaded which country in September 1939?',
    opts: ['Poland', 'France', 'Belgium', 'Norway'],
    a: 0,
    e: 'Germany\'s invasion of Poland on 1 September 1939 prompted Britain and France to declare war.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The German tactic of fast, coordinated attacks using tanks and aircraft was called:',
    opts: ['Trench warfare', 'Blitzkrieg', 'Attrition', 'Guerrilla war'],
    a: 1,
    e: 'Blitzkrieg ("lightning war") emphasized speed and combined arms to overwhelm defenders quickly.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The 1939 non-aggression pact between Germany and the Soviet Union is named after which two foreign ministers?',
    opts: ['Chamberlain and Daladier', 'Hitler and Stalin', 'Ribbentrop and Molotov', 'Ciano and Halifax'],
    a: 2,
    e: 'The Molotov-Ribbentrop Pact secretly divided Eastern Europe between Germany and the USSR.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'In 1940, the mass evacuation of Allied troops from a French port took place at:',
    opts: ['Calais', 'Le Havre', 'Cherbourg', 'Dunkirk'],
    a: 3,
    e: 'The Dunkirk evacuation in 1940 rescued hundreds of thousands of Allied soldiers trapped by the German advance.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'Who became British Prime Minister in 1940 and led the country through most of the war?',
    opts: ['Neville Chamberlain', 'Clement Attlee', 'Anthony Eden', 'Winston Churchill'],
    a: 3,
    e: 'Winston Churchill became Prime Minister in May 1940 and became a symbol of British resistance.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The 1940 air campaign in which the German Luftwaffe fought the Royal Air Force was called the:',
    opts: ['Battle of the Bulge', 'Battle of Midway', 'Battle of Britain', 'Battle of the Atlantic'],
    a: 2,
    e: 'The Battle of Britain saw the RAF defeat the Luftwaffe\'s attempt to gain air superiority over Britain.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The German invasion of the Soviet Union launched in June 1941 was code-named:',
    opts: ['Operation Sea Lion', 'Operation Barbarossa', 'Operation Overlord', 'Operation Torch'],
    a: 1,
    e: 'Operation Barbarossa was the massive German invasion of the USSR, breaking the 1939 pact.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The Japanese attack that brought the United States into World War II struck which naval base?',
    opts: ['Pearl Harbor', 'Midway', 'Guam', 'Manila'],
    a: 0,
    e: 'Japan\'s attack on Pearl Harbor, Hawaii, on 7 December 1941 led the United States to declare war.',
    tags: ['world wars', 'wwii'],
  },

  // ── Level 9 — WWII: Global Conflict & the Holocaust ──
  {
    q: 'The Holocaust was the systematic, state-sponsored persecution and murder of roughly how many Jewish people?',
    opts: ['Six million', 'One million', 'Three million', 'Twelve million'],
    a: 0,
    e: 'Nazi Germany murdered approximately six million Jews in the Holocaust, alongside millions of other victims.',
    tags: ['world wars', 'holocaust'],
  },
  {
    q: 'Which was the largest Nazi concentration and extermination camp complex?',
    opts: ['Dachau', 'Auschwitz-Birkenau', 'Buchenwald', 'Bergen-Belsen'],
    a: 1,
    e: 'Auschwitz-Birkenau in occupied Poland was the largest camp, where over a million people were murdered.',
    tags: ['world wars', 'holocaust'],
  },
  {
    q: 'The Nazi euphemism for their plan to systematically annihilate the Jewish people was the:',
    opts: ['New Order', 'Total War', '"Final Solution"', 'Great Purge'],
    a: 2,
    e: 'The Nazis called their genocidal program the "Final Solution to the Jewish Question."',
    tags: ['world wars', 'holocaust'],
  },
  {
    q: 'The turning-point battle on the Eastern Front where German forces suffered a catastrophic defeat in 1942-43 was at:',
    opts: ['Kursk', 'Moscow', 'Kiev', 'Stalingrad'],
    a: 3,
    e: 'The Battle of Stalingrad ended with the destruction of a German army and marked a decisive Soviet turning point.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The 1942 naval battle widely seen as the turning point of the Pacific War was the Battle of:',
    opts: ['Coral Sea', 'Leyte Gulf', 'Okinawa', 'Midway'],
    a: 3,
    e: 'At Midway in June 1942, the U.S. Navy sank four Japanese carriers, shifting the balance in the Pacific.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The Allied invasion of German-occupied France on 6 June 1944 is commonly known as:',
    opts: ['V-E Day', 'The Blitz', 'D-Day', 'The Armistice'],
    a: 2,
    e: 'D-Day, the Normandy landings, opened a major Western front against Germany in June 1944.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'Enclosed districts where Nazis confined Jewish populations under brutal conditions were called:',
    opts: ['Reservations', 'Ghettos', 'Communes', 'Colonies'],
    a: 1,
    e: 'Nazis forced Jews into overcrowded, sealed ghettos, such as the Warsaw Ghetto, before deportations to camps.',
    tags: ['world wars', 'holocaust'],
  },
  {
    q: 'The overall code name for the Allied invasion of Normandy was:',
    opts: ['Operation Overlord', 'Operation Market Garden', 'Operation Husky', 'Operation Cobra'],
    a: 0,
    e: 'Operation Overlord was the overall codename for the Allied invasion of Normandy in 1944.',
    tags: ['world wars', 'wwii'],
  },

  // ── Level 10 — The End of WWII ──
  {
    q: 'The day marking Germany\'s surrender in Europe, 8 May 1945, is known as:',
    opts: ['V-E Day', 'D-Day', 'V-J Day', 'Armistice Day'],
    a: 0,
    e: 'V-E Day (Victory in Europe Day) marked the end of the war against Germany in Europe.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The last major German offensive on the Western Front, in the winter of 1944-45, was the Battle of the:',
    opts: ['Rhine', 'Bulge', 'Ruhr', 'Scheldt'],
    a: 1,
    e: 'The Battle of the Bulge was Germany\'s failed final offensive in the Ardennes in December 1944.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The two Japanese cities struck by atomic bombs in August 1945 were Hiroshima and:',
    opts: ['Kyoto', 'Osaka', 'Nagasaki', 'Yokohama'],
    a: 2,
    e: 'The United States dropped atomic bombs on Hiroshima and Nagasaki in August 1945.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'Which U.S. president made the decision to use atomic weapons against Japan?',
    opts: ['Franklin D. Roosevelt', 'Dwight D. Eisenhower', 'Herbert Hoover', 'Harry S. Truman'],
    a: 3,
    e: 'Harry S. Truman, who became president after Roosevelt\'s death in April 1945, authorized the atomic bombings.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The February 1945 conference where the "Big Three" Allied leaders shaped postwar Europe was held at:',
    opts: ['Potsdam', 'Tehran', 'Casablanca', 'Yalta'],
    a: 3,
    e: 'The Yalta Conference in February 1945 saw Churchill, Roosevelt, and Stalin plan the final defeat and division of postwar Germany.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The postwar trials that prosecuted leading Nazi officials for war crimes were held in which city?',
    opts: ['Berlin', 'Munich', 'Nuremberg', 'Frankfurt'],
    a: 2,
    e: 'The Nuremberg Trials (1945-46) prosecuted major Nazi leaders for war crimes and crimes against humanity.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'Japan\'s formal surrender in September 1945 took place aboard which U.S. battleship?',
    opts: ['USS Arizona', 'USS Missouri', 'USS Enterprise', 'USS Iowa'],
    a: 1,
    e: 'Japan signed the instrument of surrender aboard the USS Missouri in Tokyo Bay on 2 September 1945.',
    tags: ['world wars', 'wwii'],
  },
  {
    q: 'The international organization founded in 1945 to succeed the League of Nations was the:',
    opts: ['United Nations', 'World Council', 'Allied Assembly', 'Global Compact'],
    a: 0,
    e: 'The United Nations was established in 1945 to promote international cooperation and prevent future wars.',
    tags: ['world wars', 'wwii'],
  },
];
