// CSS, rebalanced: six levels of the browser, not of one library's vocabulary.
//
// The old nine-level path spent its final three levels — a third of the course —
// on Tailwind and styling approaches, and one of those questions asserted that
// theme configuration belongs in a config file, which stopped being true when
// Tailwind moved theming into CSS with `@theme`. Meanwhile the cascade, the box
// model and layout debugging — the things that decide whether a bug takes two
// minutes or an afternoon — got one level each.
//
// So the scope is six levels of the underlying model: the cascade, the box and
// flow, Flexbox, Grid and responsiveness, positioning and stacking, and
// maintainable accessible styling. A styling tool is a way of writing these
// down; none of them stops being true because a class name is doing the
// writing.
//
// Where a question depends on a version or a context, it says so, because "it
// depends" is the honest answer to most CSS questions and the useful part is
// what it depends on.
//
// Authored for devShark. See docs/curriculum-retirement.md.

import type { Seed } from './roadmap-build';

export const cssCoreSeeds: Seed[] = [
  // ── Level 1 — Cascade, inheritance, selectors and scope ────────────────
  { q: 'Two rules in the same stylesheet set `color` on the same element: `.card p` and `p`. Assuming no layers and no `!important`, which wins?', opts: ['`p`, because it is simpler', '`.card p`, because its selector is more specific', 'Whichever appears later in the file', 'Neither — the declaration is dropped'], a: 1, e: '`.card p` is 0-1-1 (one class, one type) and `p` is 0-0-1. The cascade compares specificity before source order, so `.card p` wins wherever both match, even if `p` comes later in the file. Order only breaks ties between selectors of equal specificity, and the losing declaration is not dropped — it simply is not applied to that element.', intro: 'Write each selector\'s specificity as id-class-type counts before you look at where the rules sit in the file.', tags: ['CSS', 'Cascade'] },
  { q: 'Two rules in the same stylesheet, with no layers and no `!important`, have identical specificity and set the same property. What decides which one applies?', opts: ['The one written first', 'The one written last', 'The one with the shorter selector', 'The one that matches more elements'], a: 1, e: 'When origin, layer, importance and specificity all tie, the last declaration in source order wins. That is why the order of imported stylesheets matters: a library imported after your overrides silently undoes them. Selector length and how many elements a rule matches play no part in the cascade.', intro: 'Specificity is a tie here, so the cascade falls through to its last criterion. Think about what changes when you move one rule further down the file.', tags: ['CSS', 'Cascade'] },
  { q: 'A declaration is marked `!important`. What has that actually changed?', opts: ['Its selector\'s specificity is increased', 'It is ranked by importance, above every normal declaration', 'It is applied earlier than the other rules', 'It starts inheriting to descendant elements'], a: 1, e: 'The cascade sorts by origin and importance before it looks at specificity, and an important author declaration outranks every normal declaration whatever its selector. That is why a more specific selector cannot beat an `!important` and only another `!important` can — and why it is worth avoiding rather than winning. The flag changes nothing about specificity, order or inheritance.', intro: 'Specificity, origin and importance are separate steps of the cascade. Work out which of them the `!important` flag actually touches.', tags: ['CSS', 'Cascade'] },
  { q: 'Which of these properties is inherited by default?', opts: ['`border`', '`color`', '`padding`', '`display`'], a: 1, e: '`color` inherits: text inside a coloured paragraph takes the same colour unless something overrides it. `border`, `padding` and `display` are box properties and start from their initial value on every element — a border on every descendant of a bordered box would be unusable. The rule of thumb is that text-related properties inherit and box-related ones do not; any property can be forced either way with `inherit` or `initial`.', intro: 'Ask which of these four you would want to flow from a paragraph down into a `<span>` inside it, and which would look wrong if it did.', tags: ['CSS', 'Cascade'] },
  { q: 'What do cascade layers (`@layer`) let you express that specificity alone cannot?', opts: ['Faster matching for the selectors inside the layer', 'A whole group of rules that loses to a later group whatever their selectors', 'Styles that are scoped to a single component subtree', 'Styles that apply only while a condition holds'], a: 1, e: 'Layer order is decided before specificity: for normal declarations a later layer beats an earlier one whatever the selectors say, and unlayered styles beat every layer. That is how a library\'s styles can be made to lose to yours without escalating selectors. Scoping (`@scope`) and conditions (`@media`, `@supports`) are different tools, and layers do nothing for matching speed. Note that `!important` reverses the layer order.', intro: 'Specificity compares single selectors. Ask what you would need in order to rank an entire stylesheet below another without editing any selector.', tags: ['CSS', 'Cascade'] },
  { q: 'In the selector `:is(h2, #hero) .badge`, what specificity does the `:is()` part contribute?', opts: ['That of its first argument, `h2`', 'That of its most specific argument, `#hero`', 'The sum of all its arguments', 'None — it contributes zero specificity'], a: 1, e: '`:is()` takes the specificity of its most specific argument, so `:is(h2, #hero)` counts as an id (1-0-0) and the whole selector is 1-1-0 with `.badge`. Taking the first argument would give 0-1-1, adding both would give 1-1-1, and zero is what `:where()` does — which is the usual reason to choose one over the other.', intro: 'Its two arguments have different weights. Recall how `:is()` resolves that, and how `:where()` differs.', tags: ['CSS', 'Selectors'] },
  { q: 'What does `.card:has(> img)` select?', opts: ['The images that are direct children of a card', 'Cards that have an image as a direct child', 'Cards that contain an image anywhere inside them', 'The first card in the document that contains an image'], a: 1, e: '`:has()` matches the element it is attached to when the relative selector inside it finds something: here a `.card` whose direct child is an `img`. The image itself is never the subject, `:has(img)` without the `>` would accept an image anywhere in the subtree, and nothing limits it to the first card. `:has()` has been available in all major browsers since December 2023.', intro: 'Ask which element is the subject of the selector: the one before the parentheses or the one inside them. Then read `>` as you would anywhere else.', tags: ['CSS', 'Selectors'] },
  { q: 'A style applies to an element in one page and not another. The markup and the selectors are identical on both pages. What is worth checking first?', opts: ['Whether the two pages declare a different character encoding', 'Whether the pages load their stylesheets in a different order or layer', 'Whether the element has a different tag name on each page', 'Whether the browser has CSS enabled on the second page'], a: 1, e: 'With identical selectors, specificity is a tie, so origin, layer and source order decided — and those are exactly what differs when two pages include stylesheets in a different order or wrap one in `@layer`. The Computed panel in DevTools shows which rule won and where it came from, which is faster than reading either file. Encoding and the tag name do not change a rule\'s rank, and CSS is not switched off per page.', intro: 'Identical selectors mean specificity cannot be the difference. List the cascade criteria that are left and ask which of them a page can change.', tags: ['CSS', 'Cascade'] },

  // ── Level 2 — Box model, flow, sizing and overflow ─────────────────────
  { q: 'An element has `width: 300px`, `padding: 20px` and `border: 5px solid`, under `box-sizing: content-box`. How wide is its border box?', opts: ['300px', '350px', '345px', '325px'], a: 1, e: 'Under `content-box`, `width: 300px` sizes the content only, so the border box is 300 + 20 + 20 of padding + 5 + 5 of border = 350px. 345 and 325 come from counting a side once — both padding and border are added on the left and the right. This is why nearly every codebase sets `box-sizing: border-box` globally, where `width: 300px` would mean a 300px border box.', intro: 'Padding and border each have a left and a right side. Decide what `width` measures under `content-box` before you add anything.', tags: ['CSS', 'Box model'] },
  { q: 'What does `box-sizing: border-box` change?', opts: ['The border is drawn inside the padding', '`width` includes padding and border rather than only the content', 'Margins stop collapsing', 'The element becomes a block'], a: 1, e: '`border-box` makes `width` and `height` measure the border box, so `width: 300px` is 300px on screen with padding and border fitted inside. It does not move the border inside the padding, does not affect margins — which sit outside the border box either way and still collapse — and has nothing to do with `display`.', intro: 'Think about which parts of the box a declared `width` is measured across, and whether that changes anything outside the border.', tags: ['CSS', 'Box model'] },
  { q: 'Two stacked block elements have `margin-bottom: 20px` and `margin-top: 30px`. What is the gap in normal flow?', opts: ['50px', '30px', '20px', '0'], a: 1, e: 'Adjacent vertical margins in normal flow collapse into one margin the size of the larger, so the gap is 30px, not 50px. Collapsing only happens in the block direction and only in normal flow: flex items and grid items keep their margins, which is one reason spacing is easier to reason about with `gap`.', intro: 'Two block margins meet here. Recall what normal flow does when vertical margins touch — it is not the same as for horizontal margins.', tags: ['CSS', 'Box model'] },
  { q: 'What does `min-height: 100%` on a child depend on?', opts: ['The viewport height', 'The parent having a definite height', 'The child\'s own content height', 'The total document height'], a: 1, e: 'A percentage height resolves against the containing block\'s height, and when that height is `auto` (it depends on content) the percentage is treated as 0, so the rule does nothing. It is not the viewport or the document, which is why the pattern usually appears as `min-height: 100vh` (or `100dvh`) on the outermost element — or the parent is made a flex or grid container and stretches the child instead of relying on a percentage.', intro: 'A percentage is a fraction of something. Identify what `min-height: 100%` is a fraction of, and what happens when that something is `auto`.', tags: ['CSS', 'Sizing'] },
  { q: 'A long unbroken string overflows its container. Which property addresses it directly?', opts: ['`text-overflow: ellipsis`', '`overflow-wrap: anywhere`', '`white-space: nowrap`', '`overflow: hidden`'], a: 1, e: 'The string has no break opportunity, so the fix is permission to break inside a word: `overflow-wrap: anywhere` (or `break-word`). `overflow: hidden` clips the symptom, `white-space: nowrap` removes even the breaks you had, and `text-overflow: ellipsis` only decorates a clipped single line — it needs `overflow: hidden` and `nowrap` before it shows anything.', intro: 'Separate the properties that hide or measure overflow from the one that creates a new place where a line may break.', tags: ['CSS', 'Overflow'] },
  { q: 'A page scrolls horizontally on a phone and nobody knows why. What is the most efficient way to find the cause?', opts: ['Set `overflow-x: hidden` on the body and move on', 'Find the element that is wider than the viewport, by outline or by script', 'Remove the media queries one at a time until it stops', 'Reduce the base font size until the scrollbar disappears'], a: 1, e: 'Something is wider than the viewport, and the fix belongs on that element, so the efficient move is to find it: `* { outline: 1px solid red }` or a small script comparing each element\'s right edge with `document.documentElement.clientWidth`. `overflow-x: hidden` on the body hides the evidence and often traps content off-screen where it cannot be reached; removing queries or shrinking type is guesswork.', intro: 'Horizontal scroll is a symptom. Ask what must be true of at least one element for the page to scroll sideways, and start from that.', tags: ['CSS', 'Overflow'] },
  { q: 'What is the difference between `1rem` and `1em` for a font size?', opts: ['They are identical for font sizes', '`rem` is relative to the root font size; `em` to the inherited font size', '`em` is an absolute unit; `rem` is relative', '`rem` is relative to the viewport width'], a: 1, e: '`rem` reads the root element\'s font size; `em` on `font-size` reads the inherited font size, so `em` compounds through nesting — three levels of `0.9em` give 0.729 of the start, not 0.9. `rem` is stable, which makes it the safer default for type, and both follow the user\'s browser font-size setting, which `px` does not. Neither unit is absolute or viewport-based.', intro: 'Ask what each unit measures against, then follow a list nested three levels deep and watch which unit\'s computed size changes at each level.', tags: ['CSS', 'Sizing'] },
  { q: 'Two items in a flex row are each given `width: 50%`, and the container has `gap: 16px`. What does each `50%` resolve against?', opts: ['Half of the space left after the gap is subtracted', 'Half of the flex container\'s content box, ignoring the gap and the sibling', 'Half of the item\'s own content width', 'Half of the viewport width'], a: 1, e: 'A percentage width on a flex item resolves against the flex container\'s content box, so two `50%` items plus a 16px gap add up to more than the row. Flexbox then shrinks them because `flex-shrink` defaults to 1, and with `flex-shrink: 0` they overflow. `flex: 1` sizes from the free space that is left after the gap, which is what the layout wants to say; the item\'s own content and the viewport play no part.', intro: 'A percentage width is resolved before flex distributes anything. Identify the containing block it reads, and ask whether that box knows about `gap`.', tags: ['CSS', 'Sizing'] },

  // ── Level 3 — Flexbox ──────────────────────────────────────────────────
  { q: 'In a flex container with `flex-direction: row`, which axis does `justify-content` act on?', opts: ['The cross axis, which runs vertically here', 'The main axis, which runs horizontally here', 'Both axes at the same time', 'Whichever axis has free space left'], a: 1, e: '`justify-content` distributes items along the main axis, and `flex-direction: row` makes the main axis the inline (horizontal) axis in a horizontal writing mode; `align-items` handles the cross axis. Switch to `column` and the two swap, which is where most flex confusion starts. No property acts on both axes at once, and free space does not choose the axis.', intro: 'First decide which axis `flex-direction: row` makes the main axis; then recall which of the two alignment properties belongs to it.', tags: ['CSS', 'Flexbox'] },
  { q: 'What does `flex: 1` expand to?', opts: ['`flex-grow: 1`, `flex-shrink: 1`, `flex-basis: 0%`', '`flex-grow: 1` only', '`flex-basis: 1`', '`flex-grow: 1`, `flex-shrink: 0`, `flex-basis: auto`'], a: 0, e: '`flex: 1` is `flex: 1 1 0%`: grow 1, shrink 1, basis 0%. The basis of 0% is the part people miss — every item starts from nothing and the free space is shared equally regardless of content. `flex: auto` (`1 1 auto`) keeps the content or `width` as the starting size and shares only the leftover, and the default `flex: initial` (`0 1 auto`) does not grow at all.', intro: 'A single unitless number sets `flex-grow`. Recall what the shorthand chooses for the other two longhands when you leave them out.', tags: ['CSS', 'Flexbox'] },
  { q: 'Flex items overflow the container instead of wrapping. What is the likeliest cause?', opts: ['`flex-wrap` was left at its default, `nowrap`', '`justify-content` was set to the wrong value', 'The container was never given an explicit width', '`align-items` was left at its default, `stretch`'], a: 0, e: 'A flex container lays its items out on a single line unless `flex-wrap` says otherwise, because the initial value is `nowrap`, so on a narrow screen the row keeps going past the edge. `justify-content` and `align-items` only place items within the space; they never create a second line. A missing width does not cause it either — the container already takes its width from its parent.', intro: 'Ask what a flex container does with items that no longer fit on one line when nothing has told it otherwise.', tags: ['CSS', 'Flexbox'] },
  { q: 'A flex item with long text refuses to shrink below its content. What usually fixes it?', opts: ['`flex-shrink: 0`', '`min-width: 0` on the item', '`overflow: hidden` on the container', '`width: auto`'], a: 1, e: 'A flex item\'s `min-width` is `auto`, which for flex items means its min-content size, so it will not shrink past its longest unbreakable content. `min-width: 0` releases that floor and is the standard fix for a truncating label that refuses to truncate. `flex-shrink: 0` does the opposite, `width: auto` is already the default, and `overflow: hidden` only helps on the item itself — a scroll container gets an automatic minimum of 0 — not on the container.', intro: 'Flex items have an automatic minimum size along the main axis. Ask what that minimum is based on, and which declaration would lower it.', tags: ['CSS', 'Flexbox'] },
  { q: 'What is the difference between `align-items` and `align-content` in a wrapping flex container?', opts: ['`align-items` spaces the lines; `align-content` aligns items within their line', '`align-items` aligns items within their line; `align-content` spaces the lines', '`align-content` only works inside grid containers', '`align-items` only works when `flex-wrap` is `nowrap`'], a: 1, e: '`align-items` positions each item inside its own flex line; `align-content` distributes the lines themselves along the cross axis. With a single line there is nothing to distribute, so `align-content` appears to do nothing until the container wraps — which is why it looks broken at first. It applies to flex, grid and block containers, and `align-items` works regardless of wrapping.', intro: 'A wrapping container has two things to align on the cross axis: the items and the lines they sit in. Decide which property owns which.', tags: ['CSS', 'Flexbox'] },
  { q: 'Which is the more robust way to space flex items evenly with a fixed gap?', opts: ['`margin-right` on every item, negated on the last', '`gap`', '`justify-content: space-between`', 'A spacer element between items'], a: 1, e: '`gap` puts a fixed space between items and nowhere else, so nothing needs negating on the last item and wrapping keeps the spacing on every line. `margin-right` needs a special case and breaks at the wrap point, spacer elements are markup for a styling job, and `space-between` distributes whatever space is left over — a different thing that varies with the container width.', intro: 'Think about what happens to each option when the row wraps onto a second line.', tags: ['CSS', 'Flexbox'] },
  { q: 'An icon and a label sit in a flex row and the icon squashes on narrow screens. What is the fix?', opts: ['`flex-shrink: 0` on the icon', '`align-items: center`', '`flex-wrap: wrap`', '`min-width` on the container'], a: 0, e: 'Every flex item shrinks by default (`flex-shrink: 1`), so the icon and the label both lose width. `flex-shrink: 0` on the icon takes it out of the shrinking, which concentrates it on the text — the thing that can wrap. `align-items` only affects the cross axis, `flex-wrap` would push the label under the icon, and a `min-width` on the container does not protect any item inside it.', intro: 'Both items are being asked to give up space. Think about the per-item property that decides how much each one gives.', tags: ['CSS', 'Flexbox'] },
  { q: 'When is Flexbox a better fit than Grid?', opts: ['Whenever the container holds more than one item', 'When the layout runs in one dimension and sizes come from the content', 'Whenever the layout has to respond to the viewport', 'Whenever items need aligning on an axis'], a: 1, e: 'Flexbox distributes along one axis from the content out; Grid defines a structure in both dimensions and places items into it. A toolbar is flex; a page skeleton is grid, and mixing them per level is normal. Both respond to the viewport and both align items, so neither of those decides — and if you find yourself fixing widths on flex items to line them up with the row above, you wanted a grid.', intro: 'Both methods align items and both respond to width, so neither settles it. Ask what each one needs you to define before it lays anything out.', tags: ['CSS', 'Flexbox'] },

  // ── Level 4 — Grid and responsive layout ───────────────────────────────
  { q: 'What does `grid-template-columns: repeat(auto-fit, minmax(200px, 1fr))` produce?', opts: ['Exactly three columns at every width', 'As many columns of at least 200px as fit, sharing leftover space', 'One column per grid item, however many there are', 'A fixed grid of 200px columns with no growth'], a: 1, e: '`auto-fit` fits as many tracks as the width allows, `minmax(200px, 1fr)` makes each track at least 200px and lets it grow, and `1fr` shares the leftover space, so the column count follows the container width with no media query. It responds to the container rather than the viewport, which is usually the better answer. The width decides how many tracks fit rather than the item count, and nothing here is fixed at 200px; `auto-fit` only differs from `auto-fill` in collapsing tracks that end up empty.', intro: 'Take the three pieces in turn: what `repeat()` with a keyword counts, what `minmax()` bounds, and what `1fr` does with leftover space.', tags: ['CSS', 'Grid'] },
  { q: 'A grid uses `repeat(auto-fit, minmax(200px, 1fr))`, or the same with `auto-fill`. What is the difference when there are fewer items than tracks?', opts: ['None — they are two names for one behaviour', '`auto-fit` collapses the empty tracks so items stretch; `auto-fill` keeps them', '`auto-fill` collapses the empty tracks; `auto-fit` keeps them', '`auto-fit` creates extra tracks until the row is full'], a: 1, e: 'Both create as many tracks as fit; the difference is what happens to the tracks left empty. `auto-fit` collapses them to 0px so the items that exist stretch across the width, while `auto-fill` keeps them, leaving the items narrow with a gap beside them. With a full row there is nothing to collapse and the two are identical, which is why the difference goes unnoticed until a row is short.', intro: 'Picture a row with room for four tracks and only two items. Ask what each keyword does with the two tracks nobody fills.', tags: ['CSS', 'Grid'] },
  { q: 'What does the `fr` unit distribute?', opts: ['The total container width', 'The space left after fixed sizes and gaps are taken', 'A fraction of the viewport', 'A fraction of the content width'], a: 1, e: '`fr` is a share of the leftover space: fixed tracks and gaps are subtracted first and the fractions divide what remains, which is why `200px 1fr` works and adding a gap does not break the arithmetic. It is not a fraction of the whole container, of the viewport or of the content width — a fraction of the total would overflow as soon as a fixed track is present.', intro: 'Test each option against `grid-template-columns: 200px 1fr`: which one still gives a sensible answer while the fixed track is present?', tags: ['CSS', 'Grid'] },
  { q: 'A grid item with long content refuses to shrink and pushes the layout wide. What is the usual cause?', opts: ['The `gap` between the tracks is too large', '`1fr` has an `auto` minimum, so the track will not go below its content', 'The grid container was never given a width', '`fr` tracks can grow but are never allowed to shrink'], a: 1, e: '`1fr` outside `minmax()` means `minmax(auto, 1fr)`, and an `auto` minimum is the largest minimum size of the items in the track — their min-content size for most items — so the track refuses to go below the longest unbreakable content. `minmax(0, 1fr)` (or `min-width: 0` on the item) releases the floor, the same shape as the flex fix. `fr` tracks do shrink otherwise, and neither the gap nor a missing container width creates this.', intro: '`1fr` is shorthand for a `minmax()`. Write out what its minimum is, then ask what that minimum is measured from.', tags: ['CSS', 'Grid'] },
  { q: 'A media query breakpoint is chosen at 768px because that is a common tablet width. What is the better basis?', opts: ['The most popular device sizes this year', 'The width at which this layout stops working', 'The nearest round number', 'The design tool’s default artboards'], a: 1, e: 'A breakpoint exists to fix a layout that stops working, so the right place for it is the width at which that happens: narrow the window until the content squashes or overflows and put the query there. Device widths change every year and there are too many of them, round numbers and artboards are arbitrary, and a breakpoint tied to the layout stays right when the devices change.', intro: 'Ask what a breakpoint is protecting — the content or the device — and which of those changes more often.', tags: ['CSS', 'Responsive'] },
  { q: 'What does a container query let you do that a media query cannot?', opts: ['Respond to the user\'s system preferences', 'Style a component by the size of its container, not the viewport', 'Respond to the model of device in use', 'Apply styles depending on the scroll position'], a: 1, e: 'A card in a sidebar and the same card in a main column want different layouts at the same viewport width; a media query cannot tell them apart, while a container query asks the container\'s size, which is the question that actually decides. It needs an ancestor with `container-type: inline-size` (or `size`) to measure against. User preferences are media features (`prefers-reduced-motion`), the device model is not queryable at all, and scroll position is not what a size query answers.', intro: 'The same card sits in a narrow sidebar and in a wide main column at one viewport width. Ask which question each kind of query can answer.', tags: ['CSS', 'Responsive'] },
  { q: 'A stylesheet is written mobile-first. Why are its breakpoints expressed as `min-width` (or `width >=`) rather than `max-width`?', opts: ['`min-width` queries evaluate faster', 'The base styles serve small screens and each breakpoint adds to them', '`max-width` queries have poorer browser support', '`min-width` queries avoid specificity conflicts'], a: 1, e: 'Mobile-first means the base styles need no query at all and each `min-width` breakpoint adds what a wider screen can use, so the sheet reads as a series of additions. `max-width` (desktop-first) works equally well and has the same support and speed; what produces rules that fight is mixing both directions in one stylesheet. Specificity is unaffected — declarations inside a media query keep their selector\'s specificity.', intro: 'Decide which screen the un-queried base styles are written for; the direction of the breakpoints has to follow from that.', tags: ['CSS', 'Responsive'] },
  { q: 'Which layout still has a legitimate use for `float`?', opts: ['A two-column page', 'Wrapping text around an image or a pull quote', 'A card grid', 'A sticky header'], a: 1, e: '`float` takes an element out of normal flow and lets the text and inline content that follows wrap around it, which is exactly what a figure or pull quote inside an article needs and what nothing else does as simply. Page columns and card grids were the workaround era; Flexbox and Grid replaced them, and a sticky header is `position: sticky`.', intro: 'Recall what `float` does to the text that follows it, and ask which of the four layouts needs exactly that effect.', tags: ['CSS', 'Layout'] },

  // ── Level 5 — Positioning and stacking ─────────────────────────────────
  { q: 'What is `position: absolute` positioned relative to?', opts: ['The viewport, in every case', 'The nearest positioned ancestor, else the initial containing block', 'Its direct parent, in every case', 'The `<body>` element, in every case'], a: 1, e: 'An absolutely positioned box is placed relative to the padding box of its nearest ancestor whose `position` is anything other than `static`; if there is none, the initial containing block — the viewport-sized rectangle at the top of the document — is used. A dropdown that escapes to the page corner is nearly always this: the intended ancestor was never given `position: relative`. An ancestor with a `transform` or `filter` also becomes the containing block, which is a separate surprise.', intro: 'The parent is not automatically the reference. Ask what an ancestor must have for an absolutely positioned child to measure from it.', tags: ['CSS', 'Positioning'] },
  { q: 'What does `position: sticky` need in order to do anything?', opts: ['A `z-index` higher than its siblings', 'An inset such as `top`, plus an ancestor that can actually scroll', 'A fixed height on the element itself', '`overflow: hidden` on its parent element'], a: 1, e: 'Without an inset (`top`, `bottom`, …) sticky has no threshold and behaves as `relative`, and it sticks within its nearest ancestor that has a scrolling mechanism. An ancestor with `overflow: hidden` counts as that mechanism even though it never scrolls, which is the commonest reason a correct-looking sticky does nothing — so `overflow: hidden` on the parent is the cause of the failure, not a requirement. `z-index` and a fixed height are unrelated.', intro: 'Sticky is "relative until a threshold, then pinned". Ask what defines the threshold and what has to move for it to be reached.', tags: ['CSS', 'Positioning'] },
  { q: 'A `position: fixed` modal with `z-index: 9999` still renders behind the site header. What is the likeliest cause?', opts: ['9999 is not high enough to beat the header', 'The modal sits inside a stacking context that ranks below the header', 'The header uses `position: fixed`, which always paints on top', 'The header comes later in the DOM, so it paints last'], a: 1, e: 'z-index is compared within a stacking context, not globally. A transform, a filter, an opacity below 1 or a positioned ancestor with its own z-index creates one, and the modal\'s 9999 then only ranks it among its siblings inside that context — the context as a whole sits wherever its root does, however large the number. A larger value cannot escape it, `position: fixed` does not paint on top by itself, and DOM order only breaks ties at the same level.', intro: 'A z-index is not compared against the whole page. Ask what it is compared within, and what decides where that group as a whole sits.', tags: ['CSS', 'Stacking'] },
  { q: 'Which of these creates a new stacking context?', opts: ['`position: relative` with no `z-index`', '`opacity: 0.99`', '`overflow: hidden`', '`display: flex`'], a: 1, e: 'Any `opacity` below 1 creates a stacking context, as do `transform`, `filter`, `will-change` naming such a property, and a positioned element with a z-index other than `auto`. `position: relative` on its own (z-index `auto`) does not, `overflow: hidden` only clips, and `display: flex` creates a formatting context — a flex *item* gets a stacking context only when it has a z-index. That is why an animation added for polish can reorder a layout that was working.', intro: 'Being positioned is not enough on its own. Recall the short list of values that create a stacking context and check each of these four against it.', tags: ['CSS', 'Stacking'] },
  { q: 'What is the containing block for a `position: fixed` element in the ordinary case?', opts: ['Its parent', 'The viewport', 'The document', 'The nearest positioned ancestor'], a: 1, e: 'In the ordinary case the containing block is the viewport, which is why a fixed header stays put while the document scrolls. The exception is an ancestor with a `transform`, `filter`, `perspective`, `will-change` naming one of those, or `contain: paint`: it becomes the containing block, and a fixed header that scrolls away inside a transformed section is exactly this. The nearest positioned ancestor is the rule for `absolute` rather than `fixed`, and neither the parent nor the document is a containing block on its own.', intro: 'Scroll the page in your head: what does a fixed element keep its distance from, and which ancestor properties can quietly change that?', tags: ['CSS', 'Positioning'] },
  { q: 'A tooltip is clipped by its parent. Which property on an ancestor is the likely cause?', opts: ['`position: relative`', '`overflow: hidden`', '`z-index: 0`', '`display: flex`'], a: 1, e: 'Clipping comes from overflow: an ancestor with `overflow: hidden` (or `auto`/`scroll`) cuts everything that spills past its padding box, including a tooltip positioned outside it. `z-index` decides painting order, not visibility, so raising it changes nothing; `position: relative` only sets a reference point and `display: flex` only lays out children. The tooltip has to leave the clipping ancestor, or the ancestor has to stop clipping.', intro: 'Clipping and stacking are different questions. Decide which of the four properties changes what part of a box\'s content can be painted at all.', tags: ['CSS', 'Positioning'] },
  { q: 'What does `inset: 0` on an absolutely positioned element do?', opts: ['Adds zero padding on all four sides', 'Sets all four offsets to 0, stretching it across its containing block', 'Centres it inside its containing block', 'Sets a zero margin on all four sides'], a: 1, e: '`inset` is the shorthand for `top`, `right`, `bottom` and `left`, so `inset: 0` pins all four edges to the containing block. With `width` and `height` left `auto`, an absolutely positioned box solves for its size from the pinned edges and fills the block — the standard overlay. It has no effect on non-positioned elements, and it is not padding, margin or centring (centring needs `margin: auto` on top of it).', intro: 'Name the four longhands `inset` stands for. Then ask what an absolutely positioned box with `auto` width does when both of its horizontal edges are set.', tags: ['CSS', 'Positioning'] },
  { q: 'A dropdown must escape a parent that clips it. Which approach solves it structurally?', opts: ['Give the dropdown a larger `z-index` than the ancestor', 'Render it outside the clipping ancestor: a portal, or the top layer via `popover`', 'Remove the padding from the clipping ancestor', 'Set `overflow: visible` on the dropdown itself'], a: 1, e: 'Clipping is decided by the ancestor, so the fix is to not be inside it: render the dropdown elsewhere in the tree (a portal) or put it in the top layer with the `popover` attribute or a `<dialog>`, which paints above everything without depending on stacking order or ancestors\' overflow. A z-index never overrides clipping, `overflow: visible` on the child does not undo the parent\'s clip, and padding is unrelated. Popover has been available in all major browsers since January 2025.', intro: 'The clip is applied by an ancestor to everything inside it. Ask which option changes where the dropdown is, rather than how it is painted.', tags: ['CSS', 'Stacking'] },

  // ── Level 6 — Maintainable, accessible styling ─────────────────────────
  { q: 'What does a custom property (`--brand: green`) give you that a preprocessor variable does not?', opts: ['Smaller stylesheets after the build step', 'A live value in the browser that cascades, inherits and can change per element', 'Support in browsers older than the preprocessor', 'Type checking of the value at build time'], a: 1, e: 'A preprocessor variable is substituted at build time and is gone before the browser sees the file. A custom property is live: it participates in the cascade, inherits down the tree, can be redefined on any element and read or set from JavaScript — which is what makes theming by scope possible at all. It does not shrink files, older browsers handle preprocessor output better, and neither kind is type checked at build time; `@property` can constrain a custom property\'s value, but only in the browser.', intro: 'Ask what is left of each kind of variable once the browser receives the stylesheet.', tags: ['CSS', 'Architecture'] },
  { q: 'A theme is defined with custom properties on `:root`, and one component needs a different accent. What is the cheapest correct change?', opts: ['Redefine the property on that component’s own element', 'Add an `!important` override for each affected rule', 'Duplicate the component’s styles', 'Add a second stylesheet'], a: 0, e: 'Custom properties inherit, so redefining the accent token on the component\'s own element reskins everything under it that reads the token — no rule inside the component changes. That is the whole design: components read the token and never the value. `!important` overrides fight the cascade rule by rule, duplicated styles drift apart, and a second stylesheet still has to override each declaration.', intro: 'The component\'s rules read the token, not the colour. Ask where a new value has to be declared for everything inside the component to pick it up.', tags: ['CSS', 'Architecture'] },
  { q: 'Where does Tailwind v4 expect theme tokens to be defined?', opts: ['In a JavaScript config file', 'In CSS, using `@theme`', 'In an inline `style` attribute', 'In a JSON file'], a: 1, e: 'Version 4 moved theming into CSS with `@theme`; the JavaScript config was the v3 answer. State the version when a syntax question depends on it — an unqualified "the config file" is now wrong.', tags: ['CSS', 'Tooling'] },
  { q: 'What does a utility-class approach change about the cascade?', opts: ['Nothing: the cascade is bypassed entirely', 'Every rule has the same low specificity, so which class is applied decides', 'Inheritance is switched off for utility-styled elements', 'Specificity is raised so each utility always wins'], a: 1, e: 'Every utility is a single class selector at 0-1-0, so nothing in the sheet outranks anything else: the cascade is not gone, it simply never has a specificity contest to run. You control the result by choosing which classes go on the element, and when two applied utilities set the same property, the later one in the generated stylesheet wins. Inheritance and the box model are untouched underneath, and no utility raises specificity.', intro: 'Write out the specificity of `.p-4` and `.mt-2`. Ask what is left for the cascade to decide when every rule in the sheet looks like that.', tags: ['CSS', 'Tooling'] },
  { q: 'Why is `outline: none` on `:focus` a problem?', opts: ['It breaks the layout', 'It removes the only indication a keyboard user has of where they are', 'It disables the click handler', 'It is invalid CSS'], a: 1, e: 'The focus ring is how someone who is not using a mouse knows what Enter will activate; `outline: none` on `:focus` removes that with nothing in its place, and keyboard navigation becomes guesswork for sighted users. If the default ring clashes with the design, replace it with a visible one — `:focus-visible` shows it for keyboard use and not for mouse clicks. The declaration is valid CSS, and it changes neither layout nor event handlers.', intro: 'Think about who navigates with Tab rather than a pointer, and what changes for them when the outline goes.', tags: ['CSS', 'Accessibility'] },
  { q: 'A status is shown by turning text red. What is missing?', opts: ['A larger font', 'A cue that is not colour — a word, an icon, or a shape', 'A higher z-index', 'A transition'], a: 1, e: 'Colour alone excludes anyone who cannot distinguish it, disappears in high-contrast modes and on poor screens, and is invisible to a screen reader; WCAG 1.4.1 says colour must not be the only visual means of conveying information. The word "Error" or an icon beside the red does the work for everyone. Font size, z-index and transitions change nothing about whether the meaning is perceivable.', intro: 'Imagine the same screen in greyscale, or read aloud. Ask what still tells the user that something went wrong.', tags: ['CSS', 'Accessibility'] },
  { q: 'A card lifts (`transform`) and fades in (`opacity`) when it appears. Inside `@media (prefers-reduced-motion: reduce)`, which change respects the setting without losing the feedback?', opts: ['Leave both as they are — it is only a preference', 'Remove the movement and keep the fade', 'Remove both the movement and the fade', 'Make both faster so they finish sooner'], a: 1, e: 'The preference exists mainly for vestibular discomfort, which movement — scaling, sliding, panning — causes and an opacity change does not, so freezing the transform is the change that matters. Removing the fade too loses the feedback for no benefit, ignoring the setting is what the media query is there to prevent, and faster motion is still motion.', intro: 'The setting is about motion, not about change. Ask which of the two effects moves anything across the screen.', tags: ['CSS', 'Accessibility'] },
  { q: 'A layout is correct at 100% zoom and unusable at 200%. Which choice is the likeliest cause?', opts: ['Using `rem` for spacing', 'Fixed pixel heights on containers holding text', 'Using Grid', 'Using custom properties'], a: 1, e: 'Zooming makes the text larger and a fixed `height` does not follow, so the content overflows or is clipped — WCAG 1.4.4 requires text to resize to 200% without loss of content, and 1.4.10 requires reflow without two-dimensional scrolling. Sizing from the content with `min-height` survives it. `rem` spacing scales with the text, Grid and custom properties are neutral, and zoom is the cheapest accessibility test there is.', intro: 'Zoom enlarges the text. Ask which of the four choices stops the box around that text from growing with it.', tags: ['CSS', 'Accessibility'] },
];
