// Rules & Betting roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const rulesFormatsSeeds: Seed[] = [
  // ── Level 1 — The flow of a hand ──
  { q: 'How many private hole cards does each player receive in Texas Hold\'em?', opts: ['Two', 'One', 'Three', 'Four'], a: 0, e: 'Every player is dealt two face-down hole cards that only they can use.', tags: ['Poker', 'Hand flow'] },
  { q: 'What is the "flop" in Texas Hold\'em?', opts: ['The first three community cards, dealt at once', 'A single face-up card', 'The final community card', 'A player\'s hole cards'], a: 0, e: 'The flop is three shared community cards dealt face up together after the first betting round.', tags: ['Poker', 'Hand flow'] },
  { q: 'In what order are the community cards revealed?', opts: ['Flop, turn, river', 'Turn, flop, river', 'River, turn, flop', 'Flop, river, turn'], a: 0, e: 'Community cards come out as the flop (3 cards), then the turn (1 card), then the river (1 card).', tags: ['Poker', 'Hand flow'] },
  { q: 'How many community cards are on the board by the river?', opts: ['Five', 'Three', 'Four', 'Seven'], a: 0, e: 'The flop (3), turn (1), and river (1) give five shared community cards in total.', tags: ['Poker', 'Hand flow'] },
  { q: 'What is the river?', opts: ['The fifth and final community card', 'The first community card', 'A player\'s hole card', 'The fourth betting round bet'], a: 0, e: 'The river is the fifth and last community card, dealt before the final betting round.', tags: ['Poker', 'Hand flow'] },
  { q: 'What forced bets get chips into the pot before any cards are dealt?', opts: ['The small blind and big blind', 'A single ante only', 'Nothing is posted', 'The winner\'s share'], a: 0, e: 'In Hold\'em two players post the small and big blinds so there is money to play for each hand.', tags: ['Poker', 'Hand flow'] },
  { q: 'What is the showdown?', opts: ['Remaining players reveal their hands to decide the winner', 'The initial deal of hole cards', 'The shuffle before a hand', 'The moment the flop appears'], a: 0, e: 'If two or more players remain after the last bet, they show cards and the best hand wins.', tags: ['Poker', 'Hand flow'] },
  { q: 'In Hold\'em, a player\'s final hand is the best five cards chosen from which pool?', opts: ['Their two hole cards plus the five community cards', 'Only their two hole cards', 'Only the five community cards', 'Exactly one hole card and the board'], a: 0, e: 'Each player makes the best five-card hand from the seven available: two hole cards and five community cards.', tags: ['Poker', 'Hand flow'] },

  // ── Level 2 — Betting actions & rounds ──
  { q: 'What does it mean to "check"?', opts: ['Decline to bet while staying in, when no bet is owed', 'Match the current bet', 'Increase the current bet', 'Give up your hand'], a: 0, e: 'Checking passes the action without wagering, and is only allowed when no bet has been made in the round.', tags: ['Poker', 'Betting actions'] },
  { q: 'What does it mean to "fold"?', opts: ['Discard your hand and give up any claim to the pot', 'Match the current bet', 'Raise the bet', 'Check to the next player'], a: 0, e: 'Folding forfeits your cards and the pot; you put in no more chips for that hand.', tags: ['Poker', 'Betting actions'] },
  { q: 'To "call" means to do what?', opts: ['Match the current bet to stay in the hand', 'Increase the bet', 'Bet nothing', 'Throw your hand away'], a: 0, e: 'Calling matches the amount of the current bet so you continue in the hand.', tags: ['Poker', 'Betting actions'] },
  { q: 'To "raise" means to do what?', opts: ['Increase the current bet, forcing others to match more', 'Match the bet exactly', 'Pass the action along', 'Surrender your cards'], a: 0, e: 'A raise increases the wager beyond the current bet, so opponents must call the new amount or fold.', tags: ['Poker', 'Betting actions'] },
  { q: 'When are you allowed to check?', opts: ['Only when no bet has yet been made in that round', 'At any time', 'Only after someone raises', 'Only before the flop'], a: 0, e: 'You can check only if the action reaches you with no outstanding bet; otherwise you must call, raise, or fold.', tags: ['Poker', 'Betting actions'] },
  { q: 'How many betting rounds are there in a Texas Hold\'em hand?', opts: ['Four', 'Two', 'Three', 'Five'], a: 0, e: 'Betting occurs preflop, on the flop, on the turn, and on the river — four rounds in all.', tags: ['Poker', 'Betting rounds'] },
  { q: 'What is the first betting round, before any community cards, called?', opts: ['Preflop', 'The flop', 'The turn', 'The showdown'], a: 0, e: 'The opening round of betting on just the hole cards is called preflop.', tags: ['Poker', 'Betting rounds'] },
  { q: 'What is a "check-raise"?', opts: ['Checking first, then raising after an opponent bets', 'Raising and then immediately folding', 'Checking twice in a row', 'Calling then calling again'], a: 0, e: 'A check-raise is a trap: you check, and after an opponent bets you raise in the same round.', tags: ['Poker', 'Betting actions'] },

  // ── Level 3 — Blinds, antes, button & acting order ──
  { q: 'What is the "button" in poker?', opts: ['A marker showing the nominal dealer position', 'The total pot of chips', 'A type of forced bet', 'The winning hand'], a: 0, e: 'The dealer button marks who is the nominal dealer; blinds and acting order are set relative to it.', tags: ['Poker', 'Position'] },
  { q: 'Who posts the small blind?', opts: ['The player immediately to the left of the button', 'The player on the button', 'The player in the big blind', 'The house dealer'], a: 0, e: 'The small blind is posted by the seat directly left of the button, with the big blind to their left.', tags: ['Poker', 'Blinds'] },
  { q: 'The big blind is typically what size relative to the small blind?', opts: ['Twice the small blind', 'Half the small blind', 'Equal to the small blind', 'Ten times the small blind'], a: 0, e: 'By convention the big blind is double the small blind (e.g. 1 and 2 chips).', tags: ['Poker', 'Blinds'] },
  { q: 'Before the flop, which player acts first?', opts: ['The player left of the big blind ("under the gun")', 'The small blind', 'The button', 'The big blind'], a: 0, e: 'Preflop action starts with the player to the left of the big blind, known as under the gun.', tags: ['Poker', 'Acting order'] },
  { q: 'After the flop, which remaining player acts first?', opts: ['The first active player to the left of the button', 'The button', 'The under-the-gun player', 'The big blind, always'], a: 0, e: 'From the flop onward, action begins with the first active player left of the button (usually the small blind).', tags: ['Poker', 'Acting order'] },
  { q: 'What is an ante?', opts: ['A small forced bet contributed before the hand by players', 'A raise made after the river', 'Another name for the button', 'A purely voluntary bonus bet'], a: 0, e: 'An ante is a small mandatory contribution that builds the pot, common in later tournament levels.', tags: ['Poker', 'Antes'] },
  { q: 'Between hands, which way does the button move?', opts: ['One seat clockwise, to the next player on the left', 'One seat counterclockwise', 'It stays with the same player', 'To a randomly chosen seat'], a: 0, e: 'The button rotates one seat to the left each hand so blinds and dealing pass fairly around the table.', tags: ['Poker', 'Position'] },
  { q: 'Why is being "on the button" an advantage after the flop?', opts: ['You act last, seeing everyone\'s decisions first', 'You must bet every round', 'You act first each round', 'You post no blinds ever'], a: 0, e: 'The button acts last on every postflop street, gaining information from opponents before deciding.', tags: ['Poker', 'Position'] },

  // ── Level 4 — Bet sizing, all-ins & side pots ──
  { q: 'In no-limit Hold\'em, what is the maximum you can bet?', opts: ['All of your chips (going all-in)', 'The current size of the pot', 'Twice the big blind', 'Exactly the big blind'], a: 0, e: 'No-limit means you may wager any amount up to your entire stack at any time.', tags: ['Poker', 'Bet sizing'] },
  { q: 'What is the smallest opening bet allowed on the flop, turn, or river?', opts: ['At least the size of the big blind', 'The full size of the pot', 'Any amount, even one chip', 'Double the pot'], a: 0, e: 'A postflop bet must be at least one big blind (unless a player is going all-in for less).', tags: ['Poker', 'Bet sizing'] },
  { q: 'A minimum legal raise must be at least how large?', opts: ['The size of the previous bet or raise', 'Double the current pot', 'Always one big blind', 'A single chip'], a: 0, e: 'You must raise by at least as much as the last bet or raise, so a raise cannot be tiny.', tags: ['Poker', 'Bet sizing'] },
  { q: 'What does going "all-in" mean?', opts: ['Betting all of your remaining chips', 'Folding your hand', 'Calling half the bet', 'Checking your option'], a: 0, e: 'Going all-in puts your entire remaining stack into the pot; you can win only what you can match.', tags: ['Poker', 'All-ins'] },
  { q: 'When is a side pot created?', opts: ['When a player is all-in and others keep betting', 'On every single hand', 'Only at the showdown', 'Whenever anyone folds'], a: 0, e: 'Chips bet beyond an all-in player\'s stack go into a separate side pot that only the still-active players contest.', tags: ['Poker', 'Side pots'] },
  { q: 'A player all-in for less than the current bet can win at most what?', opts: ['Only up to the amount each opponent matched (the main pot)', 'The entire pot including later bets', 'Nothing at all', 'Only a side pot'], a: 0, e: 'An all-in player can win only the portion of the pot they contributed to; extra chips form a side pot.', tags: ['Poker', 'Side pots'] },
  { q: 'After you go all-in, can the other players keep betting?', opts: ['Yes, into a side pot that you cannot win', 'No, all betting stops immediately', 'Only if they first fold', 'Never under any rule'], a: 0, e: 'Players with chips left can continue betting among themselves in a side pot the all-in player has no claim to.', tags: ['Poker', 'All-ins'] },
  { q: 'Can a raise ever be for less than a full legal raise?', opts: ['Yes, when a player goes all-in for less than a full raise', 'No, raises are always full-sized', 'Only during preflop play', 'Only on the river'], a: 0, e: 'A short all-in can be less than a full raise; such a raise usually does not reopen the betting to players already acted.', tags: ['Poker', 'All-ins'] },

  // ── Level 5 — Formats & variants ──
  { q: 'In a cash (ring) game, what do the chips represent?', opts: ['Real money you can add to or cash out at any time', 'Points with no cash value', 'A tournament ranking', 'Nothing of value'], a: 0, e: 'Cash-game chips equal real money; players may buy in, top up, or leave and cash out whenever they like.', tags: ['Poker', 'Formats'] },
  { q: 'In a poker tournament, when are you eliminated?', opts: ['When you lose all of your chips', 'The first time you fold', 'When the blinds go up', 'When you leave your seat briefly'], a: 0, e: 'Tournament players start with a fixed stack and are knocked out once they run out of chips.', tags: ['Poker', 'Formats'] },
  { q: 'A defining feature of tournaments compared with cash games is that over time the...', opts: ['Blinds (and antes) increase at set intervals', 'Blinds stay fixed forever', 'Hand has no blinds at all', 'Deck is changed each level'], a: 0, e: 'Tournament blinds rise on a schedule, steadily raising the pressure and forcing action.', tags: ['Poker', 'Formats'] },
  { q: 'In no-limit betting, how much may you wager?', opts: ['Any amount, up to your whole stack', 'Only fixed preset amounts', 'Only the size of the pot', 'Only one big blind'], a: 0, e: 'No-limit lets you bet or raise anything from the minimum up to all your chips.', tags: ['Poker', 'Betting formats'] },
  { q: 'In fixed-limit Hold\'em, bets and raises are...', opts: ['Fixed, predetermined amounts each round', 'Unlimited up to your stack', 'Always the size of the pot', 'Chosen freely by the bettor'], a: 0, e: 'Limit poker restricts each bet and raise to set sizes, unlike the free sizing of no-limit.', tags: ['Poker', 'Betting formats'] },
  { q: 'In a pot-limit game, the maximum bet is...', opts: ['The current size of the pot', 'Your entire stack always', 'One big blind', 'Twice the pot'], a: 0, e: 'Pot-limit caps any bet or raise at the total currently in the pot, a middle ground between limit and no-limit.', tags: ['Poker', 'Betting formats'] },
  { q: 'How does Omaha differ from Texas Hold\'em?', opts: ['Players get four hole cards and must use exactly two', 'It deals six community cards', 'It has no community cards', 'It deals five hole cards each'], a: 0, e: 'In Omaha each player receives four hole cards and must use precisely two of them with three community cards.', tags: ['Poker', 'Variants'] },
  { q: 'How does Seven-Card Stud differ from Hold\'em?', opts: ['It has no community cards or flop', 'It uses a shared flop', 'It deals only two cards per player', 'It is always no-limit'], a: 0, e: 'Seven-Card Stud deals each player their own up and down cards with no shared board, and uses antes and a bring-in.', tags: ['Poker', 'Variants'] },
];
