import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Digestive System roadmap question bank (rm-digest-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const digestiveSystemTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-digest-1': { introduction: 'Zamysli se nad tím, kudy jídlo postupně prochází od úst až po konečník.', question: 'Jaká je správná cesta potravy trávicím traktem?', options: ['Ústa → žaludek → jícen → střeva', 'Ústa → jícen → žaludek → tenké střevo → tlusté střevo', 'Ústa → tenké střevo → žaludek → tlusté střevo', 'Ústa → žaludek → tlusté střevo → tenké střevo'], explanation: 'Potrava putuje ústa → jícen → žaludek → tenké střevo → tlusté střevo a končí v konečníku a řitním otvoru.' },
  'rm-digest-2': { introduction: 'Kde se do potravy poprvé pustí enzymy a zuby?', question: 'Kde začíná trávení jako první?', options: ['V žaludku', 'V ústech', 'V tenkém střevě', 'V jícnu'], explanation: 'Trávení začíná v ústech, kde zuby drtí potravu a sliny začínají rozkládat škrob.' },
  'rm-digest-3': { introduction: 'Jde o svalovou trubici, ne o dýchací cestu.', question: 'Která svalová trubice vede potravu z hltanu do žaludku?', options: ['Průdušnice', 'Jícen', 'Dvanáctník', 'Hrtan'], explanation: 'Jícen spojuje hltan se žaludkem a posouvá potravu dolů svalovými stahy.' },
  'rm-digest-4': { introduction: 'Jak se jmenují ty vlnovité stahy svaloviny?', question: 'Jak se nazývají vlnovité svalové stahy, které posouvají potravu trávicí trubicí?', options: ['Peristaltika', 'Difuze', 'Osmóza', 'Trávení'], explanation: 'Peristaltika je rytmické stahování hladké svaloviny, které pohání potravu trávicím traktem.' },
  'rm-digest-5': { introduction: 'Který orgán potravu skladuje a promíchává s kyselou šťávou?', question: 'Který orgán skladuje potravu a mísí ji s kyselou žaludeční šťávou?', options: ['Játra', 'Žaludek', 'Žlučník', 'Tračník'], explanation: 'Žaludek je svalový vak, který skladuje potravu a mísí ji s kyselinou a enzymy na kaši.' },
  'rm-digest-6': { introduction: 'Kde probíhá většina vstřebávání živin?', question: 'Kde probíhá většina trávení a vstřebávání živin?', options: ['V žaludku', 'V tlustém střevě', 'V tenkém střevě', 'V jícnu'], explanation: 'Tenké střevo je hlavním místem chemického trávení a vstřebávání živin do krve.' },
  'rm-digest-7': { introduction: 'Co dělá tlusté střevo s tím, co zbude?', question: 'Jaká je hlavní úloha tlustého střeva?', options: ['Vstřebává vodu a tvoří stolici', 'Vytváří žluč', 'Tráví bílkoviny', 'Vyrábí inzulin'], explanation: 'Tlusté střevo vstřebává vodu a soli z nestrávených zbytků a tvoří a skladuje stolici.' },
  'rm-digest-8': { introduction: 'Co brání vdechnutí sousta při polykání?', question: 'Která chlopeň brání vniknutí potravy do průdušnice při polykání?', options: ['Čípek', 'Hrtanová příklopka (epiglottis)', 'Mandle', 'Bránice'], explanation: 'Hrtanová příklopka se při polykání sklopí přes průdušnici, takže potrava jde do jícnu, ne do dýchacích cest.' },

  'rm-digest-9': { introduction: 'Jde o fyzikální, ne chemické rozmělnění.', question: 'Co znamená mechanické trávení?', options: ['Fyzické rozmělnění potravy na menší kousky', 'Rozklad chemických vazeb enzymy', 'Vstřebávání živin', 'Odstraňování odpadu'], explanation: 'Mechanické trávení fyzicky rozmělní potravu na menší kousky (žvýkání, promíchávání) bez změny její chemie.' },
  'rm-digest-10': { introduction: 'Čím se rozkládají velké molekuly na malé?', question: 'Chemické trávení rozkládá potravu tím, že', options: ['ji drtí zuby', 'používá enzymy k rozštěpení molekulových vazeb', 'ji mačká svaly', 'ji zmrazí'], explanation: 'Chemické trávení používá enzymy, které štěpí velké molekuly na malé, vstřebatelné jednotky.' },
  'rm-digest-11': { introduction: 'Do které kategorie žvýkání patří?', question: 'Žvýkání potravy je příkladem čeho?', options: ['Chemického trávení', 'Mechanického trávení', 'Vstřebávání', 'Vylučování'], explanation: 'Žvýkání fyzicky rozmělní potravu a zvětší povrch pro enzymy — jde o mechanické trávení.' },
  'rm-digest-12': { introduction: 'Jak se jmenuje ta polotekutá kaše ze žaludku?', question: 'Jak se nazývá polotekutá kaše vzniklá promícháním potravy v žaludku?', options: ['Sousto (bolus)', 'Trávenina (chymus)', 'Žluč', 'Stolice'], explanation: 'Žaludek mísí potravu s žaludeční šťávou na trávaninu (chymus), která pak přechází do tenkého střeva.' },
  'rm-digest-13': { introduction: 'Co dělá žaludek tak kyselým?', question: 'Žaludek je silně kyselý hlavně proto, že obsahuje', options: ['kyselinu chlorovodíkovou', 'hydrogenuhličitan sodný', 'žlučové soli', 'kyselinu mléčnou'], explanation: 'Krycí (parietální) buňky vylučují kyselinu chlorovodíkovou (HCl), která hubí mikroby a aktivuje enzymy štěpící bílkoviny.' },
  'rm-digest-14': { introduction: 'Odhadni, jak nízké je pH v žaludku.', question: 'Přibližná hodnota pH uvnitř žaludku je', options: ['1,5 až 3 (silně kyselé)', '7 (neutrální)', '9 až 10 (zásadité)', '5 až 6 (mírně kyselé)'], explanation: 'Žaludeční šťáva je silně kyselá, kolem pH 1,5–3, což je ideální prostředí pro pepsin.' },
  'rm-digest-15': { introduction: 'Jak se jmenuje sousto před polknutím?', question: 'Rozžvýkané sousto potravy připravené k polknutí se nazývá', options: ['Trávenina (chymus)', 'Sousto (bolus)', 'Klk', 'Žluč'], explanation: 'Bolus je zvlhčená kulička rozžvýkané potravy vytvořená v ústech před polknutím.' },
  'rm-digest-16': { introduction: 'Co znamená emulgace tuků?', question: 'Žluč pomáhá trávit tuk tím, že jej emulguje, což znamená, že žluč', options: ['rozkládá tuk na aminokyseliny', 'rozbíjí velké tukové kapky na mnoho malých', 'vstřebává tuk do krve', 'tuk neutralizuje'], explanation: 'Emulgace rozbíjí velké tukové kapky na drobné kapičky, čímž zvětší povrch, aby lipáza mohla působit rychleji.' },

  'rm-digest-17': { introduction: 'Co začíná štěpit slinná amyláza?', question: 'Slinná amyláza v ústech začíná trávit', options: ['bílkoviny', 'škrob (sacharidy)', 'tuky', 'vitaminy'], explanation: 'Slinná amyláza začíná štěpit škrob na jednodušší cukry ještě v ústech.' },
  'rm-digest-18': { introduction: 'Který žaludeční enzym se pustí do bílkovin?', question: 'Který žaludeční enzym začíná trávit bílkoviny?', options: ['Amyláza', 'Lipáza', 'Pepsin', 'Maltáza'], explanation: 'Pepsin, aktivní v kyselém prostředí, štěpí bílkoviny na menší peptidy v žaludku.' },
  'rm-digest-19': { introduction: 'Co promění neaktivní pepsinogen v pepsin?', question: 'Pepsin se vylučuje jako neaktivní pepsinogen a aktivuje jej', options: ['žluč', 'žaludeční kyselina (HCl)', 'inzulin', 'sliny'], explanation: 'Kyselina chlorovodíková mění neaktivní pepsinogen na aktivní pepsin a chrání buňky, které jej tvoří.' },
  'rm-digest-20': { introduction: 'Který orgán vyrábí žluč?', question: 'Žluč vytvářejí', options: ['slinivka břišní', 'játra', 'žaludek', 'slezina'], explanation: 'Játra nepřetržitě vytvářejí žluč, která napomáhá trávení tuků v tenkém střevě.' },
  'rm-digest-21': { introduction: 'Kde se žluč skladuje, než je potřeba?', question: 'Žluč se skladuje a zahušťuje ve', options: ['žlučníku', 'apendixu', 'dvanáctníku', 'ledvině'], explanation: 'Žlučník skladuje a zahušťuje žluč a vypouští ji do tenkého střeva, když dorazí tuk.' },
  'rm-digest-22': { introduction: 'Proč slinivka vypouští zásaditý hydrogenuhličitan?', question: 'Slinivka vypouští do tenkého střeva hydrogenuhličitan hlavně proto, aby', options: ['neutralizovala kyselou tráveninu', 'emulgovala tuky', 'vstřebala glukózu', 'zabíjela bakterie'], explanation: 'Hydrogenuhličitan ze slinivky neutralizuje kyselou tráveninu ze žaludku, čímž chrání střevo a napomáhá enzymům.' },
  'rm-digest-23': { introduction: 'Který enzym slinivky štěpí bílkoviny?', question: 'Který enzym slinivky tráví bílkoviny?', options: ['Amyláza', 'Trypsin', 'Laktáza', 'Lipáza'], explanation: 'Trypsin vylučovaný slinivkou štěpí peptidy na menší peptidy a aminokyseliny v tenkém střevě.' },
  'rm-digest-24': { introduction: 'Na co se zaměřuje enzym lipáza?', question: 'Enzym lipáza je zodpovědný za trávení', options: ['škrobu', 'bílkovin', 'tuků (lipidů)', 'nukleových kyselin'], explanation: 'Lipáza štěpí tuky na mastné kyseliny a glycerol a nejlépe působí poté, co žluč tuk emulgovala.' },

  'rm-digest-25': { introduction: 'Jak se jmenují ty drobné výběžky ve střevě?', question: 'Vnitřní stěna tenkého střeva je pokryta drobnými prstovitými výběžky zvanými', options: ['řasinky', 'klky', 'plicní sklípky', 'nefrony'], explanation: 'Klky jsou prstovité výběžky, které výrazně zvětšují povrch střeva pro vstřebávání živin.' },
  'rm-digest-26': { introduction: 'K čemu jsou klky a mikroklky dobré?', question: 'Hlavním účelem klků a mikroklků je', options: ['vytvářet enzymy', 'zvětšit povrch pro vstřebávání', 'skladovat žluč', 'zabíjet bakterie'], explanation: 'Klky a ještě menší mikroklky výrazně zvětšují povrch, čímž urychlují vstřebávání živin.' },
  'rm-digest-27': { introduction: 'Znáš pořadí tří úseků tenkého střeva?', question: 'Tři úseky tenkého střeva jsou v pořadí', options: ['dvanáctník, lačník, kyčelník', 'kyčelník, lačník, dvanáctník', 'slepé střevo, tračník, konečník', 'lačník, dvanáctník, kyčelník'], explanation: 'Trávenina prochází z dvanáctníku do lačníku a nakonec do kyčelníku, než dojde do tlustého střeva.' },
  'rm-digest-28': { introduction: 'Kam míří glukóza a aminokyseliny?', question: 'Glukóza a aminokyseliny se z tenkého střeva vstřebávají přímo do', options: ['krevních vlásečnic', 'žaludku', 'žlučovodů', 'plicních sklípků'], explanation: 'Ve vodě rozpustné živiny jako glukóza a aminokyseliny přecházejí do krevních vlásečnic uvnitř každého klku.' },
  'rm-digest-29': { introduction: 'Kam jdou strávené tuky (ne do krve)?', question: 'Strávené tuky (mastné kyseliny) se vstřebávají hlavně do', options: ['krevních vlásečnic', 'mízních cév (lakteálů)', 'slinivky', 'přímo do jater'], explanation: 'Mastné kyseliny vstupují do lakteálů, mízních cév uvnitř klků, nikoli přímo do krve.' },
  'rm-digest-30': { introduction: 'Co musí žaludek dodat pro vstřebání B12?', question: 'Vstřebání vitaminu B12 v kyčelníku vyžaduje látku ze žaludku zvanou', options: ['vnitřní faktor', 'pepsin', 'žlučovou sůl', 'amylázu'], explanation: 'Žaludek vylučuje vnitřní faktor, který se váže na vitamin B12, aby mohl být vstřebán v kyčelníku.' },
  'rm-digest-31': { introduction: 'Kudy putuje krev bohatá na živiny nejdřív?', question: 'Krev bohatá na živiny putuje ze střev nejprve do jater cévou zvanou', options: ['plicní žíla', 'vrátnicová žíla (portální)', 'aorta', 'ledvinová tepna'], explanation: 'Vrátnicová (portální) žíla přivádí vstřebané živiny do jater ke zpracování, než se dostanou do zbytku těla.' },
  'rm-digest-32': { introduction: 'Kde se vstřebá největší objem vody?', question: 'Které je hlavní místo, kde se vstřebává většina vody z trávicího obsahu?', options: ['Jícen', 'Tenké střevo', 'Ústa', 'Žlučník'], explanation: 'I když tračník vstřebá zbytek, tenké střevo vstřebává největší objem vody.' },

  'rm-digest-33': { introduction: 'Které tři skupiny živin potřebujeme ve velkém?', question: 'Tři hlavní makroživiny v potravě jsou', options: ['vitaminy, minerály, voda', 'sacharidy, bílkoviny, tuky', 'vláknina, sůl, cukr', 'glukóza, kyslík, voda'], explanation: 'Sacharidy, bílkoviny a tuky jsou makroživiny, které tělo potřebuje ve velkém množství pro energii a stavbu.' },
  'rm-digest-34': { introduction: 'Která živina má nejvíc energie na gram?', question: 'Která makroživina poskytuje nejvíce energie na gram?', options: ['Sacharid', 'Bílkovina', 'Tuk', 'Vláknina'], explanation: 'Tuk dodává asi 9 kcal na gram, více než dvojnásobek oproti ~4 kcal na gram u sacharidů či bílkovin.' },
  'rm-digest-35': { introduction: 'Z jakých stavebních jednotek jsou bílkoviny?', question: 'Stavebními jednotkami (monomery) bílkovin jsou', options: ['mastné kyseliny', 'aminokyseliny', 'jednoduché cukry', 'nukleotidy'], explanation: 'Bílkoviny jsou řetězce aminokyselin; trávení je rozloží zpět na aminokyseliny pro vstřebání.' },
  'rm-digest-36': { introduction: 'Na co se nakonec rozloží sacharidy?', question: 'Sacharidy se nakonec rozkládají na', options: ['aminokyseliny', 'jednoduché cukry jako glukóza', 'mastné kyseliny', 'glycerol'], explanation: 'Trávení sacharidů dává jednoduché cukry, hlavně glukózu, která je hlavním energetickým palivem těla.' },
  'rm-digest-37': { introduction: 'V jaké formě se ukládá přebytečná glukóza?', question: 'Přebytečná glukóza se ukládá v játrech a svalech jako', options: ['glykogen', 'škrob', 'celulóza', 'sacharóza'], explanation: 'Tělo ukládá přebytečnou glukózu jako glykogen, větvený polymer uvolňovaný pro energii v případě potřeby.' },
  'rm-digest-38': { introduction: 'Proč je vláknina důležitá, i když se nevstřebá?', question: 'Vláknina je důležitá pro trávení, protože', options: ['dodává většinu naší energie', 'dodává objem a napomáhá vyprazdňování', 'vstřebává se jako glukóza', 'tráví bílkoviny'], explanation: 'Vláknina je nestravitelná rostlinná hmota, která dodává stolici objem a pomáhá posouvat potravu střevem.' },
  'rm-digest-39': { introduction: 'Proč jsou některé aminokyseliny „esenciální“?', question: 'Esenciální aminokyseliny se nazývají „esenciální“, protože', options: ['jsou nejhojnější', 'musíme je přijmout z potravy', 'tvoří je jen játra', 'slouží jen k energii'], explanation: 'Esenciální aminokyseliny si tělo neumí vytvořit a musí je dodat strava.' },
  'rm-digest-40': { introduction: 'Jak se souhrnně nazývají všechny chemické reakce v buňkách?', question: 'Souhrn chemických reakcí, které v buňkách budují a rozkládají molekuly, se nazývá', options: ['trávení', 'metabolismus', 'vstřebávání', 'vylučování'], explanation: 'Metabolismus zahrnuje anabolismus (budování molekul) a katabolismus (jejich rozklad) k řízení energie.' },
};
