// Developer jargon in context: 120 questions, 15 levels × 8.
//
// These questions teach the expansion in the explanation, but ask learners to
// recognise the term from a realistic use. That tests understanding instead of
// rewarding the only expansion that happens to sound like English.

import type { Seed } from './roadmap-build';

const term = (q: string, opts: string[], a: number, e: string, tags: string[]): Seed => ({
  q, opts, a, e, tags: ['Abbreviations', ...tags],
});

export const abbreviationsSeeds: Seed[] = [
  // Level 1 — Languages & runtimes
  term('A browser runs the source file app.js directly. Which label names the language in that file?', ['TS', 'JS', 'PHP', 'WASM'], 1, 'JS means JavaScript, the language built into web browsers and also used by runtimes such as Node.js.', ['Languages']),
  term('A project adds static type checks while keeping JavaScript syntax and libraries. Which language is it using?', ['JS', 'TS', 'Flow', 'WASM'], 1, 'TS means TypeScript. It adds a static type system to JavaScript and compiles to JavaScript.', ['Languages']),
  term('You need to describe the headings, links, forms, and other structure of a web page. Which language does that job?', ['HTML', 'CSS', 'DOM', 'JSX'], 0, 'HTML means HyperText Markup Language. It gives a web document its structure and meaning.', ['Languages']),
  term('You need responsive layout, colors, spacing, and typography for an HTML page. Which language belongs in the stylesheet?', ['HTML', 'Sass', 'CSS', 'JSX'], 2, 'CSS means Cascading Style Sheets. The cascade is the set of rules that decides which styles apply.', ['Languages']),
  term('A legacy server renders pages from files ending in .php. Which label names the language handling those requests?', ['JSP', 'PHP', 'SQL', 'JS'], 1, 'PHP now expands recursively to PHP: Hypertext Preprocessor. It is commonly used for server-rendered web applications.', ['Languages']),
  term('An analyst needs to filter and join rows in a relational database. Which language should they write?', ['GraphQL', 'SQL', 'JSON', 'ORM'], 1, 'SQL means Structured Query Language. It is used to query and change data in relational databases.', ['Languages']),
  term('Compiled Java bytecode needs a runtime that can execute it on different operating systems. Which runtime is that?', ['V8', 'JVM', 'CLR', 'WASM'], 1, 'JVM means Java Virtual Machine. It executes Java bytecode and provides services such as memory management.', ['Languages']),
  term('Rust code is compiled to a portable binary format so it can run inside a browser. Which target format fits?', ['JVM', 'WASM', 'V8', 'CLR'], 1, 'WASM means WebAssembly. It is a portable binary instruction format supported by browsers and other hosts.', ['Languages']),

  // Level 2 — Web standards
  term('A client sends GET /orders and receives a response with a status code and headers. Which protocol defines that exchange?', ['HTTP', 'TCP', 'TLS', 'DNS'], 0, 'HTTP means HyperText Transfer Protocol. It defines the request and response messages used by the web.', ['Web']),
  term('A login form must protect the request from network eavesdropping and authenticate the server. Which URL scheme should it use?', ['HTTP', 'HTTPS', 'SSH', 'TLS'], 1, 'HTTPS means HyperText Transfer Protocol Secure: HTTP protected by TLS.', ['Web']),
  term('You copy https://example.com/docs?id=4 from the address bar. What kind of identifier is the whole string?', ['URN', 'URL', 'URI template', 'DNS record'], 1, 'URL means Uniform Resource Locator. It identifies a resource and tells a client where and how to access it.', ['Web']),
  term('A specification needs the broad name for identifiers that includes both URLs and URNs. Which term fits?', ['URI', 'URL', 'URN', 'IP'], 0, 'URI means Uniform Resource Identifier. URL and URN are more specific kinds of URI.', ['Web']),
  term('An identifier names a resource without saying where it can be fetched. Which kind of URI is that?', ['URL', 'URI template', 'URN', 'DNS'], 2, 'URN means Uniform Resource Name. It identifies by name rather than by a network location.', ['Web']),
  term('A team wants the standards body responsible for specifications such as WCAG and many core web APIs. Which group should they consult?', ['W3C', 'WHATWG', 'TC39', 'IETF'], 0, 'W3C means World Wide Web Consortium. It develops many open standards for the web, including accessibility standards.', ['Web']),
  term('JavaScript calls querySelector and receives an in-memory node from the parsed page. Which model does that node belong to?', ['DOM', 'CSSOM', 'AST', 'VDOM'], 0, 'DOM means Document Object Model. It represents a document as objects that scripts can read and change.', ['Web']),
  term('A browser blocks a frontend request because the API did not allow that origin. Which browser mechanism is involved?', ['CORS', 'CSP', 'CSRF', 'SOP cookie'], 0, 'CORS means Cross-Origin Resource Sharing. Response headers let a server grant selected origins access to a response.', ['Web']),

  // Level 3 — APIs and data formats
  term('A payment service publishes the methods, inputs, and outputs that other programs can call. What is that contract?', ['API', 'SDK', 'CLI', 'ABI'], 0, 'API means Application Programming Interface. It is the contract exposed to other software.', ['API']),
  term('An HTTP service models orders as resources and uses GET, POST, and DELETE consistently. Which architectural style does this resemble?', ['RPC', 'REST', 'SOAP', 'GraphQL'], 1, 'REST means Representational State Transfer. It is an architectural style built around resources and standard HTTP semantics.', ['API']),
  term('An API response must carry a small text object that browser code can parse without an XML parser. Which format is the usual choice?', ['JSON', 'XML', 'YAML', 'CSV'], 0, 'JSON means JavaScript Object Notation. It is a compact text format for objects, arrays, and primitive values.', ['API']),
  term('A document needs nested elements, namespaces, and validation against a schema. Which format is designed for that?', ['JSON', 'XML', 'YAML', 'TOML'], 1, 'XML means eXtensible Markup Language. Its element model, namespaces, and schemas suit structured documents.', ['API']),
  term('Client code invokes createInvoice on another service as though it were calling a local function. Which communication style is this?', ['RPC', 'REST', 'SSE', 'CDN'], 0, 'RPC means Remote Procedure Call. It frames network communication as calls to procedures on another process.', ['API']),
  term('Two backend services need typed contracts, streaming, and efficient binary messages over HTTP/2. Which technology fits?', ['WebSocket', 'gRPC', 'REST', 'GraphQL'], 1, 'gRPC is an RPC framework that commonly uses Protocol Buffers and HTTP/2 for typed service calls and streaming.', ['API']),
  term('An enterprise integration requires an XML envelope, a formal service contract, and protocol-level fault messages. Which protocol fits?', ['SOAP', 'REST', 'RPC', 'SSE'], 0, 'SOAP means Simple Object Access Protocol. It defines XML messages and formal conventions for service operations and faults.', ['API']),
  term('A deployment pipeline needs a human-readable configuration file where indentation defines nested data. Which format fits?', ['JSON', 'YAML', 'TOML', 'XML'], 1, 'YAML expands to YAML Ain\'t Markup Language. It is a data-serialization format often used for configuration.', ['API']),

  // Level 4 — Frontend rendering
  term('Navigation updates the current document with JavaScript instead of requesting a new HTML page each time. Which app model is this?', ['MPA', 'SPA', 'SSR', 'SSG'], 1, 'SPA means Single-Page Application. Client-side code updates one loaded document as the user navigates.', ['Rendering']),
  term('Each route navigation asks the server for a new HTML document. Which app model describes this?', ['MPA', 'SPA', 'PWA', 'RSC'], 0, 'MPA means Multi-Page Application. Navigation loads a separate document for each page.', ['Rendering']),
  term('A server creates the page HTML for every request before sending it to the browser. Which rendering mode is this?', ['SSR', 'CSR', 'SSG', 'ISR'], 0, 'SSR means Server-Side Rendering. HTML is produced on the server for an incoming request.', ['Rendering']),
  term('The server sends a small HTML shell and browser JavaScript builds the visible page. Which rendering mode is this?', ['SSR', 'CSR', 'SSG', 'RSC'], 1, 'CSR means Client-Side Rendering. The browser runs application code to build and update the interface.', ['Rendering']),
  term('Documentation pages are rendered during the build and deployed as files. Which approach is this?', ['SSG', 'SSR', 'CSR', 'ISR'], 0, 'SSG means Static Site Generation. Pages are produced ahead of requests, usually during a build.', ['Rendering']),
  term('A Next.js product page is static but can be rebuilt after a revalidation window without a full deployment. Which feature is being used?', ['SSR', 'ISR', 'CSR', 'RSC'], 1, 'ISR means Incremental Static Regeneration. Selected static pages can be refreshed after deployment.', ['Rendering']),
  term('A website can be installed, cache resources for offline use, and receive supported browser capabilities. Which label fits?', ['SPA', 'PWA', 'MPA', 'SSR'], 1, 'PWA means Progressive Web Application. It describes a web app enhanced with installability and resilient browser features.', ['Rendering']),
  term('A React component fetches data and renders on the server without shipping its component code to the browser. Which model is this?', ['SSR', 'RSC', 'CSR', 'SSG'], 1, 'RSC means React Server Components. These components execute on the server and send a serialized result to the client.', ['Rendering']),

  // Level 5 — Build and tooling
  term('A package.json script runs through the command npm test. Which package-tool command is being used?', ['pnpm', 'Yarn', 'Bun', 'npm'], 3, 'npm is the package manager and command-line tool distributed with Node.js. Its name is not officially treated as an acronym.', ['Tooling']),
  term('A developer wants one program with an editor, debugger, language tools, and run configurations. Which tool category fits?', ['Text editor', 'IDE', 'REPL', 'SDK'], 1, 'IDE means Integrated Development Environment. It combines editing with tools such as debugging and project execution.', ['Tooling']),
  term('A deployment tool is controlled by typed commands in a terminal rather than buttons in a window. Which interface is this?', ['CLI', 'GUI', 'IDE', 'API'], 0, 'CLI means Command-Line Interface. Users interact through commands and text output.', ['Tooling']),
  term('A desktop database client is mainly operated through windows, menus, and buttons. Which interface is this?', ['CLI', 'GUI', 'TUI', 'REPL'], 1, 'GUI means Graphical User Interface. It uses visual controls instead of a command line.', ['Tooling']),
  term('A platform ships libraries, a local emulator, command-line tools, and documentation for app developers. What is that bundle?', ['API', 'SDK', 'CLI', 'IDE'], 1, 'SDK means Software Development Kit. It packages tools and libraries for building against a platform.', ['Tooling']),
  term('A linter parses source code into a tree of declarations, calls, and expressions before inspecting it. Which structure is that?', ['Token stream', 'AST', 'Bytecode', 'Source map'], 1, 'AST means Abstract Syntax Tree. It represents the grammatical structure of source code.', ['Tooling']),
  term('A runtime profiles a hot function and compiles it to machine code while the program is running. Which compilation strategy is this?', ['Interpreter only', 'JIT', 'AOT', 'Transpilation'], 1, 'JIT means Just-In-Time compilation. Code is compiled during execution, often using runtime profiling.', ['Tooling']),
  term('A mobile app is compiled to native machine code before it is installed. Which compilation strategy is this?', ['JIT', 'AOT', 'GC', 'REPL'], 1, 'AOT means Ahead-Of-Time compilation. Code is compiled before the program runs.', ['Tooling']),

  // Level 6 — Version control and delivery
  term('A team needs software that records file history, branches, and merges. What kind of system is Git?', ['CI', 'VCS', 'IDE', 'SDK'], 1, 'VCS means Version Control System. It records changes and supports parallel work through branches and merges.', ['Git']),
  term('A GitHub contributor wants review before a branch is merged. Which object should they open?', ['Issue', 'PR', 'Release', 'Tag'], 1, 'PR means Pull Request. It proposes a set of changes for review and merge.', ['Git']),
  term('GitLab uses a different name for a reviewed proposal to merge one branch into another. Which term does it use?', ['MR', 'PR', 'CI/CD', 'Cherry-pick'], 0, 'MR means Merge Request, GitLab\'s name for the workflow GitHub calls a pull request.', ['Git']),
  term('Every push should automatically build the project and run its tests. Which practice provides that feedback?', ['CI', 'CD', 'UAT', 'SRE'], 0, 'CI means Continuous Integration. Changes are integrated frequently and checked by an automated build and test pipeline.', ['Git']),
  term('Validated changes should remain release-ready or be deployed automatically after CI. Which part of the pipeline covers that?', ['CI', 'CD', 'UAT', 'SLO'], 1, 'CD means Continuous Delivery or Continuous Deployment. It takes validated changes toward a production release.', ['Git']),
  term('A Git commit is identified by a cryptographic digest. Which common label names that digest family?', ['SHA', 'SemVer', 'LOC', 'AST'], 0, 'SHA means Secure Hash Algorithm. Git historically used SHA-1 object identifiers and can also use SHA-256.', ['Git']),
  term('A codebase report counts physical source lines as a rough size measure. Which metric is it reporting?', ['LOC', 'Cyclomatic complexity', 'Coverage', 'Latency'], 0, 'LOC means Lines of Code. It measures code volume, but not quality or delivered value.', ['Git']),
  term('A library release moves from 2.4.1 to 3.0.0 because it breaks its public API. Which versioning convention explains the major bump?', ['CalVer', 'SemVer', 'Lockfile version', 'SHA'], 1, 'SemVer means Semantic Versioning. In MAJOR.MINOR.PATCH, a major bump signals incompatible API changes.', ['Git']),

  // Level 7 — Authentication and security
  term('A calendar app asks Google for limited access to a user\'s calendar without receiving the Google password. Which delegation protocol is used?', ['SAML', 'OAuth', 'JWT', 'OIDC'], 1, 'OAuth means Open Authorization. It lets a user delegate limited access without sharing a password.', ['Security']),
  term('An API receives a compact signed token containing JSON claims such as sub and exp. Which token format is this?', ['Session ID', 'JWT', 'CSRF token', 'API key'], 1, 'JWT means JSON Web Token. It is a compact format for signed or encrypted claims.', ['Security']),
  term('An employee signs in once and then opens several company applications without another login. Which capability is this?', ['SSO', 'MFA', 'OAuth', 'RBAC'], 0, 'SSO means Single Sign-On. One authenticated session provides access to multiple related services.', ['Security']),
  term('A login requires a password plus a security key, using two independent kinds of evidence. Which general control is this?', ['SSO', 'MFA', 'OAuth', 'RBAC'], 1, 'MFA means Multi-Factor Authentication. It combines factors from different categories such as knowledge and possession.', ['Security']),
  term('A bank specifically requires exactly two independent authentication factors. Which shorter label fits?', ['2FA', 'MFA', 'SSO', 'OTP'], 0, '2FA means Two-Factor Authentication. It is the case of MFA that uses exactly two factors.', ['Security']),
  term('Unsanitized comment text is inserted as HTML and runs an attacker\'s script in another user\'s browser. Which vulnerability is this?', ['CSRF', 'XSS', 'SSRF', 'SQLi'], 1, 'XSS means Cross-Site Scripting. Attacker-controlled script executes in the context of a trusted site.', ['Security']),
  term('A malicious page causes a signed-in browser to submit an unwanted transfer to another site. Which attack is this?', ['XSS', 'CSRF', 'SSRF', 'CORS'], 1, 'CSRF means Cross-Site Request Forgery. It abuses credentials a browser automatically includes with a request.', ['Security']),
  term('HTTPS needs a protocol that encrypts traffic and authenticates the server certificate. Which protocol provides that layer?', ['TLS', 'SSH', 'OAuth', 'DNSSEC'], 0, 'TLS means Transport Layer Security. HTTPS is HTTP carried over TLS.', ['Security']),

  // Level 8 — Networking
  term('A file transfer must arrive reliably and in order, and the application can tolerate retransmission. Which transport fits?', ['TCP', 'UDP', 'IP', 'QUIC datagram'], 0, 'TCP means Transmission Control Protocol. It provides an ordered, reliable byte stream.', ['Network']),
  term('A live game prefers a fresh position update over retransmitting an old lost packet. Which lightweight transport often fits?', ['TCP', 'UDP', 'HTTP', 'TLS'], 1, 'UDP means User Datagram Protocol. It sends independent datagrams without built-in delivery or ordering guarantees.', ['Network']),
  term('Routers need an addressing protocol to move packets between networks. Which protocol provides those addresses?', ['TCP', 'IP', 'DNS', 'MAC'], 1, 'IP means Internet Protocol. It provides packet addressing and routing across networks.', ['Network']),
  term('A browser knows example.com but needs the server address before connecting. Which system performs that lookup?', ['DNS', 'DHCP', 'ARP', 'NAT'], 0, 'DNS means Domain Name System. It maps domain names to records such as IP addresses.', ['Network']),
  term('The devices in one office are connected on the same local network. Which term describes that scope?', ['WAN', 'LAN', 'VPN', 'VPC'], 1, 'LAN means Local Area Network. It covers a limited area such as a home, office, or campus.', ['Network']),
  term('A company links offices in several countries over a network that spans long distances. Which term fits?', ['WAN', 'LAN', 'VLAN', 'VPN'], 0, 'WAN means Wide Area Network. It connects networks across large geographic areas.', ['Network']),
  term('A remote employee creates an encrypted tunnel into the private company network. Which service are they using?', ['VPN', 'VPC', 'NAT', 'LAN'], 0, 'VPN means Virtual Private Network. It creates a protected logical connection over another network.', ['Network']),
  term('A switch forwards an Ethernet frame using the hardware address of a network interface. Which address is that?', ['IP', 'MAC', 'DNS', 'URL'], 1, 'MAC means Media Access Control. A MAC address identifies an interface at the data-link layer.', ['Network']),

  // Level 9 — Databases and storage
  term('A bug report says the application cannot connect to its persistent data store. Which common shorthand names that store?', ['API', 'DB', 'ORM', 'CLI'], 1, 'DB is shorthand for database.', ['DB']),
  term('PostgreSQL manages tables, relations, constraints, and SQL queries. Which product category does it belong to?', ['RDBMS', 'NoSQL', 'ORM', 'OLAP'], 0, 'RDBMS means Relational Database Management System. It manages related tables and enforces the relational model.', ['DB']),
  term('A document store and a key-value store are grouped under a broad non-relational label. Which label is it?', ['RDBMS', 'NoSQL', 'OLTP', 'SQL'], 1, 'NoSQL commonly means non-relational or Not Only SQL. It covers several data models outside traditional relational tables.', ['DB']),
  term('Application code maps a User class to rows in a users table and generates queries. Which abstraction is doing that?', ['ORM', 'RDBMS', 'DAO', 'API'], 0, 'ORM means Object-Relational Mapper. It maps language-level objects to relational data.', ['DB']),
  term('A transaction must be all-or-nothing, isolated from concurrent work, and durable after commit. Which guarantee set is being requested?', ['ACID', 'BASE', 'CAP', 'CRUD'], 0, 'ACID means Atomicity, Consistency, Isolation, and Durability: the classic transaction properties.', ['DB']),
  term('A distributed store favors availability and accepts temporary inconsistency that later converges. Which model describes that choice?', ['BASE', 'ACID', 'OLTP', 'RDBMS'], 0, 'BASE is commonly expanded as Basically Available, Soft state, Eventual consistency.', ['DB']),
  term('An admin screen can create, view, edit, and remove customer records. Which shorthand covers those four operations?', ['ACID', 'CRUD', 'ETL', 'CQRS'], 1, 'CRUD means Create, Read, Update, and Delete.', ['DB']),
  term('A warehouse runs large analytical reports, while the checkout database handles many small transactions. Which pairing names those workloads?', ['OLAP for analytics; OLTP for transactions', 'OLTP for analytics; OLAP for transactions', 'ACID for analytics; BASE for transactions', 'ETL for analytics; CRUD for transactions'], 0, 'OLAP means Online Analytical Processing; OLTP means Online Transaction Processing.', ['DB']),

  // Level 10 — Cloud and infrastructure
  term('A team chooses Amazon\'s cloud for managed compute, storage, and networking. Which provider abbreviation will appear in the design?', ['AWS', 'Azure', 'GCP', 'OCI'], 0, 'AWS means Amazon Web Services, Amazon\'s public cloud platform.', ['Cloud']),
  term('A data team uses BigQuery and Cloud Run from Google\'s public cloud. Which provider abbreviation fits?', ['AWS', 'GCP', 'Azure', 'Cloudflare'], 1, 'GCP means Google Cloud Platform.', ['Cloud']),
  term('A workload needs its own guest operating system and virtualized hardware. Which compute unit fits?', ['Container', 'VM', 'Function', 'Pod'], 1, 'VM means Virtual Machine. It runs a guest operating system on virtualized hardware.', ['Cloud']),
  term('An AWS architecture diagram shows general-purpose virtual servers. Which AWS service label belongs on that box?', ['S3', 'EC2', 'Lambda', 'RDS'], 1, 'EC2 means Elastic Compute Cloud. It is AWS\'s general-purpose virtual compute service.', ['Cloud']),
  term('An AWS service stores uploaded objects in buckets and serves them by key. Which service is it?', ['EC2', 'S3', 'EBS', 'RDS'], 1, 'S3 means Simple Storage Service. It is AWS object storage.', ['Cloud']),
  term('Static assets should be cached at edge locations close to users around the world. Which infrastructure component does that?', ['VPN', 'CDN', 'DNS', 'VPC'], 1, 'CDN means Content Delivery Network. It serves cached content from distributed edge locations.', ['Cloud']),
  term('Customers use a hosted application in the browser while the vendor operates the software. Which delivery model is this?', ['SaaS', 'PaaS', 'IaaS', 'FaaS'], 0, 'SaaS means Software as a Service. The provider operates the application for its users.', ['Cloud']),
  term('A diagram compares raw virtual infrastructure, a managed application platform, and individual serverless functions. Which family of labels describes those layers?', ['SaaS, VPN, and CDN', 'IaaS, PaaS, and FaaS', 'EC2, S3, and RDS', 'LAN, WAN, and VPC'], 1, 'IaaS, PaaS, and FaaS mean Infrastructure, Platform, and Function as a Service.', ['Cloud']),

  // Level 11 — Architecture principles
  term('A web application separates domain data, presentation, and request handling into three roles. Which pattern names those roles?', ['MVVM', 'MVC', 'CQRS', 'BFF'], 1, 'MVC means Model-View-Controller. It separates data, presentation, and input or request handling.', ['Architecture']),
  term('A UI architecture places presentation state and commands in a ViewModel between the domain model and the view. Which pattern is this?', ['MVVM', 'MVC', 'MVP', 'DDD'], 0, 'MVVM means Model-View-ViewModel. The ViewModel exposes state and behavior tailored to the view.', ['Architecture']),
  term('A review discusses single responsibility, open/closed design, substitution, interface segregation, and dependency inversion. Which label groups them?', ['SOLID', 'DRY', 'KISS', 'YAGNI'], 0, 'SOLID is the common label for those five object-oriented design principles.', ['Architecture']),
  term('Two modules encode the same pricing rule, and fixes keep reaching only one copy. Which principle argues for one source of that knowledge?', ['DRY', 'KISS', 'SOLID', 'YAGNI'], 0, 'DRY means Don\'t Repeat Yourself. A piece of knowledge should have one authoritative representation.', ['Architecture']),
  term('A small feature is implemented with a clear function instead of a new framework and six abstractions. Which principle supports that choice?', ['DRY', 'KISS', 'SOLID', 'DDD'], 1, 'KISS means Keep It Simple, Stupid. Prefer the simplest design that meets the real need.', ['Architecture']),
  term('A developer proposes a plugin system for a requirement nobody has asked for. Which principle says to wait for evidence that it is needed?', ['YAGNI', 'KISS', 'DRY', 'SOLID'], 0, 'YAGNI means You Aren\'t Gonna Need It. Avoid speculative features and abstractions.', ['Architecture']),
  term('A team models code and conversations around the business terms used by domain experts. Which design approach is this?', ['DDD', 'MVC', 'CQRS', 'SOLID'], 0, 'DDD means Domain-Driven Design. It aligns software models and language with the business domain.', ['Architecture']),
  term('The mobile client and web client need different response shapes, so each gets a small tailored backend. What is that pattern called?', ['BFF', 'API gateway', 'MVC', 'Facade'], 0, 'BFF means Backend for Frontend. Each client gets a backend tailored to its needs.', ['Architecture']),

  // Level 12 — Performance metrics
  term('A page request starts now; the first response byte arrives 180 ms later. Which metric records that delay?', ['FCP', 'TTFB', 'LCP', 'INP'], 1, 'TTFB means Time to First Byte. It measures time from the request until the first response byte arrives.', ['Performance']),
  term('The first visible text or image appears on the page. Which paint milestone has just occurred?', ['TTFB', 'FCP', 'LCP', 'CLS'], 1, 'FCP means First Contentful Paint. It marks the first rendered text, image, canvas, or SVG content.', ['Performance']),
  term('The largest visible content element in the initial viewport finishes rendering. Which Core Web Vital records that point?', ['LCP', 'FCP', 'CLS', 'INP'], 0, 'LCP means Largest Contentful Paint. It measures when the largest visible content element is rendered.', ['Performance']),
  term('Images load without reserved space and push the article down. Which metric captures that unexpected movement?', ['LCP', 'CLS', 'INP', 'TBT'], 1, 'CLS means Cumulative Layout Shift. It measures unexpected visual movement during the page lifecycle.', ['Performance']),
  term('A user clicks, types, and opens a menu; a metric summarizes how quickly the page paints after those interactions. Which metric is it?', ['FID', 'INP', 'TBT', 'FCP'], 1, 'INP means Interaction to Next Paint. It measures page responsiveness across user interactions.', ['Performance']),
  term('An older report measures only the delay before the browser begins handling the first interaction. Which retired Core Web Vital is that?', ['FID', 'INP', 'TBT', 'TTFB'], 0, 'FID means First Input Delay. It measured the delay before handling the first interaction and was replaced by INP.', ['Performance']),
  term('A lab report sums the blocking portion of long main-thread tasks between first content and interactivity. Which metric is that?', ['TBT', 'INP', 'CLS', 'LCP'], 0, 'TBT means Total Blocking Time. It is a lab metric for main-thread blocking during page load.', ['Performance']),
  term('A load test reports that an API sustained 2,400 completed requests each second. Which throughput unit fits?', ['RPS', 'RPM', 'TTFB', 'QPS latency'], 0, 'RPS means Requests Per Second. It is a common measure of request throughput.', ['Performance']),

  // Level 13 — Testing and service quality
  term('A developer writes a failing test, implements the smallest passing change, then refactors. Which workflow are they following?', ['TDD', 'BDD', 'UAT', 'E2E'], 0, 'TDD means Test-Driven Development: red, green, then refactor.', ['Testing']),
  term('A team writes examples as Given, When, Then to discuss behavior with product experts. Which approach is this?', ['BDD', 'TDD', 'UAT', 'QA'], 0, 'BDD means Behavior-Driven Development. It uses concrete behavior examples to support collaboration.', ['Testing']),
  term('A role owns test strategy, release confidence, and wider software-quality practices. Which discipline is this?', ['SRE', 'QA', 'UAT', 'TDD'], 1, 'QA means Quality Assurance. It covers practices used to ensure software meets its quality goals.', ['Testing']),
  term('Real users or business representatives confirm that a release meets their needs before launch. Which test stage is this?', ['UAT', 'E2E', 'TDD', 'QA automation'], 0, 'UAT means User Acceptance Testing. Intended users verify that the system meets agreed business needs.', ['Testing']),
  term('A browser test starts at the UI, calls the real API, and verifies the stored result. Which scope does it have?', ['Integration', 'E2E', 'Unit', 'Contract'], 1, 'E2E means End-to-End. The test exercises a complete user path across the system.', ['Testing']),
  term('A startup releases the smallest useful product that can test its main assumption with customers. Which product term fits?', ['Prototype', 'MVP', 'POC', 'SLA'], 1, 'MVP means Minimum Viable Product. It is the smallest usable version that can deliver value and produce learning.', ['Testing']),
  term('A contract promises customers 99.9% monthly availability and defines compensation if it is missed. What is that commitment?', ['SLA', 'SLO', 'SLI', 'Error budget'], 0, 'SLA means Service Level Agreement. It is an external or contractual service commitment.', ['Testing']),
  term('An engineering team targets 99.95% of requests succeeding each month, without making that target a customer contract. What is it?', ['SLO', 'SLA', 'SLI', 'KPI'], 0, 'SLO means Service Level Objective. It is a target for a measured aspect of service reliability.', ['Testing']),

  // Level 14 — DevOps and containers
  term('A runbook says to inspect the Kubernetes cluster. Which compact name for Kubernetes might it use?', ['K3s', 'K8s', 'K9s', 'Kubelet'], 1, 'K8s is a numeronym for Kubernetes: there are eight letters between K and s.', ['DevOps']),
  term('Terraform files in version control define networks and servers instead of an operator creating them by hand. Which practice is this?', ['GitOps', 'IaC', 'CI', 'SRE'], 1, 'IaC means Infrastructure as Code. Infrastructure is defined and changed through versioned code or configuration.', ['DevOps']),
  term('A pipeline builds and tests each change, then keeps it releasable or deploys it. Which combined label fits?', ['CI/CD', 'SRE', 'IaC', 'UAT'], 0, 'CI/CD combines Continuous Integration with Continuous Delivery or Continuous Deployment.', ['DevOps']),
  term('A cloud policy grants one service account permission to read a bucket but not delete objects. Which system manages that access?', ['IAM', 'SSO', 'RBAC library', 'TLS'], 0, 'IAM means Identity and Access Management. It controls which identities can perform which actions on resources.', ['DevOps']),
  term('An operator wants a terminal interface for browsing Kubernetes pods, logs, and resources. Which tool fits?', ['K9s', 'K8s', 'kubectl plugin API', 'Docker Compose'], 0, 'K9s is a terminal user interface for working with Kubernetes clusters.', ['DevOps']),
  term('Two container runtimes can run the same image because both implement shared image and runtime standards. Which organization defines them?', ['CNCF', 'OCI', 'IETF', 'W3C'], 1, 'OCI means Open Container Initiative. It maintains open specifications for container images, runtimes, and distribution.', ['DevOps']),
  term('A team compares isolation: one option runs a guest OS, while the other shares the host kernel. Which statement is correct?', ['VMs share the host kernel; containers run a guest OS', 'Containers share the host kernel; VMs run a guest OS', 'Both always run a guest OS', 'Both always share every host process'], 1, 'A VM includes a guest operating system; a container isolates processes while sharing the host kernel.', ['DevOps']),
  term('Engineers use software practices, automation, and error budgets to operate reliable production services. Which discipline is this?', ['SRE', 'QA', 'ITIL', 'UAT'], 0, 'SRE means Site Reliability Engineering. It applies software engineering to production operations and reliability.', ['DevOps']),

  // Level 15 — Data and runtime concepts
  term('A pipeline reads source data, cleans and reshapes it, then writes the result to a warehouse. Which order is this?', ['ETL', 'ELT', 'CDC', 'OLAP'], 0, 'ETL means Extract, Transform, Load. Transformation happens before data is loaded into the target.', ['Data']),
  term('Raw data is written to a warehouse first and transformed there using the warehouse compute. Which order is this?', ['ELT', 'ETL', 'CDC', 'OLTP'], 0, 'ELT means Extract, Load, Transform. Transformation happens after loading into the target system.', ['Data']),
  term('Two compiled modules must agree on calling conventions, register use, and binary data layout. Which contract defines that?', ['ABI', 'API', 'FFI', 'AST'], 0, 'ABI means Application Binary Interface. It defines the low-level contract between compiled components.', ['Advanced']),
  term('Python code calls a function implemented in a native C library. Which mechanism connects code across those language boundaries?', ['ABI document', 'FFI', 'RPC', 'SDK'], 1, 'FFI means Foreign Function Interface. It lets code in one language call code written in another.', ['Advanced']),
  term('A runtime automatically reclaims heap memory that can no longer be reached by the program. Which subsystem does this?', ['JIT', 'GC', 'AOT', 'REPL'], 1, 'GC means Garbage Collection. It finds and reclaims memory that is no longer reachable.', ['Advanced']),
  term('A shell reads an expression, evaluates it, prints the result, and waits for the next expression. What kind of tool is it?', ['REPL', 'CLI parser', 'IDE', 'JIT'], 0, 'REPL means Read-Eval-Print Loop. It is an interactive environment for evaluating code.', ['Advanced']),
  term('A system uses separate models for commands that change state and queries that read it. Which architecture pattern is this?', ['CQRS', 'CRUD', 'MVC', 'ETL'], 0, 'CQRS means Command Query Responsibility Segregation. It separates write responsibilities from read responsibilities.', ['Advanced']),
  term('During a network partition, a distributed store must choose between rejecting some requests and serving possibly stale data. Which theorem frames that trade-off?', ['ACID', 'CAP', 'BASE', 'PACELC only'], 1, 'CAP means Consistency, Availability, and Partition tolerance. During a partition, a system cannot guarantee both consistency and availability.', ['Advanced']),
];
