// Betting Strategy roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const bettingStrategySeeds: Seed[] = [
  // ── Level 1 — Why we bet (value vs bluff, protection) ──
  { q: 'What are the two fundamental reasons to bet in poker?', opts: ['For value and as a bluff', 'To fold and to check', 'To limp and to raise', 'For luck and for tells'], a: 0, e: 'Almost every bet is either a value bet (hoping worse hands call) or a bluff (hoping better hands fold).', tags: ['Poker', 'Fundamentals'] },
  { q: 'A value bet is designed to be called by which type of hand?', opts: ['A worse hand', 'A better hand', 'Only the nuts', 'Only a folded hand'], a: 0, e: 'You value bet to extract chips from hands that are worse than yours but still likely to call.', tags: ['Poker', 'Value betting'] },
  { q: 'A bluff succeeds when it makes your opponent do what?', opts: ['Fold a better hand', 'Call with a worse hand', 'Raise the nuts', 'Check behind'], a: 0, e: 'A pure bluff wins the pot only by forcing a hand that beats you to fold.', tags: ['Poker', 'Bluffing'] },
  { q: 'Betting "for protection" mainly aims to do what?', opts: ['Deny opponents cheap draws to outdraw you', 'Guarantee you win at showdown', 'Build the biggest possible pot', 'Hide the strength of your hand'], a: 0, e: 'A protection bet charges drawing hands, denying them the equity they would get from seeing a free card.', tags: ['Poker', 'Protection'] },
  { q: 'You flop top set on a wet, draw-heavy board. Betting here is primarily for...', opts: ['Value and protection', 'A pure bluff', 'A blocker bet', 'Balance only'], a: 0, e: 'A strong made hand bets to get called by worse and to charge the many draws, combining value with protection.', tags: ['Poker', 'Protection'] },
  { q: 'When you hold the effective nuts, your main goal with a bet is to...', opts: ['Get called by worse hands', 'Make everyone fold', 'Keep the pot small', 'Induce a check'], a: 0, e: 'With the best hand you want action, so you size and bet to maximise calls from worse holdings.', tags: ['Poker', 'Value betting'] },
  { q: 'Which of these is NOT a reason to put chips in the pot?', opts: ['Because you dislike checking', 'To get value from worse hands', 'To fold out better hands', 'To deny equity to draws'], a: 0, e: 'Betting should always have a purpose (value, bluff, or protection); betting just to avoid checking is not a reason.', tags: ['Poker', 'Fundamentals'] },
  { q: 'A "thin value bet" refers to betting a hand that...', opts: ['Is only slightly ahead of the hands that call', 'Is the clear nuts', 'Has no showdown value at all', 'Can never be called by worse'], a: 0, e: 'Thin value means betting a marginal made hand that is called by a mix, but by enough worse hands to profit.', tags: ['Poker', 'Value betting'] },

  // ── Level 2 — Bet sizing fundamentals (relative to the pot) ──
  { q: 'The pot is $100 and you make a "half-pot" bet. How much do you bet?', opts: ['$50', '$25', '$100', '$150'], a: 0, e: 'Bet sizing is expressed relative to the pot; half of a $100 pot is a $50 bet.', tags: ['Poker', 'Bet sizing'] },
  { q: 'A "pot-sized bet" means your bet equals...', opts: ['The current size of the pot', 'Your whole stack', 'The big blind', 'Half the pot'], a: 0, e: 'A pot-sized bet is an amount equal to the chips already in the pot before your bet.', tags: ['Poker', 'Bet sizing'] },
  { q: 'An "overbet" is a bet that is...', opts: ['Larger than the current pot', 'Exactly half the pot', 'Equal to the big blind', 'Smaller than a min-bet'], a: 0, e: 'An overbet exceeds the size of the pot, applying maximum pressure and building the pot fast.', tags: ['Poker', 'Bet sizing'] },
  { q: 'Facing a half-pot bet, what pot odds equity do you need to call profitably?', opts: ['About 25%', 'About 50%', 'About 10%', 'About 40%'], a: 0, e: 'You risk $50 to win $150 ($100 pot + $50 bet), so you need 50/200 = 25% equity to break even.', tags: ['Poker', 'Pot odds'] },
  { q: 'Facing a pot-sized bet, roughly what equity do you need to call?', opts: ['About 33%', 'About 25%', 'About 50%', 'About 20%'], a: 0, e: 'You call the pot to win the pot plus your call: risk 1 to win 2, needing 1/3 = 33% equity.', tags: ['Poker', 'Pot odds'] },
  { q: 'For a half-pot BLUFF to break even, how often must your opponent fold?', opts: ['About 33% of the time', 'About 50% of the time', 'About 25% of the time', 'About 66% of the time'], a: 0, e: 'You risk 0.5 to win 1, so the bluff needs to work 0.5/1.5 = 33% of the time to be break-even.', tags: ['Poker', 'Bluffing'] },
  { q: 'Larger bet sizes generally make your betting range more...', opts: ['Polarized (nutted hands or bluffs)', 'Merged (lots of medium hands)', 'Random', 'Passive'], a: 0, e: 'Big bets risk a lot to win a lot, so they favour a polarized range of strong value and bluffs, not medium hands.', tags: ['Poker', 'Bet sizing'] },
  { q: 'Why is bet sizing usually measured relative to the pot rather than in fixed dollars?', opts: ['Because pot odds and pressure scale with pot size', 'Because dollars are hard to count', 'Because blinds never change', 'Because stacks are always equal'], a: 0, e: 'The odds you lay and the leverage you apply depend on the bet-to-pot ratio, so sizing is framed relative to the pot.', tags: ['Poker', 'Bet sizing'] },

  // ── Level 3 — Continuation bets and betting the flop ──
  { q: 'A "continuation bet" (c-bet) is a bet made on the flop by...', opts: ['The preflop aggressor', 'The player who called preflop', 'The big blind only', 'Whoever is last to act'], a: 0, e: 'A c-bet continues the aggression: the player who raised preflop follows up by betting the flop.', tags: ['Poker', 'C-betting'] },
  { q: 'On which flop texture is a high-frequency c-bet generally most effective?', opts: ['A dry, disconnected board like K-7-2', 'A wet board like 9-8-7 two-tone', 'A four-flush board', 'A double-paired board'], a: 0, e: 'Dry, disconnected boards miss the caller\'s range and favour the raiser, so c-bets get many folds cheaply.', tags: ['Poker', 'C-betting'] },
  { q: 'On a dry board that hits your range hard, a common effective c-bet size is...', opts: ['A small bet (about a third of the pot)', 'A pot-sized overbet', 'Your entire stack', 'A min-raise only'], a: 0, e: 'With a range advantage on a dry board you can bet small, denying equity cheaply while betting many hands.', tags: ['Poker', 'C-betting'] },
  { q: 'Having a "range advantage" on a flop means...', opts: ['Your range contains more strong hands than your opponent\'s', 'You hold the single best hand', 'You have position', 'You have more chips'], a: 0, e: 'Range advantage is having a higher proportion of strong holdings overall, which supports betting more often.', tags: ['Poker', 'Range advantage'] },
  { q: 'Why might you c-bet the flop with a strong made hand?', opts: ['To build the pot and charge draws', 'To fold out worse hands', 'To keep the pot small', 'To disguise weakness'], a: 0, e: 'Betting a strong hand grows the pot for value and denies free cards to hands drawing to beat you.', tags: ['Poker', 'C-betting'] },
  { q: 'On a very wet board that favours the caller, the preflop raiser should usually...', opts: ['C-bet less often and check more', 'C-bet 100% of hands', 'Always overbet', 'Never check any hand'], a: 0, e: 'When the board connects with the caller\'s range, blindly c-betting is punished, so checking more protects your range.', tags: ['Poker', 'C-betting'] },
  { q: 'A "delayed c-bet" is when the preflop raiser...', opts: ['Checks the flop and bets the turn instead', 'Bets flop, turn, and river', 'Bets only the river', 'Never bets at all'], a: 0, e: 'A delayed c-bet checks back the flop and takes the betting lead on the turn, often after the field weakens.', tags: ['Poker', 'C-betting'] },
  { q: 'Good bluffing candidates for a c-bet on the flop are typically hands with...', opts: ['Backdoor draws or overcards that can improve', 'No equity and no future potential', 'The current nuts', 'Only showdown value'], a: 0, e: 'Betting hands with some equity (draws, overcards) means you can still win by improving if called.', tags: ['Poker', 'C-betting'] },

  // ── Level 4 — Bluffing, semi-bluffing & fold equity ──
  { q: 'A "semi-bluff" is a bet made with a hand that...', opts: ['Is likely behind now but can improve to the best hand', 'Is already the nuts', 'Has zero chance to improve', 'Can never be called'], a: 0, e: 'A semi-bluff bets a drawing hand: you can win immediately by a fold, or later by hitting your draw.', tags: ['Poker', 'Semi-bluffing'] },
  { q: '"Fold equity" refers to...', opts: ['The extra value from the chance your opponent folds', 'The pot you win at showdown', 'The rake taken by the house', 'Your equity when all-in and called'], a: 0, e: 'Fold equity is the added expected value that comes from the possibility of making your opponent fold.', tags: ['Poker', 'Fold equity'] },
  { q: 'Why is a semi-bluff often better than a pure bluff?', opts: ['It has two ways to win: a fold now or hitting later', 'It never gets called', 'It requires no fold equity', 'It always makes the nuts'], a: 0, e: 'A semi-bluff wins if the opponent folds, and still has backup equity to make the best hand when called.', tags: ['Poker', 'Semi-bluffing'] },
  { q: 'A flush draw with two overcards is a strong semi-bluff mainly because it has...', opts: ['High equity when called', 'No equity at all', 'Guaranteed fold equity', 'The current best hand'], a: 0, e: 'Many outs (flush and pair cards) give it high equity, so barreling is profitable even when called.', tags: ['Poker', 'Semi-bluffing'] },
  { q: 'A "blocker" (or card-removal) bluff is stronger when your hole cards...', opts: ['Reduce the combinations of hands that could call you', 'Make a full house', 'Match the board pairs', 'Give you the nuts'], a: 0, e: 'Holding a card that blocks the opponent\'s strong calling hands means they are less likely to have a call.', tags: ['Poker', 'Blockers'] },
  { q: 'As stacks get deeper relative to the pot, your fold equity when betting tends to...', opts: ['Increase, because opponents risk more to continue', 'Disappear completely', 'Stay exactly the same', 'Become negative'], a: 0, e: 'Deeper stacks mean bets threaten more chips on later streets, giving your aggression more leverage and fold equity.', tags: ['Poker', 'Fold equity'] },
  { q: 'A good river bluffing spot often occurs when...', opts: ['An obvious draw missed and you have a blocker to value hands', 'You have just made the nuts', 'The board is completely blank for everyone', 'You have shown weakness all hand'], a: 0, e: 'When draws brick, few value hands remain; a credible story plus blockers makes a river bluff most effective.', tags: ['Poker', 'Bluffing'] },
  { q: 'Barreling (betting multiple streets) as a bluff works best when later cards...', opts: ['Favour your range and scare the opponent\'s hands', 'Always improve the opponent', 'Are irrelevant to both ranges', 'Complete every draw for the caller'], a: 0, e: 'Turn and river "scare cards" that credibly hit your range let you keep applying pressure and fold out marginal calls.', tags: ['Poker', 'Bluffing'] },

  // ── Level 5 — Multi-street planning, polarized vs merged ranges, thin value ──
  { q: 'A "polarized" betting range consists of...', opts: ['Strong value hands and bluffs, with few medium hands', 'Only medium-strength hands', 'Only drawing hands', 'A random mix of everything'], a: 0, e: 'A polarized range is split into nutted value bets and bluffs, which is why it can use large sizings.', tags: ['Poker', 'Ranges'] },
  { q: 'A "merged" (or linear) betting range is built mostly from...', opts: ['Strong and medium-strength value hands', 'Only pure bluffs', 'Only the absolute nuts', 'Hands with no equity'], a: 0, e: 'A merged range value-bets a band of strong and good-but-not-nutted hands, and pairs well with smaller sizings.', tags: ['Poker', 'Ranges'] },
  { q: 'Overbets are best paired with which kind of range?', opts: ['A polarized range', 'A merged range', 'A purely capped range', 'A range of only draws'], a: 0, e: 'Because overbets risk so much, they suit polarized ranges of very strong hands and bluffs, not medium value.', tags: ['Poker', 'Ranges'] },
  { q: 'Good "multi-street planning" primarily means...', opts: ['Choosing bet sizes across streets to reach a target stack outcome', 'Only thinking about the current bet', 'Always betting the same amount', 'Never betting the river'], a: 0, e: 'You plan flop, turn, and river sizings in advance so a value hand can get all the chips in by the river.', tags: ['Poker', 'Planning'] },
  { q: 'To get all-in by the river for value, you should generally...', opts: ['Size flop and turn bets so the river bet is a natural jam', 'Bet tiny early then shove river', 'Check the flop and turn always', 'Only bet the river'], a: 0, e: 'Geometric sizing means each street\'s bet is proportional so stacks go in smoothly by the river.', tags: ['Poker', 'Planning'] },
  { q: 'Stack-to-pot ratio (SPR) is important because a low SPR...', opts: ['Makes it easier to commit your whole stack', 'Guarantees you win the pot', 'Means bluffs always work', 'Removes the need to plan bets'], a: 0, e: 'A low SPR means fewer chips remain relative to the pot, so strong hands can profitably get all-in.', tags: ['Poker', 'Planning'] },
  { q: 'Which spot is the clearest example of a thin value bet on the river?', opts: ['Betting second pair when a station calls with worse pairs and draws', 'Betting the nut flush', 'Betting with no pair and no draw', 'Checking a full house'], a: 0, e: 'Thin value bets a modest made hand that is only slightly ahead, relying on being called by enough worse hands.', tags: ['Poker', 'Value betting'] },
  { q: 'Why can betting a polarized range use a much larger size than a merged range?', opts: ['Because it never needs medium hands to bluff-catch, so it can risk more', 'Because bluffs always win', 'Because it holds only medium hands', 'Because position never matters'], a: 0, e: 'A polarized range only bets nutted value and bluffs, so it can leverage big sizings without exposing medium hands.', tags: ['Poker', 'Ranges'] },
];
