import type { QuestionTranslation } from './quiz-data';

export const cartographyTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Čtení map ──
  'rm-carto-1': { introduction: 'Zamyslete se, co mapa vlastně zobrazuje.', question: 'Co je to mapa?', options: ['Trojrozměrný model budovy', 'Psaný seznam názvů míst', 'Plošné znázornění území souše nebo moře', 'Fotografie pořízená z letadla'], explanation: 'Mapa je plošná, zmenšená kresba, která znázorňuje prvky určitého území při pohledu shora.' },
  'rm-carto-2': { introduction: 'Hlavní světové strany.', question: 'Kolik je hlavních světových stran?', options: ['Čtyři', 'Šest', 'Osm', 'Dvanáct'], explanation: 'Čtyři hlavní světové strany jsou sever, východ, jih a západ.' },
  'rm-carto-3': { introduction: 'Vzpomeňte si na běžnou konvenci orientace map.', question: 'Která světová strana je na většině map nahoře?', options: ['Jih', 'Východ', 'Západ', 'Sever'], explanation: 'Podle dlouholeté konvence bývá sever obvykle umístěn na horním okraji mapy.' },
  'rm-carto-4': { introduction: 'Vyberte správnou čtveřici hlavních směrů.', question: 'Která množina uvádí čtyři hlavní světové strany?', options: ['Nahoru, dolů, vlevo, vpravo', 'Sever, východ, jih, západ', 'Severovýchod, jihovýchod, jihozápad, severozápad', 'Vpřed, vzad, levobok, pravobok'], explanation: 'Sever, východ, jih a západ jsou čtyři hlavní světové strany.' },
  'rm-carto-5': { introduction: 'Sever nahoře — kam ukazuje pravá strana?', question: 'Je-li na mapě sever nahoře, která světová strana je vpravo?', options: ['Východ', 'Západ', 'Jih', 'Severozápad'], explanation: 'Je-li sever nahoře, je východ vpravo, západ vlevo a jih dole.' },
  'rm-carto-6': { introduction: 'Odkud se člověk dívá při „ptačím pohledu"?', question: 'Pohled z ptačí perspektivy znamená dívat se na něco...', options: ['Z úrovně země', 'Ze strany', 'Přímo shora', 'Z podzemí'], explanation: 'Mapy zobrazují místa tak, jako by byla vidět přímo shora — z ptačí perspektivy neboli v půdorysu.' },
  'rm-carto-7': { introduction: 'Která světová strana leží přímo proti severu?', question: 'Která světová strana je přímo naproti severu?', options: ['Východ', 'Jih', 'Západ', 'Severovýchod'], explanation: 'Jih leží přímo naproti severu; východ a západ jsou naproti sobě.' },
  'rm-carto-8': { introduction: 'K čemu na mapě slouží směrová růžice?', question: 'Co na mapě zobrazuje směrová (větrná) růžice?', options: ['Cenu mapy', 'Jméno tvůrce mapy', 'Měřítko mapy', 'Orientaci a světové strany'], explanation: 'Směrová růžice vyznačuje hlavní světové strany a ukazuje, jak je mapa orientována.' },

  // ── Úroveň 2 — Zeměpisná šířka a délka ──
  'rm-carto-9': { introduction: 'Jak se jinak říká rovnoběžkám?', question: 'Rovnoběžky (linie zeměpisné šířky) se také nazývají...', options: ['Poledníky', 'Rovnoběžky', 'Vrstevnice', 'Azimuty'], explanation: 'Linie zeměpisné šířky vedou ve směru východ–západ a nazývají se rovnoběžky, protože zůstávají rovnoběžné s rovníkem.' },
  'rm-carto-10': { introduction: 'Jakou zeměpisnou šířku má rovník?', question: 'Jaká je zeměpisná šířka rovníku?', options: ['90°', '45°', '23,5°', '0°'], explanation: 'Rovník je definován jako 0° zeměpisné šířky a rozděluje Zemi na severní a jižní polokouli.' },
  'rm-carto-11': { introduction: 'Jak se jinak říká liniím zeměpisné délky?', question: 'Poledníky (linie zeměpisné délky) se také nazývají...', options: ['Poledníky', 'Rovnoběžky', 'Izobary', 'Obratníky'], explanation: 'Linie zeměpisné délky vedou ve směru sever–jih od pólu k pólu a nazývají se poledníky.' },
  'rm-carto-12': { introduction: 'Kudy prochází nultý poledník?', question: 'Nultý poledník (0° zeměpisné délky) prochází kterým místem?', options: ['Paříží ve Francii', 'Washingtonem, D.C.', 'Greenwichem v Londýně', 'Římem v Itálii'], explanation: 'Nultý poledník, 0° zeměpisné délky, prochází Greenwichem v Londýně.' },
  'rm-carto-13': { introduction: 'Kterým směrem se měří zeměpisná šířka?', question: 'Zeměpisná šířka udává vzdálenost místa v kterých směrech?', options: ['Východ a západ', 'Nahoru a dolů', 'Pouze k pólům', 'Sever a jih'], explanation: 'Zeměpisná šířka udává vzdálenost na sever nebo na jih od rovníku.' },
  'rm-carto-14': { introduction: 'Kterým směrem se měří zeměpisná délka?', question: 'Zeměpisná délka udává vzdálenost místa v kterých směrech?', options: ['Sever a jih', 'Východ a západ', 'Směrem k rovníku', 'Svisle'], explanation: 'Zeměpisná délka udává vzdálenost na východ nebo na západ od nultého poledníku.' },
  'rm-carto-15': { introduction: 'Které linie jsou rovnoběžné s rovníkem?', question: 'Které linie vedou rovnoběžně s rovníkem?', options: ['Linie zeměpisné délky', 'Poledníky', 'Linie zeměpisné šířky', 'Datová hranice'], explanation: 'Linie zeměpisné šířky (rovnoběžky) vedou ve směru východ–západ, rovnoběžně s rovníkem.' },
  'rm-carto-16': { introduction: 'Jaké je maximum zeměpisné šířky?', question: 'Jaké nejvyšší hodnoty může zeměpisná šířka dosáhnout, a to na pólech?', options: ['90°', '180°', '360°', '100°'], explanation: 'Zeměpisná šířka nabývá hodnot od 0° na rovníku po 90° na severním a jižním pólu.' },

  // ── Úroveň 3 — Měřítko mapy a vzdálenost ──
  'rm-carto-17': { introduction: 'Co vyjadřuje měřítko mapy?', question: 'Co vám prozradí měřítko mapy?', options: ['Vztah mezi vzdáleností na mapě a skutečnou vzdáleností v terénu', 'Stáří mapy', 'Počet použitých barev', 'Směr severu'], explanation: 'Měřítko vyjadřuje, jak vzdálenost na mapě odpovídá skutečné vzdálenosti v terénu.' },
  'rm-carto-18': { introduction: 'Přepočítejte poměr měřítka.', question: 'Měřítko 1:100 000 znamená, že 1 cm na mapě odpovídá jaké vzdálenosti v terénu?', options: ['100 cm', '1 000 cm', '100 000 cm', '10 cm'], explanation: 'Poměrové měřítko 1:100 000 znamená, že 1 cm na mapě odpovídá 100 000 cm (1 km) ve skutečnosti.' },
  'rm-carto-19': { introduction: 'Co ukazuje mapa velkého měřítka?', question: 'Mapa velkého měřítka zobrazuje...', options: ['Velkou oblast s malými podrobnostmi', 'Malou oblast ve velkých podrobnostech', 'Celý svět', 'Pouze oceány'], explanation: 'Mapy velkého měřítka (např. 1:10 000) pokrývají malé území, ale zobrazují velké množství podrobností.' },
  'rm-carto-20': { introduction: 'Co ukazuje mapa malého měřítka?', question: 'Mapa malého měřítka zobrazuje...', options: ['Malou oblast ve velkých podrobnostech', 'Jedinou ulici', 'Pouze póly', 'Velkou oblast s méně podrobnostmi'], explanation: 'Mapy malého měřítka (např. 1:1 000 000) pokrývají velká území s menším množstvím podrobností.' },
  'rm-carto-21': { introduction: 'Menší druhé číslo znamená větší měřítko.', question: 'Které z těchto měřítek je největší?', options: ['1:1 000 000', '1:250 000', '1:10 000', '1:500 000'], explanation: 'Čím menší je druhé číslo, tím větší je měřítko, takže 1:10 000 zde zobrazuje nejvíce podrobností.' },
  'rm-carto-22': { introduction: 'Grafické pravítko na mapě.', question: 'Grafické pravítko na mapě sloužící k měření skutečných vzdáleností se nazývá...', options: ['Grafické měřítko', 'Legenda', 'Souřadnicová síť', 'Vrstevnice'], explanation: 'Grafické měřítko (délkové měřítko) je grafické pravítko, podle kterého odměřujete skutečné vzdálenosti.' },
  'rm-carto-23': { introduction: 'Přepočítejte 2 cm při daném měřítku.', question: 'Kolik terénu představují 2 cm na mapě v měřítku 1:50 000?', options: ['500 m', '100 m', '5 km', '1 km'], explanation: 'Při měřítku 1:50 000 je 1 cm = 50 000 cm = 0,5 km, takže 2 cm představují 1 km.' },
  'rm-carto-24': { introduction: 'Který typ mapy nejlépe ukáže ulice města?', question: 'Který typ mapy by nejlépe zobrazil jednotlivé ulice jednoho města?', options: ['Mapa světa malého měřítka', 'Mapa velkého měřítka', 'Globus', 'Mapa 1:1 000 000'], explanation: 'Mapa velkého měřítka pokrývá malé území s velkou podrobností — ideální pro ulice města.' },

  // ── Úroveň 4 — Kartografická zobrazení ──
  'rm-carto-25': { introduction: 'Co je to kartografické zobrazení?', question: 'Kartografické zobrazení je způsob, jak...', options: ['Měřit teplotu', 'Zobrazit pouze oceány', 'Promítat filmy na plátno', 'Znázornit zakřivenou Zemi na plochém povrchu'], explanation: 'Zobrazení je metoda, jak znázornit povrch kulaté Země na ploché mapě.' },
  'rm-carto-26': { introduction: 'Čím je proslulé Mercatorovo zobrazení?', question: 'Mercatorovo zobrazení je známé tím, že zkresluje...', options: ['Barvy oceánů', 'Velikost souše v blízkosti pólů', 'Názvy zemí', 'Časová pásma'], explanation: 'Na Mercatorově mapě se oblasti v blízkosti pólů jeví mnohem větší, než ve skutečnosti jsou.' },
  'rm-carto-27': { introduction: 'Jak vypadá Grónsko na Mercatorově mapě?', question: 'Na Mercatorově mapě vypadá Grónsko...', options: ['Ve své skutečné velikosti', 'Mnohem menší, než je', 'Mnohem větší, než ve skutečnosti je', 'Stejně velké jako Island'], explanation: 'Mercator obrovsky zveličuje polární oblasti, takže Grónsko vypadá zhruba stejně velké jako Afrika, přestože je mnohem menší.' },
  'rm-carto-28': { introduction: 'Které znázornění nezkresluje tvary ani plochy?', question: 'Které znázornění zobrazuje Zemi bez zkreslení tvarů či ploch?', options: ['Globus', 'Mercatorova mapa', 'Gall–Petersova mapa', 'Silniční atlas'], explanation: 'Pouze globus znázorňuje povrch Země bez zkreslení způsobeného jejím zploštěním.' },
  'rm-carto-29': { introduction: 'K čemu je navrženo Robinsonovo zobrazení?', question: 'Robinsonovo zobrazení je navrženo tak, aby...', options: ['Dokonale zachovalo plochu', 'Zobrazilo celý svět s vyváženým, málo zkresleným vzhledem', 'Zmapovalo pouze oceány', 'Zachovalo přímé směrové linie'], explanation: 'Robinsonovo zobrazení je kompromis, který snižuje celkové zkreslení kvůli přitažlivé mapě světa, ačkoli přesně nezachovává ani plochu, ani tvar.' },
  'rm-carto-30': { introduction: 'Co zachovává Gall–Petersovo zobrazení?', question: 'Gall–Petersovo zobrazení je příkladem zobrazení, které zachovává...', options: ['Přesný tvar', 'Směrové azimuty', 'Vzdálenost všude', 'Poměrnou plochu'], explanation: 'Gall–Peters je stejnoplochým zobrazením: zobrazuje země ve správných poměrných velikostech, ačkoli tvary jsou protažené.' },
  'rm-carto-31': { introduction: 'Proč každá plochá mapa Zemi zkresluje?', question: 'Proč každá plochá mapa nějakým způsobem zkresluje Zemi?', options: ['Protože kouli nelze zploštit, aniž byste ji protáhli nebo roztrhli', 'Protože inkoust časem bledne', 'Protože Země je plochá', 'Kvůli magnetickému severu'], explanation: 'Kouli nelze rozvinout do roviny bez protažení, stlačení nebo roztržení, takže všechny ploché mapy něco zkreslují.' },
  'rm-carto-32': { introduction: 'Zobrazení zachovávající tvary malých oblastí.', question: 'Zobrazení, které zachovává správné tvary malých oblastí, se označuje jako...', options: ['Stejnoplochá', 'Ekvidistantní', 'Konformní', 'Azimutálně-plošné'], explanation: 'Konformní zobrazení (jako Mercatorovo) zachovává místní tvary a úhly za cenu zkreslení velikosti.' },

  // ── Úroveň 5 — Kompas a směr ──
  'rm-carto-33': { introduction: 'Kolik má osmisměrný kompas směrů?', question: 'Kolik směrů má osmisměrný kompas?', options: ['Čtyři', 'Šest', 'Osm', 'Dvanáct'], explanation: 'Osmisměrný kompas přidává ke čtyřem hlavním světovým stranám SV, JV, JZ a SZ.' },
  'rm-carto-34': { introduction: 'Vyberte vedlejší (mezilehlý) směr.', question: 'Který z těchto směrů je vedlejší (mezilehlý)?', options: ['Sever', 'Jih', 'Západ', 'Severovýchod'], explanation: 'Severovýchod, jihovýchod, jihozápad a severozápad jsou vedlejší směry mezi hlavními světovými stranami.' },
  'rm-carto-35': { introduction: 'Od kterého směru se měří azimut?', question: 'Azimut se měří ve stupních po směru hodinových ručiček od kterého směru?', options: ['Sever', 'Východ', 'Jih', 'Slunce'], explanation: 'Azimuty se měří po směru hodinových ručiček od severu, od 000° až po 360°.' },
  'rm-carto-36': { introduction: 'Kterým směrem ukazuje azimut 090°?', question: 'Azimut 090° míří kterým směrem?', options: ['Sever', 'Východ', 'Jih', 'Západ'], explanation: 'Na azimutové stupnici je 000° sever, 090° východ, 180° jih a 270° západ.' },
  'rm-carto-37': { introduction: 'Kam ukazuje pravý sever?', question: 'Pravý (zeměpisný) sever míří k...', options: ['Nejbližší hoře', 'Magnetickému pólu v Kanadě', 'Kamkoli právě ukazuje střelka', 'Zeměpisnému severnímu pólu Země'], explanation: 'Pravý sever je směr k zeměpisnému severnímu pólu Země, k bodu její osy.' },
  'rm-carto-38': { introduction: 'Co je magnetický sever?', question: 'Magnetický sever je...', options: ['Místo, kde vychází slunce', 'Místo, kde se tisknou mapy', 'Směr, kterým ukazuje střelka kompasu a který se liší od pravého severu', 'Bod, kde se rovník setkává s pólem'], explanation: 'Střelka kompasu ukazuje k magnetickému severu, který je odchýlen od pravého (zeměpisného) severu.' },
  'rm-carto-39': { introduction: 'Jak se nazývá úhel mezi pravým a magnetickým severem?', question: 'Úhel mezi pravým severem a magnetickým severem se nazývá...', options: ['Zeměpisná šířka', 'Deklinace', 'Azimut', 'Azimut (angl. azimuth)'], explanation: 'Magnetická deklinace (neboli variace) je úhel mezi pravým severem a magnetickým severem na daném místě.' },
  'rm-carto-40': { introduction: 'Kterým směrem ukazuje azimut 270°?', question: 'Azimut 270° míří kterým směrem?', options: ['Západ', 'Východ', 'Jih', 'Sever'], explanation: 'Měřeno po směru hodinových ručiček od severu odpovídá 270° západu.' },

  // ── Úroveň 6 — Vrstevnice a reliéf ──
  'rm-carto-41': { introduction: 'Co spojují vrstevnice na mapě?', question: 'Vrstevnice na mapě spojují body se stejnou...', options: ['Nadmořskou výškou', 'Teplotou', 'Srážkovou úhrnem', 'Hustotou zalidnění'], explanation: 'Vrstevnice spojuje body, které jsou ve stejné výšce nad mořem.' },
  'rm-carto-42': { introduction: 'Mapa zobrazující výšku a tvar terénu.', question: 'Mapa, která zobrazuje nadmořskou výšku a tvar terénu, se nazývá...', options: ['Politická mapa', 'Topografická mapa', 'Povětrnostní mapa', 'Silniční mapa'], explanation: 'Topografická mapa používá vrstevnice k zobrazení výšky a tvaru (reliéfu) terénu.' },
  'rm-carto-43': { introduction: 'Co znamenají hustě nakreslené vrstevnice?', question: 'Když jsou vrstevnice velmi blízko u sebe, svah je...', options: ['Rovný', 'Mírný', 'Pod vodou', 'Strmý'], explanation: 'Hustě umístěné vrstevnice znamenají, že terén prudce stoupá nebo klesá — strmý svah.' },
  'rm-carto-44': { introduction: 'Co znamenají vrstevnice daleko od sebe?', question: 'Když jsou vrstevnice daleko od sebe, terén je...', options: ['Velmi strmý', 'Svislý útes', 'Mírně svažitý nebo téměř rovný', 'Pod hladinou moře'], explanation: 'Řídce umístěné vrstevnice naznačují mírné svahy nebo téměř rovný terén.' },
  'rm-carto-45': { introduction: 'Výškový rozdíl mezi dvěma sousedními vrstevnicemi.', question: 'Výškový rozdíl mezi dvěma sousedními vrstevnicemi je...', options: ['Faktor měřítka', 'Interval vrstevnic (ekvidistance)', 'Souřadnice v síti', 'Azimut'], explanation: 'Interval vrstevnic (ekvidistance) je pevný svislý rozestup mezi po sobě jdoucími vrstevnicemi.' },
  'rm-carto-46': { introduction: 'Co na mapě znamená pojem „reliéf"?', question: 'Pojem „reliéf" na mapě označuje...', options: ['Tvar a výšku zemského povrchu', 'Celkový úhrn srážek', 'Silniční síť', 'Hustotu zalidnění'], explanation: 'Reliéf popisuje tvar a výšku terénu — jeho kopce, údolí a svahy.' },
  'rm-carto-47': { introduction: 'Uzavřené smyčky s vyššími hodnotami směrem ke středu.', question: 'Vrstevnice tvořící uzavřené smyčky s vyššími hodnotami směrem ke středu obvykle znázorňují...', options: ['Jezero', 'Údolí', 'Kopec nebo horu', 'Ústí řeky'], explanation: 'Soustředné uzavřené vrstevnice rostoucí směrem ke středu naznačují kopec nebo vrchol.' },
  'rm-carto-48': { introduction: 'Vrstevnice ohnuté do písmene V mířícího do kopce.', question: 'Vrstevnice ohýbající se do písmene V, které míří do kopce, často označují...', options: ['Útes', 'Náhorní plošinu', 'Rovnou nížinu', 'Údolí nebo potok'], explanation: 'Tam, kde vrstevnice tvoří V mířící k vyšším místům, prochází údolí — často s vodním tokem.' },

  // ── Úroveň 7 — Značky, klíče a legendy ──
  'rm-carto-49': { introduction: 'Část mapy vysvětlující významy značek.', question: 'Část mapy, která vysvětluje, co značky znamenají, se nazývá...', options: ['Měřítko', 'Název', 'Kompas', 'Legenda'], explanation: 'Legenda neboli klíč uvádí značky mapy a stanoví, co každá z nich představuje.' },
  'rm-carto-50': { introduction: 'K čemu slouží mapové značky?', question: 'Mapové značky se používají k...', options: ['Ozdobě mapy', 'Skrytí informací', 'Znázornění skutečných objektů jednoduchou zmenšenou formou', 'Zobrazení ceny'], explanation: 'Značky zastupují skutečné objekty (silnice, kostely, lesy) v úsporné a snadno čitelné podobě.' },
  'rm-carto-51': { introduction: 'Co obvykle znázorňuje modrá barva?', question: 'Na většině map se modrá barva běžně používá k zobrazení...', options: ['Lesů', 'Vody', 'Silnic', 'Hor'], explanation: 'Modrá tradičně představuje vodní prvky, jako jsou řeky, jezera a moře.' },
  'rm-carto-52': { introduction: 'K čemu slouží souřadnice v síti?', question: 'Souřadnice v síti se používají k...', options: ['Přesnému určení polohy na mapě', 'Měření teploty', 'Zobrazení stáří mapy', 'Vysvětlení měřítka'], explanation: 'Souřadnice v síti používají číslované linie (svislice a vodorovnice) k určení přesné polohy.' },
  'rm-carto-53': { introduction: 'Svislé linie sítě, které se čtou první.', question: 'Svislé linie souřadnicové sítě, které se v souřadnicích čtou jako první, se nazývají...', options: ['Vodorovnice (severingy)', 'Vrstevnice', 'Svislice (eastingy)', 'Poledníky'], explanation: 'Svislice (eastingy) jsou svislé linie sítě; čtou se jako první („nejprve chodbou, pak po schodech nahoru").' },
  'rm-carto-54': { introduction: 'V jakém pořadí se čtou čísla souřadnic?', question: 'Ve čtyřmístné souřadnici v síti, v jakém pořadí čtete čísla?', options: ['Nejprve vodorovnici, pak svislici', 'Nejprve šířku, pak délku', 'Nejprve horní, pak dolní', 'Nejprve svislici, pak vodorovnici'], explanation: 'Nejprve se čte svislice (podél), potom vodorovnice (nahoru).' },
  'rm-carto-55': { introduction: 'Co obvykle znamená zelené vybarvení?', question: 'Zelené vybarvení na topografické mapě nejčastěji označuje...', options: ['Vegetaci, jako je les', 'Hluboký oceán', 'Zastavěné městské oblasti', 'Vysoké hory'], explanation: 'Zelená se běžně používá k zobrazení vegetace, jako jsou lesy a hvozdy.' },
  'rm-carto-56': { introduction: 'Vodorovné linie sítě.', question: 'Vodorovné linie souřadnicové sítě na mapě se nazývají...', options: ['Svislice (eastingy)', 'Vodorovnice (severingy)', 'Rovnoběžky', 'Izobary'], explanation: 'Vodorovnice (severingy) jsou vodorovné linie sítě, jejichž čísla rostou směrem na sever.' },

  // ── Úroveň 8 — Časová pásma ──
  'rm-carto-57': { introduction: 'Na kolik základních časových pásem je svět rozdělen?', question: 'Přibližně na kolik základních časových pásem je svět rozdělen?', options: ['12', '24', '36', '60'], explanation: 'Země je rozdělena přibližně na 24 základních časových pásem, jedno pro každou hodinu dne.' },
  'rm-carto-58': { introduction: 'Zkratka světového referenčního standardu času.', question: 'Jaká je zkratka celosvětového referenčního standardu občanského času?', options: ['UTC', 'MPH', 'DST', 'GPS'], explanation: 'Koordinovaný světový čas (UTC), úzce sladěný s GMT, je světovým časovým standardem.' },
  'rm-carto-59': { introduction: 'Proč vůbec časová pásma existují?', question: 'Proč časová pásma existují?', options: ['Země se navzájem nemají rády', 'Slunce se fyzicky pohybuje kolem Země', 'Země se otáčí, takže na různých místech je den a noc v jinou dobu', 'Kvůli magnetickému severu'], explanation: 'Jak se Země otáčí, poledne nastává na různých místech planety v jiných okamžicích, a tak jsou místní hodiny posunuty do pásem.' },
  'rm-carto-60': { introduction: 'Kudy přibližně vede datová hranice?', question: 'Datová hranice vede zhruba podél kterého poledníku?', options: ['0°', '90° v. d.', '45° z. d.', '180°'], explanation: 'Datová hranice leží zhruba na 180° zeměpisné délky, naproti nultému poledníku.' },
  'rm-carto-61': { introduction: 'Co se stane při překročení datové hranice na západ?', question: 'Při překročení datové hranice směrem na západ...', options: ['Posunete datum o jeden den dopředu', 'Vrátíte se pouze o jednu hodinu', 'Nic se nezmění', 'Ztratíte celý týden'], explanation: 'Při překročení datové hranice na západ přidáváte jeden den; při cestě na východ jeden den ubíráte.' },
  'rm-carto-62': { introduction: 'O kolik se liší sousední časová pásma?', question: 'Každé základní časové pásmo se od sousedního liší přibližně o...', options: ['Jednu minutu', 'Jednu hodinu', 'Dvě hodiny', 'Půl dne'], explanation: 'Při 24 pásmech pokrývajících celý svět jsou sousední pásma vzdálena přibližně jednu hodinu.' },
  'rm-carto-63': { introduction: 'Co znamená zkratka GMT?', question: 'Co znamená zkratka GMT?', options: ['Global Map Time', 'General Meridian Time', 'Greenwich Magnetic Time', 'Greenwich Mean Time (greenwichský střední čas)'], explanation: 'GMT je Greenwich Mean Time, greenwichský střední čas, tj. střední sluneční čas na nultém poledníku v Greenwichi.' },
  'rm-carto-64': { introduction: 'Kolik stupňů zeměpisné délky zabírá jedno pásmo?', question: 'Přibližně kolik stupňů zeměpisné délky zabírá jedno časové pásmo?', options: ['1°', '5°', '15°', '45°'], explanation: '360° děleno 24 pásmy dává přibližně 15° zeměpisné délky na jedno časové pásmo.' },

  // ── Úroveň 9 — GPS a moderní mapování ──
  'rm-carto-65': { introduction: 'Co znamená zkratka GPS?', question: 'Co znamená zkratka GPS?', options: ['Geographic Plotting Service', 'Ground Position Sensor', 'Global Positioning System (globální polohovací systém)', 'General Placement System'], explanation: 'GPS znamená Global Positioning System, tj. globální polohovací systém založený na družicích.' },
  'rm-carto-66': { introduction: 'Odkud GPS získává signály pro určení polohy?', question: 'GPS určuje vaši polohu pomocí signálů z...', options: ['Pouze z mobilních vysílačů', 'Družic obíhajících Zemi', 'Podmořských kabelů', 'Magnetických pólů'], explanation: 'Přijímače GPS využívají časové signály vysílané družicemi obíhajícími Zemi.' },
  'rm-carto-67': { introduction: 'Kolik družic je potřeba pro 3D určení polohy?', question: 'Kolik družic minimálně potřebuje přijímač GPS pro trojrozměrné (3D) určení polohy?', options: ['4', '1', '12', '24'], explanation: 'K výpočtu zeměpisné šířky, délky a nadmořské výšky (3D určení) jsou potřeba nejméně čtyři družice.' },
  'rm-carto-68': { introduction: 'Co znamená zkratka GIS?', question: 'Co znamená zkratka GIS?', options: ['Global Imaging Service', 'Ground Inspection System', 'Geological Index Survey', 'Geographic Information System (geografický informační systém)'], explanation: 'Geografický informační systém (GIS) ukládá, analyzuje a zobrazuje prostorová data ve vrstvách.' },
  'rm-carto-69': { introduction: 'Co znamená dálkový průzkum Země?', question: 'Dálkový průzkum Země znamená získávání informací o Zemi...', options: ['Kopáním do země', 'Z dálky, např. pomocí družice nebo letadla', 'Rozhovory s lidmi', 'Pouze pomocí magnetického kompasu'], explanation: 'Dálkový průzkum Země shromažďuje data o Zemi z dálky, obvykle pomocí družic nebo letadel.' },
  'rm-carto-70': { introduction: 'Metoda, kterou GPS určuje polohu z několika vzdáleností.', question: 'Metoda, kterou GPS určuje vaši polohu z několika vzdáleností k družicím, se nazývá...', options: ['Triangulace úhlů', 'Deklinace', 'Trilaterace', 'Kartografické zobrazení'], explanation: 'GPS využívá trilateraci, kdy kombinuje změřené vzdálenosti k několika družicím k přesnému určení polohy.' },
  'rm-carto-71': { introduction: 'Jak jsou v GIS uloženy různé typy informací?', question: 'V systému GIS jsou různé druhy informací (silnice, řeky, využití půdy) uloženy jako...', options: ['Vrstevnice', 'Azimuty', 'Kartografická zobrazení', 'Vrstvy'], explanation: 'GIS organizuje různé druhy prostorových dat jako samostatné vrstvy, které lze překrývat.' },
  'rm-carto-72': { introduction: 'Družicové a letecké snímky jako produkt čeho?', question: 'Družicové snímky a letecké fotografie jsou příklady dat získaných pomocí...', options: ['Dálkového průzkumu Země', 'Trilaterace', 'Souřadnic v síti', 'Vrstevnicového měření'], explanation: 'Družicové a letecké snímky jsou klasickými produkty dálkového průzkumu Země.' },

  // ── Úroveň 10 — Mistrovství v kartografii ──
  'rm-carto-73': { introduction: 'Na jaké šířce leží obratník Raka?', question: 'Obratník Raka leží přibližně na jaké zeměpisné šířce?', options: ['23,5° s. š.', '23,5° j. š.', '0°', '66,5° s. š.'], explanation: 'Obratník Raka leží asi na 23,5° severní šířky; obratník Kozoroha je asi na 23,5° jižní šířky.' },
  'rm-carto-74': { introduction: 'Které zobrazení nejvíce klamavě zvětšuje polární oblasti?', question: 'Které zobrazení nejklamavěji zvětšuje Antarktidu a Grónsko?', options: ['Gall–Peters', 'Robinson', 'Globus', 'Mercator'], explanation: 'Mercatorovo zobrazení výrazně zveličuje oblasti v blízkosti pólů, takže Grónsko a Antarktida vypadají obrovské.' },
  'rm-carto-75': { introduction: 'Kde leží bod 0° šířky a 0° délky?', question: 'Místo na 0° zeměpisné šířky a 0° zeměpisné délky leží v...', options: ['Tichém oceánu', 'Atlantském oceánu u západní Afriky', 'Sahaře', 'Indickém oceánu'], explanation: 'Rovník a nultý poledník se protínají v bodě 0°, 0° v Guinejském zálivu v Atlantském oceánu jižně od Ghany.' },
  'rm-carto-76': { introduction: 'Přepočítejte 4 cm při daném měřítku.', question: 'Kolik skutečné vzdálenosti představují 4 cm na mapě v měřítku 1:25 000?', options: ['250 m', '2,5 km', '1 km', '100 m'], explanation: 'Při měřítku 1:25 000 je 1 cm = 25 000 cm = 0,25 km, takže 4 cm představují 1 km.' },
  'rm-carto-77': { introduction: 'Na jaké šířce leží obratník Kozoroha?', question: 'Obratník Kozoroha se nachází přibližně na jaké zeměpisné šířce?', options: ['23,5° s. š.', '66,5° j. š.', '0°', '23,5° j. š.'], explanation: 'Obratník Kozoroha leží asi na 23,5° jižně od rovníku.' },
  'rm-carto-78': { introduction: 'Co zachovává stejnoplochá zobrazení?', question: 'Stejnoplochá zobrazení je takové, které zachovává...', options: ['Správné poměrné velikosti oblastí', 'Přesný tvar každého pobřeží', 'Přímé směrové azimuty', 'Vzdálenosti mezi všemi body'], explanation: 'Stejnoplochá (ekvivalentní) zobrazení zachovávají správné poměrné velikosti oblastí, ačkoli tvary jsou zkreslené.' },
  'rm-carto-79': { introduction: 'Linie na 66,5° s. š. ohraničující oblast půlnočního slunce.', question: 'Linie asi na 66,5° s. š., která vymezuje okraj oblasti s možností půlnočního slunce, je...', options: ['Nultý poledník', 'Obratník Raka', 'Severní polární kruh', 'Rovník'], explanation: 'Severní polární kruh leží asi na 66,5° s. š.; severně od něj může slunce o letním slunovratu zůstat nad obzorem 24 hodin.' },
  'rm-carto-80': { introduction: 'Přepočítejte místní čas 45° východně od Greenwiche.', question: 'Je-li 12:00 poledne UTC, přibližný místní sluneční čas 45° východně od Greenwiche je...', options: ['9:00 ráno', '15:00 (3:00 odpoledne)', '12:00 poledne', '18:00 (6:00 večer)'], explanation: 'Každých 15° zeměpisné délky na východ přidává jednu hodinu, takže 45° na východ je asi o tři hodiny napřed — kolem 15:00.' },
};
