// Intellectual History roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const intellectualHistorySeeds: Seed[] = [
  // ── Level 1 — Ancient Philosophy ──
  { q: 'Socrates is best known for a style of inquiry based on what?', opts: ['Persistent questioning of assumptions', 'Writing lengthy treatises', 'Mathematical proof', 'Religious revelation'], a: 0, e: 'The Socratic method (elenchus) probes beliefs through systematic questioning to expose contradictions.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  { q: 'Plato\'s Theory of Forms holds that ultimate reality consists of what?', opts: ['Atoms in a void', 'Eternal, unchanging Forms', 'Sense impressions', 'Divine commandments'], a: 1, e: 'For Plato, perfect and eternal Forms are more real than their imperfect physical copies.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  { q: 'In which dialogue does Plato describe an ideal state ruled by philosopher-kings?', opts: ['The Iliad', 'Nicomachean Ethics', 'The Republic', 'Meditations'], a: 2, e: 'Plato\'s Republic outlines a just city governed by wisdom-loving philosopher-rulers.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  { q: 'Aristotle\'s concept of eudaimonia is best translated as what?', opts: ['Pleasure', 'Human flourishing', 'Wealth', 'Fame'], a: 1, e: 'Eudaimonia is a life of flourishing achieved through virtuous activity, the goal of ethics for Aristotle.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  { q: 'Aristotle held that moral virtue typically lies where?', opts: ['In total self-denial', 'In a mean between two extremes', 'In following pleasure', 'In strict obedience'], a: 1, e: 'His doctrine of the mean places virtue between the vices of excess and deficiency, e.g. courage between rashness and cowardice.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  { q: 'The Confucian virtue of ren is best described as what?', opts: ['Benevolence or humaneness', 'Military strength', 'Ritual purity', 'Material wealth'], a: 0, e: 'Ren, central to Confucian ethics, denotes humaneness and benevolence toward others.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  { q: 'Daoism, linked to the Dao De Jing, emphasizes which idea?', opts: ['Rigid legal codes', 'Harmony with the Dao and wu wei', 'Conquest of nature', 'Strict caste duty'], a: 1, e: 'Daoism urges living in accord with the Dao and wu wei, effortless action that does not force events.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  { q: 'The Buddhist Four Noble Truths begin with which recognition?', opts: ['The world is an illusion', 'Existence involves suffering (dukkha)', 'The soul is eternal', 'Desire should be maximized'], a: 1, e: 'The first Noble Truth identifies dukkha (suffering); the others trace its cause and its cessation via the Eightfold Path.', tags: ['Intellectual History', 'Ancient Philosophy'] },
  // ── Level 2 — Religious & Medieval Thought ──
  { q: 'Medieval scholasticism chiefly sought to do what?', opts: ['Reject all ancient learning', 'Reconcile faith with reason', 'Abolish universities', 'Replace theology with science'], a: 1, e: 'Scholastics used rigorous logic, often Aristotelian, to harmonize Christian doctrine with rational argument.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  { q: 'Thomas Aquinas is famous for synthesizing Christian theology with whose philosophy?', opts: ['Epicurus', 'Aristotle', 'Democritus', 'Pythagoras'], a: 1, e: 'In the Summa Theologica, Aquinas integrated Aristotelian philosophy with Catholic theology.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  { q: 'Aquinas\'s famous Five Ways are arguments for what?', opts: ['The immortality of the soul', 'The existence of God', 'The value of poverty', 'The structure of the Church'], a: 1, e: 'The Five Ways offer rational demonstrations of God\'s existence, including the arguments from motion and causation.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  { q: 'Augustine of Hippo\'s Confessions is notable as an early example of what?', opts: ['A scientific treatise', 'Spiritual autobiography', 'A legal code', 'An epic poem'], a: 1, e: 'Augustine\'s Confessions is a pioneering introspective autobiography blending Christian theology with Neoplatonism.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  { q: 'Anselm of Canterbury is known for which argument for God?', opts: ['The ontological argument', 'The wager argument', 'The evolutionary argument', 'The historical argument'], a: 0, e: 'Anselm\'s ontological argument reasons from the concept of God as that than which nothing greater can be conceived.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  { q: 'The Islamic philosopher Averroes (Ibn Rushd) was especially influential as what?', opts: ['A commentator on Aristotle', 'A critic of all philosophy', 'A poet', 'A conqueror'], a: 0, e: 'Averroes\'s detailed commentaries on Aristotle deeply shaped later Jewish and Christian scholasticism.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  { q: 'Al-Ghazali\'s The Incoherence of the Philosophers did what?', opts: ['Defended Greek metaphysics', 'Criticized certain philosophers\' claims', 'Founded algebra', 'Rejected the Quran'], a: 1, e: 'Al-Ghazali challenged the necessitarian metaphysics of philosophers like Avicenna, defending theological positions.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  { q: 'Maimonides\' Guide for the Perplexed aimed to reconcile Judaism with what?', opts: ['Roman law', 'Aristotelian philosophy', 'Egyptian religion', 'Persian astrology'], a: 1, e: 'The Jewish philosopher Maimonides sought to harmonize Torah with Aristotelian reason.', tags: ['Intellectual History', 'Religious & Medieval Thought'] },
  // ── Level 3 — Renaissance Humanism & the Enlightenment ──
  { q: 'Renaissance humanism centered on the renewed study of what?', opts: ['Classical Greek and Roman texts', 'Alchemy', 'Feudal law', 'Monastic ritual'], a: 0, e: 'Humanists revived the studia humanitatis, studying classical literature, rhetoric, and moral philosophy.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  { q: 'Descartes\' statement "Cogito, ergo sum" expresses which idea?', opts: ['God guarantees all truth', 'The certainty of one\'s own thinking self', 'Knowledge comes only from senses', 'The soul does not exist'], a: 1, e: '"I think, therefore I am" is Descartes\' indubitable foundation: doubting proves a thinking self exists.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  { q: 'John Locke\'s idea of the mind as a tabula rasa means what?', opts: ['The mind holds innate ideas', 'The mind begins as a blank slate', 'The mind is unknowable', 'The mind is divine'], a: 1, e: 'Locke argued the mind starts blank and knowledge is built from experience, a cornerstone of empiricism.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  { q: 'Locke argued governments derive their legitimate authority from what?', opts: ['Divine right of kings', 'The consent of the governed', 'Military conquest', 'Inherited nobility'], a: 1, e: 'Locke held that legitimate government rests on consent and exists to protect natural rights to life, liberty, and property.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  { q: 'Rousseau\'s The Social Contract introduced which key concept?', opts: ['The general will', 'The invisible hand', 'The categorical imperative', 'The dialectic'], a: 0, e: 'Rousseau\'s general will represents the collective interest of the people as the basis of legitimate sovereignty.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  { q: 'Kant\'s categorical imperative directs one to act how?', opts: ['To maximize personal pleasure', 'Only on maxims one could will as universal law', 'According to tradition', 'As the majority decides'], a: 1, e: 'Kant\'s test asks whether the principle of your action could consistently become a universal law binding on all.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  { q: 'Kant summarized the Enlightenment with which motto?', opts: ['Know thyself', 'Sapere aude (dare to know)', 'I think therefore I am', 'The end justifies the means'], a: 1, e: 'In "What Is Enlightenment?" Kant urged people to use their own reason: sapere aude, dare to know.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  { q: 'Montesquieu\'s The Spirit of the Laws is best known for advocating what?', opts: ['Absolute monarchy', 'Separation of governmental powers', 'Abolition of property', 'Theocracy'], a: 1, e: 'Montesquieu argued that dividing power among legislative, executive, and judicial branches guards against tyranny.', tags: ['Intellectual History', 'Renaissance & Enlightenment'] },
  // ── Level 4 — Modern Political Ideologies ──
  { q: 'Classical liberalism primarily emphasizes what?', opts: ['Individual liberty and limited government', 'Rule by hereditary elites', 'Collective ownership of all property', 'A single-party state'], a: 0, e: 'Liberalism stresses individual rights, the rule of law, and constraints on state power.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  { q: 'Edmund Burke\'s Reflections on the Revolution in France is a founding text of what?', opts: ['Socialism', 'Modern conservatism', 'Anarchism', 'Fascism'], a: 1, e: 'Burke defended tradition, gradual reform, and inherited institutions against radical, abstract revolution.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  { q: 'Socialism is centrally defined by advocacy of what?', opts: ['Unregulated free markets', 'Social ownership of the means of production', 'Hereditary monarchy', 'Minimal taxation'], a: 1, e: 'Socialism calls for collective or public ownership and control of production to reduce economic inequality.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  { q: 'Nationalism as a political ideology holds that what?', opts: ['States should merge into one empire', 'The nation is the primary basis of political loyalty', 'Religion should govern all states', 'Property should be abolished'], a: 1, e: 'Nationalism makes the nation the central unit of identity and legitimacy, often demanding self-determination.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  { q: 'Adam Smith\'s "invisible hand" describes what?', opts: ['State direction of the economy', 'How self-interested exchange can benefit society', 'Divine control of history', 'Central bank policy'], a: 1, e: 'In The Wealth of Nations, Smith argued individuals pursuing self-interest can unintentionally promote the common good.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  { q: 'John Stuart Mill\'s harm principle in On Liberty states what?', opts: ['The state may regulate all conduct', 'Power over an individual is justified only to prevent harm to others', 'Liberty applies only to the wealthy', 'Speech should be censored for offense'], a: 1, e: 'Mill held that individuals should be free to act unless their actions harm others.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  { q: 'Anarchism is defined by its opposition to what?', opts: ['All trade', 'Coercive state authority', 'Human cooperation', 'Written language'], a: 1, e: 'Anarchist thinkers such as Proudhon and Bakunin reject the state, favoring voluntary, self-organized association.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  { q: 'Jeremy Bentham\'s utilitarianism judges actions by what standard?', opts: ['Their conformity to tradition', 'The greatest happiness of the greatest number', 'Divine command', 'National glory'], a: 1, e: 'Bentham\'s principle of utility evaluates acts by how much net pleasure or happiness they produce.', tags: ['Intellectual History', 'Modern Political Ideologies'] },
  // ── Level 5 — Modern Thought ──
  { q: 'Marx\'s theory of historical materialism argues that history is chiefly driven by what?', opts: ['Great individuals', 'Material and economic conditions and class struggle', 'Divine providence', 'Random chance'], a: 1, e: 'For Marx, changes in the material means of production and the resulting class conflict drive historical development.', tags: ['Intellectual History', 'Modern Thought'] },
  { q: 'In Marxist theory, "alienation" refers to what?', opts: ['Workers\' estrangement from their labor and its products', 'Migration between countries', 'Loss of religious faith', 'Political exile'], a: 0, e: 'Marx argued that under capitalism workers become alienated from their labor, its products, and their own human potential.', tags: ['Intellectual History', 'Modern Thought'] },
  { q: 'Nietzsche\'s declaration "God is dead" was meant to signal what?', opts: ['A proof that God never existed', 'The collapse of traditional religious foundations for values', 'A call to build churches', 'The triumph of science over art'], a: 1, e: 'Nietzsche diagnosed the waning authority of Christian morality in modern culture and the crisis of meaning it created.', tags: ['Intellectual History', 'Modern Thought'] },
  { q: 'Nietzsche\'s concept of the Übermensch refers to what?', opts: ['A ruler by divine right', 'An individual who creates his own values', 'A perfectly rational scientist', 'An obedient citizen'], a: 1, e: 'The Übermensch (overman) affirms life and creates new values rather than inheriting them from tradition.', tags: ['Intellectual History', 'Modern Thought'] },
  { q: 'Sartre\'s existentialist slogan "existence precedes essence" means what?', opts: ['Humans are born with a fixed nature', 'Humans first exist and then define themselves through choices', 'Essence is more real than existence', 'God designs each person\'s purpose'], a: 1, e: 'For Sartre, there is no preset human essence; we are radically free and define ourselves through our actions.', tags: ['Intellectual History', 'Modern Thought'] },
  { q: 'Kierkegaard, often called the father of existentialism, emphasized what?', opts: ['Collective reason', 'Individual subjective choice and faith', 'Scientific objectivity', 'Historical inevitability'], a: 1, e: 'Kierkegaard stressed the individual\'s passionate, subjective commitment, including the "leap of faith."', tags: ['Intellectual History', 'Modern Thought'] },
  { q: 'Lyotard famously defined postmodernism as what?', opts: ['Faith in progress', 'Incredulity toward metanarratives', 'A return to tradition', 'Confidence in universal reason'], a: 1, e: 'Lyotard characterized the postmodern condition as skepticism toward grand, all-explaining narratives like progress or emancipation.', tags: ['Intellectual History', 'Modern Thought'] },
  { q: 'Michel Foucault\'s work is especially known for analyzing what relationship?', opts: ['Supply and demand', 'Power and knowledge', 'Faith and reason', 'Nature and nurture'], a: 1, e: 'Foucault argued that power and knowledge are intertwined, shaping discourse, institutions, and what counts as truth.', tags: ['Intellectual History', 'Modern Thought'] },
];
