import type { Seed } from './roadmap-build';

// "System design at scale" learning path — 120 questions (15 levels × 8),
// easiest → hardest: scaling, load balancing, caching, replication, sharding,
// queues, consistency/CAP, rate limiting, CDNs, failure modes, observability,
// trade-offs and estimation. Built directly (ids rm-sysdesign-1 … 120).
export const systemDesignSeeds: Seed[] = [
  // Level 1 — System Design Basics
  { q: 'A team is deciding how an API, cache, database, and queue should work together under expected traffic and failures. What kind of work is this?', opts: ['Detailed UI design for one client screen', 'System design: arranging components to meet functional and quality requirements', 'Unit design inside a single pure function', 'Source-control design for the repository branches'], a: 1, e: 'System design defines components, data flow, and trade-offs so the whole service meets requirements such as scale, reliability, latency, and cost.', tags: ['System Design', 'basics'], intro: 'Tie each architecture choice to a requirement or failure mode.' },
  { q: '“Users can upload photos” is a feature requirement. Which option is a non-functional requirement for the same service?', opts: ['Users can add a caption to each photo', 'Ninety-five percent of uploads complete within two seconds', 'Users can delete a photo they own', 'Moderators can remove a reported photo'], a: 1, e: 'Non-functional requirements describe how well a system operates—such as latency, capacity, availability, durability, and cost—rather than which actions it supports.', tags: ['System Design', 'requirements'] },
  { q: 'A monitoring chart shows that the p95 time from receiving an API request to sending its response is 180 ms. What is it measuring?', opts: ['Throughput over the monitoring interval', 'Request latency at the 95th percentile', 'Total storage consumed by the service', 'Concurrent server capacity before saturation'], a: 1, e: 'Latency is the elapsed time for an operation. A p95 value means 95% of measured requests completed at or below that time.', tags: ['System Design', 'latency'] },
  { q: 'A queue consumer handles 4,000 messages per second while each message takes 20 ms end to end. Which number describes throughput?', opts: ['20 ms per message', '4,000 messages per second', 'The queue’s total retained bytes', 'The number of consumer instances'], a: 1, e: 'Throughput is completed work per unit time. Latency measures how long one item takes; the two metrics answer different questions.', tags: ['System Design', 'throughput'] },
  { q: 'A service-level objective says the API must be usable for 99.95% of each month. Which quality does that percentage describe?', opts: ['Consistency of replicated records', 'Availability over the measurement period', 'Throughput per provisioned server', 'Durability of accepted writes'], a: 1, e: 'Availability is the proportion of time or requests for which the service is operational, often expressed as a percentage or “nines.”', tags: ['System Design', 'availability'] },
  { q: 'Before choosing a database for a new chat service, what should the team establish first?', opts: ['The cloud vendor’s default database offering', 'Features, traffic and data estimates, reliability needs, and constraints', 'The final table and index names', 'The visual layout of the mobile conversation screen'], a: 1, e: 'Requirements and rough scale estimates constrain the design. Choosing technology first risks optimizing for needs the product does not have.', tags: ['System Design', 'process'] },
  { q: 'Traffic grows tenfold, and the service can meet it by adding instances without redesigning every component. Which property does this show?', opts: ['Durability, because every request reaches permanent storage', 'Scalability, because capacity can grow with added resources', 'Consistency, because every instance returns identical data immediately', 'Idempotency, because requests may be retried safely'], a: 1, e: 'Scalability is the ability to handle increasing load by adding resources while maintaining acceptable service quality.', tags: ['System Design', 'scalability'] },
  { q: 'Every application instance depends on one configuration service, and no request can start when that service is down. What role does it have?', opts: ['A redundant failover component', 'A single point of failure for request handling', 'A read-through cache for application data', 'A rate limiter that protects downstream capacity'], a: 1, e: 'A single point of failure has no effective redundancy and can take down the larger system. Replication, fallback behavior, or removing the synchronous dependency can reduce the risk.', tags: ['System Design', 'reliability'] },

  // Level 2 — Client–Server & APIs
  { q: 'A web app and a mobile app both use the same ordering rules. Where should the shared business rules run?', opts: ['Independently in each client, with the database exposed to both', 'On a server that exposes the same API to both clients', 'Only in database triggers, with clients writing tables directly', 'In the web client, with the mobile app copying its responses'], a: 1, e: 'Putting shared rules behind a server API gives both clients one trusted implementation and keeps the database private. Client-side checks can improve UX, but the server must enforce the rules.', tags: ['System Design', 'client-server'] },
  { q: 'Which endpoint design uses HTTP resource semantics most consistently?', opts: ['POST /getOrder with { action: "read" } for every operation', 'GET /orders/42 to read and DELETE /orders/42 to remove the same resource', 'GET /orders/42/delete to remove an order', 'POST /rpc with a method name for every operation'], a: 1, e: 'A REST-style API models an order as a resource and uses HTTP methods for the operation. RPC can also be valid, but it is a different API style.', tags: ['System Design', 'rest'] },
  { q: 'A key benefit of a stateless API server is:', opts: ['It remembers each user between requests', 'Any instance can handle any request, making horizontal scaling easy', 'It needs no database', 'It cannot use load balancers'], a: 1, e: 'Statelessness (no per-client server memory) lets a load balancer route any request to any instance, easing scaling.', tags: ['System Design', 'stateless'] },
  { q: 'A mobile screen needs a user, their latest orders, and only three fields from each order. Which GraphQL property may reduce over-fetching compared with several fixed REST representations?', opts: ['Every resource is addressed through a separate fixed URL', 'The client selects the fields and related data it needs in one query', 'The API maps each query directly to one database table', 'Every response uses the same schema-free document shape'], a: 1, e: 'GraphQL clients select fields through a typed schema and can traverse related data in one operation. That flexibility also creates server-side complexity around authorization, caching, and query cost.', tags: ['System Design', 'graphql'] },
  { q: 'gRPC is often chosen for:', opts: ['Browser-to-server only', 'Efficient, strongly-typed service-to-service communication (binary protobuf over HTTP/2)', 'Static file hosting', 'Email'], a: 1, e: 'gRPC uses protobuf over HTTP/2 for fast, typed inter-service calls, popular in microservice backends.', tags: ['System Design', 'grpc'] },
  { q: 'Several backend services need one public entry point with shared authentication, quotas, and path routing. Which component fits?', opts: ['A service registry used only by internal clients', 'An API gateway in front of the backend services', 'A database proxy that routes SQL by table name', 'A CDN configured only for immutable static files'], a: 1, e: 'An API gateway can centralize edge concerns such as authentication, routing, rate limits, and response aggregation. Business rules should still live in the owning services.', tags: ['System Design', 'gateway'] },
  { q: 'Idempotency in an API means:', opts: ['Each call returns random data', 'Making the same request multiple times has the same effect as making it once', 'The API never fails', 'Requests must be encrypted'], a: 1, e: 'Idempotent operations can be safely retried; e.g. PUT or a delete by id has the same end state if repeated.', tags: ['System Design', 'idempotency'] },
  { q: 'Versioning an API (e.g. /v1/) helps by:', opts: ['Making it faster', 'Letting you evolve the API without breaking existing clients', 'Removing the need for docs', 'Encrypting traffic'], a: 1, e: 'Versioning lets new, possibly breaking changes ship under a new path while old clients keep using the prior version.', tags: ['System Design', 'versioning'] },

  // Level 3 — Scaling: Vertical vs Horizontal
  { q: 'Vertical scaling ("scaling up") means:', opts: ['Adding more machines', 'Adding more power (CPU/RAM) to a single machine', 'Removing servers', 'Sharding the database'], a: 1, e: 'Vertical scaling makes one machine bigger; simple, but bounded by the largest available machine and a SPOF.', tags: ['Scaling', 'vertical'] },
  { q: 'Horizontal scaling ("scaling out") means:', opts: ['Buying a bigger server', 'Adding more machines/instances to share the load', 'Deleting data', 'Disabling caching'], a: 1, e: 'Horizontal scaling adds more nodes; it scales further and adds redundancy but requires statelessness/coordination.', tags: ['Scaling', 'horizontal'] },
  { q: 'A major limitation of vertical scaling is:', opts: ['It is infinitely scalable', 'There is a hardware ceiling and it remains a single point of failure', 'It needs many machines', 'It cannot use a database'], a: 1, e: 'You can only make one box so big, and that box is still a SPOF — eventually you must scale out.', tags: ['Scaling', 'vertical'] },
  { q: 'Horizontal scaling generally requires application servers to be:', opts: ['Stateful', 'Stateless (or sharing state via an external store)', 'Single-threaded', 'Written in one language'], a: 1, e: 'To freely add instances behind a load balancer, servers should keep no local per-client state (use Redis/DB for shared state).', tags: ['Scaling', 'stateless'] },
  { q: 'Traffic follows unpredictable daily spikes. Which auto-scaling policy responds to actual demand?', opts: ['Add instances at midnight in every region regardless of load', 'Add or remove instances from signals such as request rate or CPU utilization', 'Keep one large instance and restart it when its queue grows', 'Create a new database shard for every application deployment'], a: 1, e: 'Metric-based auto-scaling changes instance count in response to observed demand. Thresholds and cooldowns help it balance performance, stability, and cost.', tags: ['Scaling', 'autoscale'] },
  { q: 'Why is statefulness on app servers a problem for scaling?', opts: ['It uses no memory', 'Sessions tied to one instance break when load balancers route elsewhere or instances die', 'It is required by HTTP', 'It improves caching'], a: 1, e: 'Local session state means a user must hit the same box; instead store sessions externally so any instance can serve them.', tags: ['Scaling', 'state'] },
  { q: 'Sessions are stored in each app server’s memory. Which load-balancer setting can reduce random logouts without changing session storage?', opts: ['Route every request to the least busy server', 'Route the same user to the same server when possible', 'Send writes to one server and reads to another', 'Hash each URL path to a different database'], a: 1, e: 'Sticky sessions, or session affinity, keep a user on one instance. They can be a short-term fix, but shared external session storage usually gives better failover and load distribution.', tags: ['Scaling', 'sessions'] },
  { q: 'A practical scaling order is often:', opts: ['Shard first, always', 'Optimize/scale vertically and add caching/replicas before sharding', 'Rewrite in another language first', 'Add SPOFs'], a: 1, e: 'Sharding is complex; teams usually exhaust caching, read replicas, and vertical/horizontal app scaling first.', tags: ['Scaling', 'strategy'] },

  // Level 4 — Load Balancing
  { q: 'Four stateless API instances are healthy, but clients know only one public address. Which component should receive that traffic?', opts: ['A read replica that forwards writes to the primary', 'A load balancer that routes requests across the API instances', 'A message broker that turns every request into a background job', 'A CDN configured to cache every authenticated response'], a: 1, e: 'A load balancer gives clients one entry point and spreads requests across healthy application instances. The other components solve storage, asynchronous work, or caching problems.', tags: ['Load Balancing', 'basics'] },
  { q: 'Three equal app servers handle requests of roughly equal cost. Which simple policy distributes successive requests A, B, C, A, B, C?', opts: ['Least connections', 'Round-robin', 'IP hash', 'Weighted failover'], a: 1, e: 'Round-robin cycles through servers in order. It works well when instances and request costs are similar; least-connections is often better when request duration varies.', tags: ['Load Balancing', 'round-robin'] },
  { q: 'One app instance still accepts TCP connections but returns 500 for every request. What lets the load balancer remove it from rotation?', opts: ['An application-level health check that fails on that instance', 'A process restart policy with no load-balancer check', 'A round-robin policy that keeps sending occasional requests', 'TLS termination at the load balancer'], a: 0, e: 'An application-level health check detects that the instance cannot serve requests and removes it from rotation. A supervisor may restart it, but that does not replace routing health checks.', tags: ['Load Balancing', 'health'] },
  { q: 'API requests vary from 20 ms to 30 seconds. Which routing policy best accounts for servers tied up by long requests?', opts: ['Round-robin, which ignores current work', 'Least connections, which favors the server with fewer active requests', 'IP hash, which pins clients regardless of load', 'Random routing with no health information'], a: 1, e: 'Least-connections routing uses current active work as a signal, so it handles uneven request duration better than a fixed rotation.', tags: ['Load Balancing', 'algorithms'] },
  { q: 'An L7 (application-layer) load balancer can route based on:', opts: ['Only IP address', 'HTTP details like path, headers, or cookies', 'Disk size', 'CPU model'], a: 1, e: 'Layer-7 balancers understand HTTP, enabling path/host-based routing, TLS termination, and more.', tags: ['Load Balancing', 'L7'] },
  { q: 'One of four app instances fails during a deploy. Why can the service stay available behind a load balancer?', opts: ['Health checks stop new traffic reaching the failed instance while healthy instances continue', 'The balancer restores the failed instance’s memory from a backup', 'The balancer guarantees that no instance will fail during traffic', 'Every request is replayed from the database until that instance returns'], a: 0, e: 'Health-aware routing lets redundant app instances absorb the failed instance’s traffic. The balancer also needs redundancy; it does not repair application state or guarantee zero downtime by itself.', tags: ['Load Balancing', 'availability'] },
  { q: 'To avoid the load balancer itself being a SPOF you:', opts: ['Use exactly one balancer', 'Run redundant balancers (e.g. active-passive with failover/DNS)', 'Remove health checks', 'Disable TLS'], a: 1, e: 'Redundant load balancers with failover ensure the entry point isn’t a single point of failure.', tags: ['Load Balancing', 'redundancy'] },
  { q: 'TLS termination at the load balancer means:', opts: ['TLS is disabled', 'The balancer decrypts HTTPS so backends can use plain HTTP internally', 'Backends handle all TLS', 'Traffic is never encrypted'], a: 1, e: 'Terminating TLS at the edge offloads crypto from backends; internal traffic may stay on a trusted network (or re-encrypt).', tags: ['Load Balancing', 'tls'] },

  // Level 5 — Caching
  { q: 'A product catalogue is read thousands of times between updates. Which change most directly reduces repeated database work?', opts: ['Add another identical query after the first one', 'Cache catalogue responses and invalidate them when products change', 'Encrypt each catalogue row before reading it', 'Move catalogue reads to a background queue'], a: 1, e: 'A cache keeps frequently read, slowly changing data in faster storage. Invalidation on product changes controls staleness.', tags: ['Caching', 'basics'] },
  { q: 'The API checks Redis for product 42, finds a valid value, and returns it without querying Postgres. What happened?', opts: ['A cache hit', 'A cache miss followed by a fill', 'An expired-entry refresh', 'A write-through update'], a: 0, e: 'A cache hit means the requested value was already present and valid. A miss or expired entry would require reading the source of truth.', tags: ['Caching', 'hit-miss'] },
  { q: 'A cached price has a TTL of 60 seconds and no explicit invalidation. What does that setting guarantee?', opts: ['The entry becomes ineligible after about 60 seconds and must be refreshed', 'The entry can be read at most 60 times', 'The source price cannot change during those 60 seconds', 'The cache writes the price back to the database every 60 seconds'], a: 0, e: 'TTL means time to live. It limits how long an entry remains valid, but it does not stop the source data changing before expiry.', tags: ['Caching', 'ttl'] },
  { q: 'A profile is updated in the database, but some users still see the old value from cache. Why is cache invalidation difficult?', opts: ['A cache entry becomes immutable after its first read', 'Every relevant cached copy must expire or be invalidated when the source changes', 'A cache may use a TTL only when the backing store is SQL', 'Invalidation always requires deleting the source record too'], a: 1, e: 'The system must identify and refresh or remove every cached representation affected by a change. Missed dependencies, concurrent updates, and distributed copies make that coordination error-prone.', tags: ['Caching', 'invalidation'] },
  { q: 'Users on three continents download the same versioned JavaScript bundle. Where should that bundle be cached?', opts: ['Only in the primary application database', 'At CDN edge locations near the users', 'In a per-user server session', 'In the application server’s request stack'], a: 1, e: 'A CDN caches shared content at geographically distributed edge locations, reducing network latency and origin traffic.', tags: ['Caching', 'cdn'] },
  { q: 'A "cache stampede" (thundering herd) happens when:', opts: ['One key is read once', 'A popular key expires and many requests hit the backend at once to recompute it', 'The cache is empty forever', 'TTL is infinite'], a: 1, e: 'When a hot entry expires, a flood of concurrent misses can overwhelm the backend; mitigations include locks and staggered TTLs.', tags: ['Caching', 'stampede'] },
  { q: 'Write-through caching means:', opts: ['Writes skip the cache', 'Writes update the cache and the datastore together', 'Writes only go to the cache', 'Writes are dropped'], a: 1, e: 'Write-through updates cache and database on each write, keeping them consistent at the cost of write latency.', tags: ['Caching', 'write-through'] },
  { q: 'Caching is most beneficial when data is:', opts: ['Written constantly and read rarely', 'Read far more often than it changes', 'Unique per request', 'Never accessed'], a: 1, e: 'Read-heavy, slowly-changing data gives the best cache hit rates and the biggest wins.', tags: ['Caching', 'tradeoffs'] },

  // Level 6 — Databases at Scale (Replication)
  { q: 'A team keeps the same database records on nodes in two availability zones. Which technique is this?', opts: ['Archiving old rows to cold storage', 'Replication across database nodes', 'Vertical partitioning by column', 'Hash sharding by customer id'], a: 1, e: 'Replication maintains copies of the same data on multiple nodes. It can support redundancy, failover, and read scaling.', tags: ['Replication', 'basics'] },
  { q: 'A primary–replica database receives an order update and later serves catalogue reads. Which routing is typical?', opts: ['Send every write to any replica and merge conflicts later', 'Send the write to the primary and allow suitable reads from replicas', 'Send writes only to replicas and reads only to the primary', 'Write to the cache and never persist the change'], a: 1, e: 'In primary–replica replication, writes go through the primary and are copied to replicas. Replicas can serve reads that tolerate their consistency behavior.', tags: ['Replication', 'primary-replica'] },
  { q: 'A database is overloaded by product-page reads, while all writes already fit on the primary. What do read replicas improve?', opts: ['Write throughput by accepting independent updates', 'Read throughput by serving copies of the data', 'Transaction isolation on the primary', 'The amount of data one primary disk can store'], a: 1, e: 'Read replicas offload read queries. They do not normally accept independent writes, so they do not solve a write-throughput bottleneck.', tags: ['Replication', 'reads'] },
  { q: '"Replication lag" can cause:', opts: ['Faster writes', 'A read replica returning slightly stale data shortly after a write', 'Stronger consistency', 'Data loss on the primary'], a: 1, e: 'Asynchronous replication means replicas may briefly trail the primary, so a just-written value might not appear yet.', tags: ['Replication', 'lag'] },
  { q: 'The primary database becomes unreachable, but a current replica is healthy. Which action restores write availability?', opts: ['Promote the replica to become the new primary', 'Spread read queries evenly across the remaining replicas', 'Restore last night’s backup over every healthy node', 'Keep accepting writes locally on each app server'], a: 0, e: 'Failover promotes a suitable replica to primary and redirects writers. Read balancing and backups are related operations, but they do not by themselves restore a writable leader.', tags: ['Replication', 'failover'] },
  { q: 'A write is acknowledged only after a replica confirms it. What trade-off does this synchronous policy make?', opts: ['Lower write latency but a larger window for data loss', 'Higher write latency for stronger durability', 'Higher read throughput with no effect on writes', 'Lower storage use because only one copy is retained'], a: 1, e: 'Waiting for a replica adds a network round trip to the write path, but reduces the chance that an acknowledged write is lost with the primary.', tags: ['Replication', 'sync'] },
  { q: 'Multi-primary (multi-leader) replication adds the challenge of:', opts: ['No writes allowed', 'Write conflicts that must be detected and resolved', 'Single point of failure', 'No reads'], a: 1, e: 'Allowing writes on multiple nodes introduces conflicting concurrent writes that need resolution strategies.', tags: ['Replication', 'multi-leader'] },
  { q: 'To read your own just-written data despite replica lag, you can:', opts: ['Always read from a replica', 'Route that user’s reads to the primary (read-your-writes consistency)', 'Disable writes', 'Drop the cache'], a: 1, e: 'Read-your-writes consistency routes a user’s reads to the primary (or a caught-up replica) right after they write.', tags: ['Replication', 'consistency'] },

  // Level 7 — Sharding & Partitioning
  { q: 'One database can no longer hold every customer row. The team routes each customer id to one of several database nodes. Which technique is this?', opts: ['Vertical partitioning by column', 'Horizontal sharding by customer id', 'Primary–replica read scaling', 'Table indexing on customer id'], a: 1, e: 'Horizontal sharding distributes different rows across nodes using a shard key. Replication would copy the same rows instead.', tags: ['Sharding', 'basics'] },
  { q: 'A good shard key:', opts: ['Concentrates traffic on one shard', 'Spreads data and load evenly with high cardinality', 'Is always the created_at timestamp', 'Is the smallest column'], a: 1, e: 'A high-cardinality, evenly-distributed key avoids hotspots and balances load across shards.', tags: ['Sharding', 'shard-key'] },
  { q: 'Orders are sharded by country, and 70% of orders come from one country. What problem is most likely?', opts: ['The shard for that country receives a disproportionate share of data and traffic', 'Every query must contact all shards, including lookups by country', 'Replication lag makes the country value change between reads', 'The primary key can no longer be indexed inside any shard'], a: 0, e: 'A skewed shard key creates a hotspot: one shard carries much more load than the others. Shard-key choice should distribute the expected traffic, not just the schema values.', tags: ['Sharding', 'hotspot'] },
  { q: 'Cross-shard queries (e.g. JOINs across shards) are:', opts: ['Trivial and fast', 'Hard — they require scatter-gather and lose simple JOIN semantics', 'Impossible to attempt', 'Automatically cached'], a: 1, e: 'Queries spanning shards require gathering from many nodes; sharding trades query flexibility for scale.', tags: ['Sharding', 'queries'] },
  { q: 'A cache cluster adds one node. Which partitioning approach is designed to avoid remapping nearly every key?', opts: ['Encrypt the shard key before taking a fixed modulo', 'Consistent hashing, which moves only part of the key space', 'Sort every cached value and assign equal row counts', 'Add a secondary index that points to the new node'], a: 1, e: 'Consistent hashing maps nodes and keys onto a logical ring, so adding or removing a node reassigns only nearby ranges rather than most keys.', tags: ['Sharding', 'consistent-hashing'] },
  { q: 'A profiles table moves its large biography and avatar metadata into a separate table keyed by user id. Which technique is this?', opts: ['Horizontal partitioning by user-id ranges', 'Vertical partitioning by groups of columns', 'Time partitioning by creation month', 'Hash sharding across database nodes'], a: 1, e: 'Vertical partitioning separates columns that have different access patterns. Horizontal partitioning and sharding split rows instead.', tags: ['Sharding', 'vertical-partition'] },
  { q: 'Range-based sharding (e.g. by date) risks:', opts: ['Perfect balance', 'Recent ranges becoming hotspots while old ranges go cold', 'No partitioning at all', 'Loss of all data'], a: 1, e: 'Range sharding can concentrate current traffic on the newest range; hash sharding spreads load more evenly.', tags: ['Sharding', 'range'] },
  { q: 'A read-heavy app still fits on one database, and repeated catalogue queries cause most of the load. What should the team try before sharding?', opts: ['Shard immediately so every query becomes distributed', 'Add targeted caching and, if needed, read replicas', 'Move each table to a different database vendor', 'Split rows randomly without measuring access patterns'], a: 1, e: 'Caching and read replicas address this measured read bottleneck with less operational cost. Sharding becomes useful when write volume or data size exceeds one node, but it adds routing and query complexity.', tags: ['Sharding', 'strategy'] },

  // Level 8 — Message Queues & Async
  { q: 'Checkout should respond before receipt email and analytics finish. Which design separates those tasks from the request?', opts: ['Call both dependencies synchronously before returning', 'Publish jobs to a queue for independent workers', 'Run both tasks in the browser after payment', 'Wrap every dependency call in one database transaction'], a: 1, e: 'A queue lets checkout hand work to independent consumers and return promptly. The jobs can be retried and scaled without coupling their latency to the user request.', tags: ['Queues', 'basics'] },
  { q: 'Image processing takes seconds and traffic arrives in bursts. What benefit does putting jobs on a queue provide?', opts: ['The request must remain open until every image variant finishes', 'The queue buffers bursts and lets background workers process at a sustainable rate', 'Each job is guaranteed to execute exactly once without idempotency', 'The upload service becomes synchronously coupled to every worker'], a: 1, e: 'A queue decouples submission from processing and absorbs temporary bursts. Workers can scale independently, while retries and duplicate delivery still need explicit handling.', tags: ['Queues', 'async'] },
  { q: 'In pub/sub, a published message is:', opts: ['Sent to exactly one consumer', 'Delivered to all subscribers of that topic', 'Stored in the database', 'Discarded'], a: 1, e: 'Publish/subscribe broadcasts each message to every subscriber of the topic, enabling event-driven fan-out.', tags: ['Queues', 'pubsub'] },
  { q: 'A broker promises at-least-once delivery. A worker may finish a job and crash before acknowledging it. What property should the handler have?', opts: ['It must keep all state only in process memory', 'It should be idempotent because the same message may be delivered again', 'It must process messages synchronously on one global thread', 'It should acknowledge the message before performing any work'], a: 1, e: 'At-least-once delivery permits duplicates when acknowledgements are lost. Idempotency keys, deduplication, or transactional state make repeated handling safe.', tags: ['Queues', 'delivery'] },
  { q: 'A dead-letter queue (DLQ) holds:', opts: ['The fastest messages', 'Messages that repeatedly failed processing, for later inspection', 'All successful messages', 'Encrypted backups'], a: 1, e: 'A DLQ captures messages that can’t be processed after retries, so they don’t block the queue and can be debugged.', tags: ['Queues', 'dlq'] },
  { q: 'Backpressure is about:', opts: ['Speeding up producers', 'Signaling/limiting producers when consumers can’t keep up', 'Deleting the queue', 'Encrypting messages'], a: 1, e: 'Backpressure prevents overload by slowing or buffering producers when consumers fall behind.', tags: ['Queues', 'backpressure'] },
  { q: 'Order service publishes OrderPlaced without knowing which teams consume it. Billing and analytics subscribe independently. What property does this create?', opts: ['Tight runtime coupling because the producer calls every consumer', 'Loose coupling through an event contract, with eventual processing', 'Immediate consistency across every subscriber by default', 'One shared database schema that all services must write'], a: 1, e: 'The producer depends on the event contract rather than each consumer’s address or uptime. This reduces runtime coupling, while introducing delivery, ordering, and consistency concerns.', tags: ['Queues', 'event-driven'] },
  { q: 'A trade-off of asynchronous processing is:', opts: ['Instant consistency', 'Eventual consistency and added complexity (ordering, retries, monitoring)', 'No need for monitoring', 'Guaranteed exactly-once for free'], a: 1, e: 'Async decoupling buys scalability but introduces eventual consistency and operational complexity around delivery and ordering.', tags: ['Queues', 'tradeoffs'] },

  // Level 9 — Consistency & CAP
  { q: 'Two database nodes cannot communicate. The service must either reject some operations or risk returning conflicting values. Which trade-off is this?', opts: ['Cost versus performance during normal operation', 'Consistency versus availability during a network partition', 'Latency versus storage when filling a cache', 'Read throughput versus write throughput when adding an index'], a: 1, e: 'CAP frames the choice between consistency and availability while a network partition exists. Partition tolerance is the condition, not an optional feature to trade away once the nodes cannot communicate.', tags: ['CAP', 'theorem'] },
  { q: 'During a network partition, a CP system favors:', opts: ['Availability over consistency', 'Consistency, refusing/erroring rather than serving stale data', 'Neither', 'Lower latency only'], a: 1, e: 'CP systems keep data consistent during partitions, potentially rejecting requests to avoid divergence.', tags: ['CAP', 'cp'] },
  { q: 'An AP system during a partition favors:', opts: ['Consistency', 'Availability, possibly returning stale/eventually-consistent data', 'Refusing all requests', 'Shutting down'], a: 1, e: 'AP systems stay available during partitions, accepting temporary inconsistency that converges later.', tags: ['CAP', 'ap'] },
  { q: 'Eventual consistency means:', opts: ['Data is never consistent', 'Given no new writes, replicas converge to the same value over time', 'Strong consistency always', 'Reads are blocked'], a: 1, e: 'With eventual consistency, replicas may temporarily differ but converge once updates propagate.', tags: ['Consistency', 'eventual'] },
  { q: 'Strong consistency guarantees:', opts: ['Reads may be stale', 'Every read sees the most recent committed write', 'No writes are allowed', 'Lower latency always'], a: 1, e: 'Strong consistency means reads always reflect the latest write, usually at the cost of latency/availability.', tags: ['Consistency', 'strong'] },
  { q: 'Why is partition tolerance essentially mandatory in distributed systems?', opts: ['Networks never fail', 'Real networks drop/delay messages, so you must tolerate partitions', 'It is optional and rare', 'It improves UI'], a: 1, e: 'Network failures are inevitable at scale, so the real CAP choice is C vs A when a partition occurs.', tags: ['CAP', 'partition'] },
  { q: 'A banking ledger most likely prioritizes:', opts: ['Availability with stale balances', 'Strong consistency to prevent incorrect balances', 'No consistency', 'Maximum caching of balances'], a: 1, e: 'Financial correctness demands strong consistency; serving stale or conflicting balances is unacceptable.', tags: ['Consistency', 'tradeoffs'] },
  { q: 'A social media "like" counter can often tolerate:', opts: ['Strong consistency only', 'Eventual consistency (a slightly delayed count is fine)', 'No availability', 'No writes'], a: 1, e: 'Approximate, eventually-consistent counts are acceptable for likes, favoring availability and scale.', tags: ['Consistency', 'tradeoffs'] },

  // Level 10 — Rate Limiting & Throttling
  { q: 'One API key sends 20,000 requests in a minute and crowds out normal clients. Which control addresses that behavior most directly?', opts: ['Require TLS for requests from that key', 'Cap requests for the key within a time window', 'Cache every response regardless of method or user', 'Add replicas without identifying the noisy client'], a: 1, e: 'Rate limiting bounds traffic for an identity, address, or route within a window. More capacity may help overall load, but it does not enforce fair or safe use by one client.', tags: ['Rate Limiting', 'basics'] },
  { q: 'The token bucket algorithm allows:', opts: ['No bursts ever', 'Bursts up to the bucket size while enforcing an average rate', 'Unlimited requests', 'Only one request total'], a: 1, e: 'Token bucket refills tokens at a steady rate; requests spend tokens, permitting short bursts within the average limit.', tags: ['Rate Limiting', 'token-bucket'] },
  { q: 'Which HTTP status code typically signals "rate limit exceeded"?', opts: ['200', '404', '429', '500'], a: 2, e: 'HTTP 429 Too Many Requests indicates the client has hit a rate limit.', tags: ['Rate Limiting', 'http'] },
  { q: 'A "Retry-After" response header tells the client:', opts: ['To never retry', 'How long to wait before retrying', 'The server crashed', 'To switch protocols'], a: 1, e: 'Retry-After advises the client when it may safely retry, helping it back off gracefully.', tags: ['Rate Limiting', 'retry'] },
  { q: 'Throttling differs from hard rejection by:', opts: ['Dropping all excess traffic immediately', 'Slowing or queuing excess requests rather than failing them outright', 'Permanently blocking clients after one violation', 'Serving cached responses to all excess requests'], a: 1, e: 'Throttling smooths excess load by delaying or queuing requests instead of immediately rejecting them, when the workload can tolerate it.', tags: ['Rate Limiting', 'throttling'] },
  { q: 'Exponential backoff on the client means:', opts: ['Retry instantly forever', 'Wait increasingly longer between retries (often with jitter)', 'Never retry', 'Retry exactly once'], a: 1, e: 'Exponential backoff (plus jitter) spaces out retries, avoiding synchronized retry storms against a struggling server.', tags: ['Rate Limiting', 'backoff'] },
  { q: 'Distributed rate limiting across many servers usually needs:', opts: ['Per-server local counters only', 'A shared store (e.g. Redis) to coordinate counts globally', 'No coordination', 'A bigger CPU'], a: 1, e: 'To enforce a global limit, instances share counters in a fast central store like Redis.', tags: ['Rate Limiting', 'distributed'] },
  { q: 'Why would a login endpoint apply a strict per-account and per-source rate limit?', opts: ['To reduce the browser time needed to parse stylesheets', 'To slow brute-force guessing and absorb abusive request bursts', 'To stop database indexes from growing with new accounts', 'To make failed unit tests retry at a lower frequency'], a: 1, e: 'Rate limits bound how quickly an attacker can try credentials and reduce the impact of abusive traffic. They complement authentication, monitoring, and broader denial-of-service controls.', tags: ['Rate Limiting', 'security'] },

  // Level 11 — CDNs & Edge
  { q: 'Users far from the origin repeatedly download the same versioned images. What is the CDN’s main role?', opts: ['Copy relational transactions to a database near each user', 'Serve cached image bytes from edge locations near users', 'Compile the frontend separately for every request', 'Queue image requests until the origin has spare capacity'], a: 1, e: 'A CDN places cacheable content at distributed edge locations. This shortens network paths and reduces repeated work at the origin.', tags: ['CDN', 'basics'] },
  { q: 'CDNs are especially effective for:', opts: ['Per-user dynamic banking pages', 'Static assets like images, CSS, JS, and videos', 'Write-heavy transactions', 'Database migrations'], a: 1, e: 'Cacheable static assets are ideal for CDNs; highly personalized dynamic content benefits less (without edge logic).', tags: ['CDN', 'static'] },
  { q: 'The same 2 MB image is served from an edge 20 ms away instead of an origin 180 ms away. What improves most directly?', opts: ['Network latency because the request travels a shorter path', 'Payload size because the edge automatically compresses every format', 'Server-rendering time because image delivery executes the page renderer', 'Freshness because edge responses do not need cache rules'], a: 0, e: 'A closer edge reduces network round-trip time. It does not inherently shrink the object, speed server rendering, or remove the need for cache-control and invalidation.', tags: ['CDN', 'latency'] },
  { q: 'Cache busting via filename hashing (e.g. app.3f9a.js) lets you:', opts: ['Never update assets', 'Cache assets aggressively yet force fresh downloads when content changes', 'Disable the CDN', 'Avoid HTTPS'], a: 1, e: 'A content hash in the filename changes on update, so you can cache forever and still serve new versions instantly.', tags: ['CDN', 'cache-busting'] },
  { q: 'Edge computing/functions run code:', opts: ['Only in one central region', 'At edge locations close to users for lower-latency dynamic logic', 'On the client GPU', 'Inside the database'], a: 1, e: 'Edge functions execute logic near users, reducing latency for personalization, auth, and routing.', tags: ['CDN', 'edge'] },
  { q: 'Many CDN edge locations miss the same popular object at once and would all contact the origin. What does an origin shield change?', opts: ['It sends every edge miss directly to a different origin replica', 'It funnels misses through another cache tier so the origin sees fewer requests', 'It disables edge caching and serves the object only from the shield', 'It encrypts cached objects but leaves origin request volume unchanged'], a: 1, e: 'An origin shield is a shared cache layer between edge points of presence and the origin. It consolidates misses and protects the origin from duplicate fetches.', tags: ['CDN', 'origin'] },
  { q: 'A downside of aggressive CDN caching is:', opts: ['Lower latency', 'Stale content if invalidation isn’t handled when assets change', 'Better SEO', 'Smaller bills'], a: 1, e: 'Without proper invalidation/versioning, users may receive outdated cached content after a deploy.', tags: ['CDN', 'staleness'] },
  { q: 'Many CDNs also provide:', opts: ['Nothing extra', 'DDoS protection and TLS termination at the edge', 'Database sharding', 'Unit tests'], a: 1, e: 'CDNs commonly absorb DDoS traffic and terminate TLS at the edge in addition to caching.', tags: ['CDN', 'security'] },

  // Level 12 — Failure Modes & Resilience
  { q: 'A recommendation service is useful but not required for checkout. How should checkout behave if recommendations time out?', opts: ['Fail the entire checkout to keep every page section consistent', 'Omit recommendations and keep the purchase path working', 'Retry recommendations without a deadline before showing checkout', 'Return success but delay writing the order until recommendations recover'], a: 1, e: 'Designing for failure means containing dependency failures and preserving core behavior. Here, recommendations can degrade gracefully while checkout remains correct.', tags: ['Resilience', 'philosophy'] },
  { q: 'A payment dependency is timing out, and retries are exhausting every request thread. How can a circuit breaker help?', opts: ['Retry each call continuously with no delay until it succeeds', 'Temporarily fail calls fast after repeated failures, then probe for recovery', 'Move the payment payload to an encrypted transport but keep retrying', 'Add a database index to reduce the dependency’s network timeout'], a: 1, e: 'A circuit breaker opens after a failure threshold, avoiding doomed calls and giving the dependency time to recover. A half-open state later allows limited probes.', tags: ['Resilience', 'circuit-breaker'] },
  { q: 'Graceful degradation means:', opts: ['The whole system goes down on any error', 'Non-critical features fail/turn off while core functionality keeps working', 'Ignoring all errors', 'Doubling latency'], a: 1, e: 'Graceful degradation sheds non-essential features under stress so the core service stays available.', tags: ['Resilience', 'degradation'] },
  { q: 'A timeout on a downstream call prevents:', opts: ['Fast responses', 'Threads/resources hanging indefinitely on a slow dependency', 'Successful calls', 'Caching'], a: 1, e: 'Timeouts bound how long you wait, freeing resources and avoiding cascading stalls from a slow dependency.', tags: ['Resilience', 'timeouts'] },
  { q: 'Retries should be paired with backoff and jitter to avoid:', opts: ['Any success', 'Retry storms that hammer a recovering service in sync', 'Lower latency', 'Idempotency'], a: 1, e: 'Naïve immediate retries from many clients can overwhelm a recovering service; backoff with jitter de-synchronizes them.', tags: ['Resilience', 'retries'] },
  { q: 'A "cascading failure" is when:', opts: ['One success triggers more successes', 'One component’s failure overloads others, spreading the outage', 'A backup completes', 'Latency drops'], a: 1, e: 'Failures can cascade as load shifts onto remaining components, toppling them too — bulkheads and breakers contain it.', tags: ['Resilience', 'cascading'] },
  { q: 'The bulkhead pattern improves resilience by:', opts: ['Sharing one pool for everything', 'Isolating resources so one failing area can’t exhaust resources needed elsewhere', 'Removing timeouts', 'Disabling retries'], a: 1, e: 'Bulkheads partition resources (like connection pools) so a failure in one part can’t sink the whole ship.', tags: ['Resilience', 'bulkhead'] },
  { q: 'Chaos engineering involves:', opts: ['Writing chaotic code', 'Deliberately injecting failures to verify the system’s resilience', 'Deleting production data', 'Removing monitoring'], a: 1, e: 'Chaos engineering proactively tests resilience by injecting controlled failures (e.g. killing instances) to find weaknesses.', tags: ['Resilience', 'chaos'] },

  // Level 13 — Observability & Monitoring
  { q: 'The three common "pillars of observability" are:', opts: ['HTML, CSS, JS', 'Logs, metrics, and traces', 'CPU, RAM, disk', 'Dev, staging, prod'], a: 1, e: 'Observability is commonly framed as logs (events), metrics (aggregates), and traces (request paths).', tags: ['Observability', 'pillars'] },
  { q: 'Metrics are best described as:', opts: ['Full request payloads', 'Numeric time-series aggregates (e.g. request rate, error rate, latency)', 'Stack traces', 'Source code'], a: 1, e: 'Metrics are cheap-to-store numeric series ideal for dashboards and alerting on trends.', tags: ['Observability', 'metrics'] },
  { q: 'One checkout request crosses four services, but the team cannot tell where its extra two seconds were spent. Which signal is most useful?', opts: ['Encrypted log storage without shared request context', 'A distributed trace with spans for the request across services', 'One host-level CPU average for the whole cluster', 'A database shard count from the deployment configuration'], a: 1, e: 'Distributed tracing propagates trace context and records timed spans across service boundaries, revealing the end-to-end path, errors, and bottlenecks.', tags: ['Observability', 'tracing'] },
  { q: 'Structured logging means logs are:', opts: ['Free-form prose', 'Emitted as machine-parseable key/value (e.g. JSON) for querying', 'Disabled in production', 'Stored only on disk'], a: 1, e: 'Structured logs (JSON) are searchable and filterable, far more useful at scale than unstructured text.', tags: ['Observability', 'logging'] },
  { q: 'A team commits that 99.9% of API requests will finish within 300 ms over 30 days. What is that target?', opts: ['An SLA that automatically defines customer compensation', 'An SLO: a target value for a measured reliability indicator', 'An SLI: the individual latency measurement from one request', 'An error budget: the total number of requests the service receives'], a: 1, e: 'A service-level objective (SLO) sets a target for a service-level indicator (SLI). The allowed shortfall from that target forms the error budget; an SLA is a separate external agreement.', tags: ['Observability', 'slo'] },
  { q: 'The "four golden signals" of monitoring are latency, traffic, errors, and:', opts: ['Color', 'Saturation', 'Filenames', 'Cookies'], a: 1, e: 'Google’s golden signals are latency, traffic, errors, and saturation (how "full" your resources are).', tags: ['Observability', 'golden-signals'] },
  { q: 'Good alerting should be:', opts: ['Triggered on every log line', 'Actionable and tied to user-impacting symptoms, to avoid alert fatigue', 'Disabled at night', 'Based only on CPU'], a: 1, e: 'Alert on symptoms that matter (e.g. SLO burn), not noisy causes — too many alerts cause fatigue and missed incidents.', tags: ['Observability', 'alerting'] },
  { q: 'Logs from several services contain the same request ID. What investigation does that enable?', opts: ['Decrypting sensitive fields written by those services', 'Finding log events associated with one request across service boundaries', 'Reducing storage by merging all events into one log line', 'Reconstructing precise span timing without any other telemetry'], a: 1, e: 'A propagated correlation ID connects log records for one request. It complements tracing but does not by itself provide a full span model or timing hierarchy.', tags: ['Observability', 'correlation'] },

  // Level 14 — Trade-offs & Estimation
  { q: 'Before choosing storage for uploaded video, why estimate uploads per day, average size, and retention?', opts: ['To produce an exact bill that makes later measurement unnecessary', 'To check the order of magnitude and see which designs are feasible', 'To prove that a distributed design is required before building anything', 'To replace load tests and production capacity monitoring'], a: 1, e: 'Back-of-the-envelope estimates expose orders of magnitude and likely constraints. They guide an initial design; they do not replace measurement or load testing.', tags: ['Estimation', 'basics'] },
  { q: 'If a service handles 1,000 requests/second steadily, that is roughly how many per day?', opts: ['~86 million', '~1 million', '~1 billion', '~3,600'], a: 0, e: '1,000 × 86,400 seconds/day ≈ 86.4 million requests/day.', tags: ['Estimation', 'math'] },
  { q: 'Two designs both meet the features. One costs less but has higher tail latency; the other is faster but harder to operate. How should the team choose?', opts: ['Select the architecture with the most services because it is more advanced', 'Compare the trade-offs against measured requirements and team constraints', 'Select the cheaper design because cost always outranks reliability', 'Select the faster design because latency always outranks complexity'], a: 1, e: 'System design rarely has one context-free winner. The right choice follows explicit requirements, expected load, cost, operational skill, and acceptable failure modes.', tags: ['Estimation', 'tradeoffs'] },
  { q: 'Premature optimization in system design tends to:', opts: ['Always pay off', 'Add complexity for scale you may never reach', 'Reduce all latency', 'Be required by CAP'], a: 1, e: 'Designing for imaginary scale wastes effort and adds complexity; design for realistic, near-term needs with room to grow.', tags: ['Estimation', 'yagni'] },
  { q: 'Reading throughput estimates helps decide whether to:', opts: ['Pick a font', 'Add caching/replicas vs serve directly from the primary DB', 'Rename the repo', 'Disable logging'], a: 1, e: 'Knowing read volume informs whether caches and replicas are needed to protect the primary database.', tags: ['Estimation', 'capacity'] },
  { q: 'An API reports p50 latency of 50 ms and p99 latency of 2 seconds. What does that distribution suggest?', opts: ['Every request finishes somewhere between 50 ms and 2 seconds', 'Typical requests are fast, but roughly the slowest 1% take about 2 seconds or more', 'The arithmetic mean latency is exactly 2 seconds', 'Only one request in the period was slower than 50 ms'], a: 1, e: 'The median describes the typical request while p99 exposes the slow tail. At scale, even 1% can affect many requests and deserves investigation.', tags: ['Estimation', 'percentiles'] },
  { q: 'Storage estimate = items × size each. 1 billion 1 KB rows ≈:', opts: ['~1 TB', '~1 GB', '~1 MB', '~1 PB'], a: 0, e: '1e9 × 1 KB = 1e12 bytes ≈ 1 TB (before indexes/overhead/replication).', tags: ['Estimation', 'storage'] },
  { q: 'A small team expects modest launch traffic but might grow later. Which starting architecture is usually easiest to justify?', opts: ['Split every capability into an independently deployed service immediately', 'Use the simplest design that meets current requirements, then evolve from measured constraints', 'Shard every table before collecting traffic or query data', 'Add caches at every layer even when the backing store meets the latency target'], a: 1, e: 'Architectural complexity creates operational cost. Begin with a design that meets known needs and preserve sensible evolution paths rather than paying for hypothetical scale.', tags: ['Estimation', 'simplicity'] },

  // Level 15 — Designing Real Systems
  { q: 'Most URL-shortener traffic resolves a short code and redirects immediately. Which data-access shape dominates?', opts: ['A multi-table analytical join over every click event', 'A read-heavy key-to-value lookup from short code to destination URL', 'A cross-account transaction that locks many rows for each redirect', 'A graph traversal that discovers a path between two users'], a: 1, e: 'Redirects are simple, high-volume lookups by short code. A cache in front of a durable key-value mapping is a natural fit, while click analytics can use a separate path.', tags: ['Design', 'url-shortener'] },
  { q: 'A news feed is often built with:', opts: ['Only synchronous joins at read time', 'Fan-out on write (precomputing feeds) or fan-out on read, balancing write vs read cost', 'No database', 'A single giant table scan per view'], a: 1, e: 'Feeds trade off fan-out-on-write (fast reads, heavy writes) vs fan-out-on-read (cheaper writes, heavier reads).', tags: ['Design', 'newsfeed'] },
  { q: 'A chat system commonly relies on:', opts: ['Polling only, always', 'Persistent connections (WebSockets) and a message store/queue', 'Static files', 'Email'], a: 1, e: 'Real-time chat uses persistent connections (WebSockets) plus durable storage and often a message broker.', tags: ['Design', 'chat'] },
  { q: 'For a rate-limited public API, a critical component is:', opts: ['A CSS framework', 'A shared rate limiter (e.g. Redis-backed) at the gateway', 'A graph database', 'A spreadsheet'], a: 1, e: 'Public APIs need centralized rate limiting (often at the gateway, backed by Redis) to protect capacity and prevent abuse.', tags: ['Design', 'api'] },
  { q: 'To serve images globally with low latency you would use:', opts: ['One server in one country', 'Object storage + a CDN', 'Only the database', 'Client-side generation'], a: 1, e: 'Store blobs in object storage and front them with a CDN so users worldwide get low-latency, cached delivery.', tags: ['Design', 'media'] },
  { q: 'Idempotency keys are important in a payments API to:', opts: ['Speed up reads', 'Prevent double-charging when a request is retried', 'Encrypt cards', 'Shard the DB'], a: 1, e: 'An idempotency key lets the server recognize a retried payment request and avoid processing it twice.', tags: ['Design', 'payments'] },
  { q: 'Uploading a photo also creates four thumbnails, and resizing can take seconds. Which request flow is most resilient?', opts: ['Resize every thumbnail before acknowledging the upload', 'Store the upload, enqueue resize jobs, and let workers create thumbnails', 'Ask the browser to create the only permanent thumbnails', 'Run image processing in a database transaction that stays open until completion'], a: 1, e: 'Durably enqueueing the slow work keeps the request short and lets workers retry or scale independently. The design must also make repeated jobs safe.', tags: ['Design', 'jobs'] },
  { q: 'You receive a broad prompt to design a messaging service. What is the strongest opening sequence?', opts: ['Name a full technology stack before asking about users or traffic', 'Clarify the required behavior and scale, sketch a simple flow, then examine bottlenecks and trade-offs', 'Choose a distributed database first and adapt every requirement to it', 'Draw every possible component before defining the critical request path'], a: 1, e: 'Start by narrowing requirements and scale. A simple end-to-end flow gives you something concrete to test against bottlenecks, failure modes, and trade-offs.', tags: ['Design', 'method'] },
];
