// TypeScript roadmap questions — set B (100). A second question per level theme,
// distinct from set A. Combined with set A this gives 8 questions per level so
// each 5-level checkpoint has a full 40-question test. 25 levels × 4.

import type { Seed } from './roadmap-build';

export const tsSeedsB: Seed[] = [
  // ── Level 1 — Basic Types ──────────────────────────────────────────────
  { q: 'What happens?\n\n```ts\nlet x: string;\nx = 42;\n```', opts: ['Compiles', 'Type error', 'x is 42', 'Runtime error'], a: 1, e: 'A number is not assignable to a string variable.', tags: ['Types', 'Errors'] },
  { q: 'Which declaration uses a numeric type that TypeScript actually provides?', opts: ['const n: number = 3.14;', 'const n: float = 3.14;', 'const n: integer = 3;', 'const n: decimal = 3.14;'], a: 0, e: 'TypeScript types describe JavaScript values, and JavaScript has a single floating-point Number type, so number covers both 3.14 and 3. float, integer and decimal are not defined anywhere; the compiler reports Cannot find name for each. The only other built-in numeric primitive is bigint, for arbitrarily large integers written with an n suffix.', intro: 'TypeScript\'s primitive types mirror JavaScript\'s runtime values. Think about how JavaScript itself represents 3.14 and 3.', tags: ['Types'] },
  { q: 'What does TypeScript report?\n\n```ts\nlet u: undefined = undefined;\n```', opts: ['Type error: undefined is a value, not a type', 'Compiles: undefined is also a type holding that single value', 'Type error: u needs a union such as string | undefined', 'Compiles, but u is widened to any'], a: 1, e: 'undefined is both a value and a type: the type undefined contains exactly that one value, so the declaration compiles. On its own it is rarely written, but it is what makes unions such as string | undefined and optional properties work under strictNullChecks. The annotation also prevents widening, so u is not any, and nothing here runs or throws.', intro: 'Ask whether undefined may appear in a type position at all, and if so, which values that type admits.', tags: ['Types'] },
  { q: 'What does TypeScript report?\n\n```ts\nlet x: null = 0;\n```', opts: ['Compiles, because 0 is falsy like null', 'Type error: 0 is not assignable to null', 'Compiles, and x is widened to number | null', 'Compiles, because null accepts any primitive'], a: 1, e: 'The type null contains exactly one value, null, so assigning 0 is TS2322 (Type \'0\' is not assignable to type \'null\'). Falsiness means nothing to the checker: 0, "" and false belong to unrelated types. The annotation also blocks widening, so x does not silently become number | null; a union like that has to be written out.', intro: 'The type null is not a family of empty-looking values. Count how many values it contains before judging the assignment.', tags: ['Types', 'Errors'] },

  // ── Level 2 — Type Inference ───────────────────────────────────────────
  { q: 'What type is inferred for arr?\n\n```ts\nconst arr = [1, "a"];\n```', opts: ['number[]', '(string | number)[]', 'any[]', '[1, "a"]'], a: 1, e: 'TypeScript infers the element type as the union of every element\'s type, so [1, "a"] is (string | number)[]: each slot may hold either. It does not fall back to any[], and it does not produce the tuple [1, "a"], because array literals are treated as growable arrays; a tuple needs an annotation or as const. Reading an element later gives string | number, which you narrow before calling string-only or number-only methods.', intro: 'Elements 1 and "a" share no primitive type. Decide whether TypeScript gives up and uses any, or keeps both types in play.', tags: ['Inference', 'Arrays'] },
  { q: 'What type is inferred for x?\n\n```ts\nconst x = "hi";\n```', opts: ['string', '"hi"', 'any', 'const'], a: 1, e: 'A const string infers the literal type "hi".', tags: ['Inference', 'Literals'] },
  { q: 'What is the inferred return type?\n\n```ts\nfunction f() {\n  return 5;\n}\n```', opts: ['void', 'number', '5', 'any'], a: 1, e: 'Returning a number value infers a number return type.', tags: ['Inference', 'Functions'] },
  { q: 'What type is inferred for obj?\n\n```ts\nconst obj = { a: 1, b: "x" };\n```', opts: ['{ a: number; b: string }', '{ a: 1; b: "x" }', 'any', 'object'], a: 0, e: 'The binding is const, but the properties remain writable (obj.a = 2 is allowed), so TypeScript widens each property\'s literal to its base type: { a: number; b: string }. Literal property types such as { a: 1; b: "x" } appear only when you ask for them, with an explicit annotation or an as const assertion, which also makes the properties readonly. The type is not the vague object, and any is inferred only when the initialiser is itself any.', intro: 'obj is const, but its properties are not. Ask whether obj.a could be given a different number later, and what that means for the property\'s type.', tags: ['Inference', 'Objects'] },

  // ── Level 3 — Function Types ───────────────────────────────────────────
  { q: 'What does TypeScript report?\n\n```ts\nconst f: () => void = () => 5;\n```', opts: ['Type error: 5 is not assignable to void', 'No error; a void return type means callers ignore the result', 'Type error: an arrow function cannot be assigned to a function type', 'No error, but calling f() has type number'], a: 1, e: 'A function type with a void return does not constrain what the implementation returns; the arrow may return 5, and callers typed through f cannot use the result, since f() has type void. This rule is what lets you pass a value-returning arrow, or a method like array.push, to a callback typed () => void. The error appears only when the function itself carries the : void annotation, as in function g(): void { return 5 } or (): void => 5, because there the annotation applies to the body directly. At runtime f() still yields 5, which is why the types treat the value as ignored rather than absent.', intro: 'Ask what a () => void type promises to callers, and whether an implementation that hands back extra information breaks that promise.', tags: ['Functions', 'void'] },
  { q: 'Which callback satisfies run’s parameter type?\n\n```ts\nfunction run(cb: (n: number) => number) {}\n```', opts: ['n => console.log(n)', 'n => n * 2', 'n => String(n)', '(n: string) => n.length'], a: 1, e: 'cb must accept a number and return a number; n => n * 2 does both, with n contextually typed as number. n => console.log(n) returns void, so TS2322 reports that void is not assignable to number; n => String(n) returns a string and fails the same way; and (n: string) => n.length declares a parameter that cannot receive the number run will pass, which TS2345 rejects. Matching the parameter list alone is not enough.', intro: 'The callback type has two parts to satisfy: what n is and what the callback must give back. Check each candidate against both.', tags: ['Functions'] },
  { q: 'What is the inferred return type?\n\n```ts\nconst g = (a: number, b: number) => a > b;\n```', opts: ['number', 'boolean', 'void', 'any'], a: 1, e: 'A comparison returns a boolean.', tags: ['Functions', 'Inference'] },
  { q: 'What does f(1, 2, 3) return?\n\n```ts\nfunction f(...nums: number[]): number {\n  return nums.length;\n}\nf(1, 2, 3);\n```', opts: ['3', '6', '[1, 2, 3]', 'A type error, because f declares no fixed parameters'], a: 0, e: 'The rest parameter ...nums: number[] collects all three arguments into the array [1, 2, 3], and the body returns its length, 3. It does not sum the elements (6) and it does not return the array itself, because the return statement reads .length. Passing three arguments to a function whose only parameter is a rest parameter is exactly what rest parameters allow, so there is no type error; f() with no arguments would return 0.', intro: '...nums gathers every argument into one array. Ask what the body measures about that array rather than about the values inside it.', tags: ['Functions', 'Rest'] },

  // ── Level 4 — Arrays & Tuples ──────────────────────────────────────────
  { q: 'What type is t[0]?\n\n```ts\nconst t: [number, string] = [1, "a"];\nt[0];\n```', opts: ['number', 'string', '1', 'any'], a: 0, e: 'The tuple types position 0 as number.', tags: ['Tuples'] },
  { q: 'What does TypeScript report for the second line?\n\n```ts\nconst a: number[] = [];\na.push(1);\n```', opts: ['Type error: a is const and cannot be changed', 'No error; push accepts a number and const only fixes the binding', 'Type error: an empty array has no element type', 'Runtime error: the array is frozen'], a: 1, e: 'a is annotated number[], so push accepts a number and the call compiles; const only stops a from being rebound to another array and never freezes its contents. The annotation also matters because an empty literal gives TypeScript no element type to infer from on its own. Nothing is frozen at runtime, so there is no error there either; Object.freeze would be needed for that, and a readonly number[] type removes push at compile time.', intro: 'Separate the two possible objections: what const forbids for the name a, and what push on a number[] demands of its argument.', tags: ['Arrays'] },
  { q: 'What does TypeScript report?\n\n```ts\nconst t: [number, ...string[]] = [1, "a", "b"];\n```', opts: ['Type error: a tuple has a fixed length', 'No error; the rest element allows any number of trailing strings', 'Type error: "b" has no matching position', 'No error, but only because t is treated as (string | number)[]'], a: 1, e: '[number, ...string[]] means one required number followed by zero or more strings, so [1, "a", "b"] matches, and so would [1]. The rest element keeps the tuple a tuple: t[0] is still number and t is not downgraded to (string | number)[]. A second number, as in [1, 2], is rejected with TS2322. This shape, one fixed element plus a tail, is how a non-empty array type such as [T, ...T[]] is written.', intro: 'Read the tuple type as one fixed first slot plus an open-ended tail. Ask what the tail permits for the second and third values.', tags: ['Tuples'] },
  { q: 'What type does TypeScript give n?\n\n```ts\nconst pair: [string, number] = ["a", 1];\nconst n = pair.length;\n```', opts: ['number', '2', 'string | number', 'any'], a: 1, e: 'A tuple type fixes its element count, so [string, number] has length typed as the literal 2, and const n keeps that literal. A plain array such as string[] has length: number, because its size is unknown to the checker; this literal length is one of the ways tuples differ from arrays. string | number is the type of pair\'s elements, not of its length, and nothing here is any. The same fact is available at the type level as [string, number]["length"], which you will meet with indexed access types.', intro: 'pair is a tuple, so its size is fixed by its type. Ask how precisely TypeScript can state a length that can never change.', tags: ['Tuples', 'Indexed access'] },

  // ── Level 5 — Object Types ─────────────────────────────────────────────
  { q: 'What does TypeScript report for the second line?\n\n```ts\nconst o: { a: number } = { a: 1 };\no.b;\n```', opts: ['Compiles', 'Type error', 'undefined', 'Runtime error'], a: 1, e: 'o is typed { a: number }, which declares no b, so o.b is TS2339 (Property \'b\' does not exist on type \'{ a: number; }\'). In plain JavaScript the same read would yield undefined, and that silent undefined is exactly the bug the checker reports early. If unknown keys are expected, declare an index signature such as { a: number; [key: string]: number } or use a Record type.', intro: 'The type of o was written out explicitly. Ask whether the checker allows reading a property that the type never mentions, whatever JavaScript would return.', tags: ['Objects'] },
  { q: 'What does TypeScript report?\n\n```ts\ntype T = { [key: string]: number };\nconst x: T = { a: 1, b: 2 };\n```', opts: ['Type error: a and b are not declared in T', 'No error; any string key with a number value is allowed', 'Type error: index-signature keys must be numeric', 'No error, but only the first property is checked'], a: 1, e: 'An index signature { [key: string]: number } says that any property with a string name has a number value, so a and b are both allowed and no excess-property check applies to them. The word key is only a placeholder name, not a required property. The signature constrains values too: { a: "1" } would be TS2322. Use index signatures or Record<string, number> for dictionary-like objects whose keys are not known ahead of time.', intro: '[key: string]: number is not a property named key. Ask what it says about every property name a value of T may have.', tags: ['Objects', 'Index signatures'] },
  { q: 'What does TypeScript report for the second line?\n\n```ts\nconst o: { readonly a: number } = { a: 1 };\no.a = 5;\n```', opts: ['Compiles', 'Type error', 'a is 5', 'Runtime error'], a: 1, e: 'readonly a: number allows a to be set when the object is created and forbids assigning it afterwards, so o.a = 5 is TS2540 (Cannot assign to \'a\' because it is a read-only property). The check is static: readonly compiles away, so no runtime error occurs and Object.freeze would be needed for real immutability. It also applies only through this type; the same object seen through a type without readonly could still be modified.', intro: 'readonly governs what may happen to a after the object exists. Ask whether the checker or the runtime enforces it.', tags: ['Objects', 'readonly'] },
  { q: 'What does TypeScript report for the call?\n\n```ts\nfunction f(p: { x: number; y: number }) {}\nf({ x: 1, y: 2, z: 3 });\n```', opts: ['Compiles', 'Type error', 'z is ignored', 'Runtime error'], a: 1, e: 'A fresh object literal passed as an argument is checked against the parameter type just like an assignment, so z triggers TS2353 (Object literal may only specify known properties). The same literal stored in a variable first, const arg = { x: 1, y: 2, z: 3 }; f(arg);, is accepted because structural typing allows extra properties once the value is no longer fresh. z is therefore not silently ignored, and nothing fails at runtime.', intro: 'The argument is an object literal written straight into the call. Ask whether call arguments get the same freshness check as assignments to a typed variable.', tags: ['Objects', 'Excess properties'] },

  // ── Level 6 — Interfaces ───────────────────────────────────────────────
  { q: 'What does TypeScript report?\n\n```ts\ninterface A {\n  f(): void;\n}\nconst a: A = { f() {} };\n```', opts: ['Error: f must be written as f: () => void to match the interface', 'No error: the shorthand method f() {} matches the signature f(): void', 'Error: an empty body returns undefined, which is not void', 'No error, but calling a.f() fails because the body is empty'], a: 1, e: 'The literal supplies a callable f with no parameters, which is what f(): void requires, so it compiles. A void return type tells callers to ignore the result: an empty body returning undefined is fine, and so is f() { return 42; }, which also compiles. Shorthand and the property form f: () => void are both accepted, and calling an empty function simply returns undefined.', intro: 'Ask what void requires of the function body, and whether the shorthand f() {} counts as a different kind of member from f: () => void.', tags: ['Interfaces'] },
  { q: 'What does TypeScript report?\n\n```ts\ninterface A {\n  x: number;\n}\ninterface A {\n  y: number;\n}\nconst a: A = { x: 1, y: 2 };\n```', opts: ['Error: duplicate identifier A', 'No error: the two declarations merge, so A requires x and y', 'No error: the second declaration replaces the first, so only y is required', 'Error: a value cannot satisfy two declarations of one interface'], a: 1, e: 'Interfaces with the same name in the same scope merge, so A has x and y and the literal must supply both. Redeclaring neither conflicts nor replaces: `type A = ...` written twice is TS2300 Duplicate identifier \'A\', but interfaces are allowed to merge instead. The merge is not unconditional — declaring x: number and later x: string is TS2717 (Subsequent property declarations must have the same type). This is what makes module augmentation possible: adding members to an interface another package declares.', intro: 'Two declarations share the name A. Decide whether the second one competes with the first or adds to it.', tags: ['Interfaces', 'Merging'] },
  { q: 'What does this code do?\n\n```ts\ninterface Fn {\n  (n: number): number;\n}\nconst f: Fn = n => n * 2;\nf(3);\n```', opts: ['f(3) returns 6', 'Type error: an interface cannot describe a callable value', 'Type error: n is implicitly any because the arrow function has no annotation', 'f(3) returns 6, but the argument type is not checked at the call'], a: 0, e: 'A member with no name written as (n: number): number is a call signature, so Fn describes a callable value; the arrow function matches it and f(3) returns 3 * 2 = 6. n needs no annotation because Fn contextually types it as number, so strict mode raises no implicit-any error. The call is checked against the same signature: f("3") is TS2345, Argument of type \'string\' is not assignable to parameter of type \'number\'.', intro: '(n: number): number sits in the interface with no member name in front of it. Ask what that describes, and where n gets its type.', tags: ['Interfaces', 'Call signatures'] },
  { q: 'What does TypeScript report?\n\n```ts\ninterface A {\n  readonly id: number;\n}\nconst a: A = { id: 1 };\na.id = 2;\n```', opts: ['Error on a.id = 2: cannot assign to id because it is a read-only property', 'No error: readonly constrains the interface, not values typed by it', 'Error on const a: A = { id: 1 }: a readonly property cannot be set in a literal', 'No error at compile time; the assignment throws at run time'], a: 0, e: 'readonly forbids writing to the property through the type, so a.id = 2 is TS2540: Cannot assign to \'id\' because it is a read-only property. Initializing the property in the object literal is how a readonly property gets its value, so the declaration line is fine. The check is compile-time only and shallow: passing a to a parameter typed { id: number } lets the callee reassign id, and nothing throws at run time.', intro: 'readonly blocks exactly one operation on values of this type. Find the line that performs it.', tags: ['Interfaces', 'readonly'] },

  // ── Level 7 — Union Types ──────────────────────────────────────────────
  { q: 'What happens?\n\n```ts\nfunction f(x: "a" | "b") {}\nf("c");\n```', opts: ['Compiles', 'Type error', '"c" is allowed', 'Runtime error'], a: 1, e: 'The parameter x accepts only "a" or "b", and the argument "c" is neither, so the call is rejected (TS2345) before anything runs. Passing an argument is checked exactly like assigning to a variable of that type, so a runtime error is impossible here: the code never compiles.', intro: 'The parameter type lists two strings. Check the argument against that list; a call is checked the same way an assignment is.', tags: ['Unions', 'Literals'] },
  { q: 'What happens?\n\n```ts\nfunction f(x: number | string) {\n  return x.toFixed(2);\n}\n```', opts: ['Compiles', 'Type error', 'Error only at a call such as f("5")', 'Runtime error'], a: 1, e: 'toFixed exists on number but not on string, so on number | string the call is rejected (TS2339) inside the body of f, whether or not f is ever called, and nothing runs. To call it you first narrow, for example with typeof x === "number". Note that the form let x: number | string = 5; x.toFixed(2) compiles: assigning 5 narrows the local variable to number until the next assignment, which is why this question uses a parameter.', intro: 'A method call on a union is allowed only if every member has that method. Check toFixed on string as well as on number.', tags: ['Unions'] },
  { q: 'What happens?\n\n```ts\ntype T = (number | string)[];\nconst a: T = [1, "a", 2];\n```', opts: ['Type error', 'Compiles', 'Compiles, but a is widened to any[]', 'Runtime error'], a: 1, e: '(number | string)[] means every element is a number or a string, so [1, "a", 2] fits and the assignment compiles. This differs from number[] | string[], which would require all elements to share one type and would reject the mix. No widening to any happens: each element is checked against the union.', intro: 'The parentheses put the union inside the array type. Ask whether each element, one at a time, fits number | string.', tags: ['Unions', 'Arrays'] },
  { q: 'What happens?\n\n```ts\ntype R = string | number;\nconst r: R = true;\n```', opts: ['Compiles', 'Type error', 'r is true', 'Runtime error'], a: 1, e: 'R is string | number, and true has type boolean, which is not a member, so the assignment is rejected (TS2322). A union widens what a variable may hold, but only to the listed members; anything else is still an error, and because compilation fails there is no runtime step in which r could become true.', intro: 'R names exactly two types. Ask which type true has and whether that type appears in R.', tags: ['Unions', 'Errors'] },

  // ── Level 8 — Literal Types ────────────────────────────────────────────
  { q: 'What happens?\n\n```ts\ntype Yes = true;\nconst y: Yes = false;\n```', opts: ['Compiles', 'Type error', 'y is false', 'Runtime error'], a: 1, e: 'type Yes = true names the literal type true, which has exactly one value, so assigning false is rejected (TS2322). This differs from boolean, which would accept both values. Single boolean literals are useful as discriminants, for example { ok: true; data: T } | { ok: false; error: string }, where the checker can tell the two shapes apart.', intro: 'In a type position, true is a type with a single value, not the boolean type. Check whether the initializer is that value.', tags: ['Literals'] },
  { q: 'What type is obj.dir?\n\n```ts\nconst obj = { dir: "left" } as const;\nobj.dir;\n```', opts: ['string', '"left"', 'any', '{ readonly dir: "left" }'], a: 1, e: 'as const makes every property read-only and keeps its literal type, so obj has type { readonly dir: "left" } and obj.dir has type "left". Without the assertion, dir would be inferred as string because a mutable property is widened. { readonly dir: "left" } is the type of obj itself, not of obj.dir.', intro: 'Object properties are normally inferred with widened, mutable types. Decide what as const changes about that before naming the property type.', tags: ['Literals', 'as const'] },
  { q: 'What happens?\n\n```ts\nfunction move(d: "up" | "down") {}\nmove("up");\n```', opts: ['Type error', 'Compiles', 'Runtime error', 'Compiles only with a cast'], a: 1, e: '"up" is one of the two members of the parameter type, so the call compiles. A string literal passed directly is typed against the parameter, so no cast such as "up" as "up" is needed; a cast becomes tempting only when the value is held in a variable typed as string. Nothing fails at runtime.', intro: 'The parameter type lists the exact strings the function accepts. Compare the argument with that list before deciding what the compiler does.', tags: ['Literals'] },
  { q: 'What happens?\n\n```ts\nlet x: "a" = "a";\nx = "b";\n```', opts: ['Compiles', 'Type error', 'x is "b"', 'Runtime error'], a: 1, e: 'x is annotated as the literal type "a", so it can only ever hold "a"; the reassignment to "b" is rejected (TS2322). Using let does not widen the annotation to string: let only makes reassignment syntactically possible, and each assignment is still checked against the declared type. Compilation fails, so x never holds "b".', intro: 'The annotation, not the first value, fixes what x may hold for its whole lifetime. Check the second assignment against it.', tags: ['Literals'] },

  // ── Level 9 — Optional & Readonly ──────────────────────────────────────
  { q: 'What happens?\n\n```ts\ninterface T {\n  a?: number;\n}\nconst x: T = { a: undefined };\n```', opts: ['Type error', 'Compiles', 'a is required', 'Runtime error'], a: 1, e: 'An optional property accepts undefined.', tags: ['Optional'] },
  { q: 'What does f() return?\n\n```ts\nfunction f(a?: number) {\n  return a;\n}\nf();\n```', opts: ['0', 'undefined', 'Error', 'null'], a: 1, e: 'A missing optional argument is undefined, which is returned.', tags: ['Optional'] },
  { q: 'What happens?\n\n```ts\nconst arr: readonly number[] = [1, 2];\narr.push(3);\n```', opts: ['Compiles', 'Type error', 'arr is [1, 2, 3]', 'Runtime error'], a: 1, e: 'readonly number[] is the ReadonlyArray<number> type, which declares no mutating methods, so push does not exist on it and the call is rejected (TS2339). The restriction is compile-time only: at runtime the value is an ordinary array, so readonly is a promise about how your code treats the array rather than a frozen object. Reading, indexing, map and filter remain available.', intro: 'readonly number[] is a different type from number[]. Ask which methods that type declares before thinking about what runs.', tags: ['readonly', 'Arrays'] },
  { q: 'What happens?\n\n```ts\ninterface P {\n  readonly name: string;\n}\nlet p: P = { name: "a" };\np = { name: "b" };\n```', opts: ['Type error', 'Compiles', 'p.name stays "a"', 'Runtime error'], a: 1, e: 'readonly marks the property name inside a P object, so p.name = "b" would be an error, but the last line reassigns the variable p to a new object, which readonly does not restrict. Because p is declared with let, reassignment is allowed and the new object satisfies P, so after that line p.name reads "b". To lock the variable as well you would declare it with const.', intro: 'Find exactly which name readonly was attached to, then look at which name the last line writes to.', tags: ['readonly'] },

  // ── Level 10 — Type Aliases ────────────────────────────────────────────
  { q: 'What happens?\n\n```ts\ntype Age = number;\ntype User = { age: Age; name: string };\nconst u: User = { age: 1, name: "a" };\n```', opts: ['Type error', 'Compiles', 'Runtime error', 'Compiles, but age becomes any'], a: 1, e: 'Age is just another name for number, so age: 1 satisfies the age property and name: "a" satisfies name; the object compiles as a User. Aliases can be nested inside other aliases freely and are erased at compile time, so nothing changes at runtime and no property becomes any.', intro: 'Replace Age with the type it names, then check each property of the literal against User.', tags: ['Type aliases'] },
  { q: 'What does f(4) return?\n\n```ts\ntype Fn = (x: number) => number;\nconst f: Fn = x => x + 1;\nf(4);\n```', opts: ['5', 'a number', 'Error', 'undefined'], a: 0, e: 'f adds 1 to its argument: 4 + 1 = 5.', tags: ['Type aliases', 'Functions'] },
  { q: 'What is U?\n\n```ts\ntype T = string | number;\ntype U = T | boolean;\n```', opts: ['string | number | boolean', 'string | number', 'boolean', 'never'], a: 0, e: 'U substitutes T\'s definition and adds boolean, so U is the flat union string | number | boolean; unions never nest, so (string | number) | boolean is the same type. Nothing is intersected, so never does not appear, and the new member is added to, not swapped for, the existing ones. Building unions from smaller aliases is the usual way to grow a type incrementally.', intro: 'T is only a name for a union. Write out what T stands for, then add the new member and see whether anything nests.', tags: ['Type aliases', 'Unions'] },
  { q: 'What happens?\n\n```ts\ntype Tree = { value: number; children: Tree[] };\n```', opts: ['Type error', 'Compiles', 'Compiler hangs', 'Runtime error'], a: 1, e: 'The self-reference sits inside the element type of children, a position the compiler resolves lazily, so the alias compiles and describes a tree of any depth. A direct self-reference such as type T = T | number is rejected (TS2456: circularly references itself) because the checker has no base case. Nothing loops at runtime: types are erased and the declaration produces no JavaScript.', intro: 'Look at where Tree appears on the right-hand side: directly, or inside an array element type? The compiler treats those two positions differently.', tags: ['Type aliases', 'Recursive'] },

  // ── Level 11 — Type Narrowing ──────────────────────────────────────────
  { q: 'What happens?\n\n```ts\nfunction f(x: string | string[]) {\n  return typeof x === "string" ? x : x.join(",");\n}\n```', opts: ['Type error: join does not exist on x', 'Compiles', 'Type error: the two branches have different types', 'Compiles only if x is cast to string[]'], a: 1, e: 'typeof x === "string" narrows x to string in the true branch, and because that is the only other constituent, the false branch narrows to string[], where join exists. No cast is needed: the narrowing is what makes the second branch safe, and both branches produce string, so the return type is string. Note that typeof cannot name an array — typeof [] is "object" — so this pattern works by ruling the string case out rather than by testing for an array.', intro: 'typeof cannot name an array. Ask what is left in the false branch once the string case has been ruled out.', tags: ['Narrowing'] },
  { q: 'What is the return type?\n\n```ts\nfunction f(x?: number) {\n  if (x !== undefined) return x.toFixed();\n  return "0";\n}\n```', opts: ['number', 'string', 'number | string', 'Error'], a: 1, e: 'toFixed returns a string, not a number, so the guarded branch returns string and the fallback returns "0" — the inferred return type is string. Choosing number | string assumes the two branches differ; they do not, because toFixed formats a number into text. The x !== undefined check is what makes the call legal in the first place, but it has no effect on the return type.', intro: 'One branch calls toFixed. Check what that method hands back before you combine it with the other branch\'s value.', tags: ['Narrowing'] },
  { q: 'What happens?\n\n```ts\nfunction f(x: number | null) {\n  return x!.toFixed();\n}\n```', opts: ['Type error', 'Compiles', 'Compiles and checks x at runtime', 'Compiles only with strictNullChecks off'], a: 1, e: 'The ! operator asserts to the compiler that x is not null, so the call type-checks and the function returns string. The assertion is erased in the emitted JavaScript and adds no check, so f(null) still throws TypeError: Cannot read properties of null (reading \'toFixed\'). A real guard such as if (x === null) return "0" narrows the type and protects the call; ! only moves the risk from compile time to run time.', intro: 'The ! operator changes what the compiler believes about x. Ask whether it also changes the JavaScript that runs.', tags: ['Narrowing', 'Non-null'] },
  { q: 'In the else branch, what is the type of x?\n\n```ts\nfunction f(x: "a" | "b") {\n  if (x === "a") {\n  } else {\n    // here\n  }\n}\n```', opts: ['"a"', '"b"', '"a" | "b"', 'never'], a: 1, e: 'The union has two members and the equality test removes "a", so the else branch leaves exactly "b". never is the type only after every member has been ruled out — that is what an exhaustiveness check at the end of a switch relies on, and it is why an unhandled member shows up as a type error there. Choosing "a" | "b" assumes === against a literal tells the compiler nothing, but it narrows both branches.', intro: 'Two members, one of them ruled out by the test. Ask what the compiler has left when the equality check is false.', tags: ['Narrowing'] },

  // ── Level 12 — Type Guards ─────────────────────────────────────────────
  { q: 'After this check, what type is x?\n\n```ts\nfunction f(x: unknown) {\n  if (typeof x === "number") {\n    // x here\n  }\n}\n```', opts: ['unknown', 'number', 'any', 'never'], a: 1, e: 'typeof x === "number" narrows x inside the block, and because the declared type is unknown the narrowed type is exactly number. It does not stay unknown — narrowing is what makes unknown usable — and it is not any: the typeof test tells the compiler which type the value has, and the branch gets that type. never would be the result only if the declared type contained no number at all, for example string | boolean, where the branch is unreachable.', intro: 'The declared type is unknown. Ask what is left of it once the typeof test succeeds.', tags: ['Type guards'] },
  { q: 'Is this a valid type guard?\n\n```ts\nfunction isArr(x: unknown): x is unknown[] {\n  return Array.isArray(x);\n}\n```', opts: ['Type error', 'Yes, a valid type guard', 'runtime only', 'Runtime error'], a: 1, e: 'The x is unknown[] predicate makes it a custom type guard.', tags: ['Type guards'] },
  { q: 'What happens?\n\n```ts\nfunction f(x: Date | string) {\n  return x instanceof Date ? x.getFullYear() : x;\n}\n```', opts: ['Type error: getFullYear is not on Date | string', 'Compiles', 'Type error: instanceof works only on classes you define', 'Compiles only after casting x to Date'], a: 1, e: 'instanceof narrows x to Date in the true branch, so getFullYear is available; the false branch narrows to string, and the conditional\'s type is number | string. instanceof works with any constructor, built-ins included, so Date needs no special handling and no cast. Without the guard, getFullYear would not exist on every member of the union and the call would be rejected.', intro: 'x is one of two things and only one of them has getFullYear. Ask what instanceof tells the compiler in each branch.', tags: ['Type guards', 'instanceof'] },
  { q: 'What happens?\n\n```ts\nfunction f(x: { a: number } | { b: number }) {\n  return "a" in x ? x.a : x.b;\n}\n```', opts: ['Type error: a does not exist on the union', 'Compiles', 'Type error: in is a runtime operator only', 'Compiles only with a shared kind field'], a: 1, e: 'The in operator is a narrowing check: "a" in x leaves { a: number } in the true branch and { b: number } in the false branch, so x.a and x.b are each valid and the function returns number. Without the guard neither property exists on every member of the union, and both accesses would be rejected. A shared discriminant field such as kind is one way to narrow, but it is not required — in works from the property names themselves.', intro: 'Neither property exists on both members of the union. Ask what the in check leaves in each branch of the conditional.', tags: ['Type guards', 'in'] },

  // ── Level 13 — Enums ───────────────────────────────────────────────────
  { q: 'What is E.A + E.B?\n\n```ts\nenum E {\n  A = 1,\n  B = 2,\n}\nE.A + E.B;\n```', opts: ['3', '"AB"', '12', 'Error'], a: 0, e: 'E.A and E.B are the numbers 1 and 2 at runtime, so + adds them and the result is 3. The names A and B do survive on the emitted enum object, as keys and as values in its reverse mapping (E[1] is "A"), but + only ever sees the numbers, so neither "AB" nor 12 from string concatenation can happen. Adding two numeric enum members is also not a type error.', intro: 'Look at the value each member was given, then decide whether + is working on those numbers or on the member names.', tags: ['Enums'] },
  { q: 'Compiled by tsc with no extra flags (no isolatedModules, no preserveConstEnums), what does the compiler emit for the last line?\n\n```ts\nconst enum C {\n  X,\n  Y,\n}\nconsole.log(C.Y);\n```', opts: ['console.log(1); the value is inlined and no C object is emitted', 'console.log(C.Y); C is emitted as an ordinary enum object', 'console.log("Y"); the member name is inlined as a string', 'Nothing; a const enum member cannot be used as a value'], a: 0, e: 'Y auto-numbers to 1 (X is 0), and because C is a const enum the compiler replaces C.Y with that value: the output is console.log(1 /* C.Y */); and no C object exists at runtime. A plain enum would emit an object and keep the C.Y lookup, and so does a const enum compiled with isolatedModules, which is why the question fixes the flags. That inlining is also why const enums are avoided in shared code: a mismatched dependency version can bake in stale values.', intro: 'A const enum differs from a plain enum in what survives compilation; think about where the member\'s value ends up in the output JavaScript.', tags: ['Enums'] },
  { q: 'What does E.A.toUpperCase() return?\n\n```ts\nenum E {\n  A = "a",\n}\nE.A.toUpperCase();\n```', opts: ['"a"', '"A"', '0', 'Error'], a: 1, e: 'E.A is initialised with the string "a", so at runtime E.A is exactly that string and toUpperCase() returns "A". String enum members are never auto-numbered, so 0 is impossible, and because the member\'s type is a subtype of string the method call type-checks; it is not an error.', intro: 'Decide what E.A actually holds at runtime before asking what a string method does with it.', tags: ['Enums', 'Strings'] },
  { q: 'What is E.C?\n\n```ts\nenum E {\n  A,\n  B,\n  C,\n}\nE.C;\n```', opts: ['0', '1', '2', '"C"'], a: 2, e: 'Without initialisers a numeric enum starts at 0 and each member is one more than the previous: A = 0, B = 1, C = 2. Counting starts at 0, not 1, so 1 is B; and the name "C" is only reachable through the reverse mapping E[2], it is not the value of E.C.', intro: 'No member has an initialiser; recall where TypeScript starts counting and how each following member gets its value.', tags: ['Enums'] },

  // ── Level 14 — Generics: Basics ────────────────────────────────────────
  { q: 'What type is pair(1, "x")?\n\n```ts\nfunction pair<T, U>(a: T, b: U): [T, U] {\n  return [a, b];\n}\npair(1, "x");\n```', opts: ['[number, string]', '[T, U]', '[1, "x"]', 'any[]'], a: 0, e: 'T is inferred from 1 and U from "x", and both widen to number and string, so the annotated [T, U] becomes [number, string]. Widening happens because the parameters are unconstrained and sit inside a tuple in the return type; [1, "x"] would need a constraint such as T extends number or an as const argument. [T, U] is the declaration, not a result, and any[] would mean inference failed.', intro: 'Each type parameter is inferred from its own argument; then decide whether the literals 1 and "x" stay literal or widen inside the annotated tuple.', tags: ['Generics'] },
  { q: 'What is the return type of id("hi")?\n\n```ts\nfunction id<T>(x: T) {\n  return x;\n}\nid("hi");\n```', opts: ['string', '"hi"', 'T', 'any'], a: 1, e: 'T is inferred from "hi", and because T is the return type itself TypeScript keeps the literal: id("hi") has type "hi" (const r = id("hi") gives r: "hi"). Inference widens to string only when T is not returned directly, for example wrap<T>(x: T): T[] gives string[], or when the result is stored in a let variable, where let r = id("hi") is string. T is a placeholder inside the declaration and any never arises because inference succeeded.', intro: 'T is inferred from the argument and returned directly; decide whether TypeScript keeps the literal type or widens it in that position.', tags: ['Generics', 'Inference'] },
  { q: 'What does arr(true) return?\n\n```ts\nfunction arr<T>(x: T): T[] {\n  return [x, x];\n}\narr(true);\n```', opts: ['[true, true]', '[true]', 'true', 'A type error'], a: 0, e: 'The body returns [x, x], so arr(true) evaluates to [true, true]. T[] means an array of any length whose elements are T, so returning two elements is type-correct; a one-element tuple would be written [T]. T is inferred as boolean, which is only the element type, not the result.', intro: 'T[] is an ordinary array type; check what the body actually builds before deciding how many elements come back.', tags: ['Generics'] },
  { q: 'With strict mode and no other flags, what does first([10, 20]) return?\n\n```ts\nconst first = <T>(a: T[]): T => a[0];\nfirst([10, 20]);\n```', opts: ['10', '[10]', 'undefined', 'A type error'], a: 0, e: 'first is an ordinary arrow function whose body returns a[0], so first([10, 20]) evaluates to 10; T is inferred as number, but that only describes the element type. The result is an element, not an array, and the array is non-empty so undefined does not occur. The declaration type-checks under default strict settings; only the optional noUncheckedIndexedAccess flag would make a[0] be T | undefined and reject it.', intro: 'The <T> only names the element type; read the arrow body as plain JavaScript applied to [10, 20].', tags: ['Generics'] },

  // ── Level 15 — Generic Constraints ─────────────────────────────────────
  { q: 'What does f("hi") return?\n\n```ts\nfunction f<T extends string>(x: T) {\n  return x.length;\n}\nf("hi");\n```', opts: ['2', 'a number', '"hi"', 'Error'], a: 0, e: 'A string is allowed by the constraint; its length is 2.', tags: ['Generics', 'Constraints'] },
  { q: 'What does f([1, 2, 3]) return?\n\n```ts\nfunction f<T extends any[]>(x: T) {\n  return x.length;\n}\nf([1, 2, 3]);\n```', opts: ['3', 'a number', '[1, 2, 3]', 'Error'], a: 0, e: 'The array satisfies the constraint; its length is 3.', tags: ['Generics', 'Constraints'] },
  { q: 'What is the type of merge({ a: 1 }, { b: 2 })?\n\n```ts\nfunction merge<T extends object, U extends object>(a: T, b: U) {\n  return { ...a, ...b };\n}\nmerge({ a: 1 }, { b: 2 });\n```', opts: ['{ a: number } & { b: number }', '{ a: number }', '{ b: number }', 'object'], a: 0, e: 'Inside merge the compiler cannot enumerate the keys of T and U, so { ...a, ...b } is typed as the intersection T & U; at this call T = { a: number } and U = { b: number }, giving { a: number } & { b: number }, and the runtime value is { a: 1, b: 2 }. Neither spread wins entirely, so { a: number } and { b: number } alone are wrong, and the object constraint does not widen the result to object.', intro: 'Inside merge the compiler knows only T and U, never their key names. Ask what type the spread expression can be given in those terms.', tags: ['Generics', 'Constraints'] },
  { q: 'What does f({ id: 5, name: "a" }) return?\n\n```ts\nfunction f<T extends { id: number }>(x: T) {\n  return x.id;\n}\nf({ id: 5, name: "a" });\n```', opts: ['5', '{ id: 5 }', 'undefined', 'A type error'], a: 0, e: 'T is inferred as { id: number; name: string }, which satisfies T extends { id: number } because it has the required id, so the call compiles and x.id is 5. The extra property is not an excess-property error here: that check applies when an object literal is assigned directly to a non-generic type such as x: { id: number }, but with a type parameter the literal\'s full type becomes T. The function returns only the id, not the object.', intro: 'T is inferred from the whole argument, not just from the constraint; ask whether the extra name property blocks the call before reading the body.', tags: ['Generics', 'Constraints'] },

  // ── Level 16 — keyof & typeof ──────────────────────────────────────────
  { q: 'What is K?\n\n```ts\nconst p = { x: 1, y: 2 };\ntype K = keyof typeof p;\n```', opts: ['"x" | "y"', '{ x: number; y: number }', 'number', 'string'], a: 0, e: 'p is a value, so keyof cannot be applied to it directly; typeof p first produces its type { x: number; y: number }, and keyof of that is the union of property names "x" | "y". { x: number; y: number } is only the intermediate typeof result, number is the type of the values, and string is broader than the two known keys. keyof typeof is the usual way to type a function that accepts only the keys of an existing object.', intro: 'Apply the two operators in order: typeof p first gives a type, then ask what keyof does to that type.', tags: ['keyof', 'typeof'] },
  { q: 'What is T?\n\n```ts\nconst s = "hi";\ntype T = typeof s;\n```', opts: ['"hi"', 'string', 'any', 'unknown'], a: 0, e: 'A const variable initialised with a primitive literal keeps the literal type, so s is typed "hi" and typeof s is "hi". With let s = "hi" the type would widen to string, which is why string is the tempting wrong answer; any and unknown would only appear if the variable were annotated that way.', intro: 's is declared with const and initialised with a literal; recall what type TypeScript gives such a variable before applying typeof.', tags: ['typeof', 'Literals'] },
  { q: 'What is T?\n\n```ts\nconst arr = [1, 2, 3] as const;\ntype T = typeof arr[0];\n```', opts: ['1', 'number', '1 | 2 | 3', 'readonly [1, 2, 3]'], a: 0, e: 'as const makes arr a readonly tuple of literals, readonly [1, 2, 3], so typeof arr[0] is the type at position 0: the literal 1. Indexing with number instead of 0 would give the union 1 | 2 | 3; number would be the element type only without as const; and readonly [1, 2, 3] is the whole tuple, not one element.', intro: 'First write down the exact type as const gives arr, then apply the index [0] to that type.', tags: ['typeof', 'as const'] },
  { q: 'What is K?\n\n```ts\ntype K = keyof { 0: "a"; 1: "b" };\n```', opts: ['0 | 1', '"a" | "b"', 'number', 'string'], a: 0, e: 'keyof reports the property names as literal types; because these names are numeric, the result is 0 | 1 rather than the values "a" | "b". number would need a numeric index signature such as { [i: number]: string }, and string never appears because the keys are known. In practice you meet this with numeric-keyed lookup tables and with the numeric index type of arrays.', intro: 'The property names are written as numbers, not quoted strings; decide what literal type keyof reports for such a key.', tags: ['keyof'] },

  // ── Level 17 — Indexed Access Types ────────────────────────────────────
  { q: 'What is B?\n\n```ts\ntype T = { a: { b: number } };\ntype B = T["a"]["b"];\n```', opts: ['number', '{ b: number }', '"b"', 'T'], a: 0, e: 'Indexed access applies left to right: T["a"] is { b: number }, and indexing that with "b" gives number. { b: number } is the intermediate result after only the first bracket, and "b" is the key you index with, never the type it selects. Chaining this way lets you name a nested field\'s type without repeating its shape.', intro: 'Resolve the brackets left to right: take T\'s a property first, then look up b on whatever that gives you.', tags: ['Indexed access'] },
  { q: 'What is Values?\n\n```ts\ntype Person = { name: string; age: number };\ntype Values = Person[keyof Person];\n```', opts: ['string | number', 'string', 'number', 'keyof Person'], a: 0, e: 'Person[keyof Person] indexes with "name" | "age", and an indexed access with a union key resolves each key and unions the results: string | number. string or number alone would come from indexing with one key, and keyof Person is the key union itself, not the values those keys select. This is the standard way to say "the type of any value in this object".', intro: 'keyof Person is both key names at once; work out what each key gives you before deciding on a single result.', tags: ['Indexed access', 'keyof'] },
  { q: 'What is Item?\n\n```ts\nconst obj = { list: [1, 2, 3] };\ntype Item = typeof obj["list"][number];\n```', opts: ['number', 'number[]', '1 | 2 | 3', 'any'], a: 0, e: 'typeof obj["list"] is number[], because a plain array literal widens its elements to number; indexing that by number gives the element type, number. 1 | 2 | 3 would require as const to keep the literal types, and number[] is the array itself rather than one element. This typeof X[number] chain is the usual way to derive an element type from a value you already have.', intro: 'The last bracket asks for an element type, not the array itself. Check how the numbers in the literal were inferred before you pick.', tags: ['Indexed access', 'typeof'] },
  { q: 'What is R?\n\n```ts\ntype Fn = { greet: () => string };\ntype R = ReturnType<Fn["greet"]>;\n```', opts: ['string', '() => string', 'void', 'never'], a: 0, e: 'Fn["greet"] is an indexed access that selects the method\'s type, () => string, and ReturnType<T> extracts the return type of a function type: string. () => string is that function type itself, before ReturnType is applied. void would be right only if greet were declared () => void, and never would require a function declared never to return.', intro: 'Work out the type of Fn["greet"] first, then ask what ReturnType extracts from a function type.', tags: ['Indexed access', 'Utility'] },

  // ── Level 18 — Partial & Required ──────────────────────────────────────
  { q: 'What is T?\n\n```ts\ntype T = Required<Partial<{ a: number }>>;\n```', opts: ['{ a?: number }', '{ a: number }', '{}', 'never'], a: 1, e: 'Partial makes a optional, giving { a?: number }, and Required then strips the ?, so T is { a: number }. { a?: number } is only the inner result, and never is not what mapping over a type with one key produces. The round trip returns the original type here because a was required to begin with; Required also removes undefined, so Required<Partial<X>> is not X when X declares a: number | undefined.', intro: 'Apply the two utilities from the inside out, then ask whether the outer one undoes what the inner one did.', tags: ['Utility', 'Partial', 'Required'] },
  { q: 'What can you pass to update?\n\n```ts\ntype User = { id: number; name: string; email: string };\n\nfunction update(u: Partial<User>) {}\n```', opts: ['Only an object with all three properties', 'An object with any subset of User\'s properties', 'Only an object with no properties', 'Only an object with the id property'], a: 1, e: 'Partial<User> makes every property optional, so update accepts any subset of User\'s properties, including none at all. Demanding all three would be plain User, and accepting id alone would be Pick<User, "id">. Keys that are not on User are still rejected in an object literal, so a patch function stays type-checked while callers send only the fields they change.', intro: 'Partial changes only whether properties are required, not which properties exist. Decide which combinations that leaves valid.', tags: ['Utility', 'Partial'] },
  { q: 'What happens?\n\n```ts\ntype T = Partial<{ a: number; b: string }>;\nconst x: T = { b: "hi" };\n```', opts: ['It fails to compile, because a is missing', 'It compiles, because both properties are optional', 'It compiles only because b was supplied; {} would fail', 'It throws at runtime'], a: 1, e: 'Partial<{ a: number; b: string }> is { a?: number; b?: string }, so an object carrying only b satisfies it, and so would {}. Nothing is required, so there is no missing-property error and no minimum of one property. No runtime error is possible either: the annotation is erased before the code runs.', intro: 'x is annotated with the Partial version of the object type, not the original. Work out which of the two properties an object is obliged to carry.', tags: ['Utility', 'Partial'] },
  { q: 'What happens?\n\n```ts\ntype T = Required<{ a?: number }>;\nconst x: T = {};\n```', opts: ['Compiles', 'Type error', 'a is optional', 'Runtime error'], a: 1, e: 'Required makes a mandatory, so the empty object is a type error.', tags: ['Utility', 'Required'] },

  // ── Level 19 — Pick & Omit ─────────────────────────────────────────────
  { q: 'Which keys does T have?\n\n```ts\ntype T = Pick<{ a: 1; b: 2; c: 3 }, "a" | "c">;\n```', opts: ['a and c', 'b', 'all three', 'none'], a: 0, e: 'Pick keeps only the listed keys: a and c.', tags: ['Utility', 'Pick'] },
  { q: 'What is T?\n\n```ts\ntype T = Omit<{ a: 1; b: 2 }, "a" | "b">;\n```', opts: ['{ a: 1; b: 2 }', '{}', '{ a: 1 }', 'never'], a: 1, e: 'Omit is Pick<T, Exclude<keyof T, K>>, and excluding both keys leaves no keys, so T is {} - an object type that declares nothing. never is the empty type that no value has; {} is close to the opposite, since almost any value satisfies it. tsc accepts both const y: T = { z: 1 } and const n: T = 5 for this T, which is why an accidental Omit<T, keyof T> in generic code quietly stops checking anything.', intro: 'Every key is listed for removal. Ask what is left of an object type when no properties remain, and whether that is the same as no type at all.', tags: ['Utility', 'Omit'] },
  { q: 'Which keys does Safe have?\n\n```ts\ntype User = { id: number; pw: string };\ntype Safe = Omit<User, "pw">;\n```', opts: ['id and pw', 'id only', 'pw only', 'none'], a: 1, e: 'Omit<User, "pw"> builds a new object type from every key of User except "pw", so Safe is { id: number }. Reading the second argument as the keys to keep is what Pick does and would wrongly give pw only; nothing in Omit adds or removes id.', intro: 'Omit and Pick take the same two arguments but do opposite things. Decide which direction this one goes before reading the keys off.', tags: ['Utility', 'Omit'] },
  { q: 'What happens?\n\n```ts\ntype T = Pick<{ a: number }, "b">;\n```', opts: ['T is {}', 'Type error', 'T is { b }', 'any'], a: 1, e: 'Pick is declared as Pick<T, K extends keyof T>, so the type argument "b" must be one of the keys of { a: number }. It is not, and TypeScript reports TS2344: Type \'"b"\' does not satisfy the constraint \'"a"\'. The result is neither an empty object type nor { b }: the constraint is checked before any mapping happens.', intro: 'Pick<T, K> is declared with K extends keyof T. Ask what the checker does when the key you pass is not one of T\'s keys.', tags: ['Utility', 'Pick'] },

  // ── Level 20 — Record ──────────────────────────────────────────────────
  { q: 'What happens?\n\n```ts\ntype Scores = Record<"math" | "art", number>;\nconst s: Scores = { math: 90, art: 80 };\n```', opts: ['Type error', 'Compiles', 'art is missing', 'Runtime error'], a: 1, e: 'Record<"math" | "art", number> requires exactly the properties math and art, each a number. The literal supplies both with numbers, so it compiles; a missing key, a wrong value type, or an extra unknown key in the literal is what would make TypeScript reject it.', intro: 'List the keys the union demands and the keys the literal supplies, then compare the value types.', tags: ['Utility', 'Record'] },
  { q: 'What happens?\n\n```ts\ntype T = Record<number, string>;\nconst x: T = { 0: "a", 1: "b" };\n```', opts: ['Type error', 'Compiles', 'string keys only', 'Runtime error'], a: 1, e: 'Record<number, string> is { [x: number]: string }, a numeric index signature, so an object literal with keys 0 and 1 and string values compiles. Record\'s key parameter is constrained to keyof any (string | number | symbol), not to string alone; nothing runs at this point because the code only declares a type and a constant.', intro: 'Record\'s key type is constrained to keyof any, which is wider than string. Consider what property signature a number key produces.', tags: ['Utility', 'Record'] },
  { q: 'What happens?\n\n```ts\ntype Flags = Record<string, boolean>;\nconst f: Flags = { on: true, off: false };\n```', opts: ['Type error', 'Compiles', 'Runtime error', 'any'], a: 1, e: 'Any string key maps to a boolean, so this is valid.', tags: ['Utility', 'Record'] },
  { q: 'Record<K, V> is equivalent to:', opts: ['{ [P in K]: V }', 'K | V', '[K, V]', 'K & V'], a: 0, e: 'lib.es5.d.ts declares type Record<K extends keyof any, T> = { [P in K]: T }: a mapped type that creates one T-valued property for every member of K. K | V would be a union of the key and value types, [K, V] a two-element tuple, and K & V an intersection; none of them produces properties.', intro: 'Record is not a compiler primitive; lib.es5.d.ts spells it out in ordinary type syntax. Ask what shape a value of Record<K, V> has.', tags: ['Utility', 'Record'] },

  // ── Level 21 — Mapped Types ────────────────────────────────────────────
  { q: 'What does this do to each property?\n\n```ts\ntype Nullable<T> = { [K in keyof T]: T[K] | null };\n```', opts: ['makes them readonly', 'makes them optional', 'lets each also accept null', 'removes them'], a: 2, e: 'The mapped type keeps every key of T and replaces each value type with T[K] | null, so each property now accepts its original type or null; for { a: number } the result is { a: number | null }. No readonly or ? modifier appears, so the properties stay writable and required: a property that accepts null is not the same as an optional one.', intro: 'Compare the type on the right of the colon with the original T[K]; what has been added to it is the whole change.', tags: ['Mapped types'] },
  { q: 'What does each property become?\n\n```ts\ntype Getters<T> = { [K in keyof T]: () => T[K] };\n```', opts: ['its value', 'a function returning its value', 'optional', 'readonly'], a: 1, e: 'For each key K, the value type becomes () => T[K]: a zero-argument function returning the original value type, so Getters<{ a: number }> is { a: () => number }. No modifier is added, so the properties remain required and writable; the original value is only reachable by calling the function.', intro: 'The right side is no longer T[K] on its own; ask what kind of type has been built around it.', tags: ['Mapped types'] },
  { q: 'What does -readonly do here?\n\n```ts\ntype Mutable = { -readonly [K in keyof { readonly a: number }]: number };\n```', opts: ['keeps a readonly', 'makes a mutable', 'makes a optional', 'never'], a: 1, e: 'A mapped type over keyof X is homomorphic, so it normally copies X\'s modifiers: without the minus, a would stay readonly. -readonly removes that modifier, so Mutable is { a: number } and m.a = 2 compiles. This is the mirror image of +readonly (or bare readonly) and says nothing about optionality; the built-in Required<T> uses -? in the same way.', intro: 'Without the minus, a mapped type over keyof X copies X\'s property modifiers. Ask what a minus in front of a modifier does to that copy.', tags: ['Mapped types', 'readonly'] },
  { q: 'What is the result for { a: 1 }?\n\n```ts\ntype Keys<T> = { [K in keyof T]: K };\ntype R = Keys<{ a: 1 }>;\n```', opts: ['{ a: 1 }', '{ a: "a" }', '{ a: number }', 'never'], a: 1, e: 'The mapped type visits the single key "a" and, because the value position is K rather than T[K], gives the property the literal type of its own name: { a: "a" }. The original value 1 is never read (that would need T[K]), and number would require a widening that mapped types do not perform.', intro: 'A mapped type can put anything in the value position, not only the original value type. Read this one\'s value position and decide what type it names.', tags: ['Mapped types'] },

  // ── Level 22 — Conditional Types ───────────────────────────────────────
  { q: 'What is T?\n\n```ts\ntype T = 1 extends number ? true : false;\n```', opts: ['true', 'false', 'boolean', 'never'], a: 0, e: 'The literal type 1 is a subtype of number, so 1 extends number holds and the conditional selects its first branch, the literal type true. The checked type here is a concrete literal, not a type parameter standing for a union, so nothing distributes and the result is exactly one written branch: boolean would need a branch written as boolean, and never a branch written as never.', intro: 'Settle one question first: is the literal 1 assignable to number? The branch follows from that.', tags: ['Conditional types'] },
  { q: 'What is T?\n\n```ts\ntype T = string extends number ? "a" : "b";\n```', opts: ['"a"', '"b"', 'never', 'boolean'], a: 1, e: 'string does not extend number, so T is the "b" branch.', tags: ['Conditional types'] },
  { q: 'What is R?\n\n```ts\ntype Without<T, U> = T extends U ? never : T;\ntype R = Without<"a" | "b", "a">;\n```', opts: ['"a"', '"b"', 'never', '"a" | "b"'], a: 1, e: 'T is a naked type parameter, so the conditional distributes: the member matching U becomes never and the other is kept, and never adds nothing to a union, leaving "b". The untouched input union would be the answer only without distribution, and never only if every member matched U. This is exactly how the built-in Exclude<T, U> is defined.', intro: 'Notice that T is used bare on the left of extends. Ask what that does when the argument handed in is a union, before you read the branches.', tags: ['Conditional types', 'Distributive'] },
  { q: 'What is T?\n\n```ts\ntype T = [] extends { length: number } ? 1 : 0;\n```', opts: ['0', '1', 'never', 'boolean'], a: 1, e: 'Array and tuple types are object types with a length property - for the empty tuple it has type 0, which is assignable to number - so the check succeeds and T is the first branch, 1. Answering 0 assumes an array cannot satisfy a plain object shape. Nothing on the left of extends is a type parameter standing for a union, so no distribution happens and the result is exactly one of the two written branches, which is why boolean and never cannot appear.', intro: 'The check is structural, not nominal: ask whether the empty tuple type carries a length property that fits number.', tags: ['Conditional types'] },

  // ── Level 23 — infer ───────────────────────────────────────────────────
  { q: 'What is R?\n\n```ts\ntype Last<T> = T extends [...any[], infer L] ? L : never;\ntype R = Last<[1, 2, 3]>;\n```', opts: ['1', '3', 'number', 'never'], a: 1, e: '[...any[], infer L] matches a tuple that ends in one more element, so L binds to the last element type, 3. Answering 1 reads the pattern as though the named slot came first. never is the false branch, taken only when T is not a tuple. Rest elements in a leading position are exactly what makes last-element inference possible.', intro: 'The pattern puts the rest element before the named slot. Work out which element of [1, 2, 3] the named slot can line up with.', tags: ['infer', 'Tuples'] },
  { q: 'What is R?\n\n```ts\ntype Arg<T> = T extends (a: infer A) => any ? A : never;\ntype R = Arg<(x: string) => void>;\n```', opts: ['string', 'void', 'never', 'x'], a: 0, e: 'The signature matches (a: infer A) => any with A bound to the first parameter\'s type, so R is string. Parameter names are not part of a function type\'s identity - the names a and x need not agree - so x is not a type and cannot be the result. void is the return type, which this pattern discards by matching it against any.', intro: 'Match (x: string) => void against the pattern and ask what the first parameter\'s type has to be.', tags: ['infer'] },
  { q: 'What is R?\n\n```ts\ntype Unwrap<T> = T extends Promise<infer U> ? U : T;\ntype R = Unwrap<number>;\n```', opts: ['number', 'never', 'Promise<number>', 'U'], a: 0, e: 'number does not match Promise<infer U>, so the conditional takes its false branch, which is written as T - the input itself - making R number. It is not never, because neither branch of this conditional is written as never; filtering helpers are the ones that put never in a branch. And the conditional never wraps its input, so Promise<number> cannot be produced.', intro: 'Check whether the input matches the Promise pattern at all, then read what the false branch is written as.', tags: ['infer', 'Conditional types'] },
  { q: 'What is R?\n\n```ts\ntype Inner<T> = T extends Array<Array<infer U>> ? U : never;\ntype R = Inner<number[][]>;\n```', opts: ['number[][]', 'number[]', 'number', 'never'], a: 2, e: 'number[][] is Array<Array<number>>, so the pattern Array<Array<infer U>> matches both levels and binds U to the innermost element type, number. number[] is the result of peeling only one level, which this pattern does not do. never is the false branch, taken when T is not a two-level array.', intro: 'The pattern nests one Array inside another. Line number[][] up against it and decide which level the placeholder is on.', tags: ['infer'] },

  // ── Level 24 — Template Literal Types ──────────────────────────────────
  { q: 'What is T?\n\n```ts\ntype T = Uppercase<"hello">;\n```', opts: ['"hello"', '"HELLO"', '"Hello"', 'string'], a: 1, e: 'Uppercase<S> is a compiler intrinsic that upper-cases the whole literal, so the result is the literal type "HELLO". "Hello" would be Capitalize<"hello">, which changes only the first character. The result also stays a literal type rather than widening to string, which is what makes these intrinsics useful for deriving key names.', intro: 'This is one of TypeScript\'s four built-in string-manipulation types. Decide how much of the literal it changes.', tags: ['Template literals'] },
  { q: 'What is T?\n\n```ts\ntype T = `${1}-${2}`;\n```', opts: ['"1-2"', '"12"', '"3"', 'number'], a: 0, e: 'Number literal types are converted to their text form when interpolated, and the hyphen is a fixed part of the template, so T is the string literal type "1-2". "12" would require the hyphen to disappear, and nothing arithmetic happens at the type level, so "3" is never produced.', intro: 'A template literal type is assembled piece by piece. Write out every part in order, including what sits between the placeholders.', tags: ['Template literals'] },
  { q: 'What happens?\n\n```ts\ntype Event = `${string}Changed`;\nconst e: Event = "valueChanged";\n```', opts: ['Type error', 'Compiles', 'Runtime error', 'any'], a: 1, e: '"valueChanged" matches the pattern `${string}Changed`.', tags: ['Template literals'] },
  { q: 'What is T?\n\n```ts\ntype T = Capitalize<"name">;\n```', opts: ['"name"', '"Name"', '"NAME"', 'string'], a: 1, e: 'Capitalize<S> upper-cases only the first character, so "name" becomes the literal type "Name". "NAME" is Uppercase<"name">, which changes every character. The result stays a literal type rather than widening to string, which is what lets patterns like `on${Capitalize<K & string>}` derive handler names from keys.', intro: 'Capitalize and Uppercase differ in scope, not in direction. Decide how many characters this one touches.', tags: ['Template literals'] },

  // ── Level 25 — Mixed Mastery ───────────────────────────────────────────
  { q: 'What is T?\n\n```ts\ntype T = Partial<Pick<{ a: number; b: string }, "a">>;\n```', opts: ['{ a?: number }', '{ a: number }', '{ b?: string }', 'never'], a: 0, e: 'Pick<{ a: number; b: string }, "a"> is { a: number }, and Partial marks each property optional, so T is { a?: number } - the compiler prints it as { a?: number | undefined; }. { a: number } is the result of skipping the outer Partial, and { b?: string } keeps the key that Pick discarded.', intro: 'Read it from the inside out: what does Pick leave, and what does the outer utility then change about it?', tags: ['Utility', 'Mastery'] },
  { q: 'What type is prop({ a: "x" }, "a")?\n\n```ts\nfunction prop<T, K extends keyof T>(o: T, k: K): T[K] {\n  return o[k];\n}\nprop({ a: "x" }, "a");\n```', opts: ['string', '"x"', 'T[K]', 'any'], a: 0, e: 'T is inferred as { a: string } - a mutable object literal widens "x" to string - and K is "a", so the return type T[K] resolves to string. "x" would require the argument to be asserted as const, or the parameter to force literal inference. T[K] is not an answer either: an indexed access is evaluated once both type arguments are known.', intro: 'T is inferred from the argument object. Decide how a string property in a plain object literal is inferred.', tags: ['Generics', 'Mastery'] },
  { q: 'What is R?\n\n```ts\ntype R = ReturnType<() => Promise<number>>;\n```', opts: ['number', 'Promise<number>', 'void', 'never'], a: 1, e: 'ReturnType<T> extracts the return type as written, and this signature declares Promise<number>, so R is Promise<number>. number is the value the promise resolves to; reaching it takes Awaited<ReturnType<T>>, which unwraps the promise. void and never would require a signature that returns nothing or an argument that is not a function type.', intro: 'Two types are in play here: the one the signature declares and the one the promise resolves to. Decide which one ReturnType is defined to give.', tags: ['Utility', 'Mastery'] },
  { q: 'What is T?\n\n```ts\ntype T = Record<"a", number> & Record<"b", string>;\n```', opts: ['{ a: number; b: string }', '{ a: number } | { b: string }', 'never', 'any'], a: 0, e: 'Each Record contributes one required property and & requires a value to satisfy both, so T behaves as { a: number; b: string }; the compiler still prints the intersection, but the two types are assignable to each other in both directions. A union would let a value satisfy only one side, which is the opposite of &. The intersection is not never either: object types with different keys have nothing to conflict over.', intro: 'Notice which operator joins the two Record types, then work out what a single value must provide to be accepted by it.', tags: ['Utility', 'Mastery'] },
];
