// The Skeletal System roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const skeletalSystemSeeds: Seed[] = [
  // ── Level 1 — Bone structure, composition & types ──
  { q: 'How many bones are in the typical adult human skeleton?', opts: ['106', '206', '306', '406'], a: 1, e: 'The adult skeleton has 206 bones; infants are born with about 270, many of which fuse during growth.', tags: ['Skeletal System', 'Bone Basics'] },
  { q: 'Which mineral gives bone most of its hardness?', opts: ['Sodium chloride', 'Calcium phosphate', 'Potassium iodide', 'Magnesium sulfate'], a: 1, e: 'Calcium phosphate, deposited as hydroxyapatite crystals, provides bone with its rigidity and compressive strength.', tags: ['Skeletal System', 'Bone Basics'] },
  { q: 'What protein gives bone its flexibility and tensile strength?', opts: ['Collagen', 'Keratin', 'Actin', 'Elastin'], a: 0, e: 'Collagen fibres form the organic matrix of bone, giving it flexibility so it resists breaking under tension.', tags: ['Skeletal System', 'Bone Basics'] },
  { q: 'Which type of bone is the femur (thigh bone) classified as?', opts: ['Short bone', 'Flat bone', 'Long bone', 'Irregular bone'], a: 2, e: 'The femur is a long bone: longer than it is wide, with a shaft and two ends, built for support and leverage.', tags: ['Skeletal System', 'Bone Types'] },
  { q: 'What is the dense, hard outer layer of bone called?', opts: ['Spongy bone', 'Compact bone', 'Cartilage', 'Marrow'], a: 1, e: 'Compact (cortical) bone forms the dense outer shell, providing strength; spongy bone lies deeper inside.', tags: ['Skeletal System', 'Bone Structure'] },
  { q: 'Red bone marrow is chiefly responsible for producing what?', opts: ['Bile', 'Blood cells', 'Digestive enzymes', 'Insulin'], a: 1, e: 'Red bone marrow carries out haematopoiesis, generating red blood cells, white blood cells, and platelets.', tags: ['Skeletal System', 'Bone Function'] },
  { q: 'The skull and sternum are examples of which bone type?', opts: ['Long bones', 'Flat bones', 'Sesamoid bones', 'Long bones only'], a: 1, e: 'Flat bones, such as those of the skull and the sternum, are thin and often protect organs or provide broad muscle attachment.', tags: ['Skeletal System', 'Bone Types'] },
  { q: 'Which is NOT a major function of the skeletal system?', opts: ['Support', 'Protection of organs', 'Mineral storage', 'Producing hormones like adrenaline'], a: 3, e: 'The skeleton supports, protects, stores minerals, and makes blood cells; adrenaline comes from the adrenal glands, not bone.', tags: ['Skeletal System', 'Bone Function'] },

  // ── Level 2 — The axial skeleton (skull, spine, ribs) ──
  { q: 'The axial skeleton includes which of the following?', opts: ['Arms and legs', 'Skull, spine, and rib cage', 'Hands and feet', 'Shoulder and hip girdles'], a: 1, e: 'The axial skeleton forms the central axis: the skull, vertebral column, and thoracic cage (ribs and sternum).', tags: ['Skeletal System', 'Axial Skeleton'] },
  { q: 'How many vertebrae make up the typical adult vertebral column?', opts: ['24 separate plus sacrum and coccyx', '12', '7', '40 separate bones'], a: 0, e: 'Adults have 24 movable vertebrae (7 cervical, 12 thoracic, 5 lumbar) plus the fused sacrum and coccyx.', tags: ['Skeletal System', 'Vertebral Column'] },
  { q: 'Which region of the spine consists of 7 vertebrae in the neck?', opts: ['Cervical', 'Thoracic', 'Lumbar', 'Sacral'], a: 0, e: 'The cervical region has 7 vertebrae; nearly all mammals, including giraffes, share this number.', tags: ['Skeletal System', 'Vertebral Column'] },
  { q: 'How many pairs of ribs does a typical human have?', opts: ['10', '12', '14', '8'], a: 1, e: 'Humans normally have 12 pairs of ribs, all attached posteriorly to the thoracic vertebrae.', tags: ['Skeletal System', 'Rib Cage'] },
  { q: 'What is the common name for the sternum?', opts: ['Collarbone', 'Breastbone', 'Shoulder blade', 'Kneecap'], a: 1, e: 'The sternum, or breastbone, is a flat bone in the centre of the chest to which most ribs connect via cartilage.', tags: ['Skeletal System', 'Rib Cage'] },
  { q: 'Which ribs are called "floating ribs" because they lack an anterior attachment?', opts: ['Pairs 1–2', 'Pairs 8–10', 'Pairs 11–12', 'Pairs 5–6'], a: 2, e: 'The 11th and 12th rib pairs attach only to the vertebrae and are called floating ribs, having no sternal connection.', tags: ['Skeletal System', 'Rib Cage'] },
  { q: 'The first cervical vertebra, which supports the skull, is named the', opts: ['Axis', 'Atlas', 'Sacrum', 'Hyoid'], a: 1, e: 'The atlas (C1) holds up the skull and allows the nodding "yes" motion; it articulates with the axis (C2) below.', tags: ['Skeletal System', 'Vertebral Column'] },
  { q: 'Which bone of the skull encloses and protects the brain as a domed vault?', opts: ['Mandible', 'Cranium', 'Maxilla', 'Zygomatic'], a: 1, e: 'The cranium is the bony braincase; the mandible, maxilla, and zygomatic are facial bones outside the vault.', tags: ['Skeletal System', 'Skull'] },

  // ── Level 3 — The appendicular skeleton (limbs, girdles) ──
  { q: 'The appendicular skeleton consists mainly of what?', opts: ['Skull and spine', 'Limbs and their girdles', 'Ribs and sternum', 'Vertebrae only'], a: 1, e: 'The appendicular skeleton comprises the arms, legs, and the pectoral and pelvic girdles that anchor them.', tags: ['Skeletal System', 'Appendicular Skeleton'] },
  { q: 'Which bone is the only movable bone of the pectoral (shoulder) girdle attaching to the axial skeleton?', opts: ['Scapula', 'Clavicle', 'Humerus', 'Radius'], a: 1, e: 'The clavicle (collarbone) links the arm to the sternum; the scapula attaches to the axial skeleton only via muscles.', tags: ['Skeletal System', 'Pectoral Girdle'] },
  { q: 'What is the single long bone of the upper arm?', opts: ['Humerus', 'Femur', 'Tibia', 'Ulna'], a: 0, e: 'The humerus is the upper-arm bone, running from the shoulder to the elbow, where it meets the radius and ulna.', tags: ['Skeletal System', 'Upper Limb'] },
  { q: 'Which two bones make up the forearm?', opts: ['Tibia and fibula', 'Radius and ulna', 'Femur and patella', 'Carpals and tarsals'], a: 1, e: 'The forearm contains the radius (thumb side) and the ulna (little-finger side), which allow rotation of the hand.', tags: ['Skeletal System', 'Upper Limb'] },
  { q: 'The pelvic girdle attaches the lower limbs to which part of the axial skeleton?', opts: ['Skull', 'Sacrum', 'Sternum', 'Clavicle'], a: 1, e: 'The two hip bones join the sacrum posteriorly, transmitting body weight from the spine to the legs.', tags: ['Skeletal System', 'Pelvic Girdle'] },
  { q: 'What is the largest and strongest bone in the human body?', opts: ['Tibia', 'Humerus', 'Femur', 'Pelvis'], a: 2, e: 'The femur, the thigh bone, is the longest and strongest bone, bearing much of the body\'s weight during movement.', tags: ['Skeletal System', 'Lower Limb'] },
  { q: 'Which small bones form the wrist?', opts: ['Tarsals', 'Carpals', 'Metacarpals', 'Phalanges'], a: 1, e: 'The wrist is made of eight carpal bones arranged in two rows; the metacarpals lie in the palm beyond them.', tags: ['Skeletal System', 'Upper Limb'] },
  { q: 'The patella is better known as which structure?', opts: ['Kneecap', 'Ankle bone', 'Heel bone', 'Elbow'], a: 0, e: 'The patella, or kneecap, is a sesamoid bone embedded in the quadriceps tendon that protects the knee joint.', tags: ['Skeletal System', 'Lower Limb'] },

  // ── Level 4 — Joints & articulations ──
  { q: 'What is a joint (articulation)?', opts: ['A break in a bone', 'A place where two bones meet', 'A type of muscle', 'A blood vessel in bone'], a: 1, e: 'A joint is any site where two or more bones meet; joints vary in how much movement they permit.', tags: ['Skeletal System', 'Joints'] },
  { q: 'Which joint type allows the widest range of movement, as in the shoulder and hip?', opts: ['Hinge joint', 'Ball-and-socket joint', 'Pivot joint', 'Suture'], a: 1, e: 'Ball-and-socket joints let the rounded head of one bone rotate freely within a cup, giving movement in all directions.', tags: ['Skeletal System', 'Joint Types'] },
  { q: 'The elbow and knee are examples of which joint type?', opts: ['Ball-and-socket', 'Hinge joint', 'Gliding joint', 'Fixed joint'], a: 1, e: 'Hinge joints permit movement in one plane, like a door hinge, allowing flexion and extension only.', tags: ['Skeletal System', 'Joint Types'] },
  { q: 'What tough tissue connects bone to bone across a joint?', opts: ['Tendon', 'Ligament', 'Cartilage', 'Nerve'], a: 1, e: 'Ligaments are bands of dense connective tissue that link bone to bone and stabilise joints.', tags: ['Skeletal System', 'Joints'] },
  { q: 'The immovable joints between the bones of the adult skull are called', opts: ['Sutures', 'Pivots', 'Bursae', 'Menisci'], a: 0, e: 'Sutures are fibrous joints where cranial bones interlock tightly, allowing essentially no movement.', tags: ['Skeletal System', 'Joint Types'] },
  { q: 'What slippery tissue covers the ends of bones to reduce friction in a joint?', opts: ['Compact bone', 'Articular cartilage', 'Periosteum', 'Tendon'], a: 1, e: 'Articular (hyaline) cartilage caps bone ends, providing a smooth, low-friction surface for movement.', tags: ['Skeletal System', 'Joints'] },
  { q: 'What is the function of synovial fluid in a joint?', opts: ['To harden the bone', 'To lubricate and nourish the joint', 'To produce blood cells', 'To store fat'], a: 1, e: 'Synovial fluid lubricates the joint surfaces, reduces friction, and delivers nutrients to the cartilage.', tags: ['Skeletal System', 'Joints'] },
  { q: 'The rotation of the head "no" is enabled by which joint between the atlas and axis?', opts: ['Hinge joint', 'Pivot joint', 'Saddle joint', 'Gliding joint'], a: 1, e: 'A pivot joint between C1 and C2 lets the atlas rotate around the axis\'s dens, turning the head side to side.', tags: ['Skeletal System', 'Joint Types'] },

  // ── Level 5 — Bone growth, remodeling & common disorders ──
  { q: 'The process by which cartilage is gradually replaced by bone during growth is called', opts: ['Ossification', 'Digestion', 'Filtration', 'Respiration'], a: 0, e: 'Ossification (osteogenesis) is the formation of bone; endochondral ossification replaces a cartilage model with bone.', tags: ['Skeletal System', 'Bone Growth'] },
  { q: 'Which cells build new bone matrix?', opts: ['Osteoclasts', 'Osteoblasts', 'Erythrocytes', 'Neurons'], a: 1, e: 'Osteoblasts synthesise and deposit new bone matrix; osteoclasts break bone down, balancing remodeling.', tags: ['Skeletal System', 'Bone Remodeling'] },
  { q: 'Which cells break down and resorb bone tissue?', opts: ['Osteoblasts', 'Osteoclasts', 'Osteocytes', 'Chondrocytes'], a: 1, e: 'Osteoclasts are large cells that dissolve bone matrix, releasing minerals and enabling remodeling and repair.', tags: ['Skeletal System', 'Bone Remodeling'] },
  { q: 'Lengthwise bone growth in children occurs at the', opts: ['Growth plate (epiphyseal plate)', 'Bone marrow', 'Periosteum tips only', 'Joint capsule'], a: 0, e: 'The epiphyseal (growth) plate is a cartilage zone near bone ends where lengthening occurs until it closes in adulthood.', tags: ['Skeletal System', 'Bone Growth'] },
  { q: 'Osteoporosis is a condition characterised by', opts: ['Excess bone density', 'Weak, porous, brittle bones', 'Extra ribs', 'Overgrown cartilage'], a: 1, e: 'In osteoporosis bone resorption outpaces formation, lowering density and greatly raising fracture risk.', tags: ['Skeletal System', 'Bone Disorders'] },
  { q: 'A deficiency of which vitamin impairs calcium absorption and can cause rickets?', opts: ['Vitamin C', 'Vitamin D', 'Vitamin K', 'Vitamin B12'], a: 1, e: 'Vitamin D is needed to absorb calcium; its deficiency causes soft, deformed bones (rickets in children).', tags: ['Skeletal System', 'Bone Disorders'] },
  { q: 'Which hormone raises blood calcium partly by stimulating bone resorption?', opts: ['Insulin', 'Parathyroid hormone (PTH)', 'Adrenaline', 'Melatonin'], a: 1, e: 'Parathyroid hormone increases blood calcium by promoting osteoclast activity and renal calcium reabsorption.', tags: ['Skeletal System', 'Bone Regulation'] },
  { q: 'Osteoarthritis primarily involves the degeneration of what tissue at joints?', opts: ['Ligaments', 'Articular cartilage', 'Bone marrow', 'Tendons'], a: 1, e: 'Osteoarthritis is the wear-and-tear breakdown of articular cartilage, causing pain, stiffness, and reduced mobility.', tags: ['Skeletal System', 'Bone Disorders'] },
];
