// CSS, rebalanced: six levels of the browser, not of one library's vocabulary.
//
// The old nine-level path spent its final three levels — a third of the course —
// on Tailwind and styling approaches, and one of those questions asserted that
// theme configuration belongs in a config file, which stopped being true when
// Tailwind moved theming into CSS with `@theme`. Meanwhile the cascade, the box
// model and layout debugging — the things that decide whether a bug takes two
// minutes or an afternoon — got one level each.
//
// So the scope is six levels of the underlying model: the cascade, the box and
// flow, Flexbox, Grid and responsiveness, positioning and stacking, and
// maintainable accessible styling. A styling tool is a way of writing these
// down; none of them stops being true because a class name is doing the
// writing.
//
// Where a question depends on a version or a context, it says so, because "it
// depends" is the honest answer to most CSS questions and the useful part is
// what it depends on.
//
// Authored for devShark. See docs/curriculum-retirement.md.

import type { Seed } from './roadmap-build';

export const cssCoreSeeds: Seed[] = [
  // ── Level 1 — Cascade, inheritance, selectors and scope ────────────────
  { q: 'Two rules in the same stylesheet set `color` on the same element: `.card p` and `p`. Assuming no layers and no `!important`, which wins?', opts: ['`p`, because it is simpler', '`.card p`, because its selector is more specific', 'Whichever appears later in the file', 'Neither — the declaration is dropped'], a: 1, e: 'Specificity is compared before source order. One class plus one element beats one element, so `.card p` wins wherever it applies; order only decides between selectors of equal specificity.', tags: ['CSS', 'Cascade'] },
  { q: 'Two rules with identical specificity set the same property. What decides?', opts: ['The one defined first', 'The one defined last', 'The shorter selector', 'The one in the smaller file'], a: 1, e: 'At equal specificity the later declaration wins. This is why the order of imported stylesheets matters, and why a library imported after your overrides silently undoes them.', tags: ['CSS', 'Cascade'] },
  { q: 'A declaration is marked `!important`. What has that actually changed?', opts: ['Its specificity is raised', 'It moves to a higher-priority origin, above all normal declarations from that origin', 'It applies before other rules', 'It becomes inherited'], a: 1, e: 'Importance is a separate step in the cascade, ahead of specificity. That is why one `!important` is usually answered by another rather than by a more specific selector — and why it is worth avoiding rather than winning.', tags: ['CSS', 'Cascade'] },
  { q: 'Which of these properties is inherited by default?', opts: ['`border`', '`color`', '`padding`', '`display`'], a: 1, e: 'Typography-related properties inherit; box-related ones do not. It is a practical division: you want text colour to flow down a subtree and you would not want a border on every descendant.', tags: ['CSS', 'Cascade'] },
  { q: 'What do cascade layers (`@layer`) let you express that specificity alone cannot?', opts: ['Faster selector matching', 'That one whole group of rules should lose to another regardless of how specific it is', 'Scoped styles per component', 'Conditional styling'], a: 1, e: 'A later layer beats an earlier one whatever the selectors say, which is how a library’s styles can be made to lose to yours without an escalation. Assume no layers unless a question says otherwise: they change the answer.', tags: ['CSS', 'Cascade'] },
  { q: 'What does `:is(h1, h2, h3) .badge` take its specificity from?', opts: ['The first argument, `h1`', 'The most specific argument in the list', 'The number of arguments', 'It has zero specificity'], a: 1, e: '`:is()` takes the specificity of its most specific argument, which is what makes it a compact shorthand rather than a free one. `:where()` is the zero-specificity version, and that difference is usually the reason to pick one.', tags: ['CSS', 'Selectors'] },
  { q: 'What does `:has(> img)` on a card select?', opts: ['The images inside cards', 'Cards that contain an image as a direct child', 'The first card containing an image', 'Nothing — it is not a real selector'], a: 1, e: '`:has()` matches the ancestor based on its descendants, which is the "parent selector" CSS lacked for twenty years. It is widely supported now; state the assumption when a browser floor matters.', tags: ['CSS', 'Selectors'] },
  { q: 'A style applies to an element in one page and not another, and the selectors are identical. What is worth checking first?', opts: ['The file encoding', 'Whether the two pages load the stylesheets in a different order, or one is inside a layer', 'The element’s tag name', 'Whether CSS is enabled'], a: 1, e: 'Identical selectors mean the cascade decided, and origin, layer and order are what it decided on. The computed-styles panel showing which rule won is faster than reading either file.', tags: ['CSS', 'Cascade'] },

  // ── Level 2 — Box model, flow, sizing and overflow ─────────────────────
  { q: 'An element has `width: 300px`, `padding: 20px` and `border: 5px`, under `box-sizing: content-box`. How wide is its border box?', opts: ['300px', '350px', '345px', '325px'], a: 1, e: '300 + 40 of padding + 10 of border = 350. Under `content-box` the width sets the content only, which is why nearly every codebase sets `box-sizing: border-box` globally.', tags: ['CSS', 'Box model'] },
  { q: 'What does `box-sizing: border-box` change?', opts: ['The border is drawn inside the padding', '`width` includes padding and border rather than only the content', 'Margins stop collapsing', 'The element becomes a block'], a: 1, e: 'It makes `width: 300px` mean "300 wide on screen", which is what people expect. It changes nothing about margins, which sit outside the border box either way.', tags: ['CSS', 'Box model'] },
  { q: 'Two stacked block elements have `margin-bottom: 20px` and `margin-top: 30px`. What is the gap in normal flow?', opts: ['50px', '30px', '20px', '0'], a: 1, e: 'Adjacent vertical margins collapse to the larger of the two. It surprises people every time, and it does not happen inside a flex or grid container — which is one reason gaps are easier to reason about there.', tags: ['CSS', 'Box model'] },
  { q: 'What does `min-height: 100%` on a child depend on?', opts: ['The viewport height', 'The parent having a resolvable height', 'The `display` value', 'The document height'], a: 1, e: 'A percentage needs something to be a percentage of. If the parent’s height is `auto`, there is nothing to resolve against — which is why the pattern usually appears with `100vh`, or with the parent made a flex or grid container.', tags: ['CSS', 'Sizing'] },
  { q: 'A long unbroken string overflows its container. Which property addresses it directly?', opts: ['`text-overflow: ellipsis`', '`overflow-wrap: anywhere`', '`white-space: nowrap`', '`overflow: hidden`'], a: 1, e: 'The string has no break opportunity, so wrapping needs permission to break inside a word. `overflow: hidden` clips the symptom, and `text-overflow` only applies to a single clipped line.', tags: ['CSS', 'Overflow'] },
  { q: 'A page scrolls horizontally on a phone and nobody knows why. What is the most efficient way to find the cause?', opts: ['Set `overflow-x: hidden` on the body', 'Find the element wider than the viewport — an outline on everything, or a scripted width comparison', 'Remove media queries one at a time', 'Reduce the base font size'], a: 1, e: 'Something is wider than the viewport, and the fix belongs on that element. Hiding the overflow on the body hides the evidence and often traps content off-screen where it cannot be reached.', tags: ['CSS', 'Overflow'] },
  { q: 'What is the difference between `1rem` and `1em` for a font size?', opts: ['They are identical', '`rem` is relative to the root font size; `em` is relative to the element’s inherited font size', '`em` is absolute', '`rem` is relative to the viewport'], a: 1, e: 'Because `em` compounds through nesting, three levels of `0.9em` is not `0.9`. `rem` is stable, which is what makes it the safer default for type — and both respect the user’s browser setting, which `px` does not.', tags: ['CSS', 'Sizing'] },
  { q: 'Why is `width: 100%` on an element with horizontal padding often the wrong tool inside a flex row?', opts: ['Percentages are not allowed in flex containers', 'It sizes against the parent rather than participating in the layout, and can overflow', 'It disables `gap`', 'It forces a line break'], a: 1, e: 'In a flex or grid context the layout is meant to distribute space; a fixed percentage opts out of that and then adds padding on top. `flex: 1` or a grid track expresses the intent and cannot overflow the way this does.', tags: ['CSS', 'Sizing'] },

  // ── Level 3 — Flexbox ──────────────────────────────────────────────────
  { q: 'In a flex container with `flex-direction: row`, which axis does `justify-content` act on?', opts: ['The vertical axis', 'The main axis, which is horizontal here', 'Both axes', 'The axis with more space'], a: 1, e: '`justify-content` is the main axis and `align-items` is the cross axis. Switch the direction to `column` and the two swap, which is where most flex confusion starts.', tags: ['CSS', 'Flexbox'] },
  { q: 'What does `flex: 1` expand to?', opts: ['`flex-grow: 1`, `flex-shrink: 1`, `flex-basis: 0%`', '`flex-grow: 1` only', '`flex-basis: 1`', '`flex-grow: 1`, `flex-shrink: 0`, `flex-basis: auto`'], a: 0, e: 'The `flex-basis: 0%` is the part people miss: items share the space equally regardless of their content. `flex: auto` keeps `flex-basis: auto`, so content size is respected first.', tags: ['CSS', 'Flexbox'] },
  { q: 'Flex items overflow the container instead of wrapping. What is the likeliest cause?', opts: ['`flex-wrap` is `nowrap`, which is the default', '`justify-content` is wrong', 'The container is missing a width', '`align-items` is `stretch`'], a: 0, e: 'A flex container does not wrap unless told to. It is the default nearly everyone forgets, and it shows up as a row that keeps going past the edge on a narrow screen.', tags: ['CSS', 'Flexbox'] },
  { q: 'A flex item with long text refuses to shrink below its content. What usually fixes it?', opts: ['`flex-shrink: 0`', '`min-width: 0` on the item', '`overflow: hidden` on the container', '`width: auto`'], a: 1, e: 'A flex item’s automatic minimum size is its content, so it will not shrink past it. `min-width: 0` releases that floor, and it is the standard fix for a truncating label that refuses to truncate.', tags: ['CSS', 'Flexbox'] },
  { q: 'What is the difference between `align-items` and `align-content` in a wrapping flex container?', opts: ['They are the same', '`align-items` positions items within their line; `align-content` distributes the lines themselves', '`align-content` works only on grids', '`align-items` works only with `nowrap`'], a: 1, e: 'With a single line `align-content` has nothing to distribute and appears to do nothing — which is why it looks broken until the container wraps.', tags: ['CSS', 'Flexbox'] },
  { q: 'Which is the more robust way to space flex items evenly with a fixed gap?', opts: ['`margin-right` on every item, negated on the last', '`gap`', '`justify-content: space-between`', 'A spacer element between items'], a: 1, e: '`gap` puts the spacing between items and nowhere else, so nothing needs negating and wrapping still behaves. `space-between` distributes leftover space, which is a different thing and varies with the container.', tags: ['CSS', 'Flexbox'] },
  { q: 'An icon and a label sit in a flex row and the icon squashes on narrow screens. What is the fix?', opts: ['`flex-shrink: 0` on the icon', '`align-items: center`', '`flex-wrap: wrap`', '`min-width` on the container'], a: 0, e: 'Every flex item shrinks by default. Telling the icon not to concentrates the shrinking on the text, which is what has room to give.', tags: ['CSS', 'Flexbox'] },
  { q: 'When is Flexbox a better fit than Grid?', opts: ['Whenever there is more than one item', 'When the layout is one dimension and the item sizes should follow the content', 'When the layout must be responsive', 'When alignment is needed'], a: 1, e: 'Flexbox distributes along one axis from the content out; Grid defines a structure both ways and places into it. A toolbar is flex; a page skeleton is grid — and mixing them per level is normal.', tags: ['CSS', 'Flexbox'] },

  // ── Level 4 — Grid and responsive layout ───────────────────────────────
  { q: 'What does `grid-template-columns: repeat(auto-fit, minmax(200px, 1fr))` produce?', opts: ['Exactly three columns', 'As many columns of at least 200px as fit, sharing the leftover space', 'One column per item', 'A fixed 200px grid'], a: 1, e: 'The browser decides the column count from the available width. It is a responsive grid with no media query at all, which is usually the better answer because it responds to the container rather than the viewport.', tags: ['CSS', 'Grid'] },
  { q: 'What is the difference between `auto-fit` and `auto-fill` when there are fewer items than tracks?', opts: ['None', '`auto-fit` collapses the empty tracks so items stretch; `auto-fill` keeps them, leaving a gap', '`auto-fill` collapses them', '`auto-fit` creates more tracks'], a: 1, e: 'With a full row they are identical, which is why the difference goes unnoticed until a row is short — and then one stretches two cards across the width and the other leaves them narrow.', tags: ['CSS', 'Grid'] },
  { q: 'What does the `fr` unit distribute?', opts: ['The total container width', 'The space left after fixed sizes and gaps are taken', 'A fraction of the viewport', 'A fraction of the content width'], a: 1, e: 'It is a share of the *remaining* space, which is why `200px 1fr` works and why adding a gap does not break the arithmetic — the gap is subtracted before the fractions are handed out.', tags: ['CSS', 'Grid'] },
  { q: 'A grid item with long content refuses to shrink and pushes the layout wide. What is the usual cause?', opts: ['The gap is too large', 'A grid track’s automatic minimum is `auto`, so it will not go below its content', 'The container is missing a width', '`fr` does not shrink'], a: 1, e: 'Same shape as the flex problem: `minmax(0, 1fr)` instead of `1fr` releases the content floor. It is the single commonest grid bug once real text arrives.', tags: ['CSS', 'Grid'] },
  { q: 'A media query breakpoint is chosen at 768px because that is a common tablet width. What is the better basis?', opts: ['The most popular device sizes this year', 'The width at which this layout stops working', 'The nearest round number', 'The design tool’s default artboards'], a: 1, e: 'Device widths change and there are too many. Widening the window until the content looks wrong gives a breakpoint that belongs to the layout and stays right when devices change.', tags: ['CSS', 'Responsive'] },
  { q: 'What does a container query let you do that a media query cannot?', opts: ['Query the user’s preferences', 'Style a component by the size of its container rather than the viewport', 'Query the device model', 'Apply styles conditionally on scroll'], a: 1, e: 'A card in a sidebar and the same card in a main column want different layouts at the same viewport width. The media query cannot tell them apart; the container query is asking the question that actually decides.', tags: ['CSS', 'Responsive'] },
  { q: 'Why is `min-width` generally preferred over `max-width` in media queries?', opts: ['It is faster', 'It expresses a mobile-first base with progressive additions, which is easier to reason about', 'It has better support', 'It avoids specificity conflicts'], a: 1, e: 'Mobile-first means the base styles need no query and each breakpoint adds. Either direction works; mixing them in one stylesheet is what produces rules that fight.', tags: ['CSS', 'Responsive'] },
  { q: 'Which layout still has a legitimate use for `float`?', opts: ['A two-column page', 'Wrapping text around an image or a pull quote', 'A card grid', 'A sticky header'], a: 1, e: 'Wrapping text around a figure is what floats were for and still do best. Using them for page columns is what Flexbox and Grid replaced, and there is no reason to go back.', tags: ['CSS', 'Layout'] },

  // ── Level 5 — Positioning and stacking ─────────────────────────────────
  { q: 'What is `position: absolute` positioned relative to?', opts: ['The viewport', 'The nearest positioned ancestor, or the initial containing block if there is none', 'Its parent, always', 'The document body'], a: 1, e: 'Nearest *positioned* — anything other than `static`. A dropdown escaping to the page corner is nearly always this: the intended ancestor was never given `position: relative`.', tags: ['CSS', 'Positioning'] },
  { q: 'What does `position: sticky` need in order to do anything?', opts: ['A `z-index`', 'A threshold such as `top`, and a scrolling ancestor with room to scroll', 'A fixed height', '`overflow: hidden` on the parent'], a: 1, e: 'Without a threshold it has nothing to stick at. And an ancestor with `overflow: hidden` clips the scroll it needed, which is the commonest reason a correct-looking sticky does nothing at all.', tags: ['CSS', 'Positioning'] },
  { q: 'A modal with a high `z-index` still renders behind the header. What is the likeliest cause?', opts: ['The z-index is not high enough', 'The modal is inside a stacking context whose own level is below the header', 'The header uses `position: fixed`', 'z-index only works on positioned elements'], a: 1, e: 'z-index is compared within a stacking context, not globally. A transform, a filter, an opacity below 1 — any of them creates one, and the child cannot escape its parent’s place in the order however large its number.', tags: ['CSS', 'Stacking'] },
  { q: 'Which of these creates a new stacking context?', opts: ['`position: relative` with no `z-index`', '`opacity: 0.99`', '`overflow: hidden`', '`display: flex`'], a: 1, e: 'Any opacity below 1 creates one, along with transforms, filters and `will-change`. That is why an animation added for polish can reorder a layout that was working.', tags: ['CSS', 'Stacking'] },
  { q: 'What is the containing block for a `position: fixed` element in the ordinary case?', opts: ['Its parent', 'The viewport', 'The document', 'The nearest positioned ancestor'], a: 1, e: 'The viewport — except when an ancestor has a transform, filter or `will-change`, which makes *it* the containing block. A fixed header that scrolls away inside a transformed section is exactly this.', tags: ['CSS', 'Positioning'] },
  { q: 'A tooltip is clipped by its parent. Which property on an ancestor is the likely cause?', opts: ['`position: relative`', '`overflow: hidden`', '`z-index: 0`', '`display: flex`'], a: 1, e: 'Clipping comes from overflow, not from stacking. Raising the z-index changes nothing; the tooltip has to leave the clipping ancestor, or the ancestor has to stop clipping.', tags: ['CSS', 'Positioning'] },
  { q: 'What does `inset: 0` on an absolutely positioned element do?', opts: ['Adds padding on all sides', 'Sets top, right, bottom and left to 0, stretching it to its containing block', 'Centres it', 'Sets a margin'], a: 1, e: 'It is the shorthand for all four offsets. With a width and a height set to auto, the element fills its containing block — the standard overlay.', tags: ['CSS', 'Positioning'] },
  { q: 'A dropdown must escape a parent that clips it. Which approach solves it structurally?', opts: ['A larger z-index', 'Rendering it outside the clipping ancestor — a portal, or the top layer via `popover`/`dialog`', 'Removing the parent’s padding', '`overflow: visible` on the dropdown'], a: 1, e: 'Clipping is decided by the ancestor, so the fix is to not be inside it. The top layer exists for this: it renders above everything without depending on the stacking order at all.', tags: ['CSS', 'Stacking'] },

  // ── Level 6 — Maintainable, accessible styling ─────────────────────────
  { q: 'What does a custom property (`--brand: green`) give you that a preprocessor variable does not?', opts: ['Smaller files', 'It exists at runtime: it cascades, inherits, and can be changed per element or by script', 'Better browser support', 'Type checking'], a: 1, e: 'A preprocessor variable is gone by the time the browser sees the file. A custom property is live, which is what makes theming by scope — a dark section, one component overriding one token — possible at all.', tags: ['CSS', 'Architecture'] },
  { q: 'A theme is defined with custom properties on `:root`, and one component needs a different accent. What is the cheapest correct change?', opts: ['Redefine the property on that component’s own element', 'Add an `!important` override for each affected rule', 'Duplicate the component’s styles', 'Add a second stylesheet'], a: 0, e: 'Custom properties inherit, so redefining one on a subtree reskins everything under it that reads it. That is the whole design: components read the token and never the value.', tags: ['CSS', 'Architecture'] },
  { q: 'Where does Tailwind v4 expect theme tokens to be defined?', opts: ['In a JavaScript config file', 'In CSS, using `@theme`', 'In an inline `style` attribute', 'In a JSON file'], a: 1, e: 'Version 4 moved theming into CSS with `@theme`; the JavaScript config was the v3 answer. State the version when a syntax question depends on it — an unqualified "the config file" is now wrong.', tags: ['CSS', 'Tooling'] },
  { q: 'What does a utility-class approach change about the cascade?', opts: ['Nothing', 'Most declarations end up at the same low specificity, so conflicts are resolved by which class is applied rather than by selector weight', 'It removes inheritance', 'It disables the cascade'], a: 1, e: 'That flatness is the appeal: no specificity war, because nothing is more specific than anything else. It is a way of writing CSS, not a different CSS — the box model and the cascade are underneath either way.', tags: ['CSS', 'Tooling'] },
  { q: 'Why is `outline: none` on `:focus` a problem?', opts: ['It breaks the layout', 'It removes the only indication a keyboard user has of where they are', 'It disables the click handler', 'It is invalid CSS'], a: 1, e: 'The focus ring is how somebody not using a mouse knows what Enter will activate. If the default ring clashes with the design, replace it with a visible one — `:focus-visible` shows it for keyboard use and not for mouse clicks.', tags: ['CSS', 'Accessibility'] },
  { q: 'A status is shown by turning text red. What is missing?', opts: ['A larger font', 'A cue that is not colour — a word, an icon, or a shape', 'A higher z-index', 'A transition'], a: 1, e: 'Colour alone excludes anyone who cannot distinguish it, and disappears in a high-contrast mode or on a bad screen. The word "Error" beside the red does the work for everyone.', tags: ['CSS', 'Accessibility'] },
  { q: 'What should `@media (prefers-reduced-motion: reduce)` do to a card that lifts and fades in?', opts: ['Nothing — it is only a preference', 'Remove the movement and keep the fade', 'Remove both', 'Speed both up'], a: 1, e: 'The setting is usually about vestibular discomfort, which movement causes and opacity does not. Removing everything loses the feedback for no benefit; freezing the transform is the change that matters.', tags: ['CSS', 'Accessibility'] },
  { q: 'A layout is correct at 100% zoom and unusable at 200%. Which choice is the likeliest cause?', opts: ['Using `rem` for spacing', 'Fixed pixel heights on containers holding text', 'Using Grid', 'Using custom properties'], a: 1, e: 'Zooming enlarges the text and the fixed box does not follow, so the content overflows or is clipped. Sizing from the content — `min-height` rather than `height` — survives it, and zoom is the cheapest accessibility test there is.', tags: ['CSS', 'Accessibility'] },
];
