import type { Seed } from './roadmap-build';

// React Hook Form + Zod learning path — 120 questions (15 levels × 8), ordered
// easiest → hardest. Teaches form handling with React Hook Form (v7) and schema
// validation with Zod (v3), then how to combine them via zodResolver: from
// controlled vs uncontrolled inputs, register/handleSubmit and built-in rules,
// through Zod primitives/objects/infer and safeParse, to Controller,
// useFieldArray, refine/superRefine, discriminated unions and integration
// patterns. Built like the other single-list topics via buildRoadmap
// (ids rm-rhf-1 … rm-rhf-120, 8 per level).
export const rhfZodSeeds: Seed[] = [
  // Level 1 — Forms in React (why RHF + Zod)
  { q: "In React, what is a 'controlled' input?", opts: ["An input whose value is driven by React state via value and onChange", "An input that can only be edited by an administrator", "An input that never re-renders", "An input that stores its value only in the DOM"], a: 0, e: "A controlled input gets its value from React state and updates it through onChange, so React is the single source of truth for that field.", tags: ["forms", "controlled"], intro: "Start with the core idea behind React forms." },
  { q: "What is an 'uncontrolled' input in React?", opts: ["An input that is disabled", "An input whose value lives in the DOM and is read via a ref", "An input bound to Redux", "An input that validates itself automatically"], a: 1, e: "An uncontrolled input keeps its value in the DOM. You read it when needed (e.g. via a ref) instead of mirroring every keystroke in React state.", tags: ["forms", "uncontrolled"] },
  { q: "Which problem does React Hook Form (RHF) primarily aim to solve?", opts: ["Styling forms with CSS", "Making network requests", "The boilerplate and frequent re-renders of fully controlled forms", "Routing between pages"], a: 2, e: "RHF reduces the boilerplate of controlled forms and minimizes re-renders by embracing uncontrolled inputs with subscriptions.", tags: ["RHF", "why"] },
  { q: "How does React Hook Form keep re-renders low by default?", opts: ["By using uncontrolled inputs (refs) and isolated subscriptions instead of re-rendering on every keystroke", "By disabling React's reconciler", "By caching the whole component tree", "By rendering forms on the server only"], a: 0, e: "RHF registers inputs as uncontrolled and tracks them with refs, so typing in one field doesn't re-render the entire form.", tags: ["RHF", "performance"] },
  { q: "What is Zod?", opts: ["A CSS-in-JS library", "A state management library", "A test runner", "A TypeScript-first schema declaration and validation library"], a: 3, e: "Zod lets you declare a schema once and use it to validate data at runtime and to infer static TypeScript types.", tags: ["Zod", "basics"] },
  { q: "Why is pairing React Hook Form with Zod a popular combination?", opts: ["Zod renders the form UI for you", "One Zod schema can drive both runtime validation and the form's TypeScript types while RHF manages form state", "Zod replaces React entirely", "RHF cannot work without Zod"], a: 1, e: "RHF handles form state/submission; Zod provides validation and inferred types from a single schema, avoiding duplicated rules and type definitions.", tags: ["RHF", "Zod", "why"] },
  { q: "Which package provides the adapter that connects Zod to React Hook Form?", opts: ["react-zod-form", "@hookform/resolvers", "zod-react", "@rhf/zod"], a: 1, e: "The @hookform/resolvers package exposes zodResolver (imported from '@hookform/resolvers/zod') to bridge Zod and RHF.", tags: ["RHF", "Zod", "setup"] },
  { q: "A key DRY benefit of using Zod with RHF + TypeScript is that:", opts: ["You can skip writing any components", "The form values type can be inferred from the schema, so you don't maintain a separate interface", "It removes the need for a submit button", "Validation runs only on the server"], a: 1, e: "With z.infer you derive the form value type directly from the schema, keeping validation and types in sync from one source.", tags: ["Zod", "types"] },

  // Level 2 — useForm & register
  { q: "Which hook do you call to create a form with React Hook Form?", opts: ["useState()", "useForm()", "useFormState()", "createForm()"], a: 1, e: "useForm() initializes a form instance and returns helpers like register, handleSubmit and formState.", tags: ["RHF", "useForm"] },
  { q: "What does register('email') do in React Hook Form?", opts: ["Sends the email to the server", "Creates a new React context", "Registers the input with RHF, returning props (name, onChange, onBlur, ref) to spread onto it", "Permanently stores the value in localStorage"], a: 2, e: "register returns the props RHF needs to track an input; you spread them onto the field so RHF can manage its value and validation.", tags: ["RHF", "register"] },
  { q: "How do you attach register to a native input?", opts: ["<input ref={register} />", "<input register='email' />", "<input {...register('email')} />", "<input onChange={register} />"], a: 2, e: "You spread the object returned by register onto the input: <input {...register('email')} />.", tags: ["RHF", "register"] },
  { q: "What does the object returned by register contain?", opts: ["Only a value string", "name, onChange, onBlur and a ref", "A full React component", "The validation error message"], a: 1, e: "register returns name, onChange, onBlur and ref — the wiring RHF needs for an uncontrolled input.", tags: ["RHF", "register"] },
  { q: "Which of these is returned by useForm()?", opts: ["register, handleSubmit and formState", "useEffect and useMemo", "fetch and axios", "dispatch and getState"], a: 0, e: "useForm() returns an object including register, handleSubmit, formState, control, watch, reset and more.", tags: ["RHF", "useForm"] },
  { q: "What is the purpose of the defaultValues option in useForm?", opts: ["To disable validation", "To set each field's initial value", "To define the submit URL", "To choose a theme"], a: 1, e: "defaultValues seeds the form's initial field values and is also what reset() falls back to.", tags: ["RHF", "defaultValues"] },
  { q: "By default, inputs registered with React Hook Form are:", opts: ["Controlled by React state", "Uncontrolled (managed via refs)", "Read-only", "Rendered on the server"], a: 1, e: "RHF registers inputs as uncontrolled by default, which is what keeps re-renders minimal.", tags: ["RHF", "uncontrolled"] },
  { q: "How do you register a field for a nested value like a city inside an address object?", opts: ["register('address->city')", "register('address.city')", "register('city', 'address')", "register('[address][city]')"], a: 1, e: "RHF uses dot/bracket path notation, so register('address.city') maps to { address: { city } } in the form values.", tags: ["RHF", "nested"] },

  // Level 3 — handleSubmit & onSubmit
  { q: "What does handleSubmit(onSubmit) return?", opts: ["The form data immediately", "An event handler you pass to the form's onSubmit", "A promise that never resolves", "A React component"], a: 1, e: "handleSubmit wraps your callback and returns an event handler; attach it to <form onSubmit={handleSubmit(onSubmit)}>.", tags: ["RHF", "handleSubmit"] },
  { q: "When validation passes, the function you pass to handleSubmit receives:", opts: ["The raw DOM event only", "The validated form data object", "An array of refs", "Nothing"], a: 1, e: "On success, your valid handler is called with the collected, validated form values.", tags: ["RHF", "handleSubmit"] },
  { q: "handleSubmit accepts an optional second argument. What is it?", opts: ["A CSS class", "An onInvalid callback, called with the validation errors", "The API endpoint", "A list of field names"], a: 1, e: "handleSubmit(onValid, onInvalid) lets you handle the failure case; onInvalid receives the errors object.", tags: ["RHF", "handleSubmit"] },
  { q: "Where should you use handleSubmit?", opts: ["On the form element: <form onSubmit={handleSubmit(fn)}>", "Inside useEffect", "On every input's onChange", "In the component's return type"], a: 0, e: "Pass handleSubmit(fn) to the form's onSubmit so submission triggers validation then your handler.", tags: ["RHF", "handleSubmit"] },
  { q: "Does handleSubmit call event.preventDefault() for you?", opts: ["No, you must call it yourself", "Yes, it prevents the default full-page submit", "Only in production", "Only for GET forms"], a: 1, e: "handleSubmit calls preventDefault internally, so the browser won't do a native form submission/reload.", tags: ["RHF", "handleSubmit"] },
  { q: "If validation fails on submit, what happens?", opts: ["The valid handler still runs with partial data", "The valid handler is skipped and formState.errors is populated", "The page reloads", "The form is reset"], a: 1, e: "When validation fails, your valid callback does not run and the errors are written to formState.errors.", tags: ["RHF", "validation"] },
  { q: "How does handleSubmit handle an async submit function?", opts: ["It rejects async functions", "It awaits it, and formState.isSubmitting is true while it runs", "It runs it twice", "It ignores the returned promise"], a: 1, e: "handleSubmit supports async handlers and exposes formState.isSubmitting so you can disable the button while it awaits.", tags: ["RHF", "async"] },
  { q: "What is the return type of handleSubmit(onSubmit)?", opts: ["A string", "A function (an event handler)", "A boolean", "The form values"], a: 1, e: "It returns a function — the event handler — which you wire to the form's onSubmit.", tags: ["RHF", "handleSubmit"] },

  // Level 4 — formState & errors
  { q: "Where does React Hook Form expose validation errors?", opts: ["formState.errors", "form.problems", "errors() function", "useErrors()"], a: 0, e: "Validation errors live on formState.errors, keyed by field name.", tags: ["RHF", "errors"] },
  { q: "How do you read the message for the email field's error?", opts: ["errors.email.text", "formState.errors.email?.message", "errors('email')", "getError('email')"], a: 1, e: "Each error is an object; its human-readable text is at formState.errors.email?.message.", tags: ["RHF", "errors"] },
  { q: "What does formState.isValid represent?", opts: ["Whether the form has been submitted", "Whether the form currently passes all validation", "Whether the form is visible", "Whether inputs are focused"], a: 1, e: "isValid is true when the form has no validation errors (its accuracy depends on the validation mode).", tags: ["RHF", "formState"] },
  { q: "What does formState.isDirty tell you?", opts: ["That an input is focused", "That the current values differ from the defaultValues", "That validation failed", "That the form is loading"], a: 1, e: "isDirty is true once the user changes any value away from the provided defaultValues.", tags: ["RHF", "formState"] },
  { q: "Which formState flag is true while an async submit handler is running?", opts: ["isLoading", "isPending", "isSubmitting", "isBusy"], a: 2, e: "formState.isSubmitting is true during submission — handy for disabling the submit button.", tags: ["RHF", "formState"] },
  { q: "What does formState.touchedFields track?", opts: ["Fields that have been blurred/interacted with", "Fields with errors", "Hidden fields", "Fields with default values"], a: 0, e: "touchedFields records which fields the user has interacted with (typically blurred), useful for showing errors only after touch.", tags: ["RHF", "formState"] },
  { q: "Why should you destructure the fields you need from formState (e.g. const { errors } = formState)?", opts: ["It is required syntax", "formState is a Proxy; reading a property subscribes the component to that state so it updates", "It deletes unused state", "It disables validation"], a: 1, e: "formState is a proxy that tracks which properties you read, subscribing only to those — so destructure what you actually use.", tags: ["RHF", "formState"] },
  { q: "What is the shape of formState.errors?", opts: ["An array of strings", "An object keyed by field name, each value describing that field's error", "A single string", "A Map of refs"], a: 1, e: "errors is an object keyed by field path; each entry has properties like type and message.", tags: ["RHF", "errors"] },

  // Level 5 — Built-in validation rules
  { q: "Using RHF's built-in rules, how do you make a field required with a custom message?", opts: ["register('name', { required: 'Name is required' })", "register('name', 'required')", "register('name').required()", "required('name')"], a: 0, e: "Pass a rules object: register('name', { required: 'Name is required' }). A string both enables the rule and sets the message.", tags: ["RHF", "validation"] },
  { q: "How do you enforce a minimum length with a message using register?", opts: ["{ min: 3 }", "{ minLength: { value: 3, message: 'Too short' } }", "{ length: 3 }", "{ minimum: 3 }"], a: 1, e: "minLength takes an object with value and message: { minLength: { value: 3, message: 'Too short' } }.", tags: ["RHF", "validation"] },
  { q: "Which rule validates a value against a regular expression?", opts: ["regex", "pattern", "match", "test"], a: 1, e: "The pattern rule takes { value: /regex/, message }, e.g. to validate an email or phone format.", tags: ["RHF", "validation"] },
  { q: "For a number input, which rules constrain the numeric range?", opts: ["minLength and maxLength", "min and max", "low and high", "floor and ceil"], a: 1, e: "min and max constrain numeric values; minLength/maxLength constrain string length instead.", tags: ["RHF", "validation"] },
  { q: "What does register('age', { valueAsNumber: true }) do?", opts: ["Hides the field", "Coerces the input's string value to a number in the form data", "Makes the field required", "Formats it as currency"], a: 1, e: "Native inputs yield strings; valueAsNumber tells RHF to convert the value to a number before validation/submission.", tags: ["RHF", "valueAsNumber"] },
  { q: "How do you add a custom validation function with register?", opts: ["{ validate: (v) => v === 'ok' || 'Invalid' }", "{ check: (v) => true }", "{ custom: 'fn' }", "{ rule: () => false }"], a: 0, e: "The validate rule takes a function returning true (valid) or a string/false (invalid). Returning a string sets the error message.", tags: ["RHF", "validate"] },
  { q: "With register('x', { required: true }) vs { required: 'Required' }, the difference is:", opts: ["Only the string form actually validates", "The string form also supplies the error message shown to the user", "true is faster", "There is no difference"], a: 1, e: "Both enable the rule; passing a string additionally sets the message that appears in errors.x.message.", tags: ["RHF", "validation"] },
  { q: "Which rule limits the maximum number of characters allowed?", opts: ["max", "maxLength", "limit", "size"], a: 1, e: "maxLength caps string length (max caps numeric value).", tags: ["RHF", "validation"] },

  // Level 6 — Zod primitives & parse
  { q: "Which Zod schema validates a string?", opts: ["z.text()", "z.string()", "z.str()", "string()"], a: 1, e: "z.string() creates a schema that accepts string values.", tags: ["Zod", "primitives"] },
  { q: "What does schema.parse(value) do on valid input?", opts: ["Returns the parsed, typed value", "Returns true", "Logs to the console", "Mutates the input in place"], a: 0, e: "parse returns the validated value (typed) when input is valid.", tags: ["Zod", "parse"] },
  { q: "What happens when schema.parse(value) receives invalid input?", opts: ["It returns null", "It returns false", "It throws a ZodError", "It silently coerces the value"], a: 2, e: "parse throws a ZodError describing what failed; use safeParse if you'd rather not catch exceptions.", tags: ["Zod", "parse"] },
  { q: "Does z.number().parse('5') succeed?", opts: ["Yes, it coerces the string", "No, a string is not a number (unless you use coercion)", "Yes, all strings pass", "Only in production"], a: 1, e: "By default Zod does not coerce; '5' is a string, so it fails. Use z.coerce.number() to coerce.", tags: ["Zod", "number"] },
  { q: "Which schema validates a boolean?", opts: ["z.bool()", "z.boolean()", "z.flag()", "z.truthy()"], a: 1, e: "z.boolean() accepts true/false values.", tags: ["Zod", "primitives"] },
  { q: "After const r = z.string().parse(x), what is the static type of r?", opts: ["any", "unknown", "string", "never"], a: 2, e: "parse narrows the return type to the schema's output type — here, string.", tags: ["Zod", "types"] },
  { q: "What does z.literal('GET') validate?", opts: ["Any string", "Exactly the value 'GET'", "Any uppercase string", "A function named GET"], a: 1, e: "z.literal('GET') accepts only the exact value 'GET'.", tags: ["Zod", "literal"] },
  { q: "What does z.string().parse(123) do?", opts: ["Returns '123'", "Throws a ZodError (expected string, received number)", "Returns 123", "Returns undefined"], a: 1, e: "123 is a number, not a string, so parse throws a ZodError with a type message.", tags: ["Zod", "parse"] },

  // Level 7 — Zod objects & z.infer
  { q: "Which Zod schema describes an object shape?", opts: ["z.shape({...})", "z.object({...})", "z.record({...})", "z.struct({...})"], a: 1, e: "z.object({ key: schema, ... }) defines an object schema.", tags: ["Zod", "object"] },
  { q: "How do you get the TypeScript type for a Zod schema?", opts: ["type T = z.typeOf(schema)", "type T = z.infer<typeof schema>", "type T = schema.type", "type T = Infer(schema)"], a: 1, e: "z.infer<typeof schema> extracts the static type that the schema validates to.", tags: ["Zod", "infer"] },
  { q: "Why use z.infer instead of writing a separate interface?", opts: ["It runs faster at runtime", "It keeps the type and the validation in sync from one source of truth", "Interfaces are deprecated", "It enables CSS modules"], a: 1, e: "Deriving the type from the schema means changes to validation automatically update the type — no drift.", tags: ["Zod", "types"] },
  { q: "By default, what does a z.object() do with unknown extra keys during parse?", opts: ["Throws an error", "Strips them from the output", "Keeps them as-is", "Converts them to null"], a: 1, e: "By default Zod strips unrecognized keys. Use .passthrough() to keep them or .strict() to error.", tags: ["Zod", "object"] },
  { q: "What does calling .strict() on a z.object() do?", opts: ["Makes all fields required", "Throws if there are unknown/extra keys", "Freezes the object", "Disables type inference"], a: 1, e: ".strict() causes parsing to fail when the input contains keys not declared in the schema.", tags: ["Zod", "object"] },
  { q: "How do you model a nested object in Zod?", opts: ["Nest a z.object() as a field's schema", "Use z.nested()", "Use a dot in the key name", "It is not supported"], a: 0, e: "Just put another z.object({...}) as the value for a key, e.g. z.object({ address: z.object({ city: z.string() }) }).", tags: ["Zod", "object"] },
  { q: "How can you access an individual field's schema on a z.object()?", opts: ["schema.fields.city", "schema.shape.city", "schema.get('city')", "schema.city()"], a: 1, e: "schema.shape exposes the per-key schemas, e.g. schema.shape.city.", tags: ["Zod", "object"] },
  { q: "Given z.object({ name: z.string().optional() }), the inferred type is:", opts: ["{ name: string }", "{ name?: string }", "{ name: null }", "{ name: string | null }"], a: 1, e: ".optional() makes the key optional (string | undefined), inferred as { name?: string }.", tags: ["Zod", "optional"] },

  // Level 8 — safeParse & error handling
  { q: "What does schema.safeParse(value) return?", opts: ["The value or throws", "An object: { success: true, data } or { success: false, error }", "Always true", "A promise"], a: 1, e: "safeParse never throws; it returns a discriminated result you check via success.", tags: ["Zod", "safeParse"] },
  { q: "How do you correctly use the result of safeParse?", opts: ["Always read result.data", "if (result.success) use result.data else handle result.error", "Wrap it in try/catch", "Call result.parse()"], a: 1, e: "Check result.success first; data exists only on success, error only on failure.", tags: ["Zod", "safeParse"] },
  { q: "Where are the individual validation problems found on a ZodError?", opts: ["error.messages", "error.issues", "error.list", "error.problems"], a: 1, e: "A ZodError exposes error.issues — an array of issue objects.", tags: ["Zod", "errors"] },
  { q: "What does each issue's path property tell you?", opts: ["The file path of the schema", "The location (key path) of the field that failed", "The stack trace", "The URL of the request"], a: 1, e: "path is an array pointing to the offending field, e.g. ['address','city'].", tags: ["Zod", "errors"] },
  { q: "What does error.flatten() produce?", opts: ["A single string", "An object with fieldErrors and formErrors for easy display", "The original input", "A boolean"], a: 1, e: "flatten() returns { formErrors, fieldErrors } — a convenient shape for surfacing messages per field.", tags: ["Zod", "errors"] },
  { q: "When is safeParse preferable to parse?", opts: ["When you want to avoid try/catch and handle failure as a value", "When performance is critical", "When the schema is an object", "Never"], a: 0, e: "safeParse returns success/failure as data, so you can branch without exceptions.", tags: ["Zod", "safeParse"] },
  { q: "The main difference between parse and safeParse is:", opts: ["parse is async", "parse throws on failure; safeParse returns a result object", "safeParse coerces values", "There is no difference"], a: 1, e: "parse throws a ZodError on invalid input; safeParse returns { success, data | error }.", tags: ["Zod", "parse"] },
  { q: "ZodError is:", opts: ["A plain string", "A subclass of Error carrying an issues array", "A React component", "A number code"], a: 1, e: "ZodError extends Error and holds the structured issues describing every failure.", tags: ["Zod", "errors"] },

  // Level 9 — String/number refinements & coercion
  { q: "Which built-in Zod check validates an email string?", opts: ["z.string().isEmail()", "z.string().email()", "z.email().string()", "z.string().mail()"], a: 1, e: "z.string().email() validates that the string looks like an email address.", tags: ["Zod", "string"] },
  { q: "What does z.string().min(8) enforce?", opts: ["The number is at least 8", "The string has at least 8 characters", "There are at least 8 fields", "The array has 8 items"], a: 1, e: "On a string, .min(8) requires a minimum length of 8 characters.", tags: ["Zod", "string"] },
  { q: "What is the purpose of z.coerce.number()?", opts: ["To format numbers with commas", "To convert the input (e.g. the string '5') to a number before validating", "To round numbers", "To reject all numbers"], a: 1, e: "z.coerce.number() coerces the input via Number() first, which is handy because form inputs produce strings.", tags: ["Zod", "coerce"] },
  { q: "What is the difference between .optional() and .default(value)?", opts: ["They are identical", ".optional() allows undefined; .default(value) substitutes a value when input is undefined so output is always defined", ".default only works on numbers", ".optional() throws on undefined"], a: 1, e: ".optional() permits undefined; .default() provides a fallback, so the parsed output is never undefined.", tags: ["Zod", "optional", "default"] },
  { q: "How do you validate a string against a custom regular expression in Zod?", opts: ["z.string().pattern(/.../) ", "z.string().regex(/.../) ", "z.regex('...')", "z.string().match(/.../) "], a: 1, e: "z.string().regex(/.../) validates the string against the provided pattern.", tags: ["Zod", "string"] },
  { q: "Which chain validates a positive integer?", opts: ["z.number().int().positive()", "z.int().pos()", "z.number().whole().plus()", "z.positive().int()"], a: 0, e: "z.number().int().positive() requires an integer greater than zero.", tags: ["Zod", "number"] },
  { q: "What does .nullable() add to a schema?", opts: ["Allows the value to be null", "Allows the value to be undefined", "Makes it required", "Removes the value"], a: 0, e: ".nullable() accepts null in addition to the base type (T | null). Use .nullish() for null or undefined.", tags: ["Zod", "nullable"] },
  { q: "Which validates that a number is at most 100?", opts: ["z.number().max(100)", "z.number().maxLength(100)", "z.number().lte(100).gte(100)", "z.number().limit(100)"], a: 0, e: "On numbers, .max(100) (or .lte(100)) enforces an upper bound of 100.", tags: ["Zod", "number"] },

  // Level 10 — Connecting Zod to RHF via zodResolver
  { q: "Where is zodResolver imported from?", opts: ["'zod'", "'react-hook-form'", "'@hookform/resolvers/zod'", "'@zod/resolver'"], a: 2, e: "zodResolver lives in the resolvers package: import { zodResolver } from '@hookform/resolvers/zod'.", tags: ["RHF", "Zod", "zodResolver"] },
  { q: "How do you wire a Zod schema into useForm?", opts: ["useForm({ schema })", "useForm({ resolver: zodResolver(schema) })", "useForm({ validate: schema })", "useForm(zodResolver)"], a: 1, e: "Pass resolver: zodResolver(schema) to useForm so RHF delegates validation to Zod.", tags: ["RHF", "Zod", "zodResolver"] },
  { q: "When using zodResolver, where do Zod's validation messages appear?", opts: ["In the console only", "In formState.errors[field].message", "In a separate zodErrors object", "They are discarded"], a: 1, e: "zodResolver maps Zod issues into RHF's formState.errors, so messages show up at errors[field].message.", tags: ["RHF", "Zod", "errors"] },
  { q: "How do you type the form values from the schema?", opts: ["useForm<any>()", "useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema) })", "useForm<schema>()", "useForm<FormData>()"], a: 1, e: "Parameterize useForm with z.infer<typeof schema> so register names and values are fully typed.", tags: ["RHF", "Zod", "types"] },
  { q: "A benefit of zodResolver over per-field register rules is:", opts: ["It removes the need for inputs", "Validation logic lives in one schema (reusable, e.g. on the server) instead of scattered across register calls", "It makes the form controlled", "It disables TypeScript"], a: 1, e: "Centralizing validation in a Zod schema is DRY and lets you reuse the same schema elsewhere (like API handlers).", tags: ["RHF", "Zod", "why"] },
  { q: "Which package must be installed to use zodResolver?", opts: ["@hookform/resolvers", "rhf-zod", "zod-form-resolver", "@react-hook-form/zod"], a: 0, e: "zodResolver is part of @hookform/resolvers (alongside resolvers for Yup, Joi, etc.).", tags: ["RHF", "Zod", "setup"] },
  { q: "When using zodResolver, the per-field rules object in register is:", opts: ["Still required for every field", "Generally unnecessary because the schema handles validation", "Used for styling", "Used to set defaultValues"], a: 1, e: "With a resolver, validation comes from the schema, so you typically call register('name') without a rules object.", tags: ["RHF", "Zod", "register"] },
  { q: "Why is z.coerce.number() (or valueAsNumber) commonly needed with form inputs?", opts: ["Because Zod cannot validate numbers", "Because native inputs produce strings, so the value must be coerced to a number", "Because numbers are forbidden in forms", "Because RHF stores everything as booleans"], a: 1, e: "HTML inputs yield strings even for type='number', so coercion converts '42' to 42 before Zod's number checks.", tags: ["RHF", "Zod", "coerce"] },

  // Level 11 — Controller & controlled components
  { q: "Why does React Hook Form provide the Controller component?", opts: ["To style inputs", "To integrate controlled components (e.g. MUI, react-select) that don't expose a ref like native inputs", "To make network requests", "To replace useForm"], a: 1, e: "Controller bridges RHF with controlled third-party inputs that manage their own value/onChange rather than a DOM ref.", tags: ["RHF", "Controller"] },
  { q: "Which props does Controller require?", opts: ["name, control and render", "value and onChange", "schema and resolver", "id and type"], a: 0, e: "Controller needs name, the control object from useForm, and a render function.", tags: ["RHF", "Controller"] },
  { q: "What does the field object passed to Controller's render include?", opts: ["onChange, onBlur, value, ref and name", "errors and isValid", "schema and resolver", "dispatch and state"], a: 0, e: "render={({ field }) => ...} gives you field.onChange/onBlur/value/ref/name to spread onto the controlled input.", tags: ["RHF", "Controller"] },
  { q: "What is useController?", opts: ["A router hook", "The hook form of Controller for building custom controlled inputs", "A Zod helper", "A replacement for useState"], a: 1, e: "useController is the hook equivalent of Controller, useful when authoring a reusable controlled field component.", tags: ["RHF", "useController"] },
  { q: "Where does the control object passed to Controller come from?", opts: ["From useState", "From useForm()", "From the schema", "From React context only"], a: 1, e: "useForm() returns control, which you pass to Controller (or useController).", tags: ["RHF", "control"] },
  { q: "What typically happens if you use a controlled UI library input with plain register instead of Controller?", opts: ["It works perfectly", "RHF may not track its value correctly because the component doesn't forward a ref/onChange the way register expects", "It becomes uncontrolled automatically", "TypeScript refuses to compile"], a: 1, e: "Controlled components often don't expose the native ref/onChange register relies on, so Controller is the reliable bridge.", tags: ["RHF", "Controller"] },
  { q: "What does the fieldState argument in Controller's render provide?", opts: ["The whole form's values", "Per-field state like error, invalid and isDirty", "The resolver", "The submit handler"], a: 1, e: "render={({ field, fieldState }) => ...} exposes fieldState.error and flags for that specific field.", tags: ["RHF", "Controller"] },
  { q: "How is a Controller-managed field's initial value typically provided?", opts: ["Only via setValue after mount", "From useForm's defaultValues (or Controller's defaultValue prop)", "It cannot have an initial value", "From localStorage automatically"], a: 1, e: "Provide initial values through defaultValues in useForm (recommended) or the Controller defaultValue prop.", tags: ["RHF", "Controller", "defaultValues"] },

  // Level 12 — watch, getValues, setValue, reset, trigger
  { q: "What does watch('email') do?", opts: ["Reads the value once with no subscription", "Subscribes to the field and re-renders the component when it changes", "Validates the field", "Deletes the field"], a: 1, e: "watch subscribes to a field (or the whole form) and re-renders when its value updates.", tags: ["RHF", "watch"] },
  { q: "How does getValues() differ from watch()?", opts: ["getValues is async", "getValues reads current values without subscribing or causing a re-render", "getValues validates first", "They are identical"], a: 1, e: "getValues returns a snapshot without subscribing, so it doesn't trigger re-renders like watch does.", tags: ["RHF", "getValues"] },
  { q: "How do you programmatically set a field's value and validate it?", opts: ["setValue('age', 30, { shouldValidate: true })", "setState('age', 30)", "update('age', 30)", "field.age = 30"], a: 0, e: "setValue updates a field; pass { shouldValidate: true } to re-run validation (and shouldDirty to mark it dirty).", tags: ["RHF", "setValue"] },
  { q: 'What does reset(values) do in React Hook Form?', opts: ['Clears field values but leaves errors and dirty state untouched', 'Resets fields, errors and dirty state, optionally to the provided values', 'Only changes defaultValues without touching current field values', 'Re-runs validation on all fields without changing values'], a: 1, e: 'reset restores the form to a clean state (optionally to new values) and updates the baseline used for isDirty.', tags: ["RHF", "reset"] },
  { q: "What does trigger('email') do?", opts: ["Submits only that field", "Manually runs validation for that field (or fields)", "Focuses the field", "Removes the field"], a: 1, e: "trigger imperatively runs validation, useful for validating a step before moving on in a wizard.", tags: ["RHF", "trigger"] },
  { q: "If you only need a value at submit time and don't want extra re-renders, you should use:", opts: ["watch", "getValues", "useState", "a ref to the form element"], a: 1, e: "getValues reads on demand without subscribing, avoiding the re-renders watch would cause.", tags: ["RHF", "getValues", "performance"] },
  { q: "After calling reset() with no arguments, the form returns to:", opts: ["Empty strings always", "Its defaultValues", "The last submitted values", "Random values"], a: 1, e: "With no argument, reset restores the form to its configured defaultValues.", tags: ["RHF", "reset"] },
  { q: "Which option makes setValue mark the field as dirty?", opts: ["{ shouldDirty: true }", "{ dirty: true }", "{ touch: true }", "{ markDirty: true }"], a: 0, e: "setValue('x', v, { shouldDirty: true }) flags the field (and form) as dirty.", tags: ["RHF", "setValue"] },

  // Level 13 — useFieldArray (dynamic fields)
  { q: "What is useFieldArray used for?", opts: ["Validating arrays in Zod", "Managing a dynamic list of fields (add/remove/reorder)", "Fetching arrays from an API", "Sorting the DOM"], a: 1, e: "useFieldArray manages dynamic, repeatable groups of fields like a list of phone numbers.", tags: ["RHF", "useFieldArray"] },
  { q: "Which values does useFieldArray return?", opts: ["{ fields, append, remove, ... }", "{ value, setValue }", "{ data, error }", "{ register, handleSubmit }"], a: 0, e: "It returns fields plus helpers like append, prepend, remove, insert, move and swap.", tags: ["RHF", "useFieldArray"] },
  { q: "When rendering a field array, what should you use as the React key?", opts: ["The array index", "field.id (the stable id RHF generates)", "Math.random()", "The field's value"], a: 1, e: "Use field.id, not the index, so React preserves component identity as items are added/removed/reordered.", tags: ["RHF", "useFieldArray", "keys"] },
  { q: "How do you add a new item to a field array?", opts: ["push(obj)", "append(obj)", "add(obj)", "insertEnd(obj)"], a: 1, e: "append(obj) adds a new entry (use prepend/insert for other positions).", tags: ["RHF", "useFieldArray"] },
  { q: "How do you remove the item at index 2 from a field array?", opts: ["remove(2)", "delete(2)", "pop(2)", "splice(2)"], a: 0, e: "remove(index) drops the entry at that index; calling remove() with no arg clears all.", tags: ["RHF", "useFieldArray"] },
  { q: "What must you pass to useFieldArray?", opts: ["Only a name", "control and the field array's name", "The resolver", "A ref"], a: 1, e: "useFieldArray needs { control, name } so it can manage that array within the form.", tags: ["RHF", "useFieldArray"] },
  { q: "The fields array returned by useFieldArray is:", opts: ["The raw input values", "An array of objects each with a stable id for rendering", "A single object", "Always empty until submit"], a: 1, e: "fields is a mapped array (each item carries an id) that you iterate to render the rows.", tags: ["RHF", "useFieldArray"] },
  { q: "How do you provide the initial items for a field array?", opts: ["Via defaultValues in useForm (e.g. { phones: [{ number: '' }] })", "You cannot", "Via CSS", "Via the URL"], a: 0, e: "Seed the array through useForm's defaultValues so the initial rows render.", tags: ["RHF", "useFieldArray", "defaultValues"] },

  // Level 14 — Zod advanced (refine, unions, transform)
  { q: "What is .refine() used for in Zod?", opts: ["To rename keys", "To add custom validation logic beyond the built-in checks", "To remove fields", "To format output"], a: 1, e: ".refine(fn, { message, path }) adds a custom predicate, e.g. ensuring a value passes a bespoke rule.", tags: ["Zod", "refine"] },
  { q: "How do you validate that two fields match (e.g. password and confirmPassword)?", opts: ["Use .email()", "Use .refine on the object and set path to the field to attach the error", "Use z.literal", "Use two separate parse calls"], a: 1, e: "Call .refine on the object schema comparing the two fields, and set { path: ['confirmPassword'] } so the error attaches there.", tags: ["Zod", "refine", "cross-field"] },
  { q: "When would you reach for .superRefine() instead of .refine()?", opts: ["Never; they are identical", "When you need to add multiple issues or conditional issues via ctx.addIssue", "Only for strings", "To improve performance"], a: 1, e: "superRefine((val, ctx) => ...) gives access to ctx.addIssue, letting you emit several context-dependent errors.", tags: ["Zod", "superRefine"] },
  { q: "What does z.enum(['light', 'dark']) create?", opts: ["A number range", "A schema accepting only 'light' or 'dark', with type inference", "A random value", "An array of any strings"], a: 1, e: "z.enum lists allowed string literals; it validates membership and infers the union type 'light' | 'dark'.", tags: ["Zod", "enum"] },
  { q: "What is z.discriminatedUnion('type', [...]) good for?", opts: ["Merging objects", "Efficiently validating a tagged union by switching on a shared discriminant key", "Sorting arrays", "Coercing numbers"], a: 1, e: "It validates one of several object schemas chosen by a common literal key (the discriminant), with clearer errors and better performance than a plain union.", tags: ["Zod", "discriminatedUnion"] },
  { q: "What does .transform() do to a schema?", opts: ["Validates without changing the value", "Transforms the parsed value (and changes the output type) after validation", "Deletes the value", "Coerces the input before validation"], a: 1, e: ".transform(fn) maps the validated value to a new value/type, e.g. converting a string to a Date.", tags: ["Zod", "transform"] },
  { q: "Which creates a schema accepting either a string or a number?", opts: ["z.either(z.string(), z.number())", "z.union([z.string(), z.number()]) (or z.string().or(z.number()))", "z.string().and(z.number())", "z.mix(z.string(), z.number())"], a: 1, e: "z.union([...]) (or the .or() helper) accepts any one of the provided schemas.", tags: ["Zod", "union"] },
  { q: "What does z.preprocess(fn, schema) do?", opts: ["Runs after validation", "Runs fn on the raw input first, then validates the result with the schema", "Disables validation", "Caches the schema"], a: 1, e: "z.preprocess transforms the input before validation — handy for trimming or coercing values prior to checks.", tags: ["Zod", "preprocess"] },

  // Level 15 — Mastery: integration, performance, gotchas
  { q: "What is React Hook Form's main performance advantage over a fully controlled form?", opts: ["It avoids JavaScript", "Uncontrolled inputs and scoped subscriptions mean far fewer re-renders as the user types", "It renders on the GPU", "It disables validation"], a: 1, e: "Because RHF tracks inputs via refs and isolated subscriptions, typing doesn't re-render the whole form like controlled state would.", tags: ["RHF", "performance"] },
  { q: "What does the mode option in useForm control?", opts: ["The color theme", "When validation is triggered (onSubmit, onBlur, onChange, onTouched, all)", "The HTTP method", "The number of fields"], a: 1, e: "mode sets the validation strategy before the first submit; e.g. mode: 'onBlur' validates when a field loses focus.", tags: ["RHF", "mode"] },
  { q: "What does reValidateMode govern?", opts: ["When fields re-validate after the first validation/error (default onChange)", "How often the page reloads", "The reset behavior", "The submit URL"], a: 0, e: "After a field has errored once, reValidateMode (default 'onChange') decides when it is checked again.", tags: ["RHF", "reValidateMode"] },
  { q: "Why are defaultValues especially important in RHF?", opts: ["They are optional and never matter", "They establish initial values and the baseline for reset/isDirty, and are needed for controlled inputs and field arrays", "They set the page title", "They control routing"], a: 1, e: "defaultValues seed the form, anchor reset() and isDirty comparisons, and ensure controlled inputs/field arrays start correctly.", tags: ["RHF", "defaultValues"] },
  { q: "A major benefit of defining your form's Zod schema once is that you can:", opts: ["Only use it on the client", "Reuse the same schema to validate the API request on the server (DRY + defense in depth)", "Avoid writing any components", "Skip TypeScript entirely"], a: 1, e: "The same schema can validate the form in the browser and the payload on the server, keeping rules consistent and inputs trusted.", tags: ["Zod", "integration"] },
  { q: "A common gotcha when collecting a numeric value from an <input type='number'> is:", opts: ["The value arrives as a string, so use register valueAsNumber or z.coerce.number()", "Numbers are blocked by RHF", "It always submits as NaN", "You must use a Controller"], a: 0, e: "Inputs yield strings; without valueAsNumber or coercion, your 'number' field is actually a string at validation time.", tags: ["RHF", "Zod", "gotcha"] },
  { q: "How is formState.isSubmitting typically used in the UI?", opts: ["To hide the form", "To disable the submit button and show a spinner while an async submit runs", "To validate fields", "To reset the form"], a: 1, e: "Disable the submit button when isSubmitting is true to prevent double submissions during async work.", tags: ["RHF", "formState", "ux"] },
  { q: "Which statement best captures the RHF + Zod division of responsibilities?", opts: ["Zod renders inputs; RHF validates", "RHF manages form state, registration and submission; Zod declares the schema for validation and types, connected via zodResolver", "They both manage routing", "RHF stores data in a database"], a: 1, e: "RHF owns form state/submission; Zod owns validation/types; zodResolver wires them together — a clean separation of concerns.", tags: ["RHF", "Zod", "summary"] },
];
