// Data Structures & Algorithms roadmap questions (120): 15 levels × 8, easiest →
// hardest. Authored as a single 8-per-level list and built directly (like the
// other 15-level topics). See lib/roadmap.ts for the level titles.

import type { Seed } from './roadmap-build';

export const dsaSeeds: Seed[] = [
  // ── Level 1 — Complexity Basics ────────────────────────────────────────
  { q: 'What does an algorithm’s "time complexity" describe?', opts: ['Its memory use', 'How its running time grows as input grows', 'Its line count', 'Its CPU temperature'], a: 1, e: 'Time complexity describes how the number of operations grows as a function of input size n.', tags: ['DSA', 'Complexity'] },
  { q: 'What does "space complexity" measure?', opts: ['How long an algorithm runs', 'How much extra memory an algorithm uses as input grows', 'The number of functions', 'The size of the source file'], a: 1, e: 'Space complexity measures the additional memory an algorithm needs relative to the input size n.', tags: ['DSA', 'Complexity'] },
  { q: 'When analyzing complexity, what does the variable n usually represent?', opts: ['The answer', 'The number of CPUs', 'The recursion depth limit', 'The size of the input'], a: 3, e: 'By convention n is the size of the input, such as the number of elements in an array.', tags: ['DSA', 'Complexity'] },
  { q: 'A data structure is best described as:', opts: ['A way to organize and store data for efficient access', 'A programming language', 'A type of CPU', 'A network protocol'], a: 0, e: 'A data structure is a way of organizing and storing data so that operations on it can be done efficiently.', tags: ['DSA', 'Complexity'] },
  { q: 'Why do we usually analyze the "worst case" of an algorithm?', opts: ['It is always the fastest', 'It gives an upper bound that is guaranteed to hold', 'It ignores the input', 'It is the only case that exists'], a: 1, e: 'Worst-case analysis gives a guaranteed upper bound on running time regardless of the specific input.', tags: ['DSA', 'Complexity'] },
  { q: 'If algorithm A does fewer operations than algorithm B for every input size, A is generally:', opts: ['Less efficient', 'More efficient', 'Identical to B', 'Impossible to compare'], a: 1, e: 'Doing fewer operations for the same work means A is more efficient than B.', tags: ['DSA', 'Complexity'] },
  { q: 'Which usually grows faster as n increases?', opts: ['A constant number of steps', 'Neither grows', 'A number of steps proportional to n', 'Always the same'], a: 2, e: 'A constant amount of work does not grow with n, while work proportional to n increases as n grows.', tags: ['DSA', 'Complexity'] },
  { q: 'An algorithm whose running time does not change as the input grows is said to run in:', opts: ['Constant time', 'Linear time', 'Quadratic time', 'Exponential time'], a: 0, e: 'Constant time means the running time stays the same regardless of input size n.', tags: ['DSA', 'Complexity'] },

  // ── Level 2 — Big-O Notation ───────────────────────────────────────────
  { q: 'What does Big-O notation express?', opts: ['Exact runtime in seconds', 'The best case only', 'An upper bound on how an algorithm scales', 'The memory address'], a: 2, e: 'Big-O describes an asymptotic upper bound on the growth rate of an algorithm as input size increases.', tags: ['DSA', 'Big-O'] },
  { q: 'Which Big-O describes constant time?', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 0, e: 'O(1) means the running time is constant and does not depend on the input size n.', tags: ['DSA', 'Big-O'] },
  { q: 'Which Big-O describes linear time?', opts: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], a: 2, e: 'O(n) means the running time grows in direct proportion to the input size n.', tags: ['DSA', 'Big-O'] },
  { q: 'In Big-O, what is O(2n + 5) simplified to?', opts: ['O(2n)', 'O(5)', 'O(2n + 5)', 'O(n)'], a: 3, e: 'Big-O drops constant factors and lower-order terms, so O(2n + 5) simplifies to O(n).', tags: ['DSA', 'Big-O'] },
  { q: 'Which of these growth rates is the fastest growing (worst) for large n?', opts: ['O(log n)', 'O(n)', 'O(n log n)', 'O(n²)'], a: 3, e: 'For large n, O(n²) grows faster than O(n log n), O(n), and O(log n).', tags: ['DSA', 'Big-O'] },
  { q: 'Order these from slowest to fastest growth: O(n), O(1), O(n²), O(log n).', opts: ['O(n²), O(n), O(log n), O(1)', 'O(1), O(log n), O(n), O(n²)', 'O(1), O(n), O(log n), O(n²)', 'O(log n), O(1), O(n), O(n²)'], a: 1, e: 'From slowest-growing to fastest-growing: O(1) < O(log n) < O(n) < O(n²).', tags: ['DSA', 'Big-O'] },
  { q: 'A loop that runs n times, nested inside another loop that runs n times, is typically:', opts: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], a: 2, e: 'Two nested loops each running n times perform about n × n = n² operations, so O(n²).', tags: ['DSA', 'Big-O'] },
  { q: 'When we add two sequential steps that are O(n) and O(n²), the overall complexity is:', opts: ['O(n)', 'O(n³)', 'O(n²)', 'O(2n²)'], a: 2, e: 'Big-O keeps only the dominant term, so O(n) + O(n²) simplifies to O(n²).', tags: ['DSA', 'Big-O'] },

  // ── Level 3 — Arrays ───────────────────────────────────────────────────
  { q: 'What is the time complexity of accessing an array element by its index?', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 0, e: 'Arrays store elements contiguously, so accessing any index is a direct O(1) lookup.', tags: ['DSA', 'Arrays'] },
  { q: 'In a zero-indexed array, what is the index of the first element?', opts: ['1', '0', '-1', 'The array length'], a: 1, e: 'Most languages use zero-based indexing, so the first element is at index 0.', tags: ['DSA', 'Arrays'] },
  { q: 'What does this print?\n\n```js\nconst a = [10, 20, 30];\nconsole.log(a[2]);\n```', opts: ['10', '20', '30', 'undefined'], a: 2, e: 'Index 2 refers to the third element, which is 30.', tags: ['DSA', 'Arrays'] },
  { q: 'Searching for a value in an unsorted array (linear search) is, in the worst case:', opts: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], a: 2, e: 'Without ordering you may have to check every element, so a linear search is O(n) in the worst case.', tags: ['DSA', 'Arrays'] },
  { q: 'Why is inserting an element at the beginning of an array O(n)?', opts: ['Arrays cannot be modified', 'Every following element must shift over by one', 'It must re-sort the array', 'It always reallocates memory'], a: 1, e: 'Inserting at the front requires shifting all subsequent elements by one position, which is O(n).', tags: ['DSA', 'Arrays'] },
  { q: 'What does this leave in `a`?\n\n```js\nconst a = [1, 2, 3];\na.push(4);\n```', opts: ['[1, 2, 3]', '[4, 1, 2, 3]', '[1, 2, 3, 4]', '[1, 2, 4]'], a: 2, e: 'Array push appends an element to the end, giving [1, 2, 3, 4].', tags: ['DSA', 'Arrays'] },
  { q: 'A key property of arrays compared with linked lists is that arrays:', opts: ['Cannot be indexed', 'Always use more memory per element', 'Cannot hold numbers', 'Store elements in contiguous memory'], a: 3, e: 'Arrays store their elements in contiguous memory, which is what enables O(1) index access.', tags: ['DSA', 'Arrays'] },
  { q: 'What does removing the last element of an array (pop) typically cost?', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 0, e: 'Removing the final element requires no shifting, so it is an O(1) operation.', tags: ['DSA', 'Arrays'] },

  // ── Level 4 — Strings ──────────────────────────────────────────────────
  { q: 'A string is most commonly modeled as:', opts: ['A sequence of characters', 'A single number', 'A hash map', 'A binary tree'], a: 0, e: 'A string is an ordered sequence of characters, often stored much like an array.', tags: ['DSA', 'Strings'] },
  { q: 'What does this print?\n\n```js\nconsole.log("hello".length);\n```', opts: ['4', '5', '6', 'undefined'], a: 1, e: 'The string "hello" has five characters, so its length is 5.', tags: ['DSA', 'Strings'] },
  { q: 'What does this print?\n\n```js\nconsole.log("cat".charAt(0));\n```', opts: ['"c"', '"a"', '"t"', '""'], a: 0, e: 'charAt(0) returns the character at index 0, which is "c".', tags: ['DSA', 'Strings'] },
  { q: 'In many languages, strings are immutable. This means:', opts: ['They cannot be read', 'They cannot be compared', 'Their characters cannot be changed in place', 'They have no length'], a: 2, e: 'Immutable strings cannot be modified in place; operations that "change" them create new strings.', tags: ['DSA', 'Strings'] },
  { q: 'A palindrome is a string that:', opts: ['Has all unique characters', 'Reads the same forwards and backwards', 'Is sorted alphabetically', 'Contains only vowels'], a: 1, e: 'A palindrome reads identically in both directions, such as "racecar".', tags: ['DSA', 'Strings'] },
  { q: 'What does this print?\n\n```js\nconsole.log("ab" + "cd");\n```', opts: ['"abcd"', '"ab cd"', '"cdab"', '"abc"'], a: 0, e: 'The + operator concatenates the two strings into "abcd".', tags: ['DSA', 'Strings'] },
  { q: 'Comparing two strings of length n character-by-character is, in the worst case:', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 1, e: 'You may need to compare up to all n characters, so the comparison is O(n).', tags: ['DSA', 'Strings'] },
  { q: 'An anagram of a word is formed by:', opts: ['Reversing the word', 'Removing its vowels', 'Doubling each letter', 'Rearranging its letters'], a: 3, e: 'An anagram uses exactly the same letters rearranged into a different order, like "listen" and "silent".', tags: ['DSA', 'Strings'] },

  // ── Level 5 — Hash Tables ──────────────────────────────────────────────
  { q: 'What is the average-case time to look up a value by key in a hash table?', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 0, e: 'A hash table computes the bucket from the key, giving average-case O(1) lookups.', tags: ['DSA', 'Hash Tables'] },
  { q: 'What is the role of a hash function in a hash table?', opts: ['To sort the keys', 'To encrypt the data', 'To map a key to an index/bucket', 'To count the elements'], a: 2, e: 'A hash function converts a key into an index that determines where the value is stored.', tags: ['DSA', 'Hash Tables'] },
  { q: 'A "collision" in a hash table occurs when:', opts: ['Two keys hash to the same bucket', 'The table is empty', 'A key is deleted', 'The hash function is fast'], a: 0, e: 'A collision happens when two different keys map to the same bucket index.', tags: ['DSA', 'Hash Tables'] },
  { q: 'Which is a common technique for handling collisions?', opts: ['Binary search', 'Recursion', 'Sorting the table', 'Chaining (linked lists in buckets)'], a: 3, e: 'Separate chaining stores colliding entries in a list at the same bucket; open addressing is another approach.', tags: ['DSA', 'Hash Tables'] },
  { q: 'In the worst case (many collisions), a hash table lookup can degrade to:', opts: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], a: 2, e: 'If all keys collide into one bucket, a lookup may scan all n entries, degrading to O(n).', tags: ['DSA', 'Hash Tables'] },
  { q: 'In JavaScript, a Map or plain object is most often used to provide:', opts: ['Sorted iteration', 'Key-value lookups in average O(1)', 'Binary tree balancing', 'Constant memory'], a: 1, e: 'JavaScript objects and Maps act as hash tables, giving average O(1) key-value access.', tags: ['DSA', 'Hash Tables'] },
  { q: 'What property must a value have to work as a hash table key?', opts: ['It must be kept in sorted order', 'It must map to a consistent hash value', 'It must be an integer', 'It must be unique across all programs'], a: 1, e: 'The hash function must produce the same hash for the same key every time, so lookups land in the right bucket.', tags: ['DSA', 'Hash Tables'] },
  { q: 'A hash table (hash set) is an excellent choice when you need to:', opts: ['Keep elements sorted', 'Test membership quickly', 'Always use minimal memory', 'Access elements by numeric index'], a: 1, e: 'Hash sets give average O(1) membership checks, making them ideal for fast lookups of seen values.', tags: ['DSA', 'Hash Tables'] },

  // ── Level 6 — Stacks ───────────────────────────────────────────────────
  { q: 'A stack follows which ordering principle?', opts: ['FIFO (first in, first out)', 'Sorted order', 'LIFO (last in, first out)', 'Random order'], a: 2, e: 'A stack is LIFO: the most recently pushed element is the first one popped.', tags: ['DSA', 'Stacks'] },
  { q: 'What are the two primary stack operations called?', opts: ['enqueue and dequeue', 'push and pop', 'insert and delete', 'add and remove-min'], a: 1, e: 'Push adds an element to the top of the stack and pop removes the top element.', tags: ['DSA', 'Stacks'] },
  { q: 'What is the time complexity of push and pop on a stack?', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 0, e: 'Push and pop operate only at the top of the stack, so both are O(1).', tags: ['DSA', 'Stacks'] },
  { q: 'After these operations, what does pop() return?\n\n```js\nstack.push(1);\nstack.push(2);\nstack.push(3);\nstack.pop();\n```', opts: ['1', '2', '3', 'undefined'], a: 2, e: 'A stack is LIFO, so pop removes and returns the most recently pushed value, 3.', tags: ['DSA', 'Stacks'] },
  { q: 'Which problem is naturally solved using a stack?', opts: ['Scheduling print jobs in order', 'Finding the shortest path', 'Sorting numbers', 'Matching balanced parentheses'], a: 3, e: 'Checking balanced parentheses uses a stack to match each closing bracket with the most recent opening one.', tags: ['DSA', 'Stacks'] },
  { q: 'The call stack used for function calls behaves like:', opts: ['A queue', 'A stack', 'A hash table', 'A binary tree'], a: 1, e: 'Function calls push frames and returns pop them in LIFO order, exactly like a stack.', tags: ['DSA', 'Stacks'] },
  { q: 'Looking at the top of a stack without removing it is usually called:', opts: ['pop', 'peek', 'poll', 'shift'], a: 1, e: 'Peek (or top) returns the top element without removing it from the stack.', tags: ['DSA', 'Stacks'] },
  { q: 'Which everyday feature is commonly implemented with a stack?', opts: ['Undo functionality in an editor', 'Autocomplete suggestions', 'Spell checking', 'Load balancing'], a: 0, e: 'Undo uses a stack: the last action performed is the first one undone (LIFO).', tags: ['DSA', 'Stacks'] },

  // ── Level 7 — Queues ───────────────────────────────────────────────────
  { q: 'A queue follows which ordering principle?', opts: ['LIFO (last in, first out)', 'Sorted order', 'FIFO (first in, first out)', 'Random order'], a: 2, e: 'A queue is FIFO: the first element added is the first one removed.', tags: ['DSA', 'Queues'] },
  { q: 'What are the two primary queue operations commonly called?', opts: ['push and pop', 'enqueue and dequeue', 'peek and poke', 'insert and find'], a: 1, e: 'Enqueue adds to the back of the queue and dequeue removes from the front.', tags: ['DSA', 'Queues'] },
  { q: 'For a well-implemented queue, enqueue and dequeue are each:', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 0, e: 'Adding to the back and removing from the front are both O(1) in a proper queue implementation.', tags: ['DSA', 'Queues'] },
  { q: 'After these operations, what does dequeue() return?\n\n```js\nqueue.enqueue("a");\nqueue.enqueue("b");\nqueue.enqueue("c");\nqueue.dequeue();\n```', opts: ['"a"', '"b"', '"c"', 'undefined'], a: 0, e: 'A queue is FIFO, so dequeue removes the earliest-added element, "a".', tags: ['DSA', 'Queues'] },
  { q: 'Which graph traversal uses a queue to visit nodes level by level?', opts: ['Depth-first search', 'Binary search', 'Quicksort', 'Breadth-first search'], a: 3, e: 'Breadth-first search (BFS) uses a queue to explore neighbors level by level.', tags: ['DSA', 'Queues'] },
  { q: 'A double-ended queue (deque) allows:', opts: ['Insertion only at the back', 'Access only by index', 'Insertion and removal at both ends', 'Sorting on insertion'], a: 2, e: 'A deque supports adding and removing elements from both the front and the back.', tags: ['DSA', 'Queues'] },
  { q: 'Which scenario maps naturally to a queue?', opts: ['Evaluating nested parentheses', 'Processing tasks in arrival order', 'Reversing a string', 'Implementing recursion', ], a: 1, e: 'Processing jobs in the order they arrive is FIFO behavior, which a queue models directly.', tags: ['DSA', 'Queues'] },
  { q: 'In a circular queue, the main advantage over a naive array queue is:', opts: ['It allows duplicate values', 'It reuses freed front slots, avoiding shifting', 'It keeps elements sorted', 'It removes the need for a back pointer'], a: 1, e: 'A circular queue wraps indices around so freed front space is reused without shifting elements.', tags: ['DSA', 'Queues'] },

  // ── Level 8 — Linked Lists ─────────────────────────────────────────────
  { q: 'What is the time complexity of accessing the k-th element of a singly linked list by position?', opts: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], a: 2, e: 'Linked lists lack index access, so you must walk from the head, making positional access O(n).', tags: ['DSA', 'Linked Lists'] },
  { q: 'Each node in a singly linked list typically stores:', opts: ['Only a value', 'A value and an index', 'A value and a reference to the next node', 'Two values'], a: 2, e: 'A singly linked list node holds its value plus a pointer to the next node in the list.', tags: ['DSA', 'Linked Lists'] },
  { q: 'Inserting a node at the head of a linked list (given the head) is:', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 0, e: 'Inserting at the head only updates a couple of pointers, so it is O(1).', tags: ['DSA', 'Linked Lists'] },
  { q: 'A doubly linked list differs from a singly linked list because each node also stores:', opts: ['Its index', 'A hash of its value', 'The list length', 'A reference to the previous node'], a: 3, e: 'Doubly linked list nodes keep both next and previous pointers, allowing traversal in both directions.', tags: ['DSA', 'Linked Lists'] },
  { q: 'A key advantage of linked lists over arrays is:', opts: ['O(1) random access by index', 'Less memory per element', 'Efficient insertion/deletion without shifting elements', 'Built-in sorting'], a: 2, e: 'Linked lists can insert or delete by relinking pointers, avoiding the element shifting arrays require.', tags: ['DSA', 'Linked Lists'] },
  { q: 'What special value typically marks the end of a singly linked list?', opts: ['The head', 'A null (or None) next pointer', 'A zero value', 'A loop back to the head'], a: 1, e: 'The final node points to null/None, signaling the end of the list.', tags: ['DSA', 'Linked Lists'] },
  { q: 'A common technique to detect a cycle in a linked list uses:', opts: ['Two pointers moving at different speeds', 'Binary search', 'A hash function', 'Sorting the nodes'], a: 0, e: 'Floyd’s fast/slow two-pointer method detects a cycle when the pointers meet.', tags: ['DSA', 'Linked Lists'] },
  { q: 'To delete a node given only a pointer to it (not its predecessor) in a singly linked list, a common trick is to:', opts: ['Reverse the list', 'Copy the next node’s value into it and skip the next node', 'Sort the list', 'Set the head to null'], a: 1, e: 'You overwrite the current node with the next node’s data and bypass the next node, effectively deleting it.', tags: ['DSA', 'Linked Lists'] },

  // ── Level 9 — Recursion ────────────────────────────────────────────────
  { q: 'A recursive function is one that:', opts: ['Never returns', 'Has no parameters', 'Calls itself', 'Cannot use loops'], a: 2, e: 'Recursion is when a function solves a problem by calling itself on smaller inputs.', tags: ['DSA', 'Recursion'] },
  { q: 'Every correct recursion must have a:', opts: ['Global variable', 'Loop inside it', 'Return type of void', 'Base case that stops the recursion'], a: 3, e: 'A base case terminates the recursion; without one it would recurse forever.', tags: ['DSA', 'Recursion'] },
  { q: 'What happens if a recursion has no reachable base case?', opts: ['It returns 0', 'It recurses until a stack overflow', 'It runs in O(1)', 'It is automatically optimized away'], a: 1, e: 'Without a reachable base case the calls never stop and the call stack overflows.', tags: ['DSA', 'Recursion'] },
  { q: 'What does this return?\n\n```js\nfunction f(n) {\n  if (n <= 1) return 1;\n  return n * f(n - 1);\n}\nf(4);\n```', opts: ['10', '16', '24', '4'], a: 2, e: 'This computes 4! = 4 × 3 × 2 × 1 = 24.', tags: ['DSA', 'Recursion'] },
  { q: 'Recursion uses which structure to keep track of pending calls?', opts: ['A queue', 'A hash table', 'A heap', 'The call stack'], a: 3, e: 'Each recursive call pushes a frame onto the call stack, which is popped as calls return.', tags: ['DSA', 'Recursion'] },
  { q: 'A naive recursive Fibonacci (recomputing subproblems) has time complexity of about:', opts: ['O(n)', 'O(log n)', 'O(2ⁿ)', 'O(n²)'], a: 2, e: 'Naive Fibonacci branches into two calls each time and recomputes overlapping subproblems, giving roughly O(2ⁿ).', tags: ['DSA', 'Recursion'] },
  { q: 'Memoization speeds up recursion by:', opts: ['Removing the base case', 'Converting recursion to a queue', 'Sorting the inputs', 'Caching results of subproblems to avoid recomputation'], a: 3, e: 'Memoization stores computed results so repeated subproblems are returned instantly instead of recomputed.', tags: ['DSA', 'Recursion'] },
  { q: 'A tail-recursive call is one where the recursive call is:', opts: ['Inside a loop', 'The last operation performed before returning', 'Made twice', 'Never reached'], a: 1, e: 'In tail recursion the recursive call is the final action, which some languages can optimize into a loop.', tags: ['DSA', 'Recursion'] },

  // ── Level 10 — Sorting Algorithms ──────────────────────────────────────
  { q: 'What is the worst-case time complexity of bubble sort?', opts: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], a: 2, e: 'Bubble sort makes repeated passes swapping adjacent elements, giving O(n²) in the worst case.', tags: ['DSA', 'Sorting'] },
  { q: 'Merge sort has a time complexity of:', opts: ['O(n log n)', 'O(n)', 'O(n²)', 'O(log n)'], a: 0, e: 'Merge sort divides the list in half repeatedly and merges, giving O(n log n) in all cases.', tags: ['DSA', 'Sorting'] },
  { q: 'What is the worst-case time complexity of quicksort?', opts: ['O(n log n)', 'O(n²)', 'O(log n)', 'O(n)'], a: 1, e: 'With poor pivot choices quicksort can degrade to O(n²), though its average case is O(n log n).', tags: ['DSA', 'Sorting'] },
  { q: 'A sorting algorithm is "stable" when it:', opts: ['Never crashes', 'Uses no extra memory', 'Preserves the relative order of equal elements', 'Runs in O(n)'], a: 2, e: 'A stable sort keeps equal-valued elements in their original relative order.', tags: ['DSA', 'Sorting'] },
  { q: 'What is the proven lower bound for comparison-based sorting?', opts: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], a: 2, e: 'Any sort that orders elements only by comparisons needs at least O(n log n) comparisons in the worst case.', tags: ['DSA', 'Sorting'] },
  { q: 'Merge sort is typically described as stable, while a typical in-place quicksort is:', opts: ['Also always stable', 'Not stable', 'Unable to sort', 'O(n) time'], a: 1, e: 'Standard in-place quicksort can reorder equal elements, so it is generally not stable; merge sort is stable.', tags: ['DSA', 'Sorting'] },
  { q: 'Which sort can run in O(n) time on input that is already sorted?', opts: ['Merge sort', 'Selection sort', 'Heap sort', 'Insertion sort'], a: 3, e: 'On already-sorted data insertion sort does only n-1 comparisons and no shifts, giving best-case O(n).', tags: ['DSA', 'Sorting'] },
  { q: 'Quicksort partitions the array around a chosen element called the:', opts: ['median node', 'root', 'pivot', 'sentinel'], a: 2, e: 'Quicksort selects a pivot and partitions elements into those less than and greater than the pivot.', tags: ['DSA', 'Sorting'] },

  // ── Level 11 — Searching Algorithms ────────────────────────────────────
  { q: 'What is the time complexity of binary search on a sorted array?', opts: ['O(1)', 'O(n)', 'O(n log n)', 'O(log n)'], a: 3, e: 'Binary search halves the search range each step, giving O(log n).', tags: ['DSA', 'Searching'] },
  { q: 'What must be true of the data for binary search to work?', opts: ['It must be sorted', 'It must be unique', 'It must be in a hash table', 'It must be a power of two in length'], a: 0, e: 'Binary search relies on order to decide which half to discard, so the data must be sorted.', tags: ['DSA', 'Searching'] },
  { q: 'Linear search on an unsorted list is, in the worst case:', opts: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], a: 2, e: 'Linear search may scan every element, so the worst case is O(n).', tags: ['DSA', 'Searching'] },
  { q: 'In binary search, after comparing with the middle element you:', opts: ['Restart from the beginning', 'Discard one element', 'Discard half of the remaining range', 'Sort the array again'], a: 2, e: 'Each comparison lets you eliminate half of the remaining candidates, which is why it is O(log n).', tags: ['DSA', 'Searching'] },
  { q: 'For about 1,000,000 sorted elements, binary search needs roughly how many comparisons in the worst case?', opts: ['About 20', 'About 1,000', 'About 500,000', 'About 1,000,000'], a: 0, e: 'log₂(1,000,000) ≈ 20, so binary search needs about 20 comparisons.', tags: ['DSA', 'Searching'] },
  { q: 'What does this return when searching a sorted array for a value not present?\n\n```js\nfunction binarySearch(a, t) {\n  let lo = 0, hi = a.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (a[mid] === t) return mid;\n    if (a[mid] < t) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}\n```', opts: ['0', 'undefined', '-1', 'The array length'], a: 2, e: 'When the target is absent the loop ends with lo > hi and the function returns -1.', tags: ['DSA', 'Searching'] },
  { q: 'Compared with linear search, binary search trades extra requirements for:', opts: ['Higher memory use', 'Working on unsorted data', 'Stability', 'Far fewer comparisons on large sorted inputs'], a: 3, e: 'Binary search needs sorted data but examines only O(log n) elements instead of O(n).', tags: ['DSA', 'Searching'] },
  { q: 'If you must search an unsorted array exactly once, sorting it first just to binary search is usually:', opts: ['Always faster', 'Not worth it — sorting costs O(n log n), more than a single O(n) scan', 'Required', 'O(1)'], a: 1, e: 'A single linear search is O(n), cheaper than the O(n log n) needed to sort before binary searching.', tags: ['DSA', 'Searching'] },

  // ── Level 12 — Trees ───────────────────────────────────────────────────
  { q: 'In a tree, the topmost node is called the:', opts: ['root', 'leaf', 'edge', 'branch'], a: 0, e: 'The root is the single node at the top of a tree with no parent.', tags: ['DSA', 'Trees'] },
  { q: 'A node with no children is called a:', opts: ['root', 'parent', 'leaf', 'sibling'], a: 2, e: 'A leaf is a node that has no children at the bottom of the tree.', tags: ['DSA', 'Trees'] },
  { q: 'In a binary tree, each node has at most how many children?', opts: ['1', '3', 'Unlimited', '2'], a: 3, e: 'A binary tree restricts each node to at most two children, usually called left and right.', tags: ['DSA', 'Trees'] },
  { q: 'The number of edges on the longest path from the root to a leaf is the tree’s:', opts: ['height', 'width', 'degree', 'order'], a: 0, e: 'The height of a tree is the length of the longest root-to-leaf path measured in edges.', tags: ['DSA', 'Trees'] },
  { q: 'Which traversal visits left subtree, then node, then right subtree?', opts: ['Pre-order', 'Post-order', 'In-order', 'Level-order'], a: 2, e: 'In-order traversal processes the left subtree, then the current node, then the right subtree.', tags: ['DSA', 'Trees'] },
  { q: 'A depth-first traversal of a tree is naturally implemented with:', opts: ['A queue', 'A hash table', 'Binary search', 'Recursion or a stack'], a: 3, e: 'DFS dives deep before backtracking, which maps naturally to recursion or an explicit stack.', tags: ['DSA', 'Trees'] },
  { q: 'Level-order (breadth-first) tree traversal uses which structure?', opts: ['A stack', 'A queue', 'A heap', 'A linked list of leaves'], a: 1, e: 'Level-order traversal visits nodes level by level using a queue.', tags: ['DSA', 'Trees'] },
  { q: 'A binary tree of n nodes that is balanced has a height of about:', opts: ['O(n)', 'O(n²)', 'O(log n)', 'O(1)'], a: 2, e: 'A balanced binary tree distributes nodes so its height stays around log n.', tags: ['DSA', 'Trees'] },

  // ── Level 13 — Binary Search Trees ─────────────────────────────────────
  { q: 'What is the defining ordering property of a binary search tree (BST)?', opts: ['Left subtree < node < right subtree', 'Left child > node > right child', 'All children are equal', 'Nodes are unordered'], a: 0, e: 'In a BST, every value in the left subtree is less than the node and every value in the right subtree is greater.', tags: ['DSA', 'BST'] },
  { q: 'In a balanced BST, searching for a value takes:', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 2, e: 'A balanced BST halves the search space at each level, giving O(log n) search.', tags: ['DSA', 'BST'] },
  { q: 'What is the worst-case search time of an unbalanced BST (e.g. inserted in sorted order)?', opts: ['O(n)', 'O(1)', 'O(log n)', 'O(n log n)'], a: 0, e: 'Inserting sorted values makes the BST degenerate into a linked list, so search becomes O(n).', tags: ['DSA', 'BST'] },
  { q: 'An in-order traversal of a BST visits the values in:', opts: ['Reverse order', 'Random order', 'Sorted ascending order', 'Level order'], a: 2, e: 'Because of the BST ordering property, an in-order traversal yields values in ascending sorted order.', tags: ['DSA', 'BST'] },
  { q: 'Where is the minimum value found in a non-empty BST?', opts: ['At the root', 'The rightmost node', 'The leftmost node', 'Any leaf'], a: 2, e: 'Following left pointers from the root leads to the smallest value, the leftmost node.', tags: ['DSA', 'BST'] },
  { q: 'Self-balancing BSTs such as AVL or Red-Black trees exist primarily to:', opts: ['Guarantee O(log n) operations by keeping height balanced', 'Use less memory', 'Allow duplicate keys', 'Avoid recursion'], a: 0, e: 'Self-balancing trees rebalance on insert/delete so height stays O(log n), guaranteeing fast operations.', tags: ['DSA', 'BST'] },
  { q: 'To insert into a BST, you compare with the current node and:', opts: ['Always go left', 'Insert at the root', 'Rebuild the whole tree', 'Go left if smaller, right if larger, until you find an empty spot'], a: 3, e: 'Insertion walks down the tree, going left for smaller and right for larger values, until reaching an empty position.', tags: ['DSA', 'BST'] },
  { q: 'When deleting a BST node with two children, a common approach is to replace it with its:', opts: ['Root', 'In-order successor (or predecessor)', 'Left child only', 'Sibling'], a: 1, e: 'Replacing the node with its in-order successor (smallest in the right subtree) preserves the BST property.', tags: ['DSA', 'BST'] },

  // ── Level 14 — Heaps & Priority Queues ─────────────────────────────────
  { q: 'In a min-heap, the smallest element is always at the:', opts: ['leaves', 'rightmost node', 'root', 'middle'], a: 2, e: 'A min-heap keeps the minimum element at the root by the heap-order property.', tags: ['DSA', 'Heaps'] },
  { q: 'What is the time complexity of finding (peeking at) the minimum in a min-heap?', opts: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], a: 0, e: 'The minimum sits at the root, so reading it is O(1).', tags: ['DSA', 'Heaps'] },
  { q: 'What is the time complexity of inserting into a binary heap?', opts: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], a: 2, e: 'Insertion places the element at the end and sifts it up the tree height, which is O(log n).', tags: ['DSA', 'Heaps'] },
  { q: 'Removing the minimum (extract-min) from a binary heap costs:', opts: ['O(1)', 'O(n)', 'O(n log n)', 'O(log n)'], a: 3, e: 'After removing the root, the heap sifts a replacement down through its height, which is O(log n).', tags: ['DSA', 'Heaps'] },
  { q: 'A binary heap is most commonly implemented using:', opts: ['A linked list', 'A hash table', 'A stack', 'An array'], a: 3, e: 'A binary heap is stored compactly in an array, with children of index i at 2i+1 and 2i+2.', tags: ['DSA', 'Heaps'] },
  { q: 'A priority queue is best implemented with which structure for efficient operations?', opts: ['A heap', 'A plain array', 'A hash table', 'A singly linked list'], a: 0, e: 'A heap gives O(log n) insert and extract of the highest-priority element, ideal for a priority queue.', tags: ['DSA', 'Heaps'] },
  { q: 'Building a heap from an unsorted array of n elements (heapify) can be done in:', opts: ['O(n)', 'O(log n)', 'O(n log n) only', 'O(n²)'], a: 0, e: 'The bottom-up build-heap procedure runs in O(n), tighter than inserting n elements one by one.', tags: ['DSA', 'Heaps'] },
  { q: 'Heap sort works by building a heap and repeatedly extracting the root; its overall time complexity is:', opts: ['O(n)', 'O(n²)', 'O(log n)', 'O(n log n)'], a: 3, e: 'Heap sort does n extractions, each O(log n), giving O(n log n) overall.', tags: ['DSA', 'Heaps'] },

  // ── Level 15 — Graphs ──────────────────────────────────────────────────
  { q: 'A graph is composed of:', opts: ['Only nodes', 'Rows and columns', 'Vertices and edges', 'Keys and values'], a: 2, e: 'A graph consists of vertices (nodes) connected by edges.', tags: ['DSA', 'Graphs'] },
  { q: 'In a directed graph, an edge:', opts: ['Has no direction', 'Connects three vertices', 'Must form a cycle', 'Goes one way, from one vertex to another'], a: 3, e: 'A directed edge has an orientation, pointing from a source vertex to a destination vertex.', tags: ['DSA', 'Graphs'] },
  { q: 'What is the time complexity of breadth-first search (BFS) on a graph with V vertices and E edges?', opts: ['O(V)', 'O(E)', 'O(V + E)', 'O(V × E)'], a: 2, e: 'BFS visits every vertex and explores every edge once, giving O(V + E).', tags: ['DSA', 'Graphs'] },
  { q: 'What is the time complexity of depth-first search (DFS) on a graph with V vertices and E edges?', opts: ['O(V + E)', 'O(V²)', 'O(E²)', 'O(log V)'], a: 0, e: 'DFS also touches each vertex and edge once, so it runs in O(V + E).', tags: ['DSA', 'Graphs'] },
  { q: 'Which data structure does BFS use to manage which vertex to visit next?', opts: ['A stack', 'A heap', 'A queue', 'A binary search tree'], a: 2, e: 'BFS uses a queue to visit vertices in order of increasing distance from the source.', tags: ['DSA', 'Graphs'] },
  { q: 'An adjacency matrix representation of a graph with V vertices uses how much space?', opts: ['O(V)', 'O(V + E)', 'O(V²)', 'O(E)'], a: 2, e: 'An adjacency matrix stores an entry for every pair of vertices, requiring O(V²) space.', tags: ['DSA', 'Graphs'] },
  { q: 'Dijkstra’s algorithm is used to find:', opts: ['A minimum spanning tree', 'Shortest paths from a source in a graph with non-negative edge weights', 'A topological order', 'Strongly connected components'], a: 1, e: 'Dijkstra’s algorithm computes shortest paths from a source vertex when edge weights are non-negative.', tags: ['DSA', 'Graphs'] },
  { q: 'A topological sort can be performed on which kind of graph?', opts: ['Any graph', 'An undirected graph only', 'A graph with negative weights', 'A directed acyclic graph (DAG)'], a: 3, e: 'Topological ordering requires a directed acyclic graph; a cycle would make a valid ordering impossible.', tags: ['DSA', 'Graphs'] },
];
