import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Tournament Strategy roadmap bank (rm-pktourn-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const tournamentPlayTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-pktourn-1': { introduction: 'Turnaj tlačí hráče k akci časem.', question: 'Co se v pokerovém turnaji děje s blindy, jak plyne čas?', options: ['Zvyšují se v daných intervalech', 'Zůstávají po celý turnaj stejné', 'Postupně se snižují', 'Hráči si je volí každou hru'], explanation: 'Turnaje zvyšují blindy (a anty) v naplánovaných úrovních, což s postupem turnaje vynucuje akci.' },
  'rm-pktourn-2': { introduction: 'Ve freezeoutu není žádný rebuy.', question: 'Kdy jsi vyřazen ze standardního freezeout turnaje?', options: ['Když přijdeš o všechny žetony', 'Když prohraješ jeden velký pot', 'Po pevném počtu her', 'Když tě minou blindy'], explanation: 'Ve freezeoutu končíš ve chvíli, kdy tvůj stack klesne na nulu; není možnost dokoupit žetony.' },
  'rm-pktourn-3': { introduction: 'Výplaty jsou obvykle jen pro špičku pole.', question: 'Ve většině turnajů dostane výplatu zhruba jaká část pole?', options: ['Přibližně horních 10-15 %', 'Přesně polovina', 'Jen vítěz', 'Každý, kdo se přihlásil'], explanation: 'Běžná výplatní struktura platí zhruba horních 10-15 % hráčů, přičemž ceny rostou směrem k prvnímu místu.' },
  'rm-pktourn-4': { introduction: 'Vstupné financuje prize pool.', question: 'Co je v turnaji „buy-in"?', options: ['Částka za vstup, za kterou dostaneš žetony', 'První sázka každé hry', 'Cena za první místo', 'Nucená sázka před flopem'], explanation: 'Buy-in je to, co platíš za vstup; naplňuje prize pool (po odečtení poplatku) a dává ti startovní žetony.' },
  'rm-pktourn-5': { introduction: 'Turnajové žetony nejsou hotovost.', question: 'Turnajové žetony se od žetonů v cash game liší tím, že...', options: ['Nemají přímou peněžní hodnotu', 'Lze je kdykoli směnit za hotovost', 'Mají hodnotu v dolarech podle nominálu', 'Používají se jen na riveru'], explanation: 'Turnajové žetony určují jen tvé postavení; nemůžeš je během turnaje vyplatit jako žetony v cash game.' },
  'rm-pktourn-6': { introduction: 'Formát umožňuje dokoupit žetony.', question: 'Co je „rebuy" turnaj?', options: ['Takový, kde po brzkém vypadnutí můžeš dokoupit žetony', 'Takový bez vstupního poplatku', 'Takový, který nikdy nevyplácí', 'Takový s pevnými blindy'], explanation: 'V rebuy turnaji si hráči mohou během úvodního rebuy období dokoupit další žetony (obvykle když jsou krátcí nebo vypadli).' },
  'rm-pktourn-7': { introduction: 'Malá nucená sázka do potu.', question: 'Co po hráčích vyžaduje „ante"?', options: ['Vložit malou nucenou sázku do většiny či každého potu', 'Dorovnat největší stack', 'Vynechat hru', 'Ukázat karty předčasně'], explanation: 'Ante je malý nucený příspěvek, který nafukuje pot a zejména v pozdějších úrovních podporuje akci.' },
  'rm-pktourn-8': { introduction: 'Struktura je nakloněná ke špičce.', question: 'Kam putuje většina výherní částky turnaje?', options: ['Silně nakloněno k nejlepším umístěním', 'Rozděleno rovnoměrně mezi všechny placené', 'Celé poslednímu místu', 'Vráceno vyřazeným hráčům'], explanation: 'Výplatní struktury jsou nahoře těžké: první místo bere velký podíl a ceny prudce klesají po žebříčku dolů.' },

  'rm-pktourn-9': { introduction: 'Blindy rostou, žetony ne.', question: 'Proč hráči měří svůj stack ve „velkých blindech" místo v žetonech?', options: ['Ukazuje to skutečnou sílu bez ohledu na rostoucí blindy', 'Žetony se těžko počítají', 'Vyžadují to pravidla', 'Velké blindy se nikdy nemění'], explanation: 'Protože blindy rostou, holý počet žetonů klame; velké blindy (stack ÷ velký blind) ukazují skutečnou hloubku stacku.' },
  'rm-pktourn-10': { introduction: 'Hluboký stack dává volnost.', question: 'Hráč s 80 velkými blindy je obecně považován za...', options: ['Hluboký, pohodlný stack', 'Krátký stack', 'Stack nucený jít all-in', 'Stack, který musí všechno foldovat'], explanation: 'Kolem 80 velkých blindů je hluboký, flexibilní stack, který umožňuje hru po flopu a nenutí k all-in rozhodnutím.' },
  'rm-pktourn-11': { introduction: 'Málo prostoru po flopu.', question: 'Jaká hloubka stacku se běžně označuje jako „krátký stack"?', options: ['Pod zhruba 15-20 velkými blindy', 'Přes 100 velkých blindů', 'Přesně 50 velkých blindů', 'Jakýkoli stack s žetony'], explanation: 'Pod zhruba 15-20 velkými blindy jsi krátký a máš po flopu jen málo prostoru k manévrování.' },
  'rm-pktourn-12': { introduction: 'Rané fáze odměňují trpělivost.', question: 'V rané fázi turnaje jsou blindy vůči stackům...', options: ['Malé, což umožňuje trpělivou hlubokou hru', 'Větší než stack kohokoli', 'Pevné po celý turnaj', 'Určené čipovým lídrem'], explanation: 'Na začátku hluboké stacky a malé blindy odměňují trpělivost a výběrovou hru zaměřenou na potflop.' },
  'rm-pktourn-13': { introduction: 'Nastupují anty.', question: 'Jak turnaj dosáhne střední fáze, klíčovou změnou je, že...', options: ['Nastupují anty a krádež blindů získává na významu', 'Blindy přestanou růst', 'Všichni hrají každou hru all-in', 'Prize pool se zmenší'], explanation: 'Ve střední fázi se objevují anty a rostoucí blindy činí krádež blindů a antů čím dál cennější.' },
  'rm-pktourn-14': { introduction: 'Jednoduchý výpočet.', question: 'Pokud máš 100 velkých blindů a velký blind je 500, tvůj stack je...', options: ['50 000 žetonů', '5 000 žetonů', '500 žetonů', '1 000 000 žetonů'], explanation: '100 velkých blindů × 500 žetonů na velký blind se rovná 50 000 žetonů.' },
  'rm-pktourn-15': { introduction: 'Stejné žetony, méně blindů.', question: 'Proč rostoucí úroveň blindů fakticky zmenšuje stack, který nevyhraje žádný pot?', options: ['Stejné žetony mají hodnotu méně velkých blindů', 'Žetony jsou fyzicky odebrány', 'Krupiér si bere podíl', 'Anty se vrací'], explanation: 'I když se počet žetonů nemění, vyšší blindy znamenají, že tyto žetony představují méně velkých blindů hratelné hloubky.' },
  'rm-pktourn-16': { introduction: 'Blízko peněz je tlak vysoký.', question: 'Co je určujícím rysem „pozdní fáze" turnaje blízko peněz?', options: ['Mělké stacky a rozhodnutí pod velkým tlakem', 'Nejhlubší stacky turnaje', 'Žádné anty ve hře', 'Blindy resetované na začátek'], explanation: 'Pozdní fáze se vyznačuje mělkými stacky ve velkých blindech, anty a napjatými situacemi, jak se blíží peníze.' },

  'rm-pktourn-17': { introduction: 'Buď all-in, nebo fold.', question: 'Co je strategie „push/fold"?', options: ['Buď jít all-in, nebo foldovat, bez malých raisů', 'Vždy dorovnat blind', 'Nikdy nesázet na riveru', 'Limpovat každou hru'], explanation: 'S krátkým stackem push/fold zjednodušuje rozhodování: jdeš all-in, nebo foldíš a vyhýbáš se snadno committujícím malým raisům.' },
  'rm-pktourn-18': { introduction: 'Málo fold equity, málo prostoru.', question: 'Hra push/fold se stává správnou hlavně tehdy, když je tvůj stack...', options: ['Kolem 10-15 velkých blindů nebo méně', 'Přes 100 velkých blindů', 'Přesně 40 velkých blindů', 'Jakékoli hloubky'], explanation: 'Zhruba při 10-15 velkých blindech nebo méně je málo fold equity a prostoru po flopu, takže shove-nebo-fold je optimální.' },
  'rm-pktourn-19': { introduction: 'Kolik oběhů přežiješ.', question: 'Poměr „M-ratio" měří tvůj stack vůči čemu?', options: ['Blindům a antům, které platíš za jeden oběh', 'Stacku čipového lídra', 'Celkovému prize poolu', 'Počtu zbývajících hráčů'], explanation: 'M se rovná tvému stacku dělenému celkovými blindy a anty za oběh a ukazuje, kolik kol přežiješ jen foldováním.' },
  'rm-pktourn-20': { introduction: 'Blindy tě požírají.', question: 'Nízké M-ratio (řekněme pod 5) signalizuje, že by hráč měl...', options: ['Brzy hledat příležitost jít all-in', 'Hrát velmi pasivně a všechno foldovat', 'Dorovnávat každý raise', 'Počkat dalších desítky her'], explanation: 'Nízké M znamená, že tě blindy požírají, takže musíš najít ruku k shove, než tě blindy vyřadí.' },
  'rm-pktourn-21': { introduction: 'Hodnota z toho, že soupeři foldnou.', question: 'Co je „fold equity"?', options: ['Šance, že soupeři foldnou na tvou sázku nebo shove', 'Equity ze skládání rukou', 'Pot, který vyhraješ na showdownu', 'Rake sebraný z potu'], explanation: 'Fold equity je hodnota získaná z možnosti, že soupeři foldnou, která se zmenšuje, jak se tvůj stack ztenčuje.' },
  'rm-pktourn-22': { introduction: 'Méně hráčů za tebou.', question: 'Z pozdní pozice s krátkým stackem je širší shove rozsah oprávněný, protože...', options: ['Zbývá méně hráčů, kteří by mohli mít silnou ruku', 'Blindy jsou tam menší', 'Musíš jednat první', 'Karty se v pozdní pozici zlepšují'], explanation: 'Jednat později znamená méně hráčů za tebou, kteří mohou dorovnat, takže větší fold equity podpírá shove širšího rozsahu.' },
  'rm-pktourn-23': { introduction: 'Neplýtvej žetony.', question: 'Se zhruba 12 velkými blindy, proč je min-raise a následný fold na shove často chyba?', options: ['Vzdáváš se žetonů, které jsi mohl vložit shovem', 'Je to proti pravidlům', 'Min-raise není nakrátko dovolen', 'Zdvojnásobí to blindy'], explanation: 'Malý raise a fold na re-shove plýtvá žetony; v této hloubce shove přímo čistě získává fold equity.' },
  'rm-pktourn-24': { introduction: 'Harringtonovy zóny.', question: 'Harringtonovy „zóny" vážou strategii na M; vstup do „červené zóny" (M pod 5) znamená...', options: ['Tvým jediným reálným tahem je jít all-in, nebo foldovat', 'Můžeš hrát poker s hlubokým stackem', 'Měl bys sedět mimo', 'Musíš dorovnat každou sázku'], explanation: 'V červené zóně je tvůj stack tak krátký vůči blindům, že shove-nebo-fold je v podstatě tvá jediná životaschopná hra.' },

  'rm-pktourn-25': { introduction: 'Těsně před penězi.', question: 'Co je v turnaji „bublina"?', options: ['Místo těsně předtím, než hráči začnou dostávat výplatu', 'Poslední hra turnaje', 'První úroveň hry', 'Přestávka mezi úrovněmi'], explanation: 'Bublina je bod těsně před penězi; poslední vyřazený hráč bez výplaty je tzv. „bubble boy".' },
  'rm-pktourn-26': { introduction: 'Žetony na hotovost.', question: 'K čemu slouží ICM (Independent Chip Model)?', options: ['K odhadu skutečné peněžní hodnoty stacku podle výplat', 'K počtu zbývajících her', 'K dlužnému rake', 'K rozpisu blindů'], explanation: 'ICM převádí stacky na jejich očekávaný podíl z prize poolu, protože žetony nemají lineární hodnotu v hotovosti.' },
  'rm-pktourn-27': { introduction: 'Ztráta bolí víc než zisk.', question: 'Klíčovým poznatkem ICM je, že žetony, o které můžeš přijít, mají hodnotu...', options: ['Vyšší než stejný počet žetonů, které můžeš vyhrát', 'Přesně stejnou jako žetony, které vyhraješ', 'Vůbec žádnou', 'Jen svou nominální'], explanation: 'Ztráta žetonů stojí více equity, než získá výhra stejného množství, protože výherní částka není s žetony lineární.' },
  'rm-pktourn-28': { introduction: 'Velký stack tlačí.', question: 'Na bublině může velký stack profitovat tím, že...', options: ['Tlačí na střední stacky, které se bojí vypadnout', 'Foldí každou hru', 'Dorovnává all-iny s jakýmikoli dvěma kartami', 'Odmítá raisovat'], explanation: 'Velké stacky vyvíjejí tlak na bublině: střední stacky riskují vyřazení před penězi, takže víc foldí a ty kradeš.' },
  'rm-pktourn-29': { introduction: 'Hodnota dosažení peněz.', question: 'Kvůli ICM by měl krátký stack blízko bubliny obecně...', options: ['Vyhnout se marginálním all-inům, které riskují vypadnutí před penězi', 'Dorovnat s jakoukoli rukou', 'Zcela ignorovat výplaty', 'Hrát přesně jako cash game'], explanation: 'Blízko bubliny činí hodnota pouhého dosažení peněz tenké, rizikové all-iny v pojetí ICM méně výhodnými.' },
  'rm-pktourn-30': { introduction: 'Posun po žebříčku.', question: 'Co je „pay-jump" (skok ve výplatě)?', options: ['Nárůst výherní částky za posun o jedno místo', 'Skok v úrovni blindů', 'Bonus pro čipového lídra', 'Možnost rebuy'], explanation: 'Pay-jump je částka navíc získaná tím, že přežiješ o jednoho hráče déle a vystoupáš po výplatním žebříčku.' },
  'rm-pktourn-31': { introduction: 'ICM trestá vypadnutí.', question: 'Ve srovnání s přístupem chip-EV (cash game) ICM obvykle činí správné rozsahy pro dorovnání...', options: ['Těsnějšími, protože vypadnutí je nákladnější', 'Mnohem širšími', 'Nezměněnými', 'Náhodnými'], explanation: 'ICM penalizuje vyřazení, takže all-iny dorovnáváš těsněji, než by naznačoval čistý chip-EV model.' },
  'rm-pktourn-32': { introduction: 'Přežít a stoupat.', question: 'Proč může být fold mírně +chip-EV all-inu správný blízko velkého pay-jumpu?', options: ['Přežití a posun po žebříčku má větší hodnotu než malá čipová výhoda', 'Fold vždy vyhrává žetony', 'Ruka je proti pravidlům', 'Žetony mají pevnou hodnotu v hotovosti'], explanation: 'Když je pay-jump velký, equity z posunu po žebříčku může převážit marginální čipovou výhodu, takže fold je z hlediska ICM správný.' },

  'rm-pktourn-33': { introduction: 'Velké skoky ve výplatách.', question: 'Proč jsou u finálového stolu úvahy o ICM obzvlášť silné?', options: ['Skoky ve výplatách mezi místy jsou velké', 'Nejsou žádné anty', 'Blindy přestanou růst', 'Všichni mají stejný stack'], explanation: 'Pay-jumpy u finálového stolu jsou velké, takže tlak ICM na udržení stacku a vyhnutí se vypadnutí zde vrcholí.' },
  'rm-pktourn-34': { introduction: 'Tlač na ty, kdo nemohou riskovat.', question: 'Jak může velký stack u finálového stolu nejlépe využít tlak ICM?', options: ['Agresí proti stackům, které si nemohou dovolit vypadnout', 'Vynecháváním každé hry', 'Jen dorovnáváním all-inů', 'Pasivní hrou každého potu'], explanation: 'Krátké a střední stacky se bojí pay-jumpů, takže velký stack raisuje a re-raisuje, aby bral poty bez odporu.' },
  'rm-pktourn-35': { introduction: 'Méně hráčů, silnější ruce.', question: 'Jak by se měly hodnoty rukou posunout, když se stůl stane short-handed (méně hráčů)?', options: ['Ruce získávají na hodnotě, takže jich hraješ víc', 'Ruce ztrácejí hodnotu, hraj těsněji', 'Hodnoty se nemění', 'Hratelná jsou jen esa'], explanation: 'S méně soupeři tě blindy zasahují častěji a každá ruka je v průměru silnější, takže otevíráš širší rozsah.' },
  'rm-pktourn-36': { introduction: 'Button je small blind.', question: 'Jak jedná v heads-up hře button (small blind)?', options: ['Sází small blind, před flopem jedná první, po flopu poslední', 'Sází big blind', 'Jedná poslední na každé ulici', 'Nesází žádný blind'], explanation: 'V heads-up sází button small blind, před flopem jedná první a poté jedná poslední na flopu, turnu i riveru.' },
  'rm-pktourn-37': { introduction: 'Jen jeden soupeř.', question: 'Správná heads-up strategie je oproti hře u plného stolu...', options: ['Mnohem agresivnější, s velmi širokým rozsahem', 'Mnohem těsnější, s foldováním většiny rukou', 'Totožná', 'Foldovat vše kromě es'], explanation: 'S jediným soupeřem a blindy zasahujícími každou hru vyžaduje heads-up široký, agresivní rozsah a neustálý tlak.' },
  'rm-pktourn-38': { introduction: 'Zbývají jen dvě výplaty.', question: 'Když jsi heads-up o titul, proč se tlak ICM do velké míry uvolní?', options: ['Zbývá jen první a druhé místo, takže je to blíž chip-EV', 'Blindy se zastaví', 'Anty jsou odstraněny', 'Žetony získají pevnou hodnotu'], explanation: 'Se zbývajícími jen dvěma výplatami je žebříček téměř vyčerpán a hra se vrací k maximalizaci chip EV.' },
  'rm-pktourn-39': { introduction: 'Stále máš šanci.', question: '„Chip and a chair" comeback ilustruje, že krátký stack by měl...', options: ['Hrát dál, protože i s jakýmkoli stackem lze vyhrát', 'Vzdát to, jakmile je krátký', 'Vždy foldovat na lídra', 'Odmítat jít all-in'], explanation: 'Rčení připomíná, že i jediný žeton tě drží ve hře a krátké stacky se běžně zvednou až k vítězství.' },
  'rm-pktourn-40': { introduction: 'Spravedlivé rozdělení podle stacků.', question: 'Při vyjednávání „dealu" (chopu) u finálového stolu se stacky nejspravedlivěji dělí pomocí...', options: ['Výpočtu ICM nebo chip-chop', 'Rovného dělení bez ohledu na stacky', 'Toho, kdo má button', 'Pořadí, v jakém hráči vypadli'], explanation: 'Spravedlivé dealy váží zbývající výherní částku podle velikosti stacku, obvykle výpočtem ICM (nebo chip-chop).' },
};
