import type { Seed } from './roadmap-build';

// Population & Cities — 10 levels × 8 questions, easiest → hardest.
export const populationSeeds: Seed[] = [
  // ── Level 1 — World Population Basics ──
  { q: 'Roughly how many people live on Earth today?', opts: ['About 1 billion', 'About 4 billion', 'About 6 billion', 'About 8 billion'], a: 3, e: 'The world population passed 8 billion in late 2022 and continues to grow slowly.', tags: ['population', 'World Basics'] },
  { q: 'Which continent has the most people?', opts: ['Africa', 'Asia', 'Europe', 'North America'], a: 1, e: 'Asia is by far the most populous continent, home to well over half of humanity.', tags: ['population', 'World Basics'] },
  { q: 'Which continent has no permanent human population?', opts: ['Antarctica', 'Australia', 'Europe', 'South America'], a: 0, e: 'Antarctica has only temporary researchers and no permanent residents.', tags: ['population', 'World Basics'] },
  { q: 'Besides Antarctica, which inhabited continent has the fewest people?', opts: ['Asia', 'Africa', 'Australia (Oceania)', 'Europe'], a: 2, e: 'Oceania, dominated by Australia, has the smallest population of the inhabited continents — around 45 million.', tags: ['population', 'World Basics'] },
  { q: 'About what share of the world’s people live in Asia?', opts: ['About 20%', 'About 60%', 'About 40%', 'About 80%'], a: 1, e: 'Roughly 60% of all humans live in Asia, led by India and China.', tags: ['population', 'World Basics'] },
  { q: 'Which two countries each have more than a billion people?', opts: ['USA and Indonesia', 'Russia and Brazil', 'Nigeria and Pakistan', 'India and China'], a: 3, e: 'India and China are the only two countries with populations above one billion.', tags: ['population', 'World Basics'] },
  { q: 'In which year did the world population reach 8 billion?', opts: ['2010', '2015', '2022', '2005'], a: 2, e: 'The United Nations marked the 8-billion milestone in November 2022.', tags: ['population', 'World Basics'] },
  { q: 'Which continent is home to the second-most people after Asia?', opts: ['Africa', 'Europe', 'South America', 'North America'], a: 0, e: 'Africa is the second most populous continent, with about 1.4 billion people and rising fast.', tags: ['population', 'World Basics'] },

  // ── Level 2 — Most Populous Countries ──
  { q: 'Which country has the most people in the world today?', opts: ['China', 'India', 'United States', 'Indonesia'], a: 1, e: 'India became the world’s most populous country in 2023, overtaking China.', tags: ['population', 'Countries'] },
  { q: 'Which country is now the second most populous in the world?', opts: ['India', 'United States', 'Nigeria', 'China'], a: 3, e: 'China slipped to second place behind India in 2023, with about 1.4 billion people.', tags: ['population', 'Countries'] },
  { q: 'India overtook which country in 2023 to become number one?', opts: ['China', 'Indonesia', 'Pakistan', 'United States'], a: 0, e: 'India passed China in 2023 as its population kept growing while China’s began to decline.', tags: ['population', 'Countries'] },
  { q: 'Which is the most populous country in the Americas?', opts: ['Brazil', 'Mexico', 'United States', 'Canada'], a: 2, e: 'The United States, with about 335 million people, is the third most populous country overall.', tags: ['population', 'Countries'] },
  { q: 'Which Southeast Asian country is the fourth most populous in the world?', opts: ['Philippines', 'Vietnam', 'Thailand', 'Indonesia'], a: 3, e: 'Indonesia, with roughly 280 million people, ranks fourth globally.', tags: ['population', 'Countries'] },
  { q: 'Which country ranks as the fifth most populous?', opts: ['Brazil', 'Pakistan', 'Nigeria', 'Bangladesh'], a: 1, e: 'Pakistan, with about 240 million people, is the fifth most populous country.', tags: ['population', 'Countries'] },
  { q: 'Which is the most populous country in South America?', opts: ['Argentina', 'Colombia', 'Brazil', 'Peru'], a: 2, e: 'Brazil, with about 215 million people, is South America’s most populous nation.', tags: ['population', 'Countries'] },
  { q: 'Nigeria is the most populous country on which continent?', opts: ['Africa', 'Asia', 'Europe', 'South America'], a: 0, e: 'Nigeria, with more than 220 million people, is Africa’s most populous country.', tags: ['population', 'Countries'] },

  // ── Level 3 — Megacities ──
  { q: 'Which urban area is generally the largest in the world by population?', opts: ['Delhi', 'Shanghai', 'Tokyo', 'New York'], a: 2, e: 'Greater Tokyo is usually ranked the world’s largest metropolitan area.', tags: ['population', 'Megacities'] },
  { q: 'Roughly how many people live in the greater Tokyo metropolitan area?', opts: ['About 37 million', 'About 10 million', 'About 100 million', 'About 5 million'], a: 0, e: 'The Tokyo metro area holds roughly 37 million people, more than many entire countries.', tags: ['population', 'Megacities'] },
  { q: 'Which Indian megacity is one of the world’s largest, often ranked just behind Tokyo?', opts: ['Mumbai', 'Delhi', 'Kolkata', 'Chennai'], a: 1, e: 'Delhi’s metropolitan area, with over 30 million people, is among the largest on Earth.', tags: ['population', 'Megacities'] },
  { q: 'Which Chinese city is one of the world’s most populous urban areas?', opts: ['Guangzhou', 'Beijing', 'Chengdu', 'Shanghai'], a: 3, e: 'Shanghai is one of China’s and the world’s largest urban areas, with over 25 million people.', tags: ['population', 'Megacities'] },
  { q: 'São Paulo, one of the largest metro areas in the Americas, is in which country?', opts: ['Brazil', 'Argentina', 'Mexico', 'Portugal'], a: 0, e: 'São Paulo, in Brazil, is the largest city in the Southern Hemisphere.', tags: ['population', 'Megacities'] },
  { q: 'A "megacity" is usually defined as a metro area with at least how many people?', opts: ['1 million', '5 million', '10 million', '50 million'], a: 2, e: 'A megacity is conventionally a metropolitan area with 10 million or more inhabitants.', tags: ['population', 'Megacities'] },
  { q: 'Which of these is a megacity in Mexico?', opts: ['Lima', 'Bogotá', 'Santiago', 'Mexico City'], a: 3, e: 'Mexico City’s metro area, with over 20 million people, is one of the largest in the Americas.', tags: ['population', 'Megacities'] },
  { q: 'Cairo, one of Africa’s largest metro areas, is the capital of which country?', opts: ['Nigeria', 'Egypt', 'Sudan', 'Libya'], a: 1, e: 'Cairo is the capital of Egypt and among Africa’s biggest urban areas, with over 20 million people.', tags: ['population', 'Megacities'] },

  // ── Level 4 — Population Density ──
  { q: 'Which is the most densely populated sovereign country?', opts: ['Monaco', 'Russia', 'Canada', 'Brazil'], a: 0, e: 'Monaco packs tens of thousands of people per square kilometer into a tiny area.', tags: ['population', 'Density'] },
  { q: 'Which Southeast Asian city-state is famous for very high population density?', opts: ['Malaysia', 'Indonesia', 'Singapore', 'Vietnam'], a: 2, e: 'Singapore is a small, extremely densely populated island city-state.', tags: ['population', 'Density'] },
  { q: 'Population density measures the number of people per what?', opts: ['Per household', 'Per unit of land area', 'Per city', 'Per country in total'], a: 1, e: 'Density is population divided by land area, usually people per square kilometer or square mile.', tags: ['population', 'Density'] },
  { q: 'Which large Asian country has one of the highest densities, with over 170 million people in a small area?', opts: ['Russia', 'Kazakhstan', 'Australia', 'Bangladesh'], a: 3, e: 'Bangladesh combines a huge population with a small area, giving it very high density.', tags: ['population', 'Density'] },
  { q: 'Which country is often cited as having the lowest population density?', opts: ['India', 'Japan', 'Mongolia', 'Germany'], a: 2, e: 'Mongolia has only about two people per square kilometer, among the lowest of any country.', tags: ['population', 'Density'] },
  { q: 'Which country has a huge land area but low overall density, with most people near the coasts?', opts: ['Australia', 'Bangladesh', 'Netherlands', 'South Korea'], a: 0, e: 'Australia is vast but arid inland, so most of its people cluster along the coasts.', tags: ['population', 'Density'] },
  { q: 'Why does an arid country like Namibia have low population density?', opts: ['It is too cold', 'It is too mountainous', 'The government limits residents', 'Harsh, dry land supports few people'], a: 3, e: 'Namibia’s deserts and dry climate can sustain only a sparse population.', tags: ['population', 'Density'] },
  { q: 'The Netherlands is known in Europe for being:', opts: ['Very sparsely populated', 'One of Europe’s most densely populated countries', 'Completely uninhabited', 'Larger than Russia'], a: 1, e: 'The Netherlands is among Europe’s most densely populated countries.', tags: ['population', 'Density'] },

  // ── Level 5 — Urban vs Rural ──
  { q: 'What does "urbanization" mean?', opts: ['People moving to farms', 'The growing share of people living in towns and cities', 'A drop in total population', 'Building more highways'], a: 1, e: 'Urbanization is the rising proportion of a population that lives in urban areas.', tags: ['population', 'Urban & Rural'] },
  { q: 'Today, roughly what share of the world’s people live in urban areas?', opts: ['About 10%', 'About 25%', 'About 40%', 'More than half'], a: 3, e: 'Since around 2007, more than half of humanity has lived in cities and towns.', tags: ['population', 'Urban & Rural'] },
  { q: 'A "rural" area is best described as:', opts: ['Countryside with low population density', 'A dense downtown', 'A national capital', 'An industrial port'], a: 0, e: 'Rural areas are sparsely populated countryside, often centered on farming.', tags: ['population', 'Urban & Rural'] },
  { q: 'Which of these is a typical "pull" factor drawing people to cities?', opts: ['Lack of clean water', 'A natural disaster', 'More job opportunities', 'Isolation'], a: 2, e: 'Better jobs and services pull people toward cities; hardships push them away from where they live.', tags: ['population', 'Urban & Rural'] },
  { q: 'Which region of the world is still largely rural, with a lower urban share?', opts: ['North America', 'Sub-Saharan Africa', 'Western Europe', 'Australia'], a: 1, e: 'Much of Sub-Saharan Africa remains rural, though it is urbanizing quickly.', tags: ['population', 'Urban & Rural'] },
  { q: 'What is a "suburb"?', opts: ['A city center', 'A rural farm', 'A national park', 'A residential area on the outskirts of a city'], a: 3, e: 'Suburbs are the mostly residential zones surrounding a city’s core.', tags: ['population', 'Urban & Rural'] },
  { q: 'The world’s most urbanized regions include:', opts: ['North America and Western Europe', 'Central Africa', 'The Himalayas', 'Rural South Asia'], a: 0, e: 'North America and Western Europe are among the most heavily urbanized regions.', tags: ['population', 'Urban & Rural'] },
  { q: 'A "metropolitan area" typically includes:', opts: ['Only the historic old town', 'A single street', 'A city plus its surrounding towns and suburbs', 'Just farmland'], a: 2, e: 'A metro area covers a core city together with the commuter towns and suburbs tied to it.', tags: ['population', 'Urban & Rural'] },

  // ── Level 6 — Migration & Movement ──
  { q: 'What is "immigration"?', opts: ['Leaving your country', 'Traveling for a holiday', 'Moving into a new country to settle', 'Moving between cities'], a: 2, e: 'Immigration is entering another country to live there.', tags: ['population', 'Migration'] },
  { q: 'What is "emigration"?', opts: ['Leaving your home country to live elsewhere', 'Arriving in a country', 'Being a tourist', 'Commuting to work'], a: 0, e: 'Emigration is leaving your home country to settle in another one.', tags: ['population', 'Migration'] },
  { q: 'A "refugee" is someone who:', opts: ['Moves abroad for a better job', 'Travels for tourism', 'Is studying abroad', 'Is forced to flee their country to escape war or persecution'], a: 3, e: 'Refugees are people compelled to leave their homeland due to conflict, violence, or persecution.', tags: ['population', 'Migration'] },
  { q: 'Which is a typical "push" factor causing people to leave a place?', opts: ['Better schools', 'War or conflict', 'Higher wages', 'A pleasant climate'], a: 1, e: 'Push factors like war, poverty, or disaster drive people away from where they live.', tags: ['population', 'Migration'] },
  { q: 'Which is a "pull" factor attracting migrants to a destination?', opts: ['Famine', 'Persecution', 'Better job opportunities', 'A natural disaster'], a: 2, e: 'Pull factors such as jobs, safety, and opportunity attract migrants to a new place.', tags: ['population', 'Migration'] },
  { q: 'The United States has historically been one of the world’s largest destinations for:', opts: ['Immigrants', 'Emigrants only', 'Returning refugees', 'Nomads'], a: 0, e: 'The U.S. has received more immigrants than any other country over its history.', tags: ['population', 'Migration'] },
  { q: 'An internally displaced person (IDP) differs from a refugee because they:', opts: ['Have crossed an ocean', 'Moved abroad for a job', 'Are tourists', 'Remain within their own country'], a: 3, e: 'IDPs are forced from their homes but stay inside their own country’s borders.', tags: ['population', 'Migration'] },
  { q: 'What are "remittances"?', opts: ['Travel visas', 'Money migrants send back to family in their home country', 'Border walls', 'Refugee camps'], a: 1, e: 'Remittances are earnings migrants send home, a major income source for many countries.', tags: ['population', 'Migration'] },

  // ── Level 7 — Languages & Peoples ──
  { q: 'Which language has the most native (first-language) speakers?', opts: ['English', 'Spanish', 'Hindi', 'Mandarin Chinese'], a: 3, e: 'Mandarin Chinese has the largest number of native speakers in the world.', tags: ['population', 'Languages'] },
  { q: 'Which language has the most total speakers (native plus second-language)?', opts: ['Mandarin Chinese', 'English', 'Spanish', 'Arabic'], a: 1, e: 'English has the most total speakers once second-language learners are counted.', tags: ['population', 'Languages'] },
  { q: 'Spanish is the dominant language across most of which region?', opts: ['Most of Latin America', 'All of Africa', 'South Asia', 'East Asia'], a: 0, e: 'Spanish is spoken across most of Latin America — Brazil being the main exception, where Portuguese is spoken.', tags: ['population', 'Languages'] },
  { q: 'Hindi is one of the most widely spoken languages, mainly in which country?', opts: ['China', 'Indonesia', 'India', 'Nigeria'], a: 2, e: 'Hindi is one of the most spoken languages of India.', tags: ['population', 'Languages'] },
  { q: 'Arabic is the dominant language across which region?', opts: ['Southern Africa', 'Scandinavia', 'Southeast Asia', 'The Middle East and North Africa'], a: 3, e: 'Arabic is widely spoken across the Middle East and North Africa.', tags: ['population', 'Languages'] },
  { q: 'Portuguese is the official language of which large South American country?', opts: ['Argentina', 'Brazil', 'Colombia', 'Peru'], a: 1, e: 'Brazil, the largest country in South America, has Portuguese as its official language.', tags: ['population', 'Languages'] },
  { q: 'Which country has the most native English speakers?', opts: ['United States', 'United Kingdom', 'India', 'Australia'], a: 0, e: 'The United States has by far the largest number of native English speakers.', tags: ['population', 'Languages'] },
  { q: 'Roughly how many distinct languages are spoken in the world today?', opts: ['About 100', 'About 700', 'About 7,000', 'About 70,000'], a: 2, e: 'Linguists count roughly 7,000 living languages worldwide, though many are endangered.', tags: ['population', 'Languages'] },

  // ── Level 8 — Population Growth & Decline ──
  { q: 'Which continent is projected to have the fastest population growth this century?', opts: ['Europe', 'Africa', 'Asia', 'Antarctica'], a: 1, e: 'Africa is expected to drive most of the world’s population growth through 2100.', tags: ['population', 'Growth & Decline'] },
  { q: 'The "birth rate" measures:', opts: ['Deaths per year', 'People moving in', 'Total population', 'Births per 1,000 people each year'], a: 3, e: 'The crude birth rate is the number of live births per 1,000 people in a year.', tags: ['population', 'Growth & Decline'] },
  { q: 'Many countries in Europe and East Asia now face:', opts: ['Runaway growth', 'Too many children', 'Aging populations and low birth rates', 'No cities'], a: 2, e: 'Low birth rates and longer lifespans are leaving these regions with aging populations.', tags: ['population', 'Growth & Decline'] },
  { q: 'Which country’s population has been shrinking, partly due to very low birth rates?', opts: ['Japan', 'Nigeria', 'India', 'Philippines'], a: 0, e: 'Japan’s population has been declining for years amid low birth rates and an aging society.', tags: ['population', 'Growth & Decline'] },
  { q: 'The fertility rate roughly needed to keep a population stable (replacement level) is about:', opts: ['1.0 children per woman', 'About 2.1 children per woman', '4.0 children per woman', '6.0 children per woman'], a: 1, e: 'Around 2.1 children per woman keeps a population stable over the long run.', tags: ['population', 'Growth & Decline'] },
  { q: 'Which country is expected to grow enormously, possibly becoming one of the largest by 2100?', opts: ['Germany', 'Russia', 'Italy', 'Nigeria'], a: 3, e: 'Nigeria’s rapid growth could make it one of the world’s most populous countries by 2100.', tags: ['population', 'Growth & Decline'] },
  { q: 'A "population pyramid" with a wide base indicates:', opts: ['An aging society', 'A shrinking population', 'Many young people and high birth rates', 'No children at all'], a: 2, e: 'A broad base means a large share of children and a fast-growing, youthful population.', tags: ['population', 'Growth & Decline'] },
  { q: 'China’s total population recently began to:', opts: ['Decline', 'Double', 'Triple', 'Reach 3 billion'], a: 0, e: 'China’s population started to decline in the early 2020s as births fell below deaths.', tags: ['population', 'Growth & Decline'] },

  // ── Level 9 — Cities of the World ──
  { q: 'Nairobi is the capital of which country?', opts: ['Nigeria', 'Ghana', 'Kenya', 'Tanzania'], a: 2, e: 'Nairobi is the capital and largest city of Kenya.', tags: ['population', 'Cities'] },
  { q: 'The city of Istanbul is in which country?', opts: ['Turkey', 'Greece', 'Egypt', 'Iran'], a: 0, e: 'Istanbul, straddling Europe and Asia, is Turkey’s largest city.', tags: ['population', 'Cities'] },
  { q: 'Buenos Aires is the capital of which country?', opts: ['Brazil', 'Chile', 'Uruguay', 'Argentina'], a: 3, e: 'Buenos Aires is the capital and largest city of Argentina.', tags: ['population', 'Cities'] },
  { q: 'Lagos, one of Africa’s largest cities, is in which country?', opts: ['Kenya', 'Nigeria', 'Ghana', 'South Africa'], a: 1, e: 'Lagos, in Nigeria, is one of Africa’s biggest and fastest-growing cities.', tags: ['population', 'Cities'] },
  { q: 'The city of Karachi is in which country?', opts: ['India', 'Bangladesh', 'Pakistan', 'Iran'], a: 2, e: 'Karachi is Pakistan’s largest city and a major port.', tags: ['population', 'Cities'] },
  { q: 'Ho Chi Minh City is the largest city of which country?', opts: ['Vietnam', 'Thailand', 'Cambodia', 'Laos'], a: 0, e: 'Ho Chi Minh City, formerly Saigon, is the largest city in Vietnam.', tags: ['population', 'Cities'] },
  { q: 'The city of Casablanca is in which country?', opts: ['Egypt', 'Algeria', 'Tunisia', 'Morocco'], a: 3, e: 'Casablanca is the largest city of Morocco.', tags: ['population', 'Cities'] },
  { q: 'The city of Toronto is in which country?', opts: ['United States', 'Canada', 'United Kingdom', 'Australia'], a: 1, e: 'Toronto is the largest city in Canada.', tags: ['population', 'Cities'] },

  // ── Level 10 — Population Mastery ──
  { q: 'Of these four countries, which has the largest population?', opts: ['Germany', 'France', 'United Kingdom', 'Ethiopia'], a: 3, e: 'Ethiopia has over 120 million people — more than Germany, France, or the UK.', tags: ['population', 'Mastery'] },
  { q: 'Which country recently overtook China as most populous, and roughly how large is it?', opts: ['China, ~1.2 billion', 'India, ~1.4 billion', 'United States, ~330 million', 'Indonesia, ~280 million'], a: 1, e: 'India passed China in 2023 and now has about 1.4 billion people.', tags: ['population', 'Mastery'] },
  { q: 'Of these, which has the largest metropolitan population?', opts: ['Tokyo', 'London', 'Paris', 'Moscow'], a: 0, e: 'Greater Tokyo, at roughly 37 million, dwarfs the metro areas of London, Paris, and Moscow.', tags: ['population', 'Mastery'] },
  { q: 'Of these four countries, which has the largest population?', opts: ['Canada', 'Australia', 'Bangladesh', 'Argentina'], a: 2, e: 'Bangladesh has over 170 million people, far more than Canada, Australia, or Argentina.', tags: ['population', 'Mastery'] },
  { q: 'Which statement about population density is TRUE?', opts: ['Russia is the densest country', 'Australia is very densely populated', 'Bangladesh has very low density', 'Monaco is among the most densely populated'], a: 3, e: 'Monaco is among the most densely populated places on Earth; Russia and Australia are sparse, and Bangladesh is very dense.', tags: ['population', 'Mastery'] },
  { q: 'Which region is projected to account for most of the world’s population growth to 2100?', opts: ['Europe', 'Sub-Saharan Africa', 'East Asia', 'North America'], a: 1, e: 'Sub-Saharan Africa is expected to supply the majority of global population growth this century.', tags: ['population', 'Mastery'] },
  { q: 'Which pairing about world languages is correct?', opts: ['Mandarin most native speakers; English most total speakers', 'English most native; Mandarin most total', 'Spanish most native; Hindi most total', 'Hindi most native; Arabic most total'], a: 0, e: 'Mandarin Chinese leads in native speakers while English leads in total speakers.', tags: ['population', 'Mastery'] },
  { q: 'Which is the most populous country in Africa, and roughly how large?', opts: ['Egypt, ~110 million', 'South Africa, ~60 million', 'Nigeria, over 200 million', 'Ethiopia, ~30 million'], a: 2, e: 'Nigeria, with more than 200 million people, is Africa’s most populous country.', tags: ['population', 'Mastery'] },
];
