// Basic Tactics roadmap questions (80): 10 levels × 8, easiest → hardest.
// Covers forks, pins, skewers, discovered & double attacks, removing the
// defender, and trapped pieces.

import type { Seed } from './roadmap-build';

export const tacticsSeeds: Seed[] = [
  // ── Level 1 — What Is a Tactic? ───────────────────────────────────────
  { q: 'In chess, what is a "tactic"?', opts: ['A short forcing sequence that wins material or delivers mate','A long-term plan spanning the whole game','A way to arrange pawns for defense','An opening you memorize move by move'], a: 0, e: 'A tactic is a short forcing sequence that wins material or delivers checkmate.', tags: ['Chess','Tactics'] },
  { q: 'Tactics usually rely on moves that are...', opts: ['Slow and quiet','Forcing, like checks, captures, and threats','Purely defensive','Chosen at random'], a: 1, e: 'Tactics work because forcing moves (checks, captures, threats) limit the opponent\'s replies.', tags: ['Chess','Tactics'] },
  { q: 'What is the typical goal of a tactic?', opts: ['To lose time','To develop slowly','To win material or deliver mate','To offer a draw'], a: 2, e: 'A tactic aims to win material or force checkmate.', tags: ['Chess','Tactics'] },
  { q: 'Which of these is a common building block of tactics?', opts: ['Castling early','Trading queens','Pushing every pawn','A check that forces a reply'], a: 3, e: 'Checks are forcing, so they are a key building block of tactics.', tags: ['Chess','Tactics'] },
  { q: 'Why are forcing moves important in tactics?', opts: ['They limit the opponent\'s options so you can calculate','They only waste the opponent\'s time','They always lead to a draw','They would otherwise be illegal'], a: 0, e: 'Forcing moves restrict the opponent\'s replies, letting you calculate the sequence to the end.', tags: ['Chess','Tactics'] },
  { q: 'A "combination" in chess is best described as...', opts: ['A single quiet waiting move','A forcing sequence of moves, often with a sacrifice, that gains an advantage','A way to castle safely','A fixed pawn structure'], a: 1, e: 'A combination is a forcing sequence, often involving a sacrifice, that yields an advantage.', tags: ['Chess','Tactics'] },
  { q: 'How does strategy differ from tactics?', opts: ['Strategy is only about captures','Strategy is only one-move threats','Strategy is long-term planning and positioning, tactics are short forcing sequences','Strategy is only about checkmate'], a: 2, e: 'Strategy concerns long-term plans, while tactics are short forcing sequences.', tags: ['Chess','Tactics'] },
  { q: 'Which statement about tactics is TRUE?', opts: ['Tactics can never involve checkmate','Tactics only work in the opening','A tactic can win material even without giving check','Only the queen can create tactics'], a: 2, e: 'Many tactics win material through threats and captures without any check.', tags: ['Chess','Tactics'] },

  // ── Level 2 — The Fork ────────────────────────────────────────────────
  { q: 'What is a fork?', opts: ['One piece attacking two or more targets at once','Two pieces defending one square','A pawn reaching the last rank','A special kind of castling'], a: 0, e: 'A fork is a single piece attacking two or more targets simultaneously.', tags: ['Chess','Tactics'] },
  { q: 'Which piece is especially famous for forking?', opts: ['The bishop','The knight','The rook','The king'], a: 1, e: 'The knight is the most famous forking piece because of its unique jumping move.', tags: ['Chess','Tactics'] },
  { q: 'A pawn fork attacks two enemy pieces...', opts: ['Along a file','Straight ahead','Diagonally, one to each side','By jumping over them'], a: 2, e: 'A pawn attacks diagonally, so it can fork two pieces at once, one on each diagonal.', tags: ['Chess','Tactics'] },
  { q: 'A "family fork" by a knight typically hits...', opts: ['Two pawns only','Two rooks only','A bishop and a knight only','The king and queen (often more) at once'], a: 3, e: 'A family fork is a knight forking the king and queen, and often other pieces, simultaneously.', tags: ['Chess','Tactics'] },
  { q: 'Why is a knight fork of the enemy king and queen so strong?', opts: ['The king must move out of check, so the queen is then lost','The knight immediately promotes','It forces an automatic draw','It lets you castle for free'], a: 0, e: 'Because the king must escape check, the forked queen cannot be saved.', tags: ['Chess','Tactics'] },
  { q: 'A knight on e5 attacks both c6 and f7 at the same time. This is an example of a...', opts: ['Pin','Fork','Skewer','Castling move'], a: 1, e: 'One knight hitting two squares (c6 and f7) at once is a fork.', tags: ['Chess','Tactics'] },
  { q: 'Which pieces can deliver a fork?', opts: ['Only knights','Only the queen','Any piece, including pawns and the king','Only rooks and bishops'], a: 2, e: 'Any piece can fork; even a pawn or the king can attack two targets at once.', tags: ['Chess','Tactics'] },
  { q: 'Your knight forks the enemy king and an undefended rook. Roughly how much material do you win?', opts: ['Nothing','A pawn (about 1 point)','A bishop (about 3 points)','A rook (about 5 points), since the king must move'], a: 3, e: 'The king must escape check, so you capture the rook, winning about 5 points.', tags: ['Chess','Tactics'] },

  // ── Level 3 — The Pin ─────────────────────────────────────────────────
  { q: 'What is a pin?', opts: ['A piece is stuck because a more valuable piece sits behind it on the same line','Two pieces attack one square together','A pawn reaches the last rank','A king that is in check'], a: 0, e: 'In a pin, a piece cannot (or should not) move because a more valuable piece is behind it on the same line.', tags: ['Chess','Tactics'] },
  { q: 'An ABSOLUTE pin is a pin against the...', opts: ['Queen','King, so moving the pinned piece is illegal','Rook','Bishop'], a: 1, e: 'An absolute pin is against the king, making it illegal to move the pinned piece.', tags: ['Chess','Tactics'] },
  { q: 'A RELATIVE pin is one where...', opts: ['The pinned piece is the king','Moving the pinned piece is always illegal','Moving is legal but loses material, because a more valuable piece is behind','There is no piece behind at all'], a: 2, e: 'In a relative pin the piece behind is valuable (not the king), so moving is legal but costly.', tags: ['Chess','Tactics'] },
  { q: 'Which piece can NEVER create a pin?', opts: ['Bishop','Rook','Queen','Knight'], a: 3, e: 'Only line pieces (bishop, rook, queen) can pin; a knight can never pin.', tags: ['Chess','Tactics'] },
  { q: 'A bishop pins along...', opts: ['Diagonals','Ranks only','Files only','L-shaped paths'], a: 0, e: 'A bishop moves and pins along diagonals.', tags: ['Chess','Tactics'] },
  { q: 'A rook creates pins along...', opts: ['Diagonals','Ranks and files','L-shaped paths','Only the central squares'], a: 1, e: 'A rook pins along ranks and files, the lines it moves on.', tags: ['Chess','Tactics'] },
  { q: 'Why is a pinned piece often a good target?', opts: ['It can move away freely','It always defends the king','It cannot move away, so you can pile more attackers onto it','It is about to promote'], a: 2, e: 'A pinned piece cannot escape, so adding more attackers can win it.', tags: ['Chess','Tactics'] },
  { q: 'A white bishop on b5 pins a black knight on c6 against the black king on d7. May the knight legally move away?', opts: ['Yes, to any square it likes','Yes, but only forward','Only to capture a pawn','No — it is absolutely pinned, so moving it would illegally expose the king'], a: 3, e: 'The knight is pinned to the king, so moving it is illegal.', tags: ['Chess','Tactics'] },

  // ── Level 4 — The Skewer ──────────────────────────────────────────────
  { q: 'A skewer is best described as...', opts: ['Like a pin reversed: the more valuable piece is in front and must move, exposing a lesser piece behind','Two knights attacking together','A pawn forking two pieces','A queenside castling move'], a: 0, e: 'A skewer is a reversed pin: the valuable piece is in front, and when it moves the piece behind is captured.', tags: ['Chess','Tactics'] },
  { q: 'In a skewer, which piece is in front (attacked first)?', opts: ['The less valuable piece','The more valuable piece','A pawn, always','A knight, always'], a: 1, e: 'In a skewer the more valuable piece stands in front and is forced to move.', tags: ['Chess','Tactics'] },
  { q: 'Which pieces can deliver a skewer?', opts: ['Only knights','Only pawns','Line pieces: bishop, rook, or queen','The king only'], a: 2, e: 'Skewers, like pins, are made by line pieces: bishops, rooks, and queens.', tags: ['Chess','Tactics'] },
  { q: 'The key difference between a pin and a skewer is...', opts: ['They are exactly identical','A skewer can only use knights','A pin only works in the endgame','Which piece is in front: the valuable one in front for a skewer, behind for a pin'], a: 3, e: 'In a skewer the valuable piece is in front; in a pin it is behind.', tags: ['Chess','Tactics'] },
  { q: 'A white rook checks a black king, and when the king steps aside a black queen behind it is captured. This is a...', opts: ['Skewer','Pin','Fork','Discovered check'], a: 0, e: 'The king (more valuable) is forced to move, exposing the queen behind it — a classic skewer.', tags: ['Chess','Tactics'] },
  { q: 'Why are skewers delivered with check especially effective?', opts: ['Check can simply be ignored','The king MUST move, guaranteeing the piece behind is exposed','Giving check is illegal','They promote a pawn for free'], a: 1, e: 'A check forces the king to move, so the piece behind it is left to be captured.', tags: ['Chess','Tactics'] },
  { q: 'A bishop skewers along which lines?', opts: ['Ranks','Files','Diagonals','L-shaped paths'], a: 2, e: 'A bishop, being a diagonal mover, skewers along diagonals.', tags: ['Chess','Tactics'] },
  { q: 'A white queen on a1 checks a black king on a5 along the a-file, with a black rook on a8 behind the king. What is White\'s idea?', opts: ['Offer a draw','Castle to safety','Retreat the queen','The king must step off the file, then the queen captures the rook on a8 — a skewer'], a: 3, e: 'The king is skewered to the rook: it must move, and White wins the rook on a8.', tags: ['Chess','Tactics'] },

  // ── Level 5 — Discovered Attacks ──────────────────────────────────────
  { q: 'A discovered attack happens when...', opts: ['Moving one piece uncovers an attack from a piece behind it','A pawn promotes to a queen','Two pawns advance together','You castle kingside'], a: 0, e: 'A discovered attack occurs when moving a front piece unmasks an attack from a piece behind it.', tags: ['Chess','Tactics'] },
  { q: 'A discovered CHECK is when...', opts: ['The moving piece itself gives check','The unmasked piece behind gives the check','A pawn gives the only check','No one is actually in check'], a: 1, e: 'In a discovered check, the piece revealed behind the moving piece gives the check.', tags: ['Chess','Tactics'] },
  { q: 'A double check means that...', opts: ['One piece checks twice in a row','A pawn and the king check together','Both the moving piece and the unmasked piece give check at once','Two players are in check'], a: 2, e: 'A double check is when the moving piece and the revealed piece both give check simultaneously.', tags: ['Chess','Tactics'] },
  { q: 'How can a double check be answered?', opts: ['By blocking with any piece','By capturing one of the two checkers','By simply ignoring it','Only by moving the king'], a: 3, e: 'A double check can only be met by a king move, since no single move stops both checkers.', tags: ['Chess','Tactics'] },
  { q: 'Why are discovered attacks so powerful?', opts: ['The moving piece can make its own threat while unveiling another, creating two threats at once','They are always quiet moves','They give away material','They can only defend'], a: 0, e: 'The moving piece can attack something while unveiling another attack, producing two threats.', tags: ['Chess','Tactics'] },
  { q: 'In a discovered check, which piece can often grab material freely?', opts: ['The king','The moving (front) piece, since the opponent must first deal with the check','Only a pawn','No piece can'], a: 1, e: 'While the opponent must respond to the discovered check, the moving piece can safely capture.', tags: ['Chess','Tactics'] },
  { q: 'What must be "in front" to set up a discovered attack?', opts: ['A line piece','The enemy king','A piece that, when it moves, unmasks a line piece behind it','A rook, specifically'], a: 2, e: 'The front piece moves aside to reveal a bishop, rook, or queen lined up behind it.', tags: ['Chess','Tactics'] },
  { q: 'A double check is especially dangerous mainly because...', opts: ['It can be blocked very easily','You can capture both checkers in one move','It is not really a check','The defender cannot block or capture his way out — the king is forced to run'], a: 3, e: 'Since no single move removes both checks, the king must move, often into a mating net.', tags: ['Chess','Tactics'] },

  // ── Level 6 — Double Attacks ──────────────────────────────────────────
  { q: 'A double attack is...', opts: ['Creating two threats at once','A single quiet developing move','A castling maneuver','A pawn promotion'], a: 0, e: 'A double attack means creating two threats simultaneously so the opponent cannot meet both.', tags: ['Chess','Tactics'] },
  { q: 'A fork is a specific kind of...', opts: ['Pin','Double attack','Endgame technique','Opening trap'], a: 1, e: 'A fork is a double attack delivered by one piece hitting two targets.', tags: ['Chess','Tactics'] },
  { q: 'Besides a fork by one piece, a double attack can also be made by...', opts: ['Only knights','Only pawns','Two different pieces each creating a threat on the same move (for example, a discovered attack)','Only the king'], a: 2, e: 'Double attacks arise from forks but also from moves like discovered attacks, where two pieces threaten at once.', tags: ['Chess','Tactics'] },
  { q: 'Why does a double attack often win material?', opts: ['It gives check twice','It promotes a pawn','It is always a sacrifice','The opponent can usually parry only one of the two threats'], a: 3, e: 'With two threats at once, the defender can typically save only one of the targets.', tags: ['Chess','Tactics'] },
  { q: 'The queen is a great double-attacker because...', opts: ['It moves like a rook and a bishop, so it can hit two distant targets at once','It can jump like a knight','It is only worth 3 points','It can never be captured'], a: 0, e: 'The queen\'s long range on lines and diagonals lets it threaten two targets simultaneously.', tags: ['Chess','Tactics'] },
  { q: 'A queen that attacks an undefended piece AND threatens mate at the same time is using a...', opts: ['Pin','Double attack','Skewer','Simple retreat'], a: 1, e: 'Threatening a piece and mate together is a double attack; the opponent cannot stop both.', tags: ['Chess','Tactics'] },
  { q: 'To find double attacks, you should look for...', opts: ['Only quiet pawn moves','Only ways to trade queens','Undefended enemy pieces and the enemy king that can be hit together','Ways to force a draw'], a: 2, e: 'Spot loose (undefended) pieces and the king, then find one move that threatens two of them.', tags: ['Chess','Tactics'] },
  { q: 'A "loose" piece matters in double attacks because...', opts: ['It is very well defended','It can never be captured','It blocks your own pieces','It is undefended, so one attack on it already wins it once you make a second threat'], a: 3, e: 'Loose (undefended) pieces are prime targets, since one threat against them, paired with another threat, wins material.', tags: ['Chess','Tactics'] },

  // ── Level 7 — Removing the Defender ───────────────────────────────────
  { q: '"Removing the defender" means...', opts: ['Capturing or deflecting the piece that guards a key square or piece','Developing your own knight','Castling your king to safety','Trading off the queens'], a: 0, e: 'Removing the defender eliminates or deflects the piece protecting a key target.', tags: ['Chess','Tactics'] },
  { q: 'Another common name for this tactic is...', opts: ['Overprotection','Removing the guard','Zugzwang','Fianchetto'], a: 1, e: '"Removing the defender" is also called "removing the guard."', tags: ['Chess','Tactics'] },
  { q: 'If a knight is defended only by one bishop, you can win the knight by...', opts: ['Ignoring the bishop entirely','Castling immediately','Capturing or driving away that bishop first','Offering a draw'], a: 2, e: 'Eliminating or deflecting the sole defender leaves the knight hanging.', tags: ['Chess','Tactics'] },
  { q: '"Deflection" removes a defender by...', opts: ['Defending it even more','Blocking it with a pawn','Pinning your own piece to it','Luring or forcing it to move away from its defensive duty'], a: 3, e: 'Deflection forces the defending piece off the square it needs to guard.', tags: ['Chess','Tactics'] },
  { q: 'Removing a key defender near the enemy king can lead to...', opts: ['Checkmate or winning material','An automatic draw','Losing your own queen','Nothing useful at all'], a: 0, e: 'Stripping away a defender of the king can open the way to mate or decisive material gain.', tags: ['Chess','Tactics'] },
  { q: 'Before capturing a well-defended piece, you should check...', opts: ['Only the clock','Whether removing or overloading its defender lets you win it','The name of the opening','Nothing in particular'], a: 1, e: 'Assess whether you can remove, deflect, or overload the defender to win the target.', tags: ['Chess','Tactics'] },
  { q: 'An "overloaded" piece is one that...', opts: ['Carries too much material','Is pinned to the king','Is defending two things at once and cannot cover both','Has just promoted'], a: 2, e: 'An overloaded defender guards multiple targets and fails when forced to choose between them.', tags: ['Chess','Tactics'] },
  { q: 'A pawn on e5 is defended only by a knight on f3. You have a bishop that can capture that knight. What is the tactical idea?', opts: ['Push a distant pawn','Castle first','Trade a pair of rooks','Capture the knight to remove the defender, then win the e5 pawn'], a: 3, e: 'Taking the sole defender (the f3 knight) leaves the e5 pawn undefended to be captured.', tags: ['Chess','Tactics'] },

  // ── Level 8 — Trapped Pieces ──────────────────────────────────────────
  { q: 'A "trapped piece" is one that...', opts: ['Has no safe squares and can be won','Is still on its starting square','Is defended twice over','Has just promoted'], a: 0, e: 'A trapped piece has no safe escape squares, so it can be captured.', tags: ['Chess','Tactics'] },
  { q: 'To trap an enemy piece, you usually...', opts: ['Give it more open squares','Cover its escape squares while attacking it','Trade it off at once','Simply ignore it'], a: 1, e: 'You trap a piece by attacking it while controlling all of its escape squares.', tags: ['Chess','Tactics'] },
  { q: 'Which piece is notoriously easy to trap deep in enemy territory?', opts: ['The king','A single pawn','A greedy queen or bishop that grabs a pawn and gets cut off','A rook on its home square'], a: 2, e: 'A queen or bishop that grabs material and ventures too far can be surrounded and trapped.', tags: ['Chess','Tactics'] },
  { q: 'A knight on the rim can be trapped because...', opts: ['It is much faster there','It always defends the king','It is about to promote','It has fewer squares to jump to from the edge'], a: 3, e: 'On the edge a knight controls fewer squares, making it easier to trap.', tags: ['Chess','Tactics'] },
  { q: 'The classic "grab the b2 or b7 pawn with the queen" can backfire when...', opts: ['The queen gets trapped by developing moves that cut off its retreat','It always wins a clean pawn','It delivers instant check','It promotes a pawn'], a: 0, e: 'Snatching that pawn can leave the queen cornered, as the opponent gains time and cuts off its escape.', tags: ['Chess','Tactics'] },
  { q: 'To win a trapped piece, you often need to...', opts: ['Give an aimless check','Bring another attacker so its lone defender or single escape is not enough','Offer a draw','Castle immediately'], a: 1, e: 'Adding attackers overwhelms a trapped piece that can neither run nor be sufficiently defended.', tags: ['Chess','Tactics'] },
  { q: 'A bishop that captures a rook-pawn (such as on h2 or a2) can be trapped by...', opts: ['A distant queen check','Quick castling','A pawn advance that attacks it and takes away its only retreat square','A pawn promotion'], a: 2, e: 'Pushing a pawn to hit the bishop and cover its escape is the classic way to win a "trapped bishop."', tags: ['Chess','Tactics'] },
  { q: 'You attack an enemy rook that has exactly one flight square, and you can also cover that square with a bishop. The best plan is...', opts: ['Trade queens first','Push a far-away pawn','Give an irrelevant check','Cover the flight square, leaving the rook trapped, then capture it'], a: 3, e: 'Controlling its only escape square traps the rook so you can win it.', tags: ['Chess','Tactics'] },

  // ── Level 9 — Spotting Tactics ────────────────────────────────────────
  { q: 'A knight on d5 attacks a queen on f6 and a rook on c7 at the same time. What tactic is this?', opts: ['A fork','A pin','A skewer','A discovered check'], a: 0, e: 'One knight hitting the queen (f6) and rook (c7) at once is a fork.', tags: ['Chess','Tactics'] },
  { q: 'A bishop attacks an enemy knight, and directly behind that knight on the same diagonal sits the enemy queen, so the knight dare not move. What is this?', opts: ['A skewer','A pin (a relative pin against the queen)','A fork','A double check'], a: 1, e: 'The knight is pinned: moving it would lose the more valuable queen behind it.', tags: ['Chess','Tactics'] },
  { q: 'A rook gives check along a rank; the king steps aside and the rook then captures an enemy queen that had been behind the king. What tactic won the queen?', opts: ['A pin','A fork','A skewer','A trapped piece'], a: 2, e: 'The king (in front) was forced to move, exposing the queen behind it — a skewer.', tags: ['Chess','Tactics'] },
  { q: 'You move your knight, revealing a rook behind it that gives check, and the knight itself attacks the enemy queen. What is this?', opts: ['A simple pin','A plain skewer','A trapped piece','A discovered check that also wins the queen'], a: 3, e: 'Moving the knight unveils the rook\'s check while the knight attacks the queen — a discovered check winning material.', tags: ['Chess','Tactics'] },
  { q: 'An enemy bishop is defended only by a pawn. You capture that pawn with check. After the forced reply, the bishop is...', opts: ['Undefended and can be captured','Suddenly promoted','Completely safe','Pinned to your own king'], a: 0, e: 'Removing the defending pawn with tempo (via check) leaves the bishop hanging.', tags: ['Chess','Tactics'] },
  { q: 'A queen on h5 attacks an undefended bishop on b5 and also threatens mate on f7. The opponent can...', opts: ['Stop both threats with one move','Meet only one of the two threats, so White wins','Ignore both threats safely','Castle out of everything'], a: 1, e: 'It is a double attack; the defender can meet only one threat, so White wins material or mates.', tags: ['Chess','Tactics'] },
  { q: 'A white pawn on e4 attacks a black knight on d5 and a black bishop on f5 at the same time. This is a...', opts: ['Skewer','Pin','Pawn fork','Discovered check'], a: 2, e: 'A pawn attacking two pieces diagonally (d5 and f5) is a pawn fork.', tags: ['Chess','Tactics'] },
  { q: 'A black knight is the king\'s only guard of the g7 mating square. White\'s strongest tactical try is to...', opts: ['Trade a pair of rooks','Advance a queenside pawn','Offer a draw','Remove or deflect that knight, then deliver mate on g7'], a: 3, e: 'Eliminating the defender of g7 opens the square for a mating blow.', tags: ['Chess','Tactics'] },

  // ── Level 10 — Tactics Mastery ────────────────────────────────────────
  { q: 'Which description fits a discovered DOUBLE check?', opts: ['The moving piece and the piece it unmasks both give check, forcing a king move','A pawn forks two pieces at once','A rook pins a knight to the king','A bishop skewers a queen to a rook'], a: 0, e: 'In a discovered double check, both the moving piece and the revealed piece give check, so only a king move helps.', tags: ['Chess','Tactics'] },
  { q: 'You can win a queen that is defended by a single rook by first...', opts: ['Checking the king aimlessly','Deflecting or capturing the defending rook (removing the defender), then taking the queen','Promoting a distant pawn','Trading off the bishops'], a: 1, e: 'Remove the queen\'s only defender first, then capture the now-undefended queen.', tags: ['Chess','Tactics'] },
  { q: 'A relative pin differs from an absolute pin in that...', opts: ['A relative pin is illegal to break','Both are pins against the king','In a relative pin the pinned piece MAY legally move (losing material), while in an absolute pin it may not','A relative pin can only use knights'], a: 2, e: 'A relative pin is against a valuable piece (legal but costly to break); an absolute pin is against the king (illegal to break).', tags: ['Chess','Tactics'] },
  { q: 'Which combination could a single knight move create?', opts: ['A pin and a skewer together','Two absolute pins at once','A castling and a promotion','A discovered check (unmasking a rook) plus a fork of the queen'], a: 3, e: 'Moving a knight can unveil a rook\'s check while the knight itself forks the queen — a discovered attack combined with a fork.', tags: ['Chess','Tactics'] },
  { q: 'Using the piece values (pawn 1, knight 3, bishop 3, rook 5, queen 9): you give up a bishop to win a rook, then a knight fork wins the queen. Is the combination worth it?', opts: ['Yes — you give 3 and gain 5 and then 9, a large net material gain','No, it loses material overall','Only if it forces a draw','No, you should never sacrifice'], a: 0, e: 'Giving up 3 points to win 5 and then 9 is a huge net gain, so the combination is worth it.', tags: ['Chess','Tactics'] },
  { q: 'The only reliable way out of a double check is...', opts: ['Blocking with the queen','Moving the king','Capturing one checker with a pawn','Giving a counter-check with a rook'], a: 1, e: 'A double check can only be answered by moving the king.', tags: ['Chess','Tactics'] },
  { q: 'A knight stuck on the edge, an overloaded defender, and a loose enemy queen all suggest you should look for...', opts: ['A quiet pawn move','A quick draw offer','A tactic — a trap, a removal of the defender, or a double attack','An early castle'], a: 2, e: 'These features (a trapped edge knight, an overloaded defender, a loose queen) are classic tactical signals.', tags: ['Chess','Tactics'] },
  { q: 'You give a rook check; the enemy king must move because it cannot block or capture; behind the king stands the queen, which you then capture. You have executed a...', opts: ['Relative pin','Pawn fork','Discovered attack','Skewer that wins the queen'], a: 3, e: 'Forcing the more valuable king to move and capturing the queen behind it is a skewer.', tags: ['Chess','Tactics'] },
];
