import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Betting Strategy roadmap bank (rm-pkbet-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const bettingStrategyTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-pkbet-1': { introduction: 'Zamysli se, proč vlastně vkládáme žetony do banku.', question: 'Jaké jsou dva základní důvody, proč v pokeru sázet?', options: ['Na hodnotu a jako blaf', 'Abychom složili a checkovali', 'Abychom dorovnávali a navyšovali', 'Pro štěstí a kvůli tellům'], explanation: 'Téměř každá sázka je buď hodnotová (chceme, aby dorovnaly horší ruce), nebo blaf (chceme, aby lepší ruce složily).' },
  'rm-pkbet-2': { introduction: 'Kdo má tvou hodnotovou sázku dorovnat?', question: 'Hodnotová sázka má být dorovnána jakým typem ruky?', options: ['Horší rukou', 'Lepší rukou', 'Pouze nuts', 'Pouze složenou rukou'], explanation: 'Hodnotově sázíš, abys získal žetony od rukou, které jsou horší než ta tvá, ale přesto pravděpodobně dorovnají.' },
  'rm-pkbet-3': { introduction: 'Kdy blaf vydělá?', question: 'Blaf uspěje, když soupeře přinutí k čemu?', options: ['Složit lepší ruku', 'Dorovnat s horší rukou', 'Navýšit s nuts', 'Checknout za tebou'], explanation: 'Čistý blaf získá bank jedině tak, že donutí ruku, která tě poráží, aby složila.' },
  'rm-pkbet-4': { introduction: 'Jde o sázku proti dotahujícím rukám.', question: 'Sázka „pro ochranu" míří především k čemu?', options: ['Odepřít soupeřům levné dotahy, aby tě nepřetáhli', 'Zaručit, že vyhraješ ve showdownu', 'Postavit co největší bank', 'Skrýt sílu tvé ruky'], explanation: 'Ochranná sázka nechá dotahující ruce platit a odepře jim ekvitu, kterou by získaly zdarma z další karty.' },
  'rm-pkbet-5': { introduction: 'Silná ruka na mokrém boardu.', question: 'Flopneš top set na mokrém boardu plném dotahů. Sázka zde slouží především k...', options: ['Hodnotě a ochraně', 'Čistému blafu', 'Blocker sázce', 'Pouze k vyvážení'], explanation: 'Silná hotová ruka sází, aby ji dorovnaly horší ruce a aby platily četné dotahy, čímž spojuje hodnotu s ochranou.' },
  'rm-pkbet-6': { introduction: 'Máš nejlepší možnou ruku, co teď chceš?', question: 'Když držíš efektivní nuts, hlavním cílem tvé sázky je...', options: ['Být dorovnán horšími rukami', 'Přimět všechny složit', 'Udržet bank malý', 'Vyvolat check'], explanation: 'S nejlepší rukou chceš akci, takže sázíš a volíš velikost tak, abys maximalizoval dorovnání od horších rukou.' },
  'rm-pkbet-7': { introduction: 'Který z těchto důvodů není platný?', question: 'Co z následujícího NENÍ důvod vložit žetony do banku?', options: ['Protože nerad checkuješ', 'Získat hodnotu od horších rukou', 'Vytlačit lepší ruce', 'Odepřít ekvitu dotahům'], explanation: 'Sázka má mít vždy účel (hodnota, blaf nebo ochrana); sázet jen proto, abys nemusel checkovat, není důvod.' },
  'rm-pkbet-8': { introduction: 'Sázka s těsnou převahou.', question: 'Pojem „tenká hodnotová sázka" označuje sázku s rukou, která...', options: ['Je jen mírně před rukami, které ji dorovnají', 'Je jasné nuts', 'Nemá vůbec žádnou hodnotu ve showdownu', 'Nikdy nemůže být dorovnána horší rukou'], explanation: 'Tenká hodnota znamená sázet okrajovou hotovou ruku, kterou dorovná směs rukou, ale dost horších na to, abys vydělal.' },

  'rm-pkbet-9': { introduction: 'Velikost sázky se počítá vůči banku.', question: 'V banku je 100 $ a vsadíš „půl banku". Kolik sázíš?', options: ['50 $', '25 $', '100 $', '150 $'], explanation: 'Velikost sázky se vyjadřuje vůči banku; polovina banku 100 $ je sázka 50 $.' },
  'rm-pkbet-10': { introduction: 'Co znamená sázka o velikosti banku?', question: 'Sázka „o velikosti banku" znamená, že tvá sázka se rovná...', options: ['Aktuální velikosti banku', 'Celému tvému stacku', 'Velkému blindu', 'Polovině banku'], explanation: 'Sázka o velikosti banku je částka rovnající se žetonům, které už jsou v banku před tvou sázkou.' },
  'rm-pkbet-11': { introduction: 'Sázka větší než bank.', question: '„Overbet" je sázka, která je...', options: ['Větší než aktuální bank', 'Přesně poloviční vůči banku', 'Rovná velkému blindu', 'Menší než min-bet'], explanation: 'Overbet přesahuje velikost banku, vyvíjí maximální tlak a rychle staví bank.' },
  'rm-pkbet-12': { introduction: 'Spočítej pot odds proti sázce o půl banku.', question: 'Když čelíš sázce o půl banku, jakou ekvitu potřebuješ k ziskovému dorovnání?', options: ['Přibližně 25 %', 'Přibližně 50 %', 'Přibližně 10 %', 'Přibližně 40 %'], explanation: 'Riskuješ 50 $, abys vyhrál 150 $ (bank 100 $ + sázka 50 $), takže potřebuješ 50/200 = 25 % ekvity.' },
  'rm-pkbet-13': { introduction: 'Pot odds proti sázce o velikosti banku.', question: 'Když čelíš sázce o velikosti banku, jakou ekvitu zhruba potřebuješ k dorovnání?', options: ['Přibližně 33 %', 'Přibližně 25 %', 'Přibližně 50 %', 'Přibližně 20 %'], explanation: 'Dorovnáváš bank, abys vyhrál bank plus své dorovnání: riskuješ 1, abys vyhrál 2, tedy 1/3 = 33 % ekvity.' },
  'rm-pkbet-14': { introduction: 'Jak často musí blaf projít?', question: 'Aby byl BLAF o půl banku ziskově vyrovnaný, jak často musí soupeř složit?', options: ['Přibližně ve 33 % případů', 'Přibližně v 50 % případů', 'Přibližně ve 25 % případů', 'Přibližně v 66 % případů'], explanation: 'Riskuješ 0,5, abys vyhrál 1, takže blaf musí projít v 0,5/1,5 = 33 % případů, aby byl vyrovnaný.' },
  'rm-pkbet-15': { introduction: 'Velká sázka a struktura rozsahu.', question: 'Větší velikosti sázek obvykle činí tvůj sázecí rozsah více...', options: ['Polarizovaným (nutované ruce nebo blafy)', 'Sloučeným (spousta středních rukou)', 'Náhodným', 'Pasivním'], explanation: 'Velké sázky riskují mnoho, aby vyhrály mnoho, takže odpovídají polarizovanému rozsahu silné hodnoty a blafů, ne středním rukám.' },
  'rm-pkbet-16': { introduction: 'Proč měřit velikost vůči banku?', question: 'Proč se velikost sázky obvykle měří vůči banku, a ne v pevných dolarech?', options: ['Protože pot odds a tlak se škálují s velikostí banku', 'Protože se dolary těžko počítají', 'Protože blindy se nikdy nemění', 'Protože stacky jsou vždy stejné'], explanation: 'Šance, které nabízíš, i páka, kterou vyvíjíš, závisí na poměru sázky k banku, proto se velikost udává vůči banku.' },

  'rm-pkbet-17': { introduction: 'Kdo dělá continuation bet?', question: '„Continuation bet" (c-bet) je sázka na flopu, kterou dělá...', options: ['Preflopový agresor', 'Hráč, který preflop dorovnal', 'Pouze velký blind', 'Ten, kdo je poslední na tahu'], explanation: 'C-bet pokračuje v agresi: hráč, který navýšil preflop, naváže sázkou na flopu.' },
  'rm-pkbet-18': { introduction: 'Na jakém boardu c-bet nejlépe funguje?', question: 'Na jaké struktuře flopu je vysokofrekvenční c-bet obecně nejúčinnější?', options: ['Suchý, nesouvislý board jako K-7-2', 'Mokrý board jako 9-8-7 dvoubarevný', 'Board se čtyřmi kartami jedné barvy', 'Dvojitě spárovaný board'], explanation: 'Suché, nesouvislé boardy míjejí rozsah dorovnávajícího a nahrávají navyšovateli, takže c-bety levně získají mnoho složení.' },
  'rm-pkbet-19': { introduction: 'Jaká velikost c-betu na suchém boardu?', question: 'Na suchém boardu, který sedí tvému rozsahu, je běžná účinná velikost c-betu...', options: ['Malá sázka (asi třetina banku)', 'Overbet o velikosti banku', 'Celý tvůj stack', 'Pouze min-raise'], explanation: 'S převahou rozsahu na suchém boardu můžeš sázet malou částku, levně odepřeš ekvitu a přitom sázíš mnoho rukou.' },
  'rm-pkbet-20': { introduction: 'Co znamená převaha rozsahu?', question: 'Mít na flopu „převahu rozsahu" znamená, že...', options: ['Tvůj rozsah obsahuje více silných rukou než soupeřův', 'Držíš jedinou nejlepší ruku', 'Máš pozici', 'Máš více žetonů'], explanation: 'Převaha rozsahu je vyšší podíl silných rukou celkově, což podporuje častější sázení.' },
  'rm-pkbet-21': { introduction: 'Proč sázet silnou ruku na flopu?', question: 'Proč bys mohl c-betovat flop se silnou hotovou rukou?', options: ['Postavit bank a nechat platit dotahy', 'Vytlačit horší ruce', 'Udržet bank malý', 'Zamaskovat slabost'], explanation: 'Sázka se silnou rukou zvětšuje bank pro hodnotu a odepírá volné karty rukám, které se dotahují na tvé přebití.' },
  'rm-pkbet-22': { introduction: 'Mokrý board nahrává dorovnávajícímu.', question: 'Na velmi mokrém boardu, který nahrává dorovnávajícímu, by preflopový navyšovatel měl obvykle...', options: ['C-betovat méně často a více checkovat', 'C-betovat 100 % rukou', 'Vždy overbetovat', 'Nikdy nechecknout žádnou ruku'], explanation: 'Když board sedí rozsahu dorovnávajícího, slepé c-betování je trestáno, takže častější check chrání tvůj rozsah.' },
  'rm-pkbet-23': { introduction: 'Odložená sázka o jednu ulici.', question: '„Odložený c-bet" (delayed c-bet) je, když preflopový navyšovatel...', options: ['Checkne flop a místo toho sází turn', 'Sází flop, turn i river', 'Sází pouze river', 'Nesází vůbec'], explanation: 'Odložený c-bet checkne flop a převezme iniciativu sázení na turnu, často poté, co se pole oslabí.' },
  'rm-pkbet-24': { introduction: 'Které ruce jsou dobré blafy na flopu?', question: 'Dobří kandidáti na blaf v rámci c-betu na flopu jsou obvykle ruce s...', options: ['Zadními dotahy nebo overkartami, které se mohou zlepšit', 'Žádnou ekvitou a bez budoucího potenciálu', 'Aktuálním nuts', 'Pouze hodnotou do showdownu'], explanation: 'Sázet ruce s nějakou ekvitou (dotahy, overkarty) znamená, že i po dorovnání můžeš vyhrát zlepšením.' },

  'rm-pkbet-25': { introduction: 'Sázka s dotahem, který se může zlepšit.', question: '„Polovblaf" (semi-bluff) je sázka rukou, která...', options: ['Je nyní pravděpodobně vzadu, ale může se zlepšit na nejlepší ruku', 'Je už teď nuts', 'Nemá žádnou šanci na zlepšení', 'Nikdy nemůže být dorovnána'], explanation: 'Polovblaf sází dotahující ruku: můžeš vyhrát hned složením, nebo později trefením svého dotahu.' },
  'rm-pkbet-26': { introduction: 'Hodnota z možnosti složení.', question: '„Fold equity" označuje...', options: ['Přidanou hodnotu z šance, že soupeř složí', 'Bank, který vyhraješ ve showdownu', 'Rake odebraný kasinem', 'Tvou ekvitu, když jsi all-in a dorovnaný'], explanation: 'Fold equity je přidaná očekávaná hodnota plynoucí z možnosti, že soupeře přinutíš složit.' },
  'rm-pkbet-27': { introduction: 'Proč je polovblaf často lepší?', question: 'Proč je polovblaf často lepší než čistý blaf?', options: ['Má dvě cesty k výhře: složení hned, nebo trefení později', 'Nikdy není dorovnán', 'Nepotřebuje žádnou fold equity', 'Vždy udělá nuts'], explanation: 'Polovblaf vyhraje, když soupeř složí, a přesto má záložní ekvitu udělat nejlepší ruku, když je dorovnán.' },
  'rm-pkbet-28': { introduction: 'Silný dotah jako polovblaf.', question: 'Dotah na barvu se dvěma overkartami je silný polovblaf hlavně proto, že má...', options: ['Vysokou ekvitu i po dorovnání', 'Vůbec žádnou ekvitu', 'Zaručenou fold equity', 'Aktuálně nejlepší ruku'], explanation: 'Mnoho outů (karty na barvu i na pár) mu dává vysokou ekvitu, takže další sázení je ziskové i po dorovnání.' },
  'rm-pkbet-29': { introduction: 'Karty v ruce, které soupeři berou kombinace.', question: 'Blaf s „blockerem" (odebráním karet) je silnější, když tvé karty v ruce...', options: ['Snižují počet kombinací rukou, které by tě mohly dorovnat', 'Dělají full house', 'Sedí ke spárovaným kartám na boardu', 'Dávají ti nuts'], explanation: 'Držení karty, která blokuje soupeřovy silné dorovnávající ruce, znamená, že má menší šanci mít dorovnání.' },
  'rm-pkbet-30': { introduction: 'Hloubka stacku a páka.', question: 'S rostoucí hloubkou stacků vůči banku má tvá fold equity při sázení tendenci...', options: ['Růst, protože soupeři riskují víc, aby pokračovali', 'Zcela zmizet', 'Zůstat úplně stejná', 'Být záporná'], explanation: 'Hlubší stacky znamenají, že sázky hrozí větším množstvím žetonů na dalších ulicích, což dává tvé agresi větší páku a fold equity.' },
  'rm-pkbet-31': { introduction: 'Kdy je river dobrým místem na blaf?', question: 'Dobrá příležitost k blafu na riveru často nastává, když...', options: ['Zjevný dotah minul a ty držíš blocker na hodnotové ruce', 'Právě jsi udělal nuts', 'Board je pro všechny úplně prázdný', 'Celou hru jsi ukazoval slabost'], explanation: 'Když dotahy minou, zbývá málo hodnotových rukou; věrohodný příběh plus blockery činí blaf na riveru nejúčinnějším.' },
  'rm-pkbet-32': { introduction: 'Sázení na více ulicích jako blaf.', question: 'Barreling (sázení na více ulicích) jako blaf funguje nejlépe, když pozdější karty...', options: ['Nahrávají tvému rozsahu a straší soupeřovy ruce', 'Vždy zlepší soupeře', 'Jsou pro oba rozsahy nepodstatné', 'Doplní každý dotah dorovnávajícímu'], explanation: 'Strašící karty na turnu a riveru, které věrohodně sedí tvému rozsahu, ti umožní dál tlačit a vytlačit okrajová dorovnání.' },

  'rm-pkbet-33': { introduction: 'Rozsah rozdělený na hodnotu a blafy.', question: '„Polarizovaný" sázecí rozsah se skládá z...', options: ['Silných hodnotových rukou a blafů, s málo středními rukami', 'Pouze středně silných rukou', 'Pouze dotahujících rukou', 'Náhodné směsi všeho'], explanation: 'Polarizovaný rozsah je rozdělen na nutované hodnotové sázky a blafy, proto může používat velké velikosti sázek.' },
  'rm-pkbet-34': { introduction: 'Sloučený rozsah.', question: '„Sloučený" (lineární) sázecí rozsah je tvořen převážně z...', options: ['Silných a středně silných hodnotových rukou', 'Pouze čistých blafů', 'Pouze absolutního nuts', 'Rukou bez ekvity'], explanation: 'Sloučený rozsah hodnotově sází pásmo silných a dobrých, ale ne nutovaných rukou, a hodí se k menším velikostem sázek.' },
  'rm-pkbet-35': { introduction: 'K jakému rozsahu patří overbet?', question: 'Overbety se nejlépe kombinují s jakým typem rozsahu?', options: ['S polarizovaným rozsahem', 'Se sloučeným rozsahem', 'S čistě zastropovaným rozsahem', 'S rozsahem pouze dotahů'], explanation: 'Protože overbety riskují tolik, hodí se k polarizovaným rozsahům velmi silných rukou a blafů, ne ke střední hodnotě.' },
  'rm-pkbet-36': { introduction: 'Plánování napříč ulicemi.', question: 'Dobré „plánování napříč ulicemi" znamená především...', options: ['Volit velikosti sázek napříč ulicemi tak, abys dosáhl cílového stavu stacku', 'Myslet pouze na aktuální sázku', 'Vždy sázet stejnou částku', 'Nikdy nesázet river'], explanation: 'Velikosti sázek na flopu, turnu a riveru plánuješ předem, aby hodnotová ruka dostala všechny žetony do banku do riveru.' },
  'rm-pkbet-37': { introduction: 'Jak plynule dostat stacky dovnitř.', question: 'Abys dostal all-in do riveru pro hodnotu, měl bys obvykle...', options: ['Volit sázky na flopu a turnu tak, aby sázka na riveru byla přirozený jam', 'Sázet zprvu maličko a pak shovnout river', 'Vždy checkovat flop i turn', 'Sázet jen river'], explanation: 'Geometrická velikost znamená, že sázka na každé ulici je poměrná, takže stacky jdou dovnitř plynule do riveru.' },
  'rm-pkbet-38': { introduction: 'Poměr stacku k banku.', question: 'Poměr stacku k banku (SPR) je důležitý, protože nízké SPR...', options: ['Usnadňuje vložení celého stacku', 'Zaručuje výhru banku', 'Znamená, že blafy vždy projdou', 'Odstraňuje potřebu plánovat sázky'], explanation: 'Nízké SPR znamená, že vůči banku zbývá méně žetonů, takže silné ruce mohou ziskově jít all-in.' },
  'rm-pkbet-39': { introduction: 'Který příklad je tenká hodnota?', question: 'Které místo je nejjasnějším příkladem tenké hodnotové sázky na riveru?', options: ['Sázení druhého páru, když tě station dorovná s horšími páry a dotahy', 'Sázení nutové barvy', 'Sázení bez páru a bez dotahu', 'Check s full housem'], explanation: 'Tenká hodnota sází skromnou hotovou ruku, která je jen mírně vpředu, a spoléhá na dorovnání dostatkem horších rukou.' },
  'rm-pkbet-40': { introduction: 'Proč polarizovaný rozsah unese velkou sázku?', question: 'Proč může polarizovaný rozsah používat mnohem větší velikost než sloučený rozsah?', options: ['Protože nikdy nepotřebuje střední ruce k dorovnávání blafů, takže může riskovat víc', 'Protože blafy vždy vyhrají', 'Protože obsahuje pouze střední ruce', 'Protože na pozici nikdy nezáleží'], explanation: 'Polarizovaný rozsah sází jen nutovanou hodnotu a blafy, takže může využít velké velikosti, aniž by vystavil střední ruce.' },
};
