import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Endgame Technique roadmap bank (rm-endgtech-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const endgameTechniqueTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Level 1 — Pěšcové koncovky ──
  'rm-endgtech-1': { introduction: 'Klíčový pojem u soubojů králů s pěšci.', question: 'Co je v pěšcové koncovce „opozice"?', options: ['Dva králové na téže linii jedno pole od sebe, přičemž strana na tahu musí ustoupit', 'Dva pěšci blokující jeden druhého', 'Dva králové na sousedních polích', 'Král útočící na pěšce soupeře'], explanation: 'Králové stojí na téže sloupci, řadě nebo diagonále s jedním polem mezi sebou; kdo je nucen táhnout, musí ustoupit.' },
  'rm-endgtech-2': { introduction: 'Kdo opozici „drží"?', question: 'Opozici „držíš", když jsou králové proti sobě a je:', options: ['Tvůj tah', 'Tah soupeře', 'Věžová koncovka', 'Začátek partie'], explanation: 'Opozici držíš, když je na tahu soupeř a musí uhnout jako první.' },
  'rm-endgtech-3': { introduction: 'Jednoduché pravidlo pro dohonění pěšce.', question: 'Co ti okamžitě řekne „pravidlo čtverce"?', options: ['Zda osamocený král dostihne volného pěšce dříve, než promění', 'Který pěšec je volný', 'Kam rošovat', 'Jak dát mat věží'], explanation: 'Je-li král uvnitř čtverce pěšce (nebo do něj může vstoupit), pěšce dostihne; jinak pěšec promění.' },
  'rm-endgtech-4': { introduction: 'Jak čtverec narýsovat.', question: 'Jedna strana čtverce v „pravidle čtverce" vede od pěšce k:', options: ['Jeho vlastní základní řadě', 'Nejbližšímu okraji šachovnice', 'Poli proměny', 'Soupeřovu králi'], explanation: 'Spočítej pole od pěšce k poli proměny; tato vzdálenost tvoří stranu čtverce.' },
  'rm-endgtech-5': { introduction: 'Význam „klíčových polí".', question: 'Dosáhnout králem „klíčového pole" v pěšcové koncovce znamená, že:', options: ['Automaticky ztratíš pěšce', 'Musíš nabídnout remízu', 'Vyhraješ a proměníš bez ohledu na to, kdo je na tahu', 'Musíš pěšce vyměnit'], explanation: 'U nevěžových pěšců zaručuje obsazení klíčového pole proměnu bez ohledu na to, kdo táhne.' },
  'rm-endgtech-6': { introduction: 'Obranná metoda v pěšcové koncovce.', question: 'Když obranný král dosáhne pole přímo před nevěžovým pěšcem (se soupeřovým králem za ním), výsledkem obvykle je:', options: ['Výhra pěšce', 'Remíza', 'Okamžitý pat', 'Prohra obránce'], explanation: 'Dostat krále před pěšce a zablokovat ho je běžný způsob, jak udržet remízu.' },
  'rm-endgtech-7': { introduction: 'Proč jsou krajní pěšci slabší.', question: 'Proč je věžový pěšec (sloupec a nebo h) v koncovce král a pěšec proti králi často jen remíza?', options: ['Věžoví pěšci nemohou proměnit', 'Obranný král je patem uvězněn v rohu a nelze ho vyhnat', 'Pěšec táhne příliš rychle', 'Útočící král je vázán'], explanation: 'Obráncův král dosáhne rohu a útočník ho nemůže vyhnat, aniž by dal pat, takže je to remíza.' },
  'rm-endgtech-8': { introduction: 'Vzdálenější forma opozice.', question: '„Vzdálená opozice" označuje krále na téže linii oddělené:', options: ['Jedním prázdným polem', 'Lichým počtem prázdných polí (třemi nebo pěti)', 'Sudým počtem polí', 'Pěšcem'], explanation: 'S lichým počtem polí mezi nimi na téže linii drží vzdálenou opozici strana, která není na tahu.' },

  // ── Level 2 — Věžové koncovky ──
  'rm-endgtech-9': { introduction: 'Základní vyhrávající postavení ve věžovkách.', question: 'Lucenova pozice je základní VYHRÁVAJÍCÍ metoda ve věžových koncovkách; využívá techniku zvanou:', options: ['Stavba mostu', 'Obrana na třetí řadě', 'Věčný šach', 'Podproměna'], explanation: 'Silnější strana „staví most" věží, aby ochránila svého krále před šachy a proměnila pěšce.' },
  'rm-endgtech-10': { introduction: 'Základní remízová metoda obránce.', question: 'Philidorova pozice je klíčová REMÍZOVÁ metoda obránce, založená na:', options: ['Okamžité výměně věží', 'Obraně na třetí řadě', 'Oběti věže', 'Postupu krále'], explanation: 'Obránce drží věž na třetí řadě a po postupu pěšce začne šachovat zezadu, čímž udrží remízu.' },
  'rm-endgtech-11': { introduction: 'Tarraschovo pravidlo o umístění věže.', question: 'Tarraschovo pravidlo říká, že věž patří vzhledem k volnému pěšci:', options: ['Před něj', 'Vedle něj', 'Za něj, ať jde o vlastního, či soupeřova pěšce', 'Na totéž pole'], explanation: 'Věž za volným pěšcem získává aktivitu s jeho postupem, a to pro útočníka i obránce.' },
  'rm-endgtech-12': { introduction: 'Pověstná vlastnost věžovek.', question: 'Ve srovnání s jinými koncovkami jsou věžové koncovky proslule:', options: ['Téměř vždy rozhodnuté', 'Remízové, mnohé se udrží i o čistého pěšce méně', 'Nemožné remizovat', 'Vyhrané tím, kdo má víc pěšců'], explanation: 'Věžovky jsou nejremízovější ze všech; jediný pěšec navíc často k výhře nestačí.' },
  'rm-endgtech-13': { introduction: 'Hodnota aktivity věže.', question: 'Ve věžových koncovkách má aktivní věž obvykle hodnotu:', options: ['Nižší než pasivní věž', 'Vyšší než pasivní věž, někdy i pěšce', 'Vždy naprosto stejnou', 'Nulovou bez dámy'], explanation: 'Aktivita věže je zásadní; aktivní věž může mít proti pasivní hodnotu pěšce i více.' },
  'rm-endgtech-14': { introduction: 'Načasování Philidorovy obrany.', question: 'Ve Philidorově obraně zůstává věž na třetí řadě, dokud:', options: ['Soupeřův pěšec nedojde na tuto řadu, pak šachuje zezadu', 'Nepřijde úplně poslední tah', 'Se neobjeví dáma', 'Se králové nedotknou'], explanation: 'Jakmile pěšec postoupí na třetí řadu, nemůže už krýt svého krále, a tak věž sjede za pěšce a bez ustání šachuje.' },
  'rm-endgtech-15': { introduction: 'Omezení soupeřova krále.', question: '„Odříznout" soupeřova krále věží znamená:', options: ['Sebrat ho', 'Postavit věž na sloupec nebo řadu, kterou král nemůže překročit', 'Připoutat krále k pěšci', 'Dát věčný šach'], explanation: 'Věž na otevřeném sloupci či řadě uzavře soupeřova krále a drží ho mimo rozhodující prostor.' },
  'rm-endgtech-16': { introduction: 'Kdy Lucenova metoda selhává.', question: 'Vyhrávající stavba mostu podle Lucenovy pozice NEfunguje s kterým pěšcem?', options: ['Se středovým pěšcem', 'S jezdcovým pěšcem', 'S věžovým pěšcem (sloupec a nebo h)', 'Se střelcovým pěšcem'], explanation: 'U věžového pěšce není na kratší straně místo pro stavbu mostu, takže výhra obvykle selže.' },

  // ── Level 3 — Lehké figury ──
  'rm-endgtech-17': { introduction: 'Pověstně remízové koncovky.', question: 'Koncovky s různobarevnými střelci jsou proslulé tím, že jsou:', options: ['Snadné výhry pro silnější stranu', 'Remízové, často i o pěšce či dva výše', 'Vždy rozhodné', 'Nemožné bránit'], explanation: 'Protože každý střelec kryje jen svou barvu, obránce často udrží remízu i o jednoho či dva pěšce méně.' },
  'rm-endgtech-18': { introduction: 'Kdy je střelec lepší než jezdec.', question: 'Střelec bývá silnější než jezdec, když:', options: ['Je střed uzavřený', 'Je pozice otevřená s pěšci na obou křídlech', 'Jsou všichni pěšci na jedné straně', 'Na šachovnici téměř nejsou pěšci'], explanation: 'Dalekonosný střelec vyniká v otevřených pozicích a působí na obě křídla zároveň.' },
  'rm-endgtech-19': { introduction: 'Kdy je jezdec lepší než střelec.', question: 'Jezdec bývá lepší než střelec, když:', options: ['Je pozice uzavřená s pevnými pěšci', 'Je šachovnice zcela otevřená', 'Se hraje na obou křídlech', 'Jsou všichni pěšci odstraněni'], explanation: 'V uzavřených, zablokovaných pozicích převáží jezdcova schopnost přeskakovat pěšce nad dosahem střelce.' },
  'rm-endgtech-20': { introduction: 'Problém „špatného střelce".', question: 'Král, střelec a věžový pěšec proti osamocenému králi je remíza, když:', options: ['Střelec kontroluje pole proměny', 'Střelec NEkontroluje pole proměny pěšce („špatný střelec")', 'Pěšec je na druhé řadě', 'Králové jsou daleko od sebe'], explanation: 'Se špatnobarevným střelcem dosáhne obranný král rohu a nelze ho vyhnat, takže je to remíza.' },
  'rm-endgtech-21': { introduction: 'Výhoda střelce při volných pěšcích.', question: 'S volnými pěšci na obou křídlech je hlavní výhodou střelce oproti jezdci, že:', options: ['Táhne rychleji v přímé linii', 'Může z dálky hlídat či zastavit pěšce na obou křídlech', 'Umí přeskakovat figury', 'Nikdy se nedostane do pasti'], explanation: 'Jediný střelec kontroluje vzdálená pole na obou stranách zároveň, což krátkonosný jezdec nedokáže.' },
  'rm-endgtech-22': { introduction: 'Slabina jezdce.', question: 'Proč je jezdec často špatným blokátorem vzdáleného volného pěšce?', options: ['Nemůže táhnout zpět', 'Je krátkonosý a pomalu přechází na druhou stranu šachovnice', 'Nemůže kontrolovat pole proměny', 'Je vázán pěšcem'], explanation: 'Omezený dosah jezdce znamená, že přesun přes celou šachovnici k vzdálenému pěšci trvá několik tahů.' },
  'rm-endgtech-23': { introduction: 'Proč je dvojice střelců silná.', question: '„Dva střelci" jsou považováni za výhodu hlavně proto, že:', options: ['Mají hodnotu věže každý', 'Společně kryjí obě barvy a vládnou otevřeným pozicím', 'Nikdy je nelze vyměnit', 'Dávají automatický mat'], explanation: 'Dvojice střelců pokrývá zároveň bílá i černá pole, což je silné zvláště při otevírání pozice.' },
  'rm-endgtech-24': { introduction: 'Jádro obrany u různobarevných střelců.', question: 'Základní remízová myšlenka v koncovkách různobarevných střelců je, že obránce:', options: ['Ihned vymění střelce', 'Zablokuje soupeřovy pěšce na barvě svého vlastního střelce', 'Obětuje střelce za pěšce', 'Postoupí všemi svými pěšci'], explanation: 'Jelikož útočníkův střelec nikdy nenapadne pole obráncovy barvy, blokáda na těchto polích drží.' },

  // ── Level 4 — Dámské koncovky a složitější materiál ──
  'rm-endgtech-25': { introduction: 'Kdy dáma neporazí pěšce na sedmé řadě.', question: 'V koncovce dáma proti osamocenému pěšci na sedmé řadě může obránce často remizovat, je-li pěšec:', options: ['Středový', 'Jezdcový', 'Střelcový nebo věžový', 'Dámský'], explanation: 'Se střelcovým nebo věžovým pěšcem drží obránce díky patovým trikům; středoví a jezdcoví pěšci prohrávají.' },
  'rm-endgtech-26': { introduction: 'Hlavní nebezpečí dámských koncovek.', question: 'Dámské koncovky ovládá především nebezpečí:', options: ['Věčného šachu', 'Podproměny', 'Rošády', 'Braní mimochodem'], explanation: 'Síla dámy znamená, že obránce často vynutí remízu nekonečnými šachy, jimž útočník neunikne.' },
  'rm-endgtech-27': { introduction: 'Základní mat.', question: 'Král a dáma proti osamocenému králi je:', options: ['Remíza', 'Základní vynucený mat', 'Výhra jen pro bílého', 'Pevnost'], explanation: 'K+D proti K je elementární vynucený mat; jediné, na co si dát pozor, je vyhnout se patu.' },
  'rm-endgtech-28': { introduction: 'Souboj dámy proti věži.', question: 'Koncovka dáma proti věži (bez pěšců) je obecně:', options: ['Mrtvá remíza', 'Výhra dámy, byť obtížně dosažitelná', 'Výhra věže', 'Nedovolená'], explanation: 'Dáma při nejlepší hře poráží věž, ale obranná technika z toho dělá jednu z těžších základních výher.' },
  'rm-endgtech-29': { introduction: 'Materiálová rovnováha lehkých figur.', question: 'Tři sehrané lehké figury jsou zhruba materiálově srovnatelné s:', options: ['Dámou', 'Jediným pěšcem', 'Osamocenou věží', 'Králem'], explanation: 'Tři lehké figury mají dohromady asi devět bodů, srovnatelně s dámou, a při aktivitě ji mohou i překonat.' },
  'rm-endgtech-30': { introduction: 'Zdroj obrany dámy o pěšce méně.', question: 'Dáma o pěšce méně nejčastěji zachrání remízu tím, že:', options: ['Postoupí svým králem', 'Dá věčný šach', 'Vymění dámy', 'Zablokuje králem'], explanation: 'Věčný šach je hlavním zdrojem obránce v dámských koncovkách, když je o pěšce pozadu.' },
  'rm-endgtech-31': { introduction: 'Síla spojených volných pěšců.', question: 'Dva spojení volní pěšci na šesté řadě mohou někdy porazit:', options: ['Dámu', 'Věž, protože se navzájem kryjí a hrozí proměnou', 'Jen střelce', 'Nic'], explanation: 'Spojení volní pěšci na šesté řadě se navzájem podpírají, takže osamocená věž nezastaví oba před proměnou.' },
  'rm-endgtech-32': { introduction: 'Nerovnováha dáma proti dvěma věžím.', question: 'Materiálovou nerovnováhu dáma proti dvěma věžím nejlépe vystihuje, že je:', options: ['Vždy vyhraná pro dámu', 'Zhruba vyrovnaná, rozhoduje bezpečnost krále a pěšci', 'Vždy vyhraná pro věže', 'Vynucená remíza'], explanation: 'Dvě věže bodově mírně převyšují dámu, takže výsledek závisí na aktivitě, bezpečnosti krále a pěšcové struktuře.' },

  // ── Level 5 — Praktická technika ──
  'rm-endgtech-33': { introduction: 'Nucený tah do vlastní škody.', question: 'Cugcvang je situace, ve které hráč:', options: ['Nemá žádný tah', 'Je nucen táhnout a každý tah zhorší jeho postavení', 'Je v šachu', 'Může žádat remízu'], explanation: 'V cugcvangu je právě povinnost táhnout tím problémem, neboť každý tah pozici poškodí.' },
  'rm-endgtech-34': { introduction: 'Nedobytné remízové postavení.', question: '„Pevnost" v koncovce je:', options: ['Pěšcový řetěz', 'Remízové postavení, které silnější strana nedokáže prolomit ani s materiálem navíc', 'Matová síť', 'Zdvojená baterie věží'], explanation: 'Pevnost je nedobytná formace, jež udrží remízu i tehdy, má-li soupeř více materiálu.' },
  'rm-endgtech-35': { introduction: 'Manévr na ztrátu tempa.', question: 'Trojúhelníkování je manévr, jímž se:', options: ['Dává mat', 'Ztratí tempo králem, aby se soupeř dostal do cugcvangu', 'Okamžitě promění pěšec', 'Vymění dámy'], explanation: 'Pohybem krále po trojúhelníku dosáhneš téhož postavení, ale s tahem na straně soupeře.' },
  'rm-endgtech-36': { introduction: 'Proč jedna slabina nestačí.', question: '„Princip dvou slabin" radí silnější straně:', options: ['Útočit opakovaně na tutéž slabinu', 'Vytvořit druhou slabinu, protože jedna k výhře často nestačí', 'Vyměnit všechny pěšce', 'Držet krále pasivně'], explanation: 'Obránce jednu slabinu uhlídá; vynucení druhé roztáhne obranu, až se zhroutí.' },
  'rm-endgtech-37': { introduction: 'Koncovková zásada o trpělivosti.', question: 'Koncovková zásada „nespěchej" radí:', options: ['Táhnout co nejrychleji', 'Plně vylepšit své postavení, než se odhodláš k rozhodujícímu úderu', 'Vždy nabídnout remízu', 'Ihned vyměnit figury'], explanation: 'Čas věnovaný maximálnímu využití každé figury před vynucením akce zabrání obránci aktivizovat se.' },
  'rm-endgtech-38': { introduction: 'Pravidlo výměn s materiálem navíc.', question: 'Máš-li v koncovce materiál navíc, dobrým obecným pravidlem je:', options: ['Vyměňovat pěšce, figury ponechat', 'Vyměňovat figury, pěšce ponechat', 'Nevyměňovat nic', 'Obětovat pěšce za aktivitu'], explanation: 'Výměnou figur (nikoli pěšců) zjednodušíš do vyhrané pěšcové koncovky, kde se pěšec navíc projeví.' },
  'rm-endgtech-39': { introduction: 'Role krále v koncovce.', question: 'V koncovce by král měl obecně být:', options: ['Bezpečně schovaný v rohu', 'Aktivní a využitý jako bojová figura', 'Ponechán na výchozím poli', 'Vyměněn'], explanation: 'S málem figur je král dostatečně v bezpečí, aby vyrazil vpřed a stal se silným útočníkem i obráncem.' },
  'rm-endgtech-40': { introduction: 'Jak zúročit pěšce navíc.', question: 'Nejspolehlivější způsob, jak zúročit pěšce navíc, obvykle je:', options: ['Dát věčný šach', 'Vytvořit volného pěšce a proměnit ho', 'Vyměnit pouze dámy', 'Nechat každého pěšce na místě'], explanation: 'Proměnit pěšce navíc ve volného pěšce, který doběhne na proměnu, je standardní vyhrávající plán při materiálové převaze.' },
};
