import type { QuestionTranslation } from './quiz-data';

export const realAnalysisTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Reálná čísla ──
  'rm-analysis-1': { introduction: 'Nejmenší horní závora, i když nemusí ležet v množině.', question: 'Co je supremum otevřeného intervalu (0, 1)?', options: ['0', '1', '1/2', 'Neexistuje'], explanation: 'Nejmenší horní závora množiny (0, 1) je 1, přestože 1 do množiny nepatří.' },
  'rm-analysis-2': { introduction: 'Největší dolní závora hodnot 1/n.', question: 'Co je infimum množiny {1/n : n = 1, 2, 3, ...}?', options: ['1', '1/2', '0', 'Neexistuje'], explanation: 'Členy 1/n klesají k 0, takže 0 je největší dolní závora, i když se nikdy nedosáhne.' },
  'rm-analysis-3': { introduction: 'Klíčová vlastnost úplnosti R.', question: 'Axiom úplnosti R říká, že každá neprázdná shora omezená množina má:', options: ['Maximální prvek', 'Nejmenší horní závoru v R', 'Racionální horní závoru', 'Konečný počet prvků'], explanation: 'Úplnost zaručuje supremum (nejmenší horní závoru) v R pro každou neprázdnou shora omezenou množinu.' },
  'rm-analysis-4': { introduction: 'Rozepište absolutní hodnotu jako oboustrannou nerovnost.', question: 'Nerovnost |x| < 3 je ekvivalentní:', options: ['x < 3', '-3 < x < 3', 'x > -3', 'x < -3 nebo x > 3'], explanation: 'Podle definice absolutní hodnoty |x| < 3 znamená, že x leží ostře mezi -3 a 3.' },
  'rm-analysis-5': { introduction: 'Rozepište nerovnost s absolutní hodnotou a vyřešte pro x.', question: 'Množina řešení nerovnice |x - 5| < 2 je:', options: ['(3, 7)', '(-7, -3)', '(5, 7)', '(-2, 2)'], explanation: '|x - 5| < 2 znamená -2 < x - 5 < 2, tj. 3 < x < 7.' },
  'rm-analysis-6': { introduction: 'Absolutní hodnota součtu versus součet absolutních hodnot.', question: 'Trojúhelníková nerovnost pro reálná čísla říká, že pro všechna x, y platí:', options: ['|x + y| >= |x| + |y|', '|x + y| <= |x| + |y|', '|x + y| = |x| + |y|', '|x - y| = |x| - |y|'], explanation: 'Absolutní hodnota součtu nikdy nepřevýší součet absolutních hodnot.' },
  'rm-analysis-7': { introduction: 'O neomezenosti přirozených čísel.', question: 'Archimedova vlastnost R říká, že:', options: ['R je nespočetná', 'Pro každé reálné x existuje přirozené n s n > x', 'Každá omezená množina má maximum', 'Racionální čísla jsou úplná'], explanation: 'Archimedova vlastnost říká, že přirozená čísla jsou neomezená: pro libovolné reálné x je nějaké přirozené číslo větší.' },
  'rm-analysis-8': { introduction: 'Musí supremum patřit do samotné množiny?', question: 'Které tvrzení o supremu množiny S je správné?', options: ['sup S musí patřit do S', 'sup S musí být iracionální', 'sup S může, ale nemusí patřit do S', 'sup S se vždy rovná maximu'], explanation: 'Supremum nemusí být prvkem množiny; např. sup (0,1) = 1 nepatří do (0,1).' },

  // ── Úroveň 2 — Posloupnosti a limity ──
  'rm-analysis-9': { introduction: 'Epsilon-N definice konvergence.', question: 'Tvrzení lim a_n = L znamená: pro každé epsilon > 0 existuje N takové, že:', options: ['n > N implikuje |a_n - L| < epsilon', 'n < N implikuje |a_n - L| < epsilon', '|a_n - L| < epsilon pro nějaké n', 'a_n = L pro všechna n > N'], explanation: 'Konvergence vyžaduje, aby od jistého indexu N ležely všechny členy ve vzdálenosti epsilon od L.' },
  'rm-analysis-10': { introduction: 'Vydělte čitatele i jmenovatele n.', question: 'Jaká je limita posloupnosti a_n = n / (n + 1)?', options: ['0', '1', 'nekonečno', 'Neexistuje'], explanation: 'Vydělením n dostaneme 1 / (1 + 1/n), což s rostoucím n směřuje k 1.' },
  'rm-analysis-11': { introduction: 'Dvě podmínky, které společně zaručí konvergenci.', question: 'Věta o monotonní konvergenci říká, že posloupnost konverguje, pokud je:', options: ['Pouze omezená', 'Pouze monotonní', 'Monotonní a omezená', 'Alternující'], explanation: 'Monotonní posloupnost, která je zároveň omezená, musí konvergovat (ke svému supremu nebo infimu).' },
  'rm-analysis-12': { introduction: 'Která vlastnost platí pro každou konvergentní posloupnost?', question: 'Které tvrzení platí vždy pro konvergentní posloupnost?', options: ['Je monotonní', 'Je omezená', 'Je kladná', 'Má maximální člen'], explanation: 'Každá konvergentní posloupnost je omezená, protože se členy nakonec shlukují blízko limity.' },
  'rm-analysis-13': { introduction: 'Zvažte, zda se členy ustálí u jedné hodnoty.', question: 'Konverguje posloupnost a_n = (-1)^n?', options: ['Ano, k 1', 'Ano, k 0', 'Ne, osciluje mezi -1 a 1', 'Ano, k -1'], explanation: 'Členy se střídají mezi 1 a -1 a nikdy se neustálí u jediné hodnoty, takže limita neexistuje.' },
  'rm-analysis-14': { introduction: 'Sevření mezi dvěma posloupnostmi se stejnou limitou.', question: 'Věta o dvou strážnících (o sevření) dává lim b_n = L, když:', options: ['a_n <= b_n <= c_n a lim a_n = lim c_n = L', 'b_n je omezená', 'b_n je monotonní', 'pouze a_n <= b_n'], explanation: 'Je-li b_n sevřena mezi dvěma posloupnostmi konvergujícími k L, pak i b_n konverguje k L.' },
  'rm-analysis-15': { introduction: 'Podmínka na vzájemnou blízkost členů.', question: 'Posloupnost (a_n) je cauchyovská, jestliže pro každé epsilon > 0 existuje N takové, že:', options: ['|a_n - a_m| < epsilon pro všechna n, m > N', '|a_n| < epsilon pro všechna n > N', 'a_n je monotonní od N dál', '|a_n - L| < epsilon'], explanation: 'Cauchyovské kritérium vyžaduje, aby se členy od jistého indexu staly libovolně blízkými navzájem.' },
  'rm-analysis-16': { introduction: 'Ekvivalence konvergence v úplném prostoru.', question: 'V R posloupnost konverguje právě tehdy, když je:', options: ['Omezená', 'Monotonní', 'Cauchyovská', 'Kladná'], explanation: 'R je úplné, takže posloupnost konverguje právě tehdy, když je cauchyovská.' },

  // ── Úroveň 3 — Nekonečné řady ──
  'rm-analysis-17': { introduction: 'Podmínka na kvocient geometrické řady.', question: 'Geometrická řada, součet r^n od n = 0, konverguje právě tehdy, když:', options: ['|r| < 1', '|r| > 1', 'r > 0', 'r je racionální'], explanation: 'Geometrická řada konverguje právě tehdy, když kvocient splňuje |r| < 1, a to k hodnotě 1/(1 - r).' },
  'rm-analysis-18': { introduction: 'Rozmyslete, zda členy jdoucí k 0 stačí ke konvergenci.', question: 'Harmonická řada, součet 1/n, je:', options: ['Konvergentní k 1', 'Konvergentní k e', 'Divergentní', 'Konvergentní k ln 2'], explanation: 'Přestože členy směřují k 0, harmonická řada diverguje (její částečné součty rostou nade všechny meze).' },
  'rm-analysis-19': { introduction: 'Prahová hodnota exponentu p.', question: 'p-řada, součet 1/n^p, konverguje právě tehdy, když:', options: ['p > 1', 'p < 1', 'p >= 1', 'p > 0'], explanation: 'p-řada konverguje právě tehdy, když p > 1, jinak diverguje.' },
  'rm-analysis-20': { introduction: 'Co říká chování členů o divergenci.', question: 'Test (divergence) n-tého členu říká, že řada diverguje, jestliže:', options: ['a_n směřuje k 0', 'a_n nesměřuje k 0', 'a_n je kladné', 'a_n je klesající'], explanation: 'Pokud členy nesměřují k 0, řada nemůže konvergovat. (a_n jdoucí k 0 je nutná, nikoli postačující podmínka.)' },
  'rm-analysis-21': { introduction: 'Limita poměru sousedních členů.', question: 'Podílové kritérium zaručuje konvergenci součtu a_n, když:', options: ['lim |a_{n+1}/a_n| < 1', 'lim |a_{n+1}/a_n| > 1', 'lim |a_{n+1}/a_n| = 1', 'a_n je omezené'], explanation: 'Je-li limitní poměr po sobě jdoucích členů menší než 1, řada konverguje absolutně.' },
  'rm-analysis-22': { introduction: 'Podmínka na velikosti členů alternující řady.', question: 'Leibnizovo kritérium (test alternující řady) vyžaduje, aby velikosti členů b_n:', options: ['Rostly do nekonečna', 'Klesaly monotonně k 0', 'Byly konstantní', 'Byly všechny stejné'], explanation: 'Alternující řada konverguje, jestliže b_n klesají monotonně a směřují k 0.' },
  'rm-analysis-23': { introduction: 'Vztah mezi absolutní a obyčejnou konvergencí.', question: 'Konverguje-li součet |a_n|, pak součet a_n:', options: ['Diverguje', 'Konverguje (absolutní konvergence)', 'Může divergovat', 'Rovná se 0'], explanation: 'Absolutní konvergence implikuje konvergenci původní řady.' },
  'rm-analysis-24': { introduction: 'Který výraz odmocninové kritérium zkoumá.', question: 'Odmocninové kritérium zkoumá limitu výrazu:', options: ['a_{n+1}/a_n', 'n-té odmocniny z |a_n|', 'n krát a_n', 'a_n^2'], explanation: 'Odmocninové kritérium používá lim z |a_n|^(1/n); hodnota menší než 1 dává konvergenci.' },

  // ── Úroveň 4 — Spojitost ──
  'rm-analysis-25': { introduction: 'Epsilon-delta definice spojitosti v bodě.', question: 'f je spojitá v bodě a, jestliže pro každé epsilon > 0 existuje delta > 0 takové, že:', options: ['|x - a| < delta implikuje |f(x) - f(a)| < epsilon', '|f(x) - f(a)| < delta implikuje |x - a| < epsilon', 'f(x) = f(a) pro všechna x', 'x = a'], explanation: 'Spojitost znamená, že vstupy blízké a (do delta) dávají výstupy blízké f(a) (do epsilon).' },
  'rm-analysis-26': { introduction: 'Předpoklad věty o nabývání mezihodnot.', question: 'Věta o nabývání mezihodnot se vztahuje na funkci, která je:', options: ['Spojitá na uzavřeném intervalu [a, b]', 'Všude diferencovatelná', 'Monotonní', 'Pouze omezená'], explanation: 'Věta vyžaduje spojitost na uzavřeném intervalu; funkce pak nabývá každé hodnoty mezi f(a) a f(b).' },
  'rm-analysis-27': { introduction: 'Co spojitá funkce na [a, b] zaručeně nabude.', question: 'Věta o nabývání extrémů říká, že spojitá funkce na [a, b]:', options: ['Je diferencovatelná', 'Nabývá maxima a minima', 'Je neomezená', 'Nemá nulové body'], explanation: 'Funkce spojitá na uzavřeném omezeném intervalu nabývá jak maximální, tak minimální hodnoty.' },
  'rm-analysis-28': { introduction: 'Závisí delta na bodě, nebo ne?', question: 'Stejnoměrná spojitost se od spojitosti liší tím, že delta:', options: ['Závisí na bodě x', 'Lze zvolit nezávisle na bodě x', 'Je vždy 1', 'Rovná se epsilon'], explanation: 'U stejnoměrné spojitosti funguje jediné delta pro každý bod při daném epsilon; u obyčejné spojitosti se delta může s bodem měnit.' },
  'rm-analysis-29': { introduction: 'Spojitost na kompaktní množině má silnější důsledek.', question: 'Spojitá funkce na kompaktní množině (uzavřeném omezeném intervalu) je:', options: ['Neomezená', 'Stejnoměrně spojitá', 'Diferencovatelná', 'Monotonní'], explanation: 'Heineova-Cantorova věta: spojitost na kompaktní množině implikuje stejnoměrnou spojitost.' },
  'rm-analysis-30': { introduction: 'Který ze dvou pojmů je silnější.', question: 'Který vztah mezi spojitostí a stejnoměrnou spojitostí je správný?', options: ['Spojitost všude implikuje stejnoměrnou spojitost', 'Stejnoměrná spojitost implikuje spojitost', 'Na celém R jsou ekvivalentní', 'Žádná neimplikuje druhou'], explanation: 'Stejnoměrná spojitost je silnější podmínka, takže vždy implikuje obyčejnou spojitost; obrácená implikace může selhat.' },
  'rm-analysis-31': { introduction: 'Aplikace věty o nabývání mezihodnot na znaménka.', question: 'Podle věty o mezihodnotách spojitá f s f(0) = -1 a f(2) = 3 musí:', options: ['Být rostoucí', 'Mít nulový bod v (0, 2)', 'Být diferencovatelná', 'Nabývat maxima v 2'], explanation: 'Protože 0 leží mezi f(0) = -1 a f(2) = 3, věta o mezihodnotách zaručuje kořen v otevřeném intervalu.' },
  'rm-analysis-32': { introduction: 'Vlastnost složení dvou spojitých funkcí.', question: 'Složení g po f dvou spojitých funkcí je:', options: ['Spojité', 'Nespojité', 'Konstantní', 'Ne nutně definované'], explanation: 'Složení spojitých funkcí je spojité všude, kde je definované.' },

  // ── Úroveň 5 — Derivace a integrace ──
  'rm-analysis-33': { introduction: 'Rovnost okamžité a průměrné směrnice.', question: 'Lagrangeova věta o střední hodnotě vyžaduje f spojitou na [a, b] a diferencovatelnou na (a, b) a pak zaručuje bod c, pro který:', options: ["f'(c) = (f(b) - f(a)) / (b - a)", "f'(c) = 0", 'f(c) = 0', "f'(c) = f(c)"], explanation: 'Věta o střední hodnotě dává bod, kde se okamžitá směrnice rovná průměrné směrnici na [a, b].' },
  'rm-analysis-34': { introduction: 'Speciální případ věty o střední hodnotě.', question: 'Rolleova věta je speciálním případem věty o střední hodnotě, kdy:', options: ['f(a) = f(b)', 'f je konstantní', 'a = b', "f'(a) = 0"], explanation: "Když f(a) = f(b), věta o střední hodnotě dává bod c, kde f'(c) = 0, což je Rolleova věta." },
  'rm-analysis-35': { introduction: 'Co diferencovatelnost v bodě vynucuje.', question: 'Je-li f diferencovatelná v bodě, pak je v tomto bodě f:', options: ['Spojitá', 'Konstantní', 'Monotonní', 'Shora omezená'], explanation: 'Diferencovatelnost implikuje spojitost, ačkoli obrácená implikace platit nemusí.' },
  'rm-analysis-36': { introduction: 'Důsledek nulové derivace na celém intervalu.', question: "Jestliže f'(x) = 0 pro všechna x v intervalu, pak je na tomto intervalu f:", options: ['Konstantní', 'Rostoucí', 'Nulová', 'Nespojitá'], explanation: 'Nulová derivace na celém intervalu nutí funkci být konstantní (důsledek věty o střední hodnotě).' },
  'rm-analysis-37': { introduction: 'Postačující podmínka pro riemannovskou integrovatelnost.', question: 'Která podmínka zaručuje, že f je riemannovsky integrovatelná na [a, b]?', options: ['f je spojitá na [a, b]', 'f je neomezená', 'f není nikde diferencovatelná', 'f je definovaná na otevřeném intervalu'], explanation: 'Každá funkce spojitá na uzavřeném omezeném intervalu je riemannovsky integrovatelná.' },
  'rm-analysis-38': { introduction: 'Derivace integrálu s proměnnou horní mezí.', question: 'První část základní věty integrálního počtu říká, že je-li F(x) integrál z f od a do x se spojitou f, pak:', options: ["F'(x) = f(x)", "F'(x) = 0", 'F(x) = f(x)', 'F je konstantní'], explanation: 'Základní věta říká, že derivováním integrálu spojité funkce dostaneme zpět integrand.' },
  'rm-analysis-39': { introduction: 'Existence bodu s průměrnou hodnotou.', question: 'Věta o střední hodnotě integrálního počtu říká, že pro f spojitou na [a, b] existuje c, pro které:', options: ['integrál f přes [a, b] se rovná f(c)(b - a)', 'integrál se rovná 0', "f'(c) = 0", 'f(c) = 0'], explanation: 'Existuje bod c, kde se hodnota f(c) rovná průměrné hodnotě f na intervalu.' },
  'rm-analysis-40': { introduction: 'Vliv konečně mnoha bodů nespojitosti.', question: 'Omezená funkce na [a, b] jen s konečně mnoha body nespojitosti je:', options: ['Neintegrovatelná', 'Riemannovsky integrovatelná', 'Nutně spojitá', 'Nutně diferencovatelná'], explanation: 'Omezenost spolu s konečně mnoha body nespojitosti (množina míry nula) zajišťuje riemannovskou integrovatelnost.' },
};
