import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Pawn Structures roadmap bank (rm-pawns-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const pawnStructuresTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-pawns-1': { introduction: 'Zamysli se nad pěšcem, kterého nemá kdo krýt.', question: 'Co je izolovaný pěšec?', options: ['Pěšec, který nemá vlastního pěšce na žádném sousedním sloupci', 'Pěšec na kraji šachovnice', 'Pěšec, který překročil střed', 'Pěšec zablokovaný soupeřovým pěšcem'], explanation: 'Izolovaný pěšec (izolák) nemá na sousedních sloupcích žádného vlastního pěšce, takže ho nikdy nemůže krýt jiný pěšec.' },
  'rm-pawns-2': { introduction: 'Proč je slabinou to, že ho nekryje pěšec?', question: 'Proč je izolovaný pěšec často slabinou?', options: ['Pohybuje se rychleji než ostatní pěšci', 'Může ho bránit jen figura, nikdy pěšec', 'Má menší hodnotu než běžný pěšec', 'Nelze ho proměnit'], explanation: 'Protože ho nemůže krýt žádný pěšec, musí izolovaného pěšce bránit figury, což je váže.' },
  'rm-pawns-3': { introduction: 'Jde o dva pěšce nad sebou.', question: 'Co jsou zdvojení pěšci?', options: ['Dva pěšci s dvojnásobnou hodnotou', 'Dva pěšci téže barvy na stejném sloupci', 'Dva pěšci vedle sebe', 'Pěšec, který se proměnil dvakrát'], explanation: 'Zdvojení pěšci jsou dva pěšci jedné barvy na stejném sloupci, obvykle po braní.' },
  'rm-pawns-4': { introduction: 'Jde o pěšce, který zaostal.', question: 'Co je zpátečnický (zaostalý) pěšec?', options: ['Pěšec táhnoucí zpět ke své straně', 'Pěšec na poslední řadě', 'Pěšec za svými sousedy, který nemůže bezpečně postoupit a nekryje ho pěšec', 'Každý pěšec, který ještě netáhl'], explanation: 'Zpátečnický pěšec zaostává za pěšci na sousedních sloupcích a nemůže k nim postoupit, aniž by se ztratil.' },
  'rm-pawns-5': { introduction: 'Pole před izolákem má pro soupeře cenu.', question: 'Pole přímo před izolovaným pěšcem je pro soupeře cenné, protože je vhodné k:', options: ['Proměně pěšce', 'Rošádě', 'Zablokování figurou', 'Nabídnutí remízy'], explanation: 'Pole před izolovaným pěšcem nemůže napadnout soupeřův pěšec, takže je ideální blokádovou základnou.' },
  'rm-pawns-6': { introduction: 'Jaká je typická nevýhoda zdvojených pěšců?', question: 'Co je běžnou nevýhodou zdvojených pěšců?', options: ['Nemohou se navzájem krýt a ovládají méně polí', 'Nikdy nemohou brát', 'Musí vždy postupovat společně', 'Brání králi v rošádě'], explanation: 'Nastoupení na jednom sloupci znamená, že se zdvojení pěšci navzájem nekryjí a pokrývají méně polí než pěšci na různých sloupcích.' },
  'rm-pawns-7': { introduction: 'Kdy je zaostalý pěšec nejsnáze napadnutelný?', question: 'Zpátečnický pěšec je nejsnáze napadnutelný, když stojí na:', options: ['Zavřeném sloupci', 'Polootevřeném sloupci proti soupeřovým věžím', 'Druhé řadě', 'Sloupci se třemi vlastními pěšci'], explanation: 'Zaostalý pěšec na polootevřeném sloupci je pevný terč, na který se mohou soustředit soupeřovy věže a dáma.' },
  'rm-pawns-8': { introduction: 'Zdvojení pěšci nemusí být jen mínus.', question: 'Co může být kompenzací za přijetí zdvojených pěšců?', options: ['Dáma navíc', 'Získání polootevřeného sloupce pro věž a lepší kontrola centra', 'Automatická proměna', 'Právo na dvě rošády'], explanation: 'Zdvojení často otevře sloupec pro věž a přidá kontrolu klíčových polí v centru, což vyváží strukturální nevýhodu.' },

  'rm-pawns-9': { introduction: 'Pěšci se navzájem kryjí do řetězu.', question: 'Co je pěšcový řetěz?', options: ['Řada pěšců na jedné řadě', 'Diagonální řada pěšců, kde každý kryje toho před sebou', 'Pěšci obou barev spojení dohromady', 'Tři spojení volní pěšci'], explanation: 'Pěšcový řetěz je diagonála pěšců téže barvy, kde každý chrání pěšce před sebou.' },
  'rm-pawns-10': { introduction: 'Který pěšec je základnou řetězu?', question: 'Základna pěšcového řetězu je:', options: ['Nejvíce vysunutý pěšec', 'Zadní pěšec, kterého nekryje žádný pěšec', 'Pěšec ve středu', 'Kterýkoli pěšec na čtvrté řadě'], explanation: 'Základna je zadní pěšec řetězu; na rozdíl od ostatních ho nekryje spřátelený pěšec.' },
  'rm-pawns-11': { introduction: 'Jde o postup pěšce proti soupeřově struktuře.', question: 'Co je pěšcový průlom (break)?', options: ['Pěšec, který se rozlomí vejpůl', 'Ztráta pěšce nedopatřením', 'Postup pěšce, který napadá soupeřovu pěšcovou strukturu', 'Výměna dam'], explanation: 'Pěšcový průlom je výpad, který napadá soupeřovy pěšce s cílem otevřít linie nebo rozbít jejich strukturu.' },
  'rm-pawns-12': { introduction: 'Pěšci se ohrožují, ale ještě nebrali.', question: 'Co je pěšcové napětí?', options: ['Když se dva protilehlí pěšci ohrožují, ale žádný ještě nebral', 'Když je pěšec vázán', 'Když jsou pěšci zdvojení', 'Když pěšec dosáhne poslední řady'], explanation: 'Napětí vzniká, když se protilehlí pěšci mohou vzájemně brát, ale situace ještě není vyřešena.' },
  'rm-pawns-13': { introduction: 'Kam mířit útok na řetěz?', question: 'Klasická strategie proti pěšcovému řetězu je napadat ho v:', options: ['Čele (přední pěšec)', 'Základně (zadní pěšec)', 'Pouze ve středu', 'U nejbližšího kraje'], explanation: 'Útok na základnu, nejméně krytý článek, může položit celý řetěz, pokud padne.' },
  'rm-pawns-14': { introduction: 'Proč napětí nerozvíjet hned?', question: 'Častým důvodem, proč udržovat (a nerozvádět) pěšcové napětí, je:', options: ['Vynutit okamžitou remízu', 'Zachovat pružnost a přimět soupeře, aby se rozhodl první', 'Okamžitě získat materiál', 'Zabránit rošádě'], explanation: 'Udržení napětí zachovává možnosti a často nutí soupeře odhalit svůj plán nebo napětí rozvést nevýhodně.' },
  'rm-pawns-15': { introduction: 'Ve francouzské obraně útočí černý na základnu.', question: 'V pěšcovém řetězu francouzské obrany útočí černý na základnu bílého kterým průlomem?', options: ['...c5', '...h5', '...a5', '...g5'], explanation: 'Tematický průlom ...c5 zasahuje základnu řetězu bílého d4-e5, aby ho podkopal.' },
  'rm-pawns-16': { introduction: 'Braním se napětí vyřeší.', question: 'Rozvedení pěšcového napětí braním obvykle:', options: ['Nemá na pozici vliv', 'Vyjasní strukturu a může soupeři poskytnout užitečné zpětné braní', 'Vždy získá pěšce', 'Vynutí výměnu dam'], explanation: 'Braní rozvede napětí do pevné struktury, takže by mělo být načasováno ve tvůj prospěch, ne pro soupeřovo zpětné braní.' },

  'rm-pawns-17': { introduction: 'Volnému pěšci nic nebrání v cestě.', question: 'Co je volný (passed) pěšec?', options: ['Pěšec, který byl sebrán', 'Pěšec, před nímž na jeho ani sousedních sloupcích není soupeřův pěšec', 'Kterýkoli pěšec na páté řadě', 'Pěšec krytý králem'], explanation: 'Volný pěšec má volnou cestu k proměně; žádný soupeřův pěšec ho nemůže zablokovat ani sebrat při postupu.' },
  'rm-pawns-18': { introduction: 'Nimcovič měl o volných pěšcích jasno.', question: 'Slavná Nimcovičova rada o volných pěšcích zní, že se mají:', options: ['Vyměnit', 'Zablokovat', 'Nikdy neposouvat', 'Vždy jsou slabí'], explanation: 'Nimcovič učil, že „volný pěšec je zločinec, kterého je třeba držet pod zámkem" — tedy zablokovat.' },
  'rm-pawns-19': { introduction: 'Která figura blokuje nejlépe?', question: 'Která figura je tradičně považována za ideálního blokátora volného pěšce?', options: ['Věž', 'Dáma', 'Jezdec', 'Střelec'], explanation: 'Jezdec blokuje dobře, protože na rozdíl od věže či střelce jeho síla neklesá, když stojí přímo před pěšcem.' },
  'rm-pawns-20': { introduction: 'Volný pěšec krytý dalším pěšcem.', question: 'Co je krytý volný pěšec?', options: ['Volný pěšec krytý jiným pěšcem', 'Volný pěšec za věží', 'Pěšec na výchozím poli', 'Pěšec krytý pouze králem'], explanation: 'Krytý volný pěšec je volný pěšec podpořený spřáteleným pěšcem, což ho činí obzvlášť nepříjemným.' },
  'rm-pawns-21': { introduction: 'Proč pěšce raději zablokovat?', question: 'Proč volného pěšce spíše zablokovat než ignorovat?', options: ['Kvůli zisku tempa', 'Aby se zastavil jeho postup a zneškodnila hrozba proměny', 'Protože to vyžadují pravidla', 'Aby se vynutil pat'], explanation: 'Pevná blokáda pěšce znehybní, odebere mu dynamiku a uvolní ti ruce k hře jinde.' },
  'rm-pawns-22': { introduction: 'Vzdálený volný pěšec láká krále.', question: 'Vzdálený volný pěšec je cenný hlavně proto, že dokáže:', options: ['Proměnit se jedním tahem', 'Odlákat soupeřova krále daleko od ostatních pěšců', 'Nikdy nebýt sebrán', 'Táhnout kdykoli o dvě pole'], explanation: 'Protože je daleko od hlavní pěšcové masy, vzdálený volný pěšec odláká soupeřova krále a tvůj král mezitím sbírá pěšce jinde.' },
  'rm-pawns-23': { introduction: 'Jak z převahy udělat volného pěšce?', question: 'Obvyklý způsob, jak vytvořit volného pěšce ze zdravé pěšcové převahy, je:', options: ['Vyměnit všechny pěšce', 'Postupovat s převahou tak, aby prošel neobsazený kandidát', 'Nechat pěšce na výchozích polích', 'Obětovat věž'], explanation: 'Postup převahy vedený kandidátem, kterému nestojí v cestě žádný soupeřův pěšec, vytvoří volného pěšce.' },
  'rm-pawns-24': { introduction: 'Jak vzdálený volný pěšec vyhrává v koncovce?', question: 'V pěšcových koncovkách vyhrává vzdálený volný pěšec tím, že:', options: ['Se okamžitě promění', 'Přitáhne soupeřova krále na jedno křídlo, zatímco tvůj král sbírá pěšce na druhém', 'Dá věčný šach', 'Vynutí výměnu jezdců'], explanation: 'Soupeřův král musí honit vzdáleného volného pěšce, takže tvůj král uklidí zbývající pěšce na opačné straně.' },

  'rm-pawns-25': { introduction: 'Izolovaný dámský pěšec — kde stojí?', question: 'Izolovaný dámský pěšec (IQP) je izolovaný pěšec obvykle na:', options: ['Sloupci a', 'Sloupci d', 'Sloupci h', 'Druhé řadě'], explanation: 'IQP je osamocený pěšec na d4 (nebo d5) bez vlastních pěšců na sloupcích c a e, kteří by ho podpořili.' },
  'rm-pawns-26': { introduction: 'V čem je IQP pro svého majitele plusem?', question: 'Co je hlavní dynamickou předností strany, která má IQP?', options: ['Bezpečnější král', 'Aktivní figury, prostor navíc a otevřené sloupce c a e k útoku', 'Pěšec navíc', 'Jistá remíza'], explanation: 'IQP dává prostor a otevřené sloupce, což majiteli poskytuje aktivitu figur a útočné šance, hlavně ve střední hře.' },
  'rm-pawns-27': { introduction: 'Jak hrát proti IQP?', question: 'Strana hrající proti IQP obecně chce:', options: ['Nechat dámy na šachovnici a útočit', 'Zablokovat pěšce a výměnami směřovat do koncovky', 'Posunout všechny své pěšce', 'Vyhnout se obsazení pole d5'], explanation: 'Blokáda pěšce na d a výměny figur snižují aktivitu majitele a odhalují IQP jako slabinu v koncovce.' },
  'rm-pawns-28': { introduction: 'Klíčový průlom majitele IQP.', question: 'Klíčový průlom ve středu, který majitel IQP často připravuje, je:', options: ['Postup d5', 'Dlouhá rošáda', 'Postup a4', 'Pěšcová bouře h4-h5'], explanation: 'Postup d4-d5 ve vhodné chvíli osvobodí pěšce, otevře linie a aktivuje figury, než ho stačí soupeř zablokovat.' },
  'rm-pawns-29': { introduction: 'Dva pěšci vedle sebe bez sousedů.', question: 'Co jsou „visící pěšci" (hanging pawns)?', options: ['Dva pěšci, kteří se chystají padnout', 'Dva spojení vlastní pěšci na sousedních sloupcích bez pěšců na okolních sloupcích', 'Pěšci visící z okraje', 'Dva zdvojení pěšci'], explanation: 'Visící pěšci jsou sousední dvojice (obvykle pěšci c a d) s polootevřenými sloupci po obou stranách a bez sousedních pěšců.' },
  'rm-pawns-30': { introduction: 'V čem je slabina visících pěšců?', question: 'Klíčovou slabinou visících pěšců je, že:', options: ['Nikdy nemohou postoupit', 'Pokud jsou donuceni postoupit, jeden zeslábne a pole před ním se stane oporným bodem', 'Musí je bránit král', 'Nemohou brát'], explanation: 'Pod tlakem mohou být pěšci nuceni postoupit, přičemž jeden zůstane zaostalý či izolovaný a soupeř získá silné blokádové pole.' },
  'rm-pawns-31': { introduction: 'Odkud pochází carlsbadská struktura?', question: 'Carlsbadská pěšcová struktura vzniká nejtypičtěji z:', options: ['Sicilské obrany drak', 'Odmítnutého dámského gambitu, výměnná varianta', 'Královské indické obrany', 'Španělské hry'], explanation: 'Carlsbadská struktura pochází z výměnné varianty odmítnutého dámského gambitu, s bílými pěšci na sloupcích c a d proti černému c6/d5.' },
  'rm-pawns-32': { introduction: 'Klasický plán bílého v carlsbadské struktuře.', question: 'V carlsbadské struktuře je klasickým plánem bílého na dámském křídle:', options: ['Menšinový útok', 'Oběť střelce na h7', 'Fianchetto', 'Pěšcová bouře g4-g5'], explanation: 'Standardním carlsbadským plánem bílého je menšinový útok postupem b4-b5, který vytvoří trvalou slabinu na c6.' },

  'rm-pawns-33': { introduction: 'Útok menším počtem pěšců.', question: 'Co je menšinový útok?', options: ['Útok menším počtem figur', 'Postup pěšcové menšiny proti větší pěšcové skupině soupeře s cílem vytvořit slabinu', 'Útok pouze králem', 'Oběť lehké figury'], explanation: 'Menšinový útok využívá méně pěšců (často a a b), kteří postoupí proti větší skupině pěšců soupeře a vyvolají slabého pěšce.' },
  'rm-pawns-34': { introduction: 'Cíl menšinového útoku v Carlsbadu.', question: 'V Carlsbadu má menšinový útok b4-b5xc6 zanechat černému:', options: ['Volného pěšce d', 'Zaostalého či slabého pěšce na c6', 'Zdvojené pěšce f', 'Krytého volného pěšce'], explanation: 'Po b5xc6 černý bere zpět a zůstane mu zaostalý pěšec c6 na polootevřeném sloupci — pevný terč.' },
  'rm-pawns-35': { introduction: 'Na kterém křídle probíhá?', question: 'Menšinový útok obvykle probíhá na které straně šachovnice?', options: ['Na královském křídle', 'Na dámském křídle', 'Pouze ve středu', 'Na straně, kam se rošovali králové'], explanation: 'V Carlsbadu probíhá na dámském křídle, kde pěšci a a b bílého postupují proti pěšcům a, b a c černého.' },
  'rm-pawns-36': { introduction: 'Více pěšců na jednom křídle.', question: 'Co je pěšcová převaha (majorita)?', options: ['Mít více pěšců než figur', 'Mít více pěšců než soupeř na jedné straně šachovnice', 'Vlastnit všech osm pěšců', 'Pěšec na většině řad'], explanation: 'Pěšcová převaha je početní výhoda v pěšcích na jednom křídle, například čtyři proti třem na dámském křídle.' },
  'rm-pawns-37': { introduction: 'Hlavní přínos zdravé převahy.', question: 'Hlavní dlouhodobou hodnotou zdravé pěšcové převahy je schopnost:', options: ['Vytvořit volného pěšce', 'Vynutit pat', 'Vyměnit dámy', 'Získat kvalitu'], explanation: 'Zdravá převaha může nakonec vytvořit volného pěšce, což je rozhodující výhoda zejména v koncovce.' },
  'rm-pawns-38': { introduction: 'Proč je cenná převaha v centru?', question: 'Pěšcová převaha ve středu je ceněná, protože dokáže:', options: ['Pouze bránit', 'Získat prostor, omezit soupeřovy figury a postupem vytvořit centrálního volného pěšce', 'Nikdy nebýt zablokována', 'Zaručit remízu'], explanation: 'Centrální pěšci svírají soupeře a při pohyblivosti mohou postoupit a vytvořit nebezpečného volného pěšce uprostřed.' },
  'rm-pawns-39': { introduction: 'Jak reaguje černý v Carlsbadu?', question: 'Standardní protihra černého proti menšinovému útoku bílého v Carlsbadu je:', options: ['Postup pěšce a', 'Hledat figurovou hru na královském křídle nebo centrální průlom ...e5', 'Vyměnit najednou všechny věže', 'Ihned posunout pěšce h na h4'], explanation: 'Zatímco bílý mele na dámském křídle, černý hledá aktivitu na královském křídle nebo osvobozující ...e5 ve středu.' },
  'rm-pawns-40': { introduction: 'Kterým pěšcem převahy začít?', question: 'Při mobilizaci pěšcové převahy by měl obecně postoupit první který pěšec?', options: ['Ten nejblíže králi', '„Kandidát" — pěšec, kterému nestojí v cestě soupeřův pěšec', 'Kterýkoli krajní pěšec', 'Nejlépe krytý pěšec'], explanation: 'Vede se neobsazeným kandidátem, protože právě on může prorazit a stát se volným pěšcem.' },
};
