import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Opening Theory roadmap bank (rm-openthy-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid. Chess opening names and
// standard move notation are kept as established terms.
export const openingTheoryTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-openthy-1': { introduction: 'Vzpomeň si na základní zásady zahájení.', question: 'Jaké jsou tři klasické cíle zahájení?', options: ['Ovládnout centrum, vyvinout figury a zajistit bezpečí krále', 'Rychle vyměnit všechny figury', 'Dostat každý pěšec co nejdál', 'Vytáhnout nejdřív dámu'], explanation: 'Zásady zahájení jsou boj o centrum, vývin lehkých figur a rošáda pro bezpečí krále.' },
  'rm-openthy-2': { introduction: 'Jde o nejcennější políčka uprostřed šachovnice.', question: 'Která čtyři pole tvoří „centrum", o něž se v zahájení bojuje?', options: ['a1, a8, h1, h8', 'b2, b7, g2, g7', 'e4, d4, e5, d5', 'c3, f3, c6, f6'], explanation: 'Centrální pole e4, d4, e5 a d5 jsou nejcennější, protože figury na nich ovládají nejvíc prostoru.' },
  'rm-openthy-3': { introduction: 'Co znamená „vyvíjet" figury?', question: 'Vývin figury v zahájení znamená především:', options: ['Dostat jezdce a střelce ze základní řady do aktivní hry', 'Posouvat pěšce nahoru a dolů', 'Nechat figury na výchozích polích', 'Vyměnit věže'], explanation: 'Vývin znamená dostat jezdce a střelce z první řady na pole, odkud ovlivňují hru.' },
  'rm-openthy-4': { introduction: 'Jak obvykle zajistíš krále?', question: 'Jaký je obvyklý způsob, jak v zahájení zajistit bezpečí krále?', options: ['Vytáhnout ho do centra', 'Rošáda', 'Nechat ho na e1/e8', 'Vytlačit pěšce f'], explanation: 'Rošáda ukryje krále do rohu za hradbu pěšců a propojí věže.' },
  'rm-openthy-5': { introduction: 'Proč je brzký výpad dámou riskantní?', question: 'Proč je předčasný vývin dámy často chybou?', options: ['Dáma se nemůže pohybovat daleko', 'Je to proti pravidlům', 'Soupeř získá tempo tím, že ji napadá lehkými figurami', 'Dáma zeslábne'], explanation: 'Vystavenou dámu lze honit vyvíjenými figurami, takže soupeř získává tempo, zatímco ustupuješ.' },
  'rm-openthy-6': { introduction: 'Které figury mají jít ven dřív než dáma?', question: 'Které figury by se obecně měly vyvinout dříve než dáma?', options: ['Věže', 'Král', 'Žádné, dáma jde první', 'Lehké figury (jezdci a střelci)'], explanation: 'Nejdřív ven jezdci a střelci; dáma se vyvíjí později, aby nebyla vystavena útoku.' },
  'rm-openthy-7': { introduction: 'Co se stane, když stále táhneš jednou figurou?', question: 'Opakované tahání stejnou figurou v zahájení obvykle:', options: ['Získává materiál', 'Plýtvá časem (tempem), který by mohl posloužit k vývinu', 'Je nutné k rošádě', 'Ovládá víc centra'], explanation: 'Každý tah v zahájení by měl ideálně vyvinout novou figuru; opakované tahání jednou figurou ztrácí cenné tempo.' },
  'rm-openthy-8': { introduction: 'Co znamená pojem „tempo"?', question: 'Pojem „tempo" v zahájení označuje:', options: ['Jeden tah jako jednotku času', 'Zbývající čas na hodinách', 'Druh matu', 'Pěšcovou strukturu'], explanation: 'Tempo je jeden tah; získat tempo znamená udělat užitečný pokrok a přinutit soupeře reagovat.' },

  'rm-openthy-9': { introduction: 'Poznáš zahájení podle střelce na c4?', question: 'Po 1.e4 e5 2.Jf3 Jc6 zahajuje tah 3.Sc4 které zahájení?', options: ['Španělskou hru (Ruy Lopez)', 'Italskou hru', 'Skotskou hru', 'Petrov'], explanation: 'Postavení střelce na c4 je Italská hra, míří střelcem na černé pole f7.' },
  'rm-openthy-10': { introduction: 'Které slabé pole střelec míří?', question: 'V Italské hře střelec na c4 míří především na které slabé pole?', options: ['f7', 'a7', 'h7', 'd7'], explanation: 'Pole f7 hájí v zahájení jen král, proto na něj střelec z c4 tlačí.' },
  'rm-openthy-11': { introduction: 'Poznáš zahájení podle střelce na b5?', question: 'Po 1.e4 e5 2.Jf3 Jc6 je tah 3.Sb5:', options: ['Skotská hra', 'Italská hra', 'Španělská hra (Ruy Lopez)', 'Vídeňská hra'], explanation: 'Střelec na b5, který vazbou tlačí na jezdce c6 bránícího e5, je Španělská hra (Ruy Lopez).' },
  'rm-openthy-12': { introduction: 'Co dělá tah jezdcem na f3?', question: 'Co dělá tah 2.Jf3 (po 1.e4 e5)?', options: ['Brání pěšce e4', 'Napadá pěšce e5', 'Připravuje dlouhou rošádu', 'Vytváří vazbu na střelce'], explanation: 'Jezdec na f3 napadá černého pěšce e5, takže ho černý musí bránit, obvykle tahem 2...Jc6.' },
  'rm-openthy-13': { introduction: 'Poznáš zahájení podle úderu d4?', question: 'Po 1.e4 e5 2.Jf3 Jc6 je agresivní tah 3.d4:', options: ['Skotská hra', 'Španělská hra', 'Hra čtyř jezdců', 'Královský gambit'], explanation: 'Skotská hra udeří tahem 3.d4 a okamžitě otevírá centrum.' },
  'rm-openthy-14': { introduction: 'Jak se říká klidné italské variantě?', question: 'Italská varianta 3.Sc4 Sc5 s pomalou symetrickou hrou se přezdívá:', options: ['Drak', 'Giuoco Piano („tichá hra")', 'Marshall', 'Berlínská zeď'], explanation: 'Giuoco Piano znamená italsky „tichá hra" a popisuje klidný klasický vývin.' },
  'rm-openthy-15': { introduction: 'Jak se jmenuje hlavní obrana ve Španělské hře?', question: 'Ve Španělské hře je běžná odpověď černého 3...a6 (odhánějící střelce):', options: ['Berlínská obrana', 'Morphyho obrana', 'Marshallův útok', 'Výměnná varianta'], explanation: 'Tah 3...a6, který zpochybňuje střelce na b5, je Morphyho obrana, hlavní varianta Španělské hry.' },
  'rm-openthy-16': { introduction: 'Jak vzniká Evansův gambit?', question: 'Evansův gambit vzniká v Italské hře, když bílý zahraje:', options: ['4.b4, obětuje pěšce pro získání času a silného centra', '4.Jg5 s útokem na f7', '4.d3 klidně', '4.O-O ihned'], explanation: 'Evansův gambit (4.b4) obětuje pěšce b, aby odvedl černého střelce a s tempem vybudoval silné centrum.' },

  'rm-openthy-17': { introduction: 'Poznáš obranu podle tahu 1...c5?', question: 'Zahájení 1.e4 c5 se nazývá:', options: ['Francouzská obrana', 'Sicilská obrana', 'Caro-Kann', 'Pircova obrana'], explanation: 'Odpověď 1...c5 na 1.e4 je Sicilská obrana, agresivní boj o centrum.' },
  'rm-openthy-18': { introduction: 'Poznáš obranu podle tahu 1...e6?', question: 'Odpověď 1.e4 e6 zavádí:', options: ['Francouzskou obranu', 'Sicilskou obranu', 'Skandinávskou obranu', 'Caro-Kann'], explanation: 'Francouzská obrana, 1...e6, připravuje tah ...d5, kterým zpochybní bílého pěšce e4.' },
  'rm-openthy-19': { introduction: 'Poznáš solidní obranu podle 1...c6?', question: 'Solidní obrana 1.e4 c6 je:', options: ['Sicilská', 'Francouzská', 'Caro-Kann', 'Alechinova obrana'], explanation: 'Caro-Kann, 1...c6, připravuje ...d5 a zachovává zdravou pěšcovou strukturu.' },
  'rm-openthy-20': { introduction: 'Která obrana je na vrcholové úrovni nejoblíbenější?', question: 'Která obrana je nejoblíbenější odpovědí na 1.e4 na mistrovské úrovni?', options: ['Sicilská obrana', 'Pircova obrana', 'Alechinova obrana', 'Owenova obrana'], explanation: 'Sicilská je statisticky nejhranější a nejúspěšnější obranou proti 1.e4.' },
  'rm-openthy-21': { introduction: 'Jaká je slabina Francouzské obrany?', question: 'Známou nevýhodou Francouzské obrany pro černého je:', options: ['Uvězněná dáma', 'Střelec na bílých polích je často pasivní za pěšci e6/d5', 'Rošáda je zakázaná', 'Černý nemůže vyvinout jezdce'], explanation: 'Pěšec na e6 blokuje černého střelce na bílých polích, který může zůstat po velkou část partie pasivní.' },
  'rm-openthy-22': { introduction: 'Jak se jmenuje slavná varianta s ...a6?', question: 'V Sicilské je pružná varianta s ...a6 (např. 5...a6) slavná:', options: ['Drak', 'Najdorfova varianta', 'Ševeningenská', 'Sveshnikov'], explanation: 'Najdorfova varianta, charakteristická tahem ...a6, je jedním z nejrozebranějších a nejuznávanějších sicilských systémů.' },
  'rm-openthy-23': { introduction: 'V čem má Caro-Kann výhodu oproti Francouzské?', question: 'Jednou z výhod Caro-Kann oproti Francouzské je, že černý může:', options: ['Zcela vynechat vývin', 'Aktivně vyvinout střelce na bílých polích ještě před ...e6', 'Vyhnout se tahům pěšci', 'Rošovat v prvním tahu'], explanation: 'Tím, že hraje ...c6 místo ...e6, může černý vyvinout střelce na bílých polích mimo pěšcový řetěz.' },
  'rm-openthy-24': { introduction: 'Čím je typická varianta Drak?', question: 'Sicilská varianta Drak je charakteristická tím, že černý:', options: ['Fianchettuje střelce na g7 tahem ...g6', 'Táhne pěšce a na a3', 'Brzy vymění dámy', 'Rošuje na dámské křídlo ve druhém tahu'], explanation: 'V Draku hraje černý ...g6 a ...Sg7 a míří fianchettovaným střelcem po dlouhé diagonále.' },

  'rm-openthy-25': { introduction: 'Poznáš zahájení podle 2.c4?', question: 'Zahájení 1.d4 d5 2.c4 je:', options: ['Královský gambit', 'Dámský gambit', 'Londýnský systém', 'Colleův systém'], explanation: 'Nabídka pěšce c tahem 2.c4 je Dámský gambit, jehož cílem je podkopat černého centrálního pěšce d5.' },
  'rm-openthy-26': { introduction: 'Jak se jmenuje odmítnutí gambitu tahem ...e6?', question: 'Po 1.d4 d5 2.c4 je odpověď 2...e6:', options: ['Přijatý dámský gambit', 'Odmítnutý dámský gambit', 'Slovanská obrana', 'Albinův protigambit'], explanation: 'Podepření pěšce d5 tahem 2...e6 místo braní je Odmítnutý dámský gambit.' },
  'rm-openthy-27': { introduction: 'Poznáš obranu podle 2...c6?', question: 'Obrana 1.d4 d5 2.c4 c6 je:', options: ['Slovanská obrana', 'Nimcoindická', 'Gruenfeldova', 'Holandská'], explanation: 'Slovanská obrana podepírá d5 pěšcem c a přitom nechává otevřenou diagonálu střelce na bílých polích.' },
  'rm-openthy-28': { introduction: 'Proč to není „pravý" gambit?', question: 'Proč se Dámský gambit nepovažuje za „pravý" gambit?', options: ['Je zakázáno ho přijmout', 'Bílý obvykle obětovaného pěšce získá zpět', 'Ve skutečnosti se žádný pěšec nenabízí', 'Černý ho musí odmítnout'], explanation: 'Černý nedokáže pohodlně udržet pěšce navíc na c4, takže bílý ho zpravidla získá zpět; oběť je jen dočasná.' },
  'rm-openthy-29': { introduction: 'Jaká je hlavní myšlenka Královské indické?', question: 'Královská indická obrana (1.d4 Jf6 2.c4 g6) se řídí myšlenkou:', options: ['Ihned obsadit centrum pěšci', 'Nechat bílého vybudovat velké centrum a pak na něj zaútočit', 'Okamžitě vyměnit dámy', 'Vyhnout se fianchettu'], explanation: 'Černý fianchettuje ...g6 a ...Sg7, dovolí bílému široké centrum a pak proti němu udeří tahem ...e5 nebo ...c5.' },
  'rm-openthy-30': { introduction: 'Čím je definována Nimcoindická?', question: 'Nimcoindická obrana je definována tahem černého:', options: ['3...Sb4, vazbou na jezdce c3', '3...g6', '3...c5', '3...Jc6'], explanation: 'Po 1.d4 Jf6 2.c4 e6 3.Jc3 hraje černý 3...Sb4, vazbou na jezdce a bojem o centrum figurami.' },
  'rm-openthy-31': { introduction: 'Jak funguje Gruenfeldova obrana?', question: 'Gruenfeldova obrana (s ...g6 a poté ...d5) funguje tak, že:', options: ['Odmítá pohnout jakýmkoli pěšcem', 'Nechá bílého vytvořit velké centrum a pak ho napadne figurami a tahem ...d5', 'Vymění všechny lehké figury', 'Rošuje na dámské křídlo'], explanation: 'Gruenfeldova je hypermoderní obrana: černý vyzve bílého k velkému centru jen proto, aby ho podkopal.' },
  'rm-openthy-32': { introduction: 'Čím je typická Dámská indická?', question: 'Dámská indická obrana je charakteristická tím, že černý hraje:', options: ['...b6 a ...Sb7, fianchetto střelce na bílých polích', 'ihned ...f5', '...h5 a ...Vh6', '...a5 a ...Va6'], explanation: 'Po 1.d4 Jf6 2.c4 e6 3.Jf3 hraje černý ...b6 a ...Sb7, aby tlačil po dlouhé bílé diagonále, zejména na e4.' },

  'rm-openthy-33': { introduction: 'Poznáš romantické zahájení 2.f4?', question: 'Romantické zahájení 1.e4 e5 2.f4 je:', options: ['Vídeňská hra', 'Královský gambit', 'Střelcova hra', 'Středová hra'], explanation: 'Královský gambit nabízí pěšce f, aby otevřel linie a získal centrum k útoku.' },
  'rm-openthy-34': { introduction: 'Jak se jmenuje zahájení 1.c4?', question: 'Křídelní zahájení 1.c4 se nazývá:', options: ['Anglické zahájení', 'Retiho zahájení', 'Birdovo zahájení', 'Larsenovo zahájení'], explanation: 'Anglické zahájení, 1.c4, bojuje z křídla o pole d5 a často přechází do jiných systémů.' },
  'rm-openthy-35': { introduction: 'Jaká je hlavní myšlenka hypermoderních zahájení?', question: 'Základní myšlenkou „hypermoderních" zahájení je:', options: ['Obsadit centrum pěšci naráz', 'Ovládat centrum z dálky figurami a pak ho napadnout', 'Nikdy nevyvinout střelce', 'Útočit už od prvního tahu'], explanation: 'Hypermoderní hra nechá soupeře vybudovat pěšcové centrum a pak na něj útočí fianchettovanými střelci a pěšcovými údery.' },
  'rm-openthy-36': { introduction: 'Jak vzniká Moderní Benoni?', question: 'Moderní Benoni obvykle vzniká po:', options: ['1.d4 Jf6 2.c4 c5 3.d5 e6', '1.e4 e5 2.Jf3', '1.d4 d5 2.c4 c6', '1.c4 e5'], explanation: 'Po 1.d4 Jf6 2.c4 c5 3.d5 e6 přijímá černý stísněnou, ale dynamickou strukturu s aktivní hrou figur a pěšcovou převahou na dámském křídle.' },
  'rm-openthy-37': { introduction: 'Proč bílý obětuje pěšce f?', question: 'Proč se v Královském gambitu bílý vzdává pěšce f?', options: ['Aby rychle prohrál', 'Aby otevřel linie a vybudoval silné pěšcové centrum k útoku', 'Protože pěšec f je bezcenný', 'Aby vynutil remízu'], explanation: 'Oběť pěšce uvolní sloupec f a umožní bílému ovládnout centrum a hledat rychlé útočné šance.' },
  'rm-openthy-38': { introduction: 'Co získá černý za obětovaného pěšce v Benko gambitu?', question: 'Benko (Volžský) gambit, 1.d4 Jf6 2.c4 c5 3.d5 b5, se hraje pro získání:', options: ['Rychlého matu', 'Dlouhodobého tlaku na dámském křídle za obětovaného pěšce', 'Dámy navíc', 'Uzavřené pozice'], explanation: 'Černý obětuje pěšce b za trvalý tlak po polootevřených sloupcích a a b proti bílému dámskému křídlu.' },
  'rm-openthy-39': { introduction: 'Kterým tahem začíná Retiho zahájení?', question: 'Hypermoderní Retiho zahájení začíná tahem:', options: ['1.Jf3', '1.e4', '1.d4', '1.f4'], explanation: 'Retiho zahájení začíná 1.Jf3, často následované c4 a fianchettem na královském křídle, a tlačí na centrum z dálky.' },
  'rm-openthy-40': { introduction: 'Kdo položil základy hypermodernismu?', question: 'Kteří hráči jsou považováni za zakladatele hypermoderní školy?', options: ['Morphy a Anderssen', 'Nimcovič a Reti', 'Capablanca a Lasker', 'Philidor a Staunton'], explanation: 'Aron Nimcovič a Richard Reti položili ve 20. letech základy hypermoderní teorie a zpochybnili klasické pojetí centra.' },
};
