// The Endocrine System roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const endocrineSystemSeeds: Seed[] = [
  // ── Level 1 — Hormones & endocrine glands overview ──
  { q: 'What is a hormone?', opts: ['A muscle that contracts', 'A chemical messenger carried in the blood', 'A type of nerve cell', 'A digestive enzyme'], a: 1, e: 'Hormones are chemical messengers secreted by endocrine glands and carried in the blood to target cells.', tags: ['Endocrine System', 'hormones'] },
  { q: 'How do endocrine glands release their products?', opts: ['Through ducts onto the skin', 'Directly into the bloodstream', 'Into the digestive tract only', 'Through sweat pores'], a: 1, e: 'Endocrine glands are ductless and secrete hormones directly into the bloodstream.', tags: ['Endocrine System', 'glands'] },
  { q: 'Compared with the nervous system, hormonal signals are generally:', opts: ['Faster but short-lived', 'Slower but longer-lasting', 'Instant and permanent', 'Not used for communication'], a: 1, e: 'Nerve signals are fast and brief; hormonal signals travel more slowly but their effects last longer.', tags: ['Endocrine System', 'signaling'] },
  { q: 'Which of these is an endocrine gland?', opts: ['Thyroid', 'Gallbladder', 'Salivary gland', 'Sweat gland'], a: 0, e: 'The thyroid is an endocrine gland; the others are exocrine or storage organs that use ducts.', tags: ['Endocrine System', 'glands'] },
  { q: 'A hormone only affects a cell that has the correct:', opts: ['Receptor', 'Nucleus', 'Mitochondria', 'Ribosome'], a: 0, e: 'A hormone acts only on target cells that carry a specific receptor able to recognise and bind it.', tags: ['Endocrine System', 'receptors'] },
  { q: 'Chemically, most hormones are steroids or:', opts: ['Proteins and amino-acid derivatives', 'Simple sugars', 'DNA strands', 'Metals'], a: 0, e: 'Hormones are broadly either lipid-based steroids or protein/peptide and amino-acid-derived molecules.', tags: ['Endocrine System', 'chemistry'] },
  { q: 'The stable internal environment kept by the nervous and endocrine systems is called:', opts: ['Homeostasis', 'Metabolism', 'Digestion', 'Respiration'], a: 0, e: 'Homeostasis is the maintenance of a steady internal environment, regulated largely by hormones.', tags: ['Endocrine System', 'homeostasis'] },
  { q: 'Which is a purely exocrine (not endocrine) gland?', opts: ['Sweat gland', 'Thyroid', 'Adrenal gland', 'Pituitary gland'], a: 0, e: 'Sweat glands release their product through ducts, so they are exocrine, not endocrine.', tags: ['Endocrine System', 'glands'] },

  // ── Level 2 — The hypothalamus & pituitary gland ──
  { q: 'Which gland is often called the "master gland"?', opts: ['Pituitary', 'Pineal', 'Thymus', 'Thyroid'], a: 0, e: 'The pituitary is the master gland because its hormones control many other endocrine glands.', tags: ['Endocrine System', 'pituitary'] },
  { q: 'The pituitary gland has two main lobes: anterior and:', opts: ['Posterior', 'Lateral', 'Superior', 'Central'], a: 0, e: 'The pituitary is divided into an anterior lobe and a posterior lobe with different roles.', tags: ['Endocrine System', 'pituitary'] },
  { q: 'The pituitary gland is directly controlled by which brain region?', opts: ['Cerebellum', 'Hypothalamus', 'Medulla', 'Hippocampus'], a: 1, e: 'The hypothalamus links the nervous and endocrine systems and controls the pituitary gland.', tags: ['Endocrine System', 'hypothalamus'] },
  { q: 'Which anterior pituitary hormone stimulates the thyroid gland?', opts: ['TSH', 'ADH', 'Insulin', 'Melatonin'], a: 0, e: 'Thyroid-stimulating hormone (TSH) from the anterior pituitary drives the thyroid to make its hormones.', tags: ['Endocrine System', 'pituitary'] },
  { q: 'Growth hormone (GH) is released by the:', opts: ['Anterior pituitary', 'Posterior pituitary', 'Adrenal gland', 'Pancreas'], a: 0, e: 'Growth hormone, which promotes growth and cell repair, is secreted by the anterior pituitary.', tags: ['Endocrine System', 'growth hormone'] },
  { q: 'The posterior pituitary releases ADH and:', opts: ['Oxytocin', 'Cortisol', 'Glucagon', 'Thyroxine'], a: 0, e: 'The posterior pituitary stores and releases two hypothalamic hormones: ADH and oxytocin.', tags: ['Endocrine System', 'pituitary'] },
  { q: 'ADH (vasopressin) mainly acts on the kidneys to:', opts: ['Retain water', 'Lose water rapidly', 'Raise blood sugar', 'Digest fat'], a: 0, e: 'Antidiuretic hormone makes the kidneys reabsorb more water, concentrating the urine.', tags: ['Endocrine System', 'ADH'] },
  { q: 'How does the hypothalamus control the anterior pituitary?', opts: ['Via releasing hormones in a portal blood system', 'Via direct nerve axons', 'Via the spinal cord', 'It does not control it'], a: 0, e: 'The hypothalamus sends releasing and inhibiting hormones through the hypophyseal portal blood vessels.', tags: ['Endocrine System', 'hypothalamus'] },

  // ── Level 3 — Thyroid, parathyroid & adrenal glands ──
  { q: 'The thyroid gland is located in the:', opts: ['Neck', 'Abdomen', 'Chest', 'Pelvis'], a: 0, e: 'The butterfly-shaped thyroid gland wraps around the windpipe in the front of the neck.', tags: ['Endocrine System', 'thyroid'] },
  { q: 'Which mineral is needed to make thyroid hormones?', opts: ['Iodine', 'Calcium', 'Iron', 'Sodium'], a: 0, e: 'Iodine is an essential building block of the thyroid hormones thyroxine (T4) and T3.', tags: ['Endocrine System', 'thyroid'] },
  { q: 'Thyroid hormones such as thyroxine mainly regulate the body\'s:', opts: ['Metabolic rate', 'Blood clotting', 'Vision', 'Hearing'], a: 0, e: 'Thyroxine sets the basal metabolic rate, controlling how quickly cells use energy.', tags: ['Endocrine System', 'thyroid'] },
  { q: 'The adrenal glands sit on top of the:', opts: ['Kidneys', 'Lungs', 'Heart', 'Liver'], a: 0, e: 'There is one adrenal gland capping each kidney, hence the name (ad- = upon, renal = kidney).', tags: ['Endocrine System', 'adrenal'] },
  { q: 'Adrenaline (epinephrine) from the adrenal medulla prepares the body for:', opts: ['Fight or flight', 'Sleep', 'Digestion', 'Bone growth'], a: 0, e: 'Adrenaline triggers the rapid fight-or-flight response: faster heart rate, wider airways and released glucose.', tags: ['Endocrine System', 'adrenal'] },
  { q: 'Parathyroid hormone (PTH) regulates the blood level of:', opts: ['Calcium', 'Glucose', 'Oxygen', 'Sodium'], a: 0, e: 'PTH raises blood calcium by releasing it from bone and increasing its absorption and reabsorption.', tags: ['Endocrine System', 'parathyroid'] },
  { q: 'Calcitonin, which lowers blood calcium, is produced by the:', opts: ['Thyroid', 'Liver', 'Spleen', 'Ovaries'], a: 0, e: 'Calcitonin from the thyroid lowers blood calcium, acting as an antagonist to parathyroid hormone.', tags: ['Endocrine System', 'thyroid'] },
  { q: 'Cortisol, a steroid from the adrenal cortex, is released mainly in response to:', opts: ['Long-term stress', 'A full stomach', 'Bright light', 'Loud noise'], a: 0, e: 'Cortisol is the main stress hormone; it raises blood glucose and helps the body cope with prolonged stress.', tags: ['Endocrine System', 'adrenal'] },

  // ── Level 4 — The pancreas & blood-sugar regulation ──
  { q: 'The pancreas releases hormones from clusters of cells called the:', opts: ['Islets of Langerhans', 'Nephrons', 'Alveoli', 'Villi'], a: 0, e: 'The islets of Langerhans are the endocrine cell clusters of the pancreas that secrete insulin and glucagon.', tags: ['Endocrine System', 'pancreas'] },
  { q: 'Which hormone lowers blood glucose?', opts: ['Insulin', 'Glucagon', 'Adrenaline', 'Cortisol'], a: 0, e: 'Insulin lowers blood glucose by helping cells absorb it and store it as glycogen.', tags: ['Endocrine System', 'insulin'] },
  { q: 'Which hormone raises blood glucose?', opts: ['Glucagon', 'Insulin', 'Calcitonin', 'Oxytocin'], a: 0, e: 'Glucagon raises blood glucose by making the liver break down stored glycogen back into glucose.', tags: ['Endocrine System', 'glucagon'] },
  { q: 'Insulin is produced by which pancreatic islet cells?', opts: ['Beta cells', 'Alpha cells', 'Delta cells', 'Red blood cells'], a: 0, e: 'Beta cells of the islets of Langerhans secrete insulin when blood glucose is high.', tags: ['Endocrine System', 'insulin'] },
  { q: 'Glucagon is produced by which pancreatic islet cells?', opts: ['Alpha cells', 'Beta cells', 'Gamma cells', 'White blood cells'], a: 0, e: 'Alpha cells of the islets secrete glucagon when blood glucose falls too low.', tags: ['Endocrine System', 'glucagon'] },
  { q: 'After a meal, insulin causes body cells to:', opts: ['Take up glucose from the blood', 'Release glucose into the blood', 'Stop using glucose', 'Make more glucagon'], a: 0, e: 'Insulin signals cells to absorb glucose from the blood, lowering blood sugar after eating.', tags: ['Endocrine System', 'insulin'] },
  { q: 'Insulin promotes storage of glucose in the liver as:', opts: ['Glycogen', 'Starch', 'Cellulose', 'Keratin'], a: 0, e: 'The liver stores excess glucose as glycogen, an animal storage carbohydrate, under insulin\'s influence.', tags: ['Endocrine System', 'glycogen'] },
  { q: 'In type 1 diabetes, blood sugar rises because the body:', opts: ['Cannot produce enough insulin', 'Makes too much insulin', 'Has no glucagon', 'Absorbs no water'], a: 0, e: 'In type 1 diabetes the immune system destroys beta cells, so little or no insulin is made and glucose stays high.', tags: ['Endocrine System', 'diabetes'] },

  // ── Level 5 — Reproductive hormones & feedback loops ──
  { q: 'The main male sex hormone is:', opts: ['Testosterone', 'Estrogen', 'Insulin', 'Cortisol'], a: 0, e: 'Testosterone drives male sexual development and the appearance of male secondary sex characteristics.', tags: ['Endocrine System', 'reproductive'] },
  { q: 'The main female sex hormones are estrogen and:', opts: ['Progesterone', 'Testosterone', 'Thyroxine', 'Adrenaline'], a: 0, e: 'Estrogen and progesterone regulate the menstrual cycle and female reproductive function.', tags: ['Endocrine System', 'reproductive'] },
  { q: 'Testosterone is produced mainly in the:', opts: ['Testes', 'Liver', 'Adrenal medulla', 'Pancreas'], a: 0, e: 'The testes produce most of the body\'s testosterone, with a small amount from the adrenal glands.', tags: ['Endocrine System', 'reproductive'] },
  { q: 'Estrogen and progesterone are produced mainly in the:', opts: ['Ovaries', 'Kidneys', 'Thyroid', 'Thymus'], a: 0, e: 'The ovaries are the main source of estrogen and progesterone in females.', tags: ['Endocrine System', 'reproductive'] },
  { q: 'Which pituitary hormones regulate the gonads?', opts: ['FSH and LH', 'TSH and GH', 'ADH and oxytocin', 'ACTH and prolactin'], a: 0, e: 'Follicle-stimulating hormone (FSH) and luteinising hormone (LH) control the ovaries and testes.', tags: ['Endocrine System', 'feedback'] },
  { q: 'Most hormone systems are kept in balance by which type of feedback?', opts: ['Negative feedback', 'Positive feedback', 'No feedback', 'Random feedback'], a: 0, e: 'Negative feedback dominates the endocrine system: a rising output switches off further production.', tags: ['Endocrine System', 'feedback'] },
  { q: 'In negative feedback, a rising hormone level tends to:', opts: ['Inhibit its own further release', 'Speed up its own release', 'Have no effect', 'Destroy the gland'], a: 0, e: 'High hormone levels feed back to the hypothalamus and pituitary to shut down further release, stabilising levels.', tags: ['Endocrine System', 'feedback'] },
  { q: 'The LH surge that triggers ovulation is an example of:', opts: ['Positive feedback', 'Negative feedback', 'Digestion', 'Random chance'], a: 0, e: 'Rising estrogen briefly boosts LH release, an unusual positive-feedback loop that triggers ovulation.', tags: ['Endocrine System', 'feedback'] },
];
