import type { QuestionTranslation } from './quiz-data';

export const historyOfScienceTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Antická a středověká věda ──
  'rm-histsci-1': { introduction: 'Zakladatel atomismu ve starověkém Řecku.', question: 'Který starořecký filozof tvrdil, že veškerá hmota se skládá z nepatrných nedělitelných částic zvaných atomy?', options: ['Démokritos', 'Platón', 'Pythagoras', 'Thálés'], explanation: 'Démokritos (spolu s Leukippem) rozvinul raný atomismus a zastával názor, že skutečnost tvoří atomy pohybující se v prázdnotě.' },
  'rm-histsci-2': { introduction: 'Klasické živly podle Aristotela.', question: 'Aristoteles učil, že veškerá pozemská hmota se skládá z kolika klasických živlů?', options: ['Tří', 'Čtyř', 'Pěti', 'Sedmi'], explanation: 'Aristoteles zastával názor, že pozemská hmota kombinuje čtyři živly: zemi, vodu, vzduch a oheň.' },
  'rm-histsci-3': { introduction: 'Geocentrický model, který přetrval přes tisíc let.', question: 'Čí geocentrický model umístil nehybnou Zemi do středu vesmíru na více než tisíciletí?', options: ['Ptolemaiův', 'Koperníkův', 'Eratosthenův', 'Archimédův'], explanation: 'Ptolemaiův Almagest (2. století n. l.) kodifikoval geocentrický model, který ovládal astronomii až do 16. století.' },
  'rm-histsci-4': { introduction: 'Zakladatelské dílo geometrie.', question: 'Který řecký matematik napsal Základy, zakladatelské dílo geometrie?', options: ['Eukleidés', 'Pythagoras', 'Ptolemaios', 'Hipparchos'], explanation: 'Eukleidovy Základy (kolem 300 př. n. l.) systematizovaly geometrii na základě axiomů a zůstaly standardním textem po dva tisíce let.' },
  'rm-histsci-5': { introduction: 'Perský učenec proslulý naukou o vidění.', question: 'Perský učenec Ibn al-Hajtham (Alhazen) významně přispěl především do které oblasti?', options: ['Optiky', 'Botaniky', 'Metalurgie', 'Kartografie'], explanation: 'Alhazenova Kniha optiky správně tvrdila, že vidění vzniká vstupem světla do oka, a využívala experimentální metodu.' },
  'rm-histsci-6': { introduction: 'Z jeho díla pochází samotné slovo „algebra“.', question: 'Slovo „algebra“ pochází z díla kterého matematika islámského zlatého věku?', options: ['Al-Chwárizmí', 'Avicenna', 'Al-Rází', 'Al-Bírúní'], explanation: 'Al-Chwárizmího pojednání „al-džabr“ dalo algebře jméno; z jeho jména máme také slovo „algoritmus“.' },
  'rm-histsci-7': { introduction: 'Lékařská učebnice používaná po staletí.', question: 'Čí Kánon medicíny byl po staletí standardní lékařskou učebnicí v Evropě i v islámském světě?', options: ['Avicenna (Ibn Síná)', 'Galén', 'Hippokratés', 'Vesalius'], explanation: 'Avicennův Kánon medicíny (11. století) systematizoval lékařské znalosti a používal se na univerzitách až do 17. století.' },
  'rm-histsci-8': { introduction: 'Antický učenec proslulý přesným měřením Země.', question: 'Čím je Eratosthenés proslulý ve starověku díky svému přesnému odhadu?', options: ['Obvodem Země', 'Rychlostí světla', 'Vzdáleností k jádru Slunce', 'Stářím vesmíru'], explanation: 'Eratosthenés použil úhly stínů v Syéné a Alexandrii k pozoruhodně přesnému odhadu obvodu Země.' },

  // ── Úroveň 2 — Vědecká revoluce ──
  'rm-histsci-9': { introduction: 'Autor heliocentrického modelu.', question: 'Který astronom navrhl heliocentrický model, který umístil Slunce do středu vesmíru?', options: ['Mikuláš Koperník', 'Tycho Brahe', 'Galileo Galilei', 'Giordano Bruno'], explanation: 'Koperníkovo dílo De revolutionibus (1543) oživilo a rozpracovalo heliocentrický model a zahájilo vědeckou revoluci.' },
  'rm-histsci-10': { introduction: 'Čtyři měsíce, které podpořily heliocentrismus.', question: 'Galileův dalekohledový objev čtyř velkých měsíců obíhajících kolem které planety podpořil heliocentrismus?', options: ['Jupitera', 'Saturnu', 'Marsu', 'Venuše'], explanation: 'V roce 1610 Galileo pozoroval čtyři měsíce Jupitera, čímž ukázal, že ne vše obíhá kolem Země.' },
  'rm-histsci-11': { introduction: 'Tvar planetárních drah podle Keplera.', question: 'Keplerův první zákon říká, že planety se pohybují po drahách jakého tvaru?', options: ['Elips', 'Dokonalých kružnic', 'Spirál', 'Parabol'], explanation: 'Kepler ukázal, že planetární dráhy jsou elipsy se Sluncem v jednom ohnisku, čímž se rozešel s antickými představami o kruhových drahách.' },
  'rm-histsci-12': { introduction: 'Newtonovo dílo z roku 1687 a zákon o čem?', question: 'Newtonovo dílo Principia z roku 1687 zavedlo zákon všeobecné čeho?', options: ['Gravitace', 'Elektromagnetismu', 'Termodynamiky', 'Relativity'], explanation: 'Principia formulovala všeobecnou gravitaci a tři pohybové zákony, čímž sjednotila pozemskou a nebeskou mechaniku.' },
  'rm-histsci-13': { introduction: 'Pozorovatel, jehož data využil Kepler.', question: 'Čí pečlivá pozorování pouhým okem poskytla data, která Kepler použil k odvození svých zákonů?', options: ['Tychona Brahe', 'Koperníka', 'Halleyho', 'Hooka'], explanation: 'Desetiletí přesných polohových dat Tychona Brahe, zejména o Marsu, umožnila Keplerovi odvodit eliptické dráhy.' },
  'rm-histsci-14': { introduction: 'Zastánce induktivního, experimentálního uvažování.', question: 'Který filozof prosazoval induktivní uvažování založené na experimentu jako základ vědecké metody?', options: ['Francis Bacon', 'René Descartes', 'John Locke', 'Thomas Hobbes'], explanation: 'Baconovo dílo Novum Organum (1620) obhajovalo systematické pozorování a indukci před aristotelskou dedukcí.' },
  'rm-histsci-15': { introduction: 'Fyziologický objev z roku 1628.', question: 'Williamu Harveymu se připisuje správný popis kterého fyziologického procesu v roce 1628?', options: ['Krevního oběhu', 'Buněčného dýchání', 'Vedení nervového vzruchu', 'Trávení tuků'], explanation: 'Harvey prokázal, že srdce pumpuje krev v uzavřeném oběhu, čímž vyvrátil galénovskou fyziologii.' },
  'rm-histsci-16': { introduction: 'Spor o prvenství v objevu diferenciálního počtu.', question: 'Newton a který matematik nezávisle na sobě rozvinuli diferenciální počet, což vyvolalo spor o prvenství?', options: ['Gottfried Leibniz', 'Blaise Pascal', 'Pierre de Fermat', 'Christiaan Huygens'], explanation: 'Leibniz a Newton nezávisle na sobě vynalezli diferenciální počet; Leibnizova notace se používá dodnes.' },

  // ── Úroveň 3 — Osvícenství a věda 19. století ──
  'rm-histsci-17': { introduction: 'Otec moderní chemie a překonaná teorie hoření.', question: 'Antoine Lavoisier bývá nazýván otcem moderní chemie za pomoc při vyvrácení které teorie?', options: ['Flogistonové teorie hoření', 'Teorie choroboplodných zárodků', 'Teorie kalorika', 'Atomové teorie'], explanation: 'Lavoisier ukázal, že hoření zahrnuje slučování s kyslíkem, čímž zdiskreditoval flogistonovou teorii a pojmenoval kyslík.' },
  'rm-histsci-18': { introduction: 'Charakteristická vlastnost atomů podle Daltona.', question: 'Daltonova atomová teorie z počátku 19. století navrhla, že každý prvek se skládá z atomů s charakteristickou jakou vlastností?', options: ['Hmotností (váhou)', 'Barvou', 'Elektrickým nábojem', 'Poločasem rozpadu'], explanation: 'Dalton tvrdil, že atomy daného prvku mají pevnou atomovou hmotnost a slučují se v celočíselných poměrech.' },
  'rm-histsci-19': { introduction: 'Mechanismus evoluce podle Darwina.', question: 'Darwinovo dílo O původu druhů z roku 1859 navrhlo evoluci poháněnou kterým mechanismem?', options: ['Přírodním výběrem', 'Dědičností získaných znaků', 'Samovolným vznikem života', 'Genetickým driftem'], explanation: 'Darwin tvrdil, že dědičná proměnlivost spolu s rozdílným přežíváním (přírodní výběr) pohání evoluční změny.' },
  'rm-histsci-20': { introduction: 'Mnich a jeho pokusy s hrachem.', question: 'Čí pokusy s rostlinami hrachu stanovily základní zákony dědičnosti?', options: ['Gregora Mendela', 'Louise Pasteura', 'Alfreda Wallace', 'Thomase Huxleyho'], explanation: 'Mendelovy křížicí pokusy z 60. let 19. století odhalily dominantní a recesivní faktory a založily genetiku (uznanou o desetiletí později).' },
  'rm-histsci-21': { introduction: 'Slavné dílo z roku 1869.', question: 'Čím je Dmitrij Mendělejev nejznámější díky svému dílu z roku 1869?', options: ['Periodickou tabulkou prvků', 'Kahanem', 'Teorií valence', 'Plynovými zákony'], explanation: 'Mendělejev uspořádal prvky podle atomové hmotnosti a vlastností a ponechal mezery, které předpověděly dosud neobjevené prvky.' },
  'rm-histsci-22': { introduction: 'Veličina, která v izolovaných soustavách roste.', question: 'Druhý termodynamický zákon zavedl kterou veličinu, jež má v izolovaných soustavách tendenci růst?', options: ['Entropii', 'Entalpii', 'Hybnost', 'Napětí'], explanation: 'Druhý zákon, formulovaný Clausiem a Kelvinem, říká, že entropie izolované soustavy nikdy neklesá.' },
  'rm-histsci-23': { introduction: 'Maxwellovy rovnice sjednotily elektřinu, magnetismus a co dalšího?', question: 'Rovnice Jamese Clerka Maxwella sjednotily elektřinu, magnetismus a který jev?', options: ['Světlo', 'Zvuk', 'Vedení tepla', 'Gravitaci'], explanation: 'Maxwell ukázal, že světlo je elektromagnetická vlna, čímž v 60. letech 19. století sjednotil optiku s elektromagnetismem.' },
  'rm-histsci-24': { introduction: 'Pasteurovy pokusy vyvrátily dlouho zastávanou myšlenku.', question: 'Pasteurovy pokusy z 60. let 19. století pomohly vyvrátit kterou dlouho zastávanou myšlenku?', options: ['Samovolný vznik života', 'Krevní oběh', 'Atomovou teorii', 'Heliocentrismus'], explanation: 'Pasteurovy pokusy s baňkami s labutím hrdlem ukázaly, že mikrobi vznikají z jiných mikrobů, čímž vyvrátil samovolný vznik života.' },

  // ── Úroveň 4 — Revoluce v moderní fyzice ──
  'rm-histsci-25': { introduction: 'Diskrétní jednotky energie z roku 1900.', question: 'Max Planck zahájil kvantovou teorii v roce 1900 návrhem, že energie se vyzařuje v diskrétních jednotkách zvaných jak?', options: ['Kvanta', 'Fotony', 'Elektrony', 'Pole'], explanation: 'K vysvětlení záření černého tělesa Planck navrhl, že energie přichází v diskrétních kvantech, E = hν, čímž položil základy kvantové fyziky.' },
  'rm-histsci-26': { introduction: 'Veličina konstantní pro všechny pozorovatele.', question: 'Einsteinova speciální teorie relativity z roku 1905 tvrdí, že která veličina je konstantní pro všechny pozorovatele?', options: ['Rychlost světla ve vakuu', 'Čas', 'Hmotnost', 'Kinetická energie'], explanation: 'Speciální relativita postuluje, že rychlost světla ve vakuu je neměnná, čímž se prostor a čas stávají relativními.' },
  'rm-histsci-27': { introduction: 'Gravitace jako zakřivení čeho?', question: 'Einsteinova obecná teorie relativity (1915) popisuje gravitaci jako zakřivení čeho?', options: ['Časoprostoru', 'Elektromagnetického pole', 'Éteru', 'Prázdných atomů'], explanation: 'Obecná relativita vykládá gravitaci jako zakřivení časoprostoru hmotou-energií, což bylo potvrzeno ohybem světla v roce 1919.' },
  'rm-histsci-28': { introduction: 'Pokus, který odhalil atomové jádro.', question: 'Který Rutherfordův pokus odhalil, že atomy mají nepatrné, husté, kladně nabité jádro?', options: ['Pokus se zlatou fólií (rozptyl částic alfa)', 'Pokus s dvojštěrbinou', 'Pokus s olejovou kapkou', 'Fotoelektrický pokus'], explanation: 'Rutherfordův pokus se zlatou fólií z let 1909–11 ukázal, že většina částic alfa prochází skrz, čímž odhalil kompaktní jádro.' },
  'rm-histsci-29': { introduction: 'Model atomu z roku 1913 a rozmístění elektronů.', question: 'Bohrův model atomu z roku 1913 navrhl, že elektrony zaujímají co?', options: ['Diskrétní energetické hladiny (dráhy)', 'Rovnoměrně nabitý oblak', 'Samotné jádro', 'Vakuum bez struktury'], explanation: 'Bohr navrhl, že elektrony obíhají na kvantovaných energetických hladinách a při přeskoku mezi nimi vyzařují nebo pohlcují světlo.' },
  'rm-histsci-30': { introduction: 'Nelze současně znát polohu a co dalšího?', question: 'Heisenbergův princip neurčitosti říká, že nelze současně přesně znát polohu částice a co?', options: ['Hybnost', 'Náboj', 'Pouze směr spinu', 'Hmotnost'], explanation: 'Princip neurčitosti stanovuje zásadní mez pro současnou znalost polohy a hybnosti a je klíčový pro kvantovou mechaniku.' },
  'rm-histsci-31': { introduction: 'Vlnová rovnice popisující vývoj kvantových stavů.', question: 'Který fyzik formuloval vlnovou rovnici popisující, jak se kvantové stavy vyvíjejí v čase?', options: ['Erwin Schrödinger', 'Paul Dirac', 'Wolfgang Pauli', 'Max Born'], explanation: 'Schrödingerova vlnová rovnice z roku 1926 popisuje vývoj vlnové funkce kvantové soustavy.' },
  'rm-histsci-32': { introduction: 'Fotoelektrický jev a povaha světla.', question: 'Einsteinovo vysvětlení fotoelektrického jevu z roku 1905 poskytlo klíčový důkaz, že se světlo chová jako co?', options: ['Částice (fotony)', 'Spojitá kapalina', 'Zvukové vlny', 'Pouze magnetické pole'], explanation: 'Einstein vysvětlil fotoelektrický jev tím, že světlo považoval za kvanta (fotony) – práce, za kterou získal Nobelovu cenu.' },

  // ── Úroveň 5 — Biologie, medicína a výpočetní technika 20. století ──
  'rm-histsci-33': { introduction: 'Struktura DNA odhalená v roce 1953.', question: 'Model Watsona a Cricka z roku 1953 odhalil, že DNA má jakou strukturu?', options: ['Dvojité šroubovice', 'Jedné ploché vrstvy', 'Rozvětveného stromu', 'Uzavřené koule'], explanation: 'Watson a Crick s využitím rentgenových dat navrhli strukturu dvojité šroubovice DNA, čímž vysvětlili, jak se kopíruje genetická informace.' },
  'rm-histsci-34': { introduction: 'Autorka snímků rentgenové difrakce (Fotografie 51).', question: 'Čí snímky rentgenové difrakce (Fotografie 51) byly klíčovým důkazem pro strukturu DNA?', options: ['Rosalind Franklinové', 'Barbary McClintockové', 'Lynn Margulisové', 'Dorothy Hodgkinové'], explanation: 'Fotografie 51 Rosalind Franklinové odhalila šroubovicový tvar a rozměry DNA, klíčové pro model z roku 1953.' },
  'rm-histsci-35': { introduction: 'Plíseň, která něco zabíjela, vedla k objevu penicilinu.', question: 'Objev penicilinu Alexanderem Flemingem v roce 1928 vzešel z pozorování plísně, která zabíjela co?', options: ['Bakterie', 'Viry', 'Houby', 'Rakovinné buňky'], explanation: 'Fleming si všiml, že plíseň rodu Penicillium potlačovala růst bakterií, čímž zahájil éru antibiotik.' },
  'rm-histsci-36': { introduction: 'Postuláty spojující mikroby s nemocemi.', question: 'Který vědec dokázal, že konkrétní mikroorganismy způsobují konkrétní nemoci, což zformuloval jako soubor postulátů?', options: ['Robert Koch', 'Edward Jenner', 'Joseph Lister', 'Paul Ehrlich'], explanation: 'Kochovy postuláty (80. léta 19. století) stanovily přísná kritéria spojující konkrétní mikroby s konkrétními nemocemi.' },
  'rm-histsci-37': { introduction: 'Koncept univerzálního stroje z roku 1936.', question: 'Koncept univerzálního stroje Alana Turinga z roku 1936 položil teoretický základ pro co?', options: ['Moderní počítač', 'Internetový směrovač', 'Tranzistor', 'Kvantové provázání'], explanation: 'Turingův abstraktní stroj definoval vypočitatelnost a tvoří základ teorie počítačů pro všeobecné použití.' },
  'rm-histsci-38': { introduction: 'Vynález z Bellových laboratoří z roku 1947.', question: 'Vynález kterého zařízení v Bellových laboratořích v roce 1947 nahradil objemné elektronky a umožnil moderní elektroniku?', options: ['Tranzistoru', 'Mikroprocesoru', 'Laseru', 'Vakuové diody'], explanation: 'Tranzistor Bardeena, Brattaina a Shockleyho umožnil malé, spolehlivé zesilování a spínání, čímž umožnil mikroelektroniku.' },
  'rm-histsci-39': { introduction: 'Očkování z roku 1796 s využitím kravských neštovic.', question: 'Edward Jenner byl v roce 1796 průkopníkem očkování s využitím kravských neštovic k ochraně proti které nemoci?', options: ['Pravým neštovicím', 'Dětské obrně', 'Choleře', 'Vzteklině'], explanation: 'Jenner ukázal, že nákaza kravskými neštovicemi propůjčuje imunitu vůči pravým neštovicím, čímž založil praxi očkování.' },
  'rm-histsci-40': { introduction: 'Milník dokončený převážně v roce 2003.', question: 'Projekt lidského genomu, převážně dokončený v roce 2003, dosáhl jakého milníku?', options: ['Osekvenování genomu lidské DNA', 'Naklonování prvního savce', 'Vyléčení všech genetických nemocí', 'Sestrojení prvního kvantového počítače'], explanation: 'Projekt lidského genomu zmapoval zhruba tři miliardy párů bází lidské DNA, čímž proměnil biologii a medicínu.' },
};
