import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Internet roadmap question bank (rm-internet-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const internetTranslationsCs: Record<string, QuestionTranslation> = {
  "rm-internet-1": {
    introduction: "Zamysli se, co internet vlastně je, a vyhni se zaměňování s pojmy jako web nebo prohlížeč.",
    question: "Co je internet, řečeno jednou větou?",
    options: ["Jeden obří počítač v cloudu", "Firma, která vlastní všechny weby", "Globální síť sítí, které se propojují a vyměňují si data", "Jiné označení pro webový prohlížeč"],
    explanation: "Internet je celosvětová soustava nezávislých sítí, které se propojují tak, aby každé zařízení mohlo komunikovat s libovolným jiným.",
  },
  "rm-internet-2": {
    introduction: "Rozliš, co je samotná síť a co je jen jedna ze služeb, které po ní běží.",
    question: "Je „internet“ totéž co „web“?",
    options: ["Ano, jsou to synonyma", "Ne, web je jedna ze služeb, které běží na internetu", "Ne, web je starší než internet", "Ano, ale jen na telefonech"],
    explanation: "Internet je síť pod tím vším; web (stránky přes HTTP) je jen jednou z mnoha věcí, které po něm jezdí.",
  },
  "rm-internet-3": {
    introduction: "Vzpomeň si, co všechno na počítači nebo telefonu používá připojení k síti.",
    question: "Co dalšího kromě webových stránek putuje po internetu?",
    options: ["Jen webové stránky", "Jen obrázky", "Nic dalšího", "E-maily, videohovory, hry a data aplikací"],
    explanation: "E-maily, streamování, online hry i provoz aplikací jezdí po internetu, nejen webové stránky v prohlížeči.",
  },
  "rm-internet-4": {
    introduction: "Zaměř se na to, kdo nebo co internet řídí, a jestli má vůbec jeden střed.",
    question: "Má internet jeden centrální počítač, který vše řídí?",
    options: ["Ano, běží na jednom hlavním serveru", "Ne, je decentralizovaný, bez jediného řídicího bodu", "Ano, vlastní ho jedna firma", "Ano, sídlí v jedné zemi"],
    explanation: "Internet je decentralizovaný; skládá se z mnoha nezávisle provozovaných sítí a nemá jednoho správce.",
  },
  "rm-internet-5": {
    introduction: "Přemýšlej, na čem se dvě různá zařízení musí předem domluvit, aby si rozuměla.",
    question: "Co umožňuje dvěma vzdáleným počítačům spolu komunikovat?",
    options: ["Sdílejí stejný pevný disk", "Dodržují společná pravidla zvaná protokoly", "Musí být od stejné značky", "Používají stejné heslo"],
    explanation: "Protokoly jsou dohodnutá pravidla pro formátování a výměnu dat, díky nimž si různé stroje rozumí.",
  },
  "rm-internet-6": {
    introduction: "Rozhodni, jakou roli hraje tvůj počítač, když si o stránku říká.",
    question: "Když načítáš web, tvůj počítač vystupuje hlavně jako:",
    options: ["Klient, který si o data říká", "Server", "Router", "Databáze"],
    explanation: "Zařízení, které o data žádá, je klient; stroj, který data poskytne, je server.",
  },
  "rm-internet-7": {
    introduction: "Zamysli se, jestli se data posílají vcelku, nebo po menších kouscích.",
    question: "Jak se po internetu obvykle posílá většina dat?",
    options: ["Jako jeden obrovský souvislý proud", "Rozdělená na malé kousky zvané pakety", "Jako vytištěné stránky", "Jen jako prostý text"],
    explanation: "Data se rozdělí na malé pakety, které putují samostatně a v cíli se znovu složí dohromady.",
  },
  "rm-internet-8": {
    introduction: "Přemýšlej, jakou výhodu přináší, když síť nemá jediný centrální bod.",
    question: "Proč byl internet navržen jako decentralizovaný?",
    options: ["Aby byl pomalejší", "Aby šetřil elektřinu", "Aby fungoval dál, i když některé části vypadnou", "Aby bylo potřeba méně kabelů"],
    explanation: "Bez jediného centrálního bodu může provoz objíždět výpadky, takže je síť odolnější.",
  },
  "rm-internet-9": {
    introduction: "Zaměř se na to, k čemu IP adresa slouží, ne na to, jak vypadá.",
    question: "K čemu slouží IP adresa?",
    options: ["K jednoznačné identifikaci zařízení v síti", "K pojmenování webu slovy", "K šifrování hesel", "K ukládání historie prohlížeče"],
    explanation: "IP adresa je číselný štítek, který identifikuje zařízení, aby mu šlo doručit data.",
  },
  "rm-internet-10": {
    introduction: "Vyber zápis, který vypadá jako čtyři čísla oddělená tečkami.",
    question: "Co z toho vypadá jako adresa IPv4?",
    options: ["example.com", "https://", "192.168.1.10", "user@mail.com"],
    explanation: "Adresy IPv4 jsou čtyři čísla (0 až 255) oddělená tečkami, například 192.168.1.10.",
  },
  "rm-internet-11": {
    introduction: "Zamysli se, čeho začalo být u staršího IPv4 nedostatek.",
    question: "Proč vzniklo IPv6?",
    options: ["Aby byly adresy kratší", "Protože ve světě docházely adresy IPv4", "Aby nahradilo DNS", "Aby blokovalo hackery"],
    explanation: "IPv4 má jen asi 4 miliardy adres, což nestačí, a tak IPv6 nabízí mnohonásobně větší zásobu.",
  },
  "rm-internet-12": {
    introduction: "Rozliš adresy dosažitelné z celého internetu od těch, které platí jen doma.",
    question: "Jaký je rozdíl mezi veřejnou a privátní IP adresou?",
    options: ["Veřejné jsou šifrované", "Veřejné IP jsou dosažitelné z internetu; privátní se používají v lokálních sítích", "Privátní IP jsou rychlejší", "Žádný rozdíl není"],
    explanation: "Privátní IP (například 192.168.x.x) fungují jen v lokální síti; veřejné IP jsou směrovatelné na otevřeném internetu.",
  },
  "rm-internet-13": {
    introduction: "Vzpomeň si, kdo doma rozdává adresy zařízením a co sdílíš se zbytkem internetu.",
    question: "Jakou IP adresu obvykle má zařízení na domácí Wi-Fi?",
    options: ["Veřejnou IP, celosvětově unikátní", "Privátní IP přidělenou routerem", "Žádnou IP adresu", "Stejnou IP jako navštívený web"],
    explanation: "Router rozdává zařízením privátní IP a navenek s internetem sdílí jednu veřejnou IP.",
  },
  "rm-internet-14": {
    introduction: "Zamysli se, na jaké zařízení ukazuje adresa 127.0.0.1.",
    question: "Na co odkazuje smyčková adresa 127.0.0.1 (localhost)?",
    options: ["Na tvého poskytovatele internetu", "Na samotné zařízení", "Na výchozí vyhledávač", "Na nejbližší server"],
    explanation: "127.0.0.1, známá jako localhost, vždy ukazuje zpět na stroj, který právě používáš.",
  },
  "rm-internet-15": {
    introduction: "Odhadni řádově počet adres, které dává 32bitové IPv4.",
    question: "Kolik adres přibližně poskytuje IPv4?",
    options: ["Asi 256", "Asi 4,3 miliardy", "Neomezeně", "Přesně jeden milion"],
    explanation: "IPv4 používá 32bitové adresy, což dává zhruba 4,3 miliardy možných hodnot, a to už dnes nestačí.",
  },
  "rm-internet-16": {
    introduction: "Přemýšlej, jak zařízení dostane adresu, aniž bys ji zadával ručně.",
    question: "Jak zařízení v běžné síti obvykle získá svou IP adresu?",
    options: ["Uživatel ji zadá zpaměti", "Je vytištěná na zařízení", "Z výroby se nikdy nemění", "Automaticky přes DHCP"],
    explanation: "DHCP (Dynamic Host Configuration Protocol) automaticky přiděluje IP adresy zařízením, která se připojí do sítě.",
  },
  "rm-internet-17": {
    introduction: "Zamysli se, co převádí jméno webu na číslo, kterému rozumí počítače.",
    question: "Jaký problém řeší DNS?",
    options: ["Překládá jména srozumitelná lidem na IP adresy", "Zrychluje stahování", "Šifruje tvůj provoz", "Blokuje reklamy"],
    explanation: "DNS mapuje jména jako example.com na číselné IP adresy, které počítače skutečně používají k připojení.",
  },
  "rm-internet-18": {
    introduction: "Vzpomeň si, co převádí jména na čísla i v běžném životě.",
    question: "K jaké každodenní pomůcce se DNS často přirovnává?",
    options: ["Ke kalkulačce", "K telefonnímu seznamu", "K fotoaparátu", "K hodinám"],
    explanation: "Jako telefonní seznam mapuje jména na čísla, DNS mapuje doménová jména na IP adresy.",
  },
  "rm-internet-19": {
    introduction: "Přemýšlej, kdy prohlížeč potřebuje znát IP serveru, než se vůbec připojí.",
    question: "Kdy při návštěvě webu proběhne dotaz na DNS?",
    options: ["Až po úplném načtení stránky", "Před připojením, aby zjistil IP adresu serveru", "Jen když je web offline", "Nikdy, prohlížeč ji už zná"],
    explanation: "Prohlížeč musí přeložit doménové jméno na IP, než může otevřít spojení se serverem.",
  },
  "rm-internet-20": {
    introduction: "Zamysli se, proč se vyplatí pamatovat si nedávno zjištěné adresy.",
    question: "Proč si počítače ukládají výsledky DNS do cache?",
    options: ["Aby naschvál spotřebovaly víc paměti", "Aby web skryly", "Aby neopakovaly stejný dotaz a odpověděly rychleji", "Aby změnily IP adresu"],
    explanation: "Cache uchovává nedávné dotazy, takže opakovaná návštěva přeskočí celý proces překladu a načte se rychleji.",
  },
  "rm-internet-21": {
    introduction: "Najdi v názvu domény tu úplně pravou část.",
    question: "Která část názvu „shop.example.com“ je doména nejvyššího řádu (TLD)?",
    options: ["shop", "example", "com", "www"],
    explanation: "TLD je nejpravější část, například com, org nebo net; example je doména a shop je subdoména.",
  },
  "rm-internet-22": {
    introduction: "Přemýšlej, co znamená předpona před hlavní doménou.",
    question: "Co je „subdoména“?",
    options: ["Záložní web", "Předpona, která vytváří oddíl pod doménou, například blog.example.com", "Druh IP adresy", "Nastavení prohlížeče"],
    explanation: "Subdoména jako blog.example.com je pojmenovaný oddíl uvnitř hlavní domény example.com.",
  },
  "rm-internet-23": {
    introduction: "Zamysli se, jestli DNS drží vše v jednom seznamu, nebo je rozdělené.",
    question: "Jak je systém DNS zhruba uspořádaný?",
    options: ["Jako jeden obří plochý seznam", "Jako distribuovaná hierarchie jmenných serverů", "Jako jeden soubor na tvém počítači", "Jako tištěná kniha aktualizovaná jednou ročně"],
    explanation: "DNS je distribuovaný, hierarchický systém: kořenové servery, servery TLD a autoritativní servery, každý spravuje část jména.",
  },
  "rm-internet-24": {
    introduction: "Vzpomeň si, který záznam přiřazuje doméně její IPv4 adresu.",
    question: "Co dělá v DNS „A záznam“?",
    options: ["Ukládá heslo", "Mapuje doménové jméno na IPv4 adresu", "Vyjmenovává pravidla pro e-maily", "Blokuje doménu"],
    explanation: "A záznam ukazuje hostname na jeho IPv4 adresu (záznam AAAA dělá totéž pro IPv6).",
  },
  "rm-internet-25": {
    introduction: "Zamysli se, jak velký kus dat paket je a co k němu patří navíc.",
    question: "Co je paket?",
    options: ["Celý soubor poslaný najednou", "Druh kabelu", "Malý kousek dat s adresními informacemi", "Webový prohlížeč"],
    explanation: "Paket je malá jednotka dat zabalená se zdrojovou a cílovou informací, aby se dala směrovat.",
  },
  "rm-internet-26": {
    introduction: "Přemýšlej, jaké výhody přináší posílat data po menších kouscích.",
    question: "Proč se velká data dělí na mnoho paketů?",
    options: ["Aby se hůř četla", "Aby kousky mohly putovat pružně a daly se znovu poslat, když se ztratí", "Aby se spotřebovala větší přenosová kapacita", "Protože kabely jsou krátké"],
    explanation: "Rozdělení dat umožní paketům jít různými cestami, zotavit se ze ztráty po jednom a férově sdílet síť.",
  },
  "rm-internet-27": {
    introduction: "Zaměř se na hlavní úkol routeru v cestě paketu.",
    question: "Jaký je hlavní úkol routeru?",
    options: ["Přeposílat pakety k jejich cíli", "Ukládat weby", "Šifrovat veškerý provoz", "Přidělovat doménová jména"],
    explanation: "Router přečte cíl každého paketu a přepošle ho nejlepší dostupnou cestou k tomuto cíli.",
  },
  "rm-internet-28": {
    introduction: "Zamysli se, jestli musí všechny pakety jedné zprávy jít stejnou trasou.",
    question: "Musí všechny pakety jedné zprávy jít stejnou cestou?",
    options: ["Ano, vždy stejnou cestou", "Ne, mohou jít různými trasami a přesto dorazit", "Ano, jinak se ztratí", "Jen pokud jsou šifrované"],
    explanation: "Pakety se směrují samostatně a mohou jít různými cestami; v cíli se opět složí ve správném pořadí.",
  },
  "rm-internet-29": {
    introduction: "Přemýšlej, jaké informace paket potřebuje, aby ho šlo doručit.",
    question: "Co každý paket nese, aby se dostal na správné místo?",
    options: ["Fotku odesílatele", "Zdrojovou a cílovou adresu", "Heslo uživatele", "Kopii webu"],
    explanation: "Hlavičky paketů obsahují zdrojovou a cílovou IP adresu, aby routery věděly, kam je poslat.",
  },
  "rm-internet-30": {
    introduction: "Zamysli se, jestli ztracený paket znamená konec, nebo se dá řešit.",
    question: "Co se stane, když se paket cestou ztratí?",
    options: ["Celý internet se zastaví", "Podle protokolu jej lze rozpoznat a poslat znovu", "Je navždy pryč bez možnosti obnovy", "Promění se ve virus"],
    explanation: "Spolehlivé protokoly jako TCP poznají chybějící pakety a vyžádají si jejich opětovné poslání.",
  },
  "rm-internet-31": {
    introduction: "Vzpomeň si, co přesně ti příkaz ping ukazuje o spojení.",
    question: "Co zhruba měří příkaz „ping“?",
    options: ["Místo na disku", "Sílu hesla", "Jas obrazovky", "Dobu cesty paketu k hostiteli a zpět"],
    explanation: "Ping pošle malý paket a změří, jak dlouho trvá cesta tam a zpět, což ukazuje latenci k hostiteli.",
  },
  "rm-internet-32": {
    introduction: "Rozliš zpoždění od množství dat, které proteče.",
    question: "Co je v síti „latence“?",
    options: ["Množství dat za sekundu", "Zpoždění, než data začnou přicházet", "Počet zařízení online", "Velikost souboru"],
    explanation: "Latence je doba, než data dorazí ze zdroje do cíle; přenosová kapacita říká, kolik dat může protéct.",
  },
  "rm-internet-33": {
    introduction: "Zaměř se na to, co TCP zaručuje ohledně doručení dat.",
    question: "Co má TCP hlavně zajišťovat?",
    options: ["Spolehlivé doručení dat ve správném pořadí", "Co nejvyšší rychlost bez kontrol", "Šifrování veškerého provozu", "Překlad doménových jmen"],
    explanation: "TCP zajišťuje, že data dorazí celá a ve správném pořadí, a znovu pošle vše, co se cestou ztratilo.",
  },
  "rm-internet-34": {
    introduction: "Přemýšlej, co UDP obětuje výměnou za rychlost.",
    question: "Čím se UDP liší od TCP?",
    options: ["UDP je pomalejší a spolehlivější", "UDP je rychlejší, ale nezaručuje doručení ani pořadí", "UDP šifruje data, TCP ne", "Jsou úplně stejné"],
    explanation: "UDP vynechává záruky doručení a pořadí, aby bylo rychlejší a mělo nižší režii, a počítá s nějakou ztrátou.",
  },
  "rm-internet-35": {
    introduction: "Zamysli se, jestli u živého přenosu víc vadí čekání, nebo občasný výpadek.",
    question: "Který protokol se obvykle lépe hodí pro živé videohovory nebo online hry?",
    options: ["TCP, protože nejvíc záleží na pořadí", "UDP, protože rychlost je důležitější než dokonalé doručení", "Ani jeden pro video nefunguje", "DNS"],
    explanation: "Aplikace v reálném čase volí UDP, protože mírně zahozený snímek je lepší než čekat na opětovné poslání starých dat.",
  },
  "rm-internet-36": {
    introduction: "Přemýšlej, jestli u stahování smí nějaký byte chybět.",
    question: "Jaký protokol bys čekal u stahování souboru?",
    options: ["UDP, aby směly bajty chybět", "TCP, aby každý bajt dorazil správně", "Ani jeden", "Jen DNS"],
    explanation: "Stahování potřebuje každý bajt celý a ve správném pořadí, což přesně zaručuje TCP.",
  },
  "rm-internet-37": {
    introduction: "Vzpomeň si na tři kroky, kterými TCP otevírá spojení.",
    question: "Co je „třícestný handshake“ u TCP?",
    options: ["Způsob šifrování dat", "Výměna SYN, SYN-ACK, ACK, která navazuje spojení", "Metoda komprese souborů", "Krok dotazu na DNS"],
    explanation: "TCP otevírá spojení třícestným handshakem (SYN, SYN-ACK, ACK), než začnou téct data.",
  },
  "rm-internet-38": {
    introduction: "Zamysli se, jak příjemce pozná, v jakém pořadí pakety poskládat.",
    question: "Jak TCP udržuje data ve správném pořadí?",
    options: ["Posílá vždy jen jeden paket", "Spoléhá, že je seřadí uživatel", "Čísluje pakety, aby je příjemce mohl složit", "Pořadí udržet neumí"],
    explanation: "TCP přiděluje pořadová čísla, takže příjemce může pakety seřadit a poznat, jestli některý chybí.",
  },
  "rm-internet-39": {
    introduction: "Přemýšlej, co TCP dělá navíc oproti UDP a co tím vzniká.",
    question: "Proč může mít UDP nižší režii než TCP?",
    options: ["Používá větší pakety", "Nesleduje potvrzení a neposílá znovu ztracená data", "Vždy šifruje", "Potřebuje víc handshaků"],
    explanation: "UDP je nespojované a vynechává potvrzování i opětovné posílání, čímž snižuje režii a zpoždění.",
  },
  "rm-internet-40": {
    introduction: "Zamysli se, na které vrstvě modelu TCP a UDP pracují.",
    question: "Jakého druhu protokolu jsou TCP a UDP příkladem?",
    options: ["Protokoly aplikační vrstvy", "Fyzické kabely", "Šifrovací standardy", "Protokoly transportní vrstvy"],
    explanation: "TCP a UDP pracují na transportní vrstvě a přenášejí data mezi aplikacemi na různých zařízeních.",
  },
  "rm-internet-41": {
    introduction: "Přemýšlej, jakou výhodu přináší rozdělit složitý systém do vrstev.",
    question: "Proč je internet uspořádaný do vrstev?",
    options: ["Aby každá vrstva řešila jeden úkol a stavěla na té pod sebou", "Aby byl matoucí", "Aby zpomalil data", "Kvůli zákonným pravidlům"],
    explanation: "Vrstvení odděluje úkoly, takže každá vrstva (linka, IP, transport, aplikace) může fungovat samostatně.",
  },
  "rm-internet-42": {
    introduction: "Zamysli se, která vrstva řeší adresy a vede pakety mezi sítěmi.",
    question: "Která vrstva má na starosti adresování a směrování paketů mezi sítěmi?",
    options: ["Aplikační vrstva", "Internetová (IP) vrstva", "Fyzická vrstva", "Prezentační vrstva"],
    explanation: "Internetová vrstva pomocí IP řeší logické adresování a směrování paketů napříč sítěmi.",
  },
  "rm-internet-43": {
    introduction: "Vzpomeň si, kam v modelu patří TCP a UDP.",
    question: "Na které vrstvě pracují TCP a UDP?",
    options: ["Linková vrstva", "Transportní vrstva", "Aplikační vrstva", "Internetová vrstva"],
    explanation: "TCP a UDP jsou protokoly transportní vrstvy, které přenášejí data mezi aplikacemi na zařízeních.",
  },
  "rm-internet-44": {
    introduction: "Přemýšlej, kde sídlí HTTP a o co se opírá zespodu.",
    question: "Kam v modelu TCP/IP patří HTTP?",
    options: ["Do aplikační vrstvy", "Do transportní vrstvy", "Do linkové vrstvy", "Do internetové vrstvy"],
    explanation: "HTTP je protokol aplikační vrstvy, který se při přenosu samotných bajtů opírá o TCP pod sebou.",
  },
  "rm-internet-45": {
    introduction: "Zamysli se, co dělá každá vrstva s daty, než je předá níž.",
    question: "Co znamená „zapouzdření“ v sítích?",
    options: ["Mazání starých dat", "Šifrování hesel", "Každá vrstva před předáním níž obalí data vlastní hlavičkou", "Přejmenování domény"],
    explanation: "Jak data putují dolů zásobníkem, každá vrstva přidá hlavičku a obalí jí data z vrstvy nad sebou.",
  },
  "rm-internet-46": {
    introduction: "Přemýšlej, co má na starosti vrstva nejblíž fyzickému přenosu.",
    question: "Co zhruba řeší linková vrstva?",
    options: ["Výběr webu k načtení", "Přenos dat po místním fyzickém spoji, jako je Ethernet nebo Wi-Fi", "Překlad doménových jmen", "Šifrování HTTPS"],
    explanation: "Linková vrstva má na starosti přenos dat po bezprostředním fyzickém médiu mezi přímo propojenými zařízeními.",
  },
  "rm-internet-47": {
    introduction: "Zamysli se, proč horním vrstvám nezáleží na tom, co je pod nimi.",
    question: "Proč web funguje stejně přes Wi-Fi, optiku i mobilní data?",
    options: ["Protože všechny kabely jsou stejné", "Protože horní vrstvy neřeší, jaké fyzické médium je pod nimi", "Protože Wi-Fi přesně kopíruje optiku", "Ve skutečnosti funguje jen přes optiku"],
    explanation: "Vrstvení skrývá fyzické detaily, takže stejné IP a HTTP fungují bez ohledu na použité připojení.",
  },
  "rm-internet-48": {
    introduction: "Přemýšlej, kterým směrem data procházejí vrstvami při odesílání.",
    question: "V jakém pořadí data při odesílání obvykle procházejí vrstvami?",
    options: ["Od fyzické k aplikační", "Od aplikační dolů k fyzické a u příjemce zase nahoru", "Jen transportní", "Vrstvy se přeskakují"],
    explanation: "Odchozí data jdou od aplikační vrstvy dolů k fyzické a u příjemce putují zásobníkem zase nahoru.",
  },
  "rm-internet-49": {
    introduction: "Zaměř se na to, k čemu HTTP v prohlížeči slouží.",
    question: "Co je HTTP?",
    options: ["Protokol, kterým prohlížeče žádají a přijímají webové stránky", "Druh kabelu", "Programovací jazyk", "Vyhledávač"],
    explanation: "HTTP je protokol aplikační vrstvy, který určuje, jak klienti žádají o zdroje a jak servery odpovídají.",
  },
  "rm-internet-50": {
    introduction: "Rozliš, kdo se ptá a kdo odpovídá při načítání stránky.",
    question: "Kdo je při webovém požadavku klient a kdo server?",
    options: ["Server se ptá, prohlížeč odpovídá", "Prohlížeč se ptá, webový server odpovídá", "Oba jsou servery", "Ani jeden roli nemá"],
    explanation: "Prohlížeč je klient, který posílá požadavky; webový server odpovídá požadovaným obsahem.",
  },
  "rm-internet-51": {
    introduction: "Zamysli se, co dělá nejběžnější HTTP metoda pro načtení obsahu.",
    question: "Co dělá HTTP požadavek GET?",
    options: ["Maže stránku", "Restartuje server", "Žádá server, aby poslal zdroj", "Šifruje web"],
    explanation: "Požadavky GET získávají ze serveru zdroj, například HTML stránku nebo obrázek.",
  },
  "rm-internet-52": {
    introduction: "Vzpomeň si, co znamená nejznámější chybový kód při načítání webu.",
    question: "Co znamená stavový kód HTTP 404?",
    options: ["Úspěch", "Požadovaný zdroj nebyl nalezen", "Server tě přesměrovává", "Přístup zakázán"],
    explanation: "404 znamená, že server nenašel požadovaný zdroj na dané URL.",
  },
  "rm-internet-53": {
    introduction: "Přemýšlej, co k HTTP přidává písmeno „S“ a jak chrání provoz.",
    question: "Co přidává „S“ v HTTPS oproti HTTP?",
    options: ["Rychlost", "Zabezpečení šifrováním TLS", "Úložiště", "Streamování"],
    explanation: "HTTPS přidává k HTTP šifrování TLS, takže je provoz chráněný před odposlechem a úpravami.",
  },
  "rm-internet-54": {
    introduction: "Zamysli se, jestli si HTTP samo pamatuje předchozí požadavky.",
    question: "Proč se prosté HTTP označuje jako „bezstavové“?",
    options: ["Neumí posílat data", "Každý požadavek je samostatný a server si ve výchozím stavu předchozí nepamatuje", "Funguje jen jednou", "Vše uchovává navždy"],
    explanation: "Samotné HTTP si mezi požadavky nic nepamatuje; stav se doplňuje přes cookies nebo tokeny.",
  },
  "rm-internet-55": {
    introduction: "Rozeber, z jakých částí se skládá adresa webu.",
    question: "Co obsahuje URL jako https://example.com/page?",
    options: ["Jen IP adresu", "Schéma, hostitele (doménu) a cestu ke zdroji", "Heslo", "Jen náhodný text"],
    explanation: "URL spojuje schéma (https), hostitele (example.com) a cestu (/page), aby určilo umístění zdroje.",
  },
  "rm-internet-56": {
    introduction: "Zamysli se, jaké doplňkové informace nesou hlavičky kromě samotného obsahu.",
    question: "Jakou roli hrají HTTP hlavičky v požadavku nebo odpovědi?",
    options: ["Jsou samotným obsahem stránky", "Ukládají databázi", "Nahrazují URL", "Nesou metadata jako typ obsahu, délku a informace o cachování"],
    explanation: "Hlavičky nesou metadata o zprávě, například typ obsahu, délku, cookies a pokyny pro cachování.",
  },
  "rm-internet-57": {
    introduction: "Zaměř se na to, k čemu na zařízení slouží číslo portu.",
    question: "K čemu slouží síťový port?",
    options: ["K určení, které aplikaci nebo službě provoz patří", "K připojení monitoru", "K ukládání souborů", "K šifrování dat"],
    explanation: "Číslo portu říká zařízení, která aplikace nebo služba má daný provoz dostat.",
  },
  "rm-internet-58": {
    introduction: "Vzpomeň si na výchozí číslo portu pro zabezpečený web.",
    question: "Který port používá HTTPS ve výchozím stavu?",
    options: ["21", "80", "443", "25"],
    explanation: "HTTPS ve výchozím stavu používá port 443, zatímco prosté HTTP používá port 80.",
  },
  "rm-internet-59": {
    introduction: "Zamysli se, jak může víc zařízení vystupovat navenek pod jednou adresou.",
    question: "Co dělá NAT (Network Address Translation)?",
    options: ["Šifruje všechny pakety", "Zrychluje DNS", "Umožňuje mnoha privátním zařízením sdílet jednu veřejnou IP adresu", "Blokuje všechny weby"],
    explanation: "NAT mapuje mnoho interních privátních IP na jednu veřejnou IP a sdílí tak jednu adresu napříč sítí.",
  },
  "rm-internet-60": {
    introduction: "Přemýšlej, kolik veřejných adres díky NAT domácnost reálně potřebuje.",
    question: "Kolik veřejných IP adres obvykle domácnost díky NAT potřebuje?",
    options: ["Jednu na každé zařízení", "Často jen jednu pro celou domácnost", "Žádnou", "Přesně deset"],
    explanation: "NAT umožní všem domácím zařízením sdílet jednu veřejnou IP od poskytovatele, čímž šetří adresy.",
  },
  "rm-internet-61": {
    introduction: "Zaměř se na to, co firewall s provozem dělá.",
    question: "Jaký je hlavní účel firewallu?",
    options: ["Zrychlit připojení", "Přidělovat IP adresy", "Ukládat hesla", "Filtrovat provoz a blokovat nežádoucí nebo nebezpečná spojení"],
    explanation: "Firewall vynucuje pravidla o tom, jaký provoz smí dovnitř nebo ven, a blokuje nežádoucí spojení.",
  },
  "rm-internet-62": {
    introduction: "Zamysli se, co server kombinuje, aby trefil správný program na tvém zařízení.",
    question: "Jak server pozná, kterému programu na tvém zařízení má poslat web zpět?",
    options: ["Hádá náhodně", "Použije kombinaci tvé IP adresy a čísla portu", "Použije tvé uživatelské jméno", "Použije velikost obrazovky"],
    explanation: "IP adresa spolu s číslem portu určuje přesně to spojení aplikace, které má odpověď dostat.",
  },
  "rm-internet-63": {
    introduction: "Přemýšlej, proč jsou nízká čísla portů vyhrazená pro běžné služby.",
    question: "Proč se porty 0 až 1023 nazývají „dobře známé“ porty?",
    options: ["Jsou vždy blokované", "Jsou vyhrazené pro běžné standardní služby jako HTTP a SSH", "Jsou nejrychlejší", "Jsou jen pro hry"],
    explanation: "Dobře známé porty jsou podle konvence vyhrazené pro standardní služby, například 80 pro HTTP a 22 pro SSH.",
  },
  "rm-internet-64": {
    introduction: "Zamysli se, jak nasměrovat příchozí provoz na konkrétní zařízení v síti.",
    question: "Co dělá „přesměrování portů“ na routeru?",
    options: ["Zavírá všechny porty", "Směruje příchozí provoz na daném portu na konkrétní interní zařízení", "Mění tvou veřejnou IP", "Šifruje síť"],
    explanation: "Přesměrování portů vede provoz přicházející na zvolený port na určité zařízení za routerem.",
  },
  "rm-internet-65": {
    introduction: "Zaměř se na to, kdo ti zprostředkuje přístup k internetu.",
    question: "Co je ISP?",
    options: ["Firma, která ti poskytuje přístup k internetu", "Webový prohlížeč", "Druh webu", "Bezpečnostní protokol"],
    explanation: "Poskytovatel internetu (ISP) připojuje tvou domácnost nebo zařízení ke zbytku internetu.",
  },
  "rm-internet-66": {
    introduction: "Přemýšlej, kudy fyzicky vede většina provozu mezi kontinenty.",
    question: "Jak většina mezinárodního internetového provozu fyzicky putuje mezi kontinenty?",
    options: ["Jen přes satelit", "Vzduchem jako rádiové vlny", "Podmořskými optickými kabely", "Jen po měděných telefonních linkách"],
    explanation: "Naprostá většina mezikontinentálních dat teče podmořskými optickými kabely na dně oceánů.",
  },
  "rm-internet-67": {
    introduction: "Zamysli se, jaké médium přenese data nejrychleji na velké vzdálenosti.",
    question: "Co přenáší data nejrychleji na velké vzdálenosti?",
    options: ["Měděný drát", "Optický kabel přenášející světlo", "Wi-Fi", "Bluetooth"],
    explanation: "Optické kabely přenášejí data jako pulzy světla a nabízejí velmi vysokou rychlost a kapacitu na dlouhé vzdálenosti.",
  },
  "rm-internet-68": {
    introduction: "Rozliš kapacitu spoje od zpoždění.",
    question: "Co je „přenosová kapacita“ (bandwidth)?",
    options: ["Zpoždění, než data dorazí", "Maximum dat, které může protéct za sekundu", "Počet kabelů", "Stáří sítě"],
    explanation: "Přenosová kapacita je kapacita spoje, tedy kolik dat unese za sekundu, na rozdíl od latence.",
  },
  "rm-internet-69": {
    introduction: "Zamysli se, kde se setkávají různé sítě, aby si předaly provoz.",
    question: "Jaká je role peeringového uzlu (IXP, Internet Exchange Point)?",
    options: ["Hostuje všechny weby", "Je to místo, kde se různé sítě propojují a vyměňují si provoz", "Přiděluje doménová jména", "Šifruje internet"],
    explanation: "IXP jsou fyzická místa, kde se ISP a sítě propojují, aby si efektivně vyměňovaly provoz.",
  },
  "rm-internet-70": {
    introduction: "Přemýšlej, kolik mezikroků provoz cestou ke vzdálenému webu projde.",
    question: "Když posíláš data na vzdálený web, tvůj provoz obvykle:",
    options: ["Jde přímo bez zastávek", "Projde cestou mnoha routery a sítěmi", "Putuje jen přes tvého poskytovatele", "Přeskočí veškerý hardware"],
    explanation: "Data typicky proskáčou přes několik routerů a sítí poskytovatelů, než dorazí ke vzdálenému cíli.",
  },
  "rm-internet-71": {
    introduction: "Zamysli se, jakou vzdálenost musí signál u satelitu urazit navíc.",
    question: "Proč může mít satelitní internet vyšší latenci než optika?",
    options: ["Satelity jsou pomalejší počítače", "Signál musí urazit dlouhou cestu na oběžnou dráhu a zpět", "Optika používá rádiové vlny", "Satelity nemají antény"],
    explanation: "Vyslání signálu k satelitu a zpět přidá vzdálenost, čímž se prodlouží doba cesty tam a zpět.",
  },
  "rm-internet-72": {
    introduction: "Přemýšlej, na jaký poslední úsek spoje se pojem „last mile“ vztahuje.",
    question: "Co znamená „poslední míle“ (last mile) u internetového připojení?",
    options: ["Poslední web, který navštívíš", "Nejpomalejší server", "Konec životnosti kabelu", "Poslední spoj propojující síť poskytovatele s tvým domem nebo budovou"],
    explanation: "Poslední míle je závěrečný úsek infrastruktury, který propojuje širší síť s koncovým uživatelem.",
  },
  "rm-internet-73": {
    introduction: "Zamysli se, co šifrování s daty udělá a kdo je pak přečte.",
    question: "Co šifrování dělá s tvými daty?",
    options: ["Zamíchá je tak, aby je přečetla jen určená strana", "Smaže je", "Načte je rychleji", "Přeloží je do jiného jazyka"],
    explanation: "Šifrování převede data do nečitelné podoby, kterou dokáže rozluštit jen ten, kdo má klíč.",
  },
  "rm-internet-74": {
    introduction: "Přemýšlej, před čím tě HTTPS chrání při přenosu dat.",
    question: "Před čím chrání HTTPS?",
    options: ["Před pomalými weby", "Před odposlechem a úpravou dat během přenosu", "Před vyčerpáním úložiště", "Před překlepy"],
    explanation: "HTTPS šifruje provoz, takže útočníci mezi tebou a serverem ho nemohou číst ani měnit.",
  },
  "rm-internet-75": {
    introduction: "Vzpomeň si, který protokol stojí za šifrováním v HTTPS.",
    question: "Který protokol poskytuje šifrování, jež HTTPS používá?",
    options: ["DNS", "FTP", "TLS (dříve SSL)", "DHCP"],
    explanation: "HTTPS se při šifrování a zabezpečení spojení opírá o TLS (nástupce SSL).",
  },
  "rm-internet-76": {
    introduction: "Zamysli se, co certifikát o serveru dokazuje a co umožňuje.",
    question: "Jaký je hlavní účel TLS certifikátu webu?",
    options: ["Udělat stránku barevnou", "Prokázat identitu serveru a umožnit šifrování", "Ukládat hesla uživatelů", "Zrychlit načítání"],
    explanation: "Certifikát ověřuje, že server je skutečně tím, za koho se vydává, a umožňuje bezpečné šifrované spojení.",
  },
  "rm-internet-77": {
    introduction: "Přemýšlej, jak spolupracuje dvojice veřejného a soukromého klíče.",
    question: "Jak se používají klíče v kryptografii s veřejným klíčem?",
    options: ["Jeden tajný klíč sdílený všemi", "Veřejný klíč šifruje a odpovídající soukromý klíč dešifruje", "Žádné klíče nejsou potřeba", "Stejný klíč je zveřejněný"],
    explanation: "Veřejný klíč (volně sdílený) a soukromý klíč (držený v tajnosti) tvoří pár; co jeden zamkne, druhý odemkne.",
  },
  "rm-internet-78": {
    introduction: "Zamysli se, kdo se vmísí mezi dvě komunikující strany.",
    question: "Co je útok typu „man-in-the-middle“?",
    options: ["Pomalý server", "Útočník tajně odposlouchávající provoz mezi dvěma stranami", "Druh firewallu", "Zálohovací systém"],
    explanation: "Při útoku man-in-the-middle se někdo vmísí mezi tebe a server, aby četl nebo měnil provoz.",
  },
  "rm-internet-79": {
    introduction: "Přemýšlej, co VPN dělá s tvým provozem a kudy ho vede.",
    question: "Proč se někdy používá VPN?",
    options: ["K mazání cookies", "Ke zvýšení limitů přenosové kapacity", "K nahrazení prohlížeče", "K šifrování provozu a jeho vedení přes jiný server"],
    explanation: "VPN šifruje tvé spojení a tuneluje ho přes vzdálený server, čímž skryje provoz před místními pozorovateli.",
  },
  "rm-internet-80": {
    introduction: "Zamysli se, co ikona zámku přesně potvrzuje a co naopak nezaručuje.",
    question: "Co hlavně znamená ikona zámku v adresním řádku prohlížeče?",
    options: ["Web vlastní Google", "Spojení je šifrované přes HTTPS", "Web nemá reklamy", "Stránka se načetla rychle"],
    explanation: "Zámek ukazuje, že spojení používá šifrování HTTPS; sám o sobě ale nezaručuje, že je web důvěryhodný.",
  },
};
