// GTO & Advanced Theory roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const gtoAdvancedSeeds: Seed[] = [
  // ── Level 1 — GTO vs exploitative play ──
  { q: 'In poker, what does "GTO" stand for?', opts: ['Game Theory Optimal', 'Guaranteed Table Odds', 'General Turn Order', 'Grand Tournament Objective'], a: 0, e: 'GTO means Game Theory Optimal: a strategy derived from game theory that cannot be exploited.', tags: ['Poker', 'GTO'] },
  { q: 'A GTO strategy is best described as one that...', opts: ['Cannot be exploited by any opponent', 'Maximally punishes weak players', 'Always folds to aggression', 'Guarantees winning every hand'], a: 0, e: 'A GTO strategy is unexploitable: no matter how the opponent plays, they cannot gain against it.', tags: ['Poker', 'GTO'] },
  { q: 'Exploitative play means...', opts: ['Deviating to target an opponent\'s specific mistakes', 'Playing identically against everyone', 'Only bluffing on the river', 'Never straying from a preset chart'], a: 0, e: 'Exploitative play adjusts your strategy to attack the particular leaks a given opponent shows.', tags: ['Poker', 'Exploitative'] },
  { q: 'Against a weak player who folds far too often, the most profitable approach is usually to...', opts: ['Deviate exploitatively and bluff more', 'Play strict GTO', 'Fold every hand', 'Check everything down'], a: 0, e: 'Strict GTO leaves money on the table; against an over-folder you profit most by bluffing more.', tags: ['Poker', 'Exploitative'] },
  { q: 'A key drawback of playing pure GTO is that it...', opts: ['Does not maximally exploit weak opponents', 'Is always a losing strategy', 'Requires no study at all', 'Is against the rules'], a: 0, e: 'GTO is unexploitable but not maximally exploitative, so it wins less than a good read-based line versus weak players.', tags: ['Poker', 'GTO'] },
  { q: 'A key risk of playing exploitatively is that...', opts: ['You open yourself to being counter-exploited', 'It can never be profitable', 'It ignores opponents entirely', 'It requires a solver at the table'], a: 0, e: 'Deviating from balance to exploit others makes your own strategy imbalanced and vulnerable to counter-adjustment.', tags: ['Poker', 'Exploitative'] },
  { q: 'GTO play is most valuable against which type of opponent?', opts: ['Strong, observant regulars', 'Complete beginners only', 'Players who have already folded', 'Empty seats'], a: 0, e: 'Balanced GTO play shines against tough observant players who would punish any exploitable imbalance.', tags: ['Poker', 'GTO'] },
  { q: 'At a Nash equilibrium, a player who unilaterally deviates from the GTO strategy will...', opts: ['Not increase their expected value', 'Always win a bigger pot', 'Always lose their whole stack', 'Force an automatic fold'], a: 0, e: 'By definition of equilibrium, no player can improve their expectation by changing strategy on their own.', tags: ['Poker', 'GTO'] },

  // ── Level 2 — Balanced ranges, MDF & bluff-to-value ratios ──
  { q: 'Minimum Defense Frequency (MDF) is...', opts: ['The minimum share of your range you must continue with to stop profitable bluffs', 'The largest bet you may make', 'The minimum stack you can sit with', 'The number of bluffs per value bet'], a: 0, e: 'MDF is the fraction of your range you must defend so an opponent cannot profitably bluff any two cards.', tags: ['Poker', 'MDF'] },
  { q: 'MDF is calculated as...', opts: ['pot / (pot + bet)', 'bet / (pot + bet)', 'bet / pot', 'pot / bet'], a: 0, e: 'MDF = pot / (pot + bet); it is the complement of the bluff\'s required success frequency.', tags: ['Poker', 'MDF'] },
  { q: 'Facing a pot-sized bet, what is your Minimum Defense Frequency?', opts: ['50%', '33%', '67%', '100%'], a: 0, e: 'MDF = pot/(pot+bet) = 1/(1+1) = 50%, so you must defend half your range versus a pot-sized bet.', tags: ['Poker', 'MDF'] },
  { q: 'The required bluff success frequency (alpha) needed for a bet to break even is...', opts: ['bet / (pot + bet)', 'pot / (pot + bet)', 'bet / pot', 'pot / bet'], a: 0, e: 'Alpha = bet/(pot+bet) is how often a pure bluff must get a fold to break even.', tags: ['Poker', 'Bluffing'] },
  { q: 'For a balanced pot-sized river bet, the ideal ratio of bluffs to value bets is about...', opts: ['1 bluff to 2 value', '2 bluffs to 1 value', '1 bluff to 1 value', 'All value, no bluffs'], a: 0, e: 'A pot-sized bet gives 2:1 pot odds, so bluffs make up one third of the range, i.e. 1 bluff per 2 value bets.', tags: ['Poker', 'Bluffing'] },
  { q: 'As your river bet size gets larger, the share of bluffs in a balanced betting range...', opts: ['Increases', 'Decreases', 'Stays fixed at 50%', 'Drops to zero'], a: 0, e: 'Bigger bets lay worse pot odds, letting you include a higher proportion of bluffs while staying balanced.', tags: ['Poker', 'Bluffing'] },
  { q: 'A "balanced" range is one that...', opts: ['Mixes value and bluffs so it cannot be exploited', 'Contains only premium hands', 'Contains only bluffs', 'Is chosen at random'], a: 0, e: 'Balance means the right proportion of value and bluffs so opponents cannot profit by always calling or always folding.', tags: ['Poker', 'Balance'] },
  { q: 'Facing a pot-sized river bet, roughly how much equity does a bluff-catcher need to break even calling?', opts: ['33%', '50%', '25%', '66%'], a: 0, e: 'You risk one bet to win the pot plus the bet (2 units for 1), needing 1/3 = 33% equity to break even.', tags: ['Poker', 'Pot odds'] },

  // ── Level 3 — Combinatorics & blockers ──
  { q: 'How many distinct two-card starting combinations exist in Hold\'em?', opts: ['1326', '169', '52', '2652'], a: 0, e: 'There are C(52,2) = 1326 unique two-card combinations dealt from a 52-card deck.', tags: ['Poker', 'Combinatorics'] },
  { q: 'How many combinations of a specific pocket pair (e.g. pocket aces) are there?', opts: ['6', '4', '12', '16'], a: 0, e: 'A pocket pair has C(4,2) = 6 combos, one for each pair of the four suits.', tags: ['Poker', 'Combinatorics'] },
  { q: 'How many total combinations of a specific unpaired hand like Ace-King are there (all suits)?', opts: ['16', '12', '6', '4'], a: 0, e: 'Two unpaired ranks give 4 × 4 = 16 combos (4 suited plus 12 offsuit).', tags: ['Poker', 'Combinatorics'] },
  { q: 'How many combinations of a specific suited hand like Ace-King suited (AKs) are there?', opts: ['4', '6', '12', '16'], a: 0, e: 'A suited hand has exactly 4 combos, one for each of the four suits.', tags: ['Poker', 'Combinatorics'] },
  { q: 'How many combinations of a specific offsuit hand like Ace-King offsuit (AKo) are there?', opts: ['12', '16', '6', '4'], a: 0, e: 'An offsuit hand has 12 combos: 4 × 4 = 16 total minus the 4 suited combos.', tags: ['Poker', 'Combinatorics'] },
  { q: 'A "blocker" is a card in your hand that...', opts: ['Reduces the combos of specific hands the opponent can hold', 'Blocks the flop from coming', 'Guarantees you the pot', 'Must always be an ace'], a: 0, e: 'Holding a blocker removes cards from the deck, cutting the number of combinations your opponent can have.', tags: ['Poker', 'Blockers'] },
  { q: 'On a three-spade board, if you hold the ace of spades, how many nut-flush combos can your opponent have?', opts: ['Zero', 'One', 'Two', 'Four'], a: 0, e: 'The ace-high flush requires the ace of spades; holding it yourself blocks every nut-flush combo.', tags: ['Poker', 'Blockers'] },
  { q: 'When choosing which hand to bluff with, a strong candidate is one that...', opts: ['Blocks the opponent\'s value and calling combos', 'Blocks the opponent\'s folding combos', 'Matches the board texture exactly', 'Contains only low cards'], a: 0, e: 'A good bluff blocks the hands that would call (their value range), making a fold more likely.', tags: ['Poker', 'Blockers'] },

  // ── Level 4 — Range construction, polarization & bet-sizing theory ──
  { q: 'A "polarized" range is made up of...', opts: ['Strong value hands and bluffs, with few medium hands', 'Only medium-strength hands', 'Only pocket pairs', 'Randomly chosen hands'], a: 0, e: 'A polarized range splits into the top (value) and the bottom (bluffs), leaving out most middling hands.', tags: ['Poker', 'Range construction'] },
  { q: 'A "linear" or "merged" range consists of...', opts: ['A top-down band of strong through medium hands', 'Only bluffs and the nuts', 'Only the weakest hands', 'No value hands at all'], a: 0, e: 'A linear/merged range takes the best hands down through medium strength, with little or no pure bluffing.', tags: ['Poker', 'Range construction'] },
  { q: 'Polarized ranges tend to favour which bet sizing?', opts: ['Large bets and overbets', 'Only minimum bets', 'Only checks', 'Only small blinds'], a: 0, e: 'With only strong hands and bluffs, larger sizes apply maximum pressure and extract more from the value hands.', tags: ['Poker', 'Bet sizing'] },
  { q: 'A polarized range can bet large because the opponent is typically left holding...', opts: ['Mainly bluff-catchers', 'Only the nuts', 'No hands at all', 'Only stronger value'], a: 0, e: 'When you are polarized, the opponent\'s medium hands become bluff-catchers that beat only your bluffs.', tags: ['Poker', 'Bet sizing'] },
  { q: 'Linear or merged ranges tend to favour which bet sizing?', opts: ['Smaller bet sizes', 'Only overbets', 'Only all-ins', 'No bets at all'], a: 0, e: 'Merged ranges want value from worse hands that would fold to big bets, so smaller sizes work better.', tags: ['Poker', 'Bet sizing'] },
  { q: 'A "capped" range is one that...', opts: ['Contains none of the strongest possible hands', 'Contains only the nuts', 'Is perfectly balanced', 'Holds too many bluffs'], a: 0, e: 'A capped range has an upper limit on strength: it cannot hold the best hands, making it vulnerable to pressure.', tags: ['Poker', 'Range construction'] },
  { q: 'A player with a clear range and nut advantage on a board should generally...', opts: ['Bet more often and can use larger sizes', 'Always check', 'Fold most hands', 'Never bluff'], a: 0, e: 'Range and nut advantage let a player bet aggressively, often with big sizings the opponent cannot match.', tags: ['Poker', 'Range construction'] },
  { q: 'When a strategy uses several bet sizes, each size must contain both value and bluffs, otherwise...', opts: ['The size becomes readable and exploitable', 'The dealer stops the hand', 'The pot is void', 'You must go all-in'], a: 0, e: 'If a given size held only value or only bluffs, opponents could read your hand from the sizing and exploit it.', tags: ['Poker', 'Bet sizing'] },

  // ── Level 5 — Equilibrium concepts, solvers & practical simplifications ──
  { q: 'A Nash equilibrium is a set of strategies where...', opts: ['No player can improve by unilaterally changing strategy', 'One player always wins', 'All players fold', 'Strategies change every hand'], a: 0, e: 'At a Nash equilibrium each player\'s strategy is a best response to the others, so no solo deviation helps.', tags: ['Poker', 'Equilibrium'] },
  { q: 'A poker "GTO solution" produced by a solver is essentially...', opts: ['A Nash equilibrium of the game tree', 'A memorized preflop chart', 'A random strategy', 'A copy of a pro\'s play'], a: 0, e: 'Solvers approximate a Nash equilibrium: a pair of strategies neither player can exploit.', tags: ['Poker', 'Solvers'] },
  { q: 'Which algorithm do most modern poker solvers use to approximate equilibrium?', opts: ['Counterfactual Regret Minimization (CFR)', 'Gradient boosting', 'Alpha-beta pruning', 'Linear regression'], a: 0, e: 'CFR iteratively minimizes regret across the game tree, converging toward an unexploitable strategy.', tags: ['Poker', 'Solvers'] },
  { q: 'The "exploitability" of a strategy measures...', opts: ['How much a best-response opponent could win against it', 'How many hands it has played', 'Its total stack size', 'The rake it has paid'], a: 0, e: 'Exploitability is the EV a perfectly adjusting opponent could gain; a true GTO strategy has zero exploitability.', tags: ['Poker', 'Solvers'] },
  { q: 'A "mixed strategy" means a hand is...', opts: ['Played with a randomized frequency between actions', 'Always played the same way', 'Only ever folded', 'Only ever shoved all-in'], a: 0, e: 'A mixed strategy plays the same hand different ways by frequency, e.g. bet 70% and check 30% of the time.', tags: ['Poker', 'Equilibrium'] },
  { q: 'Solver solutions include mixed strategies mainly because...', opts: ['At equilibrium the actions have equal EV, so the hand is indifferent', 'Mixing wastes the opponent\'s time', 'The rules require randomization', 'It always maximizes folds'], a: 0, e: 'When two actions yield equal EV the player is indifferent, and mixing keeps the opponent from exploiting either choice.', tags: ['Poker', 'Equilibrium'] },
  { q: 'A common way to make GTO usable in real time is to...', opts: ['Simplify to a few bet sizes and memorable frequencies', 'Play every hand identically', 'Ignore position entirely', 'Never bluff'], a: 0, e: 'Humans approximate solver output with simplified sizings and round frequency heuristics rather than exact mixes.', tags: ['Poker', 'Practical'] },
  { q: 'In a solver, "node locking" refers to...', opts: ['Fixing one player\'s strategy at a spot to compute the best exploit', 'Freezing the software', 'Locking your hole cards', 'Preventing all-in bets'], a: 0, e: 'Node locking sets a player\'s action to a chosen (often flawed) strategy so the solver finds the maximally exploitative response.', tags: ['Poker', 'Solvers'] },
];
