import type { Seed } from './roadmap-build';

// "Databases & data modeling" learning path — 120 questions (15 levels × 8),
// easiest → hardest: relational basics, SQL, schema design & normalization,
// keys/constraints, indexing, transactions/ACID, the N+1 problem, NoSQL and
// scaling. Built directly (ids rm-db-1 … rm-db-120, 8 per level).
export const databasesSeeds: Seed[] = [
  // Level 1 — What is a Database?
  { q: 'What is a database?', opts: ['A single text file on your desktop', 'An organized collection of data stored so it can be queried and updated efficiently', 'A programming language', 'A type of web server'], a: 1, e: 'A database is an organized, persistent store of data managed so it can be efficiently queried, updated, and kept consistent.', tags: ['Databases', 'basics'], intro: 'Start with the big picture.' },
  { q: 'What does DBMS stand for?', opts: ['Data Backup Management Service', 'Database Management System', 'Distributed Binary Memory Store', 'Dynamic Block Mapping System'], a: 1, e: 'A DBMS (Database Management System) is the software that stores, retrieves, and manages data — e.g. PostgreSQL, MySQL, SQLite.', tags: ['Databases', 'DBMS'] },
  { q: 'Which is a relational database?', opts: ['Redis', 'MongoDB', 'PostgreSQL', 'Neo4j'], a: 2, e: 'PostgreSQL is a relational (SQL) database. Redis is a key-value store, MongoDB is document-oriented, and Neo4j is a graph database.', tags: ['Databases', 'relational'] },
  { q: 'In a relational database, data is organized into:', opts: ['Tables made of rows and columns', 'Folders and files', 'Nested JSON documents only', 'A single flat list'], a: 0, e: 'Relational databases store data in tables (relations); each row is a record and each column is a field/attribute.', tags: ['Databases', 'tables'] },
  { q: 'What is "persistence" in the context of databases?', opts: ['Data is lost when the program exits', 'Data survives beyond the lifetime of the process and machine restarts', 'Data can only be read once', 'Data is always encrypted'], a: 1, e: 'Persistence means stored data outlives the running process and survives restarts, unlike in-memory variables.', tags: ['Databases', 'persistence'] },
  { q: 'What does CRUD stand for?', opts: ['Create, Read, Update, Delete', 'Copy, Run, Undo, Deploy', 'Cache, Read, Update, Drop', 'Create, Replicate, Use, Destroy'], a: 0, e: 'CRUD names the four basic data operations: Create, Read, Update, Delete.', tags: ['Databases', 'CRUD'] },
  { q: 'Which language is the standard for querying relational databases?', opts: ['HTML', 'SQL', 'XML', 'Bash'], a: 1, e: 'SQL (Structured Query Language) is the standard language for defining and querying relational data.', tags: ['Databases', 'SQL'] },
  { q: 'What is a "schema" in a relational database?', opts: ['A backup of the data', 'The definition of the structure: tables, columns, types, and relationships', 'A single row of data', 'The network address of the server'], a: 1, e: 'A schema is the structural blueprint — which tables exist, their columns and types, and how they relate.', tags: ['Databases', 'schema'] },

  // Level 2 — Relational Basics
  { q: 'In a table, a "row" represents:', opts: ['A single field', 'A single record/entity instance', 'The table name', 'A database connection'], a: 1, e: 'A row (tuple) is one record — e.g. one user — with a value for each column.', tags: ['Databases', 'rows'] },
  { q: 'A "column" in a table represents:', opts: ['One record', 'An attribute/field shared by every row', 'A foreign server', 'An index'], a: 1, e: 'A column defines an attribute (like email or created_at) that every row has a value for.', tags: ['Databases', 'columns'] },
  { q: 'What is a primary key?', opts: ['Any column that allows duplicates', 'A column (or set) that uniquely identifies each row in a table', 'The first column alphabetically', 'A password for the table'], a: 1, e: 'A primary key uniquely identifies each row and cannot be NULL or duplicated.', tags: ['Databases', 'primary key'] },
  { q: 'What is a foreign key?', opts: ['A key from another database vendor', 'A column that references the primary key of another table to link them', 'A duplicate primary key', 'An encrypted column'], a: 1, e: 'A foreign key references another table’s primary key, enforcing a relationship and referential integrity.', tags: ['Databases', 'foreign key'] },
  { q: 'A relationship where one user has many orders is called:', opts: ['One-to-one', 'One-to-many', 'Many-to-many', 'None-to-one'], a: 1, e: 'One user → many orders is a one-to-many relationship, typically modeled with a foreign key on the "many" side (orders.user_id).', tags: ['Databases', 'relationships'] },
  { q: 'A many-to-many relationship (e.g. students and courses) is usually modeled with:', opts: ['A single table', 'A junction/join table holding both foreign keys', 'Two primary keys in one row', 'No table at all'], a: 1, e: 'Many-to-many uses a junction (join) table, e.g. enrollments(student_id, course_id).', tags: ['Databases', 'many-to-many'] },
  { q: 'What does "referential integrity" ensure?', opts: ['Every foreign key value points to an existing row', 'Every column is indexed', 'All data is encrypted', 'Queries always run fast'], a: 0, e: 'Referential integrity guarantees a foreign key cannot reference a non-existent row, keeping relationships valid.', tags: ['Databases', 'integrity'] },
  { q: 'Which best describes a "relation" in relational theory?', opts: ['A foreign key', 'A table (a set of tuples over the same attributes)', 'A network link', 'A stored procedure'], a: 1, e: 'In relational theory a "relation" is a table: a set of tuples (rows) sharing the same attributes (columns).', tags: ['Databases', 'theory'] },

  // Level 3 — SQL SELECT Basics
  { q: 'Which clause retrieves data from a table?', opts: ['GET', 'SELECT', 'FETCH', 'READ'], a: 1, e: 'SELECT is the SQL statement used to read rows from one or more tables.', tags: ['SQL', 'select'] },
  { q: 'How do you select every column from a table named users?', opts: ['SELECT all FROM users', 'SELECT * FROM users', 'GET * IN users', 'SELECT columns(users)'], a: 1, e: 'SELECT * FROM users returns all columns. In production, listing explicit columns is usually preferred.', tags: ['SQL', 'select'] },
  { q: 'Which clause limits which rows are returned based on a condition?', opts: ['FILTER', 'HAVING', 'WHERE', 'ONLY'], a: 2, e: 'WHERE filters rows by a condition, e.g. WHERE age >= 18.', tags: ['SQL', 'where'] },
  { q: 'What does SELECT name FROM users WHERE id = 5 return?', opts: ['All names', 'The name(s) of the row(s) where id equals 5', 'The id column', 'Nothing, it is invalid'], a: 1, e: 'It returns the name column for rows whose id is 5 (typically one row, since id is usually a primary key).', tags: ['SQL', 'where'] },
  { q: 'How do you return only distinct (unique) values of a column?', opts: ['SELECT UNIQUE col', 'SELECT DISTINCT col', 'SELECT ONLY col', 'SELECT col GROUP'], a: 1, e: 'SELECT DISTINCT col removes duplicate values from the result.', tags: ['SQL', 'distinct'] },
  { q: 'Which clause renames a column or table in the result (an alias)?', opts: ['AS', 'RENAME', 'ALIAS', 'CALL'], a: 0, e: 'AS creates an alias, e.g. SELECT price AS cost. The AS keyword is often optional.', tags: ['SQL', 'alias'] },
  { q: 'What does LIMIT 10 do?', opts: ['Skips 10 rows', 'Returns at most 10 rows', 'Deletes 10 rows', 'Requires exactly 10 rows'], a: 1, e: 'LIMIT caps the number of rows returned — here, at most 10.', tags: ['SQL', 'limit'] },
  { q: 'Which combination paginates results (skip then take)?', opts: ['SKIP and TAKE', 'OFFSET and LIMIT', 'PAGE and SIZE', 'START and END'], a: 1, e: 'OFFSET skips rows and LIMIT caps the count, together enabling pagination (note: large OFFSETs can be slow).', tags: ['SQL', 'pagination'] },

  // Level 4 — Filtering & Sorting
  { q: 'How do you sort results by a column ascending?', opts: ['SORT col', 'ORDER BY col ASC', 'ARRANGE col', 'GROUP BY col'], a: 1, e: 'ORDER BY col ASC sorts ascending (ASC is the default; DESC sorts descending).', tags: ['SQL', 'order by'] },
  { q: 'Which operator matches a pattern, e.g. names starting with "A"?', opts: ['MATCH', 'LIKE', 'REGEX', 'CONTAINS'], a: 1, e: "LIKE matches patterns: WHERE name LIKE 'A%' matches names starting with A (% is any sequence).", tags: ['SQL', 'like'] },
  { q: 'What does WHERE age BETWEEN 18 AND 30 match?', opts: ['Ages 19 to 29', 'Ages 18 to 30 inclusive', 'Only 18 and 30', 'Ages over 30'], a: 1, e: 'BETWEEN is inclusive of both endpoints, so it matches 18 through 30.', tags: ['SQL', 'between'] },
  { q: 'How do you match any of several values, e.g. status is active, pending, or closed?', opts: ['WHERE status = (active, pending, closed)', "WHERE status IN ('active','pending','closed')", 'WHERE status ANY ...', 'WHERE status LIKE list'], a: 1, e: "IN tests membership in a set: WHERE status IN ('active','pending','closed').", tags: ['SQL', 'in'] },
  { q: 'How do you find rows where a column has no value?', opts: ['WHERE col = NULL', 'WHERE col IS NULL', 'WHERE col == NULL', 'WHERE col EMPTY'], a: 1, e: 'Use IS NULL (not = NULL), because NULL comparisons with = yield unknown, never true.', tags: ['SQL', 'null'] },
  { q: 'Which combines two conditions so both must be true?', opts: ['OR', 'AND', 'NOT', 'XOR'], a: 1, e: 'AND requires both conditions to be true; OR requires at least one.', tags: ['SQL', 'logic'] },
  { q: 'What does ORDER BY created_at DESC do?', opts: ['Oldest first', 'Newest (largest) first', 'Random order', 'Alphabetical by id'], a: 1, e: 'DESC sorts descending, so the most recent created_at values come first.', tags: ['SQL', 'order by'] },
  { q: "WHERE name LIKE '%son' matches names that:", opts: ['Start with son', 'End with son', 'Contain exactly son', 'Have no son'], a: 1, e: "A leading % means any prefix, so '%son' matches names ending in 'son' (Anderson, Jackson).", tags: ['SQL', 'like'] },

  // Level 5 — Aggregations & GROUP BY
  { q: 'Which function counts the number of rows?', opts: ['SUM()', 'COUNT()', 'TOTAL()', 'ROWS()'], a: 1, e: 'COUNT(*) counts rows; COUNT(col) counts non-NULL values of that column.', tags: ['SQL', 'aggregate'] },
  { q: 'Which function adds up numeric values in a column?', opts: ['ADD()', 'SUM()', 'PLUS()', 'AGG()'], a: 1, e: 'SUM(col) returns the total of the numeric values in that column.', tags: ['SQL', 'aggregate'] },
  { q: 'What does GROUP BY do?', opts: ['Sorts rows', 'Collapses rows that share values into groups so aggregates apply per group', 'Deletes duplicate columns', 'Joins two tables'], a: 1, e: 'GROUP BY buckets rows by the grouping columns so aggregate functions (COUNT, SUM, …) compute per group.', tags: ['SQL', 'group by'] },
  { q: 'To count orders per user you would:', opts: ['SELECT COUNT(*) FROM orders', 'SELECT user_id, COUNT(*) FROM orders GROUP BY user_id', 'SELECT user_id FROM orders LIMIT 1', 'ORDER BY user_id'], a: 1, e: 'Group by user_id and COUNT(*) to get the number of orders for each user.', tags: ['SQL', 'group by'] },
  { q: 'Which clause filters groups after aggregation (e.g. only users with > 5 orders)?', opts: ['WHERE', 'HAVING', 'FILTER', 'GROUP WHERE'], a: 1, e: 'HAVING filters on aggregate results after GROUP BY; WHERE filters individual rows before grouping.', tags: ['SQL', 'having'] },
  { q: 'What does AVG(price) return?', opts: ['The largest price', 'The arithmetic mean of price', 'The number of prices', 'The smallest price'], a: 1, e: 'AVG computes the average (mean) of the non-NULL values in the column.', tags: ['SQL', 'aggregate'] },
  { q: 'Which pair returns the smallest and largest values?', opts: ['LOW() and HIGH()', 'MIN() and MAX()', 'FIRST() and LAST()', 'HEAD() and TAIL()'], a: 1, e: 'MIN() and MAX() return the minimum and maximum values of a column.', tags: ['SQL', 'aggregate'] },
  { q: 'Why does COUNT(col) sometimes differ from COUNT(*)?', opts: ['They are always equal', 'COUNT(col) ignores rows where col is NULL', 'COUNT(*) ignores NULLs', 'COUNT(col) counts columns'], a: 1, e: 'COUNT(*) counts all rows; COUNT(col) skips rows where col is NULL.', tags: ['SQL', 'count', 'null'] },

  // Level 6 — Joins
  { q: 'What does a JOIN do?', opts: ['Sorts a table', 'Combines rows from two or more tables based on a related column', 'Deletes related rows', 'Renames a table'], a: 1, e: 'A JOIN combines rows from multiple tables using a matching condition, usually a foreign-key relationship.', tags: ['SQL', 'joins'] },
  { q: 'An INNER JOIN returns:', opts: ['All rows from both tables', 'Only rows with a match in both tables', 'Only unmatched rows', 'Rows from the left table only'], a: 1, e: 'INNER JOIN returns only rows that have matching values in both tables.', tags: ['SQL', 'inner join'] },
  { q: 'A LEFT JOIN returns:', opts: ['Only matching rows', 'All rows from the left table, plus matches (NULLs where none) from the right', 'All rows from the right table', 'No rows'], a: 1, e: 'LEFT (OUTER) JOIN keeps every left-table row, filling right-table columns with NULL when there is no match.', tags: ['SQL', 'left join'] },
  { q: 'Which column typically connects orders to users in a JOIN?', opts: ['orders.user_id = users.id', 'orders.id = users.id', 'orders.name = users.name', 'orders.* = users.*'], a: 0, e: 'You join on the foreign key: orders.user_id references users.id.', tags: ['SQL', 'joins'] },
  { q: 'What does a CROSS JOIN produce?', opts: ['Only matching rows', 'The Cartesian product: every left row paired with every right row', 'An error', 'The union of both tables'], a: 1, e: 'A CROSS JOIN pairs each row of one table with every row of the other (the Cartesian product) — rarely what you want by accident.', tags: ['SQL', 'cross join'] },
  { q: 'A "self join" is:', opts: ['Joining a table to itself (e.g. employees to their managers)', 'Joining two unrelated databases', 'A join that never returns rows', 'A join without a condition'], a: 0, e: 'A self join joins a table to itself using aliases, useful for hierarchical data like employee→manager.', tags: ['SQL', 'self join'] },
  { q: 'Why prefer a JOIN over running many separate queries in a loop?', opts: ['It always returns fewer rows', 'The database can fetch related data in one efficient round trip instead of many', 'Joins are required by SQL', 'Loops cannot read databases'], a: 1, e: 'One JOIN lets the database return related data in a single optimized query, avoiding many slow round trips (the N+1 problem).', tags: ['SQL', 'joins', 'performance'] },
  { q: 'A FULL OUTER JOIN returns:', opts: ['Only matched rows', 'All rows from both tables, matched where possible and NULL-filled where not', 'Only left rows', 'Only right rows'], a: 1, e: 'FULL OUTER JOIN keeps all rows from both sides, pairing matches and using NULLs where a side has none.', tags: ['SQL', 'outer join'] },

  // Level 7 — Schema Design & Normalization
  { q: 'What is the goal of normalization?', opts: ['To make queries slower', 'To reduce data redundancy and avoid update anomalies', 'To store everything in one table', 'To encrypt the data'], a: 1, e: 'Normalization organizes data to minimize duplication and the anomalies that come from storing the same fact in many places.', tags: ['Databases', 'normalization'] },
  { q: 'First normal form (1NF) requires that:', opts: ['Every column holds a single atomic value (no repeating groups/arrays)', 'There are no foreign keys', 'Every table has exactly one column', 'Data is denormalized'], a: 0, e: '1NF requires atomic column values — no lists or repeating groups packed into one field.', tags: ['Databases', '1NF'] },
  { q: 'Storing a customer’s address in every order row (instead of once per customer) risks:', opts: ['Faster updates', 'Update anomalies — changing the address means editing many rows', 'Better integrity', 'Smaller storage'], a: 1, e: 'Duplicating a fact causes update anomalies: one change must be applied everywhere or the data becomes inconsistent.', tags: ['Databases', 'anomalies'] },
  { q: 'A "surrogate key" is:', opts: ['A natural attribute like email', 'An artificial identifier (e.g. an auto-increment id) with no business meaning', 'A foreign key', 'A password'], a: 1, e: 'A surrogate key is a system-generated id (serial/UUID) used as the primary key instead of a natural attribute.', tags: ['Databases', 'keys'] },
  { q: 'When is denormalization (deliberate redundancy) reasonable?', opts: ['Never', 'To optimize read-heavy workloads, accepting extra write/consistency cost', 'Only in 1NF', 'Only for primary keys'], a: 1, e: 'Denormalization trades redundancy for read performance; it is a deliberate optimization, managed carefully.', tags: ['Databases', 'denormalization'] },
  { q: 'Third normal form (3NF) removes:', opts: ['All foreign keys', 'Transitive dependencies (non-key columns depending on other non-key columns)', 'Primary keys', 'Indexes'], a: 1, e: '3NF requires non-key columns depend only on the key — eliminating transitive dependencies through other non-key columns.', tags: ['Databases', '3NF'] },
  { q: 'Which is generally a good modeling practice?', opts: ['One giant table for everything', 'Separate entities into their own tables and link them with foreign keys', 'Avoid primary keys', 'Store JSON blobs for all data'], a: 1, e: 'Model distinct entities as separate tables related by keys; this keeps data consistent and queryable.', tags: ['Databases', 'modeling'] },
  { q: 'A junction table for a many-to-many relationship typically has:', opts: ['No columns', 'Foreign keys to both related tables (often as a composite key)', 'Only a primary key', 'All columns from both tables'], a: 1, e: 'The junction table holds a foreign key to each side, often combined as a composite primary key.', tags: ['Databases', 'modeling'] },

  // Level 8 — Keys & Constraints
  { q: 'A UNIQUE constraint guarantees:', opts: ['Values can repeat', 'No two rows share the same value(s) in that column', 'The column is the primary key', 'The column is indexed but not unique'], a: 1, e: 'UNIQUE prevents duplicate values in a column (or set of columns), e.g. a unique email.', tags: ['Databases', 'constraints'] },
  { q: 'A NOT NULL constraint means:', opts: ['The column may be empty', 'The column must always have a value', 'The column is the primary key', 'The column auto-increments'], a: 1, e: 'NOT NULL forbids missing values, requiring every row to supply one.', tags: ['Databases', 'constraints'] },
  { q: 'A CHECK constraint is used to:', opts: ['Encrypt a column', 'Enforce a condition on values (e.g. price >= 0)', 'Create an index', 'Join two tables'], a: 1, e: 'CHECK enforces a boolean rule on column values, rejecting rows that violate it.', tags: ['Databases', 'constraints'] },
  { q: 'What does ON DELETE CASCADE do for a foreign key?', opts: ['Blocks deletes', 'Deletes child rows automatically when the referenced parent row is deleted', 'Duplicates the parent', 'Nulls the parent'], a: 1, e: 'ON DELETE CASCADE removes dependent child rows when their parent is deleted, keeping referential integrity.', tags: ['Databases', 'cascade'] },
  { q: 'A composite key is:', opts: ['A key made of two or more columns together', 'A key that is encrypted', 'A foreign key only', 'A key that allows NULLs'], a: 0, e: 'A composite (compound) key uses multiple columns together to uniquely identify a row.', tags: ['Databases', 'keys'] },
  { q: 'A DEFAULT on a column:', opts: ['Forbids inserts', 'Supplies a value automatically when none is provided', 'Deletes old rows', 'Indexes the column'], a: 1, e: 'DEFAULT gives a column a fallback value (e.g. created_at DEFAULT now()) when an insert omits it.', tags: ['Databases', 'default'] },
  { q: 'You INSERT a row whose foreign key points at a parent that does not exist. What does the database do?', opts: ['Silently ignores the bad reference', 'Rejects the statement with a constraint violation error', 'Drops the table', 'Converts the value to NULL automatically'], a: 1, e: 'A foreign-key violation makes the offending statement fail with an error (and aborts the transaction if not handled), protecting referential integrity.', tags: ['Databases', 'constraints'] },
  { q: 'Why add a UNIQUE constraint on email rather than just checking in app code?', opts: ['It is slower but cleaner', 'The database enforces it atomically even under concurrent inserts; app checks can race', 'App checks are impossible', 'Constraints disable indexes'], a: 1, e: 'A DB constraint is enforced atomically and survives race conditions that a check-then-insert in app code cannot.', tags: ['Databases', 'constraints', 'concurrency'] },

  // Level 9 — Data Types & NULL
  { q: 'Which type best stores a monetary amount precisely?', opts: ['FLOAT', 'NUMERIC/DECIMAL', 'INT only', 'TEXT'], a: 1, e: 'NUMERIC/DECIMAL stores exact fixed-point values; FLOAT/DOUBLE can introduce rounding errors unsuitable for money.', tags: ['Databases', 'types'] },
  { q: 'What does NULL represent?', opts: ['The number zero', 'An empty string', 'The absence of a value (unknown/not applicable)', 'A boolean false'], a: 2, e: 'NULL means "no value" — distinct from 0 or empty string, and it propagates through comparisons as unknown.', tags: ['Databases', 'null'] },
  { q: 'What is NULL = NULL in SQL?', opts: ['TRUE', 'FALSE', 'NULL/unknown', 'An error'], a: 2, e: 'Comparing NULL with anything (including NULL) yields unknown (NULL), which is why IS NULL exists.', tags: ['Databases', 'null'] },
  { q: 'Which type is best for a true/false flag?', opts: ['TEXT', 'BOOLEAN', 'VARCHAR(1)', 'FLOAT'], a: 1, e: 'BOOLEAN cleanly represents true/false (where supported), better than encoding it in text or numbers.', tags: ['Databases', 'types'] },
  { q: 'A TIMESTAMP WITH TIME ZONE column is preferable to a naive timestamp because:', opts: ['It uses less space', 'It records an unambiguous instant regardless of server time zone', 'It is faster to index', 'It cannot be NULL'], a: 1, e: 'Time-zone-aware timestamps store an absolute instant, avoiding ambiguity when servers or users span zones.', tags: ['Databases', 'time'] },
  { q: 'COALESCE(col, 0) returns:', opts: ['Always 0', 'col if it is not NULL, otherwise 0', 'NULL', 'An error'], a: 1, e: 'COALESCE returns its first non-NULL argument, so it substitutes 0 when col is NULL.', tags: ['Databases', 'null', 'coalesce'] },
  { q: 'Choosing VARCHAR(50) vs TEXT mainly affects:', opts: ['Whether NULL is allowed', 'A length constraint on the value (TEXT is unbounded)', 'Index type only', 'Encryption'], a: 1, e: 'VARCHAR(n) caps length; TEXT is unbounded. Pick a limit when the domain has a real maximum.', tags: ['Databases', 'types'] },
  { q: 'Storing a JSON document in a JSONB column is useful when:', opts: ['Data is always perfectly relational', 'The shape is flexible/semi-structured but you still want to query it', 'You never query the data', 'You want maximum normalization'], a: 1, e: 'JSONB suits semi-structured data you still need to index and query, blending flexibility with SQL power.', tags: ['Databases', 'json'] },

  // Level 10 — Indexing
  { q: 'What is the primary purpose of an index?', opts: ['To encrypt rows', 'To speed up reads by letting the database find rows without scanning the whole table', 'To enforce NOT NULL', 'To compress data'], a: 1, e: 'An index is a lookup structure (often a B-tree) that lets the DB locate matching rows quickly instead of a full table scan.', tags: ['Indexing', 'basics'] },
  { q: 'What is a common downside of adding many indexes?', opts: ['Reads get slower', 'Writes (INSERT/UPDATE/DELETE) get slower and storage grows, since indexes must be maintained', 'Queries stop working', 'NULLs are forbidden'], a: 1, e: 'Every index must be updated on writes and consumes space, so over-indexing slows writes and wastes storage.', tags: ['Indexing', 'tradeoffs'] },
  { q: 'A query filtering on WHERE email = ? is fastest when:', opts: ['email has no index', 'email is indexed', 'the table has no primary key', 'you SELECT *'], a: 1, e: 'An index on email lets the DB jump straight to matching rows instead of scanning every row.', tags: ['Indexing', 'where'] },
  { q: 'What data structure backs most general-purpose database indexes?', opts: ['Linked list', 'B-tree (balanced tree)', 'Stack', 'Bloom filter only'], a: 1, e: 'B-trees keep keys sorted and balanced, giving logarithmic lookups, range scans, and ordered traversal.', tags: ['Indexing', 'b-tree'] },
  { q: 'A composite index on (last_name, first_name) helps queries that filter:', opts: ['By first_name only', 'By last_name, or last_name then first_name (leftmost prefix)', 'By any column in any order equally', 'Only by primary key'], a: 1, e: 'Composite indexes are usable by the leftmost prefix: (last_name) or (last_name, first_name), not first_name alone.', tags: ['Indexing', 'composite'] },
  { q: 'EXPLAIN (or EXPLAIN ANALYZE) is used to:', opts: ['Delete a query', 'Show the query plan so you can see if an index is used', 'Encrypt the query', 'Format SQL'], a: 1, e: 'EXPLAIN reveals the planner’s execution strategy (seq scan vs index scan), key for diagnosing slow queries.', tags: ['Indexing', 'explain'] },
  { q: 'A "full table scan" means:', opts: ['The DB used an index efficiently', 'The DB read every row because no useful index existed', 'The table was dropped', 'A backup ran'], a: 1, e: 'A full/sequential scan reads all rows; fine for small tables, but a red flag for large filtered queries lacking an index.', tags: ['Indexing', 'scan'] },
  { q: 'A UNIQUE index additionally:', opts: ['Allows duplicates', 'Enforces uniqueness while also speeding lookups', 'Disables the primary key', 'Slows down all reads'], a: 1, e: 'A unique index both prevents duplicate values and accelerates lookups on that column.', tags: ['Indexing', 'unique'] },

  // Level 11 — Transactions & ACID
  { q: 'What is a database transaction?', opts: ['A single SELECT', 'A unit of work whose statements all succeed or all fail together', 'A backup', 'A user login'], a: 1, e: 'A transaction groups operations so they commit together or roll back together — all-or-nothing.', tags: ['Transactions', 'basics'] },
  { q: 'What does the "A" in ACID stand for?', opts: ['Availability', 'Atomicity', 'Authorization', 'Aggregation'], a: 1, e: 'Atomicity: a transaction is indivisible — either all its changes apply or none do.', tags: ['Transactions', 'ACID'] },
  { q: 'The "C" in ACID (Consistency) means:', opts: ['The cache is warm', 'A transaction moves the database from one valid state to another, preserving constraints', 'Data is compressed', 'Queries are case-insensitive'], a: 1, e: 'Consistency ensures committed transactions leave the database satisfying all rules/constraints.', tags: ['Transactions', 'ACID'] },
  { q: 'The "D" in ACID (Durability) guarantees:', opts: ['Committed data survives crashes/power loss', 'Transactions never fail', 'Data is deleted on restart', 'Reads are always fast'], a: 0, e: 'Durability means once committed, changes persist even through crashes, typically via write-ahead logs.', tags: ['Transactions', 'ACID'] },
  { q: 'Which command makes a transaction’s changes permanent?', opts: ['ROLLBACK', 'COMMIT', 'SAVE', 'FLUSH'], a: 1, e: 'COMMIT finalizes a transaction; ROLLBACK discards its changes.', tags: ['Transactions', 'commit'] },
  { q: 'Why wrap "debit one account, credit another" in a transaction?', opts: ['For speed', 'So money is never lost or created if one step fails — both apply or neither does', 'To avoid indexes', 'To bypass constraints'], a: 1, e: 'Atomicity ensures a partial transfer can’t happen; either both updates commit or both roll back.', tags: ['Transactions', 'atomicity'] },
  { q: 'ROLLBACK is used when:', opts: ['You want to keep changes', 'An error occurs and you want to undo the transaction’s changes', 'You want to index a table', 'You want to commit faster'], a: 1, e: 'ROLLBACK aborts the transaction, undoing all its uncommitted changes.', tags: ['Transactions', 'rollback'] },
  { q: 'A SAVEPOINT lets you:', opts: ['Back up the whole database', 'Roll back part of a transaction to a marked point without aborting all of it', 'Commit half a row', 'Encrypt a transaction'], a: 1, e: 'A SAVEPOINT marks an intermediate point you can roll back to, giving finer control within a transaction.', tags: ['Transactions', 'savepoint'] },

  // Level 12 — Isolation & Locking
  { q: 'Isolation levels control:', opts: ['How data is encrypted', 'What concurrent transactions can see of each other’s uncommitted/committed changes', 'Index types', 'Backup frequency'], a: 1, e: 'Isolation levels trade consistency for concurrency by defining which concurrency anomalies are allowed.', tags: ['Transactions', 'isolation'] },
  { q: 'A "dirty read" is:', opts: ['Reading committed data', 'Reading another transaction’s uncommitted changes that may be rolled back', 'Reading from a backup', 'A failed read'], a: 1, e: 'A dirty read sees uncommitted data that might disappear if that transaction rolls back.', tags: ['Transactions', 'anomalies'] },
  { q: 'Which isolation level prevents dirty reads but may allow non-repeatable reads?', opts: ['READ UNCOMMITTED', 'READ COMMITTED', 'No level does', 'SERIALIZABLE only'], a: 1, e: 'READ COMMITTED only sees committed data (no dirty reads) but a row can change between two reads (non-repeatable read).', tags: ['Transactions', 'isolation'] },
  { q: 'The strongest standard isolation level is:', opts: ['READ UNCOMMITTED', 'REPEATABLE READ', 'SERIALIZABLE', 'SNAPSHOT-NONE'], a: 2, e: 'SERIALIZABLE behaves as if transactions ran one at a time, preventing all standard anomalies (at a concurrency cost).', tags: ['Transactions', 'isolation'] },
  { q: 'A deadlock occurs when:', opts: ['A query is slow', 'Two transactions each hold a lock the other needs, so neither can proceed', 'An index is missing', 'A table is empty'], a: 1, e: 'A deadlock is a circular wait on locks; the DB detects it and aborts one transaction to break it.', tags: ['Transactions', 'deadlock'] },
  { q: 'SELECT ... FOR UPDATE is used to:', opts: ['Read without locking', 'Lock the selected rows so other transactions can’t modify them until you commit', 'Update without selecting', 'Create an index'], a: 1, e: 'FOR UPDATE takes a row lock, preventing concurrent writers — useful for read-modify-write patterns.', tags: ['Transactions', 'locking'] },
  { q: 'Optimistic concurrency control typically:', opts: ['Locks rows up front', 'Lets transactions proceed and checks for conflicts at commit (e.g. a version column)', 'Disables transactions', 'Always uses SERIALIZABLE'], a: 1, e: 'Optimistic control avoids locks, detecting conflicts at commit time (often via a version/updated_at check) and retrying.', tags: ['Transactions', 'concurrency'] },
  { q: 'A "lost update" anomaly happens when:', opts: ['Two transactions read a value and both overwrite it, losing one update', 'A backup fails', 'An index is dropped', 'NULL is inserted'], a: 0, e: 'Two read-modify-write transactions can clobber each other; locking or version checks prevent the lost update.', tags: ['Transactions', 'anomalies'] },

  // Level 13 — The N+1 Problem
  { q: 'The "N+1 query problem" is:', opts: ['Running one efficient query', 'Running 1 query to get a list, then 1 extra query per item (N more) to load related data', 'A type of index', 'A backup strategy'], a: 1, e: 'N+1 means a list query plus one follow-up query per row — N+1 total — usually a performance bug.', tags: ['N+1', 'performance'] },
  { q: 'Fetching 100 posts then querying each post’s author separately causes:', opts: ['1 query', '101 queries (1 + 100)', '2 queries', '0 queries'], a: 1, e: 'That is the classic N+1: 1 query for posts plus 100 for authors = 101 round trips.', tags: ['N+1', 'performance'] },
  { q: 'A common fix for N+1 is to:', opts: ['Add more loops', 'Use a JOIN or batched "IN" query to load related data in one (or few) queries', 'Remove indexes', 'Disable the database'], a: 1, e: 'Load related rows together with a JOIN or a single WHERE id IN (...) batch instead of one query per item.', tags: ['N+1', 'joins'] },
  { q: 'In ORMs, "eager loading" (e.g. includes/joins) helps by:', opts: ['Deferring all queries', 'Pre-fetching related records up front to avoid per-item queries', 'Disabling relations', 'Encrypting queries'], a: 1, e: 'Eager loading fetches associations in advance (via joins or batched queries), preventing N+1 lazy loads.', tags: ['N+1', 'orm'] },
  { q: 'Why is N+1 often invisible in development but painful in production?', opts: ['Production has fewer rows', 'With small dev data the extra queries are cheap; at scale the per-row queries dominate latency', 'It only affects writes', 'Indexes hide it'], a: 1, e: 'A handful of dev rows masks N+1; with thousands of rows the many round trips become the bottleneck.', tags: ['N+1', 'scaling'] },
  { q: 'A "DataLoader"-style batching utility addresses N+1 by:', opts: ['Caching the whole DB', 'Collecting individual key lookups within a tick and issuing one batched query', 'Removing foreign keys', 'Running queries twice'], a: 1, e: 'DataLoader batches per-key requests into a single IN query (and caches within a request), a standard N+1 fix in GraphQL.', tags: ['N+1', 'batching'] },
  { q: 'Which tool best reveals an N+1 problem?', opts: ['A spell checker', 'Query logging / an APM that shows repeated similar queries per request', 'A linter', 'A CSS inspector'], a: 1, e: 'Logging queries or using an APM surfaces the tell-tale burst of near-identical queries per request.', tags: ['N+1', 'observability'] },
  { q: 'A risk of over-eager joining everything to avoid N+1 is:', opts: ['Nothing, always join all', 'Fetching huge result sets / cartesian blow-ups you do not need', 'Losing the primary key', 'Breaking ACID'], a: 1, e: 'Joining too much can over-fetch and even multiply rows; balance eager loading against payload size.', tags: ['N+1', 'tradeoffs'] },

  // Level 14 — NoSQL & When to Use It
  { q: 'A document database (e.g. MongoDB) stores data as:', opts: ['Rows in fixed tables', 'Flexible, often JSON-like documents', 'Only key-value pairs', 'Graphs of nodes/edges'], a: 1, e: 'Document stores hold semi-structured documents (JSON/BSON), allowing flexible, nested schemas.', tags: ['NoSQL', 'document'] },
  { q: 'A key-value store (e.g. Redis) is ideal for:', opts: ['Complex multi-table joins', 'Fast lookups by key, caching, and ephemeral data', 'Strong relational constraints', 'Ad-hoc analytical SQL'], a: 1, e: 'Key-value stores excel at O(1) lookups by key — great for caches, sessions, and counters.', tags: ['NoSQL', 'key-value'] },
  { q: 'A graph database is best suited to:', opts: ['Tabular reports', 'Highly connected data with relationship-heavy queries (e.g. social graphs)', 'Storing images', 'Simple counters'], a: 1, e: 'Graph databases (Neo4j) model nodes and edges, making traversals over connected data efficient.', tags: ['NoSQL', 'graph'] },
  { q: '"Schema-less" in NoSQL really means:', opts: ['No structure ever', 'Schema flexibility — structure is enforced by the application, not the database', 'Encryption by default', 'No primary keys allowed'], a: 1, e: 'NoSQL stores allow varying document shapes; the burden of consistency shifts to application code.', tags: ['NoSQL', 'schema'] },
  { q: 'A reason to choose a relational DB over NoSQL is:', opts: ['You need flexible, ever-changing shapes', 'You need strong consistency, complex joins, and multi-row transactions', 'You only do key lookups', 'You never query the data'], a: 1, e: 'Relational databases shine for structured data needing joins, constraints, and ACID transactions.', tags: ['NoSQL', 'tradeoffs'] },
  { q: 'Many document databases favor which trade-off by default?', opts: ['Strong consistency over availability', 'Availability and partition tolerance, with eventual consistency', 'No durability', 'No replication'], a: 1, e: 'Many NoSQL systems lean toward availability and eventual consistency (AP) to scale horizontally.', tags: ['NoSQL', 'consistency'] },
  { q: 'Denormalizing/embedding related data in a document is common in NoSQL because:', opts: ['Joins are cheap there', 'There are no joins, so related data is embedded to be read in one fetch', 'It enforces 3NF', 'It is required by SQL'], a: 1, e: 'Document stores typically lack joins, so you embed related data to read it in a single document fetch.', tags: ['NoSQL', 'modeling'] },
  { q: 'A balanced modern approach is often:', opts: ['Use only one database type forever', 'Polyglot persistence — pick the store that fits each workload', 'Avoid databases', 'Always use NoSQL'], a: 1, e: 'Polyglot persistence uses the right tool per job (e.g. Postgres for core data, Redis for cache, a search engine for full text).', tags: ['NoSQL', 'architecture'] },

  // Level 15 — Performance & Scaling
  { q: 'Read replicas primarily help by:', opts: ['Increasing write throughput', 'Spreading read load across copies of the database', 'Replacing indexes', 'Enforcing constraints'], a: 1, e: 'Replicas serve reads from copies of the primary, scaling read-heavy workloads (writes still go to the primary).', tags: ['Scaling', 'replication'] },
  { q: 'Connection pooling improves performance by:', opts: ['Encrypting queries', 'Reusing a limited set of established DB connections instead of opening one per request', 'Removing indexes', 'Disabling transactions'], a: 1, e: 'Pools reuse expensive-to-create connections, avoiding per-request connection overhead and protecting the DB from overload.', tags: ['Scaling', 'pooling'] },
  { q: 'Caching frequent query results (e.g. in Redis) helps when:', opts: ['Data changes every millisecond', 'Reads vastly outnumber writes and slightly stale data is acceptable', 'You need strong consistency always', 'The table is tiny'], a: 1, e: 'A cache offloads the DB for hot, read-mostly data, trading some staleness for big latency and load wins.', tags: ['Scaling', 'caching'] },
  { q: 'Horizontal partitioning (sharding) splits a table by:', opts: ['Columns across servers', 'Rows across multiple servers based on a shard key', 'Indexes only', 'Time of day'], a: 1, e: 'Sharding distributes rows across nodes by a shard key, spreading both storage and load beyond one machine.', tags: ['Scaling', 'sharding'] },
  { q: 'A poorly chosen shard key can cause:', opts: ['Perfect balance', 'Hot spots where one shard gets most of the traffic', 'Automatic indexing', 'Stronger consistency'], a: 1, e: 'If the shard key concentrates access, one shard becomes a hotspot, undermining the benefit of sharding.', tags: ['Scaling', 'sharding'] },
  { q: 'A frequent root cause of a slow endpoint is:', opts: ['Too many indexes only', 'A missing index causing a full scan, or an N+1 query pattern', 'Using a primary key', 'Committing transactions'], a: 1, e: 'Missing indexes and N+1 patterns are the usual suspects behind slow data access; profile with EXPLAIN and query logs.', tags: ['Scaling', 'performance'] },
  { q: 'Pagination with large OFFSET values is slow because:', opts: ['It uses an index perfectly', 'The DB still scans and discards all skipped rows', 'It locks the table', 'It disables the cache'], a: 1, e: 'OFFSET must walk past skipped rows; keyset ("seek") pagination using WHERE id > last_id scales far better.', tags: ['Scaling', 'pagination'] },
  { q: 'Before optimizing a query, you should first:', opts: ['Add random indexes', 'Measure: use EXPLAIN/metrics to find the actual bottleneck', 'Rewrite the whole schema', 'Switch databases'], a: 1, e: 'Profile first — EXPLAIN and real metrics reveal the true cost so you fix the actual bottleneck, not a guess.', tags: ['Scaling', 'optimization'] },
];
