import type { Seed } from './roadmap-build';

// Continents & Oceans — 10 levels × 8 questions, easiest → hardest.
export const continentsSeeds: Seed[] = [
  // ── Level 1 — The Seven Continents ──
  { q: 'How many continents are there on Earth?', opts: ['Five', 'Six', 'Seven', 'Eight'], a: 2, e: 'Most geographers recognize seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.', tags: ['continents', 'count'] },
  { q: 'Which continent is the largest by area?', opts: ['Africa', 'Asia', 'North America', 'Europe'], a: 1, e: 'Asia is the largest continent at about 44 million km², holding more than half the world\'s population.', tags: ['continents', 'sizes'] },
  { q: 'Which continent is the smallest by area?', opts: ['Australia', 'Europe', 'Antarctica', 'South America'], a: 0, e: 'Australia is the smallest continent at roughly 7.7 million km².', tags: ['continents', 'sizes'] },
  { q: 'On which continent is the Sahara Desert located?', opts: ['Asia', 'South America', 'Australia', 'Africa'], a: 3, e: 'The Sahara spans much of North Africa and is the world\'s largest hot desert.', tags: ['continents', 'africa'] },
  { q: 'Which continent is almost entirely covered by a thick sheet of ice?', opts: ['Europe', 'Antarctica', 'North America', 'Asia'], a: 1, e: 'Antarctica holds about 90% of the world\'s ice and is the coldest continent.', tags: ['continents', 'antarctica'] },
  { q: 'France, Germany, and Italy are countries on which continent?', opts: ['Asia', 'Africa', 'Europe', 'North America'], a: 2, e: 'These nations lie in Europe, the second-smallest continent.', tags: ['continents', 'europe'] },
  { q: 'The United States is located primarily on which continent?', opts: ['South America', 'Europe', 'Australia', 'North America'], a: 3, e: 'The contiguous US, along with Canada and Mexico, sits on North America.', tags: ['continents', 'north-america'] },
  { q: 'Brazil is located on which continent?', opts: ['South America', 'Africa', 'North America', 'Australia'], a: 0, e: 'Brazil is the largest country in South America by both area and population.', tags: ['continents', 'south-america'] },

  // ── Level 2 — The Five Oceans ──
  { q: 'Which is the largest ocean?', opts: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], a: 1, e: 'The Pacific is the largest and deepest ocean, covering about a third of Earth\'s surface.', tags: ['continents', 'oceans'] },
  { q: 'How many oceans are named in the modern five-ocean model?', opts: ['Two', 'Three', 'Four', 'Five'], a: 3, e: 'The modern model names the Pacific, Atlantic, Indian, Southern, and Arctic Oceans.', tags: ['continents', 'oceans'] },
  { q: 'Which ocean lies between the Americas to the west and Europe and Africa to the east?', opts: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], a: 0, e: 'The Atlantic separates the Americas from Europe and Africa.', tags: ['continents', 'oceans'] },
  { q: 'Which ocean surrounds the continent of Antarctica?', opts: ['Arctic', 'Indian', 'Southern', 'Atlantic'], a: 2, e: 'The Southern (Antarctic) Ocean encircles Antarctica, generally south of 60°S.', tags: ['continents', 'oceans'] },
  { q: 'Which is the smallest and shallowest ocean?', opts: ['Indian', 'Southern', 'Atlantic', 'Arctic'], a: 3, e: 'The Arctic Ocean is the smallest and shallowest, largely covered by sea ice.', tags: ['continents', 'oceans'] },
  { q: 'Which ocean lies between Africa, southern Asia, and Australia?', opts: ['Pacific', 'Indian', 'Southern', 'Atlantic'], a: 1, e: 'The Indian Ocean is the third-largest, bordered by Africa, Asia, and Australia.', tags: ['continents', 'oceans'] },
  { q: 'Which ocean covers the North Pole?', opts: ['Southern', 'Atlantic', 'Arctic', 'Pacific'], a: 2, e: 'The North Pole sits within the ice-covered Arctic Ocean.', tags: ['continents', 'oceans'] },
  { q: 'Which ocean is the second-largest by area?', opts: ['Atlantic', 'Indian', 'Arctic', 'Southern'], a: 0, e: 'The Atlantic is second only to the Pacific in size.', tags: ['continents', 'oceans'] },

  // ── Level 3 — Continent Sizes & Shapes ──
  { q: 'Which continent is the second-largest by area?', opts: ['North America', 'South America', 'Antarctica', 'Africa'], a: 3, e: 'Africa is second-largest at about 30 million km².', tags: ['continents', 'sizes'] },
  { q: 'Which continent is the third-largest by area?', opts: ['North America', 'South America', 'Antarctica', 'Europe'], a: 0, e: 'North America ranks third at roughly 24.7 million km².', tags: ['continents', 'sizes'] },
  { q: 'About what fraction of Earth\'s land area does Asia cover?', opts: ['About 10%', 'About 20%', 'About 30%', 'About 50%'], a: 2, e: 'Asia makes up roughly 30% of Earth\'s land area.', tags: ['continents', 'sizes'] },
  { q: 'Africa is roughly how many times the area of Europe?', opts: ['About the same', 'About 3 times', 'About 6 times', 'About 10 times'], a: 1, e: 'Africa (~30 million km²) is about three times the size of Europe (~10 million km²).', tags: ['continents', 'sizes'] },
  { q: 'Which continent\'s shape tapers southward to a point at Cape Horn?', opts: ['South America', 'Africa', 'Australia', 'North America'], a: 0, e: 'South America narrows to Cape Horn at its southern tip.', tags: ['continents', 'shapes'] },
  { q: 'Which continent is the smallest and is sometimes called an "island continent"?', opts: ['Europe', 'Antarctica', 'South America', 'Australia'], a: 3, e: 'Australia is the smallest continent and the largest landmass described as an island continent.', tags: ['continents', 'sizes'] },
  { q: 'Ranked fourth-largest and home to the Amazon rainforest, which continent is this?', opts: ['Antarctica', 'South America', 'Europe', 'Australia'], a: 1, e: 'South America is the fourth-largest continent at about 17.8 million km².', tags: ['continents', 'sizes'] },
  { q: 'Europe and Asia together form one continuous landmass called what?', opts: ['Afroeurasia', 'Australasia', 'Eurasia', 'Laurasia'], a: 2, e: 'Europe and Asia share a single landmass known as Eurasia.', tags: ['continents', 'shapes'] },

  // ── Level 4 — Where Continents Meet ──
  { q: 'The Isthmus of Panama connects North America to which continent?', opts: ['South America', 'Africa', 'Asia', 'Australia'], a: 0, e: 'The narrow Isthmus of Panama joins North and South America.', tags: ['continents', 'borders'] },
  { q: 'The Suez Canal separates Africa from which continent?', opts: ['Europe', 'Australia', 'Asia', 'North America'], a: 2, e: 'The Suez Canal cuts across the isthmus linking Africa and Asia.', tags: ['continents', 'borders'] },
  { q: 'The Ural Mountains are commonly taken as the boundary between Europe and which continent?', opts: ['Africa', 'Asia', 'North America', 'Antarctica'], a: 1, e: 'The Ural Mountains traditionally divide Europe from Asia.', tags: ['continents', 'borders'] },
  { q: 'The Bering Strait separates Asia from which continent?', opts: ['South America', 'Europe', 'Australia', 'North America'], a: 3, e: 'The Bering Strait lies between easternmost Asia (Russia) and North America (Alaska).', tags: ['continents', 'borders'] },
  { q: 'The Strait of Gibraltar separates Europe from which continent?', opts: ['Asia', 'North America', 'Africa', 'South America'], a: 2, e: 'The Strait of Gibraltar is a narrow passage between Spain (Europe) and Morocco (Africa).', tags: ['continents', 'borders'] },
  { q: 'During the last Ice Age, a land bridge called Beringia connected Asia to which continent?', opts: ['North America', 'South America', 'Australia', 'Europe'], a: 0, e: 'Beringia spanned the present Bering Strait, linking Asia and North America.', tags: ['continents', 'borders'] },
  { q: 'The Bosphorus strait, dividing Europe from Asia, runs through which city?', opts: ['Athens', 'Cairo', 'Baku', 'Istanbul'], a: 3, e: 'The Bosphorus splits Istanbul between the European and Asian continents.', tags: ['continents', 'borders'] },
  { q: 'The Sinai Peninsula, a land bridge between Africa and Asia, belongs to which country?', opts: ['Israel', 'Egypt', 'Jordan', 'Saudi Arabia'], a: 1, e: 'Egypt\'s Sinai Peninsula forms the land bridge connecting Africa and Asia.', tags: ['continents', 'borders'] },

  // ── Level 5 — Islands & Archipelagos ──
  { q: 'What is the world\'s largest island?', opts: ['New Guinea', 'Borneo', 'Greenland', 'Madagascar'], a: 2, e: 'Greenland is the world\'s largest island; Australia is classed as a continent, not an island.', tags: ['continents', 'islands'] },
  { q: 'The archipelago nation of Indonesia lies mainly between which two oceans?', opts: ['Atlantic and Indian', 'Arctic and Pacific', 'Atlantic and Pacific', 'Indian and Pacific'], a: 3, e: 'Indonesia straddles the boundary between the Indian and Pacific Oceans.', tags: ['continents', 'islands'] },
  { q: 'Madagascar, the world\'s fourth-largest island, lies off the coast of which continent?', opts: ['Asia', 'Africa', 'Australia', 'South America'], a: 1, e: 'Madagascar sits in the Indian Ocean off southeastern Africa.', tags: ['continents', 'islands'] },
  { q: 'Which country is made up of over 17,000 islands, forming the world\'s largest archipelago?', opts: ['Indonesia', 'Philippines', 'Japan', 'Maldives'], a: 0, e: 'Indonesia comprises more than 17,000 islands, the world\'s largest archipelago.', tags: ['continents', 'islands'] },
  { q: 'The British Isles lie off the northwest coast of which continent?', opts: ['Asia', 'Africa', 'North America', 'Europe'], a: 3, e: 'The British Isles sit off the northwestern edge of Europe.', tags: ['continents', 'islands'] },
  { q: 'The island of New Guinea is generally associated with which region?', opts: ['Asia', 'Africa', 'Oceania', 'Antarctica'], a: 2, e: 'New Guinea, the world\'s second-largest island, is part of Oceania near Australia.', tags: ['continents', 'islands'] },
  { q: 'The Hawaiian Islands lie in which ocean?', opts: ['Pacific', 'Atlantic', 'Indian', 'Arctic'], a: 0, e: 'Hawaii is a volcanic archipelago in the central Pacific Ocean.', tags: ['continents', 'islands'] },
  { q: 'The islands of Cuba and Jamaica lie between North and South America in which body of water?', opts: ['Gulf of Mexico', 'Caribbean Sea', 'Sargasso Sea', 'Coral Sea'], a: 1, e: 'The Greater and Lesser Antilles dot the Caribbean Sea.', tags: ['continents', 'islands'] },

  // ── Level 6 — Seas, Gulfs & Bays ──
  { q: 'The Mediterranean Sea is bordered by Europe, Africa, and which other continent?', opts: ['Australia', 'Asia', 'North America', 'Antarctica'], a: 1, e: 'The Mediterranean touches Europe, Africa, and Asia.', tags: ['continents', 'seas'] },
  { q: 'Which is the largest bay in the world by area?', opts: ['Bay of Bengal', 'Hudson Bay', 'Gulf of Mexico', 'Persian Gulf'], a: 0, e: 'The Bay of Bengal, in the northeastern Indian Ocean, is the world\'s largest bay by area.', tags: ['continents', 'seas'] },
  { q: 'The Red Sea separates Africa from which peninsula?', opts: ['Iberian Peninsula', 'Balkan Peninsula', 'Indian subcontinent', 'Arabian Peninsula'], a: 3, e: 'The Red Sea lies between northeastern Africa and the Arabian Peninsula.', tags: ['continents', 'seas'] },
  { q: 'The Gulf of Mexico is bordered by the US, Mexico, and which island nation to the southeast?', opts: ['Jamaica', 'Haiti', 'Cuba', 'Bahamas'], a: 2, e: 'Cuba lies at the southeastern edge of the Gulf of Mexico.', tags: ['continents', 'seas'] },
  { q: 'The Caspian Sea, the world\'s largest inland body of water, is technically what?', opts: ['A lake', 'An ocean', 'A gulf', 'A strait'], a: 0, e: 'Despite its name, the Caspian Sea is the world\'s largest lake by area.', tags: ['continents', 'seas'] },
  { q: 'The Black Sea connects to the Mediterranean through straits controlled by which country?', opts: ['Greece', 'Turkey', 'Ukraine', 'Romania'], a: 1, e: 'The Bosphorus and Dardanelles straits in Turkey link the Black Sea to the Mediterranean.', tags: ['continents', 'seas'] },
  { q: 'The Persian Gulf lies between the Arabian Peninsula and which country?', opts: ['Iraq', 'Oman', 'Iran', 'Yemen'], a: 2, e: 'The Persian Gulf separates the Arabian Peninsula from Iran.', tags: ['continents', 'seas'] },
  { q: 'The Dead Sea, Earth\'s lowest exposed land, borders Jordan and which other place?', opts: ['Egypt', 'Lebanon', 'Syria', 'Israel'], a: 3, e: 'The Dead Sea\'s shores lie in Jordan, Israel, and the West Bank, about 430 m below sea level.', tags: ['continents', 'seas'] },

  // ── Level 7 — Hemispheres & the Equator ──
  { q: 'The Equator passes through all of these continents EXCEPT which one?', opts: ['South America', 'Africa', 'Asia', 'Europe'], a: 3, e: 'The Equator crosses South America, Africa, and Asia (via Indonesia) but not Europe.', tags: ['continents', 'hemispheres'] },
  { q: 'Which continent lies entirely within the Southern Hemisphere?', opts: ['Africa', 'Asia', 'Antarctica', 'North America'], a: 2, e: 'Antarctica lies wholly in the Southern Hemisphere, surrounding the South Pole.', tags: ['continents', 'hemispheres'] },
  { q: 'Which of these continents lies entirely within the Northern Hemisphere?', opts: ['Europe', 'Africa', 'South America', 'Australia'], a: 0, e: 'Europe lies completely north of the Equator.', tags: ['continents', 'hemispheres'] },
  { q: 'The Equator passes through which of these African countries?', opts: ['Egypt', 'Kenya', 'South Africa', 'Morocco'], a: 1, e: 'The Equator crosses Kenya, passing near Lake Victoria.', tags: ['continents', 'hemispheres'] },
  { q: 'Which line of latitude marks 0 degrees?', opts: ['Prime Meridian', 'Tropic of Cancer', 'Equator', 'Arctic Circle'], a: 2, e: 'The Equator is the line of 0° latitude, dividing the Northern and Southern Hemispheres.', tags: ['continents', 'hemispheres'] },
  { q: 'Most of the world\'s land and population lies in which hemisphere?', opts: ['Southern', 'Eastern', 'Western', 'Northern'], a: 3, e: 'About 90% of humans live in the Northern Hemisphere, which contains most of Earth\'s land.', tags: ['continents', 'hemispheres'] },
  { q: 'Which continent is crossed by both the Equator and the Prime Meridian?', opts: ['South America', 'Africa', 'Asia', 'Europe'], a: 1, e: 'Only Africa is crossed by both the Equator and the Prime Meridian, near the Gulf of Guinea.', tags: ['continents', 'hemispheres'] },
  { q: 'The imaginary line at 0 degrees longitude is called the?', opts: ['Prime Meridian', 'Equator', 'International Date Line', 'Tropic of Capricorn'], a: 0, e: 'The Prime Meridian (0° longitude) passes through Greenwich, England.', tags: ['continents', 'hemispheres'] },

  // ── Level 8 — Continental Extremes ──
  { q: 'What is the highest point on Earth above sea level?', opts: ['Mount Everest', 'K2', 'Denali', 'Aconcagua'], a: 0, e: 'Mount Everest in the Himalayas (Asia) reaches 8,849 m, Earth\'s highest point above sea level.', tags: ['continents', 'extremes'] },
  { q: 'The highest mountain in Africa is which peak?', opts: ['Mount Kenya', 'Kilimanjaro', 'Mount Elgon', 'Ras Dashen'], a: 1, e: 'Mount Kilimanjaro in Tanzania rises to about 5,895 m, Africa\'s highest peak.', tags: ['continents', 'extremes'] },
  { q: 'The highest peak in South America is which mountain?', opts: ['Chimborazo', 'Huascarán', 'Aconcagua', 'Cotopaxi'], a: 2, e: 'Aconcagua in Argentina, at 6,961 m, is the highest mountain outside Asia.', tags: ['continents', 'extremes'] },
  { q: 'The lowest exposed land on Earth is the shore of which feature?', opts: ['Death Valley', 'Lake Assal', 'Caspian Depression', 'Dead Sea'], a: 3, e: 'The Dead Sea shore lies about 430 m below sea level, the lowest exposed land on Earth.', tags: ['continents', 'extremes'] },
  { q: 'The highest point in North America is which peak?', opts: ['Mount Logan', 'Denali', 'Pico de Orizaba', 'Mount Whitney'], a: 1, e: 'Denali in Alaska reaches 6,190 m, North America\'s highest peak.', tags: ['continents', 'extremes'] },
  { q: 'The highest mountain in Antarctica is which peak?', opts: ['Vinson Massif', 'Mount Erebus', 'Mount Kirkpatrick', 'Mount Tyree'], a: 0, e: 'The Vinson Massif rises to about 4,892 m, Antarctica\'s highest point.', tags: ['continents', 'extremes'] },
  { q: 'The highest peak in Europe, by common definition, is which mountain?', opts: ['Mont Blanc', 'Matterhorn', 'Dufourspitze', 'Mount Elbrus'], a: 3, e: 'Mount Elbrus in Russia\'s Caucasus, at 5,642 m, is usually cited as Europe\'s highest peak.', tags: ['continents', 'extremes'] },
  { q: 'The highest mountain on mainland Australia is which peak?', opts: ['Mount Bogong', 'Mount Townsend', 'Mount Kosciuszko', 'Mount Ossa'], a: 2, e: 'Mount Kosciuszko, at 2,228 m, is mainland Australia\'s highest peak.', tags: ['continents', 'extremes'] },

  // ── Level 9 — Ocean Depths & Features ──
  { q: 'The deepest point in Earth\'s oceans lies in which trench?', opts: ['Tonga Trench', 'Java Trench', 'Mariana Trench', 'Puerto Rico Trench'], a: 2, e: 'The Challenger Deep in the Mariana Trench reaches about 10,935 m below sea level.', tags: ['continents', 'ocean-depths'] },
  { q: 'The Mariana Trench is located in which ocean?', opts: ['Pacific', 'Indian', 'Atlantic', 'Southern'], a: 0, e: 'The Mariana Trench lies in the western Pacific, east of the Mariana Islands.', tags: ['continents', 'ocean-depths'] },
  { q: 'The Mid-Atlantic Ridge is an example of which kind of feature?', opts: ['A deep-sea trench', 'An ocean current', 'A coral atoll', 'A mid-ocean ridge'], a: 3, e: 'The Mid-Atlantic Ridge is a mid-ocean ridge where tectonic plates spread apart.', tags: ['continents', 'ocean-depths'] },
  { q: 'The warm current that moderates Western Europe\'s climate is the?', opts: ['Humboldt Current', 'Gulf Stream', 'Kuroshio Current', 'Canary Current'], a: 1, e: 'The Gulf Stream carries warm water from the Gulf of Mexico toward Europe.', tags: ['continents', 'ocean-currents'] },
  { q: 'Approximately how deep is the Challenger Deep?', opts: ['About 11 km', 'About 6 km', 'About 20 km', 'About 3 km'], a: 0, e: 'The Challenger Deep descends nearly 11 km (about 10,935 m).', tags: ['continents', 'ocean-depths'] },
  { q: 'The cold, fish-rich current flowing north along South America\'s west coast is the?', opts: ['Gulf Stream', 'Agulhas Current', 'Humboldt Current', 'Benguela Current'], a: 2, e: 'The Humboldt (Peru) Current flows northward along Chile and Peru.', tags: ['continents', 'ocean-currents'] },
  { q: 'Which ocean has the greatest average depth?', opts: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], a: 1, e: 'The Pacific is both the largest and, on average, the deepest ocean.', tags: ['continents', 'ocean-depths'] },
  { q: 'A tsunami is most directly caused by what?', opts: ['Strong tides', 'Hurricanes', 'High winds', 'Undersea earthquakes'], a: 3, e: 'Most tsunamis are triggered by undersea earthquakes that displace large volumes of water.', tags: ['continents', 'ocean-depths'] },

  // ── Level 10 — Continents & Oceans Mastery ──
  { q: 'The Ninetyeast Ridge, one of the longest straight underwater ridges, lies in which ocean?', opts: ['Pacific', 'Indian', 'Atlantic', 'Southern'], a: 1, e: 'The Ninetyeast Ridge runs north–south near 90°E longitude in the Indian Ocean.', tags: ['continents', 'mastery'] },
  { q: 'The Bentley Subglacial Trench, the lowest land point not under ocean, lies beneath which continent?', opts: ['Greenland', 'Asia', 'Antarctica', 'South America'], a: 2, e: 'The Bentley Subglacial Trench in Antarctica reaches about 2,540 m below sea level under the ice.', tags: ['continents', 'mastery'] },
  { q: 'Which strait connects the Red Sea to the Gulf of Aden between Africa and Arabia?', opts: ['Strait of Hormuz', 'Strait of Malacca', 'Strait of Gibraltar', 'Bab-el-Mandeb'], a: 3, e: 'The Bab-el-Mandeb strait links the Red Sea with the Gulf of Aden and the Indian Ocean.', tags: ['continents', 'mastery'] },
  { q: 'Because of the equatorial bulge, which summit is the point on Earth\'s surface farthest from its center?', opts: ['Chimborazo', 'Mount Everest', 'Aconcagua', 'Denali'], a: 0, e: 'Ecuador\'s Chimborazo sits on the equatorial bulge, making its summit the farthest point from Earth\'s center.', tags: ['continents', 'mastery'] },
  { q: 'Zealandia, the largely submerged "eighth continent," lies mostly beneath which ocean?', opts: ['Indian', 'Atlantic', 'Southern', 'Pacific'], a: 3, e: 'Zealandia is a mostly submerged continent in the southwestern Pacific, with New Zealand as its main above-water land.', tags: ['continents', 'mastery'] },
  { q: 'The Denmark Strait cataract, the world\'s largest underwater waterfall, lies between Greenland and which island?', opts: ['Svalbard', 'Iceland', 'Faroe Islands', 'Great Britain'], a: 1, e: 'A massive density-driven underwater cascade flows through the Denmark Strait between Greenland and Iceland.', tags: ['continents', 'mastery'] },
  { q: 'The Sargasso Sea, unique for having no land borders, sits within which ocean?', opts: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], a: 0, e: 'The Sargasso Sea lies within the North Atlantic Gyre, bounded by ocean currents rather than coastlines.', tags: ['continents', 'mastery'] },
  { q: 'Which continent has the highest average elevation?', opts: ['Asia', 'South America', 'Antarctica', 'Africa'], a: 2, e: 'Antarctica has the highest average elevation of any continent, largely because of its thick ice sheet.', tags: ['continents', 'mastery'] },
];
