// Starting Hands & Ranges roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const startingHandsSeeds: Seed[] = [
  // ── Level 1 — Premium hands and hand notation ──
  { q: 'In poker hand notation, what does "AKs" mean?', opts: ['Ace-King suited', 'Ace-King offsuit', 'Two aces and a king', 'Ace-King on the board'], a: 0, e: 'The lowercase "s" means suited, so "AKs" is an Ace and King of the same suit.', tags: ['Poker', 'Notation'] },
  { q: 'In the notation "72o", what does the "o" stand for?', opts: ['Offsuit', 'Open', 'Outs', 'Overpair'], a: 0, e: 'The "o" marks the two cards as offsuit, meaning they are of different suits.', tags: ['Poker', 'Notation'] },
  { q: 'Which is the strongest possible starting hand in Texas Hold\'em?', opts: ['Pocket aces (AA)', 'Ace-King suited', 'Pocket kings', 'Ace-Queen suited'], a: 0, e: 'Pocket aces are the best starting hand, a favorite preflop against any other holding.', tags: ['Poker', 'Premium hands'] },
  { q: 'How is a pocket pair of queens written in shorthand?', opts: ['QQ', 'QJ', 'Qs', 'Q2'], a: 0, e: 'A pocket pair is written as the rank doubled, so two queens are "QQ".', tags: ['Poker', 'Notation'] },
  { q: 'The starting hand Ace-King is popularly nicknamed what?', opts: ['Big Slick', 'The Hammer', 'Cowboys', 'Snowmen'], a: 0, e: 'Ace-King is called "Big Slick"; "Cowboys" is KK, "Snowmen" is 88, and "The Hammer" is 72.', tags: ['Poker', 'Nicknames'] },
  { q: 'How many distinct card combinations does any single pocket pair have?', opts: ['6', '4', '12', '2'], a: 0, e: 'Each pair has 6 combinations (4 cards choose 2), unlike 4 suited and 12 offsuit combos for non-pairs.', tags: ['Poker', 'Combinatorics'] },
  { q: 'Which hand is widely considered the worst starting hand in Hold\'em?', opts: ['7-2 offsuit', '3-2 offsuit', 'Pocket twos', '7-2 suited'], a: 0, e: '7-2 offsuit is the classic worst hand: no straight potential, no flush, and low card strength.', tags: ['Poker', 'Weak hands'] },
  { q: 'What does it mean for two hole cards to be "suited"?', opts: ['They share the same suit', 'They are consecutive ranks', 'They are both face cards', 'They form a pair'], a: 0, e: 'Suited simply means both cards are of the same suit, giving added flush potential.', tags: ['Poker', 'Notation'] },

  // ── Level 2 — Hand categories ──
  { q: '"Suited connectors" are two cards that are...', opts: ['Same suit and consecutive rank', 'The same rank', 'Both aces', 'Any two suited cards'], a: 0, e: 'Suited connectors are the same suit and adjacent in rank, like 8-7 of hearts.', tags: ['Poker', 'Categories'] },
  { q: 'Which of these is an example of a suited connector?', opts: ['8-7 suited', 'A-K offsuit', 'K-9 suited', 'Pocket fives'], a: 0, e: '8-7 suited is same-suit and consecutive; K-9 is suited but gapped, not a true connector.', tags: ['Poker', 'Categories'] },
  { q: 'The "broadway" cards are which ranks?', opts: ['Ten through Ace', 'Two through Five', 'Any pair', 'Suited cards only'], a: 0, e: 'Broadway cards are Ten, Jack, Queen, King, and Ace, the five highest ranks.', tags: ['Poker', 'Categories'] },
  { q: 'Which hand is a "broadway" holding (two broadway cards)?', opts: ['K-Q', '9-8', 'Pocket sixes', 'A-2'], a: 0, e: 'K-Q is made of two broadway cards; both are in the Ten-through-Ace group.', tags: ['Poker', 'Categories'] },
  { q: 'A "suited ace" is an ace paired with...', opts: ['Another card of the same suit', 'Another ace', 'A face card only', 'A card on the board'], a: 0, e: 'A suited ace is an ace with a second card of the same suit, like A-5 of spades.', tags: ['Poker', 'Categories'] },
  { q: 'Why are suited aces valued as starting hands?', opts: ['They can make the nut (best) flush', 'They are always pairs', 'They cannot be beaten', 'They guarantee a straight'], a: 0, e: 'Holding the ace of a suit means any flush you make is the nut flush, the strongest possible.', tags: ['Poker', 'Categories'] },
  { q: 'Small pocket pairs like 2-2 through 5-5 are often played hoping to...', opts: ['Flop a set (three of a kind)', 'Make a flush', 'Make a straight', 'Hit top pair'], a: 0, e: 'Small pairs mainly aim to flop a set, a well-disguised, powerful hand worth chasing cheaply.', tags: ['Poker', 'Categories'] },
  { q: 'What does "pocket pair" mean?', opts: ['Two hole cards of the same rank', 'Two suited cards', 'Two connected cards', 'Two broadway cards'], a: 0, e: 'A pocket pair is two hole cards of matching rank, such as 9-9, dealt to a single player.', tags: ['Poker', 'Categories'] },

  // ── Level 3 — Preflop hand selection by position ──
  { q: 'Which position acts last on every postflop street?', opts: ['The button', 'Under the gun', 'Small blind', 'Big blind'], a: 0, e: 'The button acts last after the flop, the most powerful positional advantage at the table.', tags: ['Poker', 'Position'] },
  { q: 'From "under the gun" (first to act preflop), you should generally play...', opts: ['A tight, strong range', 'Any two cards', 'Only suited hands', 'All pocket pairs'], a: 0, e: 'Acting first with many players behind, under the gun demands a tight range of strong hands.', tags: ['Poker', 'Position'] },
  { q: 'As you move from early to late position, your opening range should generally...', opts: ['Get wider', 'Get tighter', 'Stay identical', 'Include only pairs'], a: 0, e: 'Fewer players remain to act in late position, so you can profitably open a wider range.', tags: ['Poker', 'Position'] },
  { q: 'Which hand is a comfortable open-raise even from early position?', opts: ['A-K', '7-2 offsuit', 'J-4 offsuit', '9-3 suited'], a: 0, e: 'A-K is a premium hand strong enough to open from any position, including early seats.', tags: ['Poker', 'Position'] },
  { q: 'Speculative hands like small suited connectors are best opened from...', opts: ['Late position', 'Under the gun', 'The big blind only', 'Any position equally'], a: 0, e: 'Small suited connectors play best in late position, where you act last and can realize equity.', tags: ['Poker', 'Position'] },
  { q: '"Positional advantage" means being in position lets you...', opts: ['Act after your opponent with more information', 'See an extra card', 'Bet larger blinds', 'Skip a betting street'], a: 0, e: 'In position, you act after your opponent each street, using their action as information.', tags: ['Poker', 'Position'] },
  { q: 'Why is the small blind generally a difficult position to play?', opts: ['You act first postflop and are out of position', 'You must always fold', 'You have the best pot odds', 'You see the flop for free'], a: 0, e: 'The small blind acts first on every postflop street, a lasting out-of-position disadvantage.', tags: ['Poker', 'Position'] },
  { q: 'Which position typically has the widest opening range?', opts: ['The button', 'Under the gun', 'Middle position', 'Lojack'], a: 0, e: 'The button, acting last and with only two blinds behind, can open the widest range of hands.', tags: ['Poker', 'Position'] },

  // ── Level 4 — Ranges and 3-betting ──
  { q: 'In poker, a player\'s "range" refers to...', opts: ['All the hands they could have in a spot', 'One specific hand', 'The size of the pot', 'The blind levels'], a: 0, e: 'A range is the full set of hands a player might hold given their actions, not one exact hand.', tags: ['Poker', 'Ranges'] },
  { q: 'Preflop, "3-betting" means...', opts: ['Making the third bet, i.e. re-raising a raise', 'Betting three times postflop', 'Betting the third community card', 'Betting three times the pot'], a: 0, e: 'The blind is bet one, the open-raise is bet two, and re-raising that is the 3-bet.', tags: ['Poker', '3-betting'] },
  { q: 'A "value 3-bet" is made with...', opts: ['A strong hand wanting more money in the pot', 'A weak hand as a bluff', 'Any random hand', 'Only pocket aces'], a: 0, e: 'A value 3-bet uses a strong hand that welcomes a call, building the pot when you are ahead.', tags: ['Poker', '3-betting'] },
  { q: 'A "3-bet bluff" is often made with hands like...', opts: ['Suited aces that hold a useful blocker', 'Pocket aces', 'Random offsuit trash', 'A made straight'], a: 0, e: 'Suited aces make good 3-bet bluffs: the ace blocks strong hands and the suit adds playability.', tags: ['Poker', '3-betting'] },
  { q: 'A "polarized" 3-betting range consists mostly of...', opts: ['Strong value hands and bluffs, with little in between', 'Only medium-strength hands', 'Every suited hand', 'Only pocket pairs'], a: 0, e: 'A polarized range splits into strong value hands and bluffs, skipping marginal calling hands.', tags: ['Poker', 'Ranges'] },
  { q: 'A "linear" (or merged) 3-betting range consists of...', opts: ['The strongest hands grouped together', 'Bluffs only', 'Purely random hands', 'Offsuit hands only'], a: 0, e: 'A linear range 3-bets your very best hands as a block, common against loose or weak openers.', tags: ['Poker', 'Ranges'] },
  { q: '"Range vs range" thinking means evaluating...', opts: ['How your whole range fares against your opponent\'s whole range', 'Only your two exact cards', 'The pot odds alone', 'Stack sizes only'], a: 0, e: 'Strong players compare entire ranges, not single hands, to plan bets and find the best line.', tags: ['Poker', 'Ranges'] },
  { q: 'If a hand is a profitable call but too weak to 3-bet for value, and you do not want to bluff, you should usually...', opts: ['Flat call (just call the raise)', 'Always fold it', 'Always 3-bet it', 'Move all-in'], a: 0, e: 'Such hands go in your calling range: flatting keeps weaker hands in and controls the pot size.', tags: ['Poker', 'Ranges'] },

  // ── Level 5 — Adjusting ranges to opponents, stacks & format ──
  { q: 'Against a very tight player who only raises premium hands, you should...', opts: ['Fold marginal hands and avoid light 3-bets', 'Call with almost anything', '3-bet bluff constantly', 'Never fold'], a: 0, e: 'A tight opener rarely has a weak hand, so respect their range and drop your speculative holdings.', tags: ['Poker', 'Adjusting'] },
  { q: 'Against a loose player who opens far too many weak hands, you should...', opts: ['Widen your value 3-betting and calling range', 'Tighten drastically', 'Fold everything', 'Only ever flat call'], a: 0, e: 'A loose opener has a weak range, so you can 3-bet more hands for value and call wider profitably.', tags: ['Poker', 'Adjusting'] },
  { q: 'Short-stacked (around 15-20 big blinds), which hands rise in relative value?', opts: ['High-card strength hands like big aces and big pairs', 'Small suited connectors', 'Low offsuit hands', 'Deep implied-odds speculative hands'], a: 0, e: 'Short stacks favor raw high-card strength for shoving; speculative hands lose value without depth.', tags: ['Poker', 'Stack depth'] },
  { q: 'Deep-stacked (200bb or more), which hand type gains value?', opts: ['Suited connectors and suited aces', 'Offsuit high cards', 'Small offsuit hands', 'Weak pairs only'], a: 0, e: 'Deep stacks reward suited connectors and suited aces because they can win huge pots when they hit.', tags: ['Poker', 'Stack depth'] },
  { q: 'Speculative hands like small suited connectors rely mostly on...', opts: ['Implied odds (winning a big pot on the times they connect)', 'Pot odds alone', 'Preflop fold equity', 'Card removal'], a: 0, e: 'They flop strong hands rarely, so they need deep stacks and implied odds to be worth playing.', tags: ['Poker', 'Stack depth'] },
  { q: 'In a tournament near the money bubble, ICM pressure generally makes you...', opts: ['Play tighter to avoid busting before cashing', 'Play much looser', 'Ignore stack sizes', 'Call all-ins freely'], a: 0, e: 'ICM values survival, so near the bubble you tighten up and avoid marginal all-in confrontations.', tags: ['Poker', 'Format'] },
  { q: 'Against opponents who fold far too often to 3-bets, you should...', opts: ['3-bet bluff more frequently', '3-bet only for value', 'Stop 3-betting entirely', 'Flat call everything'], a: 0, e: 'If they overfold, 3-bet bluffing prints chips, so add more light 3-bets to attack their weakness.', tags: ['Poker', 'Adjusting'] },
  { q: 'Because cash games and tournaments differ in stack depth and blind pressure, a strong player...', opts: ['Adjusts starting-hand ranges to the stack depth and format', 'Uses one fixed range everywhere', 'Ignores the format', 'Plays only premium hands always'], a: 0, e: 'Optimal ranges shift with stack depth, antes, and ICM, so good players tailor selection to the game.', tags: ['Poker', 'Format'] },
];
