// JavaScript roadmap questions — set B (100). A second question per level theme,
// distinct from set A. Combined with set A (lib/roadmap-questions.ts) this gives
// 8 questions per level, so each 5-level checkpoint has a full 40-question test.
// 25 levels × 4, easiest → hardest. See lib/roadmap.ts for the level titles.

import type { Seed } from './roadmap-build';

export const jsSeedsB: Seed[] = [
  // ── Level 1 — Values & Math ────────────────────────────────────────────
  { q: 'What does this return?\n\n```js\nMath.floor(-4.2);\n```', opts: ['-5', '-4', '-4.2', '4'], a: 0, e: 'Math.floor returns the largest integer less than or equal to its argument, which for -4.2 is -5. -4 is what truncation gives (Math.trunc(-4.2)), because dropping the decimal part moves a negative number up rather than down.', intro: 'floor always moves one fixed direction along the number line. Settle that direction before applying it to a negative value.', tags: ['Numbers', 'Math'] },
  { q: 'What is the result, including its type?\n\n```js\n(7 / 2).toFixed(1);\n```', opts: ['3.5', '"3.5"', '"3"', '4'], a: 1, e: '7 / 2 is 3.5, and toFixed(1) formats it as text, so the result is the string "3.5" with quotes. The bare number 3.5 is what the division alone gives; because toFixed returns a string, (7 / 2).toFixed(1) + 1 is "3.51", not 4.5.', intro: 'toFixed is a formatting method. Ask what kind of value a formatter hands back, not only which digits it shows.', tags: ['Numbers'] },
  { q: 'JavaScript rounds a half toward positive infinity. What does this return?\n\n```js\nMath.round(-2.5);\n```', opts: ['-3', '-2', '-2.5', '2'], a: 1, e: 'For an exact half, Math.round goes toward positive infinity, so -2.5 becomes -2. -3 is what "round half away from zero" would give, the rule many other languages use; a value that is not a tie still rounds normally, so Math.round(-2.6) is -3.', intro: 'Other languages round a half away from zero. Check whether the rule this question states agrees with that habit for a negative number.', tags: ['Numbers', 'Math'] },
  { q: 'What is the result?\n\n```js\ntypeof NaN;\n```', opts: ['"NaN"', '"number"', '"undefined"', '"object"'], a: 1, e: 'NaN is the IEEE-754 "not a number" value that lives inside JavaScript\'s single numeric type, so typeof reports "number". "NaN" is not one of typeof\'s result strings, and "object" is what typeof null returns. Since NaN !== NaN, detect it with Number.isNaN rather than ===.', intro: 'The name says "not a number", but a value\'s name and its type are decided separately. Recall the fixed set of strings typeof can return.', tags: ['typeof', 'Gotchas'] },

  // ── Level 2 — Strings ──────────────────────────────────────────────────
  { q: 'What does charAt return for an index equal to the string length?\n\n```js\n"hello".charAt(5);\n```', opts: ['""', 'undefined', '"o"', 'Error'], a: 0, e: 'charAt always returns a string, and for an index outside the string that string is empty. The last index of "hello" is 4, so index 5 is past the end. Bracket access behaves differently: "hello"[5] is undefined, which is why undefined is offered here.', intro: 'A five-character string has no index 5. Recall what charAt is documented to give back for an index it cannot find.', tags: ['Strings', 'Methods'] },
  { q: 'The second argument sets the starting position. What is the result?\n\n```js\n"ababa".indexOf("b", 2);\n```', opts: ['1', '3', '2', '-1'], a: 1, e: 'The search starts at index 2, so the "b" at index 1 is skipped and the next "b", at index 3, is the match. indexOf always reports a position in the whole string, never an offset from the start position, so 1 is wrong on both readings; -1 would mean no "b" exists from index 2 onward.', intro: 'The search begins at index 2, but ask what the number it hands back is counted from.', tags: ['Strings', 'Methods'] },
  { q: 'What does this return?\n\n```js\n"  a b  ".trim();\n```', opts: ['"ab"', '"a b"', '"a b  "', '"  a b"'], a: 1, e: 'trim removes whitespace from both ends and returns "a b"; the space between a and b is interior and stays. "ab" would require replacing whitespace everywhere, while "a b  " and "  a b" are exactly what trimStart and trimEnd give.', intro: 'The string has whitespace in three places. Decide which of them trim is concerned with.', tags: ['Strings', 'Methods'] },
  { q: 'What is returned after repeating and slicing?\n\n```js\n"ab".repeat(3).slice(1, 5);\n```', opts: ['"baba"', '"abab"', '"ababab"', '"ba"'], a: 0, e: 'repeat(3) builds "ababab"; slice(1, 5) then takes indexes 1, 2, 3 and 4, giving "baba". "abab" is slice(0, 4), which is what counting the first character as index 1 produces, and "ababab" is the string before any slicing.', intro: 'Write out the repeated string first, then number its characters from 0 before taking the slice.', tags: ['Strings', 'Methods'] },

  // ── Level 3 — Booleans & Comparison ────────────────────────────────────
  { q: 'What does this return?\n\n```js\n2 != "2";\n```', opts: ['true', 'false', 'undefined', 'Error'], a: 1, e: 'Loose != coerces "2" to 2, so they are equal and != is false.', tags: ['Comparison', 'Coercion'] },
  { q: 'What does this return?\n\n```js\nnull == undefined;\n```', opts: ['true', 'false', 'Error', 'undefined'], a: 0, e: 'Loose equality has a special rule: null and undefined are equal to each other and to nothing else, so this is true. Strict equality does not apply that rule, so null === undefined is false. This is why x != null is a common single check that covers both missing-value cases.', intro: 'Ask whether == treats the two ways of saying \'no value\' as the same, and whether === would answer differently.', tags: ['Comparison'] },
  { q: 'What is the result?\n\n```js\n"10" < "2";\n```', opts: ['true', 'false', '0', 'TypeError'], a: 0, e: 'With strings on both sides, < compares characters from the left: "1" comes before "2", so the answer is decided at the first character and the 0 is never read. Reading them as numbers would give false, and that is what happens once one side is a number: 10 < "2" coerces the string and is false.', intro: 'Both operands are quoted. Decide whether < reads them as text or converts them to numbers first.', tags: ['Comparison', 'Strings'] },
  { q: 'What is the result?\n\n```js\n10 >= "10";\n```', opts: ['true', 'false', 'undefined', 'TypeError'], a: 0, e: 'When one side is a number, a relational operator converts the string operand to a number, so this compares 10 with 10 and >= is true for equal values. No error is raised, unlike languages that refuse mixed-type comparison; a string that cannot convert becomes NaN and makes every comparison false, so 10 >= "ten" is false.', intro: 'One side is a number and the other is text. Decide what a relational operator does with that mismatch before it compares.', tags: ['Comparison'] },

  // ── Level 4 — Arrays: Basics ───────────────────────────────────────────
  { q: 'What does a negative start index select?\n\n```js\n[1, 2, 3].slice(-2);\n```', opts: ['[2, 3]', '[1, 2]', '[1]', '[3, 2]'], a: 0, e: 'A negative start counts back from the end, so -2 begins at the second-to-last element and slice reads forward to the end: [2, 3]. It does not read backwards, so [3, 2] never occurs, and slice copies rather than mutates, leaving [1, 2, 3] intact.', intro: 'The start index is negative. Decide where that puts the starting position, then which direction slice reads from there.', tags: ['Arrays', 'Methods'] },
  { q: 'What are a and b after this runs?\n\n```js\nconst a = [1, 2];\nconst b = a.concat(3);\n[a, b];\n```', opts: ['[[1, 2], [1, 2, 3]]', '[[1, 2, 3], [1, 2, 3]]', '[[1, 2], [3]]', '[1, 2, 3]'], a: 0, e: 'concat copies a, appends the argument and returns the copy, so b is [1, 2, 3] while a is still [1, 2]. A method that changes the array in place and hands the same array back, such as sort or reverse, would leave both names showing the change, which is the [[1, 2, 3], [1, 2, 3]] option.', intro: 'Decide whether concat changes the array it was called on or builds a separate one, then read off both names.', tags: ['Arrays', 'Methods'] },
  { q: 'What are a and b after this runs?\n\n```js\nconst a = [1, 2, 3];\nconst b = a.reverse();\n[a, b];\n```', opts: ['[[1, 2, 3], [3, 2, 1]]', '[[3, 2, 1], [3, 2, 1]]', '[[3, 2, 1], [1, 2, 3]]', '[[1, 2, 3], [1, 2, 3]]'], a: 1, e: 'reverse reorders the array in place and returns that same array, so a and b are two names for one array and both read [3, 2, 1]. Only a copying method leaves the original intact: [...a].reverse() or a.toReversed() would give [[1, 2, 3], [3, 2, 1]].', intro: 'Decide whether reverse builds a second array or rearranges the one it was given, then read off both names.', tags: ['Arrays', 'Methods'] },
  { q: 'What is the result?\n\n```js\n[1, 2, 3].at(-1);\n```', opts: ['1', '3', '-1', 'undefined'], a: 1, e: 'at takes a negative index as a position counted back from the end, so at(-1) is the last element, 3. Bracket access does not: [1, 2, 3][-1] is undefined, because -1 is read as a property name rather than a position. That gap is why at was added, and it works the same way on strings.', intro: 'The index is negative. Decide whether at gives a negative index a meaning of its own, or whether the lookup finds nothing.', tags: ['Arrays', 'Methods'] },

  // ── Level 5 — Objects: Basics ──────────────────────────────────────────
  { q: 'What does this return?\n\n```js\nconst o = { a: 1 };\n"a" in o;\n```', opts: ['true', 'false', '1', 'undefined'], a: 0, e: 'in asks whether the property name is reachable on the object, so it answers true here no matter what value "a" holds. It also finds inherited names: "toString" in o is true while Object.hasOwn(o, "toString") is false. That is the difference from o.a !== undefined, which is false for a property deliberately set to undefined.', intro: 'Ask what in is testing — that the name exists, or that a value was stored — and what kind of answer that question has.', tags: ['Objects'] },
  { q: 'What is the result?\n\n```js\nconst o = { a: 1, b: 2 };\ndelete o.a;\nObject.keys(o);\n```', opts: ['["a", "b"]', '["b"]', '["a"]', '[]'], a: 1, e: 'delete removes the a property, leaving only ["b"].', tags: ['Objects'] },
  { q: 'What keys remain after the update and delete?\n\n```js\nconst o = { a: 1 };\no.b = 2;\ndelete o.a;\nObject.keys(o);\n```', opts: ['["a"]', '["b"]', '["a", "b"]', '[]'], a: 1, e: 'o.b = 2 adds the key b, and delete o.a removes a entirely, so Object.keys reports ["b"]. Setting o.a = undefined would not do this: the key would survive and Object.keys would still report ["a", "b"]. Objects are open to new properties at any time, so ["a"] and [] cannot follow from these two lines.', intro: 'Two edits in a row. Track the key list after each line rather than judging the object at the end.', tags: ['Objects'] },
  { q: 'What does this return?\n\n```js\nObject.entries({ a: 1 });\n```', opts: ['[["a", 1]]', '["a", 1]', '{ a: 1 }', '["a:1"]'], a: 0, e: 'Object.entries returns one element per property and each element is a [key, value] pair, so a single property gives [["a", 1]] — a pair inside an array. The flat ["a", 1] is that inner pair on its own, which is what you would get from entries[0]. The nesting is what lets for (const [k, v] of Object.entries(o)) destructure each pair, and Object.fromEntries turns the shape back into an object.', intro: 'One property, but check how many levels of array the result has.', tags: ['Objects', 'Methods'] },

  // ── Level 6 — Array Iteration ──────────────────────────────────────────
  { q: 'What does forEach return here?\n\n```js\n[1, 2, 3].forEach(x => x * 2);\n```', opts: ['[2, 4, 6]', 'undefined', '6', '[1, 2, 3]'], a: 1, e: 'forEach always returns undefined regardless of the callback.', tags: ['Arrays', 'forEach'] },
  { q: 'What does this return?\n\n```js\n["a", "b"].map(s => s.toUpperCase());\n```', opts: ['["A", "B"]', '"AB"', '["a", "b"]', '"A B"'], a: 0, e: 'map uppercases each element into a new array ["A", "B"].', tags: ['Arrays', 'map'] },
  { q: 'What is the result?\n\n```js\n[1, 2, 3, 4].map((x, i) => x + i);\n```', opts: ['[1, 3, 5, 7]', '[1, 2, 3, 4]', '[2, 4, 6, 8]', '[0, 1, 2, 3]'], a: 0, e: 'Each element is added to its own index: 1+0, 2+1, 3+2, 4+3, giving [1, 3, 5, 7]. [2, 4, 6, 8] is doubling, which is what you get by treating the second parameter as the value again, and [0, 1, 2, 3] is the indexes alone.', intro: 'The callback takes two parameters and uses both. Work out what the second one holds at each position before adding.', tags: ['Arrays', 'map'] },
  { q: 'What does this return?\n\n```js\n[[1, 2], [3, 4]].map(p => p[0]);\n```', opts: ['[1, 3]', '[2, 4]', '[1, 2, 3, 4]', '[[1], [3]]'], a: 0, e: 'Every callback call receives one inner array, so p[0] takes its first element and map collects them into [1, 3]. [1, 2, 3, 4] is what flat() or flatMap would give: map never changes the element count, so two inner arrays in means two values out, and [2, 4] would be p[1].', intro: 'Decide what p refers to on each call before you evaluate p[0].', tags: ['Arrays', 'map'] },

  // ── Level 7 — Filter & Find ────────────────────────────────────────────
  { q: 'What does this return?\n\n```js\n[1, 2, 3, 4].findIndex(x => x === 3);\n```', opts: ['1', '2', '3', '-1'], a: 1, e: 'findIndex returns the index of the first element that satisfies the callback. Counting from 0, the value 3 sits at index 2, so the result is 2. Answering 3 confuses the element with its position (or counts positions from 1), and 1 is an off-by-one slip in the other direction. -1 is what findIndex returns only when nothing matches, which makes it the value to check before using the index.', intro: 'findIndex reports a position, not the element itself; remember where array positions start counting.', tags: ['Arrays', 'findIndex'] },
  { q: 'What does this return?\n\n```js\n["", "a", "", "b"].filter(Boolean);\n```', opts: ['["a", "b"]', '["", ""]', '["", "a", "", "b"]', '[]'], a: 0, e: 'filter keeps the elements for which the callback returns true. With Boolean as the callback, each element is converted to a boolean: Boolean(\'\') is false, Boolean(\'a\') and Boolean(\'b\') are true, so only \'a\' and \'b\' survive. The idiom removes every falsy value (empty strings, 0, null, undefined, NaN, false), which is why [\'\', \'\'] — the inverted result — and the untouched array are wrong.', intro: 'Boolean itself is the callback here, so each element is passed to Boolean(...); work out what Boolean(\'\') gives.', tags: ['Arrays', 'filter'] },
  { q: 'What does this return?\n\n```js\n[1, 2, 3].some(x => x > 2);\n```', opts: ['true', 'false', '3', '[3]'], a: 0, e: 'some returns true as soon as one element satisfies the callback and false only if none do. 3 > 2 holds, so the result is true. It never returns the matching element (3) or an array of matches ([3]); those are the jobs of find and filter. Because it stops at the first hit, it is also cheaper than filter(...).length > 0.', intro: 'some asks a yes/no question about the whole array — whether at least one element passes x > 2 — so consider what type it returns.', tags: ['Arrays', 'some'] },
  { q: 'What does this return?\n\n```js\n[1, 2, 3].every(x => x > 0);\n```', opts: ['true', 'false', '3', '[1, 2, 3]'], a: 0, e: 'every returns true only if the callback is true for every element, stopping with false at the first failure. 1, 2 and 3 are all greater than 0, so the result is true. It returns a boolean, never the last element (3) or the array itself. On an empty array every returns true, which is worth remembering when validating lists.', intro: 'every needs the test to hold for all elements; look for a single element that fails x > 0 and consider the return type.', tags: ['Arrays', 'every'] },

  // ── Level 8 — Reduce ───────────────────────────────────────────────────
  { q: 'What does this return?\n\n```js\n[1, 2, 3, 4].reduce((a, b) => Math.max(a, b));\n```', opts: ['1', '4', '10', '24'], a: 1, e: 'With no initial value, the accumulator starts as 1 and the callback compares it with each following element: max(1,2) = 2, max(2,3) = 3, max(3,4) = 4, so the final accumulator is 4. 10 and 24 are the sum and product, but this callback never adds or multiplies, and 1 would mean the accumulator never updated. Math.max(...arr) gives the same result for short arrays; the reduce form also works for very long arrays and for custom comparisons such as picking the object with the highest score.', intro: 'There is no initial value, so the first callback call compares the first two elements; carry the winner forward through the rest.', tags: ['Arrays', 'reduce'] },
  { q: 'What does this return?\n\n```js\n[[1], [2], [3]].reduce((a, b) => a.concat(b), []);\n```', opts: ['[1, 2, 3]', '[[1], [2], [3]]', '[6]', '[1]'], a: 0, e: 'Starting from [], each step concatenates the next inner array: [].concat([1]) = [1], [1].concat([2]) = [1, 2], then [1, 2, 3]. concat spreads the elements of an array argument rather than nesting it, which is why the result is flat and not [[1], [2], [3]]. [6] would require summing, and [1] would mean the fold stopped after the first step. Today [[1], [2], [3]].flat() does this one-level flattening directly; the reduce form shows what flat does underneath.', intro: 'a.concat(b) returns a new array; decide whether an array passed to concat is added as one element or as its elements, then follow the accumulator through the three steps.', tags: ['Arrays', 'reduce'] },
  { q: 'What does this return?\n\n```js\n["a", "b", "a"].reduce((m, x) => {\n  m[x] = (m[x] || 0) + 1;\n  return m;\n}, {});\n```', opts: ['{ a: 2, b: 1 }', '{ a: 1, b: 1 }', '["a", "b"]', '3'], a: 0, e: 'The accumulator m starts as {}. For \'a\', m.a is undefined, so (undefined || 0) + 1 stores 1; for \'b\' the same gives m.b = 1; the second \'a\' reads m.a = 1 and stores 2. The callback returns m each time, so the final result is { a: 2, b: 1 }. { a: 1, b: 1 } would mean the existing count was ignored, and [\'a\', \'b\'] or 3 are what a Set or .length would give, not this reduce. Forgetting return m is the usual bug: the next callback would then receive undefined.', intro: 'm starts as an empty object and the callback returns it after each write; work out what (m[x] || 0) evaluates to the first and the second time a key is seen.', tags: ['Arrays', 'reduce'] },
  { q: 'What does this return?\n\n```js\n[1, 2, 3].reduce((a, b) => a + b, 10);\n```', opts: ['6', '16', '10', '15'], a: 1, e: 'The accumulator starts at 10, then the elements are added: 10+1 = 11, 11+2 = 13, 13+3 = 16. The initial value is part of the total, so 6 (the sum without it) is wrong, and 10 would mean no element was ever added. Seeding with a non-zero value is how you continue a running total or add a base amount in a single pass.', intro: 'Look at the second argument of reduce before adding anything: it is where the accumulator starts, not something appended at the end.', tags: ['Arrays', 'reduce'] },

  // ── Level 9 — Destructuring ────────────────────────────────────────────
  { q: 'What is the value of x?\n\n```js\nconst { a: x } = { a: 5 };\nx;\n```', opts: ['5', 'undefined', '"a"', '{ a: 5 }'], a: 0, e: 'In a destructuring pattern, property: target reads the property named on the left and binds it to the name on the right, so x receives obj.a, which is 5. No variable a is created at all. undefined would be the result of reading a property named x, which the object does not have, and the pattern yields the value, never the string \'a\' or the whole object. The same syntax avoids name clashes, e.g. const { id: userId } = user.', intro: 'Only one of the two names in { a: x } becomes a variable; decide which side of the colon names the property and which the new binding.', tags: ['Destructuring', 'Objects'] },
  { q: 'What is the value of a?\n\n```js\nconst [[a]] = [[9]];\na;\n```', opts: ['9', '[9]', 'undefined', '[[9]]'], a: 0, e: 'The outer pattern takes the first element of [[9]], which is [9]; the inner pattern then takes the first element of that, 9. a is therefore 9, not [9] (one level too shallow) or [[9]]. It would be undefined only if an inner array were empty. Nested patterns are useful in callbacks such as Object.entries(obj).map(([key, value]) => ...).', intro: 'Compare the bracket pairs around a in the pattern with the nesting of the value on the right; decide how many levels a reaches into before it binds.', tags: ['Destructuring', 'Arrays'] },
  { q: 'What does f return?\n\n```js\nfunction f({ a, b }) {\n  return a + b;\n}\nf({ a: 1, b: 2 });\n```', opts: ['3', '12', 'undefined', 'NaN'], a: 0, e: 'A destructuring pattern in the parameter list pulls a and b out of the argument object, so inside f, a is 1 and b is 2 and the return value is 3. Both values are numbers, so + adds rather than concatenating (12 would need strings). NaN would appear only if a or b were undefined — for example if the call passed { a: 1 } — which is why defaults like { a = 0, b = 0 } are common in this pattern.', intro: 'The braces in the parameter list are a pattern, not an object literal; ask what a and b are bound to when f receives { a: 1, b: 2 }.', tags: ['Destructuring', 'Functions'] },
  { q: 'What is rest?\n\n```js\nconst { a, ...rest } = { a: 1, b: 2, c: 3 };\nrest;\n```', opts: ['{ b: 2, c: 3 }', '{ a: 1 }', '{ a: 1, b: 2, c: 3 }', '[2, 3]'], a: 0, e: 'The pattern binds a to 1 and then collects every remaining own property into a new object, so rest is { b: 2, c: 3 }. rest never includes the properties already named, and it is an object, not an array [2, 3], because the source is an object. The original object is not modified. This is the usual way to copy an object while dropping one key, e.g. const { password, ...safeUser } = user.', intro: '...rest gathers whatever the pattern did not name explicitly; note which property is picked out first and what kind of container the remainder is put in.', tags: ['Destructuring', 'Rest'] },

  // ── Level 10 — Spread & Rest ───────────────────────────────────────────
  { q: 'What does this return?\n\n```js\nMath.max(...[3, 1, 4, 1, 5]);\n```', opts: ['5', 'NaN', '[3, 1, 4, 1, 5]', '14'], a: 0, e: 'Spread expands the array into separate arguments, so the call is Math.max(3, 1, 4, 1, 5), which returns 5. Without the dots, Math.max([3, 1, 4, 1, 5]) receives a single array, fails to convert it to a number, and returns NaN. Math.max never returns an array, and 14 would be the sum. For very large arrays prefer a loop or reduce, since spreading passes every element as a separate argument.', intro: 'Math.max wants separate numeric arguments, not one array; ask what the spread turns the array into at the call site.', tags: ['Spread'] },
  { q: 'What is the value of a.length after this runs?\n\n```js\nconst a = [1, 2];\nconst b = [...a];\nb.push(3);\na.length;\n```', opts: ['2', '3', 'undefined', 'TypeError'], a: 0, e: 'Spread copies a\'s elements into a brand-new array, so b === a is false and b.push(3) grows only b: a still has 2 elements while b has 3. Answering 3 assumes b is another name for the same array, which is what const b = a would give. No TypeError occurs: const stops the binding b from being reassigned, not the array from being mutated. The copy is shallow, so objects nested inside would still be shared between a and b.', intro: 'Decide whether b is the same array object as a or a separate one before you work out what b.push can touch.', tags: ['Spread', 'Arrays'] },
  { q: 'What is c.a?\n\n```js\nconst o = { a: 1 };\nconst c = { ...o, a: 2 };\nc.a;\n```', opts: ['1', '2', 'undefined', '[1, 2]'], a: 1, e: 'The literal is built in order: ...o copies a: 1 first, then the explicit a: 2 overwrites it, so c.a is 2. Had a: 2 been written before ...o, the spread would have overwritten it and c.a would be 1 — position decides. Duplicate keys never accumulate into an array, and o itself is unchanged. This \'spread, then override\' shape is the standard immutable update, e.g. setState({ ...state, loading: true }).', intro: 'Think of the literal as being built key by key from left to right, and decide what happens when the key a is written a second time.', tags: ['Spread', 'Objects'] },
  { q: 'What does this return?\n\n```js\n[..."abc"];\n```', opts: ['["a", "b", "c"]', '"abc"', '["abc"]', 'TypeError'], a: 0, e: 'Strings are iterable, so spreading \'abc\' into an array literal yields one element per character: [\'a\', \'b\', \'c\']. No TypeError is thrown — that happens only for non-iterables such as numbers or plain objects. [\'abc\'] is what [\'abc\'] without dots would give, and the result is an array, not the original string. Unlike \'abc\'.split(\'\'), spread iterates by code point, so it keeps emoji and other characters outside the BMP intact.', intro: 'Array spread works on any iterable; decide whether a string counts as one and what its iteration yields.', tags: ['Spread', 'Strings'] },

  // ── Level 11 — Functions & Scope ───────────────────────────────────────
  { q: 'What does this return?\n\n```js\n(function () {\n  return 42;\n})();\n```', opts: ['42', 'undefined', 'the function itself', 'SyntaxError'], a: 0, e: 'The parentheses turn the function into an expression, and the trailing () calls it immediately, so the whole expression evaluates to the function\'s return value, 42. Without the trailing () the value would be the function itself. The wrapping parentheses are what make this valid: a bare function () {} statement followed by () would be a SyntaxError. IIFEs still appear for isolating variables in plain scripts and for top-level async code in CommonJS.', intro: 'The function is wrapped in parentheses and followed by (); decide whether that expression only defines the function, calls it, or both.', tags: ['Functions', 'IIFE'] },
  { q: 'What is the value of x after f(x) runs?\n\n```js\nfunction f(a) {\n  a = 5;\n}\nlet x = 1;\nf(x);\nx;\n```', opts: ['1', '5', 'undefined', 'Error'], a: 0, e: 'Arguments are passed by value: a starts as a copy of the number 1, and a = 5 rebinds the local parameter only, so x is still 1 after the call. Nothing is thrown and x is never undefined. The same rule holds for objects — reassigning the parameter never affects the caller — but mutating an object\'s properties through the parameter does, because both variables hold the same reference.', intro: 'Inside f, a is a parameter and x is the caller\'s variable; decide whether assigning to a changes what x holds or only what a holds.', tags: ['Functions', 'Scope'] },
  { q: 'What does add(2)(3) return?\n\n```js\nconst add = a => b => a + b;\nadd(2)(3);\n```', opts: ['5', '23', 'undefined', '6'], a: 0, e: 'add is an arrow that returns another arrow: add(2) returns b => 2 + b, and calling that with 3 gives 5. undefined would mean the first call returned nothing, but a concise arrow body always returns its expression. 23 would need string concatenation and 6 would need multiplication. This two-step form is currying: it lets you preset the first argument and reuse the result, e.g. const add2 = add(2).', intro: 'add(2) is itself a function call; work out what it returns before you apply (3) to that result.', tags: ['Functions', 'Currying'] },
  { q: 'What is the result?\n\n```js\nconst f = function g() {\n  return typeof g;\n};\nf();\n```', opts: ['"function"', '"undefined"', 'Error', '"g"'], a: 0, e: 'A named function expression binds its name inside its own body, so within the function g refers to the function itself and typeof g is \'function\'. That name is not created in the surrounding scope: outside, typeof g would be \'undefined\' and a bare g would throw a ReferenceError. typeof never returns a function\'s name, so \'g\' is impossible. The inner name is useful for recursion and gives clearer stack traces than an anonymous expression.', intro: 'g is the function expression\'s own name; decide whether that name is in scope inside the body when f() runs.', tags: ['Functions', 'Scope'] },

  // ── Level 12 — Closures ────────────────────────────────────────────────
  { q: 'What does b.get() return?\n\n```js\nfunction bank() {\n  let bal = 0;\n  return { add: n => (bal += n), get: () => bal };\n}\nconst b = bank();\nb.add(5);\nb.add(3);\nb.get();\n```', opts: ['0', '5', '8', 'undefined'], a: 2, e: 'Both arrows are created inside one bank() call, so they close over the same bal. add(5) makes it 5, add(3) makes it 8, and get() reads that shared 8. 0 would mean get saw its own untouched copy, and 5 would mean the second addition was lost. Because bal is reachable only through those two functions, this keeps state private without a class — the idea behind the module pattern.', intro: 'add and get were created in the same bank() call; decide whether they read the same bal or separate copies, then apply the two additions.', tags: ['Closures'] },
  { q: 'What does fns[1]() return?\n\n```js\nconst fns = [1, 2, 3].map(n => () => n);\nfns[1]();\n```', opts: ['1', '2', '3', 'undefined'], a: 1, e: 'map invokes n => () => n once per element, so fns holds three functions, each closing over its own n: 1, 2 and 3. fns[1] is the second one and returns 2. Answering 3 assumes all closures share the last value, which is the var-loop pitfall — but a callback parameter is a fresh binding on every call, so it cannot happen here. Nothing is undefined, since each inner arrow returns its captured n.', intro: 'map calls the outer arrow once per element; decide whether the three inner arrows end up sharing one n or each holding the n from their own call, then look at index 1.', tags: ['Closures'] },
  { q: 'What does mul(3)(4) return?\n\n```js\nfunction mul(a) {\n  return b => a * b;\n}\nmul(3)(4);\n```', opts: ['7', '12', '34', 'undefined'], a: 1, e: 'mul(3) returns a function that multiplies by 3; called with 4 gives 12.', tags: ['Closures'] },
  { q: 'What does the second inc() return?\n\n```js\nconst inc = (() => {\n  let count = 0;\n  return () => ++count;\n})();\ninc();\ninc();\n```', opts: ['1', '2', '0', 'undefined'], a: 1, e: 'The outer arrow is invoked at once (an IIFE); it creates count and returns an inner arrow that closes over it. count survives after the IIFE finishes because the returned function still references it, so the first inc() makes it 1 and the second returns 2. 1 would mean count was recreated per call, and 0 would mean the increment was lost; ++count returns the new value, so undefined is impossible. Unlike a reusable factory function, this creates exactly one private counter that nothing outside can read or reset.', intro: 'The outer arrow runs immediately and returns the inner arrow; decide where count lives and whether the second call sees the first call\'s change.', tags: ['Closures'] },

  // ── Level 13 — Hoisting & let/const ────────────────────────────────────
  { q: 'What is logged?\n\n```js\nvar a = 1;\nfunction f() {\n  console.log(a);\n  var a = 2;\n}\nf();\n```', opts: ['1', '2', 'undefined', 'ReferenceError'], a: 2, e: 'Inside f, var a = 2 is hoisted to the top of the function as a bare declaration, so console.log reads the local a, which is still undefined at that point. The outer a = 1 is shadowed, so 1 is wrong, and the assignment itself is not hoisted, so 2 is wrong. A ReferenceError would need let or const, which have a temporal dead zone; var does not.', intro: 'Two variables share the name a. Decide which one console.log inside f sees, and where in f that variable\'s declaration takes effect.', tags: ['Hoisting', 'var'] },
  { q: 'What is the value of obj.x on the last line?\n\n```js\nconst obj = {};\nobj.x = 1;\nobj.x;\n```', opts: ['1', 'TypeError', 'undefined', 'SyntaxError'], a: 0, e: 'const fixes the binding obj (writing obj = {} again would throw), but the object it refers to stays mutable, so obj.x = 1 adds a property and obj.x reads 1. A TypeError occurs only when reassigning obj itself, or, in strict mode, when writing to an object frozen with Object.freeze. undefined would mean the assignment was silently ignored, which does not happen to an ordinary, unfrozen object.', intro: 'Ask what exactly const protects: the variable name obj, or the contents of the object stored in it.', tags: ['const', 'Objects'] },
  { q: 'What is the result?\n\n```js\nlet x;\ntypeof x;\n```', opts: ['"undefined"', '"number"', 'ReferenceError', '"null"'], a: 0, e: 'let x; declares x and initialises it to undefined, so typeof x is the string "undefined". A ReferenceError happens only when a let variable is read before its declaration line runs (the temporal dead zone); here the declaration has already run. "null" is wrong because null is a separate value that must be assigned explicitly.', intro: 'x is declared but never assigned. Ask what value a let variable holds once its declaration line has run, and what typeof reports for that value.', tags: ['let', 'typeof'] },
  { q: 'What is logged?\n\n```js\nconsole.log(b);\nvar b;\n```', opts: ['undefined', 'ReferenceError', 'null', '0'], a: 0, e: 'var b is hoisted as undefined, so logging it before assignment prints undefined.', tags: ['Hoisting', 'var'] },

  // ── Level 14 — this & Context ──────────────────────────────────────────
  { q: 'What does o.get() return?\n\n```js\nconst o = {\n  v: 1,\n  get() {\n    return (() => this.v)();\n  },\n};\no.get();\n```', opts: ['1', 'undefined', 'TypeError', 'null'], a: 0, e: 'get is a normal method called as o.get(), so inside it this is o. The arrow function does not create its own this; it uses the this of the scope where it was written, which is get\'s, so this.v is 1. The arrow would lose the object only if get itself were an arrow, or if get were called without o in front.', intro: 'There are two functions here: the method get and the arrow inside it. Ask which one gives the arrow its this, and how get itself was called.', tags: ['this', 'Arrow'] },
  { q: 'What does g() return?\n\n```js\nfunction f() {\n  return this.x;\n}\nconst g = f.bind({ x: 7 });\ng();\n```', opts: ['7', 'undefined', 'TypeError', '{ x: 7 }'], a: 0, e: 'bind does not call f; it returns a new function g whose this is permanently set to { x: 7 }, so g() returns 7. If bind had called f immediately, g would hold the number 7 and g() would throw a TypeError, which is not what happens. A bound this cannot be overridden later by call or apply.', intro: 'Ask what bind gives back — a result or a new function — and what that new function uses as this when it finally runs.', tags: ['this', 'bind'] },
  { q: 'What does the map call return?\n\n```js\n[1, 2, 3].map(function () {\n  return this.n;\n}, { n: 9 });\n```', opts: ['[9, 9, 9]', '[1, 2, 3]', '[undefined, undefined, undefined]', 'Error'], a: 0, e: 'map accepts an optional second argument, thisArg, which becomes this inside a regular-function callback, so each call returns this.n = 9 and map collects [9, 9, 9]. Without it, this in the callback would be undefined in strict mode (so .n would throw) or the global object in sloppy mode. An arrow-function callback ignores thisArg entirely, which is why modern code rarely needs it and you mostly meet it when reading older code.', intro: 'map takes an optional second argument after the callback. Check what that argument is used for before deciding what this.n reads.', tags: ['this', 'map'] },
  { q: 'What does o.x2 return?\n\n```js\nconst o = {\n  x: 5,\n  get x2() {\n    return this.x * 2;\n  },\n};\no.x2;\n```', opts: ['10', '5', 'function', 'undefined'], a: 0, e: 'get x2() defines an accessor property: reading o.x2 runs the getter and yields its return value, this.x * 2 = 10, with no parentheses needed. It does not evaluate to a function, because an accessor hides the function behind ordinary property access; o.x2() would in fact throw because 10 is not callable. 5 is the value of o.x, not of x2.', intro: 'x2 is defined with the get keyword. Ask what happens when you read o.x2 without parentheses.', tags: ['this', 'Getters'] },

  // ── Level 15 — Callbacks & HOFs ────────────────────────────────────────
  { q: 'What does this return?\n\n```js\n["1", "2", "3"].map(Number);\n```', opts: ['["1", "2", "3"]', '[1, 2, 3]', '"123"', '[1, NaN, NaN]'], a: 1, e: 'Number("2") is 2, and Number ignores the extra index and array arguments map passes, so every string becomes its number: [1, 2, 3]. Passing parseInt instead would give [1, NaN, NaN], because parseInt reads map\'s second argument as a radix. map never returns a single string, so "123" is out.', intro: 'Number is used directly as the callback. Ask what Number("2") returns, and whether Number cares about the extra index argument map passes.', tags: ['Callbacks', 'map'] },
  { q: 'What does this return?\n\n```js\n[1, 2, 3, 4].filter((_, i) => i % 2 === 0);\n```', opts: ['[1, 3]', '[2, 4]', '[1, 2]', '[0, 2]'], a: 0, e: 'The callback ignores each value (_) and keeps only elements whose index i is even: indices 0 and 2 hold 1 and 3. [2, 4] confuses the values\' parity with the indices\'; the values 2 and 4 sit at odd indices 1 and 3. [0, 2] lists the indices themselves, but filter returns values, not indices.', intro: 'The callback names its first parameter _ and tests only the second one, i. Check what filter passes as that second argument before deciding which elements survive.', tags: ['Callbacks', 'filter'] },
  { q: 'What does twice(n => n + 3)(1) return?\n\n```js\nconst twice = f => x => f(f(x));\ntwice(n => n + 3)(1);\n```', opts: ['4', '7', '5', '1'], a: 1, e: 'twice(f) returns a function that applies f to its argument and then applies f again to the result. With f = n => n + 3 and x = 1, that is (1 + 3) + 3 = 7. 4 is the result of applying f only once, and 1 would mean f was never applied.', intro: 'Work out what twice(f) is before you apply it to 1: it is a function that nests f inside f.', tags: ['HOF'] },
  { q: 'What does this return?\n\n```js\n[10, 9, 1].sort();\n```', opts: ['[1, 9, 10]', '[1, 10, 9]', '[10, 9, 1]', '[9, 10, 1]'], a: 1, e: 'Without a comparator, sort converts every element to a string and compares them character by character. "10" comes before "9" because "1" is less than "9", so the array becomes [1, 10, 9]. [1, 9, 10] is what a numeric comparator gives: [10, 9, 1].sort((a, b) => a - b).', intro: 'No comparator is given. Recall how sort compares elements by default, and what "10" looks like next to "9" under that rule.', tags: ['Arrays', 'sort'] },

  // ── Level 16 — Ternary & Short-circuit ─────────────────────────────────
  { q: 'What does this return?\n\n```js\ntrue ? (false ? 1 : 2) : 3;\n```', opts: ['1', '2', '3', 'false'], a: 1, e: 'The outer ternary checks true and takes its first branch, which is the parenthesised inner ternary. That inner expression checks false and takes its second branch, 2. 3 is the outer false branch and is never evaluated; false is a condition, not a result.', intro: 'The parentheses make the inner ternary the whole \'true\' branch of the outer one. Resolve the outer condition first, then the inner one.', tags: ['Ternary'] },
  { q: 'What is the result?\n\n```js\nundefined || null || "x";\n```', opts: ['undefined', 'null', '"x"', 'false'], a: 2, e: '|| stops at the first truthy operand. undefined and null are both falsy, so evaluation continues to "x", which is returned. The chain is evaluated left to right, so a truthy operand earlier in it would have ended evaluation immediately; false is never produced because || returns an operand, not a boolean.', intro: 'Walk the chain from the left: || stops at the first operand that is truthy. Decide whether undefined and null qualify.', tags: ['Short-circuit'] },
  { q: 'What does this return?\n\n```js\n5 && 0 && 9;\n```', opts: ['5', '0', '9', 'false'], a: 1, e: '&& evaluates left to right and stops at the first falsy operand, returning it. 5 is truthy, so evaluation reaches 0, which is falsy and becomes the result; 9 is never evaluated. && returns the operand itself rather than false, which is why count && <List /> in React can render a stray 0.', intro: '&& evaluates left to right and stops early. Decide which of 5, 0 and 9 is the first one that makes it stop.', tags: ['Short-circuit'] },
  { q: 'What is the result?\n\n```js\nconst x = null;\nx?.toUpperCase() ?? "none";\n```', opts: ['"none"', 'null', 'undefined', 'Error'], a: 0, e: 'x is null, so x?.toUpperCase() short-circuits the whole chain — the method is not called — and evaluates to undefined. ?? then sees undefined and returns "none". Without ?., calling toUpperCase on null would throw a TypeError; with ?. but no ??, the result would be undefined rather than null.', intro: 'x?. short-circuits before .toUpperCase() is ever called. Ask what the whole x?.toUpperCase() expression is worth, then apply ??.', tags: ['Nullish', 'Optional chaining'] },

  // ── Level 17 — Type Coercion ───────────────────────────────────────────
  { q: 'What does this return?\n\n```js\ntrue + 1;\n```', opts: ['2', '"true1"', 'true', '1'], a: 0, e: 'Arithmetic converts booleans to numbers: true becomes 1, so true + 1 is 2. "true1" would need a string operand, and there is none; + only concatenates when a string is involved. false would become 0, which is why summing booleans is a quick way to count how many conditions hold.', intro: 'Arithmetic converts booleans to numbers first. Ask which number true becomes.', tags: ['Coercion'] },
  { q: 'What is the result?\n\n```js\n"6" / "2";\n```', opts: ['3', '"3"', '"6/2"', 'NaN'], a: 0, e: '/ has no string form, so both operands are converted to numbers first: 6 / 2 = 3, a number, not the string "3". Only + concatenates, so "6/2" is wrong. NaN appears only when a string cannot be converted, for example "six" / 2.', intro: 'Division has no string meaning. Ask what happens to both operands before / runs.', tags: ['Coercion'] },
  { q: 'What does this return?\n\n```js\nnull + 1;\n```', opts: ['1', 'null', 'NaN', '"null1"'], a: 0, e: 'Number(null) is 0, so null + 1 evaluates numerically to 1. This differs from undefined, which converts to NaN, so NaN is wrong here. "null1" would need a string operand. The silent conversion to 0 is why a null returned by an API for a missing number can produce a wrong total instead of an obvious error.', intro: 'null is not undefined: Number(null) has a definite numeric value. Recall which one before adding 1.', tags: ['Coercion', 'Gotchas'] },
  { q: 'What is the result?\n\n```js\nundefined + 1;\n```', opts: ['NaN', '1', 'undefined', '"undefined1"'], a: 0, e: 'Number(undefined) is NaN, and any arithmetic involving NaN yields NaN, so undefined + 1 is NaN. This differs from null, which converts to 0 and would give 1. "undefined1" would need a string operand. Reading a missing property and adding to it is the most common way NaN gets into a calculation.', intro: 'Ask what Number(undefined) is, then remember how that value behaves in any arithmetic.', tags: ['Coercion', 'Gotchas'] },

  // ── Level 18 — Truthy / Falsy ──────────────────────────────────────────
  { q: 'What is the result?\n\n```js\nBoolean(NaN);\n```', opts: ['true', 'false', 'NaN', '0'], a: 1, e: 'NaN is on the falsy list, so Boolean(NaN) is false. Among numbers only 0, -0 and NaN (and 0n for BigInt) are falsy; every other number, including negatives, is truthy. Boolean never returns the input itself, so NaN and 0 are not possible results.', intro: 'NaN is a number, but is it a truthy one? Most numbers are, so check which numeric values the falsy list includes.', tags: ['Truthy'] },
  { q: 'What does this return?\n\n```js\n!!" ";\n```', opts: ['true', 'false', '" "', 'undefined'], a: 0, e: '" " is a non-empty string — its length is 1 — so it is truthy and !! converts it to true. Only the empty string "" is falsy; whitespace does not count as empty. This is why input validation should call trim() before checking whether a string is truthy.', intro: '" " is a string containing one space. Ask whether truthiness checks a string\'s length or its meaning.', tags: ['Truthy', 'Strings'] },
  { q: 'What does this return?\n\n```js\n[] == false;\n```', opts: ['true', 'false', 'Error', 'undefined'], a: 0, e: '== does not compare truthiness; it converts both sides to a common type. false becomes 0, and [] becomes "" through toString and then 0, so the comparison is 0 == 0, which is true. Yet [] itself is truthy — if ([]) runs — which is exactly why == is confusing and === is the default choice.', intro: '== does not test truthiness; it converts both sides to a common type. Ask what Number([]) and Number(false) are.', tags: ['Truthy', 'Gotchas'] },
  { q: 'What is the result?\n\n```js\nBoolean(undefined);\n```', opts: ['true', 'false', 'undefined', 'null'], a: 1, e: 'undefined is one of the falsy values, so Boolean(undefined) is false. Boolean always returns true or false, never the input, so undefined and null are not possible results. The complete falsy list is false, 0, -0, 0n, "", null, undefined and NaN.', intro: 'Boolean() has a short fixed list of falsy inputs. Ask whether undefined is on it.', tags: ['Truthy'] },

  // ── Level 19 — JSON & Objects ──────────────────────────────────────────
  { q: 'What does this return?\n\n```js\nJSON.stringify([1, "a", true]);\n```', opts: ['\'[1,"a",true]\'', '"[1,a,true]"', '[1, "a", true]', 'Error'], a: 0, e: 'JSON.stringify writes numbers and booleans as bare tokens and strings inside double quotes, so the array becomes the string \'[1,"a",true]\'. "[1,a,true]" is not valid JSON because the string is unquoted. The result is text, not an array, and nothing here can throw.', intro: 'Ask how JSON writes each element type: numbers, strings and booleans do not all look the same in the output text.', tags: ['JSON'] },
  { q: 'What does this return?\n\n```js\nJSON.stringify({ a: undefined });\n```', opts: ['\'{"a":undefined}\'', '"{}"', '\'{"a":null}\'', 'Error'], a: 1, e: 'JSON has no representation for undefined, so JSON.stringify omits any object property whose value is undefined, leaving the string "{}". It does not write undefined, and it does not substitute null for object properties — although inside an array an undefined element does become null. Functions and symbols are dropped the same way, which is why data can silently go missing when it is serialized.', intro: 'JSON has no undefined value. Ask how JSON.stringify treats an object property it cannot represent.', tags: ['JSON', 'Gotchas'] },
  { q: 'What does this return?\n\n```js\nJSON.parse(\'{"x":1}\').x;\n```', opts: ['1', '"1"', 'undefined', 'Error'], a: 0, e: 'JSON.parse converts the JSON text into a live object, and a JSON number literal becomes a JavaScript number, so .x is the number 1. It would be the string "1" only if the JSON were {"x":"1"} with quotes around the value. The outer single quotes are just JavaScript string delimiters, so nothing is thrown.', intro: 'The whole argument is a string, but JSON.parse builds real JavaScript values from it. Decide what type the value stored under x has after parsing.', tags: ['JSON'] },
  { q: 'What is the result?\n\n```js\nObject.keys({}).length;\n```', opts: ['0', '1', 'undefined', '[]'], a: 0, e: 'Object.keys({}) returns an empty array because the object has no own enumerable properties, and an empty array\'s length is 0; this is the common way to test whether a plain object is empty. [] is what Object.keys returns before .length is read, and 1 would need one property such as { a: 1 }.', intro: 'Object.keys always returns an array, even for an object with nothing in it. The expression then reads .length on that array, not the array itself.', tags: ['Objects'] },

  // ── Level 20 — Optional Chaining & Nullish ─────────────────────────────
  { q: 'What is the result?\n\n```js\nconst o = { a: { b: null } };\no.a?.b ?? "d";\n```', opts: ['null', '"d"', 'undefined', 'Error'], a: 1, e: 'o.a exists, so ?. reads b normally and gets null; ?. only short-circuits when the value before it is nullish. Then ?? sees null on its left and returns the fallback "d". null would be the result only without the ??, and undefined would need the chain to have short-circuited, which did not happen because a is present. With b: 0 the result would be 0, because ?? does not treat falsy values as missing.', intro: 'Two operators, two questions: does ?. stop anywhere inside o.a?.b, and which values make ?? use its right side?', tags: ['Optional chaining', 'Nullish'] },
  { q: 'What does this return?\n\n```js\nconst f = null;\nf?.();\n```', opts: ['undefined', 'null', 'Error', 'false'], a: 0, e: 'f?.() checks whether f is null or undefined before calling it; f is null, so the call is skipped and the expression is undefined. Plain f() would throw TypeError: f is not a function. The result is undefined rather than null even though f held null, because a short-circuited optional chain always produces undefined, and it is never a boolean.', intro: 'This is the call form of optional chaining. Ask what happens to the whole call expression when f turns out to be null.', tags: ['Optional chaining'] },
  { q: 'What is the result?\n\n```js\nconst a = { b: 0 };\na.b ?? 5;\n```', opts: ['0', '5', 'undefined', 'null'], a: 0, e: '0 is not null or undefined, so ?? keeps it: 0.', tags: ['Nullish'] },
  { q: 'What does this return?\n\n```js\nconst arr = [10, 20];\narr?.[1];\n```', opts: ['10', '20', 'undefined', 'Error'], a: 1, e: 'arr?.[1] is the bracket form of optional chaining. arr is an array, not null or undefined, so the chain continues and reads index 1, which is 20. Index 0 would give 10, and undefined would appear only if arr were nullish or the index were out of range (arr?.[5] is undefined); the syntax is valid, so nothing throws.', intro: 'The ?. here is followed by square brackets. Decide whether arr is nullish first; if not, read it like ordinary index access.', tags: ['Optional chaining'] },

  // ── Level 21 — Promises ────────────────────────────────────────────────
  { q: 'What does the resulting promise resolve to?\n\n```js\nPromise.reject("e").catch(err => err);\n```', opts: ['"e"', 'a rejected promise', 'undefined', 'Error'], a: 0, e: 'Promise.reject("e") rejects with the string "e". The catch callback receives it and returns it normally, so the promise that catch creates fulfills with "e"; the chain has recovered. It would stay rejected only if the handler re-threw or returned a rejected promise, and undefined would need a handler with no return value. "e" is a plain string here, not an Error object.', intro: 'The handler here returns normally rather than throwing. Ask what that does to the state of the promise catch creates, and what value err actually holds.', tags: ['Promises'] },
  { q: 'What does this resolve to?\n\n```js\nPromise.resolve().then(() => 1).catch(() => 2);\n```', opts: ['1', '2', 'undefined', 'Error'], a: 0, e: 'Promise.resolve() fulfills, the then callback returns 1 and nothing throws, so the catch handler never runs; a catch with no rejection to handle passes the fulfilled value through unchanged. The result is 1. It would be 2 only if then had thrown or the initial promise had rejected, and undefined would require a then callback that returns nothing.', intro: 'catch only reacts to a rejection. Check whether anything before it in this chain rejects or throws.', tags: ['Promises'] },
  { q: 'What does this resolve to?\n\n```js\nPromise.race([Promise.resolve("a"), new Promise(() => {})]);\n```', opts: ['"a"', 'never resolves', 'Error', '["a"]'], a: 0, e: 'Promise.race adopts the outcome of whichever input settles first. Promise.resolve("a") is already fulfilled, and new Promise(() => {}) never calls resolve or reject, so the race fulfills with "a". The pending promise does not block anything, so the result is not stuck forever, and unlike Promise.all the value is the single winner, not an array. This is the basis of the timeout pattern, where a real request races a timer.', intro: 'race settles as soon as any one input settles. Ask which of these two inputs can ever settle, and when.', tags: ['Promises'] },
  { q: 'What is the result?\n\n```js\ntypeof Promise.resolve();\n```', opts: ['"object"', '"promise"', '"function"', '"undefined"'], a: 0, e: 'A Promise is an object, so typeof returns "object".', tags: ['Promises', 'typeof'] },

  // ── Level 22 — Async / Await ───────────────────────────────────────────
  { q: 'What does f() resolve to?\n\n```js\nasync function f() {\n  return await 5;\n}\n```', opts: ['5', 'a Promise', 'undefined', 'Error'], a: 0, e: 'await wraps a non-promise operand as if by Promise.resolve and waits for it, so await 5 yields 5 and f resolves to 5. f() itself is still a Promise, as with every async function, but the question asks what it resolves to, and that resolved value is the plain number 5, not a Promise wrapping it; no error occurs, because awaiting a non-promise is allowed. Outside try/catch, return await 5 behaves like return 5; inside try/catch, return await is what lets a rejection be caught in this function.', intro: 'await does not require a promise on its right. Ask what it yields when given a plain number.', tags: ['async', 'await'] },
  { q: 'In what order are values logged?\n\n```js\nconsole.log(1);\n(async () => {\n  console.log(2);\n  await null;\n  console.log(3);\n})();\nconsole.log(4);\n```', opts: ['1 2 3 4', '1 2 4 3', '1 4 2 3', '2 1 4 3'], a: 1, e: 'Calling the async arrow runs its body synchronously: 1 is logged, then 2, and await null suspends the function. Control returns to the caller, which logs 4. The continuation after await is queued as a microtask and runs once the synchronous script finishes, logging 3, so the order is 1 2 4 3. 1 4 2 3 assumes async functions defer their whole body, which they do not.', intro: 'An async function does not start later; it runs like a normal function until it meets await. Find exactly where that first pause happens.', tags: ['async', 'Event loop'] },
  { q: 'What does f() resolve to?\n\n```js\nasync function f() {\n  try {\n    await Promise.reject("x");\n  } catch (e) {\n    return e;\n  }\n}\n```', opts: ['"x"', 'a rejected promise', 'undefined', 'Error'], a: 0, e: 'await Promise.reject("x") throws the rejection reason "x" at the await, the catch block receives it as e, and return e makes f resolve to "x". Because the rejection was caught, the returned promise fulfills rather than rejects; it would stay a rejected promise only without the try/catch. undefined would require the catch block to return nothing, and the reason is a plain string, not an Error object.', intro: 'Inside an async function, await turns a rejection into a thrown exception. Follow where that exception lands and what the function then returns.', tags: ['async', 'Errors'] },
  { q: 'What does this promise resolve to?\n\n```js\nPromise.all([1, 2, 3].map(async n => n * 2));\n```', opts: ['[2, 4, 6]', '[1, 2, 3]', '6', '[Promise, Promise, Promise]'], a: 0, e: 'Each async callback returns a promise that resolves to n * 2, so map produces three promises. Promise.all waits for all of them and resolves to their values in input order: [2, 4, 6]. It unwraps the promises, so the result is never an array of Promise objects, and it collects values rather than summing them; [1, 2, 3] would mean the callbacks were never applied.', intro: 'map with an async callback produces an array of promises. Think about what Promise.all does with such an array once every promise settles.', tags: ['async', 'Promises'] },

  // ── Level 23 — Sets & Maps ─────────────────────────────────────────────
  { q: 'What is the result?\n\n```js\nnew Set("hello").size;\n```', opts: ['5', '4', '3', '2'], a: 1, e: 'new Set("hello") iterates the string character by character and keeps one copy of each: h, e, l, o, so size is 4. "hello".length is 5 because the second l counts there but is a duplicate in the Set. This works because strings are iterable; a non-iterable argument such as new Set(5) throws a TypeError.', intro: 'The Set constructor takes any iterable, and a string iterates character by character. Then apply the uniqueness rule.', tags: ['Set'] },
  { q: 'What does m.get("a") return?\n\n```js\nconst m = new Map([["a", 1], ["a", 2]]);\nm.get("a");\n```', opts: ['1', '2', 'undefined', '[1, 2]'], a: 1, e: 'The Map constructor processes the entries in order, calling set for each one: "a" is set to 1, then set again to 2, which replaces the earlier value because a Map holds exactly one value per key. m.get("a") therefore returns 2, and the map\'s size is 1. A Map never keeps both values in a list, so [1, 2] is wrong, and the first value does not win.', intro: 'The constructor calls set for each pair in order. Ask what set does when the key is already present.', tags: ['Map'] },
  { q: 'What is s.size?\n\n```js\nconst s = new Set([1, 2]);\ns.add(2);\ns.size;\n```', opts: ['1', '2', '3', 'undefined'], a: 1, e: 'new Set([1, 2]) holds 1 and 2; s.add(2) finds 2 already present and leaves the Set unchanged (add returns the Set itself, so calls can be chained), so size stays 2. 3 would require a new value such as s.add(3), and 1 would need a removal, which only delete does.', intro: 'The Set already contains 2 before add runs. Ask whether add can create a second entry for a value that is already there.', tags: ['Set'] },
  { q: 'What does this return?\n\n```js\n[...new Map([["a", 1]]).keys()];\n```', opts: ['["a"]', '[1]', '[["a", 1]]', '"a"'], a: 0, e: 'map.keys() returns an iterator over the keys, and spreading that iterator into an array literal collects them: ["a"]. values() would have produced [1] and entries() (or spreading the map itself) [["a", 1]]. The result is an array even with a single key, so a bare "a" is wrong.', intro: 'keys(), values() and entries() each iterate something different. Identify which part of the ["a", 1] pair keys() yields, then spread it.', tags: ['Map'] },

  // ── Level 24 — Edge Cases & Gotchas ────────────────────────────────────
  { q: 'What is the result?\n\n```js\ntypeof function () {};\n```', opts: ['"function"', '"object"', '"undefined"', '"Function"'], a: 0, e: 'typeof returns "function" for any callable object, including function expressions, arrow functions and classes. Functions are objects, but typeof gives them their own tag precisely so code can check typeof cb === "function" before calling a callback. typeof results are always lowercase strings, so "Function" (the constructor\'s name) is never returned, and a function expression is a defined value, not undefined.', intro: 'Functions are objects underneath. Ask whether typeof reports that underlying nature or treats callable values specially.', tags: ['typeof'] },
  { q: 'What is a after this?\n\n```js\nconst a = [1, 2, 3];\na.length = 1;\na;\n```', opts: ['[1, 2, 3]', '[1]', '[1, undefined, undefined]', 'Error'], a: 1, e: 'Assigning a smaller length truncates the array in place: the elements at index 1 and 2 are removed, leaving [1]; a[1] is now undefined and a.length is 1. const prevents reassigning the variable a, not mutating the array it references, so no error is thrown. The removed slots are gone rather than replaced by undefined values, and a.length = 0 is a common way to empty an array in place.', intro: 'length is writable, and const only fixes the binding, not the array\'s contents. Ask what the array does with elements past a smaller length.', tags: ['Arrays', 'Gotchas'] },
  { q: 'What is the result?\n\n```js\n0.1 + 0.2;\n```', opts: ['0.3', '0.30000000000000004', '0.300', 'Error'], a: 1, e: 'Floating-point math gives 0.30000000000000004, not exactly 0.3.', tags: ['Numbers', 'Gotchas'] },
  { q: 'What does this return?\n\n```js\n"5" * "2";\n```', opts: ['10', '"52"', '"10"', 'NaN'], a: 0, e: 'The * operator has no string meaning, so both operands are converted to numbers: "5" * "2" is 5 * 2 = 10, a number, not the string "10". Only + concatenates when either operand is a string, which is why "5" + "2" gives "52". NaN would appear only if a string could not be parsed as a number, such as "5" * "a".', intro: 'Only + has a string meaning. Ask what * does with two numeric strings and what type its result has.', tags: ['Coercion'] },

  // ── Level 25 — Mixed Mastery ───────────────────────────────────────────
  { q: 'What does this return?\n\n```js\n[1, 2, 3]\n  .map(x => x * 2)\n  .filter(x => x > 2)\n  .reduce((a, b) => a + b, 0);\n```', opts: ['10', '12', '6', '4'], a: 0, e: 'map doubles each value to [2, 4, 6]; filter keeps only values strictly greater than 2, dropping the 2 itself, leaving [4, 6]; reduce sums them from an initial 0, giving 10. 12 is the sum of all three doubled values (as if the filter were >= 2), and 6 is the sum of the original array before mapping.', intro: 'Write the intermediate array after each stage before summing. Pay attention to whether the filter test is > or >=.', tags: ['Chaining', 'Mastery'] },
  { q: 'What does this return?\n\n```js\nObject.keys({ a: 1, b: 2, c: 3 }).filter(k => k !== "b");\n```', opts: ['["a", "c"]', '["b"]', '["a", "b", "c"]', '[1, 3]'], a: 0, e: 'Object.keys returns ["a", "b", "c"]; filter keeps every key for which k !== "b" is true, so "b" is dropped and the result is ["a", "c"]. ["b"] would need the opposite test k === "b", and [1, 3] would need Object.values, which the code does not call.', intro: 'Object.keys yields strings, not values. Decide what the predicate k !== "b" keeps, not what it removes.', tags: ['Objects', 'Mastery'] },
  { q: 'What does this return?\n\n```js\n[..."hello"].reverse().join("");\n```', opts: ['"olleh"', '"hello"', '["o", "l", "l", "e", "h"]', 'Error'], a: 0, e: '[..."hello"] spreads the iterable string into ["h", "e", "l", "l", "o"]; reverse() flips it in place; join("") concatenates without separators to "olleh". The result is a string, so the reversed array option is the state before join. Nothing throws because reverse is called on an array, not on the string; "hello".reverse() would fail. Spread splits by code point, so combining marks and some emoji can still end up out of order.', intro: 'Strings have no reverse method, which is why the code spreads into an array first. Follow what join("") turns that reversed array back into.', tags: ['Strings', 'Mastery'] },
  { q: 'What does this return?\n\n```js\n[50, 3, 8, 10].sort((a, b) => a - b)[0];\n```', opts: ['3', '10', '50', '8'], a: 0, e: 'With (a, b) => a - b, a negative result places a before b, so the array is sorted ascending in place: [3, 8, 10, 50], and index 0 is 3. 50 would be first with b - a. Without a comparator, sort compares the values as strings, so "10" sorts before "3" and index 0 would be 10, which is the bug the comparator prevents.', intro: 'The comparator returns a - b, so decide whether that puts smaller or larger numbers first. Then consider why the comparator is there instead of a plain sort().', tags: ['Arrays', 'Mastery'] },
];
