// GIS & Cartographic Science roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const gisSeeds: Seed[] = [
  // ── Level 1 — Coordinate Systems ──
  { q: 'Lines of latitude measure position in which direction?', opts: ['North-south', 'East-west', 'Up-down', 'Diagonally'], a: 0, e: 'Latitude gives a location\'s angular distance north or south of the equator.', tags: ['GIS', 'Coordinate Systems'] },
  { q: 'What is the latitude of the equator?', opts: ['90°', '45°', '0°', '180°'], a: 2, e: 'The equator is the 0° reference line for latitude, midway between the poles.', tags: ['GIS', 'Coordinate Systems'] },
  { q: 'The prime meridian (0° longitude) passes through which city?', opts: ['Paris', 'Greenwich', 'Washington', 'Rome'], a: 1, e: 'By international convention the prime meridian runs through Greenwich, England.', tags: ['GIS', 'Coordinate Systems'] },
  { q: 'Longitude values range from 0° to what maximum east or west?', opts: ['90°', '180°', '360°', '45°'], a: 1, e: 'Longitude spans 180° east and 180° west of the prime meridian, meeting at the antimeridian.', tags: ['GIS', 'Coordinate Systems'] },
  { q: 'A geodetic datum primarily defines what?', opts: ['Map colours', 'Earth model and origin', 'Image resolution', 'Symbol sizes'], a: 1, e: 'A datum specifies a reference ellipsoid and its position, giving coordinates a consistent frame.', tags: ['GIS', 'Coordinate Systems'] },
  { q: 'WGS84 is best described as a global what?', opts: ['Projection', 'Datum', 'File format', 'Colour space'], a: 1, e: 'WGS84 is the global geodetic datum used by GPS for latitude and longitude.', tags: ['GIS', 'Coordinate Systems'] },
  { q: 'The UTM system divides the world into how many longitudinal zones?', opts: ['24', '60', '100', '360'], a: 1, e: 'UTM has 60 zones, each 6° of longitude wide, numbered from the antimeridian eastward.', tags: ['GIS', 'Coordinate Systems'] },
  { q: 'One degree of latitude is subdivided into 60 of what unit?', opts: ['Seconds', 'Radians', 'Minutes', 'Grads'], a: 2, e: 'A degree contains 60 arcminutes, and each minute contains 60 arcseconds.', tags: ['GIS', 'Coordinate Systems'] },

  // ── Level 2 — Map Projections & Distortion ──
  { q: 'A map projection transfers the curved Earth onto what?', opts: ['A flat surface', 'A larger globe', 'A satellite', 'A grid of points'], a: 0, e: 'Projection is the mathematical transformation from a 3D sphere to a 2D plane.', tags: ['GIS', 'Map Projections'] },
  { q: 'Why can no flat map perfectly represent the whole Earth?', opts: ['Ink limits', 'A sphere cannot flatten undistorted', 'Screens are square', 'GPS errors'], a: 1, e: 'A sphere is not developable, so flattening always introduces some distortion.', tags: ['GIS', 'Map Projections'] },
  { q: 'A conformal projection preserves which property locally?', opts: ['Area', 'Distance', 'Shape/angles', 'Direction only'], a: 2, e: 'Conformal projections preserve local angles and shapes, though areas can distort greatly.', tags: ['GIS', 'Map Projections'] },
  { q: 'An equal-area projection preserves what?', opts: ['Shape', 'Relative area', 'Angles', 'Scale everywhere'], a: 1, e: 'Equal-area (equivalent) projections keep relative area correct at the expense of shape.', tags: ['GIS', 'Map Projections'] },
  { q: 'The Mercator projection notably exaggerates the size of what?', opts: ['Equatorial regions', 'High-latitude regions', 'Oceans only', 'Small islands only'], a: 1, e: 'Mercator inflates areas toward the poles, making Greenland look as large as Africa.', tags: ['GIS', 'Map Projections'] },
  { q: 'Mercator remained popular for marine navigation because it preserves what?', opts: ['Area', 'Rhumb lines as straight', 'Pole shapes', 'Great circles'], a: 1, e: 'Lines of constant compass bearing (rhumb lines) plot as straight lines on Mercator.', tags: ['GIS', 'Map Projections'] },
  { q: 'A projection developed onto a cone is classified as what?', opts: ['Cylindrical', 'Conic', 'Azimuthal', 'Pseudocylindrical'], a: 1, e: 'Conic projections wrap a cone on the globe and suit mid-latitude regions well.', tags: ['GIS', 'Map Projections'] },
  { q: 'A compromise projection like Robinson does what with distortion?', opts: ['Eliminates it', 'Balances several types', 'Preserves area exactly', 'Preserves shape exactly'], a: 1, e: 'Compromise projections minimise overall visual distortion without preserving any single property perfectly.', tags: ['GIS', 'Map Projections'] },

  // ── Level 3 — Spatial Data Models ──
  { q: 'The vector data model represents features using which primitives?', opts: ['Pixels', 'Points, lines, polygons', 'Bands', 'Voxels'], a: 1, e: 'Vector data stores discrete features as points, lines, and polygons defined by coordinates.', tags: ['GIS', 'Spatial Data Models'] },
  { q: 'The raster data model represents space as a grid of what?', opts: ['Nodes', 'Cells/pixels', 'Polygons', 'Vertices'], a: 1, e: 'Raster data divides space into a regular grid of cells, each holding a value.', tags: ['GIS', 'Spatial Data Models'] },
  { q: 'Which model is generally best for continuous phenomena like elevation?', opts: ['Vector', 'Raster', 'Topology', 'Network'], a: 1, e: 'Raster grids naturally represent continuously varying surfaces such as elevation or temperature.', tags: ['GIS', 'Spatial Data Models'] },
  { q: 'In a GIS attribute table, each row typically represents what?', opts: ['A pixel band', 'A geographic feature', 'A projection', 'A map layer'], a: 1, e: 'Each row (record) stores the attributes of one spatial feature such as a parcel or road.', tags: ['GIS', 'Spatial Data Models'] },
  { q: 'Topology in GIS describes what about features?', opts: ['Their colour', 'Spatial relationships', 'Their file size', 'Their projection'], a: 1, e: 'Topology encodes adjacency, connectivity, and containment relationships between features.', tags: ['GIS', 'Spatial Data Models'] },
  { q: 'A key advantage of vector data over raster is usually what?', opts: ['Smaller for imagery', 'Precise boundaries and geometry', 'Simpler math', 'No projection needed'], a: 1, e: 'Vector data represents sharp, precise boundaries and stores rich attributes compactly.', tags: ['GIS', 'Spatial Data Models'] },
  { q: 'Increasing raster resolution (smaller cells) tends to do what?', opts: ['Reduce file size', 'Increase detail and file size', 'Remove distortion', 'Change the datum'], a: 1, e: 'Smaller cells capture more detail but greatly increase the number of cells and storage.', tags: ['GIS', 'Spatial Data Models'] },
  { q: 'A topological rule can enforce that adjacent polygons have no what?', opts: ['Attributes', 'Gaps or overlaps', 'Colours', 'Labels'], a: 1, e: 'Topology rules prevent slivers, gaps, and overlaps, ensuring a clean, consistent coverage.', tags: ['GIS', 'Spatial Data Models'] },

  // ── Level 4 — Remote Sensing & Satellite Imagery ──
  { q: 'Remote sensing gathers information about Earth how?', opts: ['Ground surveys only', 'Without physical contact', 'By drilling cores', 'Using paper maps'], a: 1, e: 'Remote sensing measures reflected or emitted energy from a distance, without touching the target.', tags: ['GIS', 'Remote Sensing'] },
  { q: 'Spatial resolution of a satellite image refers to what?', opts: ['Number of bands', 'Ground size of a pixel', 'Revisit time', 'Bit depth'], a: 1, e: 'Spatial resolution is the ground area represented by one pixel, e.g. 30 m for Landsat.', tags: ['GIS', 'Remote Sensing'] },
  { q: 'Spectral resolution describes a sensor\'s ability to distinguish what?', opts: ['Time periods', 'Wavelength bands', 'Pixel sizes', 'Elevations'], a: 1, e: 'Spectral resolution is the number and narrowness of wavelength bands the sensor records.', tags: ['GIS', 'Remote Sensing'] },
  { q: 'Healthy vegetation reflects strongly in which part of the spectrum?', opts: ['Near-infrared', 'Blue', 'Thermal only', 'Ultraviolet'], a: 0, e: 'Chlorophyll and leaf structure make healthy plants reflect strongly in near-infrared light.', tags: ['GIS', 'Remote Sensing'] },
  { q: 'The NDVI index is used mainly to assess what?', opts: ['Soil depth', 'Vegetation health', 'Water salinity', 'Cloud height'], a: 1, e: 'NDVI combines red and near-infrared bands to measure vegetation greenness and vigour.', tags: ['GIS', 'Remote Sensing'] },
  { q: 'A GPS receiver determines position by measuring what from satellites?', opts: ['Colour', 'Signal travel time', 'Magnetic field', 'Air pressure'], a: 1, e: 'GPS computes distance from signal travel time to several satellites, then trilaterates position.', tags: ['GIS', 'Remote Sensing'] },
  { q: 'How many satellites must a GPS receiver typically track for a 3D fix?', opts: ['At least 2', 'At least 4', 'Exactly 1', 'At least 12'], a: 1, e: 'Four satellites resolve the three position unknowns plus the receiver clock error.', tags: ['GIS', 'Remote Sensing'] },
  { q: 'Temporal resolution of a satellite refers to what?', opts: ['Pixel size', 'Revisit frequency', 'Band count', 'Swath colour'], a: 1, e: 'Temporal resolution is how often a sensor images the same location, key for change detection.', tags: ['GIS', 'Remote Sensing'] },

  // ── Level 5 — Spatial Analysis & GIS Applications ──
  { q: 'A buffer operation creates what around a feature?', opts: ['A label', 'A zone of set distance', 'A projection', 'An attribute'], a: 1, e: 'Buffering generates a polygon enclosing all area within a specified distance of a feature.', tags: ['GIS', 'Spatial Analysis'] },
  { q: 'Overlaying two polygon layers to keep only their common area is which operation?', opts: ['Union', 'Intersect', 'Dissolve', 'Merge'], a: 1, e: 'Intersect returns only the geometry and attributes where both input layers overlap.', tags: ['GIS', 'Spatial Analysis'] },
  { q: 'Spatial interpolation estimates values at unsampled locations using what?', opts: ['Random guesses', 'Nearby known points', 'Projection math', 'Attribute joins'], a: 1, e: 'Interpolation predicts unknown values from measurements at surrounding sampled points.', tags: ['GIS', 'Spatial Analysis'] },
  { q: 'Kriging is a spatial interpolation method based on what?', opts: ['Simple averaging', 'Spatial autocorrelation', 'Edge detection', 'Random sampling'], a: 1, e: 'Kriging uses modelled spatial autocorrelation (a variogram) to produce optimal weighted estimates.', tags: ['GIS', 'Spatial Analysis'] },
  { q: 'A dissolve operation does what to features sharing an attribute value?', opts: ['Deletes them', 'Merges them into one', 'Splits them', 'Buffers them'], a: 1, e: 'Dissolve aggregates adjacent features with the same attribute into a single feature.', tags: ['GIS', 'Spatial Analysis'] },
  { q: 'A spatial join transfers attributes between layers based on what?', opts: ['Alphabetical order', 'Location/relationship', 'File date', 'Colour'], a: 1, e: 'A spatial join links records by their geographic relationship, such as containment or proximity.', tags: ['GIS', 'Spatial Analysis'] },
  { q: 'Weighted overlay for site suitability typically combines layers by doing what?', opts: ['Deleting overlaps', 'Scoring and weighting criteria', 'Random selection', 'Reprojecting only'], a: 1, e: 'Suitability analysis reclassifies criteria to common scales, weights them, and sums the results.', tags: ['GIS', 'Spatial Analysis'] },
  { q: 'Network analysis in GIS is most suited to solving what kind of problem?', opts: ['Elevation modelling', 'Shortest-path routing', 'Cloud masking', 'Datum conversion'], a: 1, e: 'Network analysis uses connected edges and nodes to find optimal routes, service areas, and travel costs.', tags: ['GIS', 'Spatial Analysis'] },
];
