// Pawn Structures roadmap questions (40): 5 levels × 8, easiest → hardest.

import type { Seed } from './roadmap-build';

export const pawnStructuresSeeds: Seed[] = [
  // ── Level 1 — Pawn Weaknesses: Isolated, Doubled, Backward ─────────────
  { q: 'What is an isolated pawn?', opts: ['A pawn with no friendly pawns on either adjacent file','A pawn on the edge of the board','A pawn that has crossed the center','A pawn blocked by an enemy pawn'], a: 0, e: 'An isolated pawn (or "isolani") has no friendly pawns on the files next to it, so no pawn can ever defend it.', tags: ['Pawn Structures','Isolated pawns'] },
  { q: 'Why is an isolated pawn often a weakness?', opts: ['It moves faster than other pawns','It can only be defended by pieces, never by pawns','It is worth less than a normal pawn','It cannot be promoted'], a: 1, e: 'Because no pawn can guard it, an isolated pawn must be defended by pieces, which ties them down.', tags: ['Pawn Structures','Isolated pawns'] },
  { q: 'What are doubled pawns?', opts: ['Two pawns worth double value','Two pawns of the same color on the same file','Two pawns side by side','A pawn that has promoted twice'], a: 1, e: 'Doubled pawns are two pawns of one color stacked on the same file, usually the result of a capture.', tags: ['Pawn Structures','Doubled pawns'] },
  { q: 'What is a backward pawn?', opts: ['A pawn moving toward its own side','A pawn on the last rank','A pawn behind its neighbors that cannot safely advance and is not defended by a pawn','Any pawn that has not yet moved'], a: 2, e: 'A backward pawn lags behind the pawns on adjacent files and cannot advance to join them without being lost.', tags: ['Pawn Structures','Backward pawns'] },
  { q: 'The square directly in front of an isolated pawn is valuable to the opponent because it is a good spot to:', opts: ['Promote a pawn','Castle','Blockade with a piece','Offer a draw'], a: 2, e: 'The square in front of an isolated pawn cannot be attacked by an enemy pawn, making it an ideal blockading outpost.', tags: ['Pawn Structures','Isolated pawns'] },
  { q: 'Which is a common drawback of doubled pawns?', opts: ['They cannot defend one another and control fewer squares','They can never capture','They must always advance together','They block the king from castling'], a: 0, e: 'Stacked on one file, doubled pawns cannot guard each other and cover fewer squares than pawns on separate files.', tags: ['Pawn Structures','Doubled pawns'] },
  { q: 'A backward pawn is most easily attacked when it sits on:', opts: ['A closed file','A half-open file facing enemy rooks','The second rank','A file with three friendly pawns'], a: 1, e: 'A backward pawn on a half-open file is a fixed target that enemy rooks and queen can pile up against.', tags: ['Pawn Structures','Backward pawns'] },
  { q: 'What is a possible compensation for accepting doubled pawns?', opts: ['An extra queen','Gaining a half-open file for a rook and extra central control','Automatic promotion','The right to castle twice'], a: 1, e: 'Doubling often opens a file for a rook and can add control of key central squares, offsetting the structural cost.', tags: ['Pawn Structures','Doubled pawns'] },

  // ── Level 2 — Pawn Chains, Pawn Breaks & Tension ──────────────────────
  { q: 'What is a pawn chain?', opts: ['A row of pawns all on one rank','A diagonal line of pawns where each defends the one in front','Pawns of both colors locked together','Three connected passed pawns'], a: 1, e: 'A pawn chain is a diagonal of same-color pawns, each protecting the pawn ahead of it.', tags: ['Pawn Structures','Pawn chains'] },
  { q: 'The "base" of a pawn chain is:', opts: ['The most advanced pawn','The rearmost pawn, which no pawn defends','The pawn in the center','Any pawn on the fourth rank'], a: 1, e: 'The base is the rear pawn of the chain; unlike the others it is not defended by a fellow pawn.', tags: ['Pawn Structures','Pawn chains'] },
  { q: 'What is a pawn break?', opts: ['A pawn that breaks in half','Losing a pawn by accident','A pawn advance that challenges the opponent\'s pawn structure','Trading queens'], a: 2, e: 'A pawn break is a thrust that attacks the enemy pawns, aiming to open lines or dissolve their structure.', tags: ['Pawn Structures','Pawn breaks'] },
  { q: 'What is pawn tension?', opts: ['When two opposing pawns attack each other but neither has captured yet','When a pawn is pinned','When pawns are doubled','When a pawn reaches the last rank'], a: 0, e: 'Tension exists when opposing pawns can capture one another, but the position is not yet resolved.', tags: ['Pawn Structures','Pawn tension'] },
  { q: 'A classic strategy against a pawn chain is to attack it at the:', opts: ['Head (front pawn)','Base (rear pawn)','Center only','Nearest edge'], a: 1, e: 'Attacking the base, the least defended link, can collapse the whole chain if it falls.', tags: ['Pawn Structures','Pawn chains'] },
  { q: 'A frequent reason to maintain (not resolve) pawn tension is to:', opts: ['Force an immediate draw','Keep flexibility and make the opponent commit first','Win material instantly','Prevent castling'], a: 1, e: 'Holding the tension preserves options and often forces the opponent to reveal their plan or release it unfavorably.', tags: ['Pawn Structures','Pawn tension'] },
  { q: 'In the French Defense pawn chain, Black typically strikes at White\'s base with which break?', opts: ['...c5','...h5','...a5','...g5'], a: 0, e: 'The thematic ...c5 break hits the base of White\'s d4-e5 chain to undermine it.', tags: ['Pawn Structures','Pawn breaks'] },
  { q: 'Releasing pawn tension by capturing usually:', opts: ['Has no effect on the position','Clarifies the structure and can hand the opponent a useful recapture','Always wins a pawn','Forces a queen trade'], a: 1, e: 'Capturing resolves the tension into a fixed structure, so it should be timed to benefit you, not the opponent\'s recapture.', tags: ['Pawn Structures','Pawn tension'] },

  // ── Level 3 — Passed Pawns: Creation, Blockade, the Outside Passer ────
  { q: 'What is a passed pawn?', opts: ['A pawn that has been captured','A pawn with no enemy pawns ahead on its file or the adjacent files','Any pawn on the fifth rank','A pawn defended by the king'], a: 1, e: 'A passed pawn has a clear path to promotion, with no enemy pawns able to block or capture it as it advances.', tags: ['Pawn Structures','Passed pawns'] },
  { q: 'Nimzowitsch\'s famous advice about passed pawns is that they:', opts: ['Must be exchanged','Must be blockaded','Should never advance','Are always weak'], a: 1, e: 'Nimzowitsch taught that "the passed pawn is a criminal who should be kept under lock and key" — that is, blockaded.', tags: ['Pawn Structures','Passed pawns'] },
  { q: 'Which piece is traditionally considered the ideal blockader of a passed pawn?', opts: ['The rook','The queen','The knight','The bishop'], a: 2, e: 'A knight blockades well because, unlike a rook or bishop, its power is not reduced by sitting directly in front of the pawn.', tags: ['Pawn Structures','Blockade'] },
  { q: 'What is a protected passed pawn?', opts: ['A passed pawn defended by another pawn','A passed pawn behind a rook','A pawn on the starting square','A pawn guarded only by the king'], a: 0, e: 'A protected passer is a passed pawn supported by a friendly pawn, making it especially hard to deal with.', tags: ['Pawn Structures','Passed pawns'] },
  { q: 'Why blockade a passed pawn rather than ignore it?', opts: ['To gain a tempo','To stop it advancing and neutralize its promotion threat','Because the rules require it','To force a stalemate'], a: 1, e: 'A firm blockade immobilizes the pawn, removing its dynamic potential and freeing you to play elsewhere.', tags: ['Pawn Structures','Blockade'] },
  { q: 'An "outside passed pawn" is valuable mainly because it can:', opts: ['Promote in one move','Decoy the enemy king far from the other pawns','Never be captured','Move two squares at any time'], a: 1, e: 'Being distant from the main pawn mass, an outside passer lures the enemy king away, letting your king win pawns elsewhere.', tags: ['Pawn Structures','Outside passer'] },
  { q: 'The usual way to create a passed pawn from a healthy pawn majority is to:', opts: ['Trade all the pawns','Advance the majority so an unopposed candidate pawn breaks through','Keep the pawns on their starting squares','Sacrifice a rook'], a: 1, e: 'Rolling the majority forward, led by the candidate that no enemy pawn opposes, produces a passed pawn.', tags: ['Pawn Structures','Passed pawns'] },
  { q: 'In king-and-pawn endings, the outside passed pawn wins by:', opts: ['Promoting immediately','Drawing the enemy king to one wing while your king captures pawns on the other','Giving perpetual check','Forcing a knight trade'], a: 1, e: 'The enemy king must chase the outside passer, so your king mops up the remaining pawns on the far side.', tags: ['Pawn Structures','Outside passer'] },

  // ── Level 4 — Classic Structures: IQP, Hanging Pawns, Carlsbad ────────
  { q: 'The isolated queen\'s pawn (IQP) is an isolated pawn usually located on:', opts: ['The a-file','The d-file','The h-file','The second rank'], a: 1, e: 'The IQP is a lone pawn on d4 (or d5), with no friendly c- or e-pawns to support it.', tags: ['Pawn Structures','IQP'] },
  { q: 'What is the main dynamic asset for the side that owns an IQP?', opts: ['A safer king','Active pieces, extra space, and open c- and e-files for attack','An extra pawn','A guaranteed draw'], a: 1, e: 'The IQP grants space and open files, giving the owner piece activity and attacking chances, especially in the middlegame.', tags: ['Pawn Structures','IQP'] },
  { q: 'The side playing against an IQP generally wants to:', opts: ['Keep queens on and attack','Blockade the pawn and trade pieces toward an endgame','Advance all their own pawns','Avoid occupying the d5 square'], a: 1, e: 'Blockading the d-pawn and swapping pieces reduces the owner\'s activity and exposes the IQP as an endgame weakness.', tags: ['Pawn Structures','IQP'] },
  { q: 'The key central break the IQP owner often prepares is:', opts: ['The d5 advance','Castling long','The a4 push','The h4-h5 pawn storm'], a: 0, e: 'Advancing d4-d5 at the right moment frees the pawn, opens lines, and activates the pieces before it can be blockaded.', tags: ['Pawn Structures','IQP'] },
  { q: 'What are "hanging pawns"?', opts: ['Two pawns about to be lost','Two connected friendly pawns on adjacent files with no pawns on the files beside them','Pawns hanging off the edge','Two doubled pawns'], a: 1, e: 'Hanging pawns are an adjacent pair (typically c- and d-pawns) with half-open files on both sides and no neighboring pawns.', tags: ['Pawn Structures','Hanging pawns'] },
  { q: 'A key weakness of hanging pawns is that:', opts: ['They can never advance','If forced to advance, one becomes weak and the square in front becomes an outpost','They must be defended by the king','They cannot capture'], a: 1, e: 'Under pressure the pawns may have to advance, leaving one backward or isolated and yielding a strong blockade square.', tags: ['Pawn Structures','Hanging pawns'] },
  { q: 'The Carlsbad pawn structure arises most typically from the:', opts: ['Sicilian Dragon','Queen\'s Gambit Declined, Exchange Variation','King\'s Indian Defense','Ruy Lopez'], a: 1, e: 'The Carlsbad structure comes from the QGD Exchange, with White pawns on the c- and d-files facing Black\'s c6/d5.', tags: ['Pawn Structures','Carlsbad'] },
  { q: 'In the Carlsbad structure, White\'s classic queenside plan is the:', opts: ['Minority attack','Bishop sacrifice on h7','Fianchetto','Pawn storm with g4-g5'], a: 0, e: 'White\'s standard Carlsbad plan is the minority attack, pushing b4-b5 to create a lasting weakness on c6.', tags: ['Pawn Structures','Carlsbad'] },

  // ── Level 5 — Structure-Based Plans: Minority Attack & Majorities ─────
  { q: 'What is the minority attack?', opts: ['Attacking with fewer pieces','Advancing your pawn minority against the opponent\'s larger pawn group to create a weakness','Attacking only with the king','Sacrificing a minor piece'], a: 1, e: 'The minority attack uses fewer pawns (often a and b) to advance against a larger enemy pawn group and induce a weak pawn.', tags: ['Pawn Structures','Minority attack'] },
  { q: 'In the Carlsbad, the b4-b5xc6 minority attack aims to leave Black with a:', opts: ['Passed d-pawn','Backward or weak pawn on c6','Doubled f-pawns','Protected passer'], a: 1, e: 'After b5xc6, Black recaptures and is saddled with a backward c6-pawn on a half-open file — a fixed target.', tags: ['Pawn Structures','Minority attack'] },
  { q: 'The minority attack typically takes place on which side of the board?', opts: ['The kingside','The queenside','Only in the center','The side where the kings castled'], a: 1, e: 'In the Carlsbad it unfolds on the queenside, where White\'s a- and b-pawns advance against Black\'s a-, b-, and c-pawns.', tags: ['Pawn Structures','Minority attack'] },
  { q: 'What is a pawn majority?', opts: ['Having more pawns than pieces','Having more pawns than the opponent on one side of the board','Owning all eight pawns','A pawn on the majority of ranks'], a: 1, e: 'A pawn majority is a local numerical edge in pawns on one wing, for example four-against-three on the queenside.', tags: ['Pawn Structures','Pawn majority'] },
  { q: 'The chief long-term value of a healthy pawn majority is the ability to:', opts: ['Create a passed pawn','Force stalemate','Trade the queens','Win the exchange'], a: 0, e: 'A sound majority can eventually produce a passed pawn, a decisive asset especially in the endgame.', tags: ['Pawn Structures','Pawn majority'] },
  { q: 'A central pawn majority is prized because it can:', opts: ['Only defend','Gain space, restrict enemy pieces, and roll forward to create a central passer','Never be blockaded','Guarantee a draw'], a: 1, e: 'Central pawns cramp the opponent and, when mobile, can advance to make a dangerous passed pawn in the middle.', tags: ['Pawn Structures','Pawn majority'] },
  { q: 'Black\'s standard counterplay against White\'s Carlsbad minority attack is to:', opts: ['Advance the a-pawn','Seek kingside piece play or a central ...e5 break','Trade all the rooks at once','Push the h-pawn to h4 immediately'], a: 1, e: 'While White grinds on the queenside, Black looks for activity on the kingside or a freeing ...e5 in the center.', tags: ['Pawn Structures','Minority attack'] },
  { q: 'When mobilizing a pawn majority, which pawn should generally advance first?', opts: ['The one nearest the king','The "candidate" — the pawn not opposed by an enemy pawn','Any edge pawn','The most defended pawn'], a: 1, e: 'You lead with the unopposed candidate pawn, since it is the one that can break through to become passed.', tags: ['Pawn Structures','Pawn majority'] },
];
