// Differential Equations roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const differentialEquationsSeeds: Seed[] = [
  // ── Level 1 — First-Order Separable & Linear ──
  { q: 'What is the order of the differential equation dy/dx = x^2 + y?', opts: ['First order', 'Second order', 'Third order', 'Zeroth order'], a: 0, e: 'The highest derivative present is the first derivative, so the equation is first order.', tags: ['Differential Equations', 'First-Order ODEs'] },
  { q: 'What is the general solution of dy/dx = ky, where k is constant?', opts: ['y = Ce^{kx}', 'y = kx + C', 'y = Ce^{-kx}', 'y = k e^{x} + C'], a: 0, e: 'Separating variables gives dy/y = k dx, so ln|y| = kx + C and y = Ce^{kx}.', tags: ['Differential Equations', 'First-Order ODEs'] },
  { q: 'Solve the separable equation dy/dx = xy.', opts: ['y = Ce^{x^2/2}', 'y = Ce^{x}', 'y = C x^2/2', 'y = x^2/2 + C'], a: 0, e: 'dy/y = x dx integrates to ln|y| = x^2/2 + C, so y = Ce^{x^2/2}.', tags: ['Differential Equations', 'First-Order ODEs'] },
  { q: 'Solve dy/dx = 3x^2 with y(0) = 1.', opts: ['y = x^3 + 1', 'y = x^3', 'y = 3x^3 + 1', 'y = x^2 + 1'], a: 0, e: 'Integrating gives y = x^3 + C; the condition y(0) = 1 forces C = 1.', tags: ['Differential Equations', 'First-Order ODEs'] },
  { q: 'What is the general solution of y\' + 2y = 0?', opts: ['y = Ce^{-2x}', 'y = Ce^{2x}', 'y = C e^{-x/2}', 'y = -2x + C'], a: 0, e: 'This linear homogeneous equation separates to give y = Ce^{-2x}.', tags: ['Differential Equations', 'First-Order ODEs'] },
  { q: 'What is an integrating factor for y\' + 2y = e^{x}?', opts: ['e^{2x}', 'e^{-2x}', 'e^{x}', '2x'], a: 0, e: 'For y\' + P(x)y = Q(x) the integrating factor is e raised to the integral of P dx, here e^{2x}.', tags: ['Differential Equations', 'First-Order ODEs'] },
  { q: 'Which is the standard form of a first-order linear ODE?', opts: ['y\' + P(x)y = Q(x)', 'y\' + P(x)y^2 = Q(x)', 'y y\' = Q(x)', 'y\'\' + P(x)y = 0'], a: 0, e: 'A first-order linear ODE is linear in y and y\', giving y\' + P(x)y = Q(x).', tags: ['Differential Equations', 'First-Order ODEs'] },
  { q: 'Solve the separable equation dy/dx = -x/y.', opts: ['x^2 + y^2 = C', 'y^2 - x^2 = C', 'y = -x + C', 'x^2 - y^2 = C'], a: 0, e: 'Separating gives y dy = -x dx, so y^2/2 = -x^2/2 + C, i.e. x^2 + y^2 = C.', tags: ['Differential Equations', 'First-Order ODEs'] },

  // ── Level 2 — Exact Equations, Integrating Factors & Applications ──
  { q: 'The equation M(x,y)dx + N(x,y)dy = 0 is exact when:', opts: ['dM/dy = dN/dx', 'dM/dx = dN/dy', 'M = N', 'dM/dy = -dN/dx'], a: 0, e: 'Exactness requires the partial derivative of M with respect to y to equal that of N with respect to x.', tags: ['Differential Equations', 'Exact Equations & Applications'] },
  { q: 'Solve the exact equation 2xy dx + x^2 dy = 0.', opts: ['x^2 y = C', 'x y^2 = C', 'x^2 + y^2 = C', 'xy = C'], a: 0, e: 'Here d(x^2 y) = 2xy dx + x^2 dy, so the solution is x^2 y = C.', tags: ['Differential Equations', 'Exact Equations & Applications'] },
  { q: 'For a decay process N = N0 e^{-kt}, the half-life equals:', opts: ['(ln 2)/k', 'k/(ln 2)', '(ln 2) * k', '1/k'], a: 0, e: 'Setting N = N0/2 gives e^{-kt} = 1/2, so t = (ln 2)/k.', tags: ['Differential Equations', 'Exact Equations & Applications'] },
  { q: 'A radioactive sample has a half-life of 10 years. What fraction remains after 20 years?', opts: ['1/4', '1/2', '1/3', '1/8'], a: 0, e: '20 years is two half-lives, so the remaining fraction is (1/2)^2 = 1/4.', tags: ['Differential Equations', 'Exact Equations & Applications'] },
  { q: 'Newton\'s law of cooling models temperature by:', opts: ['dT/dt = -k(T - T_env)', 'dT/dt = -kT^2', 'dT/dt = kT', 'dT/dt = -k t'], a: 0, e: 'The rate of cooling is proportional to the difference between the object and its environment.', tags: ['Differential Equations', 'Exact Equations & Applications'] },
  { q: 'A tank holds 100 L of water. Brine with 2 g/L enters at 5 L/min and the well-mixed solution leaves at 5 L/min. The salt Q(t) satisfies:', opts: ['dQ/dt = 10 - Q/20', 'dQ/dt = 2 - Q/100', 'dQ/dt = 10 - 5Q', 'dQ/dt = 5 - Q/20'], a: 0, e: 'Rate in is 2*5 = 10 g/min; rate out is (Q/100)*5 = Q/20 g/min.', tags: ['Differential Equations', 'Exact Equations & Applications'] },
  { q: 'For the mixing tank with dQ/dt = 10 - Q/20, the steady-state amount of salt is:', opts: ['200 g', '100 g', '20 g', '50 g'], a: 0, e: 'Setting dQ/dt = 0 gives Q/20 = 10, so Q = 200 g.', tags: ['Differential Equations', 'Exact Equations & Applications'] },
  { q: 'If a population grows as P = P0 e^{kt}, its doubling time is:', opts: ['(ln 2)/k', 'k ln 2', '2/k', '(ln 2)/(2k)'], a: 0, e: 'Setting P = 2P0 gives e^{kt} = 2, so t = (ln 2)/k.', tags: ['Differential Equations', 'Exact Equations & Applications'] },

  // ── Level 3 — Second-Order Linear Homogeneous (Constant Coefficients) ──
  { q: 'Solve y\'\' + 5y\' + 6y = 0.', opts: ['y = C1 e^{-2x} + C2 e^{-3x}', 'y = C1 e^{2x} + C2 e^{3x}', 'y = C1 e^{-2x} + C2 e^{3x}', 'y = (C1 + C2 x)e^{-2x}'], a: 0, e: 'The characteristic equation r^2 + 5r + 6 = 0 has roots r = -2 and r = -3.', tags: ['Differential Equations', 'Second-Order Homogeneous'] },
  { q: 'Solve y\'\' - y = 0.', opts: ['y = C1 e^{x} + C2 e^{-x}', 'y = C1 cos x + C2 sin x', 'y = (C1 + C2 x)e^{x}', 'y = C1 e^{x} + C2 x e^{x}'], a: 0, e: 'The roots of r^2 - 1 = 0 are r = 1 and r = -1.', tags: ['Differential Equations', 'Second-Order Homogeneous'] },
  { q: 'Solve y\'\' + 4y = 0.', opts: ['y = C1 cos 2x + C2 sin 2x', 'y = C1 e^{2x} + C2 e^{-2x}', 'y = C1 cos 4x + C2 sin 4x', 'y = (C1 + C2 x)cos 2x'], a: 0, e: 'The roots are r = +/- 2i, giving oscillatory solutions with angular frequency 2.', tags: ['Differential Equations', 'Second-Order Homogeneous'] },
  { q: 'Solve y\'\' - 4y\' + 4y = 0.', opts: ['y = (C1 + C2 x)e^{2x}', 'y = C1 e^{2x} + C2 e^{-2x}', 'y = (C1 + C2 x)e^{-2x}', 'y = C1 e^{4x} + C2 e^{x}'], a: 0, e: 'The characteristic equation (r - 2)^2 = 0 has the repeated root r = 2.', tags: ['Differential Equations', 'Second-Order Homogeneous'] },
  { q: 'If the characteristic roots are a +/- bi, the general solution is:', opts: ['e^{ax}(C1 cos bx + C2 sin bx)', 'C1 e^{ax} + C2 e^{bx}', 'e^{bx}(C1 cos ax + C2 sin ax)', '(C1 + C2 x)e^{ax}'], a: 0, e: 'Complex conjugate roots give e^{ax}(C1 cos bx + C2 sin bx).', tags: ['Differential Equations', 'Second-Order Homogeneous'] },
  { q: 'Solve y\'\' + y\' = 0.', opts: ['y = C1 + C2 e^{-x}', 'y = C1 e^{x} + C2 e^{-x}', 'y = C1 + C2 e^{x}', 'y = C1 cos x + C2 sin x'], a: 0, e: 'The roots of r^2 + r = 0 are r = 0 and r = -1.', tags: ['Differential Equations', 'Second-Order Homogeneous'] },
  { q: 'The equation y\'\' + by\' + cy = 0 gives oscillatory (underdamped) solutions when:', opts: ['b^2 - 4c < 0', 'b^2 - 4c > 0', 'b^2 - 4c = 0', 'b = 0'], a: 0, e: 'A negative discriminant yields complex roots and therefore oscillation.', tags: ['Differential Equations', 'Second-Order Homogeneous'] },
  { q: 'How many arbitrary constants appear in the general solution of a second-order linear ODE?', opts: ['2', '1', '3', '0'], a: 0, e: 'An n-th order linear ODE has n independent arbitrary constants.', tags: ['Differential Equations', 'Second-Order Homogeneous'] },

  // ── Level 4 — Nonhomogeneous Equations ──
  { q: 'The general solution of a nonhomogeneous linear ODE equals:', opts: ['the homogeneous solution plus a particular solution', 'only a particular solution', 'the product of two particular solutions', 'the homogeneous solution only'], a: 0, e: 'y = y_h + y_p combines the complementary and particular solutions.', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },
  { q: 'Find a particular solution of y\'\' - y = e^{2x}.', opts: ['y_p = (1/3)e^{2x}', 'y_p = e^{2x}', 'y_p = (1/5)e^{2x}', 'y_p = 3 e^{2x}'], a: 0, e: 'Guess y_p = A e^{2x}; then (4 - 1)A = 1, so A = 1/3.', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },
  { q: 'For y\'\' + y = 3x^2, the correct trial form for y_p is:', opts: ['Ax^2 + Bx + C', 'Ax^2', 'Ax^2 + B', 'Ae^{x}'], a: 0, e: 'A polynomial forcing of degree 2 requires a full quadratic trial Ax^2 + Bx + C.', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },
  { q: 'For y\'\' + y = cos x, the trial solution must be:', opts: ['x(A cos x + B sin x)', 'A cos x + B sin x', 'A cos x', 'Ae^{x}'], a: 0, e: 'Because cos x solves the homogeneous equation, the guess is multiplied by x (resonance).', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },
  { q: 'For y\'\' + 3y\' + 2y = e^{-x}, since -1 is a characteristic root, the trial y_p is:', opts: ['A x e^{-x}', 'A e^{-x}', 'A x^2 e^{-x}', 'A e^{x}'], a: 0, e: 'The value -1 is a simple root of r^2 + 3r + 2, so the guess A e^{-x} is multiplied by x.', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },
  { q: 'Variation of parameters constructs y_p using:', opts: ['integrals involving the Wronskian of the homogeneous solutions', 'a single undetermined constant', 'the characteristic roots only', 'Laplace transforms only'], a: 0, e: 'y_p is built from y1, y2 and their Wronskian, and works for any forcing function.', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },
  { q: 'Find a particular solution of y\'\' - 3y\' + 2y = 4.', opts: ['y_p = 2', 'y_p = 4', 'y_p = -2', 'y_p = 4x'], a: 0, e: 'A constant trial y_p = k gives 2k = 4, so k = 2.', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },
  { q: 'For forcing e^{x} sin x (not a homogeneous solution), the trial form is:', opts: ['e^{x}(A cos x + B sin x)', 'A e^{x} sin x', 'e^{x}(A + B x)', 'A sin x + B cos x'], a: 0, e: 'A product of exponential and sinusoid requires e^{x}(A cos x + B sin x).', tags: ['Differential Equations', 'Nonhomogeneous Equations'] },

  // ── Level 5 — Systems, Laplace Transforms & Series Solutions ──
  { q: 'The Laplace transform of f(t) = 1 is:', opts: ['1/s', '1', '1/s^2', 's'], a: 0, e: 'L{1} is the integral of e^{-st} dt from 0 to infinity, which equals 1/s for s > 0.', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
  { q: 'The Laplace transform of e^{at} is:', opts: ['1/(s - a)', '1/(s + a)', 'a/(s^2 + a^2)', '1/s - a'], a: 0, e: 'L{e^{at}} = 1/(s - a) for s > a.', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
  { q: 'The Laplace transform of f\'(t) is:', opts: ['sF(s) - f(0)', 'F(s)/s', 'sF(s)', 'F(s) - f(0)'], a: 0, e: 'Differentiation in time becomes multiplication by s minus the initial value: sF(s) - f(0).', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
  { q: 'The Laplace transform of t is:', opts: ['1/s^2', '1/s', '2/s^3', 's'], a: 0, e: 'L{t^n} = n!/s^{n+1}; for n = 1 this is 1/s^2.', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
  { q: 'The Laplace transform of sin(at) is:', opts: ['a/(s^2 + a^2)', 's/(s^2 + a^2)', 'a/(s^2 - a^2)', '1/(s^2 + a^2)'], a: 0, e: 'L{sin at} = a/(s^2 + a^2).', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
  { q: 'The inverse Laplace transform of 1/(s - 3) is:', opts: ['e^{3t}', 'e^{-3t}', '3e^{t}', 't^3'], a: 0, e: 'Since L{e^{at}} = 1/(s - a), the inverse of 1/(s - 3) is e^{3t}.', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
  { q: 'For the linear system x\' = Ax, the origin is asymptotically stable when:', opts: ['all eigenvalues of A have negative real part', 'A is invertible', 'A has a zero eigenvalue', 'all eigenvalues are real'], a: 0, e: 'Solutions behave like e^{lambda t}; negative real parts force decay to the origin.', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
  { q: 'A point x0 is an ordinary point of y\'\' + p(x)y\' + q(x)y = 0 when:', opts: ['p and q are analytic at x0', 'p or q is singular at x0', 'the equation is nonlinear', 'x0 = 0 always'], a: 0, e: 'At an ordinary point the coefficients are analytic, guaranteeing a convergent power-series solution.', tags: ['Differential Equations', 'Systems & Laplace Transforms'] },
];
