// Special Moves roadmap questions (80): 10 levels × 8, easiest → hardest.
// Covers castling (both sides + rules), pawn promotion & underpromotion, en
// passant, and the two-square pawn advance.

import type { Seed } from './roadmap-build';

export const specialMovesSeeds: Seed[] = [
  // ── Level 1 — Kingside Castling ───────────────────────────────────────
  { q: 'What is the standard chess notation for kingside castling?', opts: ['O-O', 'O-O-O', 'K-R', '0-0-0'], a: 0, e: 'Kingside castling is written O-O (two letter O\'s), while queenside is O-O-O.', tags: ['Chess','Special Moves'] },
  { q: 'When White castles kingside, from which square to which square does the king move?', opts: ['e1 to c1', 'e1 to g1', 'e1 to f1', 'e1 to h1'], a: 1, e: 'Castling moves the king two squares toward the rook, so kingside the White king goes e1 to g1.', tags: ['Chess','Special Moves'] },
  { q: 'Which White rook is used in kingside castling?', opts: ['The a1 rook', 'Either rook', 'The h1 rook', 'No rook is used'], a: 2, e: 'Kingside castling uses the rook nearest the king, the h1 rook.', tags: ['Chess','Special Moves'] },
  { q: 'After White castles kingside, where does the rook end up?', opts: ['On f1', 'On g1', 'On h1', 'On e1'], a: 0, e: 'The h1 rook jumps over the king to f1, the square the king crossed.', tags: ['Chess','Special Moves'] },
  { q: 'How many squares does the king move when it castles?', opts: ['One square', 'Three squares', 'Two squares', 'It does not move'], a: 2, e: 'In any castling the king always moves exactly two squares toward the rook.', tags: ['Chess','Special Moves'] },
  { q: 'Kingside castling is also commonly called castling on which side?', opts: ['The short side', 'The long side', 'The queen side', 'The back side'], a: 0, e: 'Because the king travels a shorter distance, kingside castling is called castling "short".', tags: ['Chess','Special Moves'] },
  { q: 'When Black castles kingside, where does the king move to?', opts: ['c8', 'e8', 'f8', 'g8'], a: 3, e: 'Black\'s king starts on e8 and moves two squares to g8 when castling kingside.', tags: ['Chess','Special Moves'] },
  { q: 'After White plays O-O, on which squares are the king and rook?', opts: ['King g1, rook f1', 'King f1, rook g1', 'King g1, rook h1', 'King c1, rook d1'], a: 0, e: 'Kingside castling leaves the White king on g1 and the rook on f1.', tags: ['Chess','Special Moves'] },

  // ── Level 2 — Queenside Castling ──────────────────────────────────────
  { q: 'What is the notation for queenside castling?', opts: ['O-O', 'Q-R', 'O-O-O', 'x-x-x'], a: 2, e: 'Queenside castling is written with three O\'s: O-O-O.', tags: ['Chess','Special Moves'] },
  { q: 'When White castles queenside, where does the king move to?', opts: ['c1', 'g1', 'd1', 'b1'], a: 0, e: 'The king still moves two squares toward the rook, landing on c1 when castling queenside.', tags: ['Chess','Special Moves'] },
  { q: 'When White castles queenside, where does the rook end up?', opts: ['On c1', 'On b1', 'On e1', 'On d1'], a: 3, e: 'The a1 rook jumps to d1, the square the king passed over.', tags: ['Chess','Special Moves'] },
  { q: 'Queenside castling is commonly called castling on which side?', opts: ['The short side', 'The long side', 'The king side', 'The near side'], a: 1, e: 'Because the king and rook are farther apart, queenside castling is called castling "long".', tags: ['Chess','Special Moves'] },
  { q: 'Which rook does White use when castling queenside?', opts: ['The a1 rook', 'The h1 rook', 'The d1 rook', 'The e1 rook'], a: 0, e: 'Queenside castling uses the rook on the queen\'s side, the a1 rook.', tags: ['Chess','Special Moves'] },
  { q: 'When Black castles queenside, where do the king and rook go?', opts: ['King g8, rook f8', 'King c8, rook d8', 'King b8, rook c8', 'King d8, rook c8'], a: 1, e: 'Black queenside castling puts the king on c8 and the a8 rook on d8.', tags: ['Chess','Special Moves'] },
  { q: 'For White to castle queenside, which squares between the king and rook must be empty?', opts: ['Only c1', 'b1, c1 and d1', 'c1 and d1 only', 'd1 and e1'], a: 1, e: 'All three squares between the king on e1 and rook on a1 — b1, c1 and d1 — must be vacant.', tags: ['Chess','Special Moves'] },
  { q: 'Compared with kingside castling, how far does the rook travel in queenside castling?', opts: ['The same distance', 'A shorter distance', 'A longer distance', 'It does not move'], a: 2, e: 'The queenside rook travels from a1 to d1, farther than the kingside rook\'s h1 to f1 hop.', tags: ['Chess','Special Moves'] },

  // ── Level 3 — Castling Rules & Restrictions ───────────────────────────
  { q: 'Can you castle if your king has already moved earlier in the game and returned home?', opts: ['Yes, if it came back', 'No, castling rights are lost permanently', 'Yes, once per game', 'Only kingside'], a: 1, e: 'Once the king moves, castling rights are lost for the rest of the game, even if it returns.', tags: ['Chess','Special Moves'] },
  { q: 'You want to castle kingside but that rook moved earlier and came back. Is it allowed?', opts: ['Yes, the rook is home', 'No, that rook has lost castling rights', 'Yes, if the king never moved', 'Only if it is still your first move'], a: 1, e: 'If a rook has moved, you can no longer castle with that rook even if it returned home.', tags: ['Chess','Special Moves'] },
  { q: 'Your king is currently in check. May you castle to get out of it?', opts: ['Yes, castling escapes check', 'No, you cannot castle out of check', 'Only kingside', 'Only if the rook is safe'], a: 1, e: 'You may never castle while your king is in check.', tags: ['Chess','Special Moves'] },
  { q: 'A square the king would pass over during castling is attacked by an enemy piece. May you castle?', opts: ['No, the king cannot pass through an attacked square', 'Yes, only the destination matters', 'Yes, passing squares do not matter', 'Only queenside'], a: 0, e: 'The king may not move through a square that is under attack while castling.', tags: ['Chess','Special Moves'] },
  { q: 'Which of these would leave castling still legal?', opts: ['The king is in check', 'The king would land on an attacked square', 'The rook you castle with is attacked', 'The king passes through an attacked square'], a: 2, e: 'A rook being attacked never prevents castling — only the king\'s squares matter.', tags: ['Chess','Special Moves'] },
  { q: 'What must be true of the squares between the king and rook before castling?', opts: ['They must all be empty', 'They may hold pawns', 'Only one may be occupied', 'They must hold minor pieces'], a: 0, e: 'All squares between the king and the castling rook must be empty.', tags: ['Chess','Special Moves'] },
  { q: 'When castling queenside, an enemy piece attacks the b1 square (next to the rook). Can White still castle?', opts: ['No, b1 is attacked', 'Yes, b1 is not a king square', 'Only if the rook moves first', 'No, any attacked square blocks it'], a: 1, e: 'For queenside castling only the king\'s squares e1, d1, c1 matter; an attacked b1 is irrelevant.', tags: ['Chess','Special Moves'] },
  { q: 'Which statement about castling is FALSE?', opts: ['You cannot castle out of check', 'You cannot castle through check', 'You cannot castle into check', 'You cannot castle if the rook is attacked'], a: 3, e: 'An attacked rook does not stop castling; the three "check" restrictions all do apply.', tags: ['Chess','Special Moves'] },

  // ── Level 4 — Pawn Promotion ──────────────────────────────────────────
  { q: 'What happens when a White pawn reaches the 8th rank?', opts: ['It stays a pawn', 'It must promote to a new piece', 'It is removed', 'It becomes a king'], a: 1, e: 'A pawn reaching the far rank must promote and cannot remain a pawn.', tags: ['Chess','Special Moves'] },
  { q: 'Which pieces can a pawn promote to?', opts: ['King or queen only', 'Any piece except the king', 'Only a queen', 'Queen, rook, bishop or knight'], a: 3, e: 'A promoting pawn becomes a queen, rook, bishop or knight of its own color.', tags: ['Chess','Special Moves'] },
  { q: 'Can a pawn promote to a king?', opts: ['No, never', 'Yes, if you have no king', 'Yes, once per game', 'Only in the endgame'], a: 0, e: 'A pawn can never promote to a king; only queen, rook, bishop or knight are allowed.', tags: ['Chess','Special Moves'] },
  { q: 'On which rank does a Black pawn promote?', opts: ['The 8th rank', 'The 2nd rank', 'The 1st rank', 'The 7th rank'], a: 2, e: 'Black pawns move down the board and promote on the 1st rank.', tags: ['Chess','Special Moves'] },
  { q: 'Which piece is chosen in the vast majority of pawn promotions?', opts: ['The queen', 'The knight', 'The rook', 'The bishop'], a: 0, e: 'The queen is the strongest piece, so pawns are almost always promoted to a queen.', tags: ['Chess','Special Moves'] },
  { q: 'Can a player have two queens on the board at the same time?', opts: ['No, only one queen ever', 'Yes, through pawn promotion', 'Only if the first queen is captured', 'Only in blitz games'], a: 1, e: 'By promoting a pawn you can have two or even more queens simultaneously.', tags: ['Chess','Special Moves'] },
  { q: 'How is a promotion to a queen on e8 written in notation?', opts: ['e8Q+', 'Qe8', 'e8=Q', 'e8-Q'], a: 2, e: 'Promotion is shown with an equals sign and the new piece, for example e8=Q.', tags: ['Chess','Special Moves'] },
  { q: 'A pawn reaches the last rank but you would prefer to keep it a pawn. Is that allowed?', opts: ['Yes, promotion is optional', 'No, promotion is compulsory', 'Yes, once per game', 'Only if it is not attacked'], a: 1, e: 'Promotion is mandatory; a pawn reaching the far rank must become another piece.', tags: ['Chess','Special Moves'] },

  // ── Level 5 — Underpromotion ──────────────────────────────────────────
  { q: 'What does "underpromotion" mean?', opts: ['Promoting to a queen', 'Promoting to something other than a queen', 'Refusing to promote', 'Promoting on the wrong rank'], a: 1, e: 'Underpromotion is promoting to a rook, bishop or knight instead of the usual queen.', tags: ['Chess','Special Moves'] },
  { q: 'A common reason to underpromote to a knight is to:', opts: ['Deliver a fork or check a queen cannot', 'Save material', 'Follow the rules', 'Avoid losing the pawn'], a: 0, e: 'A knight reaches squares a queen cannot, so underpromoting to a knight can fork or give a decisive check.', tags: ['Chess','Special Moves'] },
  { q: 'Promoting to a rook or bishop instead of a queen is sometimes done to:', opts: ['Gain more power', 'Avoid stalemating the opponent', 'Follow tournament rules', 'Speed up the game'], a: 1, e: 'A new queen can accidentally stalemate; underpromoting to a rook or bishop can avoid that.', tags: ['Chess','Special Moves'] },
  { q: 'Which promotion piece can give check in a way a queen never could?', opts: ['A rook', 'A bishop', 'A knight', 'None of them'], a: 2, e: 'The knight moves in an L-shape, reaching check squares no queen can, which is why knight underpromotion exists.', tags: ['Chess','Special Moves'] },
  { q: 'Is underpromotion a legal move in chess?', opts: ['No, you must take a queen', 'Yes, any of the four pieces is legal', 'Only in special variants', 'Only for the knight'], a: 1, e: 'You may legally promote to a queen, rook, bishop or knight — the choice is yours.', tags: ['Chess','Special Moves'] },
  { q: 'You promote and would immediately stalemate the enemy king with a new queen. A good idea is to:', opts: ['Promote to a rook instead to keep the win', 'Promote to the queen anyway', 'Not promote at all', 'Promote to a king'], a: 0, e: 'Underpromoting to a rook keeps enough control to win while avoiding an accidental stalemate.', tags: ['Chess','Special Moves'] },
  { q: 'Which statement about underpromotion is true?', opts: ['It is illegal', 'It is always weaker than a queen', 'It can occasionally be the strongest choice', 'It must be to a bishop'], a: 2, e: 'In certain tactical positions underpromotion (often to a knight) is objectively the best move.', tags: ['Chess','Special Moves'] },
  { q: 'A pawn on e7 promotes to a knight to fork the enemy king and queen. This is best described as:', opts: ['An illegal move', 'A queen promotion', 'An underpromotion', 'En passant'], a: 2, e: 'Choosing a knight over a queen is an underpromotion, here used to fork two pieces.', tags: ['Chess','Special Moves'] },

  // ── Level 6 — En Passant Basics ───────────────────────────────────────
  { q: 'Which piece is able to capture en passant?', opts: ['Only pawns', 'Only the queen', 'Any piece', 'Only the king'], a: 0, e: 'En passant is a special capture that only pawns can perform.', tags: ['Chess','Special Moves'] },
  { q: 'What kind of piece is captured in an en passant capture?', opts: ['A knight', 'A pawn', 'A bishop', 'Any adjacent piece'], a: 1, e: 'En passant always captures an enemy pawn, never any other piece.', tags: ['Chess','Special Moves'] },
  { q: 'How is an en passant capture commonly marked in notation?', opts: ['O-O', '=Q', 'e.p.', '++'], a: 2, e: 'En passant captures are often annotated with "e.p." after the move.', tags: ['Chess','Special Moves'] },
  { q: 'In en passant, the capturing pawn moves as if the enemy pawn had done what?', opts: ['Moved one square only', 'Moved three squares', 'Not moved at all', 'Promoted'], a: 0, e: 'You capture the pawn "in passing" as though it had advanced just one square.', tags: ['Chess','Special Moves'] },
  { q: 'En passant is only possible in response to which enemy move?', opts: ['A one-square pawn move', 'A pawn\'s two-square advance', 'A knight jump', 'A castling move'], a: 1, e: 'The chance to capture en passant arises only when an enemy pawn advances two squares.', tags: ['Chess','Special Moves'] },
  { q: 'For en passant to be possible, the two pawns must end up how, relative to each other?', opts: ['On the same square', 'On adjacent files side by side', 'Two files apart', 'On the same file'], a: 1, e: 'The enemy pawn must land directly beside your pawn on an adjacent file.', tags: ['Chess','Special Moves'] },
  { q: 'After a White pawn on e5 captures a Black pawn en passant, where does the White pawn land?', opts: ['e6', 'd6', 'f6', 'It stays on e5'], a: 1, e: 'If the Black pawn advanced d7-d5, White\'s e5 pawn captures diagonally onto d6.', tags: ['Chess','Special Moves'] },
  { q: 'Can a rook capture a pawn en passant?', opts: ['Yes, any piece can', 'No, only pawns capture en passant', 'Yes, if adjacent', 'Only on the 5th rank'], a: 1, e: 'Only pawns can make an en passant capture; other pieces cannot.', tags: ['Chess','Special Moves'] },

  // ── Level 7 — En Passant Conditions ───────────────────────────────────
  { q: 'When must an en passant capture be made?', opts: ['Any time later', 'On the very next move only', 'Within three moves', 'Before castling'], a: 1, e: 'En passant must be played immediately, on the move right after the enemy pawn\'s two-square advance.', tags: ['Chess','Special Moves'] },
  { q: 'You do not capture en passant this turn and play something else. What happens to the option?', opts: ['It is lost permanently', 'It carries over one more move', 'It returns next turn', 'It can still be used later'], a: 0, e: 'If you do not take en passant on the very next move, the chance is gone for good.', tags: ['Chess','Special Moves'] },
  { q: 'A Black pawn advances only one square, e7-e6, landing beside your pawn. Can you take it en passant?', opts: ['Yes, it is adjacent', 'No, en passant needs a two-square advance', 'Yes, if you do it now', 'Only with a pawn on the 5th rank'], a: 1, e: 'En passant requires the enemy pawn to advance two squares; a one-square move does not qualify.', tags: ['Chess','Special Moves'] },
  { q: 'For White to capture en passant, on which rank must the capturing White pawn already sit?', opts: ['The 4th rank', 'The 6th rank', 'The 5th rank', 'The 7th rank'], a: 2, e: 'A White pawn must be on the 5th rank to capture a Black pawn en passant.', tags: ['Chess','Special Moves'] },
  { q: 'Which condition is NOT required for an en passant capture?', opts: ['The enemy pawn advanced two squares', 'You respond immediately', 'The pawns end up on adjacent files', 'Your king is in check'], a: 3, e: 'En passant has nothing to do with check; the other three conditions are all required.', tags: ['Chess','Special Moves'] },
  { q: 'An enemy pawn made its two-square jump three moves ago. Can you still capture it en passant now?', opts: ['Yes, anytime', 'No, the window closed after one move', 'Yes, within five moves', 'Only if it has not moved since'], a: 1, e: 'The en passant right lasts only for the single move immediately after the two-square advance.', tags: ['Chess','Special Moves'] },
  { q: 'Can you capture a knight en passant if it moves two squares next to your pawn?', opts: ['Yes, two squares counts', 'No, en passant only works against a pawn\'s two-square move', 'Yes, if immediate', 'Only for the queen'], a: 1, e: 'En passant applies solely to a pawn\'s two-square advance, never to a knight or any other piece.', tags: ['Chess','Special Moves'] },
  { q: 'A Black pawn plays d7-d5 next to your e5 pawn. On your reply you play a different move. Later, may you take that d5 pawn en passant?', opts: ['Yes, still available', 'No, the chance expired', 'Yes, once more only', 'Only if it stays on d5'], a: 1, e: 'Because you did not capture on the immediate next move, the en passant opportunity is lost.', tags: ['Chess','Special Moves'] },

  // ── Level 8 — The Two-Square Pawn Move ────────────────────────────────
  { q: 'When is a pawn allowed to advance two squares?', opts: ['On any move', 'Only on its first move', 'Only when capturing', 'Only on the 4th rank'], a: 1, e: 'A pawn may advance two squares only on its very first move from its starting square.', tags: ['Chess','Special Moves'] },
  { q: 'From which rank do White pawns make a two-square advance?', opts: ['Rank 1', 'Rank 3', 'Rank 2', 'Rank 4'], a: 2, e: 'White pawns start on the 2nd rank, so their optional two-square jump is from rank 2 to rank 4.', tags: ['Chess','Special Moves'] },
  { q: 'A pawn has already moved once. How many squares can it advance afterward?', opts: ['Two squares', 'One square', 'Three squares', 'Any number'], a: 1, e: 'After its first move a pawn can only advance one square at a time.', tags: ['Chess','Special Moves'] },
  { q: 'A White pawn on e2 has an enemy piece sitting on e3. Can it advance two squares to e4?', opts: ['Yes, it jumps over', 'No, the square in front is blocked', 'Yes, if it captures', 'Only diagonally'], a: 1, e: 'Pawns cannot jump over a piece; a blocker on e3 prevents both the one- and two-square advance.', tags: ['Chess','Special Moves'] },
  { q: 'The two-square pawn advance is what makes which special capture possible?', opts: ['Castling', 'Promotion', 'En passant', 'Checkmate'], a: 2, e: 'En passant exists precisely because a pawn can bypass an enemy pawn using the two-square move.', tags: ['Chess','Special Moves'] },
  { q: 'From which rank do Black pawns make their two-square advance?', opts: ['Rank 8', 'Rank 7', 'Rank 6', 'Rank 5'], a: 1, e: 'Black pawns begin on the 7th rank, advancing to the 5th on their optional double step.', tags: ['Chess','Special Moves'] },
  { q: 'Is a pawn required to move two squares on its first move?', opts: ['Yes, always', 'No, one square is also allowed', 'Only if unblocked', 'Only in the opening'], a: 1, e: 'The two-square advance is optional; a pawn may instead move a single square on its first move.', tags: ['Chess','Special Moves'] },
  { q: 'A pawn on its starting square wants to move two squares, but the square it would pass over is occupied. Is the move legal?', opts: ['Yes, pawns can jump', 'No, both squares must be clear', 'Yes, if the far square is empty', 'Only when capturing'], a: 1, e: 'For a two-square advance both the intermediate and the destination square must be empty.', tags: ['Chess','Special Moves'] },

  // ── Level 9 — Combining Special Moves ─────────────────────────────────
  { q: 'Can you castle while at the same time promoting a pawn in a single move?', opts: ['Yes, both happen', 'No, only one move is made per turn', 'Only kingside', 'Only if the pawn is on the 7th'], a: 1, e: 'Each turn is a single move; castling and promotion cannot occur together.', tags: ['Chess','Special Moves'] },
  { q: 'A rook that just castled is later used for nothing special. Which earlier special move gave up that side\'s castling right?', opts: ['Moving the king or that rook', 'Promoting a pawn', 'Capturing en passant', 'A two-square pawn move'], a: 0, e: 'Castling rights are forfeited once the king or the relevant rook has moved.', tags: ['Chess','Special Moves'] },
  { q: 'White\'s e5 pawn captures en passant onto d6 with check. Which two ideas combined here?', opts: ['Castling and promotion', 'En passant and a discovered/direct check', 'Promotion and en passant', 'Two-square move and castling'], a: 1, e: 'The en passant capture can itself deliver check, combining the special capture with an attack on the king.', tags: ['Chess','Special Moves'] },
  { q: 'Your opponent plays a two-square pawn advance that gives you an en passant capture which also promotes... is that possible?', opts: ['Yes, en passant can land on the last rank', 'No, an en passant capture never lands on the promotion rank', 'Yes, always with a queen', 'Only for Black'], a: 1, e: 'En passant happens on the 6th rank (for White) or 3rd (for Black), never on a promotion rank, so it cannot promote.', tags: ['Chess','Special Moves'] },
  { q: 'A pawn on the 7th rank can, on its next move, do which special action?', opts: ['Castle', 'Capture en passant a two-rank away pawn', 'Promote by reaching the last rank', 'Advance two squares'], a: 2, e: 'From the 7th rank a White pawn reaches the 8th and must promote; it long ago lost its two-square option.', tags: ['Chess','Special Moves'] },
  { q: 'Which special move can decisively change the king\'s safety in one turn by relocating both king and rook?', opts: ['Promotion', 'En passant', 'Castling', 'The two-square pawn move'], a: 2, e: 'Castling is unique in moving two pieces at once, tucking the king to safety behind the rook.', tags: ['Chess','Special Moves'] },
  { q: 'You castle queenside; the b1 square is attacked but c1 and d1 are safe and empty, and the king is not in check. Legal?', opts: ['No, b1 is attacked', 'Yes, only the king\'s squares must be safe', 'No, all four squares matter', 'Only if the rook is defended'], a: 1, e: 'For queenside castling only e1, d1 and c1 (the king\'s squares) must be unattacked; b1 is irrelevant.', tags: ['Chess','Special Moves'] },
  { q: 'Which combination of statements is fully correct?', opts: ['Pawns promote to any piece; en passant lasts forever', 'Castling moves the king two squares; en passant must be immediate', 'You can castle out of check; pawns may become kings', 'En passant captures knights; castling needs no empty squares'], a: 1, e: 'Castling always moves the king two squares, and en passant must be taken on the immediate next move.', tags: ['Chess','Special Moves'] },

  // ── Level 10 — Special Moves Mastery ──────────────────────────────────
  { q: 'White: Ke1, Rh1, no other pieces on the e1-h1 rank; the king is in check from a bishop. White wants O-O. Legal?', opts: ['Yes, castling blocks the check', 'No, you cannot castle out of check', 'Yes, the rook is safe', 'Only if g1 is empty'], a: 1, e: 'Being in check forbids castling entirely, regardless of the rook or the destination.', tags: ['Chess','Special Moves'] },
  { q: 'A Black pawn on b4; White plays a2-a4. Can Black play ...bxa3 en passant?', opts: ['Yes, capturing onto a3', 'No, the pawns are not adjacent after the move', 'No, only White may take en passant', 'Yes, capturing onto a4'], a: 0, e: 'White\'s a2-a4 lands beside Black\'s b4 pawn, so Black captures en passant onto a3.', tags: ['Chess','Special Moves'] },
  { q: 'White pawn on g7 promotes to a knight, giving check and forking the Black king and queen. This move is:', opts: ['Illegal, must be a queen', 'A legal underpromotion', 'En passant', 'A castling move'], a: 1, e: 'Promoting to a knight is a legal underpromotion, here winning the queen by a forking check.', tags: ['Chess','Special Moves'] },
  { q: 'For White queenside castling, which single set of squares must ALL be unattacked?', opts: ['a1, b1, c1', 'b1, c1, d1', 'c1, d1, e1', 'd1, e1, f1'], a: 2, e: 'The king travels e1-d1-c1, so exactly those three squares must be free of attack; b1 does not count.', tags: ['Chess','Special Moves'] },
  { q: 'Which sequence describes a legal chain of events?', opts: ['Pawn advances two squares, opponent takes en passant next move, board continues', 'King castles then castles again', 'Pawn promotes to a king to escape', 'Rook captures a pawn en passant'], a: 0, e: 'A two-square advance immediately followed by an en passant capture is a fully legal sequence.', tags: ['Chess','Special Moves'] },
  { q: 'A player already has one queen. A pawn reaches e8. What are the promotion options?', opts: ['Only a rook, since one queen exists', 'Any of queen, rook, bishop, knight — a second queen is fine', 'Nothing, promotion is blocked', 'It must stay a pawn'], a: 1, e: 'Having a queen never limits promotion; you may make a second queen or any other allowed piece.', tags: ['Chess','Special Moves'] },
  { q: 'White\'s king on e1 never moved, but the h1 rook moved to h5 and back to h1. Can White now castle kingside?', opts: ['Yes, both are home', 'No, that rook lost its castling right', 'Yes, once', 'Only queenside now'], a: 1, e: 'A rook that has moved loses castling rights permanently, even after returning to h1.', tags: ['Chess','Special Moves'] },
  { q: 'Which statement is completely accurate about the special moves?', opts: ['En passant may be delayed a few moves if you announce it', 'You can castle through an attacked square if the rook defends it', 'A promoting pawn must become Q, R, B, or N and can never be a king or stay a pawn', 'Any piece can capture en passant'], a: 2, e: 'Promotion is mandatory and limited to queen, rook, bishop or knight — never a king and never a pawn.', tags: ['Chess','Special Moves'] },
];
