// The Board & Setup roadmap questions (80): 10 levels × 8, easiest → hardest.
// Covers the chessboard, initial setup, square colors, ranks/files/diagonals,
// the goal of the game, turns, captures, check basics, and etiquette.

import type { Seed } from './roadmap-build';

export const rulesSeeds: Seed[] = [
  // ── Level 1 — The Chessboard ──────────────────────────────────────────
  { q: 'How many squares are on a standard chessboard?', opts: ['32','48','64','100'], a: 2, e: 'A chessboard is an 8×8 grid, which is 8 times 8 equals 64 squares.', tags: ['Chess','Rules'] },
  { q: 'A chessboard is a grid of how many rows by how many columns?', opts: ['8 by 8','6 by 6','10 by 10','9 by 9'], a: 0, e: 'The board has 8 rows and 8 columns, giving 64 squares in total.', tags: ['Chess','Rules'] },
  { q: 'What two colors are the squares on a chessboard?', opts: ['Red and black','Light and dark','Blue and yellow','All one color'], a: 1, e: 'The squares alternate between light and dark colors across the whole board.', tags: ['Chess','Rules'] },
  { q: 'Do the squares on a chessboard alternate in color?', opts: ['No, they are random','Yes, they alternate','Only on the edges','Only in the center'], a: 1, e: 'Light and dark squares alternate so that no two same-colored squares sit side by side.', tags: ['Chess','Rules'] },
  { q: 'How many pieces does each player start the game with?', opts: ['12','16','20','8'], a: 1, e: 'Each side begins with 16 pieces: 8 pawns and 8 other pieces.', tags: ['Chess','Rules'] },
  { q: 'How many total pieces are on the board at the start of a game?', opts: ['24','16','32','64'], a: 2, e: 'Both players together start with 32 pieces, 16 each.', tags: ['Chess','Rules'] },
  { q: 'What is the shape of a chessboard?', opts: ['A circle','A square','A triangle','A hexagon'], a: 1, e: 'The chessboard is a square, with 8 squares along each side.', tags: ['Chess','Rules'] },
  { q: 'How many colors of pieces are there in a chess game?', opts: ['Two','Three','Four','One'], a: 0, e: 'One player controls the White pieces and the other controls the Black pieces.', tags: ['Chess','Rules'] },

  // ── Level 2 — Setting Up the Pieces ───────────────────────────────────
  { q: 'On which rank do White\'s pawns start?', opts: ['The 1st rank','The 2nd rank','The 3rd rank','The 4th rank'], a: 1, e: 'White\'s eight pawns line up along the 2nd rank at the start of the game.', tags: ['Chess','Rules'] },
  { q: 'On which rank do Black\'s pawns start?', opts: ['The 8th rank','The 6th rank','The 7th rank','The 5th rank'], a: 2, e: 'Black\'s eight pawns line up along the 7th rank at the start.', tags: ['Chess','Rules'] },
  { q: 'How many pawns does each side have at the start?', opts: ['6','8','10','16'], a: 1, e: 'Each player starts with 8 pawns filling an entire rank.', tags: ['Chess','Rules'] },
  { q: 'Which piece sits in each corner of the board at the start?', opts: ['The rook','The knight','The bishop','The queen'], a: 0, e: 'A rook occupies each of the four corner squares in the starting position.', tags: ['Chess','Rules'] },
  { q: 'From the a-file, what is the correct order of White\'s back-rank pieces?', opts: ['Rook, Bishop, Knight, Queen, King, Knight, Bishop, Rook','Rook, Knight, Bishop, Queen, King, Bishop, Knight, Rook','Rook, Knight, Bishop, King, Queen, Bishop, Knight, Rook','Knight, Rook, Bishop, Queen, King, Bishop, Rook, Knight'], a: 1, e: 'The back rank runs Rook, Knight, Bishop, Queen, King, Bishop, Knight, Rook from the a-file.', tags: ['Chess','Rules'] },
  { q: 'On which square does the White king start?', opts: ['d1','e1','c1','f1'], a: 1, e: 'The White king starts on e1, with the queen beside it on d1.', tags: ['Chess','Rules'] },
  { q: 'On which square does the White queen start?', opts: ['e1','c1','d1','d2'], a: 2, e: 'The White queen starts on d1, which is a light square (queen on her color).', tags: ['Chess','Rules'] },
  { q: 'Next to which piece do the knights sit in the starting position?', opts: ['Next to the rooks in the corners','Next to the king only','Next to the queen only','In the center'], a: 0, e: 'Each knight sits just inside a corner rook, between a rook and a bishop.', tags: ['Chess','Rules'] },

  // ── Level 3 — Light & Dark Squares ────────────────────────────────────
  { q: 'When set up correctly, what color is the near-right corner square for each player?', opts: ['Dark','Light','It varies','Green'], a: 1, e: 'The rule "white on the right" means a light square sits in each player\'s near-right corner.', tags: ['Chess','Rules'] },
  { q: 'The square h1 is what color?', opts: ['Light','Dark','Red','Neither'], a: 0, e: 'h1 is a light square, sitting in White\'s near-right corner.', tags: ['Chess','Rules'] },
  { q: 'The square a1 is what color?', opts: ['Light','Dark','Blue','White'], a: 1, e: 'a1 is a dark square, in White\'s near-left corner.', tags: ['Chess','Rules'] },
  { q: 'The White queen starts on which color square?', opts: ['A dark square','A light square','A red square','It has no color'], a: 1, e: 'The White queen starts on d1, a light square, following "queen on her own color".', tags: ['Chess','Rules'] },
  { q: 'The Black queen starts on which color square?', opts: ['A light square','A dark square','A green square','The same as the king'], a: 1, e: 'The Black queen starts on d8, a dark square, matching her own color.', tags: ['Chess','Rules'] },
  { q: 'How many light squares are on the board?', opts: ['30','32','34','16'], a: 1, e: 'The 64 squares split evenly, so there are 32 light and 32 dark squares.', tags: ['Chess','Rules'] },
  { q: 'A bishop that starts on a light square can move to which squares?', opts: ['Only light squares','Only dark squares','Any square','Only its own file'], a: 0, e: 'A bishop stays on one color for the entire game, so a light-squared bishop only reaches light squares.', tags: ['Chess','Rules'] },
  { q: 'Two squares that share only a corner touch are always what?', opts: ['Different colors','The same color','Both light','Both dark'], a: 1, e: 'Diagonally adjacent squares (corner-touching) are always the same color.', tags: ['Chess','Rules'] },

  // ── Level 4 — Ranks, Files & Diagonals ────────────────────────────────
  { q: 'What is a "rank" on a chessboard?', opts: ['A column','A horizontal row','A diagonal line','A single square'], a: 1, e: 'A rank is a horizontal row, numbered 1 through 8.', tags: ['Chess','Rules'] },
  { q: 'What is a "file" on a chessboard?', opts: ['A vertical column','A horizontal row','A diagonal','A corner'], a: 0, e: 'A file is a vertical column, lettered a through h.', tags: ['Chess','Rules'] },
  { q: 'How are the ranks labeled?', opts: ['With letters a–h','With numbers 1–8','With Roman numerals','With colors'], a: 1, e: 'Ranks are the horizontal rows, numbered 1 to 8.', tags: ['Chess','Rules'] },
  { q: 'How are the files labeled?', opts: ['With numbers 1–8','With letters a–h','With numbers 0–7','With symbols'], a: 1, e: 'Files are the vertical columns, lettered a to h.', tags: ['Chess','Rules'] },
  { q: 'What is a diagonal made up of?', opts: ['Squares of alternating colors','Squares all the same color','Only edge squares','A row of eight ranks'], a: 1, e: 'A diagonal is a slanted line of squares that are all the same color.', tags: ['Chess','Rules'] },
  { q: 'How many squares are in the a-file?', opts: ['6','7','8','9'], a: 2, e: 'Every file runs the full height of the board, so it contains 8 squares.', tags: ['Chess','Rules'] },
  { q: 'The square e4 lies on which file and rank?', opts: ['File e, rank 4','File 4, rank e','File a, rank 4','File e, rank 1'], a: 0, e: 'In algebraic notation the letter is the file and the number is the rank, so e4 is file e, rank 4.', tags: ['Chess','Rules'] },
  { q: 'The longest diagonals on the board contain how many squares?', opts: ['6','7','8','9'], a: 2, e: 'The two long corner-to-corner diagonals each span 8 squares.', tags: ['Chess','Rules'] },

  // ── Level 5 — The Goal of the Game ────────────────────────────────────
  { q: 'What is the main goal of a game of chess?', opts: ['To capture the most pieces','To checkmate the opponent\'s king','To reach the other side','To take the queen'], a: 1, e: 'The object of chess is to checkmate the enemy king, not simply to win material.', tags: ['Chess','Rules'] },
  { q: 'Do you actually capture the king to win?', opts: ['Yes, you remove it','No, you checkmate it','Only in blitz','Only the queen matters'], a: 1, e: 'The king is never captured; the game ends when it is checkmated (trapped in check).', tags: ['Chess','Rules'] },
  { q: 'What does "checkmate" mean?', opts: ['The king is in check with no legal escape','The king is captured','A draw is agreed','A pawn reaches the end'], a: 0, e: 'Checkmate is when the king is in check and there is no legal move to escape it.', tags: ['Chess','Rules'] },
  { q: 'Which piece must you protect above all others?', opts: ['The queen','The king','The rook','A pawn'], a: 1, e: 'The king is the most important piece; if it is checkmated, the game is lost.', tags: ['Chess','Rules'] },
  { q: 'If a game ends with neither side able to checkmate, what is it called?', opts: ['A win','A loss','A draw','A forfeit'], a: 2, e: 'A game that ends with no checkmate, such as a stalemate, is a draw.', tags: ['Chess','Rules'] },
  { q: 'Which of these is a way a game can end?', opts: ['Checkmate','Resignation','Draw','All of these'], a: 3, e: 'A game can end by checkmate, resignation, a draw, and other means.', tags: ['Chess','Rules'] },
  { q: 'What happens when a player resigns?', opts: ['The game is a draw','That player loses','The game restarts','Nothing changes'], a: 1, e: 'Resigning means conceding the game, so the resigning player loses.', tags: ['Chess','Rules'] },
  { q: 'Is capturing more pieces the same as winning the game?', opts: ['Yes, most pieces wins','No, only checkmate wins','Yes, if you take the queen','Only in the endgame'], a: 1, e: 'Extra material helps, but the game is only won by delivering checkmate.', tags: ['Chess','Rules'] },

  // ── Level 6 — Turns & Touch-Move ──────────────────────────────────────
  { q: 'Which color always moves first?', opts: ['Black','White','The player who chooses','Whoever is older'], a: 1, e: 'White always makes the first move of the game.', tags: ['Chess','Rules'] },
  { q: 'How many pieces may you move on a single turn (ignoring castling)?', opts: ['One','Two','As many as you like','None'], a: 0, e: 'A normal turn is exactly one move of one piece; castling is the special exception.', tags: ['Chess','Rules'] },
  { q: 'After White moves, whose turn is it?', opts: ['White again','Black','Either player','Nobody'], a: 1, e: 'Players strictly alternate, so Black moves after White.', tags: ['Chess','Rules'] },
  { q: 'Can you skip your turn if you don\'t like your options?', opts: ['Yes, anytime','No, you must move','Only once per game','Only in check'], a: 1, e: 'Passing is not allowed; on your turn you must make a legal move.', tags: ['Chess','Rules'] },
  { q: 'Under the touch-move rule, what happens if you touch your own piece?', opts: ['Nothing','You must move it if it has a legal move','You lose the game','You must move a pawn'], a: 1, e: 'If you deliberately touch your own piece and it can move legally, you must move it.', tags: ['Chess','Rules'] },
  { q: 'Under touch-move, what happens if you touch an opponent\'s piece?', opts: ['You must capture it if legally possible','Nothing happens','You lose your queen','You must move your king'], a: 0, e: 'Touching an enemy piece obliges you to capture it if a legal capture exists.', tags: ['Chess','Rules'] },
  { q: 'How do you signal you want to adjust a piece without being forced to move it?', opts: ['You cannot adjust','Say "adjust" (j\'adoube) first','Move it back quickly','Ask the arbiter to move it'], a: 1, e: 'Announcing "adjust" or "j\'adoube" before touching lets you center a piece without the touch-move obligation.', tags: ['Chess','Rules'] },
  { q: 'When is a move considered complete in a game with a clock?', opts: ['When you say "done"','When you release the piece (and press the clock)','When the opponent replies','It is never final'], a: 1, e: 'A move is finished once you let go of the piece on its new square; you then press your clock.', tags: ['Chess','Rules'] },

  // ── Level 7 — Capturing Basics ────────────────────────────────────────
  { q: 'How do most pieces capture an enemy piece?', opts: ['By jumping over it','By moving onto its square','By touching it','You cannot capture'], a: 1, e: 'A capturing piece moves to the square occupied by the enemy piece and removes it.', tags: ['Chess','Rules'] },
  { q: 'What happens to a captured piece?', opts: ['It stays on the board','It is removed from the board','It changes color','It returns next turn'], a: 1, e: 'A captured piece is taken off the board and plays no further part in the game.', tags: ['Chess','Rules'] },
  { q: 'Can you capture one of your own pieces?', opts: ['Yes','No','Only pawns','Only the queen'], a: 1, e: 'You may never capture your own pieces; captures are only of enemy pieces.', tags: ['Chess','Rules'] },
  { q: 'Is capturing ever compulsory in standard chess?', opts: ['Yes, always','No, captures are optional','Only with pawns','Only in check'], a: 1, e: 'Unlike some games, chess never forces a capture; it is your choice.', tags: ['Chess','Rules'] },
  { q: 'How does a pawn capture?', opts: ['Straight ahead','One square diagonally forward','Sideways','Backwards'], a: 1, e: 'A pawn moves straight but captures one square diagonally forward.', tags: ['Chess','Rules'] },
  { q: 'Which piece can jump over other pieces when it moves or captures?', opts: ['The rook','The bishop','The knight','The queen'], a: 2, e: 'The knight is the only piece that can leap over other pieces.', tags: ['Chess','Rules'] },
  { q: 'Can a pawn capture a piece sitting directly in front of it?', opts: ['Yes','No','Only the king','Only another pawn'], a: 1, e: 'A pawn captures only diagonally, so a piece blocking it directly ahead cannot be taken by it.', tags: ['Chess','Rules'] },
  { q: 'If two of your pieces could both capture the same enemy piece, how many do you use?', opts: ['Both at once','Just one, it is one move','Neither','You must use the higher-valued one'], a: 1, e: 'A capture is a single move, so you choose exactly one piece to make it.', tags: ['Chess','Rules'] },

  // ── Level 8 — Check Basics ────────────────────────────────────────────
  { q: 'What does it mean when a king is "in check"?', opts: ['It is trapped forever','It is under attack and could be captured next','It has been taken','It cannot ever move'], a: 1, e: 'Check means the king is attacked by an enemy piece and must be made safe immediately.', tags: ['Chess','Rules'] },
  { q: 'When your king is in check, what must you do?', opts: ['Ignore it','Get out of check on this move','Resign','Skip your turn'], a: 1, e: 'You are required to respond to check on your very next move.', tags: ['Chess','Rules'] },
  { q: 'Which of these is a legal way to answer a check?', opts: ['Move the king to safety','Block the check','Capture the checking piece','All of these'], a: 3, e: 'You can escape check by moving the king, blocking the attack, or capturing the attacker.', tags: ['Chess','Rules'] },
  { q: 'Can you make a move that leaves your own king in check?', opts: ['Yes','No, it is illegal','Only with a pawn','Only once'], a: 1, e: 'Any move that leaves or puts your own king in check is illegal.', tags: ['Chess','Rules'] },
  { q: 'Is being in check the same as losing the game?', opts: ['Yes','No, only checkmate loses','Only if the queen checks','Only in the endgame'], a: 1, e: 'Check is just an attack on the king; you only lose if it becomes checkmate.', tags: ['Chess','Rules'] },
  { q: 'Can a king move into a square attacked by an enemy piece?', opts: ['Yes, freely','No, that would be moving into check','Only to capture','Only on the back rank'], a: 1, e: 'A king may never move onto a square where it would be in check.', tags: ['Chess','Rules'] },
  { q: 'Can you block a check delivered by a knight?', opts: ['Yes, always','No, a knight check cannot be blocked','Only with a pawn','Only with the queen'], a: 1, e: 'Because knights jump, there is no square between attacker and king to block, so you must move the king or capture the knight.', tags: ['Chess','Rules'] },
  { q: 'If your only legal response to a check is to capture the attacker, must you?', opts: ['No, you may pass','Yes, you must make a legal move','You may resign only','You lose automatically'], a: 1, e: 'You must play a legal move that escapes check; if capturing is the only one, that is what you play.', tags: ['Chess','Rules'] },

  // ── Level 9 — Illegal Moves & Etiquette ───────────────────────────────
  { q: 'Which of these is an illegal move?', opts: ['Castling','Moving a knight in an L-shape','Leaving your own king in check','Capturing a pawn'], a: 2, e: 'A move that leaves your own king in check is always illegal.', tags: ['Chess','Rules'] },
  { q: 'What should you do if you notice an illegal move was played?', opts: ['Ignore it','Take the move back and correct the position','Immediately win','Swap a piece'], a: 1, e: 'An illegal move must be retracted and a legal move played instead.', tags: ['Chess','Rules'] },
  { q: 'What is the polite custom at the start and end of a serious game?', opts: ['Shake hands','Say nothing','Take a piece','Move the clock'], a: 0, e: 'Players traditionally shake hands before and after the game as a mark of respect.', tags: ['Chess','Rules'] },
  { q: 'Is it good etiquette to talk or distract your opponent during their move?', opts: ['Yes','No','Only in check','Only about the weather'], a: 1, e: 'Distracting or disturbing your opponent is considered poor etiquette and is discouraged.', tags: ['Chess','Rules'] },
  { q: 'How is resignation traditionally shown over the board?', opts: ['Flipping the board','Tipping over your king or offering a handshake','Removing all pawns','Shouting "check"'], a: 1, e: 'A player often resigns by gently tipping over their king or extending a handshake.', tags: ['Chess','Rules'] },
  { q: 'When is it appropriate to offer a draw?', opts: ['On your own move, after making it','During your opponent\'s thinking time','Only in check','Never'], a: 0, e: 'Correct etiquette is to offer a draw after you have made your move, before pressing the clock.', tags: ['Chess','Rules'] },
  { q: 'Can you take back a move once you have released the piece?', opts: ['Yes, anytime','No, the move stands','Only pawn moves','Only your first move'], a: 1, e: 'Once you release a piece on its square, the move is complete and cannot be retracted.', tags: ['Chess','Rules'] },
  { q: 'Announcing "check" out loud is which of the following?', opts: ['Required by the rules','A courtesy, not required in formal play','Illegal','Only for the queen'], a: 1, e: 'Saying "check" is a friendly courtesy but is not required under official tournament rules.', tags: ['Chess','Rules'] },

  // ── Level 10 — Rules Mastery ──────────────────────────────────────────
  { q: 'A beginner sets up the board with a dark square in the near-right corner. What is wrong?', opts: ['Nothing, that is correct','The board is rotated; a light square belongs on the near right','The pawns are missing','The king and queen are fine'], a: 1, e: 'The rule "white on the right" requires a light square in each player\'s near-right corner, so the board must be turned.', tags: ['Chess','Rules'] },
  { q: 'A player sets the queens on d1 and d8 but swaps them so White\'s queen is on a dark square. What is wrong?', opts: ['Queens can go anywhere','The queen must start on her own color, so White\'s queen belongs on light d1','Kings are misplaced','Nothing is wrong'], a: 1, e: '"Queen on her color" means the White queen must sit on the light d1 square, not a dark one.', tags: ['Chess','Rules'] },
  { q: 'White is in check from a bishop on a diagonal, with an empty square between them. Which is NOT a way out?', opts: ['Move the king off the diagonal','Block on the square between','Capture the bishop','Announce a pass and do nothing'], a: 3, e: 'Passing is never legal; you must move the king, block, or capture to escape check.', tags: ['Chess','Rules'] },
  { q: 'It is Black\'s move and Black\'s only legal reply to a check is to capture the attacking rook with the king. What must happen?', opts: ['Black may resign instead of moving','Black must play that capture','It is stalemate','Black skips the turn'], a: 1, e: 'When a single legal move exists to escape check, the player is obliged to make it.', tags: ['Chess','Rules'] },
  { q: 'In a tournament game a player touches their knight, which has a legal move. They then want to move a bishop instead. Allowed?', opts: ['Yes, always','No, touch-move requires them to move the knight','Only if they say sorry','Only if it is check'], a: 1, e: 'Under touch-move, a deliberately touched piece with a legal move must be the piece that moves.', tags: ['Chess','Rules'] },
  { q: 'A knight on f3 gives check to a king on g1-area. Why can this check never be blocked?', opts: ['Knights move too fast','A knight jumps, leaving no square to interpose','Knights cannot give check','The king is pinned'], a: 1, e: 'Because a knight leaps over squares, there is no line to interpose a blocker, so the king must move or the knight be captured.', tags: ['Chess','Rules'] },
  { q: 'Which statement about the goal of chess is most accurate?', opts: ['You win by capturing the enemy king','You win by checkmating the enemy king','You win by taking the most material','You win by promoting a pawn'], a: 1, e: 'The king is never actually captured; the game is won by checkmate, trapping the king in check.', tags: ['Chess','Rules'] },
  { q: 'A pawn on e5 wants to capture an enemy pawn sitting directly on e6. Can it?', opts: ['Yes, pawns capture straight ahead','No, pawns capture only diagonally, so it is blocked','Only if it is White','Only by jumping'], a: 1, e: 'Pawns move straight but capture diagonally, so a pawn cannot take a piece directly in front of it.', tags: ['Chess','Rules'] },
];
