import type { QuestionTranslation } from './quiz-data';

export const checkmateTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Co je šach? ──────────────────────────────────────────
  'rm-mate-1': { introduction: 'Zamysli se, co znamená, že je král ohrožen.', question: 'Co znamená, že je král „v šachu“?', options: ['Král je napaden nepřátelskou figurou', 'Král byl sebrán', 'Král se vůbec nemůže hýbat', 'Hra skončila'], explanation: 'Šach znamená, že je král právě napaden alespoň jednou nepřátelskou figurou.' },
  'rm-mate-2': { introduction: 'Na šach musíš vždy nějak reagovat.', question: 'Když je tvůj král v šachu, co musíš udělat?', options: ['Můžeš to podle libosti ignorovat', 'Musíš zareagovat a dostat krále ze šachu', 'Automaticky prohráváš', 'Musíš nabídnout remízu'], explanation: 'Jsi povinen okamžitě zareagovat a dostat svého krále ze šachu.' },
  'rm-mate-3': { introduction: 'Nechat vlastního krále v ohrožení není dovoleno.', question: 'Můžeš zahrát tah, který ponechá tvého vlastního krále v šachu?', options: ['Ano, kdykoli', 'Jen s dámou', 'Ne, nikdy to není dovoleno', 'Jen při rošádě'], explanation: 'Ponechat vlastního krále v šachu je nelegální, takže takový tah není nikdy povolen.' },
  'rm-mate-4': { introduction: 'V šachu bývá vždy jen jedna konkrétní figura.', question: 'Která figura je ta, která se dostává „do šachu“?', options: ['Dáma', 'Věž', 'Kterákoli figura', 'Král'], explanation: 'V šachu se říká, že je vždy jen král.' },
  'rm-mate-5': { introduction: 'Existuje tradiční slovo, kterým se ohlašuje útok na krále.', question: 'Běžný způsob, jak ohlásit útok na krále, je říct:', options: ['„Šach!“', '„Mat!“', '„Remíza!“', '„Pas!“'], explanation: 'Hráči tradičně říkají „šach“, aby upozornili, že je král napaden.' },
  'rm-mate-6': { introduction: 'Šach a výhra nejsou totéž.', question: 'Je dát nepřátelskému králi šach totéž jako vyhrát partii?', options: ['Ano, šach okamžitě vyhrává', 'Ne, samotný šach nevyhrává', 'Jen v bleskovce', 'Jen s věží'], explanation: 'Šach jen znamená, že je král napaden; pokud lze šachu uniknout, hra pokračuje.' },
  'rm-mate-7': { introduction: 'Po tvém tahu musí být tvůj král v bezpečí.', question: 'Může být král na konci tvého tahu ponechán na šachovnici v šachu?', options: ['Ano, to je v pořádku', 'Někdy s pěšcem', 'Ne, musíš být ze šachu venku', 'Jen pokud vyhráváš'], explanation: 'Po tvém tahu nesmí být tvůj vlastní král v šachu.' },
  'rm-mate-8': { introduction: 'Šach nemusí dávat jen těžké figury.', question: 'Která z těchto možností může dát šach?', options: ['Jen dáma', 'Jen věže', 'Jen pěšci', 'Kterákoli figura napadající krále'], explanation: 'Šach dává kterákoli figura včetně pěšce, pokud napadá nepřátelského krále.' },

  // ── Úroveň 2 — Jak se dostat ze šachu ────────────────────────────────────
  'rm-mate-9': { introduction: 'Vzpomeň si na tři základní obranné možnosti.', question: 'Kolik obecných způsobů existuje, jak se dostat ze šachu?', options: ['Tři', 'Jeden', 'Pět', 'Dva'], explanation: 'Můžeš pohnout králem, šach zaclonit nebo sebrat šachující figuru.' },
  'rm-mate-10': { introduction: 'Jedna z možností při rošádě není dovolena.', question: 'Která z těchto možností NENÍ legální způsob, jak uniknout šachu?', options: ['Přesun krále na bezpečné pole', 'Rošáda ze šachu', 'Zaclonění šachu', 'Sebrání útočníka'], explanation: 'Rošádu ze šachu nemáš nikdy dovolenou.' },
  'rm-mate-11': { introduction: 'Jde o vložení figury mezi útočníka a krále.', question: 'Šachu můžeš uniknout tak, že mezi útočníka a svého krále postavíš jednu ze svých figur. Tomu se říká:', options: ['Rošáda', 'Proměna', 'Zaclonění (vložení figury)', 'Vazba'], explanation: 'Vložení figury, které přeruší útok, se nazývá zaclonění šachu.' },
  'rm-mate-12': { introduction: 'Nejpřímější řešení je zbavit se útočníka.', question: 'Jeden přímý způsob, jak ukončit šach, je:', options: ['Nabídnout remízu', 'Pohnout vzdáleným pěšcem', 'Ignorovat ho', 'Sebrat šachující figuru'], explanation: 'Sebrání figury, která dává šach, útok zcela odstraní.' },
  'rm-mate-13': { introduction: 'Vzpomeň si, jak se pohybuje jezdec.', question: 'Můžeš proti šachu od jezdce zaclonit vložením figury?', options: ['Ne, šach od jezdce nelze zaclonit', 'Ano, vždy', 'Jen s věží', 'Jen s dámou'], explanation: 'Jezdec přeskakuje figury, takže jeho šach nelze nikdy zaclonit.' },
  'rm-mate-14': { introduction: 'Když je útočník přímo vedle krále, není kam vložit figuru.', question: 'Když je šachující figura přímo vedle krále (kontaktní šach), lze ji zaclonit?', options: ['Ano, snadno', 'Ne, mezi nimi není žádné pole', 'Jen střelcem', 'Jen pěšcem'], explanation: 'Kontaktní šach neponechává žádnou mezeru pro vložení figury, takže ho nelze zaclonit.' },
  'rm-mate-15': { introduction: 'Když nefunguje žádná ze tří obran, jde o něco vážného.', question: 'Pokud je tvůj král v šachu a přesun, zaclonění i sebrání jsou nemožné, pak je pozice:', options: ['Remíza', 'Jen běžný šach', 'Mat', 'Pat'], explanation: 'Žádná úniková možnost ze šachu znamená mat.' },
  'rm-mate-16': { introduction: 'Král nemůže vejít pod další útok.', question: 'Když pohneš králem ze šachu, cílové pole musí být:', options: ['Kterékoli sousední pole', 'Nejbližší roh', 'Obsazené vlastní figurou', 'Pole nenapadené soupeřem'], explanation: 'Král se může přesunout jen na pole, které není napadeno.' },

  // ── Úroveň 3 — Co je mat? ──────────────────────────────────────
  'rm-mate-17': { introduction: 'Jde o šach, ze kterého není úniku.', question: 'Co je mat?', options: ['Král je v šachu bez legálního úniku', 'Král je sebrán a odstraněn', 'Remíza, když nezbývají figury', 'Král v pasti, ale ne v šachu'], explanation: 'Mat je šach, ze kterého neexistuje žádný legální únik.' },
  'rm-mate-18': { introduction: 'Mat nastane a co se stane s partií?', question: 'Co se s partií stane v okamžiku matu?', options: ['Hra pokračuje ještě o jeden tah', 'Hra okamžitě končí', 'Král je sebrán v příštím tahu', 'Obě strany získají bod'], explanation: 'Mat ukončí partii okamžitě; strana dávající mat vyhrává.' },
  'rm-mate-19': { introduction: 'Král se ve skutečnosti nikdy nesebere.', question: 'Je král někdy fyzicky sebrán a odstraněn ze šachovnice?', options: ['Ano, při posledním tahu', 'Jen při patu', 'Ne, hra končí matem', 'Jen dámou'], explanation: 'Král se nikdy nesebere; hra se zastaví matem.' },
  'rm-mate-20': { introduction: 'Kdo dává mat, ten vítězí.', question: 'Kdo při matu vyhrává?', options: ['Hráč, kterému došel čas', 'Nikdo, je to remíza', 'Hráč s více figurami', 'Hráč dávající mat'], explanation: 'Vyhrává strana, která dá mat.' },
  'rm-mate-21': { introduction: 'Bez šachu není mat.', question: 'Aby mat existoval, musí být král:', options: ['V šachu', 'Ne v šachu', 'Na své základní řadě', 'Vedle nepřátelského krále'], explanation: 'Mat vyžaduje, aby byl král v šachu bez legální odpovědi.' },
  'rm-mate-22': { introduction: 'Pokud existuje legální únik, o mat nejde.', question: 'Pokud je král napaden, ale může útočníka sebrat, je to mat?', options: ['Ano, vždy', 'Ne, existuje legální únik', 'Jen pokud útočí věž', 'Jen v koncovce'], explanation: 'Pokud jakýkoli legální tah odstraní šach, nejde o mat.' },
  'rm-mate-23': { introduction: 'Hledej situaci se šachem a bez legálního tahu.', question: 'Která situace je mat?', options: ['Král napaden, ale může utéct', 'Král nenapaden, bez tahů', 'Král v šachu bez legálního tahu', 'Král bezpečně po rošádě'], explanation: 'Mat je neuniknutelný šach, po němž nezbývá žádný legální tah.' },
  'rm-mate-24': { introduction: 'Existuje tradiční slovo, kterým se hra ukončí matem.', question: 'Tradiční slovo, které se řekne, když se partie vyhraje matem, je:', options: ['„Šach“', '„Remíza“', '„Pas“', '„Šach mat“'], explanation: 'Hráči říkají „šach mat“, aby ohlásili vítězný tah.' },

  // ── Úroveň 4 — Mat na základní řadě ──────────────────────────────────────
  'rm-mate-25': { introduction: 'Krále často uvězní jeho vlastní figury.', question: 'Mat na základní řadě nastane, když je král uvězněn na své domácí řadě kým?', options: ['Vlastními pěšci', 'Nepřátelskými jezdci', 'Středovými pěšci', 'Vlastním králem'], explanation: 'Král je uzavřen svými vlastními nehnutými pěšci na základní řadě.' },
  'rm-mate-26': { introduction: 'Podél řady kloužou těžké figury.', question: 'Která figura obvykle dává mat na základní řadě podél řady?', options: ['Jezdec', 'Věž nebo dáma', 'Střelec', 'Pěšec'], explanation: 'Mat dává věž nebo dáma klouzající podél základní řady.' },
  'rm-mate-27': { introduction: 'Jde o vytvoření únikového pole pro krále.', question: 'Posunutí pěšce před tvého krále po rošádě, aby vzniklo únikové pole, se nazývá vytvoření:', options: ['Vidličky', 'Vazby', '„Luftu“ (únikového pole)', 'Rožně'], explanation: 'Vytvoření „luftu“ dá králi únikové pole a zabrání matu na základní řadě.' },
  'rm-mate-28': { introduction: 'Zamysli se, co brání králi v úniku.', question: 'Proč král nemůže uniknout matu na základní řadě?', options: ['Je vázán na dámu', 'Nepřátelský král mu brání', 'Je v rohu', 'Jeho vlastní pěšci blokují únikové pole'], explanation: 'Králi vlastní pěšci berou pole vpředu, která by potřeboval k úniku.' },
  'rm-mate-29': { introduction: 'Mat vede podél řady, na které král stojí.', question: 'Podél které linie se dává mat na základní řadě?', options: ['Podél řady, na které král stojí', 'Podél diagonály', 'Podél sloupce, na kterém král stojí', 'Podél středových sloupců'], explanation: 'Matující věž nebo dáma útočí podél králova vlastní řady.' },
  'rm-mate-30': { introduction: 'Nejlepší obrana je předejít slabině předem.', question: 'Nejlepší obranou proti hrozícímu matu na základní řadě je často:', options: ['Postoupit nepřátelské pěšce', 'Vytvořit králi „luft“ předem', 'Slepě vyměnit obě věže', 'Přesunout krále do středu'], explanation: 'Vytvoření „luftu“ předem odstraní slabinu základní řady.' },
  'rm-mate-31': { introduction: 'Pokud lze šach zaclonit, o mat nejde.', question: 'Pokud může obránce vložit věž na základní řadu a šach zaclonit, pak je mat:', options: ['Stále vynucený', 'Automatický', 'Odvrácený (nešlo o skutečný mat)', 'Pat'], explanation: 'Zaclonění znamená, že existoval legální tah, takže o mat nešlo.' },
  'rm-mate-32': { introduction: 'Slabina vzniká po konkrétním tahu krále.', question: 'Slabiny na základní řadě se nejčastěji objevují po kterém tahu krále?', options: ['Po dlouhém pochodu vzhůru po šachovnici', 'Po sebrání na kraji', 'Po výměně dam', 'Po rošádě za nehnutými pěšci'], explanation: 'Rošáda ponechá krále za hradbou pěšců, čímž vzniká riziko matu na základní řadě.' },

  // ── Úroveň 5 — Základní matové vzory ───────────────────────────────────
  'rm-mate-33': { introduction: 'Král s dámou proti samotnému králi je jasná věc.', question: 'Král a dáma proti samotnému králi je:', options: ['Vynucená výhra', 'Vynucená remíza', 'Nelze dát mat', 'Vždy pat'], explanation: 'K+D proti K je elementární vynucený mat.' },
  'rm-mate-34': { introduction: 'Základní koncovka, kterou by měl znát každý.', question: 'Král a věž proti samotnému králi je:', options: ['Remíza', 'Vynucená výhra', 'Nedostatek materiálu', 'Výhra jen se štěstím'], explanation: 'K+V proti K je základní vynucený mat, který by měl znát každý hráč.' },
  'rm-mate-35': { introduction: 'Dva jezdci mají s matem potíže.', question: 'Král a dva jezdci proti samotnému králi obecně jsou:', options: ['Snadný vynucený mat', 'Rychlá výhra', 'Nelze vynutit mat', 'Nelegální'], explanation: 'Dva jezdci a král nemohou vynutit mat proti samotnému králi.' },
  'rm-mate-36': { introduction: 'Dvojice střelců mat zvládne.', question: 'Král a dva střelci proti samotnému králi je:', options: ['Remíza', 'Nemožné', 'Výhra jen s pěšcem', 'Vynucená výhra'], explanation: 'K + dva střelci proti K je vyhratelný, vynucený mat.' },
  'rm-mate-37': { introduction: 'Osamělého krále je třeba zatlačit.', question: 'Při matu králem a dámou je nepřátelský král obvykle zahnán:', options: ['Ke kraji nebo do rohu', 'Do středu', 'Na výchozí pole', 'Na otevřený sloupec'], explanation: 'Dáma a král zatlačí samotného krále ke kraji šachovnice, aby ho zmatovali.' },
  'rm-mate-38': { introduction: 'Tento mat je vynucený, ale vyžaduje techniku.', question: 'Král, střelec a jezdec proti samotnému králi je:', options: ['Remíza', 'Vynucená výhra (i když záludná)', 'Nemožné', 'Výhra jen s dámou'], explanation: 'Mat střelcem a jezdcem je skutečná vynucená výhra, i když vyžaduje techniku.' },
  'rm-mate-39': { introduction: 'Samotný král nemá čím dát mat.', question: 'Může samotný král dát mat jinému samotnému králi?', options: ['Ano, snadno', 'Někdy', 'Ne, je to nemožné', 'Jen v rohu'], explanation: 'Samotný král nemůže nikdy dát mat.' },
  'rm-mate-40': { introduction: 'Vzpomeň si na pojem „opozice“.', question: 'Při matu králem a věží stojí oba králové často v „opozici“, což znamená, že jsou:', options: ['Na stejném poli', 'Diagonálně a daleko od sebe', 'Na opačných stranách šachovnice', 'Přímo proti sobě s jedním polem mezi nimi'], explanation: 'Opozice je, když králové stojí proti sobě s jedním polem mezi sebou.' },

  // ── Úroveň 6 — Co je pat? ──────────────────────────────────────
  'rm-mate-41': { introduction: 'Klíčové je, že strana na tahu nemá tah, ale není v šachu.', question: 'Co je pat?', options: ['Strana na tahu nemá legální tah a NENÍ v šachu', 'Král dostal mat', 'Král sebrán na kraji', 'Opakovaná pozice'], explanation: 'Pat je situace, kdy nemáš žádný legální tah a přitom nejsi v šachu.' },
  'rm-mate-42': { introduction: 'Pat má jasný výsledek.', question: 'Jaký je výsledek patu?', options: ['Patovaná strana prohrává', 'Partie je remíza', 'Silnější strana vyhrává', 'Hra pokračuje'], explanation: 'Pat okamžitě ukončí partii remízou.' },
  'rm-mate-43': { introduction: 'Rozdíl je v tom, zda je král napaden.', question: 'Klíčový rozdíl mezi patem a matem je v tom, zda je král:', options: ['Na základní řadě', 'Poblíž věže', 'V šachu', 'Po rošádě'], explanation: 'Žádný legální tah s králem v šachu je mat; bez šachu jde o pat.' },
  'rm-mate-44': { introduction: 'Při patu nezbývá vůbec žádný tah.', question: 'Při patu má strana na tahu:', options: ['Jeden legální tah', 'Jen tah krále', 'Několik legálních tahů', 'Vůbec žádný legální tah'], explanation: 'Pat znamená, že není k dispozici žádný legální tah.' },
  'rm-mate-45': { introduction: 'Patovat soupeře, když snadno vyhráváš, je chyba.', question: 'Pokud snadno vyhráváš, patovat soupeře je:', options: ['Chyba, která zahodí výhru', 'Rychlejší cesta k výhře', 'Stále výhra', 'Vyžadováno pravidly'], explanation: 'Nechtěný pat promění výhru v remízu, takže je to nákladná chyba.' },
  'rm-mate-46': { introduction: 'Hráč jen s králem a bez tahu, mimo šach.', question: 'Hráč, který má jen krále a žádný legální tah, a přitom není v šachu, dosáhl:', options: ['Matu', 'Patu', 'Výhry', 'Trojího opakování'], explanation: 'Žádný tah a žádný šach je definice patu.' },
  'rm-mate-47': { introduction: 'Spoj správně podmínky s výsledkem.', question: 'Která dvojice je správná?', options: ['Žádný tah + v šachu = remíza', 'Žádný tah + ne v šachu = výhra', 'Žádný tah + ne v šachu = remíza (pat)', 'Žádný tah + v šachu = remíza'], explanation: 'Žádný legální tah a přitom ne v šachu je pat, tedy remíza.' },
  'rm-mate-48': { introduction: 'Pat se nejčastěji objevuje s málo figurami.', question: 'Pat se nejčastěji vyskytuje v které fázi partie?', options: ['V zahájení', 'V prvních pár tazích', 'Hned po rošádě', 'V koncovce s málo figurami'], explanation: 'Když zbývá málo materiálu, zahnaný král může snadno nemít žádný legální tah.' },

  // ── Úroveň 7 — Remízy a opakování ──────────────────────────────────────
  'rm-mate-49': { introduction: 'Trojí opakování téže pozice umožňuje nárok.', question: 'Trojí zopakování téže pozice umožňuje nárokovat:', options: ['Remízu trojím opakováním', 'Mat', 'Výhru opakováním', 'Pat'], explanation: 'Pravidlo trojího opakování umožňuje hráči nárokovat remízu.' },
  'rm-mate-50': { introduction: 'Pravidlo padesáti tahů se týká pěšců a braní.', question: 'Pravidlo padesáti tahů umožňuje remízu, když se po dobu žádného braní ani tahu pěšcem odehraje:', options: ['Padesát sekund', 'Padesát tahů každou stranou', 'Pět tahů', 'Patnáct tahů'], explanation: 'Pokud uplyne 50 tahů bez tahu pěšcem nebo braní, lze nárokovat remízu.' },
  'rm-mate-51': { introduction: 'Se dvěma králi nelze dát mat.', question: 'Král proti králi je remíza z důvodu:', options: ['Trojího opakování', 'Pravidla padesáti tahů', 'Nedostatku materiálu', 'Jen patu'], explanation: 'Jen se dvěma králi je mat nemožný, takže jde o nedostatek materiálu.' },
  'rm-mate-52': { introduction: 'Hráči se mohou na remíze prostě dohodnout.', question: 'Oba hráči se mohou jednoduše dohodnout na smírném ukončení partie. To je remíza:', options: ['Opakováním', 'Nedostatkem materiálu', 'Pravidlem padesáti tahů', 'Vzájemnou dohodou'], explanation: 'Hráči se mohou na remíze dohodnout kdykoli.' },
  'rm-mate-53': { introduction: 'Samotný střelec nedokáže vynutit mat.', question: 'Která z těchto možností je remíza z důvodu nedostatku materiálu?', options: ['Král a střelec proti králi', 'Král a věž proti králi', 'Král a dáma proti králi', 'Král a dva střelci proti králi'], explanation: 'Samotný střelec nedokáže vynutit mat, takže K+S proti K je remíza.' },
  'rm-mate-54': { introduction: 'Nekonečné šachy opakují pozici.', question: 'Věčný šach, kdy jedna strana šachuje donekonečna, obvykle vede k remíze cestou:', options: ['Matu', 'Trojího opakování', 'Výhry šachujícího', 'Jen pravidla padesáti tahů'], explanation: 'Nekonečné šachování opakuje pozici a remizuje opakováním.' },
  'rm-mate-55': { introduction: 'Samotný jezdec na mat nestačí.', question: 'Král a jezdec proti králi je:', options: ['Vynucená výhra', 'Pat', 'Remíza pro nedostatek materiálu', 'Mat na základní řadě'], explanation: 'Samotný jezdec nedokáže vynutit mat, takže je partie remíza.' },
  'rm-mate-56': { introduction: 'Král se nikdy neseber.', question: 'Která z možností NENÍ uznávaný způsob remízy partie?', options: ['Pat', 'Trojí opakování', 'Nedostatek materiálu', 'Sebrání krále'], explanation: 'Král se nikdy nesebere; to není způsob remízy.' },

  // ── Úroveň 8 — Mat vs. pat ───────────────────────────────────
  'rm-mate-57': { introduction: 'Žádný tah a přitom v šachu.', question: 'Král bez legálního tahu, který je právě v šachu, je:', options: ['Mat (prohra)', 'Pat (remíza)', 'Věčný šach', 'Nedostatek materiálu'], explanation: 'Žádný legální tah spolu s tím, že je král v šachu, znamená mat, tedy prohru.' },
  'rm-mate-58': { introduction: 'Žádný tah a přitom mimo šach.', question: 'Král bez legálního tahu, který NENÍ v šachu, je:', options: ['Mat (prohra)', 'Pat (remíza)', 'Výhra', 'Opakování'], explanation: 'Žádný legální tah a přitom ne v šachu je pat, tedy remíza.' },
  'rm-mate-59': { introduction: 'Nech soupeři tah, dokud nemůžeš dát mat.', question: 'Abys proměnil patovou past ve skutečnou výhru, měl bys zajistit, aby nepřátelský král:', options: ['Neměl vůbec žádná pole', 'Byl ve středu', 'Měl legální tah, dokud mu nemůžeš dát šach', 'Měl pěšce navíc'], explanation: 'Ponechání tahu soupeři zabrání patu, dokud nemůžeš skutečně dát mat.' },
  'rm-mate-60': { introduction: 'Zahnaný král, který ale není napaden.', question: 'Samotný král zahnaný do rohu se všemi únikovými poli pokrytými, ale bez napadení, dává jaký výsledek?', options: ['Mat', 'Výhru pro útočníka', 'Věčný šach', 'Pat (remíza)'], explanation: 'Zahnaný do rohu bez toho, aby byl v šachu, znamená pat, takže je partie remíza.' },
  'rm-mate-61': { introduction: 'Začátečníci často patují místo matu.', question: 'Proč začátečníci často remizují vyhrané koncovky K+D proti K?', options: ['Omylem patují samotného krále', 'Dojdou jim šachy', 'Dáma je příliš slabá', 'Pravidlo mat zakazuje'], explanation: 'Neopatrná hra může vzít každé pole bez šachu, čímž vznikne pat.' },
  'rm-mate-62': { introduction: 'Rozdíl je jen v tom, zda je král napaden.', question: 'Při matu je prohrávající král napaden; při patu je uvázlý král:', options: ['Rovněž napaden', 'Nenapaden', 'Už sebrán', 'Vázán na věž'], explanation: 'Určujícím rozdílem je, že patovaný král není v šachu.' },
  'rm-mate-63': { introduction: 'Táž pozice může být výhra i remíza.', question: 'Táž pozice „bez legálního tahu“ může být výhrou i remízou podle toho:', options: ['Kolik je pěšců', 'Podle hodin', 'Zda je král v šachu', 'Kdo má více figur'], explanation: 'Šach z toho dělá mat (výhru); bez šachu jde o pat (remízu).' },
  'rm-mate-64': { introduction: 'Drž dámu ve vzdálenosti jezdcova skoku od krále.', question: 'Při matu dámou je bezpečnou technikou držet dámu ve vzdálenosti jezdcova skoku od nepřátelského krále, dokud nepřijde tvůj král, což pomáhá vyhnout se:', options: ['Trojímu opakování', 'Remíze podle pravidla padesáti tahů', 'Matu na základní řadě', 'Nechtěnému patu'], explanation: 'Udržování vzdálenosti jezdcova skoku ponechává králi pole a zabraňuje patu.' },

  // ── Úroveň 9 — Běžné matové sítě ──────────────────────────────────
  'rm-mate-65': { introduction: 'Tento mat dává skákavá figura.', question: 'Udušený mat dává která figura?', options: ['Jezdec', 'Věž', 'Střelec', 'Dáma'], explanation: 'Udušený mat je šach jezdcem králi, který je uzavřen vlastními figurami.' },
  'rm-mate-66': { introduction: 'Krále obklopují jeho vlastní figury.', question: 'Při udušeném matu je zmatovaný král obklopen:', options: ['Nepřátelskými pěšci', 'Vlastními figurami', 'Volnými poli', 'Dvěma věžemi'], explanation: 'Král nemůže utéct, protože jeho vlastní figury mu zahradí každé únikové pole.' },
  'rm-mate-67': { introduction: 'Školský mat míří na jedno slabé pole u krále.', question: 'Takzvaný „školský mat“ míří na které slabé pole na počátku partie?', options: ['d5', 'h7', 'f7 (f2 pro bílého)', 'a8'], explanation: 'Školský mat využívá dámu a střelce k úderu na zranitelné pole f7.' },
  'rm-mate-68': { introduction: 'Jde o tlačení krále dvěma těžkými figurami.', question: 'Takzvaný „žebříkový“ mat (též „sekačka“) se obvykle provádí:', options: ['Jezdcem a střelcem', 'Jediným pěšcem', 'Samotnou dámou', 'Dvěma věžemi (nebo věží a dámou)'], explanation: 'Dvě těžké figury tlačí krále řadu po řadě po šachovnici až k matu.' },
  'rm-mate-69': { introduction: 'Nejjednodušší obrana je vytvořit únikové pole.', question: 'Motiv „matu na základní řadě“ se nejjednodušeji zastaví:', options: ['Vytvořením „luftu“ pro krále', 'Postupem všech pěšců', 'Výměnou jen dam', 'Přesunem krále na kraj'], explanation: 'Pole „luft“ dá králi únikové pole mimo základní řadu.' },
  'rm-mate-70': { introduction: 'Krytá dáma přímo vedle krále je klasický vzor.', question: 'Krytá dáma zahraná přímo vedle nepřátelského krále, která bere každé únikové pole, je běžný vzor pro:', options: ['Pat', 'Rychlý vynucený mat', 'Remízu', 'Věčný šach'], explanation: 'Krytá dáma vedle krále, která pokrývá jeho pole, je klasický mat.' },
  'rm-mate-71': { introduction: 'Nejrychlejší možný mat dává jedna figura.', question: 'Bláznův mat, nejrychlejší možný mat, dává:', options: ['Jezdec', 'Věž', 'Dáma', 'Střelec'], explanation: 'Bláznův mat je mat dámou proti velmi oslabenému králi ve dvou tazích.' },
  'rm-mate-72': { introduction: 'Anastáziin mat kombinuje jezdce a jednu figuru na sloupci.', question: 'Anastáziin mat je známý vzor kombinující jezdce a kterou figuru podél sloupce?', options: ['Pěšce', 'Střelce', 'Druhého jezdce', 'Věž'], explanation: 'Anastáziin mat spojuje jezdce s věží, aby uvěznil krále na kraji.' },

  // ── Úroveň 10 — Mistrovství v matu ──────────────────────────────────
  'rm-mate-73': { introduction: 'Vzpomeň si, co proti jezdcovu šachu nefunguje.', question: 'Král je v šachu od jezdce na sousedním poli. Která možnost NENÍ možná?', options: ['Zaclonění šachu od jezdce', 'Přesun krále', 'Sebrání jezdce', 'Jakákoli legální odpověď odstraňující šach'], explanation: 'Šach od jezdce nelze nikdy zaclonit, takže vložení figury je nemožné.' },
  'rm-mate-74': { introduction: 'Bez šachu vzniká pat, ne výhra.', question: 'Máš K+D proti K a vezmeš samotnému králi poslední pole, aniž bys dal šach. Výsledek je:', options: ['Vyhráváš', 'Remíza patem', 'Trojí opakování', 'Mat na základní řadě'], explanation: 'Žádný tah bez šachu je pat, který zremizuje vyhranou pozici.' },
  'rm-mate-75': { introduction: 'Hledej šach bez jakéhokoli legálního tahu.', question: 'Která kombinace faktů popisuje skutečný mat?', options: ['Král není v šachu, má jeden tah', 'Král v šachu, může sebrat útočníka', 'Král v šachu, neexistuje žádný legální tah', 'Král není v šachu, žádný legální tah'], explanation: 'Mat je neuniknutelný šach bez jakéhokoli legálního tahu.' },
  'rm-mate-76': { introduction: 'Pokud lze šach zaclonit, o mat nejde.', question: 'Věž šachuje krále po rošádě podél základní řady; obránce má střelce, kterým může zaclonit. To znamená, že pozice je:', options: ['Mat', 'Pat', 'Remíza', 'Ne mat, protože šach lze zaclonit'], explanation: 'Protože existuje legální zaclonění, jde jen o šach, ne o mat.' },
  'rm-mate-77': { introduction: 'Dva jezdci nedokážou vynutit mat.', question: 'Která koncovka je remíza i při nejlepší hře?', options: ['Král a dva jezdci proti samotnému králi', 'Král a věž proti samotnému králi', 'Král a dáma proti samotnému králi', 'Král a dva střelci proti samotnému králi'], explanation: 'Dva jezdci nedokážou vynutit mat proti samotnému králi, takže jde o remízu.' },
  'rm-mate-78': { introduction: 'Král uzavřený vlastními figurami je udušen.', question: 'Jezdec dává šach králi uzavřenému na h8 vlastní věží na g8 a pěšci na g7/h7. To je:', options: ['Pat', 'Udušený mat', 'Zaclonitelný šach', 'Věčný šach'], explanation: 'Král je udušen svými vlastními figurami a zmatován jezdcem.' },
  'rm-mate-79': { introduction: 'Padesát tahů bez pěšce a braní.', question: 'Žádný pěšec se nepohnul a žádné braní se neodehrálo po dobu padesáti tahů každou stranou. Hráč může nárokovat:', options: ['Výhru', 'Mat', 'Remízu podle pravidla padesáti tahů', 'Nedostatek materiálu'], explanation: 'Pravidlo padesáti tahů umožňuje v této situaci nárokovat remízu.' },
  'rm-mate-80': { introduction: 'Trojí opakování téže pozice umožňuje remízu.', question: 'Jsi o dámu napřed, ale honěním krále potřetí zopakuješ identickou pozici. Soupeř teď může nárokovat:', options: ['Výhru pro tebe', 'Mat', 'Nedostatek materiálu', 'Remízu trojím opakováním'], explanation: 'Dosažení téže pozice potřetí umožňuje nárokovat remízu trojím opakováním.' },
};
