// The Muscular System roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const muscularSystemSeeds: Seed[] = [
  // ── Level 1 — Muscle types & properties ──
  { q: 'How many main types of muscle tissue does the human body have?', opts: ['Two', 'Three', 'Four', 'Five'], a: 1, e: 'The body has three muscle types: skeletal, smooth, and cardiac.', tags: ['Muscular System', 'Muscle types'] },
  { q: 'Which muscle type is under voluntary (conscious) control?', opts: ['Skeletal', 'Smooth', 'Cardiac', 'All of them'], a: 0, e: 'Skeletal muscle is voluntary; smooth and cardiac muscle work automatically.', tags: ['Muscular System', 'Muscle types'] },
  { q: 'Which muscle type is found only in the heart?', opts: ['Skeletal', 'Smooth', 'Cardiac', 'Visceral'], a: 2, e: 'Cardiac muscle occurs only in the heart wall and contracts rhythmically without tiring.', tags: ['Muscular System', 'Muscle types'] },
  { q: 'Which muscle type lines the walls of hollow organs such as the stomach and blood vessels?', opts: ['Skeletal', 'Smooth', 'Cardiac', 'Striated'], a: 1, e: 'Smooth muscle forms the walls of hollow organs and blood vessels, moving contents involuntarily.', tags: ['Muscular System', 'Muscle types'] },
  { q: 'Which two muscle types appear striped (striated) under a microscope?', opts: ['Smooth and cardiac', 'Skeletal and smooth', 'Skeletal and cardiac', 'Only skeletal'], a: 2, e: 'Skeletal and cardiac muscle both show striations; smooth muscle looks uniform and non-striated.', tags: ['Muscular System', 'Muscle types'] },
  { q: 'Which muscle type is made of spindle-shaped cells with a single central nucleus?', opts: ['Smooth', 'Skeletal', 'Cardiac', 'Tendon'], a: 0, e: 'Smooth muscle cells are tapered (spindle-shaped) with one central nucleus each.', tags: ['Muscular System', 'Muscle types'] },
  { q: 'The ability of a muscle to shorten and generate force is called', opts: ['Elasticity', 'Contractility', 'Excitability', 'Extensibility'], a: 1, e: 'Contractility is the muscle property of actively shortening to produce force and movement.', tags: ['Muscular System', 'Properties'] },
  { q: 'Roughly what proportion of total body mass is skeletal muscle in an adult?', opts: ['About 10%', 'About 40%', 'About 70%', 'About 90%'], a: 1, e: 'Skeletal muscle makes up roughly 40% of body mass, the largest single tissue group.', tags: ['Muscular System', 'Muscle types'] },

  // ── Level 2 — Skeletal muscle structure ──
  { q: 'A single skeletal muscle cell is also called a muscle', opts: ['Fiber', 'Fascicle', 'Tendon', 'Sarcomere'], a: 0, e: 'Each long, cylindrical skeletal muscle cell is called a muscle fiber.', tags: ['Muscular System', 'Structure'] },
  { q: 'How many nuclei does a mature skeletal muscle fiber contain?', opts: ['None', 'One', 'Two', 'Many'], a: 3, e: 'Skeletal muscle fibers are multinucleate, formed by the fusion of many precursor cells.', tags: ['Muscular System', 'Structure'] },
  { q: 'The plasma membrane of a muscle fiber is called the', opts: ['Sarcolemma', 'Sarcoplasm', 'Endomysium', 'Myofibril'], a: 0, e: 'The sarcolemma is the specialized plasma membrane surrounding a muscle fiber.', tags: ['Muscular System', 'Structure'] },
  { q: 'Long thread-like bundles of contractile proteins inside a muscle fiber are called', opts: ['Myofibrils', 'Tendons', 'Fascicles', 'Neurons'], a: 0, e: 'Myofibrils are the rod-like contractile bundles that fill most of a muscle fiber.', tags: ['Muscular System', 'Structure'] },
  { q: 'The repeating structural and functional contractile unit of a myofibril is the', opts: ['Sarcomere', 'Sarcolemma', 'Fascicle', 'Nucleus'], a: 0, e: 'The sarcomere is the basic repeating contractile unit that gives striated muscle its bands.', tags: ['Muscular System', 'Sarcomere'] },
  { q: 'Which protein makes up the thick filaments of the sarcomere?', opts: ['Myosin', 'Actin', 'Troponin', 'Tropomyosin'], a: 0, e: 'Thick filaments are built from myosin, whose heads pull on the thin filaments.', tags: ['Muscular System', 'Sarcomere'] },
  { q: 'Which protein makes up the thin filaments of the sarcomere?', opts: ['Actin', 'Myosin', 'Collagen', 'Keratin'], a: 0, e: 'Thin filaments are made mainly of actin, along with the regulatory proteins troponin and tropomyosin.', tags: ['Muscular System', 'Sarcomere'] },
  { q: 'A sarcomere is defined as the region between two', opts: ['Z lines (Z discs)', 'A bands', 'H zones', 'Sarcolemmas'], a: 0, e: 'Each sarcomere stretches from one Z line (Z disc) to the next, anchoring the thin filaments.', tags: ['Muscular System', 'Sarcomere'] },

  // ── Level 3 — Sliding filament theory ──
  { q: 'According to the sliding filament theory, during contraction the filaments', opts: ['Slide past each other', 'Shorten individually', 'Break apart', 'Swap places'], a: 0, e: 'The filaments themselves do not shorten; thin and thick filaments slide past each other, shortening the sarcomere.', tags: ['Muscular System', 'Contraction'] },
  { q: 'Which ion is released to trigger skeletal muscle contraction?', opts: ['Sodium', 'Calcium', 'Potassium', 'Chloride'], a: 1, e: 'Calcium ions (Ca2+) released from the sarcoplasmic reticulum initiate contraction.', tags: ['Muscular System', 'Contraction'] },
  { q: 'Inside a muscle fiber, calcium is stored in and released from the', opts: ['Sarcoplasmic reticulum', 'Nucleus', 'Mitochondria', 'Golgi apparatus'], a: 0, e: 'The sarcoplasmic reticulum is the calcium store that surrounds each myofibril.', tags: ['Muscular System', 'Contraction'] },
  { q: 'Released calcium binds to which regulatory protein on the thin filament?', opts: ['Troponin', 'Myosin', 'Actin', 'Titin'], a: 0, e: 'Calcium binds troponin, which then shifts tropomyosin away from the myosin-binding sites.', tags: ['Muscular System', 'Contraction'] },
  { q: 'When calcium binds troponin, tropomyosin moves in order to', opts: ['Expose the myosin-binding sites on actin', 'Cut the actin filament', 'Store more calcium', 'Block the nerve signal'], a: 0, e: 'Tropomyosin slides aside, uncovering binding sites so myosin heads can attach to actin.', tags: ['Muscular System', 'Contraction'] },
  { q: 'The connection formed when a myosin head attaches to actin is called a', opts: ['Cross-bridge', 'Synapse', 'Z line', 'Motor unit'], a: 0, e: 'A cross-bridge is the temporary link between a myosin head and actin that drives the power stroke.', tags: ['Muscular System', 'Contraction'] },
  { q: 'Which molecule provides the energy for the myosin power stroke and for detachment?', opts: ['ATP', 'DNA', 'Glucose directly', 'Water'], a: 0, e: 'ATP powers the power stroke and is required for the myosin head to detach and reset.', tags: ['Muscular System', 'Contraction'] },
  { q: 'Which neurotransmitter is released at the neuromuscular junction to excite skeletal muscle?', opts: ['Acetylcholine', 'Dopamine', 'Serotonin', 'Adrenaline'], a: 0, e: 'Motor neurons release acetylcholine (ACh) at the neuromuscular junction, triggering the muscle impulse.', tags: ['Muscular System', 'Contraction'] },

  // ── Level 4 — Major muscles & movements ──
  { q: 'The biceps brachii mainly produces which movement at the elbow?', opts: ['Flexion', 'Extension', 'Rotation', 'Abduction'], a: 0, e: 'The biceps brachii flexes the elbow, bending the forearm toward the upper arm.', tags: ['Muscular System', 'Major muscles'] },
  { q: 'The triceps brachii mainly produces which movement at the elbow?', opts: ['Extension', 'Flexion', 'Abduction', 'Rotation'], a: 0, e: 'The triceps extends (straightens) the elbow and acts as the antagonist to the biceps.', tags: ['Muscular System', 'Major muscles'] },
  { q: 'The quadriceps, on the front of the thigh, act to', opts: ['Extend the knee', 'Flex the knee', 'Rotate the hip', 'Point the foot'], a: 0, e: 'The quadriceps straighten (extend) the knee, essential for standing, walking, and kicking.', tags: ['Muscular System', 'Major muscles'] },
  { q: 'The hamstrings, on the back of the thigh, act to', opts: ['Flex the knee', 'Extend the knee', 'Abduct the arm', 'Elevate the jaw'], a: 0, e: 'The hamstrings flex the knee (and extend the hip), opposing the quadriceps.', tags: ['Muscular System', 'Major muscles'] },
  { q: 'The gastrocnemius (calf muscle) produces which movement at the ankle?', opts: ['Plantar flexion (pointing the toes)', 'Dorsiflexion', 'Knee extension', 'Hip rotation'], a: 0, e: 'The gastrocnemius plantar flexes the ankle, pointing the foot for pushing off and jumping.', tags: ['Muscular System', 'Major muscles'] },
  { q: 'The deltoid, capping the shoulder, chiefly acts to', opts: ['Abduct the arm', 'Flex the elbow', 'Extend the knee', 'Rotate the head'], a: 0, e: 'The deltoid abducts the arm, lifting it away from the side at the shoulder.', tags: ['Muscular System', 'Major muscles'] },
  { q: 'The gluteus maximus mainly produces which movement at the hip?', opts: ['Extension', 'Flexion', 'Plantar flexion', 'Pronation'], a: 0, e: 'The gluteus maximus extends the hip, powering rising from a squat, climbing, and running.', tags: ['Muscular System', 'Major muscles'] },
  { q: 'The masseter is a strong muscle that acts mainly to', opts: ['Close the jaw for chewing', 'Blink the eye', 'Turn the head', 'Flex the wrist'], a: 0, e: 'The masseter elevates the mandible to close the jaw, a key muscle of chewing (mastication).', tags: ['Muscular System', 'Major muscles'] },

  // ── Level 5 — Energy, fatigue & physiology ──
  { q: 'What is the immediate energy molecule used directly for muscle contraction?', opts: ['ATP', 'Glucose', 'Fat', 'Protein'], a: 0, e: 'ATP is the direct energy source; other fuels must first be used to regenerate ATP.', tags: ['Muscular System', 'Energy'] },
  { q: 'Which high-energy compound rapidly regenerates ATP during short, intense bursts of activity?', opts: ['Creatine phosphate', 'Insulin', 'Collagen', 'Glycogen synthase'], a: 0, e: 'Creatine phosphate (phosphocreatine) quickly rephosphorylates ADP to ATP for the first seconds of intense effort.', tags: ['Muscular System', 'Energy'] },
  { q: 'During intense exercise with too little oxygen, glucose is broken down anaerobically, producing', opts: ['Lactic acid', 'Pure water', 'Extra oxygen', 'Creatine'], a: 0, e: 'Anaerobic glycolysis yields ATP quickly but produces lactic acid (lactate), contributing to muscle fatigue.', tags: ['Muscular System', 'Energy'] },
  { q: 'Which fiber type is fatigue-resistant and best suited to endurance activity?', opts: ['Slow-twitch (Type I)', 'Fast-twitch (Type II)', 'Smooth muscle', 'Cardiac fibers'], a: 0, e: 'Slow-twitch (Type I) fibers are rich in mitochondria and myoglobin, resisting fatigue for endurance work.', tags: ['Muscular System', 'Physiology'] },
  { q: 'Fast-twitch (Type II) fibers are specialized for', opts: ['Rapid, powerful contractions', 'Long endurance', 'Storing calcium', 'Digesting food'], a: 0, e: 'Fast-twitch fibers contract quickly and powerfully but fatigue rapidly, ideal for sprinting and lifting.', tags: ['Muscular System', 'Physiology'] },
  { q: 'Which protein stores oxygen inside muscle and gives red muscle its color?', opts: ['Myoglobin', 'Hemoglobin', 'Keratin', 'Tropomyosin'], a: 0, e: 'Myoglobin binds and stores oxygen within muscle fibers, giving endurance muscle its red color.', tags: ['Muscular System', 'Physiology'] },
  { q: 'Muscle fatigue during prolonged activity is caused mainly by', opts: ['Depleted ATP and ion or metabolite buildup', 'Too much oxygen', 'Extra calcium storage', 'Increased bone density'], a: 0, e: 'Fatigue results from depleted energy stores and the buildup of ions and metabolites that impair contraction.', tags: ['Muscular System', 'Physiology'] },
  { q: 'Rigor mortis stiffens muscles after death because', opts: ['No ATP is available to detach myosin from actin', 'Too much ATP is made', 'Calcium is removed', 'Nerves keep firing'], a: 0, e: 'Without ATP, cross-bridges cannot release, so myosin stays locked to actin and the muscles stiffen.', tags: ['Muscular System', 'Physiology'] },
];
