// General web/dev knowledge roadmap questions (120): 15 levels × 8, easiest →
// hardest. Conceptual coverage of how the web actually works: clients, servers,
// HTTP, browser rendering, code execution, frameworks, APIs, caching, auth,
// databases, deployment, and performance.

import type { Seed } from './roadmap-build';

export const generalSeeds: Seed[] = [
  // ── Level 1 — How the Web Works ────────────────────────────────────────
  { q: 'A browser has a hostname but no cached address for it. Which lookup must happen before it can connect to the site?', opts: ['Render the document to discover the server address', 'Resolve the hostname to an IP address through DNS', 'Download the site’s CSS to identify its origin', 'Ask the destination server to generate its TLS certificate'], a: 1, e: 'DNS resolution maps the hostname to an IP address. The browser can then open a connection and, for HTTPS, perform the TLS handshake.', tags: ['General', 'Web Basics'] },
  { q: 'How does the World Wide Web relate to the internet?', opts: ['They are two names for the same single protocol', 'The web is a system of linked resources and apps that uses internet protocols such as HTTP', 'The internet runs inside web browsers and cannot carry other traffic', 'The web is the physical network, while the internet is only its HTML documents'], a: 1, e: 'The internet is the underlying network of networks. The web is one service on it, built around URLs, HTTP, and linked resources.', tags: ['General', 'Web Basics'] },
  { q: 'The first HTML response references CSS, JavaScript, fonts, and images from the same host. Together, what do these resources form?', opts: ['One executable binary that the browser installs', 'A website served as a collection of documents and assets', 'A relational database copied into the browser', 'A browser extension tied to one origin'], a: 1, e: 'A website is normally a set of resources. The browser parses the HTML and fetches the referenced assets to assemble the page.', tags: ['General', 'Web Basics'] },
  { q: 'Which file does a browser usually request first for a page?', opts: ['style.css', 'main.js', 'The HTML document', 'favicon.ico'], a: 2, e: 'The HTML comes first; the browser parses it to discover the CSS, JS, and image URLs to fetch next.', tags: ['General', 'Web Basics'] },
  { q: 'Which pair is cross-origin according to browser security rules?', opts: ['`https://app.example.com/a` and `https://app.example.com/b`', '`https://app.example.com` and `https://api.example.com`', '`https://app.example.com/a?q=1` and the same URL with `q=2`', '`https://app.example.com` and the same URL with a different fragment'], a: 1, e: 'An origin is the scheme, host, and port tuple. Changing the host from `app` to `api` creates a different origin even under the same parent domain.', tags: ['General', 'Web Basics'] },
  { q: 'Why can JavaScript from one origin not freely read a signed-in user’s data from another origin?', opts: ['DNS refuses to resolve two hostnames for one browser tab', 'The same-origin policy creates a browser security boundary for cross-origin reads', 'TLS encrypts responses so browser JavaScript cannot inspect them', 'HTTP allows only one origin to be open at a time'], a: 1, e: 'The same-origin policy prevents a malicious page from reading another site’s protected responses. CORS lets the target origin explicitly relax that rule.', tags: ['General', 'Web Basics'] },
  { q: 'Two identical HTTP requests arrive from the same browser. Why does the protocol alone not tell the server that they belong to one signed-in user?', opts: ['HTTP requires a new DNS record for every request', 'HTTP is stateless; the application must attach state such as a session cookie or token', 'Browsers remove all headers after the first request to an origin', 'The server may associate requests only by their TCP port number'], a: 1, e: 'HTTP requests do not carry built-in memory of earlier requests. Applications add continuity with cookies, tokens, or other identifiers.', tags: ['General', 'Web Basics'] },
  { q: 'A user moves from `http://example.com` to `https://example.com`. What security property is added in transit?', opts: ['The server is guaranteed to have no application vulnerabilities', 'TLS encrypts and authenticates the connection and protects it from tampering', 'The browser no longer needs DNS to reach the host', 'Every resource becomes available offline in the browser cache'], a: 1, e: 'HTTPS is HTTP over TLS. TLS provides confidentiality, server authentication, and integrity for traffic in transit; it does not make the application itself bug-free.', tags: ['General', 'Web Basics'] },

  // ── Level 2 — Clients & Servers ────────────────────────────────────────
  { q: 'Who initiates communication: the client or the server?', opts: ['The server', 'The client', 'Both at random', 'Neither — it’s peer-to-peer'], a: 1, e: 'Classic web is a request/response model; the client sends a request, the server replies.', tags: ['General', 'Client/Server'] },
  { q: 'What is a "web server" in one sentence?', opts: ['A specific OS', 'A program that listens for HTTP requests and returns responses', 'A type of router', 'A relational database'], a: 1, e: 'A web server is software (e.g. nginx, Express, Spring) that handles HTTP requests on a network port.', tags: ['General', 'Client/Server'] },
  { q: 'What is a "client" in web terms?', opts: ['The marketing team', 'Anything that initiates a request — usually a browser, app, or curl', 'A database', 'A CDN'], a: 1, e: 'A client is the requester. The most common one is the browser, but any HTTP-speaking program qualifies.', tags: ['General', 'Client/Server'] },
  { q: 'When an HTTP server has prepared a response, how does it know where to send it?', opts: ['It sends the response back over the same TCP connection the request arrived on', 'It looks up the client\'s hostname in DNS', 'It broadcasts the response to all connected clients', 'It uses the user\'s account name stored in a cookie'], a: 0, e: 'Each HTTP request arrives over a connection; the server writes its response back on that same socket, so responses are naturally paired with requests.', tags: ['General', 'Client/Server'] },
  { q: 'Which side typically renders the UI in a "classic" SSR app?', opts: ['The client', 'The server (sends complete HTML)', 'Neither', 'Both must, every time'], a: 1, e: 'Server-side rendering means the HTML is built on the server and shipped fully formed.', tags: ['General', 'Client/Server'] },
  { q: 'Which side renders the UI in a typical SPA?', opts: ['The server', 'The client (browser runs JS to build the DOM)', 'A CDN', 'A worker thread'], a: 1, e: 'A Single-Page App ships a shell and then constructs the UI in the browser using JS.', tags: ['General', 'Client/Server'] },
  { q: 'Several app instances should share one public hostname, TLS policy, and request-routing layer. What can sit in front of them?', opts: ['A forward proxy configured in each end user’s browser', 'A reverse proxy that terminates TLS and routes or balances incoming requests', 'A database replica that accepts the application’s HTTP traffic', 'A build server that compiles the app for every request'], a: 1, e: 'A reverse proxy is a public entry point for servers behind it. It can terminate TLS, route paths, balance traffic, cache responses, and apply common policies.', tags: ['General', 'Client/Server'] },
  { q: 'What does "load balancer" do?', opts: ['Compiles JS faster', 'Spreads incoming requests across multiple server instances', 'Encrypts the DB', 'Logs requests only'], a: 1, e: 'A load balancer distributes traffic so no single server is overwhelmed and so you can scale horizontally.', tags: ['General', 'Client/Server'] },

  // ── Level 3 — HTTP Methods ─────────────────────────────────────────────
  { q: 'Which HTTP method is meant to retrieve a resource without changing it?', opts: ['POST', 'DELETE', 'GET', 'PATCH'], a: 2, e: 'GET should be safe and idempotent — it reads data and shouldn’t cause side effects.', tags: ['General', 'HTTP'] },
  { q: 'Which method is typically used to create a new resource?', opts: ['POST', 'GET', 'HEAD', 'OPTIONS'], a: 0, e: 'POST is the conventional method for "create" or for operations that don’t map cleanly to others.', tags: ['General', 'HTTP'] },
  { q: 'Which method replaces a resource at a known URL with a new representation?', opts: ['POST', 'PUT', 'GET', 'OPTIONS'], a: 1, e: 'PUT replaces the resource at the target URL; it’s idempotent — repeated PUTs land the same final state.', tags: ['General', 'HTTP'] },
  { q: 'Which method is for partial updates to a resource?', opts: ['PATCH', 'PUT', 'GET', 'POST'], a: 0, e: 'PATCH applies a partial modification (e.g. change just one field).', tags: ['General', 'HTTP'] },
  { q: 'Which method removes a resource?', opts: ['DROP', 'DELETE', 'REMOVE', 'CLEAR'], a: 1, e: 'DELETE is the HTTP method for deleting a resource.', tags: ['General', 'HTTP'] },
  { q: 'Which method asks "what would you return for GET?" but without the body?', opts: ['OPTIONS', 'HEAD', 'TRACE', 'CONNECT'], a: 1, e: 'HEAD is identical to GET but the server only returns headers (handy for size/last-modified checks).', tags: ['General', 'HTTP'] },
  { q: 'OPTIONS is mostly used by browsers for what?', opts: ['Saving cookies', 'CORS preflight to check what cross-origin operations are allowed', 'Compression negotiation', 'Caching only'], a: 1, e: 'Browsers send OPTIONS preflights before non-simple cross-origin requests to check CORS permissions.', tags: ['General', 'HTTP'] },
  { q: 'A request is "idempotent" if:', opts: ['Repeating it yields the same effect as doing it once', 'It runs in parallel', 'It must be GET', 'It uses HTTPS'], a: 0, e: 'Idempotent means N identical requests have the same effect as one. GET/PUT/DELETE should be idempotent; POST usually isn’t.', tags: ['General', 'HTTP'] },

  // ── Level 4 — HTTP Status Codes ────────────────────────────────────────
  { q: 'What does HTTP 200 mean?', opts: ['Not found', 'OK — the request succeeded', 'Created', 'Server error'], a: 1, e: '200 OK is the generic success response with a body.', tags: ['General', 'Status'] },
  { q: 'What does HTTP 201 mean?', opts: ['Created — a new resource was created', 'Accepted but not done', 'Continue', 'Not modified'], a: 0, e: '201 Created indicates the request succeeded and produced a new resource (typically with a Location header).', tags: ['General', 'Status'] },
  { q: 'What does HTTP 204 mean?', opts: ['No content — success with no body', 'No-content cache', 'Conflict', 'Method not allowed'], a: 0, e: '204 No Content — request succeeded but there’s nothing to send back.', tags: ['General', 'Status'] },
  { q: 'What does HTTP 301 mean?', opts: ['Moved permanently — use the new URL from now on', 'See other (temporarily)', 'Forbidden', 'Not modified'], a: 0, e: '301 Moved Permanently tells the client (and search engines) the resource has a new permanent URL.', tags: ['General', 'Status'] },
  { q: 'What does HTTP 304 mean?', opts: ['Not modified — your cached copy is still good', 'Temporary redirect', 'Bad gateway', 'Unauthorized'], a: 0, e: '304 Not Modified is returned in response to conditional GETs when the cached version is still valid.', tags: ['General', 'Status'] },
  { q: 'What does HTTP 401 mean?', opts: ['Unauthorized — authentication required', 'Forbidden by policy', 'Page not found', 'OK'], a: 0, e: '401 Unauthorized means "we don’t know who you are" — credentials are missing or invalid.', tags: ['General', 'Status'] },
  { q: 'What does HTTP 403 mean?', opts: ['Forbidden — you are known, but not allowed', 'Authentication failure', 'Not found', 'Conflict'], a: 0, e: '403 Forbidden means the server understands but refuses — usually a permissions issue.', tags: ['General', 'Status'] },
  { q: 'What does HTTP 404 mean?', opts: ['Not found — the resource doesn’t exist at this URL', 'Server crashed', 'Method not allowed', 'Bad request'], a: 0, e: '404 Not Found — the URL doesn’t map to any resource on the server.', tags: ['General', 'Status'] },

  // ── Level 5 — URLs & Routing ───────────────────────────────────────────
  { q: 'In https://app.com:3000/users/42?tab=posts, the "path" is:', opts: ['app.com', 'https', '/users/42', 'tab=posts'], a: 2, e: 'The path is the part between the host:port and the query string — here, /users/42.', tags: ['General', 'URLs'] },
  { q: 'In that URL, "tab=posts" lives in the:', opts: ['Hash', 'Query string', 'Path', 'Host'], a: 1, e: 'Query parameters live after the "?" — they’re commonly used to filter or sort a page.', tags: ['General', 'URLs'] },
  { q: 'What goes after "#" in a URL?', opts: ['The fragment / hash — handled by the client only', 'A query parameter', 'A separate request', 'Nothing valid'], a: 0, e: 'The fragment (e.g. #section) is never sent to the server; the browser uses it to scroll or for client-side routing.', tags: ['General', 'URLs'] },
  { q: 'A "route" in a web framework is:', opts: ['A function name', 'A mapping from URL pattern → handler/page', 'A network packet', 'A database table'], a: 1, e: 'Routing tells the framework which code should respond to a given URL (and method).', tags: ['General', 'URLs'] },
  { q: 'A "dynamic route" like /users/:id means:', opts: [':id is a literal string', 'The :id segment is a parameter the handler can read', 'It’s a 404', 'It’s a redirect'], a: 1, e: 'Colon-prefixed (or bracketed) segments capture a runtime value — e.g. :id matches "42" and exposes id="42".', tags: ['General', 'URLs'] },
  { q: 'A "deep link" is:', opts: ['A URL pointing directly to a specific in-app screen, not just the homepage', 'A broken link', 'A link without a domain', 'An internal-only link'], a: 0, e: 'Deep links jump straight into a specific app state (e.g. /products/42), useful for sharing or notifications.', tags: ['General', 'URLs'] },
  { q: 'What does a 301 redirect mean for SEO?', opts: ['Search engines update their index to the new URL and pass link equity', 'Search engines drop the page', 'No effect at all', 'They split equity 50/50'], a: 0, e: '301 = permanent move; search engines treat the new URL as the canonical destination.', tags: ['General', 'URLs'] },
  { q: 'What problem does "URL encoding" solve?', opts: ['Compresses URLs', 'Lets reserved/unsafe characters travel safely in URLs (e.g. spaces → %20)', 'Encrypts the URL', 'Caches it'], a: 1, e: 'Percent-encoding turns characters that have special URL meaning (or non-ASCII) into a safe %XX form.', tags: ['General', 'URLs'] },

  // ── Level 6 — How Browsers Render ──────────────────────────────────────
  { q: 'After receiving HTML, the browser builds the:', opts: ['CSS only', 'DOM (Document Object Model) tree', 'JIT cache', 'Service Worker'], a: 1, e: 'The HTML parser builds the DOM tree — the in-memory representation of the document.', tags: ['General', 'Browser'] },
  { q: 'From CSS the browser builds the:', opts: ['DOM', 'CSSOM (CSS Object Model)', 'V8 heap', 'TLS cache'], a: 1, e: 'CSSOM is the parsed/normalised stylesheet tree; combined with the DOM it forms the render tree.', tags: ['General', 'Browser'] },
  { q: 'What is "layout" (or reflow) in the browser?', opts: ['Downloading JS', 'Computing positions and sizes of every visible node', 'Decoding images', 'Sending a request'], a: 1, e: 'Layout computes geometry based on DOM + CSSOM — where each box is and how big it is.', tags: ['General', 'Browser'] },
  { q: 'What is "paint"?', opts: ['Filling pixels for each box (colors, text, borders, shadows)', 'Downloading fonts', 'Running JS', 'Connecting to the server'], a: 0, e: 'Paint rasterises the laid-out boxes into actual pixels (often on layers).', tags: ['General', 'Browser'] },
  { q: 'What does "render-blocking CSS" mean?', opts: ['CSS that prevents downloads', 'CSS that the browser must fully load before it can render the first paint', 'CSS that crashes the page', 'CSS only for print'], a: 1, e: 'CSS in <head> blocks the first paint by default because the browser needs styles to build the render tree.', tags: ['General', 'Browser'] },
  { q: 'Why does a synchronous <script> tag block parsing?', opts: ['Browser bug', 'JS may write to the document mid-parse, so the parser must pause to run it', 'Network reasons', 'It’s a CSS rule'], a: 1, e: 'Because document.write() can mutate the doc mid-parse, classic <script> blocks parsing until executed (use async/defer to fix).', tags: ['General', 'Browser'] },
  { q: 'What does the "critical rendering path" describe?', opts: ['A debugging tool', 'The minimum steps + resources needed to render the first pixel', 'A specific framework', 'A type of CDN'], a: 1, e: 'The Critical Rendering Path = the sequence (HTML → CSSOM/DOM → render tree → layout → paint) needed for the first frame.', tags: ['General', 'Browser'] },
  { q: 'What does "hydration" mean for an SSR app?', opts: ['Loading CSS', 'Attaching JS event listeners to server-rendered HTML so it becomes interactive', 'Compressing assets', 'A type of GC'], a: 1, e: 'Hydration takes the static HTML from the server and "wakes it up" by binding React/Vue/etc. to the existing DOM.', tags: ['General', 'Browser'] },

  // ── Level 7 — How Code Runs ────────────────────────────────────────────
  { q: 'Compiled vs interpreted languages — JavaScript is traditionally:', opts: ['Compiled to a machine binary upfront', 'Parsed and executed at runtime (with JIT in modern engines)', 'Neither', 'Both — but only on the server'], a: 1, e: 'JS is parsed and executed by a runtime engine; modern engines (V8, SpiderMonkey) JIT-compile hot code.', tags: ['General', 'Runtimes'] },
  { q: 'What is a "compiler"?', opts: ['A debugger', 'A tool that translates source code into another form (often lower-level)', 'A type of server', 'A bundler'], a: 1, e: 'A compiler translates one language into another (e.g. TS → JS, C → machine code).', tags: ['General', 'Runtimes'] },
  { q: 'What is an "interpreter"?', opts: ['It compiles to GPU', 'A program that reads source and executes it directly, statement by statement', 'A type of router', 'A linter'], a: 1, e: 'Interpreters execute code without producing a separate binary artefact.', tags: ['General', 'Runtimes'] },
  { q: 'What does "JIT compilation" do?', opts: ['Pre-builds everything at install', 'Compiles parts of the program at runtime, often after observing them', 'Skips compilation', 'Is only used in C'], a: 1, e: 'Just-In-Time compilers compile hot code paths while the program runs, balancing startup speed and peak performance.', tags: ['General', 'Runtimes'] },
  { q: 'What does a "bundler" (Vite/Webpack) do?', opts: ['Runs on the server only', 'Combines + transforms source files into optimized assets for the browser', 'Replaces the language runtime', 'Sends notifications'], a: 1, e: 'Bundlers resolve imports, transpile, and emit production-ready JS/CSS the browser can load efficiently.', tags: ['General', 'Runtimes'] },
  { q: 'What is "minification"?', opts: ['Removing whitespace, renaming locals, etc., to shrink JS/CSS size', 'A linting rule', 'A type of cache', 'A test pattern'], a: 0, e: 'Minification rewrites code into an equivalent but smaller form for faster transfer.', tags: ['General', 'Runtimes'] },
  { q: 'What is "transpilation"?', opts: ['Compiling JS to assembly', 'Translating source from one high-level language/version to another (e.g. TS → JS, ES2020 → ES5)', 'A networking term', 'Renaming files'], a: 1, e: 'Transpilation is source-to-source compilation — useful for backward compatibility or language interop.', tags: ['General', 'Runtimes'] },
  { q: 'A "runtime" provides:', opts: ['The OS', 'Built-in APIs and the environment in which code executes (e.g. Node, browser)', 'Only the parser', 'Only the editor'], a: 1, e: 'The runtime supplies host objects (DOM, window) or globals (process, Buffer) plus the engine that runs the code.', tags: ['General', 'Runtimes'] },

  // ── Level 8 — How Frameworks Work ──────────────────────────────────────
  { q: 'A project adopts routing, request handling, configuration conventions, and a standard application structure from one toolkit. What is that toolkit acting as?', opts: ['Only a runtime that executes any program without conventions', 'A web framework that supplies structure and common application plumbing', 'A database driver limited to sending queries', 'A browser engine that renders the server’s source code'], a: 1, e: 'A web framework combines reusable code with conventions for recurring concerns such as routing, rendering, data access, and configuration.', tags: ['General', 'Frameworks'] },
  { q: 'Library vs framework — what is the difference?', opts: ['No difference', 'You call a library; a framework calls you (inversion of control)', 'Libraries are only for backends', 'Frameworks don’t ship code'], a: 1, e: 'With a library, your code is in charge. With a framework, the framework calls your code at the right moments.', tags: ['General', 'Frameworks'] },
  { q: 'A "component" in modern UI frameworks is:', opts: ['A class only', 'A reusable, self-contained unit of UI + behaviour', 'A CSS file', 'A database table'], a: 1, e: 'Components encapsulate markup + style + behaviour and can be composed to build pages.', tags: ['General', 'Frameworks'] },
  { q: 'What is the "virtual DOM"?', opts: ['Another name for the DOM', 'An in-memory representation of the UI used to diff and minimise real-DOM updates', 'A debugger tool', 'A CSS engine'], a: 1, e: 'Frameworks like React keep a virtual DOM and apply just the differences to the real DOM, which is expensive to touch.', tags: ['General', 'Frameworks'] },
  { q: 'A "router" in a framework:', opts: ['Routes electrical signals', 'Maps URL patterns to pages/components', 'Compiles assets', 'Sends emails'], a: 1, e: 'A router decides which view/component renders for a given URL.', tags: ['General', 'Frameworks'] },
  { q: 'A "middleware" function typically:', opts: ['Compiles JS', 'Wraps requests with cross-cutting logic (auth, logging, CORS) and calls next()', 'Boots the database', 'Replaces the OS'], a: 1, e: 'Express-style middleware sits in the request pipeline, optionally short-circuiting or augmenting the response.', tags: ['General', 'Frameworks'] },
  { q: 'What is "state" in a UI framework?', opts: ['CSS classes', 'Data that, when it changes, causes the UI to re-render', 'A type of route', 'A network protocol'], a: 1, e: 'State is the dynamic data of a component — change it and the framework updates the view.', tags: ['General', 'Frameworks'] },
  { q: 'What does "declarative" UI mean (vs imperative)?', opts: ['You step-by-step manipulate DOM nodes', 'You describe what the UI should look like for a given state; the framework figures out the how', 'You write only CSS', 'It’s the same'], a: 1, e: 'Declarative frameworks let you describe the target UI for the current state, and the framework reconciles the DOM.', tags: ['General', 'Frameworks'] },

  // ── Level 9 — Frontend vs Backend ──────────────────────────────────────
  { q: 'Frontend code runs:', opts: ['On the database', 'In the browser (and sometimes prerendered on the server)', 'In the network card', 'In DNS'], a: 1, e: 'Frontend = client-side: HTML/CSS/JS executed in the user’s browser.', tags: ['General', 'FE vs BE'] },
  { q: 'Backend code runs:', opts: ['In the browser', 'On the server you control', 'On the user’s phone', 'In a DNS record'], a: 1, e: 'Backend = server-side code, running on infrastructure you operate or rent.', tags: ['General', 'FE vs BE'] },
  { q: 'Where should you keep secrets like API keys?', opts: ['In a frontend file', 'On the server (env vars, secret manager) — never in client bundles', 'In a public Git repo', 'In a cookie'], a: 1, e: 'Anything shipped to the browser is visible; secrets must live server-side and be used via your backend.', tags: ['General', 'FE vs BE'] },
  { q: 'Why is the database usually not directly accessible from the browser?', opts: ['Browsers can’t connect', 'Direct DB access from clients can’t be safely authorised; a server enforces rules', 'It’s impossible technically', 'Bandwidth issues only'], a: 1, e: 'You want a controlled API in front of the DB to enforce auth, validation, rate limiting, and shape responses.', tags: ['General', 'FE vs BE'] },
  { q: 'A "BFF" (Backend For Frontend) is:', opts: ['A bigger backend', 'A thin server tailored to one specific client (e.g. mobile)', 'A new framework', 'A frontend test runner'], a: 1, e: 'BFFs let each client (web, iOS, etc.) have a backend tailored to its needs, in front of shared services.', tags: ['General', 'FE vs BE'] },
  { q: 'A "serverless function" is:', opts: ['Code that runs without any computer', 'A short-lived function the platform spins up on demand to handle a request', 'A client-only function', 'A worker thread'], a: 1, e: 'Serverless (Vercel/AWS Lambda/etc.) abstracts away the server: you ship functions, the platform manages instances.', tags: ['General', 'FE vs BE'] },
  { q: 'Why is "edge" computing useful?', opts: ['Code runs geographically close to users for lower latency', 'It eliminates errors', 'It removes the need for HTML', 'It only helps SEO'], a: 0, e: 'Edge runtimes execute code at globally-distributed points-of-presence, reducing the round-trip distance.', tags: ['General', 'FE vs BE'] },
  { q: 'A "full-stack" engineer is someone who:', opts: ['Only writes CSS', 'Works across both frontend and backend (and often the glue between them)', 'Only manages servers', 'Only writes SQL'], a: 1, e: 'Full-stack covers the whole stack — UI, server, sometimes DB and ops too.', tags: ['General', 'FE vs BE'] },

  // ── Level 10 — APIs & Communication ────────────────────────────────────
  { q: 'A mobile client knows which endpoint to call, which fields to send, and the response shape it will receive. What defines that agreement?', opts: ['The database’s internal storage layout', 'An API contract between the client and server', 'The HTML markup language used by a web page', 'The physical network path between both machines'], a: 1, e: 'API means Application Programming Interface. Its contract defines how software components interact, including operations, inputs, outputs, and errors.', tags: ['General', 'APIs'] },
  { q: 'A REST API typically uses:', opts: ['Custom binary protocols', 'HTTP verbs (GET/POST/…) on resource URLs, usually returning JSON', 'WebSocket frames only', 'SQL'], a: 1, e: 'REST maps domain "resources" to URLs and uses HTTP methods + status codes as the verbs/feedback.', tags: ['General', 'APIs'] },
  { q: 'GraphQL is:', opts: ['A relational database', 'A query language for APIs — the client asks for exactly the fields it wants', 'A bundler', 'A CDN'], a: 1, e: 'GraphQL gives clients a typed query language to request only the data they need, in one round-trip.', tags: ['General', 'APIs'] },
  { q: 'A "webhook" is:', opts: ['A client polling endpoint', 'A user-configured URL that another service will POST to when something happens', 'A websocket', 'A DNS record'], a: 1, e: 'With webhooks, the source system pushes events to your URL instead of you constantly polling.', tags: ['General', 'APIs'] },
  { q: 'WebSocket vs HTTP — what does WebSocket enable?', opts: ['Plain GETs only', 'Long-lived, bidirectional connections for real-time messages', 'Faster file uploads', 'CSS streaming'], a: 1, e: 'WebSocket upgrades an HTTP connection into a persistent duplex channel — handy for chat, games, live dashboards.', tags: ['General', 'APIs'] },
  { q: '"Polling" is:', opts: ['Repeatedly asking the server "anything new?" on an interval', 'A push protocol', 'A database join', 'A type of cache'], a: 0, e: 'Polling = client periodically requests updates. Long-polling or WebSocket/SSE scale better for real-time.', tags: ['General', 'APIs'] },
  { q: '"Rate limiting" on an API means:', opts: ['Charging by request', 'Capping how many requests a caller can make per time window', 'Compressing responses', 'Logging only'], a: 1, e: 'Rate limits protect APIs from abuse and accidental floods; usually returned as 429 Too Many Requests.', tags: ['General', 'APIs'] },
  { q: '"Pagination" exists to:', opts: ['Make URLs longer', 'Avoid returning huge lists in one response — clients fetch pages of N items', 'Improve SEO', 'Compress JSON'], a: 1, e: 'Page or cursor-based pagination keeps responses small and predictable as datasets grow.', tags: ['General', 'APIs'] },

  // ── Level 11 — Caching & CDNs ──────────────────────────────────────────
  { q: 'Why cache at all?', opts: ['To save energy', 'To return a previously computed/fetched result faster and cheaper', 'To delete files', 'Required by HTTP'], a: 1, e: 'Caching trades freshness for speed/cost: don’t re-fetch or recompute what hasn’t changed.', tags: ['General', 'Caching'] },
  { q: 'A CDN is most useful for:', opts: ['Database writes', 'Serving static assets and cached responses from edge nodes near users', 'Running ML training', 'Encrypting passwords'], a: 1, e: 'CDNs cache assets at the edge so users get them with low latency and your origin sees less load.', tags: ['General', 'Caching'] },
  { q: 'What does Cache-Control: max-age=3600 tell the client?', opts: ['Never cache', 'It’s OK to use this response for up to 3600 seconds before revalidating', 'Cache forever', 'Cache only for HTTPS'], a: 1, e: 'max-age says the response is considered "fresh" for N seconds.', tags: ['General', 'Caching'] },
  { q: 'What does Cache-Control: immutable mean?', opts: ['It’s a private cache', 'During its fresh period, don’t revalidate — the resource won’t change', 'Never cache it', 'Only cache on the server'], a: 1, e: 'immutable promises the file at this URL never changes (typical for hashed asset filenames).', tags: ['General', 'Caching'] },
  { q: 'A 304 response is the server saying:', opts: ['"Forbidden"', '"Your cached copy is still good — keep using it"', '"Page is gone"', '"Try again later"'], a: 1, e: 'After a conditional GET (with ETag or If-Modified-Since), 304 Not Modified means the cache is still fresh.', tags: ['General', 'Caching'] },
  { q: 'A "cache hit" vs "cache miss":', opts: ['Hit = served from cache; miss = had to fetch from origin', 'Hit = error; miss = success', 'They mean the same', 'Both refer to DB queries'], a: 0, e: 'Hit ratio (hits ÷ requests) is the main metric for cache effectiveness.', tags: ['General', 'Caching'] },
  { q: 'Why is cache invalidation famously hard?', opts: ['It’s easy actually', 'Knowing exactly when stale data becomes wrong, and refreshing it everywhere, is subtle', 'Browsers ignore caches', 'CDNs don’t support it'], a: 1, e: '"There are only two hard things in CS: cache invalidation and naming things." Old caches can serve stale data unexpectedly.', tags: ['General', 'Caching'] },
  { q: 'A common pattern for safe long caching of bundles is:', opts: ['Random Cache-Control headers', 'Hashed filenames (e.g. app.ab12.js) + Cache-Control: immutable', 'Caching only on the user device', 'Never cache JS'], a: 1, e: 'Fingerprint the filename so a new deploy yields a new URL; old URLs can be cached forever.', tags: ['General', 'Caching'] },

  // ── Level 12 — Authentication Basics ───────────────────────────────────
  { q: 'Authentication vs authorization:', opts: ['Same thing', 'AuthN = who you are; AuthZ = what you’re allowed to do', 'Both mean rate limiting', 'AuthN is for APIs, AuthZ is for pages'], a: 1, e: 'AuthN proves identity (login); AuthZ checks permissions (RBAC, RLS, scopes).', tags: ['General', 'Auth'] },
  { q: 'A session cookie is:', opts: ['A static file', 'A cookie holding an opaque id the server maps to your session', 'A JS variable', 'A type of CDN'], a: 1, e: 'Classic session auth: the server stores session state and the cookie just carries the lookup id.', tags: ['General', 'Auth'] },
  { q: 'A JWT (JSON Web Token):', opts: ['Is encrypted', 'Is a signed, self-contained token whose claims the server can verify without DB lookup', 'Is just a cookie type', 'Cannot expire'], a: 1, e: 'JWTs are signed (not necessarily encrypted) blobs of JSON; the server trusts the contents because the signature checks out.', tags: ['General', 'Auth'] },
  { q: 'OAuth is mainly used for:', opts: ['Encrypting traffic', 'Letting users grant a third-party app limited access to their account on another service', 'Replacing TLS', 'Building APIs'], a: 1, e: 'OAuth = delegated authorization. "Sign in with Google" lets your app obtain a Google-signed identity without ever seeing the password.', tags: ['General', 'Auth'] },
  { q: 'Why is hashing passwords (not encrypting) the right move?', opts: ['Encryption is slower', 'A hash is one-way; even if leaked, attackers can’t trivially reverse it back to the password', 'It’s required by browsers', 'It’s just convention'], a: 1, e: 'Use a slow, salted password hash (bcrypt, argon2). Encryption is reversible — bad for passwords.', tags: ['General', 'Auth'] },
  { q: 'A "refresh token" exists so that:', opts: ['Short-lived access tokens can be re-issued without the user re-logging in', 'You can pay for the API', 'The session never expires', 'You can sign out'], a: 0, e: 'Access tokens are kept short-lived for security; the refresh token swaps for a new one when the old expires.', tags: ['General', 'Auth'] },
  { q: 'Two-factor authentication adds:', opts: ['A second factor (something you have/are) on top of the first (something you know)', 'A second password only', 'A second username', 'A second cookie'], a: 0, e: '2FA requires two different categories of factor — even a stolen password isn’t enough.', tags: ['General', 'Auth'] },
  { q: '"RBAC" (Role-Based Access Control) means:', opts: ['Each user has every permission', 'Permissions are grouped into roles, and users get roles', 'There is no access control', 'Only admins exist'], a: 1, e: 'RBAC simplifies admin: assign a "role" (editor, viewer, admin) and the permissions follow.', tags: ['General', 'Auth'] },

  // ── Level 13 — Databases Overview ──────────────────────────────────────
  { q: 'A relational database stores data as:', opts: ['Documents', 'Tables with rows + columns, often related by foreign keys', 'Key-value pairs only', 'Graphs only'], a: 1, e: 'Postgres, MySQL etc. model data in tables; relationships are expressed by foreign keys.', tags: ['General', 'DB'] },
  { q: 'A "schema" describes:', opts: ['Compiled queries', 'The structure of your data — tables, columns, types, constraints', 'A type of user', 'Caching policy'], a: 1, e: 'Schemas are the data model; "migrations" change them over time.', tags: ['General', 'DB'] },
  { q: 'A "primary key" is:', opts: ['Any column', 'A column (or set) that uniquely identifies each row', 'A type of password', 'A cache identifier'], a: 1, e: 'Primary keys are unique per row and not null — the row’s identity.', tags: ['General', 'DB'] },
  { q: 'A "foreign key" is:', opts: ['A duplicated value', 'A column referencing the primary key of another table — encoding a relationship', 'An admin role', 'A type of cache'], a: 1, e: 'Foreign keys enforce referential integrity between tables (e.g. order.user_id → users.id).', tags: ['General', 'DB'] },
  { q: 'An "index" exists to:', opts: ['Save disk space', 'Speed up reads (lookups, sorts) at the cost of extra storage and slightly slower writes', 'Compress backups', 'Encrypt rows'], a: 1, e: 'An index is an auxiliary data structure (often a B-tree) the engine uses to find rows fast.', tags: ['General', 'DB'] },
  { q: 'A "transaction" exists so that:', opts: ['Multiple statements either all succeed or all roll back together', 'You can pay invoices', 'Indexes update lazily', 'Only one user is connected'], a: 0, e: 'Transactions give you atomicity + isolation across multiple statements — partial writes are rolled back on failure.', tags: ['General', 'DB'] },
  { q: 'NoSQL databases are useful when:', opts: ['You hate SQL', 'Your data is document/key-value/graph-shaped or needs horizontal scale beyond a single relational node', 'You don’t need persistence', 'You only have one user'], a: 1, e: 'NoSQL trades some relational features for different data models or scale-out characteristics.', tags: ['General', 'DB'] },
  { q: 'An ORM gives you:', opts: ['A new database', 'A typed, language-native way to talk to your DB instead of writing raw SQL strings', 'A free CDN', 'A way to skip auth'], a: 1, e: 'ORMs (Prisma, TypeORM, ActiveRecord) map rows to objects and generate SQL.', tags: ['General', 'DB'] },

  // ── Level 14 — Deployment & Hosting ────────────────────────────────────
  { q: 'To "deploy" an app means:', opts: ['Open the editor', 'Take built code and make it available on infrastructure for users to reach', 'Delete it', 'Test it locally'], a: 1, e: 'Deployment is the step from "built artefact" to "running and reachable" for real traffic.', tags: ['General', 'Deploy'] },
  { q: '"Staging" vs "production" environments:', opts: ['Production is for testing', 'Staging mirrors production for safe testing before releasing to real users', 'They’re the same thing', 'Staging has the real database'], a: 1, e: 'Staging is the pre-prod rehearsal environment so you can catch issues without affecting users.', tags: ['General', 'Deploy'] },
  { q: 'A "rolling deployment" works by:', opts: ['Stopping all servers, then starting new ones', 'Replacing instances gradually so the app stays up the whole time', 'Doing nothing', 'Skipping deploys at peak hours'], a: 1, e: 'Rolling deploys avoid downtime — new instances come up while old ones drain, and traffic shifts gradually.', tags: ['General', 'Deploy'] },
  { q: 'A "blue/green deployment":', opts: ['Two colour themes', 'Two full environments — switch traffic atomically and roll back instantly if needed', 'A type of CSS framework', 'A DNS record'], a: 1, e: 'Run blue (current) + green (new) in parallel and flip the router; rollback is instant.', tags: ['General', 'Deploy'] },
  { q: 'A "feature flag" lets you:', opts: ['Compile faster', 'Enable/disable a feature at runtime, often per user/segment, without redeploying', 'Skip testing', 'Hide bugs'], a: 1, e: 'Flags decouple deploy from release: ship the code dark, turn it on gradually, dark-launch.', tags: ['General', 'Deploy'] },
  { q: 'An "environment variable" is:', opts: ['A new programming concept', 'A value injected into the process at start time (e.g. DATABASE_URL, NODE_ENV)', 'A CSS variable', 'A DNS record'], a: 1, e: 'Env vars let the same binary run in different environments with different config (and keep secrets out of source).', tags: ['General', 'Deploy'] },
  { q: 'Why does "12-factor" recommend stateless processes?', opts: ['Faster compilation', 'They scale out trivially and recover from crashes — state lives in backing services', 'It’s required by Docker', 'Old browsers'], a: 1, e: 'Stateless processes can be killed/replaced freely; persistent state goes to DBs, caches, queues, blob stores.', tags: ['General', 'Deploy'] },
  { q: 'A "container image" is roughly:', opts: ['A VM disk', 'A packaged, immutable snapshot of an app + its runtime dependencies, ready to run anywhere with a container runtime', 'A type of CDN file', 'A backup'], a: 1, e: 'Container images (Docker/OCI) give you reproducible deploys — same image runs identically on any host.', tags: ['General', 'Deploy'] },

  // ── Level 15 — Performance & Optimization ──────────────────────────────
  { q: 'Why do we measure "Core Web Vitals" (LCP, INP, CLS)?', opts: ['Marketing', 'They quantify user-perceived loading, responsiveness, and visual stability', 'They’re a billing metric', 'Compiler config'], a: 1, e: 'CWV are Google’s standardised, user-centric performance metrics; they also feed into SEO ranking.', tags: ['General', 'Performance'] },
  { q: '"Time To First Byte" (TTFB) primarily measures:', opts: ['Time spent painting', 'Server + network time until the first response byte arrives', 'JS execution', 'CSS parsing'], a: 1, e: 'High TTFB usually points at backend latency, geographical distance, or slow DB queries.', tags: ['General', 'Performance'] },
  { q: 'A long-running JS task on the main thread harms:', opts: ['Storage', 'Responsiveness (INP) — clicks/scrolls feel sluggish because the thread is busy', 'TLS performance', 'Server uptime'], a: 1, e: 'JS runs on the same thread as rendering and input — long tasks block them, and the page feels frozen.', tags: ['General', 'Performance'] },
  { q: '"Code-splitting" helps performance by:', opts: ['Letting you ship more code', 'Loading only the JS each route actually needs, on demand', 'Eliminating bugs', 'Disabling JS'], a: 1, e: 'Code-splitting breaks a bundle into chunks; the browser fetches a chunk only when the user navigates to it.', tags: ['General', 'Performance'] },
  { q: 'Why do hashed asset filenames matter for caching?', opts: ['They look nicer', 'A new build → new filename → safe to set a long cache while never serving stale content', 'They reduce file size', 'Security'], a: 1, e: 'Content-hashed filenames let you cache aggressively without worrying about deploying an update.', tags: ['General', 'Performance'] },
  { q: 'A "debounce" on a search input does what?', opts: ['Sends a query per keystroke', 'Waits until input has been idle for N ms before sending one query', 'Caches every keystroke forever', 'Disables typing'], a: 1, e: 'Debouncing reduces request count by waiting for the user to pause before firing the side effect.', tags: ['General', 'Performance'] },
  { q: '"Lazy loading" an image means:', opts: ['Loading it eagerly', 'Deferring its download until it’s near the viewport', 'Replacing it with text', 'Caching it forever'], a: 1, e: 'loading="lazy" (or IntersectionObserver) postpones off-screen image loads, saving bytes and time.', tags: ['General', 'Performance'] },
  { q: 'The single biggest win for first-load performance is usually:', opts: ['Shipping less JavaScript', 'Bigger images', 'More frameworks', 'Disabling caching'], a: 0, e: 'JS is the most expensive resource — it must be downloaded, parsed, and executed before it does anything. Less of it is almost always better.', tags: ['General', 'Performance'] },
];
