import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Starting Hands & Ranges roadmap bank (rm-pkstart-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const startingHandsTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-pkstart-1': { introduction: 'Malé „s" za kartami má svůj význam.', question: 'Co v pokerovém zápisu znamená „AKs"?', options: ['Eso-král v jedné barvě', 'Eso-král v různých barvách', 'Dvě esa a král', 'Eso-král na stole'], explanation: 'Malé „s" znamená „suited", tedy eso a král stejné barvy.' },
  'rm-pkstart-2': { introduction: 'Písmeno rozlišuje barvy karet.', question: 'Co v zápisu „72o" znamená písmeno „o"?', options: ['Různé barvy (offsuit)', 'Otevření sázky', 'Outy', 'Overpár'], explanation: 'Písmeno „o" značí offsuit, tedy že obě karty jsou různých barev.' },
  'rm-pkstart-3': { introduction: 'Nejlepší možný start.', question: 'Která je nejsilnější možná startovní ruka v Texas Hold\'em?', options: ['Pár es (AA)', 'Eso-král v barvě', 'Pár králů', 'Eso-dáma v barvě'], explanation: 'Pár es je nejlepší startovní ruka a je favoritem před flopem proti jakékoli jiné ruce.' },
  'rm-pkstart-4': { introduction: 'Pár se zapisuje zdvojenou hodnotou.', question: 'Jak se ve zkráceném zápisu značí pár dam?', options: ['QQ', 'QJ', 'Qs', 'Q2'], explanation: 'Pár se píše zdvojenou hodnotou karty, dvě dámy jsou tedy „QQ".' },
  'rm-pkstart-5': { introduction: 'Populární přezdívka jedné ruky.', question: 'Jakou přezdívku má populárně startovní ruka eso-král?', options: ['Big Slick', 'The Hammer', 'Cowboys', 'Snowmen'], explanation: 'Eso-král se nazývá „Big Slick"; „Cowboys" je KK, „Snowmen" je 88 a „The Hammer" je 72.' },
  'rm-pkstart-6': { introduction: 'Kombinatorika párů.', question: 'Kolik různých kombinací má kterýkoli konkrétní pár v ruce?', options: ['6', '4', '12', '2'], explanation: 'Každý pár má 6 kombinací (4 karty po dvou), zatímco nepárová ruka má 4 suited a 12 offsuit kombinací.' },
  'rm-pkstart-7': { introduction: 'Klasicky nejhorší ruka.', question: 'Která ruka je obecně považována za nejhorší startovní ruku v Hold\'em?', options: ['7-2 offsuit', '3-2 offsuit', 'Pár dvojek', '7-2 v barvě'], explanation: '7-2 offsuit je klasicky nejhorší ruka: bez potenciálu na postupku, bez barvy a s nízkou silou karet.' },
  'rm-pkstart-8': { introduction: 'Co znamená „suited".', question: 'Co znamená, že dvě karty v ruce jsou „suited"?', options: ['Jsou stejné barvy', 'Jsou po sobě jdoucí hodnoty', 'Jsou obě obrázkové', 'Tvoří pár'], explanation: 'Suited jednoduše znamená, že obě karty jsou stejné barvy a dávají potenciál na barvu.' },

  'rm-pkstart-9': { introduction: 'Definice suited konektorů.', question: '„Suited konektory" jsou dvě karty, které jsou...', options: ['Stejné barvy a po sobě jdoucí hodnoty', 'Stejné hodnoty', 'Obě esa', 'Jakékoli dvě karty v barvě'], explanation: 'Suited konektory jsou stejné barvy a sousedí v hodnotě, například 8-7 srdcová.' },
  'rm-pkstart-10': { introduction: 'Najdi pravý konektor.', question: 'Který z těchto příkladů je suited konektor?', options: ['8-7 v barvě', 'A-K offsuit', 'K-9 v barvě', 'Pár pětek'], explanation: '8-7 v barvě je stejné barvy a po sobě jdoucí; K-9 je sice v barvě, ale s mezerou, není to pravý konektor.' },
  'rm-pkstart-11': { introduction: 'Nejvyšší hodnoty karet.', question: 'Které hodnoty se označují jako „broadway" karty?', options: ['Desítka až eso', 'Dvojka až pětka', 'Jakýkoli pár', 'Jen karty v barvě'], explanation: 'Broadway karty jsou desítka, kluk, dáma, král a eso, tedy pět nejvyšších hodnot.' },
  'rm-pkstart-12': { introduction: 'Ruka ze dvou vysokých karet.', question: 'Která ruka je „broadway" (dvě broadway karty)?', options: ['K-Q', '9-8', 'Pár šestek', 'A-2'], explanation: 'K-Q tvoří dvě broadway karty; obě patří do skupiny desítka až eso.' },
  'rm-pkstart-13': { introduction: 'Eso s doprovodem stejné barvy.', question: '„Suited eso" je eso spolu s...', options: ['Další kartou stejné barvy', 'Dalším esem', 'Jen s obrázkovou kartou', 'Kartou na stole'], explanation: 'Suited eso je eso s druhou kartou stejné barvy, například A-5 pikové.' },
  'rm-pkstart-14': { introduction: 'Proč mají suited esa cenu.', question: 'Proč jsou suited esa ceněná jako startovní ruka?', options: ['Mohou udělat nejvyšší (nut) barvu', 'Jsou vždy párem', 'Nelze je porazit', 'Zaručují postupku'], explanation: 'Držení esa dané barvy znamená, že každá vaše barva je nut, tedy nejsilnější možná.' },
  'rm-pkstart-15': { introduction: 'Cíl malých párů.', question: 'Malé páry jako 2-2 až 5-5 se často hrají s nadějí, že...', options: ['Trefí set (trojici)', 'Udělají barvu', 'Udělají postupku', 'Trefí top pár'], explanation: 'Malé páry míří hlavně na trefení setu, což je dobře maskovaná a silná ruka, za níž se vyplatí táhnout lacino.' },
  'rm-pkstart-16': { introduction: 'Co je pár v ruce.', question: 'Co znamená „pocket pair" (pár v ruce)?', options: ['Dvě karty v ruce stejné hodnoty', 'Dvě karty v barvě', 'Dvě navazující karty', 'Dvě broadway karty'], explanation: 'Pár v ruce jsou dvě karty stejné hodnoty, například 9-9, rozdané jednomu hráči.' },

  'rm-pkstart-17': { introduction: 'Nejlepší pozice u stolu.', question: 'Která pozice jedná jako poslední na každé ulici po flopu?', options: ['Button (dealer)', 'Under the gun', 'Malý blind', 'Velký blind'], explanation: 'Button jedná po flopu jako poslední, což je nejsilnější poziční výhoda u stolu.' },
  'rm-pkstart-18': { introduction: 'První na tahu před flopem.', question: 'Z pozice „under the gun" (první na tahu) byste měli obecně hrát...', options: ['Úzký, silný rozsah', 'Jakékoli dvě karty', 'Jen ruce v barvě', 'Všechny páry'], explanation: 'Jako první na tahu s mnoha hráči za sebou vyžaduje under the gun úzký rozsah silných rukou.' },
  'rm-pkstart-19': { introduction: 'Vliv pozdější pozice.', question: 'Jak by se měl váš otevírací rozsah obecně měnit od rané k pozdní pozici?', options: ['Rozšiřovat se', 'Zužovat se', 'Zůstat stejný', 'Obsahovat jen páry'], explanation: 'V pozdní pozici zbývá méně hráčů na tahu, takže lze ziskově otevírat širší rozsah.' },
  'rm-pkstart-20': { introduction: 'Ruka i pro ranou pozici.', question: 'Která ruka je pohodlné otevření raisem i z rané pozice?', options: ['A-K', '7-2 offsuit', 'J-4 offsuit', '9-3 v barvě'], explanation: 'A-K je prémiová ruka dost silná na otevření z jakékoli pozice, včetně raných míst.' },
  'rm-pkstart-21': { introduction: 'Kde hrát spekulativní ruce.', question: 'Spekulativní ruce jako malé suited konektory se nejlépe otevírají z...', options: ['Pozdní pozice', 'Under the gun', 'Jen z velkého blindu', 'Ze všech pozic stejně'], explanation: 'Malé suited konektory hrají nejlépe v pozdní pozici, kde jednáte poslední a lépe realizujete ekvitu.' },
  'rm-pkstart-22': { introduction: 'Co dává pozice.', question: '„Poziční výhoda" znamená, že být v pozici vám umožní...', options: ['Jednat po soupeři s více informacemi', 'Vidět kartu navíc', 'Sázet vyšší blindy', 'Přeskočit ulici sázení'], explanation: 'V pozici jednáte po soupeři na každé ulici a jeho akci využíváte jako informaci.' },
  'rm-pkstart-23': { introduction: 'Proč je malý blind těžký.', question: 'Proč je malý blind obecně obtížná pozice na hraní?', options: ['Po flopu jednáte první a jste mimo pozici', 'Musíte vždy složit', 'Máte nejlepší pot odds', 'Vidíte flop zdarma'], explanation: 'Malý blind jedná první na každé ulici po flopu, což je trvalá nevýhoda hry mimo pozici.' },
  'rm-pkstart-24': { introduction: 'Nejširší otevírací rozsah.', question: 'Která pozice má obvykle nejširší otevírací rozsah?', options: ['Button', 'Under the gun', 'Střední pozice', 'Lojack'], explanation: 'Button, který jedná poslední a má za sebou jen dva blindy, může otevírat nejširší rozsah rukou.' },

  'rm-pkstart-25': { introduction: 'Co je rozsah rukou.', question: 'Co v pokeru označuje „rozsah" (range) hráče?', options: ['Všechny ruce, které v dané situaci může držet', 'Jednu konkrétní ruku', 'Velikost banku', 'Úrovně blindů'], explanation: 'Rozsah je celá množina rukou, které hráč může vzhledem ke svým akcím držet, ne jedna konkrétní ruka.' },
  'rm-pkstart-26': { introduction: 'Počítání sázek před flopem.', question: 'Co znamená „3-bet" před flopem?', options: ['Třetí sázku, tedy přeraise původního raisu', 'Sázení třikrát po flopu', 'Sázku na třetí kartu stolu', 'Sázku trojnásobku banku'], explanation: 'Blind je sázka jedna, otevírací raise je sázka dvě, a jeho přeraise je 3-bet.' },
  'rm-pkstart-27': { introduction: 'Silný 3-bet.', question: '„Hodnotový 3-bet" (value) se dělá s...', options: ['Silnou rukou, která chce do banku víc peněz', 'Slabou rukou jako blaf', 'Jakoukoli náhodnou rukou', 'Jen s párem es'], explanation: 'Hodnotový 3-bet používá silnou ruku, která uvítá dorovnání a plní bank, když vedete.' },
  'rm-pkstart-28': { introduction: 'Blafovací 3-bet.', question: '„3-bet blaf" se často dělá s rukama jako...', options: ['Suited esa s užitečným blokerem', 'Pár es', 'Náhodné offsuit odpadky', 'Hotová postupka'], explanation: 'Suited esa jsou dobré 3-bet blafy: eso blokuje silné ruce a barva přidává hratelnost.' },
  'rm-pkstart-29': { introduction: 'Rozdělený rozsah.', question: '„Polarizovaný" 3-betový rozsah tvoří převážně...', options: ['Silné hodnotové ruce a blafy, s málem mezi tím', 'Jen ruce střední síly', 'Každá ruka v barvě', 'Jen páry'], explanation: 'Polarizovaný rozsah se dělí na silné hodnotové ruce a blafy a vynechává okrajové dorovnávací ruce.' },
  'rm-pkstart-30': { introduction: 'Sloučený rozsah.', question: '„Lineární" (sloučený) 3-betový rozsah tvoří...', options: ['Nejsilnější ruce seskupené pohromadě', 'Jen blafy', 'Čistě náhodné ruce', 'Jen offsuit ruce'], explanation: 'Lineární rozsah 3-betuje vaše nejlepší ruce jako blok, běžně proti volným či slabým otvíračům.' },
  'rm-pkstart-31': { introduction: 'Myšlení v rozsazích.', question: 'Uvažování „rozsah proti rozsahu" znamená posuzovat...', options: ['Jak si vede celý váš rozsah proti celému rozsahu soupeře', 'Jen vaše dvě konkrétní karty', 'Jen pot odds', 'Jen velikosti stacků'], explanation: 'Silní hráči porovnávají celé rozsahy, ne jednotlivé ruce, aby naplánovali sázky a našli nejlepší linii.' },
  'rm-pkstart-32': { introduction: 'Ruka na dorovnání, ne na 3-bet.', question: 'Pokud je ruka ziskové dorovnání, ale příliš slabá na hodnotový 3-bet a nechcete blafovat, obvykle byste měli...', options: ['Jen dorovnat raise (flat call)', 'Vždy ji složit', 'Vždy ji 3-betnout', 'Jít all-in'], explanation: 'Takové ruce patří do dorovnávacího rozsahu: dorovnání drží ve hře slabší ruce a kontroluje velikost banku.' },

  'rm-pkstart-33': { introduction: 'Proti těsnému soupeři.', question: 'Proti velmi těsnému hráči, který raisuje jen prémiové ruce, byste měli...', options: ['Skládat okrajové ruce a vyhýbat se lehkým 3-betům', 'Dorovnávat skoro cokoli', 'Neustále 3-bet blafovat', 'Nikdy neskládat'], explanation: 'Těsný otvírač málokdy drží slabou ruku, proto respektujte jeho rozsah a odhoďte spekulativní ruce.' },
  'rm-pkstart-34': { introduction: 'Proti volnému soupeři.', question: 'Proti volnému hráči, který otevírá příliš mnoho slabých rukou, byste měli...', options: ['Rozšířit hodnotové 3-bety a dorovnávací rozsah', 'Výrazně přitáhnout', 'Skládat všechno', 'Jen dorovnávat'], explanation: 'Volný otvírač má slabý rozsah, takže můžete ziskově 3-betovat víc rukou pro hodnotu a dorovnávat šířeji.' },
  'rm-pkstart-35': { introduction: 'Krátký stack a síla karet.', question: 'S krátkým stackem (kolem 15-20 velkých blindů) které ruce relativně získávají na ceně?', options: ['Ruce se silou vysokých karet jako velká esa a velké páry', 'Malé suited konektory', 'Nízké offsuit ruce', 'Spekulativní ruce na hloubkové implied odds'], explanation: 'Krátké stacky preferují surovou sílu vysokých karet na all-in; spekulativní ruce bez hloubky ztrácejí cenu.' },
  'rm-pkstart-36': { introduction: 'Hluboké stacky.', question: 'S hlubokým stackem (200 blindů a víc) který typ ruky získává na ceně?', options: ['Suited konektory a suited esa', 'Offsuit vysoké karty', 'Malé offsuit ruce', 'Jen slabé páry'], explanation: 'Hluboké stacky odměňují suited konektory a suited esa, protože mohou vyhrát obří bank, když se trefí.' },
  'rm-pkstart-37': { introduction: 'Na čem stojí spekulativní ruce.', question: 'Spekulativní ruce jako malé suited konektory se opírají hlavně o...', options: ['Implied odds (výhru velkého banku, když se trefí)', 'Jen pot odds', 'Fold ekvitu před flopem', 'Odebrání karet (removal)'], explanation: 'Silnou ruku trefí zřídka, proto potřebují hluboké stacky a implied odds, aby se vyplatilo je hrát.' },
  'rm-pkstart-38': { introduction: 'Tlak ICM na bublině.', question: 'V turnaji blízko peněžní bubliny vás tlak ICM obecně vede k tomu, abyste...', options: ['Hráli těsněji a nevypadli před dosažením peněz', 'Hráli mnohem volněji', 'Ignorovali velikosti stacků', 'Volně dorovnávali all-iny'], explanation: 'ICM cení přežití, takže blízko bubliny přitáhnete a vyhýbáte se okrajovým all-in konfrontacím.' },
  'rm-pkstart-39': { introduction: 'Proti přehnaně skládajícím.', question: 'Proti soupeřům, kteří příliš často skládají na 3-bet, byste měli...', options: ['3-bet blafovat častěji', '3-betovat jen pro hodnotu', 'Přestat 3-betovat úplně', 'Všechno jen dorovnávat'], explanation: 'Pokud přehnaně skládají, 3-bet blaf vydělává, proto přidejte víc lehkých 3-betů a využijte jejich slabinu.' },
  'rm-pkstart-40': { introduction: 'Cash hra vs. turnaj.', question: 'Protože se cash hry a turnaje liší hloubkou stacků a tlakem blindů, silný hráč...', options: ['Přizpůsobuje startovní rozsahy hloubce stacku a formátu', 'Používá jeden pevný rozsah všude', 'Formát ignoruje', 'Hraje vždy jen prémiové ruce'], explanation: 'Optimální rozsahy se mění s hloubkou stacku, ante a ICM, proto dobří hráči přizpůsobují výběr rukou hře.' },
};
