// Tournament Strategy roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const tournamentPlaySeeds: Seed[] = [
  // ── Level 1 — How tournaments work (levels, blinds up, payouts) ──
  { q: 'In a poker tournament, what happens to the blinds as time goes on?', opts: ['They increase at set intervals', 'They stay fixed all event', 'They decrease over time', 'Players choose them each hand'], a: 0, e: 'Tournaments raise the blinds (and antes) at scheduled level changes, forcing action as the event goes on.', tags: ['Poker', 'Basics'] },
  { q: 'When are you eliminated from a standard freezeout tournament?', opts: ['When you lose all your chips', 'When you lose one big pot', 'After a fixed number of hands', 'When the blinds pass your seat'], a: 0, e: 'In a freezeout you are out the moment your chip stack reaches zero; there is no rebuy.', tags: ['Poker', 'Basics'] },
  { q: 'In most tournaments, roughly what fraction of the field gets paid?', opts: ['About the top 10-15%', 'Exactly half', 'Only the winner', 'Everyone who entered'], a: 0, e: 'A common payout structure pays roughly the top 10-15% of entrants, with prizes rising toward first place.', tags: ['Poker', 'Payouts'] },
  { q: 'What is a "buy-in" in a tournament?', opts: ['The amount paid to enter and receive chips', 'The first bet of each hand', 'The prize for first place', 'A forced bet before the flop'], a: 0, e: 'The buy-in is what you pay to enter; it funds the prize pool (minus the fee) and grants your starting chips.', tags: ['Poker', 'Basics'] },
  { q: 'Tournament chips differ from cash-game chips in that they...', opts: ['Have no direct cash value', 'Can be exchanged for cash anytime', 'Are worth their face value in dollars', 'Are only used on the river'], a: 0, e: 'Tournament chips only determine your standing; you cannot cash them out mid-event like cash-game chips.', tags: ['Poker', 'Basics'] },
  { q: 'What is a "rebuy" tournament?', opts: ['One where you can buy more chips after busting early', 'One with no entry fee', 'One that never pays out', 'One with fixed blinds'], a: 0, e: 'In a rebuy event, players may purchase additional chips (usually while short or busted) during an early rebuy period.', tags: ['Poker', 'Formats'] },
  { q: 'What does an "ante" require players to do?', opts: ['Post a small forced bet into most or every pot', 'Match the biggest stack', 'Skip a hand', 'Show their cards early'], a: 0, e: 'An ante is a small forced contribution that builds the pot and, especially in later levels, encourages action.', tags: ['Poker', 'Basics'] },
  { q: 'Where does most of a tournament\'s prize money go?', opts: ['Weighted heavily toward the top finishers', 'Split evenly among all who cash', 'Entirely to last place', 'Refunded to eliminated players'], a: 0, e: 'Payout structures are top-heavy: first place earns a large share, and prizes shrink steeply down the ladder.', tags: ['Poker', 'Payouts'] },

  // ── Level 2 — Stack sizes in big blinds & stages of a tournament ──
  { q: 'Why do players measure their stack in "big blinds" rather than chips?', opts: ['It shows real strength regardless of rising blinds', 'Chips are hard to count', 'It is required by the rules', 'Big blinds never change'], a: 0, e: 'Because blinds rise, a raw chip count is misleading; big blinds (stack ÷ big blind) show your true stack depth.', tags: ['Poker', 'Stack sizes'] },
  { q: 'A player with 80 big blinds is generally considered to have a...', opts: ['Deep, comfortable stack', 'Short stack', 'Stack forced to go all-in', 'Stack that must fold everything'], a: 0, e: 'Around 80 big blinds is a deep, flexible stack that allows post-flop play and does not force all-in decisions.', tags: ['Poker', 'Stack sizes'] },
  { q: 'Roughly what stack depth is commonly called "short-stacked"?', opts: ['Under about 15-20 big blinds', 'Over 100 big blinds', 'Exactly 50 big blinds', 'Any stack with chips left'], a: 0, e: 'Below roughly 15-20 big blinds you are short-stacked, with little room to maneuver after the flop.', tags: ['Poker', 'Stack sizes'] },
  { q: 'During the early stage of a tournament, blinds relative to stacks are...', opts: ['Small, allowing patient deep play', 'Larger than everyone\'s stack', 'Fixed for the whole event', 'Set by the chip leader'], a: 0, e: 'Early on, deep stacks and small blinds reward patience and selective, post-flop-oriented play.', tags: ['Poker', 'Stages'] },
  { q: 'As a tournament reaches its middle stage, a key change is that...', opts: ['Antes kick in and stealing blinds matters more', 'The blinds stop rising', 'All players go all-in every hand', 'The prize pool shrinks'], a: 0, e: 'In the middle stage antes appear and rising blinds make stealing blinds and antes increasingly valuable.', tags: ['Poker', 'Stages'] },
  { q: 'If you have 100 big blinds and the big blind is 500, your stack is...', opts: ['50,000 chips', '5,000 chips', '500 chips', '1,000,000 chips'], a: 0, e: '100 big blinds × 500 chips per big blind equals 50,000 chips.', tags: ['Poker', 'Stack sizes'] },
  { q: 'Why does a rising blind level effectively shrink a stack that wins no pots?', opts: ['The same chips are worth fewer big blinds', 'Chips are physically removed', 'The dealer takes a cut', 'Antes are refunded'], a: 0, e: 'Even if your chip count is unchanged, higher blinds mean those chips represent fewer big blinds of playable depth.', tags: ['Poker', 'Stack sizes'] },
  { q: 'What is a defining feature of the "late stage" of a tournament near the money?', opts: ['Shallow stacks and high-pressure decisions', 'The deepest stacks of the event', 'No antes in play', 'Blinds resetting to the start'], a: 0, e: 'Late-stage play features shallow stacks in big blinds, antes, and pressure-packed spots as the money nears.', tags: ['Poker', 'Stages'] },

  // ── Level 3 — Short-stack play, push/fold & the M-ratio ──
  { q: 'What is "push/fold" strategy?', opts: ['Either move all-in or fold, skipping small raises', 'Always call the blind', 'Never bet on the river', 'Limp every hand'], a: 0, e: 'With a short stack, push/fold simplifies decisions: you shove all-in or fold, avoiding easily-committed small raises.', tags: ['Poker', 'Short stack'] },
  { q: 'Push/fold play becomes correct mainly when your stack is...', opts: ['Around 10-15 big blinds or fewer', 'Over 100 big blinds', 'Exactly 40 big blinds', 'Any depth at all'], a: 0, e: 'At roughly 10-15 big blinds or less there is little fold equity or post-flop room, so shove-or-fold is optimal.', tags: ['Poker', 'Short stack'] },
  { q: 'The "M-ratio" measures your stack relative to what?', opts: ['The blinds and antes you pay each orbit', 'The chip leader\'s stack', 'The total prize pool', 'The number of players left'], a: 0, e: 'M equals your stack divided by the total blinds and antes per orbit, showing how many rounds you can survive folding.', tags: ['Poker', 'M-ratio'] },
  { q: 'A low M-ratio (say under 5) signals that a player should...', opts: ['Look for spots to move all-in soon', 'Play very passively and fold everything', 'Call every raise', 'Wait dozens more hands'], a: 0, e: 'A low M means the blinds are eating you alive, so you must find a hand to shove before you are blinded out.', tags: ['Poker', 'M-ratio'] },
  { q: 'What is "fold equity"?', opts: ['The chance opponents fold to your bet or shove', 'Equity from folding hands', 'The pot you win at showdown', 'The rake taken from the pot'], a: 0, e: 'Fold equity is the value gained from the possibility that opponents fold, which shrinks as your stack gets tiny.', tags: ['Poker', 'Short stack'] },
  { q: 'From late position with a short stack, a wider shoving range is justified because...', opts: ['Fewer players remain to wake up with a strong hand', 'The blinds are smaller there', 'You must act first', 'Cards improve in late position'], a: 0, e: 'Acting later means fewer players behind can call, so more fold equity supports shoving a wider range.', tags: ['Poker', 'Short stack'] },
  { q: 'With about 12 big blinds, why is min-raising then folding to a shove often a mistake?', opts: ['You forfeit chips you could have committed by shoving', 'It is against the rules', 'Min-raises are not allowed short', 'It doubles the blinds'], a: 0, e: 'Raising small and folding to a re-shove wastes chips; at this depth shoving directly captures fold equity cleanly.', tags: ['Poker', 'Short stack'] },
  { q: 'Harrington\'s "zones" tie strategy to M; entering the "red zone" (M under 5) means...', opts: ['Your only real move is to push all-in or fold', 'You can play deep-stack poker', 'You should sit out', 'You must call every bet'], a: 0, e: 'In the red zone your stack is so short relative to the blinds that shove-or-fold is essentially your only viable play.', tags: ['Poker', 'M-ratio'] },

  // ── Level 4 — The bubble, ICM basics & pay-jumps ──
  { q: 'What is the "bubble" in a tournament?', opts: ['The spot just before players start getting paid', 'The final hand of the event', 'The first level of play', 'The break between levels'], a: 0, e: 'The bubble is the point right before the money; the last player eliminated without cashing is the "bubble boy".', tags: ['Poker', 'Bubble'] },
  { q: 'ICM (Independent Chip Model) is used to estimate what?', opts: ['The real cash value of a chip stack given the payouts', 'The number of hands left', 'The rake owed', 'The blind schedule'], a: 0, e: 'ICM converts chip stacks into their expected share of the prize pool, since chips are not worth linear cash.', tags: ['Poker', 'ICM'] },
  { q: 'A core ICM insight is that chips you can lose are worth...', opts: ['More than the equal number of chips you can win', 'Exactly the same as chips you win', 'Nothing at all', 'Only their face value'], a: 0, e: 'Losing chips costs more equity than winning the same amount gains, because prize money is non-linear with chips.', tags: ['Poker', 'ICM'] },
  { q: 'On the bubble, a big stack can profit by...', opts: ['Pressuring medium stacks who fear busting', 'Folding every hand', 'Calling all-ins with any two cards', 'Refusing to raise'], a: 0, e: 'Big stacks apply bubble pressure: medium stacks risk elimination before cashing, so they fold more, letting you steal.', tags: ['Poker', 'Bubble'] },
  { q: 'Because of ICM, a short stack near the bubble should generally...', opts: ['Avoid marginal all-ins that risk busting before the cash', 'Call off with any hand', 'Ignore the payouts entirely', 'Play exactly like a cash game'], a: 0, e: 'Near the bubble the value of simply reaching the money makes thin, high-risk all-ins less profitable in ICM terms.', tags: ['Poker', 'ICM'] },
  { q: 'What is a "pay-jump"?', opts: ['The increase in prize money for moving up a spot', 'A jump in the blind level', 'A bonus for the chip leader', 'A rebuy option'], a: 0, e: 'A pay-jump is the extra prize money earned by outlasting one more player and climbing the payout ladder.', tags: ['Poker', 'Pay-jumps'] },
  { q: 'Compared with a chip-EV (cash-game) approach, ICM tends to make correct calling ranges...', opts: ['Tighter, since busting is more costly', 'Much wider', 'Unchanged', 'Random'], a: 0, e: 'ICM penalizes elimination, so you call all-ins tighter than a pure chip-EV model would suggest.', tags: ['Poker', 'ICM'] },
  { q: 'Why can folding a slightly +chip-EV all-in be correct near a big pay-jump?', opts: ['Surviving to ladder up is worth more than the small chip edge', 'Folding always wins chips', 'The hand is against the rules', 'Chips have fixed cash value'], a: 0, e: 'When a pay-jump is large, the equity from laddering can outweigh a marginal chip edge, so folding is ICM-correct.', tags: ['Poker', 'Pay-jumps'] },

  // ── Level 5 — Final-table and heads-up adjustments ──
  { q: 'At a final table, why do ICM considerations become especially strong?', opts: ['Pay-jumps between spots are large', 'There are no antes', 'Blinds stop rising', 'Everyone has the same stack'], a: 0, e: 'Final-table pay-jumps are big, so ICM pressure to preserve your stack and avoid busting peaks here.', tags: ['Poker', 'Final table'] },
  { q: 'A big stack at a final table can best exploit ICM pressure by...', opts: ['Applying aggression against stacks that cannot risk busting', 'Sitting out every hand', 'Only calling all-ins', 'Playing every pot passively'], a: 0, e: 'Short and medium stacks fear the pay-jumps, so a big stack raises and re-raises to win pots uncontested.', tags: ['Poker', 'Final table'] },
  { q: 'How should hand values shift as a table becomes short-handed (fewer players)?', opts: ['Hands go up in value, so you play more of them', 'Hands lose value, so play tighter', 'Values do not change', 'Only aces are playable'], a: 0, e: 'With fewer opponents, the blinds hit you more often and each hand is stronger on average, so you open wider.', tags: ['Poker', 'Short-handed'] },
  { q: 'In heads-up play, how does the button (small blind) act?', opts: ['Posts the small blind and acts first pre-flop, last post-flop', 'Posts the big blind', 'Acts last on every street', 'Does not post a blind'], a: 0, e: 'Heads-up, the button posts the small blind, acts first pre-flop, and then acts last on the flop, turn, and river.', tags: ['Poker', 'Heads-up'] },
  { q: 'Correct heads-up strategy compared with full-ring play is...', opts: ['Much more aggressive, playing a very wide range', 'Far tighter, folding most hands', 'Identical', 'Fold everything but aces'], a: 0, e: 'With only one opponent and blinds hitting every hand, heads-up demands a wide, aggressive range and constant pressure.', tags: ['Poker', 'Heads-up'] },
  { q: 'When heads-up for the title, why does ICM pressure largely ease?', opts: ['Only first and second remain, so it is closer to chip-EV', 'The blinds stop', 'Antes are removed', 'Chips gain fixed value'], a: 0, e: 'With just two payouts left, the ladder is nearly exhausted and play skews back toward maximizing chip EV.', tags: ['Poker', 'Heads-up'] },
  { q: 'A "chip and a chair" comeback illustrates that a short stack should...', opts: ['Keep playing, since any stack can still win', 'Give up once short', 'Always fold to the leader', 'Refuse to go all-in'], a: 0, e: 'The saying reminds players that even one chip keeps you alive, and short stacks routinely rebuild to win.', tags: ['Poker', 'Final table'] },
  { q: 'When negotiating a "deal" (chop) at a final table, stacks are most fairly split using...', opts: ['An ICM or chip-chop calculation', 'An even split regardless of stacks', 'Whoever has the button', 'The order players busted'], a: 0, e: 'Fair deals weight remaining prize money by stack size, typically via an ICM (or chip-chop) calculation.', tags: ['Poker', 'Final table'] },
];
