// Positional Strategy roadmap questions (80): 10 levels × 8, easiest → hardest.
// Covers pawn structure, weak pawns, open files, outposts, good vs bad bishops,
// space, the bishop pair, weak squares, and planning.

import type { Seed } from './roadmap-build';

export const strategySeeds: Seed[] = [
  // ── Level 1 — Pawn Structure Basics ───────────────────────────────────
  { q: 'What does "strategy" mean in chess?', opts: ['Long-term positional planning based on the pawn structure and pieces','Memorizing the first ten opening moves','Always trading queens early','A single forcing checkmate sequence'], a: 0, e: 'Strategy is long-term positional play — plans and structure — as opposed to short forcing tactics.', tags: ['Chess','Strategy'] },
  { q: 'How does strategy differ from tactics?', opts: ['They are exactly the same thing','Strategy is long-term planning, tactics are short forcing combinations','Tactics only happen in the endgame','Strategy is short forcing shots, tactics are long plans'], a: 1, e: 'Strategy handles long-term plans while tactics are the short, forcing calculations.', tags: ['Chess','Strategy'] },
  { q: 'Why is the pawn structure so important to strategy?', opts: ['Pawns can jump over other pieces','Pawns move backward to defend','The pawn skeleton is semi-permanent and shapes long-term plans','Pawns are the strongest attacking pieces'], a: 2, e: 'Because pawns rarely retreat, their fixed structure defines the long-term character of the position.', tags: ['Chess','Strategy'] },
  { q: 'What is a "pawn chain"?', opts: ['Two pawns on the same file','Pawns that have all been captured','Pawns all standing on the same rank','A diagonal line of pawns defending one another'], a: 3, e: 'A pawn chain is a diagonal row of pawns where each defends the one in front of it.', tags: ['Chess','Strategy'] },
  { q: 'A healthy pawn majority on one wing is valuable mainly because it can eventually create what?', opts: ['A passed pawn','A stalemate','A pinned knight','A back-rank mate'], a: 0, e: 'A pawn majority can be mobilized to produce a passed pawn.', tags: ['Chess','Strategy'] },
  { q: 'Which is generally considered the soundest of these pawn formations?', opts: ['Tripled pawns','A connected, unbroken pawn front','Isolated doubled pawns','Three pawn islands'], a: 1, e: 'Connected, unbroken pawns support each other and have no long-term weaknesses.', tags: ['Chess','Strategy'] },
  { q: 'What is a "pawn island"?', opts: ['A pawn that has just promoted','A single pawn stranded on the eighth rank','A group of one or more pawns separated from other friendly pawns by a file','Any pawn on a light square'], a: 2, e: 'A pawn island is a connected group of pawns cut off from the rest by an empty file; fewer islands is usually healthier.', tags: ['Chess','Strategy'] },
  { q: 'In general, having fewer pawn islands is:', opts: ['Always a losing sign','Irrelevant to strategy','Only good in blitz','A structural advantage'], a: 3, e: 'Fewer pawn islands means a more compact, easier-to-defend structure.', tags: ['Chess','Strategy'] },

  // ── Level 2 — Weak & Isolated Pawns ───────────────────────────────────
  { q: 'What defines an ISOLATED pawn?', opts: ['A pawn with no friendly pawns on either adjacent file','Two pawns stacked on one file','A pawn defended by the king','A pawn that has reached the sixth rank'], a: 0, e: 'An isolated pawn has no friendly pawns on the adjacent files, so no pawn can ever defend it.', tags: ['Chess','Strategy'] },
  { q: 'What are DOUBLED pawns?', opts: ['Pawns on the same diagonal','Two friendly pawns on the same file','Two pawns on adjacent files','A pawn defended twice'], a: 1, e: 'Doubled pawns are two of your own pawns sitting on the same file.', tags: ['Chess','Strategy'] },
  { q: 'What is a BACKWARD pawn?', opts: ['A pawn that can move backward','A pawn on an open file with no enemy in front','A pawn that lags behind its neighbors and cannot advance safely','Any pawn on the second rank'], a: 2, e: 'A backward pawn trails its neighboring pawns and cannot advance without being lost.', tags: ['Chess','Strategy'] },
  { q: 'Why is an isolated pawn considered a long-term weakness?', opts: ['It can never be captured','It automatically becomes doubled','It blocks your own bishop','No friendly pawn can defend it, so pieces must guard it'], a: 3, e: 'Since no pawn can protect it, an isolated pawn ties down pieces to its defense.', tags: ['Chess','Strategy'] },
  { q: 'The square directly in front of an isolated or backward pawn is valuable to the opponent because:', opts: ['It is a perfect blockading square, often for a knight','Pawns can promote there instantly','It is always a check','The pawn defends it'], a: 0, e: 'The square in front cannot be controlled by the weak pawn, making it an ideal blockade/outpost square.', tags: ['Chess','Strategy'] },
  { q: 'What is the standard plan of the side PLAYING AGAINST an isolated queen\'s pawn (IQP)?', opts: ['Castle queenside and attack','Trade pieces and blockade the pawn, then win it in the endgame','Give away the queen','Advance all the kingside pawns immediately'], a: 1, e: 'Against an IQP you exchange pieces, blockade the pawn, and target it as an endgame weakness.', tags: ['Chess','Strategy'] },
  { q: 'What compensation does the side WITH an isolated queen\'s pawn usually enjoy?', opts: ['Two connected passers','An extra pawn','Active piece play and space, using open files and the e5/e4 square','A guaranteed passed pawn'], a: 2, e: 'The IQP grants active pieces, open lines, and central space as dynamic compensation for the long-term weakness.', tags: ['Chess','Strategy'] },
  { q: 'Doubled pawns are not always bad; one real benefit they can provide is:', opts: ['They defend the king better than normal pawns','They can move two squares each turn','They can promote twice as fast','They control extra central squares and open a file for the rooks'], a: 3, e: 'Doubled pawns often grant extra central control and a half-open file for the rooks as compensation.', tags: ['Chess','Strategy'] },

  // ── Level 3 — Open & Half-Open Files ──────────────────────────────────
  { q: 'What is an OPEN file?', opts: ['A file with no pawns on it at all','A file with only your pawns','A file with only enemy pawns','A file where a rook has never moved'], a: 0, e: 'An open file contains no pawns of either side.', tags: ['Chess','Strategy'] },
  { q: 'Which piece most wants to be placed on an open file?', opts: ['The knight','The rook','The bishop','The king'], a: 1, e: 'Rooks belong on open (or half-open) files where their power along the file is unobstructed.', tags: ['Chess','Strategy'] },
  { q: 'What is a HALF-OPEN file (from your point of view)?', opts: ['A file blocked by a knight','A file with pawns of both colors','A file with only the opponent\'s pawns and none of yours','A file with only your own pawns'], a: 2, e: 'A half-open file has only the opponent\'s pawns; your rook can pressure that pawn along it.', tags: ['Chess','Strategy'] },
  { q: 'Placing two rooks on the same open file is called:', opts: ['A pawn storm','Zugzwang','Fianchetto','Doubling rooks'], a: 3, e: 'Stacking both rooks on one file is called doubling, and it multiplies pressure along that file.', tags: ['Chess','Strategy'] },
  { q: 'Why is a rook on the 7th rank so strong?', opts: ['It attacks enemy pawns on their starting rank and hems in the king','It can promote there','It gives check every move','It cannot be captured on the 7th'], a: 0, e: 'A rook on the 7th rank raids the enemy pawns and can trap the king along the back.', tags: ['Chess','Strategy'] },
  { q: 'On a half-open file, the enemy pawn on that file is a natural:', opts: ['Passed pawn','Target for your rook','Outpost for your knight','Promotion square'], a: 1, e: 'The lone enemy pawn on a half-open file is a fixed target your rook can attack.', tags: ['Chess','Strategy'] },
  { q: 'A key strategic goal in many middlegames is to:', opts: ['Never castle','Trade all your rooks immediately','Seize and control the only open file with your rooks','Keep every pawn on its starting square'], a: 2, e: 'Grabbing the open file with the rooks is a classic way to gain and use an advantage.', tags: ['Chess','Strategy'] },
  { q: 'A rook lift (e.g., Rf1-f3-h3) is a maneuver most often used to:', opts: ['Force an immediate draw','Promote a pawn','Defend the first rank forever','Bring a rook into the attack via the third rank'], a: 3, e: 'The rook lift routes a rook along the third rank to join an attack, often on the king.', tags: ['Chess','Strategy'] },

  // ── Level 4 — Outposts & Strong Squares ───────────────────────────────
  { q: 'What is an OUTPOST?', opts: ['An advanced square, safe from enemy pawns, where a piece can sit securely','A file with no pawns','A pinned bishop','A pawn on the seventh rank'], a: 0, e: 'An outpost is an advanced square that enemy pawns can never attack, ideal for a piece.', tags: ['Chess','Strategy'] },
  { q: 'Which piece most loves a protected outpost?', opts: ['The king','The knight','The rook','The queen'], a: 1, e: 'Knights thrive on outposts because they cannot be chased by pawns and radiate influence from there.', tags: ['Chess','Strategy'] },
  { q: 'For a square to be a true outpost, it must be:', opts: ['On the edge of the board','On the first rank','Unable to be attacked by any enemy pawn','Occupied by a pawn'], a: 2, e: 'The defining feature of an outpost is that no enemy pawn can ever kick the piece away.', tags: ['Chess','Strategy'] },
  { q: 'On which ranks are outposts typically most valuable for White?', opts: ['8th only','It never matters','1st–2nd','4th–6th'], a: 3, e: 'Advanced outposts on the 4th to 6th ranks let a knight dominate deep in enemy territory.', tags: ['Chess','Strategy'] },
  { q: 'A knight firmly planted on an outpost like d6 or e6 is often worth more than a rook because:', opts: ['It cripples the opponent\'s coordination and cannot be dislodged','It gives perpetual check','Knights are always worth a rook','It can promote'], a: 0, e: 'A dominating, unassailable knight can paralyze the enemy position, sometimes outweighing a rook.', tags: ['Chess','Strategy'] },
  { q: 'To create an outpost for your knight, you often want to:', opts: ['Keep all pawns on their home squares','Advance or trade to remove the enemy pawns that could attack the square','Double your own pawns in front of it','Trade off your knight first'], a: 1, e: 'You engineer an outpost by eliminating the enemy pawns that could otherwise control the square.', tags: ['Chess','Strategy'] },
  { q: 'A "hole" in a position is:', opts: ['A trapped rook','A move that loses instantly','A square that can no longer be defended by a pawn, often becoming an outpost','A file with three pawns'], a: 2, e: 'A hole is a weak square a pawn can no longer guard, which the opponent may occupy as an outpost.', tags: ['Chess','Strategy'] },
  { q: 'Playing ...f5 and later ...f4, or pushing a pawn past a key square, can be double-edged because it may:', opts: ['Win a queen automatically','Undouble your pawns','Force stalemate','Create a permanent hole/outpost for the enemy on the square left behind'], a: 3, e: 'Advancing a pawn permanently surrenders control of the square behind it, which can become an enemy outpost.', tags: ['Chess','Strategy'] },

  // ── Level 5 — Good vs Bad Bishops ─────────────────────────────────────
  { q: 'What is a "bad" bishop?', opts: ['A bishop hemmed in by its own pawns fixed on its color','Any bishop that has not moved','A bishop on a white square','A bishop worth less than a pawn'], a: 0, e: 'A bad bishop is blocked by its own pawns sitting on the same color squares it travels.', tags: ['Chess','Strategy'] },
  { q: 'What makes a bishop "good"?', opts: ['It never leaves the back rank','It has open diagonals and is not blocked by its own pawns','It sits behind its own pawn chain','It is the same color as the enemy king'], a: 1, e: 'A good bishop enjoys open diagonals unobstructed by its own pawns.', tags: ['Chess','Strategy'] },
  { q: 'To improve a bad bishop, a common plan is to:', opts: ['Never move it again','Put your pawns and bishop on the same square','Trade it off or free it by moving your pawns off its color','Lock all your pawns on its color'], a: 2, e: 'You cure a bad bishop by exchanging it or by relocating the pawns that block it.', tags: ['Chess','Strategy'] },
  { q: 'If your pawns are fixed on light squares, which of your bishops becomes bad?', opts: ['Both bishops equally','Neither bishop','The dark-squared bishop','The light-squared bishop'], a: 3, e: 'Pawns fixed on light squares obstruct the light-squared bishop, making it the bad one.', tags: ['Chess','Strategy'] },
  { q: 'In a closed position with locked pawn chains, which minor piece is usually superior?', opts: ['The knight, because it can hop over the fixed pawns','The bishop, always','The rook','The king'], a: 0, e: 'Knights outshine bishops in closed positions because they can jump over the blocked pawn structure.', tags: ['Chess','Strategy'] },
  { q: 'In an open position with pawns on both wings, which minor piece is usually superior?', opts: ['The knight','The bishop, for its long-range reach across the board','Neither, they are always equal','The rook counts as a minor piece'], a: 1, e: 'In open positions bishops dominate thanks to their long-range control of both flanks.', tags: ['Chess','Strategy'] },
  { q: 'A useful practical rule about your own pawns and your remaining bishop is:', opts: ['Pawn color never matters','Put pawns on the same color as your bishop','Keep pawns on the opposite color of your bishop so it stays active','Bishops and pawns should share a diagonal'], a: 2, e: 'Placing pawns on the opposite color of your bishop keeps its diagonals open and the bishop good.', tags: ['Chess','Strategy'] },
  { q: 'A bishop that is temporarily blocked by pawns but could become active if the structure changes is sometimes called:', opts: ['A fianchettoed knight','A dead bishop','A "big pawn"','A tall pawn or a bishop with potential'], a: 3, e: 'Such a bishop is a "tall pawn" for now but may spring to life once the pawns shift, so it has latent potential.', tags: ['Chess','Strategy'] },

  // ── Level 6 — Space & the Center ──────────────────────────────────────
  { q: 'What does a "space advantage" mean?', opts: ['Having pawns advanced further, giving your pieces more room','Having captured the enemy queen','Owning both bishops','Having more pieces on the board'], a: 0, e: 'A space advantage comes from advanced pawns that give your pieces greater freedom of movement.', tags: ['Chess','Strategy'] },
  { q: 'The side with more space should generally:', opts: ['Trade off as many pieces as possible','Avoid piece trades to keep the cramped side short of room','Give up the center','Push the a-pawn only'], a: 1, e: 'With more space you avoid trades, since exchanges relieve the opponent\'s cramped position.', tags: ['Chess','Strategy'] },
  { q: 'The side with LESS space should generally:', opts: ['Never move a pawn','Resign','Seek exchanges to gain breathing room','Keep all pieces on to stay cramped'], a: 2, e: 'The cramped side benefits from trades, which free up space for the remaining pieces.', tags: ['Chess','Strategy'] },
  { q: 'Why is controlling the center strategically important?', opts: ['The center squares give bonus points','Only central pawns can promote','It forces the enemy to castle','Central pieces reach both wings quickly and enjoy maximum mobility'], a: 3, e: 'Central control gives pieces maximum reach and lets you shift forces to either flank fastest.', tags: ['Chess','Strategy'] },
  { q: 'A classical center (pawns on d4 and e4) is strong but must be:', opts: ['Maintained and supported, since if it is undermined it can become a target','Immediately traded','Doubled','Ignored'], a: 0, e: 'A big pawn center is powerful when supported but becomes a liability if the opponent successfully undermines it.', tags: ['Chess','Strategy'] },
  { q: 'In hypermodern strategy, the center is:', opts: ['Occupied by pawns as early as possible','Controlled from a distance by pieces (e.g., a fianchettoed bishop) then attacked','Completely ignored all game','Only about the a- and h-files'], a: 1, e: 'Hypermodern play lets the opponent build a center, then controls and attacks it with pieces from afar.', tags: ['Chess','Strategy'] },
  { q: 'A protected passed pawn cramping the enemy is an example of using space where the key idea is that the pawn:', opts: ['Only helps in the opening','Can always be captured for free','Is defended by another pawn and cannot be blockaded cheaply','Must be given up quickly'], a: 2, e: 'A protected passed pawn is defended by a fellow pawn, making it hard to blockade or win and a lasting space asset.', tags: ['Chess','Strategy'] },
  { q: 'A space advantage carries a hidden risk if overextended, namely:', opts: ['It forces you to promote too fast','Your king is safer than you want','Your pieces gain too much room','The advanced pawns can become weak and be attacked from behind'], a: 3, e: 'Overextended pawns leave weak squares and can themselves become targets, so space must be handled with care.', tags: ['Chess','Strategy'] },

  // ── Level 7 — The Two Bishops ─────────────────────────────────────────
  { q: 'The "bishop pair" refers to:', opts: ['Having both bishops versus an opponent who has a bishop and knight or two knights','A bishop plus a rook','Two bishops that have been traded','Two bishops of the same color square'], a: 0, e: 'The bishop pair means keeping both bishops while the opponent has surrendered one of theirs for a knight.', tags: ['Chess','Strategy'] },
  { q: 'The bishop pair is most advantageous in:', opts: ['Closed, locked positions','Open positions where both bishops sweep long diagonals','Positions with no pawns left','Only in the opening'], a: 1, e: 'Two bishops shine in open positions where their long-range diagonals control the whole board.', tags: ['Chess','Strategy'] },
  { q: 'Why do two bishops complement each other so well?', opts: ['They can never be pinned','They can occupy the same square','Together they cover both light and dark squares','They move like knights'], a: 2, e: 'The two bishops jointly control both color complexes, covering squares a single bishop cannot.', tags: ['Chess','Strategy'] },
  { q: 'When you own the bishop pair, a good general strategy is to:', opts: ['Trade one bishop immediately','Trap your own bishops behind pawns','Close the position with locked pawns','Open the position so the bishops gain scope'], a: 3, e: 'You want to open lines so the pair can exploit its long-range advantage.', tags: ['Chess','Strategy'] },
  { q: 'The side FIGHTING against the bishop pair often tries to:', opts: ['Trade one of the bishops or keep the position closed','Give up a rook','Push all pawns to the seventh rank','Keep the position open'], a: 0, e: 'To neutralize the pair you swap off one bishop or keep the structure closed to blunt them.', tags: ['Chess','Strategy'] },
  { q: 'A common technique with the bishop pair in the endgame is to:', opts: ['Promote a bishop','Use the bishops to dominate a lone knight and restrict its squares','Trade both bishops for the knight','Keep the bishops on the back rank'], a: 1, e: 'In the endgame the two bishops can cut off and dominate an enemy knight, controlling its escape squares.', tags: ['Chess','Strategy'] },
  { q: 'Roughly how much is the bishop pair often valued at in open positions?', opts: ['Nothing at all','A full rook','About half a pawn of extra value','Three pawns'], a: 2, e: 'The bishop pair is commonly reckoned worth around half a pawn, more in very open positions.', tags: ['Chess','Strategy'] },
  { q: 'Giving up the bishop pair can still be correct when:', opts: ['Only if you are losing','Only in blitz games','Never, the pair is always kept','It wins material, damages the enemy structure, or the position is closed'], a: 3, e: 'Surrendering a bishop is fine when it gains material, wrecks the opponent\'s pawns, or the closed nature favors a knight.', tags: ['Chess','Strategy'] },

  // ── Level 8 — Weak Squares & Color Complexes ──────────────────────────
  { q: 'A "weak square" is best described as:', opts: ['A square that can no longer be controlled or defended by a pawn','Any square on the edge','A square with a rook on it','A square a pawn stands on'], a: 0, e: 'A weak square is one your pawns can no longer guard, making it available to enemy pieces.', tags: ['Chess','Strategy'] },
  { q: 'A "color complex" weakness means:', opts: ['Your king is on a corner square','You are weak on all squares of one color, often light or dark','Your bishops are painted the wrong color','You have too many pawns'], a: 1, e: 'A color-complex weakness is a chronic lack of control over the squares of one particular color.', tags: ['Chess','Strategy'] },
  { q: 'Trading off a fianchettoed bishop (e.g., a g7-bishop) is risky because it often:', opts: ['Forces stalemate','Wins a pawn for the opponent','Leaves the dark squares around the king permanently weak','Doubles your rooks'], a: 2, e: 'Removing the fianchettoed bishop leaves the squares of its color near the king weak and hard to defend.', tags: ['Chess','Strategy'] },
  { q: 'If your opponent has a chronic dark-square weakness, you especially want to keep:', opts: ['Both rooks on the first rank','Your light-squared bishop only','No minor pieces at all','Your dark-squared bishop to exploit those squares'], a: 3, e: 'You retain the dark-squared bishop to dominate and invade on the opponent\'s weak dark squares.', tags: ['Chess','Strategy'] },
  { q: 'Weak squares matter most when:', opts: ['They can actually be occupied by an enemy piece that stays there','They are on the eighth rank only','No pieces remain','They are defended by three pawns'], a: 0, e: 'A weak square is only truly a problem if the opponent can plant a piece on it securely.', tags: ['Chess','Strategy'] },
  { q: 'The classic way to exploit a weak square is to:', opts: ['Ignore it','Occupy it with a well-supported piece, usually a knight','Trade all pieces at once','Push a pawn onto it and lose it'], a: 1, e: 'You exploit a weak square by installing a durable, protected piece (often a knight) on it.', tags: ['Chess','Strategy'] },
  { q: 'Weak squares of one color frequently arise together with:', opts: ['A doubled rook','Castling kingside','A missing or bad bishop of that color','An extra queen'], a: 2, e: 'Losing or having a bad bishop of a given color typically leaves that color complex weak.', tags: ['Chess','Strategy'] },
  { q: 'A pawn structure with pawns fixed on one color creates weak squares on:', opts: ['Only the central four squares','No squares at all','The same color as the pawns','The opposite color from the pawns'], a: 3, e: 'Pawns on one color cannot guard the opposite-colored squares, so those become the weak complex.', tags: ['Chess','Strategy'] },

  // ── Level 9 — Planning & Piece Placement ──────────────────────────────
  { q: 'A sound middlegame plan should be based primarily on:', opts: ['The specific features of the position — structure, weaknesses, and piece activity','Always attacking the king no matter what','Copying your last game','A coin flip'], a: 0, e: 'Good plans grow directly from the concrete strategic features of the position.', tags: ['Chess','Strategy'] },
  { q: 'The "principle of two weaknesses" says the stronger side often wins by:', opts: ['Sacrificing the queen','Creating a second weakness so the defender cannot cover both','Trading into a drawn endgame','Attacking only one point forever'], a: 1, e: 'By opening a second front, the attacker overloads a defender who cannot guard two weaknesses at once.', tags: ['Chess','Strategy'] },
  { q: 'Identifying your worst-placed piece and improving it is a famous guideline associated with:', opts: ['Pushing the h-pawn','Always trading queens','The idea that improving your least active piece improves the whole position','Never castling'], a: 2, e: 'A classic method is to find your worst piece and bring it to a better square, lifting the whole position.', tags: ['Chess','Strategy'] },
  { q: 'Prophylaxis in chess means:', opts: ['Trading everything','Ignoring the opponent entirely','Attacking at all costs','Anticipating and preventing the opponent\'s plans before pursuing your own'], a: 3, e: 'Prophylactic thinking asks what the opponent wants and stops it before advancing your own plan.', tags: ['Chess','Strategy'] },
  { q: 'When you have a space advantage on the queenside, your plan is usually to:', opts: ['Attack and expand on the queenside where you are stronger','Immediately push the h-pawn','Trade all your pawns','Move your king to the queenside first'], a: 0, e: 'You generally attack where you are strongest — here the queenside, using your extra space.', tags: ['Chess','Strategy'] },
  { q: 'The classic maxim about attacking a pawn chain is to strike at its:', opts: ['Head (the most advanced pawn)','Base (the rearmost pawn), which supports the rest','Middle only','Adjacent file'], a: 1, e: 'Attacking the base of a pawn chain undermines the whole structure it supports.', tags: ['Chess','Strategy'] },
  { q: 'Overprotection, a Nimzowitsch idea, means:', opts: ['Trading the queen for safety','Moving the king three times','Defending a key point with more force than seems necessary so pieces gain flexibility','Never defending anything'], a: 2, e: 'Overprotecting an important square with several pieces both secures it and gives those pieces added scope.', tags: ['Chess','Strategy'] },
  { q: 'Before committing to a pawn break, you should mainly evaluate:', opts: ['Only whether it looks aggressive','Whether it uses your a-pawn','If it is your opponent\'s favorite move','Whether it favorably opens lines for your better-placed pieces'], a: 3, e: 'A pawn break is good when the lines it opens benefit your pieces more than the opponent\'s.', tags: ['Chess','Strategy'] },

  // ── Level 10 — Strategy Mastery ───────────────────────────────────────
  { q: 'You hold the bishop pair against a knight, but the center pawns are locked. The most consistent plan is to:', opts: ['Prepare a pawn break to open the position for your bishops','Trade a bishop for the knight at once','Shuffle rooks on the back rank','Keep the center closed to help the knight'], a: 0, e: 'With the bishop pair you engineer a break to open lines and unleash the bishops\' long-range power.', tags: ['Chess','Strategy'] },
  { q: 'Your opponent has an isolated queen\'s pawn and few pieces remain. Correct strategy is to:', opts: ['Advance your own pawns recklessly','Keep trading pieces and blockade the pawn, aiming to win it in the endgame','Sacrifice a piece for a kingside attack','Return the pieces to the back rank'], a: 1, e: 'Against an IQP in a simplified position you trade down, blockade, and target the pawn as an endgame weakness.', tags: ['Chess','Strategy'] },
  { q: 'You can win a pawn but it saddles you with doubled, isolated pawns and hands your opponent an open file and the bishop pair. This is:', opts: ['A forced checkmate','Always correct — a pawn is a pawn','A structural trade-off to weigh; the positional concessions may outweigh the pawn','Illegal'], a: 2, e: 'Grabbing the pawn is only right if the pawn outweighs the resulting structural and piece-activity concessions.', tags: ['Chess','Strategy'] },
  { q: 'A knight reaches a protected outpost on d5 that no enemy pawn can attack, dominating the board. To fight it the opponent should ideally:', opts: ['Leave it and attack elsewhere forever','Push a pawn onto d6','Move the king toward it','Trade a piece to eliminate the monster knight, even conceding the bishop pair'], a: 3, e: 'A dominant outpost knight is often worth exchanging a bishop for, removing the strongest enemy piece.', tags: ['Chess','Strategy'] },
  { q: 'Your opponent fianchettoed on g7, then traded that dark-squared bishop. The thematic follow-up is to:', opts: ['Target the weakened dark squares around the enemy king','Advance your h-pawn to h3 only','Retreat your pieces','Trade queens immediately'], a: 0, e: 'Once the fianchettoed bishop is gone, you invade the resulting weak dark squares near the king.', tags: ['Chess','Strategy'] },
  { q: 'You have more space and the bishop pair in an open position; your opponent is cramped. The best overall strategy combines:', opts: ['Ignoring the center','Avoiding trades to keep them cramped while opening lines for the bishops','Trading everything to reach a draw','Locking the pawns to help their knight'], a: 1, e: 'You keep pieces on to preserve the cramp and open lines so your bishops and space tell.', tags: ['Chess','Strategy'] },
  { q: 'A rook reaches the open file and prepares to double and invade the 7th rank while the opponent has a backward pawn on that file. The plan is to:', opts: ['Push the rook\'s pawn to promote','Abandon the file','Double rooks, penetrate to the 7th, and pressure the backward pawn','Trade both rooks off'], a: 2, e: 'You double on the open file, break into the 7th rank, and win or bind the backward pawn.', tags: ['Chess','Strategy'] },
  { q: 'Deciding between a knight and a bishop to keep, you note the position is opening up with pawns on both wings. You should generally keep the:', opts: ['King, as a fighting piece','Neither; trade both','Knight, because it is faster','Bishop, because open positions with pawns on both flanks favor its range'], a: 3, e: 'In an opening position with pawns on both wings the long-range bishop outperforms the knight.', tags: ['Chess','Strategy'] },
];
