import type { Seed } from './roadmap-build';

// "Security" learning path — 120 questions (15 levels × 8), easiest → hardest:
// security fundamentals, authentication & authorization, password hashing,
// sessions/JWT, HTTPS/TLS, injection, XSS, CSRF, the OWASP Top 10, secrets
// management, secure headers, supply chain, privacy and threat modeling.
// (ids rm-security-1 … rm-security-120, 8 per level).
export const securitySeeds: Seed[] = [
  // Level 1 — Security Fundamentals
  { q: 'The "CIA triad" in security stands for:', opts: ['Central Intelligence Agency', 'Confidentiality, Integrity, Availability', 'Code, Infrastructure, Automation', 'Cipher, Identity, Authorization'], a: 1, e: 'The CIA triad — Confidentiality, Integrity, Availability — defines the core goals of information security.', tags: ['Security', 'fundamentals'], intro: 'Start with the core principles.' },
  { q: 'The principle of least privilege means:', opts: ['Give everyone admin', 'Grant each user/process only the minimum permissions it needs', 'Remove all access', 'Share one account'], a: 1, e: 'Least privilege limits each actor’s permissions to the minimum required, shrinking the damage from compromise.', tags: ['Security', 'least-privilege'] },
  { q: 'Defense in depth means:', opts: ['One strong wall only', 'Multiple layered controls so one failure doesn’t breach everything', 'No controls', 'Encryption only'], a: 1, e: 'Defense in depth layers independent controls, so an attacker must defeat several to succeed.', tags: ['Security', 'defense-in-depth'] },
  { q: '"Never trust user input" implies you should:', opts: ['Render input as-is', 'Validate, sanitize, and treat all external input as potentially hostile', 'Trust authenticated users fully', 'Only check input in the UI'], a: 1, e: 'All external input can be malicious; validate and sanitize on the server, regardless of client checks.', tags: ['Security', 'input'] },
  { q: 'The "attack surface" of a system is:', opts: ['Its UI color', 'The sum of points where an attacker can try to interact/enter', 'The database size', 'The number of users'], a: 1, e: 'Attack surface is all the exposed entry points (endpoints, inputs, dependencies); minimizing it reduces risk.', tags: ['Security', 'attack-surface'] },
  { q: 'Security by obscurity (relying only on secrecy of design) is:', opts: ['A strong primary defense', 'Weak on its own — security should not depend on hidden design alone', 'Required by TLS', 'The same as encryption'], a: 1, e: 'Hiding details may help slightly, but real security must hold even if the design is known (Kerckhoffs’s principle).', tags: ['Security', 'obscurity'] },
  { q: '"Fail securely" means when something errors, the system should:', opts: ['Grant access by default', 'Deny access / default to the safe state', 'Expose stack traces to users', 'Disable logging'], a: 1, e: 'On failure, default to denying access and revealing nothing sensitive, rather than failing open.', tags: ['Security', 'fail-secure'] },
  { q: 'A "zero trust" approach assumes:', opts: ['The internal network is automatically safe', 'No request is trusted by default; verify every request regardless of origin', 'Firewalls are enough', 'Users never lie'], a: 1, e: 'Zero trust verifies identity and authorization for every request, not relying on network location as trust.', tags: ['Security', 'zero-trust'] },

  // Level 2 — Authentication
  { q: 'Authentication answers the question:', opts: ['What can you do?', 'Who are you? (verifying identity)', 'Where are you?', 'How fast are you?'], a: 1, e: 'Authentication verifies identity (who you are); authorization decides what you’re allowed to do.', tags: ['AuthN', 'basics'] },
  { q: 'Multi-factor authentication (MFA) combines:', opts: ['Two passwords', 'Factors from different categories: something you know, have, and/or are', 'Two usernames', 'One factor twice'], a: 1, e: 'MFA requires factors of different types (knowledge, possession, inherence), so a stolen password alone isn’t enough.', tags: ['AuthN', 'mfa'] },
  { q: 'A password is an example of which authentication factor?', opts: ['Something you have', 'Something you know', 'Something you are', 'Somewhere you are'], a: 1, e: 'A password is a "knowledge" factor; a phone/token is "possession"; a fingerprint is "inherence".', tags: ['AuthN', 'factors'] },
  { q: 'OAuth 2.0 is primarily a framework for:', opts: ['Encrypting disks', 'Delegated authorization (granting an app limited access on your behalf)', 'Hashing passwords', 'Compressing data'], a: 1, e: 'OAuth 2.0 lets a user authorize an app to access resources without sharing their password (delegated access).', tags: ['AuthN', 'oauth'] },
  { q: 'OpenID Connect (OIDC) adds to OAuth:', opts: ['Disk encryption', 'An identity/authentication layer (who the user is) via ID tokens', 'A database', 'A CDN'], a: 1, e: 'OIDC builds on OAuth 2.0 to provide authentication and user identity (ID tokens), not just authorization.', tags: ['AuthN', 'oidc'] },
  { q: 'Account lockout/throttling after repeated failed logins defends against:', opts: ['XSS', 'Brute-force password guessing', 'CSRF', 'SQL injection'], a: 1, e: 'Rate limiting/lockout slows brute-force attacks that try many password guesses.', tags: ['AuthN', 'brute-force'] },
  { q: 'Single sign-on (SSO) lets users:', opts: ['Use one identity to access many applications', 'Have many passwords per app', 'Skip authentication', 'Disable MFA'], a: 0, e: 'SSO authenticates once with a central identity provider, granting access to multiple connected applications.', tags: ['AuthN', 'sso'] },
  { q: 'Generic login error messages ("invalid email or password") help by:', opts: ['Confusing users', 'Not revealing whether the email exists (avoiding user enumeration)', 'Improving speed', 'Disabling MFA'], a: 1, e: 'Vague errors prevent attackers from learning which accounts exist (user enumeration).', tags: ['AuthN', 'enumeration'] },

  // Level 3 — Authorization
  { q: 'Authorization determines:', opts: ['Who you are', 'What an authenticated identity is allowed to do/access', 'Your IP address', 'Your password'], a: 1, e: 'Authorization (access control) decides which actions/resources an authenticated user may use.', tags: ['AuthZ', 'basics'] },
  { q: 'Role-based access control (RBAC) grants permissions based on:', opts: ['Random chance', 'A user’s assigned role(s) (e.g. admin, editor, viewer)', 'IP address only', 'Password length'], a: 1, e: 'RBAC assigns permissions to roles and roles to users, simplifying management of who can do what.', tags: ['AuthZ', 'rbac'] },
  { q: 'A "broken access control" bug is when:', opts: ['Passwords are weak', 'Users can access resources/actions they shouldn’t be allowed to', 'TLS is misconfigured', 'Logs are missing'], a: 1, e: 'Broken access control (OWASP #1) lets users perform actions or view data beyond their authorization.', tags: ['AuthZ', 'broken-access'] },
  { q: 'An IDOR (Insecure Direct Object Reference) happens when:', opts: ['Passwords are reused', 'Changing an id in a request (e.g. /orders/124) lets you access another user’s object', 'TLS is old', 'Cookies expire'], a: 1, e: 'IDOR is missing object-level authorization: the server returns data by id without checking the requester owns it.', tags: ['AuthZ', 'idor'] },
  { q: 'Authorization checks must be enforced:', opts: ['Only in the client UI', 'On the server for every protected action', 'Only at login', 'Never'], a: 1, e: 'Client-side checks are bypassable; the server must verify authorization on every protected request.', tags: ['AuthZ', 'server-side'] },
  { q: 'Hiding an admin button in the UI but not checking permission on the server is:', opts: ['Secure', 'Insecure — the endpoint can still be called directly', 'Best practice', 'Encryption'], a: 1, e: 'UI hiding is cosmetic; without server-side authorization, the endpoint is exploitable by direct requests.', tags: ['AuthZ', 'client-vs-server'] },
  { q: 'Deny-by-default authorization means:', opts: ['Allow everything unless blocked', 'Block everything unless explicitly permitted', 'No checks at all', 'Allow admins only'], a: 1, e: 'Default-deny is safer: access is refused unless a rule explicitly grants it, preventing accidental exposure.', tags: ['AuthZ', 'default-deny'] },
  { q: 'Attribute/policy-based access control (ABAC) decides access using:', opts: ['Only a single role', 'Attributes/policies (user, resource, context) for fine-grained rules', 'Password length', 'IP only'], a: 1, e: 'ABAC evaluates attributes (e.g. department, ownership, time) for flexible, fine-grained authorization beyond simple roles.', tags: ['AuthZ', 'abac'] },

  // Level 4 — Passwords & Hashing
  { q: 'Passwords should be stored:', opts: ['In plaintext', 'As salted hashes using a slow password-hashing algorithm', 'Encrypted with a shared key', 'In the source code'], a: 1, e: 'Never store plaintext; use a slow, salted password hash (bcrypt/scrypt/Argon2) so leaks don’t expose passwords.', tags: ['Passwords', 'hashing'] },
  { q: 'A "salt" is:', opts: ['A secret key', 'A unique random value added per password before hashing', 'A type of cipher', 'A session token'], a: 1, e: 'A per-user salt ensures identical passwords hash differently, defeating precomputed rainbow tables.', tags: ['Passwords', 'salt'] },
  { q: 'Why use a deliberately slow hash (bcrypt/Argon2) for passwords?', opts: ['To slow logins for fun', 'To make brute-forcing leaked hashes computationally expensive', 'To save CPU', 'To compress the password'], a: 1, e: 'Slow, work-factor hashes drastically increase the cost of guessing each password if the hash database leaks.', tags: ['Passwords', 'slow-hash'] },
  { q: 'Using a fast hash like MD5/SHA-256 (alone) for passwords is:', opts: ['Recommended', 'Insecure — they’re too fast to brute-force and have no built-in salt/work factor', 'Required', 'The same as bcrypt'], a: 1, e: 'General-purpose fast hashes are easy to brute-force at scale; password hashing needs salting and a tunable cost.', tags: ['Passwords', 'mistakes'] },
  { q: 'A "rainbow table" attack is defeated mainly by:', opts: ['Longer usernames', 'Per-password salting', 'Faster hashing', 'Plaintext storage'], a: 1, e: 'Unique salts make precomputed hash tables (rainbow tables) useless, since each password hashes uniquely.', tags: ['Passwords', 'rainbow'] },
  { q: 'Modern password guidance favors:', opts: ['Frequent forced resets and complex rules', 'Longer passphrases and checking against known-breached lists', 'Short complex passwords', 'No password manager'], a: 1, e: 'Current guidance (NIST) prefers length/passphrases and breach checks over arbitrary complexity and forced rotation.', tags: ['Passwords', 'policy'] },
  { q: 'A "pepper" differs from a salt by being:', opts: ['Stored with each hash', 'A secret kept separate from the database (e.g. in app config)', 'Public', 'Per-user random'], a: 1, e: 'A pepper is a secret applied to all passwords and stored outside the DB, adding protection if only the DB leaks.', tags: ['Passwords', 'pepper'] },
  { q: 'Credential stuffing exploits the fact that:', opts: ['Hashes are slow', 'People reuse passwords across sites, so leaked credentials work elsewhere', 'Salts are unique', 'MFA is enabled'], a: 1, e: 'Attackers replay leaked username/password pairs on other sites, succeeding wherever users reused them — MFA mitigates this.', tags: ['Passwords', 'credential-stuffing'] },

  // Level 5 — Sessions & Tokens (JWT)
  { q: 'After login, a server commonly tracks the user via:', opts: ['Their IP only', 'A session id (cookie) or a token', 'Their password each request', 'Nothing'], a: 1, e: 'Sessions/tokens let the server recognize an authenticated user across requests without re-sending the password.', tags: ['Sessions', 'basics'] },
  { q: 'A session cookie should typically be set with:', opts: ['No flags', 'HttpOnly, Secure, and SameSite attributes', 'A long plaintext password', 'Public read access'], a: 1, e: 'HttpOnly blocks JS access (XSS theft), Secure requires HTTPS, and SameSite mitigates CSRF.', tags: ['Sessions', 'cookies'] },
  { q: 'The HttpOnly cookie flag prevents:', opts: ['HTTPS', 'JavaScript from reading the cookie (limiting XSS token theft)', 'CSRF entirely', 'Cookies from being sent'], a: 1, e: 'HttpOnly stops client-side JS from accessing the cookie, so XSS can’t easily steal the session token.', tags: ['Sessions', 'httponly'] },
  { q: 'A JWT (JSON Web Token) is:', opts: ['Always encrypted', 'A signed token carrying claims that the server can verify without a DB lookup', 'A password', 'A cookie flag'], a: 1, e: 'A JWT is a signed (not necessarily encrypted) token of claims; the signature lets the server trust it statelessly.', tags: ['Tokens', 'jwt'] },
  { q: 'A common JWT pitfall is:', opts: ['Verifying the signature', 'Putting sensitive data in the (base64, readable) payload thinking it’s hidden', 'Short expiry', 'Using HTTPS'], a: 1, e: 'JWT payloads are merely base64-encoded, not encrypted — anyone can read them, so never put secrets there.', tags: ['Tokens', 'jwt-pitfall'] },
  { q: 'Short token lifetimes plus refresh tokens help by:', opts: ['Never expiring', 'Limiting the damage window if an access token is stolen', 'Removing authentication', 'Disabling logout'], a: 1, e: 'Short-lived access tokens reduce exposure; refresh tokens (revocable) get new ones without frequent re-login.', tags: ['Tokens', 'expiry'] },
  { q: 'A downside of stateless JWTs is that:', opts: ['They’re easy to revoke instantly', 'They’re hard to revoke before expiry without extra infrastructure', 'They can’t carry claims', 'They require a database'], a: 1, e: 'Because servers don’t store them, JWTs can’t be trivially invalidated early; you need denylists/short expiry to revoke.', tags: ['Tokens', 'revocation'] },
  { q: 'Storing a JWT in localStorage (vs an HttpOnly cookie) increases risk of:', opts: ['CSRF only', 'Theft via XSS, since JS can read localStorage', 'Slower requests', 'TLS failures'], a: 1, e: 'localStorage is readable by JS, so an XSS flaw can exfiltrate the token; HttpOnly cookies aren’t JS-accessible.', tags: ['Tokens', 'storage'] },

  // Level 6 — HTTPS & TLS
  { q: 'HTTPS protects traffic by providing:', opts: ['Only faster loading', 'Encryption, integrity, and server authentication via TLS', 'A database', 'Nothing'], a: 1, e: 'HTTPS uses TLS to encrypt data in transit, detect tampering, and authenticate the server’s identity.', tags: ['TLS', 'https'] },
  { q: 'Without HTTPS, data sent over the network can be:', opts: ['Never seen', 'Read or modified by anyone on the path (man-in-the-middle)', 'Automatically encrypted', 'Compressed only'], a: 1, e: 'Plain HTTP is readable and modifiable in transit, enabling eavesdropping and man-in-the-middle attacks.', tags: ['TLS', 'mitm'] },
  { q: 'A TLS certificate is used to:', opts: ['Speed up the CPU', 'Prove the server’s identity and enable an encrypted connection', 'Store passwords', 'Replace cookies'], a: 1, e: 'Certificates (signed by a CA) authenticate the server and underpin the encrypted TLS session.', tags: ['TLS', 'certificates'] },
  { q: 'A certificate authority (CA) is:', opts: ['A hacker group', 'A trusted entity that signs certificates so browsers trust them', 'A type of cookie', 'A password store'], a: 1, e: 'CAs vouch for certificate ownership; browsers trust certs chaining to a trusted CA.', tags: ['TLS', 'ca'] },
  { q: 'HSTS (HTTP Strict Transport Security) tells browsers to:', opts: ['Allow HTTP', 'Always use HTTPS for the site, preventing downgrade to HTTP', 'Disable TLS', 'Cache forever'], a: 1, e: 'HSTS forces HTTPS for future visits, blocking protocol-downgrade and some man-in-the-middle attacks.', tags: ['TLS', 'hsts'] },
  { q: 'TLS provides "encryption in transit." Sensitive data also needs:', opts: ['Nothing more', 'Protection at rest (e.g. encrypted storage)', 'Only HTTP', 'Public storage'], a: 1, e: 'TLS protects data moving over the network; data at rest needs its own protection (encryption, access control).', tags: ['TLS', 'at-rest'] },
  { q: 'Mixed content (HTTPS page loading HTTP resources) is risky because:', opts: ['It loads faster', 'The insecure resources can be intercepted/altered, undermining the secure page', 'It is always blocked', 'It improves SEO'], a: 1, e: 'HTTP sub-resources on an HTTPS page can be tampered with in transit, weakening the page’s security.', tags: ['TLS', 'mixed-content'] },
  { q: 'Modern TLS configuration should:', opts: ['Support old protocols like SSLv3', 'Use up-to-date protocol versions and strong cipher suites, disabling weak/legacy ones', 'Disable certificates', 'Use self-signed certs in prod'], a: 1, e: 'Keep TLS current (TLS 1.2/1.3, strong ciphers) and disable deprecated, vulnerable protocols/ciphers.', tags: ['TLS', 'config'] },

  // Level 7 — Injection (SQLi)
  { q: 'SQL injection occurs when:', opts: ['Queries are parameterized', 'Untrusted input is concatenated into a SQL query, letting attackers alter it', 'TLS is enabled', 'Passwords are hashed'], a: 1, e: 'SQLi happens when user input is built directly into SQL, allowing attackers to change the query’s meaning.', tags: ['Injection', 'sqli'] },
  { q: 'The primary defense against SQL injection is:', opts: ['Hiding error messages only', 'Parameterized queries / prepared statements', 'Faster databases', 'Longer passwords'], a: 1, e: 'Parameterized queries separate code from data, so input can’t be interpreted as SQL — the core SQLi fix.', tags: ['Injection', 'parameterized'] },
  { q: "An input like ' OR '1'='1 in a vulnerable login is an attempt to:", opts: ['Crash the CSS', 'Make the WHERE clause always true to bypass authentication', 'Speed up the query', 'Encrypt the DB'], a: 1, e: "The classic ' OR '1'='1 makes the condition always true, potentially logging in without valid credentials.", tags: ['Injection', 'example'] },
  { q: 'Injection vulnerabilities are not limited to SQL; they also affect:', opts: ['Only CSS', 'OS commands, LDAP, NoSQL, and more whenever input is interpreted as code', 'Nothing else', 'Only images'], a: 1, e: 'Any interpreter (shell, LDAP, NoSQL, templates) is vulnerable when untrusted input is treated as code.', tags: ['Injection', 'general'] },
  { q: 'An ORM helps reduce SQLi risk by:', opts: ['Encrypting the database', 'Generating parameterized queries instead of string concatenation', 'Disabling SQL', 'Hashing inputs'], a: 1, e: 'ORMs typically parameterize queries by default, reducing manual string-building SQLi risk (raw queries still need care).', tags: ['Injection', 'orm'] },
  { q: 'Input validation (allow-listing) complements parameterization by:', opts: ['Replacing it entirely', 'Rejecting clearly invalid input early as defense in depth', 'Encrypting input', 'Slowing the server'], a: 1, e: 'Validation/allow-listing reduces attack surface, but parameterized queries remain the primary SQLi defense.', tags: ['Injection', 'validation'] },
  { q: 'Command injection happens when:', opts: ['You parameterize input', 'User input is passed to a shell/OS command, letting attackers run arbitrary commands', 'You use HTTPS', 'You hash passwords'], a: 1, e: 'Building shell commands from untrusted input can let attackers execute arbitrary OS commands; avoid shells or use safe APIs.', tags: ['Injection', 'command'] },
  { q: 'Showing raw database error details to users can:', opts: ['Improve UX', 'Leak schema/structure that aids attackers', 'Prevent injection', 'Encrypt data'], a: 1, e: 'Verbose DB errors reveal internals useful to attackers; return generic errors and log details privately.', tags: ['Injection', 'errors'] },

  // Level 8 — XSS
  { q: 'Cross-site scripting (XSS) is when:', opts: ['The server crashes', 'Attacker-controlled script runs in another user’s browser via your page', 'TLS fails', 'A password leaks'], a: 1, e: 'XSS injects malicious script into pages so it executes in victims’ browsers, stealing data or hijacking sessions.', tags: ['XSS', 'basics'] },
  { q: 'Stored (persistent) XSS differs from reflected XSS because the payload is:', opts: ['Never executed', 'Saved on the server (e.g. in a comment) and served to many users', 'Only in the URL', 'In the database schema'], a: 1, e: 'Stored XSS persists (e.g. a malicious comment) and hits every viewer; reflected XSS bounces off a single request.', tags: ['XSS', 'types'] },
  { q: 'The main defense against XSS is:', opts: ['Faster JavaScript', 'Context-aware output encoding/escaping of untrusted data', 'Longer passwords', 'Disabling cookies'], a: 1, e: 'Escaping/encoding untrusted data for the output context (HTML, attribute, JS) prevents it from being treated as code.', tags: ['XSS', 'encoding'] },
  { q: 'In React, a common way to introduce XSS is:', opts: ['Rendering text normally', 'Using dangerouslySetInnerHTML with untrusted content', 'Using props', 'Using useState'], a: 1, e: 'React escapes text by default; dangerouslySetInnerHTML bypasses that and can inject untrusted HTML/scripts.', tags: ['XSS', 'react'] },
  { q: 'A Content Security Policy (CSP) helps mitigate XSS by:', opts: ['Encrypting cookies', 'Restricting which scripts/sources the browser will execute/load', 'Hashing passwords', 'Disabling HTTPS'], a: 1, e: 'CSP limits allowed script sources and inline scripts, reducing the impact of injected content.', tags: ['XSS', 'csp'] },
  { q: 'Sanitizing user-provided HTML (e.g. with DOMPurify) is needed when:', opts: ['You only render plain text', 'You must render rich HTML from users and want to strip dangerous markup', 'You never show user content', 'You disable JS'], a: 1, e: 'If you must render user HTML, sanitize it to remove scripts/handlers; otherwise prefer escaping as text.', tags: ['XSS', 'sanitize'] },
  { q: 'XSS can lead to:', opts: ['Faster pages', 'Session/cookie theft, keylogging, and actions performed as the victim', 'Better SEO', 'Stronger encryption'], a: 1, e: 'Running script as the victim lets attackers steal tokens, capture input, and act on the user’s behalf.', tags: ['XSS', 'impact'] },
  { q: 'Escaping data correctly requires knowing:', opts: ['The user’s name', 'The output context (HTML body vs attribute vs JS vs URL)', 'The database type', 'The TLS version'], a: 1, e: 'Different contexts need different encoding; using the wrong escaping can still leave an XSS hole.', tags: ['XSS', 'context'] },

  // Level 9 — CSRF
  { q: 'Cross-Site Request Forgery (CSRF) tricks a user into:', opts: ['Revealing their password', 'Unknowingly sending an authenticated request (using their cookies) to your site', 'Downloading a file', 'Reading a script'], a: 1, e: 'CSRF leverages the victim’s existing session/cookies to perform actions they didn’t intend on a trusted site.', tags: ['CSRF', 'basics'] },
  { q: 'CSRF is possible largely because browsers:', opts: ['Never send cookies', 'Automatically attach cookies to requests to a site, even cross-origin ones', 'Block all requests', 'Encrypt all forms'], a: 1, e: 'Browsers auto-send a site’s cookies with requests to it, so a forged cross-site request rides the victim’s session.', tags: ['CSRF', 'why'] },
  { q: 'A primary CSRF defense is:', opts: ['Longer passwords', 'Anti-CSRF tokens that attackers can’t predict/read', 'Hashing inputs', 'Disabling TLS'], a: 1, e: 'A per-request secret token (validated server-side) that the attacker can’t obtain stops forged requests.', tags: ['CSRF', 'token'] },
  { q: 'The SameSite cookie attribute mitigates CSRF by:', opts: ['Encrypting cookies', 'Restricting cookies from being sent on cross-site requests', 'Making cookies public', 'Removing cookies'], a: 1, e: 'SameSite=Lax/Strict limits sending cookies on cross-site requests, blunting many CSRF attacks.', tags: ['CSRF', 'samesite'] },
  { q: 'CSRF primarily targets:', opts: ['Read-only GETs', 'State-changing actions (transfers, deletes, settings changes)', 'Static images', 'CSS files'], a: 1, e: 'CSRF aims at actions that change state; safe, idempotent reads aren’t the main concern.', tags: ['CSRF', 'targets'] },
  { q: 'APIs using a bearer token in an Authorization header (not cookies) are:', opts: ['More vulnerable to CSRF', 'Largely not susceptible to classic CSRF, since the token isn’t auto-sent by the browser', 'Always vulnerable', 'Unable to authenticate'], a: 1, e: 'CSRF relies on auto-sent cookies; tokens placed in headers by JS aren’t automatically attached cross-site.', tags: ['CSRF', 'tokens'] },
  { q: 'A "double submit cookie" CSRF defense works by:', opts: ['Submitting two passwords', 'Sending a token both as a cookie and a request value and verifying they match', 'Encrypting the URL', 'Using two sessions'], a: 1, e: 'The server checks that a CSRF token in the request matches one in a cookie — an attacker can’t read/forge both.', tags: ['CSRF', 'double-submit'] },
  { q: 'Validating the Origin/Referer header can help against CSRF by:', opts: ['Encrypting requests', 'Rejecting state-changing requests that don’t come from your own site', 'Hashing tokens', 'Disabling cookies'], a: 1, e: 'Checking Origin/Referer on sensitive requests adds defense by rejecting cross-site origins (alongside tokens/SameSite).', tags: ['CSRF', 'origin'] },

  // Level 10 — OWASP Top 10
  { q: 'The OWASP Top 10 is:', opts: ['A list of programming languages', 'A widely-referenced list of the most critical web application security risks', 'A type of firewall', 'A cloud provider'], a: 1, e: 'The OWASP Top 10 catalogs the most common, impactful web app security risks to prioritize defenses.', tags: ['OWASP', 'overview'] },
  { q: 'The #1 risk in the OWASP Top 10 (2021) is:', opts: ['Broken Access Control', 'Memory leaks', 'Slow queries', 'CSS bugs'], a: 0, e: 'Broken Access Control rose to #1 in 2021, reflecting how often authorization is implemented incorrectly.', tags: ['OWASP', 'access-control'] },
  { q: '"Cryptographic Failures" (formerly Sensitive Data Exposure) involve:', opts: ['Fast code', 'Failing to properly protect sensitive data (weak/missing encryption, exposure)', 'Too many tests', 'UI glitches'], a: 1, e: 'This category covers weak or missing encryption and improper handling that exposes sensitive data.', tags: ['OWASP', 'crypto'] },
  { q: '"Security Misconfiguration" includes things like:', opts: ['Strong defaults', 'Default credentials, verbose errors, open cloud buckets, unnecessary features enabled', 'Encrypted data', 'Rate limiting'], a: 1, e: 'Misconfiguration covers insecure defaults, exposed debug info, and unhardened services — a very common risk.', tags: ['OWASP', 'misconfig'] },
  { q: '"Vulnerable and Outdated Components" warns about:', opts: ['Writing your own code', 'Using dependencies/libraries with known vulnerabilities', 'Strong passwords', 'TLS'], a: 1, e: 'Outdated, vulnerable libraries are a major attack vector; keep dependencies patched and monitored.', tags: ['OWASP', 'components'] },
  { q: 'Server-Side Request Forgery (SSRF) is when:', opts: ['The client attacks itself', 'An app is tricked into making requests to unintended (often internal) destinations', 'CSS leaks', 'A cookie expires'], a: 1, e: 'SSRF abuses a server that fetches a user-supplied URL to reach internal services/metadata endpoints.', tags: ['OWASP', 'ssrf'] },
  { q: '"Identification and Authentication Failures" include:', opts: ['Strong MFA', 'Weak passwords, broken session management, and credential stuffing exposure', 'Good logging', 'Parameterized queries'], a: 1, e: 'This category covers authentication weaknesses: poor password handling, session flaws, and missing brute-force protection.', tags: ['OWASP', 'authn'] },
  { q: 'The OWASP Top 10 is best used as:', opts: ['A complete guarantee of security', 'An awareness/prioritization starting point, not an exhaustive checklist', 'A programming language', 'A firewall rule'], a: 1, e: 'It raises awareness of common risks to prioritize, but real security needs deeper, context-specific work beyond the list.', tags: ['OWASP', 'usage'] },

  // Level 11 — Secrets Management
  { q: 'API keys, DB passwords, and tokens should be:', opts: ['Hardcoded in source', 'Kept out of code and stored in env vars or a secrets manager', 'Posted publicly', 'Sent to the client'], a: 1, e: 'Secrets must never live in source or ship to clients; use environment config or a dedicated secrets manager.', tags: ['Secrets', 'storage'] },
  { q: 'If a secret is accidentally committed to Git, you should:', opts: ['Just delete the latest commit', 'Rotate the secret immediately (assume it’s compromised) and then purge it', 'Ignore it', 'Make the repo private later'], a: 1, e: 'History and bots may have captured it, so rotate the secret right away — removing the commit alone isn’t enough.', tags: ['Secrets', 'leak'] },
  { q: 'A secrets manager provides benefits like:', opts: ['Plaintext sharing', 'Access control, auditing, encryption, and rotation of secrets', 'Public exposure', 'No control'], a: 1, e: 'Managers (Vault, cloud secret stores) centralize secrets with encryption, fine-grained access, auditing, and rotation.', tags: ['Secrets', 'manager'] },
  { q: 'Secrets should never be:', opts: ['Encrypted', 'Exposed in client-side code or logs', 'Rotated', 'Access-controlled'], a: 1, e: 'Anything shipped to the browser or written to logs can leak; keep secrets server-side and out of logs.', tags: ['Secrets', 'exposure'] },
  { q: 'Rotating secrets periodically helps by:', opts: ['Breaking everything', 'Limiting how long a leaked secret remains useful', 'Slowing the app', 'Removing access control'], a: 1, e: 'Regular rotation shrinks the window an exposed secret can be abused, and is essential after any suspected leak.', tags: ['Secrets', 'rotation'] },
  { q: 'A frontend app needing to call a third-party API with a secret should:', opts: ['Embed the secret in JS', 'Proxy through a backend that holds the secret server-side', 'Put it in localStorage', 'Hardcode it in HTML'], a: 1, e: 'Browser code is fully visible; route secret-bearing calls through your backend so the key never reaches the client.', tags: ['Secrets', 'frontend'] },
  { q: 'Environment-specific secrets (dev vs prod) should be:', opts: ['Shared/identical', 'Separate, so a dev leak doesn’t compromise production', 'In the repo', 'Disabled'], a: 1, e: 'Distinct secrets per environment limit blast radius: a non-prod leak doesn’t hand over production access.', tags: ['Secrets', 'environments'] },
  { q: 'Scanning repos/commits for secrets (e.g. with automated tools) helps:', opts: ['Add secrets', 'Catch accidental secret commits before/after they happen', 'Slow CI for no reason', 'Encrypt nothing'], a: 1, e: 'Secret-scanning tools detect leaked credentials in code/history so they can be rotated and removed quickly.', tags: ['Secrets', 'scanning'] },

  // Level 12 — Secure Defaults & Headers
  { q: 'Secure defaults mean:', opts: ['The most permissive settings out of the box', 'The system is safe by default, requiring opt-in to loosen', 'No configuration', 'Debug mode in production'], a: 1, e: 'Secure-by-default ships locked-down settings, so safety doesn’t depend on every operator hardening it manually.', tags: ['Headers', 'defaults'] },
  { q: 'The Content-Security-Policy header primarily mitigates:', opts: ['SQL injection', 'XSS and other content-injection by restricting allowed sources', 'CSRF only', 'TLS downgrade'], a: 1, e: 'CSP constrains where scripts/styles/etc. can load from, reducing the impact of injected content (XSS).', tags: ['Headers', 'csp'] },
  { q: 'X-Content-Type-Options: nosniff prevents:', opts: ['CSRF', 'Browsers from MIME-sniffing responses into a different, riskier type', 'SQLi', 'Slow loads'], a: 1, e: 'nosniff stops content-type sniffing that could cause, e.g., a text file to be executed as script.', tags: ['Headers', 'nosniff'] },
  { q: 'The Strict-Transport-Security header enforces:', opts: ['HTTP only', 'HTTPS-only access for the domain (HSTS)', 'No TLS', 'Caching'], a: 1, e: 'HSTS instructs browsers to use HTTPS exclusively, preventing downgrade attacks.', tags: ['Headers', 'hsts'] },
  { q: 'Running an app in debug mode in production is risky because it can:', opts: ['Improve security', 'Expose stack traces, configs, and internals to attackers', 'Speed up the app', 'Encrypt data'], a: 1, e: 'Debug mode often leaks sensitive internals (stack traces, secrets, routes), aiding attackers — disable it in prod.', tags: ['Headers', 'debug'] },
  { q: 'Default/sample credentials (admin/admin) should be:', opts: ['Left as-is', 'Changed/removed before deployment', 'Posted publicly', 'Reused everywhere'], a: 1, e: 'Default credentials are widely known and a top cause of breaches; always change or disable them.', tags: ['Headers', 'defaults'] },
  { q: 'CORS misconfiguration (e.g. reflecting any Origin with credentials) can:', opts: ['Improve security', 'Let malicious sites read authenticated responses from your API', 'Disable HTTPS', 'Prevent XSS'], a: 1, e: 'An over-permissive CORS policy can expose authenticated data to untrusted origins; scope allowed origins carefully.', tags: ['Headers', 'cors'] },
  { q: 'Disabling directory listing and removing unused endpoints/features:', opts: ['Increases attack surface', 'Reduces attack surface and information leakage', 'Has no effect', 'Breaks TLS'], a: 1, e: 'Turning off unnecessary features and exposure shrinks the attack surface and limits reconnaissance.', tags: ['Headers', 'hardening'] },

  // Level 13 — Dependency & Supply Chain
  { q: 'A software supply chain attack compromises:', opts: ['Only your own code', 'Third-party dependencies or build tools to reach everyone who uses them', 'The CSS only', 'The user’s monitor'], a: 1, e: 'Attackers poison a popular dependency or build pipeline so the malicious code spreads to all downstream consumers.', tags: ['Supply Chain', 'basics'] },
  { q: 'Keeping dependencies updated is important because:', opts: ['New versions are always slower', 'Updates patch known security vulnerabilities', 'It increases bugs', 'Old versions are safer'], a: 1, e: 'Outdated libraries accumulate known CVEs; timely updates close those holes (balanced against change risk).', tags: ['Supply Chain', 'updates'] },
  { q: 'A lockfile (e.g. package-lock.json) improves supply-chain safety by:', opts: ['Allowing arbitrary version drift', 'Pinning exact, reviewed dependency versions for reproducible installs', 'Removing dependencies', 'Disabling audits'], a: 1, e: 'Lockfiles ensure everyone installs the same vetted versions, preventing surprise (possibly malicious) updates.', tags: ['Supply Chain', 'lockfile'] },
  { q: 'Tools like npm audit / Dependabot help by:', opts: ['Writing features', 'Flagging dependencies with known vulnerabilities', 'Encrypting code', 'Deploying apps'], a: 1, e: 'Vulnerability scanners alert you to insecure dependencies (and can open update PRs) so you can remediate.', tags: ['Supply Chain', 'scanning'] },
  { q: 'Typosquatting in package registries refers to:', opts: ['A linting error', 'Malicious packages named like popular ones to trick installs', 'A TLS bug', 'A CSS hack'], a: 1, e: 'Attackers publish look-alike package names (e.g. reqeusts) hoping developers install the malicious one by typo.', tags: ['Supply Chain', 'typosquatting'] },
  { q: 'Pulling unpinned Docker base images (e.g. :latest) is risky because:', opts: ['It is reproducible', 'The underlying image can change unexpectedly, including vulnerabilities', 'It improves security', 'It pins versions'], a: 1, e: ':latest is a moving target; pin to a digest/version for reproducible, auditable builds.', tags: ['Supply Chain', 'images'] },
  { q: 'An SBOM (software bill of materials) is:', opts: ['A type of firewall', 'An inventory of components/dependencies in your software', 'A password', 'A test'], a: 1, e: 'An SBOM lists all components so you can quickly assess exposure when a new vulnerability is disclosed.', tags: ['Supply Chain', 'sbom'] },
  { q: 'Minimizing the number of dependencies helps security by:', opts: ['Increasing attack surface', 'Reducing the amount of third-party code you must trust and patch', 'Slowing the app', 'Removing features always'], a: 1, e: 'Fewer dependencies mean less third-party code to trust, audit, and keep patched — a smaller supply-chain surface.', tags: ['Supply Chain', 'minimize'] },

  // Level 14 — Data Protection & Privacy
  { q: 'PII (personally identifiable information) includes:', opts: ['Server uptime', 'Data like names, emails, addresses that identify a person', 'CPU temperature', 'Build logs'], a: 1, e: 'PII is data that identifies an individual; it requires careful handling, protection, and minimization.', tags: ['Privacy', 'pii'] },
  { q: 'Data minimization means:', opts: ['Collect everything possible', 'Collect and retain only the data you actually need', 'Never store data', 'Encrypt nothing'], a: 1, e: 'Collecting only necessary data reduces breach impact and regulatory burden — you can’t leak what you don’t hold.', tags: ['Privacy', 'minimization'] },
  { q: 'Encryption at rest protects data by:', opts: ['Speeding queries', 'Making stored data unreadable without the key if storage is stolen', 'Removing backups', 'Disabling access control'], a: 1, e: 'Encrypting stored data means a stolen disk/backup is useless without the keys, protecting confidentiality.', tags: ['Privacy', 'at-rest'] },
  { q: 'Regulations like GDPR grant users rights such as:', opts: ['Nothing', 'Access to and deletion of their personal data', 'Free hardware', 'Faster internet'], a: 1, e: 'GDPR (and similar laws) give individuals rights over their data, including access, correction, and erasure.', tags: ['Privacy', 'gdpr'] },
  { q: 'Masking/redacting sensitive fields in logs prevents:', opts: ['Faster logging', 'Leaking secrets/PII into log storage', 'Encryption', 'Monitoring'], a: 1, e: 'Redacting passwords, tokens, and PII keeps sensitive data out of logs where it could be exposed.', tags: ['Privacy', 'logging'] },
  { q: 'Pseudonymization differs from anonymization because pseudonymized data:', opts: ['Can never be re-identified', 'Can still be re-identified with additional information/keys', 'Is plaintext', 'Is encrypted forever'], a: 1, e: 'Pseudonymization replaces identifiers but allows re-identification with a key; true anonymization is irreversible.', tags: ['Privacy', 'pseudonymization'] },
  { q: 'A data breach response should include:', opts: ['Silence', 'Containment, assessment, notification (as required), and remediation', 'Deleting all logs', 'Blaming users'], a: 1, e: 'Good incident response contains the breach, assesses scope, notifies affected parties/regulators as required, and fixes root causes.', tags: ['Privacy', 'breach'] },
  { q: 'Encrypting backups is important because:', opts: ['Backups are never sensitive', 'Backups contain the same sensitive data and are a common theft target', 'It speeds restores', 'It removes the need for access control'], a: 1, e: 'Backups hold full copies of sensitive data; if unencrypted and stolen, they expose everything — encrypt them too.', tags: ['Privacy', 'backups'] },

  // Level 15 — Secure Design & Threat Modeling
  { q: 'Threat modeling is the practice of:', opts: ['Ignoring threats', 'Systematically identifying assets, threats, and mitigations during design', 'Only testing UI', 'Encrypting code'], a: 1, e: 'Threat modeling proactively analyzes what could go wrong (assets, attackers, attack paths) so you design mitigations early.', tags: ['Design', 'threat-modeling'] },
  { q: 'The STRIDE model categorizes threats like:', opts: ['Speed, Time, Reliability', 'Spoofing, Tampering, Repudiation, Information disclosure, DoS, Elevation of privilege', 'CSS, HTML, JS', 'Dev, Staging, Prod'], a: 1, e: 'STRIDE enumerates threat categories to guide threat modeling: Spoofing, Tampering, Repudiation, Info disclosure, DoS, Elevation of privilege.', tags: ['Design', 'stride'] },
  { q: '"Shift left" in security means:', opts: ['Fix security only after release', 'Address security earlier in the development lifecycle, not just at the end', 'Move servers physically', 'Disable testing'], a: 1, e: 'Shifting left builds security in from design/coding (threat modeling, reviews, scans) rather than bolting it on late.', tags: ['Design', 'shift-left'] },
  { q: 'Building security into design is cheaper than retrofitting because:', opts: ['It never matters', 'Flaws found early cost far less to fix than after deployment/breach', 'Late fixes are free', 'Design has no impact'], a: 1, e: 'Like all defects, security flaws are far cheaper to address in design than after they ship or cause a breach.', tags: ['Design', 'cost'] },
  { q: 'A secure design principle is to minimize trust by:', opts: ['Trusting all internal services blindly', 'Validating inputs and authenticating/authorizing across trust boundaries', 'Removing authentication', 'Sharing one admin account'], a: 1, e: 'Treat trust boundaries explicitly: validate and authorize data crossing them rather than assuming internal calls are safe.', tags: ['Design', 'trust-boundaries'] },
  { q: 'Security testing should include:', opts: ['Only manual UI clicks', 'Automated scanning, dependency checks, and periodic penetration testing/reviews', 'Nothing', 'Only unit tests'], a: 1, e: 'A layered program combines automated scanning, dependency/secret checks, code review, and pen testing to find issues.', tags: ['Design', 'testing'] },
  { q: 'Logging and monitoring for security helps by:', opts: ['Hiding attacks', 'Detecting and investigating suspicious activity and breaches', 'Encrypting nothing', 'Slowing the app only'], a: 1, e: 'Security logging/monitoring enables detection and forensic investigation of attacks; missing it is itself an OWASP risk.', tags: ['Design', 'monitoring'] },
  { q: 'The most realistic mindset about security is that it is:', opts: ['A one-time checkbox', 'An ongoing process of risk reduction, never "done"', 'Only the security team’s job', 'Achievable as 100% safe'], a: 1, e: 'Security is continuous risk management — threats evolve, so it’s an ongoing shared responsibility, never fully "finished".', tags: ['Design', 'mindset'] },
];
