import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Middlegame Strategy roadmap bank (rm-middle-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const middlegameTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Tvorba plánu ──
  'rm-middle-1': { introduction: 'Zamysli se, z čeho vychází dobrý plán.', question: 'Co je „plán" ve střední hře?', options: ['Cílevědomá řada tahů vycházející z rysů pozice','Naučení odpovědí soupeře dopředu','Jakýkoli náhodný útočný tah','Vždy vyměnit dámy'], explanation: 'Plán je souvislý sled tahů směřující ke konkrétnímu cíli odvozenému z vlastností pozice.' },
  'rm-middle-2': { introduction: 'Něco musí plánování předcházet.', question: 'Co bys měl udělat DŘÍVE, než zvolíš plán?', options: ['Nabídnout remízu','Zhodnotit (posoudit) pozici','Zatlačit všechny pěšce dopředu','Vyměnit všechny lehké figury'], explanation: 'Dobrý plán vychází z upřímného zhodnocení pozice, ne z dohadů.' },
  'rm-middle-3': { introduction: 'Jde o trvalé rysy pozice.', question: 'Který z těchto prvků je klíčový při hodnocení pozice?', options: ['Barva šachovnice','Jak dlouho partie trvá','Pěšcová struktura','Komu se dřív spustily hodiny'], explanation: 'Bezpečnost krále, materiál, pěšcová struktura, aktivita figur a prostor jsou standardní hodnoticí faktory.' },
  'rm-middle-4': { introduction: 'Vzpomeň si na Steinitzovu zásadu.', question: 'Podle Steinitze — kdy bys měl zahájit útok?', options: ['V každém jednotlivém tahu','Co nejdříve, ať se děje cokoli','Ve střední hře nikdy','Jen když už máš výhodu'], explanation: 'Steinitz učil, že útok je oprávněný, když jsi nashromáždil výhodu; útok na zdravou pozici obvykle selže.' },
  'rm-middle-5': { introduction: 'Přemýšlej, co dělat s prostorovou převahou.', question: 'Máš-li prostorovou převahu, jaký přístup se doporučuje?', options: ['Vyhýbat se hromadným výměnám a využívat prostor','Vyměnit co nejvíc figur','Ihned vzdát centrum','Přesouvat krále sem a tam'], explanation: 'S větším prostorem chceš mít figury na šachovnici, abys ho využil; stísněná strana těží z výměn.' },
  'rm-middle-6': { introduction: 'Opak prostorové převahy.', question: 'Je-li tvá pozice stísněná, o co bys měl obecně usilovat?', options: ['Naráz posunout všechny pěšce','O výměny, které uvolní nedostatek prostoru','Ponechat všechny figury na desce','O okamžitý pochod krále'], explanation: 'Výměna figur dodá stísněné pozici více prostoru pro zbývající síly.' },
  'rm-middle-7': { introduction: 'Kde hrát na šachovnici?', question: 'Rozumná zásada říká hrát na té straně šachovnice, kde:', options: ['Máš nejméně figur','Máš krále','Jsi silnější (více prostoru nebo pěšcová převaha)','Nemáš žádné pěšce'], explanation: 'Hru směřuješ do sektoru, kde máš výhodu, například pěšcovou převahu nebo více prostoru.' },
  'rm-middle-8': { introduction: 'Co je vhodný cíl plánu?', question: 'Za „slabinu", proti níž stojí za to plánovat, se obvykle považuje:', options: ['Dobře krytý centrální pěšec','Figura na výchozím poli','Věž na otevřené linii','Pole nebo pěšec, který nelze bránit pěšcem'], explanation: 'Trvalé slabiny — zaostalí či izolovaní pěšci a díry, jež žádný pěšec nekryje — jsou přirozeným cílem plánu.' },

  // ── Úroveň 2 — Aktivita figur a dobrý/špatný střelec ──
  'rm-middle-9': { introduction: 'Jde o omezeného střelce.', question: 'Co je „špatný střelec"?', options: ['Střelec svázaný vlastními pěšci na jeho barvě','Každý střelec, který ještě netáhl','Střelec, který má podle pravidel nižší cenu než jezdec','Střelec, kterého nelze sebrat'], explanation: 'Špatný střelec je blokován vlastními pěšci stojícími na polích jeho barvy, což omezuje jeho dosah.' },
  'rm-middle-10': { introduction: 'Opak špatného střelce.', question: 'Co je „dobrý střelec"?', options: ['Střelec, který dal šach králi','Střelec s volnými diagonálami, nebržděný vlastními pěšci','Střelec, který začínal na bílém poli','Každý střelec krytý věží'], explanation: 'Dobrý střelec má aktivní diagonály, protože jeho vlastní pěšci stojí většinou mimo jeho barvu.' },
  'rm-middle-11': { introduction: 'Jak zlepšit svázaného střelce?', question: 'Jak můžeš vylepšit špatného střelce?', options: ['Nechat ho navždy tam, kde je','Proměnit ho v dámu','Vyměnit ho, nebo přesunout pěšce mimo jeho barvu','Ihned ho obětovat'], explanation: 'Buď špatného střelce vyměň, nebo ho uvolni přesunem svých pevných pěšců na druhou barvu.' },
  'rm-middle-12': { introduction: 'Výhoda dvojice střelců.', question: 'Proč je „dvojice střelců" cenná?', options: ['Střelci mohou přeskakovat figury','Dva střelci zaručují poslední řadu','Střelci táhnou dvakrát za tah','Dva střelci pokrývají obě barvy a vládnou otevřeným pozicím'], explanation: 'Dvojice kontroluje pole obou barev a je obzvlášť silná v otevřených pozicích s volnými diagonálami.' },
  'rm-middle-13': { introduction: 'Kdy je lepší jezdec.', question: 'Jezdec bývá lepší než střelec, když:', options: ['Je deska zcela otevřená','Je pozice uzavřená nebo má jezdec silné opěrné pole','Zbývají už jen pěšci','Jsou ještě na desce dámy'], explanation: 'V uzavřených pozicích jezdec, který přeskakuje pěšce a sedí na opěrných polích, často předčí střelce.' },
  'rm-middle-14': { introduction: 'Vysněné pole jezdce.', question: 'Co je „opěrné pole" (outpost)?', options: ['Pěšec na poslední řadě','Pole chráněné před soupeřovými pěšci, ideální pro jezdce','Věž zdvojená s dámou','Král, který provedl rošádu'], explanation: 'Opěrné pole je díra, kterou žádný soupeřův pěšec nenapadne, obvykle krytá vlastním pěšcem — vysněné pole pro jezdce.' },
  'rm-middle-15': { introduction: 'Figury by měly spolupracovat.', question: '„Souhra figur" znamená:', options: ['Držet figury na výchozích polích','Mít figury jen jedné barvy','Figury pracující společně ke stejnému cíli','Vyměňovat figury co nejrychleji'], explanation: 'Sehrané figury se navzájem podporují a spojují svou sílu, místo aby působily osamoceně.' },
  'rm-middle-16': { introduction: 'Kam patří věže.', question: 'Aktivní věže obecně patří na:', options: ['Stejnou linii jako jejich vlastní král','Otevřené nebo polootevřené linie','Pole blokovaná vlastními pěšci','Pouze první řadu'], explanation: 'Věže rozvíjejí svůj potenciál na otevřených a polootevřených liniích, kde jim nic nebrání v dosahu.' },

  // ── Úroveň 3 — Útok na krále ──
  'rm-middle-17': { introduction: 'Útok potřebuje otevřené cesty.', question: 'Chceš-li napadnout krále po rošádě, obvykle potřebuješ otevřít:', options: ['Linie a diagonály vedoucí k němu','Vlastní poslední řadu','Jen dámské křídlo','Linie směřující od krále pryč'], explanation: 'Otevření linií ke králi dovolí věžím, střelcům a dámě dosáhnout na něj.' },
  'rm-middle-18': { introduction: 'Síla věže na sedmé řadě.', question: 'Proč je věž na sedmé řadě tak silná?', options: ['Dává automatický mat','Napadá pěšce a svírá soupeřova krále','Nelze ji tam sebrat','Na té řadě se promění'], explanation: 'Věž na sedmé řadě hrabe soupeřovy pěšce a často uvězní krále na jeho poslední řadě.' },
  'rm-middle-19': { introduction: 'Klasická oběť na h7.', question: 'Klasická oběť střelce Sxh7+, jež obnaží krále po rošádě, se nazývá:', options: ['Bláznův mat','Větrný mlýn','Řecký dar','Zadušený mat'], explanation: '„Řecký dar" obětuje střelce na h7 (nebo h2), aby rozbil krále, a navazuje jezdcem a dámou.' },
  'rm-middle-20': { introduction: 'Rošády na opačná křídla.', question: 'Při rošádách na opačné strany je typickým útočným plánem:', options: ['Nechat všechny pěšce doma','Hnát vlastní pěšce proti soupeřovu králi','Vyměnit naráz všechny figury','Vytáhnout krále doprostřed desky'], explanation: 'Při rošádách na opačná křídla obě strany ženou pěšce na soupeřova krále, protože to neoslabuje vlastní úkryt.' },
  'rm-middle-21': { introduction: 'Proč se obětuje při útoku.', question: 'Obvyklým účelem oběti při útoku na krále je:', options: ['Snížit vlastní materiál jen tak','Otevřít linie, odstranit obránce nebo získat čas','Nabídnout remízu','Zjednodušit do vyrovnané koncovky'], explanation: 'Útočné oběti kupují přístup — otevírají linie, likvidují obránce nebo získávají tempo proti králi.' },
  'rm-middle-22': { introduction: 'Předpoklad úspěšného útoku.', question: 'Rozumným předpokladem před útokem na krále je:', options: ['Mít víc útočníků, než má obránce obránců','Být v materiálním deficitu','Nemít vyvinuté figury','Zcela symetrická pozice'], explanation: 'Útok uspěje, když dokážeš ke králi přivést víc síly, než kolik soupeř sežene k obraně.' },
  'rm-middle-23': { introduction: 'Hon na krále.', question: 'Co je „hon na krále"?', options: ['Dvojitá rošáda','Schování vlastního krále','Vyhnání soupeřova krále do otevřeného pole a jeho zmatování','Výměna dam'], explanation: 'Při honu na krále je bránící král vyhnán z úkrytu přes celou desku, dokud není matován.' },
  'rm-middle-24': { introduction: 'Kdy je útok na křídle oprávněný.', question: 'Útok na křídle je obecně nejlépe oprávněn, když je centrum:', options: ['Zcela otevřené','Uzavřené nebo zablokované','Plné tvých vlastních figur','Obsazené oběma dámami'], explanation: 'Uzavřené centrum zajišťuje tvou základnu, takže pěšcový útok na křídle nelze srazit průlomem ve středu.' },

  // ── Úroveň 4 — Profylaxe, obrana a zlepšení figur ──
  'rm-middle-25': { introduction: 'Prevence soupeřových plánů.', question: 'Co znamená „profylaxe" v šachu?', options: ['Útočit co nejrychleji','Předcházet soupeřovým záměrům dřív, než jdeš za svými','Vždy nabízet remízu','Vyměnit dámy hned v prvním tahu'], explanation: 'Profylaxe je předvídání a zastavení soupeřových plánů dřív, než rozvineš vlastní.' },
  'rm-middle-26': { introduction: 'Autor pojmu.', question: 'Který hráč je nejvíce spojován s profylaxí a přezajištěním?', options: ['Aron Nimcovič','Paul Morphy','Adolf Anderssen','Frank Marshall'], explanation: 'Nimcovič zformuloval profylaxi a přezajištění ve svém klasickém díle „Můj systém".' },
  'rm-middle-27': { introduction: 'Vzduch pro krále.', question: 'Vytvoření „luftu" (únikového pole pro krále) je profylaktický tah proti:', options: ['Patu','Pěšcovému útoku','Matu na poslední řadě','Vidličce jezdcem'], explanation: 'Malý pěšcový tah dávající králi „luft" (vzduch) předchází matu věží či dámou na poslední řadě.' },
  'rm-middle-28': { introduction: 'Výměny při obraně.', question: 'Jsi-li pod útokem, výměna figur obvykle:', options: ['Útok zesílí','Ulehčí obranu odstraněním útočníků','Okamžitě prohraje','Nemá vůbec žádný účinek'], explanation: 'Výměna soupeřových útočících figur zmenší sílu namířenou na tvého krále.' },
  'rm-middle-29': { introduction: 'Když chybí konkrétní plán.', question: 'Nemáš-li konkrétní plán, spolehlivým přístupem je:', options: ['Zlepšit svou nejhůře postavenou figuru','Vzdát partii','Vytáhnout krále dopředu','Opakovat tahy pro remízu'], explanation: 'Vylepšení pozice nejméně aktivní figury je zdravý způsob, jak dělat pokrok, když není nic nuceného.' },
  'rm-middle-30': { introduction: 'Nimcovičův pojem.', question: 'Co je „přezajištění" (overprotection)?', options: ['Bránit bod mnohem víckrát, než je třeba, jen aby se ztrácel čas','Krýt klíčový bod navíc, aby tvé figury získaly pružnost','Nechat pěšce bez ochrany','Útočit králem'], explanation: 'Přezajištění důležitého pole udrží tvé figury dobře postavené a připravené a bod natrvalo zabezpečí.' },
  'rm-middle-31': { introduction: 'Jádro profylaktického myšlení.', question: 'Profylaktické myšlení hlavně znamená neustále se ptát:', options: ['„Jak rychle dám mat?"','„Co chce udělat můj soupeř?"','„Mohu nabídnout remízu?"','„Který pěšec vypadá nejhezčí?"'], explanation: 'Základním profylaktickým návykem je odhalit soupeřovu hrozbu či plán a zabránit mu dřív, než jednáš.' },
  'rm-middle-32': { introduction: 'Vrácení materiálu.', question: 'Pod silným útokem může být moudré vrátit část materiálu, protože to:', options: ['Vždy prohraje partii','Je proti pravidlům','Otupí útok a vede k bezpečnější pozici','Vynutí okamžitou remízu'], explanation: 'Vrácení pěšce navíc nebo kvality často zabije soupeřovu iniciativu a nechá tě v bezpečí, či dokonce lépe.' },

  // ── Úroveň 5 — Nerovnováhy, iniciativa a realizace výhody ──
  'rm-middle-33': { introduction: 'Silmanův pojem.', question: 'V Silmanově pojetí je „nerovnováha":', options: ['Rozdíl mezi oběma stranami, jenž určuje správný plán','Nelegální pozice','Remízová koncovka','Dvě stejné armády bez o co hrát'], explanation: 'Nerovnováhy — střelec vs jezdec, rozdíly ve struktuře, prostor, vývin — určují, o co má každá strana usilovat.' },
  'rm-middle-34': { introduction: 'Kdo určuje děj.', question: '„Iniciativa" označuje:', options: ['Zaostávání ve vývinu','Schopnost vytvářet hrozby a nutit soupeře reagovat','To, že ses dřív rošoval','Vlastnictví dvojice střelců'], explanation: 'Strana s iniciativou určuje program a vytváří hrozby, na které soupeř musí odpovídat.' },
  'rm-middle-35': { introduction: 'Co iniciativa umožňuje.', question: 'Držení iniciativy ti umožňuje:', options: ['Bezpečně ztratit tempo','Vynechat tah','Diktovat průběh hry','Slíbit remízu'], explanation: 'S iniciativou diktuješ dění a držíš soupeře v defenzivě.' },
  'rm-middle-36': { introduction: 'Máš-li materiál navíc.', question: 'Máš-li materiální převahu, standardní technikou je:', options: ['Ponechat všechny figury k útoku','Vyměňovat figury (ne pěšce) směrem k vyhrané koncovce','Obětovat další materiál','Vyhýbat se všem výměnám'], explanation: '„Máš-li materiál navíc, vyměňuj figury" — zjednodušení znásobí materiální převahu v koncovce.' },
  'rm-middle-37': { introduction: 'Máš-li materiál méně.', question: 'Jsi-li v materiálním deficitu, měl bys obecně:', options: ['Vyměnit se do prohrané koncovky','Ihned vzdát','Ponechat figury na desce a hledat komplikace','Rozdat další materiál'], explanation: 'Slabší strana se vyhýbá zjednodušení a drží figury na desce, aby vytvořila praktické šance.' },
  'rm-middle-38': { introduction: 'Plán proti pěšcové většině.', question: 'Co je „menšinový útok"?', options: ['Postup menšího počtu pěšců proti většině s cílem vytvořit slabinu','Útok jen králem','Oběť celé armády','Odmítnutí vyvinout figury'], explanation: 'Menšinový útok žene malou skupinu pěšců (často pěšce b a a) proti soupeřově většině, aby zanechal zaostalého či izolovaného pěšce.' },
  'rm-middle-39': { introduction: 'Zásada realizace výhody.', question: '„Zásada dvou slabin" říká, že k realizaci výhody často potřebuješ:', options: ['Vytvořit jen jeden cíl','Otevřít druhou frontu, aby obrana byla přetížená','Ihned vyměnit dámy','Vzdát se své výhody'], explanation: 'Jedinou slabinu lze často udržet; vytvoření druhé přetíží obránce za hranici únosnosti.' },
  'rm-middle-40': { introduction: 'Oběť kvality.', question: 'Oběť kvality (odevzdání věže za lehkou figuru) je příkladem čeho?', options: ['Chyby už z definice','Záměrného přijetí materiální nerovnováhy za poziční zisky','Nelegálního tahu','Vynucené remízy'], explanation: 'Oběť kvality mění materiál za trvalou poziční kompenzaci — aktivitu, silné pole nebo rozbitou strukturu.' },
};
