import type { Seed } from './roadmap-build';

// Political Geography & Borders — 10 levels × 8 questions, easiest → hardest.
export const politicalSeeds: Seed[] = [
  // ── Level 1 — Countries & Sovereignty ──
  { q: 'Approximately how many countries are widely recognized as sovereign states in the world today?', opts: ['About 195', 'About 120', 'About 260', 'About 310'], a: 0, e: 'There are around 195 widely recognized sovereign states: the 193 UN member states plus the Vatican (Holy See) and Palestine, which hold non-member observer status.', tags: ['political', 'sovereignty'] },
  { q: 'What best defines a sovereign state?', opts: ['A province governed from a national capital', 'A territory with a permanent population, defined borders, a government, and the capacity to conduct foreign relations', 'Any large city that elects its own mayor', 'A member of a military alliance'], a: 1, e: 'A sovereign state has a permanent population, a defined territory, a functioning government, and the capacity to enter into relations with other states.', tags: ['political', 'sovereignty'] },
  { q: 'How many member states belong to the United Nations?', opts: ['173', '183', '193', '203'], a: 2, e: 'The United Nations has 193 member states, the most recent being South Sudan, which joined in 2011.', tags: ['political', 'united-nations'] },
  { q: 'Which entity holds UN permanent observer status rather than full membership?', opts: ['Canada', 'Australia', 'Nigeria', 'The Holy See (Vatican City)'], a: 3, e: 'The Holy See (Vatican City) is a non-member permanent observer at the UN, not a full member state, as is Palestine.', tags: ['political', 'united-nations'] },
  { q: 'Which is the smallest sovereign state in the world by area?', opts: ['Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'], a: 0, e: 'Vatican City covers only about 0.49 square kilometers, making it the smallest sovereign state on Earth.', tags: ['political', 'sovereignty'] },
  { q: 'The classic criteria for statehood — population, territory, government, and capacity for relations — are most associated with which agreement?', opts: ['The Geneva Convention', 'The Montevideo Convention', 'The Treaty of Versailles', 'The Kyoto Protocol'], a: 1, e: 'The 1933 Montevideo Convention on the Rights and Duties of States set out the widely cited criteria for statehood.', tags: ['political', 'sovereignty'] },
  { q: 'Which of these is an independent sovereign country?', opts: ['Scotland', 'Bavaria', 'Iceland', 'Quebec'], a: 2, e: 'Iceland is a sovereign state. Scotland is a nation within the United Kingdom, Bavaria a state of Germany, and Quebec a province of Canada.', tags: ['political', 'sovereignty'] },
  { q: 'As of the mid-2020s, which country has the largest population?', opts: ['United States', 'Indonesia', 'China', 'India'], a: 3, e: 'India overtook China as the world\'s most populous country in 2023, with both nations exceeding 1.4 billion people.', tags: ['political', 'population'] },

  // ── Level 2 — Borders & Boundaries ──
  { q: 'What is the longest international border in the world?', opts: ['The Russia–China border', 'The United States–Canada border', 'The Argentina–Chile border', 'The Kazakhstan–Russia border'], a: 1, e: 'The border between the United States and Canada, at roughly 8,890 km, is the longest international border in the world.', tags: ['political', 'borders'] },
  { q: 'Which two countries each share a land border with 14 other countries — the most of any nation?', opts: ['United States and Mexico', 'India and Pakistan', 'China and Russia', 'Brazil and Argentina'], a: 2, e: 'China and Russia each border 14 countries, more than any other nation on Earth.', tags: ['political', 'borders'] },
  { q: 'Which country forms the southern land border of the United States?', opts: ['Guatemala', 'Belize', 'Canada', 'Mexico'], a: 3, e: 'Mexico shares the southern land border of the United States; Canada lies to the north.', tags: ['political', 'borders'] },
  { q: 'Which river forms a large part of the border between the United States and Mexico?', opts: ['The Rio Grande', 'The Colorado River', 'The Mississippi River', 'The Columbia River'], a: 0, e: 'The Rio Grande (Río Bravo) forms much of the Texas–Mexico boundary, running to the Gulf of Mexico.', tags: ['political', 'borders'] },
  { q: 'Which country shares the longest land border with Brazil?', opts: ['Argentina', 'Bolivia', 'Peru', 'Venezuela'], a: 1, e: 'Brazil\'s longest land border, about 3,400 km, is with Bolivia.', tags: ['political', 'borders'] },
  { q: 'The border between which two countries runs largely along the Pyrenees mountains?', opts: ['Italy and Switzerland', 'Norway and Sweden', 'France and Spain', 'Germany and Poland'], a: 2, e: 'The Pyrenees form a natural boundary between France and Spain, with Andorra nestled within the range.', tags: ['political', 'borders'] },
  { q: 'Which two countries are separated by the heavily militarized boundary known as the Korean DMZ?', opts: ['China and Mongolia', 'Vietnam and Laos', 'Japan and South Korea', 'North Korea and South Korea'], a: 3, e: 'The Demilitarized Zone near the 38th parallel separates North Korea and South Korea.', tags: ['political', 'borders'] },
  { q: 'The 49th parallel forms a large part of the border between which two countries?', opts: ['United States and Canada', 'France and Germany', 'India and China', 'Chile and Argentina'], a: 0, e: 'Much of the western US–Canada border follows the 49th parallel of latitude.', tags: ['political', 'borders'] },

  // ── Level 3 — Landlocked & Coastal States ──
  { q: 'What is a landlocked country?', opts: ['A country made up entirely of islands', 'A country with a very long coastline', 'A country with no direct access to the ocean or sea', 'A country that borders only one other nation'], a: 2, e: 'A landlocked country is surrounded by land and has no coastline giving direct access to the open ocean.', tags: ['political', 'landlocked'] },
  { q: 'Which of these is a landlocked country?', opts: ['Portugal', 'Vietnam', 'Chile', 'Switzerland'], a: 3, e: 'Switzerland is landlocked in the Alps; Portugal, Vietnam, and Chile all have coastlines.', tags: ['political', 'landlocked'] },
  { q: 'Which South American country is landlocked?', opts: ['Bolivia', 'Peru', 'Ecuador', 'Colombia'], a: 0, e: 'Bolivia and Paraguay are South America\'s two landlocked countries; Bolivia lost its coast in the 19th-century War of the Pacific.', tags: ['political', 'landlocked'] },
  { q: 'A "double-landlocked" country is surrounded only by other landlocked countries. Which European microstate is double-landlocked?', opts: ['Monaco', 'Liechtenstein', 'Andorra', 'San Marino'], a: 1, e: 'Liechtenstein is bordered only by Switzerland and Austria, both landlocked, making it doubly landlocked.', tags: ['political', 'landlocked'] },
  { q: 'Besides Liechtenstein, which other country is doubly landlocked, surrounded entirely by landlocked neighbors?', opts: ['Kazakhstan', 'Mongolia', 'Uzbekistan', 'Afghanistan'], a: 2, e: 'Uzbekistan is the only other doubly landlocked country; all five of its neighbors are themselves landlocked.', tags: ['political', 'landlocked'] },
  { q: 'Which Asian country, home to Mount Everest\'s southern side, is landlocked between India and China?', opts: ['Bhutan', 'Bangladesh', 'Myanmar', 'Nepal'], a: 3, e: 'Nepal is landlocked between India and China and contains the southern approach to Mount Everest.', tags: ['political', 'landlocked'] },
  { q: 'Mongolia is landlocked between which two countries?', opts: ['Russia and China', 'China and Kazakhstan', 'Russia and Kazakhstan', 'China and India'], a: 0, e: 'Mongolia borders only Russia to the north and China to the south, making those its only two neighbors.', tags: ['political', 'landlocked'] },
  { q: 'Which continent has the most landlocked countries?', opts: ['South America', 'Africa', 'Europe', 'Asia'], a: 1, e: 'Africa has 16 landlocked countries, more than any other continent.', tags: ['political', 'landlocked'] },

  // ── Level 4 — Territories & Dependencies ──
  { q: 'Greenland is an autonomous territory belonging to which country?', opts: ['Norway', 'Iceland', 'Canada', 'Denmark'], a: 3, e: 'Greenland is an autonomous constituent country within the Kingdom of Denmark.', tags: ['political', 'territories'] },
  { q: 'Puerto Rico is an unincorporated territory of which country?', opts: ['The United States', 'Spain', 'Mexico', 'Cuba'], a: 0, e: 'Puerto Rico is an unincorporated territory of the United States; its residents are US citizens.', tags: ['political', 'territories'] },
  { q: 'French Guiana, on the northern coast of South America, is an overseas region of which country?', opts: ['Portugal', 'France', 'The Netherlands', 'Spain'], a: 1, e: 'French Guiana is an overseas region of France and part of the European Union, hosting the Guiana Space Centre.', tags: ['political', 'territories'] },
  { q: 'What is an overseas territory or dependency?', opts: ['A fully sovereign UN member state', 'A country that has withdrawn from an alliance', 'A region under the jurisdiction of a sovereign state but not fully integrated into it', 'The headquarters of an international organization'], a: 2, e: 'A dependency or overseas territory is governed by a sovereign state but is not a fully integrated, independent part of it.', tags: ['political', 'territories'] },
  { q: 'Which country administers the North Atlantic overseas territory of Bermuda?', opts: ['United States', 'Canada', 'Portugal', 'United Kingdom'], a: 3, e: 'Bermuda is a British Overseas Territory in the North Atlantic Ocean.', tags: ['political', 'territories'] },
  { q: 'The Caribbean islands of Aruba and Curaçao are constituent countries within the kingdom of which nation?', opts: ['The Netherlands', 'France', 'United Kingdom', 'Spain'], a: 0, e: 'Aruba and Curaçao are constituent countries within the Kingdom of the Netherlands.', tags: ['political', 'territories'] },
  { q: 'Gibraltar, a British Overseas Territory at the southern tip of the Iberian Peninsula, borders which country?', opts: ['Portugal', 'Spain', 'Morocco', 'France'], a: 1, e: 'Gibraltar shares its only land border with Spain and guards the strait between the Mediterranean and Atlantic.', tags: ['political', 'territories'] },
  { q: 'New Caledonia and French Polynesia in the Pacific Ocean are overseas territories of which country?', opts: ['Australia', 'New Zealand', 'France', 'United States'], a: 2, e: 'New Caledonia and French Polynesia are overseas collectivities of France in the Pacific.', tags: ['political', 'territories'] },

  // ── Level 5 — International Organizations ──
  { q: 'How many member states does the European Union have?', opts: ['27', '25', '30', '15'], a: 0, e: 'The European Union has 27 member states following the United Kingdom\'s departure (Brexit) in 2020.', tags: ['political', 'organizations'] },
  { q: 'What does NATO primarily function as?', opts: ['A shared global currency union', 'An environmental treaty body', 'A military and collective-defense alliance', 'A UN humanitarian relief agency'], a: 2, e: 'NATO, the North Atlantic Treaty Organization, is a collective-defense military alliance founded in 1949.', tags: ['political', 'organizations'] },
  { q: 'ASEAN is an organization of countries in which region?', opts: ['South America', 'Southeast Asia', 'Central Africa', 'The Middle East'], a: 1, e: 'ASEAN, the Association of Southeast Asian Nations, promotes economic and political cooperation among Southeast Asian states.', tags: ['political', 'organizations'] },
  { q: 'The African Union (AU) includes almost every country on which continent?', opts: ['Asia', 'Europe', 'South America', 'Africa'], a: 3, e: 'The African Union is a continental body comprising the countries of Africa.', tags: ['political', 'organizations'] },
  { q: 'The United Nations was founded in 1945 primarily to promote what?', opts: ['International peace and cooperation', 'A single world currency', 'Free movement within Europe', 'Territorial conquest'], a: 0, e: 'The UN was founded after World War II to maintain international peace and security and foster cooperation among nations.', tags: ['political', 'united-nations'] },
  { q: 'Which of these countries is a member of the European Union?', opts: ['Norway', 'Switzerland', 'Germany', 'United Kingdom'], a: 2, e: 'Germany is a founding EU member. Norway and Switzerland have never joined, and the UK left in 2020.', tags: ['political', 'organizations'] },
  { q: 'How many permanent members with veto power sit on the UN Security Council?', opts: ['Three', 'Five', 'Seven', 'Ten'], a: 1, e: 'The five permanent members are the United States, United Kingdom, France, Russia, and China, each holding a veto.', tags: ['political', 'united-nations'] },
  { q: 'Which organization uses the euro as a shared currency among many of its members?', opts: ['NATO', 'ASEAN', 'The African Union', 'The European Union'], a: 3, e: 'The euro is the shared currency of the eurozone, a group of EU member states.', tags: ['political', 'organizations'] },

  // ── Level 6 — Capitals & Government Seats ──
  { q: 'In which city is the headquarters of the United Nations located?', opts: ['Geneva', 'New York City', 'Washington, D.C.', 'Brussels'], a: 1, e: 'The UN\'s main headquarters is in New York City, though it maintains major offices in Geneva, Vienna, and Nairobi.', tags: ['political', 'capitals'] },
  { q: 'Which city hosts the main institutions of the European Union?', opts: ['Paris', 'Berlin', 'Strasbourg', 'Brussels'], a: 3, e: 'Brussels hosts the European Commission and Council and is regarded as the de facto capital of the EU.', tags: ['political', 'capitals'] },
  { q: 'What is the capital of Australia?', opts: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], a: 2, e: 'Canberra was purpose-built as Australia\'s capital as a compromise between rivals Sydney and Melbourne.', tags: ['political', 'capitals'] },
  { q: 'What is the seat of government of the Netherlands, even though Amsterdam is the constitutional capital?', opts: ['The Hague', 'Rotterdam', 'Utrecht', 'Eindhoven'], a: 0, e: 'The Hague is the seat of the Dutch government and parliament, while Amsterdam is the constitutional capital.', tags: ['political', 'capitals'] },
  { q: 'What is the capital of Canada?', opts: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], a: 1, e: 'Ottawa, in Ontario, is the national capital of Canada, not the larger cities of Toronto or Montreal.', tags: ['political', 'capitals'] },
  { q: 'What is the capital of Brazil?', opts: ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Brasília'], a: 3, e: 'Brasília, inaugurated in 1960, replaced Rio de Janeiro as Brazil\'s purpose-built capital.', tags: ['political', 'capitals'] },
  { q: 'South Africa has three capital cities. Which one is the seat of the executive branch of government?', opts: ['Cape Town', 'Bloemfontein', 'Pretoria', 'Johannesburg'], a: 2, e: 'Pretoria is the executive capital, Cape Town the legislative capital, and Bloemfontein the judicial capital.', tags: ['political', 'capitals'] },
  { q: 'What is the capital of Turkey?', opts: ['Ankara', 'Istanbul', 'Izmir', 'Antalya'], a: 0, e: 'Ankara is Turkey\'s capital, chosen over the larger and more famous Istanbul.', tags: ['political', 'capitals'] },

  // ── Level 7 — Disputed Regions ──
  { q: 'The Kashmir region is claimed and administered in parts primarily by which two countries?', opts: ['China and Mongolia', 'Iran and Afghanistan', 'India and Pakistan', 'Nepal and Bhutan'], a: 2, e: 'Kashmir is divided and disputed mainly between India and Pakistan, with China also administering a portion.', tags: ['political', 'disputed'] },
  { q: 'Western Sahara is a disputed territory largely controlled by which neighboring country?', opts: ['Morocco', 'Algeria', 'Mauritania', 'Libya'], a: 0, e: 'Morocco controls most of Western Sahara, while the Polisario Front seeks independence for the Sahrawi people.', tags: ['political', 'disputed'] },
  { q: 'Under the 1959 Antarctic Treaty, the continent of Antarctica is reserved for what?', opts: ['Military bases only', 'The control of a single nation', 'Commercial mining', 'Peaceful scientific research'], a: 3, e: 'The Antarctic Treaty sets aside territorial claims and dedicates the continent to peaceful scientific cooperation.', tags: ['political', 'disputed'] },
  { q: 'Taiwan is governed separately, but the People\'s Republic of China claims it as its territory. Taiwan\'s official name is what?', opts: ['The Kingdom of Taiwan', 'The Republic of China', 'The People\'s State of Taiwan', 'The Formosa Union'], a: 1, e: 'Taiwan\'s government officially calls itself the Republic of China, distinct from the mainland People\'s Republic of China.', tags: ['political', 'disputed'] },
  { q: 'In which year was the Antarctic Treaty, which sets aside all territorial claims, signed?', opts: ['1919', '1945', '1959', '1982'], a: 2, e: 'The Antarctic Treaty was signed in 1959 and entered into force in 1961.', tags: ['political', 'disputed'] },
  { q: 'Taiwan is not a member of which major international body, being represented there instead by the People\'s Republic of China?', opts: ['The United Nations', 'The Olympic Games', 'The World Trade Organization', 'APEC'], a: 0, e: 'Taiwan is not a UN member; it competes at the Olympics as "Chinese Taipei" and participates in the WTO and APEC.', tags: ['political', 'disputed'] },
  { q: 'The Golan Heights is a disputed plateau lying between Israel and which country?', opts: ['Lebanon', 'Jordan', 'Egypt', 'Syria'], a: 3, e: 'The Golan Heights lies between Israel and Syria; Israel has controlled most of it since 1967.', tags: ['political', 'disputed'] },
  { q: 'The Falkland Islands in the South Atlantic are administered by the United Kingdom and also claimed by which country?', opts: ['Chile', 'Argentina', 'Uruguay', 'Brazil'], a: 1, e: 'Argentina claims the Falkland Islands (Islas Malvinas), which the UK administers; the two fought a war over them in 1982.', tags: ['political', 'disputed'] },

  // ── Level 8 — Historical Borders & Change ──
  { q: 'In which year did the Soviet Union (USSR) dissolve into 15 independent countries?', opts: ['1985', '1975', '1995', '1991'], a: 3, e: 'The Soviet Union was formally dissolved in December 1991, giving rise to 15 independent states.', tags: ['political', 'history'] },
  { q: 'In which year did East and West Germany reunify into a single country?', opts: ['1985', '1990', '1995', '1989'], a: 1, e: 'Germany reunified on 3 October 1990, less than a year after the Berlin Wall fell in November 1989.', tags: ['political', 'history'] },
  { q: 'Yugoslavia broke apart in the 1990s into several countries. Which of these was one of them?', opts: ['Croatia', 'Austria', 'Hungary', 'Bulgaria'], a: 0, e: 'Croatia was one of the successor states of the former Yugoslavia, along with Serbia, Slovenia, and others.', tags: ['political', 'history'] },
  { q: 'Which country changed its official name from Burma?', opts: ['Thailand', 'Cambodia', 'Myanmar', 'Laos'], a: 2, e: 'Burma was renamed Myanmar by its government in 1989.', tags: ['political', 'history'] },
  { q: 'The country formerly known as Zaire is now called what?', opts: ['Republic of the Congo', 'Zambia', 'Angola', 'Democratic Republic of the Congo'], a: 3, e: 'Zaire reverted to the name Democratic Republic of the Congo in 1997.', tags: ['political', 'history'] },
  { q: 'Which country was formerly known as Siam?', opts: ['Vietnam', 'Thailand', 'Malaysia', 'Indonesia'], a: 1, e: 'Siam was renamed Thailand in 1939 (and briefly reverted before adopting Thailand permanently in 1949).', tags: ['political', 'history'] },
  { q: 'In 2011, which country gained independence as the world\'s newest widely recognized sovereign state?', opts: ['South Sudan', 'Kosovo', 'East Timor', 'Montenegro'], a: 0, e: 'South Sudan seceded from Sudan in 2011 and became the 193rd member of the United Nations.', tags: ['political', 'history'] },
  { q: 'Czechoslovakia peacefully split in 1993 into the Czech Republic and which other country?', opts: ['Austria', 'Hungary', 'Slovakia', 'Slovenia'], a: 2, e: 'The "Velvet Divorce" of 1993 split Czechoslovakia into the Czech Republic and Slovakia.', tags: ['political', 'history'] },

  // ── Level 9 — Enclaves & Exclaves ──
  { q: 'Which sovereign country is an enclave located entirely within Italy?', opts: ['San Marino', 'Monaco', 'Andorra', 'Liechtenstein'], a: 0, e: 'San Marino, one of the world\'s oldest republics, is completely surrounded by Italy.', tags: ['political', 'enclaves'] },
  { q: 'Vatican City is an independent state located entirely within which city?', opts: ['Florence', 'Milan', 'Rome', 'Naples'], a: 2, e: 'Vatican City is an enclave within the city of Rome, the capital of Italy.', tags: ['political', 'enclaves'] },
  { q: 'Lesotho is a country completely surrounded by which single nation?', opts: ['Namibia', 'Botswana', 'Zimbabwe', 'South Africa'], a: 3, e: 'Lesotho is entirely enclaved within South Africa, one of only three such enclaved sovereign states.', tags: ['political', 'enclaves'] },
  { q: 'What is an exclave?', opts: ['A country with no coastline', 'A part of a country that is geographically separated from its main territory', 'A disputed border zone', 'An uninhabited island'], a: 1, e: 'An exclave is a portion of a state that is physically detached from the main body of that state.', tags: ['political', 'enclaves'] },
  { q: 'Kaliningrad is an exclave of which country, cut off from the mainland by Lithuania and Poland?', opts: ['Russia', 'Belarus', 'Ukraine', 'Germany'], a: 0, e: 'Kaliningrad is a Russian exclave on the Baltic Sea, separated from the rest of Russia by other countries.', tags: ['political', 'enclaves'] },
  { q: 'The Nagorno-Karabakh region is a mountainous area lying within the internationally recognized borders of which country?', opts: ['Armenia', 'Georgia', 'Azerbaijan', 'Turkey'], a: 2, e: 'Nagorno-Karabakh lies within Azerbaijan\'s internationally recognized borders and has long been contested with Armenia.', tags: ['political', 'enclaves'] },
  { q: 'An enclave is best described as a territory that is what?', opts: ['Split into many islands', 'A former colony', 'Surrounded by mountains', 'Entirely surrounded by the territory of another state'], a: 3, e: 'An enclave is a territory (or part of one) completely surrounded by the territory of another state.', tags: ['political', 'enclaves'] },
  { q: 'The three sovereign states each enclaved entirely within a single other country are Vatican City, San Marino, and which third?', opts: ['Monaco', 'Lesotho', 'Andorra', 'Brunei'], a: 1, e: 'Lesotho, surrounded by South Africa, joins Vatican City and San Marino (both within Italy) as the only fully enclaved sovereign states.', tags: ['political', 'enclaves'] },

  // ── Level 10 — Political Geography Mastery ──
  { q: 'Counting its overseas territories, which country spans the most time zones in the world?', opts: ['Russia', 'France', 'United States', 'China'], a: 1, e: 'France spans 12 time zones through its overseas territories, more than any other country; Russia has 11.', tags: ['political', 'mastery'] },
  { q: 'Which country\'s largest city straddles two continents, split between Europe and Asia by a strait?', opts: ['Russia', 'Kazakhstan', 'Georgia', 'Turkey'], a: 3, e: 'Istanbul, Turkey\'s largest city, spans the Bosphorus strait, placing it in both Europe and Asia.', tags: ['political', 'mastery'] },
  { q: 'Which country has the longest total land border of any nation, touching 14 neighbors?', opts: ['China', 'Russia', 'Brazil', 'India'], a: 0, e: 'China has the longest land border of any country, roughly 22,000 km shared with 14 neighbors.', tags: ['political', 'mastery'] },
  { q: 'Which entity in the Middle East is a UN non-member permanent observer rather than a full member state?', opts: ['Israel', 'Jordan', 'Palestine', 'Lebanon'], a: 2, e: 'Palestine holds non-member observer state status at the UN, while Israel, Jordan, and Lebanon are full members.', tags: ['political', 'mastery'] },
  { q: 'The Caspian Sea is bordered by five countries. Which of these is one of them?', opts: ['Georgia', 'Kazakhstan', 'Uzbekistan', 'Armenia'], a: 1, e: 'The Caspian Sea is bordered by Russia, Kazakhstan, Turkmenistan, Iran, and Azerbaijan.', tags: ['political', 'mastery'] },
  { q: 'Which transcontinental country is the largest in the world by land area?', opts: ['Canada', 'China', 'United States', 'Russia'], a: 3, e: 'Russia is the largest country by area, spanning some 17 million square kilometers across Europe and Asia.', tags: ['political', 'mastery'] },
  { q: 'Kazakhstan is the world\'s largest landlocked country. Across which two continents\' borderland does it sit?', opts: ['Europe and Asia', 'Asia and Africa', 'Europe and Africa', 'Asia and Australia'], a: 0, e: 'Kazakhstan straddles the conventional boundary between Europe and Asia and is the largest landlocked country by area.', tags: ['political', 'mastery'] },
  { q: 'Among the European microstates Andorra, Liechtenstein, Malta, and San Marino, which is an island nation?', opts: ['Andorra', 'Liechtenstein', 'Malta', 'San Marino'], a: 2, e: 'Malta is an island nation in the Mediterranean, while Andorra, Liechtenstein, and San Marino are landlocked.', tags: ['political', 'mastery'] },
];
