// React roadmap questions (100): "what renders / what does this hook do / what
// is the value". 25 levels × 4 questions, easiest → hardest. See lib/roadmap.ts
// for the per-level titles. Ids are rm-react-1 … rm-react-100.

import { buildRoadmap, type Seed } from './roadmap-build';

const seeds: Seed[] = [
  // ── Level 1 — JSX Basics ───────────────────────────────────────────────
  { q: 'What does App render?\n\n```jsx\nfunction App() {\n  return <h1>Hello</h1>;\n}\n```', opts: ['An h1 with text "Hello"', 'The string "Hello"', 'Nothing', 'An error'], a: 0, e: 'JSX <h1>Hello</h1> renders a real h1 element containing the text "Hello".', tags: ['JSX'] },
  { q: 'What does the paragraph show?\n\n```jsx\nconst x = 5;\n<p>{x + 1}</p>;\n```', opts: ['6', '5', 'x + 1', '{x + 1}'], a: 0, e: 'Braces embed a JS expression; x + 1 evaluates to 6.', tags: ['JSX', 'Expressions'] },
  { q: 'What is rendered?\n\n```jsx\n<div>{2 + 2}</div>;\n```', opts: ['"2 + 2"', '4', '{4}', 'an error'], a: 1, e: 'The expression inside braces is evaluated, so the div shows 4.', tags: ['JSX', 'Expressions'] },
  { q: 'What is rendered?\n\n```jsx\nconst name = "Sam";\n<p>Hi {name}</p>;\n```', opts: ['"Hi {name}"', 'Hi Sam', 'Hi name', 'an error'], a: 1, e: 'The {name} expression is substituted with its value, giving "Hi Sam".', tags: ['JSX'] },

  // ── Level 2 — Components ────────────────────────────────────────────────
  { q: 'What does App render?\n\n```jsx\nfunction Welcome() {\n  return <p>Welcome</p>;\n}\nfunction App() {\n  return <Welcome />;\n}\n```', opts: ['<p>Welcome</p>', 'The string "Welcome"', 'Nothing', 'An error'], a: 0, e: 'App renders the Welcome component, which outputs <p>Welcome</p>.', tags: ['Components'] },
  { q: 'Why might <app /> not work as a component?\n\n```jsx\nfunction app() {\n  return <div />;\n}\n```', opts: ['Components must start uppercase', 'It is missing a return', 'It needs props', 'Syntax error'], a: 0, e: 'JSX treats lowercase names as HTML tags; component names must be capitalized.', tags: ['Components', 'JSX'] },
  { q: 'What is <>...</> called?\n\n```jsx\nfunction App() {\n  return (\n    <>\n      <p>A</p>\n      <p>B</p>\n    </>\n  );\n}\n```', opts: ['A Fragment', 'A div', 'An array', 'An error'], a: 0, e: '<>...</> is a Fragment: it groups children without adding a DOM node.', tags: ['Components', 'Fragment'] },
  { q: 'What is rendered?\n\n```jsx\nfunction Sum() {\n  return <p>{1 + 2 + 3}</p>;\n}\n```', opts: ['"1 + 2 + 3"', '6', '"123"', 'an error'], a: 1, e: 'The arithmetic expression evaluates to 6.', tags: ['Components', 'Expressions'] },

  // ── Level 3 — Props ────────────────────────────────────────────────────
  { q: 'What is rendered?\n\n```jsx\nfunction Hello({ name }) {\n  return <p>Hi {name}</p>;\n}\n<Hello name="Ada" />;\n```', opts: ['"Hi name"', 'Hi Ada', '"Hi {name}"', 'an error'], a: 1, e: 'The name prop "Ada" is destructured and rendered, giving "Hi Ada".', tags: ['Props'] },
  { q: 'What width does the div get?\n\n```jsx\nfunction Box({ width }) {\n  return <div style={{ width }} />;\n}\n<Box width={100} />;\n```', opts: ['100', '"width"', 'no width', 'an error'], a: 0, e: 'The width prop (100) is passed into the inline style.', tags: ['Props', 'Style'] },
  { q: 'What is rendered?\n\n```jsx\nfunction Greet({ name = "Guest" }) {\n  return <p>{name}</p>;\n}\n<Greet />;\n```', opts: ['empty', 'Guest', 'undefined', 'an error'], a: 1, e: 'No name prop is passed, so the destructuring default "Guest" is used.', tags: ['Props', 'Defaults'] },
  { q: 'What does Card render around its content?\n\n```jsx\nfunction Card({ children }) {\n  return <div className="card">{children}</div>;\n}\n<Card>Hi</Card>;\n```', opts: ['"Hi" inside the div', 'the word "children"', 'Nothing', 'an error'], a: 0, e: 'children holds whatever is nested between the tags, here the text "Hi".', tags: ['Props', 'children'] },

  // ── Level 4 — Rendering Lists ──────────────────────────────────────────
  { q: 'How many list items render?\n\n```jsx\nconst items = ["a", "b", "c"];\n<ul>{items.map(i => <li key={i}>{i}</li>)}</ul>;\n```', opts: ['1', '3', '0', 'an error'], a: 1, e: 'map produces one <li> per array element, so three render.', tags: ['Lists', 'map'] },
  { q: 'What is missing here?\n\n```jsx\n{items.map(i => <li>{i}</li>)}\n```', opts: ['A key prop', 'A return', 'A ref', 'Nothing'], a: 0, e: 'List elements need a stable key prop so React can track them.', tags: ['Lists', 'key'] },
  { q: 'What is rendered?\n\n```jsx\nconst nums = [1, 2, 3];\n<div>{nums.map(n => n * 2)}</div>;\n```', opts: ['246', '123', '[2, 4, 6]', 'an error'], a: 0, e: 'React renders the array [2, 4, 6] by concatenating the values: "246".', tags: ['Lists', 'map'] },
  { q: 'What is rendered?\n\n```jsx\nconst empty = [];\n<ul>{empty.map(i => <li key={i}>{i}</li>)}</ul>;\n```', opts: ['An empty list', 'an error', 'undefined', '"[]"'], a: 0, e: 'Mapping an empty array yields no children, so the ul renders empty.', tags: ['Lists'] },

  // ── Level 5 — Conditional Rendering ────────────────────────────────────
  { q: 'What is rendered?\n\n```jsx\nconst loggedIn = true;\n<div>{loggedIn ? "Welcome" : "Sign in"}</div>;\n```', opts: ['Welcome', 'Sign in', 'true', 'an error'], a: 0, e: 'The ternary picks the first value because loggedIn is true.', tags: ['Conditional'] },
  { q: 'What is rendered?\n\n```jsx\nconst show = false;\n<div>{show && <p>Hi</p>}</div>;\n```', opts: ['<p>Hi</p>', 'Nothing', '"false"', 'an error'], a: 1, e: 'When the left side of && is false, React renders nothing (false is ignored).', tags: ['Conditional', 'Short-circuit'] },
  { q: 'What does this render?\n\n```jsx\nconst count = 0;\n<div>{count && <p>Has items</p>}</div>;\n```', opts: ['Nothing', '0', '<p>Has items</p>', 'an error'], a: 1, e: 'count is 0, which is falsy but still a number — React renders the 0. This is a classic && pitfall.', tags: ['Conditional', 'Gotchas'] },
  { q: 'What is rendered?\n\n```jsx\nconst items = ["a"];\n<div>{items.length > 0 && <p>{items.length}</p>}</div>;\n```', opts: ['1', 'Nothing', '0', 'an error'], a: 0, e: 'The length is 1 (truthy), so the paragraph renders showing 1.', tags: ['Conditional'] },

  // ── Level 6 — useState: Basics ─────────────────────────────────────────
  { q: 'What is the initial value of count?\n\n```jsx\nconst [count, setCount] = useState(0);\n```', opts: ['0', 'undefined', 'null', 'setCount'], a: 0, e: 'The argument to useState is the initial state, here 0.', tags: ['useState'] },
  { q: 'What is the value of name?\n\n```jsx\nconst [name] = useState("Sam");\n```', opts: ['Sam', 'undefined', '[]', 'useState'], a: 0, e: 'The first array element is the current state value, "Sam".', tags: ['useState'] },
  { q: 'What is state[1]?\n\n```jsx\nconst state = useState(0);\nstate[1];\n```', opts: ['0', 'the setter function', 'undefined', 'an array'], a: 1, e: 'useState returns [value, setter]; index 1 is the setter function.', tags: ['useState'] },
  { q: 'What type is setOn?\n\n```jsx\nconst [on, setOn] = useState(false);\n```', opts: ['boolean', 'a function', 'false', 'undefined'], a: 1, e: 'The second value from useState is the updater function.', tags: ['useState'] },

  // ── Level 7 — Event Handling ───────────────────────────────────────────
  { q: 'When does it log "clicked"?\n\n```jsx\n<button onClick={() => console.log("clicked")}>Go</button>;\n```', opts: ['On render', 'When clicked', 'Never', 'On mount'], a: 1, e: 'Passing a function to onClick runs it only when the button is clicked.', tags: ['Events'] },
  { q: 'What is the problem here?\n\n```jsx\n<button onClick={handleClick()}>Go</button>;\n```', opts: ['handleClick runs immediately on render', 'It works fine', 'It never runs', 'Syntax error'], a: 0, e: 'The parentheses call handleClick during render and pass its result, not the function itself.', tags: ['Events', 'Gotchas'] },
  { q: 'After one click, what does the button show?\n\n```jsx\nfunction App() {\n  const [n, setN] = useState(0);\n  return <button onClick={() => setN(n + 1)}>{n}</button>;\n}\n```', opts: ['0', '1', '2', 'undefined'], a: 1, e: 'Clicking sets n to 0 + 1, and the re-render shows 1.', tags: ['Events', 'useState'] },
  { q: 'What is e.target.value?\n\n```jsx\n<input onChange={e => console.log(e.target.value)} />;\n```', opts: ['The input value', 'The element', 'undefined', 'the event name'], a: 0, e: 'e.target is the input, and its value is the current text.', tags: ['Events', 'Forms'] },

  // ── Level 8 — Updating State ───────────────────────────────────────────
  { q: 'After re-render, what is n?\n\n```jsx\nconst [n, setN] = useState(0);\nsetN(5);\n```', opts: ['0', '5', 'undefined', 'NaN'], a: 1, e: 'setN(5) schedules the new state, so after re-render n is 5.', tags: ['useState'] },
  { q: 'What is prev here?\n\n```jsx\nsetN(prev => prev + 1);\n```', opts: ['The new value', 'The current state value', 'undefined', 'the setter'], a: 1, e: 'The functional updater receives the latest state as prev.', tags: ['useState'] },
  { q: 'After one call from n = 0, what is n?\n\n```jsx\nconst [n, setN] = useState(0);\nfunction handle() {\n  setN(n + 1);\n  setN(n + 1);\n}\n```', opts: ['1', '2', '0', '3'], a: 0, e: 'Both calls read the same stale n (0), so both set it to 1. The result is 1.', tags: ['useState', 'Gotchas'] },
  { q: 'After one call from n = 0, what is n?\n\n```jsx\nfunction handle() {\n  setN(p => p + 1);\n  setN(p => p + 1);\n}\n```', opts: ['1', '2', '0', '3'], a: 1, e: 'Functional updates use the latest value each time, so 0 → 1 → 2.', tags: ['useState'] },

  // ── Level 9 — State with Objects/Arrays ────────────────────────────────
  { q: 'What is the resulting user?\n\n```jsx\nconst [user, setUser] = useState({ name: "A", age: 1 });\nsetUser({ ...user, age: 2 });\n```', opts: ['{ name: "A", age: 2 }', '{ age: 2 }', '{ name: "A" }', 'an error'], a: 0, e: 'Spreading user then overriding age keeps name and updates age to 2.', tags: ['useState', 'Objects'] },
  { q: 'What is the new list?\n\n```jsx\nconst [list, setList] = useState([1, 2]);\nsetList([...list, 3]);\n```', opts: ['[1, 2, 3]', '[3]', '[1, 2]', 'an error'], a: 0, e: 'Spreading the old list and adding 3 produces [1, 2, 3].', tags: ['useState', 'Arrays'] },
  { q: 'Why might the UI not update?\n\n```jsx\nconst [list, setList] = useState([1, 2]);\nlist.push(3);\nsetList(list);\n```', opts: ['Same array reference, so React may skip the re-render', 'It always works', 'push is invalid', 'Syntax error'], a: 0, e: 'Mutating then passing the same reference can make React think nothing changed.', tags: ['useState', 'Immutability'] },
  { q: 'What is the new list?\n\n```jsx\nconst [list, setList] = useState([1, 2, 3]);\nsetList(list.filter(x => x !== 2));\n```', opts: ['[1, 3]', '[2]', '[1, 2, 3]', '[1, 2]'], a: 0, e: 'filter removes the element equal to 2, leaving [1, 3].', tags: ['useState', 'Arrays'] },

  // ── Level 10 — Derived State ───────────────────────────────────────────
  { q: 'Should count be its own state?\n\n```jsx\nconst [items, setItems] = useState([1, 2, 3]);\nconst count = items.length;\n```', opts: ['Yes, use useState', 'No, derive it from items', 'Use a ref', 'Use useEffect'], a: 1, e: 'Values computable from existing state should be derived, not stored separately.', tags: ['Derived state'] },
  { q: 'What is full?\n\n```jsx\nconst [first] = useState("A");\nconst [last] = useState("B");\nconst full = `${first} ${last}`;\n```', opts: ['"A B"', '"AB"', '"A"', 'undefined'], a: 0, e: 'The template combines the two pieces of state into "A B".', tags: ['Derived state'] },
  { q: 'What is total?\n\n```jsx\nconst [price] = useState(10);\nconst [qty] = useState(2);\nconst total = price * qty;\n```', opts: ['10', '20', '2', '12'], a: 1, e: 'total is derived from price * qty = 20.', tags: ['Derived state'] },
  { q: 'What is evens?\n\n```jsx\nconst [nums] = useState([1, 2, 3, 4]);\nconst evens = nums.filter(n => n % 2 === 0);\n```', opts: ['[2, 4]', '[1, 3]', '[1, 2, 3, 4]', '4'], a: 0, e: 'Filtering for even numbers gives [2, 4].', tags: ['Derived state'] },

  // ── Level 11 — useEffect: Basics ───────────────────────────────────────
  { q: 'When does this log "mounted"?\n\n```jsx\nuseEffect(() => {\n  console.log("mounted");\n}, []);\n```', opts: ['Every render', 'Once on mount', 'Never', 'On unmount'], a: 1, e: 'An empty dependency array runs the effect once, after the first render.', tags: ['useEffect'] },
  { q: 'When does this run?\n\n```jsx\nuseEffect(() => {\n  console.log("ran");\n});\n```', opts: ['Once', 'After every render', 'Never', 'On unmount only'], a: 1, e: 'With no dependency array, the effect runs after every render.', tags: ['useEffect'] },
  { q: 'When does this run?\n\n```jsx\nuseEffect(() => {\n  console.log(count);\n}, [count]);\n```', opts: ['Only on mount', 'On mount and whenever count changes', 'Every render', 'Never'], a: 1, e: 'With [count], it runs on mount and again each time count changes.', tags: ['useEffect'] },
  { q: 'What does the paragraph finally show?\n\n```jsx\nfunction App() {\n  const [n, setN] = useState(0);\n  useEffect(() => {\n    setN(1);\n  }, []);\n  return <p>{n}</p>;\n}\n```', opts: ['0', '1', 'undefined', 'an error'], a: 1, e: 'The effect runs once after mount and sets n to 1, triggering a re-render.', tags: ['useEffect', 'useState'] },

  // ── Level 12 — Effect Dependencies ─────────────────────────────────────
  { q: 'What is the problem if value changes?\n\n```jsx\nuseEffect(() => {\n  console.log(value);\n}, []);\n```', opts: ['It re-runs each change', 'It logs a stale value and never re-runs', 'Syntax error', 'Infinite loop'], a: 1, e: 'Missing value from the deps means the effect keeps the original value and never re-runs.', tags: ['useEffect', 'Dependencies'] },
  { q: 'What happens?\n\n```jsx\nuseEffect(() => {\n  setCount(count + 1);\n}, [count]);\n```', opts: ['Runs once', 'Infinite re-render loop', 'Never runs', 'Syntax error'], a: 1, e: 'Updating count re-runs the effect, which updates count again — an infinite loop.', tags: ['useEffect', 'Gotchas'] },
  { q: 'What is the problem?\n\n```jsx\nuseEffect(() => {}, [{ a: 1 }]);\n```', opts: ['Runs once', 'A new object each render makes it run every render', 'Never runs', 'Syntax error'], a: 1, e: 'The object literal is a fresh reference each render, so the dependency always "changes".', tags: ['useEffect', 'Dependencies'] },
  { q: 'When does this run?\n\n```jsx\nuseEffect(() => {\n  document.title = `Count: ${count}`;\n}, [count]);\n```', opts: ['Every render', 'On mount and when count changes', 'Never', 'On unmount'], a: 1, e: 'The effect runs on mount and whenever count changes.', tags: ['useEffect', 'Dependencies'] },

  // ── Level 13 — Cleanup Functions ───────────────────────────────────────
  { q: 'What is the returned function for?\n\n```jsx\nuseEffect(() => {\n  const id = setInterval(tick, 1000);\n  return () => clearInterval(id);\n}, []);\n```', opts: ['Cleanup that runs on unmount', 'Runs the effect again', 'Sets state', 'Nothing'], a: 0, e: 'A function returned from an effect is its cleanup, run on unmount (and before re-runs).', tags: ['useEffect', 'Cleanup'] },
  { q: 'When does "cleanup" log?\n\n```jsx\nuseEffect(() => {\n  console.log("setup");\n  return () => console.log("cleanup");\n}, [id]);\n```', opts: ['Only on unmount', 'Before each re-run and on unmount', 'Never', 'On mount'], a: 1, e: 'Cleanup runs before the effect re-runs (when id changes) and once on unmount.', tags: ['useEffect', 'Cleanup'] },
  { q: 'Why return removeEventListener?\n\n```jsx\nuseEffect(() => {\n  window.addEventListener("resize", onResize);\n  return () => window.removeEventListener("resize", onResize);\n}, []);\n```', opts: ['To avoid memory leaks and duplicate listeners', 'To add it twice', 'No reason', 'To re-render'], a: 0, e: 'Cleanup removes the listener so it does not leak or stack up across mounts.', tags: ['useEffect', 'Cleanup'] },
  { q: 'What is the bug?\n\n```jsx\nuseEffect(() => {\n  const id = setInterval(() => setN(n => n + 1), 1000);\n}, []);\n```', opts: ['The interval is never cleared (a leak)', 'It works fine', 'It runs once', 'Syntax error'], a: 0, e: 'Without returning clearInterval, the timer keeps running after unmount.', tags: ['useEffect', 'Cleanup'] },

  // ── Level 14 — useRef ──────────────────────────────────────────────────
  { q: 'Does changing ref.current re-render?\n\n```jsx\nconst ref = useRef(0);\nref.current = 5;\n```', opts: ['Yes', 'No', 'Only once', 'It throws'], a: 1, e: 'Mutating a ref does not trigger a re-render; refs hold values outside the render cycle.', tags: ['useRef'] },
  { q: 'After mount, what is inputRef.current?\n\n```jsx\nconst inputRef = useRef(null);\n<input ref={inputRef} />;\ninputRef.current;\n```', opts: ['null', 'the DOM input element', '0', 'a function'], a: 1, e: 'After the element mounts, React assigns the DOM node to ref.current.', tags: ['useRef', 'DOM'] },
  { q: 'What is this pattern commonly used for?\n\n```jsx\nconst renders = useRef(0);\nrenders.current++;\n```', opts: ['Triggering re-renders', 'Persisting a value across renders without re-rendering', 'Replacing state', 'Causing loops'], a: 1, e: 'Refs persist a mutable value between renders without causing updates.', tags: ['useRef'] },
  { q: 'What is rendered?\n\n```jsx\nconst ref = useRef(10);\nfunction Comp() {\n  ref.current = 20;\n  return <p>{ref.current}</p>;\n}\n```', opts: ['10', '20', 'undefined', 'an error'], a: 1, e: 'ref.current is set to 20 before the return, so the paragraph shows 20.', tags: ['useRef'] },

  // ── Level 15 — Forms & Inputs ──────────────────────────────────────────
  { q: 'What kind of input is this?\n\n```jsx\nconst [text, setText] = useState("");\n<input value={text} onChange={e => setText(e.target.value)} />;\n```', opts: ['Uncontrolled input', 'Controlled input', 'Read-only input', 'Ref input'], a: 1, e: 'React state drives value and onChange updates it — a controlled input.', tags: ['Forms'] },
  { q: 'What is the problem?\n\n```jsx\n<input value="hi" />;\n```', opts: ['Works normally', 'It is read-only and React warns', 'It crashes', 'It is uncontrolled'], a: 1, e: 'A value with no onChange makes the field read-only and React warns about it.', tags: ['Forms', 'Gotchas'] },
  { q: 'What does e.target.checked give?\n\n```jsx\nconst [checked, setChecked] = useState(false);\n<input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} />;\n```', opts: ['the value string', 'the boolean checked state', 'undefined', 'the element'], a: 1, e: 'For checkboxes, e.target.checked is the boolean checked state.', tags: ['Forms'] },
  { q: 'Why call preventDefault?\n\n```jsx\n<form onSubmit={e => { e.preventDefault(); }}>\n```', opts: ['To prevent the page from reloading', 'To submit faster', 'To clear inputs', 'No reason'], a: 0, e: 'preventDefault stops the browser’s default full-page reload on submit.', tags: ['Forms'] },

  // ── Level 16 — Lifting State Up ────────────────────────────────────────
  { q: 'Where does the state live?\n\n```jsx\nfunction Parent() {\n  const [value, setValue] = useState("");\n  return <Child value={value} onChange={setValue} />;\n}\n```', opts: ['In Child', 'In Parent', 'In both', 'Nowhere'], a: 1, e: 'The state is declared in Parent and passed down to Child via props.', tags: ['Lifting state'] },
  { q: 'How does Child change count?\n\n```jsx\nfunction Child({ count, onInc }) {\n  return <button onClick={onInc}>{count}</button>;\n}\n```', opts: ['setCount directly', 'By calling onInc from props', 'With its own useState', 'It cannot'], a: 1, e: 'Child calls the onInc callback passed by the parent, which owns the state.', tags: ['Lifting state'] },
  { q: 'To share state between two sibling components you should:', opts: ['Use a global variable', 'Lift the state to their common parent', 'Duplicate the state', 'Use refs'], a: 1, e: 'Move shared state up to the closest common ancestor and pass it down.', tags: ['Lifting state'] },
  { q: 'When Nav calls onSelect("about"), what tab does Content get?\n\n```jsx\nfunction App() {\n  const [tab, setTab] = useState("home");\n  return (\n    <>\n      <Nav onSelect={setTab} />\n      <Content tab={tab} />\n    </>\n  );\n}\n```', opts: ['"home"', '"about"', 'undefined', 'an error'], a: 1, e: 'onSelect is setTab, so tab becomes "about" and Content re-renders with it.', tags: ['Lifting state'] },

  // ── Level 17 — useMemo ─────────────────────────────────────────────────
  { q: 'When does expensiveCalc run?\n\n```jsx\nconst result = useMemo(() => expensiveCalc(a), [a]);\n```', opts: ['Every render', 'Only when a changes', 'Never', 'On unmount'], a: 1, e: 'useMemo recomputes only when a dependency changes; otherwise it reuses the cached value.', tags: ['useMemo'] },
  { q: 'What is value?\n\n```jsx\nconst value = useMemo(() => 2 + 2, []);\n```', opts: ['4', '"2+2"', 'a function', 'undefined'], a: 0, e: 'useMemo returns the function’s result, 4 — not the function itself.', tags: ['useMemo'] },
  { q: 'Why use useMemo here?\n\n```jsx\nconst sorted = useMemo(() => [...items].sort(), [items]);\n```', opts: ['To re-sort on every render', 'To avoid re-sorting unless items changes', 'To mutate items', 'It has no effect'], a: 1, e: 'Memoizing skips the costly sort unless items actually changes.', tags: ['useMemo'] },
  { q: 'Across renders (with no dep changes), what is a?\n\n```jsx\nconst a = useMemo(() => ({ x: 1 }), []);\n```', opts: ['A new object each render', 'The same object reference', 'undefined', 're-created on any state change'], a: 1, e: 'With an empty dep array, useMemo keeps returning the same object reference.', tags: ['useMemo'] },

  // ── Level 18 — useCallback ─────────────────────────────────────────────
  { q: 'What does useCallback return?\n\n```jsx\nconst handleClick = useCallback(() => doThing(id), [id]);\n```', opts: ['The result of doThing', 'A memoized function', 'undefined', 'a new function each render'], a: 1, e: 'useCallback returns a memoized version of the function, stable until deps change.', tags: ['useCallback'] },
  { q: 'Across renders (deps empty), what is fn?\n\n```jsx\nconst fn = useCallback(() => {}, []);\n```', opts: ['New each render', 'The same function reference', 'undefined', 're-created always'], a: 1, e: 'An empty dep array keeps fn referentially stable across renders.', tags: ['useCallback'] },
  { q: 'What is the bug if count changes?\n\n```jsx\nuseCallback(() => console.log(count), []);\n```', opts: ['It always logs the current count', 'It closes over a stale count', 'Syntax error', 'It re-renders'], a: 1, e: 'With empty deps, the callback captures the first count and never updates.', tags: ['useCallback', 'Gotchas'] },
  { q: 'useCallback(fn, deps) is roughly equivalent to:', opts: ['useMemo(() => fn, deps)', 'useEffect(fn, deps)', 'useRef(fn)', 'useState(fn)'], a: 0, e: 'useCallback(fn, deps) is shorthand for useMemo(() => fn, deps).', tags: ['useCallback'] },

  // ── Level 19 — useReducer ──────────────────────────────────────────────
  { q: 'After dispatch, what is count?\n\n```jsx\nfunction reducer(state, action) {\n  switch (action.type) {\n    case "inc":\n      return state + 1;\n    default:\n      return state;\n  }\n}\nconst [count, dispatch] = useReducer(reducer, 0);\ndispatch({ type: "inc" });\n```', opts: ['0', '1', '2', 'undefined'], a: 1, e: 'The "inc" action returns state + 1, so count becomes 1.', tags: ['useReducer'] },
  { q: 'What does dispatch do?\n\n```jsx\nconst [state, dispatch] = useReducer(reducer, { n: 0 });\n```', opts: ['Reads state', 'Sends an action to the reducer', 'Re-renders only', 'Nothing'], a: 1, e: 'dispatch sends an action object to the reducer, which computes the next state.', tags: ['useReducer'] },
  { q: 'After dispatch, what is n?\n\n```jsx\nfunction reducer(s, a) {\n  if (a.type === "add") return s + a.value;\n  return s;\n}\nconst [n, dispatch] = useReducer(reducer, 10);\ndispatch({ type: "add", value: 5 });\n```', opts: ['10', '15', '5', 'undefined'], a: 1, e: 'The "add" action adds a.value (5) to 10, giving 15.', tags: ['useReducer'] },
  { q: 'useReducer is preferable to useState when:', opts: ['State is a single boolean', 'State logic is complex or transitions are structured', 'You never update state', 'Never use it'], a: 1, e: 'useReducer shines when state updates are complex or involve many related actions.', tags: ['useReducer'] },

  // ── Level 20 — useContext ──────────────────────────────────────────────
  { q: 'With no Provider above, what is theme?\n\n```jsx\nconst ThemeContext = createContext("light");\nconst theme = useContext(ThemeContext);\n```', opts: ['undefined', '"light"', 'null', 'an error'], a: 1, e: 'Without a matching Provider, useContext returns the default passed to createContext.', tags: ['useContext'] },
  { q: 'Inside Child, what is the context value?\n\n```jsx\n<ThemeContext.Provider value="dark">\n  <Child />\n</ThemeContext.Provider>\n```', opts: ['"light"', '"dark"', 'undefined', 'an error'], a: 1, e: 'The nearest Provider supplies "dark" to any descendant reading the context.', tags: ['useContext'] },
  { q: 'What problem does Context solve?', opts: ['Slow renders', 'Prop drilling through many layers', 'Type errors', 'State mutation'], a: 1, e: 'Context lets deeply nested components read shared data without passing props at every level.', tags: ['useContext'] },
  { q: 'What is rendered (no Provider)?\n\n```jsx\nconst Ctx = createContext(0);\nfunction A() {\n  const v = useContext(Ctx);\n  return <p>{v}</p>;\n}\n```', opts: ['0', 'undefined', 'null', 'an error'], a: 0, e: 'With no Provider, the default value 0 is used.', tags: ['useContext'] },

  // ── Level 21 — Custom Hooks ────────────────────────────────────────────
  { q: 'What makes this a custom hook?\n\n```jsx\nfunction useCounter(start) {\n  const [n, setN] = useState(start);\n  return { n, inc: () => setN(p => p + 1) };\n}\n```', opts: ['It returns JSX', 'Its name starts with "use" and it calls hooks', 'It uses a class', 'Nothing'], a: 1, e: 'A custom hook is a function named use* that composes other hooks.', tags: ['Custom hooks'] },
  { q: 'After calling toggle() once, what is open?\n\n```jsx\nfunction useToggle(init) {\n  const [on, setOn] = useState(init);\n  return [on, () => setOn(p => !p)];\n}\nconst [open, toggle] = useToggle(false);\n```', opts: ['false', 'true', 'undefined', 'toggle'], a: 1, e: 'toggle flips the boolean, so open goes from false to true.', tags: ['Custom hooks'] },
  { q: 'Two components using the same custom hook share:', opts: ['The same state', 'Independent state', 'Only refs', 'Props'], a: 1, e: 'Each call to a hook gets its own isolated state; hooks share logic, not state.', tags: ['Custom hooks'] },
  { q: 'What does useDouble(8) return?\n\n```jsx\nfunction useDouble(n) {\n  return n * 2;\n}\nuseDouble(8);\n```', opts: ['8', '16', 'undefined', 'a hook'], a: 1, e: 'It simply returns n * 2 = 16.', tags: ['Custom hooks'] },

  // ── Level 22 — Keys & Reconciliation ───────────────────────────────────
  { q: 'Why does React need keys in lists?', opts: ['For styling', 'To track each item’s identity across renders', 'To sort the list', 'No reason'], a: 1, e: 'Keys let React match elements between renders to know what changed, moved, or was removed.', tags: ['Keys', 'Reconciliation'] },
  { q: 'Why is using the array index as a key risky?\n\n```jsx\n{items.map((item, i) => <Row key={i} {...item} />)}\n```', opts: ['It is always best', 'Reordering or inserting can mismatch state', 'It is required', 'It improves speed'], a: 1, e: 'Index keys break when items reorder or insert, causing state to attach to the wrong row.', tags: ['Keys', 'Gotchas'] },
  { q: 'Changing a component’s key causes React to:', opts: ['Update it in place', 'Remount a fresh instance, resetting its state', 'Ignore it', 'Throw an error'], a: 1, e: 'A new key is treated as a different element, so React unmounts the old and mounts a new one.', tags: ['Keys', 'Reconciliation'] },
  { q: 'Keys should be:', opts: ['Random on each render', 'Stable and unique among siblings', 'Always the array index', 'The same for all items'], a: 1, e: 'Good keys are stable across renders and unique within the list.', tags: ['Keys'] },

  // ── Level 23 — Performance Patterns ────────────────────────────────────
  { q: 'React.memo skips re-rendering a component when:', opts: ['Its state changes', 'Its props are unchanged (shallow equal)', 'Always', 'Never'], a: 1, e: 'React.memo memoizes a component, re-rendering only when its props shallowly change.', tags: ['Performance', 'memo'] },
  { q: 'Does memo help here?\n\n```jsx\nconst Child = React.memo(Inner);\n// parent passes a new inline arrow every render\n<Child onClick={() => {}} />;\n```', opts: ['Yes', 'No — a new function prop each render defeats it', 'Always', 'It crashes'], a: 1, e: 'A fresh inline function every render changes the prop, so memo cannot skip the re-render.', tags: ['Performance', 'memo'] },
  { q: 'useMemo and useCallback mainly help by:', opts: ['Reducing bundle size', 'Preserving stable references between renders', 'Avoiding hooks', 'Adding state'], a: 1, e: 'They keep values and functions referentially stable, which helps memoized children and deps.', tags: ['Performance'] },
  { q: 'Memoizing everything prematurely can:', opts: ['Always speed things up', 'Add overhead and complexity for little gain', 'Break React', 'Remove all re-renders'], a: 1, e: 'Over-memoization adds its own cost and complexity; measure before optimizing.', tags: ['Performance'] },

  // ── Level 24 — Common Pitfalls ─────────────────────────────────────────
  { q: 'What happens?\n\n```jsx\nfunction App() {\n  const [n, setN] = useState(0);\n  setN(n + 1);\n  return <p>{n}</p>;\n}\n```', opts: ['Shows 1', 'Infinite re-render loop', 'Shows 0 once', 'Syntax error'], a: 1, e: 'Calling a setter during render schedules another render, repeating forever.', tags: ['Pitfalls'] },
  { q: 'What is the problem?\n\n```jsx\nif (loading) {\n  const [x, setX] = useState(0);\n}\n```', opts: ['It is fine', 'Hooks must not be called conditionally', 'It is faster', 'It needs a key'], a: 1, e: 'Hooks must run in the same order every render, so they cannot be inside conditions.', tags: ['Pitfalls', 'Rules of hooks'] },
  { q: 'In the same render, what do both logs show?\n\n```jsx\nconst [n, setN] = useState(0);\nconsole.log(n);\nsetN(5);\nconsole.log(n);\n```', opts: ['0 then 5', '0 then 0', '5 then 5', 'undefined'], a: 1, e: 'State is constant during a render; n stays 0 until the next render after setN.', tags: ['Pitfalls', 'useState'] },
  { q: 'What is the issue?\n\n```jsx\nuseEffect(async () => {\n  await fetchData();\n}, []);\n```', opts: ['Works fine', 'The effect callback should not be async directly', 'It needs no deps', 'Syntax error'], a: 1, e: 'An effect must return undefined or a cleanup; an async function returns a promise, so define an inner async function instead.', tags: ['Pitfalls', 'useEffect'] },

  // ── Level 25 — Mixed Mastery ───────────────────────────────────────────
  { q: 'What does this component do?\n\n```jsx\nfunction App() {\n  const [n, setN] = useState(0);\n  useEffect(() => {\n    const id = setInterval(() => setN(p => p + 1), 1000);\n    return () => clearInterval(id);\n  }, []);\n  return <p>{n}</p>;\n}\n```', opts: ['Counts up by one every second', 'Renders once', 'Loops infinitely', 'Does nothing'], a: 0, e: 'The interval increments n each second, and cleanup clears it on unmount — a ticking counter.', tags: ['Mastery'] },
  { q: 'What does this do?\n\n```jsx\nconst [items, setItems] = useState([]);\nuseEffect(() => {\n  fetch("/api").then(r => r.json()).then(setItems);\n}, []);\n```', opts: ['Fetches on every render', 'Fetches once on mount and stores the result', 'Never fetches', 'Loops'], a: 1, e: 'The empty deps run the fetch once on mount and put the JSON into state.', tags: ['Mastery'] },
  { q: 'When does doubled recompute?\n\n```jsx\nconst doubled = useMemo(() => items.map(x => x * 2), [items]);\n```', opts: ['Every render', 'Only when items changes', 'Never', 'On unmount'], a: 1, e: 'useMemo recomputes the mapped array only when items changes.', tags: ['Mastery'] },
  { q: 'What does clicking the button do?\n\n```jsx\nfunction Toggle() {\n  const [on, setOn] = useState(false);\n  return <button onClick={() => setOn(o => !o)}>{on ? "ON" : "OFF"}</button>;\n}\n```', opts: ['Always shows ON', 'Toggles the label between ON and OFF', 'Always shows OFF', 'Does nothing'], a: 1, e: 'Each click flips on, switching the label between ON and OFF.', tags: ['Mastery'] },
];

export const roadmapReactQuestions = buildRoadmap('rm-react', 'react', seeds);
