import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Rules & Betting roadmap bank (rm-pkrules-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const rulesFormatsTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-pkrules-1': { introduction: 'Kolik vlastních karet dostane každý hráč.', question: 'Kolik vlastních uzavřených karet dostane každý hráč v Texas Hold\'em?', options: ['Dvě', 'Jednu', 'Tři', 'Čtyři'], explanation: 'Každý hráč dostane dvě lícem dolů otočené karty (hole cards), které může využít jen on.' },
  'rm-pkrules-2': { introduction: 'První společné karty na stole.', question: 'Co je v Texas Hold\'em „flop"?', options: ['První tři společné karty vyložené najednou', 'Jedna karta lícem nahoru', 'Poslední společná karta', 'Vlastní karty hráče'], explanation: 'Flop jsou tři společné karty vyložené lícem nahoru najednou po prvním kole sázek.' },
  'rm-pkrules-3': { introduction: 'V jakém pořadí přicházejí společné karty.', question: 'V jakém pořadí se odkrývají společné karty?', options: ['Flop, turn, river', 'Turn, flop, river', 'River, turn, flop', 'Flop, river, turn'], explanation: 'Společné karty přicházejí jako flop (3 karty), pak turn (1 karta) a nakonec river (1 karta).' },
  'rm-pkrules-4': { introduction: 'Kolik společných karet leží na stole na konci.', question: 'Kolik společných karet je na stole po riveru?', options: ['Pět', 'Tři', 'Čtyři', 'Sedm'], explanation: 'Flop (3), turn (1) a river (1) dávají dohromady pět společných karet.' },
  'rm-pkrules-5': { introduction: 'Poslední společná karta.', question: 'Co je river?', options: ['Pátá a poslední společná karta', 'První společná karta', 'Vlastní karta hráče', 'Sázka ve čtvrtém kole'], explanation: 'River je pátá a poslední společná karta, vyložená před posledním kolem sázek.' },
  'rm-pkrules-6': { introduction: 'Vynucené sázky před rozdáním.', question: 'Jaké vynucené sázky vloží peníze do potu ještě před rozdáním karet?', options: ['Malý a velký blind', 'Pouze jedno ante', 'Nevkládá se nic', 'Podíl vítěze'], explanation: 'V Hold\'em dva hráči vloží malý a velký blind, aby se každou hru hrálo o peníze.' },
  'rm-pkrules-7': { introduction: 'Rozuzlení na konci hry.', question: 'Co je showdown?', options: ['Zbývající hráči ukážou karty a určí se vítěz', 'První rozdání vlastních karet', 'Zamíchání před hrou', 'Okamžik, kdy přijde flop'], explanation: 'Pokud po poslední sázce zůstanou dva či více hráčů, ukážou karty a vyhraje nejlepší kombinace.' },
  'rm-pkrules-8': { introduction: 'Z čeho se skládá výsledná kombinace.', question: 'V Hold\'em se výsledná pětikaretní kombinace tvoří z jakého souboru?', options: ['Ze dvou vlastních a pěti společných karet', 'Jen ze dvou vlastních karet', 'Jen z pěti společných karet', 'Přesně z jedné vlastní karty a stolu'], explanation: 'Každý hráč sestaví nejlepších pět karet ze sedmi dostupných: dvou vlastních a pěti společných.' },

  'rm-pkrules-9': { introduction: 'Sázková akce bez vkladu.', question: 'Co znamená „check" (čekat)?', options: ['Nesázet a zůstat ve hře, pokud není co dorovnávat', 'Dorovnat aktuální sázku', 'Zvýšit aktuální sázku', 'Zahodit karty'], explanation: 'Check přenechá akci dál bez sázky a je možný jen tehdy, když v kole ještě nikdo nevsadil.' },
  'rm-pkrules-10': { introduction: 'Vzdání se hry.', question: 'Co znamená „fold" (složit)?', options: ['Zahodit karty a vzdát se nároku na pot', 'Dorovnat aktuální sázku', 'Zvýšit sázku', 'Checknout na dalšího hráče'], explanation: 'Fold znamená zahodit karty a pot; do dané hry už nevkládáte žádné žetony.' },
  'rm-pkrules-11': { introduction: 'Dorovnání sázky.', question: 'Co znamená „call" (dorovnat)?', options: ['Dorovnat aktuální sázku a zůstat ve hře', 'Zvýšit sázku', 'Nevsadit nic', 'Zahodit karty'], explanation: 'Call znamená dorovnat výši aktuální sázky, abyste pokračovali ve hře.' },
  'rm-pkrules-12': { introduction: 'Zvýšení sázky.', question: 'Co znamená „raise" (zvýšit)?', options: ['Zvýšit aktuální sázku a přinutit ostatní vsadit víc', 'Přesně dorovnat sázku', 'Předat akci dál', 'Vzdát se karet'], explanation: 'Raise zvýší sázku nad současnou úroveň, takže soupeři musí novou částku dorovnat, nebo složit.' },
  'rm-pkrules-13': { introduction: 'Kdy je check povolený.', question: 'Kdy smíte checknout?', options: ['Jen když v daném kole ještě nikdo nevsadil', 'Kdykoli', 'Jen po něčím raisu', 'Jen před flopem'], explanation: 'Check je možný jen tehdy, když k vám akce dorazí bez otevřené sázky; jinak musíte dorovnat, zvýšit, nebo složit.' },
  'rm-pkrules-14': { introduction: 'Počet sázkových kol.', question: 'Kolik sázkových kol má jedna hra Texas Hold\'em?', options: ['Čtyři', 'Dvě', 'Tři', 'Pět'], explanation: 'Sází se preflop, na flopu, na turnu a na riveru — celkem čtyři kola.' },
  'rm-pkrules-15': { introduction: 'První sázkové kolo.', question: 'Jak se nazývá první sázkové kolo, ještě před společnými kartami?', options: ['Preflop', 'Flop', 'Turn', 'Showdown'], explanation: 'Úvodní kolo sázek jen na vlastní karty se nazývá preflop.' },
  'rm-pkrules-16': { introduction: 'Nastražená akce.', question: 'Co je „check-raise"?', options: ['Nejprve checknout a po sázce soupeře zvýšit', 'Zvýšit a hned složit', 'Checknout dvakrát po sobě', 'Dorovnat a znovu dorovnat'], explanation: 'Check-raise je past: nejdřív checknete, a když soupeř vsadí, ve stejném kole zvýšíte.' },

  'rm-pkrules-17': { introduction: 'Značka rozdávajícího.', question: 'Co je v pokeru „button" (tlačítko)?', options: ['Značka určující pozici nominálního rozdávajícího', 'Celkový pot žetonů', 'Druh vynucené sázky', 'Vítězná kombinace'], explanation: 'Button označuje nominálního rozdávajícího; podle něj se určují blindy i pořadí akce.' },
  'rm-pkrules-18': { introduction: 'Kdo vkládá malý blind.', question: 'Kdo vkládá malý blind?', options: ['Hráč hned nalevo od buttonu', 'Hráč na buttonu', 'Hráč na velkém blindu', 'Rozdávající krupiér'], explanation: 'Malý blind vkládá místo přímo nalevo od buttonu a velký blind je nalevo od něj.' },
  'rm-pkrules-19': { introduction: 'Poměr blindů.', question: 'Jak velký je obvykle velký blind vůči malému blindu?', options: ['Dvojnásobek malého blindu', 'Polovina malého blindu', 'Roven malému blindu', 'Desetinásobek malého blindu'], explanation: 'Podle zvyklosti je velký blind dvojnásobkem malého (např. 1 a 2 žetony).' },
  'rm-pkrules-20': { introduction: 'Kdo hraje první před flopem.', question: 'Kdo jedná jako první před flopem?', options: ['Hráč nalevo od velkého blindu („under the gun")', 'Malý blind', 'Button', 'Velký blind'], explanation: 'Akce preflop začíná hráčem nalevo od velkého blindu, kterému se říká under the gun.' },
  'rm-pkrules-21': { introduction: 'Kdo hraje první po flopu.', question: 'Kdo z aktivních hráčů jedná jako první po flopu?', options: ['První aktivní hráč nalevo od buttonu', 'Button', 'Hráč under the gun', 'Vždy velký blind'], explanation: 'Od flopu dál začíná akci první aktivní hráč nalevo od buttonu (obvykle malý blind).' },
  'rm-pkrules-22': { introduction: 'Malá povinná sázka od více hráčů.', question: 'Co je ante?', options: ['Malá vynucená sázka vložená hráči před hrou', 'Raise po riveru', 'Jiný název pro button', 'Zcela dobrovolná bonusová sázka'], explanation: 'Ante je malý povinný vklad, který navyšuje pot, běžný ve vyšších úrovních turnajů.' },
  'rm-pkrules-23': { introduction: 'Pohyb buttonu.', question: 'Kterým směrem se mezi hrami posouvá button?', options: ['O jedno místo po směru hodin, k dalšímu hráči vlevo', 'O jedno místo proti směru hodin', 'Zůstává u stejného hráče', 'Na náhodně vybrané místo'], explanation: 'Button se každou hru posune o jedno místo doleva, aby blindy i rozdávání spravedlivě obíhaly stůl.' },
  'rm-pkrules-24': { introduction: 'Výhoda poslední akce.', question: 'Proč je výhodné být „na buttonu" po flopu?', options: ['Jednáte poslední a vidíte rozhodnutí ostatních', 'Musíte každé kolo sázet', 'Jednáte první v každém kole', 'Nikdy nevkládáte blindy'], explanation: 'Button jedná na každé pofloppové ulici poslední a získává informace od soupeřů dřív, než se rozhodne.' },

  'rm-pkrules-25': { introduction: 'Maximum v no-limit.', question: 'Jaká je v no-limit Hold\'em maximální možná sázka?', options: ['Všechny vaše žetony (all-in)', 'Aktuální velikost potu', 'Dvojnásobek velkého blindu', 'Přesně velký blind'], explanation: 'No-limit znamená, že můžete kdykoli vsadit jakoukoli částku až do výše celého svého stacku.' },
  'rm-pkrules-26': { introduction: 'Nejmenší otevírací sázka.', question: 'Jaká je nejmenší povolená otevírací sázka na flopu, turnu či riveru?', options: ['Alespoň velikost velkého blindu', 'Celá velikost potu', 'Jakákoli částka, i jeden žeton', 'Dvojnásobek potu'], explanation: 'Sázka po flopu musí být alespoň jeden velký blind (pokud hráč nejde all-in za méně).' },
  'rm-pkrules-27': { introduction: 'Minimální raise.', question: 'Jak velký musí být nejmenší povolený raise?', options: ['Alespoň velikost předchozí sázky nebo raisu', 'Dvojnásobek aktuálního potu', 'Vždy jeden velký blind', 'Jediný žeton'], explanation: 'Zvýšit musíte alespoň o tolik, kolik činila poslední sázka či raise, takže raise nemůže být titěrný.' },
  'rm-pkrules-28': { introduction: 'Vsazení celého stacku.', question: 'Co znamená jít „all-in"?', options: ['Vsadit všechny své zbývající žetony', 'Složit karty', 'Dorovnat polovinu sázky', 'Checknout'], explanation: 'All-in vloží do potu celý zbývající stack; vyhrát můžete jen tolik, kolik dokážete dorovnat.' },
  'rm-pkrules-29': { introduction: 'Vznik vedlejšího potu.', question: 'Kdy vzniká vedlejší pot (side pot)?', options: ['Když je hráč all-in a ostatní sázejí dál', 'V každé hře', 'Jen při showdownu', 'Kdykoli někdo složí'], explanation: 'Žetony vsazené nad rámec stacku all-in hráče jdou do samostatného side potu, o který hrají jen aktivní hráči.' },
  'rm-pkrules-30': { introduction: 'Kolik může vyhrát all-in za méně.', question: 'Hráč all-in za méně, než je aktuální sázka, může vyhrát nejvýše co?', options: ['Jen částku, kterou každý soupeř dorovnal (hlavní pot)', 'Celý pot včetně pozdějších sázek', 'Vůbec nic', 'Pouze side pot'], explanation: 'All-in hráč může vyhrát jen tu část potu, do níž přispěl; přebytečné žetony tvoří side pot.' },
  'rm-pkrules-31': { introduction: 'Sázení po all-inu.', question: 'Mohou ostatní hráči sázet dál poté, co jdete all-in?', options: ['Ano, do side potu, který vy vyhrát nemůžete', 'Ne, veškeré sázení hned skončí', 'Jen když nejdřív složí', 'Nikdy podle žádného pravidla'], explanation: 'Hráči, kterým zbývají žetony, mohou dál sázet mezi sebou do side potu, na nějž all-in hráč nemá nárok.' },
  'rm-pkrules-32': { introduction: 'Neúplný raise.', question: 'Může být raise někdy menší než plný povolený raise?', options: ['Ano, když hráč jde all-in za méně než plný raise', 'Ne, raisy jsou vždy plné', 'Jen během preflopu', 'Jen na riveru'], explanation: 'Krátký all-in může být menší než plný raise; takový raise obvykle znovu neotevře sázení hráčům, kteří už jednali.' },

  'rm-pkrules-33': { introduction: 'Žetony v cash hře.', question: 'Co v cash (ring) hře představují žetony?', options: ['Skutečné peníze, které lze kdykoli přikoupit či vybrat', 'Body bez peněžní hodnoty', 'Turnajové pořadí', 'Nic hodnotného'], explanation: 'V cash hře se žetony rovnají skutečným penězům; hráči mohou dokupovat, doplňovat i odejít a vybrat výhru, kdy chtějí.' },
  'rm-pkrules-34': { introduction: 'Vyřazení v turnaji.', question: 'Kdy jste v pokerovém turnaji vyřazeni?', options: ['Když přijdete o všechny žetony', 'Když poprvé složíte', 'Když se zvýší blindy', 'Když na chvíli odejdete od stolu'], explanation: 'Hráči turnaje začínají s pevným stackem a jsou vyřazeni, jakmile jim dojdou žetony.' },
  'rm-pkrules-35': { introduction: 'Čím se turnaj liší.', question: 'Charakteristickým rysem turnajů oproti cash hrám je, že se v čase...', options: ['Blindy (a antes) v pravidelných intervalech zvyšují', 'Blindy zůstávají navždy stejné', 'Vůbec nehrají žádné blindy', 'Každou úroveň se mění balíček'], explanation: 'Turnajové blindy rostou podle rozpisu a postupně zvyšují tlak a nutí k akci.' },
  'rm-pkrules-36': { introduction: 'Rozsah sázek v no-limit.', question: 'Kolik smíte vsadit v no-limit sázení?', options: ['Jakoukoli částku až do výše celého stacku', 'Jen pevně dané částky', 'Jen velikost potu', 'Jen jeden velký blind'], explanation: 'No-limit umožňuje vsadit nebo zvýšit cokoli od minima až po všechny své žetony.' },
  'rm-pkrules-37': { introduction: 'Sázky ve fixed-limit.', question: 'Ve fixed-limit Hold\'em jsou sázky a raisy...', options: ['Pevně předem dané částky pro každé kolo', 'Neomezené až do výše stacku', 'Vždy velikosti potu', 'Volně volené sázejícím'], explanation: 'Limit poker omezuje každou sázku i raise na pevné částky, na rozdíl od volného sázení v no-limit.' },
  'rm-pkrules-38': { introduction: 'Maximum v pot-limit.', question: 'V pot-limit hře je maximální sázka...', options: ['Aktuální velikost potu', 'Vždy celý váš stack', 'Jeden velký blind', 'Dvojnásobek potu'], explanation: 'Pot-limit omezuje každou sázku či raise na částku aktuálně v potu, tedy mezi limitem a no-limitem.' },
  'rm-pkrules-39': { introduction: 'Odlišnosti Omahy.', question: 'Čím se Omaha liší od Texas Hold\'em?', options: ['Hráči dostanou čtyři vlastní karty a musí použít přesně dvě', 'Rozdává šest společných karet', 'Nemá žádné společné karty', 'Rozdává pět vlastních karet'], explanation: 'V Omaze dostane každý hráč čtyři vlastní karty a musí použít přesně dvě z nich se třemi společnými.' },
  'rm-pkrules-40': { introduction: 'Odlišnosti Seven-Card Stud.', question: 'Čím se Seven-Card Stud liší od Hold\'em?', options: ['Nemá žádné společné karty ani flop', 'Používá společný flop', 'Rozdává jen dvě karty na hráče', 'Je vždy no-limit'], explanation: 'Seven-Card Stud rozdává každému hráči vlastní otevřené i zavřené karty bez společného stolu a používá antes a bring-in.' },
};
