import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Chess History & Champions roadmap bank (rm-chesshist-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const chessHistoryTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-chesshist-1': { introduction: 'Zamysli se, kde vznikla hra předcházející šachům.', question: 'Ve které zemi šachy nejpravděpodobněji vznikly?', options: ['Indie', 'Čína', 'Egypt', 'Řecko'], explanation: 'Šachy sahají do Indie, kde se jejich předchůdce čaturanga hrál už kolem 6. století.' },
  'rm-chesshist-2': { introduction: 'Název znamená „čtyři oddíly" vojska.', question: 'Jak se jmenovala stará indická hra považovaná za předchůdce šachů?', options: ['Čaturanga', 'Senet', 'Go', 'Vrhcáby'], explanation: 'Čaturanga, tedy „čtyři oddíly" armády, je nejstarší známý předchůdce šachů.' },
  'rm-chesshist-3': { introduction: 'Odsud se hra šířila přes islámský svět.', question: 'Do které říše se šachy z Indie rozšířily a kde dostaly jméno šatrandž?', options: ['Persie', 'Řím', 'Japonsko', 'Mongolsko'], explanation: 'Šachy dorazily do Persie, kde se nazývaly šatrandž, a odtud se šířily islámským světem.' },
  'rm-chesshist-4': { introduction: 'Perský původ slova „mat".', question: 'Slovo „šach mat" pochází z perského „šáh mát", což zhruba znamená co?', options: ['Král je bezmocný', 'Dáma je ztracena', 'Hra je vyrovnaná', 'Šachovnice je plná'], explanation: '„Šáh mát" znamená, že král je bezmocný či poražený, odtud pochází slovo šachmat.' },
  'rm-chesshist-5': { introduction: 'Čtyři druhy vojska staré Indie.', question: 'Čtyřmi oddíly vojska v čaturanze byla pěchota, jízda, sloni a co ještě?', options: ['Vozy', 'Lučištníci', 'Lodě', 'Katapulty'], explanation: 'Čtyřmi složkami čaturangy byly pěchota, jízda, sloni a bojové vozy, z nichž vznikly dnešní figury.' },
  'rm-chesshist-6': { introduction: 'Klíčovou roli sehrálo maurské Španělsko.', question: 'Kudy se šachy převážně dostaly do středověké Evropy?', options: ['Přes islámský svět a maurské Španělsko', 'Přes Vikingy', 'Ze starověkého Říma', 'Hedvábnou stezkou do Skandinávie'], explanation: 'Šachy se do Evropy rozšířily hlavně přes islámský svět, zejména maurské Španělsko, do 10. století.' },
  'rm-chesshist-7': { introduction: 'Stará dáma byla mnohem slabší než dnes.', question: 'Jak daleko se ve starých šachách mohla pohybovat figura, z níž vznikla dáma (tzv. „ferz")?', options: ['Jen o jedno pole diagonálně', 'Libovolně daleko diagonálně', 'Jako dnešní věž', 'Jako dnešní jezdec'], explanation: 'Stará dáma (ferz) byla slabá a táhla jen o jedno pole diagonálně, na rozdíl od dnešní mocné dámy.' },
  'rm-chesshist-8': { introduction: 'Moderní pravidla vznikla v renesanci.', question: 'Ve které oblasti kolem roku 1475 vznikla moderní silná dáma a dalekonosný střelec?', options: ['Evropa', 'Indie', 'Persie', 'Čína'], explanation: 'Moderní pravidla včetně silné dámy se ustálila v Evropě (Španělsku a Itálii) kolem roku 1475.' },

  'rm-chesshist-9': { introduction: 'Styl 19. století plný odvahy.', question: 'Jaký styl hry zdůrazňovala romantická éra šachů v 19. století?', options: ['Odvážné útoky a oběti', 'Pomalou obrannou hru', 'Vyhýbání se všem výměnám', 'Rychlé remízy'], explanation: 'Romantické šachy oceňovaly smělé útoky, gambity a efektní oběti více než opatrnou obranu.' },
  'rm-chesshist-10': { introduction: 'Slavná partie z roku 1851 plná obětí.', question: 'Kdo v roce 1851 vyhrál oslnivými oběťmi proslulou „Nesmrtelnou partii"?', options: ['Adolf Anderssen', 'Paul Morphy', 'Wilhelm Steinitz', 'Emanuel Lasker'], explanation: 'Adolf Anderssen porazil Lionela Kieseritzkého v roce 1851 s mnoha oběťmi v proslulé Nesmrtelné partii.' },
  'rm-chesshist-11': { introduction: 'Americký zázrak z poloviny 19. století.', question: 'Ve kterém desetiletí ovládal světové šachy americký zázrak Paul Morphy?', options: ['V 50. letech 19. století', 'V 90. letech 18. století', 'V prvním desetiletí 20. století', 'Ve 30. letech 20. století'], explanation: 'Paul Morphy porazil nejlepší evropské hráče v 50. letech 19. století a je považován za nejlepšího své doby.' },
  'rm-chesshist-12': { introduction: 'Partie se hrála v operní lóži.', question: 'Morphyho slavná „Operní partie" z roku 1858 se hrála v opeře v kterém městě?', options: ['Paříž', 'Londýn', 'Vídeň', 'New York'], explanation: 'Morphy sehrál skvělou Operní partii v Paříži roku 1858 proti dvěma spojeným šlechtickým soupeřům.' },
  'rm-chesshist-13': { introduction: 'První oficiální titul padl roku 1886.', question: 'Kdo je uznáván jako první oficiální mistr světa v šachu, od roku 1886?', options: ['Wilhelm Steinitz', 'Paul Morphy', 'Emanuel Lasker', 'Adolf Anderssen'], explanation: 'Wilhelm Steinitz vyhrál první oficiální zápas o mistrovství světa v roce 1886 a stal se prvním šampionem.' },
  'rm-chesshist-14': { introduction: 'Přinesl vědecký přístup ke hře.', question: 'Kterému přístupu k šachu se připisuje průkopnictví Wilhelma Steinitze?', options: ['Poziční (vědecké) hře', 'Čistě útočným šachům', 'Hře naslepo', 'Bleskovým šachům'], explanation: 'Steinitz založil poziční školu, která zdůrazňovala pevnou strukturu a zásady místo bezhlavých útoků.' },
  'rm-chesshist-15': { introduction: 'Rekordně dlouhá vláda na trůnu.', question: 'Emanuel Lasker vytvořil rekord tím, že držel titul mistra světa jak dlouho?', options: ['27 let', '5 let', '15 let', '40 let'], explanation: 'Lasker vládl od roku 1894 do 1921, tedy rekordních 27 let jako mistr světa.' },
  'rm-chesshist-16': { introduction: 'Byl také matematikem.', question: 'Jaké národnosti byl mistr světa Emanuel Lasker?', options: ['Německé', 'Ruské', 'Americké', 'Francouzské'], explanation: 'Emanuel Lasker byl německý šachový velmistr a matematik, který držel titul 27 let.' },

  'rm-chesshist-17': { introduction: 'Mistr koncovek z ostrova.', question: 'Z které země pocházel mistr světa José Raúl Capablanca, proslulý koncovkami?', options: ['Kuba', 'Španělsko', 'Argentina', 'Mexiko'], explanation: 'Capablanca z Kuby byl proslulý svou zdánlivě samozřejmou a přesnou technikou koncovek.' },
  'rm-chesshist-18': { introduction: 'Sesadil dlouholetého šampiona.', question: 'Porážkou kterého dlouho vládnoucího šampiona získal Capablanca v roce 1921 titul?', options: ['Emanuel Lasker', 'Wilhelm Steinitz', 'Alexander Aljechin', 'Michail Botvinnik'], explanation: 'Capablanca porazil Emanuela Laskera v roce 1921 a stal se třetím mistrem světa.' },
  'rm-chesshist-19': { introduction: 'Rok 1927 znamenal změnu na trůnu.', question: 'Kdo porazil Capablancu v roce 1927 a stal se mistrem světa?', options: ['Alexander Aljechin', 'Max Euwe', 'Michail Botvinnik', 'Emanuel Lasker'], explanation: 'Alexander Aljechin porazil Capablancu v dlouhém zápase roku 1927 a nikdy mu nepovolil odvetu.' },
  'rm-chesshist-20': { introduction: 'Smutná jedinečnost mezi šampiony.', question: 'Kterým jedinečným prvenstvím se Alexander Aljechin liší od ostatních mistrů světa?', options: ['Zemřel jako držitel titulu', 'Nikdy neprohrál partii', 'Byl nejmladším šampionem', 'Vyhrál bez zápasu'], explanation: 'Aljechin je jediný šampion, který zemřel jako držitel titulu; zesnul v roce 1946.' },
  'rm-chesshist-21': { introduction: 'Zakladatelská postava sovětské tradice.', question: 'Michail Botvinnik bývá nazýván patriarchou které šachové tradice?', options: ['Sovětské školy', 'Romantické školy', 'Italské školy', 'Hypermoderní školy'], explanation: 'Botvinnik vedl dominantní sovětskou šachovou školu a formoval její důsledné tréninkové metody.' },
  'rm-chesshist-22': { introduction: 'Z jeho školy vzešli budoucí šampioni.', question: 'Botvinnik vedl slavnou šachovou školu, jež vychovala budoucí šampiony včetně koho?', options: ['Karpova a Kasparova', 'Fischera a Morphyho', 'Steinitze a Laskera', 'Capablanky a Aljechina'], explanation: 'Botvinnikova škola pomohla vychovat pozdější mistry světa Anatolije Karpova a Garriho Kasparova.' },
  'rm-chesshist-23': { introduction: 'Mezinárodní šachová federace.', question: 'Ve kterém roce byla založena FIDE, mezinárodní šachová federace?', options: ['1924', '1886', '1948', '1972'], explanation: 'FIDE, Mezinárodní šachová federace (Fédération Internationale des Échecs), byla založena v Paříži roku 1924.' },
  'rm-chesshist-24': { introduction: 'Po Aljechinově smrti zůstal titul volný.', question: 'Po Aljechinově smrti uspořádala FIDE v roce 1948 turnaj o nového šampiona; kdo jej vyhrál?', options: ['Michail Botvinnik', 'Vasilij Smyslov', 'Paul Keres', 'Max Euwe'], explanation: 'Botvinnik vyhrál zápas-turnaj roku 1948, získal uvolněný titul a zahájil sovětskou nadvládu.' },

  'rm-chesshist-25': { introduction: 'Studená válka u šachovnice.', question: 'Bobby Fischer získal titul mistra světa roku 1972 porážkou kterého sovětského šampiona?', options: ['Boris Spasskij', 'Anatolij Karpov', 'Michail Tal', 'Tigran Petrosjan'], explanation: 'Fischer porazil Borise Spasského v roce 1972 a stal se prvním nesporným šampionem narozeným v USA.' },
  'rm-chesshist-26': { introduction: '„Zápas století" na severu.', question: 'Ve kterém městě se konal zápas Fischer–Spasskij z roku 1972 zvaný „zápas století"?', options: ['Reykjavík', 'Moskva', 'New York', 'Bělehrad'], explanation: 'Zápas z roku 1972, nabitý atmosférou studené války, se odehrál v islandském Reykjavíku.' },
  'rm-chesshist-27': { introduction: 'Netradiční způsob zisku titulu.', question: 'Jak se Anatolij Karpov stal v roce 1975 mistrem světa?', options: ['Fischer odmítl titul obhajovat', 'Vyhrál zápas s Fischerem', 'Botvinnik odstoupil', 'Vyhrál turnaj'], explanation: 'Fischer odmítl hrát za dohodnutých podmínek, a tak byl titul roku 1975 přiznán Karpovovi.' },
  'rm-chesshist-28': { introduction: 'Narodil se v Chicagu.', question: 'Jaké národnosti byl Bobby Fischer?', options: ['Americké', 'Ruské', 'Německé', 'Islandské'], explanation: 'Bobby Fischer byl americký velmistr, narozený v Chicagu v roce 1943.' },
  'rm-chesshist-29': { introduction: 'Zápas, který nikdo nedohrál.', question: 'Jak neobvykle skončil první zápas Karpov–Kasparov (1984–85)?', options: ['Byl přerušen bez vítěze', 'Skončil rychlou remízou', 'Karpov se titulu vzdal', 'Kasparov odstoupil'], explanation: 'Po pěti měsících a 48 partiích FIDE kontroverzně přerušila zápas 1984–85 bez výsledku.' },
  'rm-chesshist-30': { introduction: 'Nejmladší nesporný šampion své doby.', question: 'V roce 1985 se Garri Kasparov stal nejmladším nesporným mistrem světa v jakém věku?', options: ['22 let', '18 let', '28 let', '35 let'], explanation: 'Kasparov porazil Karpova v roce 1985 ve 22 letech, tehdy rekordně mladý nesporný šampion.' },
  'rm-chesshist-31': { introduction: 'Rodné město v tehdejším SSSR.', question: 'Ve kterém městě, tehdy součásti Sovětského svazu, se narodil Garri Kasparov?', options: ['Baku', 'Moskva', 'Kyjev', 'Leningrad'], explanation: 'Kasparov se narodil v Baku v sovětském Ázerbájdžánu v roce 1963.' },
  'rm-chesshist-32': { introduction: 'Vzpoura proti FIDE.', question: 'V roce 1993 se Kasparov odtrhl od FIDE a spoluzaložil kterou konkurenční organizaci?', options: ['Profesionální šachovou asociaci', 'Světovou šachovou ligu', 'Unii velmistrů', 'Elo federaci'], explanation: 'Kasparov a Nigel Short se roku 1993 odtrhli od FIDE a založili Profesionální šachovou asociaci (PCA).' },

  'rm-chesshist-33': { introduction: 'Šampion ze severské země.', question: 'Jaké národnosti je Magnus Carlsen, mistr světa v letech 2013 až 2023?', options: ['Norské', 'Švédské', 'Dánské', 'Nizozemské'], explanation: 'Magnus Carlsen z Norska ovládl šachový svět a držel klasický titul v letech 2013–2023.' },
  'rm-chesshist-34': { introduction: 'Porazil indického šampiona.', question: 'Carlsen získal titul mistra světa v roce 2013 porážkou kterého dlouholetého šampiona?', options: ['Viswanathan Anand', 'Vladimir Kramnik', 'Veselin Topalov', 'Boris Gelfand'], explanation: 'Carlsen porazil indického šampiona Viswanathana Ananda v roce 2013 a získal titul mistra světa.' },
  'rm-chesshist-35': { introduction: 'Nejvyšší rating v historii.', question: 'Magnus Carlsen vytvořil rekord v nejvyšším ratingu, když překonal jakou hodnotu Elo?', options: ['2882', '2600', '2700', '3100'], explanation: 'Carlsen dosáhl v roce 2014 vrcholného ratingu 2882, nejvyššího oficiálně zaznamenaného.' },
  'rm-chesshist-36': { introduction: 'Historický souboj člověka a stroje.', question: 'Který počítač firmy IBM porazil v roce 1997 mistra světa Garriho Kasparova v zápase?', options: ['Deep Blue', 'Watson', 'Deep Thought', 'Big Blue'], explanation: 'Deep Blue od IBM porazil Kasparova v roce 1997, první prohru šampiona s počítačem v zápase.' },
  'rm-chesshist-37': { introduction: 'Nejsilnější šachistka historie.', question: 'Ze které země pochází Judit Polgárová, považovaná za nejsilnější šachistku všech dob?', options: ['Maďarsko', 'Rusko', 'Polsko', 'Gruzie'], explanation: 'Judit Polgárová z Maďarska se probojovala do světové desítky, což žádná jiná žena nedokázala.' },
  'rm-chesshist-38': { introduction: 'První ženská mistryně světa.', question: 'Ve kterém roce se Věra Menčíková stala první mistryní světa v šachu žen?', options: ['1927', '1950', '1972', '1901'], explanation: 'Věra Menčíková vyhrála první mistrovství světa žen v roce 1927 a ženským šachům dlouho vládla.' },
  'rm-chesshist-39': { introduction: 'Stroj, který se učil sám.', question: 'Engine AlphaZero, který se šachy naučil hrou sám proti sobě, vyvinula která společnost?', options: ['DeepMind', 'IBM', 'Microsoft', 'Intel'], explanation: 'AlphaZero od Googlího DeepMind se naučil šachy od nuly hraním milionů partií sám proti sobě.' },
  'rm-chesshist-40': { introduction: 'Volně dostupný a velmi silný.', question: 'Který open-source engine se v moderní éře stal jedním z nejsilnějších na světě?', options: ['Stockfish', 'Fritz', 'Rybka', 'ChessMaster'], explanation: 'Stockfish, volně dostupný open-source engine, patří k nejsilnějším šachovým programům všech dob.' },
};
