import type { QuestionTranslation } from './quiz-data';

export const capitalsTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Evropská hlavní města ──
  'rm-cap-1': { introduction: 'Největší město Francie na řece Seině.', question: 'Jaké je hlavní město Francie?', options: ['Paříž', 'Lyon', 'Marseille', 'Nice'], explanation: 'Paříž je hlavním městem Francie od středověku a je jejím největším městem.' },
  'rm-cap-2': { introduction: 'Metropole na řece Temži.', question: 'Jaké je hlavní město Spojeného království?', options: ['Birmingham', 'Manchester', 'Londýn', 'Liverpool'], explanation: 'Londýn na řece Temži je hlavním a největším městem Spojeného království.' },
  'rm-cap-3': { introduction: 'Věčné město a srdce bývalého impéria.', question: 'Jaké je hlavní město Itálie?', options: ['Milán', 'Řím', 'Neapol', 'Turín'], explanation: 'Řím, kdysi srdce Římské říše, je hlavním městem Itálie od roku 1871.' },
  'rm-cap-4': { introduction: 'Leží ve středu země.', question: 'Jaké je hlavní město Španělska?', options: ['Barcelona', 'Valencie', 'Sevilla', 'Madrid'], explanation: 'Madrid ve středu země je hlavním a největším městem Španělska.' },
  'rm-cap-5': { introduction: 'Znovu se stalo hlavním městem po roce 1990.', question: 'Jaké je hlavní město Německa?', options: ['Berlín', 'Mnichov', 'Hamburk', 'Frankfurt'], explanation: 'Berlín se stal hlavním městem znovusjednoceného Německa v roce 1990 a je jeho největším městem.' },
  'rm-cap-6': { introduction: 'Přístav na atlantském pobřeží.', question: 'Jaké je hlavní město Portugalska?', options: ['Porto', 'Braga', 'Coimbra', 'Lisabon'], explanation: 'Lisabon na atlantském pobřeží je hlavním a největším městem Portugalska.' },
  'rm-cap-7': { introduction: 'Jedno z nejstarších měst na světě.', question: 'Jaké je hlavní město Řecka?', options: ['Soluň', 'Patras', 'Atény', 'Heraklion'], explanation: 'Atény jsou jedním z nejstarších měst na světě a hlavním městem Řecka.' },
  'rm-cap-8': { introduction: 'Ústavní hlavní město, i když vláda sídlí jinde.', question: 'Jaké je hlavní město Nizozemska?', options: ['Rotterdam', 'Amsterdam', 'Haag', 'Utrecht'], explanation: 'Amsterdam je ústavním hlavním městem Nizozemska, ačkoliv vláda sídlí v Haagu.' },

  // ── Úroveň 2 — Asijská hlavní města ──
  'rm-cap-9': { introduction: 'Hlavní město od roku 1868.', question: 'Jaké je hlavní město Japonska?', options: ['Ósaka', 'Tokio', 'Kjóto', 'Jokohama'], explanation: 'Tokio je hlavním městem Japonska od roku 1868, kdy se sem císař přestěhoval z Kjóta.' },
  'rm-cap-10': { introduction: 'Pozor: největší město je jiné než hlavní.', question: 'Jaké je hlavní město Číny?', options: ['Šanghaj', 'Kanton', 'Šen-čen', 'Peking'], explanation: 'Peking je hlavním městem Číny, zatímco Šanghaj je největším městem podle počtu obyvatel.' },
  'rm-cap-11': { introduction: 'Leží uvnitř většího města Dillí.', question: 'Jaké je hlavní město Indie?', options: ['Nové Dillí', 'Bombaj', 'Kalkata', 'Bengalúru'], explanation: 'Nové Dillí, v rámci většího města Dillí, je hlavním městem Indie a sídlem vlády.' },
  'rm-cap-12': { introduction: 'Metropole na řece Han.', question: 'Jaké je hlavní město Jižní Koreje?', options: ['Pusan', 'Inčchon', 'Soul', 'Tegu'], explanation: 'Soul na řece Han je hlavním a zdaleka největším městem Jižní Koreje.' },
  'rm-cap-13': { introduction: 'Největší město země, oblíbená turistická destinace.', question: 'Jaké je hlavní město Thajska?', options: ['Čiang Mai', 'Phuket', 'Pattaya', 'Bangkok'], explanation: 'Bangkok je hlavním a největším městem Thajska.' },
  'rm-cap-14': { introduction: 'Pozor: největší město je bývalý Saigon.', question: 'Jaké je hlavní město Vietnamu?', options: ['Ho Či Minovo Město', 'Hanoj', 'Da Nang', 'Hue'], explanation: 'Hanoj je hlavním městem Vietnamu, zatímco Ho Či Minovo Město (dříve Saigon) je největší.' },
  'rm-cap-15': { introduction: 'Metropole na ostrově Jáva.', question: 'Jaké je hlavní město Indonésie?', options: ['Surabaya', 'Bandung', 'Jakarta', 'Medan'], explanation: 'Jakarta na ostrově Jáva je hlavním a největším městem Indonésie.' },
  'rm-cap-16': { introduction: 'Nedaleké město bylo hlavním v letech 1948–1976.', question: 'Jaké je hlavní město Filipín?', options: ['Manila', 'Cebu', 'Davao', 'Quezon City'], explanation: 'Manila je hlavním městem Filipín; nedaleké Quezon City tuto roli zastávalo v letech 1948 až 1976.' },

  // ── Úroveň 3 — Africká hlavní města ──
  'rm-cap-17': { introduction: 'Metropole na Nilu.', question: 'Jaké je hlavní město Egypta?', options: ['Alexandrie', 'Gíza', 'Káhira', 'Luxor'], explanation: 'Káhira na Nilu je hlavním a největším městem Egypta.' },
  'rm-cap-18': { introduction: 'Největší město země ve východní Africe.', question: 'Jaké je hlavní město Keni?', options: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'], explanation: 'Nairobi je hlavním a největším městem Keni.' },
  'rm-cap-19': { introduction: 'Pozor: největší město je Casablanca.', question: 'Jaké je hlavní město Maroka?', options: ['Casablanca', 'Marrákeš', 'Fez', 'Rabat'], explanation: 'Rabat je hlavním městem Maroka, zatímco Casablanca je jeho největším městem.' },
  'rm-cap-20': { introduction: 'Nahradilo Lagos v roce 1991.', question: 'Jaké je hlavní město Nigérie?', options: ['Lagos', 'Abuja', 'Kano', 'Ibadan'], explanation: 'Abuja se stala hlavním městem Nigérie v roce 1991 a nahradila mnohem větší Lagos.' },
  'rm-cap-21': { introduction: 'Země má hned tři hlavní města; tohle je správní.', question: 'Jaké je správní hlavní město Jihoafrické republiky?', options: ['Pretoria', 'Kapské Město', 'Johannesburg', 'Durban'], explanation: 'Pretoria je správním hlavním městem Jihoafrické republiky, která má jedinečně tři hlavní města.' },
  'rm-cap-22': { introduction: 'Sídlí zde Africká unie.', question: 'Jaké je hlavní město Etiopie?', options: ['Dire Dawa', 'Mekele', 'Addis Abeba', 'Gondar'], explanation: 'Addis Abeba je hlavním městem Etiopie a sídlí zde ústředí Africké unie.' },
  'rm-cap-23': { introduction: 'Přístav v Guinejském zálivu.', question: 'Jaké je hlavní město Ghany?', options: ['Kumasi', 'Akkra', 'Tamale', 'Takoradi'], explanation: 'Akkra v Guinejském zálivu je hlavním a největším městem Ghany.' },
  'rm-cap-24': { introduction: 'Pozor: největší město je Dar es Salaam.', question: 'Jaké je hlavní město Tanzanie?', options: ['Dar es Salaam', 'Arusha', 'Mwanza', 'Dodoma'], explanation: 'Dodoma je oficiálním hlavním městem Tanzanie, ačkoliv Dar es Salaam zůstává největším městem.' },

  // ── Úroveň 4 — Hlavní města Ameriky ──
  'rm-cap-25': { introduction: 'Zvláštní distrikt, který není součástí žádného státu.', question: 'Jaké je hlavní město Spojených států?', options: ['New York', 'Los Angeles', 'Chicago', 'Washington, D.C.'], explanation: 'Washington, D.C. je hlavním městem Spojených států, distrikt, který není součástí žádného státu.' },
  'rm-cap-26': { introduction: 'Vybrala je královna Viktorie v roce 1857.', question: 'Jaké je hlavní město Kanady?', options: ['Toronto', 'Ottawa', 'Montreal', 'Vancouver'], explanation: 'Ottawa v provincii Ontario je hlavním městem Kanady, které vybrala královna Viktorie v roce 1857.' },
  'rm-cap-27': { introduction: 'Postaveno na místě aztéckého Tenochtitlánu.', question: 'Jaké je hlavní město Mexika?', options: ['Guadalajara', 'Monterrey', 'Ciudad de México', 'Puebla'], explanation: 'Ciudad de México, postavené na místě aztéckého Tenochtitlánu, je hlavním a největším městem Mexika.' },
  'rm-cap-28': { introduction: 'Účelově postavené město z roku 1960.', question: 'Jaké je hlavní město Brazílie?', options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'], explanation: 'Brasília byla účelově postavena a stala se hlavním městem Brazílie v roce 1960, kdy nahradila Rio de Janeiro.' },
  'rm-cap-29': { introduction: 'Metropole na řece La Plata.', question: 'Jaké je hlavní město Argentiny?', options: ['Córdoba', 'Buenos Aires', 'Rosario', 'Mendoza'], explanation: 'Buenos Aires na řece La Plata je hlavním a největším městem Argentiny.' },
  'rm-cap-30': { introduction: 'Založeno Španěly v roce 1535.', question: 'Jaké je hlavní město Peru?', options: ['Cusco', 'Arequipa', 'Trujillo', 'Lima'], explanation: 'Lima, založená Španěly v roce 1535, je hlavním a největším městem Peru.' },
  'rm-cap-31': { introduction: 'Leží vysoko v Andách.', question: 'Jaké je hlavní město Kolumbie?', options: ['Bogotá', 'Medellín', 'Cali', 'Cartagena'], explanation: 'Bogotá, vysoko v Andách, je hlavním a největším městem Kolumbie.' },
  'rm-cap-32': { introduction: 'Parlament sídlí v nedalekém Valparaísu.', question: 'Jaké je hlavní město Chile?', options: ['Valparaíso', 'Concepción', 'Santiago', 'Antofagasta'], explanation: 'Santiago je hlavním městem Chile, zatímco Národní kongres sídlí v nedalekém Valparaísu.' },

  // ── Úroveň 5 — Hlavní města Oceánie a ostrovů ──
  'rm-cap-33': { introduction: 'Kompromis mezi Sydney a Melbourne.', question: 'Jaké je hlavní město Austrálie?', options: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'], explanation: 'Canberra byla účelově postavena jako kompromis mezi soupeřícími Sydney a Melbourne.' },
  'rm-cap-34': { introduction: 'Pozor: největší město je Auckland.', question: 'Jaké je hlavní město Nového Zélandu?', options: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'], explanation: 'Wellington je hlavním městem Nového Zélandu, zatímco Auckland je jeho největším městem.' },
  'rm-cap-35': { introduction: 'Leží na ostrově Viti Levu.', question: 'Jaké je hlavní město Fidži?', options: ['Nadi', 'Lautoka', 'Labasa', 'Suva'], explanation: 'Suva na ostrově Viti Levu je hlavním a největším městem Fidži.' },
  'rm-cap-36': { introduction: 'Založeno Španěly v roce 1519.', question: 'Jaké je hlavní město Kuby?', options: ['Santiago de Cuba', 'Camagüey', 'Havana', 'Holguín'], explanation: 'Havana je hlavním a největším městem Kuby, založeným Španěly v roce 1519.' },
  'rm-cap-37': { introduction: 'Koloniálním hlavním městem byl Spanish Town.', question: 'Jaké je hlavní město Jamajky?', options: ['Montego Bay', 'Spanish Town', 'Kingston', 'Portmore'], explanation: 'Kingston je hlavním a největším městem Jamajky; Spanish Town bylo koloniálním hlavním městem.' },
  'rm-cap-38': { introduction: 'Nejseverněji položené hlavní město svrchovaného státu.', question: 'Jaké je hlavní město Islandu?', options: ['Reykjavík', 'Akureyri', 'Kópavogur', 'Hafnarfjörður'], explanation: 'Reykjavík je nejseverněji položeným hlavním městem svrchovaného státu na světě.' },
  'rm-cap-39': { introduction: 'Přístav v Papuánském zálivu.', question: 'Jaké je hlavní město Papuy-Nové Guineje?', options: ['Lae', 'Mount Hagen', 'Madang', 'Port Moresby'], explanation: 'Port Moresby v Papuánském zálivu je hlavním a největším městem Papuy-Nové Guineje.' },
  'rm-cap-40': { introduction: 'Jedno z nejhustěji zalidněných hlavních měst.', question: 'Jaké je hlavní město Malediv?', options: ['Hulhumalé', 'Malé', 'Addu City', 'Fuvahmulah'], explanation: 'Malé je jedním z nejhustěji zalidněných hlavních měst na světě, natěsnaným na malém ostrově.' },

  // ── Úroveň 6 — Hlavní města velkých zemí ──
  'rm-cap-41': { introduction: 'Petrohrad byl hlavním městem v letech 1712–1918.', question: 'Jaké je hlavní město Ruska, rozlohou největší země světa?', options: ['Petrohrad', 'Moskva', 'Novosibirsk', 'Jekatěrinburg'], explanation: 'Moskva je hlavním městem Ruska; Petrohrad byl hlavním městem v letech 1712 až 1918.' },
  'rm-cap-42': { introduction: 'Krátce se jmenovalo Nur-Sultan.', question: 'Jaké je hlavní město Kazachstánu, největší vnitrozemské země?', options: ['Almaty', 'Šymkent', 'Astana', 'Karaganda'], explanation: 'Astana se stala hlavním městem v roce 1997 a krátce se jmenovala Nur-Sultan, než se v roce 2022 vrátila k původnímu názvu.' },
  'rm-cap-43': { introduction: 'Přístav na pobřeží Středozemního moře.', question: 'Jaké je hlavní město Alžírska, rozlohou největší země Afriky?', options: ['Alžír', 'Oran', 'Constantine', 'Annaba'], explanation: 'Alžír na pobřeží Středozemního moře je hlavním a největším městem Alžírska.' },
  'rm-cap-44': { introduction: 'Přes řeku leží Brazzaville — nejbližší dvojice hlavních měst.', question: 'Jaké je hlavní město Demokratické republiky Kongo?', options: ['Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Kinshasa'], explanation: 'Kinshasa leží přes řeku Kongo od Brazzaville, což je nejbližší dvojice hlavních měst na světě.' },
  'rm-cap-45': { introduction: 'Leží ve středu Arabského poloostrova.', question: 'Jaké je hlavní město Saúdské Arábie?', options: ['Džidda', 'Mekka', 'Medina', 'Rijád'], explanation: 'Rijád ve středu Arabského poloostrova je hlavním a největším městem Saúdské Arábie.' },
  'rm-cap-46': { introduction: 'Leží u soutoku Modrého a Bílého Nilu.', question: 'Jaké je hlavní město Súdánu?', options: ['Omdurman', 'Chartúm', 'Port Sudan', 'Nyala'], explanation: 'Chartúm leží tam, kde se Modrý Nil a Bílý Nil setkávají a vytvářejí hlavní tok Nilu.' },
  'rm-cap-47': { introduction: 'Leží na úpatí pohoří Alborz.', question: 'Jaké je hlavní město Íránu?', options: ['Mašhad', 'Isfahán', 'Teherán', 'Šíráz'], explanation: 'Teherán na úpatí pohoří Alborz je hlavním a největším městem Íránu.' },
  'rm-cap-48': { introduction: 'Účelově postaveno v 60. letech místo Karáčí.', question: 'Jaké je hlavní město Pákistánu?', options: ['Islámábád', 'Karáčí', 'Láhaur', 'Faisalábád'], explanation: 'Islámábád byl účelově postaven v 60. letech, aby nahradil Karáčí jako hlavní město Pákistánu.' },

  // ── Úroveň 7 — Záludná hlavní města ──
  'rm-cap-49': { introduction: 'Pozor: největší město je Istanbul.', question: 'Jaké je hlavní město Turecka?', options: ['Istanbul', 'Izmir', 'Ankara', 'Antalya'], explanation: 'Ankara se stala hlavním městem v roce 1923 a nahradila Istanbul, který zůstává největším městem.' },
  'rm-cap-50': { introduction: 'Sídlo vlády, i když největší město je Curych.', question: 'Jaké je hlavní město Švýcarska?', options: ['Curych', 'Ženeva', 'Basilej', 'Bern'], explanation: 'Bern je sídlem vlády Švýcarska, zatímco Curych je největším městem.' },
  'rm-cap-51': { introduction: 'Vybudováno ve vnitrozemí, hlavním městem od roku 2006.', question: 'Jaké je hlavní město Myanmaru?', options: ['Rangún', 'Neipyijto', 'Mandalay', 'Bagan'], explanation: 'Neipyijto bylo vybudováno ve vnitrozemí a stalo se hlavním městem v roce 2006, když nahradilo Rangún.' },
  'rm-cap-52': { introduction: 'Oficiálním hlavním městem od roku 1983.', question: 'Jaké je oficiální hlavní město Pobřeží slonoviny?', options: ['Yamoussoukro', 'Abidžan', 'Bouaké', 'San-Pédro'], explanation: 'Yamoussoukro se stalo oficiálním hlavním městem v roce 1983, ačkoliv Abidžan zůstává ekonomickým centrem.' },
  'rm-cap-53': { introduction: 'Ústavní hlavní město; vláda sídlí v La Paz.', question: 'Jaké je ústavní hlavní město Bolívie?', options: ['Sucre', 'La Paz', 'Santa Cruz', 'Cochabamba'], explanation: 'Sucre je ústavním hlavním městem Bolívie, zatímco La Paz je sídlem vlády.' },
  'rm-cap-54': { introduction: 'Sídlem vlády je naopak Cotonou.', question: 'Jaké je oficiální hlavní město Beninu?', options: ['Cotonou', 'Parakou', 'Porto-Novo', 'Abomey'], explanation: 'Porto-Novo je oficiálním hlavním městem Beninu, ačkoliv Cotonou je sídlem vlády a největším městem.' },
  'rm-cap-55': { introduction: 'Vybudováno ve vnitrozemí po hurikánu.', question: 'Jaké je hlavní město Belize?', options: ['Belize City', 'San Ignacio', 'Orange Walk', 'Belmopan'], explanation: 'Belmopan bylo vybudováno ve vnitrozemí po hurikánu a stalo se hlavním městem v roce 1970, kdy nahradilo Belize City.' },
  'rm-cap-56': { introduction: 'Obchodním centrem je naopak Kolombo.', question: 'Jaké je oficiální hlavní město Srí Lanky?', options: ['Kolombo', 'Sri Jayawardenepura Kotte', 'Kandy', 'Galle'], explanation: 'Sri Jayawardenepura Kotte je správním hlavním městem, zatímco Kolombo je obchodním centrem a největším městem.' },

  // ── Úroveň 8 — Vícenásobná a bývalá hlavní města ──
  'rm-cap-57': { introduction: 'Zde zasedá jihoafrický parlament.', question: 'Které město je zákonodárným hlavním městem Jihoafrické republiky?', options: ['Pretoria', 'Bloemfontein', 'Johannesburg', 'Kapské Město'], explanation: 'Kapské Město je zákonodárným hlavním městem a sídlí zde parlament Jihoafrické republiky.' },
  'rm-cap-58': { introduction: 'Hlavní město v letech 1763–1960.', question: 'Které město bylo hlavním městem Brazílie před Brasílií?', options: ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Recife'], explanation: 'Rio de Janeiro bylo hlavním městem Brazílie od roku 1763, dokud jej v roce 1960 nenahradila Brasília.' },
  'rm-cap-59': { introduction: 'Vláda se přestěhovala v roce 1991.', question: 'Které město bylo hlavním městem Nigérie před Abujou?', options: ['Kano', 'Lagos', 'Ibadan', 'Port Harcourt'], explanation: 'Lagos bylo hlavním městem Nigérie, dokud se vláda v roce 1991 nepřestěhovala do účelově postavené Abuji.' },
  'rm-cap-60': { introduction: 'Vláda se přestěhovala v roce 2006.', question: 'Které město bylo hlavním městem Myanmaru před Neipyijtem?', options: ['Mandalay', 'Bagan', 'Rangún', 'Taunggyi'], explanation: 'Rangún byl hlavním městem, dokud se vláda v roce 2006 nepřestěhovala do Neipyijta.' },
  'rm-cap-61': { introduction: 'Sídlo vlády se přesunulo na sever v roce 1997.', question: 'Které město bylo hlavním městem Kazachstánu před Astanou?', options: ['Šymkent', 'Karaganda', 'Almaty', 'Pavlodar'], explanation: 'Almaty bylo hlavním městem do roku 1997, kdy se sídlo vlády přesunulo na sever do Astany.' },
  'rm-cap-62': { introduction: 'Sídlí zde Nejvyšší odvolací soud.', question: 'Které město je soudním hlavním městem Jihoafrické republiky?', options: ['Kapské Město', 'Durban', 'Pretoria', 'Bloemfontein'], explanation: 'Bloemfontein je soudním hlavním městem a sídlí zde Nejvyšší odvolací soud.' },
  'rm-cap-63': { introduction: 'Královským a zákonodárným centrem je Lobamba.', question: 'Jaké je správní hlavní město Eswatini (Svazijsko)?', options: ['Mbabane', 'Manzini', 'Lobamba', 'Big Bend'], explanation: 'Mbabane je správním hlavním městem, zatímco Lobamba je královským a zákonodárným hlavním městem.' },
  'rm-cap-64': { introduction: 'Sídlí zde federální vláda; oficiálním hlavním městem zůstává jiné město.', question: 'Jaké je správní hlavní město Malajsie, sídlo federální vlády?', options: ['Kuala Lumpur', 'Putrajaya', 'George Town', 'Johor Bahru'], explanation: 'Putrajaya je správním hlavním městem Malajsie, zatímco Kuala Lumpur zůstává oficiálním národním hlavním městem.' },

  // ── Úroveň 9 — Podrobný pohled na hlavní města ──
  'rm-cap-65': { introduction: 'Podle průměrné teploty nejchladnější hlavní město světa.', question: 'Jaké je hlavní město Mongolska?', options: ['Ulánbátar', 'Erdenet', 'Darchan', 'Čojbalsan'], explanation: 'Ulánbátar, což znamená „Rudý hrdina", je podle průměrné teploty nejchladnějším hlavním městem na světě.' },
  'rm-cap-66': { introduction: 'Jedno z mála hlavních měst bez semaforů.', question: 'Jaké je hlavní město Bhútánu?', options: ['Paro', 'Punakha', 'Phuentsholing', 'Thimphu'], explanation: 'Thimphu je hlavním městem Bhútánu a jedním z mála hlavních měst bez semaforů.' },
  'rm-cap-67': { introduction: 'Proslulé mnoha bílými mramorovými budovami.', question: 'Jaké je hlavní město Turkmenistánu?', options: ['Türkmenbaşy', 'Mary', 'Ašchabad', 'Daşoguz'], explanation: 'Ašchabad je proslulý mnoha bílými mramorovými budovami a je hlavním městem Turkmenistánu.' },
  'rm-cap-68': { introduction: 'Leží na úpatí pohoří Ťan-šan.', question: 'Jaké je hlavní město Kyrgyzstánu?', options: ['Oš', 'Biškek', 'Džalalabad', 'Karakol'], explanation: 'Biškek na úpatí pohoří Ťan-šan je hlavním a největším městem Kyrgyzstánu.' },
  'rm-cap-69': { introduction: 'Jedno z nejstarších nepřetržitě obývaných měst.', question: 'Jaké je hlavní město Arménie?', options: ['Gjumri', 'Jerevan', 'Vanadzor', 'Vagharšapat'], explanation: 'Jerevan je jedním z nejstarších nepřetržitě obývaných měst na světě a hlavním městem Arménie.' },
  'rm-cap-70': { introduction: 'Metropole na řece Kura.', question: 'Jaké je hlavní město Gruzie?', options: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'], explanation: 'Tbilisi na řece Kura je hlavním a největším městem Gruzie.' },
  'rm-cap-71': { introduction: 'Nejníže položené hlavní město na světě, u Kaspického moře.', question: 'Jaké je hlavní město Ázerbájdžánu?', options: ['Ganja', 'Sumqayit', 'Lankaran', 'Baku'], explanation: 'Baku u Kaspického moře je největším a nejníže položeným hlavním městem na světě.' },
  'rm-cap-72': { introduction: 'Nejlidnatější město Střední Asie.', question: 'Jaké je hlavní město Uzbekistánu?', options: ['Samarkand', 'Buchara', 'Taškent', 'Nukus'], explanation: 'Taškent je hlavním a největším městem Uzbekistánu a nejlidnatějším městem Střední Asie.' },

  // ── Úroveň 10 — Mistrovství v hlavních městech ──
  'rm-cap-73': { introduction: 'Nahradilo Koror v roce 2006; jedno z nejméně lidnatých.', question: 'Jaké je hlavní město Palau?', options: ['Koror', 'Ngerulmud', 'Melekeok', 'Airai'], explanation: 'Ngerulmud nahradilo Koror jako hlavní město Palau v roce 2006 a je jedním z nejméně lidnatých hlavních měst na Zemi.' },
  'rm-cap-74': { introduction: 'Země nemá oficiální hlavní město.', question: 'Jaké je hlavní město Nauru?', options: ['Yaren', 'Denigomodu', 'Aiwo', 'Meneng'], explanation: 'Nauru nemá oficiální hlavní město, ale Yaren slouží jako jeho faktické sídlo vlády.' },
  'rm-cap-75': { introduction: 'Hlavní město sultanátu.', question: 'Jaké je hlavní město Bruneje?', options: ['Kuala Belait', 'Seria', 'Tutong', 'Bandar Seri Begawan'], explanation: 'Bandar Seri Begawan je hlavním a největším městem sultanátu Brunej.' },
  'rm-cap-76': { introduction: 'Nedaleká obec Schaan je lidnatější.', question: 'Jaké je hlavní město Lichtenštejnska?', options: ['Schaan', 'Balzers', 'Vaduz', 'Triesen'], explanation: 'Vaduz je hlavním městem Lichtenštejnska, ačkoliv nedaleká obec Schaan je lidnatější.' },
  'rm-cap-77': { introduction: 'Proslulé nizozemskou koloniální architekturou.', question: 'Jaké je hlavní město Surinamu?', options: ['Lelydorp', 'Nieuw Nickerie', 'Paramaribo', 'Moengo'], explanation: 'Paramaribo se svou nizozemskou koloniální architekturou je hlavním a největším městem Surinamu.' },
  'rm-cap-78': { introduction: 'Sdílí název se zemí, u ústí Rudého moře.', question: 'Jaké je hlavní město Džibutska?', options: ['Ali Sabieh', 'Džibuti', 'Tadjoura', 'Obock'], explanation: 'Město Džibuti u ústí Rudého moře sdílí svůj název se zemí, kterou spravuje.' },
  'rm-cap-79': { introduction: 'Leží na ostrově Grande Comore.', question: 'Jaké je hlavní město Komor?', options: ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni'], explanation: 'Moroni na ostrově Grande Comore je hlavním a největším městem Komor.' },
  'rm-cap-80': { introduction: 'Leží na severním pobřeží.', question: 'Jaké je hlavní město Východního Timoru?', options: ['Baucau', 'Maliana', 'Suai', 'Dili'], explanation: 'Dili na severním pobřeží je hlavním a největším městem Východního Timoru.' },
};
