import type { QuestionTranslation } from './quiz-data';

export const landformsTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Hory a pohoří ──
  'rm-land-1': { introduction: 'Nejvyšší vrchol světa nad hladinou moře.', question: 'Která hora je nejvyšší nad hladinou moře na Zemi?', options: ['Mount Everest', 'K2', 'Kančendženga', 'Denali'], explanation: 'Mount Everest v Himálaji je nejvyšší horou nad hladinou moře, s výškou přibližně 8 849 m.' },
  'rm-land-2': { introduction: 'Zaměř se na to, kde Alpy leží.', question: 'Alpy jsou pohoří ležící převážně na kterém kontinentu?', options: ['Asie', 'Jižní Amerika', 'Evropa', 'Afrika'], explanation: 'Alpy se táhnou napříč jižní a střední Evropou, přes země jako Francie, Švýcarsko, Itálie a Rakousko.' },
  'rm-land-3': { introduction: 'Druhý nejvyšší vrchol světa.', question: 'Která hora je druhá nejvyšší na světě?', options: ['Lhotse', 'K2', 'Makalu', 'Everest'], explanation: 'K2 na hranici Číny a Pákistánu je druhým nejvyšším vrcholem s výškou přibližně 8 611 m.' },
  'rm-land-4': { introduction: 'Nejdelší pohoří světa a jeho kontinent.', question: 'Podél kterého kontinentu se táhne pohoří Andy?', options: ['Severní Amerika', 'Afrika', 'Asie', 'Jižní Amerika'], explanation: 'Andy se táhnou podél západního okraje Jižní Ameriky a jsou nejdelším kontinentálním pohořím na světě.' },
  'rm-land-5': { introduction: 'Kde se nachází nejvyšší pohoří světa.', question: 'Na kterém kontinentu se nachází Himálaj?', options: ['Evropa', 'Afrika', 'Asie', 'Austrálie'], explanation: 'Himálaj se rozkládá přes několik asijských zemí, včetně Nepálu, Indie, Bhútánu a Číny (Tibetu).' },
  'rm-land-6': { introduction: 'Pohoří na západě Severní Ameriky.', question: 'Na kterém kontinentu se nacházejí Skalnaté hory?', options: ['Severní Amerika', 'Jižní Amerika', 'Evropa', 'Asie'], explanation: 'Skalnaté hory se táhnou od Kanady dolů přes západ Spojených států v Severní Americe.' },
  'rm-land-7': { introduction: 'Odhadni výšku nejvyšší hory.', question: 'Jak vysoký je přibližně Mount Everest nad hladinou moře?', options: ['5 895 m', '7 200 m', '10 900 m', '8 849 m'], explanation: 'Mount Everest dosahuje přibližně 8 849 m nad hladinou moře, což je nejvyšší bod na Zemi.' },
  'rm-land-8': { introduction: 'Dvě nejvyšší hory a jejich pohoří.', question: 'Které pohoří obsahuje Mount Everest a K2?', options: ['Alpy', 'Himálaj a Karákóram', 'Andy', 'Skalnaté hory'], explanation: 'Everest leží v Himálaji a K2 v přilehlém pohoří Karákóram, obě ve vysoké Asii.' },

  // ── Úroveň 2 — Řeky ──
  'rm-land-9': { introduction: 'Tradičně nejdelší řeka světa.', question: 'Která řeka je tradičně považována za nejdelší na světě?', options: ['Amazonka', 'Jang-c’-ťiang', 'Nil', 'Mississippi'], explanation: 'Nil v Africe je tradičně považován za nejdelší řeku s délkou přibližně 6 650 km, ačkoli Amazonka je blízkým rivalem.' },
  'rm-land-10': { introduction: 'Řeka s největším průtokem vody.', question: 'Která řeka odvádí největší objem vody (průtok) ze všech řek?', options: ['Nil', 'Jang-c’-ťiang', 'Kongo', 'Amazonka'], explanation: 'Amazonka odvádí více vody než několik dalších největších řek dohromady, zdaleka největší podle objemu.' },
  'rm-land-11': { introduction: 'Kontinent, kterým protéká Amazonka.', question: 'Řeka Amazonka protéká převážně kterým kontinentem?', options: ['Jižní Amerika', 'Afrika', 'Asie', 'Severní Amerika'], explanation: 'Amazonka protéká Jižní Amerikou, převážně Brazílií, než dosáhne Atlantského oceánu.' },
  'rm-land-12': { introduction: 'Na kterém kontinentu teče Nil.', question: 'Na kterém kontinentu se nachází řeka Nil?', options: ['Asie', 'Jižní Amerika', 'Afrika', 'Evropa'], explanation: 'Nil teče na sever přes severovýchodní Afriku, přes Súdán a Egypt až ke Středozemnímu moři.' },
  'rm-land-13': { introduction: 'Nejdelší řeka Asie a její země.', question: 'Jang-c’-ťiang, nejdelší řeka Asie, protéká kterou zemí?', options: ['Indie', 'Čína', 'Rusko', 'Vietnam'], explanation: 'Jang-c’-ťiang protéká výhradně Čínou a je nejdelší řekou Asie s délkou přibližně 6 300 km.' },
  'rm-land-14': { introduction: 'Kontinent významné severoamerické řeky.', question: 'Řeka Mississippi je významnou řekou kterého kontinentu?', options: ['Evropa', 'Afrika', 'Asie', 'Severní Amerika'], explanation: 'Mississippi protéká centrálními Spojenými státy v Severní Americe do Mexického zálivu.' },
  'rm-land-15': { introduction: 'Kam se vlévá Nil.', question: 'Do kterého moře se vlévá řeka Nil?', options: ['Středozemní moře', 'Rudé moře', 'Černé moře', 'Arabské moře'], explanation: 'Nil se vlévá do Středozemního moře velkou deltou v severním Egyptě.' },
  'rm-land-16': { introduction: 'Kam ústí Amazonka.', question: 'Do kterého oceánu ústí řeka Amazonka?', options: ['Tichý oceán', 'Indický oceán', 'Atlantský oceán', 'Jižní oceán'], explanation: 'Amazonka ústí do Atlantského oceánu na severovýchodním pobřeží Brazílie.' },

  // ── Úroveň 3 — Jezera a vnitrozemská moře ──
  'rm-land-17': { introduction: 'Největší jezero podle plochy.', question: 'Které je největší jezero na světě podle rozlohy?', options: ['Hořejší jezero', 'Viktoriino jezero', 'Kaspické moře', 'Bajkal'], explanation: 'Kaspické moře je největší uzavřená vnitrozemská vodní plocha na Zemi; navzdory svému názvu je klasifikováno jako jezero.' },
  'rm-land-18': { introduction: 'Nejhlubší jezero světa.', question: 'Které je nejhlubší jezero na světě?', options: ['Bajkal', 'Tanganika', 'Kaspické moře', 'Hořejší jezero'], explanation: 'Bajkal na Sibiři dosahuje hloubky přibližně 1 642 m, což z něj činí nejhlubší a také nejstarší sladkovodní jezero.' },
  'rm-land-19': { introduction: 'Největší sladkovodní jezero podle plochy.', question: 'Které je největší sladkovodní jezero na světě podle rozlohy?', options: ['Viktoriino jezero', 'Bajkal', 'Titicaca', 'Hořejší jezero'], explanation: 'Hořejší jezero, jedno z Velkých jezer Severní Ameriky, je největším sladkovodním jezerem podle rozlohy.' },
  'rm-land-20': { introduction: 'Kontinent největšího jezera Afriky.', question: 'Viktoriino jezero, největší jezero Afriky, se nachází na kterém kontinentu?', options: ['Asie', 'Afrika', 'Jižní Amerika', 'Evropa'], explanation: 'Viktoriino jezero leží ve východní Africe, na hranicích Tanzanie, Ugandy a Keni.' },
  'rm-land-21': { introduction: 'Pohoří vysoko položeného jezera Titicaca.', question: 'Jezero Titicaca, nejvýše položené velké splavné jezero, leží vysoko v kterém pohoří?', options: ['Andy', 'Himálaj', 'Skalnaté hory', 'Alpy'], explanation: 'Jezero Titicaca leží v Andách na hranici Peru a Bolívie v nadmořské výšce přibližně 3 810 m.' },
  'rm-land-22': { introduction: 'Nejstarší jezero světa, kolem 25 milionů let.', question: 'Které jezero je nejstarším jezerem na Zemi, staré přibližně 25 milionů let?', options: ['Hořejší jezero', 'Viktoriino jezero', 'Bajkal', 'Kaspické moře'], explanation: 'Odhaduje se, že Bajkal je přibližně 25 milionů let starý, tedy nejstarší jezero na světě.' },
  'rm-land-23': { introduction: 'Největší z Velkých jezer.', question: 'Které z těchto je největší z Velkých jezer Severní Ameriky?', options: ['Michiganské jezero', 'Hořejší jezero', 'Huronské jezero', 'Erijské jezero'], explanation: 'Hořejší jezero je největší z pěti Velkých jezer podle rozlohy i objemu.' },
  'rm-land-24': { introduction: 'Kaspické moře sousedí s Evropou a čím dalším.', question: 'Kaspické moře sousedí s Evropou a kterým dalším kontinentem?', options: ['Afrika', 'Severní Amerika', 'Austrálie', 'Asie'], explanation: 'Kaspické moře leží mezi Evropou a Asií, obklopené zeměmi jako Rusko, Kazachstán a Írán.' },

  // ── Úroveň 4 — Pouště ──
  'rm-land-25': { introduction: 'Vezmi v úvahu i studené pouště.', question: 'Která je největší poušť na světě celkově?', options: ['Sahara', 'Gobi', 'Antarktická poušť', 'Arabská poušť'], explanation: 'Antarktická poušť je největší pouští na Zemi; poušť je definována nízkými srážkami a Antarktida je extrémně suchá.' },
  'rm-land-26': { introduction: 'Největší horká poušť.', question: 'Která je největší horká poušť na světě?', options: ['Gobi', 'Sahara', 'Kalahari', 'Arabská poušť'], explanation: 'Sahara v severní Africe je největší horkou pouští, pokrývá přibližně 9,2 milionu čtverečních kilometrů.' },
  'rm-land-27': { introduction: 'Nejsušší místo na Zemi.', question: 'Která poušť je obecně považována za nejsušší místo na Zemi?', options: ['Sahara', 'Gobi', 'Poušť Atacama', 'Arabská poušť'], explanation: 'Poušť Atacama v Chile je nejsušší nepolární pouští; některé meteorologické stanice nikdy nezaznamenaly déšť.' },
  'rm-land-28': { introduction: 'Kontinent Sahary.', question: 'Poušť Sahara pokrývá většinu kterého kontinentu?', options: ['Afrika', 'Asie', 'Austrálie', 'Jižní Amerika'], explanation: 'Sahara se táhne přes severní Afriku a rozkládá se přes mnoho zemí od Atlantiku po Rudé moře.' },
  'rm-land-29': { introduction: 'Poušť Gobi leží v Mongolsku a kde ještě.', question: 'Poušť Gobi leží převážně v Mongolsku a které další zemi?', options: ['Indie', 'Čína', 'Rusko', 'Kazachstán'], explanation: 'Poušť Gobi pokrývá části severní Číny a jižního Mongolska ve střední Asii.' },
  'rm-land-30': { introduction: 'Poloostrov, který pokrývá Arabská poušť.', question: 'Arabská poušť pokrývá většinu kterého poloostrova?', options: ['Pyrenejský poloostrov', 'Indický poloostrov', 'Balkánský poloostrov', 'Arabský poloostrov'], explanation: 'Arabská poušť dominuje Arabskému poloostrovu, včetně velké části Saúdské Arábie.' },
  'rm-land-31': { introduction: 'Země pouště Atacama.', question: 'Poušť Atacama se nachází v které zemi?', options: ['Chile', 'Peru', 'Argentina', 'Mexiko'], explanation: 'Poušť Atacama leží podél tichomořského pobřeží severního Chile v Jižní Americe.' },
  'rm-land-32': { introduction: 'Poušť není definována teplem.', question: 'Proč je Antarktida klasifikována jako poušť?', options: ['Je zcela pokryta pískem', 'Nemá žádný led', 'Je nejteplejším místem na Zemi', 'Dostává velmi málo srážek'], explanation: 'Poušť je definována nízkými srážkami, nikoli teplem; vnitrozemí Antarktidy dostává téměř žádný sníh ani déšť, takže se kvalifikuje jako polární poušť.' },

  // ── Úroveň 5 — Údolí a kaňony ──
  'rm-land-33': { introduction: 'Řeka, která vytvořila Grand Canyon.', question: 'Grand Canyon vytvořila především která řeka?', options: ['Řeka Colorado', 'Rio Grande', 'Řeka Mississippi', 'Řeka Columbia'], explanation: 'Řeka Colorado vytvořila Grand Canyon během milionů let a odhalila téměř dvě miliardy let starou horninu.' },
  'rm-land-34': { introduction: 'Země, kde leží Grand Canyon.', question: 'Ve které zemi se nachází Grand Canyon?', options: ['Mexiko', 'Kanada', 'Spojené státy', 'Brazílie'], explanation: 'Grand Canyon se nachází ve státě Arizona na jihozápadě Spojených států.' },
  'rm-land-35': { introduction: 'Kontinent Velké příkopové propadliny.', question: 'Velká příkopová propadlina se táhne převážně kterým kontinentem?', options: ['Jižní Amerika', 'Asie', 'Austrálie', 'Afrika'], explanation: 'Velká příkopová propadlina je řada propojených příkopů táhnoucích se východní Afrikou (a dále na Blízký východ).' },
  'rm-land-36': { introduction: 'Jak vznikají fjordy.', question: 'Jak vznikají fjordy?', options: ['Ledovci, které vytvořily hluboká údolí později zaplavená mořem', 'Sopečnými erupcemi', 'Dopady meteoritů', 'Větrnou erozí'], explanation: 'Fjordy jsou hluboká, ledovcem vyhloubená údolí, která byla později zaplavena mořem a vytvořila strmé zálivy.' },
  'rm-land-37': { introduction: 'Země proslulá fjordy.', question: 'Která země je obzvláště proslulá svými dramatickými fjordy?', options: ['Egypt', 'Indie', 'Norsko', 'Keňa'], explanation: 'Norské pobřeží je proslulé svými hlubokými ledovcovými fjordy, jako je Sognefjord a Geirangerfjord.' },
  'rm-land-38': { introduction: 'Geologický proces vzniku příkopové propadliny.', question: 'Příkopová propadlina obvykle vzniká jakým geologickým procesem?', options: ['Řekami ukládajícími sedimenty', 'Tektonickými deskami, které se od sebe vzdalují', 'Mořskými přílivy', 'Táním ledovců'], explanation: 'Příkopové propadliny vznikají tam, kde se tektonické desky Země od sebe vzdalují, což způsobuje pokles pevniny mezi zlomy.' },
  'rm-land-39': { introduction: 'Nejnižší bod Severní Ameriky, čím je proslulý.', question: 'Údolí smrti, nejnižší bod Severní Ameriky, je nejlépe známé tím, že je extrémně jaké?', options: ['Studené', 'Vlhké', 'Vysoko položené', 'Horké a suché'], explanation: 'Údolí smrti v Kalifornii je jedním z nejteplejších a nejsušších míst na Zemi a drží rekordní teploty vzduchu.' },
  'rm-land-40': { introduction: 'Definice kaňonu.', question: 'Jak lze nejlépe popsat kaňon?', options: ['Hluboké údolí se strmými stěnami, často vyhloubené řekou', 'Zaoblený kopec', 'Plochá pobřežní nížina', 'Podmořská hora'], explanation: 'Kaňon je hluboké, úzké údolí se strmými stěnami, obvykle vytvořené erozivním působením řeky během dlouhých období.' },

  // ── Úroveň 6 — Plošiny a roviny ──
  'rm-land-41': { introduction: 'Přezdívka Tibetské náhorní plošiny.', question: 'Tibetská náhorní plošina je často přezdívána kterak z následujícího?', options: ['Zahrada světa', 'Střecha světa', 'Dno světa', 'Okraj světa'], explanation: 'Tibetská náhorní plošina je nazývána „Střechou světa“, protože je nejvyšší a největší náhorní plošinou na Zemi.' },
  'rm-land-42': { introduction: 'Kontinent Tibetské náhorní plošiny.', question: 'Na kterém kontinentu se nachází Tibetská náhorní plošina?', options: ['Afrika', 'Evropa', 'Asie', 'Jižní Amerika'], explanation: 'Tibetská náhorní plošina leží ve střední a východní Asii, převážně na území Číny (Tibetu).' },
  'rm-land-43': { introduction: 'Kontinent rozlehlých Velkých plání.', question: 'Velké pláně jsou rozsáhlou plochou nížinou na kterém kontinentu?', options: ['Severní Amerika', 'Evropa', 'Asie', 'Afrika'], explanation: 'Velké pláně se táhnou přes centrální Spojené státy a Kanadu v Severní Americe.' },
  'rm-land-44': { introduction: 'Co je step.', question: 'Co je step?', options: ['Vysoký zasněžený vrchol', 'Hluboká oceánská brázda', 'Rozlehlá oblast ploché, bezlesé travnaté plochy', 'Tropický deštný prales'], explanation: 'Step je rozsáhlá, polosuchá travnatá plocha s málo stromy, jako je Euroasijská step táhnoucí se přes Asii.' },
  'rm-land-45': { introduction: 'Definice náhorní plošiny.', question: 'Jak lze nejlépe popsat náhorní plošinu?', options: ['Úzké řečiště', 'Strmý horský vrchol', 'Propadlá pánev pod hladinou moře', 'Oblast vysoko položené, poměrně ploché země'], explanation: 'Náhorní plošina je vyvýšená oblast poměrně rovné země, prudce vyzdvižená nad okolní terén alespoň z jedné strany.' },
  'rm-land-46': { introduction: 'Země Dekánské plošiny.', question: 'Dekánská plošina tvoří velkou část které země?', options: ['Čína', 'Indie', 'Írán', 'Egypt'], explanation: 'Dekánská plošina pokrývá většinu jižní části Indie.' },
  'rm-land-47': { introduction: 'Kontinent úrodných rovin Pampy.', question: 'Pampy jsou úrodné nížinné roviny nacházející se na kterém kontinentu?', options: ['Evropa', 'Afrika', 'Jižní Amerika', 'Austrálie'], explanation: 'Pampy jsou rozsáhlé travnaté roviny v Jižní Americe, zejména v Argentině, Uruguayi a jižní Brazílii.' },
  'rm-land-48': { introduction: 'Odhadni průměrnou nadmořskou výšku.', question: 'Tibetská náhorní plošina je nejvyšší a největší náhorní plošinou na světě. V jaké přibližné průměrné nadmořské výšce leží?', options: ['Přes 4 000 m', 'Asi 500 m', 'Asi 1 000 m', 'Asi 2 000 m'], explanation: 'Tibetská náhorní plošina má průměrnou nadmořskou výšku přes 4 000 m nad hladinou moře.' },

  // ── Úroveň 7 — Pobřeží a poloostrovy ──
  'rm-land-49': { introduction: 'Dvě hlavní země Pyrenejského poloostrova.', question: 'Pyrenejský poloostrov tvoří převážně které dvě země?', options: ['Itálie a Řecko', 'Španělsko a Portugalsko', 'Francie a Německo', 'Norsko a Švédsko'], explanation: 'Pyrenejský poloostrov v jihozápadní Evropě zaujímá převážně Španělsko a Portugalsko.' },
  'rm-land-50': { introduction: 'Skandinávský poloostrov sdílejí Norsko a čí země.', question: 'Skandinávský poloostrov sdílejí převážně Norsko a která země?', options: ['Dánsko', 'Finsko', 'Island', 'Švédsko'], explanation: 'Skandinávský poloostrov v severní Evropě zaujímají převážně Norsko a Švédsko.' },
  'rm-land-51': { introduction: 'Největší poloostrov světa.', question: 'Který je největší poloostrov na světě?', options: ['Pyrenejský poloostrov', 'Arabský poloostrov', 'Balkánský poloostrov', 'Korejský poloostrov'], explanation: 'Arabský poloostrov je největším poloostrovem na Zemi, zaujímá velkou část jihozápadní Asie.' },
  'rm-land-52': { introduction: 'Země proslulého mysu Dobré naděje.', question: 'Mys Dobré naděje je proslulý skalnatý výběžek v které zemi?', options: ['Austrálie', 'Argentina', 'Jihoafrická republika', 'Indie'], explanation: 'Mys Dobré naděje leží na atlantském pobřeží Jihoafrické republiky, poblíž jižního cípu kontinentu.' },
  'rm-land-53': { introduction: 'Co spojuje Gibraltarský průliv.', question: 'Gibraltarský průliv spojuje Středozemní moře s kterou vodní plochou?', options: ['Atlantský oceán', 'Černé moře', 'Rudé moře', 'Indický oceán'], explanation: 'Gibraltarský průliv spojuje Středozemní moře s Atlantským oceánem, mezi Španělskem a Marokem.' },
  'rm-land-54': { introduction: 'Město, kterým prochází Bospor.', question: 'Průliv Bospor, který odděluje Evropu a Asii, prochází kterým městem?', options: ['Atény', 'Istanbul', 'Káhira', 'Řím'], explanation: 'Bospor prochází Istanbulem v Turecku, spojuje Černé moře s Marmarským mořem a odděluje Evropu od Asie.' },
  'rm-land-55': { introduction: 'Kontinent, jehož jižní cíp tvoří mys Horn.', question: 'Mys Horn tvoří jižní cíp kterého kontinentu?', options: ['Afrika', 'Austrálie', 'Asie', 'Jižní Amerika'], explanation: 'Mys Horn je nejjižnějším výběžkem souostroví Ohňová země na cípu Jižní Ameriky.' },
  'rm-land-56': { introduction: 'Co je šíje.', question: 'Co je šíje (isthmus)?', options: ['Úzký pruh země spojující dvě větší pevninské oblasti', 'Hluboká mořská brázda', 'Prstenec korálů', 'Řetěz sopek'], explanation: 'Šíje je úzký pruh země spojující dvě větší pevniny, jako je Panamská šíje.' },

  // ── Úroveň 8 — Sopky ──
  'rm-land-57': { introduction: 'Země nejvyšší hory Afriky.', question: 'Kilimandžáro, nejvyšší hora Afriky, je sopka nacházející se v které zemi?', options: ['Keňa', 'Etiopie', 'Tanzanie', 'Uganda'], explanation: 'Kilimandžáro je dřímající sopka v Tanzanii a s výškou přibližně 5 895 m nejvyšší horou Afriky.' },
  'rm-land-58': { introduction: 'Země ikonické hory Fudži.', question: 'Hora Fudži, ikonická sopka, se nachází v které zemi?', options: ['Japonsko', 'Čína', 'Indonésie', 'Filipíny'], explanation: 'Hora Fudži je nejvyšší horou Japonska a činný (v současnosti dřímající) stratovulkán.' },
  'rm-land-59': { introduction: 'Sopka, která zničila Pompeje.', question: 'Která sopka proslule zničila římské město Pompeje v roce 79 n. l.?', options: ['Etna', 'Vesuv', 'Krakatoa', 'Mount St. Helens'], explanation: 'Vesuv poblíž Neapole v Itálii vybuchl v roce 79 n. l. a zasypal Pompeje a Herculaneum popelem.' },
  'rm-land-60': { introduction: 'Oceán, který obklopuje Ohnivý kruh.', question: '„Ohnivý kruh“, zóna častých zemětřesení a sopek, obklopuje který oceán?', options: ['Atlantský oceán', 'Indický oceán', 'Severní ledový oceán', 'Tichý oceán'], explanation: 'Ohnivý kruh je podkovovitý pás sopek a zemětřesení kolem okraje Tichého oceánu.' },
  'rm-land-61': { introduction: 'Typ sopky s vysokým strmým kuželem.', question: 'Vysoký kužel se strmými stěnami, tvořený vrstvami lávy a popela, jako hora Fudži, je kterým typem sopky?', options: ['Stratovulkán', 'Štítová sopka', 'Struskový kužel', 'Kaldera'], explanation: 'Stratovulkán (smíšená sopka) má strmý, vrstvený kužel vytvořený ze střídajících se vrstev lávy a popela, jako u hory Fudži.' },
  'rm-land-62': { introduction: 'Typ havajské sopky Mauna Loa.', question: 'Mauna Loa na Havaji, jedna z největších sopek světa, je kterým typem sopky?', options: ['Struskový kužel', 'Stratovulkán', 'Kaldera', 'Štítová sopka'], explanation: 'Mauna Loa je štítová sopka, vytvořená z tekutých lávových proudů, které vytvářejí širokou, mírně skloněnou kopuli.' },
  'rm-land-63': { introduction: 'Země katastrofické erupce Krakatoy v roce 1883.', question: 'Katastrofická erupce Krakatoy v roce 1883 se odehrála v které zemi?', options: ['Japonsko', 'Indonésie', 'Island', 'Itálie'], explanation: 'Krakatoa (Krakatau) vybuchla v roce 1883 v průlivu mezi ostrovy Jáva a Sumatra v Indonésii.' },
  'rm-land-64': { introduction: 'Název roztavené horniny po erupci.', question: 'Jak se nazývá roztavená hornina poté, co ji sopka vyvrhne na povrch?', options: ['Magma', 'Sediment', 'Tefra', 'Láva'], explanation: 'Roztavená hornina se nazývá magma, dokud je pod zemí, a láva, jakmile je vyvržena na zemský povrch.' },

  // ── Úroveň 9 — Ledovce a led ──
  'rm-land-65': { introduction: 'Oblast s největším ledovcovým štítem.', question: 'Která oblast má největší ledovcový štít na Zemi?', options: ['Antarktida', 'Grónsko', 'Island', 'Severní Kanada'], explanation: 'Antarktický ledovcový štít je zdaleka největší a obsahuje většinu sladké vody světa uzamčené v ledu.' },
  'rm-land-66': { introduction: 'Pevnina druhého největšího ledovcového štítu.', question: 'Druhý největší ledovcový štít na světě pokrývá kterou pevninu?', options: ['Antarktida', 'Grónsko', 'Aljaška', 'Sibiř'], explanation: 'Grónský ledovcový štít je druhým největším ledovcovým tělesem, pokrývá většinu ostrova Grónsko.' },
  'rm-land-67': { introduction: 'Co je moréna.', question: 'Co je moréna?', options: ['Zamrzlý vodopád', 'Trhlina v ledovci', 'Plovoucí kra mořského ledu', 'Hornina a suť uložená ledovcem'], explanation: 'Moréna je nahromadění horniny, štěrku a půdy, které nese a ukládá pohybující se ledovec.' },
  'rm-land-68': { introduction: 'Odhadni, jaká část ledovce je pod vodou.', question: 'Jaká přibližně část ledovce se nachází pod hladinou vody?', options: ['Asi polovina', 'Asi jedna čtvrtina', 'Téměř žádná', 'Asi devět desetin'], explanation: 'Protože led má jen o něco nižší hustotu než voda, přibližně 90 % ledovce leží skryto pod hladinou.' },
  'rm-land-69': { introduction: 'Jak se pohybují ledovce.', question: 'Jakým obecným způsobem se ledovce pohybují?', options: ['Zůstávají zcela nehybné', 'Velmi pomalu tečou z kopce pod vlastní vahou', 'Volně plují na oceánu', 'Stoupají vzhůru do vzduchu'], explanation: 'Pod vlivem gravitace a vlastní váhy ledovce pomalu tečou z kopce a přetvářejí zemi pod sebou.' },
  'rm-land-70': { introduction: 'Tvar příčného průřezu ledovcového údolí.', question: 'Ledovce charakteristicky vytvářejí údolí do jakého tvaru příčného průřezu?', options: ['Tvar písmene V', 'Tvar písmene U', 'Kruhový', 'Plochý'], explanation: 'Ledovce vyhlubují široká údolí ve tvaru písmene U, zatímco řeky obvykle vytvářejí užší údolí ve tvaru písmene V.' },
  'rm-land-71': { introduction: 'Kontinent, který má asi 70 % sladké vody v ledu.', question: 'Kterým kontinentem je ten, který má asi 70 % sladké vody světa ve formě ledu?', options: ['Asie', 'Severní Amerika', 'Antarktida', 'Evropa'], explanation: 'Antarktický ledovcový štít obsahuje zhruba 70 % sladké vody Země a asi 90 % jejího ledu.' },
  'rm-land-72': { introduction: 'Velká masa hustého ledu tekoucí po souši.', question: 'Jak se nazývá velká masa hustého ledu, která pomalu teče po souši?', options: ['Ledovcová kra', 'Gejzír', 'Sněhové pole', 'Ledovec'], explanation: 'Ledovec je trvalé těleso hustého ledu, které vzniká ze stlačeného sněhu a pomalu teče po souši.' },

  // ── Úroveň 10 — Mistrovství v tvarech reliéfu ──
  'rm-land-73': { introduction: 'Nejvyšší nepřerušený vodopád světa.', question: 'Který je nejvyšší nepřerušený vodopád na světě?', options: ['Niagarské vodopády', 'Salto Ángel', 'Viktoriiny vodopády', 'Vodopády Iguazú'], explanation: 'Salto Ángel ve Venezuele padá z výšky přibližně 979 m, což z něj činí nejvyšší nepřerušený vodopád na Zemi.' },
  'rm-land-74': { introduction: 'Nejnižší bod odkryté souše.', question: 'Který je nejnižší bod odkryté souše na povrchu Země?', options: ['Břeh Mrtvého moře', 'Údolí smrti', 'Břeh Kaspického moře', 'Jezero Assal'], explanation: 'Břeh Mrtvého moře, přibližně 430 m pod hladinou moře, je nejnižší odkrytou nadmořskou výškou souše na Zemi.' },
  'rm-land-75': { introduction: 'Nejhlubší známý bod oceánů.', question: 'Nejhlubší známý bod světových oceánů leží ve kterém útvaru?', options: ['Portorický příkop', 'Jávský příkop', 'Mariánský příkop', 'Tongský příkop'], explanation: 'Challengerova hlubina v Mariánském příkopu dosahuje přibližně 10 935 m, nejhlubší známý bod v jakémkoli oceánu.' },
  'rm-land-76': { introduction: 'Odhadni délku Nilu.', question: 'Jak dlouhá je přibližně řeka Nil, tradičně nejdelší na světě?', options: ['Asi 3 200 km', 'Asi 4 400 km', 'Asi 9 000 km', 'Asi 6 650 km'], explanation: 'Nil se tradičně měří na přibližně 6 650 km, což z něj (podle tohoto výpočtu) činí nejdelší řeku na světě.' },
  'rm-land-77': { introduction: 'Odhadni maximální hloubku Bajkalu.', question: 'Bajkal, nejhlubší jezero na Zemi, dosahuje přibližně jaké maximální hloubky?', options: ['Asi 1 642 m', 'Asi 500 m', 'Asi 800 m', 'Asi 3 000 m'], explanation: 'Bajkal klesá do hloubky přibližně 1 642 m, nejhlubší jezero na světě a držitel největšího množství kapalné sladké vody.' },
  'rm-land-78': { introduction: 'Nejvyšší hora měřená od úpatí k vrcholu.', question: 'Měřeno od úpatí k vrcholu, nikoli od hladiny moře, která hora je nejvyšší?', options: ['Mount Everest', 'K2', 'Mauna Kea', 'Denali'], explanation: 'Mauna Kea na Havaji se zvedá přibližně 10 200 m od svého úpatí na dně oceánu, tedy vyšší od úpatí k vrcholu než Everest.' },
  'rm-land-79': { introduction: 'Odhadni délku Andského pohoří.', question: 'Andy jsou nejdelší pohoří nad hladinou moře. Jak jsou přibližně dlouhé?', options: ['Asi 2 000 km', 'Asi 7 000 km', 'Asi 3 500 km', 'Asi 12 000 km'], explanation: 'Andy se táhnou přibližně 7 000 km podél západního okraje Jižní Ameriky, nejdelší kontinentální pohoří.' },
  'rm-land-80': { introduction: 'Neobvyklý rekord hory Chimborazo.', question: 'Hora Chimborazo v Ekvádoru drží který neobvyklý „nejvyšší“ rekord?', options: ['Nejvyšší nad hladinou moře', 'Nejaktivnější sopka', 'Její vrchol je nejvzdálenějším bodem od středu Země', 'Nejchladnější vrchol'], explanation: 'Protože se Země na rovníku vyklenuje, vrchol Chimborazo je bodem na povrchu nejvzdálenějším od středu planety.' },
};
