// Geopolitics roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const geopoliticsSeeds: Seed[] = [
  // ── Level 1 — States, Sovereignty & Borders ──
  { q: 'In political geography, what does state sovereignty primarily refer to?', opts: ['Supreme authority over a defined territory', 'The size of a country\'s army', 'Membership in the United Nations', 'A written constitution'], a: 0, e: 'Sovereignty is a state\'s supreme, independent authority to govern within its own territory, free from external control.', tags: ['Geopolitics', 'Sovereignty'] },
  { q: 'A landlocked country is one that:', opts: ['Has no coastline on any ocean or sea', 'Lies entirely in the tropics', 'Has no navigable rivers', 'Borders only one neighbour'], a: 0, e: 'A landlocked state has no direct access to the open sea, such as Bolivia, Nepal or Austria.', tags: ['Geopolitics', 'Territory'] },
  { q: 'A territory completely surrounded by the land of a single other state is called a(n):', opts: ['Enclave', 'Peninsula', 'Archipelago', 'Isthmus'], a: 0, e: 'An enclave is surrounded entirely by another state; Lesotho, encircled by South Africa, is a classic example.', tags: ['Geopolitics', 'Territory'] },
  { q: 'Kaliningrad, separated from the rest of Russia by Lithuania and Poland, is best described as a Russian:', opts: ['Exclave', 'Enclave of Poland', 'Condominium', 'Protectorate'], a: 0, e: 'An exclave is a part of a state geographically separated from the main territory; Kaliningrad is Russian land detached from Russia proper.', tags: ['Geopolitics', 'Territory'] },
  { q: 'Under the UN Convention on the Law of the Sea, a state\'s territorial sea extends up to how far from its baseline?', opts: ['12 nautical miles', '3 nautical miles', '200 nautical miles', '50 nautical miles'], a: 0, e: 'UNCLOS sets the territorial sea at up to 12 nautical miles; the 200-mile limit refers to the Exclusive Economic Zone.', tags: ['Geopolitics', 'Maritime Law'] },
  { q: 'The 1648 Peace of Westphalia is traditionally credited with establishing the principle of:', opts: ['Sovereign, territorially defined states', 'Universal human rights', 'Free global trade', 'Collective security'], a: 0, e: 'Westphalia is seen as the origin of the modern system of sovereign states with fixed territory and non-interference.', tags: ['Geopolitics', 'Sovereignty'] },
  { q: 'The principle of uti possidetis juris holds that newly independent states should:', opts: ['Inherit the borders of prior colonial units', 'Redraw borders along ethnic lines', 'Abolish all internal boundaries', 'Merge with neighbouring states'], a: 0, e: 'Uti possidetis juris preserves former colonial administrative boundaries as the borders of new states, notably applied in Latin America and Africa.', tags: ['Geopolitics', 'Borders'] },
  { q: 'What is the difference between de jure and de facto recognition of a state?', opts: ['De jure is legal/formal; de facto is in-practice', 'De jure means larger; de facto means smaller', 'They are identical terms', 'De jure applies only to monarchies'], a: 0, e: 'De jure recognition is full legal acknowledgement, while de facto recognition accepts a government exists in practice without full legal endorsement.', tags: ['Geopolitics', 'Sovereignty'] },

  // ── Level 2 — International Organizations & Alliances ──
  { q: 'How many permanent members hold veto power on the UN Security Council?', opts: ['5', '3', '10', '15'], a: 0, e: 'The five permanent members (P5) are China, France, Russia, the United Kingdom and the United States, each with a veto.', tags: ['Geopolitics', 'United Nations'] },
  { q: 'NATO\'s Article 5 embodies which core principle?', opts: ['Collective defence', 'Free trade', 'Nuclear disarmament', 'Environmental protection'], a: 0, e: 'Article 5 states that an armed attack against one member is considered an attack against all, the basis of collective defence.', tags: ['Geopolitics', 'NATO'] },
  { q: 'The Schengen Area is best known for allowing:', opts: ['Passport-free travel between members', 'A shared army', 'A single tax code', 'Joint ownership of oil fields'], a: 0, e: 'The Schengen Agreement abolished systematic internal border checks, permitting free movement of people across member states.', tags: ['Geopolitics', 'European Union'] },
  { q: 'ASEAN is a regional organization for states in which region?', opts: ['Southeast Asia', 'South America', 'West Africa', 'The Caribbean'], a: 0, e: 'The Association of Southeast Asian Nations groups ten Southeast Asian states and is headquartered in Jakarta, Indonesia.', tags: ['Geopolitics', 'ASEAN'] },
  { q: 'The headquarters of the United Nations is located in which city?', opts: ['New York', 'Geneva', 'Vienna', 'Brussels'], a: 0, e: 'The UN\'s main headquarters is in New York City, though it maintains major offices in Geneva, Vienna and Nairobi.', tags: ['Geopolitics', 'United Nations'] },
  { q: 'The African Union has its headquarters in which capital city?', opts: ['Addis Ababa', 'Nairobi', 'Cairo', 'Pretoria'], a: 0, e: 'The African Union is headquartered in Addis Ababa, Ethiopia, on the site of the former Organisation of African Unity.', tags: ['Geopolitics', 'African Union'] },
  { q: 'The group of EU member states that share the euro as their currency is called the:', opts: ['Eurozone', 'Schengen Area', 'Customs Union', 'Council of Europe'], a: 0, e: 'The eurozone comprises the EU members that have adopted the euro; not all EU states are members of it.', tags: ['Geopolitics', 'European Union'] },
  { q: 'Which of the following is NOT one of NATO\'s founding purposes in 1949?', opts: ['Managing global oil prices', 'Deterring Soviet expansion', 'Collective defence of members', 'Binding North America to Europe'], a: 0, e: 'NATO was created as a transatlantic collective-defence alliance to deter Soviet expansion, not to regulate energy markets.', tags: ['Geopolitics', 'NATO'] },

  // ── Level 3 — Classical Geostrategy ──
  { q: 'Halford Mackinder\'s "Heartland theory" argued that control of which region was key to global power?', opts: ['The interior of Eurasia', 'The Pacific islands', 'Sub-Saharan Africa', 'The Arctic Ocean'], a: 0, e: 'Mackinder held that the Eurasian interior "Heartland" was the geographic pivot of history and command of the World-Island.', tags: ['Geopolitics', 'Geostrategy'] },
  { q: 'Nicholas Spykman\'s "Rimland" theory emphasized control of:', opts: ['The coastal fringe of Eurasia', 'The central Eurasian steppe', 'The polar regions', 'Isolated island chains'], a: 0, e: 'Spykman argued the maritime Rimland encircling the Heartland, not the interior, was decisive for world power.', tags: ['Geopolitics', 'Geostrategy'] },
  { q: 'Alfred Thayer Mahan is best known for a theory stressing the strategic importance of:', opts: ['Sea power and naval dominance', 'Railway networks', 'Airborne forces', 'Mountain fortresses'], a: 0, e: 'Mahan argued that command of the sea, through a strong navy and control of trade routes, determined national greatness.', tags: ['Geopolitics', 'Geostrategy'] },
  { q: 'A "buffer state" in geopolitics is a country that:', opts: ['Separates two rival powers', 'Has the largest population', 'Controls a major canal', 'Exports mainly oil'], a: 0, e: 'A buffer state lies between two greater powers and helps reduce the chance of direct conflict between them.', tags: ['Geopolitics', 'Geostrategy'] },
  { q: 'In geopolitics, a maritime "chokepoint" is:', opts: ['A narrow passage vital to shipping', 'A deep-sea mining zone', 'A disputed island group', 'A naval training area'], a: 0, e: 'A chokepoint is a strategically narrow waterway, such as a strait, through which large volumes of trade or naval traffic must pass.', tags: ['Geopolitics', 'Chokepoints'] },
  { q: 'Mackinder used the term "World-Island" to describe the connected landmass of:', opts: ['Europe, Asia and Africa', 'North and South America', 'Australia and Oceania', 'Antarctica and its shelves'], a: 0, e: 'The World-Island referred to the interconnected continents of Eurasia and Africa, the largest and most populous landmass.', tags: ['Geopolitics', 'Geostrategy'] },
  { q: 'The strategic logic of a buffer zone is generally to:', opts: ['Provide defensive depth against invasion', 'Maximize tax revenue', 'Increase coastline length', 'Standardize a common language'], a: 0, e: 'Buffer zones give a state territorial depth and warning time, absorbing an attack before it reaches the core.', tags: ['Geopolitics', 'Geostrategy'] },
  { q: 'Mackinder\'s famous dictum linked commanding the Heartland to commanding:', opts: ['The World-Island, and thus the world', 'The Atlantic trade', 'The colonial empires', 'The polar sea lanes'], a: 0, e: 'His maxim ran: who rules the Heartland commands the World-Island; who rules the World-Island commands the world.', tags: ['Geopolitics', 'Geostrategy'] },

  // ── Level 4 — Resource & Economic Geopolitics ──
  { q: 'The Strait of Hormuz, a critical oil chokepoint, connects the Persian Gulf to the:', opts: ['Gulf of Oman', 'Red Sea', 'Black Sea', 'Caspian Sea'], a: 0, e: 'The Strait of Hormuz links the Persian Gulf to the Gulf of Oman and the Arabian Sea, carrying a large share of seaborne oil.', tags: ['Geopolitics', 'Energy'] },
  { q: 'The Strait of Malacca is a key shipping lane connecting the Indian Ocean to the:', opts: ['South China Sea', 'Mediterranean Sea', 'Baltic Sea', 'Bay of Biscay'], a: 0, e: 'The Malacca Strait between Malaysia and Indonesia links the Indian Ocean to the South China Sea, a vital Asian trade artery.', tags: ['Geopolitics', 'Trade Routes'] },
  { q: 'The Bosphorus Strait, controlled by Turkey, connects the Black Sea to the:', opts: ['Sea of Marmara', 'Adriatic Sea', 'Red Sea', 'Persian Gulf'], a: 0, e: 'The Bosphorus links the Black Sea to the Sea of Marmara, which via the Dardanelles reaches the Mediterranean.', tags: ['Geopolitics', 'Chokepoints'] },
  { q: 'The Panama Canal provides a shipping shortcut between which two oceans?', opts: ['Atlantic and Pacific', 'Indian and Pacific', 'Atlantic and Arctic', 'Indian and Atlantic'], a: 0, e: 'The Panama Canal cuts across Central America, linking the Atlantic and Pacific Oceans and avoiding Cape Horn.', tags: ['Geopolitics', 'Trade Routes'] },
  { q: 'The Bab-el-Mandeb strait, a major maritime chokepoint, lies between the Red Sea and the:', opts: ['Gulf of Aden', 'Persian Gulf', 'Mozambique Channel', 'Gulf of Guinea'], a: 0, e: 'Bab-el-Mandeb connects the Red Sea to the Gulf of Aden, linking Suez-bound traffic to the Indian Ocean.', tags: ['Geopolitics', 'Chokepoints'] },
  { q: 'The Grand Ethiopian Renaissance Dam has been a source of water-sharing tension chiefly between Ethiopia, Sudan and:', opts: ['Egypt', 'Kenya', 'Saudi Arabia', 'Libya'], a: 0, e: 'Egypt, heavily dependent on the Nile, has objected to the GERD over concerns about downstream water flows.', tags: ['Geopolitics', 'Water'] },
  { q: 'As of the 2020s, which country dominates the mining and processing of rare earth elements?', opts: ['China', 'Canada', 'Brazil', 'Norway'], a: 0, e: 'China accounts for the large majority of global rare earth production and an even larger share of refining capacity.', tags: ['Geopolitics', 'Resources'] },
  { q: 'The Suez Canal\'s strategic value lies in connecting the Mediterranean Sea to the:', opts: ['Red Sea', 'Caspian Sea', 'Arabian Sea directly', 'Black Sea'], a: 0, e: 'The Suez Canal links the Mediterranean to the Red Sea, sharply shortening the sea route between Europe and Asia.', tags: ['Geopolitics', 'Trade Routes'] },

  // ── Level 5 — Contemporary Flashpoints & Disputed Territories ──
  { q: 'The Kashmir region is primarily disputed between which two countries?', opts: ['India and Pakistan', 'India and Nepal', 'Pakistan and Iran', 'China and Myanmar'], a: 0, e: 'Kashmir has been contested by India and Pakistan since 1947, with China also administering part of the wider region.', tags: ['Geopolitics', 'Disputed Territory'] },
  { q: 'China\'s expansive maritime claim in the South China Sea is popularly known as the:', opts: ['Nine-dash line', 'Iron Curtain', 'Green Line', 'Blue Belt'], a: 0, e: 'The nine-dash line marks China\'s broad claim over most of the South China Sea, disputed by several neighbours.', tags: ['Geopolitics', 'Disputed Territory'] },
  { q: 'The Taiwan Strait separates the island of Taiwan from:', opts: ['Mainland China', 'The Philippines', 'Japan', 'Vietnam'], a: 0, e: 'The roughly 130-km-wide Taiwan Strait separates Taiwan from mainland China across a major geopolitical fault line.', tags: ['Geopolitics', 'Flashpoints'] },
  { q: 'The Nagorno-Karabakh region has been the focus of conflict between Armenia and:', opts: ['Azerbaijan', 'Georgia', 'Turkey', 'Iran'], a: 0, e: 'Nagorno-Karabakh, internationally recognized as part of Azerbaijan, was long contested with Armenia and its ethnic-Armenian population.', tags: ['Geopolitics', 'Disputed Territory'] },
  { q: 'The Kuril Islands are the subject of a sovereignty dispute between Russia and:', opts: ['Japan', 'China', 'South Korea', 'the United States'], a: 0, e: 'The southern Kuril Islands, held by Russia and claimed by Japan as the Northern Territories, have blocked a formal WWII peace treaty.', tags: ['Geopolitics', 'Disputed Territory'] },
  { q: 'Western Sahara is a disputed territory primarily contested between Morocco and:', opts: ['The Polisario Front (Sahrawi)', 'Algeria directly', 'Mauritania', 'Spain'], a: 0, e: 'Morocco controls much of Western Sahara, while the Polisario Front seeks an independent Sahrawi Arab Democratic Republic.', tags: ['Geopolitics', 'Disputed Territory'] },
  { q: 'The island of Cyprus has been politically divided since 1974 between the Republic of Cyprus and a northern entity recognized only by:', opts: ['Turkey', 'Greece', 'Russia', 'the United Kingdom'], a: 0, e: 'The Turkish Republic of Northern Cyprus is recognized solely by Turkey; the rest of the international community recognizes the Republic of Cyprus.', tags: ['Geopolitics', 'Disputed Territory'] },
  { q: 'The Crimean Peninsula, on the Black Sea, was annexed in 2014 by:', opts: ['Russia', 'Turkey', 'Romania', 'Georgia'], a: 0, e: 'Russia annexed Crimea from Ukraine in 2014, an action not recognized by most of the international community.', tags: ['Geopolitics', 'Flashpoints'] },
];
