// Real Analysis roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const realAnalysisSeeds: Seed[] = [
  // ── Level 1 — The Real Numbers ──
  { q: 'What is the supremum of the open interval (0, 1)?', opts: ['0', '1', '1/2', 'It does not exist'], a: 1, e: 'The least upper bound of (0, 1) is 1, even though 1 is not in the set.', tags: ['Real Analysis', 'Real Numbers'] },
  { q: 'What is the infimum of the set {1/n : n = 1, 2, 3, ...}?', opts: ['1', '1/2', '0', 'It does not exist'], a: 2, e: 'The terms 1/n decrease toward 0, so 0 is the greatest lower bound, though it is never attained.', tags: ['Real Analysis', 'Real Numbers'] },
  { q: 'The completeness axiom of R states that every nonempty set that is bounded above has a:', opts: ['Maximum element', 'Least upper bound in R', 'Rational upper bound', 'Finite number of elements'], a: 1, e: 'Completeness guarantees a supremum (least upper bound) in R for any nonempty set bounded above.', tags: ['Real Analysis', 'Real Numbers'] },
  { q: 'The inequality |x| < 3 is equivalent to:', opts: ['x < 3', '-3 < x < 3', 'x > -3', 'x < -3 or x > 3'], a: 1, e: 'By definition of absolute value, |x| < 3 means x lies strictly between -3 and 3.', tags: ['Real Analysis', 'Real Numbers'] },
  { q: 'The solution set of |x - 5| < 2 is:', opts: ['(3, 7)', '(-7, -3)', '(5, 7)', '(-2, 2)'], a: 0, e: '|x - 5| < 2 means -2 < x - 5 < 2, i.e. 3 < x < 7.', tags: ['Real Analysis', 'Real Numbers'] },
  { q: 'The triangle inequality for real numbers states that for all x, y:', opts: ['|x + y| >= |x| + |y|', '|x + y| <= |x| + |y|', '|x + y| = |x| + |y|', '|x - y| = |x| - |y|'], a: 1, e: 'The absolute value of a sum never exceeds the sum of the absolute values.', tags: ['Real Analysis', 'Real Numbers'] },
  { q: 'The Archimedean property of R states that:', opts: ['R is uncountable', 'For every real x there is a natural n with n > x', 'Every bounded set has a maximum', 'The rationals are complete'], a: 1, e: 'The Archimedean property says the naturals are unbounded: for any real x, some natural number exceeds it.', tags: ['Real Analysis', 'Real Numbers'] },
  { q: 'Which statement about the supremum of a set S is correct?', opts: ['sup S must belong to S', 'sup S must be irrational', 'sup S may or may not belong to S', 'sup S equals the maximum always'], a: 2, e: 'A supremum need not be an element of the set; e.g. sup (0,1) = 1 is not in (0,1).', tags: ['Real Analysis', 'Real Numbers'] },

  // ── Level 2 — Sequences and Limits ──
  { q: 'The statement lim a_n = L means: for every epsilon > 0 there exists N such that:', opts: ['n > N implies |a_n - L| < epsilon', 'n < N implies |a_n - L| < epsilon', '|a_n - L| < epsilon for some n', 'a_n = L for all n > N'], a: 0, e: 'Convergence requires that beyond some index N, all terms lie within epsilon of L.', tags: ['Real Analysis', 'Sequences'] },
  { q: 'What is the limit of the sequence a_n = n / (n + 1)?', opts: ['0', '1', 'infinity', 'It does not exist'], a: 1, e: 'Dividing by n gives 1 / (1 + 1/n), which tends to 1 as n grows.', tags: ['Real Analysis', 'Sequences'] },
  { q: 'The Monotone Convergence Theorem states that a sequence converges if it is:', opts: ['Bounded only', 'Monotone only', 'Monotone and bounded', 'Alternating'], a: 2, e: 'A monotone sequence that is also bounded must converge (to its supremum or infimum).', tags: ['Real Analysis', 'Sequences'] },
  { q: 'Which statement is always true about a convergent sequence?', opts: ['It is monotone', 'It is bounded', 'It is positive', 'It has a maximum term'], a: 1, e: 'Every convergent sequence is bounded, since terms eventually cluster near the limit.', tags: ['Real Analysis', 'Sequences'] },
  { q: 'Does the sequence a_n = (-1)^n converge?', opts: ['Yes, to 1', 'Yes, to 0', 'No, it oscillates between -1 and 1', 'Yes, to -1'], a: 2, e: 'The terms alternate between 1 and -1 and never settle near a single value, so the limit does not exist.', tags: ['Real Analysis', 'Sequences'] },
  { q: 'The Squeeze (Sandwich) Theorem concludes lim b_n = L when:', opts: ['a_n <= b_n <= c_n and lim a_n = lim c_n = L', 'b_n is bounded', 'b_n is monotone', 'a_n <= b_n only'], a: 0, e: 'If b_n is trapped between two sequences both converging to L, then b_n also converges to L.', tags: ['Real Analysis', 'Sequences'] },
  { q: 'A sequence (a_n) is Cauchy if for every epsilon > 0 there is N such that:', opts: ['|a_n - a_m| < epsilon for all n, m > N', '|a_n| < epsilon for all n > N', 'a_n is monotone past N', '|a_n - L| < epsilon'], a: 0, e: 'The Cauchy criterion requires terms to become arbitrarily close to each other beyond some index.', tags: ['Real Analysis', 'Sequences'] },
  { q: 'In R, a sequence converges if and only if it is:', opts: ['Bounded', 'Monotone', 'Cauchy', 'Positive'], a: 2, e: 'R is complete, so a sequence converges exactly when it is Cauchy.', tags: ['Real Analysis', 'Sequences'] },

  // ── Level 3 — Infinite Series ──
  { q: 'The geometric series sum of r^n from n = 0 converges if and only if:', opts: ['|r| < 1', '|r| > 1', 'r > 0', 'r is rational'], a: 0, e: 'A geometric series converges precisely when the common ratio satisfies |r| < 1, to 1/(1 - r).', tags: ['Real Analysis', 'Series'] },
  { q: 'The harmonic series, the sum of 1/n, is:', opts: ['Convergent to 1', 'Convergent to e', 'Divergent', 'Convergent to ln 2'], a: 2, e: 'Despite terms tending to 0, the harmonic series diverges (its partial sums grow without bound).', tags: ['Real Analysis', 'Series'] },
  { q: 'The p-series, the sum of 1/n^p, converges if and only if:', opts: ['p > 1', 'p < 1', 'p >= 1', 'p > 0'], a: 0, e: 'A p-series converges exactly when p > 1 and diverges otherwise.', tags: ['Real Analysis', 'Series'] },
  { q: 'The nth-term (divergence) test says a series diverges if:', opts: ['a_n tends to 0', 'a_n does not tend to 0', 'a_n is positive', 'a_n is decreasing'], a: 1, e: 'If the terms fail to approach 0, the series cannot converge. (a_n tending to 0 is necessary, not sufficient.)', tags: ['Real Analysis', 'Series'] },
  { q: 'The ratio test guarantees convergence of the sum of a_n when:', opts: ['lim |a_{n+1}/a_n| < 1', 'lim |a_{n+1}/a_n| > 1', 'lim |a_{n+1}/a_n| = 1', 'a_n is bounded'], a: 0, e: 'If the limiting ratio of consecutive terms is below 1, the series converges absolutely.', tags: ['Real Analysis', 'Series'] },
  { q: 'The alternating series test requires that the term magnitudes b_n:', opts: ['Increase to infinity', 'Decrease monotonically to 0', 'Are constant', 'Are all equal'], a: 1, e: 'An alternating series converges if b_n decreases monotonically and tends to 0.', tags: ['Real Analysis', 'Series'] },
  { q: 'If the sum of |a_n| converges, then the sum of a_n:', opts: ['Diverges', 'Converges (absolute convergence)', 'May diverge', 'Equals 0'], a: 1, e: 'Absolute convergence implies convergence of the original series.', tags: ['Real Analysis', 'Series'] },
  { q: 'The root test examines the limit of:', opts: ['a_{n+1}/a_n', 'the nth root of |a_n|', 'n times a_n', 'a_n^2'], a: 1, e: 'The root test uses lim of |a_n|^(1/n); a value below 1 gives convergence.', tags: ['Real Analysis', 'Series'] },

  // ── Level 4 — Continuity ──
  { q: 'f is continuous at a if for every epsilon > 0 there is delta > 0 such that:', opts: ['|x - a| < delta implies |f(x) - f(a)| < epsilon', '|f(x) - f(a)| < delta implies |x - a| < epsilon', 'f(x) = f(a) for all x', 'x = a'], a: 0, e: 'Continuity means inputs close to a (within delta) produce outputs close to f(a) (within epsilon).', tags: ['Real Analysis', 'Continuity'] },
  { q: 'The Intermediate Value Theorem applies to a function that is:', opts: ['Continuous on a closed interval [a, b]', 'Differentiable everywhere', 'Monotone', 'Bounded only'], a: 0, e: 'The IVT requires continuity on a closed interval; it then takes every value between f(a) and f(b).', tags: ['Real Analysis', 'Continuity'] },
  { q: 'The Extreme Value Theorem states a continuous function on [a, b]:', opts: ['Is differentiable', 'Attains a maximum and a minimum', 'Is unbounded', 'Has no zeros'], a: 1, e: 'A function continuous on a closed, bounded interval attains both a maximum and a minimum value.', tags: ['Real Analysis', 'Continuity'] },
  { q: 'Uniform continuity differs from continuity in that the delta:', opts: ['Depends on the point x', 'Can be chosen independent of the point x', 'Is always 1', 'Equals epsilon'], a: 1, e: 'For uniform continuity a single delta works for every point, given epsilon; ordinary continuity allows delta to vary with the point.', tags: ['Real Analysis', 'Continuity'] },
  { q: 'A continuous function on a compact set (closed and bounded interval) is:', opts: ['Unbounded', 'Uniformly continuous', 'Differentiable', 'Monotone'], a: 1, e: 'The Heine-Cantor theorem: continuity on a compact set implies uniform continuity.', tags: ['Real Analysis', 'Continuity'] },
  { q: 'Which relationship between continuity and uniform continuity is correct?', opts: ['Continuity implies uniform continuity everywhere', 'Uniform continuity implies continuity', 'They are equivalent on all of R', 'Neither implies the other'], a: 1, e: 'Uniform continuity is the stronger condition, so it always implies ordinary continuity; the converse can fail.', tags: ['Real Analysis', 'Continuity'] },
  { q: 'By the IVT, a continuous f with f(0) = -1 and f(2) = 3 must:', opts: ['Be increasing', 'Have a zero in (0, 2)', 'Be differentiable', 'Attain a maximum at 2'], a: 1, e: 'Since 0 lies between f(0) = -1 and f(2) = 3, the IVT guarantees a root in the open interval.', tags: ['Real Analysis', 'Continuity'] },
  { q: 'The composition g of f of two continuous functions is:', opts: ['Continuous', 'Discontinuous', 'Constant', 'Not necessarily defined'], a: 0, e: 'The composition of continuous functions is continuous wherever it is defined.', tags: ['Real Analysis', 'Continuity'] },

  // ── Level 5 — Differentiation and Integration ──
  { q: 'The Mean Value Theorem requires f continuous on [a, b] and differentiable on (a, b), then guarantees a c with:', opts: ["f'(c) = (f(b) - f(a)) / (b - a)", "f'(c) = 0", 'f(c) = 0', "f'(c) = f(c)"], a: 0, e: 'The MVT gives a point where the instantaneous slope equals the average slope over [a, b].', tags: ['Real Analysis', 'Differentiation'] },
  { q: "Rolle's Theorem is the special case of the MVT where:", opts: ['f(a) = f(b)', 'f is constant', 'a = b', "f'(a) = 0"], a: 0, e: "When f(a) = f(b), the MVT yields a point c where f'(c) = 0, which is Rolle's Theorem.", tags: ['Real Analysis', 'Differentiation'] },
  { q: 'If f is differentiable at a point, then at that point f is:', opts: ['Continuous', 'Constant', 'Monotone', 'Bounded above'], a: 0, e: 'Differentiability implies continuity, though the converse need not hold.', tags: ['Real Analysis', 'Differentiation'] },
  { q: "If f'(x) = 0 for all x in an interval, then on that interval f is:", opts: ['Constant', 'Increasing', 'Zero', 'Discontinuous'], a: 0, e: 'A vanishing derivative throughout an interval forces the function to be constant (a corollary of the MVT).', tags: ['Real Analysis', 'Differentiation'] },
  { q: 'Which condition guarantees that f is Riemann integrable on [a, b]?', opts: ['f is continuous on [a, b]', 'f is unbounded', 'f is differentiable nowhere', 'f is defined on an open interval'], a: 0, e: 'Every function continuous on a closed, bounded interval is Riemann integrable.', tags: ['Real Analysis', 'Integration'] },
  { q: 'The Fundamental Theorem of Calculus (Part 1) states that if F(x) is the integral of f from a to x with f continuous, then:', opts: ["F'(x) = f(x)", "F'(x) = 0", 'F(x) = f(x)', 'F is constant'], a: 0, e: 'The FTC says differentiating the integral of a continuous function recovers the integrand.', tags: ['Real Analysis', 'Integration'] },
  { q: 'The Mean Value Theorem for Integrals states that for f continuous on [a, b], there is c with:', opts: ['the integral of f over [a, b] equals f(c)(b - a)', 'the integral equals 0', "f'(c) = 0", 'f(c) = 0'], a: 0, e: 'There exists a point c where the value f(c) equals the average value of f over the interval.', tags: ['Real Analysis', 'Integration'] },
  { q: 'A bounded function on [a, b] with only finitely many discontinuities is:', opts: ['Not integrable', 'Riemann integrable', 'Necessarily continuous', 'Necessarily differentiable'], a: 1, e: 'Boundedness together with only finitely many discontinuities (a set of measure zero) ensures Riemann integrability.', tags: ['Real Analysis', 'Integration'] },
];
