import type { QuestionTranslation } from './quiz-data';

export const combinationsTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Co je to kombinace? ──
  'rm-combo-1': { introduction: 'Zamysli se, co odlišuje kombinaci od pouhého plánu.', question: 'Co je to „kombinace“ v šachu?', options: ['Vynucená série tahů, obvykle s obětí, která získá materiál nebo dá mat', 'Pomalý plán budovaný během mnoha tichých tahů', 'Jakékoli zahájení odehrané s oběma jezdci', 'Nabídka remízy uprostřed partie'], explanation: 'Kombinace je vynucená série tahů, typicky s obětí, která dosáhne konkrétního zisku, jako je mat nebo zisk materiálu.' },
  'rm-combo-2': { introduction: 'Klíčové slovo je „vynucená“ — co to znamená pro soupeře?', question: 'Kombinace se obvykle popisuje jako „vynucená“. Co to znamená?', options: ['Soupeř má v každém tahu dobré odpovědi', 'Soupeřovy odpovědi jsou v podstatě jedinými rozumnými dostupnými tahy', 'Musí se zahrát v časové tísni', 'Obě strany se na ní předem dohodly'], explanation: 'V kombinaci je každý tah vynucující, takže obránce má prakticky jediné odpovědi, což umožňuje spočítat výsledek až do konce.' },
  'rm-combo-3': { introduction: 'Který prvek je pro kombinaci nejtypičtější?', question: 'Který prvek se v kombinaci vyskytuje nejtypičtěji?', options: ['Pouze výměna pěšce', 'Opakování tahů', 'Oběť', 'Rošáda'], explanation: 'Kombinace obvykle obsahují oběť jako překvapivý prvek, který odemkne konkrétní zisk.' },
  'rm-combo-4': { introduction: 'Jaký je cíl kombinace?', question: 'Jaký je cíl kombinace?', options: ['Zabít čas', 'Zdvořile nabídnout remízu', 'Pomalu rozvíjet figury', 'Dosáhnout konkrétního zisku, jako je mat nebo zisk materiálu'], explanation: 'Na rozdíl od obecného plánu míří kombinace na konkrétní výsledek: mat nebo materiální výhodu.' },
  'rm-combo-5': { introduction: 'Porovnej krátkou taktiku s dlouhodobým plánem.', question: 'Jak se kombinace liší od obecného strategického plánu?', options: ['Kombinace je pomalá a poziční', 'Kombinace nikdy nepoužívá šachy', 'Plán vždy zahrnuje oběť', 'Kombinace je krátká, vynucující taktická série s konkrétním cílem'], explanation: 'Plán je dlouhodobá poziční myšlenka, zatímco kombinace je krátký vynucený taktický výbuch s konkrétním ziskem.' },
  'rm-combo-6': { introduction: 'Který typ tahu dává soupeři nejvíc volnosti?', question: 'Který typ tahu je NEJMÉNĚ vynucující, a tedy nejméně pravděpodobně žene kombinaci?', options: ['Šach', 'Braní', 'Tichý rozvíjející tah', 'Přímá hrozba matu'], explanation: 'Šachy, braní a hrozby jsou vynucující; tichý rozvíjející tah dává soupeři volnost a jen zřídka vynucuje kombinaci.' },
  'rm-combo-7': { introduction: 'Proč lze kombinaci spočítat až do konce?', question: 'Proč lze kombinaci spočítat až úplně do konce?', options: ['Protože se vždy používají počítače', 'Protože soupeřovy odpovědi jsou vynucené', 'Protože šachovnice je malá', 'Protože pěšci se nemohou vracet'], explanation: 'Protože každý tah vynucuje odpověď, větví je málo, takže celou sérii lze spočítat až k jasnému výsledku.' },
  'rm-combo-8': { introduction: 'Jak se nazývá vynucená série, která získá materiál?', question: 'Taktika, která vynuceně získá materiál, se nejlépe nazývá:', options: ['Kombinace', 'Pevnost', 'Zugzwang', 'Fianchetto'], explanation: 'Vynucující série, která získá materiál nebo dá mat, je kombinace; ostatní pojmy popisují nesouvisející myšlenky.' },

  // ── Úroveň 2 — Oběti ──
  'rm-combo-9': { introduction: 'Co znamená obětovat v šachu?', question: 'Co je to oběť v šachu?', options: ['Vzdání se materiálu za větší cíl, jako je mat, útok nebo proměna', 'Výměna figury za rovnocennou', 'Odmítnutí cokoli vzít', 'Rošáda na dámské straně'], explanation: 'Oběť znamená dobrovolné vzdání se materiálu, abychom získali něco většího, jako je mat, vítězný útok nebo proměna.' },
  'rm-combo-10': { introduction: '„Zdánlivá“ (dočasná) oběť se brzy vrátí — jak?', question: '„Zdánlivá“ (dočasná) oběť je taková, která:', options: ['Se nikdy ve skutečnosti nepřijme', 'Vynuceně získá materiál brzy zpět', 'Okamžitě prohraje partii', 'Lze provést pouze pěšcem'], explanation: 'Zdánlivá neboli dočasná oběť získá materiál vynuceně zpět během několika tahů, takže je vypočitatelná a málo riskantní.' },
  'rm-combo-11': { introduction: 'Skutečná oběť je dlouhodobá investice — v čem se liší?', question: '„Skutečná“ (pravá) oběť se liší od zdánlivé oběti tím, že:', options: ['Vždy okamžitě získá materiál zpět', 'Je na turnajích nelegální', 'Je opravdovou dlouhodobou investicí bez okamžitého návratu', 'Nastává pouze v zahájení'], explanation: 'Skutečná oběť je trvalá investice: materiál se vynuceně nevrátí, takže spoléháš na dlouhodobou útočnou hodnotu.' },
  'rm-combo-12': { introduction: 'Vzdáš se jezdce, aby pěšec mohl proměnit — jak se to nazývá?', question: 'Vzdáš se jezdce, aby volný pěšec mohl proměnit v dámu. Toto je:', options: ['Z definice hrubka', 'Patový trik', 'Vynucená remíza', 'Oběť za proměnu'], explanation: 'Vzdání se figury pro vynucení proměny je klasická oběť, kdy měníš materiál nyní za novou dámu.' },
  'rm-combo-13': { introduction: 'Který důvod ospravedlňuje oběť nejlépe?', question: 'Který je nejlepší důvod k provedení oběti?', options: ['Protože máš přebytek figur nazbyt', 'Protože ji soupeř očekává', 'Protože jsi na tahu', 'Protože vynuceně vede k matu nebo rozhodující výhodě'], explanation: 'Zdravá oběť je ospravedlněna konkrétním ziskem, který vynucuje, jako je mat nebo vítězný návrat materiálu.' },
  'rm-combo-14': { introduction: 'Poziční oběť se dává za trvalé poziční výhody.', question: '„Poziční oběť“ se typicky dává za:', options: ['Okamžitý mat', 'Rychlou remízu', 'Dlouhodobou poziční kompenzaci, jako jsou silná pole nebo pěšcová struktura', 'Vůbec nic'], explanation: 'Poziční oběť investuje materiál za trvalé poziční plusy, jako jsou opěrná pole, struktura nebo aktivita figur, spíše než za vynucený mat.' },
  'rm-combo-15': { introduction: 'Kvalita znamená rozdíl mezi věží a lehkou figurou.', question: 'Klasická „oběť kvality“ znamená vzdát se:', options: ['Dámy za věž', 'Věže za střelce nebo jezdce', 'Pěšce za pěšce', 'Střelce za střelce'], explanation: 'Oběť kvality je vzdání se věže (hodnota ~5) za lehkou figuru (~3) pro získání aktivity nebo struktury.' },
  'rm-combo-16': { introduction: 'Před skutečnou obětí je nejdůležitější posoudit kompenzaci.', question: 'Před provedením skutečné oběti je nejdůležitější posoudit:', options: ['Zda výsledný útok nebo kompenzace stojí za materiál', 'Zda běží hodiny', 'Zda je figura tvá oblíbená', 'Zda to vypadá působivě'], explanation: 'Skutečná oběť musí být ospravedlněna vyhodnocením kompenzace, protože materiál se prostě nevrátí.' },

  // ── Úroveň 3 — Odklonění (deflection) ──
  'rm-combo-17': { introduction: 'Odklonění nutí figuru opustit její obranný úkol.', question: 'Co je to odklonění (deflection)?', options: ['Vynucení, aby nepřátelská figura opustila důležitý obranný úkol', 'Nalákání figury k tvému králi', 'Zablokování vlastního střelce', 'Výměna dam pro zjednodušení'], explanation: 'Odklonění nutí bránící figuru opustit klíčový úkol, takže to, co hlídala, poté padne.' },
  'rm-combo-18': { introduction: 'Věž hlídá matové pole na poslední řadě — sundej ji odtud.', question: 'Věž hlídá matové pole na poslední řadě. Přinutíš ji vzít jinde a pak dáš mat. Tato taktika je:', options: ['Rošáda', 'Odklonění', 'Podproměna', 'Pat'], explanation: 'Stažení obránce z matového pole, aby mat prošel, je učebnicové odklonění.' },
  'rm-combo-19': { introduction: 'Odklonění útočí na figuru s jakou rolí?', question: 'Odklonění funguje útokem na figuru, která má jakou roli?', options: ['Čistě útočnou roli', 'Žádnou roli', 'Obranný úkol, který nemůže bezpečně opustit', 'Pouze blokující roli v zahájení'], explanation: 'Odklonění míří na figuru vázanou obranným úkolem; její odehnání učiní to, co bránila, zranitelným.' },
  'rm-combo-20': { introduction: 'Nejvynucenější způsob, jak odklonit obránce?', question: 'Který tah je nejvynucenější způsob, jak odklonit obránce?', options: ['Tichý postup pěšce', 'Nabídka remízy', 'Postup věže o dvě pole', 'Šach nebo braní, na které obránce musí odpovědět'], explanation: 'Vynucující šach nebo braní nutí obránce reagovat a stahuje ho z jeho postu; tiché tahy mu umožní zůstat.' },
  'rm-combo-21': { introduction: 'Dáma na d7 je jediný obránce poslední řady.', question: 'Dáma na d7 je jediným obráncem poslední řady. Zahrání tahu, který vynutí ...Dxd7, abys mohl dát mat na poslední řadě, je příkladem:', options: ['Clonění (interference)', 'Mezitahu (zwischenzug)', 'Fianchetta', 'Odklonění'], explanation: 'Odkloníš dámu od hlídání poslední řady tím, že ji přinutíš vzít, a pak zasadíš mat na poslední řadě.' },
  'rm-combo-22': { introduction: '„Odstranění obránce“ znamená napadnout ochránce cíle.', question: 'Běžné téma odklonění „odstranění obránce“ znamená:', options: ['Hlídat vlastního krále', 'Postoupit všechny pěšce', 'Napadnout figuru chránící klíčový cíl, aby cíl padl', 'Vyměnit věže na otevřeném sloupci'], explanation: 'Odstranění obránce eliminuje nebo odežene ochránce figury či pole, takže se cíl stane dobytelným.' },
  'rm-combo-23': { introduction: 'Odklonění i přetížení zneužívají přetíženého obránce.', question: 'Odklonění a přetížení spolu souvisejí, protože obojí zneužívá:', options: ['Uzavřený střed', 'Obránce, který nemůže splnit všechny své úkoly', 'Pouze nerošovaného krále', 'Volného pěšce'], explanation: 'Obojí kořistí z přetíženého či vázaného obránce; odklonění ho odežene, zatímco přetížení mu dá příliš mnoho úkolů.' },
  'rm-combo-24': { introduction: 'Doplň: odklonění nutí figuru ___ od jejího postu.', question: 'Co nejlépe doplní myšlenku: „Odklonění nutí figuru ___ od jejího postu.“', options: ['pryč', 'k', 'kolem', 'za'], explanation: 'Odklonění nutí bránící figuru PRYČ od úkolu, který plnila.' },

  // ── Úroveň 4 — Návnada a přilákání ──
  'rm-combo-25': { introduction: 'Návnada láká figuru NA konkrétní špatné pole.', question: 'Co je to taktika návnady (přilákání)?', options: ['Nalákání nepřátelské figury NA konkrétní špatné pole', 'Vynucení, aby figura opustila pole', 'Zablokování diagonály pěšcem', 'Nabídka remízy pro rozptýlení'], explanation: 'Návnada neboli přilákání láká nepřátelskou figuru na pole, kde ji lze napadnout, vidličkou zasáhnout nebo dát mat.' },
  'rm-combo-26': { introduction: 'Oběť dámy stáhne krále na pole vidličky.', question: 'Oběť dámy, která stáhne nepřátelského krále na pole, kde pak jezdec vidličkou napadne krále a dámu, je:', options: ['Odklonění', 'Návnada (přilákání)', 'Uvolnění (clearance)', 'Clonění'], explanation: 'Přilákání krále na pole vidličky obětí dámy je klasická návnada vedoucí k jezdcové vidličce.' },
  'rm-combo-27': { introduction: 'Návnada láká NA pole, odklonění žene PRYČ od úkolu.', question: 'Jak se liší návnada a odklonění?', options: ['Jsou totožné', 'Návnada používá pouze pěšce', 'Návnada láká figuru NA pole; odklonění ji žene PRYČ od úkolu', 'Odklonění funguje pouze proti králi'], explanation: 'Návnada táhne figuru na špatné pole, zatímco odklonění žene figuru pryč od obranného úkolu.' },
  'rm-combo-28': { introduction: 'Vylákání krále do otevřeného prostoru připravuje co?', question: 'Přilákání nepřátelského krále do otevřeného prostoru je často přípravou pro:', options: ['Tichou koncovku', 'Pěšcovou bouři na vzdálené straně', 'Opakování pozice', 'Matovou síť nebo vidličku'], explanation: 'Jakmile je král stažen na exponované pole, šachy mohou uplést matovou síť nebo získat materiál vidličkou.' },
  'rm-combo-29': { introduction: 'Šach, který král musí vzít a přejít na osudné pole.', question: 'Šach, který král MUSÍ vzít, čímž skončí na osudném poli, využívá téma:', options: ['Zugzwangu', 'Pevnosti', 'Profylaxe', 'Přilákání'], explanation: 'Vynucení, aby král vzal a tím vkročil na prohrávající pole, je motiv přilákání (návnady).' },
  'rm-combo-30': { introduction: 'Která figura se nejčastěji obětuje k vylákání krále?', question: 'Která figura se ve slavných kombinacích nejčastěji obětuje k vylákání nepřátelského krále?', options: ['Jediný pěšec', 'Král', 'Dáma', 'Věž, která právě rošovala'], explanation: 'Dáma, jakožto nejcennější figura, tvoří dramatickou oběť návnady, kterou král nebo obránce musí přijmout.' },
  'rm-combo-31': { introduction: 'Smysl nalákání figury na dané pole je připravit co?', question: 'Smyslem nalákání figury na konkrétní pole je obvykle:', options: ['Učinit ji silnější', 'Připravit navazující taktiku, jako je vidlička, vazba nebo mat na tomto poli', 'Vynutit remízu', 'Dát jí větší pohyblivost'], explanation: 'Nalákaná figura přistane tam, kde ji připravená vidlička, vazba, rentgen nebo mat okamžitě potrestá.' },
  'rm-combo-32': { introduction: 'Pokud soupeř oběť návnady odmítne, obvykle na tom jsi jak?', question: 'Pokud v kombinaci s návnadou soupeř nabídnutou oběť odmítne, obvykle:', options: ['Často jsi už něco získal nebo udržel hrozbu naživu', 'Automaticky prohráváš', 'Musíš se vzdát', 'Opakuješ pozici donekonečna'], explanation: 'Zdravá návnada je spočítaná tak, že odmítnutí tě stále nechává v lepší pozici nebo udrží silnou hrozbu, nejen v přijaté variantě.' },

  // ── Úroveň 5 — Clonění a uvolnění ──
  'rm-combo-33': { introduction: 'Clonění PŘETNE linii mezi nepřátelskou figurou a cílem.', question: 'Co je to clonění (interference)?', options: ['Vložení figury, které PŘETNE linii mezi nepřátelskou figurou a tím, co brání', 'Uvolnění pole pro vlastní figuru', 'Výměna všech lehkých figur', 'Zarošování do bezpečí'], explanation: 'Clonění vsadí figuru mezi nepřátelskou linijovou figuru a její cíl, čímž přetne obranu nebo spojení.' },
  'rm-combo-34': { introduction: 'Uvolnění uvolní pole nebo linii pro VLASTNÍ figuru.', question: 'Co je to uvolnění (clearance)?', options: ['Přetnutí nepřátelské obranné linie', 'Uvolnění pole nebo linie, aby ji mohla využít TVÁ VLASTNÍ figura', 'Zdvojení věží', 'Věčný šach'], explanation: 'Uvolnění vyprázdní pole nebo otevře linii, aby ji jedna z tvých vlastních figur mohla obsadit nebo po ní cestovat.' },
  'rm-combo-35': { introduction: 'Oběť uvolnění otevírá linii nebo pole pro útok.', question: '„Oběť uvolnění“ typicky vzdává materiál, aby:', options: ['Zablokovala soupeřova střelce', 'Vyměnila dámy', 'Otevřela klíčovou linii nebo uvolnila klíčové pole pro tvůj útok', 'Získala vzdáleného pěšce'], explanation: 'Oběť uvolnění odstraní vlastní překážku, aby se rozhodující linie nebo pole zpřístupnily jiné figuře.' },
  'rm-combo-36': { introduction: 'Vložíš jezdce mezi střelce a jím bráněnou věž.', question: 'Střelec na dlouhé diagonále brání věž na druhé straně. Umístíš mezi ně jezdce a přetneš obranu. To je:', options: ['Uvolnění', 'Návnada', 'Mezitah', 'Clonění'], explanation: 'Vložení jezdce, které přeruší obrannou linii střelce, je clonění.' },
  'rm-combo-37': { introduction: 'Proti kterým figurám lze clonit?', question: 'Clonění je možné pouze proti kterým druhům nepřátelských figur?', options: ['Jezdcům a králům', 'Pouze pěšcům', 'Pouze králi', 'Linijovým figurám: dámě, věži a střelci'], explanation: 'Pouze linijové figury (dáma, věž, střelec) působí podél linií, do nichž lze vložit jinou figuru jako clonu.' },
  'rm-combo-38': { introduction: 'Vlastní jezdec blokuje cestu dámy na h5.', question: 'Potřebuješ, aby tvá dáma dosáhla h5, ale cestu blokuje tvůj vlastní jezdec. Obětování tohoto jezdce, aby se otevřela cesta, je:', options: ['Odklonění', 'Mat na poslední řadě', 'Oběť uvolnění', 'Přetížení'], explanation: 'Odstranění vlastního blokujícího jezdce, aby se uvolnila cesta dámy, je oběť uvolnění.' },
  'rm-combo-39': { introduction: 'Clonění blokuje NEPŘÍTELE, uvolnění otevírá TOBĚ.', question: 'Klíčový rozdíl mezi cloněním a uvolněním je:', options: ['Jsou to tytéž myšlenky', 'Clonění blokuje NEPŘÁTELSKOU linii; uvolnění otevírá TVOU VLASTNÍ linii nebo pole', 'Clonění používá pouze pěšce', 'Uvolnění nastává pouze v koncovkách'], explanation: 'Clonění blokuje soupeřovu linii, zatímco uvolnění uvolňuje linii nebo pole pro tvou vlastní figuru.' },
  'rm-combo-40': { introduction: 'Vložená figura přetne spojení mezi dvěma nepřátelskými figurami.', question: 'Slavná myšlenka clonění umístí figuru mezi dvě nepřátelské figury, takže se už nemohou:', options: ['Bránit ani komunikovat mezi sebou', 'Útočit na tvého krále', 'Ovládat střed', 'Vůbec táhnout'], explanation: 'Vložená figura přeruší spojení, takže se obě nepřátelské figury už nemohou navzájem bránit.' },

  // ── Úroveň 6 — Mezitah (zwischenzug) ──
  'rm-combo-41': { introduction: 'Mezitah je nečekaný vynucující tah před očekávaným zpětným braním.', question: 'Co je to mezitah (zwischenzug)?', options: ['Nečekaný vynucující „mezitah“ vložený před očekávaným zpětným braním', 'Pomalý manévr v koncovce', 'Typ pěšcové struktury', 'Vynucená remíza opakováním'], explanation: 'Mezitah (intermezzo) je vsunutý tah, obvykle šach nebo větší hrozba, zahraný před dokončením očekávaného zpětného braní.' },
  'rm-combo-42': { introduction: 'Jak se německé slovo „zwischenzug“ obvykle překládá?', question: 'Slovo „zwischenzug“ se často překládá jako:', options: ['„Koncový tah“', '„Mezitah“ neboli intermezzo', '„Volný pěšec“', '„Vidlička“'], explanation: 'Zwischenzug je německy „mezitah“, nazývaný také intermezzo.' },
  'rm-combo-43': { introduction: 'Proč je mezitah účinný?', question: 'Proč je mezitah účinný?', options: ['Pouze plýtvá soupeřovým časem', 'Je to vždy tah dámou', 'Vsune vynucenější hrozbu před očekávanou odpovědí, čímž změní výsledek', 'Ukončí partii remízou'], explanation: 'Vsunutím větší hrozby před zpětným braním může mezitah získat materiál navíc nebo změnit hodnocení.' },
  'rm-combo-44': { introduction: 'Místo okamžitého braní dáš nejdřív šach, který získá věž.', question: 'Místo okamžitého zpětného braní figury nejprve dáš šach, který získá věž, A PAK vezmeš zpět. Tento šach je:', options: ['Fianchetto', 'Pat', 'Rošáda', 'Mezitah'], explanation: 'Vsunutý šach zahraný před zpětným braním je mezitah, který využívá toho, že zpětné braní může počkat.' },
  'rm-combo-45': { introduction: 'Mezitah bývá obvykle jaký typ tahu?', question: 'Mezitah je obvykle jaký typ tahu, aby vynutil odpověď?', options: ['Tichý ústup', 'Tah pěšce na kraj', 'Nabídka remízy', 'Šach, braní nebo silná hrozba'], explanation: 'Aby byl mezitah účinný, musí být sám vynucující, nejčastěji šach, braní nebo vážná hrozba.' },
  'rm-combo-46': { introduction: 'Nebezpečí předpokladu, že zpětné braní je „samozřejmé“.', question: 'Nebezpečí předpokladu, že zpětné braní je „samozřejmé“, spočívá v tom, že můžeš přehlédnout:', options: ['Vzdání se soupeře', 'Pravidlo padesáti tahů', 'Mezitah, na který se musí odpovědět nejdřív', 'Pat'], explanation: 'Hráči často přehlédnou mezitah, protože zpětné braní berou jako automatické, přičemž vynucující intermezzo přichází nejdřív.' },
  'rm-combo-47': { introduction: 'Po zodpovězení mezitahu hráč obvykle udělá co?', question: 'Poté, co je mezitah zodpovězen, hráč obvykle:', options: ['Vzdá se', 'Vrátí se k původně zamýšlenému braní, nyní za výhodnějších podmínek', 'Nabídne remízu', 'Přijde o dámu'], explanation: 'Jakmile je vynucující mezitah zodpovězen, hráč dokončí odložené zpětné braní, přičemž mezitím získal.' },
  'rm-combo-48': { introduction: 'Mezitah nejčastěji využívá faktu, že figura zůstane vzatelná.', question: 'Mezitah nejčastěji využívá faktu, že soupeřova figura:', options: ['Bude stále vzatelná i poté, co se vypořádáme s vynucujícím tahem', 'Se vůbec nemůže hnout', 'Je bráněna dvakrát', 'Už proměnila'], explanation: 'Intermezzo funguje, protože visící figura nikam neuteče, takže lze nejprve vsunout ještě vynucenější tah.' },

  // ── Úroveň 7 — Matové kombinace ──
  'rm-combo-49': { introduction: 'Mat na poslední řadě funguje, protože král je uvězněn za pěšci.', question: 'Mat na poslední řadě dává mat, protože král je:', options: ['Uvězněn na poslední řadě za vlastními nepohnutými pěšci', 'Ve středu šachovnice', 'Chráněn fianchettem', 'Už zarošován na dámské straně'], explanation: 'Při matu na poslední řadě král nemůže uniknout dopředu, protože ho blokují vlastní pěšci, a věž nebo dáma dá mat podél řady.' },
  'rm-combo-50': { introduction: 'Kterou figurou se dává udušený mat?', question: 'Udušený mat je dán kterou figurou?', options: ['Střelcem', 'Jezdcem', 'Věží', 'Pěšcem'], explanation: 'Udušený mat dává jezdec králi zcela uzavřenému vlastními figurami.' },
  'rm-combo-51': { introduction: 'Philidorův odkaz končí kterou sérií tahů?', question: 'Philidorův odkaz (klasický udušený mat) proslule končí kterou sérií?', options: ['Sxh7+ Kxh7, Jg5+', 'Vd8+ Vxd8, Dxd8#', 'Dg8+ Vxg8, Jf7#', 'O-O-O a Vd1'], explanation: 'Udušený mat končí Dg8+! Vxg8 Jf7#, kdy oběť dámy vynutí, aby věž zapečetila králi poslední únikové pole.' },
  'rm-combo-52': { introduction: 'Bodenův mat dávají jaké figury?', question: 'Bodenův mat je dán:', options: ['Dámou a jezdcem', 'Dvěma věžemi na sloupci', 'Jediným pěšcem', 'Dvěma střelci na křížících se diagonálách'], explanation: 'Bodenův mat využívá dva střelce mířící po protínajících se diagonálách, aby uvěznil zarošovaného krále.' },
  'rm-combo-53': { introduction: 'Oběť „řecký dar“ klasicky začíná kterým tahem?', question: 'Oběť „řecký dar“ klasicky začíná kterým tahem proti zarošovanému králi?', options: ['Jxf7', 'Vxh8', 'Dxd7', 'Sxh7+'], explanation: 'Řecký dar je oběť střelce Sxh7+, která roztrhne králův kryt a přivede dámu a jezdce k útoku.' },
  'rm-combo-54': { introduction: 'Anastáziin mat obvykle dávají které figury?', question: 'Anastáziin mat je vzor typicky daný:', options: ['Dvojicí pěšců', 'Osamělým střelcem', 'Jezdcem a věží, které přitlačí krále ke kraji', 'Pouze králem a dámou'], explanation: 'Anastáziin mat využívá jezdce spolu s věží, aby přitlačil krále k okraji šachovnice.' },
  'rm-combo-55': { introduction: 'Legalův mat je slavná past zahrnující co?', question: 'Legalův mat je slavná past, která zahrnuje:', options: ['Přesun věže po sloupci h', 'Oběť dámy následovanou matem lehkými figurami', 'Proměnu pěšce v jezdce', 'Patový trik'], explanation: 'Při Legalově matu jedna strana obětuje dámu a dá mat lehkými figurami (střelcem a jezdci).' },
  'rm-combo-56': { introduction: 'Který z nich je skutečně pojmenovaný matový vzor?', question: 'Který z těchto je skutečný pojmenovaný matový vzor?', options: ['Udušený mat', 'Fianchettový mat', 'Zugzwangový mat', 'Uvolňovací mat'], explanation: 'Udušený mat je skutečný, dobře známý vzor; ostatní tři názvy nejsou standardními matovými vzory.' },

  // ── Úroveň 8 — Přetížení ──
  'rm-combo-57': { introduction: 'Přetížená figura má příliš mnoho obranných úkolů.', question: 'Co znamená „přetížení“ v taktice?', options: ['Jedna figura má příliš mnoho obranných úkolů, takže napadení jednoho z nich způsobí pád druhého', 'Mít příliš mnoho pěšců', 'Umístit všechny figury na jeden sloupec', 'Proměnit dva pěšce'], explanation: 'Přetížená figura je zatížena více než jedním obranným úkolem; udeř na jeden a druhý se zhroutí.' },
  'rm-combo-58': { introduction: 'Jezdec je jediný obránce matového pole i visícího střelce.', question: 'Jezdec je jediným obráncem ZÁROVEŇ matového pole a visícího střelce. Tento jezdec je:', options: ['Absolutně vázaný', 'Přetížený', 'Fianchettovaný', 'Mezitah'], explanation: 'Protože jeden jezdec musí hlídat dvě věci najednou, je přetížený a můžeš využít kterýkoli úkol, na který zaútočíš.' },
  'rm-combo-59': { introduction: 'Jak zpravidla využiješ přetíženého obránce?', question: 'K využití přetíženého obránce obvykle:', options: ['Ho ignoruješ', 'Nejprve vyměníš dámy', 'Napadneš nebo eliminuješ ho na jednom z jeho úkolů, takže druhý cíl padne', 'Nabídneš remízu'], explanation: 'Přinutíš přetíženou figuru vypořádat se s jednou hrozbou, načež už druhou povinnost nelze splnit.' },
  'rm-combo-60': { introduction: 'Přetížení úzce souvisí s kterou další taktikou?', question: 'Přetížení úzce souvisí s kterou další taktikou?', options: ['Rošádou', 'Braním mimochodem', 'Řeckým darem', 'Odklonění / odstranění obránce'], explanation: 'Přetížení a odklonění obojí zneužívají obránce, který nemůže pokrýt všechno, a nutí ho opustit jeden z jeho úkolů.' },
  'rm-combo-61': { introduction: 'Dáma brání f7 (proti matu) i volnou věž.', question: 'Dáma brání jak f7 (proti matu), tak volnou věž. Vezmeš věž; ona vezme zpět; pak přijde mat na f7. Dáma byla:', options: ['Patová', 'Proměněná', 'Napadená rentgenem', 'Přetížená'], explanation: 'Dáma nemohla splnit obě povinnosti, takže odstranění jednoho obránce vzetím věže ponechalo f7 osudově nebráněné.' },
  'rm-combo-62': { introduction: 'Nejlepší pole k napadení při přetížení je které?', question: 'Nejlepší pole k napadení při využívání přetížení je to, kde obránce:', options: ['Má nejméně tahů', 'Je plně chráněn', 'Je nucen opustit svůj důležitější úkol', 'Nemůže být vzat'], explanation: 'Cílíš na to, aby přetížená figura musela volit, a vynutíš, aby opustila úkol, jehož ztráta je nejškodlivější.' },
  'rm-combo-63': { introduction: 'Přetížená figura se někdy popisuje jako jaká?', question: 'Přetížená figura se někdy popisuje jako:', options: ['„Fianchettovaná“', '„Příliš zaneprázdněná“ / dělá příliš mnoho úkolů', '„En prise“ z vlastní vůle', '„Mezitah“'], explanation: 'Přetížené figury jsou hovorově „příliš zaneprázdněné“, rozprostřené mezi více obrannými úkoly, než zvládnou.' },
  'rm-combo-64': { introduction: 'Rozpoznání přetížení začíná kterou otázkou?', question: 'Rozpoznání přetížení začíná otázkou:', options: ['Která nepřátelská figura dělá více než jeden obranný úkol?', 'Který pěšec je volný?', 'Který sloupec je otevřený?', 'Kde je můj král nejbezpečnější?'], explanation: 'Odhalení přetížení začíná identifikací obránce pověřeného hlídáním dvou nebo více kritických bodů.' },

  // ── Úroveň 9 — Výpočet kombinací ──
  'rm-combo-65': { introduction: 'Které tahy bys měl při výpočtu zkoumat nejdřív?', question: 'Které tahy bys měl při výpočtu zkoumat NEJDŘÍV?', options: ['Vynucující tahy: šachy, braní a hrozby', 'Tiché vyčkávací tahy', 'Pouze tahy pěšci', 'Pouze obranné tahy'], explanation: 'Dobrý výpočet začíná nejvynucenějšími tahy — šachy, braním a hrozbami — protože omezují soupeřovy odpovědi.' },
  'rm-combo-66': { introduction: 'Kombinaci bys měl obecně počítat až kam?', question: 'Kombinaci bys měl obecně počítat, dokud nedosáhneš:', options: ['Pouze úplně prvního šachu', 'Tiché, posouditelné pozice, kterou umíš vyhodnotit', 'Náhodného středního bodu', 'Soupeřovy časové tísně'], explanation: 'Počítej až do tiché pozice, kde vynucující tahy skončí, abys mohl spolehlivě posoudit, kdo stojí lépe.' },
  'rm-combo-67': { introduction: 'Co je to „kandidátský tah“?', question: 'Co je to „kandidátský tah“?', options: ['Tah, který soupeř slíbil zahrát', 'Jakýkoli náhodný legální tah', 'Tah, který v pozici vážně zvažuješ a analyzuješ', 'Pouze tah pěšcem'], explanation: 'Kandidátské tahy jsou hrstka slibných možností, které v dané pozici identifikuješ a poté počítáš.' },
  'rm-combo-68': { introduction: 'Proč počítat soupeřovu nejtvrdošíjnější obranu?', question: 'Proč počítat soupeřovu nejtvrdošíjnější obranu spíše než odpověď, ve kterou doufáš?', options: ['Abys byl zdvořilý', 'Je to šachové pravidlo', 'Abys ušetřil čas na hodinách', 'Protože kombinace funguje jen tehdy, když porazí NEJLEPŠÍ obranu'], explanation: 'Kombinace je zdravá jen tehdy, když uspěje proti soupeřově nejsilnější odpovědi, takže musíš prověřit nejlepší obranu.' },
  'rm-combo-69': { introduction: 'Návyk prověřovat každý šach, braní a hrozbu čemu brání?', question: 'Návyk prověřovat každý šach, braní a hrozbu v každém tahu je nástroj, jak se vyhnout:', options: ['Předčasné rošádě', 'Hraní zahájení', 'Remíze', 'Přehlédnutí vynucujícího prostředku pro kteroukoli stranu'], explanation: 'Prohledávání všech šachů, braní a hrozeb tě chrání před přehlédnutím taktiky — tvé nebo soupeřovy.' },
  'rm-combo-70': { introduction: 'Ve výpočetním „stromu“ se větve množí méně, když jsou tvé tahy jaké?', question: 'Ve výpočetním „stromu“ se větve množí méně, když jsou tvé tahy:', options: ['Tiché a nezávazné', 'Náhodné', 'Vynucující, takže odpovědi jsou omezené', 'Pouze tahy jezdcem'], explanation: 'Vynucující tahy omezují soupeřovy možnosti, čímž udržují výpočetní strom úzký a zvládnutelný.' },
  'rm-combo-71': { introduction: 'Užitečný poslední krok před zahráním spočítané kombinace?', question: 'Užitečný poslední krok před zahráním spočítané kombinace je:', options: ['Okamžitě se vzdát, pokud si nejsi jistý', 'Prověřit koncovou pozici na hrubky a hledat mezitah nebo protitaktiku', 'Nabídnout remízu', 'Přesunout krále do středu'], explanation: 'Před odehráním ověř koncovou pozici a dávej pozor na mezitah nebo obranný prostředek, který by mohl tvou variantu vyvrátit.' },
  'rm-combo-72': { introduction: 'Chyby „zapamatovaného obrazu“ při dlouhém výpočtu se nejlépe sníží čím?', question: 'Chyby „zapamatovaného obrazu“ nebo přehmaty v dlouhém výpočtu se nejlépe sníží:', options: ['Jasnou vizualizací každého tahu a opětovným prověřováním vynucujících odpovědí', 'Rychlejším počítáním', 'Ignorováním soupeře', 'Díváním se pouze o jeden tah dopředu'], explanation: 'Jasná vizualizace a opětovné prověřování soupeřových vynucujících odpovědí v každém uzlu snižují chyby ve výpočtu.' },

  // ── Úroveň 10 — Mistrovství kombinací ──
  'rm-combo-73': { introduction: 'Jak nejlépe popsat „mlýnek“ (windmill)?', question: 'Jak nejlépe popsat „mlýnek“ (windmill)?', options: ['Opakovaná kombinace s objevným šachem, která sklízí materiál', 'Pevnost, kterou nelze prolomit', 'Mat dámou a jezdcem', 'Závod v proměně pěšců'], explanation: 'Mlýnek je opakující se vzor objevného šachu, který stále získává materiál, jak tatáž baterie cykluje.' },
  'rm-combo-74': { introduction: 'Anderssenova „Nesmrtelná partie“ a „Věčně zelená partie“ jsou slavné čím?', question: 'Anderssenova „Nesmrtelná partie“ a „Věčně zelená partie“ jsou slavné především:', options: ['Tichým pozičním manévrováním', 'Velkolepými obětními kombinacemi', 'Dlouhou koncovkovou technikou', 'Pouze teorií zahájení'], explanation: 'Obě partie jsou proslulé skvělými obětními útočnými kombinacemi Adolfa Anderssena.' },
  'rm-combo-75': { introduction: 'Oběť dámy stáhne krále na h7, pak jezdec dá vidličku — která dvě témata?', question: 'Obětuješ dámu, abys STÁHL krále na h7, pak jezdcový šach dá VIDLIČKU králi a soupeřově dámě. Která dvě témata se kombinují?', options: ['Uvolnění a poté vazba', 'Clonění a poté pat', 'Návnada (přilákání) a poté vidlička', 'Přetížení a poté rošáda'], explanation: 'Oběť dámy je návnada přilákávající krále a navazující jezdcový šach je vidlička — dvě témata spolupracují.' },
  'rm-combo-76': { introduction: 'Kombinace stáhne bránící věž z poslední řady a pak tam dá mat.', question: 'Kombinace stáhne bránící věž z poslední řady braním a pak tam dá mat. Základní téma je:', options: ['Uvolnění', 'Mezitah', 'Přilákání', 'Odklonění'], explanation: 'Vynucení, aby věž opustila svůj úkol hlídat poslední řadu, takže následuje mat, je odklonění.' },
  'rm-combo-77': { introduction: 'Která série správně seřazuje typický závěr udušeného matu?', question: 'Která série správně seřazuje typický závěr udušeného matu?', options: ['Jf7+ pak Dg8+ pak Vxg8 pak mat nemožný', 'Sxh7+ Kxh7, Dh5+ Kg8, Dh8#', 'Vd8+ Vxd8, Dxd8#', 'Jf7+ Kg8, Jh6+ Kh8, Dg8+ Vxg8, Jf7#'], explanation: 'Jezdcové šachy zaženou krále do rohu, pak Dg8+! Vxg8 Jf7# je udušený mat.' },
  'rm-combo-78': { introduction: 'Vložíš vlastní věž, abys přetnul obranu dámy pole g7 — obětuješ ji.', question: 'Vložíš vlastní věž, abys přetnul obranu nepřátelské dámy pole g7 a umožnil mat; věž jsi kvůli tomu obětoval. To je:', options: ['Prostá výměna', 'Zugzwang', 'Oběť clonění, která přetne obrannou linii', 'Pevnost'], explanation: 'Obětování figury pro přetnutí obranné linie dámy k matovému poli je oběť clonění.' },
  'rm-combo-79': { introduction: 'Zamýšlené braní umožní soupeři záchranu, ale mezitah-šach vyhrává.', question: 'V ostré pozici si všimneš, že tvé zamýšlené braní umožňuje soupeři záchranný prostředek, ale mezitah-šach nejdřív vyhrává přímo. Nejlepší praxe říká:', options: ['Přesto vzít', 'Vsunout mezitah (šach) před braním', 'Nabídnout remízu', 'Rošovat'], explanation: 'Když vsunutý vynucující tah zlepší výsledek, zahraj nejdřív mezitah a pak dokonči zpětné braní.' },
  'rm-combo-80': { introduction: 'Nejspolehlivější způsob, jak ověřit efektní obětní kombinaci?', question: 'Nejspolehlivější způsob, jak potvrdit efektní obětní kombinaci před jejím zahráním, je:', options: ['Spočítat vynucující varianty až do tiché pozice proti nejlepší obraně', 'Věřit, že „to vypadá správně“', 'Zahrát ji rychle, než začneš pochybovat', 'Zeptat se soupeře'], explanation: 'Ověř to výpočtem vynucující série až do jasné, posouditelné pozice a ujisti se, že funguje proti nejsilnější obraně.' },
};
