// Testing Foundations: four levels inside General (levels 16–19).
//
// Testing used to be a standalone fifteen-level path. Most of it was
// terminology: six separate levels on what a test is, two overlapping levels on
// doubles, and eight questions on the words red, green and refactor. What a
// working engineer needs from a foundations module is smaller and sharper —
// what a passing suite does and does not prove, how to read a test and see the
// bug it would miss, why a check is flaky, and how to decide whether a change
// is safe to merge.
//
// So the standalone path is retired and this replaces it: thirty-two authored
// questions, scenario-first, with the applied material living in the topics it
// actually verifies (see docs/curriculum-retirement.md for the destination map).
// Nothing here is copied from the old bank.
//
// Two things every explanation is careful about, because the old bank was not:
// a green build says the checks that ran passed, not that the change is safe;
// and a regression test proves that one bug is caught, not that it can never
// return in another form.

import type { Seed } from './roadmap-build';

export const testingFoundationsSeeds: Seed[] = [
  // ── Level 16 — What tests can prove ────────────────────────────────────
  { q: 'A pull request turns the whole CI suite green. What has that established?', opts: ['The change is safe to release', 'The checks that ran passed on the code as it was run', 'The change introduces no regressions anywhere in the product', 'Every path through the changed code was executed'], a: 1, e: 'A green build is a statement about the checks that ran, and nothing wider. It says those assertions held; it does not say the suite asked the right questions, that it covered this change, or that the change is safe.', intro: 'Ask what a passing check actually observed, and what it never looked at.', tags: ['General', 'Testing Foundations'] },
  { q: 'A bug reaches production. A test is added that fails on the old code and passes on the fix. What does that test now guarantee?', opts: ['That this class of bug can never occur again', 'That this specific failure will be caught if it is reintroduced in the same way', 'That the surrounding code is correct', 'That the fix is the simplest possible one'], a: 1, e: 'A regression test pins one behavior: if the same fault returns by the same route, the test fails and you find out in CI. A variation the assertion does not describe passes it unnoticed, which is why "we added a test" is not the same as "it cannot happen again". It also says nothing about the code around the fix, and nothing about whether the fix was the simplest one available.', intro: 'The test was written from one reproduction of the bug. Ask what it would take for that test to stay green.', tags: ['General', 'Testing Foundations'] },
  { q: 'A checkout function calls a payment provider, writes to a database and sends an email. You want to know that the money arithmetic is right. Which scope fits?', opts: ['An end-to-end test through the real browser and the real provider', 'A unit test over the arithmetic, with the provider, database and mailer out of the picture', 'A manual check before every release', 'No test — arithmetic is too simple to be worth one'], a: 1, e: 'Match the scope to the question. The arithmetic is a pure decision inside one function, so isolate it: a unit test tells you within milliseconds which number is wrong. Routing that question through a browser and a payment provider makes the answer slower and less certain.', intro: 'The question is about one calculation. Ask how much of the system has to run before you can answer it.', tags: ['General', 'Testing Foundations'] },
  { q: 'Every unit in a signup flow has passing tests, but signing up is broken in the running app. What kind of fault does that pattern point to?', opts: ['One of the unit tests is wrong and the others are right', 'The units disagree at their boundaries — the wiring between them is untested', 'The application is too large to test', 'The tests are running in the wrong order'], a: 1, e: 'Units passing in isolation says nothing about how they fit together: a mismatched shape, a wrong call order, a default nobody agreed on. That is what an integration test covers, and it is the commonest hole in a suite that looks complete.', intro: 'Green units and a broken signup are both true here. Ask what each result was measured on.', tags: ['General', 'Testing Foundations'] },
  { q: 'What is an end-to-end test buying you that a unit test cannot?', opts: ['A faster signal about which line is wrong', 'Evidence that the assembled system does the user-visible thing, wiring included', 'Proof that every branch is reachable', 'A guarantee that the code has no bugs'], a: 1, e: 'End-to-end exercises the real assembly: routing, serialization, storage, rendering. That is its value and also its cost — it is slower and, when it fails, it points at the whole system rather than at a line.', intro: 'This is the slowest and least precise test in a suite. Ask what buys it a place anyway.', tags: ['General', 'Testing Foundations'] },
  { q: 'Someone proposes "70% unit, 20% integration, 10% end-to-end" as a rule for every project. What is the honest response?', opts: ['It is the industry standard and should be followed exactly', 'The shape is a heuristic, not a target: what to test where depends on where this system actually breaks', 'Ratios like this are meaningless and should be ignored', 'End-to-end tests should always be the majority'], a: 1, e: 'The pyramid captures a real trade-off — cheap and narrow at the bottom, expensive and broad at the top. Turning it into a quota measures the wrong thing. A service whose failures are all integration failures should have integration tests, whatever the ratio says.', intro: 'Ask where those numbers come from and what evidence would change them.', tags: ['General', 'Testing Foundations'] },
  { q: 'A module reports 100% line coverage. Which of these is still entirely possible?', opts: ['Some lines have never been executed', 'Every line ran, but no assertion checked what it produced', 'The file failed to compile', 'The module has no branches'], a: 1, e: 'Coverage counts execution, not verification. A test that calls a function and asserts nothing covers every line inside it. Coverage tells you where the tests definitely are not; it does not tell you they are any good.', intro: 'Think about what a coverage tool actually records while the tests run.', tags: ['General', 'Testing Foundations'] },
  { q: 'A function is documented to throw on a negative input. Which check most directly demonstrates that behavior?', opts: ['Calling it with a positive input and checking the result', 'Calling it with a negative input and asserting that it throws', 'Reading the documentation in review', 'Asserting that the function exists'], a: 1, e: 'A documented behavior is demonstrated by exercising it: pass a negative value and require the call to throw, with assert.throws or expect(() => fn(-1)).toThrow(). A positive input tests a different rule, reading the documentation verifies nothing, and asserting that the function exists still passes after the throw is deleted. The assertion has to fail when the throw does not happen.', intro: 'Documentation names an input and an outcome. Ask what the test has to do with that input.', tags: ['General', 'Testing Foundations'] },

  // ── Level 17 — Read a meaningful test ──────────────────────────────────
  { q: 'A test builds a cart with two items, calls `total(cart)`, and asserts the result is 30. Which part is the arrangement?', opts: ['The call to `total(cart)`', 'Building the cart with two items', 'The assertion that the result is 30', 'The name of the test'], a: 1, e: 'Arrange sets up the world, act performs the one operation under test, assert states what should now be true: here the cart is the arrangement, total(cart) is the act, and expecting 30 is the assertion. The test name is documentation, not a phase. Naming the parts matters less than keeping them distinct — a test that arranges inside its assertion is hard to read and harder to trust when it fails.', intro: 'The phases are named for when each step happens, not for what the code looks like.', tags: ['General', 'Testing Foundations'] },
  { q: '`discount(price, percent)` should return the reduced price. A test asserts `expect(discount(100, 10)).toBeDefined()`. Which bug does it miss?', opts: ['The function being deleted', 'Returning any number at all — including the wrong one', 'The function throwing', 'A syntax error in the file'], a: 1, e: 'The assertion asks whether something came back, not whether it is right: discount(100, 10) returning 1000 satisfies it. A deleted function or a thrown error would still fail the test, because the call itself blows up before the assertion runs — those bugs are covered, the wrong number is not. Name the expected value when one exists: expect(discount(100, 10)).toBe(90).', intro: 'Ask how large the set of values is that would satisfy this assertion.', tags: ['General', 'Testing Foundations'] },
  { q: 'A function returns a list of active users. Which assertion survives an unrelated change to the user record and still fails when the wrong users come back?', opts: ['The result equals a hard-coded array of every field of every user', 'The result contains exactly the ids of the users that are active', 'The result has length 3', 'The result is truthy'], a: 1, e: 'Assert what the function promises — which users are active — and leave the rest alone. Pinning every field breaks whenever an unrelated field is added, and asserting a length passes when the wrong three come back. A truthy check survives every change because it can never fail, which is survival without information.', intro: 'Ask which part of the result the function actually promises, and which part is incidental.', tags: ['General', 'Testing Foundations'] },
  { q: '`clamp(value, min, max)` returns min or max when the value is outside the range. Which inputs are worth a test each?', opts: ['Only a value in the middle of the range', 'The value below min, above max, exactly min, exactly max and one inside', 'A hundred random values', 'Only values that have caused bugs before'], a: 1, e: 'Bugs cluster where the answer changes, so exactly min and exactly max are the values that expose a bound written one step off (min + 1, max - 1); a value inside the range is what catches a comparison made against the wrong bound. One below and one above exercise both clamping branches, and a hundred random values mostly retest the middle. "Only values that have caused bugs before" cannot cover the bug that has not happened yet.', intro: 'Ask which inputs could catch a bug that every other input in the range would hide.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test calls `saveUser(user)` and asserts that the save function was called once. What has it verified?', opts: ['That the user was stored correctly', 'That the code called the dependency — not what the dependency did with it', 'That the database schema is valid', 'That the user is retrievable afterwards'], a: 1, e: 'Asserting on a call verifies the interaction, not the outcome. That is sometimes the point — you may care that a payment is charged exactly once. It is not evidence that the record ended up right.', intro: 'The assertion was recorded at the moment of the call. Ask what had not happened yet.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test name reads "test 3". What does the name cost you when it fails in CI six months later?', opts: ['Nothing — the assertion message is enough', 'The failure says which test broke without saying what stopped being true', 'The test runs more slowly', 'The test cannot be filtered by name'], a: 1, e: 'The name is the failure report. "returns 0 for an empty cart" tells you what the code was supposed to do; "test 3" makes you read the body first. It is the cheapest documentation a codebase has.', intro: 'Picture the CI output six months from now, before anyone has opened the file.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test for `parseCsv` passes a file with one row and asserts the parsed output. Which case would you add first?', opts: ['A file with a thousand rows', 'An empty file, and a row containing the separator inside a quoted field', 'The same file in a different directory', 'A file with a different name'], a: 1, e: 'The empty input and the escaping rule are where parsers fail. Volume tells you about performance, not correctness, and neither the path nor the name of the file is part of what the function decides.', intro: 'Ask where a CSV parser has to make a decision that one plain row never asks of it.', tags: ['General', 'Testing Foundations'] },
  { q: 'Two tests both fail after one change. One says "cart total is wrong", the other says "checkout crashed". Which failure message helps more when you go looking for the cause, and why?', opts: ['The crash, because it is the more severe symptom', 'The total, because it names the behavior that changed rather than a symptom downstream', 'Neither — the two failures carry the same information', 'The crash, because it is closer to what the user sees'], a: 1, e: 'A failure that names a behavior points at the cause; a crash downstream tells you only that something upstream broke, and the search starts from there. Severity decides what to fix first, not which message is more informative — and here both failures come from the same change. Keep both, and expect the specific one to be the one you read.', intro: 'Read each message as all you get from CI, and ask what each one tells you about where to look.', tags: ['General', 'Testing Foundations'] },

  // ── Level 18 — Make checks reliable ────────────────────────────────────
  { q: 'A test asserts on the result of an async function and passes even when the function returns the wrong value. What is the likeliest cause?', opts: ['The test runner is broken', 'The promise is not awaited, so the assertion sees the promise rather than the value', 'The function is too fast to observe', 'Async functions cannot be tested'], a: 1, e: 'Without await the assertion sees the promise, not the value it will settle to, and a loose check — assert.ok(result), expect(result).toBeTruthy(), expect(result).toBeDefined() — is satisfied by any promise, so the test finishes before the work does and reports success. Awaiting the call, or returning the promise from the test, is what puts the real value in front of the assertion. A strict comparison against the promise fails instead, which is the noisier and luckier outcome.', intro: 'The assertion did run, and it ran on something. Ask what the call handed back at that instant.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test passes alone and fails when the suite runs in a different order. What does that tell you?', opts: ['The test runner has a bug', 'Something is shared between tests and not reset — state is leaking', 'The suite is too large', 'The tests need to run in series'], a: 1, e: 'Order sensitivity means one test can see what another left behind: a module-level cache, a stubbed global, a row in a database. Pinning the order hides it; resetting the shared thing between tests fixes it.', intro: 'The test did not change between the two runs. Ask what did.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test computes an expiry from `new Date()` and fails once a month. What should change?', opts: ['Re-run the suite until it passes', 'Inject the clock so the test controls the time it runs at', 'Delete the test', 'Add a delay before the assertion'], a: 1, e: 'A test that depends on the real clock depends on when it runs. Passing the current time in as an argument makes the boundary — the end of a month, a leap day — something you choose rather than wait for.', intro: 'Ask which value in this test comes from outside the test.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test replaces a payment client with a stub that returns a fixed success. What has it deliberately stopped checking?', opts: ['The arithmetic in the code under test', 'Whether the real payment client behaves as the stub claims', 'Whether the function is called', 'Its own assertions'], a: 1, e: 'A double is a statement about a dependency that nothing verifies. That is a fair trade for speed and determinism, as long as something else — a contract test, an integration test — checks that the real thing still behaves that way.', intro: 'The stub is an assumption written into the test. Ask what would happen if it stopped being true.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test waits 500 ms and then asserts that a list has rendered. Why is that fragile?', opts: ['500 ms is too long to spend in a suite', 'It passes or fails on machine speed rather than on the behavior', 'A test cannot observe a render that has already happened', 'The list will never finish rendering within 500 ms'], a: 1, e: 'A fixed sleep encodes an assumption about how fast the machine is: under load it is too short and the test flakes, and when it is generous the suite is slow for nothing. Waiting for the condition — the element appearing — is both faster and stable, which is why testing libraries expose findBy/waitFor rather than a delay. The runtime cost is real but secondary; the fragility is the answer.', intro: 'Ask what the number 500 is a guess about.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test in CI fails about one run in twenty and passes on a re-run. What is the responsible next step?', opts: ['Re-run until it is green; the code is clearly fine', 'Treat it as a real defect and find out what varies between the runs', 'Mark it as skipped', 'Increase the timeout until it stops failing'], a: 1, e: 'An intermittent failure is information: something in the test or the code depends on timing, order or shared state. Re-running until green teaches the team to ignore the suite, which is worse than not having it.', intro: 'The suite gave two different answers to the same question. Ask which answer you are entitled to ignore.', tags: ['General', 'Testing Foundations'] },
  { q: 'Two tests write to the same record in a shared database and are run in parallel. What is the fix that keeps them parallel?', opts: ['Run the suite in series from now on', 'Give each test its own data, so they cannot collide', 'Retry the failing one', 'Remove one of the tests'], a: 1, e: 'The collision is caused by sharing, not by parallelism. Unique data per test — a fresh row, a per-test schema — keeps both the isolation and the speed. Serializing the suite pays for the isolation with everyone’s time.', intro: 'Ask what the two tests share, and whether they have any reason to share it.', tags: ['General', 'Testing Foundations'] },
  { q: 'A suite mocks the module under test itself, not its dependencies. What is left being verified?', opts: ['The real behavior of that module', 'The mock — the code under test never runs', 'Only its error paths', 'Its performance'], a: 1, e: 'Replacing the thing you are testing leaves a test of your test setup. It is a surprisingly easy mistake in a file with many mocks, and it usually shows up as a suite that passes after the implementation is deleted.', intro: 'Ask what this suite would still report if the implementation file were emptied.', tags: ['General', 'Testing Foundations'] },

  // ── Level 19 — Verify a change ─────────────────────────────────────────
  { q: 'You are reviewing a fix with one added test. What is the most useful thing to check about that test?', opts: ['That it is short', 'That it fails against the unfixed code', 'That it uses the same style as its neighbors', 'That it has a descriptive name'], a: 1, e: 'A regression test that passes on the broken code proves nothing about the fix. Reverting the change and watching the new test fail is the check that the test is about the bug — and the fastest way to find one that is not.', intro: 'Ask what evidence there is that this test is about this bug rather than any other.', tags: ['General', 'Testing Foundations'] },
  { q: 'A CI run reports "3 passed, 2 skipped". What deserves attention?', opts: ['Nothing — no test failed', 'The skipped ones: a skip is an unanswered question, not a pass', 'Only the total count', 'The order the tests ran in'], a: 1, e: 'Skips are how a suite quietly stops checking things. They are often added to unblock a release and then never removed. A skipped test in a diff needs the same question as a deleted one: what is no longer being verified, and who decided?', intro: 'Ask what each number in that summary is evidence about.', tags: ['General', 'Testing Foundations'] },
  { q: 'A generated test suite for a date parser has ten cases, all with valid ISO strings. What is the most likely gap?', opts: ['Not enough valid formats', 'The invalid, empty and boundary inputs — the cases the parser exists to handle', 'Insufficient comments', 'Missing performance assertions'], a: 1, e: 'Generated suites tend to cover the path that was described to them and miss the ones nobody mentioned. For a parser, that is the malformed input, the empty string and the boundary date — which is where parsers actually fail.', intro: 'Notice what all ten inputs have in common, then ask what a parser does with everything else.', tags: ['General', 'Testing Foundations'] },
  { q: 'Two changes are waiting: a copy fix on a marketing page and a change to how refunds are calculated. Where does the testing effort go?', opts: ['Equally across both', 'Mostly on the refund calculation, where a mistake costs money and is hard to notice', 'Mostly on the copy, because users see it first', 'Neither needs tests'], a: 1, e: 'Risk is the cost of being wrong multiplied by how likely it is to slip through. Wrong copy is visible and cheap to fix; a wrong refund is invisible, expensive, and discovered later by somebody else.', intro: 'Ask how each mistake would be discovered, and by whom.', tags: ['General', 'Testing Foundations'] },
  { q: 'A change to a shared utility passes every test. What would still make you hesitant to merge it?', opts: ['The tests took longer than usual', 'The utility has callers whose behavior no test covers', 'The diff is large', 'It was written quickly'], a: 1, e: 'The suite reports on what it covers. A shared function with untested callers means the blast radius is bigger than the evidence. That is not a reason to block the change — it is a reason to know what you are relying on when you approve it.', intro: 'A green suite is only as wide as the tests that exist. Ask how wide that is here.', tags: ['General', 'Testing Foundations'] },
  { q: 'A test fails in CI and passes on your machine. Which explanation should you check first?', opts: ['The code is correct and CI is wrong', 'Something differs between the environments — time zone, locale, environment variable, installed version', 'CI is too slow', 'The test needs a longer timeout'], a: 1, e: '"Works on my machine" is the start of the investigation, not the end. Time zone and locale are the classic pair: the same instant renders as 3/1/2024 under UTC and 2/29/2024 under America/New_York, and a locale-aware sort puts the same strings in a different order — differences that are just as real in production as in CI. Reach for the environment diff before a longer timeout, which only hides a timing problem.', intro: 'The code is the same in both places. Ask what is not.', tags: ['General', 'Testing Foundations'] },
  { q: 'A team wants one number to tell them whether their tests are good enough. What is the honest answer?', opts: ['Line coverage above 80 percent, measured on every pull request', 'No single number: coverage, test count and pass rate each measure something narrower', 'The number of tests in the suite, tracked so it never goes down', 'The suite runtime, kept low enough that everyone runs it'], a: 1, e: 'Each of these measures something real and none of them measures confidence: coverage counts execution rather than verification, a test count rewards writing more tests, a pass rate rewards weak assertions, and a runtime target rewards deleting slow ones. They are worth watching as symptoms and useless as goals — the moment a number becomes the target, the cheapest way to move it is the one that helps least. What tells you the suite is good enough is whether it catches the defects you actually ship.', intro: 'Ask what each candidate number would reward a team for doing.', tags: ['General', 'Testing Foundations'] },
  { q: 'A flaky test is deleted to unblock a release. What has changed about the system?', opts: ['It is now more reliable', 'The unreliability is still there, and nothing reports on it any more', 'The bug the test covered is fixed', 'The suite is more trustworthy'], a: 1, e: 'The flake was a symptom of something non-deterministic in the test or in the code. Removing the test removes the report, not the cause — and if the cause was in the code, it is now unobserved in production too.', intro: 'The release is unblocked. Ask what happened to whatever was making the test flake.', tags: ['General', 'Testing Foundations'] },
];
