import type { QuestionTranslation } from './quiz-data';

export const politicalTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Státy a suverenita ──
  'rm-pol-1': { introduction: 'Zamysli se nad počtem uznávaných států.', question: 'Kolik zemí je dnes ve světě obecně uznáváno jako suverénní státy?', options: ['Přibližně 195', 'Přibližně 120', 'Přibližně 260', 'Přibližně 310'], explanation: 'Existuje kolem 195 obecně uznávaných suverénních států: 193 členských států OSN plus Vatikán (Svatý stolec) a Palestina, které mají status nečlenského pozorovatele.' },
  'rm-pol-2': { introduction: 'Hledej právní definici státnosti.', question: 'Co nejlépe vymezuje suverénní stát?', options: ['Provincie spravovaná z národního hlavního města', 'Území se stálým obyvatelstvem, vymezenými hranicemi, vládou a schopností vést zahraniční vztahy', 'Jakékoli velké město, které si volí vlastního starostu', 'Člen vojenské aliance'], explanation: 'Suverénní stát má stálé obyvatelstvo, vymezené území, funkční vládu a schopnost vstupovat do vztahů s jinými státy.' },
  'rm-pol-3': { introduction: 'Jde o počet členů OSN.', question: 'Kolik členských států patří do Organizace spojených národů?', options: ['173', '183', '193', '203'], explanation: 'Organizace spojených národů má 193 členských států, přičemž nejnovějším je Jižní Súdán, který vstoupil v roce 2011.' },
  'rm-pol-4': { introduction: 'Jeden z nich není plným členem OSN.', question: 'Který subjekt má u OSN status stálého pozorovatele namísto plného členství?', options: ['Kanada', 'Austrálie', 'Nigérie', 'Svatý stolec (Vatikán)'], explanation: 'Svatý stolec (Vatikán) je u OSN nečlenským stálým pozorovatelem, nikoli plným členským státem, stejně jako Palestina.' },
  'rm-pol-5': { introduction: 'Nejmenší stát podle rozlohy.', question: 'Který je nejmenším suverénním státem světa podle rozlohy?', options: ['Vatikán', 'Monako', 'San Marino', 'Lichtenštejnsko'], explanation: 'Vatikán zabírá pouze asi 0,49 kilometru čtverečního, což z něj činí nejmenší suverénní stát na Zemi.' },
  'rm-pol-6': { introduction: 'Úmluva z roku 1933.', question: 'Klasická kritéria státnosti — obyvatelstvo, území, vláda a schopnost vztahů — jsou nejvíce spojována s kterou dohodou?', options: ['Ženevská úmluva', 'Montevidejská úmluva', 'Versailleská smlouva', 'Kjótský protokol'], explanation: 'Montevidejská úmluva o právech a povinnostech států z roku 1933 stanovila široce citovaná kritéria státnosti.' },
  'rm-pol-7': { introduction: 'Jen jeden je samostatnou zemí.', question: 'Který z těchto celků je nezávislou suverénní zemí?', options: ['Skotsko', 'Bavorsko', 'Island', 'Québec'], explanation: 'Island je suverénní stát. Skotsko je národ v rámci Spojeného království, Bavorsko je spolková země Německa a Québec je provincie Kanady.' },
  'rm-pol-8': { introduction: 'Nejlidnatější země poloviny 20. let.', question: 'Která země má k polovině 20. let 21. století největší počet obyvatel?', options: ['Spojené státy', 'Indonésie', 'Čína', 'Indie'], explanation: 'Indie předstihla Čínu jako nejlidnatější země světa v roce 2023, přičemž oba státy přesahují 1,4 miliardy obyvatel.' },

  // ── Úroveň 2 — Hranice ──
  'rm-pol-9': { introduction: 'Nejdelší hranice mezi dvěma státy.', question: 'Která je nejdelší mezinárodní hranicí na světě?', options: ['Hranice mezi Ruskem a Čínou', 'Hranice mezi Spojenými státy a Kanadou', 'Hranice mezi Argentinou a Chile', 'Hranice mezi Kazachstánem a Ruskem'], explanation: 'Hranice mezi Spojenými státy a Kanadou, dlouhá zhruba 8 890 km, je nejdelší mezinárodní hranicí na světě.' },
  'rm-pol-10': { introduction: 'Země s nejvíce sousedy.', question: 'Které dvě země mají každá pozemní hranici se 14 dalšími zeměmi — nejvíce ze všech států?', options: ['Spojené státy a Mexiko', 'Indie a Pákistán', 'Čína a Rusko', 'Brazílie a Argentina'], explanation: 'Čína a Rusko sousedí každá se 14 zeměmi, více než kterýkoli jiný stát na Zemi.' },
  'rm-pol-11': { introduction: 'Jižní soused USA.', question: 'Která země tvoří jižní pozemní hranici Spojených států?', options: ['Guatemala', 'Belize', 'Kanada', 'Mexiko'], explanation: 'Mexiko sdílí jižní pozemní hranici Spojených států; Kanada leží na severu.' },
  'rm-pol-12': { introduction: 'Řeka na hranici USA a Mexika.', question: 'Která řeka tvoří velkou část hranice mezi Spojenými státy a Mexikem?', options: ['Rio Grande', 'Řeka Colorado', 'Řeka Mississippi', 'Řeka Columbia'], explanation: 'Rio Grande (Río Bravo) tvoří velkou část hranice mezi Texasem a Mexikem a ústí do Mexického zálivu.' },
  'rm-pol-13': { introduction: 'Nejdelší hranice Brazílie.', question: 'Se kterou zemí sdílí Brazílie nejdelší pozemní hranici?', options: ['Argentina', 'Bolívie', 'Peru', 'Venezuela'], explanation: 'Nejdelší pozemní hranice Brazílie, asi 3 400 km, je s Bolívií.' },
  'rm-pol-14': { introduction: 'Pohoří jako hranice.', question: 'Hranice mezi kterými dvěma zeměmi vede převážně podél pohoří Pyreneje?', options: ['Itálie a Švýcarsko', 'Norsko a Švédsko', 'Francie a Španělsko', 'Německo a Polsko'], explanation: 'Pyreneje tvoří přirozenou hranici mezi Francií a Španělskem, přičemž Andorra leží uvnitř tohoto pohoří.' },
  'rm-pol-15': { introduction: 'Silně opevněná hranice v Asii.', question: 'Které dvě země odděluje silně militarizovaná hranice známá jako korejská DMZ?', options: ['Čína a Mongolsko', 'Vietnam a Laos', 'Japonsko a Jižní Korea', 'Severní Korea a Jižní Korea'], explanation: 'Demilitarizovaná zóna poblíž 38. rovnoběžky odděluje Severní Koreu a Jižní Koreu.' },
  'rm-pol-16': { introduction: 'Rovnoběžka jako hranice.', question: '49. rovnoběžka tvoří velkou část hranice mezi kterými dvěma zeměmi?', options: ['Spojené státy a Kanada', 'Francie a Německo', 'Indie a Čína', 'Chile a Argentina'], explanation: 'Velká část západní hranice mezi USA a Kanadou vede podél 49. rovnoběžky.' },

  // ── Úroveň 3 — Vnitrozemské a pobřežní státy ──
  'rm-pol-17': { introduction: 'Země bez přístupu k moři.', question: 'Co je vnitrozemská země?', options: ['Země tvořená výhradně ostrovy', 'Země s velmi dlouhým pobřežím', 'Země bez přímého přístupu k oceánu či moři', 'Země, která sousedí pouze s jedním jiným státem'], explanation: 'Vnitrozemská země je obklopena souší a nemá pobřeží umožňující přímý přístup k otevřenému oceánu.' },
  'rm-pol-18': { introduction: 'Jen jedna je bez pobřeží.', question: 'Která z těchto zemí je vnitrozemská?', options: ['Portugalsko', 'Vietnam', 'Chile', 'Švýcarsko'], explanation: 'Švýcarsko je vnitrozemská země v Alpách; Portugalsko, Vietnam i Chile mají pobřeží.' },
  'rm-pol-19': { introduction: 'Vnitrozemská země Jižní Ameriky.', question: 'Která jihoamerická země je vnitrozemská?', options: ['Bolívie', 'Peru', 'Ekvádor', 'Kolumbie'], explanation: 'Bolívie a Paraguay jsou dvě vnitrozemské země Jižní Ameriky; Bolívie ztratila pobřeží v tichomořské válce v 19. století.' },
  'rm-pol-20': { introduction: 'Obklopena jen vnitrozemskými sousedy.', question: '„Dvojnásobně vnitrozemská“ země je obklopena pouze jinými vnitrozemskými zeměmi. Který evropský ministát je dvojnásobně vnitrozemský?', options: ['Monako', 'Lichtenštejnsko', 'Andorra', 'San Marino'], explanation: 'Lichtenštejnsko sousedí pouze se Švýcarskem a Rakouskem, obě vnitrozemské, takže je dvojnásobně vnitrozemské.' },
  'rm-pol-21': { introduction: 'Jediná další dvojnásobně vnitrozemská země.', question: 'Kromě Lichtenštejnska, která další země je dvojnásobně vnitrozemská, obklopená výhradně vnitrozemskými sousedy?', options: ['Kazachstán', 'Mongolsko', 'Uzbekistán', 'Afghánistán'], explanation: 'Uzbekistán je jedinou další dvojnásobně vnitrozemskou zemí; všech jeho pět sousedů je samo vnitrozemských.' },
  'rm-pol-22': { introduction: 'Země pod jižní stranou Everestu.', question: 'Která asijská země, na jejíž jižní straně se nachází Mount Everest, je vnitrozemsky sevřená mezi Indií a Čínou?', options: ['Bhútán', 'Bangladéš', 'Myanmar', 'Nepál'], explanation: 'Nepál je vnitrozemsky sevřen mezi Indií a Čínou a nachází se na něm jižní přístup k Mount Everestu.' },
  'rm-pol-23': { introduction: 'Mongolsko a jeho dva sousedé.', question: 'Mongolsko je vnitrozemsky sevřeno mezi kterými dvěma zeměmi?', options: ['Rusko a Čína', 'Čína a Kazachstán', 'Rusko a Kazachstán', 'Čína a Indie'], explanation: 'Mongolsko sousedí pouze s Ruskem na severu a Čínou na jihu, což jsou jeho jediní dva sousedé.' },
  'rm-pol-24': { introduction: 'Kontinent s nejvíce vnitrozemskými zeměmi.', question: 'Který kontinent má nejvíce vnitrozemských zemí?', options: ['Jižní Amerika', 'Afrika', 'Evropa', 'Asie'], explanation: 'Afrika má 16 vnitrozemských zemí, více než kterýkoli jiný kontinent.' },

  // ── Úroveň 4 — Území a závislá území ──
  'rm-pol-25': { introduction: 'Komu patří Grónsko.', question: 'Grónsko je autonomní území patřící které zemi?', options: ['Norsko', 'Island', 'Kanada', 'Dánsko'], explanation: 'Grónsko je autonomní součástí Dánského království.' },
  'rm-pol-26': { introduction: 'Portoriko a jeho příslušnost.', question: 'Portoriko je neinkorporovaným územím které země?', options: ['Spojené státy', 'Španělsko', 'Mexiko', 'Kuba'], explanation: 'Portoriko je neinkorporovaným územím Spojených států; jeho obyvatelé jsou občany USA.' },
  'rm-pol-27': { introduction: 'Zámořský region v Jižní Americe.', question: 'Francouzská Guyana na severním pobřeží Jižní Ameriky je zámořským regionem které země?', options: ['Portugalsko', 'Francie', 'Nizozemsko', 'Španělsko'], explanation: 'Francouzská Guyana je zámořským regionem Francie a součástí Evropské unie; nachází se zde kosmodrom Guyanské kosmické středisko.' },
  'rm-pol-28': { introduction: 'Definice závislého území.', question: 'Co je zámořské území nebo závislé území?', options: ['Plně suverénní členský stát OSN', 'Země, která vystoupila z aliance', 'Oblast pod jurisdikcí suverénního státu, ale ne plně do něj začleněná', 'Sídlo mezinárodní organizace'], explanation: 'Závislé nebo zámořské území je spravováno suverénním státem, ale není jeho plně začleněnou, nezávislou součástí.' },
  'rm-pol-29': { introduction: 'Kdo spravuje Bermudy.', question: 'Která země spravuje severoatlantické zámořské území Bermudy?', options: ['Spojené státy', 'Kanada', 'Portugalsko', 'Spojené království'], explanation: 'Bermudy jsou britským zámořským územím v severním Atlantiku.' },
  'rm-pol-30': { introduction: 'Ostrovy v Karibiku.', question: 'Karibské ostrovy Aruba a Curaçao jsou autonomními zeměmi v rámci království kterého státu?', options: ['Nizozemsko', 'Francie', 'Spojené království', 'Španělsko'], explanation: 'Aruba a Curaçao jsou autonomními zeměmi v rámci Nizozemského království.' },
  'rm-pol-31': { introduction: 'Britské území na jihu Pyrenejského poloostrova.', question: 'Gibraltar, britské zámořské území na jižním cípu Pyrenejského poloostrova, sousedí s kterou zemí?', options: ['Portugalsko', 'Španělsko', 'Maroko', 'Francie'], explanation: 'Gibraltar sdílí svou jedinou pozemní hranici se Španělskem a střeží průliv mezi Středozemním mořem a Atlantikem.' },
  'rm-pol-32': { introduction: 'Zámořská území v Tichomoří.', question: 'Nová Kaledonie a Francouzská Polynésie v Tichém oceánu jsou zámořskými územími které země?', options: ['Austrálie', 'Nový Zéland', 'Francie', 'Spojené státy'], explanation: 'Nová Kaledonie a Francouzská Polynésie jsou zámořskými společenstvími Francie v Tichomoří.' },

  // ── Úroveň 5 — Mezinárodní organizace ──
  'rm-pol-33': { introduction: 'Počet členů EU.', question: 'Kolik členských států má Evropská unie?', options: ['27', '25', '30', '15'], explanation: 'Evropská unie má 27 členských států po odchodu Spojeného království (brexit) v roce 2020.' },
  'rm-pol-34': { introduction: 'Hlavní funkce NATO.', question: 'Čím NATO primárně funguje?', options: ['Sdílená globální měnová unie', 'Environmentální smluvní orgán', 'Vojenská aliance kolektivní obrany', 'Humanitární agentura OSN'], explanation: 'NATO, Severoatlantická aliance, je vojenskou aliancí kolektivní obrany založenou v roce 1949.' },
  'rm-pol-35': { introduction: 'Region organizace ASEAN.', question: 'ASEAN je organizací zemí v kterém regionu?', options: ['Jižní Amerika', 'Jihovýchodní Asie', 'Střední Afrika', 'Blízký východ'], explanation: 'ASEAN, Sdružení národů jihovýchodní Asie, podporuje hospodářskou a politickou spolupráci mezi státy jihovýchodní Asie.' },
  'rm-pol-36': { introduction: 'Kontinentální organizace.', question: 'Africká unie (AU) zahrnuje téměř každou zemi kterého kontinentu?', options: ['Asie', 'Evropa', 'Jižní Amerika', 'Afrika'], explanation: 'Africká unie je kontinentálním orgánem zahrnujícím země Afriky.' },
  'rm-pol-37': { introduction: 'Účel založení OSN v roce 1945.', question: 'Organizace spojených národů byla založena v roce 1945 především za účelem podpory čeho?', options: ['Mezinárodního míru a spolupráce', 'Jednotné světové měny', 'Volného pohybu v rámci Evropy', 'Územních výbojů'], explanation: 'OSN byla založena po druhé světové válce s cílem udržovat mezinárodní mír a bezpečnost a podporovat spolupráci mezi národy.' },
  'rm-pol-38': { introduction: 'Jen jedna je členem EU.', question: 'Která z těchto zemí je členem Evropské unie?', options: ['Norsko', 'Švýcarsko', 'Německo', 'Spojené království'], explanation: 'Německo je zakládajícím členem EU. Norsko a Švýcarsko nikdy nevstoupily a Spojené království odešlo v roce 2020.' },
  'rm-pol-39': { introduction: 'Stálí členové s právem veta.', question: 'Kolik stálých členů s právem veta zasedá v Radě bezpečnosti OSN?', options: ['Tři', 'Pět', 'Sedm', 'Deset'], explanation: 'Pěti stálými členy jsou Spojené státy, Spojené království, Francie, Rusko a Čína, přičemž každý má právo veta.' },
  'rm-pol-40': { introduction: 'Organizace se sdílenou měnou euro.', question: 'Která organizace používá euro jako sdílenou měnu mezi mnoha svými členy?', options: ['NATO', 'ASEAN', 'Africká unie', 'Evropská unie'], explanation: 'Euro je sdílenou měnou eurozóny, skupiny členských států EU.' },

  // ── Úroveň 6 — Hlavní města a sídla vlád ──
  'rm-pol-41': { introduction: 'Sídlo hlavní centrály OSN.', question: 'Ve kterém městě se nachází hlavní sídlo Organizace spojených národů?', options: ['Ženeva', 'New York', 'Washington, D.C.', 'Brusel'], explanation: 'Hlavní sídlo OSN je v New Yorku, ačkoli má významné kanceláře také v Ženevě, Vídni a Nairobi.' },
  'rm-pol-42': { introduction: 'Sídlo hlavních institucí EU.', question: 'Které město hostí hlavní instituce Evropské unie?', options: ['Paříž', 'Berlín', 'Štrasburk', 'Brusel'], explanation: 'Brusel hostí Evropskou komisi a Radu a je považován za faktické hlavní město EU.' },
  'rm-pol-43': { introduction: 'Hlavní město Austrálie.', question: 'Jaké je hlavní město Austrálie?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], explanation: 'Canberra byla účelově vybudována jako hlavní město Austrálie jako kompromis mezi rivaly Sydney a Melbourne.' },
  'rm-pol-44': { introduction: 'Sídlo vlády Nizozemska.', question: 'Kde je sídlo vlády Nizozemska, přestože ústavním hlavním městem je Amsterdam?', options: ['Haag', 'Rotterdam', 'Utrecht', 'Eindhoven'], explanation: 'Haag je sídlem nizozemské vlády a parlamentu, zatímco Amsterdam je ústavním hlavním městem.' },
  'rm-pol-45': { introduction: 'Hlavní město Kanady.', question: 'Jaké je hlavní město Kanady?', options: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], explanation: 'Ottawa v Ontariu je národním hlavním městem Kanady, nikoli větší města Toronto či Montreal.' },
  'rm-pol-46': { introduction: 'Hlavní město Brazílie.', question: 'Jaké je hlavní město Brazílie?', options: ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Brasília'], explanation: 'Brasília, uvedená do provozu v roce 1960, nahradila Rio de Janeiro jako účelově vybudované hlavní město Brazílie.' },
  'rm-pol-47': { introduction: 'JAR má tři hlavní města.', question: 'Jihoafrická republika má tři hlavní města. Které z nich je sídlem výkonné moci vlády?', options: ['Kapské Město', 'Bloemfontein', 'Pretoria', 'Johannesburg'], explanation: 'Pretoria je výkonným hlavním městem, Kapské Město zákonodárným a Bloemfontein soudním hlavním městem.' },
  'rm-pol-48': { introduction: 'Hlavní město Turecka.', question: 'Jaké je hlavní město Turecka?', options: ['Ankara', 'Istanbul', 'Izmir', 'Antalya'], explanation: 'Ankara je hlavním městem Turecka, zvolena přednostně před větším a slavnějším Istanbulem.' },

  // ── Úroveň 7 — Sporná území ──
  'rm-pol-49': { introduction: 'Sporná oblast v Himálaji.', question: 'Oblast Kašmíru je nárokována a částečně spravována především kterými dvěma zeměmi?', options: ['Čína a Mongolsko', 'Írán a Afghánistán', 'Indie a Pákistán', 'Nepál a Bhútán'], explanation: 'Kašmír je rozdělen a sporný především mezi Indií a Pákistánem, přičemž jeho část spravuje i Čína.' },
  'rm-pol-50': { introduction: 'Sporné území v severní Africe.', question: 'Západní Sahara je sporným územím z velké části ovládaným kterou sousední zemí?', options: ['Maroko', 'Alžírsko', 'Mauritánie', 'Libye'], explanation: 'Maroko ovládá většinu Západní Sahary, zatímco Fronta Polisario usiluje o nezávislost pro Sahrawský lid.' },
  'rm-pol-51': { introduction: 'K čemu je vyhrazena Antarktida.', question: 'Podle Antarktické smlouvy z roku 1959 je kontinent Antarktida vyhrazen pro co?', options: ['Pouze vojenské základny', 'Kontrolu jediného národa', 'Komerční těžbu', 'Mírový vědecký výzkum'], explanation: 'Antarktická smlouva odkládá územní nároky a věnuje kontinent mírové vědecké spolupráci.' },
  'rm-pol-52': { introduction: 'Oficiální název Tchaj-wanu.', question: 'Tchaj-wan je spravován samostatně, ale Čínská lidová republika si jej nárokuje jako své území. Jaký je oficiální název Tchaj-wanu?', options: ['Tchajwanské království', 'Čínská republika', 'Tchajwanský lidový stát', 'Formoská unie'], explanation: 'Tchajwanská vláda se oficiálně nazývá Čínská republika, což ji odlišuje od pevninské Čínské lidové republiky.' },
  'rm-pol-53': { introduction: 'Rok podpisu Antarktické smlouvy.', question: 'Ve kterém roce byla podepsána Antarktická smlouva, která odkládá všechny územní nároky?', options: ['1919', '1945', '1959', '1982'], explanation: 'Antarktická smlouva byla podepsána v roce 1959 a vstoupila v platnost v roce 1961.' },
  'rm-pol-54': { introduction: 'Tchaj-wan a mezinárodní organizace.', question: 'Tchaj-wan není členem kterého významného mezinárodního orgánu, kde jej místo něj zastupuje Čínská lidová republika?', options: ['Organizace spojených národů', 'Olympijské hry', 'Světová obchodní organizace', 'APEC'], explanation: 'Tchaj-wan není členem OSN; na olympiádě soutěží jako „Čínská Tchaj-pej“ a je členem WTO a APEC.' },
  'rm-pol-55': { introduction: 'Sporná náhorní plošina.', question: 'Golanské výšiny jsou spornou náhorní plošinou ležící mezi Izraelem a kterou zemí?', options: ['Libanon', 'Jordánsko', 'Egypt', 'Sýrie'], explanation: 'Golanské výšiny leží mezi Izraelem a Sýrií; Izrael jejich většinu ovládá od roku 1967.' },
  'rm-pol-56': { introduction: 'Ostrovy v jižním Atlantiku.', question: 'Falklandské ostrovy v jižním Atlantiku spravuje Spojené království a nárokuje si je také která země?', options: ['Chile', 'Argentina', 'Uruguay', 'Brazílie'], explanation: 'Argentina si nárokuje Falklandské ostrovy (Islas Malvinas), které spravuje Spojené království; obě země o ně v roce 1982 vedly válku.' },

  // ── Úroveň 8 — Historické hranice a změny ──
  'rm-pol-57': { introduction: 'Rozpad Sovětského svazu.', question: 'Ve kterém roce se Sovětský svaz (SSSR) rozpadl na 15 nezávislých zemí?', options: ['1985', '1975', '1995', '1991'], explanation: 'Sovětský svaz byl formálně rozpuštěn v prosinci 1991, čímž vzniklo 15 nezávislých států.' },
  'rm-pol-58': { introduction: 'Sjednocení Německa.', question: 'Ve kterém roce se východní a západní Německo sjednotily v jednu zemi?', options: ['1985', '1990', '1995', '1989'], explanation: 'Německo se sjednotilo 3. října 1990, necelý rok po pádu Berlínské zdi v listopadu 1989.' },
  'rm-pol-59': { introduction: 'Nástupnický stát Jugoslávie.', question: 'Jugoslávie se v 90. letech rozpadla na několik zemí. Která z těchto zemí byla jednou z nich?', options: ['Chorvatsko', 'Rakousko', 'Maďarsko', 'Bulharsko'], explanation: 'Chorvatsko bylo jedním z nástupnických států bývalé Jugoslávie, spolu se Srbskem, Slovinskem a dalšími.' },
  'rm-pol-60': { introduction: 'Země dříve zvaná Barma.', question: 'Která země změnila svůj oficiální název z Barmy?', options: ['Thajsko', 'Kambodža', 'Myanmar', 'Laos'], explanation: 'Barma byla svou vládou přejmenována na Myanmar v roce 1989.' },
  'rm-pol-61': { introduction: 'Země dříve zvaná Zair.', question: 'Země dříve známá jako Zair se nyní nazývá jak?', options: ['Konžská republika', 'Zambie', 'Angola', 'Konžská demokratická republika'], explanation: 'Zair se v roce 1997 vrátil k názvu Konžská demokratická republika.' },
  'rm-pol-62': { introduction: 'Země dříve zvaná Siam.', question: 'Která země byla dříve známá jako Siam?', options: ['Vietnam', 'Thajsko', 'Malajsie', 'Indonésie'], explanation: 'Siam byl přejmenován na Thajsko v roce 1939 (a nakrátko se vrátil k původnímu názvu, než v roce 1949 natrvalo přijal název Thajsko).' },
  'rm-pol-63': { introduction: 'Nejnovější suverénní stát z roku 2011.', question: 'Která země získala v roce 2011 nezávislost jako nejnovější obecně uznávaný suverénní stát světa?', options: ['Jižní Súdán', 'Kosovo', 'Východní Timor', 'Černá Hora'], explanation: 'Jižní Súdán se v roce 2011 odtrhl od Súdánu a stal se 193. členem Organizace spojených národů.' },
  'rm-pol-64': { introduction: 'Rozdělení Československa.', question: 'Československo se v roce 1993 pokojně rozdělilo na Českou republiku a kterou další zemi?', options: ['Rakousko', 'Maďarsko', 'Slovensko', 'Slovinsko'], explanation: '„Sametový rozvod“ v roce 1993 rozdělil Československo na Českou republiku a Slovensko.' },

  // ── Úroveň 9 — Enklávy a exklávy ──
  'rm-pol-65': { introduction: 'Suverénní enkláva uvnitř Itálie.', question: 'Který suverénní stát je enklávou nacházející se zcela uvnitř Itálie?', options: ['San Marino', 'Monako', 'Andorra', 'Lichtenštejnsko'], explanation: 'San Marino, jedna z nejstarších republik světa, je zcela obklopeno Itálií.' },
  'rm-pol-66': { introduction: 'Vatikán uvnitř jednoho města.', question: 'Vatikán je nezávislým státem nacházejícím se zcela uvnitř kterého města?', options: ['Florencie', 'Milán', 'Řím', 'Neapol'], explanation: 'Vatikán je enklávou uvnitř města Říma, hlavního města Itálie.' },
  'rm-pol-67': { introduction: 'Země obklopená jediným státem.', question: 'Lesotho je země zcela obklopená kterým jediným státem?', options: ['Namibie', 'Botswana', 'Zimbabwe', 'Jihoafrická republika'], explanation: 'Lesotho je zcela enklávou v Jihoafrické republice, jeden z pouhých tří takto obklopených suverénních států.' },
  'rm-pol-68': { introduction: 'Definice exklávy.', question: 'Co je exkláva?', options: ['Země bez pobřeží', 'Část země, která je geograficky oddělena od svého hlavního území', 'Sporné pohraniční pásmo', 'Neobydlený ostrov'], explanation: 'Exkláva je část státu, která je fyzicky oddělena od hlavního území tohoto státu.' },
  'rm-pol-69': { introduction: 'Ruská exkláva u Baltu.', question: 'Kaliningrad je exklávou které země, odříznutou od pevniny Litvou a Polskem?', options: ['Rusko', 'Bělorusko', 'Ukrajina', 'Německo'], explanation: 'Kaliningrad je ruskou exklávou u Baltského moře, oddělenou od zbytku Ruska jinými zeměmi.' },
  'rm-pol-70': { introduction: 'Sporná horská oblast v Zakavkazsku.', question: 'Oblast Náhorního Karabachu je horská oblast ležící v mezinárodně uznávaných hranicích které země?', options: ['Arménie', 'Gruzie', 'Ázerbájdžán', 'Turecko'], explanation: 'Náhorní Karabach leží v mezinárodně uznávaných hranicích Ázerbájdžánu a je dlouhodobě sporný s Arménií.' },
  'rm-pol-71': { introduction: 'Definice enklávy.', question: 'Enkláva je nejlépe popsána jako území, které je jaké?', options: ['Rozdělené na mnoho ostrovů', 'Bývalá kolonie', 'Obklopené horami', 'Zcela obklopené územím jiného státu'], explanation: 'Enkláva je území (nebo jeho část) zcela obklopené územím jiného státu.' },
  'rm-pol-72': { introduction: 'Třetí zcela obklopený suverénní stát.', question: 'Třemi suverénními státy, z nichž každý je zcela obklopen jedinou jinou zemí, jsou Vatikán, San Marino a který třetí?', options: ['Monako', 'Lesotho', 'Andorra', 'Brunej'], explanation: 'Lesotho, obklopené Jihoafrickou republikou, se řadí k Vatikánu a San Marinu (oba uvnitř Itálie) jako jediné zcela obklopené suverénní státy.' },

  // ── Úroveň 10 — Mistrovství v politické geografii ──
  'rm-pol-73': { introduction: 'Nejvíce časových pásem včetně zámoří.', question: 'Která země, počítaje její zámořská území, zasahuje do nejvíce časových pásem na světě?', options: ['Rusko', 'Francie', 'Spojené státy', 'Čína'], explanation: 'Francie zasahuje díky svým zámořským územím do 12 časových pásem, více než kterákoli jiná země; Rusko má 11.' },
  'rm-pol-74': { introduction: 'Město na dvou kontinentech.', question: 'Které země největší město leží na dvou kontinentech, rozdělené mezi Evropu a Asii průlivem?', options: ['Rusko', 'Kazachstán', 'Gruzie', 'Turecko'], explanation: 'Istanbul, největší město Turecka, se rozkládá přes průliv Bospor, čímž leží v Evropě i Asii.' },
  'rm-pol-75': { introduction: 'Nejdelší pozemní hranice a 14 sousedů.', question: 'Která země má nejdelší celkovou pozemní hranici ze všech států, hraničíc se 14 sousedy?', options: ['Čína', 'Rusko', 'Brazílie', 'Indie'], explanation: 'Čína má nejdelší pozemní hranici ze všech zemí, zhruba 22 000 km sdílených se 14 sousedy.' },
  'rm-pol-76': { introduction: 'Pozorovatel OSN na Blízkém východě.', question: 'Který subjekt na Blízkém východě je nečlenským stálým pozorovatelem OSN, nikoli plným členským státem?', options: ['Izrael', 'Jordánsko', 'Palestina', 'Libanon'], explanation: 'Palestina má u OSN status nečlenského pozorovatelského státu, zatímco Izrael, Jordánsko a Libanon jsou plnými členy.' },
  'rm-pol-77': { introduction: 'Země u Kaspického moře.', question: 'Kaspické moře obklopuje pět zemí. Která z těchto zemí je jednou z nich?', options: ['Gruzie', 'Kazachstán', 'Uzbekistán', 'Arménie'], explanation: 'Kaspické moře obklopují Rusko, Kazachstán, Turkmenistán, Írán a Ázerbájdžán.' },
  'rm-pol-78': { introduction: 'Největší země podle rozlohy.', question: 'Která transkontinentální země je největší na světě podle rozlohy?', options: ['Kanada', 'Čína', 'Spojené státy', 'Rusko'], explanation: 'Rusko je největší zemí podle rozlohy, rozkládá se na zhruba 17 milionech kilometrů čtverečních napříč Evropou a Asií.' },
  'rm-pol-79': { introduction: 'Největší vnitrozemská země.', question: 'Kazachstán je největší vnitrozemskou zemí světa. Na pomezí kterých dvou kontinentů leží?', options: ['Evropa a Asie', 'Asie a Afrika', 'Evropa a Afrika', 'Asie a Austrálie'], explanation: 'Kazachstán leží na konvenční hranici mezi Evropou a Asií a je největší vnitrozemskou zemí podle rozlohy.' },
  'rm-pol-80': { introduction: 'Ostrovní stát mezi ministáty.', question: 'Který z evropských ministátů Andorra, Lichtenštejnsko, Malta a San Marino je ostrovním státem?', options: ['Andorra', 'Lichtenštejnsko', 'Malta', 'San Marino'], explanation: 'Malta je ostrovní stát ve Středozemním moři, zatímco Andorra, Lichtenštejnsko a San Marino jsou vnitrozemské.' },
};
