import type { QuestionTranslation } from './quiz-data';

export const endgamesTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Král a pěšec proti králi ─────────────────────────────
  'rm-end-1': { introduction: 'Zamysli se, která fáze partie přichází jako poslední.', question: 'Co je v šachu „koncovka“?', options: ['Závěrečná fáze s malým počtem figur na šachovnici', 'Zahajovací tahy', 'Prostředek partie', 'První braní'], explanation: 'Koncovka je poslední fáze partie, kdy na šachovnici zůstává jen několik figur.' },
  'rm-end-2': { introduction: 'K čemu je dobré mít pěšce navíc?', question: 'Co se v koncovce král a pěšec proti králi obvykle snaží silnější strana udělat?', options: ['Odevzdat pěšce', 'Proměnit pěšce v dámu', 'Dát soupeři pat', 'Ztratit krále'], explanation: 'Cílem je dovést pěšce až na poslední řadu a proměnit ho, obvykle v dámu.' },
  'rm-end-3': { introduction: 'Co se stane, když pěšec dojde až na konec?', question: 'Co se stane, když pěšec dojde na opačný konec šachovnice?', options: ['Je odstraněn', 'Nestane se nic', 'Promění se v jinou figuru', 'Stane se z něj král'], explanation: 'Pěšec, který dojde na osmou řadu, se promění, nejčastěji v silnou dámu.' },
  'rm-end-4': { introduction: 'Jak by měl král v koncovce vystupovat?', question: 'V koncovce by král měl obecně být:', options: ['Schovaný v rohu', 'Ponechaný na výchozím poli', 'Brzy obětovaný', 'Aktivní a v centru'], explanation: 'Když zbývá málo figur, je král dostatečně bezpečný, aby se stal silnou, aktivní figurou v centru.' },
  'rm-end-5': { introduction: 'Kdo má materiál navíc?', question: 'V koncovce král a pěšec proti samotnému králi se o výhru snaží která strana?', options: ['Strana s pěšcem navíc', 'Samotný král', 'Žádná, vždy je to remíza', 'Obě stejně'], explanation: 'Strana s pěšcem navíc se ho snaží proměnit a vyhrát.' },
  'rm-end-6': { introduction: 'Jakou roli hraje král při doprovodu pěšce?', question: 'Proč je král v koncovkách krále a pěšce tak důležitý?', options: ['Může přeskakovat figury', 'Pomáhá pěšci postupovat vpřed', 'Táhne jako dáma', 'Nemůže být sebrán'], explanation: 'Král musí pěšce doprovázet a chránit na jeho cestě k proměně.' },
  'rm-end-7': { introduction: 'Co zmůže král bez figur a pěšců?', question: 'Samotný král bez figur a pěšců může:', options: ['Vyhrát partii', 'Proměnit pěšce', 'Jen remizovat nebo prohrát, nikdy vyhrát', 'Dát mat sám'], explanation: 'Holý král nemá čím matovat, takže nejlepší, v co může doufat, je remíza.' },
  'rm-end-8': { introduction: 'Jaká figura je nejsilnější?', question: 'V jakou figuru se pěšec proměňuje nejčastěji?', options: ['V jezdce', 'Ve střelce', 'Ve věž', 'V dámu'], explanation: 'Dáma je nejsilnější figura, proto se pěšci téměř vždy proměňují v dámu.' },

  // ── Úroveň 2 — Opozice ───────────────────────────────────────────────
  'rm-end-9': { introduction: 'Jak stojí králové vůči sobě?', question: 'Co je v královské koncovce „opozice“?', options: ['Králové stojí proti sobě s jedním polem mezi sebou', 'Dva králové na stejném poli', 'Král útočící na věž', 'Dva pěšci blokující jeden druhého'], explanation: 'Opozice je situace, kdy oba králové stojí na stejné linii s přesně jedním polem mezi sebou.' },
  'rm-end-10': { introduction: 'Kdo je ve výhodě — ten na tahu, nebo ten mimo tah?', question: 'Když jsou králové v přímé opozici, o kom se říká, že „drží opozici“?', options: ['Hráč, který je na tahu', 'Hráč, který NEMUSÍ táhnout', 'Hráč s více pěšci', 'Vždy bílý'], explanation: 'Strana, která není na tahu, drží opozici a může přinutit druhého krále, aby uhnul.' },
  'rm-end-11': { introduction: 'K čemu opozice pomáhá?', question: 'Proč je opozice v koncovkách krále a pěšce cenná?', options: ['Získá dámu', 'Okamžitě promění pěšce', 'Přinutí soupeřova krále uhnout', 'Dává šach'], explanation: 'Držení opozice nutí soupeřova krále ustoupit a umožňuje tvému králi postoupit.' },
  'rm-end-12': { introduction: 'Kolik polí je mezi králi při přímé opozici?', question: 'Přímá opozice znamená, že králové jsou odděleni kolika poli?', options: ['Dvěma poli', 'Třemi poli', 'Nula poli', 'Jedním polem'], explanation: 'Při přímé opozici stojí králové proti sobě s jediným prázdným polem mezi sebou.' },
  'rm-end-13': { introduction: 'Komu opozice pomáhá nejvíc?', question: 'Opozice je nejužitečnější pro stranu, která:', options: ['Se snaží postoupit s králem vpřed', 'Se pouze brání', 'Je v materiálu pozadu', 'Nemá žádné pěšce'], explanation: 'Útočník využívá opozici k obejití bránícího se krále a k postupu.' },
  'rm-end-14': { introduction: 'Kam králové nikdy nemohou stát?', question: 'Králové nikdy nemohou stát na:', options: ['V centru', 'Sousedních polích', 'Stejné barvě', 'Protilehlých rozích'], explanation: 'Králové nikdy nemohou stát vedle sebe, a právě proto na opozici záleží.' },
  'rm-end-15': { introduction: 'Co musí soupeřův král udělat, když je na tahu?', question: 'Když držíš opozici a soupeř musí táhnout, jeho král bude:', options: ['Získá opozici', 'Dá mat', 'Nucen ustoupit dozadu nebo do strany', 'Sebere tvého krále'], explanation: 'Být na tahu v opozici nutí krále ustoupit.' },
  'rm-end-16': { introduction: 'O co v opozici vlastně jde?', question: 'Získání opozice je v podstatě boj o to:', options: ['Kdo má víc dam', 'Čas na hodinách', 'Právo rošády', 'Kdo je nucen táhnout jako první'], explanation: 'Opozice je myšlenka zugzwangu: kdo musí táhnout, je v nevýhodě.' },

  // ── Úroveň 3 — Proměna pěšce ─────────────────────────────────────────
  'rm-end-17': { introduction: 'Vzpomeneš si na známé šachové pořekadlo o volných pěšcích?', question: 'Známé šachové rčení o volných pěšcích zní:', options: ['Volní pěšci musí být tlačeni vpřed', 'Volným pěšcem nikdy netáhni', 'Vyměň všechny volné pěšce', 'Volní pěšci se nemohou proměnit'], explanation: 'Klasická rada „volní pěšci musí být tlačeni vpřed“ vybízí k jejich postupu k proměně.' },
  'rm-end-18': { introduction: 'Co dělá pěšce „volným“?', question: '„Volný pěšec“ je pěšec, který:', options: ['Se už proměnil', 'Nemá před sebou žádné soupeřovy pěšce, kteří by ho zastavili', 'Zůstal trčet na výchozím poli', 'Je krytý věží'], explanation: 'Volný pěšec nemá před sebou na svém ani na sousedních sloupcích žádné soupeřovy pěšce, kteří by ho zablokovali nebo sebrali.' },
  'rm-end-19': { introduction: 'Kde by měl stát král útočníka?', question: 'Aby útočník vyhrál koncovku král a pěšec proti králi, obvykle chce mít krále:', options: ['Za pěšcem', 'Na okraji šachovnice', 'Před pěšcem', 'Mimo šachovnici'], explanation: 'Dostat krále před svého pěšce, s opozicí, je standardní vyhrávající metoda.' },
  'rm-end-20': { introduction: 'Co když se bránící král dostane před pěšce?', question: 'Pokud se bránící král dostane na pole před osamoceného pěšce a drží opozici, výsledek je často:', options: ['Výhra pro pěšce', 'Výhra pro bránícího se', 'Prohra patem', 'Remíza'], explanation: 'Bránící král zakotvený před pěšcem s opozicí obvykle remizuje.' },
  'rm-end-21': { introduction: 'Jak se nazývá pěšec na krajních sloupcích?', question: 'Pěšec na sloupci „a“ nebo „h“ se nazývá:', options: ['Věžový pěšec', 'Centrální pěšec', 'Střelcový pěšec', 'Volný pěšec'], explanation: 'Pěšci na sloupcích „a“ a „h“ jsou „věžoví pěšci“, pojmenovaní podle věží, které vedle nich stojí na začátku.' },
  'rm-end-22': { introduction: 'Co když se bránící král dostane do rohu?', question: 'Osamocený věžový pěšec s bránícím se králem v rohu je obvykle:', options: ['Výhra', 'Remíza', 'Pat pro útočníka', 'Nemožný'], explanation: 'Pokud se bránící král dostane do rohu proměny, je koncovka s osamoceným věžovým pěšcem známá remíza.' },
  'rm-end-23': { introduction: 'Který pěšec se proti dobře postavenému králi promění nejhůř?', question: 'Kterého pěšce je nejtěžší proměnit proti dobře postavenému bránícímu se králi?', options: ['Centrálního pěšce', 'Jezdcového pěšce', 'Věžového pěšce (sloupec „a“ nebo „h“)', 'Dámského pěšce'], explanation: 'Věžoví pěšci jsou pověstně remízoví, protože útočící král má na okraji málo prostoru.' },
  'rm-end-24': { introduction: 'Jaké nebezpečí hrozí při proměně pěšce?', question: 'Při proměně pěšce si musíš dát pozor, abys nezpůsobil:', options: ['Příliš rychlou výhru', 'Centralizaci svého krále', 'Udržení opozice', 'Pat samotnému králi'], explanation: 'Uvěznění soupeřova krále bez legálního tahu, ale bez šachu, je pat — remíza.' },

  // ── Úroveň 4 — Král a dáma proti králi ───────────────────────────────
  'rm-end-25': { introduction: 'Dá se dámou vynutit mat?', question: 'Král a dáma proti samotnému králi je:', options: ['Vynucená výhra', 'Vždy remíza', 'Prohra pro dámu', 'Nemožné dohrát'], explanation: 'K+D proti K je základní, vynucený mat pro silnější stranu.' },
  'rm-end-26': { introduction: 'Kam musíš zahnat soupeřova krále?', question: 'Abys dal mat dámou, musíš nejprve zahnat soupeřova krále na:', options: ['Do centra', 'Na okraj nebo do rohu', 'K jeho vlastním pěšcům', 'Na světlé pole'], explanation: 'Samotného krále je třeba zahnat na okraj nebo do rohu, kde lze dát mat.' },
  'rm-end-27': { introduction: 'Čemu se musíš při matování dámou vyhnout?', question: 'Největší nebezpečí, kterému se musíš při matování dámou vyhnout, je:', options: ['Ztráta dámy kvůli pěšci', 'Jen vypršení času', 'Pat', 'Proměna pěšce'], explanation: 'Protože je dáma tak silná, snadno se stane, že samotný král nemá žádný legální tah: pat.' },
  'rm-end-28': { introduction: 'Musí král s dámou spolupracovat?', question: 'Aby dali mat, král a dáma obvykle musí:', options: ['Oba útočit z dálky', 'Ignorovat soupeřova krále', 'Vyměnit dámu', 'Spolupracovat, král podporuje dámu'], explanation: 'Král musí dámu podporovat, aby mohla bezpečně dát mat na okraji.' },
  'rm-end-29': { introduction: 'K čemu slouží držení dámy skokem jezdce od krále?', question: 'Běžná technika s dámou je držet ji vzdálenou na skok jezdce od samotného krále, aby:', options: ['Zaháněla krále k okraji bez patu', 'Dávala věčný šach', 'Rychleji proměnila', 'Bránila pěšce'], explanation: 'Metoda „skoku jezdce“ dovede krále k okraji a přitom se vyhýbá patu.' },
  'rm-end-30': { introduction: 'Kde padne mat v koncovce K+D proti K?', question: 'V koncovce K+D proti K se mat dává:', options: ['V centru', 'Na okraji nebo v rohu', 'Na výchozím poli dámy', 'Jen pěšcem'], explanation: 'Samotný král je matován u okraje, kde mu vlastní hranice šachovnice odřízne únik.' },
  'rm-end-31': { introduction: 'Zvládne dáma matovat bez svého krále?', question: 'Může dáma dát mat bez pomoci vlastního krále?', options: ['Ano, vždy sama', 'Jen s věží', 'Ne, král musí hlídat úniková pole', 'Jen proti dámě'], explanation: 'Král je potřeba k pokrytí polí vedle soupeřova krále, aby dáma mohla bezpečně matovat.' },
  'rm-end-32': { introduction: 'Jak se jmenuje situace, kdy král nemůže táhnout, ale není v šachu?', question: 'Pokud tvá dáma dá „šach“, ale soupeřův král nemá žádnou legální odpověď a přitom není v šachu, je to:', options: ['Mat', 'Výhra', 'Tah bez chyby', 'Pat'], explanation: 'Žádný legální tah, když král NENÍ v šachu, je pat; jen žádný legální tah, KDYŽ je v šachu, je mat.' },

  // ── Úroveň 5 — Král a věž proti králi ────────────────────────────────
  'rm-end-33': { introduction: 'Dá se věží vynutit mat?', question: 'Král a věž proti samotnému králi je:', options: ['Vynucený mat', 'Remíza', 'Prohra pro věž', 'Jen remíza při nejlepší hře'], explanation: 'K+V proti K je základní, vynucená výhra pro stranu s věží.' },
  'rm-end-34': { introduction: 'K čemu věž slouží při matování?', question: 'Při matu K+V proti K se věž používá k tomu, aby:', options: ['Blokovala vlastního krále', 'Odřízla soupeřova krále od části šachovnice', 'Proměnila', 'Bránila pěšce'], explanation: 'Věž odřezává krále podél řady nebo sloupce a zmenšuje prostor, ve kterém se může pohybovat.' },
  'rm-end-35': { introduction: 'Jak se říká metodě postupného zmenšování prostoru krále?', question: 'Metoda zmenšování dostupného prostoru soupeřova krále pomocí věže se často nazývá:', options: ['Větrný mlýn', 'Vidlička', 'Metoda krabice nebo schodů', 'Rožeň'], explanation: 'Zahánění krále postupným zmenšováním „krabice“ ho krok za krokem nutí k okraji.' },
  'rm-end-36': { introduction: 'Jak stojí králové při matu věží?', question: 'Aby dali mat věží, oba králové obvykle stojí:', options: ['Na stejném poli', 'V protilehlých rozích', 'Vedle sebe', 'V přímé opozici'], explanation: 'Králové stojí proti sobě v opozici a věž dá mat na okraji.' },
  'rm-end-37': { introduction: 'Kde padne mat v koncovce K+V proti K?', question: 'V koncovce K+V proti K je mat vynucen na:', options: ['Okraji šachovnice', 'V centru', 'Jen na světlém poli', 'Jen na sloupci věže'], explanation: 'Samotný král je zatlačen k okraji, kde ho věž dá šach bez možnosti úniku.' },
  'rm-end-38': { introduction: 'Jaké nebezpečí hrozí i s věží?', question: 'Při matování věží musíš stále dávat pozor na:', options: ['Proměnu', 'Pat', 'Rošádu', 'Braní mimochodem'], explanation: 'I s věží můžeš omylem ponechat samotného krále bez legálního tahu: pat.' },
  'rm-end-39': { introduction: 'Jakou roli hraje král silnější strany?', question: 'Úlohou krále silnější strany v koncovce K+V proti K je:', options: ['Nepřekážet', 'Sebrat věž', 'Stát v opozici proti soupeřovu králi, aby věž mohla matovat', 'Proměnit pěšce'], explanation: 'Král zaujme opozici a kontroluje úniková pole, aby věž mohla dát mat.' },
  'rm-end-40': { introduction: 'Funguje odříznutí i z dálky?', question: 'Pokud je věž daleko od králů, když odřezává soupeřova krále, technika stále funguje, protože věž:', options: ['Může být bezpečně sebrána', 'Táhne jako střelec', 'Musí zůstat vedle krále', 'Kontroluje celou řadu nebo sloupec z dálky'], explanation: 'Věž odřezává celou linii z jakékoli vzdálenosti, takže může krále omezovat i zdálky.' },

  // ── Úroveň 6 — Základy věžových koncovek ─────────────────────────────
  'rm-end-41': { introduction: 'Kam podle Tarrasche patří věž vůči volnému pěšci?', question: 'Slavné pravidlo o věžích a volných pěšcích (od Tarrasche) říká, že věž patří:', options: ['Za volného pěšce', 'Před volného pěšce', 'Vedle volného pěšce', 'Na první řadu'], explanation: 'Tarraschovo pravidlo: „Věže patří za volné pěšce“ — jak za vlastní, tak za soupeřovy.' },
  'rm-end-42': { introduction: 'Jaká je pověst věžových koncovek?', question: 'Věžové koncovky jsou známé tím, že jsou:', options: ['Vždy rozhodné', 'Nejčastější a často remízové', 'V praxi vzácné', 'Nemožné remizovat'], explanation: 'Věžové koncovky jsou nejčastější koncovkou a mají silný sklon k remíze.' },
  'rm-end-43': { introduction: 'Co dělá věž „aktivní“?', question: '„Aktivní“ věž v koncovce je taková, která:', options: ['Sedí pasivně a brání', 'Zůstává na výchozím poli', 'Útočí na pěšce a kontroluje otevřené linie', 'Blokuje vlastního krále'], explanation: 'Aktivní věže, které útočí na pěšce a obsazují otevřené sloupce, jsou mnohem silnější než pasivní.' },
  'rm-end-44': { introduction: 'Proč umístit věž za vlastního volného pěšce?', question: 'Umístění věže za vlastního volného pěšce je dobré, protože:', options: ['Blokuje pěšce', 'Ztratí věž', 'Vynutí pat', 'Podporuje pěšce při jeho postupu'], explanation: 'Zezadu věž pěšce brání a získává akční rádius, jak pěšec postupuje vpřed.' },
  'rm-end-45': { introduction: 'Proč umístit věž za soupeřova volného pěšce?', question: 'Umístění věže za soupeřova volného pěšce je dobré, protože:', options: ['Brzdí pěšce a poutá jeho obránce', 'Pomáhá pěšci proměnit se', 'Okamžitě vyhrává', 'Je proti pravidlům'], explanation: 'Za soupeřovým pěšcem tvá věž zastavuje jeho postup a nutí soupeře k pasivní obraně.' },
  'rm-end-46': { introduction: 'Proč jsou otevřené sloupce cenné?', question: 'Ve věžových koncovkách je cenné držet věž na otevřeném sloupci, protože otevřené sloupce:', options: ['Uvězní tvého vlastního krále', 'Dávají věži maximální aktivitu', 'Nemohou být věžemi využity', 'Blokují pěšce'], explanation: 'Otevřené sloupce umožňují věži se pohybovat a útočit, což je zdroj síly věže v koncovce.' },
  'rm-end-47': { introduction: 'K čemu je dobré odříznout soupeřova krále?', question: 'Odříznutí soupeřova krále podél sloupce nebo řady tvou věží je užitečné, protože:', options: ['Vyhrává věž', 'Promění pěšce', 'Brání králi pomáhat svým pěšcům nebo obraně', 'Vynutí remízu'], explanation: 'Věž, která odřízne krále, ho izoluje od dění — klíčová technika věžových koncovek.' },
  'rm-end-48': { introduction: 'Proč je pasivní věž problém?', question: 'Pasivní věž uvázlá u obrany pěšce je problém, protože:', options: ['Je příliš silná', 'Nemůže být sebrána', 'Vždy remizuje', 'Ztrácí aktivitu a nechává soupeře postupovat'], explanation: 'Uvázání věže u pasivní obrany se vzdává aktivity, která věže činí silnými.' },

  // ── Úroveň 7 — Lucenova a Philidorova pozice ─────────────────────────
  'rm-end-49': { introduction: 'K čemu Lucenova pozice slouží?', question: 'Lucenova pozice je:', options: ['Vyhrávající technika v koncovce věž a pěšec proti věži', 'Remízová metoda pro obránce', 'Mat dvěma jezdci', 'Zahajovací past'], explanation: 'Lucenova pozice je klasická vyhrávající metoda pro silnější stranu v koncovce věž a pěšec proti věži.' },
  'rm-end-50': { introduction: 'Jak se jmenuje vyhrávající manévr v Lucenově pozici?', question: 'Vyhrávající manévr v Lucenově pozici se nazývá:', options: ['Větrný mlýn', 'Stavba mostu', 'Dlouhá rošáda', 'Trik s vidličkou'], explanation: '„Stavba mostu“ využívá věž k zaclonění krále před šachy, aby se pěšec mohl proměnit.' },
  'rm-end-51': { introduction: 'K čemu Philidorova pozice slouží?', question: 'Philidorova pozice je:', options: ['Vyhrávající metoda pro útočníka', 'Mat dámou', 'Klíčová remízová technika pro obránce v koncovce V+P proti V', 'Pěšcová struktura'], explanation: 'Philidorova pozice je zásadní remízové postavení pro obránce ve věžových koncovkách.' },
  'rm-end-52': { introduction: 'Na které řadě drží obránce věž při Philidorově obraně?', question: 'Philidorova obrana drží bránící se věž na:', options: ['První řadě', 'Soupeřově základní řadě', 'Stejném sloupci jako její král', 'Třetí řadě (dokud pěšec nepostoupí)'], explanation: 'Obránce drží třetí řadu, aby zabránil postupu soupeřova krále, a poté dává šachy zezadu.' },
  'rm-end-53': { introduction: 'Kam jde věž, jakmile pěšec postoupí?', question: 'Při Philidorově remíze, jakmile pěšec postoupí na obráncovu třetí řadu, věž jde:', options: ['Daleko dozadu, aby dávala králi šachy zezadu', 'Před pěšce', 'Mimo šachovnici', 'Vedle krále'], explanation: 'Bránící se věž ustoupí dozadu a dává šachy zezadu, kterým král nemůže uniknout.' },
  'rm-end-54': { introduction: 'V jakém typu koncovky obě pozice vznikají?', question: 'Lucenova i Philidorova pozice vznikají v jakém typu koncovky?', options: ['Dáma proti pěšci', 'Věž a pěšec proti věži', 'Dva střelci proti králi', 'Král a pěšec proti králi'], explanation: 'Obě jsou zásadní referenční pozice pro koncovky věž a pěšec proti věži.' },
  'rm-end-55': { introduction: 'Co ti řekne znalost Lucenovy pozice?', question: 'Znalost Lucenovy pozice je důležitá, protože ti řekne, kdy je V+P proti V:', options: ['Vynucená remíza', 'Pat', 'Výhra, a přesně jak ji dotáhnout', 'Nelegální'], explanation: 'Lucenova pozice ukazuje vyhrávající metodu, takže víš, že je pozice vyhraná a jak ji dokončit.' },
  'rm-end-56': { introduction: 'Co ti řekne znalost Philidorovy pozice?', question: 'Znalost Philidorovy pozice je důležitá, protože obránci řekne, jak:', options: ['Vyhrát věž', 'Proměnit pěšce', 'Dát mat', 'Udržet remízu ve V+P proti V'], explanation: 'Philidorova pozice dává obránci spolehlivou remízovou metodu proti věži a pěšci.' },

  // ── Úroveň 8 — Koncovky lehkých figur ────────────────────────────────
  'rm-end-57': { introduction: 'Zvládne samotný střelec vynutit mat?', question: 'Král a jediný střelec proti samotnému králi je:', options: ['Remíza (nedostatečný materiál)', 'Vynucená výhra', 'Prohra pro střelce', 'Výhra patem'], explanation: 'Samotný střelec nemůže vynutit mat, takže K+S proti K je remíza pro nedostatek materiálu.' },
  'rm-end-58': { introduction: 'Zvládne samotný jezdec vynutit mat?', question: 'Král a jediný jezdec proti samotnému králi je:', options: ['Vynucená výhra', 'Remíza (nedostatečný materiál)', 'Výhra jen pro bílého', 'Prohra'], explanation: 'Samotný jezdec také nemůže vynutit mat, takže K+J proti K je remíza.' },
  'rm-end-59': { introduction: 'Zvládnou dva jezdci vynutit mat?', question: 'Král a DVA jezdci proti samotnému králi je obecně:', options: ['Snadná výhra', 'Pat pro obránce', 'Nemožné vynutit mat', 'Nelegální'], explanation: 'Dva jezdci nemohou vynutit mat proti samotnému králi (kromě vzácných případů s pomocným pěšcem).' },
  'rm-end-60': { introduction: 'Co znamená „špatný střelec“?', question: '„Střelec špatné barvy“ s věžovým pěšcem může být remíza i s figurou navíc, pokud střelec:', options: ['Kontroluje pole proměny', 'Je na stejné barvě jako král', 'Je vyměněn', 'NEKONTROLUJE pole proměny pěšce'], explanation: 'Pokud střelec nedokáže pokrýt roh, kde se věžový pěšec promění, obránce remizuje.' },
  'rm-end-61': { introduction: 'Kdy je střelec silnější než jezdec?', question: 'Ve srovnání s jezdcem je střelec v koncovkách obvykle silnější, když:', options: ['Se hraje na obou křídlech na otevřené šachovnici', 'Jsou všichni pěšci na jedné straně', 'Je šachovnice uzavřená', 'Nejsou žádní pěšci'], explanation: 'Střelci vynikají na otevřené šachovnici s pěšci na obou křídlech díky svému dlouhému dosahu.' },
  'rm-end-62': { introduction: 'Kdy je jezdec přinejmenším stejně dobrý jako střelec?', question: 'Jezdec bývá přinejmenším stejně dobrý jako střelec, když:', options: ['Je pozice velmi otevřená', 'Je pěšcová struktura pevná a uzavřená', 'Jsou pěšci na obou stranách', 'Nejsou vůbec žádní pěšci'], explanation: 'Jezdci se daří v uzavřených pozicích s pevnými pěšci, kde je střelec zablokovaný.' },
  'rm-end-63': { introduction: 'K čemu vede pěšec navíc u různobarevných střelců?', question: 'V koncovkách různobarevných střelců vede jeden nebo dva pěšci navíc často k:', options: ['Snadné výhře', 'Okamžitému matu', 'Silným remízovým šancím pro obránce', 'Prohře obránce'], explanation: 'Různobarevní střelci jsou pověstně remízoví, protože každý střelec hlídá pole, na která ten druhý nemůže útočit.' },
  'rm-end-64': { introduction: 'Zvládnou dva střelci vynutit mat?', question: 'Král a dva střelci proti samotnému králi je:', options: ['Remíza', 'Výhra jen s pěšcem', 'Nedostatečný materiál', 'Vynucený mat'], explanation: 'Na rozdíl od dvou jezdců dokážou dva střelci vynutit mat proti samotnému králi.' },

  // ── Úroveň 9 — Aktivita krále ────────────────────────────────────────
  'rm-end-65': { introduction: 'Jak se mění role krále mezi střední hrou a koncovkou?', question: 'Klíčový rozdíl pro krále mezi střední hrou a koncovkou je, že v koncovce král:', options: ['Se stává silnou, aktivní bojovou figurou', 'Se musí vždy schovávat', 'Nemůže táhnout', 'Je vyřazen ze hry'], explanation: 'Když je většina figur pryč, král se může bezpečně zapojit do hry a stává se mocným útočníkem.' },
  'rm-end-66': { introduction: 'Kam by měl král v koncovce směřovat?', question: 'Do které části šachovnice by měl král v koncovce obvykle mířit?', options: ['Do rohu', 'Do centra', 'Na svou základní řadu', 'Mimo šachovnici'], explanation: 'Centralizovaný král ovlivňuje nejvíce polí a podporuje pěšce na obou křídlech.' },
  'rm-end-67': { introduction: 'Jak může aktivní král rozhodnout pěšcový závod?', question: 'V závodě králů a pěšců může aktivní, postoupený král rozhodnout partii tím, že:', options: ['Nedělá nic', 'Ustupuje', 'Doprovodí pěšce a zastaví soupeřova', 'Znovu rošuje'], explanation: 'Aktivnější král jak proměňuje vlastního pěšce, tak dohání soupeřova.' },
  'rm-end-68': { introduction: 'K čemu slouží „pravidlo čtverce“?', question: '„Pravidlo čtverce“ ti pomáhá rozhodnout, zda:', options: ['Je střelec dobrý', 'Je věž aktivní', 'Je pat', 'Král dokáže dohonit běžícího volného pěšce'], explanation: 'Pokud je král uvnitř pomyslného čtverce volného pěšce, dokáže pěšce dohonit dříve, než se promění.' },
  'rm-end-69': { introduction: 'Proč přivést krále brzy do hry?', question: 'Přivedení krále do dění brzy v koncovce je důležité, protože:', options: ['Pasivní král často stojí partii', 'Králové jsou bezcenní', 'Způsobuje to pat', 'Je to proti pravidlům'], explanation: 'Král ponechaný vzadu je vlastně figura méně; jeho aktivace je často rozhodující.' },
  'rm-end-70': { introduction: 'K čemu je aktivní král ve věžové koncovce?', question: 'Aktivní král ve věžové koncovce je cenný, protože může:', options: ['Být snadno sebrán', 'Podporovat pěšce a odstrkovat soupeřova krále', 'Táhnout jako dáma', 'Nikdy nebýt v šachu'], explanation: 'Král doprovází pěšce a „odstrkuje“ soupeřova krále z klíčových polí.' },
  'rm-end-71': { introduction: 'Co nejlépe vystihuje dobrou hru krále v koncovce?', question: 'Co z uvedeného nejlépe vystihuje dobrou hru krále v koncovce?', options: ['Držet krále bezpečně v rohu', 'Nikdy netáhnout králem', 'Centralizovat a využívat krále aktivně', 'Vyměnit krále za věž'], explanation: 'Centralizace a aktivace krále je základní princip dobré koncovkové techniky.' },
  'rm-end-72': { introduction: 'Co znamená „odstrkování“ králem?', question: '„Odstrkování“ neboli „bodyček“ králem znamená:', options: ['Blokovat vlastní věž', 'Dávat šach králem', 'Rošovat v koncovce', 'Používat svého krále k tomu, aby držel soupeřova krále dál od klíčových polí'], explanation: 'Král může obsadit pole, která soupeřovu králi odepřou přístup — důležitá koncovková zbraň.' },

  // ── Úroveň 10 — Mistrovství koncovek ─────────────────────────────────
  'rm-end-73': { introduction: 'Za jakých podmínek platí pravidlo 50 tahů?', question: 'Pravidlo 50 tahů umožňuje nárokovat remízu po 50 tazích každé strany bez:', options: ['Braní a bez tahu pěšcem', 'Daného šachu', 'Rošády', 'Proměny'], explanation: 'Pokud uplyne 50 tahů každého hráče bez braní a bez tahu pěšcem, může kterákoli strana nárokovat remízu.' },
  'rm-end-74': { introduction: 'Vzpomeneš si na klasickou remízu se „špatným střelcem“?', question: 'Jsi o celou figuru napřed s věžovým pěšcem a střelcem, který NEKONTROLUJE pole proměny, a soupeřův král se dostane do rohu. Výsledek je:', options: ['Snadná výhra', 'Remíza', 'Prohra', 'Výhra patem'], explanation: 'Toto je klasická remíza „špatného střelce“: obránce sedí v rohu a nelze ho vypudit.' },
  'rm-end-75': { introduction: 'Jak se jmenují remízové a vyhrávající pozice ve V+P proti V?', question: 'Ve V+P proti V obránce zná postavení k udržení remízy a útočník zná postavení k výhře. Tato jsou po řadě:', options: ['Lucenova a Philidorova', 'Zugzwang a opozice', 'Philidorova a Lucenova', 'Krabice a most'], explanation: 'Philidorova pozice je remízové postavení obránce; Lucenova pozice je vyhrávající postavení útočníka.' },
  'rm-end-76': { introduction: 'Která kombinace figur nedokáže vynutit mat?', question: 'Která kombinace NEDOKÁŽE vynutit mat proti samotnému králi?', options: ['Král a dáma', 'Král a věž', 'Král a dva střelci', 'Král a dva jezdci'], explanation: 'Dva jezdci nemohou vynutit mat, zatímco K+D, K+V i K+2S všechny vyhrávají.' },
  'rm-end-77': { introduction: 'Jaký je výsledek při přímé opozici s králem před pěšcem a soupeřem na tahu?', question: 'V koncovce krále a pěšce dosáhneš přímé opozice s králem před svým pěšcem a soupeř je na tahu. Nejpravděpodobněji:', options: ['Vyhráváš', 'Prohráváš', 'Jsi v patu', 'Jsi nucen k remíze'], explanation: 'Král před pěšcem plus opozice, se soupeřem na tahu, je vyhrávající recept.' },
  'rm-end-78': { introduction: 'Stačí pěšec navíc u různobarevných střelců?', question: 'Máš pěšce navíc v koncovce různobarevných střelců bez dalších figur. Nejpravděpodobnější výsledek při dobré obraně je:', options: ['Pohodlná výhra', 'Remíza', 'Prohra', 'Vynucený mat'], explanation: 'Koncovky různobarevných střelců jsou velmi remízové, takže jediný pěšec navíc často nestačí.' },
  'rm-end-79': { introduction: 'Jak zhodnotit pasivní věž a odříznutého krále?', question: 'Tvá věž je pasivně uvázaná u obrany pěšce, zatímco soupeřova věž je aktivní a tvůj král je odříznutý. Obecné hodnocení je, že jsi:', options: ['Lépe', 'Vyhráváš snadno', 'Hůře a měl bys hledat aktivitu nebo protihru', 'V patové situaci'], explanation: 'Pasivní věž plus odříznutý král je špatné znamení; aktivita má ve věžových koncovkách větší cenu než pěšec.' },
  'rm-end-80': { introduction: 'Které jediné tvrzení nejlépe vystihuje vyhrávající strategii koncovek?', question: 'Které jediné tvrzení nejlépe vystihuje vyhrávající strategii koncovek?', options: ['Držet krále schovaného a figury pasivní', 'Vyhýbat se jakýmkoli výměnám', 'Vždy usilovat o pat', 'Aktivovat krále, tlačit volné pěšce a stavět věže za ně'], explanation: 'Aktivní král, postupující volní pěšci a věže za volnými pěšci shrnují zdravou hru v koncovce.' },
};
