import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Hand Rankings & Basics roadmap bank (rm-pkhands-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const handRankingsTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-pkhands-1': { introduction: 'Nejsilnější možná kombinace v pokeru.', question: 'Jaká je nejlepší možná kombinace v pokeru?', options: ['Royal flush', 'Postupková hráze (straight flush)', 'Čtveřice (four of a kind)', 'Full house'], explanation: 'Royal flush (10-J-Q-K-A jedné barvy) je nejvyšší kombinace a nelze ji porazit.' },
  'rm-pkhands-2': { introduction: 'Porovnej barvu a postupku.', question: 'Která kombinace je vyšší: barva (flush), nebo postupka (straight)?', options: ['Barva (flush)', 'Postupka (straight)', 'Jsou stejné', 'Záleží na barvě karet'], explanation: 'Barva (pět karet jedné barvy) je vyšší než postupka (pět po sobě jdoucích), protože je vzácnější.' },
  'rm-pkhands-3': { introduction: 'Tři plus dvě karty.', question: 'Jak se nazývá kombinace tří karet jedné hodnoty a dvou karet jiné hodnoty?', options: ['Full house', 'Dva páry', 'Trojice (three of a kind)', 'Barva (flush)'], explanation: 'Full house je trojice spojená s párem, například tři osmičky a dva králové.' },
  'rm-pkhands-4': { introduction: 'Nejslabší kategorie.', question: 'Která kombinace je ve standardním pokeru nejnižší?', options: ['Vysoká karta', 'Jeden pár', 'Dva páry', 'Postupka'], explanation: 'Vysoká karta je nejslabší: žádný pár, postupka ani barva, takže rozhoduje jen nejvyšší karta.' },
  'rm-pkhands-5': { introduction: 'Pět karet jedné barvy, ale ne v řadě.', question: 'Pět karet stejné barvy, které nejdou po sobě, tvoří?', options: ['Barvu (flush)', 'Postupku (straight)', 'Postupkovou hráz (straight flush)', 'Full house'], explanation: 'Barva je jakýchkoli pět karet jedné barvy, které nejsou v souvislé řadě.' },
  'rm-pkhands-6': { introduction: 'Porovnej čtveřici a full house.', question: 'Která kombinace je vyšší: čtveřice (four of a kind), nebo full house?', options: ['Čtveřice (four of a kind)', 'Full house', 'Jsou stejné', 'Barva (flush)'], explanation: 'Čtveřice poráží full house; čtyři stejné karty jsou vzácnější než kombinace tři plus dvě.' },
  'rm-pkhands-7': { introduction: 'Pět po sobě jdoucích, různé barvy.', question: 'Pět karet jdoucích po sobě, ale různých barev, je?', options: ['Postupka (straight)', 'Barva (flush)', 'Postupková hráz (straight flush)', 'Full house'], explanation: 'Postupka je pět po sobě jdoucích hodnot v libovolných barvách, například 6-7-8-9-10.' },
  'rm-pkhands-8': { introduction: 'Porovnej dva páry a trojici.', question: 'Která kombinace je vyšší: dva páry, nebo trojice (three of a kind)?', options: ['Trojice (three of a kind)', 'Dva páry', 'Jeden pár', 'Jsou stejné'], explanation: 'Trojice poráží dva páry a stojí o jeden stupeň výš v pořadí kombinací.' },

  'rm-pkhands-9': { introduction: 'Kolik karet tvoří finální kombinaci.', question: 'V Texas Hold\'em se tvá finální kombinace skládá z čeho?', options: ['Nejlepších 5 z tvých 7 karet', 'Všech 7 karet', 'Jen tvých 2 karet v ruce', 'Jen 5 karet na stole'], explanation: 'Spojíš dvě karty v ruce a pět společných karet a ponecháš si nejlepší pětikaretní kombinaci.' },
  'rm-pkhands-10': { introduction: 'Karty, které vidí jen ty.', question: 'Kolik soukromých karet do ruky dostane každý hráč?', options: ['Dvě', 'Tři', 'Čtyři', 'Pět'], explanation: 'Každý hráč dostane přesně dvě karty do ruky, které vidí jen on.' },
  'rm-pkhands-11': { introduction: 'Společné karty na stole.', question: 'Kolik společných karet leží lícem nahoru do riveru?', options: ['Pět', 'Tři', 'Čtyři', 'Šest'], explanation: 'Na stole je celkem pět karet: tři na flopu, jedna turn a jedna river.' },
  'rm-pkhands-12': { introduction: 'Kolik karet z ruky musíš použít.', question: 'Musíš pro sestavení kombinace použít obě karty z ruky?', options: ['Ne, libovolnou kombinaci', 'Ano, vždy obě', 'Ano, aspoň jednu', 'Ne, jen jednu je povoleno'], explanation: 'V Hold\'em můžeš použít dvě, jednu, nebo žádnou kartu z ruky, podle toho, co dá nejlepších pět.' },
  'rm-pkhands-13': { introduction: 'Přečti si kombinaci.', question: 'Máš K-K; na stole je K-7-2-9-4. Tvá nejlepší kombinace je?', options: ['Trojice (three of a kind)', 'Full house', 'Dva páry', 'Jeden pár'], explanation: 'Dva králové v ruce plus král na stole dají trojici (set králů).' },
  'rm-pkhands-14': { introduction: 'Počítej karty jedné barvy.', question: 'Máš kárové A a 5; na stole káro K-9-2 a mimo barvu 7-3. Tvá kombinace?', options: ['Barva (flush)', 'Postupka (straight)', 'Trojice (three of a kind)', 'Vysoká karta'], explanation: 'Tvé dvě kárové karty plus tři kára na stole tvoří barvu s esem nahoře.' },
  'rm-pkhands-15': { introduction: 'Trojice plus pár.', question: 'Máš 6-6; na stole 6-9-9-2-K. Tvá nejlepší kombinace je?', options: ['Full house', 'Trojice (three of a kind)', 'Dva páry', 'Barva (flush)'], explanation: 'Tři šestky (dvě v ruce, jedna na stole) plus pár devítek dají full house, šestky plné devítek.' },
  'rm-pkhands-16': { introduction: 'Postupka může ležet přímo na stole.', question: 'Na stole je 5-6-7-8-9 (různé barvy); máš 2-3. Tvá nejlepší kombinace?', options: ['Postupka (straight)', 'Barva (flush)', 'Dva páry', 'Vysoká karta'], explanation: 'Samotný stůl tvoří postupku s devítkou nahoře, takže jen hraješ stůl a máš postupku.' },

  'rm-pkhands-17': { introduction: 'Co rozhodne při shodě kombinací.', question: 'Oba hráči mají pár králů. Co rozhodne o vítězi?', options: ['Vedlejší karty (kickery)', 'Barvy karet', 'Vždy se dělí', 'Pozice u stolu'], explanation: 'Když je hlavní kombinace stejná, rozhodnou nejvyšší vedlejší karty (kickery); barvy nikdy.' },
  'rm-pkhands-18': { introduction: 'Porovnej kickery.', question: 'A-K vs A-Q na stole A-7-4-2-9. Kdo vyhraje?', options: ['Vyhraje A-K', 'Vyhraje A-Q', 'Dělený bank', 'A-Q podle barvy'], explanation: 'Oba mají pár es; král jako kicker poráží dámu, takže vyhraje A-K.' },
  'rm-pkhands-19': { introduction: 'Rozhodují barvy o shodě?', question: 'Rozhodne někdy barva o shodě dvou jinak stejných kombinací?', options: ['Ne, barvy jsou rovnocenné', 'Ano, piky vyhrávají', 'Ano, srdce vyhrávají', 'Jen u barvy (flush)'], explanation: 'Ve standardním pokeru mají všechny barvy stejnou hodnotu; zcela shodné kombinace dělí bank.' },
  'rm-pkhands-20': { introduction: 'Dvě barvy stejné barvy.', question: 'Oba hráči mají srdcovou barvu (flush). Jak se rozhodne?', options: ['Nejvyšší karta barvy', 'Počet srdcí', 'Pořadí barvy', 'Vždy se dělí'], explanation: 'Barvy se porovnávají kartu po kartě odshora; vyhraje první vyšší odlišná karta.' },
  'rm-pkhands-21': { introduction: 'Když nejlepší kombinaci tvoří stůl.', question: 'Oba hráči hrají stejnou postupku pouze ze stolu. Výsledek?', options: ['Dělený bank', 'Vyhraje vyšší karta v ruce', 'Rozhodne dealer', 'Rozhodne barva'], explanation: 'Pokud nejlepší kombinací je samotný stůl a nikdo ji nevylepší, bank se dělí.' },
  'rm-pkhands-22': { introduction: 'Eso může hrát dolů.', question: 'Eso může hrát nahoře i dole. Která postupka je nejnižší?', options: ['A-2-3-4-5', '2-3-4-5-6', '10-J-Q-K-A', '5-6-7-8-9'], explanation: 'A-2-3-4-5, tzv. „kolo" (wheel), je nejnižší postupka, kde eso hraje jako jednička.' },
  'rm-pkhands-23': { introduction: 'Porovnání dvou full house.', question: 'Při porovnání dvou full house rozhoduje jako první co?', options: ['Hodnota trojice', 'Hodnota páru', 'Kicker', 'Barva'], explanation: 'Rozhoduje trojice: devítky plné čehokoli porazí šestky plné čehokoli bez ohledu na páry.' },
  'rm-pkhands-24': { introduction: 'Dva páry proti dvěma párům.', question: 'Dvě kombinace dvou párů: K-K-5-5 vs K-K-3-3. Kdo vyhraje?', options: ['K-K-5-5', 'K-K-3-3', 'Dělený bank', 'Rozhodne kicker'], explanation: 'Vyšší páry se shodují na králích, takže rozhodne vyšší druhý pár (pětky nad trojkami).' },

  'rm-pkhands-25': { introduction: 'Nejvzácnější z uvedených.', question: 'Která z těchto pětikaretních kombinací je nejvzácnější?', options: ['Postupková hráz (straight flush)', 'Full house', 'Barva (flush)', 'Postupka (straight)'], explanation: 'Postupkové hráze jsou z těchto nejvzácnější, proto stojí nejvýš v pořadí.' },
  'rm-pkhands-26': { introduction: 'Jak často máš v ruce pár.', question: 'Jak často jsou tvé dvě karty v ruce kapesní pár?', options: ['Asi 1 ku 17', 'Asi 1 ku 2', 'Asi 1 ku 100', 'Asi 1 ku 1000'], explanation: 'Kapesní pár přijde přibližně jednou za 17 rozdání (zhruba v 6 % případů).' },
  'rm-pkhands-27': { introduction: 'Konkrétně esa.', question: 'Jaká je šance, že dostaneš do ruky přesně kapesní esa?', options: ['Asi 1 ku 221', 'Asi 1 ku 17', 'Asi 1 ku 52', 'Asi 1 ku 1000'], explanation: 'Kterýkoli konkrétní kapesní pár, včetně es, přijde přibližně jednou za 221 rozdání.' },
  'rm-pkhands-28': { introduction: 'Co je častější.', question: 'Co je v náhodné pětikaretní kombinaci častější?', options: ['Dva páry', 'Trojice (three of a kind)', 'Postupka', 'Barva'], explanation: 'Dva páry (asi 4,75 %) jsou častější než trojice (asi 2,1 %).' },
  'rm-pkhands-29': { introduction: 'Jak často nic nevznikne.', question: 'Zhruba jaká část náhodných pětikaretních kombinací je jen „vysoká karta"?', options: ['Asi 50 %', 'Asi 5 %', 'Asi 1 %', 'Asi 90 %'], explanation: 'Zhruba polovina všech pětikaretních kombinací nedá nic lepšího než vysokou kartu.' },
  'rm-pkhands-30': { introduction: 'Dvě karty stejné barvy.', question: 'Máš dvě karty stejné barvy. Jaká je šance na flopnutí čtyř do barvy (flush draw)?', options: ['Asi 11 %', 'Asi 50 %', 'Asi 1 %', 'Asi 33 %'], explanation: 'Čtyřkaretní draw na barvu flopneš zhruba v 11 % případů, asi jednou z devíti flopů.' },
  'rm-pkhands-31': { introduction: 'S kapesním párem.', question: 'S kapesním párem, jaká je šance na flopnutí setu (trojice) nebo lepší?', options: ['Asi 12 %', 'Asi 50 %', 'Asi 1 %', 'Asi 30 %'], explanation: 'Kapesní pár flopne set nebo lepší asi ve 12 % případů, zhruba 1 z 8,5.' },
  'rm-pkhands-32': { introduction: 'Nejčastější reálná kombinace.', question: 'Kromě vysoké karty, která hotová kombinace je nejčastější?', options: ['Jeden pár', 'Dva páry', 'Barva', 'Postupka'], explanation: 'Jeden pár je zdaleka nejčastější hotová kombinace, vzniká asi ve 42 % případů.' },

  'rm-pkhands-33': { introduction: 'Eso dole.', question: 'Počítá se A-2-3-4-5 jako postupka?', options: ['Ano, postupka s pětkou nahoře', 'Ne, eso musí být nahoře', 'Jen v lowballu', 'Ne, je to vysoká karta'], explanation: 'Ano, eso zde hraje dole a tvoří postupku s pětkou nahoře, tzv. kolo (wheel).' },
  'rm-pkhands-34': { introduction: 'Postupka kolem esa.', question: 'Počítá se Q-K-A-2-3 jako postupka (obtočení kolem esa)?', options: ['Ne, postupky se neobtáčejí', 'Ano, eso spojuje', 'Ano, s esem nahoře', 'Jen když stejné barvy'], explanation: 'Postupky se nemohou obtočit; eso je buď nahoře, nebo dole, nikdy obojí zároveň.' },
  'rm-pkhands-35': { introduction: 'Broadway na stole.', question: 'Na stole je 10-J-Q-K-A (různé barvy) a nikdo nemá barvu. Výsledek?', options: ['Dělený bank', 'Vyhraje vyšší karta v ruce', 'Vyhraje první na tahu', 'Vyhraje nejvyšší kicker'], explanation: 'Všichni hrají postupku stolu s esem nahoře (Broadway), takže se bank dělí.' },
  'rm-pkhands-36': { introduction: 'Barva proti full house.', question: 'Ty máš barvu; soupeř má full house. Kdo vyhraje?', options: ['Full house', 'Barva (flush)', 'Dělený bank', 'Záleží na barvě'], explanation: 'Full house je vyšší než barva, takže vyhraje full house.' },
  'rm-pkhands-37': { introduction: 'Čtveřice na stole a kicker.', question: 'Na stole 8-8-8-8-K. Máš A-2, soupeř má Q-J. Kdo vyhraje?', options: ['Vyhraješ ty (eso jako kicker)', 'Vyhraje soupeř (dáma jako kicker)', 'Dělený bank', 'Čtveřice se vždy dělí'], explanation: 'Oba mají čtyři osmičky; tvé eso hraje jako pátá karta a poráží krále na stole.' },
  'rm-pkhands-38': { introduction: 'Hráz proti čtveřici.', question: 'Postupková hráz (straight flush) proti čtveřici (four of a kind). Co vyhraje?', options: ['Postupková hráz (straight flush)', 'Čtveřice (four of a kind)', 'Dělený bank', 'Záleží na kartách'], explanation: 'Postupková hráz je vyšší než čtveřice, takže vyhraje showdown.' },
  'rm-pkhands-39': { introduction: 'Čtyři esa na stole.', question: 'Na stole A-A-A-A-K. Máš 2-3, soupeř má 4-5. Výsledek?', options: ['Dělený bank', 'Vyhraješ ty', 'Vyhraje soupeř', 'Vyhraje vyšší karta v ruce'], explanation: 'Oba hrají čtyři esa s králem ze stolu jako pátou kartou; všechny karty v ruce jsou nižší, takže se dělí.' },
  'rm-pkhands-40': { introduction: 'Dvě barvy s esem nahoře.', question: 'Dvě barvy s esem nahoře: další karta hráče A je K, hráče B je Q. Kdo vyhraje?', options: ['Hráč A (král)', 'Hráč B (dáma)', 'Dělený bank', 'Záleží na barvě'], explanation: 'Barvy se porovnávají kartu po kartě; po společném esu poráží král dámu.' },
};
