// Cell Biology & Biochemistry roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const cellBiologySeeds: Seed[] = [
  // ── Level 1 — Cell structure & organelles ──
  { q: 'Which organelle is known as the "control centre" of the cell, holding its DNA?', opts: ['Nucleus', 'Ribosome', 'Lysosome', 'Golgi apparatus'], a: 0, e: 'The nucleus stores the cell\'s genetic material (DNA) and directs cell activities.', tags: ['Cell Biology', 'Organelles'] },
  { q: 'Which organelle is the main site of ATP production and is called the "powerhouse" of the cell?', opts: ['Mitochondrion', 'Nucleus', 'Vacuole', 'Ribosome'], a: 0, e: 'Mitochondria carry out aerobic respiration, generating most of the cell\'s ATP.', tags: ['Cell Biology', 'Organelles'] },
  { q: 'What structure surrounds the cell and controls what enters and leaves?', opts: ['Cell membrane', 'Nucleolus', 'Cytoplasm', 'Chromosome'], a: 0, e: 'The cell (plasma) membrane is a selectively permeable barrier regulating transport in and out.', tags: ['Cell Biology', 'Organelles'] },
  { q: 'Which organelles are the site of protein synthesis?', opts: ['Ribosomes', 'Lysosomes', 'Vacuoles', 'Centrioles'], a: 0, e: 'Ribosomes assemble amino acids into proteins by reading messenger RNA.', tags: ['Cell Biology', 'Organelles'] },
  { q: 'Which feature is found in plant cells but NOT in animal cells?', opts: ['Cell wall', 'Nucleus', 'Mitochondria', 'Cell membrane'], a: 0, e: 'Plant cells have a rigid cellulose cell wall outside the membrane; animal cells lack one.', tags: ['Cell Biology', 'Cell types'] },
  { q: 'Which organelle in plant cells captures light energy for photosynthesis?', opts: ['Chloroplast', 'Mitochondrion', 'Lysosome', 'Nucleus'], a: 0, e: 'Chloroplasts contain chlorophyll and convert light energy into chemical energy (glucose).', tags: ['Cell Biology', 'Organelles'] },
  { q: 'What key feature distinguishes eukaryotic cells from prokaryotic cells?', opts: ['A membrane-bound nucleus', 'The presence of DNA', 'A cell membrane', 'Ribosomes'], a: 0, e: 'Eukaryotes keep their DNA inside a membrane-bound nucleus; prokaryotes have no true nucleus.', tags: ['Cell Biology', 'Cell types'] },
  { q: 'Which organelle modifies, sorts, and packages proteins for secretion?', opts: ['Golgi apparatus', 'Ribosome', 'Nucleolus', 'Mitochondrion'], a: 0, e: 'The Golgi apparatus processes and packages proteins and lipids into vesicles for delivery.', tags: ['Cell Biology', 'Organelles'] },

  // ── Level 2 — The cell membrane & transport ──
  { q: 'The cell membrane is mainly built from a bilayer of which molecule?', opts: ['Phospholipids', 'Cellulose', 'Glucose', 'DNA'], a: 0, e: 'A phospholipid bilayer forms the membrane, with hydrophilic heads outward and hydrophobic tails inward.', tags: ['Cell Biology', 'Membrane'] },
  { q: 'Diffusion is best described as the movement of particles from a region of...', opts: ['High to low concentration', 'Low to high concentration', 'Cold to hot', 'Low to high pressure only'], a: 0, e: 'Diffusion moves particles down their concentration gradient, from high to low, until evenly spread.', tags: ['Cell Biology', 'Transport'] },
  { q: 'Osmosis specifically refers to the diffusion of which substance?', opts: ['Water', 'Oxygen', 'Glucose', 'Sodium ions'], a: 0, e: 'Osmosis is the net movement of water across a selectively permeable membrane down its water potential gradient.', tags: ['Cell Biology', 'Transport'] },
  { q: 'Which type of transport requires energy (ATP) to move substances against their gradient?', opts: ['Active transport', 'Simple diffusion', 'Osmosis', 'Facilitated diffusion'], a: 0, e: 'Active transport uses ATP to pump substances from low to high concentration, against the gradient.', tags: ['Cell Biology', 'Transport'] },
  { q: 'Facilitated diffusion differs from simple diffusion because it...', opts: ['Uses membrane proteins', 'Requires ATP', 'Moves against the gradient', 'Only moves water'], a: 0, e: 'Facilitated diffusion is passive but relies on channel or carrier proteins to move specific molecules.', tags: ['Cell Biology', 'Transport'] },
  { q: 'An animal cell placed in pure water (a hypotonic solution) will tend to...', opts: ['Swell and possibly burst', 'Shrink and shrivel', 'Stay exactly the same', 'Lose all its DNA'], a: 0, e: 'Water enters by osmosis into the more concentrated cell; without a wall the cell may lyse (burst).', tags: ['Cell Biology', 'Transport'] },
  { q: 'By which process does a cell engulf large particles by wrapping its membrane around them?', opts: ['Endocytosis', 'Osmosis', 'Diffusion', 'Transpiration'], a: 0, e: 'Endocytosis brings large materials into the cell by enclosing them in a vesicle formed from the membrane.', tags: ['Cell Biology', 'Transport'] },
  { q: 'The sodium-potassium pump moves 3 Na+ out and 2 K+ in per cycle. This is an example of...', opts: ['Primary active transport', 'Simple diffusion', 'Osmosis', 'Facilitated diffusion'], a: 0, e: 'It directly hydrolyses ATP to pump ions against their gradients, defining primary active transport.', tags: ['Cell Biology', 'Transport'] },

  // ── Level 3 — Biomolecules ──
  { q: 'Which biomolecule is the primary short-term energy source, with the general formula (CH2O)n?', opts: ['Carbohydrates', 'Lipids', 'Proteins', 'Nucleic acids'], a: 0, e: 'Carbohydrates such as glucose are readily broken down to release energy quickly.', tags: ['Cell Biology', 'Biomolecules'] },
  { q: 'What are the monomer (building block) units of proteins?', opts: ['Amino acids', 'Monosaccharides', 'Fatty acids', 'Nucleotides'], a: 0, e: 'Proteins are polymers of amino acids joined by peptide bonds.', tags: ['Cell Biology', 'Biomolecules'] },
  { q: 'Which biomolecule stores the most energy per gram and is a major component of membranes?', opts: ['Lipids', 'Carbohydrates', 'Proteins', 'Nucleic acids'], a: 0, e: 'Lipids (fats) are energy-dense and form the phospholipid bilayer of membranes.', tags: ['Cell Biology', 'Biomolecules'] },
  { q: 'The monomers that make up nucleic acids such as DNA and RNA are called...', opts: ['Nucleotides', 'Amino acids', 'Glucose units', 'Glycerol molecules'], a: 0, e: 'Nucleotides (a sugar, phosphate, and base) link together to form DNA and RNA.', tags: ['Cell Biology', 'Biomolecules'] },
  { q: 'Which type of reaction joins two monomers together while releasing a water molecule?', opts: ['Condensation (dehydration synthesis)', 'Hydrolysis', 'Oxidation', 'Reduction'], a: 0, e: 'Condensation reactions form bonds between monomers, releasing water; hydrolysis does the reverse.', tags: ['Cell Biology', 'Biomolecules'] },
  { q: 'Starch, glycogen, and cellulose are all polymers of which single sugar?', opts: ['Glucose', 'Fructose', 'Sucrose', 'Ribose'], a: 0, e: 'These polysaccharides are all built from glucose monomers, differing in bonding and branching.', tags: ['Cell Biology', 'Biomolecules'] },
  { q: 'Most enzymes are made of which class of biomolecule?', opts: ['Proteins', 'Lipids', 'Carbohydrates', 'Nucleic acids'], a: 0, e: 'Enzymes are typically proteins whose specific 3D shape lets them catalyse reactions.', tags: ['Cell Biology', 'Biomolecules'] },
  { q: 'A protein\'s alpha-helices and beta-pleated sheets make up which level of structure?', opts: ['Secondary structure', 'Primary structure', 'Tertiary structure', 'Quaternary structure'], a: 0, e: 'Secondary structure is local folding (helices and sheets) stabilised by hydrogen bonds along the backbone.', tags: ['Cell Biology', 'Biomolecules'] },

  // ── Level 4 — Cellular respiration & metabolism ──
  { q: 'What is the main molecule cells use to store and transfer usable chemical energy?', opts: ['ATP', 'DNA', 'Glucose', 'Water'], a: 0, e: 'ATP (adenosine triphosphate) releases energy when its terminal phosphate bond is broken.', tags: ['Cell Biology', 'Respiration'] },
  { q: 'Glycolysis, the first stage of respiration, takes place in which part of the cell?', opts: ['Cytoplasm', 'Mitochondrial matrix', 'Nucleus', 'Cell membrane'], a: 0, e: 'Glycolysis occurs in the cytoplasm and does not require oxygen.', tags: ['Cell Biology', 'Respiration'] },
  { q: 'Glycolysis breaks one glucose molecule down into two molecules of...', opts: ['Pyruvate', 'Lactic acid', 'Ethanol', 'Carbon dioxide'], a: 0, e: 'Glycolysis splits 6-carbon glucose into two 3-carbon pyruvate molecules, netting 2 ATP.', tags: ['Cell Biology', 'Respiration'] },
  { q: 'The Krebs cycle (citric acid cycle) occurs in which location?', opts: ['Mitochondrial matrix', 'Cytoplasm', 'Ribosome', 'Nucleus'], a: 0, e: 'The Krebs cycle runs in the mitochondrial matrix, releasing CO2 and reduced coenzymes.', tags: ['Cell Biology', 'Respiration'] },
  { q: 'The overall equation for aerobic respiration uses glucose and oxygen to produce...', opts: ['Carbon dioxide, water, and ATP', 'Glucose and oxygen', 'Only water', 'Proteins and lipids'], a: 0, e: 'Aerobic respiration: glucose + oxygen → carbon dioxide + water + energy (ATP).', tags: ['Cell Biology', 'Respiration'] },
  { q: 'The final stage of aerobic respiration, producing the most ATP, is the...', opts: ['Electron transport chain', 'Glycolysis', 'Krebs cycle', 'Fermentation'], a: 0, e: 'Oxidative phosphorylation via the electron transport chain yields roughly 34 of the ~38 ATP per glucose.', tags: ['Cell Biology', 'Respiration'] },
  { q: 'In the absence of oxygen, human muscle cells carry out fermentation, producing...', opts: ['Lactic acid', 'Ethanol and CO2', 'Pure ATP', 'Oxygen'], a: 0, e: 'Anaerobic respiration in human muscle converts pyruvate to lactic acid, regenerating NAD+ for glycolysis.', tags: ['Cell Biology', 'Respiration'] },
  { q: 'In the electron transport chain, what is the final electron acceptor in aerobic respiration?', opts: ['Oxygen', 'Carbon dioxide', 'Glucose', 'ATP'], a: 0, e: 'Oxygen accepts electrons at the end of the chain, combining with H+ to form water.', tags: ['Cell Biology', 'Respiration'] },

  // ── Level 5 — DNA, genes, transcription & protein synthesis ──
  { q: 'In DNA, adenine (A) always pairs with which base?', opts: ['Thymine', 'Guanine', 'Cytosine', 'Uracil'], a: 0, e: 'Complementary base pairing: A pairs with T, and C pairs with G, via hydrogen bonds.', tags: ['Cell Biology', 'Genetics'] },
  { q: 'What is a gene?', opts: ['A section of DNA coding for a protein', 'A whole chromosome', 'A type of sugar', 'A ribosome'], a: 0, e: 'A gene is a stretch of DNA that carries the code for a particular polypeptide or functional RNA.', tags: ['Cell Biology', 'Genetics'] },
  { q: 'The process of copying a gene\'s DNA into a messenger RNA molecule is called...', opts: ['Transcription', 'Translation', 'Replication', 'Digestion'], a: 0, e: 'Transcription produces mRNA from a DNA template, occurring in the nucleus of eukaryotes.', tags: ['Cell Biology', 'Genetics'] },
  { q: 'During translation, mRNA is decoded into a protein at the...', opts: ['Ribosome', 'Nucleolus', 'Golgi apparatus', 'Lysosome'], a: 0, e: 'Ribosomes read mRNA codons and assemble the matching amino acids into a polypeptide.', tags: ['Cell Biology', 'Genetics'] },
  { q: 'A codon, the unit read during translation, consists of how many bases?', opts: ['Three', 'One', 'Two', 'Four'], a: 0, e: 'Each codon is a triplet of three mRNA bases that specifies one amino acid (or a stop signal).', tags: ['Cell Biology', 'Genetics'] },
  { q: 'Which molecule carries a specific amino acid to the ribosome and reads codons via its anticodon?', opts: ['Transfer RNA (tRNA)', 'Messenger RNA (mRNA)', 'DNA polymerase', 'Ribosomal DNA'], a: 0, e: 'tRNA matches its anticodon to an mRNA codon, delivering the correct amino acid for the growing chain.', tags: ['Cell Biology', 'Genetics'] },
  { q: 'Which base found in RNA replaces thymine, pairing with adenine?', opts: ['Uracil', 'Cytosine', 'Guanine', 'Thymine'], a: 0, e: 'RNA uses uracil (U) in place of thymine, so in RNA adenine pairs with uracil.', tags: ['Cell Biology', 'Genetics'] },
  { q: 'A mutation that changes a single base so that one amino acid is swapped for another is a...', opts: ['Missense (point) mutation', 'Silent mutation', 'Frameshift deletion', 'Chromosomal duplication'], a: 0, e: 'A missense mutation alters one codon so it codes for a different amino acid, possibly changing protein function.', tags: ['Cell Biology', 'Genetics'] },
];
