// Geomorphology roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const geomorphologySeeds: Seed[] = [
  // ── Level 1 — Weathering & Erosion ──
  { q: 'What is weathering?', opts: ['Transport of rock debris by rivers', 'In-situ breakdown of rock at or near the surface', 'Uplift of rock by tectonic forces', 'Deposition of sediment in a basin'], a: 1, e: 'Weathering is the breakdown of rock in place; movement of the debris is erosion and transport.', tags: ['Geomorphology', 'Weathering'] },
  { q: 'Freeze-thaw weathering breaks rock mainly because water:', opts: ['Dissolves the minerals', 'Expands by about 9% when it freezes', 'Heats the rock unevenly', 'Reacts with feldspar'], a: 1, e: 'Water expands roughly 9% on freezing, prying open cracks; repeated cycles shatter the rock (frost shattering).', tags: ['Geomorphology', 'Physical Weathering'] },
  { q: 'Which is an example of chemical weathering?', opts: ['Frost shattering', 'Exfoliation', 'Carbonation of limestone', 'Abrasion by wind'], a: 2, e: 'Carbonation, where weak carbonic acid dissolves calcium carbonate, is a chemical process; the others are physical.', tags: ['Geomorphology', 'Chemical Weathering'] },
  { q: 'Tree roots widening cracks in rock is an example of:', opts: ['Biological weathering', 'Hydrolysis', 'Deflation', 'Oxidation'], a: 0, e: 'Roots growing and wedging into joints is biological (biophysical) weathering.', tags: ['Geomorphology', 'Biological Weathering'] },
  { q: 'Oxidation weathering is most visible as:', opts: ['White salt crusts', 'Reddish-brown iron staining', 'Rounded boulders', 'Polished rock surfaces'], a: 1, e: 'Iron minerals react with oxygen to form iron oxides, giving the rusty red-brown colouration.', tags: ['Geomorphology', 'Chemical Weathering'] },
  { q: 'Chemical weathering generally proceeds fastest in climates that are:', opts: ['Cold and dry', 'Hot and wet', 'Cool and windy', 'Hot and dry'], a: 1, e: 'Warmth and abundant moisture speed chemical reactions, so humid tropical climates weather rock chemically fastest.', tags: ['Geomorphology', 'Chemical Weathering'] },
  { q: 'Exfoliation (onion-skin weathering) is caused mainly by:', opts: ['Salt crystal growth', 'Pressure release and thermal stress near the surface', 'Acid rain', 'Root wedging'], a: 1, e: 'Unloading of overlying rock plus surface heating/cooling causes outer layers to peel off in sheets.', tags: ['Geomorphology', 'Physical Weathering'] },
  { q: 'The difference between weathering and erosion is that erosion involves:', opts: ['Chemical change only', 'Removal and transport of material', 'Formation of new minerals', 'Breakdown without movement'], a: 1, e: 'Erosion entails the detachment and transport of material by an agent (water, ice, wind); weathering does not move it.', tags: ['Geomorphology', 'Erosion'] },

  // ── Level 2 — Fluvial Landforms ──
  { q: 'A river\'s long profile is typically:', opts: ['Straight and flat', 'Concave, steep near the source and gentle near the mouth', 'Convex, gentle at the source', 'Vertical throughout'], a: 1, e: 'The idealised long profile is concave: steepest gradient near the source, flattening toward base level.', tags: ['Geomorphology', 'Fluvial'] },
  { q: 'A V-shaped valley in a river\'s upper course is formed mainly by:', opts: ['Lateral erosion and deposition', 'Vertical erosion plus weathering of the valley sides', 'Glacial scouring', 'Wind abrasion'], a: 1, e: 'Downward (vertical) cutting deepens the channel while weathering and mass movement widen the sides into a V.', tags: ['Geomorphology', 'Fluvial'] },
  { q: 'On a meander, the fastest current and greatest erosion occur on the:', opts: ['Inner bank (slip-off slope)', 'Outer bank (cut bank)', 'River bed only', 'Both banks equally'], a: 1, e: 'Centrifugal flow drives the thalweg against the outer bank, undercutting it to form a river cliff.', tags: ['Geomorphology', 'Fluvial'] },
  { q: 'An oxbow lake forms when:', opts: ['A delta is abandoned', 'A meander neck is cut through, isolating the loop', 'A waterfall retreats', 'A levee is breached'], a: 1, e: 'Erosion narrows the meander neck until the river cuts across it, leaving the abandoned loop as an oxbow lake.', tags: ['Geomorphology', 'Fluvial'] },
  { q: 'A waterfall commonly retreats upstream, leaving behind a:', opts: ['Levee', 'Gorge', 'Delta', 'Floodplain'], a: 1, e: 'Undercutting of soft rock and collapse of the resistant cap causes headward retreat, carving a steep-sided gorge.', tags: ['Geomorphology', 'Fluvial'] },
  { q: 'Natural levees are raised banks formed by:', opts: ['Deposition of coarse sediment during floods', 'Erosion of the channel bed', 'Human embankment building', 'Glacial till'], a: 0, e: 'When a river overtops its banks, velocity drops abruptly and the coarsest load is dropped first, building levees.', tags: ['Geomorphology', 'Fluvial'] },
  { q: 'A braided river channel is most likely where there is:', opts: ['A single deep channel with low load', 'Abundant coarse sediment and variable discharge', 'Solid bedrock and steady flow', 'Tidal influence only'], a: 1, e: 'Heavy bedload and fluctuating discharge cause the flow to split around gravel bars into many shifting channels.', tags: ['Geomorphology', 'Fluvial'] },
  { q: 'A delta forms where a river enters standing water and:', opts: ['Erosion increases sharply', 'Sediment is deposited faster than it is removed', 'The channel deepens', 'Salt weathering dominates'], a: 1, e: 'Loss of velocity and flocculation of clays cause deposition; if it outpaces marine removal, a delta builds out.', tags: ['Geomorphology', 'Fluvial'] },

  // ── Level 3 — Glacial & Periglacial ──
  { q: 'A glacial trough (glaciated valley) has a characteristic cross-section that is:', opts: ['V-shaped', 'U-shaped', 'Flat and featureless', 'Circular'], a: 1, e: 'Glaciers erode valley floors and walls to produce a broad, steep-sided, flat-bottomed U-shaped trough.', tags: ['Geomorphology', 'Glacial'] },
  { q: 'A cirque (corrie) is:', opts: ['A long sinuous ridge of sand', 'An armchair-shaped hollow where a glacier begins', 'A pile of terminal debris', 'A wind-eroded basin'], a: 1, e: 'Cirques are bowl-shaped hollows carved by rotational glacial erosion at the head of a glacier.', tags: ['Geomorphology', 'Glacial'] },
  { q: 'A sharp ridge between two adjacent cirques is called a(n):', opts: ['Arête', 'Drumlin', 'Esker', 'Kame'], a: 0, e: 'Back-to-back cirque erosion narrows the divide into a knife-edged ridge known as an arête.', tags: ['Geomorphology', 'Glacial'] },
  { q: 'Unsorted material deposited directly by ice is called:', opts: ['Loess', 'Till (boulder clay)', 'Alluvium', 'Outwash sand'], a: 1, e: 'Till is unsorted, unstratified debris dropped directly by the glacier; meltwater deposits are sorted outwash.', tags: ['Geomorphology', 'Glacial'] },
  { q: 'A terminal moraine marks the:', opts: ['Centre of a glacier', 'Furthest extent (snout) reached by a glacier', 'Source of the ice', 'Path of a subglacial stream'], a: 1, e: 'Debris bulldozed and dumped at the glacier snout forms a ridge marking its maximum advance.', tags: ['Geomorphology', 'Glacial'] },
  { q: 'A drumlin is a landform that is:', opts: ['A jagged rock spire', 'A smooth elongated hill of till, streamlined by ice flow', 'A meltwater channel', 'A frost-heaved mound'], a: 1, e: 'Drumlins are streamlined till mounds; the steep, blunt end faces up-ice and the tapered end down-ice.', tags: ['Geomorphology', 'Glacial'] },
  { q: 'An esker is a ridge deposited by:', opts: ['A subglacial or englacial meltwater stream', 'Wind', 'Wave action', 'Direct ice bulldozing'], a: 0, e: 'Eskers are sinuous ridges of sorted sand and gravel laid down by meltwater in tunnels beneath the ice.', tags: ['Geomorphology', 'Glacial'] },
  { q: 'In periglacial environments, patterned ground and stone circles are produced mainly by:', opts: ['Wind deflation', 'Frost heave and freeze-thaw sorting', 'River deposition', 'Chemical solution'], a: 1, e: 'Repeated freezing lifts and sorts clasts, arranging stones into polygons, circles and stripes over permafrost.', tags: ['Geomorphology', 'Periglacial'] },

  // ── Level 4 — Coastal & Aeolian ──
  { q: 'Longshore drift transports sediment along a coast because waves:', opts: ['Approach the beach at an angle', 'Always hit the shore head-on', 'Only move sediment offshore', 'Cause no net movement'], a: 0, e: 'Swash pushes material up the beach at the wave angle while backwash returns it straight down, giving net alongshore transport.', tags: ['Geomorphology', 'Coastal'] },
  { q: 'A spit is a landform created by:', opts: ['Deposition of drifted sediment across a bay or estuary', 'Wave erosion of a headland', 'Wind piling sand inland', 'River deposition only'], a: 0, e: 'Longshore drift extends a ridge of sand or shingle out from the coast where the shoreline changes direction.', tags: ['Geomorphology', 'Coastal'] },
  { q: 'The typical erosional sequence at a headland is:', opts: ['Stack, stump, arch, cave', 'Cave, arch, stack, stump', 'Arch, cave, stump, stack', 'Stump, stack, cave, arch'], a: 1, e: 'Waves widen a crack into a cave, then an arch; the arch collapses to a stack, which erodes to a stump.', tags: ['Geomorphology', 'Coastal'] },
  { q: 'A wave-cut platform is the gently sloping rock surface left as:', opts: ['A beach builds seaward', 'A cliff retreats landward through undercutting', 'A dune migrates', 'A delta advances'], a: 1, e: 'Undercutting at the wave-cut notch collapses the cliff; repeated retreat exposes a platform at the cliff base.', tags: ['Geomorphology', 'Coastal'] },
  { q: 'Sand dunes migrate downwind because sand is:', opts: ['Dissolved on the windward side', 'Eroded from the windward slope and deposited on the leeward slope', 'Blown only upward', 'Cemented in place'], a: 1, e: 'Grains creep and saltate up the gentle windward face and avalanche down the steeper slip face, moving the dune downwind.', tags: ['Geomorphology', 'Aeolian'] },
  { q: 'A crescent-shaped dune whose horns point downwind is a:', opts: ['Barchan', 'Seif (linear) dune', 'Star dune', 'Parabolic dune'], a: 0, e: 'Barchans form where sand supply is limited and wind is unidirectional, with the horns extending downwind.', tags: ['Geomorphology', 'Aeolian'] },
  { q: 'Deflation in a desert refers to:', opts: ['Wind removing loose fine particles from the surface', 'Rock breaking by frost', 'Water dissolving salts', 'Sand cementing into rock'], a: 0, e: 'Deflation is the wind\'s removal of loose sand and dust, sometimes leaving hollows or a lag of coarse pebbles (desert pavement).', tags: ['Geomorphology', 'Aeolian'] },
  { q: 'A ventifact is a rock that has been:', opts: ['Rounded by river transport', 'Faceted and polished by wind-blown sand abrasion', 'Split by tree roots', 'Dissolved by acid'], a: 1, e: 'Sand-laden wind abrades exposed stones, cutting flat, polished facets (ventifacts) on the windward faces.', tags: ['Geomorphology', 'Aeolian'] },

  // ── Level 5 — Tectonic & Landscape Evolution ──
  { q: 'An anticline is a fold that is:', opts: ['Downward-arching (trough)', 'Upward-arching (arch), with oldest rocks in the core', 'A vertical fracture', 'A horizontal slip surface'], a: 1, e: 'Anticlines arch upward with the oldest beds in the core; the complementary downfold is a syncline.', tags: ['Geomorphology', 'Tectonic'] },
  { q: 'In a normal fault, the hanging wall moves:', opts: ['Up relative to the footwall', 'Down relative to the footwall', 'Horizontally past the footwall', 'Not at all'], a: 1, e: 'Normal faults result from extension (tension); the hanging wall drops down relative to the footwall.', tags: ['Geomorphology', 'Tectonic'] },
  { q: 'A block of crust dropped down between two parallel normal faults forms a:', opts: ['Horst', 'Graben (rift valley)', 'Nappe', 'Batholith'], a: 1, e: 'A down-thrown block between faults is a graben; the up-standing block between grabens is a horst.', tags: ['Geomorphology', 'Tectonic'] },
  { q: 'Isostatic rebound is the:', opts: ['Sinking of crust under an ice load', 'Slow rising of crust after an ice or erosional load is removed', 'Horizontal drift of plates', 'Sudden slip during an earthquake'], a: 1, e: 'When heavy ice or eroded rock is removed, the buoyant crust rises to restore isostatic equilibrium.', tags: ['Geomorphology', 'Isostasy'] },
  { q: 'A river that maintains its course across a rising fold or structure is described as:', opts: ['Antecedent', 'Dendritic', 'Ephemeral', 'Braided'], a: 0, e: 'An antecedent river predates the uplift and cuts down fast enough to hold its course as the land rises.', tags: ['Geomorphology', 'Landscape Evolution'] },
  { q: 'In Davis\'s cycle of erosion, a low-relief surface worn down near base level is called a:', opts: ['Peneplain', 'Pediment', 'Cuesta', 'Monadnock'], a: 0, e: 'Davis proposed landscapes evolve through youth, maturity and old age, ending in a near-level peneplain.', tags: ['Geomorphology', 'Landscape Evolution'] },
  { q: 'An isolated resistant hill rising above a peneplain is a:', opts: ['Monadnock (inselberg)', 'Graben', 'Drumlin', 'Yardang'], a: 0, e: 'A monadnock (or inselberg) is a residual hill of resistant rock left standing above an otherwise low, worn-down plain.', tags: ['Geomorphology', 'Landscape Evolution'] },
  { q: 'A cuesta is an asymmetric ridge produced by:', opts: ['Erosion of gently dipping strata of differing resistance', 'Faulting only', 'Glacial plucking', 'Wind deposition'], a: 0, e: 'Differential erosion of tilted sedimentary layers leaves a cuesta with a steep scarp slope and a gentle dip slope.', tags: ['Geomorphology', 'Landscape Evolution'] },
];
