// Oceanography roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const oceanographySeeds: Seed[] = [
  // ── Level 1 — Ocean Basins & Seafloor ──
  { q: 'Which is the largest and deepest ocean basin on Earth?', opts: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], a: 2, e: 'The Pacific Ocean is the largest and deepest ocean, covering about a third of Earth\'s surface.', tags: ['Oceanography', 'Ocean Basins'] },
  { q: 'The deepest known point in the ocean lies in which feature?', opts: ['Mariana Trench', 'Mid-Atlantic Ridge', 'Puerto Rico Trench', 'Java Trench'], a: 0, e: 'The Challenger Deep in the Mariana Trench (~11,000 m) is the deepest known point in the ocean.', tags: ['Oceanography', 'Ocean Basins'] },
  { q: 'The gently sloping submerged edge of a continent is called the continental what?', opts: ['Rise', 'Shelf', 'Slope', 'Trench'], a: 1, e: 'The continental shelf is the shallow, gently sloping submerged margin of a continent.', tags: ['Oceanography', 'Ocean Basins'] },
  { q: 'Mid-ocean ridges are primarily sites of what tectonic activity?', opts: ['Subduction', 'Seafloor spreading', 'Transform sliding', 'Continental collision'], a: 1, e: 'Mid-ocean ridges are divergent boundaries where new oceanic crust forms by seafloor spreading.', tags: ['Oceanography', 'Ocean Basins'] },
  { q: 'The flat, deep expanse covering much of the ocean floor is the abyssal what?', opts: ['Plain', 'Ridge', 'Canyon', 'Seamount'], a: 0, e: 'Abyssal plains are the flat, sediment-covered regions of the deep ocean floor.', tags: ['Oceanography', 'Ocean Basins'] },
  { q: 'An underwater mountain that does not reach the surface is called a what?', opts: ['Atoll', 'Guyot', 'Seamount', 'Shoal'], a: 2, e: 'A seamount is an isolated underwater mountain, usually of volcanic origin, that does not breach the surface.', tags: ['Oceanography', 'Ocean Basins'] },
  { q: 'Deep ocean trenches form mainly at which plate boundary type?', opts: ['Divergent', 'Convergent (subduction)', 'Transform', 'Hotspot'], a: 1, e: 'Trenches form where one plate subducts beneath another at convergent boundaries.', tags: ['Oceanography', 'Ocean Basins'] },
  { q: 'Roughly what fraction of Earth\'s surface is covered by ocean?', opts: ['About 50%', 'About 71%', 'About 30%', 'About 90%'], a: 1, e: 'Oceans cover roughly 71% of Earth\'s surface.', tags: ['Oceanography', 'Ocean Basins'] },

  // ── Level 2 — Seawater Properties ──
  { q: 'The average salinity of seawater is closest to which value?', opts: ['3.5 ppt', '35 ppt', '350 ppt', '0.35 ppt'], a: 1, e: 'Average ocean salinity is about 35 parts per thousand (35 g of salt per kg of seawater).', tags: ['Oceanography', 'Seawater Properties'] },
  { q: 'Which dissolved ion is most abundant in seawater?', opts: ['Chloride', 'Sodium', 'Sulfate', 'Calcium'], a: 0, e: 'Chloride is the most abundant ion, followed by sodium; together they make up common salt.', tags: ['Oceanography', 'Seawater Properties'] },
  { q: 'How does seawater density generally change as salinity increases?', opts: ['Decreases', 'Increases', 'Unchanged', 'Doubles'], a: 1, e: 'Higher salinity means more dissolved mass per volume, increasing density.', tags: ['Oceanography', 'Seawater Properties'] },
  { q: 'The thermocline is a zone of rapid change in what property with depth?', opts: ['Salinity', 'Temperature', 'Pressure', 'Oxygen'], a: 1, e: 'The thermocline is the layer where temperature drops rapidly with increasing depth.', tags: ['Oceanography', 'Seawater Properties'] },
  { q: 'How does seawater density generally change as temperature increases?', opts: ['Increases', 'Decreases', 'Unchanged', 'Becomes zero'], a: 1, e: 'Warmer water is less dense, so density decreases as temperature rises (above freezing).', tags: ['Oceanography', 'Seawater Properties'] },
  { q: 'The layer of rapid density change with depth is called the what?', opts: ['Halocline', 'Pycnocline', 'Thermocline', 'Mixed layer'], a: 1, e: 'The pycnocline is the zone of rapid density change that separates surface and deep water.', tags: ['Oceanography', 'Seawater Properties'] },
  { q: 'Compared with pure water, seawater\'s freezing point is what?', opts: ['Higher', 'Lower', 'Identical', 'Above 0 C'], a: 1, e: 'Dissolved salts depress the freezing point, so seawater freezes below 0 C (around -1.9 C).', tags: ['Oceanography', 'Seawater Properties'] },
  { q: 'A halocline is a layer of rapid change in what property?', opts: ['Salinity', 'Temperature', 'Density', 'Turbidity'], a: 0, e: 'A halocline is a vertical zone in which salinity changes rapidly with depth.', tags: ['Oceanography', 'Seawater Properties'] },

  // ── Level 3 — Currents & Circulation ──
  { q: 'The Coriolis effect deflects moving water to the right in which hemisphere?', opts: ['Northern', 'Southern', 'Both equally', 'Neither'], a: 0, e: 'In the Northern Hemisphere the Coriolis effect deflects moving fluids to the right.', tags: ['Oceanography', 'Ocean Circulation'] },
  { q: 'The warm current that moderates Western Europe\'s climate is the what?', opts: ['Gulf Stream', 'Humboldt Current', 'California Current', 'Benguela Current'], a: 0, e: 'The Gulf Stream carries warm water northeast across the Atlantic, warming Western Europe.', tags: ['Oceanography', 'Ocean Circulation'] },
  { q: 'Large surface current systems that circulate around ocean basins are called what?', opts: ['Eddies', 'Gyres', 'Upwellings', 'Tsunamis'], a: 1, e: 'Gyres are large, rotating systems of surface currents driven by winds and the Coriolis effect.', tags: ['Oceanography', 'Ocean Circulation'] },
  { q: 'Surface ocean currents are driven primarily by what?', opts: ['Tides', 'Prevailing winds', 'Earthquakes', 'Salinity alone'], a: 1, e: 'Surface currents are driven mainly by prevailing winds, then shaped by Coriolis and continents.', tags: ['Oceanography', 'Ocean Circulation'] },
  { q: 'Thermohaline circulation is driven by differences in what two properties?', opts: ['Wind and tides', 'Temperature and salinity', 'Pressure and light', 'Oxygen and pH'], a: 1, e: 'Thermohaline circulation is driven by density differences set by temperature and salinity.', tags: ['Oceanography', 'Ocean Circulation'] },
  { q: 'Gyres rotate in which direction in the Northern Hemisphere?', opts: ['Clockwise', 'Counterclockwise', 'North to south only', 'Randomly'], a: 0, e: 'Northern Hemisphere subtropical gyres rotate clockwise due to the Coriolis effect.', tags: ['Oceanography', 'Ocean Circulation'] },
  { q: 'Deep-water formation in the thermohaline system occurs mainly where surface water is what?', opts: ['Warm and fresh', 'Cold and salty', 'Warm and salty', 'Cold and fresh'], a: 1, e: 'Cold, salty (dense) surface water sinks in polar regions, driving the deep global conveyor.', tags: ['Oceanography', 'Ocean Circulation'] },
  { q: 'Net wind-driven transport of the surface water layer, at right angles to the wind, is called what?', opts: ['Geostrophic flow', 'Ekman transport', 'Langmuir circulation', 'Stokes drift'], a: 1, e: 'Ekman transport is the net movement of the wind-driven surface layer about 90 degrees to the wind direction.', tags: ['Oceanography', 'Ocean Circulation'] },

  // ── Level 4 — Waves, Tides & Coasts ──
  { q: 'Most ocean surface waves are generated by what?', opts: ['Wind', 'The Moon', 'Earthquakes', 'Currents'], a: 0, e: 'Ordinary surface waves are generated by wind transferring energy to the sea surface.', tags: ['Oceanography', 'Waves and Tides'] },
  { q: 'Ocean tides are caused mainly by the gravitational pull of what?', opts: ['The Sun only', 'The Moon and Sun', 'Ocean winds', 'Earth\'s rotation alone'], a: 1, e: 'Tides result from the gravitational pull of the Moon and Sun on the ocean, mostly the Moon.', tags: ['Oceanography', 'Waves and Tides'] },
  { q: 'The largest tidal range, at new and full moon, is called a what tide?', opts: ['Neap', 'Spring', 'Ebb', 'Slack'], a: 1, e: 'Spring tides occur when Sun, Moon, and Earth align, producing the largest tidal ranges.', tags: ['Oceanography', 'Waves and Tides'] },
  { q: 'The smallest tidal range, at the quarter moons, is called a what tide?', opts: ['Spring', 'Neap', 'Flood', 'King'], a: 1, e: 'Neap tides occur at the quarter moons when solar and lunar pulls partly cancel, giving small ranges.', tags: ['Oceanography', 'Waves and Tides'] },
  { q: 'The movement of sediment along a shoreline by angled waves is called what?', opts: ['Longshore drift', 'Upwelling', 'Saltation', 'Deposition creep'], a: 0, e: 'Longshore drift transports sediment along a coast as waves approach the shore at an angle.', tags: ['Oceanography', 'Waves and Tides'] },
  { q: 'A tsunami is most commonly triggered by what?', opts: ['Strong winds', 'Undersea earthquakes', 'Spring tides', 'Ocean currents'], a: 1, e: 'Tsunamis are usually generated by undersea earthquakes that displace large volumes of water.', tags: ['Oceanography', 'Waves and Tides'] },
  { q: 'A wave "breaks" when it reaches shallow water because its base does what?', opts: ['Speeds up', 'Slows from friction', 'Freezes', 'Reverses'], a: 1, e: 'In shallow water the wave base slows from seabed friction while the crest advances, so the wave breaks.', tags: ['Oceanography', 'Waves and Tides'] },
  { q: 'In deep water, wave speed depends mainly on what property?', opts: ['Wave height', 'Wavelength (period)', 'Water salinity', 'Water color'], a: 1, e: 'Deep-water wave speed increases with wavelength/period; longer waves travel faster.', tags: ['Oceanography', 'Waves and Tides'] },

  // ── Level 5 — Marine Ecosystems & Ocean–Climate ──
  { q: 'Coastal upwelling brings deep water to the surface that is rich in what?', opts: ['Nutrients', 'Salt only', 'Oxygen only', 'Sediment'], a: 0, e: 'Upwelling raises cold, nutrient-rich deep water, fueling high biological productivity.', tags: ['Oceanography', 'Ocean and Climate'] },
  { q: 'During El Niño, sea surface temperatures in the eastern tropical Pacific tend to do what?', opts: ['Warm', 'Cool', 'Stay constant', 'Freeze'], a: 0, e: 'El Niño features anomalously warm surface waters in the central and eastern tropical Pacific.', tags: ['Oceanography', 'Ocean and Climate'] },
  { q: 'El Niño typically causes coastal upwelling off Peru to do what?', opts: ['Strengthen', 'Weaken', 'Reverse direction', 'Freeze'], a: 1, e: 'El Niño suppresses upwelling off South America, cutting nutrient supply and fisheries.', tags: ['Oceanography', 'Ocean and Climate'] },
  { q: 'The cool phase of ENSO, opposite to El Niño, is called what?', opts: ['La Niña', 'The Blob', 'Monsoon', 'Dipole'], a: 0, e: 'La Niña is the cool ENSO phase with stronger trade winds and cooler eastern Pacific waters.', tags: ['Oceanography', 'Ocean and Climate'] },
  { q: 'Roughly what share of the excess heat from global warming has the ocean absorbed?', opts: ['About 10%', 'Over 90%', 'About 50%', 'Almost none'], a: 1, e: 'The ocean has absorbed over 90% of the excess heat trapped by greenhouse gases.', tags: ['Oceanography', 'Ocean and Climate'] },
  { q: 'Ocean acidification results from seawater absorbing increasing amounts of what gas?', opts: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Methane'], a: 1, e: 'Dissolved CO2 forms carbonic acid, lowering ocean pH in a process called ocean acidification.', tags: ['Oceanography', 'Ocean and Climate'] },
  { q: 'Coral bleaching occurs when corals expel the symbiotic algae called what?', opts: ['Diatoms', 'Zooxanthellae', 'Plankton blooms', 'Cyanophytes'], a: 1, e: 'Heat-stressed corals expel zooxanthellae, losing color and their main energy source.', tags: ['Oceanography', 'Ocean and Climate'] },
  { q: 'The "biological pump" refers to the ocean process that transports what to the deep sea?', opts: ['Heat', 'Carbon', 'Salt', 'Plastic'], a: 1, e: 'The biological pump moves organic carbon from surface waters to the deep ocean via sinking material.', tags: ['Oceanography', 'Ocean and Climate'] },
];
