import type { QuestionTranslation } from './quiz-data';

export const intellectualHistoryTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Antická filozofie ──
  'rm-intelhist-1': { introduction: 'Zamysli se nad metodou, ne nad texty.', question: 'Sókratés je nejlépe znám pro styl zkoumání založený na čem?', options: ['Vytrvalé zpochybňování předpokladů', 'Psaní rozsáhlých traktátů', 'Matematický důkaz', 'Náboženské zjevení'], explanation: 'Sókratovská metoda (elenchos) prověřuje přesvědčení systematickým vyptáváním, aby odhalila rozpory.' },
  'rm-intelhist-2': { introduction: 'Co je podle Platóna skutečnější než hmotný svět?', question: 'Platónova teorie idejí tvrdí, že nejzazší skutečnost tvoří co?', options: ['Atomy v prázdnotě', 'Věčné, neměnné ideje', 'Smyslové vjemy', 'Božská přikázání'], explanation: 'Pro Platóna jsou dokonalé a věčné ideje skutečnější než jejich nedokonalé fyzické kopie.' },
  'rm-intelhist-3': { introduction: 'Hledej Platónovo dílo o ideálním státě.', question: 'Ve kterém dialogu Platón popisuje ideální stát řízený filozofy-vládci?', options: ['Ílias', 'Etika Níkomachova', 'Ústava', 'Hovory k sobě'], explanation: 'Platónova Ústava načrtává spravedlivou obec spravovanou vládci milujícími moudrost.' },
  'rm-intelhist-4': { introduction: 'Řecký pojem pro cíl dobrého života.', question: 'Aristotelův pojem eudaimonia se nejlépe překládá jako co?', options: ['Slast', 'Lidské vzkvétání', 'Bohatství', 'Sláva'], explanation: 'Eudaimonia je život vzkvétání dosažený ctnostnou činností, pro Aristotela cíl etiky.' },
  'rm-intelhist-5': { introduction: 'Mezi jakými dvěma póly leží ctnost?', question: 'Aristotelés zastával názor, že mravní ctnost obvykle spočívá kde?', options: ['V naprostém sebezáporu', 'Ve středu mezi dvěma krajnostmi', 'V následování slasti', 'V přísné poslušnosti'], explanation: 'Jeho nauka o středu klade ctnost mezi neřesti nadbytku a nedostatku, např. odvahu mezi zbrklostí a zbabělostí.' },
  'rm-intelhist-6': { introduction: 'Ústřední konfuciánská ctnost vztahu k druhým.', question: 'Konfuciánská ctnost žen (ren) se nejlépe popisuje jako co?', options: ['Laskavost neboli lidskost', 'Vojenská síla', 'Rituální čistota', 'Hmotné bohatství'], explanation: 'Žen (ren), ústřední pro konfuciánskou etiku, označuje lidskost a laskavost vůči druhým.' },
  'rm-intelhist-7': { introduction: 'Klíčem je nenásilné, přirozené jednání.', question: 'Taoismus, spjatý s knihou Tao-te-ťing, zdůrazňuje kterou myšlenku?', options: ['Přísné právní kodexy', 'Soulad s Tao a wu-wej', 'Dobývání přírody', 'Přísnou kastovní povinnost'], explanation: 'Taoismus vybízí k životu v souladu s Tao a wu-wej, nenásilnému jednání, které si věci nevynucuje.' },
  'rm-intelhist-8': { introduction: 'Čím začíná první z buddhistických pravd?', question: 'Buddhistické Čtyři vznešené pravdy začínají kterým poznáním?', options: ['Svět je iluze', 'Existence zahrnuje utrpení (dukkha)', 'Duše je věčná', 'Touhu je třeba maximalizovat'], explanation: 'První vznešená pravda určuje dukkha (utrpení); ostatní sledují jeho příčinu a jeho zánik skrze Osmidílnou stezku.' },
  // ── Úroveň 2 — Náboženské a středověké myšlení ──
  'rm-intelhist-9': { introduction: 'Šlo o vztah víry a rozumu.', question: 'Středověká scholastika se snažila především o co?', options: ['Odmítnout veškeré antické vědění', 'Uvést do souladu víru a rozum', 'Zrušit univerzity', 'Nahradit teologii vědou'], explanation: 'Scholastici používali přísnou logiku, často aristotelskou, aby sladili křesťanskou nauku s rozumovým argumentem.' },
  'rm-intelhist-10': { introduction: 'Kterého antického filozofa spojil s teologií?', question: 'Tomáš Akvinský je proslulý spojením křesťanské teologie s filozofií koho?', options: ['Epikúra', 'Aristotela', 'Démokrita', 'Pýthagora'], explanation: 'V Teologické sumě Akvinský spojil aristotelskou filozofii s katolickou teologií.' },
  'rm-intelhist-11': { introduction: 'Co těmito pěti cestami dokazoval?', question: 'Slavných Pět cest Akvinského jsou argumenty pro co?', options: ['Nesmrtelnost duše', 'Existenci Boha', 'Hodnotu chudoby', 'Uspořádání církve'], explanation: 'Pět cest nabízí rozumové důkazy Boží existence, včetně argumentů z pohybu a z příčinnosti.' },
  'rm-intelhist-12': { introduction: 'Jaký literární žánr toto dílo předznamenalo?', question: 'Vyznání Augustina z Hippa jsou pozoruhodná jako raný příklad čeho?', options: ['Vědeckého traktátu', 'Duchovní autobiografie', 'Právního kodexu', 'Epické básně'], explanation: 'Augustinova Vyznání jsou průkopnická introspektivní autobiografie spojující křesťanskou teologii s novoplatonismem.' },
  'rm-intelhist-13': { introduction: 'Argument vycházející ze samotného pojmu Boha.', question: 'Anselm z Canterbury je znám kterým argumentem pro Boha?', options: ['Ontologickým argumentem', 'Argumentem sázky', 'Evolučním argumentem', 'Historickým argumentem'], explanation: 'Anselmův ontologický argument vychází z pojmu Boha jako toho, nad co nelze pomyslet nic většího.' },
  'rm-intelhist-14': { introduction: 'Čím byl pro pozdější myšlení nejvlivnější?', question: 'Islámský filozof Averroes (Ibn Rušd) byl obzvláště vlivný jako co?', options: ['Komentátor Aristotela', 'Kritik veškeré filozofie', 'Básník', 'Dobyvatel'], explanation: 'Averroovy podrobné komentáře k Aristotelovi hluboce ovlivnily pozdější židovskou a křesťanskou scholastiku.' },
  'rm-intelhist-15': { introduction: 'Dílo namířené proti tvrzením filozofů.', question: 'Al-Ghazálího Nesoudržnost filozofů udělala co?', options: ['Obhájila řeckou metafyziku', 'Kritizovala tvrzení některých filozofů', 'Založila algebru', 'Odmítla Korán'], explanation: 'Al-Ghazálí zpochybnil nutnostní metafyziku filozofů jako Avicenna a obhajoval teologické postoje.' },
  'rm-intelhist-16': { introduction: 'S jakou filozofií chtěl sladit judaismus?', question: 'Maimonidův Průvodce zbloudilých se snažil uvést judaismus do souladu s čím?', options: ['Římským právem', 'Aristotelskou filozofií', 'Egyptským náboženstvím', 'Perskou astrologií'], explanation: 'Židovský filozof Maimonides usiloval o sladění Tóry s aristotelským rozumem.' },
  // ── Úroveň 3 — Renesanční humanismus a osvícenství ──
  'rm-intelhist-17': { introduction: 'K jakým textům se humanisté vraceli?', question: 'Renesanční humanismus se soustředil na obnovené studium čeho?', options: ['Klasických řeckých a římských textů', 'Alchymie', 'Feudálního práva', 'Klášterního rituálu'], explanation: 'Humanisté oživili studia humanitatis, studium klasické literatury, rétoriky a morální filozofie.' },
  'rm-intelhist-18': { introduction: 'Co je onou nezpochybnitelnou jistotou?', question: 'Descartův výrok „Cogito, ergo sum“ vyjadřuje kterou myšlenku?', options: ['Bůh zaručuje veškerou pravdu', 'Jistotu vlastního myslícího já', 'Poznání pochází jen ze smyslů', 'Duše neexistuje'], explanation: '„Myslím, tedy jsem“ je Descartův nezpochybnitelný základ: pochybování dokazuje, že existuje myslící já.' },
  'rm-intelhist-19': { introduction: 'Latinský výraz znamená „nepopsaná deska“.', question: 'Lockova představa mysli jako tabula rasa znamená co?', options: ['Mysl obsahuje vrozené ideje', 'Mysl začíná jako nepopsaná deska', 'Mysl je nepoznatelná', 'Mysl je božská'], explanation: 'Locke tvrdil, že mysl začíná prázdná a poznání se buduje ze zkušenosti, což je základní kámen empirismu.' },
  'rm-intelhist-20': { introduction: 'Odkud plyne legitimita vlády?', question: 'Locke tvrdil, že vlády odvozují svou legitimní moc z čeho?', options: ['Božského práva králů', 'Souhlasu ovládaných', 'Vojenského dobytí', 'Zděděné šlechty'], explanation: 'Locke zastával názor, že legitimní vláda spočívá na souhlasu a existuje, aby chránila přirozená práva na život, svobodu a majetek.' },
  'rm-intelhist-21': { introduction: 'Kolektivní vůle lidu jako základ svrchovanosti.', question: 'Rousseauova Společenská smlouva zavedla který klíčový pojem?', options: ['Obecnou vůli', 'Neviditelnou ruku', 'Kategorický imperativ', 'Dialektiku'], explanation: 'Rousseauova obecná vůle představuje společný zájem lidu jako základ legitimní svrchovanosti.' },
  'rm-intelhist-22': { introduction: 'Test univerzálnosti mravního pravidla.', question: 'Kantův kategorický imperativ nařizuje jednat jak?', options: ['Tak, aby se maximalizovala osobní slast', 'Jen podle zásad, které bys mohl chtít jako všeobecný zákon', 'Podle tradice', 'Jak rozhodne většina'], explanation: 'Kantův test se ptá, zda by se zásada tvého jednání mohla důsledně stát všeobecným zákonem závazným pro všechny.' },
  'rm-intelhist-23': { introduction: 'Latinské heslo o odvaze používat rozum.', question: 'Kant shrnul osvícenství kterým heslem?', options: ['Poznej sám sebe', 'Sapere aude (odvaž se vědět)', 'Myslím, tedy jsem', 'Účel světí prostředky'], explanation: 'V eseji „Co je osvícenství?“ Kant vybízel lidi, aby používali vlastní rozum: sapere aude, odvaž se vědět.' },
  'rm-intelhist-24': { introduction: 'Za jaké rozdělení moci se přimlouval?', question: 'Montesquieuův Duch zákonů je nejznámější tím, že prosazuje co?', options: ['Absolutní monarchii', 'Rozdělení státní moci', 'Zrušení majetku', 'Teokracii'], explanation: 'Montesquieu tvrdil, že rozdělení moci mezi zákonodárnou, výkonnou a soudní složku chrání před tyranií.' },
  // ── Úroveň 4 — Moderní politické ideologie ──
  'rm-intelhist-25': { introduction: 'Co je pro tuto ideologii nejdůležitější?', question: 'Klasický liberalismus zdůrazňuje především co?', options: ['Individuální svobodu a omezenou vládu', 'Vládu dědičných elit', 'Kolektivní vlastnictví veškerého majetku', 'Stát jedné strany'], explanation: 'Liberalismus klade důraz na individuální práva, vládu práva a omezení státní moci.' },
  'rm-intelhist-26': { introduction: 'Zakládající text jaké tradice?', question: 'Burkovy Úvahy o revoluci ve Francii jsou zakládajícím textem čeho?', options: ['Socialismu', 'Moderního konzervatismu', 'Anarchismu', 'Fašismu'], explanation: 'Burke hájil tradici, postupnou reformu a zděděné instituce proti radikální, abstraktní revoluci.' },
  'rm-intelhist-27': { introduction: 'Ústřední je otázka vlastnictví výroby.', question: 'Socialismus je ústředně definován prosazováním čeho?', options: ['Neregulovaných volných trhů', 'Společenského vlastnictví výrobních prostředků', 'Dědičné monarchie', 'Minimálního zdanění'], explanation: 'Socialismus volá po kolektivním či veřejném vlastnictví a kontrole výroby s cílem zmenšit ekonomickou nerovnost.' },
  'rm-intelhist-28': { introduction: 'Co je základní jednotkou politické loajality?', question: 'Nacionalismus jako politická ideologie tvrdí, že co?', options: ['Státy by se měly sloučit v jednu říši', 'Národ je hlavním základem politické loajality', 'Náboženství by mělo řídit všechny státy', 'Majetek by měl být zrušen'], explanation: 'Nacionalismus činí z národa ústřední jednotku identity a legitimity a často vyžaduje sebeurčení.' },
  'rm-intelhist-29': { introduction: 'Jak sledování vlastního zájmu prospívá celku?', question: 'Co popisuje „neviditelná ruka“ Adama Smitha?', options: ['Státní řízení ekonomiky', 'Jak může směna motivovaná vlastním zájmem prospět společnosti', 'Božské řízení dějin', 'Politiku centrální banky'], explanation: 'V Bohatství národů Smith tvrdil, že jednotlivci sledující vlastní zájem mohou nezáměrně podporovat obecné dobro.' },
  'rm-intelhist-30': { introduction: 'Kdy je oprávněné omezit svobodu jednotlivce?', question: 'Millův princip újmy ve spisu O svobodě říká co?', options: ['Stát smí regulovat veškeré chování', 'Moc nad jednotlivcem je ospravedlnitelná jen k zabránění újmy druhým', 'Svoboda platí jen pro bohaté', 'Projev by měl být cenzurován kvůli pohoršení'], explanation: 'Mill zastával názor, že jednotlivci mají být svobodní jednat, pokud jejich jednání neškodí druhým.' },
  'rm-intelhist-31': { introduction: 'Proti čemu se tato ideologie staví?', question: 'Anarchismus je definován svým odporem k čemu?', options: ['Veškerému obchodu', 'Donucovací státní moci', 'Lidské spolupráci', 'Písmu'], explanation: 'Anarchističtí myslitelé jako Proudhon a Bakunin odmítají stát a upřednostňují dobrovolné, samosprávné sdružování.' },
  'rm-intelhist-32': { introduction: 'Podle jakého měřítka posuzuje činy?', question: 'Utilitarismus Jeremyho Benthama posuzuje činy podle jakého měřítka?', options: ['Jejich souladu s tradicí', 'Největšího štěstí pro největší počet lidí', 'Božího příkazu', 'Národní slávy'], explanation: 'Benthamův princip užitku hodnotí činy podle toho, kolik čistého potěšení či štěstí vyprodukují.' },
  // ── Úroveň 5 — Moderní myšlení ──
  'rm-intelhist-33': { introduction: 'Co podle Marxe žene dějiny především?', question: 'Marxova teorie historického materialismu tvrdí, že dějiny žene především co?', options: ['Velké osobnosti', 'Materiální a ekonomické podmínky a třídní boj', 'Boží prozřetelnost', 'Náhoda'], explanation: 'Pro Marxe žene historický vývoj změna materiálních výrobních prostředků a z ní plynoucí třídní konflikt.' },
  'rm-intelhist-34': { introduction: 'Odcizení se týká vztahu dělníka k jeho práci.', question: 'Co v marxistické teorii označuje „odcizení“?', options: ['Odloučení dělníků od jejich práce a jejích produktů', 'Migraci mezi zeměmi', 'Ztrátu náboženské víry', 'Politické vyhnanství'], explanation: 'Marx tvrdil, že za kapitalismu se dělníci odcizují své práci, jejím produktům i vlastnímu lidskému potenciálu.' },
  'rm-intelhist-35': { introduction: 'Co tímto výrokem Nietzsche diagnostikoval?', question: 'Co měl Nietzscheho výrok „Bůh je mrtev“ naznačit?', options: ['Důkaz, že Bůh nikdy neexistoval', 'Zhroucení tradičních náboženských základů hodnot', 'Výzvu ke stavbě kostelů', 'Vítězství vědy nad uměním'], explanation: 'Nietzsche diagnostikoval slábnoucí autoritu křesťanské morálky v moderní kultuře a krizi smyslu, kterou to vyvolalo.' },
  'rm-intelhist-36': { introduction: 'Kdo si tvoří vlastní hodnoty?', question: 'Nietzscheho pojem Übermensch (nadčlověk) označuje co?', options: ['Vládce z božího práva', 'Jedince, který si tvoří vlastní hodnoty', 'Dokonale racionálního vědce', 'Poslušného občana'], explanation: 'Übermensch (nadčlověk) přitakává životu a tvoří nové hodnoty, místo aby je dědil z tradice.' },
  'rm-intelhist-37': { introduction: 'Nejprve jsme, teprve pak se definujeme.', question: 'Sartrovo existencialistické heslo „existence předchází esenci“ znamená co?', options: ['Lidé se rodí s pevnou přirozeností', 'Lidé nejprve existují a teprve pak se definují svými volbami', 'Esence je skutečnější než existence', 'Bůh určuje smysl každého člověka'], explanation: 'Pro Sartra neexistuje předem daná lidská esence; jsme radikálně svobodní a definujeme se svými činy.' },
  'rm-intelhist-38': { introduction: 'Kladl důraz na jednotlivce, ne na kolektiv.', question: 'Kierkegaard, často nazývaný otcem existencialismu, zdůrazňoval co?', options: ['Kolektivní rozum', 'Individuální subjektivní volbu a víru', 'Vědeckou objektivitu', 'Dějinnou nevyhnutelnost'], explanation: 'Kierkegaard zdůrazňoval vášnivé, subjektivní odhodlání jednotlivce, včetně „skoku víry“.' },
  'rm-intelhist-39': { introduction: 'Postoj vůči velkým vysvětlujícím příběhům.', question: 'Lyotard slavně definoval postmodernismus jako co?', options: ['Víru v pokrok', 'Nedůvěru vůči metanarativům', 'Návrat k tradici', 'Důvěru ve všeobecný rozum'], explanation: 'Lyotard charakterizoval postmoderní stav jako skepsi vůči velkým, vše vysvětlujícím příběhům, jako je pokrok či emancipace.' },
  'rm-intelhist-40': { introduction: 'Které dva pojmy podle něj splývají?', question: 'Dílo Michela Foucaulta je obzvláště známé analýzou kterého vztahu?', options: ['Nabídky a poptávky', 'Moci a vědění', 'Víry a rozumu', 'Vrozeného a získaného'], explanation: 'Foucault tvrdil, že moc a vědění jsou provázané a utvářejí diskurz, instituce a to, co se pokládá za pravdu.' },
};
