// Biogeography roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const biogeographySeeds: Seed[] = [
  // ── Level 1 — Biomes ──
  { q: 'Which biome is characterized by permafrost, low temperatures, and no trees?', opts: ['Tundra', 'Savanna', 'Taiga', 'Chaparral'], a: 0, e: 'The tundra has frozen subsoil (permafrost) and treeless vegetation of mosses, lichens, and low shrubs.', tags: ['Biogeography', 'Biomes'] },
  { q: 'Tropical rainforests are found mainly in which climatic zone?', opts: ['Polar', 'Equatorial', 'Mediterranean', 'Continental interior'], a: 1, e: 'Tropical rainforests occur near the equator, where high rainfall and warm temperatures persist year-round.', tags: ['Biogeography', 'Biomes'] },
  { q: 'The taiga, or boreal forest, is dominated by which vegetation?', opts: ['Broadleaf deciduous trees', 'Coniferous evergreen trees', 'Grasses', 'Cacti'], a: 1, e: 'The taiga is a vast belt of cold-tolerant conifers such as spruce, fir, and pine across high northern latitudes.', tags: ['Biogeography', 'Biomes'] },
  { q: 'Deserts are primarily defined by which characteristic?', opts: ['High temperatures', 'Very low precipitation', 'Dense vegetation', 'Frequent flooding'], a: 1, e: 'Deserts are defined by aridity (typically under 250 mm rainfall per year), not by heat; cold deserts also exist.', tags: ['Biogeography', 'Biomes'] },
  { q: 'Which biome is dominated by grasses with scattered trees and marked wet and dry seasons?', opts: ['Savanna', 'Tundra', 'Rainforest', 'Taiga'], a: 0, e: 'Tropical savannas, such as those in Africa, feature grassland with scattered trees and strong seasonal rainfall.', tags: ['Biogeography', 'Biomes'] },
  { q: 'The Mediterranean biome (chaparral) is best known for which climate pattern?', opts: ['Hot wet summers, cold dry winters', 'Hot dry summers, mild wet winters', 'Uniform rainfall year-round', 'Permanent snow cover'], a: 1, e: 'Mediterranean climates have hot, dry summers and mild, wet winters, supporting drought-adapted shrubland.', tags: ['Biogeography', 'Biomes'] },
  { q: 'Which factor most strongly controls the global distribution of biomes?', opts: ['Soil colour', 'Climate (temperature and precipitation)', 'Human population', 'Ocean salinity'], a: 1, e: 'Temperature and precipitation are the primary controls that determine which biome develops in a region.', tags: ['Biogeography', 'Biomes'] },
  { q: 'Moving from the equator toward the poles, which sequence of biomes is typical?', opts: ['Tundra, taiga, rainforest', 'Rainforest, desert/grassland, taiga, tundra', 'Desert, tundra, rainforest', 'Taiga, rainforest, savanna'], a: 1, e: 'Latitudinal zonation runs from tropical forests through mid-latitude deserts and grasslands to boreal forest and tundra.', tags: ['Biogeography', 'Biomes'] },

  // ── Level 2 — Ecosystems & Energy Flow ──
  { q: 'In a food chain, organisms that produce their own food are called', opts: ['Consumers', 'Producers', 'Decomposers', 'Predators'], a: 1, e: 'Producers (autotrophs) such as green plants make their own food via photosynthesis, forming the base of food chains.', tags: ['Biogeography', 'Ecosystems'] },
  { q: 'A trophic level describes an organism\'s position based on', opts: ['Its size', 'Its feeding relationships', 'Its habitat', 'Its lifespan'], a: 1, e: 'A trophic level is a step in a food chain defined by how an organism obtains energy relative to producers.', tags: ['Biogeography', 'Ecosystems'] },
  { q: 'Roughly what percentage of energy is transferred between successive trophic levels?', opts: ['About 10%', 'About 50%', 'About 90%', 'About 100%'], a: 0, e: 'On average only about 10% of energy passes to the next trophic level; the rest is lost as heat and in metabolism.', tags: ['Biogeography', 'Ecosystems'] },
  { q: 'Which organisms break down dead matter and recycle nutrients?', opts: ['Herbivores', 'Decomposers', 'Primary producers', 'Apex predators'], a: 1, e: 'Decomposers such as fungi and bacteria break down dead organisms, returning nutrients to the ecosystem.', tags: ['Biogeography', 'Ecosystems'] },
  { q: 'An ecological pyramid usually narrows toward the top because', opts: ['Predators are larger', 'Energy is lost at each level', 'Producers are rare', 'Decomposers remove biomass'], a: 1, e: 'Because energy is lost at each transfer, less energy and biomass are available to support higher trophic levels.', tags: ['Biogeography', 'Ecosystems'] },
  { q: 'A food web differs from a food chain in that it', opts: ['Shows only one pathway', 'Shows many interconnected feeding pathways', 'Excludes producers', 'Ignores predators'], a: 1, e: 'A food web depicts the many interconnected food chains and feeding relationships within an ecosystem.', tags: ['Biogeography', 'Ecosystems'] },
  { q: 'The ultimate source of energy for most ecosystems is', opts: ['Geothermal heat', 'The Sun', 'Chemical bonds in rock', 'Wind'], a: 1, e: 'Sunlight drives photosynthesis in producers, providing the energy that flows through nearly all ecosystems.', tags: ['Biogeography', 'Ecosystems'] },
  { q: 'A keystone species is one that', opts: ['Has the largest population', 'Has a disproportionately large effect on its ecosystem', 'Lives the longest', 'Is always a top predator'], a: 1, e: 'A keystone species exerts an outsized influence on community structure relative to its abundance.', tags: ['Biogeography', 'Ecosystems'] },

  // ── Level 3 — Distribution, Dispersal & Barriers ──
  { q: 'The natural geographic area where a species is found is called its', opts: ['Niche', 'Range', 'Biome', 'Guild'], a: 1, e: 'A species\' range (or distribution) is the total geographic area it naturally occupies.', tags: ['Biogeography', 'Dispersal'] },
  { q: 'Which is an example of a dispersal barrier for a land mammal?', opts: ['A wide ocean', 'A grassland', 'A river valley', 'A forest edge'], a: 0, e: 'A wide ocean is a major physical barrier that most land mammals cannot cross unaided.', tags: ['Biogeography', 'Dispersal'] },
  { q: 'A species\' fundamental niche describes', opts: ['Where it actually lives with competitors', 'The full range of conditions it could occupy', 'Its geographic range only', 'Its trophic level'], a: 1, e: 'The fundamental niche is the full set of conditions a species could tolerate absent competition or other limits.', tags: ['Biogeography', 'Dispersal'] },
  { q: 'Vicariance refers to species distributions being shaped by', opts: ['Long-distance flight', 'The splitting of a range by a new barrier', 'Human introduction', 'Seasonal migration'], a: 1, e: 'Vicariance occurs when a formerly continuous range is divided by a new barrier, such as a mountain range or sea.', tags: ['Biogeography', 'Dispersal'] },
  { q: 'The abundant-centre hypothesis predicts a species is most abundant', opts: ['At the edge of its range', 'Near the centre of its range', 'Outside its range', 'Only at high elevation'], a: 1, e: 'This model predicts abundance peaks near the range centre, where conditions are most favourable, declining toward edges.', tags: ['Biogeography', 'Dispersal'] },
  { q: 'Which climatic variable most often sets the poleward (cold) limit of a species\' range?', opts: ['Minimum temperature', 'Soil pH', 'Day length only', 'Wind speed'], a: 0, e: 'Extreme minimum temperatures frequently set the cold, high-latitude limits of many species\' distributions.', tags: ['Biogeography', 'Dispersal'] },
  { q: 'Wallace\'s Line marks a sharp faunal boundary between', opts: ['Africa and Europe', 'Asian and Australian faunas', 'North and South America', 'Arctic and Antarctic'], a: 1, e: 'Wallace\'s Line separates the distinct Asian and Australian faunas across the Indonesian archipelago.', tags: ['Biogeography', 'Dispersal'] },
  { q: 'A disjunct distribution is one in which populations are', opts: ['Evenly spread', 'Separated by a large gap', 'Confined to one island', 'Migratory'], a: 1, e: 'A disjunct distribution has closely related populations separated by wide geographic gaps, often reflecting past history.', tags: ['Biogeography', 'Dispersal'] },

  // ── Level 4 — Island Biogeography & Endemism ──
  { q: 'A species found naturally in only one place and nowhere else is', opts: ['Cosmopolitan', 'Endemic', 'Invasive', 'Generalist'], a: 1, e: 'An endemic species is restricted to a single defined area, such as one island or mountain range.', tags: ['Biogeography', 'Islands'] },
  { q: 'MacArthur and Wilson\'s theory of island biogeography predicts species richness from a balance of', opts: ['Birth and death rates', 'Immigration and extinction rates', 'Predation and competition', 'Rainfall and temperature'], a: 1, e: 'The equilibrium theory sees island richness as a balance between immigration of new species and extinction of residents.', tags: ['Biogeography', 'Islands'] },
  { q: 'According to island biogeography theory, larger islands tend to have', opts: ['Fewer species', 'More species', 'No endemics', 'Higher extinction rates'], a: 1, e: 'Larger islands support more species because they offer more habitat and have lower extinction rates (the area effect).', tags: ['Biogeography', 'Islands'] },
  { q: 'Islands closer to a mainland source generally have', opts: ['Lower immigration rates', 'Higher immigration rates', 'No colonisation', 'Only endemic species'], a: 1, e: 'Near islands receive more colonists because dispersal from the mainland source is easier (the distance effect).', tags: ['Biogeography', 'Islands'] },
  { q: 'Which is a common feature of island endemic faunas?', opts: ['High dispersal ability', 'Flightlessness and loss of defences', 'Large geographic ranges', 'Resistance to introduced predators'], a: 1, e: 'Isolated islands often evolve flightless birds and animals lacking anti-predator defences, making them vulnerable.', tags: ['Biogeography', 'Islands'] },
  { q: 'The proliferation of Darwin\'s finches from one ancestor into many forms is an example of', opts: ['Convergent evolution', 'Adaptive radiation', 'Genetic drift only', 'Vicariance'], a: 1, e: 'Adaptive radiation is the rapid diversification of one lineage into many species exploiting different niches.', tags: ['Biogeography', 'Islands'] },
  { q: 'In island biogeography theory, the equilibrium number of species is reached when', opts: ['Immigration equals extinction', 'Immigration stops', 'Extinction stops', 'Area stops changing'], a: 0, e: 'Species number stabilises when the immigration rate of new species equals the extinction rate of established ones.', tags: ['Biogeography', 'Islands'] },
  { q: 'Habitat fragmentation is often analysed using island biogeography because remnants act as', opts: ['Corridors', 'Habitat islands', 'Barriers only', 'Source populations'], a: 1, e: 'Isolated habitat patches behave like islands in a "sea" of altered land, so the theory helps predict species loss.', tags: ['Biogeography', 'Islands'] },

  // ── Level 5 — Biodiversity, Realms & Human Impact ──
  { q: 'A biodiversity hotspot is a region with', opts: ['High endemism and severe habitat loss', 'Low species richness', 'Only introduced species', 'No conservation concern'], a: 0, e: 'Hotspots combine exceptional endemic richness with significant threat, making them conservation priorities.', tags: ['Biogeography', 'Conservation'] },
  { q: 'Biogeographic realms (e.g. Neotropical, Palaearctic) divide the world based on', opts: ['Ocean currents', 'Distinct assemblages of land animals and plants', 'Political boundaries', 'Elevation alone'], a: 1, e: 'Realms group regions sharing distinctive evolutionary lineages of terrestrial life, reflecting deep geographic history.', tags: ['Biogeography', 'Realms'] },
  { q: 'The latitudinal diversity gradient describes species richness that is generally', opts: ['Highest at the poles', 'Highest near the equator', 'Uniform everywhere', 'Highest in deserts'], a: 1, e: 'Species richness typically peaks in the tropics and declines toward the poles, one of ecology\'s most consistent patterns.', tags: ['Biogeography', 'Realms'] },
  { q: 'Which human activity is the leading cause of terrestrial biodiversity loss today?', opts: ['Habitat destruction and land-use change', 'Volcanic eruptions', 'Solar variation', 'Continental drift'], a: 0, e: 'Habitat loss from agriculture, logging, and urban expansion is the foremost driver of species decline on land.', tags: ['Biogeography', 'Conservation'] },
  { q: 'An invasive species typically threatens native biodiversity by', opts: ['Increasing endemism', 'Out-competing or preying on natives', 'Improving nutrient cycling only', 'Reducing extinction risk'], a: 1, e: 'Invasive species can outcompete, prey on, or introduce disease to natives, often causing local extinctions.', tags: ['Biogeography', 'Conservation'] },
  { q: 'Wildlife corridors are used in conservation mainly to', opts: ['Isolate populations', 'Connect fragmented habitats', 'Introduce invasive species', 'Increase edge effects'], a: 1, e: 'Corridors reconnect fragmented habitats, allowing dispersal and gene flow that reduce extinction risk.', tags: ['Biogeography', 'Conservation'] },
  { q: 'Climate change is shifting many species ranges toward', opts: ['Lower latitudes and elevations', 'Higher latitudes and elevations', 'The ocean floor', 'No change in range'], a: 1, e: 'As temperatures rise, many species track suitable climate by moving poleward and upslope to cooler conditions.', tags: ['Biogeography', 'Conservation'] },
  { q: 'The species–area relationship is widely used to estimate', opts: ['Extinctions expected from habitat loss', 'Ocean salinity', 'Plate movement rates', 'Soil fertility'], a: 0, e: 'Because species number scales with area, the relationship lets ecologists predict extinctions as habitat area shrinks.', tags: ['Biogeography', 'Conservation'] },
];
