import type { Seed } from './roadmap-build';

// The Middle Ages — 10 levels × 8 questions, easiest → hardest.
export const medievalSeeds: Seed[] = [
  // ── Level 1 — Fall of Rome & the Early Middle Ages ──
  {
    q: 'In what year is the Western Roman Empire traditionally said to have fallen?',
    opts: ['476 AD', '527 AD', '313 AD', '410 AD'],
    a: 0,
    e: 'In 476 AD the Germanic leader Odoacer deposed the last Western Roman emperor, Romulus Augustulus.',
    tags: ['medieval', 'early middle ages', 'rome'],
  },
  {
    q: 'The period after the fall of Rome in western Europe is sometimes called by what name?',
    opts: ['The Iron Age', 'The Dark Ages', 'The Renaissance', 'The Enlightenment'],
    a: 1,
    e: 'The early medieval centuries in western Europe are traditionally, if now unfashionably, called the Dark Ages.',
    tags: ['medieval', 'early middle ages'],
  },
  {
    q: 'Which Germanic leader deposed the last Western Roman emperor in 476 AD?',
    opts: ['Alaric', 'Attila', 'Odoacer', 'Clovis'],
    a: 2,
    e: 'Odoacer, a Germanic commander, deposed Romulus Augustulus and ruled Italy as king.',
    tags: ['medieval', 'rome', 'early middle ages'],
  },
  {
    q: 'The Middle Ages in Europe are generally dated from roughly which centuries?',
    opts: ['15th to 18th centuries', '18th to 20th centuries', '1st to 5th centuries', 'The 5th to the 15th centuries'],
    a: 3,
    e: 'The Middle Ages span roughly a thousand years, from the fall of Rome in the 5th century to about 1500.',
    tags: ['medieval', 'early middle ages'],
  },
  {
    q: 'Which group led by Alaric sacked the city of Rome in 410 AD?',
    opts: ['The Vandals', 'The Visigoths', 'The Ostrogoths', 'The Huns'],
    a: 1,
    e: 'Alaric led the Visigoths in the sack of Rome in 410 AD, a shocking event for the Roman world.',
    tags: ['medieval', 'rome', 'early middle ages'],
  },
  {
    q: 'Who was the feared leader of the Huns who invaded the Roman Empire in the 5th century?',
    opts: ['Attila', 'Genseric', 'Theodoric', 'Odoacer'],
    a: 0,
    e: 'Attila the Hun led devastating campaigns against both the Eastern and Western Roman Empires.',
    tags: ['medieval', 'huns', 'early middle ages'],
  },
  {
    q: 'The eastern half of the Roman Empire survived the fall of the west and became known as what empire?',
    opts: ['The Holy Roman Empire', 'The Ottoman Empire', 'The Persian Empire', 'The Byzantine Empire'],
    a: 3,
    e: 'The Eastern Roman Empire, centered on Constantinople, is known to historians as the Byzantine Empire.',
    tags: ['medieval', 'byzantine', 'rome'],
  },
  {
    q: 'Monasteries in the early Middle Ages were especially important for doing what?',
    opts: ['Organizing trade fairs', 'Minting coins', 'Copying and preserving books', 'Building navies'],
    a: 2,
    e: 'Monks in scriptoria copied manuscripts by hand, preserving much classical and religious learning.',
    tags: ['medieval', 'church', 'early middle ages'],
  },

  // ── Level 2 — The Byzantine Empire ──
  {
    q: 'What was the capital of the Byzantine Empire?',
    opts: ['Rome', 'Athens', 'Constantinople', 'Alexandria'],
    a: 2,
    e: 'Constantinople, founded by Emperor Constantine, served as the Byzantine capital for over a thousand years.',
    tags: ['medieval', 'byzantine'],
  },
  {
    q: 'Which famous domed church was built in Constantinople under Emperor Justinian?',
    opts: ["St. Peter's Basilica", 'Westminster Abbey', 'Notre-Dame', 'Hagia Sophia'],
    a: 3,
    e: 'The Hagia Sophia, completed in 537, was celebrated for its vast dome and remained a marvel of engineering.',
    tags: ['medieval', 'byzantine'],
  },
  {
    q: 'Which Byzantine emperor is famous for a codification of Roman law issued in the 6th century?',
    opts: ['Justinian I', 'Heraclius', 'Basil II', 'Constantine'],
    a: 0,
    e: 'Justinian I sponsored the Corpus Juris Civilis, a compilation that shaped later European law.',
    tags: ['medieval', 'byzantine', 'law'],
  },
  {
    q: 'What was the name of the influential empress and wife of Justinian I?',
    opts: ['Anna', 'Theodora', 'Zoe', 'Irene'],
    a: 1,
    e: 'Empress Theodora was a powerful figure who advised Justinian and helped him hold power during the Nika riots.',
    tags: ['medieval', 'byzantine'],
  },
  {
    q: 'The Byzantine Empire primarily spoke which language in its later centuries?',
    opts: ['Aramaic', 'Latin', 'Arabic', 'Greek'],
    a: 3,
    e: 'Although founded as the Eastern Roman Empire, Byzantium increasingly used Greek as its main language.',
    tags: ['medieval', 'byzantine', 'language'],
  },
  {
    q: 'What incendiary weapon was a closely guarded Byzantine military secret used in naval warfare?',
    opts: ['Wildfire oil', 'Gunpowder', 'Greek fire', 'Napalm'],
    a: 2,
    e: '"Greek fire" was a flammable liquid the Byzantines sprayed at enemy ships; its exact recipe remains unknown.',
    tags: ['medieval', 'byzantine', 'warfare'],
  },
  {
    q: 'The Great Schism of 1054 split Christianity into which two main branches?',
    opts: ['Catholic and Protestant', 'Roman Catholic and Eastern Orthodox', 'Orthodox and Coptic', 'Arian and Nicene'],
    a: 1,
    e: 'In 1054 disputes over authority and doctrine split the Church into the Roman Catholic west and Eastern Orthodox east.',
    tags: ['medieval', 'byzantine', 'church'],
  },
  {
    q: 'The Byzantine dispute over the use of religious images is known by what term?',
    opts: ['Iconoclasm', 'Scholasticism', 'Monasticism', 'Simony'],
    a: 0,
    e: 'Iconoclasm was the movement, especially strong in the 8th and 9th centuries, to destroy religious icons.',
    tags: ['medieval', 'byzantine', 'church'],
  },

  // ── Level 3 — The Rise of Islam ──
  {
    q: 'In which city was the prophet Muhammad born around 570 AD?',
    opts: ['Damascus', 'Mecca', 'Baghdad', 'Medina'],
    a: 1,
    e: 'Muhammad was born in Mecca, in the Arabian Peninsula, which became Islam most sacred city.',
    tags: ['medieval', 'islam'],
  },
  {
    q: 'The Islamic calendar begins with the Hijra, the migration of Muhammad from Mecca to which city?',
    opts: ['Medina', 'Cairo', 'Damascus', 'Jerusalem'],
    a: 0,
    e: 'The Hijra of 622 AD, Muhammad move to Medina, marks year one of the Islamic calendar.',
    tags: ['medieval', 'islam'],
  },
  {
    q: 'What is the holy book of Islam called?',
    opts: ['The Torah', 'The Vedas', 'The Talmud', 'The Quran'],
    a: 3,
    e: 'The Quran is the central religious text of Islam, believed by Muslims to be revealed to Muhammad.',
    tags: ['medieval', 'islam'],
  },
  {
    q: 'The leaders of the Muslim community after Muhammad death were given what title?',
    opts: ['Sultan', 'Emir', 'Caliph', 'Vizier'],
    a: 2,
    e: 'A caliph was the political and religious successor to Muhammad, leading the caliphate.',
    tags: ['medieval', 'islam'],
  },
  {
    q: 'Which dynasty made Baghdad its capital and presided over a golden age of learning?',
    opts: ['The Abbasids', 'The Fatimids', 'The Seljuks', 'The Umayyads'],
    a: 0,
    e: 'The Abbasid Caliphate, based in Baghdad from 762, oversaw major advances in science and scholarship.',
    tags: ['medieval', 'islam', 'baghdad'],
  },
  {
    q: 'Muslim armies were halted from advancing into western Europe at which 732 battle in France?',
    opts: ['Battle of Hastings', 'Battle of Tours', 'Battle of Manzikert', 'Battle of Yarmuk'],
    a: 1,
    e: 'At the Battle of Tours (Poitiers) in 732, the Frankish leader Charles Martel checked a Muslim advance.',
    tags: ['medieval', 'islam', 'franks'],
  },
  {
    q: 'The Muslim-ruled region of medieval Spain was known by what name?',
    opts: ['Asturias', 'Andorra', 'Al-Andalus', 'Aragon'],
    a: 2,
    e: 'Al-Andalus was the Arabic name for the Iberian territories under Muslim rule, centered for a time on Cordoba.',
    tags: ['medieval', 'islam', 'spain'],
  },
  {
    q: 'The early Muslim conquests took large territories from which two empires?',
    opts: ['The Frankish and Lombard kingdoms', 'The Mongol and Chinese empires', 'The Roman and Carthaginian empires', 'The Byzantine and Sasanian empires'],
    a: 3,
    e: 'In the 7th century, Arab armies seized Byzantine provinces and conquered the Sasanian Persian Empire entirely.',
    tags: ['medieval', 'islam', 'byzantine'],
  },

  // ── Level 4 — Feudalism & Manorialism ──
  {
    q: 'In the feudal system, what did a lord grant to a vassal in exchange for military service?',
    opts: ['A ship', 'A monastery', 'A crown', 'A fief of land'],
    a: 3,
    e: 'A lord granted a fief, usually land, to a vassal who in return pledged loyalty and military service.',
    tags: ['medieval', 'feudalism'],
  },
  {
    q: 'What term describes peasants who were bound to the land and worked for a lord?',
    opts: ['Squires', 'Burghers', 'Serfs', 'Knights'],
    a: 2,
    e: 'Serfs were unfree peasants tied to a manor who farmed the land and owed labor to their lord.',
    tags: ['medieval', 'feudalism', 'manorialism'],
  },
  {
    q: 'A young man training to become a knight typically first served as a what?',
    opts: ['A monk', 'A page and then a squire', 'A reeve', 'A steward'],
    a: 1,
    e: 'Boys of noble birth trained first as pages, then as squires, before being knighted.',
    tags: ['medieval', 'feudalism', 'knights'],
  },
  {
    q: 'The self-sufficient agricultural estate at the center of medieval rural economy was called a what?',
    opts: ['A manor', 'A borough', 'A guild', 'A parish'],
    a: 0,
    e: 'The manor was the basic economic unit, an estate where serfs farmed land held by a lord.',
    tags: ['medieval', 'manorialism'],
  },
  {
    q: 'The code of conduct expected of a medieval knight is known as what?',
    opts: ['Fealty', 'Feudalism', 'Chivalry', 'Vassalage'],
    a: 2,
    e: 'Chivalry was the ideal code of honor, courage, and courtesy that knights were expected to follow.',
    tags: ['medieval', 'knights', 'chivalry'],
  },
  {
    q: 'The solemn ceremony in which a vassal pledged loyalty to a lord was called what?',
    opts: ['Tithing', 'Investiture', 'Excommunication', 'Homage'],
    a: 3,
    e: 'In the act of homage, a vassal knelt and formally pledged fealty and service to his lord.',
    tags: ['medieval', 'feudalism'],
  },
  {
    q: 'Under the three-field system, roughly what portion of farmland was typically left fallow each year?',
    opts: ['One third', 'One quarter', 'One tenth', 'One half'],
    a: 0,
    e: 'The three-field system rotated crops across three fields, leaving about one third fallow to restore the soil.',
    tags: ['medieval', 'manorialism', 'agriculture'],
  },
  {
    q: 'Which medieval technology greatly improved plowing of the heavy soils of northern Europe?',
    opts: ['The seed drill', 'The heavy moldboard plow', 'The cotton gin', 'The steam engine'],
    a: 1,
    e: 'The heavy moldboard plow could turn the dense, wet soils of northern Europe, boosting food production.',
    tags: ['medieval', 'agriculture', 'technology'],
  },

  // ── Level 5 — The Medieval Church ──
  {
    q: 'Who was the head of the Roman Catholic Church in the Middle Ages?',
    opts: ['The Pope', 'The Archbishop of Canterbury', 'The Patriarch', 'The Emperor'],
    a: 0,
    e: 'The Pope, bishop of Rome, was the supreme head of the Western Church.',
    tags: ['medieval', 'church'],
  },
  {
    q: 'The most severe penalty by which the Church cut a person off from its sacraments was called what?',
    opts: ['Confirmation', 'Coronation', 'Excommunication', 'Ordination'],
    a: 2,
    e: 'Excommunication expelled a person from the Church and its sacraments, a grave threat in a devout age.',
    tags: ['medieval', 'church'],
  },
  {
    q: 'Members of the Church who lived apart in communities devoted to prayer and work were called what?',
    opts: ['Bishops', 'Monks', 'Cardinals', 'Deacons'],
    a: 1,
    e: 'Monks lived in monasteries under a rule such as that of St. Benedict, devoted to prayer and labor.',
    tags: ['medieval', 'church', 'monasticism'],
  },
  {
    q: 'What tax, equal to about a tenth of income, did people pay to the medieval Church?',
    opts: ['The tariff', 'The tribute', 'The toll', 'The tithe'],
    a: 3,
    e: 'The tithe was a payment of roughly one tenth of a person income or produce owed to the Church.',
    tags: ['medieval', 'church'],
  },
  {
    q: 'Which monastic order was founded by St. Benedict and emphasized the motto of prayer and work?',
    opts: ['The Franciscans', 'The Dominicans', 'The Benedictines', 'The Jesuits'],
    a: 2,
    e: 'The Benedictines followed the Rule of St. Benedict, structuring monastic life around prayer and labor.',
    tags: ['medieval', 'church', 'monasticism'],
  },
  {
    q: 'The Investiture Controversy was a struggle between popes and emperors over the right to do what?',
    opts: ['Appoint bishops', 'Declare war', 'Mint coins', 'Collect taxes'],
    a: 0,
    e: 'The Investiture Controversy pitted Pope Gregory VII against Emperor Henry IV over who could appoint bishops.',
    tags: ['medieval', 'church', 'papacy'],
  },
  {
    q: 'The intellectual method of using reason and logic to explore Christian doctrine is called what?',
    opts: ['Empiricism', 'Mysticism', 'Humanism', 'Scholasticism'],
    a: 3,
    e: 'Scholasticism, associated with thinkers like Thomas Aquinas, applied Aristotelian logic to theology.',
    tags: ['medieval', 'church', 'philosophy'],
  },
  {
    q: 'The practice of buying or selling church offices was condemned as which sin?',
    opts: ['Usury', 'Simony', 'Heresy', 'Apostasy'],
    a: 1,
    e: 'Simony, the buying or selling of church positions, was a major target of medieval reformers.',
    tags: ['medieval', 'church'],
  },

  // ── Level 6 — Charlemagne & the Franks ──
  {
    q: 'Charlemagne was crowned Emperor of the Romans by the Pope in which year?',
    opts: ['711 AD', '800 AD', '843 AD', '962 AD'],
    a: 1,
    e: 'On Christmas Day 800, Pope Leo III crowned Charlemagne as Emperor in Rome.',
    tags: ['medieval', 'franks', 'charlemagne'],
  },
  {
    q: 'Charlemagne was the greatest king of which royal dynasty?',
    opts: ['The Capetians', 'The Ottonians', 'The Merovingians', 'The Carolingians'],
    a: 3,
    e: 'Charlemagne belonged to the Carolingian dynasty, which the family took its name from him (Carolus).',
    tags: ['medieval', 'franks', 'charlemagne'],
  },
  {
    q: 'Which Frankish leader defeated a Muslim army at the Battle of Tours in 732?',
    opts: ['Charles Martel', 'Louis the Pious', 'Clovis', 'Pepin the Short'],
    a: 0,
    e: 'Charles Martel, grandfather of Charlemagne, halted the Muslim advance at Tours in 732.',
    tags: ['medieval', 'franks'],
  },
  {
    q: 'Which earlier Frankish king converted to Catholic Christianity around 496 AD?',
    opts: ['Charles the Bald', 'Dagobert', 'Clovis', 'Charlemagne'],
    a: 2,
    e: 'Clovis, king of the Franks, converted to Catholic Christianity, aligning his people with the Roman Church.',
    tags: ['medieval', 'franks'],
  },
  {
    q: 'The revival of learning and culture under Charlemagne is known as the what?',
    opts: ['Ottonian Renaissance', 'Twelfth-Century Renaissance', 'Italian Renaissance', 'Carolingian Renaissance'],
    a: 3,
    e: 'The Carolingian Renaissance saw renewed scholarship, education, and manuscript production at Charlemagne court.',
    tags: ['medieval', 'franks', 'charlemagne'],
  },
  {
    q: 'The 843 Treaty of Verdun did what to Charlemagne empire?',
    opts: ['United it with Byzantium', 'Divided it among his three grandsons', 'Doubled its size', 'Gave it to the Pope'],
    a: 1,
    e: 'The Treaty of Verdun in 843 split the Carolingian Empire among the three grandsons of Charlemagne.',
    tags: ['medieval', 'franks'],
  },
  {
    q: 'Charlemagne established his main capital and palace complex in which city?',
    opts: ['Cologne', 'Paris', 'Aachen', 'Rome'],
    a: 2,
    e: 'Aachen (Aix-la-Chapelle) served as Charlemagne principal residence and the center of his court.',
    tags: ['medieval', 'franks', 'charlemagne'],
  },
  {
    q: 'Charlemagne recruited which English scholar to lead educational reforms at his court?',
    opts: ['Alcuin of York', 'Boethius', 'Cassiodorus', 'Bede'],
    a: 0,
    e: 'Alcuin of York, a leading scholar, directed the palace school and educational revival under Charlemagne.',
    tags: ['medieval', 'franks', 'charlemagne'],
  },

  // ── Level 7 — The Crusades ──
  {
    q: 'What was the main goal of the First Crusade, launched in 1096?',
    opts: ['To reach India', 'To conquer Egypt', 'To capture Jerusalem and the Holy Land', 'To invade France'],
    a: 2,
    e: 'The First Crusade aimed to seize Jerusalem and the Holy Land from Muslim control.',
    tags: ['medieval', 'crusades'],
  },
  {
    q: 'Which pope called for the First Crusade at the Council of Clermont in 1095?',
    opts: ['Urban II', 'Innocent III', 'Leo IX', 'Gregory VII'],
    a: 0,
    e: 'Pope Urban II preached the First Crusade at Clermont in 1095, urging Christians to take up arms.',
    tags: ['medieval', 'crusades', 'papacy'],
  },
  {
    q: 'The Crusaders captured Jerusalem during the First Crusade in which year?',
    opts: ['1187', '1204', '1066', '1099'],
    a: 3,
    e: 'The First Crusade succeeded in capturing Jerusalem in 1099, establishing crusader states.',
    tags: ['medieval', 'crusades'],
  },
  {
    q: 'Which Muslim leader recaptured Jerusalem from the Crusaders in 1187?',
    opts: ['Suleiman', 'Saladin', 'Baybars', 'Nur ad-Din'],
    a: 1,
    e: 'Saladin (Salah ad-Din) defeated the Crusaders at Hattin and retook Jerusalem in 1187.',
    tags: ['medieval', 'crusades'],
  },
  {
    q: 'The Fourth Crusade of 1204 notoriously ended with the sack of which Christian city?',
    opts: ['Constantinople', 'Venice', 'Rome', 'Antioch'],
    a: 0,
    e: 'The Fourth Crusade was diverted and sacked Constantinople in 1204, deeply harming Christian relations.',
    tags: ['medieval', 'crusades', 'byzantine'],
  },
  {
    q: 'Which military-religious order of knights was founded to protect pilgrims in the Holy Land?',
    opts: ['The Praetorian Guard', 'The Varangian Guard', 'The Knights Templar', 'The Teutonic burghers'],
    a: 2,
    e: 'The Knights Templar were a military order established in the early 12th century to protect pilgrims.',
    tags: ['medieval', 'crusades', 'knights'],
  },
  {
    q: 'The Third Crusade featured a rivalry between Saladin and which English king?',
    opts: ['John', 'Richard the Lionheart', 'Henry II', 'Edward I'],
    a: 1,
    e: 'King Richard I, the Lionheart, led the Third Crusade and negotiated a truce with Saladin.',
    tags: ['medieval', 'crusades'],
  },
  {
    q: 'The centuries-long Christian effort to retake the Iberian Peninsula from Muslim rule is called the what?',
    opts: ['The Inquisition', 'The Crusade of Kings', 'The Hundred Years War', 'The Reconquista'],
    a: 3,
    e: 'The Reconquista was the gradual Christian reconquest of Iberia, completed with the fall of Granada in 1492.',
    tags: ['medieval', 'reconquista', 'spain'],
  },

  // ── Level 8 — Medieval Life & Towns ──
  {
    q: 'Associations of merchants or craftsmen that regulated trade in medieval towns were called what?',
    opts: ['Parishes', 'Fiefs', 'Manors', 'Guilds'],
    a: 3,
    e: 'Guilds controlled quality, prices, and training within a particular craft or trade in medieval towns.',
    tags: ['medieval', 'towns', 'guilds'],
  },
  {
    q: 'A craftsman who had completed training but was not yet a master was known as a what?',
    opts: ['An apprentice', 'A journeyman', 'A serf', 'A burgher'],
    a: 1,
    e: 'A journeyman had finished apprenticeship and worked for wages while aspiring to become a master.',
    tags: ['medieval', 'towns', 'guilds'],
  },
  {
    q: 'The revival of long-distance trade helped a class of town-dwelling merchants known by what name?',
    opts: ['Squires', 'Serfs', 'The bourgeoisie or burghers', 'Vassals'],
    a: 2,
    e: 'The rising urban merchant class, the burghers or bourgeoisie, grew wealthy from commerce and trade.',
    tags: ['medieval', 'towns'],
  },
  {
    q: 'Which powerful trading network of northern European towns dominated Baltic commerce?',
    opts: ['The Hanseatic League', 'The Delian League', 'The Lombard League', 'The Latin League'],
    a: 0,
    e: 'The Hanseatic League was a commercial alliance of merchant towns that controlled trade around the Baltic and North Seas.',
    tags: ['medieval', 'towns', 'trade'],
  },
  {
    q: 'The tall, pointed architectural style with flying buttresses seen in medieval cathedrals is called what?',
    opts: ['Romanesque', 'Gothic', 'Baroque', 'Byzantine'],
    a: 1,
    e: 'Gothic architecture, with pointed arches and flying buttresses, allowed for taller cathedrals and larger windows.',
    tags: ['medieval', 'architecture', 'towns'],
  },
  {
    q: 'The first universities in medieval Europe emerged in cities such as Bologna and which other?',
    opts: ['Lisbon', 'Stockholm', 'Moscow', 'Paris'],
    a: 3,
    e: 'Universities arose at Bologna, Paris, Oxford, and elsewhere as centers of higher learning from the 12th century.',
    tags: ['medieval', 'towns', 'education'],
  },
  {
    q: 'The Magna Carta, sealed in 1215, limited the power of which English king?',
    opts: ['John', 'Henry III', 'Edward I', 'Richard I'],
    a: 0,
    e: 'Rebellious barons forced King John to seal the Magna Carta in 1215, restraining royal authority.',
    tags: ['medieval', 'england', 'law'],
  },
  {
    q: 'A charter granting a medieval town self-government and certain freedoms was often called a what?',
    opts: ['A benefice', 'A tithe', 'A commune or town charter', 'A fief'],
    a: 2,
    e: 'Town charters or communes gave residents rights of self-government, freeing them from some feudal obligations.',
    tags: ['medieval', 'towns', 'law'],
  },

  // ── Level 9 — Mongols & Asia ──
  {
    q: 'Who united the Mongol tribes and founded the Mongol Empire in the early 13th century?',
    opts: ['Genghis Khan', 'Tamerlane', 'Ogedei Khan', 'Kublai Khan'],
    a: 0,
    e: 'Genghis Khan (Temujin) united the Mongol tribes around 1206 and began vast conquests.',
    tags: ['medieval', 'mongols', 'asia'],
  },
  {
    q: 'Which grandson of Genghis Khan founded the Yuan dynasty and ruled China?',
    opts: ['Hulagu Khan', 'Mongke Khan', 'Batu Khan', 'Kublai Khan'],
    a: 3,
    e: 'Kublai Khan conquered China and established the Yuan dynasty, ruling as its first emperor.',
    tags: ['medieval', 'mongols', 'china'],
  },
  {
    q: 'Which Italian merchant famously described his travels to the court of Kublai Khan?',
    opts: ['Amerigo Vespucci', 'Marco Polo', 'Christopher Columbus', 'John Cabot'],
    a: 1,
    e: 'Marco Polo of Venice traveled to China and recorded his experiences at the court of Kublai Khan.',
    tags: ['medieval', 'mongols', 'trade'],
  },
  {
    q: 'The Mongol invasions helped secure trade along which famous network of routes?',
    opts: ['The Amber Road', 'The Trans-Saharan route', 'The Silk Road', 'The Spice Islands'],
    a: 2,
    e: 'The Mongol Peace (Pax Mongolica) made the Silk Road safer, boosting trade across Eurasia.',
    tags: ['medieval', 'mongols', 'trade'],
  },
  {
    q: 'The Mongols sacked Baghdad in 1258, ending which caliphate?',
    opts: ['The Fatimid Caliphate', 'The Ottoman Caliphate', 'The Umayyad Caliphate', 'The Abbasid Caliphate'],
    a: 3,
    e: 'The Mongol sack of Baghdad in 1258 destroyed the Abbasid Caliphate and its capital.',
    tags: ['medieval', 'mongols', 'islam'],
  },
  {
    q: 'The western Mongol khanate that dominated Russia was known as what?',
    opts: ['The Golden Horde', 'The Ilkhanate', 'The Chagatai Khanate', 'The Timurid Empire'],
    a: 0,
    e: 'The Golden Horde was the Mongol khanate that ruled over Russian principalities for over two centuries.',
    tags: ['medieval', 'mongols', 'russia'],
  },
  {
    q: 'Which Chinese dynasty overthrew Mongol rule and was founded in 1368?',
    opts: ['The Song dynasty', 'The Tang dynasty', 'The Ming dynasty', 'The Qing dynasty'],
    a: 2,
    e: 'The Ming dynasty expelled the Mongols and ruled China from 1368, restoring native Chinese rule.',
    tags: ['medieval', 'china', 'mongols'],
  },
  {
    q: 'Two Mongol attempts to invade Japan in the 1270s and 1280s were thwarted partly by what?',
    opts: ['Volcanic eruptions', 'Typhoons called the kamikaze', 'Frozen seas', 'Massive earthquakes'],
    a: 1,
    e: 'Typhoons known as the kamikaze, or "divine wind," destroyed much of the Mongol invasion fleets bound for Japan.',
    tags: ['medieval', 'mongols', 'japan'],
  },

  // ── Level 10 — Plague & the Late Middle Ages ──
  {
    q: 'The devastating pandemic that struck Europe around 1347-1351 is known as the what?',
    opts: ['The Great Fire', 'The Black Death', 'The Spanish Flu', 'The Sweating Sickness'],
    a: 1,
    e: 'The Black Death, a plague pandemic, killed a huge share of Europe population in the mid-14th century.',
    tags: ['medieval', 'plague', 'late middle ages'],
  },
  {
    q: 'The Black Death is generally believed to have been caused by a bacterium spread chiefly by what?',
    opts: ['Airborne dust', 'Mosquitoes', 'Fleas on rats', 'Contaminated grain'],
    a: 2,
    e: 'The plague bacterium was spread largely by fleas carried on black rats that traveled along trade routes.',
    tags: ['medieval', 'plague', 'late middle ages'],
  },
  {
    q: 'Roughly what fraction of Europe population is commonly estimated to have died in the Black Death?',
    opts: ['About one third', 'About two thirds', 'About nine tenths', 'About one tenth'],
    a: 0,
    e: 'Estimates commonly hold that the Black Death killed roughly one third of Europe population.',
    tags: ['medieval', 'plague', 'late middle ages'],
  },
  {
    q: 'The long conflict between England and France from 1337 to 1453 is called the what?',
    opts: ['The Thirty Years War', 'The Norman Conquest', 'The War of the Roses', 'The Hundred Years War'],
    a: 3,
    e: 'The Hundred Years War was a series of conflicts between England and France over the French throne and lands.',
    tags: ['medieval', 'late middle ages', 'war'],
  },
  {
    q: 'Which French peasant girl led armies to victory before her capture during the Hundred Years War?',
    opts: ['Catherine de Medici', 'Isabella of France', 'Joan of Arc', 'Eleanor of Aquitaine'],
    a: 2,
    e: 'Joan of Arc rallied French forces, notably at Orleans, before being captured and executed in 1431.',
    tags: ['medieval', 'late middle ages', 'france'],
  },
  {
    q: 'Constantinople fell to the Ottoman Turks in 1453, ending the Byzantine Empire under which sultan?',
    opts: ['Suleiman the Magnificent', 'Mehmed II', 'Osman I', 'Bayezid I'],
    a: 1,
    e: 'Sultan Mehmed II captured Constantinople in 1453, ending the Byzantine Empire and expanding Ottoman power.',
    tags: ['medieval', 'byzantine', 'ottomans'],
  },
  {
    q: 'Which English dynastic conflict between the houses of Lancaster and York took place in the late 15th century?',
    opts: ['The Anarchy', 'The Barons War', 'The Peasants Revolt', 'The Wars of the Roses'],
    a: 3,
    e: 'The Wars of the Roses were fought between the Lancastrians and Yorkists for the English throne.',
    tags: ['medieval', 'england', 'late middle ages'],
  },
  {
    q: 'Which reformer was condemned and burned at the Council of Constance in 1415 for his teachings?',
    opts: ['Jan Hus', 'John Calvin', 'Martin Luther', 'John Wycliffe'],
    a: 0,
    e: 'Jan Hus, a Bohemian church reformer, was burned at the stake in 1415 after being condemned as a heretic.',
    tags: ['medieval', 'church', 'late middle ages'],
  },
];
