// Historiography roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const historiographySeeds: Seed[] = [
  // ── Level 1 — Sources & Evidence ──
  { q: 'A primary source is best defined as evidence that:', opts: ['Interprets events long afterward', 'Originates from the time under study', 'Is written by a professional historian', 'Appears in a textbook'], a: 1, e: 'Primary sources come directly from the period being studied, such as letters, records, or artifacts.', tags: ['Historiography', 'Sources'] },
  { q: 'Which of these is a secondary source?', opts: ['A soldier\'s wartime diary', 'A medieval charter', 'A modern biography of Napoleon', 'A census return from 1851'], a: 2, e: 'A secondary source analyzes or interprets primary evidence after the fact, like a later biography.', tags: ['Historiography', 'Sources'] },
  { q: 'A clay tablet, a coin, and a pottery shard are examples of:', opts: ['Oral sources', 'Material (archaeological) sources', 'Secondary sources', 'Historiographical debates'], a: 1, e: 'Physical objects left by past societies are material or archaeological evidence.', tags: ['Historiography', 'Sources'] },
  { q: 'Oral history is most valuable for capturing:', opts: ['Exact ancient dates', 'Testimony and memory of living witnesses', 'Government statistics', 'Archaeological strata'], a: 1, e: 'Oral history records the recollections and perspectives of people who lived through events.', tags: ['Historiography', 'Sources'] },
  { q: 'A source created for public consumption at the time (e.g., a newspaper) is called a:', opts: ['Private source', 'Public source', 'Secondary source', 'Tertiary source'], a: 1, e: 'Public sources were intended for wide audiences, unlike private letters or diaries.', tags: ['Historiography', 'Sources'] },
  { q: 'An encyclopedia entry summarizing many studies is best classified as a:', opts: ['Primary source', 'Material source', 'Tertiary source', 'Eyewitness source'], a: 2, e: 'Tertiary sources compile and condense secondary works for reference.', tags: ['Historiography', 'Sources'] },
  { q: 'Why do historians value a wide variety of source types?', opts: ['To make research longer', 'To cross-check and build a fuller picture', 'To avoid using primary sources', 'To follow legal rules'], a: 1, e: 'Different source types illuminate different aspects and let historians corroborate findings.', tags: ['Historiography', 'Sources'] },
  { q: 'The "silence" of the archive most often refers to:', opts: ['Quiet reading rooms', 'Groups left unrecorded in surviving documents', 'Missing page numbers', 'Damaged microfilm'], a: 1, e: 'Many people, especially the poor and marginalized, left few written records, creating gaps historians must address.', tags: ['Historiography', 'Sources'] },

  // ── Level 2 — Historical Method ──
  { q: 'Establishing when a source was produced is called:', opts: ['Provenance', 'Dating', 'Transcription', 'Citation'], a: 1, e: 'Dating a source is essential for placing it correctly in a sequence of events.', tags: ['Historiography', 'Method'] },
  { q: 'Provenance refers to a source\'s:', opts: ['Language style', 'Origin and chain of custody', 'Word count', 'Political message'], a: 1, e: 'Provenance is the record of where a source came from and how it was preserved, key to authenticity.', tags: ['Historiography', 'Method'] },
  { q: 'Corroboration in historical method means:', opts: ['Trusting one source fully', 'Confirming a claim across independent sources', 'Translating a document', 'Dating an artifact'], a: 1, e: 'Corroboration checks whether independent sources agree, strengthening a conclusion.', tags: ['Historiography', 'Method'] },
  { q: 'Radiocarbon dating is used primarily to date:', opts: ['Metal coins', 'Organic materials', 'Printed books', 'Stone tools directly'], a: 1, e: 'Carbon-14 dating measures decay in once-living matter like wood, bone, or cloth.', tags: ['Historiography', 'Method'] },
  { q: 'A source\'s bias is best handled by historians through:', opts: ['Discarding all biased sources', 'Analyzing the bias to understand perspective', 'Ignoring the author', 'Assuming neutrality'], a: 1, e: 'Bias itself is evidence; understanding an author\'s viewpoint can reveal much about the period.', tags: ['Historiography', 'Method'] },
  { q: 'Which factor most undermines a source\'s reliability?', opts: ['It is handwritten', 'The author had reason to distort the truth', 'It is very old', 'It is in a foreign language'], a: 1, e: 'Motive to deceive or exaggerate is a central concern when weighing reliability.', tags: ['Historiography', 'Method'] },
  { q: 'Internal criticism of a source evaluates its:', opts: ['Paper and ink', 'Meaning and credibility of content', 'Physical binding', 'Storage location'], a: 1, e: 'Internal criticism assesses what a source says and whether it can be believed, versus external criticism of authenticity.', tags: ['Historiography', 'Method'] },
  { q: 'An anachronism in a document (e.g., a term coined later) suggests it may be:', opts: ['Highly authentic', 'A forgery or later addition', 'A primary source', 'Well dated'], a: 1, e: 'Anachronisms are classic clues that a text was written or altered later than claimed.', tags: ['Historiography', 'Method'] },

  // ── Level 3 — Schools of Thought ──
  { q: 'Leopold von Ranke is associated with the aim of writing history:', opts: ['To predict the future', 'As it essentially happened, from documents', 'Only through economics', 'As pure fiction'], a: 1, e: 'Ranke championed rigorous archival research and the ideal of showing the past "wie es eigentlich gewesen".', tags: ['Historiography', 'Schools'] },
  { q: 'The Annales school is best known for emphasizing:', opts: ['Great men and battles', 'Long-term social and geographic structures', 'Divine causation', 'Diplomatic treaties only'], a: 1, e: 'Annales historians like Braudel stressed the longue durée, geography, and everyday social life.', tags: ['Historiography', 'Schools'] },
  { q: 'Braudel\'s concept of the longue durée refers to:', opts: ['Single dramatic events', 'Slow-moving, long-term historical structures', 'Individual biographies', 'Annual budgets'], a: 1, e: 'The longue durée describes deep structures like climate and geography that change over centuries.', tags: ['Historiography', 'Schools'] },
  { q: 'A Marxist approach to history centers on:', opts: ['Religious visions', 'Class conflict and material economic forces', 'National character', 'Individual genius'], a: 1, e: 'Marxist historiography interprets change through economic modes of production and class struggle.', tags: ['Historiography', 'Schools'] },
  { q: '"History from below" seeks to recover the experience of:', opts: ['Kings and generals', 'Ordinary people and the marginalized', 'Diplomats', 'Bank owners'], a: 1, e: 'Associated with historians like E. P. Thompson, it studies the lives of common people rather than elites.', tags: ['Historiography', 'Schools'] },
  { q: 'Postmodern historiography is most skeptical of:', opts: ['Using any sources', 'Claims to a single objective historical truth', 'Reading documents', 'Chronology entirely'], a: 1, e: 'Postmodernists stress that narratives are constructed and question grand claims to objective truth.', tags: ['Historiography', 'Schools'] },
  { q: 'The "linguistic turn" drew historians\' attention to:', opts: ['Statistics', 'How language and texts shape meaning', 'Carbon dating', 'Military tactics'], a: 1, e: 'The linguistic turn emphasized that language does not transparently reflect reality but constructs it.', tags: ['Historiography', 'Schools'] },
  { q: 'The Whig interpretation of history was criticized by Butterfield for:', opts: ['Ignoring documents', 'Reading the past as inevitable progress toward the present', 'Overusing economics', 'Rejecting all narrative'], a: 1, e: 'Whig history judges the past by present values and frames it as steady progress, a presentist fallacy.', tags: ['Historiography', 'Schools'] },

  // ── Level 4 — Interpretation & Causation ──
  { q: 'Historical causation asks primarily:', opts: ['When something happened', 'Why and how something happened', 'Where documents are stored', 'Who owns an archive'], a: 1, e: 'Causation concerns the reasons and mechanisms behind historical change.', tags: ['Historiography', 'Causation'] },
  { q: 'Contingency in history refers to the idea that:', opts: ['Outcomes were inevitable', 'Events could have turned out differently', 'History repeats exactly', 'Only economics matters'], a: 1, e: 'Contingency stresses that chance and choice made outcomes uncertain rather than predetermined.', tags: ['Historiography', 'Causation'] },
  { q: 'A counterfactual in history explores:', opts: ['Only proven facts', 'What might have happened if events differed', 'Exact dates', 'Source provenance'], a: 1, e: 'Counterfactual reasoning tests the importance of a cause by imagining its absence.', tags: ['Historiography', 'Causation'] },
  { q: 'Historians usually distinguish long-term causes from:', opts: ['Fictional causes', 'Immediate triggers or short-term causes', 'Secondary sources', 'Anachronisms'], a: 1, e: 'Explanations often separate underlying long-term conditions from proximate triggering events.', tags: ['Historiography', 'Causation'] },
  { q: 'Presentism is the error of:', opts: ['Dating sources precisely', 'Judging the past by present-day values', 'Using primary sources', 'Comparing regions'], a: 1, e: 'Presentism imposes modern assumptions and morals anachronistically onto earlier eras.', tags: ['Historiography', 'Causation'] },
  { q: 'The problem of "overdetermination" in causation means:', opts: ['Too few causes exist', 'Multiple sufficient causes make weighting hard', 'Sources are missing', 'Dates conflict'], a: 1, e: 'When several causes could each independently produce an outcome, isolating the decisive one is difficult.', tags: ['Historiography', 'Causation'] },
  { q: 'Structure-versus-agency debates concern the tension between:', opts: ['Old and new sources', 'Broad conditions and individual choices', 'Primary and secondary sources', 'Dating methods'], a: 1, e: 'Historians debate how much outcomes reflect impersonal structures versus the actions of individuals.', tags: ['Historiography', 'Causation'] },
  { q: 'Teleological explanations of history are criticized because they:', opts: ['Use too many sources', 'Assume events aimed at a predetermined end', 'Reject chronology', 'Avoid causation'], a: 1, e: 'Teleology treats history as moving toward an inevitable goal, ignoring contingency and hindsight bias.', tags: ['Historiography', 'Causation'] },

  // ── Level 5 — Memory, Revisionism & Public History ──
  { q: 'Historical revisionism, in its legitimate scholarly sense, means:', opts: ['Denying documented facts', 'Reinterpreting the past with new evidence or questions', 'Erasing archives', 'Rejecting all sources'], a: 1, e: 'Scholarly revisionism updates interpretations as new evidence and perspectives emerge; it differs from denialism.', tags: ['Historiography', 'Memory'] },
  { q: 'Collective memory differs from academic history in that it:', opts: ['Uses footnotes', 'Reflects a group\'s shared, often selective, remembrance', 'Is always accurate', 'Avoids emotion'], a: 1, e: 'Collective memory is how communities remember and commemorate, shaped by identity rather than strict evidence.', tags: ['Historiography', 'Memory'] },
  { q: 'Pierre Nora\'s "lieux de mémoire" (sites of memory) are:', opts: ['Only physical archives', 'Places, symbols, or rituals that anchor collective memory', 'Primary documents', 'Dating techniques'], a: 1, e: 'Nora described monuments, holidays, and symbols where a society\'s memory crystallizes.', tags: ['Historiography', 'Memory'] },
  { q: 'Public history primarily involves:', opts: ['Peer-reviewed journals only', 'Presenting history to broad audiences via museums, media, sites', 'Secret archives', 'Statistical modeling'], a: 1, e: 'Public history brings the past to general audiences through exhibits, heritage sites, and media.', tags: ['Historiography', 'Memory'] },
  { q: 'A contested history is one where:', opts: ['All historians agree', 'Different groups dispute its meaning or facts', 'No sources exist', 'Dates are certain'], a: 1, e: 'Contested histories involve competing interpretations, often tied to identity, politics, or memory.', tags: ['Historiography', 'Memory'] },
  { q: 'Debates over removing or keeping monuments are essentially about:', opts: ['Carbon dating', 'How societies choose to commemorate the past', 'Source provenance', 'Radiometric error'], a: 1, e: 'Monument debates concern public memory and which narratives a community chooses to honor.', tags: ['Historiography', 'Memory'] },
  { q: '"Instrumentalization" of history refers to:', opts: ['Using scientific instruments', 'Using the past to serve present political aims', 'Archiving documents', 'Dating pottery'], a: 1, e: 'History can be instrumentalized when states or groups shape narratives to legitimize present agendas.', tags: ['Historiography', 'Memory'] },
  { q: 'The concept of "invented tradition" (Hobsbawm) holds that some customs:', opts: ['Are truly ancient', 'Were recently created but presented as old', 'Have no rituals', 'Cannot be studied'], a: 1, e: 'Hobsbawm showed many "timeless" traditions were deliberately constructed in the modern era for legitimacy.', tags: ['Historiography', 'Memory'] },
];
