// Economic History roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const economicHistorySeeds: Seed[] = [
  // ── Level 1 — Early Economies ──
  { q: 'What is \'barter\'?', opts: ['Trading goods directly for other goods', 'Paying with coins', 'Lending at interest', 'Storing grain in temples'], a: 0, e: 'Barter is the direct exchange of goods or services without using money.', tags: ['Economic History', 'Early Economies'] },
  { q: 'A key problem with barter that money solves is the lack of a \'double coincidence of\' what?', opts: ['Prices', 'Wants', 'Weights', 'Seasons'], a: 1, e: 'Barter requires both parties to want what the other offers; money removes this double coincidence of wants.', tags: ['Economic History', 'Early Economies'] },
  { q: 'Which metal were the earliest widely used coins made from?', opts: ['Electrum', 'Aluminium', 'Tin', 'Nickel'], a: 0, e: 'The first coins, minted in Lydia, were made of electrum, a natural gold-silver alloy.', tags: ['Economic History', 'Early Economies'] },
  { q: 'The kingdom credited with minting the first standardized coins (7th century BCE) was:', opts: ['Lydia', 'Egypt', 'Assyria', 'Carthage'], a: 0, e: 'Lydia, in modern-day Turkey, is credited with producing the first true coinage.', tags: ['Economic History', 'Early Economies'] },
  { q: 'Which of these is a classic \'function of money\'?', opts: ['Store of value', 'Source of rainfall', 'Cause of war', 'Unit of distance'], a: 0, e: 'Money serves as a medium of exchange, a unit of account, and a store of value.', tags: ['Economic History', 'Early Economies'] },
  { q: 'Cowrie shells were used across Africa and Asia primarily as a form of:', opts: ['Commodity money', 'Jewelry only', 'Fishing bait', 'Writing material'], a: 0, e: 'Cowrie shells functioned as commodity money in many premodern trade networks.', tags: ['Economic History', 'Early Economies'] },
  { q: 'The ancient overland route linking China to the Mediterranean was known as the:', opts: ['Silk Road', 'Amber Road', 'Royal Road', 'Spice Isles'], a: 0, e: 'The Silk Road was a network of routes trading silk, spices, and ideas between East and West.', tags: ['Economic History', 'Early Economies'] },
  { q: 'In many early Mesopotamian economies, what institution often stored grain and managed redistribution?', opts: ['The temple', 'The stock exchange', 'The central bank', 'The guild'], a: 0, e: 'Temples in Mesopotamia acted as economic hubs, storing grain and redistributing resources.', tags: ['Economic History', 'Early Economies'] },

  // ── Level 2 — Medieval & Mercantile Economies ──
  { q: 'A medieval \'guild\' was primarily an association of:', opts: ['Craftsmen or merchants', 'Soldiers', 'Monks', 'Sailors only'], a: 0, e: 'Guilds were associations of artisans or merchants that regulated their trade in a town.', tags: ['Economic History', 'Medieval and Mercantile'] },
  { q: 'The medieval trading confederation of northern German towns was the:', opts: ['Hanseatic League', 'Delian League', 'Latin Union', 'Zollverein'], a: 0, e: 'The Hanseatic League dominated Baltic and North Sea trade in the late Middle Ages.', tags: ['Economic History', 'Medieval and Mercantile'] },
  { q: 'Mercantilism held that a nation\'s wealth was best measured by its stock of:', opts: ['Gold and silver', 'Farmland', 'Population', 'Warships'], a: 0, e: 'Mercantilists equated national wealth with accumulated bullion, favoring trade surpluses.', tags: ['Economic History', 'Medieval and Mercantile'] },
  { q: 'To build up bullion, mercantilist states typically aimed for a trade:', opts: ['Surplus (export more than import)', 'Deficit', 'Balance of exactly zero', 'Ban on all exports'], a: 0, e: 'Mercantilism sought a positive trade balance to accumulate precious metals.', tags: ['Economic History', 'Medieval and Mercantile'] },
  { q: 'A \'bill of exchange\' in medieval commerce functioned mainly as an instrument of:', opts: ['Credit and payment', 'Land ownership', 'Military command', 'Religious tithe'], a: 0, e: 'Bills of exchange let merchants transfer funds and extend credit across distances.', tags: ['Economic History', 'Medieval and Mercantile'] },
  { q: 'Renaissance Italian banking was pioneered by families such as the:', opts: ['Medici', 'Habsburg', 'Tudor', 'Bourbon'], a: 0, e: 'The Medici of Florence ran one of the most influential banks of the 15th century.', tags: ['Economic History', 'Medieval and Mercantile'] },
  { q: 'Chartered firms like the Dutch and English East India Companies were early examples of:', opts: ['Joint-stock companies', 'Labor unions', 'Central banks', 'Charities'], a: 0, e: 'Joint-stock companies pooled investor capital and spread risk in long-distance trade.', tags: ['Economic History', 'Medieval and Mercantile'] },
  { q: 'The \'Columbian Exchange\' refers to the transfer between the Old and New Worlds of:', opts: ['Crops, animals, and diseases', 'Only gold', 'Only slaves', 'Only textiles'], a: 0, e: 'The Columbian Exchange moved crops, livestock, people, and pathogens across the Atlantic.', tags: ['Economic History', 'Medieval and Mercantile'] },

  // ── Level 3 — Industrial Revolution & Rise of Capitalism ──
  { q: 'The Industrial Revolution began in the late 18th century primarily in:', opts: ['Britain', 'Japan', 'Russia', 'Brazil'], a: 0, e: 'Britain led the Industrial Revolution, aided by coal, capital, and colonial markets.', tags: ['Economic History', 'Industrial Revolution'] },
  { q: 'James Watt is best known for improving which power source?', opts: ['The steam engine', 'The waterwheel', 'The windmill', 'The electric motor'], a: 0, e: 'Watt\'s improved steam engine dramatically increased efficiency and powered industry.', tags: ['Economic History', 'Industrial Revolution'] },
  { q: 'The early Industrial Revolution transformed which industry first?', opts: ['Textiles', 'Aviation', 'Electronics', 'Petrochemicals'], a: 0, e: 'Mechanized spinning and weaving made textiles the first factory-based industry.', tags: ['Economic History', 'Industrial Revolution'] },
  { q: 'Adam Smith\'s 1776 work arguing for free markets was titled:', opts: ['The Wealth of Nations', 'Das Kapital', 'The General Theory', 'Principles of Economics'], a: 0, e: 'Smith\'s The Wealth of Nations laid foundations for classical economics and free trade.', tags: ['Economic History', 'Industrial Revolution'] },
  { q: 'Smith\'s metaphor for self-interest guiding markets to social benefit was the:', opts: ['Invisible hand', 'Iron law', 'Golden mean', 'Visible fist'], a: 0, e: 'The \'invisible hand\' describes how individual self-interest can yield collective benefit.', tags: ['Economic History', 'Industrial Revolution'] },
  { q: 'The \'factory system\' primarily changed production by:', opts: ['Concentrating workers and machines in one place', 'Ending wage labor', 'Abolishing money', 'Returning work to homes'], a: 0, e: 'Factories centralized labor and machinery, replacing dispersed cottage production.', tags: ['Economic History', 'Industrial Revolution'] },
  { q: 'The division of labor increases output mainly by raising:', opts: ['Worker specialization and productivity', 'Raw material prices', 'Transport distances', 'Interest rates'], a: 0, e: 'Splitting production into specialized tasks boosts skill and efficiency, raising output.', tags: ['Economic History', 'Industrial Revolution'] },
  { q: 'Which 19th-century transport innovation most lowered the cost of moving goods overland?', opts: ['Railways', 'Canals only', 'Hot-air balloons', 'Pipelines'], a: 0, e: 'Railways drastically cut overland freight costs and integrated national markets.', tags: ['Economic History', 'Industrial Revolution'] },

  // ── Level 4 — Money, Banking & Financial Systems ──
  { q: 'A \'central bank\' is chiefly responsible for:', opts: ['Managing money supply and monetary policy', 'Selling groceries', 'Building roads', 'Setting import quotas'], a: 0, e: 'Central banks control the money supply, set policy rates, and act as lenders of last resort.', tags: ['Economic History', 'Money and Banking'] },
  { q: 'Under a strict \'gold standard,\' a currency\'s value is fixed to:', opts: ['A set quantity of gold', 'The price of oil', 'Government decree alone', 'The stock market'], a: 0, e: 'The gold standard pegged currencies to gold, constraining money issuance.', tags: ['Economic History', 'Money and Banking'] },
  { q: 'The Bank of England, founded in 1694, is an early example of a:', opts: ['National central bank', 'Stock exchange', 'Insurance guild', 'Trade union'], a: 0, e: 'The Bank of England pioneered the model of a state-linked central bank managing public debt.', tags: ['Economic History', 'Money and Banking'] },
  { q: '\'Fractional-reserve banking\' means banks:', opts: ['Hold only part of deposits as reserves', 'Hold all deposits in a vault', 'Cannot make loans', 'Are owned by depositors'], a: 0, e: 'Banks keep a fraction of deposits in reserve and lend out the rest, expanding credit.', tags: ['Economic History', 'Money and Banking'] },
  { q: 'A \'bank run\' occurs when:', opts: ['Many depositors withdraw at once fearing insolvency', 'A bank opens new branches', 'Interest rates fall', 'Coins are recalled'], a: 0, e: 'A bank run is a rush of withdrawals that can exhaust reserves and topple a solvent-seeming bank.', tags: ['Economic History', 'Money and Banking'] },
  { q: 'The role of \'lender of last resort\' is typically played by the:', opts: ['Central bank', 'Treasury auction', 'Stock exchange', 'Chamber of commerce'], a: 0, e: 'Central banks lend to solvent but illiquid banks in crises to prevent panics from spreading.', tags: ['Economic History', 'Money and Banking'] },
  { q: 'The speculative Dutch \'Tulip Mania\' of the 1630s is often cited as an early:', opts: ['Asset-price bubble', 'Central bank', 'Trade treaty', 'Tax revolt'], a: 0, e: 'Tulip Mania saw bulb prices soar then collapse, an early example of a speculative bubble.', tags: ['Economic History', 'Money and Banking'] },
  { q: '\'Fiat money\' derives its value primarily from:', opts: ['Government decree and public trust', 'Its gold backing', 'Its silver content', 'Its usefulness as fuel'], a: 0, e: 'Fiat money has value by government declaration and confidence, not intrinsic commodity backing.', tags: ['Economic History', 'Money and Banking'] },

  // ── Level 5 — 20th-Century Economic History ──
  { q: 'The Great Depression is generally dated as beginning with the 1929:', opts: ['Wall Street stock market crash', 'Fall of the Berlin Wall', 'OPEC oil embargo', 'Bretton Woods conference'], a: 0, e: 'The October 1929 crash preceded the worst economic downturn of the 20th century.', tags: ['Economic History', '20th-Century Economics'] },
  { q: 'Keynesian economics argued that in a depression governments should:', opts: ['Increase spending to boost demand', 'Cut all spending', 'Raise the gold price', 'Abolish central banks'], a: 0, e: 'Keynes urged deficit spending to raise aggregate demand and reduce unemployment.', tags: ['Economic History', '20th-Century Economics'] },
  { q: 'The 1944 Bretton Woods system pegged major currencies to the:', opts: ['US dollar (convertible to gold)', 'British pound', 'Japanese yen', 'Swiss franc'], a: 0, e: 'Bretton Woods fixed currencies to the dollar, which was convertible to gold at $35 an ounce.', tags: ['Economic History', '20th-Century Economics'] },
  { q: 'Which institutions were created at Bretton Woods in 1944?', opts: ['The IMF and World Bank', 'NATO and the UN', 'OPEC and the WTO', 'The EU and ECB'], a: 0, e: 'Bretton Woods established the International Monetary Fund and the World Bank.', tags: ['Economic History', '20th-Century Economics'] },
  { q: 'The Bretton Woods gold-convertibility system effectively ended in 1971 when the US:', opts: ['Suspended dollar-gold convertibility', 'Joined the euro', 'Adopted a gold standard', 'Banned trade'], a: 0, e: 'President Nixon suspended dollar-gold convertibility in 1971, ending the fixed system.', tags: ['Economic History', '20th-Century Economics'] },
  { q: '\'Stagflation\' in the 1970s combined high inflation with:', opts: ['High unemployment and stagnant growth', 'Rapid growth', 'Falling prices', 'Full employment'], a: 0, e: 'Stagflation paired stagnant output and high unemployment with high inflation, defying simple Keynesian models.', tags: ['Economic History', '20th-Century Economics'] },
  { q: 'Post-1980 \'globalization\' is characterized above all by rising:', opts: ['Cross-border trade and capital flows', 'National self-sufficiency', 'Barter economies', 'Guild monopolies'], a: 0, e: 'Globalization featured expanding international trade, investment, and integrated supply chains.', tags: ['Economic History', '20th-Century Economics'] },
  { q: 'Milton Friedman\'s \'monetarism\' stressed controlling inflation by managing the:', opts: ['Money supply', 'Tariff schedule', 'Minimum wage', 'Exchange of grain'], a: 0, e: 'Monetarists argued that inflation is chiefly driven by growth in the money supply.', tags: ['Economic History', '20th-Century Economics'] },
];
