import type { Seed } from './roadmap-build';

// "Cool Stuff" learning path — 120 questions (15 levels × 8) of fun, verifiable
// facts and lore from the dev world: JavaScript quirks, the birth of the Web,
// famous firsts, legendary bugs and disasters, viruses, pioneers, naming stories,
// esoteric languages, mascots, hardware oddities, gaming Easter eggs and assorted
// tech myths. Facts were researched/verified from public sources (Wikipedia,
// CERN, Computer History Museum, the Smithsonian, RFCs, etc.). Built via
// buildRoadmap (ids rm-cool-1 … rm-cool-120, 8 per level).
export const coolStuffSeeds: Seed[] = [
  // Level 1 — JavaScript: Birth & Names
  { q: "Who created JavaScript?", opts: ["James Gosling", "Brendan Eich", "Linus Torvalds", "Tim Berners-Lee"], a: 1, e: "Brendan Eich created JavaScript at Netscape in 1995. James Gosling made Java, Torvalds made Linux/Git, and Berners-Lee invented the Web.", tags: ["JavaScript", "history"], intro: "Some genuinely cool dev-world trivia ahead — let's begin with JavaScript." },
  { q: "Roughly how long did Brendan Eich take to build the first JavaScript prototype?", opts: ["About 10 days", "About 10 weeks", "About 10 months", "About 10 years"], a: 0, e: "The first prototype was famously hacked together in about ten days in May 1995 — which is why JavaScript has so many quirks.", tags: ["JavaScript", "history"] },
  { q: "What was JavaScript's original internal codename?", opts: ["Oak", "Mocha", "Coffee", "Ember"], a: 1, e: "It was first called Mocha, then shipped briefly as LiveScript, before being renamed JavaScript.", tags: ["JavaScript", "naming"] },
  { q: "Just before it was called 'JavaScript', the language shipped under which name?", opts: ["Mocha", "LiveScript", "JScript", "ECMAScript"], a: 1, e: "It shipped as LiveScript in a Netscape Navigator 2.0 beta (1995) before the marketing rename to JavaScript.", tags: ["JavaScript", "naming"] },
  { q: "Why was the language renamed 'JavaScript'?", opts: ["It was written in Java", "A marketing tie-in with the then-hot Java, despite being unrelated", "It runs on the Java Virtual Machine", "Java's team built it"], a: 1, e: "Netscape renamed it to ride Java's popularity (a Sun partnership). The two languages are otherwise largely unrelated.", tags: ["JavaScript", "naming"] },
  { q: "What is the relationship between Java and JavaScript?", opts: ["JavaScript is a version of Java", "They are essentially unrelated languages with a similar name", "Java compiles to JavaScript", "They are the same language"], a: 1, e: "As the saying goes, Java and JavaScript are alike as car and carpet — the shared name was marketing, not lineage.", tags: ["JavaScript", "myth"] },
  { q: "What is the official standardized name for the JavaScript language?", opts: ["ECMAScript", "JavaSE", "HTMLScript", "W3Script"], a: 0, e: "The language standard is ECMAScript (maintained by Ecma International); 'JavaScript' is the popular name for it.", tags: ["JavaScript", "standards"] },
  { q: "At which company was JavaScript created?", opts: ["Sun Microsystems", "Microsoft", "Netscape", "Google"], a: 2, e: "Brendan Eich created it at Netscape Communications for the Navigator browser.", tags: ["JavaScript", "history"] },

  // Level 2 — JavaScript: Weird Parts
  { q: "What does typeof null return in JavaScript?", opts: ["'null'", "'object'", "'undefined'", "'boolean'"], a: 1, e: "typeof null is 'object' — a long-standing bug kept for backward compatibility.", tags: ["JavaScript", "quirks"] },
  { q: "Why does typeof null return 'object'?", opts: ["null is technically an empty object", "An early implementation tagged values by type, and null shared the tag (0) used for objects", "The spec defines null as an object", "It is a documentation typo"], a: 1, e: "In the original engine, values had a type tag; objects were tag 0 and null was the null pointer (also 0), so it read as 'object'.", tags: ["JavaScript", "quirks"] },
  { q: "In JavaScript, what does 0.1 + 0.2 evaluate to?", opts: ["Exactly 0.3", "0.30000000000000004", "NaN", "It throws an error"], a: 1, e: "Floating-point (IEEE 754) can't represent 0.1 and 0.2 exactly, so the sum is 0.30000000000000004 — not strictly 0.3.", tags: ["JavaScript", "numbers"] },
  { q: "What is the result of NaN === NaN?", opts: ["true", "false", "It throws", "undefined"], a: 1, e: "NaN is the only value not equal to itself; NaN === NaN is false. Use Number.isNaN() to test for it.", tags: ["JavaScript", "numbers"] },
  { q: "What does typeof NaN return?", opts: ["'number'", "'NaN'", "'undefined'", "'object'"], a: 0, e: "NaN ('Not a Number') is, paradoxically, of type 'number'.", tags: ["JavaScript", "numbers"] },
  { q: "Is an empty array [] truthy or falsy in JavaScript?", opts: ["Truthy", "Falsy", "It throws", "Depends on its length"], a: 0, e: "Empty arrays (and empty objects) are truthy. Only a fixed set of values — false, 0, '', null, undefined, NaN — are falsy.", tags: ["JavaScript", "quirks"] },
  { q: "What does the loose equality operator == do that strict === does not?", opts: ["Compares object references", "Performs type coercion before comparing", "Runs faster", "Handles NaN correctly"], a: 1, e: "== coerces operands to a common type before comparing (so 1 == '1' is true); === compares without coercion.", tags: ["JavaScript", "operators"] },
  { q: "By default, JavaScript's Array sort() compares elements as what?", opts: ["Numbers, ascending", "Strings (lexicographically)", "Randomly", "By length"], a: 1, e: "Default sort converts items to strings, so [1, 2, 10].sort() gives [1, 10, 2]. Pass a comparator for numeric order.", tags: ["JavaScript", "arrays"] },

  // Level 3 — Birth of the Web
  { q: "Who invented the World Wide Web?", opts: ["Vint Cerf", "Tim Berners-Lee", "Bill Gates", "Marc Andreessen"], a: 1, e: "Tim Berners-Lee invented the Web at CERN around 1989–1991. Vint Cerf is a 'father of the Internet' — a different thing.", tags: ["web", "history"] },
  { q: "The world's first website ran on what kind of computer at CERN?", opts: ["An IBM PC", "A NeXT computer", "An Apple Macintosh", "A Cray supercomputer"], a: 1, e: "The first web server ran on a NeXT machine; a note on it reportedly warned people not to power it off.", tags: ["web", "history"] },
  { q: "What was the address of the world's first website?", opts: ["www.w3.org", "info.cern.ch", "web.cern.org", "the.first.web"], a: 1, e: "info.cern.ch hosted the first website, describing the World Wide Web project itself.", tags: ["web", "firsts"] },
  { q: "How are 'the Web' and 'the Internet' related?", opts: ["They are the same thing", "The Web is a service that runs on top of the Internet", "The Internet runs on top of the Web", "They are completely unrelated"], a: 1, e: "The Internet is the global network; the Web (sites, links, HTTP) is one of many things built on top of it.", tags: ["web", "concepts"] },
  { q: "What was the name of the first web browser, written by Berners-Lee?", opts: ["Mosaic", "WorldWideWeb", "Netscape", "Lynx"], a: 1, e: "The first browser was called WorldWideWeb (later renamed Nexus to avoid confusion with the Web itself).", tags: ["web", "browsers"] },
  { q: "Which non-standard tag, introduced by Netscape, made text flash on and off?", opts: ["<flash>", "<blink>", "<strobe>", "<marquee>"], a: 1, e: "The infamous <blink> tag made text blink; it's widely reviled and effectively obsolete.", tags: ["web", "HTML"] },
  { q: "Which non-standard tag (popularized by Internet Explorer) scrolled text across the page?", opts: ["<marquee>", "<scroll>", "<ticker>", "<blink>"], a: 0, e: "<marquee> scrolled content across the screen — a hallmark of 1990s web pages, now obsolete.", tags: ["web", "HTML"] },
  { q: "What does 'HTML' stand for?", opts: ["HyperText Markup Language", "High-level Text Machine Language", "Hyperlink Text Management Logic", "Home Tool Markup Language"], a: 0, e: "HTML is HyperText Markup Language — the markup that structures web pages.", tags: ["web", "HTML"] },

  // Level 4 — Internet Firsts
  { q: "What was the first registered .com domain name?", opts: ["apple.com", "symbolics.com", "ibm.com", "mit.com"], a: 1, e: "symbolics.com was registered on 15 March 1985 by computer maker Symbolics, Inc.", tags: ["web", "firsts"] },
  { q: "The world's first webcam was set up to watch what?", opts: ["A parking lot", "A coffee pot", "A server room", "A fish tank"], a: 1, e: "Cambridge researchers pointed a camera at the 'Trojan Room' coffee pot so they'd know if it was empty before walking over.", tags: ["web", "firsts"] },
  { q: "The web's first banner ad (1994, for AT&T) asked: 'Have you ever clicked your mouse right HERE? ___'", opts: ["You will.", "Buy now.", "Click me.", "Win big."], a: 0, e: "AT&T's 1994 banner on HotWired read 'You will.' — widely cited as the first web banner ad.", tags: ["web", "firsts"] },
  { q: "What did the very first tweet say?", opts: ["Hello world", "just setting up my twttr", "First!", "Twitter is live"], a: 1, e: "Co-founder Jack Dorsey posted 'just setting up my twttr' in 2006.", tags: ["web", "firsts"] },
  { q: "What was the title of the first video uploaded to YouTube?", opts: ["Charlie bit my finger", "Me at the zoo", "Gangnam Style", "First video"], a: 1, e: "'Me at the zoo' (2005), a 19-second clip of co-founder Jawed Karim at the San Diego Zoo, was YouTube's first upload.", tags: ["web", "firsts"] },
  { q: "Who sent the first networked email and chose the '@' sign for addresses (1971)?", opts: ["Vint Cerf", "Ray Tomlinson", "Tim Berners-Lee", "Gary Thuerk"], a: 1, e: "Ray Tomlinson sent the first email across a network and picked '@' to separate the user from the host machine.", tags: ["web", "firsts"] },
  { q: "Why did Ray Tomlinson pick the '@' symbol for email addresses?", opts: ["It was the first key on the keyboard", "It naturally meant 'user AT host' and was otherwise unused", "It stood for 'address'", "He chose it at random"], a: 1, e: "'@' conveniently read as 'at' (user at host) and wasn't used in names, avoiding ambiguity.", tags: ["web", "email"] },
  { q: "The first computer virus/worm, which printed 'I'M THE CREEPER...', was named?", opts: ["Reaper", "Creeper", "ILOVEYOU", "Morris"], a: 1, e: "Creeper (1971) was an experimental self-replicating program; the program written to delete it was called Reaper.", tags: ["security", "firsts"] },

  // Level 5 — Famous Software Disasters
  { q: "The 1996 Ariane 5 rocket self-destructed because of what software fault?", opts: ["A typo in a comment", "A 64-bit float converted into a too-small 16-bit integer (overflow)", "A dead backup battery", "A network outage"], a: 1, e: "Reused Ariane 4 code tried to fit a 64-bit floating value into a 16-bit integer; the overflow crashed the guidance system.", tags: ["bugs", "space"] },
  { q: "NASA's 1999 Mars Climate Orbiter was lost due to what mistake?", opts: ["A cracked lens", "A mix-up between metric and imperial units", "A solar flare", "A fuel leak"], a: 1, e: "One team used pound-force seconds while another expected newton-seconds, so the orbiter approached Mars at the wrong altitude.", tags: ["bugs", "space"] },
  { q: "A 2012 trading-software bug made Knight Capital lose about $440 million in roughly how long?", opts: ["A full year", "About 45 minutes", "A week", "One second"], a: 1, e: "A misconfigured deployment triggered runaway trades, losing ~$440M in about 45 minutes and nearly bankrupting the firm.", tags: ["bugs", "finance"] },
  { q: "The 1994 Intel 'FDIV' bug was an error in which operation?", opts: ["Memory addressing", "Floating-point division", "The system clock", "Integer addition"], a: 1, e: "The Pentium's floating-point division could return slightly wrong results, leading to a costly recall.", tags: ["bugs", "hardware"] },
  { q: "The Therac-25's software bug caused what tragic outcome?", opts: ["Overheating", "Lethal radiation overdoses to patients", "Loss of data", "Screen flicker"], a: 1, e: "Race conditions in the Therac-25 radiation machine delivered massive overdoses, injuring and killing patients (1985–87).", tags: ["bugs", "safety"] },
  { q: "In 2016, un-publishing a tiny (~11-line) npm package broke builds across the internet. Which package?", opts: ["lodash", "left-pad", "jquery", "is-odd"], a: 1, e: "left-pad padded strings; its removal cascaded through dependencies (Babel, React and more), breaking countless builds.", tags: ["bugs", "javascript"] },
  { q: "The 'Y2K' problem was the fear that computers would mishandle dates because they stored years how?", opts: ["With only two digits", "As random numbers", "In binary only", "Without time zones"], a: 0, e: "Storing years as two digits (e.g. '99') risked rolling over to 1900 instead of 2000 — prompting a huge global fix effort.", tags: ["bugs", "history"] },
  { q: "The 'Year 2038 problem' threatens systems that store time as what?", opts: ["A two-digit year", "A 32-bit signed integer of seconds since 1970", "A floating-point number", "A text string"], a: 1, e: "A signed 32-bit Unix timestamp overflows on 19 January 2038; systems must move to 64-bit time.", tags: ["bugs", "time"] },

  // Level 6 — The Original "Bug"
  { q: "The famous 1947 'first actual case of a bug' taped into a logbook was literally what?", opts: ["A beetle", "A moth", "A spider", "A worm"], a: 1, e: "A moth was found in a relay of the Harvard Mark II and taped into the log with that caption.", tags: ["bugs", "history"] },
  { q: "In which machine was the 1947 moth found?", opts: ["ENIAC", "The Harvard Mark II", "UNIVAC", "The Altair 8800"], a: 1, e: "Operators found the moth jammed in a relay of the Harvard Mark II electromechanical computer.", tags: ["bugs", "history"] },
  { q: "Which computing pioneer is most associated with popularizing 'bug' and 'debugging' after the moth incident?", opts: ["Ada Lovelace", "Grace Hopper", "Alan Turing", "Steve Wozniak"], a: 1, e: "Grace Hopper and the Mark II team helped popularize the terms, though they didn't invent the word 'bug'.", tags: ["bugs", "people"] },
  { q: "The term 'bug' for a technical fault actually predates 1947 — who used it decades earlier?", opts: ["Thomas Edison", "Charles Babbage", "Nikola Tesla", "Henry Ford"], a: 0, e: "Thomas Edison used 'bug' for technical faults in the 1870s–80s, so the moth was a playful 'first actual' bug.", tags: ["bugs", "etymology"] },
  { q: "Where is the logbook with the actual taped-in moth preserved today?", opts: ["At CERN", "At the Smithsonian", "At MIT", "At Google HQ"], a: 1, e: "The page with the moth is held by the Smithsonian's National Museum of American History.", tags: ["bugs", "history"] },
  { q: "What is 'rubber duck debugging'?", opts: ["A load-testing tool", "Explaining your code aloud, line by line, to an object until you spot the bug", "A type of CAPTCHA", "A waterproof keyboard"], a: 1, e: "Articulating the problem to a 'rubber duck' often reveals the flaw — the listener needn't understand a word.", tags: ["debugging", "culture"] },
  { q: "What is a 'heisenbug'?", opts: ["A bug that changes or disappears when you try to observe it", "A bug in a page heading", "A bug that corrupts memory", "A bug only on Heisenberg's PC"], a: 0, e: "Named after the uncertainty principle, a heisenbug seems to vanish under a debugger or extra logging.", tags: ["debugging", "culture"] },
  { q: "The logbook caption said 'first actual case of a bug being found.' What does 'actual' imply?", opts: ["It was the first bug ever in history", "'Bug' was already slang for a fault, so finding a real insect was the joke", "The computer was acting", "Nothing in particular"], a: 1, e: "Because engineers already called faults 'bugs', a literal insect was humorously the 'first actual' one.", tags: ["bugs", "etymology"] },

  // Level 7 — Worms, Viruses & Spam
  { q: "Creeper (1971), often called the first virus/worm, was written by whom?", opts: ["Robert Tappan Morris", "Bob Thomas", "Kevin Mitnick", "John McAfee"], a: 1, e: "Bob Thomas wrote Creeper at BBN as a harmless experiment in self-replicating programs.", tags: ["security", "history"] },
  { q: "What program was created specifically to remove Creeper?", opts: ["Cleaner", "Reaper", "Norton", "Defender"], a: 1, e: "Reaper roamed the network deleting Creeper — arguably the first antivirus.", tags: ["security", "history"] },
  { q: "The 1988 'Morris Worm', one of the first internet worms, was created by?", opts: ["Bob Thomas", "Robert Tappan Morris", "Gary Thuerk", "Linus Torvalds"], a: 1, e: "Robert Tappan Morris released it in 1988; it spread far wider than intended and led to the first CFAA conviction.", tags: ["security", "history"] },
  { q: "The first commercial spam email (1978) was sent by Gary Thuerk over which network?", opts: ["The World Wide Web", "ARPANET", "AOL", "SMS"], a: 1, e: "Thuerk emailed a DEC product pitch to hundreds of ARPANET users in 1978 — the first email spam.", tags: ["security", "firsts"] },
  { q: "The term 'spam' for unwanted messages comes from where?", opts: ["An acronym for junk mail", "A Monty Python comedy sketch", "A computer virus", "A programmer's surname"], a: 1, e: "It comes from the Monty Python sketch where 'spam' is repeated endlessly, drowning everything out.", tags: ["security", "culture"] },
  { q: "What message did Creeper display on infected machines?", opts: ["'ALL YOUR BASE ARE BELONG TO US'", "'I'M THE CREEPER : CATCH ME IF YOU CAN'", "'Hello, World'", "'Gotcha!'"], a: 1, e: "Creeper printed 'I'M THE CREEPER : CATCH ME IF YOU CAN' as it hopped between machines.", tags: ["security", "history"] },
  { q: "The year-2000 'ILOVEYOU' outbreak spread mainly through what?", opts: ["Email attachments", "USB sticks", "Bluetooth", "Floppy disks"], a: 0, e: "The ILOVEYOU worm arrived as a 'love letter' email attachment (a VBScript) and spread explosively.", tags: ["security", "history"] },
  { q: "In its original 1960s MIT sense, a 'hacker' meant what?", opts: ["A bank robber", "A clever, playful technical tinkerer", "A type of virus", "A fast typist"], a: 1, e: "Originally 'hacker' praised ingenious tinkering; the criminal sense came much later in popular usage.", tags: ["security", "culture"] },

  // Level 8 — Programming Pioneers
  { q: "Who is often called the first computer programmer?", opts: ["Grace Hopper", "Ada Lovelace", "Margaret Hamilton", "Alan Turing"], a: 1, e: "Ada Lovelace, in the 1840s, wrote what's considered the first algorithm intended for a machine.", tags: ["people", "history"] },
  { q: "Ada Lovelace's famous algorithm was written for which of Charles Babbage's machines?", opts: ["The Difference Engine", "The Analytical Engine", "ENIAC", "The Turing machine"], a: 1, e: "Her notes on the (never-built) programmable Analytical Engine included an algorithm to compute Bernoulli numbers.", tags: ["people", "history"] },
  { q: "The first programmers of the ENIAC computer were predominantly who?", opts: ["Women", "Soldiers", "Teenagers", "University professors"], a: 0, e: "Six women — including Jean Bartik and Kay McNulty — programmed ENIAC, often unrecognized for decades.", tags: ["people", "history"] },
  { q: "Before electronic machines, the word 'computer' referred to what?", opts: ["A person who performs calculations", "A typewriter", "An abacus", "A robot"], a: 0, e: "'Computer' was a job title for a human (often a woman) doing calculations by hand.", tags: ["people", "etymology"] },
  { q: "Grace Hopper was instrumental in creating which business programming language?", opts: ["FORTRAN", "COBOL", "LISP", "BASIC"], a: 1, e: "Hopper championed machine-independent languages and helped create COBOL; she also built an early compiler.", tags: ["people", "languages"] },
  { q: "The 'Turing test', proposed by Alan Turing, measures what?", opts: ["A CPU's speed", "Whether a machine's responses are indistinguishable from a human's", "A program's memory use", "Code quality"], a: 1, e: "If a human can't reliably tell the machine from a person in conversation, it passes the Turing test.", tags: ["people", "AI"] },
  { q: "Dennis Ritchie created the C language and co-created which operating system?", opts: ["Windows", "Unix", "Linux", "macOS"], a: 1, e: "At Bell Labs, Ritchie created C and co-created Unix with Ken Thompson — foundations of modern computing.", tags: ["people", "languages"] },
  { q: "Edsger Dijkstra's famous 1968 essay declared which statement 'considered harmful'?", opts: ["GOTO", "IF", "WHILE", "RETURN"], a: 0, e: "'Go To Statement Considered Harmful' argued against goto in favor of structured programming.", tags: ["people", "languages"] },

  // Level 9 — Language Naming & Lore
  { q: "Java was originally named what, after a tree outside the office?", opts: ["Oak", "Green", "Bean", "Latte"], a: 0, e: "Java started as 'Oak' (a tree outside James Gosling's office) and was renamed Java after the coffee.", tags: ["languages", "naming"] },
  { q: "The Python language is named after what?", opts: ["The snake", "Monty Python's Flying Circus", "A Greek myth", "An acronym"], a: 1, e: "Guido van Rossum named it after the British comedy troupe Monty Python — not the reptile.", tags: ["languages", "naming"] },
  { q: "'Google' is a misspelling of which mathematical term?", opts: ["googol", "goggle", "googly", "gogol"], a: 0, e: "A googol is 10^100; the company name is a (now-iconic) misspelling of it.", tags: ["companies", "naming"] },
  { q: "According to Linus Torvalds, 'git' is partly named because it's British slang for what?", opts: ["Fast", "An unpleasant person", "A tracker", "Global"], a: 1, e: "Torvalds joked he names projects after himself; 'git' is British slang for an annoying person. (Its man page calls it 'the stupid content tracker'.)", tags: ["tools", "naming"] },
  { q: "The C programming language was derived from an earlier language called what?", opts: ["A", "B", "D", "C++"], a: 1, e: "C evolved from a language called B (itself influenced by BCPL) at Bell Labs.", tags: ["languages", "naming"] },
  { q: "'GNU' is a recursive acronym standing for what?", opts: ["GNU's Not Unix", "General New Unix", "Great Networked Utility", "Grand Nix Unit"], a: 0, e: "GNU famously stands for 'GNU's Not Unix' — a recursive acronym that refers to itself.", tags: ["software", "naming"] },
  { q: "Today, 'PHP' is a recursive acronym for what (it began as 'Personal Home Page')?", opts: ["PHP: Hypertext Preprocessor", "Private Hosting Protocol", "Pre-Hyper Processor", "Public HTML Parser"], a: 0, e: "PHP now stands for the recursive 'PHP: Hypertext Preprocessor'.", tags: ["languages", "naming"] },
  { q: "In Python, the traditional placeholder variable names are often what (a Monty Python nod)?", opts: ["foo and bar", "spam and eggs", "cat and dog", "alice and bob"], a: 1, e: "Python docs favor 'spam' and 'eggs' (from a Monty Python sketch) over the usual 'foo' and 'bar'.", tags: ["languages", "culture"] },

  // Level 10 — Esoteric Languages
  { q: "The esoteric language Brainfuck is famous for having only how many commands?", opts: ["8", "26", "1", "100"], a: 0, e: "Brainfuck has just 8 single-character commands, designed for the smallest possible compiler.", tags: ["esolang", "trivia"] },
  { q: "The language 'Whitespace' is unusual because the only meaningful characters are what?", opts: ["Emojis", "Spaces, tabs, and line breaks", "Numbers", "Brackets"], a: 1, e: "Whitespace ignores everything except spaces, tabs and newlines — so programs can hide inside other text.", tags: ["esolang", "trivia"] },
  { q: "INTERCAL (1972) was created mainly as what?", opts: ["A NASA flight language", "A parody of other programming languages", "A database language", "A typing tutor"], a: 1, e: "INTERCAL was a deliberate joke; its name is 'Compiler Language With No Pronounceable Acronym'.", tags: ["esolang", "history"] },
  { q: "A LOLCODE program begins with which keyword?", opts: ["START", "HAI", "BEGIN", "MAIN"], a: 1, e: "LOLCODE programs open with 'HAI' and close with 'KTHXBYE', mimicking lolcat-speak.", tags: ["esolang", "trivia"] },
  { q: "INTERCAL famously expects you to be polite by using which keyword the right amount?", opts: ["SORRY", "PLEASE", "THANKS", "HELLO"], a: 1, e: "INTERCAL complains if you use 'PLEASE' too rarely (rude) or too often (overly polite).", tags: ["esolang", "trivia"] },
  { q: "Brainfuck's creator, Urban Müller, designed it with what goal?", opts: ["The fastest runtime", "The smallest possible compiler", "The easiest syntax", "The best graphics"], a: 1, e: "The aim was a language with the tiniest possible compiler — readability was never the point.", tags: ["esolang", "history"] },
  { q: "What is the general term for joke or experimental languages like Brainfuck and LOLCODE?", opts: ["Legacy languages", "Esoteric languages (esolangs)", "Assembly languages", "Scripting languages"], a: 1, e: "They're called esoteric languages, or 'esolangs' — built for fun, art, or to prove a point, not for production.", tags: ["esolang", "concepts"] },
  { q: "LOLCODE's syntax is styled after what?", opts: ["Latin", "The 'lolcat' meme / broken-English speak", "Pure emoji", "Binary"], a: 1, e: "LOLCODE imitates the lolcat internet meme, with keywords like 'I HAS A' and 'VISIBLE'.", tags: ["esolang", "culture"] },

  // Level 11 — Mascots, Logos & Symbols
  { q: "The Linux mascot is a penguin named what?", opts: ["Beastie", "Tux", "Gopher", "Ducky"], a: 1, e: "Tux the penguin is Linux's mascot; Linus Torvalds is fond of penguins.", tags: ["mascots", "linux"] },
  { q: "'Tux', the Linux penguin, is commonly said to stand for what?", opts: ["Tuxedo", "Torvalds Unix", "The Ultimate eXperience", "Nothing at all"], a: 1, e: "A popular backronym reads Tux as (T)orvalds (U)ni(X), though it also evokes a penguin's tuxedo look.", tags: ["mascots", "linux"] },
  { q: "Bluetooth is named after a 10th-century Scandinavian king, Harald 'Bluetooth', because he what?", opts: ["Invented radio", "United warring tribes (as Bluetooth unites devices)", "Had a blue tooth implant", "Founded Ericsson"], a: 1, e: "King Harald united Danish tribes; the tech unites devices, so his nickname was borrowed.", tags: ["naming", "hardware"] },
  { q: "The Bluetooth logo is a bind rune of which initials?", opts: ["B and T", "Harald Bluetooth's initials, H and B", "The letters B-T", "A tooth and a wave"], a: 1, e: "It merges the Younger Futhark runes for H and B — Harald Bluetooth's initials.", tags: ["naming", "hardware"] },
  { q: "Despite popular belief, 'Wi-Fi' officially stands for what?", opts: ["Wireless Fidelity", "Nothing — it isn't an acronym", "Wide Frequency", "Wireless Fast Internet"], a: 1, e: "'Wi-Fi' is just a catchy brand name (echoing Hi-Fi); it was never an abbreviation for 'Wireless Fidelity'.", tags: ["naming", "myth"] },
  { q: "GitHub's mascot is a cat-octopus hybrid called what?", opts: ["Gitty", "The Octocat", "Hubcat", "Tux"], a: 1, e: "GitHub's mascot is the Octocat (named Mona Lisa / 'Monalisa Octocat').", tags: ["mascots", "tools"] },
  { q: "Docker's mascot is a whale named what?", opts: ["Willy", "Moby Dock", "Flipper", "Bubbles"], a: 1, e: "Docker's whale (carrying containers) is named Moby Dock — a nod to Moby-Dick.", tags: ["mascots", "tools"] },
  { q: "The placeholder names 'foo' and 'bar' are widely thought to derive from which military slang?", opts: ["RADAR", "FUBAR", "SONAR", "AWOL"], a: 1, e: "'foobar' likely comes from the WWII slang FUBAR; foo and bar are the classic metasyntactic variables.", tags: ["culture", "etymology"] },

  // Level 12 — Hardware Marvels & Oddities
  { q: "IBM's first hard drive (the RAMAC, 1956) weighed roughly how much?", opts: ["A few grams", "About a ton", "About 10 kg", "About 1 kg"], a: 1, e: "The RAMAC weighed about a ton and was moved with forklifts and shipped on cargo planes.", tags: ["hardware", "history"] },
  { q: "Approximately how much data could that first IBM RAMAC hard drive store?", opts: ["About 5 megabytes", "About 5 gigabytes", "About 5 terabytes", "About 500 megabytes"], a: 0, e: "It stored about 5 MB across fifty 24-inch spinning platters — a fortune of storage at the time.", tags: ["hardware", "history"] },
  { q: "The first computer mouse, built by Douglas Engelbart in the 1960s, was made of what?", opts: ["Aluminum", "Wood", "Plastic", "Glass"], a: 1, e: "Engelbart's prototype mouse had a carved wooden shell and one button; the cord looked like a tail.", tags: ["hardware", "history"] },
  { q: "The Apollo Guidance Computer that helped land humans on the Moon had memory measured in what?", opts: ["Kilobytes", "Gigabytes", "Terabytes", "Petabytes"], a: 0, e: "The AGC had only a few kilobytes of RAM and tens of KB of ROM — far less than a modern phone.", tags: ["hardware", "space"] },
  { q: "'Moore's Law' observes that the number of transistors on a chip roughly does what?", opts: ["Halves every year", "Doubles about every two years", "Stays constant", "Triples every month"], a: 1, e: "Gordon Moore noted transistor counts roughly double about every two years — a decades-long trend.", tags: ["hardware", "concepts"] },
  { q: "Nintendo was founded in 1889 originally making what?", opts: ["Video games", "Playing cards", "Televisions", "Toy robots"], a: 1, e: "Nintendo began as a maker of hanafuda playing cards, decades before video games existed.", tags: ["companies", "history"] },
  { q: "In most software, the 'Save' icon depicts what increasingly unfamiliar object?", opts: ["A hard drive", "A floppy disk", "A CD", "A cloud"], a: 1, e: "The save icon is a 3.5-inch floppy disk — an object many users have never physically seen.", tags: ["hardware", "culture"] },
  { q: "The ENIAC (1940s) did its calculations using thousands of what?", opts: ["Transistors", "Vacuum tubes", "Microchips", "Mechanical gears"], a: 1, e: "ENIAC used around 18,000 vacuum tubes, which burned out frequently and generated enormous heat.", tags: ["hardware", "history"] },

  // Level 13 — Gaming & Easter Eggs
  { q: "The 'Konami Code' (up up down down left right left right B A) first appeared in which game?", opts: ["Contra", "Gradius", "Super Mario Bros.", "Tetris"], a: 1, e: "It debuted in Gradius (1985); it later became legendary through Contra.", tags: ["gaming", "trivia"] },
  { q: "Why did the programmer originally add the Konami Code?", opts: ["To hide his name", "To make the game easier while testing/debugging it", "To cheat in tournaments", "To unlock advertisements"], a: 1, e: "Kazuhisa Hashimoto added it to survive while testing, then forgot to remove it before release.", tags: ["gaming", "trivia"] },
  { q: "One of the first video-game Easter eggs was a hidden room secretly crediting whom?", opts: ["Shigeru Miyamoto", "Warren Robinett", "Steve Jobs", "The Atari CEO"], a: 1, e: "Robinett hid 'Created by Warren Robinett' inside Atari's Adventure — an early, iconic Easter egg.", tags: ["gaming", "history"] },
  { q: "Why did Warren Robinett hide his name in the game?", opts: ["He was bored", "Atari didn't publicly credit its game programmers", "It was a contest", "For legal reasons"], a: 1, e: "Atari withheld individual credit, so Robinett snuck his name in as quiet protest.", tags: ["gaming", "history"] },
  { q: "'Spacewar!' (1962), one of the earliest video games, ran on which computer?", opts: ["A Game Boy", "A DEC PDP-1", "An Atari 2600", "An IBM PC"], a: 1, e: "Spacewar! was developed by MIT students on the DEC PDP-1 minicomputer.", tags: ["gaming", "history"] },
  { q: "Tetris was created in 1984 by Alexey Pajitnov in which country?", opts: ["Japan", "The Soviet Union", "The United States", "The United Kingdom"], a: 1, e: "Pajitnov created Tetris while working at a computing center in Soviet Moscow.", tags: ["gaming", "history"] },
  { q: "In 1983, Atari secretly buried millions of unsold cartridges (like E.T.) where?", opts: ["In the ocean", "In a New Mexico landfill", "In a volcano", "In a museum"], a: 1, e: "Atari buried cartridges in a New Mexico landfill — long a legend until it was excavated in 2014.", tags: ["gaming", "history"] },
  { q: "The original arcade Pac-Man has a famous 'kill screen' at which level?", opts: ["Level 100", "Level 256", "Level 999", "Level 1"], a: 1, e: "An 8-bit counter overflow corrupts level 256, making it unplayable — the classic Pac-Man kill screen.", tags: ["gaming", "bugs"] },

  // Level 14 — Bizarre Tech Tales
  { q: "What does HTTP status code 418 mean?", opts: ["Server on fire", "I'm a teapot", "Coffee ready", "Not found"], a: 1, e: "418 'I'm a teapot' comes from a 1998 April Fools' RFC for a (joke) Hyper Text Coffee Pot Control Protocol.", tags: ["web", "humor"] },
  { q: "In a famous sysadmin story, a user complained they couldn't send email farther than about how far?", opts: ["5 miles", "500 miles", "5,000 miles", "The next room"], a: 1, e: "The legendary 'case of the 500-mile email' described mail mysteriously failing beyond ~500 miles.", tags: ["web", "legend"] },
  { q: "What actually caused the '500-mile email' problem?", opts: ["A cable that was physically too long", "A timeout so short only nearby servers could reply in time", "Gravity", "A distance-based firewall"], a: 1, e: "A botched config set the connect timeout to a few milliseconds; light/round-trips limited replies to roughly 500 miles.", tags: ["web", "legend"] },
  { q: "The story that NASA spent millions on a 'space pen' while the Soviets just used pencils is?", opts: ["Completely true", "Mostly false — the pen was privately developed by Fisher", "About banning ballpoints", "About anti-gravity ink"], a: 1, e: "The Fisher Space Pen was privately funded; NASA later bought them cheaply. The 'millions wasted' tale is a myth.", tags: ["space", "myth"] },
  { q: "Bill Gates is often misquoted as saying which amount of memory 'ought to be enough for anyone'?", opts: ["640K", "1 MB", "64 KB", "1 GB"], a: 0, e: "The '640K ought to be enough' quote is famous — but Gates has repeatedly denied ever saying it.", tags: ["history", "myth"] },
  { q: "The popular myth about the QWERTY keyboard is that it was designed to do what?", opts: ["Speed typists up", "Slow typists down", "Save ink", "Fit a patent diagram"], a: 1, e: "People often say QWERTY was meant to slow typists; in reality it aimed to reduce jamming of adjacent typebars.", tags: ["hardware", "myth"] },
  { q: "The web 'cookie' is believed to take its name from what earlier computing term?", opts: ["A snack-based reward system", "The 'magic cookie' — a token of data passed between programs", "The author's pet", "An acronym, C.O.O.K.I.E."], a: 1, e: "HTTP cookies were named after 'magic cookies', a pre-existing term for a small token of data handed around.", tags: ["web", "etymology"] },
  { q: "The joke 'There is no cloud — it's just someone else's computer' pokes fun at what?", opts: ["Weather apps", "Cloud computing really being remote servers", "Encryption", "Wireless charging"], a: 1, e: "It reminds people that 'the cloud' is just data centers — computers you don't own, somewhere else.", tags: ["culture", "humor"] },

  // Level 15 — Tech Trivia Mastery
  { q: "The word 'wiki' comes from a Hawaiian word meaning what?", opts: ["Knowledge", "Quick", "Web", "Together"], a: 1, e: "'Wiki' is Hawaiian for 'quick' (as in wiki-wiki) — fitting for quickly editable pages.", tags: ["web", "etymology"] },
  { q: "Who created the first wiki (the WikiWikiWeb)?", opts: ["Jimmy Wales", "Ward Cunningham", "Tim Berners-Lee", "Linus Torvalds"], a: 1, e: "Ward Cunningham launched the first wiki in 1995; Wikipedia came later, built on the wiki idea.", tags: ["web", "history"] },
  { q: "The word 'blog' is a shortening of what?", opts: ["Backlog", "Weblog", "Web log-in", "Big log"], a: 1, e: "'Blog' is a contraction of 'weblog' — a log of posts published on the web.", tags: ["web", "etymology"] },
  { q: "The programmer joke 'There are 10 kinds of people...' works because '10' is what?", opts: ["Ten in hexadecimal", "Binary for the number 2", "A typo", "Base-10 ten"], a: 1, e: "In binary, '10' equals 2 — so the joke is 'those who understand binary and those who don't'.", tags: ["culture", "humor"] },
  { q: "The word 'robot' comes from a Czech word (via Karel Capek's play R.U.R.) meaning what?", opts: ["Machine", "Forced labor", "Metal man", "Helper"], a: 1, e: "It derives from 'robota', meaning forced labor or drudgery; the play R.U.R. (1920) popularized 'robot'.", tags: ["culture", "etymology"] },
  { q: "The first text emoticons :-) and :-( were proposed in 1982 by whom?", opts: ["Kevin Mitnick", "Scott Fahlman", "Shigeru Miyamoto", "Vint Cerf"], a: 1, e: "Scott Fahlman suggested :-) and :-( on a Carnegie Mellon message board to mark jokes and serious posts.", tags: ["culture", "history"] },
  { q: "The 'Hello, World!' sample program was popularized by which author?", opts: ["Bjarne Stroustrup", "Brian Kernighan", "James Gosling", "Guido van Rossum"], a: 1, e: "Brian Kernighan used 'hello, world' in early tutorials (and K&R's 'The C Programming Language'), making it the canonical first program.", tags: ["culture", "history"] },
  { q: "A system is 'Turing complete' if it can do what?", opts: ["Pass the Turing test", "Compute anything a Turing machine can, given enough time and memory", "Run on any operating system", "Never crash"], a: 1, e: "Turing completeness means the system can express any computation a Turing machine can — a key measure of computational power.", tags: ["concepts", "theory"] },
];
