import type { Seed } from './roadmap-build';

// "Automated testing" learning path — 120 questions (15 levels × 8), easiest →
// hardest: why test, the testing pyramid, unit/integration/e2e, assertions,
// mocks/stubs/spies, async testing, coverage, TDD, flaky tests, CI and best
// practices. Built directly (ids rm-testing-1 … rm-testing-120, 8 per level).
export const testingSeeds: Seed[] = [
  // Level 1 — Why Test?
  { q: 'A pricing rule changes often and has clear examples for discounts and edge cases. What is the strongest reason to automate those checks?', opts: ['It proves no future defect is possible', 'It gives repeatable evidence that expected behavior still works after changes', 'It removes the need for code review and production monitoring', 'It guarantees the written requirements are correct'], a: 1, e: 'Automated tests repeat the same checks quickly and catch regressions after code changes. They cannot prove the requirements are right or replace every other quality practice.', tags: ['Testing', 'basics'], intro: 'Connect each test to a failure it should catch.' },
  { q: 'A refactor leaves the new feature working but breaks an older export flow. What kind of defect is this?', opts: ['A flaky test, because only one feature failed', 'A regression, because previously working behavior broke after a change', 'A merge conflict, because two versions of the behavior exist', 'A false positive, because the refactor itself completed'], a: 1, e: 'A regression is an unintended break in behavior that worked before the change. A test covering the export flow could catch it before release.', tags: ['Testing', 'regression'] },
  { q: 'A team wants to replace an internal sorting implementation without changing its public behavior. What makes the change safer?', opts: ['Avoid running old tests because they describe the previous implementation', 'A test suite that checks the observable sorting contract and edge cases', 'Snapshot every private variable before changing the algorithm', 'Require the new function to keep the same line order as the old one'], a: 1, e: 'Behavior-focused tests let the implementation change while checking that callers still receive the promised results.', tags: ['Testing', 'confidence'] },
  { q: 'Which check is the best candidate for automation on every pull request?', opts: ['An exploratory usability session that depends on human judgment', 'A deterministic calculation with fixed inputs and expected outputs', 'A one-time review of whether the product idea is useful', 'A visual design critique with no agreed acceptance criteria'], a: 1, e: 'Stable, repeatable checks are good automation targets. Exploratory and subjective evaluation still benefit from people.', tags: ['Testing', 'automation'] },
  { q: 'Why can a well-named test such as “rejects an expired reset token” act as documentation?', opts: ['It replaces the API contract and product requirements completely', 'It gives an executable example of expected behavior', 'It records which developer originally wrote the feature', 'It explains the production implementation line by line'], a: 1, e: 'Tests show concrete inputs and expected outcomes, so they document behavior while also checking it. They complement rather than replace higher-level requirements.', tags: ['Testing', 'documentation'] },
  { q: 'Finding a bug earlier (e.g. in a unit test vs production) is:', opts: ['Cheaper and faster to fix', 'More expensive, because tests must also be updated', 'About the same cost as finding it in production', 'Only worthwhile on large teams'], a: 0, e: 'The earlier a defect is caught, the less context and rework fixing it costs; tests shift detection left, before release.', tags: ['Testing', 'cost'] },
  { q: 'A critical service passes 10,000 tests. What conclusion is justified?', opts: ['The service has been proven to contain no defects', 'The tested behaviors passed, which reduces risk but does not prove every behavior is correct', 'The requirements must be correct because the implementation matches them', 'Production monitoring is unnecessary until one of the tests fails'], a: 1, e: 'Tests provide evidence about the cases they exercise. They raise confidence, but missing cases, incorrect assumptions, and environmental failures can still exist.', tags: ['Testing', 'philosophy'] },
  { q: 'Every push starts a server job that installs dependencies, builds the app, and runs its tests. Which practice is this?', opts: ['A local pre-commit hook', 'Continuous integration (CI)', 'Continuous delivery to production', 'A manual acceptance test'], a: 1, e: 'Continuous integration automatically integrates and validates changes in a shared environment. Deployment may be another later pipeline stage.', tags: ['Testing', 'ci'] },

  // Level 2 — The Testing Pyramid
  { q: 'The testing pyramid suggests having the most:', opts: ['End-to-end tests', 'Unit tests at the base, fewer integration, and even fewer end-to-end', 'Manual tests', 'No tests'], a: 1, e: 'The pyramid favors many fast unit tests, fewer integration tests, and a small number of slow E2E tests.', tags: ['Testing', 'pyramid'] },
  { q: 'Unit tests sit at the base of the testing pyramid because they are:', opts: ['Fast, cheap, and numerous', 'The most realistic simulation of user behavior', 'Required before any code can be written', 'The only kind of test CI can run'], a: 0, e: 'Unit tests are fast and isolated, so you can afford many of them as the foundation; realism is what E2E tests trade speed for.', tags: ['Testing', 'pyramid'] },
  { q: 'End-to-end tests sit at the top of the pyramid because they are:', opts: ['Slower, more brittle, and costlier — so you keep fewer of them', 'The fastest to run and easiest to maintain', 'More isolated than unit tests', 'Meant to replace integration tests entirely'], a: 0, e: 'E2E tests exercise the whole system; they\'re valuable but slow and brittle, so keep them few and focused on key flows.', tags: ['Testing', 'pyramid'] },
  { q: 'An "ice cream cone" anti-pattern means:', opts: ['Balanced tests', 'Too many slow E2E/manual tests and too few unit tests', 'No tests at all', 'Only unit tests'], a: 1, e: 'The inverted pyramid (ice cream cone) over-relies on slow, brittle high-level tests — slow feedback and flakiness result.', tags: ['Testing', 'antipattern'] },
  { q: 'A key trade-off as you move up the pyramid is:', opts: ['Higher confidence in realism but slower and more brittle', 'Faster and cheaper', 'Less realistic', 'Nothing changes'], a: 0, e: 'Higher-level tests are more realistic/integrated but slower and flakier; lower-level tests are fast but less end-to-end.', tags: ['Testing', 'tradeoffs'] },
  { q: 'The "testing trophy" (popular for frontend) emphasizes:', opts: ['Only unit tests', 'A strong layer of integration tests', 'No static analysis', 'Only E2E'], a: 1, e: 'The testing trophy (Kent C. Dodds) weights integration tests heavily, plus static checks, unit, and some E2E.', tags: ['Testing', 'trophy'] },
  { q: 'Static analysis (types, linting) fits testing strategy by:', opts: ['Replacing all tests', 'Catching a class of bugs before tests even run', 'Slowing CI to a crawl', 'Being irrelevant'], a: 1, e: 'Type checkers and linters catch many errors cheaply and instantly, complementing the test pyramid/trophy.', tags: ['Testing', 'static'] },
  { q: 'A balanced suite aims for:', opts: ['Maximum E2E coverage only', 'Fast feedback from many small tests plus a few high-value end-to-end tests', 'Zero unit tests', 'Only manual testing'], a: 1, e: 'Combine plentiful fast tests for quick feedback with a small set of E2E tests covering critical user journeys.', tags: ['Testing', 'strategy'] },

  // Level 3 — Unit Tests
  { q: 'A unit test verifies:', opts: ['The whole deployed system', 'A small, isolated piece of code (e.g. a function) in isolation', 'The database server', 'Network latency'], a: 1, e: 'Unit tests target a single unit (function/class) in isolation from its dependencies.', tags: ['Unit', 'basics'] },
  { q: 'Which test best fits a unit-test suite that runs on every saved change?', opts: ['A test that calls a live payment sandbox over the network', 'A fast deterministic test with controlled dependencies', 'A test that shares one mutable production-like database', 'A randomized test that cannot print the seed after failure'], a: 1, e: 'Unit tests should give quick, repeatable feedback and control external dependencies. Network calls and shared mutable state make failures slower and less reliable.', tags: ['Unit', 'qualities'] },
  { q: 'A "pure function" is easy to unit test because:', opts: ['It has hidden state', 'Its output depends only on its inputs, with no side effects', 'It calls the database', 'It is random'], a: 1, e: 'Pure functions are deterministic and side-effect-free, so the same input always yields the same output — ideal for testing.', tags: ['Unit', 'pure'] },
  { q: 'Unit tests should generally avoid:', opts: ['Assertions', 'Real I/O like network, disk, or database calls', 'Function inputs', 'Return values'], a: 1, e: 'To stay fast and isolated, unit tests avoid real external I/O, using test doubles for dependencies instead.', tags: ['Unit', 'isolation'] },
  { q: 'If a function has complex branching logic, you should:', opts: ['Write one test', 'Test the important branches/edge cases, not just the happy path', 'Test nothing', 'Only test types'], a: 1, e: 'Cover the meaningful branches and edge cases (empty input, boundaries, errors), not just the success path.', tags: ['Unit', 'branches'] },
  { q: 'Testing edge cases like empty arrays or zero is important because:', opts: ['They never happen', 'Boundaries are where bugs commonly hide', 'It wastes time', 'Edge cases are illegal'], a: 1, e: 'Off-by-one and boundary conditions are classic bug sources, so explicitly test the edges.', tags: ['Unit', 'edge-cases'] },
  { q: 'When a well-written unit test fails, it should:', opts: ['Make clear which behavior broke and why', 'Point to the exact production line that must change', 'Automatically repair the regression', 'Retry until it passes'], a: 0, e: 'A focused test with a clear name and assertion pinpoints the regressed behavior; identifying the exact fix is still the developer\'s job.', tags: ['Unit', 'clarity'] },
  { q: 'Each unit test should ideally verify:', opts: ['One specific behavior or expectation', 'As many behaviors as possible to maximize coverage per test', 'Private implementation details rather than outcomes', 'A complete user journey through the app'], a: 0, e: 'Small, single-purpose tests are easier to understand and localize failures than sprawling multi-assertion tests.', tags: ['Unit', 'focus'] },

  // Level 4 — Assertions & Matchers
  { q: 'What role does `expect(total).toBe(12)` play in a test?', opts: ['It records total without affecting the result', 'It states an expected value and fails the test when the comparison is false', 'It changes total to 12 before later checks run', 'It retries the tested function until total becomes 12'], a: 1, e: 'An assertion compares observed behavior with an expectation. If the matcher fails, the test reports a failure.', tags: ['Assertions', 'basics'] },
  { q: 'In Jest, expect(result).toBe(5) checks:', opts: ['result is greater than 5', 'result is strictly equal to 5', 'result contains 5', 'result is truthy'], a: 1, e: 'toBe uses Object.is (strict equality), appropriate for primitives like numbers.', tags: ['Assertions', 'jest'] },
  { q: 'To compare objects/arrays by value (deep equality) you typically use:', opts: ['toBe', 'toEqual', 'toContain', 'toThrow'], a: 1, e: 'toEqual recursively compares structure/values, unlike toBe which checks reference identity.', tags: ['Assertions', 'equality'] },
  { q: 'To assert a function throws an error you use:', opts: ['expect(fn).toThrow()', 'expect(fn).toBe(error)', 'expect(fn).toEqual()', 'expect(fn).toContain()'], a: 0, e: 'expect(() => fn()).toThrow() asserts the call throws (optionally matching a message/type).', tags: ['Assertions', 'throw'] },
  { q: 'In Jest-style assertions, the conventional argument order is:', opts: ['expect(actual).matcher(expected), e.g. expect(sum(2,3)).toBe(5)', 'expect(expected).matcher(actual), e.g. expect(5).toBe(sum(2,3))', 'expect(actual, expected) with no matcher', 'matcher(expected).expect(actual)'], a: 0, e: 'You pass the actual value to expect() and the expected value to the matcher: expect(sum(2,3)).toBe(5). Reversing them makes failure messages misleading.', tags: ['Assertions', 'syntax'] },
  { q: 'A descriptive test name should state:', opts: ['The behavior under test and the expected outcome', 'The ticket number the test was written for', 'The name of the file being tested', 'How long the test is allowed to run'], a: 0, e: 'Names like "returns 0 for an empty cart" document behavior and make failures self-explanatory.', tags: ['Assertions', 'naming'] },
  { q: 'Asserting on too many unrelated things in one test:', opts: ['Is best practice', 'Makes failures ambiguous and tests brittle', 'Speeds up CI', 'Is required'], a: 1, e: 'Overloaded tests obscure which expectation failed; prefer focused assertions per behavior.', tags: ['Assertions', 'focus'] },
  { q: 'A "soft" expectation like toBeTruthy is weaker than toBe(true) because:', opts: ['It is stricter', 'It passes for any truthy value, possibly hiding wrong values', 'It only works on numbers', 'It throws'], a: 1, e: 'toBeTruthy accepts many values (1, "x", {}), so prefer precise matchers when the exact value matters.', tags: ['Assertions', 'precision'] },

  // Level 5 — Test Structure (AAA)
  { q: 'The "AAA" pattern stands for:', opts: ['Async, Await, Assert', 'Arrange, Act, Assert', 'Add,Acknowledge, Apply', 'Assert, Arrange, Approve'], a: 1, e: 'AAA structures a test: Arrange the inputs/state, Act by invoking the code, Assert the outcome.', tags: ['Structure', 'aaa'] },
  { q: 'In the "Arrange" step you:', opts: ['Make assertions', 'Set up inputs, state, and dependencies', 'Call the function under test', 'Tear down the database'], a: 1, e: 'Arrange prepares everything the test needs before exercising the code.', tags: ['Structure', 'arrange'] },
  { q: 'The "Act" step:', opts: ['Sets up data', 'Invokes the behavior under test', 'Checks results', 'Cleans up'], a: 1, e: 'Act performs the single action being tested, e.g. calling the function.', tags: ['Structure', 'act'] },
  { q: 'A "setup" hook (e.g. beforeEach) is used to:', opts: ['Assert results', 'Run shared preparation before each test', 'Deploy the app', 'Disable tests'], a: 1, e: 'beforeEach runs common setup before every test, keeping tests DRY and isolated.', tags: ['Structure', 'hooks'] },
  { q: 'A "teardown" hook (e.g. afterEach) is used to:', opts: ['Create data', 'Clean up state/resources so tests don’t leak into each other', 'Write code', 'Skip tests'], a: 1, e: 'afterEach restores a clean slate (closing connections, clearing mocks) to keep tests independent.', tags: ['Structure', 'teardown'] },
  { q: 'Tests should be independent so that:', opts: ['They must run in a fixed order', 'They can run in any order and in isolation without affecting each other', 'They share global state', 'One failure cascades'], a: 1, e: 'Order-independent, isolated tests are reliable and parallelizable; shared mutable state causes flakiness.', tags: ['Structure', 'isolation'] },
  { q: 'Keeping the "Act" to a single action helps:', opts: ['Make failures ambiguous', 'Pinpoint exactly which behavior failed', 'Slow the suite', 'Avoid assertions'], a: 1, e: 'One clear action per test makes the cause of a failure obvious.', tags: ['Structure', 'clarity'] },
  { q: 'A test that depends on a previous test having run is:', opts: ['Well isolated', 'Fragile and an anti-pattern', 'Faster', 'Required by AAA'], a: 1, e: 'Inter-test dependencies make suites brittle and order-sensitive; each test should stand alone.', tags: ['Structure', 'independence'] },

  // Level 6 — Mocks, Stubs & Spies
  { q: 'A "test double" is:', opts: ['A duplicate test', 'A stand-in object that replaces a real dependency during testing', 'A second assertion', 'A backup database'], a: 1, e: 'Test double is the umbrella term for fakes, stubs, mocks, and spies that substitute real dependencies.', tags: ['Doubles', 'basics'] },
  { q: 'A "stub" is used to:', opts: ['Verify calls', 'Provide canned return values for a dependency', 'Run the real service', 'Measure coverage'], a: 1, e: 'A stub returns predetermined values so the code under test can run without the real dependency.', tags: ['Doubles', 'stub'] },
  { q: 'A "mock" typically also:', opts: ['Ignores interactions', 'Records and lets you assert how it was called (interactions/expectations)', 'Returns random values', 'Deploys code'], a: 1, e: 'Mocks set expectations about interactions and let you verify the code called them correctly.', tags: ['Doubles', 'mock'] },
  { q: 'A "spy" lets you:', opts: ['Replace behavior entirely', 'Observe calls to a real (or wrapped) function (args, call count)', 'Delete the function', 'Encrypt arguments'], a: 1, e: 'A spy records how a function was called (and can wrap the real one) so you can assert on its usage.', tags: ['Doubles', 'spy'] },
  { q: 'Mocking the network/database in unit tests helps by:', opts: ['Making tests slower', 'Keeping tests fast, deterministic, and isolated from external systems', 'Testing the real DB', 'Adding flakiness'], a: 1, e: 'Replacing external I/O with doubles avoids slow, flaky dependencies and keeps unit tests deterministic.', tags: ['Doubles', 'isolation'] },
  { q: 'Over-mocking can lead to tests that:', opts: ['Are too realistic', 'Pass even when the real integration is broken (testing the mock, not behavior)', 'Run too slowly', 'Never compile'], a: 1, e: 'If you mock everything, tests can verify your mocks rather than real behavior, missing integration bugs.', tags: ['Doubles', 'overmocking'] },
  { q: 'A "fake" (e.g. an in-memory database) is:', opts: ['A production system', 'A lightweight working implementation used for tests', 'A failing test', 'A spy'], a: 1, e: 'A fake is a real but simplified implementation (like an in-memory store) suitable for tests.', tags: ['Doubles', 'fake'] },
  { q: 'You should reset/clear mocks between tests to:', opts: ['Slow things down', 'Prevent call history/state from leaking into other tests', 'Increase coverage', 'Avoid assertions'], a: 1, e: 'Clearing mocks (e.g. jest.clearAllMocks) keeps tests isolated so prior calls don’t affect later assertions.', tags: ['Doubles', 'reset'] },

  // Level 7 — Integration Tests
  { q: 'An integration test verifies:', opts: ['A single pure function', 'That multiple units/modules work together correctly', 'Only the UI pixels', 'Network latency'], a: 1, e: 'Integration tests check the interaction between components (e.g. service + database) rather than one unit in isolation.', tags: ['Integration', 'basics'] },
  { q: 'Compared to unit tests, integration tests are usually:', opts: ['Faster and more isolated', 'Slower and more realistic, exercising real collaborators', 'Always end-to-end', 'Pointless'], a: 1, e: 'Integration tests trade some speed/isolation for realism, catching bugs at the seams between components.', tags: ['Integration', 'tradeoffs'] },
  { q: 'Testing an API endpoint against a real (test) database is an example of:', opts: ['A unit test', 'An integration test', 'A static check', 'A load test'], a: 1, e: 'Exercising route → handler → database together is integration testing of those collaborating parts.', tags: ['Integration', 'api'] },
  { q: 'Integration tests often use which environment for the database?', opts: ['Production', 'A disposable/isolated test database (e.g. a container or in-memory)', 'No database', 'The user’s laptop only'], a: 1, e: 'A throwaway test database (often a container) gives realistic behavior without risking production data.', tags: ['Integration', 'environment'] },
  { q: 'A common challenge with integration tests is:', opts: ['They never fail', 'Managing test data and cleanup between runs', 'They need no setup', 'They can’t use assertions'], a: 1, e: 'Seeding and cleaning data (transactions/truncation) is key so integration tests stay isolated and repeatable.', tags: ['Integration', 'data'] },
  { q: 'Integration tests catch bugs that unit tests miss, such as:', opts: ['Pure math errors only', 'Mismatched contracts, serialization, and wiring between components', 'Typos in comments', 'CSS colors'], a: 1, e: 'Bugs at boundaries (wrong query, bad serialization, misconfigured wiring) surface only when components run together.', tags: ['Integration', 'value'] },
  { q: 'Wrapping each integration test in a transaction that rolls back helps:', opts: ['Permanently change data', 'Keep tests isolated by undoing their database changes', 'Skip the database', 'Disable assertions'], a: 1, e: 'Rolling back per-test database changes provides clean isolation without slow full resets.', tags: ['Integration', 'isolation'] },
  { q: 'A payments service changes a response field without running the ordering service. Which test can catch that the two services no longer agree?', opts: ['A visual regression test of the checkout page', 'A contract test between the API provider and consumer', 'A database index benchmark inside the payments service', 'A unit test of the ordering service’s pure price function'], a: 1, e: 'Contract tests verify that a provider supplies the requests and responses its consumers expect, catching interface breaks without requiring a full end-to-end environment.', tags: ['Integration', 'contract'] },

  // Level 8 — End-to-End Tests
  { q: 'An end-to-end (E2E) test:', opts: ['Tests one function', 'Exercises the whole application as a user would, through the real UI/flows', 'Only checks types', 'Runs no assertions'], a: 1, e: 'E2E tests simulate real user journeys through the full stack (browser → server → database).', tags: ['E2E', 'basics'] },
  { q: 'Popular browser E2E tools include:', opts: ['Jest and Mocha', 'Cypress and Playwright', 'ESLint and Prettier', 'Webpack and Vite'], a: 1, e: 'Cypress and Playwright drive a real browser to test full user flows end to end.', tags: ['E2E', 'tools'] },
  { q: 'E2E tests are valuable because they:', opts: ['Verify critical user journeys actually work across the whole system', 'Are the fastest tests in the suite', 'Can fully replace unit and integration tests', 'Test each function in complete isolation'], a: 0, e: 'E2E tests give the highest confidence that key flows (signup, checkout) genuinely work for users end to end.', tags: ['E2E', 'value'] },
  { q: 'A common downside of E2E tests is that they are:', opts: ['Slow and prone to flakiness', 'Too isolated from real browser behavior', 'Unable to run in CI pipelines', 'Incapable of catching integration bugs'], a: 0, e: 'Driving a whole system through a real browser is slow and sensitive to timing and environment, making E2E suites slower and flakier.', tags: ['E2E', 'downsides'] },
  { q: 'You should reserve E2E tests for:', opts: ['Critical, high-value user journeys', 'Every function in the codebase', 'Pure utility functions with no UI', 'Code paths already covered by unit tests'], a: 0, e: 'Because they\'re costly, E2E tests should cover the most important end-to-end flows rather than every detail.', tags: ['E2E', 'scope'] },
  { q: 'To reduce E2E flakiness you should:', opts: ['Use fixed sleeps everywhere', 'Wait for explicit conditions/elements rather than arbitrary timeouts', 'Run against production', 'Disable retries'], a: 1, e: 'Waiting for real conditions (element visible, request done) instead of fixed sleeps makes E2E tests far more stable.', tags: ['E2E', 'flakiness'] },
  { q: 'Selecting elements by stable test ids (e.g. data-testid) instead of CSS classes helps because:', opts: ['It looks nicer', 'Tests don’t break when styling/markup changes for non-functional reasons', 'It is required by HTML', 'It speeds the browser'], a: 1, e: 'Stable, intention-revealing selectors decouple tests from cosmetic markup changes, reducing brittleness.', tags: ['E2E', 'selectors'] },
  { q: 'E2E tests typically run:', opts: ['On every keystroke', 'Less frequently (e.g. before deploy) due to their cost', 'Never', 'Only locally'], a: 1, e: 'Given their slowness, E2E suites often run on PRs/pre-deploy rather than on every tiny change.', tags: ['E2E', 'cadence'] },

  // Level 9 — Testing Async Code
  { q: 'When testing a function that returns a Promise you should:', opts: ['Ignore the Promise', 'await it (or return it) so the assertions run after it settles', 'Use a fixed sleep', 'Test synchronously'], a: 1, e: 'Await/return the promise so the test waits for resolution before asserting; otherwise it may pass prematurely.', tags: ['Async', 'promises'] },
  { q: 'Forgetting to await an async assertion can cause:', opts: ['Stricter tests', 'False positives — the test finishes before the assertion runs', 'Faster CI only', 'A syntax error always'], a: 1, e: 'Un-awaited async work may complete after the test ends, so failures are missed (false passes).', tags: ['Async', 'pitfalls'] },
  { q: 'To assert a rejected promise in Jest you can use:', opts: ['expect(p).toBe(error)', 'await expect(p).rejects.toThrow()', 'expect(p).toEqual()', 'p.catch ignored'], a: 1, e: 'await expect(promise).rejects.toThrow() asserts the promise rejects with the expected error.', tags: ['Async', 'rejects'] },
  { q: 'Fake timers (e.g. jest.useFakeTimers) let you:', opts: ['Speed up the CPU', 'Control time to test setTimeout/intervals without real waiting', 'Disable async', 'Mock the network'], a: 1, e: 'Fake timers let tests advance time deterministically, testing delays/timeouts instantly and reliably.', tags: ['Async', 'timers'] },
  { q: 'Relying on real setTimeout delays in tests tends to:', opts: ['Make tests slow and flaky', 'Make tests more realistic and therefore more reliable', 'Have no effect on suite duration', 'Be required for testing any async code'], a: 0, e: 'Real time-based waits are slow and timing-dependent; prefer fake timers or awaiting explicit conditions.', tags: ['Async', 'flakiness'] },
  { q: 'Testing code that polls or retries is best done by:', opts: ['Waiting the full real duration', 'Mocking time/dependencies to drive each iteration deterministically', 'Skipping it', 'Running it in production'], a: 1, e: 'Control time and dependencies so each retry/poll iteration is exercised quickly and reliably.', tags: ['Async', 'retries'] },
  { q: 'When testing UI that updates after an async fetch, you should:', opts: ['Assert immediately', 'Wait for the updated UI (e.g. findBy/waitFor) before asserting', 'Use a fixed 5s sleep', 'Mock nothing'], a: 1, e: 'Async UI tests should wait for the expected state to appear (findBy/waitFor) rather than asserting too early.', tags: ['Async', 'ui'] },
  { q: 'A flaky async test often indicates:', opts: ['Perfect isolation', 'A race condition or missing wait in the test or code', 'Too many assertions', 'A linter issue'], a: 1, e: 'Intermittent async failures usually point to race conditions or improper synchronization in the test or code.', tags: ['Async', 'flaky'] },

  // Level 10 — Test Doubles & Fakes
  { q: 'Dependency injection makes testing easier by:', opts: ['Hiding dependencies', 'Letting you pass in test doubles instead of hard-coded real dependencies', 'Removing all dependencies', 'Encrypting code'], a: 1, e: 'Injecting dependencies lets tests substitute fakes/mocks, decoupling the unit from real collaborators.', tags: ['Doubles', 'di'] },
  { q: 'A clock/now() abstraction is useful for testing because:', opts: ['Time is irrelevant', 'You can inject a fixed time to make time-dependent code deterministic', 'It speeds the CPU', 'It encrypts dates'], a: 1, e: 'Abstracting "current time" lets tests pin it, so date/time-dependent logic is deterministic.', tags: ['Doubles', 'clock'] },
  { q: 'An in-memory repository fake is good when you want:', opts: ['Maximum realism with a real DB', 'Fast tests of logic that uses a repository without a real database', 'No isolation', 'To test the ORM'], a: 1, e: 'An in-memory fake repo exercises business logic quickly without a real database, though it’s less realistic than integration tests.', tags: ['Doubles', 'fake'] },
  { q: 'Mocking a third-party API in tests avoids:', opts: ['Network calls, rate limits, and external flakiness', 'The need to test error-handling paths', 'Writing assertions about the response handling', 'Testing your own integration code at all'], a: 0, e: 'Stubbing external APIs keeps tests offline, fast, and immune to third-party outages or limits — you still test how your code handles the responses.', tags: ['Doubles', 'external'] },
  { q: 'A risk of fakes diverging from the real dependency is:', opts: ['None', 'Tests pass against the fake but the real integration behaves differently', 'Slower tests', 'Better coverage'], a: 1, e: 'Fakes can drift from real behavior; pair them with some integration/contract tests to catch divergence.', tags: ['Doubles', 'risk'] },
  { q: 'You should prefer the real thing (not a double) when:', opts: ['It is slow and external', 'The real collaborator is fast/deterministic and using it adds confidence (e.g. a pure helper)', 'It calls the network', 'It is non-deterministic'], a: 1, e: 'Don’t mock cheap, deterministic collaborators; use real ones for more realistic, valuable tests.', tags: ['Doubles', 'when'] },
  { q: 'Mocking your own code under test (rather than its dependencies) is:', opts: ['Best practice', 'A smell — you end up testing the mock, not the behavior', 'Required', 'Faster'], a: 1, e: 'Mock collaborators, not the unit you’re testing; mocking the subject defeats the purpose.', tags: ['Doubles', 'smell'] },
  { q: 'Snapshot tests are most useful for:', opts: ['Complex business logic correctness', 'Detecting unexpected changes in serializable output (e.g. rendered markup)', 'Performance', 'Security'], a: 1, e: 'Snapshots flag unintended output changes, but can be brittle/over-broad — use sparingly and review diffs.', tags: ['Doubles', 'snapshot'] },

  // Level 11 — Coverage & What to Test
  { q: 'Code coverage measures:', opts: ['How correct the code is', 'How much of the code is exercised by tests', 'How fast tests run', 'How many bugs exist'], a: 1, e: 'Coverage reports which lines/branches ran during tests — a quantity metric, not a guarantee of correctness.', tags: ['Coverage', 'basics'] },
  { q: '100% coverage guarantees:', opts: ['Bug-free code', 'That lines ran, not that behavior/assertions are correct', 'Fast code', 'No regressions ever'], a: 1, e: 'Coverage shows execution, not validation; you can run every line without asserting the right behavior.', tags: ['Coverage', 'limits'] },
  { q: 'Branch coverage is stronger than line coverage because it checks:', opts: ['Only line counts', 'That both sides of conditionals (if/else) are exercised', 'Performance', 'Types'], a: 1, e: 'Branch coverage requires testing each decision outcome, catching untested conditional paths line coverage might miss.', tags: ['Coverage', 'branch'] },
  { q: 'Chasing 100% coverage can be counterproductive when it leads to:', opts: ['Meaningful tests', 'Trivial tests that assert nothing useful just to hit lines', 'Faster CI', 'Better design'], a: 1, e: 'Gaming coverage produces low-value tests; focus on testing important behavior, not the metric itself.', tags: ['Coverage', 'antipattern'] },
  { q: 'You should prioritize testing:', opts: ['Trivial getters', 'Complex, critical, and bug-prone logic', 'Auto-generated code', 'Comments'], a: 1, e: 'Invest tests where risk and complexity are highest; low-risk trivial code yields little testing value.', tags: ['Coverage', 'priorities'] },
  { q: 'Mutation testing assesses test quality by:', opts: ['Measuring line counts', 'Introducing code mutations and checking whether tests catch them', 'Timing the suite', 'Counting files'], a: 1, e: 'Mutation testing changes the code and sees if tests fail; surviving mutants reveal weak/ineffective tests.', tags: ['Coverage', 'mutation'] },
  { q: 'A checkout suite covers only a successful card payment. Which gap is most urgent?', opts: ['The successful path needs to be duplicated with another test name', 'Failures and boundaries such as declines, timeouts, and repeated submissions', 'Every assertion needs to be moved into production code', 'The tests need a larger screenshot for the passing case'], a: 1, e: 'The happy path does not exercise the states where systems often fail. Declines, dependency timeouts, invalid input, and retries need explicit expectations.', tags: ['Coverage', 'edges'] },
  { q: 'A pragmatic coverage target is often:', opts: ['Always exactly 100%', 'A reasonable threshold focused on critical paths, not a perfect number', '0%', 'Irrelevant'], a: 1, e: 'Sensible coverage thresholds protect critical code without incentivizing useless tests to chase a perfect figure.', tags: ['Coverage', 'targets'] },

  // Level 12 — TDD
  { q: 'TDD (test-driven development) follows the cycle:', opts: ['Code, then maybe test', 'Red (failing test) → Green (make it pass) → Refactor', 'Deploy, then test', 'Test only at the end'], a: 1, e: 'TDD writes a failing test first (red), makes it pass minimally (green), then refactors with the test as a safety net.', tags: ['TDD', 'cycle'] },
  { q: 'In TDD you write the test:', opts: ['After the implementation', 'Before the implementation', 'Never', 'Only for UI'], a: 1, e: 'TDD inverts the usual order: the test comes first and drives the design of the code.', tags: ['TDD', 'order'] },
  { q: 'The first TDD step produces a test that:', opts: ['Passes immediately', 'Fails (red) because the behavior isn’t implemented yet', 'Is skipped', 'Has no assertions'], a: 1, e: 'A new test should fail first, proving it actually tests something before you implement the code.', tags: ['TDD', 'red'] },
  { q: 'The "green" step means:', opts: ['Write elegant code', 'Write the simplest code to make the test pass', 'Delete the test', 'Refactor everything'], a: 1, e: 'Green = make it pass as simply as possible; cleanup happens in the refactor step.', tags: ['TDD', 'green'] },
  { q: 'The "refactor" step is safe because:', opts: ['There are no tests', 'The passing tests catch any behavior change while you improve the code', 'You skip tests', 'You deploy first'], a: 1, e: 'With green tests in place, you can restructure code confidently, rerunning tests to ensure behavior is preserved.', tags: ['TDD', 'refactor'] },
  { q: 'A benefit of TDD is that it tends to produce:', opts: ['Untestable code', 'Testable, well-specified, modular designs', 'Slower code always', 'No documentation'], a: 1, e: 'Writing tests first pressures you toward small, decoupled, testable units and clear specifications.', tags: ['TDD', 'benefits'] },
  { q: 'A common TDD pitfall is:', opts: ['Tiny steps', 'Writing too much production code before the test, or over-specifying', 'Refactoring', 'Running tests'], a: 1, e: 'Skipping the failing-test step or writing big leaps undermines TDD; keep steps small and test-led.', tags: ['TDD', 'pitfalls'] },
  { q: 'Which task is the best fit for test-driven development?', opts: ['A one-off experiment that will be discarded today', 'Pricing logic with clear examples, edge cases, and likely future changes', 'A static paragraph whose exact wording is still undecided', 'A visual exploration with no defined behavior yet'], a: 1, e: 'TDD works well when examples can define non-trivial behavior and the tests will protect later changes. It offers less value before behavior is understood or for disposable exploration.', tags: ['TDD', 'when'] },

  // Level 13 — Flaky Tests & Isolation
  { q: 'A "flaky" test is one that:', opts: ['Always passes', 'Sometimes passes and sometimes fails without code changes', 'Never runs', 'Is well written'], a: 1, e: 'Flaky tests give nondeterministic results, eroding trust in the suite and hiding real failures.', tags: ['Flaky', 'definition'] },
  { q: 'A common cause of flakiness is:', opts: ['Pure functions', 'Reliance on timing, ordering, or shared mutable state', 'Clear assertions', 'Good isolation'], a: 1, e: 'Race conditions, test order dependencies, and shared state are frequent sources of flaky tests.', tags: ['Flaky', 'causes'] },
  { q: 'Depending on real current time/date can cause flakiness because:', opts: ['Time never changes', 'Results vary by when the test runs (timezones, midnight rollover)', 'It is encrypted', 'It is faster'], a: 1, e: 'Time-dependent tests can fail at certain times/zones; inject a fixed clock to make them deterministic.', tags: ['Flaky', 'time'] },
  { q: 'Tests sharing a global/mutable resource can fail because:', opts: ['They are isolated', 'One test’s changes leak into another, depending on order', 'Assertions are strict', 'They run too slowly'], a: 1, e: 'Shared mutable state couples tests; reset state between tests to keep them independent.', tags: ['Flaky', 'shared-state'] },
  { q: 'A good response to a flaky test is to:', opts: ['Add automatic infinite retries and ignore it', 'Diagnose and fix the root cause (timing, isolation, data)', 'Delete the assertion', 'Disable CI'], a: 1, e: 'Blindly retrying hides problems; flaky tests should be investigated and made deterministic.', tags: ['Flaky', 'fix'] },
  { q: 'Running tests in random order helps by:', opts: ['Hiding flakiness', 'Surfacing hidden inter-test dependencies', 'Slowing tests', 'Removing assertions'], a: 1, e: 'Randomized order exposes tests that secretly depend on others running first, prompting better isolation.', tags: ['Flaky', 'order'] },
  { q: 'Network calls in tests cause flakiness because:', opts: ['They are deterministic', 'External services can be slow, down, or rate-limited', 'They never fail', 'They are encrypted'], a: 1, e: 'Real network dependencies introduce nondeterminism; mock them in unit tests for reliability.', tags: ['Flaky', 'network'] },
  { q: 'Flaky tests are harmful mainly because they:', opts: ['Improve confidence', 'Erode trust, causing real failures to be ignored ("just rerun it")', 'Speed up CI', 'Increase coverage'], a: 1, e: 'When failures are routinely dismissed as flakiness, genuine regressions slip through unnoticed.', tags: ['Flaky', 'impact'] },

  // Level 14 — Testing in CI
  { q: 'A pull request starts the test suite in a clean shared environment without a developer running it manually. Where are the tests running?', opts: ['Only through a local Git hook on the author’s machine', 'In continuous integration (CI) for the proposed change', 'As production monitoring after the change is deployed', 'As a scheduled backup verification job'], a: 1, e: 'CI automatically builds and tests shared changes, commonly on each push or pull request, so failures are visible before merge.', tags: ['CI', 'basics'] },
  { q: 'A failing test in CI should typically:', opts: ['Be ignored', 'Block the merge/deploy until fixed', 'Auto-delete itself', 'Email customers'], a: 1, e: 'CI gates merges on green tests, preventing broken code from reaching the main branch or production.', tags: ['CI', 'gating'] },
  { q: 'Fast test suites matter in CI because:', opts: ['They look impressive', 'Quick feedback keeps developers productive and unblocks merges', 'They use less disk', 'They need no maintenance'], a: 1, e: 'Slow suites delay feedback and merges; keeping tests fast (mostly unit) preserves a tight develop loop.', tags: ['CI', 'speed'] },
  { q: 'Running tests in parallel can:', opts: ['Always be safe with shared state', 'Speed up CI but requires test isolation to avoid interference', 'Slow CI down', 'Remove the need for assertions'], a: 1, e: 'Parallelization cuts wall-clock time, but tests must be isolated (no shared mutable resources) to run concurrently.', tags: ['CI', 'parallel'] },
  { q: 'Tests should run against:', opts: ['Production data and services', 'Reproducible, isolated test environments/data', 'Random environments', 'No environment'], a: 1, e: 'Deterministic, isolated environments (test DBs, seeded data) make CI results reliable and repeatable.', tags: ['CI', 'environment'] },
  { q: 'A pre-commit/pre-push hook that runs quick tests/linters helps by:', opts: ['Slowing everyone down forever', 'Catching obvious issues before they reach CI', 'Replacing CI', 'Encrypting commits'], a: 1, e: 'Local hooks give fast feedback and reduce noisy CI failures, though CI remains the source of truth.', tags: ['CI', 'hooks'] },
  { q: 'Caching dependencies in CI primarily:', opts: ['Breaks tests', 'Speeds up runs by avoiding repeated installs', 'Reduces coverage', 'Hides flakiness'], a: 1, e: 'Dependency caching shortens CI by skipping redundant installs, improving feedback time.', tags: ['CI', 'cache'] },
  { q: 'A "green build" means:', opts: ['Tests failed', 'All checks/tests passed', 'No tests ran', 'The app deployed'], a: 1, e: 'A green build indicates the pipeline’s tests and checks all passed, signaling the change is safe to merge.', tags: ['CI', 'green'] },

  // Level 15 — Testing Best Practices
  { q: 'Tests should ideally focus on:', opts: ['Implementation details', 'Observable behavior and public contracts', 'Private variable names', 'Line counts'], a: 1, e: 'Testing behavior (not internals) makes tests resilient to refactors and focused on what actually matters.', tags: ['Best Practices', 'behavior'] },
  { q: 'Tests coupled to implementation details tend to:', opts: ['Survive refactors well', 'Break on harmless refactors, discouraging improvement', 'Be more valuable', 'Run faster'], a: 1, e: 'Over-specified tests that assert internals break when you refactor, even when behavior is unchanged.', tags: ['Best Practices', 'coupling'] },
  { q: 'A useful guideline for assertions is:', opts: ['Assert as much unrelated stuff as possible', 'Assert the meaningful outcome clearly, ideally one concept per test', 'Never assert', 'Only snapshot'], a: 1, e: 'Clear, focused assertions on the meaningful outcome make tests readable and failures diagnosable.', tags: ['Best Practices', 'assertions'] },
  { q: 'Test code quality:', opts: ['Does not matter', 'Matters — readable, maintainable tests are part of the codebase', 'Should be obfuscated', 'Is never reviewed'], a: 1, e: 'Tests are read often and must be maintained; treat them with the same care as production code.', tags: ['Best Practices', 'quality'] },
  { q: 'When a bug is found in production, a great practice is to:', opts: ['Just patch it', 'Write a failing test reproducing it, then fix it (so it never regresses)', 'Ignore it', 'Delete related tests'], a: 1, e: 'Capturing the bug as a test ensures the fix is verified and the regression can’t silently return.', tags: ['Best Practices', 'regression'] },
  { q: 'Deterministic tests are important because:', opts: ['Randomness is good', 'Reliable, repeatable results are trustworthy and debuggable', 'They run slower', 'They need no assertions'], a: 1, e: 'Determinism makes failures meaningful and reproducible, unlike flaky, nondeterministic tests.', tags: ['Best Practices', 'determinism'] },
  { q: 'Testing user-facing behavior of a UI (e.g. "button shows count") is better than testing:', opts: ['What the user sees', 'Internal component state/implementation', 'Accessibility', 'The rendered text'], a: 1, e: 'Testing what users observe (rendered output, interactions) is more robust than asserting internal state.', tags: ['Best Practices', 'ui'] },
  { q: 'The ultimate goal of a test suite is to:', opts: ['Maximize a coverage number', 'Give fast, reliable confidence that the software works and stays working', 'Slow releases', 'Replace code review'], a: 1, e: 'Tests exist to provide trustworthy confidence enabling safe, fast change — not to chase metrics.', tags: ['Best Practices', 'goal'] },
];
