import type { QuestionTranslation } from './quiz-data';

// Czech (cs) translations for the Cell Biology & Biochemistry roadmap bank (rm-cellbio-*).
// Only text is translated; options keep the SAME length and order as the English
// source so the stored correctAnswer index stays valid.
export const cellBiologyTranslationsCs: Record<string, QuestionTranslation> = {
  'rm-cellbio-1': { introduction: 'Zamysli se, která organela uchovává DNA a řídí buňku.', question: 'Která organela je označována jako „řídicí centrum" buňky a obsahuje její DNA?', options: ['Jádro', 'Ribozom', 'Lyzozom', 'Golgiho aparát'], explanation: 'Jádro uchovává genetický materiál (DNA) a řídí činnost buňky.' },
  'rm-cellbio-2': { introduction: 'Přemýšlej o organele, kde vzniká většina energie.', question: 'Která organela je hlavním místem tvorby ATP a nazývá se „elektrárnou" buňky?', options: ['Mitochondrie', 'Jádro', 'Vakuola', 'Ribozom'], explanation: 'Mitochondrie provádějí aerobní dýchání a vytvářejí většinu ATP buňky.' },
  'rm-cellbio-3': { introduction: 'Jde o strukturu na hranici buňky.', question: 'Která struktura obklopuje buňku a řídí, co do ní vstupuje a co ji opouští?', options: ['Buněčná membrána', 'Jadérko', 'Cytoplazma', 'Chromozom'], explanation: 'Buněčná (plazmatická) membrána je selektivně propustná bariéra řídící transport dovnitř a ven.' },
  'rm-cellbio-4': { introduction: 'Tyto malé organely „čtou" mRNA.', question: 'Které organely jsou místem syntézy bílkovin?', options: ['Ribozomy', 'Lyzozomy', 'Vakuoly', 'Centrioly'], explanation: 'Ribozomy skládají aminokyseliny do bílkovin podle informační RNA.' },
  'rm-cellbio-5': { introduction: 'Porovnej rostlinnou a živočišnou buňku.', question: 'Který útvar se nachází v rostlinných buňkách, ale NE v živočišných?', options: ['Buněčná stěna', 'Jádro', 'Mitochondrie', 'Buněčná membrána'], explanation: 'Rostlinné buňky mají pevnou celulózovou buněčnou stěnu vně membrány; živočišné ji nemají.' },
  'rm-cellbio-6': { introduction: 'Jde o zelenou organelu rostlin.', question: 'Která organela v rostlinných buňkách zachycuje světelnou energii pro fotosyntézu?', options: ['Chloroplast', 'Mitochondrie', 'Lyzozom', 'Jádro'], explanation: 'Chloroplasty obsahují chlorofyl a přeměňují světelnou energii na chemickou (glukózu).' },
  'rm-cellbio-7': { introduction: 'Rozdíl mezi eukaryoty a prokaryoty.', question: 'Který klíčový znak odlišuje eukaryotické buňky od prokaryotických?', options: ['Jádro obalené membránou', 'Přítomnost DNA', 'Buněčná membrána', 'Ribozomy'], explanation: 'Eukaryota uchovávají DNA v jádře obaleném membránou; prokaryota pravé jádro nemají.' },
  'rm-cellbio-8': { introduction: 'Tato organela balí bílkoviny.', question: 'Která organela upravuje, třídí a balí bílkoviny pro vylučování?', options: ['Golgiho aparát', 'Ribozom', 'Jadérko', 'Mitochondrie'], explanation: 'Golgiho aparát zpracovává a balí bílkoviny a lipidy do váčků k rozvozu.' },

  'rm-cellbio-9': { introduction: 'Základní stavební kámen membrány.', question: 'Buněčná membrána je tvořena hlavně dvojvrstvou které molekuly?', options: ['Fosfolipidy', 'Celulóza', 'Glukóza', 'DNA'], explanation: 'Fosfolipidová dvojvrstva tvoří membránu: hydrofilní hlavičky ven, hydrofobní ocásky dovnitř.' },
  'rm-cellbio-10': { introduction: 'Jak se pohybují částice samovolně?', question: 'Difúzi nejlépe popisuje pohyb částic z oblasti o...', options: ['Vysoké do nízké koncentrace', 'Nízké do vysoké koncentrace', 'Chladu do tepla', 'Nízkého do vysokého tlaku pouze'], explanation: 'Difúze přesouvá částice po koncentračním spádu, z vyšší do nižší, dokud se nerozprostřou.' },
  'rm-cellbio-11': { introduction: 'Speciální případ difúze.', question: 'Osmóza označuje difúzi konkrétně které látky?', options: ['Voda', 'Kyslík', 'Glukóza', 'Sodné ionty'], explanation: 'Osmóza je čistý pohyb vody přes selektivně propustnou membránu podle vodního potenciálu.' },
  'rm-cellbio-12': { introduction: 'Který transport spotřebovává energii?', question: 'Který typ transportu vyžaduje energii (ATP) k přesunu látek proti spádu?', options: ['Aktivní transport', 'Prostá difúze', 'Osmóza', 'Usnadněná difúze'], explanation: 'Aktivní transport používá ATP k přečerpávání látek z nízké do vysoké koncentrace, proti spádu.' },
  'rm-cellbio-13': { introduction: 'Porovnej s prostou difúzí.', question: 'Usnadněná difúze se liší od prosté difúze tím, že...', options: ['Využívá membránové bílkoviny', 'Vyžaduje ATP', 'Jde proti spádu', 'Přenáší jen vodu'], explanation: 'Usnadněná difúze je pasivní, ale využívá kanálové či přenašečové bílkoviny pro určité molekuly.' },
  'rm-cellbio-14': { introduction: 'Co se stane buňce v čisté vodě?', question: 'Živočišná buňka vložená do čisté vody (hypotonického roztoku) obvykle...', options: ['Nabobtná a může prasknout', 'Se scvrkne a svraští', 'Zůstane přesně stejná', 'Ztratí veškerou DNA'], explanation: 'Voda vstupuje osmózou do koncentrovanější buňky; bez stěny může buňka prasknout (lyze).' },
  'rm-cellbio-15': { introduction: 'Jak buňka pohltí velké částice?', question: 'Kterým procesem buňka pohlcuje velké částice obalením své membrány kolem nich?', options: ['Endocytóza', 'Osmóza', 'Difúze', 'Transpirace'], explanation: 'Endocytóza vnáší velké částice do buňky uzavřením do váčku vytvořeného z membrány.' },
  'rm-cellbio-16': { introduction: 'Pumpa, která přímo štěpí ATP.', question: 'Sodíko-draslíková pumpa přesouvá 3 Na+ ven a 2 K+ dovnitř za cyklus. Jde o příklad...', options: ['Primárního aktivního transportu', 'Prosté difúze', 'Osmózy', 'Usnadněné difúze'], explanation: 'Přímo hydrolyzuje ATP k přečerpávání iontů proti spádu, což definuje primární aktivní transport.' },

  'rm-cellbio-17': { introduction: 'Rychlý zdroj energie.', question: 'Která biomolekula je hlavním krátkodobým zdrojem energie se vzorcem (CH2O)n?', options: ['Sacharidy', 'Lipidy', 'Bílkoviny', 'Nukleové kyseliny'], explanation: 'Sacharidy jako glukóza se snadno rozkládají a rychle uvolňují energii.' },
  'rm-cellbio-18': { introduction: 'Stavební jednotky bílkovin.', question: 'Které monomery (stavební jednotky) tvoří bílkoviny?', options: ['Aminokyseliny', 'Monosacharidy', 'Mastné kyseliny', 'Nukleotidy'], explanation: 'Bílkoviny jsou polymery aminokyselin spojených peptidovými vazbami.' },
  'rm-cellbio-19': { introduction: 'Nejvíce energie na gram.', question: 'Která biomolekula ukládá nejvíce energie na gram a je hlavní složkou membrán?', options: ['Lipidy', 'Sacharidy', 'Bílkoviny', 'Nukleové kyseliny'], explanation: 'Lipidy (tuky) jsou energeticky bohaté a tvoří fosfolipidovou dvojvrstvu membrán.' },
  'rm-cellbio-20': { introduction: 'Stavební jednotky DNA a RNA.', question: 'Monomery tvořící nukleové kyseliny jako DNA a RNA se nazývají...', options: ['Nukleotidy', 'Aminokyseliny', 'Jednotky glukózy', 'Molekuly glycerolu'], explanation: 'Nukleotidy (cukr, fosfát a báze) se spojují a tvoří DNA a RNA.' },
  'rm-cellbio-21': { introduction: 'Reakce spojující monomery.', question: 'Který typ reakce spojuje dva monomery a přitom uvolňuje molekulu vody?', options: ['Kondenzace (dehydratační syntéza)', 'Hydrolýza', 'Oxidace', 'Redukce'], explanation: 'Kondenzační reakce tvoří vazby mezi monomery a uvolňují vodu; hydrolýza probíhá opačně.' },
  'rm-cellbio-22': { introduction: 'Polymery jednoho cukru.', question: 'Škrob, glykogen a celulóza jsou všechny polymery kterého jediného cukru?', options: ['Glukóza', 'Fruktóza', 'Sacharóza', 'Ribóza'], explanation: 'Tyto polysacharidy jsou tvořeny monomery glukózy, liší se vazbami a větvením.' },
  'rm-cellbio-23': { introduction: 'Z čeho jsou enzymy?', question: 'Většina enzymů je tvořena kterou třídou biomolekul?', options: ['Bílkoviny', 'Lipidy', 'Sacharidy', 'Nukleové kyseliny'], explanation: 'Enzymy jsou obvykle bílkoviny, jejichž specifický 3D tvar jim umožňuje katalyzovat reakce.' },
  'rm-cellbio-24': { introduction: 'Úroveň struktury bílkoviny.', question: 'Alfa-šroubovice a beta-skládané listy bílkoviny tvoří kterou úroveň struktury?', options: ['Sekundární struktura', 'Primární struktura', 'Terciární struktura', 'Kvartérní struktura'], explanation: 'Sekundární struktura je lokální sbalení (šroubovice a listy) stabilizované vodíkovými vazbami páteře.' },

  'rm-cellbio-25': { introduction: 'Univerzální „mince" energie.', question: 'Kterou molekulu buňky používají k ukládání a přenosu využitelné chemické energie?', options: ['ATP', 'DNA', 'Glukóza', 'Voda'], explanation: 'ATP (adenozintrifosfát) uvolňuje energii při rozštěpení své koncové fosfátové vazby.' },
  'rm-cellbio-26': { introduction: 'Kde začíná dýchání?', question: 'Glykolýza, první stupeň dýchání, probíhá v které části buňky?', options: ['Cytoplazma', 'Matrix mitochondrie', 'Jádro', 'Buněčná membrána'], explanation: 'Glykolýza probíhá v cytoplazmě a nevyžaduje kyslík.' },
  'rm-cellbio-27': { introduction: 'Produkt rozkladu glukózy.', question: 'Glykolýza rozkládá jednu molekulu glukózy na dvě molekuly...', options: ['Pyruvátu', 'Kyseliny mléčné', 'Etanolu', 'Oxidu uhličitého'], explanation: 'Glykolýza štěpí šestiuhlíkatou glukózu na dva tříuhlíkaté pyruváty a získá čistě 2 ATP.' },
  'rm-cellbio-28': { introduction: 'Kde probíhá citrátový cyklus?', question: 'Krebsův cyklus (citrátový cyklus) probíhá v kterém místě?', options: ['Matrix mitochondrie', 'Cytoplazma', 'Ribozom', 'Jádro'], explanation: 'Krebsův cyklus probíhá v matrix mitochondrie a uvolňuje CO2 a redukované koenzymy.' },
  'rm-cellbio-29': { introduction: 'Souhrnná rovnice dýchání.', question: 'Souhrnná rovnice aerobního dýchání využívá glukózu a kyslík k tvorbě...', options: ['Oxidu uhličitého, vody a ATP', 'Glukózy a kyslíku', 'Pouze vody', 'Bílkovin a lipidů'], explanation: 'Aerobní dýchání: glukóza + kyslík → oxid uhličitý + voda + energie (ATP).' },
  'rm-cellbio-30': { introduction: 'Kde vzniká nejvíce ATP?', question: 'Poslední stupeň aerobního dýchání, který produkuje nejvíce ATP, je...', options: ['Dýchací řetězec', 'Glykolýza', 'Krebsův cyklus', 'Kvašení'], explanation: 'Oxidační fosforylace v dýchacím řetězci dává asi 34 z přibližně 38 ATP na glukózu.' },
  'rm-cellbio-31': { introduction: 'Co dělají svaly bez kyslíku?', question: 'Bez kyslíku provádějí lidské svalové buňky kvašení a vytvářejí...', options: ['Kyselinu mléčnou', 'Etanol a CO2', 'Čisté ATP', 'Kyslík'], explanation: 'Anaerobní dýchání v lidském svalu přeměňuje pyruvát na kyselinu mléčnou a obnovuje NAD+ pro glykolýzu.' },
  'rm-cellbio-32': { introduction: 'Kdo přijímá elektrony na konci?', question: 'V dýchacím řetězci: co je konečným příjemcem elektronů při aerobním dýchání?', options: ['Kyslík', 'Oxid uhličitý', 'Glukóza', 'ATP'], explanation: 'Kyslík přijímá elektrony na konci řetězce a spojením s H+ tvoří vodu.' },

  'rm-cellbio-33': { introduction: 'Pravidlo párování bází.', question: 'V DNA se adenin (A) vždy páruje s kterou bází?', options: ['Thymin', 'Guanin', 'Cytosin', 'Uracil'], explanation: 'Komplementární párování: A se páruje s T a C s G pomocí vodíkových vazeb.' },
  'rm-cellbio-34': { introduction: 'Definice genu.', question: 'Co je gen?', options: ['Úsek DNA kódující bílkovinu', 'Celý chromozom', 'Druh cukru', 'Ribozom'], explanation: 'Gen je úsek DNA nesoucí kód pro určitý polypeptid nebo funkční RNA.' },
  'rm-cellbio-35': { introduction: 'Přepis DNA do RNA.', question: 'Proces opisu DNA genu do molekuly informační RNA se nazývá...', options: ['Transkripce', 'Translace', 'Replikace', 'Trávení'], explanation: 'Transkripce vytváří mRNA podle předlohy DNA a u eukaryot probíhá v jádře.' },
  'rm-cellbio-36': { introduction: 'Kde se mRNA překládá?', question: 'Při translaci je mRNA překládána na bílkovinu na...', options: ['Ribozomu', 'Jadérku', 'Golgiho aparátu', 'Lyzozomu'], explanation: 'Ribozomy čtou kodony mRNA a skládají odpovídající aminokyseliny do polypeptidu.' },
  'rm-cellbio-37': { introduction: 'Kolik bází je jeden kodon?', question: 'Kodon, jednotka čtená při translaci, se skládá z kolika bází?', options: ['Tří', 'Jedné', 'Dvou', 'Čtyř'], explanation: 'Každý kodon je trojice tří bází mRNA, která určuje jednu aminokyselinu (nebo stop signál).' },
  'rm-cellbio-38': { introduction: 'Kdo nosí aminokyseliny na ribozom?', question: 'Která molekula přináší určitou aminokyselinu na ribozom a čte kodony svým antikodonem?', options: ['Transferová RNA (tRNA)', 'Informační RNA (mRNA)', 'DNA polymeráza', 'Ribozomální DNA'], explanation: 'tRNA přiřazuje svůj antikodon ke kodonu mRNA a dodává správnou aminokyselinu pro rostoucí řetězec.' },
  'rm-cellbio-39': { introduction: 'Báze typická pro RNA.', question: 'Která báze v RNA nahrazuje thymin a páruje se s adeninem?', options: ['Uracil', 'Cytosin', 'Guanin', 'Thymin'], explanation: 'RNA používá místo thyminu uracil (U), takže v RNA se adenin páruje s uracilem.' },
  'rm-cellbio-40': { introduction: 'Typ bodové mutace.', question: 'Mutace, která změní jedinou bázi tak, že se jedna aminokyselina zamění za jinou, je...', options: ['Missense (záměnová) mutace', 'Tichá mutace', 'Posunová delece', 'Chromozomální duplikace'], explanation: 'Záměnová (missense) mutace pozmění jeden kodon tak, že kóduje jinou aminokyselinu, což může změnit funkci bílkoviny.' },
};
