// Chess History & Champions roadmap questions (40): 5 levels × 8, easiest → hardest.
import type { Seed } from './roadmap-build';

export const chessHistorySeeds: Seed[] = [
  // ── Level 1 — Origins & early history of chess ──
  { q: 'In which country did chess most likely originate?', opts: ['India', 'China', 'Egypt', 'Greece'], a: 0, e: 'Chess traces back to India, where its ancestor chaturanga was played by around the 6th century.', tags: ['Chess History', 'Origins'] },
  { q: 'What was the name of the ancient Indian game regarded as the ancestor of chess?', opts: ['Chaturanga', 'Senet', 'Go', 'Backgammon'], a: 0, e: 'Chaturanga, meaning "four divisions" of an army, is the earliest known ancestor of chess.', tags: ['Chess History', 'Origins'] },
  { q: 'From India chess spread to which empire, where it became known as shatranj?', opts: ['Persia', 'Rome', 'Japan', 'Mongolia'], a: 0, e: 'Chess reached Persia, where it was called shatranj, before spreading through the Islamic world.', tags: ['Chess History', 'Origins'] },
  { q: 'The word "checkmate" comes from the Persian phrase "shah mat", meaning roughly what?', opts: ['The king is helpless', 'The queen is lost', 'The game is even', 'The board is full'], a: 0, e: '"Shah mat" means the king is helpless or defeated, giving us the word checkmate.', tags: ['Chess History', 'Terminology'] },
  { q: 'The four divisions of an army in chaturanga were infantry, cavalry, elephants, and what?', opts: ['Chariots', 'Archers', 'Ships', 'Catapults'], a: 0, e: 'Chaturanga\'s four arms were infantry, cavalry, elephants, and chariots, which became modern pieces.', tags: ['Chess History', 'Origins'] },
  { q: 'Through which route did chess mainly enter medieval Europe?', opts: ['The Islamic world and Moorish Spain', 'The Vikings', 'Ancient Rome', 'The Silk Road to Scandinavia'], a: 0, e: 'Chess spread into Europe largely via the Islamic world, especially Moorish Spain, by the 10th century.', tags: ['Chess History', 'Spread'] },
  { q: 'In early chess the piece that became the queen (the "ferz") could move how far?', opts: ['Only one square diagonally', 'Any distance diagonally', 'Like a modern rook', 'Like a modern knight'], a: 0, e: 'The old queen (ferz) was weak, moving just one square diagonally, unlike today\'s powerful queen.', tags: ['Chess History', 'Rules'] },
  { q: 'The modern powerful queen and long-range bishop emerged in which region around 1475?', opts: ['Europe', 'India', 'Persia', 'China'], a: 0, e: 'The modern rules, including the strong queen, took shape in Europe (Spain and Italy) around 1475.', tags: ['Chess History', 'Rules'] },

  // ── Level 2 — The Romantic era & the first World Champions ──
  { q: 'The Romantic era of chess in the 19th century emphasized what style of play?', opts: ['Bold attacks and sacrifices', 'Slow defensive play', 'Avoiding all captures', 'Drawing quickly'], a: 0, e: 'Romantic-era chess prized daring attacks, gambits, and spectacular sacrifices over cautious defense.', tags: ['Chess History', 'Romantic era'] },
  { q: 'The famous 1851 "Immortal Game" was won with dazzling sacrifices by which player?', opts: ['Adolf Anderssen', 'Paul Morphy', 'Wilhelm Steinitz', 'Emanuel Lasker'], a: 0, e: 'Adolf Anderssen beat Lionel Kieseritzky in 1851, sacrificing heavily in the celebrated Immortal Game.', tags: ['Chess History', 'Famous games'] },
  { q: 'American prodigy Paul Morphy dominated world chess during which decade?', opts: ['The 1850s', 'The 1790s', 'The 1900s', 'The 1930s'], a: 0, e: 'Paul Morphy swept Europe\'s best players in the 1850s and is seen as the finest of his era.', tags: ['Chess History', 'Morphy'] },
  { q: 'Morphy\'s famous "Opera Game" of 1858 was played at an opera house in which city?', opts: ['Paris', 'London', 'Vienna', 'New York'], a: 0, e: 'Morphy played the brilliant Opera Game in Paris in 1858 against two allied noble opponents.', tags: ['Chess History', 'Famous games'] },
  { q: 'Who is recognized as the first official World Chess Champion, from 1886?', opts: ['Wilhelm Steinitz', 'Paul Morphy', 'Emanuel Lasker', 'Adolf Anderssen'], a: 0, e: 'Wilhelm Steinitz won the first official World Championship match in 1886, becoming the first champion.', tags: ['Chess History', 'World Champions'] },
  { q: 'Steinitz is credited with pioneering which approach to chess?', opts: ['Positional (scientific) play', 'Pure attacking chess', 'Blindfold chess', 'Speed chess'], a: 0, e: 'Steinitz founded the positional school, stressing sound structure and principles over reckless attacks.', tags: ['Chess History', 'Steinitz'] },
  { q: 'Emanuel Lasker set a record by holding the World Championship for how long?', opts: ['27 years', '5 years', '15 years', '40 years'], a: 0, e: 'Lasker reigned from 1894 to 1921, a record 27 years as World Champion.', tags: ['Chess History', 'Lasker'] },
  { q: 'What was the nationality of world champion Emanuel Lasker?', opts: ['German', 'Russian', 'American', 'French'], a: 0, e: 'Emanuel Lasker was a German chess master and mathematician who held the title for 27 years.', tags: ['Chess History', 'Lasker'] },

  // ── Level 3 — The classical & Soviet school ──
  { q: 'World champion José Raúl Capablanca, famed for his endgame skill, came from which country?', opts: ['Cuba', 'Spain', 'Argentina', 'Mexico'], a: 0, e: 'Capablanca, from Cuba, was renowned for his effortless, precise endgame technique.', tags: ['Chess History', 'Capablanca'] },
  { q: 'In 1921 Capablanca won the world title by defeating which long-reigning champion?', opts: ['Emanuel Lasker', 'Wilhelm Steinitz', 'Alexander Alekhine', 'Mikhail Botvinnik'], a: 0, e: 'Capablanca defeated Emanuel Lasker in 1921 to become the third World Champion.', tags: ['Chess History', 'Capablanca'] },
  { q: 'Who defeated Capablanca in 1927 to become World Champion?', opts: ['Alexander Alekhine', 'Max Euwe', 'Mikhail Botvinnik', 'Emanuel Lasker'], a: 0, e: 'Alexander Alekhine beat Capablanca in a long 1927 match and never granted him a rematch.', tags: ['Chess History', 'Alekhine'] },
  { q: 'Alexander Alekhine holds which unique distinction among world champions?', opts: ['Died while still holding the title', 'Never lost a game', 'Was youngest ever champion', 'Won without a match'], a: 0, e: 'Alekhine is the only champion to die while holding the title, passing away in 1946.', tags: ['Chess History', 'Alekhine'] },
  { q: 'Mikhail Botvinnik is often called the patriarch of which chess tradition?', opts: ['The Soviet school', 'The Romantic school', 'The Italian school', 'The Hypermodern school'], a: 0, e: 'Botvinnik led the dominant Soviet school of chess and shaped its rigorous training methods.', tags: ['Chess History', 'Botvinnik'] },
  { q: 'Botvinnik ran a famous chess school that trained future champions including whom?', opts: ['Karpov and Kasparov', 'Fischer and Morphy', 'Steinitz and Lasker', 'Capablanca and Alekhine'], a: 0, e: 'Botvinnik\'s school helped develop later world champions Anatoly Karpov and Garry Kasparov.', tags: ['Chess History', 'Botvinnik'] },
  { q: 'FIDE, the international chess federation, was founded in which year?', opts: ['1924', '1886', '1948', '1972'], a: 0, e: 'FIDE, the Fédération Internationale des Échecs, was founded in Paris in 1924.', tags: ['Chess History', 'FIDE'] },
  { q: 'After Alekhine\'s death, FIDE organized a 1948 tournament to find a new champion, won by whom?', opts: ['Mikhail Botvinnik', 'Vasily Smyslov', 'Paul Keres', 'Max Euwe'], a: 0, e: 'Botvinnik won the 1948 match-tournament, taking the vacant title and starting Soviet dominance.', tags: ['Chess History', 'Botvinnik'] },

  // ── Level 4 — Famous champions & rivalries ──
  { q: 'Bobby Fischer won the 1972 World Championship by defeating which Soviet champion?', opts: ['Boris Spassky', 'Anatoly Karpov', 'Mikhail Tal', 'Tigran Petrosian'], a: 0, e: 'Fischer beat Boris Spassky in 1972 to become the first American-born undisputed World Champion.', tags: ['Chess History', 'Fischer'] },
  { q: 'The 1972 Fischer–Spassky "Match of the Century" was held in which city?', opts: ['Reykjavik', 'Moscow', 'New York', 'Belgrade'], a: 0, e: 'The Cold War-charged 1972 match took place in Reykjavik, Iceland.', tags: ['Chess History', 'Fischer'] },
  { q: 'How did Anatoly Karpov become World Champion in 1975?', opts: ['Fischer refused to defend the title', 'He won a match with Fischer', 'Botvinnik retired', 'He won a tournament'], a: 0, e: 'Fischer would not play under the agreed conditions, so Karpov was awarded the title in 1975.', tags: ['Chess History', 'Karpov'] },
  { q: 'What was the nationality of Bobby Fischer?', opts: ['American', 'Russian', 'German', 'Icelandic'], a: 0, e: 'Bobby Fischer was an American grandmaster, born in Chicago in 1943.', tags: ['Chess History', 'Fischer'] },
  { q: 'The first Karpov–Kasparov match (1984–85) ended unusually in what way?', opts: ['It was stopped with no winner', 'It ended in a quick draw', 'Karpov resigned the title', 'Kasparov withdrew'], a: 0, e: 'After five months and 48 games, FIDE controversially halted the 1984–85 match with no result.', tags: ['Chess History', 'Rivalries'] },
  { q: 'In 1985 Garry Kasparov became the youngest undisputed World Champion at what age?', opts: ['22', '18', '28', '35'], a: 0, e: 'Kasparov beat Karpov in 1985 at age 22, then a record for the youngest undisputed champion.', tags: ['Chess History', 'Kasparov'] },
  { q: 'In which city was Garry Kasparov born, then part of the Soviet Union?', opts: ['Baku', 'Moscow', 'Kyiv', 'Leningrad'], a: 0, e: 'Kasparov was born in Baku, in Soviet Azerbaijan, in 1963.', tags: ['Chess History', 'Kasparov'] },
  { q: 'In 1993 Kasparov broke away from FIDE to co-found which rival organization?', opts: ['The Professional Chess Association', 'The World Chess League', 'The Grandmasters Union', 'The Elo Federation'], a: 0, e: 'Kasparov and Nigel Short split from FIDE in 1993 to form the Professional Chess Association (PCA).', tags: ['Chess History', 'Kasparov'] },

  // ── Level 5 — The modern era, women's chess & computer chess ──
  { q: 'What is the nationality of Magnus Carlsen, World Champion from 2013 to 2023?', opts: ['Norwegian', 'Swedish', 'Danish', 'Dutch'], a: 0, e: 'Magnus Carlsen, from Norway, dominated the chess world and held the classical title 2013–2023.', tags: ['Chess History', 'Carlsen'] },
  { q: 'Carlsen won the World Championship in 2013 by defeating which long-time champion?', opts: ['Viswanathan Anand', 'Vladimir Kramnik', 'Veselin Topalov', 'Boris Gelfand'], a: 0, e: 'Carlsen beat India\'s Viswanathan Anand in 2013 to claim the World Championship.', tags: ['Chess History', 'Carlsen'] },
  { q: 'Magnus Carlsen set the record for the highest peak rating, reaching over what Elo?', opts: ['2882', '2600', '2700', '3100'], a: 0, e: 'Carlsen reached a peak rating of 2882 in 2014, the highest ever officially recorded.', tags: ['Chess History', 'Carlsen'] },
  { q: 'In 1997 which IBM computer defeated world champion Garry Kasparov in a match?', opts: ['Deep Blue', 'Watson', 'Deep Thought', 'Big Blue'], a: 0, e: 'IBM\'s Deep Blue beat Kasparov in 1997, the first match loss of a champion to a computer.', tags: ['Chess History', 'Computer chess'] },
  { q: 'Judit Polgár, widely regarded as the strongest female player ever, is from which country?', opts: ['Hungary', 'Russia', 'Poland', 'Georgia'], a: 0, e: 'Judit Polgár of Hungary reached world top-ten status, the highest ever by a woman.', tags: ['Chess History', 'Women\'s chess'] },
  { q: 'Vera Menchik became the first Women\'s World Chess Champion in which year?', opts: ['1927', '1950', '1972', '1901'], a: 0, e: 'Vera Menchik won the inaugural Women\'s World Championship in 1927 and dominated women\'s chess.', tags: ['Chess History', 'Women\'s chess'] },
  { q: 'The engine AlphaZero, which taught itself chess by self-play, was developed by which company?', opts: ['DeepMind', 'IBM', 'Microsoft', 'Intel'], a: 0, e: 'AlphaZero, from Google\'s DeepMind, learned chess from scratch by playing millions of games against itself.', tags: ['Chess History', 'Computer chess'] },
  { q: 'Which open-source engine became one of the strongest in the world in the modern era?', opts: ['Stockfish', 'Fritz', 'Rybka', 'ChessMaster'], a: 0, e: 'Stockfish, a free open-source engine, is among the strongest chess programs ever built.', tags: ['Chess History', 'Computer chess'] },
];
