// The Immune & Lymphatic System roadmap questions (40): 5 levels × 8, easiest → hardest.
// Covers innate immunity & barriers, the lymphatic system, adaptive immunity (B & T cells),
// antibodies & immunological memory, and vaccines, allergies & immune disorders.

import type { Seed } from './roadmap-build';

export const immuneSystemSeeds: Seed[] = [
  // ── Level 1 — Innate immunity & physical barriers ──────────────────────
  { q: 'What is the main job of the immune system?', opts: ['To digest food', 'To defend the body against pathogens', 'To pump blood', 'To store fat'], a: 1, e: 'The immune system protects the body against harmful invaders such as bacteria, viruses, fungi, and parasites.', tags: ['Immune System', 'Basics'] },
  { q: 'Which of these is the body\'s largest physical barrier against infection?', opts: ['The skin', 'The liver', 'The kidneys', 'The spleen'], a: 0, e: 'Intact skin forms a tough, continuous barrier that keeps most pathogens from entering the body.', tags: ['Immune System', 'Barriers'] },
  { q: 'Innate immunity is best described as defenses that are:', opts: ['Learned only after infection', 'Present from birth and act quickly', 'Made only by B cells', 'Active only during sleep'], a: 1, e: 'Innate immunity is the body\'s first line of defense: it is present from birth and responds rapidly and non-specifically.', tags: ['Immune System', 'Innate'] },
  { q: 'How does stomach acid help defend the body?', opts: ['It absorbs nutrients', 'It kills many swallowed microbes', 'It produces antibodies', 'It filters the blood'], a: 1, e: 'The strongly acidic environment of the stomach destroys many pathogens that are swallowed with food or mucus.', tags: ['Immune System', 'Barriers'] },
  { q: 'Which white blood cells engulf and "eat" pathogens?', opts: ['Phagocytes', 'Red blood cells', 'Platelets', 'Osteocytes'], a: 0, e: 'Phagocytes, such as macrophages and neutrophils, surround and digest pathogens in a process called phagocytosis.', tags: ['Immune System', 'Innate'] },
  { q: 'What is the purpose of inflammation at a wound?', opts: ['To spread infection', 'To bring immune cells and limit the spread of infection', 'To lower body temperature', 'To stop blood clotting'], a: 1, e: 'Inflammation increases blood flow, bringing immune cells and fluid to the site to fight infection and begin healing.', tags: ['Immune System', 'Innate'] },
  { q: 'Why does the body often develop a fever during infection?', opts: ['To cool the body down', 'Higher temperature slows pathogens and boosts immune activity', 'To stop breathing', 'To increase appetite'], a: 1, e: 'A raised body temperature makes conditions less favorable for many pathogens and speeds up immune responses.', tags: ['Immune System', 'Innate'] },
  { q: 'Mucus in the airways helps defense mainly by:', opts: ['Producing red blood cells', 'Trapping microbes and particles so they can be removed', 'Digesting proteins', 'Cooling inhaled air'], a: 1, e: 'Sticky mucus traps inhaled microbes and dust; tiny hairs called cilia then sweep them out of the airways.', tags: ['Immune System', 'Barriers'] },

  // ── Level 2 — The lymphatic system ─────────────────────────────────────
  { q: 'What fluid flows through the lymphatic vessels?', opts: ['Blood', 'Lymph', 'Bile', 'Urine'], a: 1, e: 'Lymph is a clear fluid, derived from tissue fluid, that circulates through the lymphatic vessels.', tags: ['Immune System', 'Lymphatic'] },
  { q: 'What are lymph nodes best known for?', opts: ['Producing insulin', 'Filtering lymph and housing immune cells', 'Storing bile', 'Pumping blood'], a: 1, e: 'Lymph nodes filter lymph and are sites where immune cells detect pathogens and mount responses.', tags: ['Immune System', 'Lymphatic'] },
  { q: 'Why do lymph nodes sometimes swell when you are sick?', opts: ['They fill with fat', 'Immune cells multiply there to fight infection', 'They fill with air', 'They stop working'], a: 1, e: 'Swollen "glands" are lymph nodes where immune cells are actively multiplying to respond to a nearby infection.', tags: ['Immune System', 'Lymphatic'] },
  { q: 'The lymphatic system also helps the body by:', opts: ['Digesting starch', 'Returning excess tissue fluid to the bloodstream', 'Making red blood cells', 'Producing stomach acid'], a: 1, e: 'Besides immunity, the lymphatic system drains excess fluid from tissues and returns it to the blood.', tags: ['Immune System', 'Lymphatic'] },
  { q: 'What is the main role of the spleen in immunity?', opts: ['Filtering blood and removing old cells and pathogens', 'Producing bile', 'Storing oxygen', 'Making digestive enzymes'], a: 0, e: 'The spleen filters blood, removes worn-out red blood cells, and helps mount immune responses to blood-borne pathogens.', tags: ['Immune System', 'Lymphatic'] },
  { q: 'Where do T cells mature?', opts: ['The thymus', 'The stomach', 'The lungs', 'The pancreas'], a: 0, e: 'T cells (T lymphocytes) mature in the thymus, a gland located behind the breastbone.', tags: ['Immune System', 'Lymphatic'] },
  { q: 'Unlike blood, lymph is moved through its vessels mainly by:', opts: ['The heart pumping directly', 'Skeletal muscle movement and one-way valves', 'Gravity alone', 'Electrical shocks'], a: 1, e: 'The lymphatic system has no central pump; muscle contractions squeeze vessels and valves prevent backflow.', tags: ['Immune System', 'Lymphatic'] },
  { q: 'Lacteals in the small intestine are lymphatic vessels that absorb:', opts: ['Water only', 'Dietary fats', 'Oxygen', 'Glucose'], a: 1, e: 'Lacteals are specialized lymphatic vessels that absorb digested fats from the intestine into the lymph.', tags: ['Immune System', 'Lymphatic'] },

  // ── Level 3 — Adaptive immunity: B cells & T cells ─────────────────────
  { q: 'Adaptive immunity differs from innate immunity because it is:', opts: ['Faster but weaker', 'Specific to particular pathogens and improves with exposure', 'Present only in babies', 'Unable to remember pathogens'], a: 1, e: 'Adaptive immunity targets specific pathogens and grows stronger and faster with repeated exposure.', tags: ['Immune System', 'Adaptive'] },
  { q: 'What is an antigen?', opts: ['A type of sugar', 'A molecule that triggers an immune response', 'A red blood cell', 'A digestive enzyme'], a: 1, e: 'An antigen is a molecule, often on a pathogen\'s surface, that the immune system recognizes and responds to.', tags: ['Immune System', 'Adaptive'] },
  { q: 'What do B cells produce?', opts: ['Antibodies', 'Bile', 'Red blood cells', 'Insulin'], a: 0, e: 'B lymphocytes produce antibodies, proteins that bind specifically to antigens.', tags: ['Immune System', 'Adaptive'] },
  { q: 'What is the main role of helper T cells?', opts: ['To directly digest food', 'To coordinate and activate other immune cells', 'To carry oxygen', 'To clot blood'], a: 1, e: 'Helper T cells release signals that activate B cells, killer T cells, and other parts of the immune response.', tags: ['Immune System', 'Adaptive'] },
  { q: 'Cytotoxic (killer) T cells mainly:', opts: ['Produce antibodies', 'Destroy the body\'s own infected or cancerous cells', 'Store fat', 'Filter lymph'], a: 1, e: 'Cytotoxic T cells recognize and kill body cells that are infected by viruses or that have become cancerous.', tags: ['Immune System', 'Adaptive'] },
  { q: 'Which virus disables the immune system by destroying helper T cells?', opts: ['Influenza', 'HIV', 'Rhinovirus', 'Hepatitis A'], a: 1, e: 'HIV attacks and destroys helper T cells, weakening the immune system and eventually causing AIDS if untreated.', tags: ['Immune System', 'Adaptive'] },
  { q: 'How do antigen-presenting cells help adaptive immunity?', opts: ['They hide antigens from lymphocytes', 'They display antigen fragments to activate T cells', 'They only produce mucus', 'They make platelets'], a: 1, e: 'Cells such as dendritic cells and macrophages present pieces of antigen to T cells, triggering targeted responses.', tags: ['Immune System', 'Adaptive'] },
  { q: 'Clonal selection refers to the process where:', opts: ['All cells divide equally', 'A lymphocyte matching an antigen is selected and multiplied', 'Red blood cells are cloned', 'Antibodies destroy T cells'], a: 1, e: 'When a lymphocyte\'s receptor matches an antigen, that cell is stimulated to divide, producing many identical copies.', tags: ['Immune System', 'Adaptive'] },

  // ── Level 4 — Antibodies & immunological memory ────────────────────────
  { q: 'What is an antibody made of?', opts: ['Carbohydrate', 'Protein', 'Fat', 'Nucleic acid'], a: 1, e: 'Antibodies (immunoglobulins) are Y-shaped proteins produced by B cells (plasma cells).', tags: ['Immune System', 'Antibodies'] },
  { q: 'Each antibody binds to:', opts: ['Any antigen at random', 'A specific antigen that matches its shape', 'Only red blood cells', 'Only fat molecules'], a: 1, e: 'An antibody\'s binding site has a shape complementary to one specific antigen, giving it high specificity.', tags: ['Immune System', 'Antibodies'] },
  { q: 'One way antibodies help destroy pathogens is by:', opts: ['Digesting them with acid', 'Marking (tagging) them for destruction by other cells', 'Turning them into red blood cells', 'Freezing them'], a: 1, e: 'Antibodies coat pathogens (opsonization), tagging them so phagocytes recognize and engulf them more easily.', tags: ['Immune System', 'Antibodies'] },
  { q: 'What is the role of memory cells?', opts: ['To forget past infections', 'To enable a faster, stronger response on re-exposure', 'To make stomach acid', 'To carry oxygen'], a: 1, e: 'Memory B and T cells persist after infection so the immune system reacts much faster if the same pathogen returns.', tags: ['Immune System', 'Memory'] },
  { q: 'Compared with the primary response, the secondary immune response is:', opts: ['Slower and weaker', 'Faster and produces more antibodies', 'Identical', 'Nonexistent'], a: 1, e: 'Thanks to memory cells, the secondary response is quicker and produces far more antibodies, often preventing illness.', tags: ['Immune System', 'Memory'] },
  { q: 'Antibodies passed from mother to baby through breast milk provide:', opts: ['Active immunity', 'Passive immunity', 'No immunity', 'Permanent immunity'], a: 1, e: 'Receiving ready-made antibodies (from milk or the placenta) gives passive immunity, which is temporary.', tags: ['Immune System', 'Memory'] },
  { q: 'Which antibody type is the first produced in large amounts during a new infection?', opts: ['IgM', 'IgE', 'IgD', 'IgA'], a: 0, e: 'IgM is the first antibody class secreted in bulk during the early stage of a primary immune response.', tags: ['Immune System', 'Antibodies'] },
  { q: 'The region of an antigen that an antibody actually binds to is called the:', opts: ['Epitope', 'Nucleus', 'Ribosome', 'Vesicle'], a: 0, e: 'An epitope (antigenic determinant) is the specific part of an antigen recognized by an antibody or receptor.', tags: ['Immune System', 'Antibodies'] },

  // ── Level 5 — Vaccines, allergies & immune disorders ───────────────────
  { q: 'How do vaccines protect against disease?', opts: ['By killing all bacteria in the body', 'By training the immune system to recognize a pathogen safely', 'By replacing blood', 'By providing antibiotics'], a: 1, e: 'Vaccines expose the immune system to harmless antigens so it forms memory cells without causing the disease.', tags: ['Immune System', 'Vaccines'] },
  { q: 'What is herd immunity?', opts: ['Immunity found only in animals', 'Protection of a population when enough people are immune', 'Immunity that lasts one day', 'A type of antibody'], a: 1, e: 'When a large fraction of a population is immune, pathogen spread slows, indirectly protecting those who are not immune.', tags: ['Immune System', 'Vaccines'] },
  { q: 'An allergy is best described as:', opts: ['An immune response to a harmless substance', 'A bacterial infection', 'A vitamin deficiency', 'A type of cancer'], a: 0, e: 'Allergies occur when the immune system overreacts to normally harmless substances (allergens) such as pollen.', tags: ['Immune System', 'Allergies'] },
  { q: 'Which chemical, released during allergic reactions, causes itching and swelling?', opts: ['Histamine', 'Insulin', 'Keratin', 'Melanin'], a: 0, e: 'Mast cells release histamine during allergic reactions, producing symptoms like itching, swelling, and a runny nose.', tags: ['Immune System', 'Allergies'] },
  { q: 'An autoimmune disease is one in which:', opts: ['The immune system attacks the body\'s own cells', 'The body cannot produce blood', 'The skin cannot heal', 'The heart stops pumping'], a: 0, e: 'In autoimmune diseases such as type 1 diabetes, the immune system mistakenly attacks the body\'s own healthy tissues.', tags: ['Immune System', 'Disorders'] },
  { q: 'A severe, whole-body allergic reaction that can be life-threatening is called:', opts: ['Anaphylaxis', 'Anemia', 'Arthritis', 'Asthma'], a: 0, e: 'Anaphylaxis is a rapid, severe allergic reaction that can cause breathing difficulty and a drop in blood pressure.', tags: ['Immune System', 'Allergies'] },
  { q: 'Why must transplant patients often take immunosuppressant drugs?', opts: ['To speed up digestion', 'To stop the immune system from rejecting the donor organ', 'To increase blood pressure', 'To grow new bone'], a: 1, e: 'The immune system may attack a transplanted organ as foreign, so immunosuppressants reduce this rejection response.', tags: ['Immune System', 'Disorders'] },
  { q: 'Why do influenza vaccines need to be updated most years?', opts: ['The vaccine expires monthly', 'The virus mutates, changing its surface antigens', 'People forget their immunity daily', 'Antibodies stop working in winter'], a: 1, e: 'Influenza viruses mutate rapidly (antigenic drift), so their surface antigens change and vaccines must be reformulated.', tags: ['Immune System', 'Vaccines'] },
];
