import type { QuestionTranslation } from './quiz-data';

export const linearAlgebraTranslationsCs: Record<string, QuestionTranslation> = {
  // ── Úroveň 1 — Vektory ──
  'rm-linalg-1': { introduction: 'Zamysli se, co vektor kromě velikosti nese navíc.', question: 'Které tvrzení nejlépe popisuje vektor?', options: ['Veličina, která má velikost i směr', 'Veličina, která má pouze velikost', 'Veličina, která má pouze směr', 'Veličina, která je vždy kladná'], explanation: 'Vektor nese jak velikost (délku), tak směr.' },
  'rm-linalg-2': { introduction: 'První složka odpovídá souřadnici x.', question: 'Jaká je x-ová složka vektoru (3, 4)?', options: ['4', '3', '7', '5'], explanation: 'První prvek vektoru (3, 4) je x-ová složka, tedy 3.' },
  'rm-linalg-3': { introduction: 'Spočítej počet prvků v hranatých závorkách.', question: 'Kolik složek má vektor [1, 2, 3]?', options: ['2', '4', '3', '6'], explanation: 'Vektor [1, 2, 3] má tři prvky, takže je 3-rozměrný.' },
  'rm-linalg-4': { introduction: 'Nulový vektor má všechny složky rovné nule.', question: 'Který vektor je nulový vektor ve 2D?', options: ['(1, 1)', '(0, 0)', '(0, 1)', '(1, 0)'], explanation: 'Nulový vektor má každou složku rovnou 0, takže je to (0, 0).' },
  'rm-linalg-5': { introduction: 'Jednotkový vektor má velikost přesně 1.', question: 'Který z těchto vektorů je jednotkový vektor (velikost 1)?', options: ['(1, 0)', '(1, 1)', '(2, 0)', '(3, 4)'], explanation: 'Velikost vektoru (1, 0) je 1, takže je to jednotkový vektor.' },
  'rm-linalg-6': { introduction: 'Podívej se, která složka je nenulová.', question: 'Kterým směrem míří vektor (0, 5)?', options: ['Podél kladné osy x', 'Podél kladné osy y', 'Diagonálně pod úhlem 45 stupňů', 'Podél záporné osy y'], explanation: 'S nulovou x-ovou složkou a kladnou y-ovou složkou míří (0, 5) nahoru podél osy y.' },
  'rm-linalg-7': { introduction: 'Rovnost vektorů je otázkou všech složek.', question: 'Dva vektory jsou si rovny právě tehdy, když:', options: ['Mají pouze stejnou velikost', 'Mají pouze stejný směr', 'Mají stejné složky', 'Začínají ve stejném bodě'], explanation: 'Vektory jsou si rovny, když se všechny jejich odpovídající složky shodují.' },
  'rm-linalg-8': { introduction: 'Druhý prvek odpovídá souřadnici y.', question: 'Jaká je y-ová složka vektoru (-2, 7)?', options: ['-2', '7', '5', '-7'], explanation: 'Druhý prvek vektoru (-2, 7) je y-ová složka, tedy 7.' },

  // ── Úroveň 2 — Operace s vektory ──
  'rm-linalg-9': { introduction: 'Sčítej po složkách.', question: '(1, 2) + (3, 4) = ?', options: ['(4, 6)', '(3, 8)', '(4, 5)', '(2, 2)'], explanation: 'Sečti po složkách: (1+3, 2+4) = (4, 6).' },
  'rm-linalg-10': { introduction: 'Skalár násobí každou složku.', question: '2 · (3, -1) = ?', options: ['(6, -2)', '(5, 1)', '(6, -1)', '(3, -2)'], explanation: 'Násobení skalárem škáluje každou složku: (2·3, 2·(-1)) = (6, -2).' },
  'rm-linalg-11': { introduction: 'Odčítej po složkách.', question: '(5, 3) - (2, 1) = ?', options: ['(3, 2)', '(7, 4)', '(3, 4)', '(-3, -2)'], explanation: 'Odečti po složkách: (5-2, 3-1) = (3, 2).' },
  'rm-linalg-12': { introduction: 'Použij Pythagorovu větu na složky.', question: 'Jaká je velikost vektoru (3, 4)?', options: ['7', '5', '12', '25'], explanation: 'Velikost je sqrt(3² + 4²) = sqrt(9 + 16) = sqrt(25) = 5.' },
  'rm-linalg-13': { introduction: 'Odmocnina ze součtu druhých mocnin složek.', question: 'Jaká je velikost vektoru (6, 8)?', options: ['10', '14', '48', '100'], explanation: 'Velikost je sqrt(6² + 8²) = sqrt(36 + 64) = sqrt(100) = 10.' },
  'rm-linalg-14': { introduction: 'Vynásob každou složku třemi.', question: '3 · (1, 2, -1) = ?', options: ['(3, 6, -3)', '(3, 5, 2)', '(4, 5, 2)', '(3, 6, -1)'], explanation: 'Vynásob každou složku třemi: (3·1, 3·2, 3·(-1)) = (3, 6, -3).' },
  'rm-linalg-15': { introduction: 'Sčítej po složkách.', question: '(2, 0) + (0, 3) = ?', options: ['(2, 3)', '(0, 0)', '(2, 0)', '(5, 5)'], explanation: 'Sečti po složkách: (2+0, 0+3) = (2, 3).' },
  'rm-linalg-16': { introduction: 'Vyděl vektor jeho velikostí.', question: 'Jednotkový vektor ve směru (0, 4) je:', options: ['(0, 1)', '(0, 4)', '(1, 0)', '(0, 2)'], explanation: 'Vyděl velikostí 4: (0, 4)/4 = (0, 1).' },

  // ── Úroveň 3 — Skalární součin ──
  'rm-linalg-17': { introduction: 'Vynásob odpovídající složky a sečti.', question: '(1, 2) · (3, 4) = ?', options: ['10', '11', '14', '7'], explanation: 'Skalární součin je 1·3 + 2·4 = 3 + 8 = 11.' },
  'rm-linalg-18': { introduction: 'Sečti součiny odpovídajících složek.', question: '(2, 3) · (1, 4) = ?', options: ['14', '11', '7', '24'], explanation: 'Skalární součin je 2·1 + 3·4 = 2 + 12 = 14.' },
  'rm-linalg-19': { introduction: 'Nulový výsledek značí kolmost.', question: '(1, 0) · (0, 1) = ?', options: ['1', '0', '2', '-1'], explanation: 'Skalární součin je 1·0 + 0·1 = 0, takže tyto vektory jsou kolmé.' },
  'rm-linalg-20': { introduction: 'Pozor na záporné složky.', question: '(5, -2) · (3, 4) = ?', options: ['23', '-7', '7', '8'], explanation: 'Skalární součin je 5·3 + (-2)·4 = 15 - 8 = 7.' },
  'rm-linalg-21': { introduction: 'Kolmé vektory mají zvláštní hodnotu skalárního součinu.', question: 'Jsou-li dva nenulové vektory kolmé, jejich skalární součin je:', options: ['1', '0', 'Součin jejich velikostí', 'Nedefinovaný'], explanation: 'Kolmé vektory mají vždy skalární součin roven 0.' },
  'rm-linalg-22': { introduction: 'Sečti tři součiny odpovídajících složek.', question: '(1, 2, 3) · (4, 5, 6) = ?', options: ['32', '21', '28', '45'], explanation: 'Skalární součin je 1·4 + 2·5 + 3·6 = 4 + 10 + 18 = 32.' },
  'rm-linalg-23': { introduction: 'Skalární součin vektoru se sebou samým dává druhou mocninu velikosti.', question: '(3, 4) · (3, 4) = ?', options: ['5', '24', '25', '7'], explanation: 'Vektor skalárně vynásobený sám se sebou dává 3·3 + 4·4 = 9 + 16 = 25, tedy druhou mocninu velikosti.' },
  'rm-linalg-24': { introduction: 'Zkontroluj, zda výsledek vyjde nula.', question: '(2, 2) · (-1, 1) = ?', options: ['4', '0', '-4', '2'], explanation: 'Skalární součin je 2·(-1) + 2·1 = -2 + 2 = 0, takže vektory jsou kolmé.' },

  // ── Úroveň 4 — Matice ──
  'rm-linalg-25': { introduction: 'Rozměry se udávají jako řádky × sloupce.', question: 'Jaké jsou rozměry matice [[1,2],[3,4]]?', options: ['2×2', '2×3', '3×2', '4×1'], explanation: 'Má 2 řádky a 2 sloupce, takže je to matice 2×2.' },
  'rm-linalg-26': { introduction: 'Najdi řádek 2 a v něm třetí prvek.', question: 'V matici [[1,2,3],[4,5,6]] je prvek v řádku 2, sloupci 3:', options: ['3', '5', '2', '6'], explanation: 'Řádek 2 je [4,5,6] a jeho třetí prvek je 6.' },
  'rm-linalg-27': { introduction: 'Jednotková matice má jedničky na hlavní diagonále.', question: 'Jednotková matice 2×2 je:', options: ['[[1,0],[0,1]]', '[[0,1],[1,0]]', '[[1,1],[1,1]]', '[[0,0],[0,0]]'], explanation: 'Jednotková matice má na hlavní diagonále jedničky a jinde nuly: [[1,0],[0,1]].' },
  'rm-linalg-28': { introduction: 'Vynásob počet řádků počtem sloupců.', question: 'Kolik prvků má matice 3×2?', options: ['5', '6', '9', '8'], explanation: 'Počet prvků je řádky × sloupce = 3 × 2 = 6.' },
  'rm-linalg-29': { introduction: 'Transpozice prohodí řádky a sloupce.', question: 'Transpozice matice [[1,2],[3,4]] je:', options: ['[[1,3],[2,4]]', '[[4,3],[2,1]]', '[[2,1],[4,3]]', '[[1,2],[3,4]]'], explanation: 'Transpozice prohodí řádky a sloupce, čímž vznikne [[1,3],[2,4]].' },
  'rm-linalg-30': { introduction: 'Zamysli se nad vztahem počtu řádků a sloupců.', question: 'Čtvercová matice je taková, která má:', options: ['Stejný počet řádků a sloupců', 'Více řádků než sloupců', 'Pouze jeden řádek', 'Pouze jeden sloupec'], explanation: 'Čtvercová matice má stejný počet řádků jako sloupců.' },
  'rm-linalg-31': { introduction: 'Hlavní diagonála jde z levého horního do pravého dolního rohu.', question: 'Hlavní diagonálu matice [[7,2],[5,9]] tvoří:', options: ['2 a 5', '7 a 9', '7 a 2', '5 a 9'], explanation: 'Hlavní diagonála jde z levého horního do pravého dolního rohu: prvky 7 a 9.' },
  'rm-linalg-32': { introduction: 'Jediný řádek prvků má vlastní název.', question: 'Matice [[1,2,3]] je:', options: ['Sloupcový vektor', 'Řádkový vektor', 'Čtvercová matice', 'Nulová matice'], explanation: 'Jediný řádek prvků se nazývá řádkový vektor.' },

  // ── Úroveň 5 — Násobení matic ──
  'rm-linalg-33': { introduction: 'Výsledek přebírá vnější rozměry.', question: 'Násobení matice 2×3 maticí 3×4 dá matici velikosti:', options: ['2×4', '3×3', '2×3', '4×2'], explanation: 'Výsledek přebírá vnější rozměry: 2 řádky a 4 sloupce, tedy 2×4.' },
  'rm-linalg-34': { introduction: 'Vnitřní rozměry se musí shodovat.', question: 'Lze vynásobit matici A (2×3) maticí B (2×3)?', options: ['Ano, vždy', 'Ne, vnitřní rozměry se liší', 'Jen pokud jsou obě čtvercové', 'Jen pokud jsou si rovny'], explanation: 'Aby šlo násobit, počet sloupců A (3) se musí rovnat počtu řádků B (2); protože 3 ≠ 2, je součin nedefinovaný.' },
  'rm-linalg-35': { introduction: 'Násobení jednotkovou maticí nic nemění.', question: '[[1,0],[0,1]] × [[5,6],[7,8]] = ?', options: ['[[5,6],[7,8]]', '[[6,5],[8,7]]', '[[1,0],[0,1]]', '[[5,7],[6,8]]'], explanation: 'Násobení jednotkovou maticí ponechá druhou matici beze změny.' },
  'rm-linalg-36': { introduction: 'Každý řádek skalárně vynásob sloupcem.', question: '[[1,2],[3,4]] × [[1],[1]] = ?', options: ['[3, 7]', '[4, 6]', '[1, 1]', '[7, 3]'], explanation: 'Řádek 1 dá 1·1 + 2·1 = 3 a řádek 2 dá 3·1 + 4·1 = 7, takže výsledek je [3, 7].' },
  'rm-linalg-37': { introduction: 'Násobení matic nemá jednu důležitou vlastnost.', question: 'Pro obecné matice jsou AB a BA:', options: ['Vždy si rovny', 'Ne nutně si rovny, protože násobení není komutativní', 'Vždy navzájem inverzní', 'Vždy jednotková matice'], explanation: 'Násobení matic není komutativní, takže AB se obvykle liší od BA.' },
  'rm-linalg-38': { introduction: 'Skalárně vynásob řádek 1 a sloupec 1.', question: 'Prvek (1,1) matice [[1,2],[3,4]] × [[5,6],[7,8]] je:', options: ['19', '23', '5', '43'], explanation: 'Je to řádek 1 skalárně vynásobený sloupcem 1: 1·5 + 2·7 = 5 + 14 = 19.' },
  'rm-linalg-39': { introduction: 'Diagonální matice 2I škáluje každý prvek.', question: '[[2,0],[0,2]] × [[3,4],[5,6]] = ?', options: ['[[6,8],[10,12]]', '[[5,6],[7,8]]', '[[3,4],[5,6]]', '[[6,4],[10,6]]'], explanation: 'Matice 2I škáluje každý prvek dvěma, čímž vznikne [[6,8],[10,12]].' },
  'rm-linalg-40': { introduction: 'Skalárně vynásob řádek 2 a sloupec 1.', question: 'Prvek (2,1) matice [[1,2],[3,4]] × [[5,6],[7,8]] je:', options: ['31', '43', '23', '50'], explanation: 'Je to řádek 2 skalárně vynásobený sloupcem 1: 3·5 + 4·7 = 15 + 28 = 43.' },

  // ── Úroveň 6 — Determinanty ──
  'rm-linalg-41': { introduction: 'Použij vzorec ad - bc.', question: 'det[[1,2],[3,4]] = ?', options: ['2', '10', '-10', '-2'], explanation: 'Pro [[a,b],[c,d]] je determinant ad - bc = 1·4 - 2·3 = 4 - 6 = -2.' },
  'rm-linalg-42': { introduction: 'Determinant jednotkové matice.', question: 'Determinant jednotkové matice 2×2 [[1,0],[0,1]] je:', options: ['0', '1', '2', '-1'], explanation: 'det = 1·1 - 0·0 = 1.' },
  'rm-linalg-43': { introduction: 'U diagonální matice je to součin prvků na diagonále.', question: 'det[[2,0],[0,3]] = ?', options: ['5', '6', '0', '1'], explanation: 'det = 2·3 - 0·0 = 6, což je součin diagonály u diagonální matice.' },
  'rm-linalg-44': { introduction: 'Připomeň si standardní vzorec pro 2×2.', question: 'Pro matici 2×2 [[a,b],[c,d]] se determinant rovná:', options: ['ad - bc', 'ab - cd', 'ac - bd', 'ad + bc'], explanation: 'Vzorec pro determinant 2×2 je ad - bc.' },
  'rm-linalg-45': { introduction: 'Dosaď do vzorce ad - bc.', question: 'det[[3,1],[2,4]] = ?', options: ['10', '14', '11', '5'], explanation: 'det = 3·4 - 1·2 = 12 - 2 = 10.' },
  'rm-linalg-46': { introduction: 'Nulový determinant má důsledek pro invertovatelnost.', question: 'Má-li matice determinant 0, je:', options: ['Invertovatelná', 'Singulární (neinvertovatelná)', 'Jednotková', 'Symetrická'], explanation: 'Nulový determinant znamená, že matice je singulární a nemá inverzi.' },
  'rm-linalg-47': { introduction: 'Dosaď do vzorce ad - bc.', question: 'det[[5,2],[3,1]] = ?', options: ['1', '-1', '11', '-11'], explanation: 'det = 5·1 - 2·3 = 5 - 6 = -1.' },
  'rm-linalg-48': { introduction: 'Pozor na nuly na diagonále.', question: 'det[[0,1],[1,0]] = ?', options: ['1', '0', '-1', '2'], explanation: 'det = 0·0 - 1·1 = -1.' },

  // ── Úroveň 7 — Inverzní matice ──
  'rm-linalg-49': { introduction: 'Součin matice a její inverze dává jednotkovou matici.', question: 'Inverzní matice A splňuje:', options: ['A · A⁻¹ = I', 'A · A⁻¹ = 0', 'A + A⁻¹ = I', 'A⁻¹ = Aᵀ'], explanation: 'Podle definice dává A násobené svou inverzí jednotkovou matici I.' },
  'rm-linalg-50': { introduction: 'Invertovatelnost souvisí s determinantem.', question: 'Matice 2×2 je invertovatelná právě tehdy, když je její determinant:', options: ['Nulový', 'Nenulový', 'Záporný', 'Roven jedné'], explanation: 'Matice je invertovatelná právě tehdy, když je její determinant nenulový.' },
  'rm-linalg-51': { introduction: 'Prohoď a a d, změň znaménko u b a c.', question: 'Inverze matice [[a,b],[c,d]] se rovná (1/det) krát:', options: ['[[d,-b],[-c,a]]', '[[a,b],[c,d]]', '[[d,b],[c,a]]', '[[-d,b],[c,-a]]'], explanation: 'Prohoď a a d, změň znaménko u b a c a poté vyděl determinantem.' },
  'rm-linalg-52': { introduction: 'Dosaď do vzorce pro inverzi a vyděl determinantem.', question: 'Pro [[1,2],[3,4]] s det = -2 je inverze:', options: ['[[-2, 1],[1.5, -0.5]]', '[[4, -2],[-3, 1]]', '[[2, -1],[-1.5, 0.5]]', '[[1, 2],[3, 4]]'], explanation: '(1/-2)·[[4,-2],[-3,1]] = [[-2, 1],[1.5, -0.5]].' },
  'rm-linalg-53': { introduction: 'Jednotková matice má speciální vlastnost.', question: 'Inverze jednotkové matice je:', options: ['Nulová matice', 'Jednotková matice', 'Nedefinovaná', 'Pouze její transpozice'], explanation: 'Protože I · I = I, je jednotková matice svou vlastní inverzí.' },
  'rm-linalg-54': { introduction: 'Hledej matici s nulovým determinantem.', question: 'Která matice nemá inverzi?', options: ['[[1,2],[2,4]]', '[[1,0],[0,1]]', '[[2,1],[1,1]]', '[[1,2],[3,4]]'], explanation: 'det[[1,2],[2,4]] = 4 - 4 = 0, takže je singulární a neinvertovatelná.' },
  'rm-linalg-55': { introduction: 'U diagonální matice invertuj každý prvek na diagonále.', question: 'Inverze matice [[2,0],[0,4]] je:', options: ['[[0.5, 0],[0, 0.25]]', '[[2, 0],[0, 4]]', '[[4, 0],[0, 2]]', '[[0.25, 0],[0, 0.5]]'], explanation: 'U diagonální matice invertuj každý prvek na diagonále: 1/2 a 1/4.' },
  'rm-linalg-56': { introduction: 'Inverze součinu obrací pořadí.', question: '(AB)⁻¹ se rovná:', options: ['A⁻¹B⁻¹', 'B⁻¹A⁻¹', '(BA)⁻¹', 'AᵀBᵀ'], explanation: 'Inverze součinu obrací pořadí: (AB)⁻¹ = B⁻¹A⁻¹.' },

  // ── Úroveň 8 — Soustavy jako matice ──
  'rm-linalg-57': { introduction: 'Matice koeficientů obsahuje koeficienty u x a y po řádcích.', question: 'Soustava 2x + y = 5, x - y = 1 zapsaná jako Ax = b používá A =', options: ['[[2,1],[1,-1]]', '[[2,1],[1,1]]', '[[1,2],[-1,1]]', '[[2,-1],[1,1]]'], explanation: 'Matice koeficientů obsahuje koeficienty u x a y po řádcích: [[2,1],[1,-1]].' },
  'rm-linalg-58': { introduction: 'x je vektor neznámých.', question: 'V rovnici Ax = b představuje x:', options: ['Matici koeficientů', 'Vektor neznámých', 'Konstanty', 'Determinant'], explanation: 'x je sloupcový vektor obsahující neznámé proměnné.' },
  'rm-linalg-59': { introduction: 'Vynásob obě strany inverzí A.', question: 'Je-li A invertovatelná, řešením soustavy Ax = b je:', options: ['x = A⁻¹b', 'x = Ab', 'x = b - A', 'x = bA⁻¹'], explanation: 'Vynásobením obou stran A⁻¹ dostaneme x = A⁻¹b.' },
  'rm-linalg-60': { introduction: 'Rozšířená matice obsahuje koeficienty i pravé strany.', question: 'Rozšířená matice soustavy x + y = 3, x - y = 1 je:', options: ['[[1,1,3],[1,-1,1]]', '[[1,1],[1,-1]]', '[[3,1],[1,1]]', '[[1,1,1],[1,1,3]]'], explanation: 'Každý řádek obsahuje koeficienty a konstantu: [[1,1,3],[1,-1,1]].' },
  'rm-linalg-61': { introduction: 'Soustava bez řešení má zvláštní název.', question: 'Soustava, která nemá žádné řešení, se nazývá:', options: ['Konzistentní', 'Nekonzistentní (bez řešení)', 'Homogenní', 'Čtvercová'], explanation: 'Soustava bez řešení se označuje jako nekonzistentní.' },
  'rm-linalg-62': { introduction: 'Sečti obě rovnice a vyřeš x.', question: 'Vyřeš x + y = 4 a x - y = 2. Kolik je x?', options: ['1', '2', '4', '3'], explanation: 'Sečtením rovnic dostaneme 2x = 6, takže x = 3 (a y = 1).' },
  'rm-linalg-63': { introduction: 'Nulový vektor vždy vyhovuje homogenní soustavě.', question: 'Homogenní soustava Ax = 0 má vždy:', options: ['Žádné řešení', 'Triviální řešení x = 0', 'Jedno nenulové řešení', 'Vždy nekonečně mnoho řešení'], explanation: 'x = 0 vždy splňuje Ax = 0, takže triviální řešení vždy existuje.' },
  'rm-linalg-64': { introduction: 'Nulový determinant vylučuje jediné řešení.', question: 'Je-li det(A) = 0, pak Ax = b má:', options: ['Vždy právě jedno řešení', 'Buď žádné řešení, nebo nekonečně mnoho', 'Vždy nekonečně mnoho', 'Vždy přesně nula řešení'], explanation: 'Singulární matice znamená, že soustava má buď žádné řešení, nebo nekonečně mnoho.' },

  // ── Úroveň 9 — Lineární zobrazení ──
  'rm-linalg-65': { introduction: 'Linearita zachovává součet.', question: 'Lineární zobrazení T splňuje T(u + v) =', options: ['T(u) · T(v)', 'T(u) + T(v)', 'T(u) - T(v)', 'u + v'], explanation: 'Linearita vyžaduje T(u + v) = T(u) + T(v).' },
  'rm-linalg-66': { introduction: 'Matice 2I násobí každý vektor dvěma.', question: 'Matice [[2,0],[0,2]] představuje:', options: ['Rotaci o 90°', 'Škálování faktorem 2', 'Zrcadlení podle osy x', 'Zkosení'], explanation: 'Násobení maticí 2I zdvojnásobí každý vektor, což je rovnoměrné škálování faktorem 2.' },
  'rm-linalg-67': { introduction: 'Představ si otočení jednotkového vektoru osy x.', question: 'Rotace o 90° proti směru hodinových ručiček zobrazí (1, 0) na:', options: ['(0, 1)', '(0, -1)', '(-1, 0)', '(1, 0)'], explanation: 'Rotace o 90° proti směru hodinových ručiček převede (1, 0) na (0, 1).' },
  'rm-linalg-68': { introduction: 'Sleduj, která složka změní znaménko.', question: 'Matice [[1,0],[0,-1]] zrcadlí vektory podle:', options: ['osy y', 'osy x', 'přímky y = x', 'pouze počátku'], explanation: 'Změní znaménko y-ové složky a x-ovou ponechá, což je zrcadlení podle osy x.' },
  'rm-linalg-69': { introduction: 'Připomeň si, co dělá lineární zobrazení s počátkem.', question: 'Lineární zobrazení vždy zobrazuje počátek na:', options: ['Sebe sama (počátek)', 'Bod (1, 1)', 'Libovolný bod', 'Nekonečno'], explanation: 'Protože T(0) = 0 pro každé lineární zobrazení, počátek zůstává pevný.' },
  'rm-linalg-70': { introduction: 'Faktory škálování leží na diagonále.', question: 'Matice, která škáluje x třemi a y jedním, je:', options: ['[[1,0],[0,3]]', '[[3,0],[0,3]]', '[[3,0],[0,1]]', '[[1,3],[0,1]]'], explanation: 'Prvky na diagonále obsahují faktory škálování: 3 pro x a 1 pro y.' },
  'rm-linalg-71': { introduction: 'Tato matice prohazuje složky.', question: 'Aplikace matice [[0,1],[1,0]] na (2, 5) dá:', options: ['(2, 5)', '(-2, -5)', '(5, 2)', '(7, 7)'], explanation: 'Tato matice prohodí obě složky, čímž z (2, 5) vznikne (5, 2).' },
  'rm-linalg-72': { introduction: 'Sloupce ukazují obrazy bázových vektorů.', question: 'Sloupce matice zobrazení ti říkají:', options: ['Kam se zobrazí bázové vektory', 'Že jde vždy o jednotkovou matici', 'Vlastní čísla', 'Determinant'], explanation: 'Každý sloupec je obrazem jednoho standardního bázového vektoru při daném zobrazení.' },

  // ── Úroveň 10 — Vlastní čísla a vlastní vektory ──
  'rm-linalg-73': { introduction: 'Skalár λ, který škáluje vektor, má vlastní název.', question: 'V rovnici Av = λv se skalár λ nazývá:', options: ['Vlastní vektor', 'Vlastní číslo', 'Determinant', 'Stopa'], explanation: 'Skalár λ, který škáluje v, je vlastní číslo.' },
  'rm-linalg-74': { introduction: 'Nenulový vektor splňující Av = λv má vlastní název.', question: 'Platí-li Av = λv s v ≠ 0, pak v je:', options: ['Skalár', 'Vlastní vektor', 'Nulový vektor', 'Inverze matice A'], explanation: 'Nenulový vektor splňující Av = λv je vlastní vektor matice A.' },
  'rm-linalg-75': { introduction: 'U diagonální matice jsou vlastní čísla prvky na diagonále.', question: 'Vlastní čísla matice [[2,0],[0,3]] jsou:', options: ['5 a 6', '2 a 3', '0 a 0', '2 a 0'], explanation: 'U diagonální matice jsou vlastní čísla prvky na diagonále: 2 a 3.' },
  'rm-linalg-76': { introduction: 'Vlastní čísla jsou kořeny charakteristické rovnice.', question: 'Vlastní čísla se najdou řešením:', options: ['det(A - λI) = 0', 'A - λI = A', 'det(A) = λ', 'Av = 0'], explanation: 'Vlastní čísla jsou kořeny charakteristické rovnice det(A - λI) = 0.' },
  'rm-linalg-77': { introduction: 'Matice 3I posílá každý vektor na jeho trojnásobek.', question: 'Pro [[3,0],[0,3]] je každý nenulový vektor vlastním vektorem s vlastním číslem:', options: ['0', '3', '6', '9'], explanation: 'Protože 3I posílá každé v na 3v, je vlastní číslo 3.' },
  'rm-linalg-78': { introduction: 'U trojúhelníkové matice čti vlastní čísla z diagonály.', question: 'Charakteristická rovnice matice [[2,1],[0,2]] dává vlastní číslo (čísla):', options: ['1 a 2', '0', '2 (dvojnásobné)', '3'], explanation: 'Pro tuto trojúhelníkovou matici dává (2 - λ)² = 0 dvojnásobné λ = 2.' },
  'rm-linalg-79': { introduction: 'Součet vlastních čísel souvisí s diagonálou.', question: 'Součet vlastních čísel matice se rovná její:', options: ['Determinantu', 'Stopě', 'Hodnosti', 'Transpozici'], explanation: 'Vlastní čísla se sčítají na stopu (součet prvků na diagonále).' },
  'rm-linalg-80': { introduction: 'Součin vlastních čísel souvisí s determinantem.', question: 'Součin vlastních čísel matice se rovná jejímu:', options: ['Stopě', 'Součtu diagonály', 'Determinantu', 'Jednotkové matici'], explanation: 'Součin vlastních čísel se rovná determinantu matice.' },
};
