import type { Seed } from './roadmap-build';

// "DevOps & cloud" learning path — 120 questions (15 levels × 8), easiest →
// hardest: CI/CD, build pipelines, containers & orchestration, infrastructure
// as code, cloud fundamentals, deploying to AWS/GCP/Vercel, configuration,
// observability, monitoring, secrets and SRE. (ids rm-devops-1 … 120).
export const devopsSeeds: Seed[] = [
  // Level 1 — What is DevOps?
  { q: 'DevOps is best described as:', opts: ['A single tool you install', 'A culture/practice uniting development and operations to ship reliably and quickly', 'A programming language', 'A type of database'], a: 1, e: 'DevOps is a set of cultural practices and tooling that bring dev and ops together for faster, more reliable delivery.', tags: ['DevOps', 'basics'], intro: 'Start with what DevOps actually means.' },
  { q: 'A core DevOps goal is to:', opts: ['Release once a year', 'Shorten the feedback loop and deliver changes frequently and safely', 'Avoid automation', 'Separate dev and ops further'], a: 1, e: 'DevOps emphasizes automation and collaboration to deliver small changes often, with fast feedback and recovery.', tags: ['DevOps', 'goals'] },
  { q: 'Automation in DevOps mainly reduces:', opts: ['Reliability', 'Manual, error-prone repetitive work (builds, tests, deploys)', 'Test coverage', 'Documentation'], a: 1, e: 'Automating builds, tests, and deployments removes manual toil and human error, making releases repeatable.', tags: ['DevOps', 'automation'] },
  { q: '"You build it, you run it" expresses:', opts: ['Devs never see operations', 'Teams owning their software in production, including its operability', 'Ops writing all code', 'Outsourcing everything'], a: 1, e: 'The phrase captures DevOps ownership: the team that builds a service is responsible for running and supporting it.', tags: ['DevOps', 'ownership'] },
  { q: 'The DORA metrics measure delivery performance via things like:', opts: ['Lines of code', 'Deployment frequency, lead time, change failure rate, and time to restore', 'Number of meetings', 'Server count'], a: 1, e: 'DORA’s four key metrics gauge software delivery: deploy frequency, lead time for changes, change failure rate, and MTTR.', tags: ['DevOps', 'dora'] },
  { q: 'A "blameless postmortem" focuses on:', opts: ['Punishing an individual', 'Learning from incidents by examining systemic causes, not blaming people', 'Hiding failures', 'Avoiding documentation'], a: 1, e: 'Blameless postmortems treat incidents as learning opportunities about the system, encouraging honesty and improvement.', tags: ['DevOps', 'culture'] },
  { q: 'Continuous improvement in DevOps means:', opts: ['Never changing process', 'Iteratively refining pipelines, reliability, and practices over time', 'Doing everything manually', 'Releasing less often'], a: 1, e: 'DevOps treats process and tooling as ever-improving, using feedback and metrics to get steadily better.', tags: ['DevOps', 'improvement'] },
  { q: 'DevOps reduces the risk of each release primarily by:', opts: ['Making releases huge and rare', 'Shipping small, frequent, automated changes that are easy to verify and roll back', 'Skipping tests', 'Avoiding version control'], a: 1, e: 'Small, frequent releases are lower-risk and easier to debug or revert than big-bang deployments.', tags: ['DevOps', 'risk'] },

  // Level 2 — Version Control & Git Flow
  { q: 'Version control (e.g. Git) is foundational to DevOps because it:', opts: ['Stores only backups', 'Tracks changes and is the trigger/source for automated pipelines', 'Replaces testing', 'Hosts the database'], a: 1, e: 'Git is the source of truth; commits and PRs trigger CI/CD and provide history, review, and rollback.', tags: ['Git', 'basics'] },
  { q: 'A pull/merge request enables:', opts: ['Skipping review', 'Code review and automated checks before changes merge', 'Direct production edits', 'Deleting history'], a: 1, e: 'PRs gate changes with review and CI checks, improving quality before merging to the main branch.', tags: ['Git', 'pr'] },
  { q: 'Trunk-based development favors:', opts: ['Many long-lived branches', 'Frequent small merges to a single main branch behind feature flags', 'No branches', 'Never merging'], a: 1, e: 'Trunk-based development integrates small changes into main often, reducing merge pain (using flags to hide unfinished work).', tags: ['Git', 'trunk'] },
  { q: 'Long-lived feature branches risk:', opts: ['Easy merges', 'Painful "merge hell" and delayed integration', 'Faster delivery', 'No conflicts'], a: 1, e: 'The longer a branch diverges, the harder and riskier the eventual merge — frequent integration avoids this.', tags: ['Git', 'branches'] },
  { q: 'A protected main branch typically requires:', opts: ['Nothing', 'Passing CI and review before merging', 'Force pushes', 'Manual deploys only'], a: 1, e: 'Branch protection enforces green checks and approvals, keeping main releasable.', tags: ['Git', 'protection'] },
  { q: 'Semantic versioning (e.g. 2.4.1) communicates:', opts: ['Random numbers', 'MAJOR.MINOR.PATCH — breaking changes, features, and fixes', 'File sizes', 'Commit counts'], a: 1, e: 'SemVer encodes compatibility: bump MAJOR for breaking changes, MINOR for features, PATCH for fixes.', tags: ['Git', 'semver'] },
  { q: 'Tagging a release in Git lets you:', opts: ['Hide the release', 'Mark and reference a specific deployable version', 'Delete history', 'Avoid CI'], a: 1, e: 'Tags mark exact commits as versioned releases, useful for deploys and rollbacks.', tags: ['Git', 'tags'] },
  { q: 'Feature flags allow you to:', opts: ['Only delete code', 'Merge incomplete/feature code to main but keep it off until ready', 'Avoid version control', 'Skip testing'], a: 1, e: 'Flags decouple deploy from release: code ships dark and is enabled later, enabling trunk-based flow and safe rollouts.', tags: ['Git', 'feature-flags'] },

  // Level 3 — CI Basics
  { q: 'Continuous Integration (CI) means:', opts: ['Deploying once a quarter', 'Frequently merging and automatically building/testing changes', 'Manual testing only', 'No automation'], a: 1, e: 'CI integrates code frequently and runs automated builds/tests on each change to catch issues early.', tags: ['CI', 'basics'] },
  { q: 'A CI pipeline is usually triggered by:', opts: ['A calendar reminder', 'A push or pull request to the repository', 'A manual phone call', 'A database write'], a: 1, e: 'CI runs automatically on repository events (push/PR), giving immediate feedback on each change.', tags: ['CI', 'triggers'] },
  { q: 'A typical CI pipeline runs:', opts: ['Only deploys', 'Install deps, lint, build, and test', 'Only the database', 'Nothing'], a: 1, e: 'CI commonly installs dependencies, runs linters/type checks, builds, and executes the test suite.', tags: ['CI', 'stages'] },
  { q: 'CI helps catch integration problems:', opts: ['Months later', 'Early, soon after each change is merged', 'Never', 'Only in production'], a: 1, e: 'By building/testing on every change, CI surfaces integration issues quickly while they’re cheap to fix.', tags: ['CI', 'value'] },
  { q: 'A "broken build" on the main branch should be:', opts: ['Ignored', 'Treated as a priority to fix, since main should stay releasable', 'Left for later', 'Deployed anyway'], a: 1, e: 'Keeping main green is a core CI discipline; a red main blocks everyone and should be fixed promptly.', tags: ['CI', 'discipline'] },
  { q: 'CI configuration is usually stored:', opts: ['Only in someone’s head', 'As code in the repository (e.g. a YAML workflow file)', 'In a spreadsheet', 'In production'], a: 1, e: 'Pipeline-as-code (e.g. GitHub Actions YAML) versions the CI config alongside the app for reproducibility.', tags: ['CI', 'config'] },
  { q: 'Running CI in a clean, fresh environment each time ensures:', opts: ['"Works on my machine" bugs', 'Reproducible builds independent of local machine state', 'Slower feedback always', 'Less reliability'], a: 1, e: 'Ephemeral, clean CI environments avoid hidden local dependencies, making builds reproducible.', tags: ['CI', 'reproducible'] },
  { q: 'A fast CI pipeline matters because:', opts: ['It looks good', 'Quick feedback keeps developers unblocked and merges flowing', 'It uses less code', 'It avoids tests'], a: 1, e: 'Slow CI delays feedback and merges; optimizing pipeline speed keeps the team productive.', tags: ['CI', 'speed'] },

  // Level 4 — CD & Deployment
  { q: 'Continuous Delivery means:', opts: ['Every commit auto-deploys to users', 'Every change is automatically built/tested and kept ready to deploy (release may be a manual click)', 'No deployments', 'Manual builds'], a: 1, e: 'Continuous Delivery keeps the app always in a deployable state; the actual release can be a one-click decision.', tags: ['CD', 'delivery'] },
  { q: 'Continuous Deployment differs by:', opts: ['Never deploying', 'Automatically deploying every passing change to production', 'Requiring manual builds', 'Avoiding tests'], a: 1, e: 'Continuous Deployment goes further than delivery: every change that passes the pipeline ships to production automatically.', tags: ['CD', 'deployment'] },
  { q: 'A blue-green deployment:', opts: ['Deletes the old version immediately', 'Runs two environments and switches traffic to the new one, enabling instant rollback', 'Deploys without testing', 'Only works locally'], a: 1, e: 'Blue-green keeps the old (blue) and new (green) live; you switch traffic to green and can revert instantly if needed.', tags: ['CD', 'blue-green'] },
  { q: 'A canary release:', opts: ['Sends all traffic to the new version at once', 'Gradually routes a small percentage of traffic to the new version to limit risk', 'Skips monitoring', 'Never rolls back'], a: 1, e: 'Canary deploys expose the new version to a small slice of users first, watching metrics before full rollout.', tags: ['CD', 'canary'] },
  { q: 'A rollback is:', opts: ['Deploying a new feature', 'Reverting to a previous known-good version when a deploy fails', 'Deleting the repo', 'Scaling up'], a: 1, e: 'Rollback restores the last good release quickly when a deployment introduces problems.', tags: ['CD', 'rollback'] },
  { q: 'Deploying small changes frequently tends to:', opts: ['Increase risk per release', 'Reduce risk and make failures easier to pinpoint and revert', 'Slow everything', 'Avoid testing'], a: 1, e: 'Smaller deploys change less at once, so they’re lower-risk and easier to debug or roll back.', tags: ['CD', 'small-batches'] },
  { q: 'A rolling deployment:', opts: ['Replaces all instances at once', 'Updates instances incrementally to avoid downtime', 'Requires downtime always', 'Only deploys to one server forever'], a: 1, e: 'Rolling deploys replace instances in batches so the service stays available throughout the update.', tags: ['CD', 'rolling'] },
  { q: 'Decoupling deploy from release (via flags) lets you:', opts: ['Never release', 'Ship code safely and turn features on independently, when ready', 'Avoid version control', 'Skip CI'], a: 1, e: 'Separating deployment from feature activation reduces risk and enables gradual, controlled rollouts.', tags: ['CD', 'flags'] },

  // Level 5 — Build Pipelines
  { q: 'A build step typically:', opts: ['Runs the production database', 'Compiles/bundles source into a deployable artifact', 'Sends emails', 'Deletes code'], a: 1, e: 'The build transforms source (e.g. TS → JS bundle) into an artifact ready to test and deploy.', tags: ['Pipelines', 'build'] },
  { q: 'A pipeline "artifact" is:', opts: ['A bug', 'The built output passed between stages (e.g. a bundle or container image)', 'A log line', 'A secret'], a: 1, e: 'Artifacts are the produced outputs (bundles, images) that later stages test and deploy.', tags: ['Pipelines', 'artifacts'] },
  { q: 'Pipeline stages usually run:', opts: ['In a random order', 'In sequence/with dependencies, often failing fast on the first error', 'All independently always', 'Never'], a: 1, e: 'Stages run in order (build → test → deploy), and a failure typically stops the pipeline early ("fail fast").', tags: ['Pipelines', 'stages'] },
  { q: '"Fail fast" in a pipeline means:', opts: ['Ignore early failures', 'Stop and report on the first failing step to save time', 'Retry forever', 'Deploy on failure'], a: 1, e: 'Failing fast surfaces problems immediately and avoids wasting time on later stages that can’t succeed.', tags: ['Pipelines', 'fail-fast'] },
  { q: 'Building an artifact once and promoting the same artifact through environments avoids:', opts: ['Reproducibility', 'Environment-specific build drift ("it built differently in prod")', 'Testing', 'Versioning'], a: 1, e: 'Build-once, deploy-many ensures the exact tested artifact reaches production, eliminating rebuild differences.', tags: ['Pipelines', 'promotion'] },
  { q: 'Caching dependencies/build outputs in a pipeline:', opts: ['Slows builds', 'Speeds up builds by reusing unchanged work', 'Breaks reproducibility always', 'Is impossible'], a: 1, e: 'Caching reuses unchanged dependencies/outputs to cut build time, as long as cache keys are correct.', tags: ['Pipelines', 'cache'] },
  { q: 'A pipeline should be:', opts: ['Manual and undocumented', 'Defined as code, versioned, and reproducible', 'Different every run', 'Stored only locally'], a: 1, e: 'Pipeline-as-code makes the delivery process reviewable, reproducible, and consistent across runs.', tags: ['Pipelines', 'as-code'] },
  { q: 'Running tests as a pipeline stage before deploy ensures:', opts: ['Faster bugs in prod', 'Only verified artifacts get promoted/deployed', 'No need for tests', 'Random deploys'], a: 1, e: 'Gating deploys on tests prevents shipping artifacts that fail verification.', tags: ['Pipelines', 'gating'] },

  // Level 6 — Containers & Docker
  { q: 'A container packages:', opts: ['Only source code', 'An application with its dependencies into a portable, isolated unit', 'A whole physical server', 'Just a database'], a: 1, e: 'Containers bundle the app and its runtime/dependencies so it runs consistently across environments.', tags: ['Containers', 'basics'] },
  { q: 'A key benefit of containers is:', opts: ['"Works on my machine" problems', 'Consistent environments from dev to prod', 'Larger downloads always', 'No isolation'], a: 1, e: 'Containers package dependencies, so the same image runs identically everywhere, eliminating environment drift.', tags: ['Containers', 'consistency'] },
  { q: 'A Docker image is:', opts: ['A running process', 'A read-only template/blueprint used to create containers', 'A log file', 'A database row'], a: 1, e: 'An image is an immutable snapshot (layers) from which running containers are instantiated.', tags: ['Containers', 'image'] },
  { q: 'A container differs from a VM mainly by:', opts: ['Including a full guest OS each', 'Sharing the host kernel, making it lighter and faster to start', 'Being slower and heavier', 'Needing no OS at all'], a: 1, e: 'Containers share the host OS kernel (no full guest OS), so they’re lighter and start faster than VMs.', tags: ['Containers', 'vs-vm'] },
  { q: 'A Dockerfile is:', opts: ['A running container', 'A script of instructions to build an image', 'A network config', 'A secret store'], a: 1, e: 'A Dockerfile lists steps (base image, copy, install, command) used to build a reproducible image.', tags: ['Containers', 'dockerfile'] },
  { q: 'Docker image layers help by:', opts: ['Making images bigger', 'Caching unchanged steps so rebuilds are faster', 'Encrypting code', 'Removing dependencies'], a: 1, e: 'Each instruction creates a cached layer; unchanged layers are reused, speeding rebuilds.', tags: ['Containers', 'layers'] },
  { q: 'A container registry (e.g. Docker Hub, ECR) is used to:', opts: ['Run containers', 'Store and distribute container images', 'Write Dockerfiles', 'Monitor apps'], a: 1, e: 'Registries host images so they can be pushed from CI and pulled by deploy targets.', tags: ['Containers', 'registry'] },
  { q: 'A multi-stage Docker build helps:', opts: ['Increase final image size', 'Keep the final image small by discarding build-time tools', 'Avoid building', 'Encrypt layers'], a: 1, e: 'Multi-stage builds compile in one stage and copy only the needed output into a slim final image.', tags: ['Containers', 'multi-stage'] },

  // Level 7 — Container Orchestration (Kubernetes)
  { q: 'Container orchestration (e.g. Kubernetes) manages:', opts: ['A single container manually', 'Deploying, scaling, networking, and healing many containers across machines', 'Only source code', 'Just databases'], a: 1, e: 'Orchestrators automate running containers at scale: scheduling, scaling, networking, and self-healing.', tags: ['Kubernetes', 'basics'] },
  { q: 'In Kubernetes, the smallest deployable unit is a:', opts: ['Node', 'Pod', 'Cluster', 'Service'], a: 1, e: 'A Pod wraps one or more tightly-coupled containers; it’s the smallest schedulable unit in Kubernetes.', tags: ['Kubernetes', 'pod'] },
  { q: 'A Kubernetes Deployment is used to:', opts: ['Store secrets', 'Declare and manage a desired number of replica Pods (with rolling updates)', 'Run the database', 'Define DNS'], a: 1, e: 'A Deployment maintains a desired replica count and handles rolling updates/rollbacks of Pods.', tags: ['Kubernetes', 'deployment'] },
  { q: 'A Kubernetes Service provides:', opts: ['Persistent storage', 'A stable network endpoint and load balancing to a set of Pods', 'Image building', 'CI pipelines'], a: 1, e: 'A Service gives a stable address and load-balances traffic across the matching, possibly changing, Pods.', tags: ['Kubernetes', 'service'] },
  { q: 'Kubernetes uses a "desired state" model, meaning:', opts: ['You run imperative commands only', 'You declare the target state and the controller reconciles reality toward it', 'Nothing is automated', 'State is random'], a: 1, e: 'You declare what you want (replicas, image); controllers continuously reconcile actual state to match.', tags: ['Kubernetes', 'declarative'] },
  { q: 'Horizontal Pod Autoscaling adjusts:', opts: ['Node CPU speed', 'The number of Pod replicas based on metrics like CPU/requests', 'The image size', 'The DNS name'], a: 1, e: 'HPA scales replicas up/down according to observed load metrics, automating capacity.', tags: ['Kubernetes', 'hpa'] },
  { q: 'A liveness/readiness probe lets Kubernetes:', opts: ['Encrypt traffic', 'Detect unhealthy/not-ready Pods and restart or stop routing to them', 'Build images', 'Store config'], a: 1, e: 'Probes report Pod health/readiness so Kubernetes can restart crashed Pods and avoid routing to unready ones.', tags: ['Kubernetes', 'probes'] },
  { q: 'A trade-off of Kubernetes is:', opts: ['It is trivially simple', 'Significant operational complexity that may be overkill for small projects', 'It cannot scale', 'No self-healing'], a: 1, e: 'Kubernetes is powerful but complex; simpler platforms (PaaS/serverless) often suffice for small workloads.', tags: ['Kubernetes', 'tradeoffs'] },

  // Level 8 — Infrastructure as Code
  { q: 'Infrastructure as Code (IaC) means:', opts: ['Clicking in a cloud console manually', 'Defining infrastructure in version-controlled config/code that can be applied repeatably', 'Avoiding the cloud', 'Hardcoding IPs in the app'], a: 1, e: 'IaC declares infrastructure (servers, networks) as code, making provisioning repeatable, reviewable, and versioned.', tags: ['IaC', 'basics'] },
  { q: 'A benefit of IaC is:', opts: ['Snowflake servers no one understands', 'Reproducible, documented environments you can recreate on demand', 'Manual drift', 'No version history'], a: 1, e: 'IaC eliminates undocumented "snowflake" servers; environments are reproducible and tracked in version control.', tags: ['IaC', 'benefits'] },
  { q: 'Terraform is an example of a tool that is:', opts: ['Imperative shell scripting', 'Declarative IaC describing desired infrastructure state', 'A container runtime', 'A test framework'], a: 1, e: 'Terraform declares the desired infrastructure; it computes and applies the changes to reach that state.', tags: ['IaC', 'terraform'] },
  { q: '"Configuration drift" is:', opts: ['Code in version control', 'When real infrastructure diverges from its defined/expected state', 'A type of test', 'A deployment'], a: 1, e: 'Drift occurs when manual changes make live infrastructure differ from its IaC definition; IaC re-applies to correct it.', tags: ['IaC', 'drift'] },
  { q: 'Idempotent IaC means applying the same config:', opts: ['Creates duplicates each time', 'Converges to the same state without unintended repeated changes', 'Fails after once', 'Requires manual steps'], a: 1, e: 'Idempotency lets you apply IaC repeatedly and safely; it only changes what’s needed to reach the declared state.', tags: ['IaC', 'idempotent'] },
  { q: 'Immutable infrastructure favors:', opts: ['Patching servers in place forever', 'Replacing servers/images with new versions instead of mutating them', 'No deployments', 'Manual SSH edits'], a: 1, e: 'Immutable infra rebuilds and replaces instances per change, avoiding drift and surprise from in-place mutation.', tags: ['IaC', 'immutable'] },
  { q: 'Storing IaC in version control gives you:', opts: ['No history', 'Review, history, and rollback for infrastructure changes', 'Slower deploys only', 'Less reproducibility'], a: 1, e: 'Versioned IaC brings code-style review, audit history, and rollback to infrastructure changes.', tags: ['IaC', 'vcs'] },
  { q: 'IaC pairs naturally with CI/CD because:', opts: ['It can’t be automated', 'Infrastructure changes can be reviewed and applied through pipelines like app code', 'It forbids automation', 'It needs manual consoles'], a: 1, e: 'Treating infra as code lets pipelines plan/apply changes with the same review and automation as application code.', tags: ['IaC', 'cicd'] },

  // Level 9 — Cloud Fundamentals
  { q: 'Cloud computing provides:', opts: ['Only your own hardware', 'On-demand computing resources over the internet, billed as you use them', 'Free unlimited everything', 'No networking'], a: 1, e: 'Cloud delivers compute, storage, and services on demand with pay-as-you-go pricing, avoiding owning hardware.', tags: ['Cloud', 'basics'] },
  { q: 'IaaS, PaaS, and SaaS differ by:', opts: ['Color', 'How much the provider manages vs you (infrastructure → platform → full software)', 'Programming language', 'Region'], a: 1, e: 'IaaS gives raw infra, PaaS manages the platform/runtime, SaaS delivers complete software — increasing provider responsibility.', tags: ['Cloud', 'service-models'] },
  { q: 'Serverless (e.g. Lambda, Vercel Functions) means:', opts: ['There are literally no servers', 'You run code without managing servers; the provider scales it per request', 'You manage the OS', 'It never scales'], a: 1, e: 'Serverless abstracts servers away: you deploy functions and the platform provisions/scales them automatically.', tags: ['Cloud', 'serverless'] },
  { q: 'Cloud "elasticity" refers to:', opts: ['Fixed capacity', 'Automatically scaling resources up and down with demand', 'Never scaling', 'Manual provisioning only'], a: 1, e: 'Elasticity lets you add capacity during spikes and shed it when idle, matching cost to demand.', tags: ['Cloud', 'elasticity'] },
  { q: 'Object storage (e.g. S3) is best for:', opts: ['Relational transactions', 'Storing large unstructured blobs like images, videos, and backups', 'Running queries with JOINs', 'Hosting a kernel'], a: 1, e: 'Object stores hold large unstructured files cheaply and durably, accessed by key — ideal for media and backups.', tags: ['Cloud', 'storage'] },
  { q: 'Regions and availability zones exist to:', opts: ['Increase latency', 'Provide geographic distribution and fault isolation for resilience', 'Reduce reliability', 'Limit scaling'], a: 1, e: 'Multiple regions/zones let you place workloads near users and survive localized failures.', tags: ['Cloud', 'regions'] },
  { q: 'A pay-as-you-go model means cost is driven by:', opts: ['A flat yearly fee only', 'Actual usage (compute time, storage, requests)', 'Lines of code', 'Number of developers'], a: 1, e: 'Usage-based billing ties cost to consumption, which is efficient but requires monitoring to avoid surprises.', tags: ['Cloud', 'cost'] },
  { q: 'A common cloud cost pitfall is:', opts: ['Turning off unused resources', 'Leaving idle/over-provisioned resources running and racking up charges', 'Using autoscaling', 'Right-sizing instances'], a: 1, e: 'Forgotten idle resources and over-provisioning silently inflate bills; cost monitoring and right-sizing help.', tags: ['Cloud', 'finops'] },

  // Level 10 — Deploying to AWS/GCP/Vercel
  { q: 'A platform like Vercel or Netlify is well-suited to deploying:', opts: ['Bare-metal databases', 'Frontend apps and serverless functions with minimal ops', 'Kubernetes clusters', 'Mainframes'], a: 1, e: 'PaaS platforms (Vercel/Netlify) handle build, CDN, and serverless deploys for frontends/APIs with little ops work.', tags: ['Deploy', 'paas'] },
  { q: 'A static site/SPA is typically deployed by:', opts: ['Running a long-lived server per user', 'Building static assets and serving them via a CDN', 'Compiling on each request', 'A database trigger'], a: 1, e: 'Static frontends build to assets served from a CDN, giving fast, cheap, globally-distributed delivery.', tags: ['Deploy', 'static'] },
  { q: 'On a serverless platform, a "cold start" is:', opts: ['A failed deploy', 'The extra latency when a new function instance must be initialized', 'A database backup', 'A cache hit'], a: 1, e: 'Cold starts add latency when the platform spins up a fresh function instance after idleness.', tags: ['Deploy', 'cold-start'] },
  { q: 'Environment variables are commonly used in deploys to:', opts: ['Store source code', 'Provide per-environment config and secrets without hardcoding them', 'Replace the database', 'Compile code'], a: 1, e: 'Env vars inject configuration/secrets per environment, keeping them out of the codebase.', tags: ['Deploy', 'env'] },
  { q: 'A managed database (e.g. RDS, Cloud SQL) reduces ops by:', opts: ['Making you patch the OS', 'Handling backups, patching, and failover for you', 'Removing all queries', 'Disabling scaling'], a: 1, e: 'Managed databases offload maintenance (backups, patching, HA) so teams focus on the app, not DB ops.', tags: ['Deploy', 'managed-db'] },
  { q: 'A common deploy pattern is to run CI/CD that:', opts: ['Manually copies files over FTP', 'Builds, tests, then deploys the artifact to the cloud automatically', 'Edits production by hand', 'Skips builds'], a: 1, e: 'Automated pipelines build/test and then deploy artifacts to the target platform, removing manual error-prone steps.', tags: ['Deploy', 'cicd'] },
  { q: 'Preview/ephemeral environments per pull request let you:', opts: ['Never test changes', 'Review changes in a live URL before merging to production', 'Deploy to prod directly', 'Avoid CI'], a: 1, e: 'Preview deployments spin up a temporary environment per PR so reviewers can test changes live before merge.', tags: ['Deploy', 'previews'] },
  { q: 'Health checks at the platform/load-balancer level enable:', opts: ['Routing to crashed instances', 'Automatically replacing or skipping unhealthy instances', 'Slower deploys', 'No monitoring'], a: 1, e: 'Health checks let the platform detect bad instances and route around or replace them, keeping the service up.', tags: ['Deploy', 'health'] },

  // Level 11 — Environments & Config
  { q: 'Typical environments in a delivery flow are:', opts: ['Only production', 'Development, staging, and production', 'Just local', 'A single shared one'], a: 1, e: 'Separate dev, staging, and prod environments let you build and validate changes before they reach users.', tags: ['Config', 'environments'] },
  { q: 'Configuration should be separated from code so that:', opts: ['Secrets live in Git', 'The same artifact runs in any environment by changing config', 'You rebuild per environment', 'Config is hardcoded'], a: 1, e: 'The Twelve-Factor principle stores config in the environment, so one build runs anywhere via different config.', tags: ['Config', 'separation'] },
  { q: 'Secrets like API keys should be stored:', opts: ['In the source code', 'In a secrets manager or environment variables, never committed', 'In a public README', 'In client-side JS'], a: 1, e: 'Secrets belong in secret managers/env vars, never in version control or shipped to the client.', tags: ['Config', 'secrets'] },
  { q: 'A staging environment should ideally:', opts: ['Differ wildly from prod', 'Closely mirror production to catch environment-specific issues', 'Have no data', 'Skip the database'], a: 1, e: 'Staging that resembles production surfaces config/integration issues before they hit real users.', tags: ['Config', 'staging'] },
  { q: 'The Twelve-Factor App recommends storing config in:', opts: ['The codebase', 'The environment', 'A spreadsheet', 'The database schema'], a: 1, e: 'Twelve-Factor keeps config in the environment, decoupling it from code and enabling per-deploy values.', tags: ['Config', 'twelve-factor'] },
  { q: 'Using different databases per environment prevents:', opts: ['Any testing', 'Tests/staging from corrupting production data', 'Deployments', 'Config'], a: 1, e: 'Isolated databases per environment ensure non-prod activity can’t touch real user data.', tags: ['Config', 'isolation'] },
  { q: 'Hardcoding environment-specific URLs in the app is problematic because:', opts: ['It is flexible', 'It requires code changes/rebuilds to move between environments', 'It improves config', 'It is required'], a: 1, e: 'Hardcoded URLs couple the build to one environment; externalize them as config instead.', tags: ['Config', 'hardcoding'] },
  { q: 'Validating required config at startup helps by:', opts: ['Hiding misconfiguration', 'Failing fast with a clear error when a needed variable is missing', 'Slowing boot', 'Encrypting nothing'], a: 1, e: 'Checking config on boot surfaces missing/invalid settings immediately, instead of mysterious runtime failures later.', tags: ['Config', 'validation'] },

  // Level 12 — Observability & Logging
  { q: 'Logs are most useful when they are:', opts: ['Random prose with no context', 'Structured and include context (timestamps, request ids, levels)', 'Disabled in production', 'Printed only to one machine'], a: 1, e: 'Structured, contextual logs (JSON, request ids, levels) are searchable and far more useful for debugging at scale.', tags: ['Observability', 'logging'] },
  { q: 'Centralized log aggregation (e.g. ELK, Loki) lets you:', opts: ['Read logs on each server by SSH', 'Search and correlate logs across all services in one place', 'Avoid logging', 'Encrypt the CPU'], a: 1, e: 'Shipping logs to a central store enables cross-service search and correlation, essential for distributed systems.', tags: ['Observability', 'aggregation'] },
  { q: 'Log levels (e.g. debug/info/warn/error) help by:', opts: ['Hiding all logs', 'Letting you filter by severity and control verbosity', 'Encrypting logs', 'Replacing metrics'], a: 1, e: 'Levels let you separate noise from important events and tune verbosity per environment.', tags: ['Observability', 'levels'] },
  { q: 'Metrics are good for:', opts: ['Storing full request bodies', 'Tracking trends/aggregates like latency, error rate, and throughput over time', 'Replacing source code', 'Encrypting data'], a: 1, e: 'Metrics are compact numeric time-series ideal for dashboards and alerting on system health trends.', tags: ['Observability', 'metrics'] },
  { q: 'Distributed tracing is especially valuable in:', opts: ['A single monolith function', 'Microservices, to follow a request across service boundaries', 'CSS files', 'Static sites'], a: 1, e: 'Tracing shows a request’s path across services, pinpointing where latency or errors occur in distributed systems.', tags: ['Observability', 'tracing'] },
  { q: 'A request/correlation id propagated across services lets you:', opts: ['Encrypt requests', 'Tie all logs/traces for one request together', 'Reduce reliability', 'Avoid logging'], a: 1, e: 'A shared correlation id links all telemetry for a single request, making distributed debugging tractable.', tags: ['Observability', 'correlation'] },
  { q: 'Observability differs from plain monitoring by emphasizing:', opts: ['Only predefined dashboards', 'The ability to ask new questions about unknown problems from rich telemetry', 'Less data', 'Manual checks'], a: 1, e: 'Observability is about understanding novel issues from logs/metrics/traces, not just watching known dashboards.', tags: ['Observability', 'concept'] },
  { q: 'Logging sensitive data (passwords, tokens) is:', opts: ['Recommended', 'A security risk to avoid (redact secrets)', 'Required for debugging', 'Harmless'], a: 1, e: 'Never log secrets/PII; redact sensitive fields to avoid leaking them into log storage.', tags: ['Observability', 'security'] },

  // Level 13 — Monitoring & Alerting
  { q: 'Monitoring is primarily about:', opts: ['Writing features', 'Continuously observing system health and detecting problems', 'Deleting logs', 'Compiling code'], a: 1, e: 'Monitoring watches health signals so issues are detected (ideally before users notice).', tags: ['Monitoring', 'basics'] },
  { q: 'A good alert should be:', opts: ['Noisy and frequent', 'Actionable and tied to real user impact', 'Based on every log line', 'Disabled'], a: 1, e: 'Alerts must be actionable and meaningful; noisy alerts cause fatigue and missed real incidents.', tags: ['Monitoring', 'alerts'] },
  { q: '"Alert fatigue" happens when:', opts: ['There are too few alerts', 'So many (often false) alerts fire that responders start ignoring them', 'Alerts are actionable', 'Monitoring is off'], a: 1, e: 'Excessive or low-value alerts desensitize responders, so important alerts get ignored — tune for signal over noise.', tags: ['Monitoring', 'fatigue'] },
  { q: 'MTTR stands for:', opts: ['Mean Time To Repair/Recover', 'Maximum Test Time Rate', 'Multi-Tenant Token Registry', 'Mean Total Traffic Ratio'], a: 0, e: 'MTTR (mean time to recover/repair) measures how quickly you restore service after an incident — a key reliability metric.', tags: ['Monitoring', 'mttr'] },
  { q: 'Synthetic monitoring works by:', opts: ['Only reading logs', 'Periodically running scripted checks against the system to detect outages proactively', 'Waiting for users to complain', 'Disabling alerts'], a: 1, e: 'Synthetic checks simulate user actions on a schedule, catching outages/regressions before real users hit them.', tags: ['Monitoring', 'synthetic'] },
  { q: 'An on-call rotation exists to:', opts: ['Punish engineers', 'Ensure someone is responsible for responding to incidents at any time', 'Avoid monitoring', 'Replace tests'], a: 1, e: 'On-call ensures timely incident response around the clock, sharing the load across the team.', tags: ['Monitoring', 'oncall'] },
  { q: 'A runbook is:', opts: ['A novel', 'Documented steps to diagnose and resolve a known type of incident', 'A test file', 'A Dockerfile'], a: 1, e: 'Runbooks give responders clear, repeatable procedures for handling specific alerts/incidents, speeding recovery.', tags: ['Monitoring', 'runbook'] },
  { q: 'Dashboards are most effective when they:', opts: ['Show every metric possible', 'Highlight key health signals (e.g. golden signals) at a glance', 'Hide errors', 'Update yearly'], a: 1, e: 'Focused dashboards on the most telling signals (latency, errors, traffic, saturation) beat cluttered everything-charts.', tags: ['Monitoring', 'dashboards'] },

  // Level 14 — Secrets & Security in CI
  { q: 'Secrets in CI/CD pipelines should be:', opts: ['Printed in build logs', 'Stored in the platform’s secret store and injected at runtime', 'Committed to the repo', 'Shared in chat'], a: 1, e: 'Use the CI platform’s encrypted secrets and inject them as needed; never commit or log them.', tags: ['Secrets', 'ci'] },
  { q: 'Committing an API key to a public repo means you should:', opts: ['Leave it; it’s fine', 'Treat it as compromised and rotate it immediately', 'Just delete the commit and relax', 'Email it to users'], a: 1, e: 'Once exposed (even briefly), a secret is compromised — rotate it, since history and bots may have captured it.', tags: ['Secrets', 'leak'] },
  { q: 'A secrets manager (e.g. Vault, AWS Secrets Manager) provides:', opts: ['Plaintext files', 'Centralized, access-controlled, auditable secret storage and rotation', 'Public buckets', 'Nothing useful'], a: 1, e: 'Secret managers centralize secrets with access control, auditing, and rotation, far safer than scattered env files.', tags: ['Secrets', 'manager'] },
  { q: 'Least privilege for CI credentials means:', opts: ['Give the pipeline admin on everything', 'Grant only the permissions the pipeline actually needs', 'Use root always', 'Share one key everywhere'], a: 1, e: 'Scoping CI credentials to the minimum needed limits blast radius if they’re ever leaked.', tags: ['Secrets', 'least-privilege'] },
  { q: 'Scanning dependencies for known vulnerabilities (e.g. npm audit) in CI helps:', opts: ['Slow builds for no reason', 'Catch vulnerable packages before they ship', 'Add vulnerabilities', 'Avoid updates'], a: 1, e: 'Automated vulnerability scanning flags risky dependencies early, prompting upgrades before release.', tags: ['Secrets', 'scanning'] },
  { q: 'Pinning/locking dependency versions (lockfiles) helps by:', opts: ['Allowing silent surprise upgrades', 'Ensuring reproducible builds with known, reviewed versions', 'Disabling security', 'Removing dependencies'], a: 1, e: 'Lockfiles pin exact versions so builds are reproducible and surprise (possibly malicious) updates don’t sneak in.', tags: ['Secrets', 'supply-chain'] },
  { q: 'A supply-chain attack targets:', opts: ['Only the UI', 'Dependencies/build tooling to inject malicious code into many downstream apps', 'The CSS', 'The README'], a: 1, e: 'Supply-chain attacks compromise libraries or build pipelines so the malicious code spreads to everyone who depends on them.', tags: ['Secrets', 'supply-chain'] },
  { q: 'CI pipelines that auto-run code from untrusted PRs risk:', opts: ['Nothing', 'Exposing secrets or running malicious code if not properly sandboxed', 'Faster builds', 'Better security'], a: 1, e: 'Running untrusted PR code with access to secrets is dangerous; isolate/limit secrets for fork PRs.', tags: ['Secrets', 'pr-risk'] },

  // Level 15 — Reliability & SRE
  { q: 'Site Reliability Engineering (SRE) applies:', opts: ['Pure manual ops', 'Software-engineering practices to operations and reliability', 'No automation', 'Only frontend work'], a: 1, e: 'SRE treats operations as a software problem, using engineering and automation to run reliable systems.', tags: ['SRE', 'basics'] },
  { q: 'An SLA, SLO, and SLI relate as:', opts: ['All identical', 'SLI measures, SLO targets, SLA is the contractual promise (with consequences)', 'Random terms', 'Only marketing'], a: 1, e: 'SLIs are measured indicators, SLOs are internal targets for them, and SLAs are external commitments with penalties.', tags: ['SRE', 'slo'] },
  { q: 'An error budget represents:', opts: ['Unlimited downtime', 'The allowable amount of unreliability (e.g. 0.1% downtime) before you slow feature work to fix reliability', 'A money budget', 'A test count'], a: 1, e: 'The error budget = 1 − SLO; consuming it signals you should prioritize reliability over new features.', tags: ['SRE', 'error-budget'] },
  { q: 'Reducing "toil" in SRE means:', opts: ['Doing more manual repetitive work', 'Automating away repetitive operational tasks', 'Avoiding monitoring', 'Writing no code'], a: 1, e: 'SRE aims to automate toil (manual, repetitive, scalable-with-load work) so engineers focus on lasting improvements.', tags: ['SRE', 'toil'] },
  { q: 'Redundancy improves reliability by:', opts: ['Adding single points of failure', 'Having backups/replicas so one failure doesn’t cause an outage', 'Reducing capacity', 'Removing monitoring'], a: 1, e: 'Redundant components let the system tolerate individual failures without going down.', tags: ['SRE', 'redundancy'] },
  { q: 'A postmortem after an incident should produce:', opts: ['Blame', 'Action items to prevent recurrence and shared learnings', 'Nothing', 'A deployment'], a: 1, e: 'Effective (blameless) postmortems capture root causes and concrete follow-ups so the same incident doesn’t repeat.', tags: ['SRE', 'postmortem'] },
  { q: 'Capacity planning ensures:', opts: ['Random capacity', 'Enough resources for expected (and peak) load, avoiding outages or waste', 'No scaling', 'Constant downtime'], a: 1, e: 'Planning capacity against forecast load (with headroom for spikes) keeps systems reliable and cost-effective.', tags: ['SRE', 'capacity'] },
  { q: 'The overall aim of DevOps/SRE is to deliver software that is:', opts: ['Shipped slowly and breaks often', 'Released frequently and remains reliable, observable, and recoverable', 'Never deployed', 'Untested'], a: 1, e: 'DevOps/SRE combine speed and stability: ship often while keeping systems reliable, observable, and quick to recover.', tags: ['SRE', 'goal'] },
];
