// Regenerates shared/coding-index.ts: the task summaries the browser needs for
// the Coding section lists, without prompts, tests, or answers.
//   npm run build:coding-index
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { CODING_SUMMARIES } from '../lib/coding/catalog';
import type { CodingTaskSummary } from '../shared/coding-catalog';

export function renderCodingIndex(summaries: readonly CodingTaskSummary[]): string {
  const rows = summaries.map((s) => `  ${JSON.stringify(s)},`).join('\n');
  return `// Generated by scripts/build-coding-index.ts from lib/coding. Do not edit by hand.\n// Summaries only: no prompts, tests, or answers ship to the browser from here.\n\nimport type { CodingTaskSummary } from './coding-catalog';\n\nexport const CODING_INDEX: readonly CodingTaskSummary[] = [\n${rows}\n];\n`;
}

const isMain = process.argv[1] && /build-coding-index/.test(process.argv[1] ?? '') || process.env.CODING_INDEX_WRITE === '1';
if (isMain) {
  const target = path.join(process.cwd(), 'shared', 'coding-index.ts');
  writeFileSync(target, renderCodingIndex(CODING_SUMMARIES));
  console.log(`wrote ${target} (${CODING_SUMMARIES.length} tasks)`);
}
