// Hook contracts: the drift guard between this app's selector and the studio's evaluator,
// plus the rotation guarantees the selector owns.
//
// Run with `npm run test:hooks`. The conformance vectors ship with every `hook-library/1`
// delivery and are generated by the studio's own evaluator — if they and this implementation
// disagree, THIS implementation is wrong.

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { eligibleHooks, renderHookText } from '../shared/hooks/evaluate';
import { parseHookLibrary } from '../shared/hooks/library';
import { EMPTY_HOOK_STATE, recordShown, selectHook, type HookUserState } from '../shared/hooks/select';
import { HookLibraryError, type HookCategoryLists, type HookQuestionContext } from '../shared/hooks/types';

const ROOT = process.cwd();

function readJson<T>(relative: string): T {
  return JSON.parse(readFileSync(join(ROOT, relative), 'utf8')) as T;
}

interface Vector {
  name: string;
  asserts: string;
  subject: HookQuestionContext;
  categoryLists: HookCategoryLists;
  librarySlice: unknown[];
  expectedEligibleIds: string[];
}

interface VectorFile {
  schemaVersion: string;
  surface: string;
  vectors: Vector[];
}

const DEV_LISTS: HookCategoryLists = {
  commonUse: ['javascript', 'typescript', 'git', 'css', 'html', 'react', 'nodejs'],
  interview: ['dsa', 'algorithms', 'system-design', 'databases', 'javascript', 'typescript'],
  core: ['internet', 'git', 'security', 'databases', 'testing'],
};

function main(): void {
  const library = parseHookLibrary(readJson<unknown>('lib/hooks/quiz.hooks.json'));
  const spec = readJson<VectorFile>('lib/hooks/hooks.predicates.spec.json');

  // ── The delivered library ──────────────────────────────────────────────────────────────
  assert.equal(library.length, 49, 'the delivered library is 49 hooks');
  assert.equal(new Set(library.map((hook) => hook.id)).size, library.length, 'hook ids are unique');

  // The three cut ids must not reappear through a delivery, a merge or a hand edit. Two of them
  // were retired for dishonesty rather than taste: `speed-run` promised a ten-second timer to a
  // card that has none, and `looks-easy` warned readers off the intuitive answer, which is a
  // spoiler. `hard-mode` went with them.
  for (const cut of ['speed-run', 'looks-easy', 'hard-mode']) {
    assert.ok(!library.some((hook) => hook.id === cut), `retired hook "${cut}" must not be in the library`);
  }

  // Every hook this app can be asked to render must have a dev variant: devShark is the `dev`
  // vertical and a missing variant would throw at render time on a reader's question.
  for (const hook of library) {
    assert.ok(hook.variants.dev, `hook "${hook.id}" has no dev variant`);
  }

  // ── Conformance vectors: the drift guard ──────────────────────────────────────────────
  assert.equal(spec.schemaVersion, 'hook-predicate-vectors/1');
  assert.equal(spec.surface, 'quiz');
  assert.ok(spec.vectors.length >= 12, 'the vector set covers every predicate and its boundaries');

  for (const vector of spec.vectors) {
    const slice = parseHookLibrary(vector.librarySlice);
    const actual = eligibleHooks(slice, { subject: vector.subject, categoryLists: vector.categoryLists })
      .map((hook) => hook.id);
    assert.deepEqual(
      actual,
      vector.expectedEligibleIds,
      `vector "${vector.name}" (${vector.asserts}) — the studio's evaluator and this one disagree`,
    );
  }

  // The two cases that pin the canonical-English binding specifically, named so a future
  // "let's make it language-aware" cannot pass silently.
  const czechWhy = spec.vectors.find((vector) => vector.name === 'czech-why-english-what');
  assert.ok(czechWhy, 'the canonical-English binding is pinned by a vector');
  assert.ok(
    !czechWhy.expectedEligibleIds.includes('know-why'),
    'a question whose English does not open "Why" is not eligible for know-why, whatever its Czech says',
  );

  // ── Library validation is loud ─────────────────────────────────────────────────────────
  assert.throws(() => parseHookLibrary([]), HookLibraryError, 'an empty delivery fails loudly');
  assert.throws(() => parseHookLibrary('nope'), HookLibraryError, 'a non-array delivery fails loudly');
  assert.throws(
    () => parseHookLibrary([{ id: 'x', cooldownDays: 10, truthRequires: ['missedTopicBefore'], variants: { dev: { en: 'a', cs: 'b' } } }]),
    /Tier B predicate this app has not built yet/,
    'a Tier B gate names itself as unbuilt rather than as unknown',
  );
  assert.throws(
    () => parseHookLibrary([{ id: 'x', cooldownDays: 10, truthRequires: ['difficultyAtLeat:2'], variants: { dev: { en: 'a', cs: 'b' } } }]),
    /not in the quiz predicate vocabulary/,
    'a typo fails closed rather than becoming an always-eligible hook',
  );
  assert.throws(
    () => parseHookLibrary([{ id: 'x', cooldownDays: 10, truthRequires: ['difficultyAtLeast:three'], variants: { dev: { en: 'a', cs: 'b' } } }]),
    /needs a whole number/,
    'a malformed argument is rejected rather than coerced',
  );

  // ── Rendering ──────────────────────────────────────────────────────────────────────────
  const topicHook = library.find((hook) => hook.id === 'topic-audit')!;
  assert.equal(
    renderHookText({ hook: topicHook, vertical: 'dev', lang: 'cs', topic: 'JavaScript' }),
    'Rychlý audit: JavaScript.',
    '{topic} fills from the question category',
  );
  assert.throws(
    () => renderHookText({
      hook: { id: 'leaky', cooldownDays: 10, truthRequires: [{ kind: 'always' }], rawRequires: ['always'], variants: { dev: { en: 'Day {streak}.', cs: 'Den {streak}.' } } },
      vertical: 'dev', lang: 'en', topic: 'x',
    }),
    /still contains \{streak\}/,
    'an unfilled token never reaches the card',
  );

  // ── Starvation: 8 questions a day for 14 days ─────────────────────────────────────────
  // The scenario the pool arithmetic exists for. A daily user over a cooldown window burns
  // through the servable pool, and the LRU fallback is what stands between that and a card
  // with no hook on it. Deterministic `random` so a failure is reproducible.
  let seed = 12_345;
  const random = (): number => {
    seed = (seed * 1_103_515_245 + 12_345) % 2_147_483_648;
    return seed / 2_147_483_648;
  };

  // Deliberately gate-poor days mixed with rich ones: a run of questions that satisfy nothing
  // but `always` is the case that collapses a small pool, and it is why the always pool is
  // twelve rather than five.
  const days: HookQuestionContext[][] = [];
  for (let day = 0; day < 14; day += 1) {
    const questions: HookQuestionContext[] = [];
    for (let index = 0; index < 8; index += 1) {
      const lean = (day + index) % 3 === 0;
      questions.push({
        difficulty: lean ? 1 : ((index % 5) + 1),
        hasCode: !lean && index % 4 === 0,
        category: lean ? 'cool-stuff' : ['javascript', 'git', 'dsa', 'internet'][index % 4]!,
        optionCount: lean ? 2 : 4,
        canonicalEnglishQuestion: index % 6 === 0 ? 'Why does this happen?' : 'What does this return?',
      });
    }
    days.push(questions);
  }

  let persisted: HookUserState = EMPTY_HOOK_STATE;
  let fallbacks = 0;
  let sessionRepeats = 0;

  for (const [dayIndex, questions] of days.entries()) {
    const date = new Date(Date.UTC(2026, 7, 8 + dayIndex)).toISOString().slice(0, 10);
    // A new day is a new session: session memory is per sitting, cooldown is per user.
    let state: HookUserState = { lastShownOn: persisted.lastShownOn, sessionShown: [] };
    const shownToday = new Set<string>();

    for (const subject of questions) {
      const selection = selectHook({
        hooks: library,
        context: { subject, categoryLists: DEV_LISTS },
        state,
        today: date,
        random,
      });

      assert.ok(selection, `day ${dayIndex + 1}: the selector must never return nothing`);
      assert.ok(
        !shownToday.has(selection.hook.id),
        `day ${dayIndex + 1}: "${selection.hook.id}" repeated within one session`,
      );
      // Whatever the fallback path, the hook served is always one the question's own gates
      // licensed. This is the invariant that keeps a starving pool from becoming a lie.
      assert.ok(
        eligibleHooks(library, { subject, categoryLists: DEV_LISTS }).some((hook) => hook.id === selection.hook.id),
        `day ${dayIndex + 1}: "${selection.hook.id}" was served outside its eligible set`,
      );
      // And it always renders: a selected hook with no dev variant would throw on the card.
      renderHookText({ hook: selection.hook, vertical: 'dev', lang: 'en', topic: 'JavaScript' });

      if (selection.reason !== 'fresh') fallbacks += 1;
      if (selection.reason === 'lru-session') sessionRepeats += 1;
      shownToday.add(selection.hook.id);
      state = recordShown(state, selection.hook.id, date);
    }
    persisted = state;
  }

  // 112 impressions over 49 hooks with 6–15 day cooldowns has to lean on the fallback — if it
  // never did, the cooldown would not be doing anything and the assertion above would be vacuous.
  assert.ok(fallbacks > 0, 'the LRU fallback carries the load once cooldowns bite');
  assert.equal(sessionRepeats, 0, 'eight questions a day never exhausts the pool, so nothing repeats in a session');

  process.stdout.write(
    `hook contracts ok — 49 hooks, ${spec.vectors.length} conformance vectors, `
    + `112 simulated impressions, ${fallbacks} served by LRU fallback, 0 session repeats\n`,
  );
}

main();
