import { text, test, type Spec } from './evolving';

/** New requirements are additive; IDs 1–3 and their contracts stay stable. */
export const ADVANCED: Record<string, Partial<Spec>> = {
  'react-evolving-board': {
    prompts: [text('Add "Complete all" and "Clear completed" operating on the entire board regardless of filter. Disable them when there are no active/completed tasks respectively. Each bulk action is one undoable mutation; no-op actions must not create history. Preserve IDs and the current filter.', 'Přidej "Complete all" a "Clear completed" nad celou nástěnkou bez ohledu na filtr. Zakaž je, pokud nejsou aktivní/dokončené úkoly. Hromadná akce tvoří jednu vratnou změnu; no-op nevytváří historii. Zachovej ID a filtr.'),text('Add buttons named "Move up TASK_TEXT" and "Move down TASK_TEXT" in each task row. Move one position in the complete underlying list, not the filtered list. Disable at full-list boundaries. Reordering is undoable and clears redo, while preserving completion and stable IDs. Duplicate names remain independent.', 'Přidej v každém řádku "Move up TEXT_ÚKOLU" a "Move down TEXT_ÚKOLU". Posuň o jednu pozici v úplném seznamu, ne ve filtrovaném. Na hranicích úplného seznamu tlačítka zakaž. Přesun lze vrátit a maže redo; zachovává dokončení i stabilní ID. Duplicitní názvy zůstávají nezávislé.')],
    hints: [text('Route bulk mutations through the same history transition as single-row edits.', 'Hromadné změny veď stejným přechodem historie jako úpravy řádku.'),text('Find the index by ID in the full list, then swap a copied array.', 'Najdi index podle ID v úplném seznamu a prohoď prvky kopie pole.')],
    suites: [`test('bulk operations share history and ignore filter',()=>{render(<App/>);expect(screen.getByRole('button',{name:'Complete all',exact:true}).disabled).toBe(true);add('A');add('B');fireEvent.click(screen.getByRole('button',{name:'Active',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Complete all',exact:true}));expect(screen.getByLabelText('Remaining').textContent).toBe('0');fireEvent.click(screen.getByRole('button',{name:'Undo',exact:true}));expect(screen.getByLabelText('Remaining').textContent).toBe('2');fireEvent.click(screen.getByRole('button',{name:'Redo',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Clear completed',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Undo',exact:true}));fireEvent.click(screen.getByRole('button',{name:'All',exact:true}));expect(screen.getAllByRole('checkbox').length).toBe(2)});`, `test('reorder and undo retain identities',()=>{render(<App/>);add('A');add('B');add('C');expect(screen.getByRole('button',{name:'Move up A',exact:true}).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Move up C',exact:true}));expect(screen.getAllByRole('checkbox')[1].closest('label').textContent).toBe('C');fireEvent.click(screen.getByRole('button',{name:'Undo',exact:true}));expect(screen.getAllByRole('checkbox')[1].closest('label').textContent).toBe('B')});`],
  },
  'react-evolving-catalog': {
    prompts: [text('Add a number input labelled "Maximum price". Empty means no price limit; otherwise include products priced at or below the entered non-negative number. Combine it with search and sorting, reset pagination on changes, and preserve off-page selections and their total. No results keeps the existing empty state.', 'Přidej číselný vstup "Maximum price". Prázdný znamená bez limitu; jinak zahrň produkty s cenou nejvýše zadaného nezáporného čísla. Kombinuj s hledáním a řazením, při změně resetuj stránku a zachovej výběr i součet mimo stránku. Bez výsledků zachovej prázdný stav.'),text('Turn selection into a cart. For every selected product, show a quantity input named "Quantity NAME", even when the product is filtered out. Quantities are integers 1–99, default 1; reject invalid edits by retaining the previous value. Selected total becomes price × quantity. Deselecting removes its quantity, reselecting starts at 1. Select page must not reset existing quantities; Clear selection clears both.', 'Změň výběr na košík. Pro každý vybraný produkt zobraz vstup "Quantity NÁZEV", i když je odfiltrovaný. Množství jsou celá čísla 1–99, výchozí 1; neplatné úpravy odmítni zachováním předchozí hodnoty. Selected total je cena × množství. Odznačení množství smaže a opětovný výběr začíná na 1. Select page nesmí resetovat existující množství; Clear selection smaže obojí.')],
    hints: [text('Derive filtered rows; the cart remains independent of the viewport.', 'Filtrované řádky odvozuj; košík zůstává nezávislý na pohledu.'),text('Key quantities by stable product IDs, not page indexes.', 'Množství ukládej podle stabilních ID produktů, ne indexů stránky.')],
    suites: [`test('price facet combines with pagination and selection',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Select page',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Next',exact:true}));fireEvent.change(screen.getByLabelText('Maximum price'),{target:{value:'1'}});expect(screen.getByLabelText('Page').textContent).toBe('1 / 1');expect(screen.queryByRole('checkbox',{name:'Apple'})).toBeNull();expect(screen.getByRole('checkbox',{name:'Banana'}).checked).toBe(true);expect(screen.getByLabelText('Selected total').textContent).toBe('3')});`, `test('cart quantities survive filtering and idempotent page selection',()=>{render(<App/>);fireEvent.click(screen.getByRole('checkbox',{name:'Apple'}));fireEvent.change(screen.getByLabelText('Quantity Apple'),{target:{value:'3'}});fireEvent.click(screen.getByRole('button',{name:'Select page',exact:true}));expect(screen.getByLabelText('Selected total').textContent).toBe('7');fireEvent.change(screen.getByLabelText('Search'),{target:{value:'Dates'}});expect(screen.getByLabelText('Quantity Apple').value).toBe('3');fireEvent.change(screen.getByLabelText('Quantity Apple'),{target:{value:'0'}});expect(screen.getByLabelText('Quantity Apple').value).toBe('3');fireEvent.click(screen.getByRole('button',{name:'Clear selection',exact:true}));expect(screen.queryByLabelText('Quantity Apple')).toBeNull()});`],
  },
  'react-evolving-form': {
    prompts: [text('On the name step, add a select labelled "Account type" with values personal (default) and business. For business only, show "Company" and require at least two non-space characters before Next; otherwise show "Invalid company" in the alert. Retain the company when switching types, but include it in review and submitted receipt only for business. Back and consent rules stay unchanged.', 'V kroku jména přidej select "Account type" s hodnotami personal (výchozí) a business. Jen pro business zobraz "Company" a před Next vyžaduj alespoň dva neprázdné znaky; jinak alert "Invalid company". Při přepnutí typu firmu zachovej, ale do rekapitulace a potvrzení ji zahrň jen pro business. Pravidla Back a souhlasu zůstávají.'),text('Add explicit "Save draft", "Restore draft", "Clear draft" actions before submission, using localStorage key evolving-form-draft. Save JSON {version:1,email,name,account,company}; never store consent. Restore only well-formed version-1 records with string fields and account personal/business. Resume at the email step with cleared consent/errors; invalid or unavailable storage shows "Draft unavailable" without changing fields. Clear removes the saved record only. Start over also resets account and company.', 'Před odesláním přidej "Save draft", "Restore draft", "Clear draft" s klíčem localStorage evolving-form-draft. Ulož JSON {version:1,email,name,account,company}; nikdy souhlas. Obnov jen platné záznamy verze 1 s řetězcovými poli a account personal/business. Začni v kroku e-mailu bez souhlasu a chyb; neplatné či nedostupné úložiště zobrazí "Draft unavailable" bez změny polí. Clear smaže jen uložený záznam. Start over resetuje také account a company.')],
    hints: [text('Validate only the currently applicable branch, and snapshot the same branch at submission.', 'Validuj jen aktuální větev a při odeslání ulož snímek téže větve.'),text('Parse and validate into a temporary value before changing any React state.', 'Parsuj a validuj do dočasné hodnoty před změnou React stavu.')],
    suites: [`test('business branch validates company and includes it in receipt',()=>{render(<App/>);fireEvent.change(screen.getByLabelText('Email'),{target:{value:'a@b.cz'}});fireEvent.click(screen.getByRole('button',{name:'Next',exact:true}));fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Ada'}});fireEvent.change(screen.getByLabelText('Account type'),{target:{value:'business'}});fireEvent.click(screen.getByRole('button',{name:'Next',exact:true}));expect(screen.getByRole('alert').textContent).toBe('Invalid company');fireEvent.change(screen.getByLabelText('Company'),{target:{value:' Sharks '}});fireEvent.click(screen.getByRole('button',{name:'Next',exact:true}));expect(screen.getByText('Sharks').textContent).toBe('Sharks');fireEvent.click(screen.getByRole('checkbox',{name:'I agree'}));fireEvent.click(screen.getByRole('button',{name:'Submit',exact:true}));expect(screen.getByText('Sharks').textContent).toBe('Sharks')});`, `test('draft validation and explicit restore',()=>{localStorage.removeItem('evolving-form-draft');render(<App/>);fireEvent.change(screen.getByLabelText('Email'),{target:{value:'saved@b.cz'}});fireEvent.click(screen.getByRole('button',{name:'Save draft',exact:true}));fireEvent.change(screen.getByLabelText('Email'),{target:{value:'changed'}});fireEvent.click(screen.getByRole('button',{name:'Restore draft',exact:true}));expect(screen.getByLabelText('Email').value).toBe('saved@b.cz');localStorage.setItem('evolving-form-draft','{"version":2}');fireEvent.click(screen.getByRole('button',{name:'Restore draft',exact:true}));expect(screen.getByRole('alert').textContent).toBe('Draft unavailable');expect(screen.getByLabelText('Email').value).toBe('saved@b.cz');fireEvent.click(screen.getByRole('button',{name:'Clear draft',exact:true}));expect(localStorage.getItem('evolving-form-draft')).toBeNull()});`],
  },
  'js-evolving-calculator': {
    prompts: [text('Add calculateWithVariables(expression, variables). Resolve identifiers matching [A-Za-z_][A-Za-z0-9_]* from own finite-number properties of variables, then use the expression engine. Unknown variables, invalid values and malformed expressions return null. Never mutate variables or evaluate JavaScript.', 'Přidej calculateWithVariables(expression, variables). Identifikátory [A-Za-z_][A-Za-z0-9_]* vyhledej ve vlastních vlastnostech variables s konečnou číselnou hodnotou a použij výrazový engine. Neznámé proměnné, neplatné hodnoty a výrazy vrací null. Neměň variables ani nevyhodnocuj JavaScript.'), text('Add runProgram(lines): return {variables, results}, initially with no variables. Each line is either an expression or NAME = expression. Evaluate in order using calculateWithVariables; assignments update the environment and every line appends its number to results. Reassignment is allowed. Any invalid line makes the entire program return null; empty programs return empty variables and results. Support own keys such as constructor safely.', 'Přidej runProgram(lines): vrať {variables, results}, zpočátku bez proměnných. Řádek je výraz nebo NAME = výraz. Vyhodnocuj postupně pomocí calculateWithVariables; přiřazení mění prostředí a každý řádek přidá číslo do results. Opětovné přiřazení je povolené. Neplatný řádek způsobí null pro celý program; prázdný program vrátí prázdné variables a results. Bezpečně podporuj vlastní klíče jako constructor.')],
    hints: [text('Tokenize identifiers without joining adjacent tokens. Wrap substituted negatives in parentheses.', 'Tokenizuj identifikátory bez spojování sousedních tokenů. Záporné náhrady obal závorkami.'), text('Use a fresh null-prototype environment and validate the assignment name before evaluating its right side.', 'Použij nové prostředí bez prototypu a před vyhodnocením pravé strany ověř název.')],
    tests: [[test('calculateWithVariables("a*(b+2)",{a:-3,b:4})',-18),test('calculateWithVariables("missing+1",{})',null),test('calculateWithVariables("a",{a:Infinity})',null),test('calculateWithVariables("constructor",{})',null)], [test('runProgram(["x = 2", "x = x * 3", "x + 1"])',{variables:{x:6},results:[2,6,7]}),test('runProgram([])',{variables:{},results:[]}),test('runProgram(["x = 1", "y = missing"])',null),test('runProgram(["constructor = 2", "constructor + 3"])',{variables:{constructor:2},results:[2,5]})]],
  },
  'js-evolving-query': {
    prompts: [text('Add groupRows(rows, field, valueField). In first-seen group order, return {key,count,sum} for each strict-equality group. Sum finite numeric valueField values, ignoring other values. Empty input returns []; never mutate rows.', 'Přidej groupRows(rows, field, valueField). V pořadí prvního výskytu vrať {key,count,sum} pro skupiny podle striktní rovnosti. Sečti konečné číselné hodnoty valueField, ostatní ignoruj. Prázdný vstup vrací []; neměň řádky.'), text('Add joinRows(left, right, leftKey, rightKey, mode = "inner"). Return {left:row,right:row} for each matching strict-equality key pair, in left order then right order. Mode "left" also emits unmatched left rows with right:null. Duplicate keys produce all combinations. Do not mutate either input.', 'Přidej joinRows(left, right, leftKey, rightKey, mode = "inner"). Vrať {left:row,right:row} pro každou dvojici se striktně shodnými klíči, v pořadí levého a pak pravého vstupu. Režim "left" přidá nespárované levé řádky s right:null. Duplicitní klíče vytváří všechny kombinace. Neměň vstupy.')],
    hints: [text('Accumulate count and sum independently; every row contributes to count.', 'Počet a součet počítej nezávisle; každý řádek přispívá k počtu.'), text('Build matching arrays per left row and only add null when no match exists.', 'Pro každý levý řádek sestav shody; null přidej pouze bez shody.')],
    tests: [[test('groupRows([{k:"a",v:2},{k:"b",v:3},{k:"a",v:"4"}],"k","v")',[{key:'a',count:2,sum:2},{key:'b',count:1,sum:3}]),test('groupRows([],"k","v")',[]),test('groupRows([{k:1,v:0},{k:"1",v:2}],"k","v")',[{key:1,count:1,sum:0},{key:'1',count:1,sum:2}])],[test('joinRows([{id:1},{id:2}],[{fk:1},{fk:1}],"id","fk","left")',[{left:{id:1},right:{fk:1}},{left:{id:1},right:{fk:1}},{left:{id:2},right:null}]),test('joinRows([{id:1}],[{id:"1"}],"id","id")',[]),test('joinRows([],[],"id","id","left")',[])]],
  },
  'js-evolving-events': {
    prompts: [text('Add createBufferedBus() exposing on/once plus pause(), resume(), emit(). When paused, emit queues event/value pairs and returns []; resume delivers FIFO using the existing bus and returns all listener errors in order. Repeated pause/resume is safe; resume without queued events returns []. A listener may pause during flushing: leave remaining events queued. Listener emissions while not paused dispatch immediately.', 'Přidej createBufferedBus() s on/once a pause(), resume(), emit(). Při pozastavení emit uloží událost a hodnotu do fronty a vrátí []; resume doručí FIFO původní sběrnicí a vrátí chyby posluchačů v pořadí. Opakované pause/resume je bezpečné; bez fronty resume vrací []. Pokud posluchač při doručování pozastaví sběrnici, zbytek zůstane ve frontě. Emit bez pozastavení doručuje hned.'), text('Add createReplayBus(capacity): on(event, listener, replay=false), emit(event,value), clear(event). Retain at most capacity values per event (non-negative integer), oldest first. A replay subscription synchronously receives retained values before future live values; return unsubscribe. clear removes only history, not listeners. emit retains even when no listeners exist and returns listener errors through createBus. Replay listeners in this stage do not throw or emit recursively.', 'Přidej createReplayBus(capacity): on(event, listener, replay=false), emit(event,value), clear(event). Uchovávej nejvýše capacity hodnot na událost (nezáporné celé číslo), od nejstarší. Replay odběr synchronně obdrží historii před budoucími hodnotami; vrať odhlášení. clear smaže jen historii, nikoli posluchače. emit ukládá i bez posluchačů a vrací chyby přes createBus. Replay posluchači v této etapě nevyhazují ani rekurzivně neemitují.')],
    hints: [text('Check the paused flag before every dequeue, not just before the loop.', 'Kontroluj pozastavení před každým vyjmutím z fronty, ne jen před cyklem.'),text('Keep bounded per-event arrays separately from live subscriptions.', 'Omezená pole historie jednotlivých událostí odděl od živých předplatných.')],
    tests: [[test('(()=>{const b=createBufferedBus(),a=[];b.on("x",x=>a.push(x));b.pause();b.emit("x",1);b.emit("x",2);const before=a.slice();b.resume();return [before,a]})()',[[],[1,2]]),test('(()=>{const b=createBufferedBus();b.on("x",()=>{throw "bad"});b.pause();b.emit("x");return b.resume()})()',['bad']),test('(()=>{const b=createBufferedBus(),a=[];b.on("x",v=>{a.push(v);b.pause()});b.pause();b.emit("x",1);b.emit("x",2);b.resume();const first=a.slice();b.resume();return [first,a]})()',[[1],[1,2]])],[test('(()=>{const b=createReplayBus(2),a=[];[1,2,3].forEach(x=>b.emit("x",x));const off=b.on("x",x=>a.push(x),true);b.emit("x",4);off();b.emit("x",5);return a})()',[2,3,4]),test('(()=>{const b=createReplayBus(0),a=[];b.emit("x",1);b.on("x",x=>a.push(x),true);return a})()',[]),test('(()=>{const b=createReplayBus(2),a=[];b.on("x",x=>a.push(x));b.emit("x",1);b.clear("x");b.on("x",x=>a.push(x),true);b.emit("x",2);return a})()',[1,2,2])]],
  },
  'js-evolving-graph': {
    prompts: [text('Add criticalPath(graph, durations). Return {duration, path} for the longest dependency chain, including each node’s finite non-negative duration (default 1). Use plan() validation; invalid graphs or provided invalid durations return null. Resolve ties by the existing depth-first order and dependency-array order. Empty graph returns {duration:0,path:[]}.', 'Přidej criticalPath(graph, durations). Vrať {duration, path} pro nejdelší řetězec závislostí včetně konečné nezáporné délky uzlů (výchozí 1). Validuj přes plan(); neplatný graf či zadaná délka vrací null. Shody rozhoduje původní pořadí průchodu a pole závislostí. Prázdný graf vrací {duration:0,path:[]}.'),text('Add impactedNodes(graph, changed). Return changed nodes and all their transitive dependents in plan() order, without duplicates. Unknown changed IDs or invalid graphs return null. An empty changed list returns []. This models incremental rebuilds: dependencies of a changed node are not rebuilt unless independently affected.', 'Přidej impactedNodes(graph, changed). Vrať změněné uzly a všechny jejich přímé i nepřímé odběratele v pořadí plan(), bez duplicit. Neznámé změněné ID nebo neplatný graf vrací null. Prázdný seznam změn vrací []. Modeluješ inkrementální sestavení: závislosti změněného uzlu se nepřestavují, pokud nejsou samy ovlivněné.')],
    hints: [text('Dynamic programming over topological order gives each node its finish time and predecessor.', 'Dynamické programování v topologickém pořadí určí čas dokončení i předchůdce.'),text('Propagate an affected set forward through dependency-first order.', 'Množinu ovlivněných uzlů rozšiřuj v pořadí závislostí.')],
    tests: [[test('criticalPath({a:[],b:["a"],c:[]},{a:2,b:3,c:4})',{duration:5,path:['a','b']}),test('criticalPath({a:[],b:["a"]},{b:3})',{duration:4,path:['a','b']}),test('criticalPath({}, {})',{duration:0,path:[]}),test('criticalPath({a:[]},{a:-1})',null),test('criticalPath({a:["a"]},{})',null)],[test('impactedNodes({a:[],b:["a"],c:["b"],d:[]},["b"])',['b','c']),test('impactedNodes({a:[],b:["a"]},[])',[]),test('impactedNodes({a:[]},["x"])',null),test('impactedNodes({a:[],b:["a"]},["a","a"])',['a','b'])]],
  },
  'ts-evolving-result': {
    prompts: [text('Add partitionResults<T>(results:readonly Result<T>[]):{values:T[];errors:string[]}. Collect successes and errors independently in input order without mutating input. Unlike collectResults, inspect every result.', 'Přidej partitionResults<T>(results:readonly Result<T>[]):{values:T[];errors:string[]}. Sbírej úspěchy a chyby zvlášť v pořadí vstupu bez jeho změny. Na rozdíl od collectResults prohlédni všechny výsledky.'),text('Add recoverResult<T>(result:Result<T>, recover:(error:string)=>Result<T>):Result<T> and sequenceResults<T>(steps:readonly (()=>Result<T>)[]):Result<T[]>. Recovery only runs on failure; thrown errors become error strings. Sequence executes lazily in order, stops at the first failure or throw, and returns all values on success. Preserve generic types and never widen to any.', 'Přidej recoverResult<T>(result:Result<T>, recover:(error:string)=>Result<T>):Result<T> a sequenceResults<T>(steps:readonly (()=>Result<T>)[]):Result<T[]>. Obnova běží jen po chybě; výjimky se mění na chybové řetězce. Sekvence spouští funkce postupně, skončí při první chybě či výjimce a při úspěchu vrátí všechny hodnoty. Zachovej generické typy bez rozšíření na any.')],
    hints: [text('Narrow the discriminated union before accessing value or error.', 'Před čtením value nebo error zuž diskriminovaný union.'),text('Reuse flatMapResult to capture throws and traverseResults to short-circuit.', 'Znovu použij flatMapResult pro výjimky a traverseResults pro předčasný konec.')],
    tests: [[test('partitionResults([{ok:true,value:1},{ok:false,error:"x"},{ok:true,value:2}])',{values:[1,2],errors:['x']}),test('partitionResults([])',{values:[],errors:[]})],[test('recoverResult({ok:false,error:"x"},e=>({ok:true,value:e.length}))',{ok:true,value:1}),test('recoverResult({ok:true,value:2},()=>{throw "bad"})',{ok:true,value:2}),test('sequenceResults([()=>({ok:true,value:1}),()=>{throw "bad"},()=>({ok:true,value:3})])',{ok:false,error:'bad'})]],
    typeTests: [[{code:'const v:number[]=partitionResults<number>([]).values;'}, {code:'const v:string[]=partitionResults([{ok:true,value:1}]).values;',rejects:true}],[{code:'const r:Result<number[]>=sequenceResults([()=>({ok:true,value:1})]);'},{code:'recoverResult<number>({ok:true,value:1},()=>({ok:true,value:"x"}));',rejects:true}]],
  },
  'ts-evolving-store': {
    prompts: [text('Add selectStore<T,U>(store, select:(value:T)=>U) returning get():U, subscribe(listener:(value:U)=>void):()=>void, dispose():void. Subscribe once to the source store. Notify derived listeners only when Object.is detects a selected-value change, without initial notification. Snapshot listeners. dispose is idempotent, disconnects from source, clears listeners and freezes the last value.', 'Přidej selectStore<T,U>(store, select:(value:T)=>U) s get():U, subscribe(listener:(value:U)=>void):()=>void, dispose():void. Přihlas se jednou ke zdrojovému store. Odběratele informuj jen při změně vybrané hodnoty podle Object.is, ne při přihlášení. Procházej snímek posluchačů. dispose je idempotentní, odpojí zdroj, smaže posluchače a zmrazí poslední hodnotu.'),text('Add transactStore<T>(store, steps:readonly ((value:T)=>T)[]):boolean. Compute all steps privately, then perform one set so subscribers see only the final value and undo treats the transaction as one change. Return false on any thrown error without changing state or history; true on success including no-ops. Steps must be pure (do not mutate their input).', 'Přidej transactStore<T>(store, steps:readonly ((value:T)=>T)[]):boolean. Vypočti kroky soukromě a proveď jediné set, aby odběratelé viděli až výsledek a undo bralo transakci jako jednu změnu. Při výjimce vrať false bez změny stavu či historie; při úspěchu včetně no-op true. Kroky musí být čisté (neměnit vstup).')],
    hints: [text('Cache the last selected value and keep the source unsubscribe function.', 'Ulož poslední vybranou hodnotu a odhlašovací funkci zdroje.'),text('Do not call set from inside the loop; stage the value first.', 'Nevolej set uvnitř cyklu; nejprve připrav výslednou hodnotu.')],
    tests: [[test('(()=>{const s=createStore({n:1}),d=selectStore(s,x=>x.n),a=[];d.subscribe(x=>a.push(x));s.set({n:1});s.set({n:2});d.dispose();s.set({n:3});return [a,d.get()]})()',[[2],2])],[test('(()=>{const s=createStore(1),a=[];s.subscribe(x=>a.push(x));const ok=transactStore(s,[x=>x+1,x=>x*3]);s.undo();return [ok,a,s.get()]})()',[true,[6,1],1]),test('(()=>{const s=createStore(1);return [transactStore(s,[x=>x+1,()=>{throw "bad"}]),s.get(),s.undo()]})()',[false,1,false])]],
    typeTests: [[{code:'const d=selectStore(createStore({n:1}),x=>x.n);const v:number=d.get();'},{code:'selectStore(createStore(1),(s:string)=>s);',rejects:true}],[{code:'const ok:boolean=transactStore(createStore(1),[n=>n+1]);'},{code:'transactStore(createStore(1),[()=>"x"]);',rejects:true}]],
  },
  'ts-evolving-schema': {
    prompts: [text('Add validateRecord(schema:Schema,value:unknown):string[]. Require a non-null non-array object; otherwise return ["$: expected record"]. Validate each own enumerable value against schema, preserving key order and rewriting root paths to $.KEY. Empty records are valid. In this exercise record keys contain only letters, digits and underscores.', 'Přidej validateRecord(schema:Schema,value:unknown):string[]. Vyžaduj nenulový objekt mimo pole, jinak vrať ["$: expected record"]. Každou vlastní enumerable hodnotu validuj schématem, zachovej pořadí klíčů a změň kořen cesty na $.KLÍČ. Prázdné záznamy jsou platné. Klíče v tomto cvičení obsahují jen písmena, číslice a podtržítka.'),text('Add validateUnion(schemas:readonly Schema[],value:unknown):string[]. Accept when any schema validates. If none does, return the shortest branch error list, resolving ties by schema order; empty schemas returns ["$: no alternatives"]. Also add validateTuple(schemas:readonly Schema[],value:unknown):string[]: require an array with exact length, otherwise ["$: expected tuple of length N"], then validate each position and rewrite paths to $[INDEX]. Collect all element errors.', 'Přidej validateUnion(schemas:readonly Schema[],value:unknown):string[]. Přijmi hodnotu, pokud projde některým schématem. Jinak vrať nejkratší seznam chyb větve, při shodě podle pořadí schémat; prázdná schémata vrací ["$: no alternatives"]. Přidej také validateTuple(schemas:readonly Schema[],value:unknown):string[]: vyžaduj pole přesné délky, jinak ["$: expected tuple of length N"], pak validuj pozice s cestami $[INDEX]. Sbírej všechny chyby prvků.')],
    hints: [text('Reuse validate and replace only the leading $, not occurrences inside messages.', 'Použij validate a nahraď pouze počáteční $, nikoli výskyty uvnitř zpráv.'),text('A valid union branch wins immediately; tuple length is checked before elements.', 'Platná větev unionu hned vítězí; délku tuple kontroluj před prvky.')],
    tests: [[test('validateRecord({array:"number"},{a:[1,"x"],b:["z"]})',['$.a[1]: expected number','$.b[0]: expected number']),test('validateRecord("string",[])',['$: expected record']),test('validateRecord("number",{})',[])],[test('validateUnion(["string","number"],2)',[]),test('validateUnion([],1)',['$: no alternatives']),test('validateTuple(["string","number"],[3,"a"])',['$[0]: expected string','$[1]: expected number']),test('validateTuple(["number"],[])',['$: expected tuple of length 1'])]],
    typeTests: [[{code:'const e:string[]=validateRecord("number",{});'},{code:'validateRecord("invalid",{});',rejects:true}],[{code:'const e:string[]=validateTuple(["string"] as const,[1]);'},{code:'validateUnion(["invalid"],1);',rejects:true}]],
  },
};

export function extendSpecs(specs: Record<string, Spec>): Record<string, Spec> {
  return Object.fromEntries(Object.entries(specs).map(([id,spec]) => {
    const extra = ADVANCED[id];
    if (!extra) return [id,spec];
    return [id,{...spec, prompts:[...spec.prompts,...extra.prompts!], hints:[...spec.hints,...extra.hints!],
      ...(spec.tests ? {tests:[...spec.tests,...extra.tests ?? []]} : {}),
      ...(spec.typeTests ? {typeTests:[...spec.typeTests,...extra.typeTests ?? []]} : {}),
      ...(spec.suites ? {suites:[...spec.suites,...extra.suites ?? []]} : {}),
    }];
  }));
}
