// Czech copy for lib/coding/tasks/javascript-loops.ts, keyed by task id. Arrays align by
// index with the English source; the content test enforces parity.

import type { CodingTaskCs } from '../types';

export const JAVASCRIPT_LOOP_TASKS_CS: Record<string, CodingTaskCs> = {
  "js-digit-sum": {
    title: "Ciferný součet",
    prompt: "Napiš funkci `digitSum(n)`, která vrátí součet číslic celého nezáporného čísla, a to cyklem `while` a aritmetikou, ne přes řetězec. `digitSum(493)` dá 16. Jediná číslice je sama svým součtem a `digitSum(0)` dá 0.",
    hints: ["Zbytek po dělení deseti je poslední číslice a zaokrouhlení podílu dolů ji odstraní, takže číslice odlupuj, dokud nic nezbude."],
    approach: [
      "Začni s průběžným součtem na nule.",
      "Dokud je číslo větší než nula, přičti k součtu jeho poslední číslici — zbytek po dělení deseti.",
      "Tu číslici odstraň dělením deseti a zaokrouhlením dolů a nech cyklus číslo zkontrolovat znovu.",
      "Vrať součet; nula do cyklu vůbec nevstoupí a dá nulu.",
    ],
    testLabels: ["", "", "nula má ciferný součet nula", "jediná číslice je sama svým součtem", "nuly uvnitř čísla nic nepřidají"],
  },
  "js-count-multiples": {
    title: "Spočítej násobky",
    prompt: "Napiš funkci `countMultiples(n, from, to)`, která vrátí, kolik celých čísel od `from` do `to` (obě hranice včetně) je dělitelných `n` beze zbytku — použij cyklus `for`, který každé z nich navštíví. `countMultiples(3, 1, 10)` dá 3, za čísla 3, 6 a 9. Nula je násobkem každého `n` a `from` větší než `to` dá 0.",
    hints: ["Projdi každé celé číslo od začátku do konce a nech zbytek po dělení n rozhodnout, jestli se počítá."],
    approach: [
      "Drž si počítadlo, které začíná na nule.",
      "Napiš cyklus for, který začne na první hodnotě a běží, dokud je hodnota nejvýš rovna té poslední, aby se navštívily oba kraje.",
      "Uvnitř přičti jedničku, když je zbytek po dělení n nula.",
      "Vrať počítadlo; když je začátek už za koncem, tělo cyklu se nespustí a odpověď je nula.",
    ],
    testLabels: ["", "", "v rozsahu nejsou žádné násobky", "rozsah s jediným číslem, které je násobkem", "nula se počítá jako násobek", "začátek za koncem dá 0"],
  },
  "js-words-of-length": {
    title: "Slova dané délky",
    prompt: "Napiš funkci `countWordsOfLength(sentence, length)`, která vrátí, kolik slov ve větě má přesně tolik znaků. Slova odděluje jedna mezera; větu rozděl a slova projdi cyklem `for…of`. `countWordsOfLength(\"the cat sat on a mat\", 3)` dá 4 a prázdná věta dá 0.",
    hints: ["Nejdřív větu rozděl podle mezer, pak slova projdi a délku každého porovnej s tou zadanou."],
    approach: [
      "Rozděl větu podle jednotlivých mezer na pole slov.",
      "To pole projdi cyklem for-of s počítadlem, které začíná na nule.",
      "Přičti jedničku pokaždé, když má slovo přesně hledanou délku, a počítadlo vrať.",
    ],
    testLabels: ["", "", "prázdná věta nemá žádná slova", "žádné slovo tu délku nemá", "vyhovuje každé slovo"],
  },
  "js-queue-with-shift": {
    title: "Obsluž frontu",
    prompt: "Napiš funkci `serveNext(queue, newcomer)`. Nově příchozí se přes `push` zařadí na konec fronty a pak přijde na řadu ten, kdo stojí vepředu: odeber ho přes `shift` a vrať jeho jméno. Fronta se mění na místě. Pro `queue = [\"Ana\", \"Bo\"]` vrátí `serveNext(queue, \"Cy\")` `\"Ana\"` a ve `queue` zůstane `[\"Bo\", \"Cy\"]`; prázdná fronta obslouží nově příchozího hned.",
    hints: ["Jedna metoda přidává na konec a druhá odebírá zepředu; obě mění pole, které jsi dostal, a ta odebírající ti vrátí, co odebrala."],
    approach: [
      "Přidej nově příchozího na konec fronty přes push, který pole změní na místě.",
      "Odeber první prvek přes shift a vrať, co ti dá — to je obsloužená osoba.",
      "Ověř prázdný případ: po push je ve frontě přesně jeden člověk, shift ho vrátí a fronta zůstane prázdná.",
    ],
    testLabels: ["", "", "prázdná fronta obslouží nově příchozího hned", "dva tahy po sobě", "čísla se řadí stejně"],
  },
  "js-swap-stack-top": {
    title: "Vyměň vršek",
    prompt: "Napiš funkci `swapTop(stack, item)`, která na místě vymění vršek zásobníku: poslední prvek odeber přes `pop`, na jeho místo dej `item` přes `push` a odebraný prvek vrať. Pro `stack = [1, 2, 3]` vrátí `swapTop(stack, 9)` 3 a ve `stack` zůstane `[1, 2, 9]`. V prázdném zásobníku není co odebrat, takže se `item` jen přidá a vrátí se `undefined`.",
    hints: ["pop sundá poslední prvek a dá ti ho, push jeden přidá a pořadí těch dvou volání rozhoduje, jestli nový prvek skončí pod vrškem, nebo na něm."],
    approach: [
      "Odeber aktuální vršek přes pop a nech si, co vrátí.",
      "Přidej nový prvek přes push, aby se stal vrškem.",
      "Vrať odebranou hodnotu; v prázdném zásobníku pop vrátí undefined, což je přesně požadovaná odpověď.",
    ],
    testLabels: ["", "", "prázdný zásobník jen získá prvek", "zásobník s jediným prvkem", "dvě výměny po sobě"],
  },
  "js-add-to-front": {
    title: "Přidej na začátek",
    prompt: "Napiš funkci `addToFront(list, item)`, která přidá prvek na začátek pole na místě přes `unshift` a vrátí novou délku — přesně to, co `unshift` sám vrací. Pro `list = [2, 3]` vrátí `addToFront(list, 1)` 3 a v `list` zůstane `[1, 2, 3]`. Prázdné pole získá svůj první prvek a vrátí 1.",
    hints: ["Existuje zrcadlový protějšek push: dá prvek na index nula, ostatní posune dál a ohlásí novou délku."],
    approach: [
      "Zavolej na poli unshift s prvkem — pole se změní na místě, takže není co kopírovat.",
      "Vrať, co unshift vrátí, což je nová délka, ne pole.",
    ],
    testLabels: ["", "", "prázdné pole získá svůj první prvek", "pozdější přidání skončí víc vepředu", "pole jako prvek se přidá jako jeden prvek"],
  },
  "js-remove-a-range": {
    title: "Odeber rozsah",
    prompt: "Napiš funkci `removeRange(list, start, count)`, která na místě odebere `count` prvků od indexu `start` přes `splice` a odebrané prvky vrátí jako pole. Pro `list = [1, 2, 3, 4, 5]` vrátí `removeRange(list, 1, 2)` `[2, 3]` a v `list` zůstane `[1, 4, 5]`. Počet nula neodebere nic a počet přesahující konec se zastaví na konci.",
    hints: ["Jedna metoda pole umí na místě odebrat souvislý úsek prvků a zároveň ho vrátit; její první dva argumenty jsou přesně odkud a kolik."],
    approach: [
      "Zavolej na poli splice s počátečním indexem a počtem — prvky se odeberou na místě.",
      "Vrať pole, které splice vrátí; obsahuje odebrané prvky v původním pořadí.",
      "Spolehni se na jeho krajní chování: počet nula neodebere nic a počet přesahující konec se prostě zastaví na konci.",
    ],
    testLabels: ["", "", "počet nula neodebere nic", "počet přesahující konec se zastaví na konci", "odebrání všeho"],
  },
  "js-copy-a-range": {
    title: "Zkopíruj rozsah",
    prompt: "Napiš funkci `copyRange(list, start, end)`, která vrátí nové pole s prvky od indexu `start` až po `end` (bez něj), vzaté přes `slice`, takže původní pole se nikdy nezmění. `copyRange([1, 2, 3, 4], 1, 3)` dá `[2, 3]`. Konec za délkou pole se zastaví na konci a stejné indexy dají prázdné pole.",
    hints: ["Metoda, kterou hledáš, z pole jen čte a nesahá na něj, bere začátek a konec a samotný koncový index vynechá."],
    approach: [
      "Použij slice s počátečním a koncovým indexem — zkopíruje ten úsek do nového pole a originál nikdy nezmění.",
      "Vrať kopii; pamatuj, že koncový index se nezahrnuje a konec za délkou se ořízne na pole.",
    ],
    testLabels: ["", "", "zachová původní pole beze změny", "konec za délkou se zastaví na konci", "stejné indexy dají prázdné pole"],
  },
  "js-insert-at-index": {
    title: "Vlož na index",
    prompt: "Napiš funkci `insertAt(list, index, item)`, která na místě vloží prvek na danou pozici přes `splice`, aniž by něco odebrala, a vrátí pole. `insertAt([1, 3], 1, 2)` dá `[1, 2, 3]`. Index 0 dá prvek na začátek a index rovný délce ho připojí na konec.",
    hints: ["splice umí i přidávat: počet mazaných prvků nula a za ním nový prvek ho vloží na index, aniž by se cokoli ztratilo."],
    approach: [
      "Zavolej na poli splice s indexem, počtem mazaných prvků nula a pak prvkem — tím se vloží bez odebrání.",
      "Vrať samotné pole; splice ho změnil na místě a vrací jen to, co odebral, což tady není nic.",
    ],
    testLabels: ["", "", "index rovný délce připojí na konec", "vložení do prázdného pole", "mění pole na místě"],
  },
  "js-rotate-once": {
    title: "Otoč o jedna",
    prompt: "Napiš funkci `rotateOnce(list)`, která na místě přesune první prvek na konec přes `shift` a `push` a vrátí pole. `rotateOnce([1, 2, 3])` dá `[2, 3, 1]`. Prázdné pole zůstane prázdné — dej pozor, co tam `shift` vrací — a jediný prvek zůstane, kde je.",
    hints: ["První prvek sundej jednou metodou a druhou ho dej na konec — a ověř, co odebírající metoda vrátí, když není co odebrat."],
    approach: [
      "Nejdřív ošetři prázdné pole: shift tam vrátí undefined a jeho push by přidal falešný prvek.",
      "Jinak odeber první prvek přes shift, který ti ho předá.",
      "Ten prvek přidej přes push na konec téhož pole a vrať pole, které se změnilo na místě.",
    ],
    testLabels: ["", "", "prázdné pole zůstane prázdné", "jediný prvek zůstane na místě", "otáčí na místě"],
  },
  "js-last-item-safely": {
    title: "Poslední prvek bezpečně",
    prompt: "Napiš funkci `lastItem(list, fallback)`, která vrátí poslední prvek pole, aniž by pole změnila, nebo `fallback`, když je pole prázdné. `lastItem([1, 2, 3], 0)` dá 3 a `lastItem([], \"none\")` dá `\"none\"`. Poslední prvek, který je náhodou falsy, třeba 0, se vrátí taky, ne náhrada.",
    hints: ["Poslední index je o jedna menší než délka a jen prázdné pole takový index nemá — když to rozhodneš jako první, metoda, která prvek odebírá, zůstane mimo hru."],
    approach: [
      "Nejdřív zkontroluj délku: prázdné pole poslední prvek nemá, takže rovnou vrať náhradu.",
      "Jinak přečti prvek na indexu délka mínus jedna — nebo si vezmi jednoprvkový slice od konce — aby se z pole jen četlo a nic se neměnilo.",
      "Ten prvek vrať tak, jak je, i když je to nula nebo prázdný řetězec; náhrada je jen pro prázdné pole.",
    ],
    testLabels: ["", "", "prázdné pole dá náhradu", "zachová pole beze změny", "falsy poslední prvek je pořád poslední prvek"],
  },
  "js-sum-with-for": {
    title: "Součet cyklem for",
    prompt: "Napiš funkci `addUp(numbers)`, která vrátí součet všech čísel pomocí cyklu `for` s indexem, ne přes `reduce`. `addUp([1, 2, 3])` dá 6. Prázdné pole dá 0 a záporná i desetinná čísla se sčítají jako kterákoli jiná.",
    hints: ["Drž si průběžný součet mimo cyklus a nech index projít od nuly až po délku, ale bez ní."],
    approach: [
      "Před cyklem si založ součet rovný nule.",
      "Napiš cyklus for s indexem, který začne na nule a běží, dokud je menší než délka.",
      "V každém průchodu přičti k součtu prvek na aktuálním indexu a po cyklu součet vrať.",
    ],
    testLabels: ["", "", "prázdný vstup vrátí 0", "záporná čísla se vyruší", "desetinná čísla"],
  },
  "js-count-matches": {
    title: "Spočítej shody",
    prompt: "Napiš funkci `countMatches(items, target)`, která vrátí, kolik prvků je ostře rovno `target`, spočítaných cyklem `for` přes indexy. `countMatches([\"a\", \"b\", \"a\"], \"a\")` dá 2. Žádná shoda nebo prázdné pole dá 0 a řetězec `\"1\"` se nikdy neshoduje s číslem 1.",
    hints: ["Stejný tvar cyklu jako u sčítání, jen se počítadlo pohne, až když je prvek na indexu ostře roven hledané hodnotě."],
    approach: [
      "Začni s počítadlem na nule.",
      "Projdi cyklem s indexem každou pozici a prvek na ní porovnej s hledanou hodnotou přes ostrou rovnost.",
      "Za každou shodu přičti jedničku a na konci počítadlo vrať.",
    ],
    testLabels: ["", "", "prázdný vstup", "nic se neshoduje", "ostré porovnání: řetězec 1 není číslo 1"],
  },
  "js-reverse-in-place": {
    title: "Obrať na místě",
    prompt: "Napiš funkci `reverseInPlace(list)`, která obrátí samotné pole dvěma indexy, které začnou na krajích a prohazováním postupují ke středu, bez `reverse()` a bez kopie, a vrátí totéž pole. `reverseInPlace([1, 2, 3, 4])` dá `[4, 3, 2, 1]`. Lichá délka, jediný prvek i prázdné pole fungují.",
    hints: ["Drž jeden index na každém kraji, prohoď prvky, na které ukazují, a oba indexy posouvej ke středu, dokud se nepotkají nebo nepřekříží."],
    approach: [
      "Nastav jeden index na první pozici a druhý na poslední.",
      "Dokud je levý index menší než pravý, prohoď oba prvky přes pomocnou proměnnou.",
      "Po každém prohození posuň levý index nahoru a pravý dolů.",
      "Vrať samotné pole — jediný prvek ani prázdné pole do cyklu vůbec nevstoupí.",
    ],
    testLabels: ["", "", "mění samotné pole", "prázdný vstup", "jediný prvek"],
  },
  "js-countdown-by-step": {
    title: "Odpočet po krocích",
    prompt: "Napiš funkci `countdownBy(start, step)`, která vrátí hodnoty od `start` dolů po krocích `step`, dokud jsou pořád větší než nula, nasbírané cyklem `while`. `countdownBy(10, 3)` dá `[10, 7, 4, 1]`. Nula se nikdy nezahrne, takže start rovný nule nebo menší dá prázdné pole; předpokládej `step` aspoň 1.",
    hints: ["Na odpočet se hodí cyklus while, protože dopředu nevíš, kolik hodnot bude — pokračuj jen dokud je aktuální hodnota pořád větší než nula."],
    approach: [
      "Začni s prázdným výsledkem a hodnotou rovnou startu.",
      "Dokud je hodnota větší než nula, přidej ji do výsledku a odečti krok.",
      "Vrať výsledek; start rovný nule nebo menší do cyklu vůbec nevstoupí.",
    ],
    testLabels: ["", "", "zastaví se před nulou", "start na nule nedá nic", "krok větší než start", "záporný start nedá nic"],
  },
  "js-first-divisible": {
    title: "První dělitelné",
    prompt: "Napiš funkci `firstDivisible(numbers, divisor)`, která vrátí první číslo v poli dělitelné `divisor` beze zbytku, nebo `null`, když takové není. Pole projdi cyklem `while` a ve chvíli, kdy ho najdeš, použij `break`. `firstDivisible([7, 9, 12, 20], 4)` dá 12 a nula je dělitelná vším.",
    hints: ["Procházej s indexem, dokud je uvnitř pole, a jakmile je zbytek nula, hodnotu si zapamatuj a vyskoč přes break — samotná podmínka cyklu by pokračovala až do konce."],
    approach: [
      "Drž si výsledek, který začíná jako null, a index, který začíná na nule.",
      "Cykli, dokud je index menší než délka, a testuj zbytek prvku na tom indexu.",
      "Při prvním nulovém zbytku prvek ulož a z cyklu vyskoč přes break; jinak posuň index dál.",
      "Vrať uložený výsledek, který zůstane null, když nic nevyhovělo.",
    ],
    testLabels: ["", "", "nic dělitelného dá null", "prázdný vstup", "nula je dělitelná vším"],
  },
  "js-attempt-until": {
    title: "Zkoušej až do úspěchu",
    prompt: "Napiš funkci `attemptUntil(attempt, limit)`. Funkce `attempt` vrátí `true`, když uspěje; zavolej ji aspoň jednou cyklem `do…while` a volej ji dál, dokud neuspěje nebo dokud nepadne `limit` volání. Vrať, kolik volání to zabralo, nebo -1, když neuspělo žádné — s `attempt`, která uspěje při třetím volání, dá `attemptUntil(attempt, 5)` 3.",
    hints: ["Cyklus do…while spustí tělo dřív, než se vůbec podívá na podmínku, což je přesně to pravé, když první pokus musí vždycky proběhnout; podmínka pak potřebuje obojí — ještě neuspělo a volání jsou pořád pod limitem."],
    approach: [
      "Drž si počítadlo volání a příznak posledního výsledku.",
      "Použij do…while, aby tělo proběhlo aspoň jednou: započítej volání, spusť pokus a ulož, co vrátil.",
      "Pokračuj jen dokud pokus selhal a počítadlo je pořád pod limitem.",
      "Po cyklu vrať počítadlo, když příznak hlásí úspěch, a jinak -1.",
    ],
    testLabels: ["", "", "po limitu to vzdá", "úspěch při posledním povoleném volání se pořád počítá", "limit jedna povolí přesně jedno volání"],
  },
  "js-join-with-for-of": {
    title: "Spoj přes for-of",
    prompt: "Napiš funkci `joinWords(words, separator)`, která poskládá jeden řetězec s oddělovačem mezi sousedními slovy pomocí cyklu `for…of`, ne přes `join`. `joinWords([\"a\", \"b\", \"c\"], \"-\")` dá `\"a-b-c\"`. Jediné slovo žádný oddělovač nedostane a prázdné pole dá prázdný řetězec.",
    hints: ["Oddělovač přidej před každé slovo kromě prvního; které je první, ti řekne příznak nebo počítadlo."],
    approach: [
      "Začni s prázdným výsledným řetězcem a příznakem, že zatím žádné slovo přidané není.",
      "Projdi slova cyklem for-of: oddělovač přidej jen tehdy, když už nějaké slovo přidané je, pak přidej slovo a příznak shoď.",
      "Vrať výsledek; bez slov cyklus vůbec neproběhne a vrátí se prázdný řetězec.",
    ],
    testLabels: ["", "", "prázdný vstup dá prázdný řetězec", "jediné slovo nedostane oddělovač", "prázdný oddělovač"],
  },
  "js-number-items": {
    title: "Očísluj položky",
    prompt: "Napiš funkci `numberItems(items)`, která vrátí nové pole, kde se z každé položky stane řetězec z jejího pořadí od jedné, tečky, mezery a položky, pomocí `for…of` přes `items.entries()`, aby ti cyklus předával index i hodnotu najednou. `numberItems([\"milk\", \"eggs\"])` dá `[\"1. milk\", \"2. eggs\"]` a prázdné pole dá prázdné pole.",
    hints: ["Samotný for-of ti dá jen hodnotu; požádej pole o jeho entries a každá otočka ti předá index a hodnotu společně."],
    approach: [
      "Vytvoř prázdné výsledné pole.",
      "Projdi cyklem for-of entries pole a z každé dvojice si vezmi index a hodnotu.",
      "Přidej do výsledku pořadí od jedné, tečku, mezeru a hodnotu jako jeden řetězec a výsledek vrať.",
    ],
    testLabels: ["", "", "prázdný vstup", "jediná položka má číslo jedna", "čísla se zapíšou do řetězce"],
  },
  "js-times-table": {
    title: "Malá násobilka",
    prompt: "Napiš funkci `timesTable(size)`, která vrátí čtvercovou tabulku jako pole řádků, kde buňka v řádku r a sloupci c (oba počítané od 1) obsahuje r krát c, sestavenou jedním cyklem `for` vnořeným do druhého. `timesTable(3)` dá `[[1, 2, 3], [2, 4, 6], [3, 6, 9]]`. `timesTable(0)` dá prázdné pole.",
    hints: ["Jeden cyklus vyrábí řádky a druhý, uvnitř něj, plní každý řádek buňku po buňce — v každém průchodu vnějšího cyklu založ nové pole pro řádek."],
    approach: [
      "Vytvoř prázdnou tabulku.",
      "Projdi číslo řádku od jedné do velikosti; uvnitř založ nový prázdný řádek.",
      "Vnitřním cyklem projdi číslo sloupce od jedné do velikosti a do řádku přidej součin řádku a sloupce.",
      "Po vnitřním cyklu hotový řádek přidej do tabulky a na konci tabulku vrať.",
    ],
    testLabels: ["", "", "velikost nula dá prázdnou tabulku", "jediná buňka", "poslední řádek"],
  },
  "js-some-and-every": {
    title: "Aspoň jeden a všichni",
    prompt: "Napiš funkci `passReport(scores, passMark)`, která vrátí `{ anyPassed, allPassed }`: jestli aspoň jedno skóre dosáhne hranice, zodpovězeno přes `some`, a jestli jí dosáhnou všechna, zodpovězeno přes `every`. `passReport([40, 70], 50)` dá `{ anyPassed: true, allPassed: false }`. Samotná hranice projde a u prázdného pole `some` říká false, zatímco `every` říká true.",
    hints: ["Dvě otázky na stejnou podmínku — dosáhne hranice aspoň jedno skóre a dosáhnou jí všechna — a na každou odpovídá jedna metoda pole booleanem."],
    approach: [
      "Napiš podmínku jednou: skóre se počítá, když je aspoň rovno hranici.",
      "Zeptej se some, jestli ji splňuje některé skóre, a every, jestli ji splňují všechna.",
      "Vrať obě odpovědi v objektu; u prázdného pole some říká false a every true, což je přesně to, co úloha čeká.",
    ],
    testLabels: ["", "", "", "prázdné pole: nikdo neprošel, ale ani nepropadl", "samotná hranice projde"],
  },
  "js-locate-item": {
    title: "Najdi prvek",
    prompt: "Napiš funkci `locate(list, item)`, která vrátí `{ present, index }`: jestli je prvek v poli, zodpovězeno přes `includes`, a pozici jeho prvního výskytu, zodpovězenou přes `indexOf`, která je -1, když chybí. `locate([\"a\", \"b\", \"c\"], \"b\")` dá `{ present: true, index: 1 }`. Obě metody porovnávají ostře, takže řetězec `\"1\"` se nikdy neshoduje s číslem 1.",
    hints: ["Jedna metoda odpoví, jestli tam prvek vůbec je, druhá ti řekne, kde se objeví poprvé, a pro „nikde“ použije -1."],
    approach: [
      "Na boolean použij includes, protože rovnou říká, jestli prvek v poli je.",
      "Na pozici použij indexOf; dá první shodu a -1, když žádná není.",
      "Obojí vrať v objektu s klíči, které úloha pojmenovává.",
    ],
    testLabels: ["", "", "chybějící prvek", "prázdné pole", "vyhrává první pozice", "ostré porovnání"],
  },
  "js-remove-by-id": {
    title: "Odeber podle id",
    prompt: "Napiš funkci `removeById(items, id)`, která z pole na místě odebere první objekt, jehož `id` se rovná zadanému, a odebraný objekt vrátí, nebo vrátí `null`, když žádný nevyhovuje — v tom případě pole zůstane netknuté. Pozici najdi přes `findIndex` a objekt pak vyndej přes `splice`. Pro `items = [{ id: 1 }, { id: 2 }]` vrátí `removeById(items, 2)` `{ id: 2 }` a v `items` zůstane `[{ id: 1 }]`.",
    hints: ["Nejdřív najdi pozici a -1 ber jako „nenalezeno“ ještě před splice — splice na -1 by potichu odebral poslední prvek."],
    approach: [
      "Použij findIndex s callbackem, který porovná id každého objektu s hledaným.",
      "Když vrátí -1, nic nevyhovělo: vrať null a pole nech být.",
      "Jinak na tom indexu odeber přes splice jeden prvek a vrať jediný objekt z pole, které splice vrátí.",
    ],
    testLabels: ["", "", "chybějící id nic neodebere", "prázdné pole", "odebere se jen první shoda"],
  },
  "js-highest-with-reduce": {
    title: "Maximum přes reduce",
    prompt: "Napiš funkci `highest(numbers)`, která vrátí největší hodnotu pomocí `reduce`, kde akumulátor drží dosud nejlepší hodnotu. `highest([3, 9, 2])` dá 9. Musí fungovat, i když jsou všechny hodnoty záporné, a prázdné pole dá `null` — `reduce` bez počáteční hodnoty na něm vyhodí chybu, takže tenhle případ rozhodni jako první.",
    hints: ["Nech akumulátor být dosud nejlepší hodnotou; bez počáteční hodnoty začne reduce od prvního prvku, čímž obejde past začínání od nuly, když je všechno záporné."],
    approach: [
      "Pro prázdné pole rovnou vrať null, protože reduce bez počáteční hodnoty na něm vyhodí chybu.",
      "Použij reduce s akumulátorem, který drží dosud nejlepší hodnotu a začíná od prvního prvku.",
      "V každém kroku si nech větší z akumulátoru a aktuálního čísla.",
    ],
    testLabels: ["", "", "samá záporná čísla", "prázdný vstup dá null", "jediná hodnota"],
  },
  "js-count-by-key": {
    title: "Počty podle klíče",
    prompt: "Napiš funkci `countBy(items, keyFn)`, která vrátí objekt mapující každý klíč vrácený z `keyFn` na počet položek, které ho daly, sestavený přes `reduce` od prázdného objektu. `countBy([\"apple\", \"avocado\", \"banana\"], word => word[0])` dá `{ a: 2, b: 1 }`. Prázdné pole dá prázdný objekt a číselný klíč se stane řetězcem, jak to u klíčů objektu bývá vždycky.",
    hints: ["Redukuj do objektu, který začíná prázdný, a u každé položky přečti aktuální počet pro její klíč — chybějící klíč ber jako nulu — než uložíš o jedna víc."],
    approach: [
      "Použij reduce s prázdným objektem jako počáteční hodnotou.",
      "U každé položky se zeptej klíčové funkce, ke kterému klíči patří.",
      "Ulož předchozí počet pro ten klíč plus jedna, u nového klíče vyjdi z nuly, a objekt vrať, aby ho dostal další krok.",
    ],
    testLabels: ["", "", "prázdný vstup dá prázdný objekt", "klíče se stanou řetězci", "jediná položka"],
  },
  "js-running-totals": {
    title: "Průběžné součty",
    prompt: "Napiš funkci `runningTotals(numbers)`, která vrátí nové pole, kde každá pozice drží součet všech čísel až po ni včetně, sestavené přes `reduce`, jehož akumulátorem je výstupní pole. `runningTotals([1, 2, 3, 4])` dá `[1, 3, 6, 10]`. Prázdné pole dá prázdné pole a vstup se nemění.",
    hints: ["Akumulátorem může být samotné výstupní pole: další součet je poslední, který už v něm je, nebo nula, dokud je prázdné, plus aktuální číslo."],
    approach: [
      "Použij reduce s prázdným polem jako akumulátorem.",
      "V každém kroku přečti poslední součet, který už v akumulátoru je, nebo nulu, když tam žádný není.",
      "Přidej ten součet plus aktuální číslo a akumulátor vrať.",
    ],
    testLabels: ["", "", "prázdný vstup", "záporná čísla součet zase sníží", "jediná hodnota je sama svým součtem"],
  },
  "js-apply-all": {
    title: "Reduce jako pipeline",
    prompt: "Napiš funkci `applyAll(value, steps)`, která prožene hodnotu každou funkcí ve `steps` zleva doprava a vrátí konečný výsledek, přes `reduce` nad funkcemi s hodnotou jako počátečním akumulátorem. `applyAll(3, [n => n + 1, n => n * 2])` dá 8. Prázdné pole `steps` vrátí hodnotu beze změny a krok může vrátit jiný typ, než jaký dostal.",
    hints: ["Akumulátor je hodnota tak, jak vypadá po dosavadních krocích; každý krok reduce ji předá další funkci a vezme si, co se vrátí."],
    approach: [
      "Redukuj přes pole funkcí, ne přes data, s výchozí hodnotou jako počátečním akumulátorem.",
      "V každém kroku zavolej aktuální funkci s akumulátorem a vrať její výsledek.",
      "Bez funkcí vrátí reduce počáteční hodnotu netknutou, což je požadovaná odpověď.",
    ],
    testLabels: ["", "", "bez kroků vrátí vstup", "na pořadí záleží, zleva doprava", "typ se může mezi kroky měnit"],
  },
  "js-swap-pairs": {
    title: "Prohoď dvojice",
    prompt: "Napiš funkci `swapPairs(list)`, která vrátí nové pole, kde si každí dva sousedé vyměnili místa, prohození destrukturováním pole uvnitř cyklu `for`, který jde po dvou přes kopii pole. `swapPairs([1, 2, 3, 4])` dá `[2, 1, 4, 3]`. Při liché délce zůstane poslední prvek, kde je, prázdné pole dá prázdné pole a vstup se nikdy nemění.",
    hints: ["Nejdřív pole zkopíruj, pak jím projdi po dvou a každou dvojici sousedů prohoď jednořádkovým destrukturovacím přiřazením — pomocná proměnná není potřeba."],
    approach: [
      "Udělej kopii přes slice, aby se originál nikdy nezměnil.",
      "Cykli s indexem, který začne na nule a roste po dvou, dokud ještě existuje partner na dalším indexu.",
      "Obě pozice prohoď destrukturováním pole vlevo a polem obou hodnot vpravo.",
      "Vrať kopii.",
    ],
    testLabels: ["", "", "lichý poslední prvek zůstane, kde je", "prázdný vstup", "zachová původní pole beze změny", "jediný prvek"],
  },
  "js-sum-labelled-pairs": {
    title: "Součet označených dvojic",
    prompt: "Napiš funkci `totalOf(pairs, label)`, kde `pairs` je pole dvojic `[label, value]`, která vrátí součet hodnot s odpovídajícím štítkem, destrukturovaných rovnou v hlavičce cyklu `for…of`. `totalOf([[\"food\", 12], [\"rent\", 500], [\"food\", 8]], \"food\")` dá 20. Žádný odpovídající štítek nebo prázdné pole dá 0.",
    hints: ["Každý prvek je dvouprvkové pole a for-of ho umí rozebrat na název a hodnotu přímo v hlavičce cyklu, takže tělo už jen porovnává a sčítá."],
    approach: [
      "Začni se součtem na nule.",
      "Projdi dvojice cyklem for-of a každou v hlavičce cyklu destrukturuj na štítek a hodnotu.",
      "Když štítek odpovídá, přičti hodnotu k součtu, a součet vrať.",
    ],
    testLabels: ["", "", "prázdný vstup", "žádný odpovídající štítek", "záporná čísla se vyruší"],
  },
  "js-immutable-list-edits": {
    title: "Neměnné úpravy pole",
    prompt: "Napiš funkce `withInserted(list, index, item)`, `withoutIndex(list, index)` a `withReplaced(list, index, item)`. Každá vrátí nové pole složené ze dvou kopií přes `slice` rozbalených spreadem do nového literálu pole a nikdy nezmění pole, které dostala. `withInserted([1, 3], 1, 2)` dá `[1, 2, 3]`, `withoutIndex([1, 2, 3], 0)` dá `[2, 3]` a `withReplaced([1, 2, 3], 2, 9)` dá `[1, 2, 9]`.",
    hints: ["slice ti dá část před indexem a část od indexu nebo za ním, a rozbalit ty dva kusy spreadem do nového literálu pole — s prvkem mezi nimi, nebo bez něj — je celý trik."],
    approach: [
      "V každé funkci si přes slice vezmi část pole před indexem; slice na originál nikdy nesáhne.",
      "Vezmi si i konec: od samotného indexu při vkládání, nebo od pozice o jedna dál při odebírání a nahrazování.",
      "Začátek a konec rozbal spreadem do nového literálu pole a při vkládání a nahrazování mezi ně dej prvek.",
    ],
    testLabels: ["", "", "", "zachová původní pole beze změny", "vložení na konec připojí", "odebrání jediného prvku"],
  },
  "js-variadic-sum": {
    title: "Součet libovolného počtu",
    prompt: "Napiš funkci `sumAll(...numbers)`, která přes rest parametr přijme libovolný počet argumentů a vrátí jejich součet z cyklu `for…of` přes to pole. `sumAll(1, 2, 3)` dá 6. Bez argumentů je součet 0 a do volání jde rozbalit pole: `sumAll(...[4, 5])` dá 9.",
    hints: ["Rest parametr posbírá všechny argumenty, ať jich přijde kolik chce, do jednoho opravdového pole, a odtud je to obyčejný součet přes for-of."],
    approach: [
      "Parametr napiš se třemi tečkami, aby se každý argument posbíral do pole.",
      "Začni se součtem na nule a pole projdi cyklem for-of, každé číslo přičti.",
      "Vrať součet; bez argumentů je pole prázdné a součet zůstane nula.",
    ],
    testLabels: ["", "", "vůbec žádné argumenty", "pole rozbalené do volání", "záporná a desetinná čísla"],
  },
  "js-make-tally": {
    title: "Továrna na sčítač",
    prompt: "Napiš funkci `makeTally(start)`, která vrátí funkci držící průběžný součet ve scope továrny: každé volání přijme libovolný počet hodnot, projde je cyklem a každou přičte k součtu, a vrátí nový součet. Pro `tally = makeTally(10)` dá `tally(1, 2)` 13 a pozdější `tally(5)` dá 18. Volání bez hodnot vrátí součet tak, jak je, a dva sčítače nikdy nesdílejí součet.",
    hints: ["Součet žije ve scope továrny, vrácená funkce je jediná, kdo na něj dosáhne, a uvnitř ní sčítání obstará cyklus přes rest parametr."],
    approach: [
      "Uvnitř továrny si založ proměnnou s počáteční hodnotou.",
      "Vrať šipkovou funkci, která své argumenty posbírá rest parametrem.",
      "Uvnitř ní projdi hodnoty cyklem, každou přičti k vnější proměnné a tu pak vrať — mezi voláními přežije, protože vrácená funkce na ni pořád odkazuje.",
    ],
    testLabels: ["", "", "bez hodnot nechá součet, jak je", "každý sčítač si drží vlastní součet", "záporná čísla se počítají taky"],
  },
  "js-handlers-keep-index": {
    title: "Handlery si pamatují index",
    prompt: "Napiš funkci `makeHandlers(count)`, která vrátí pole `count` funkcí sestavené v cyklu `for`, jehož počítadlo je deklarované přes `let`, takže funkce na pozici i po zavolání vrátí i — stejně jako si handlery kliknutí vyrobené v cyklu pamatují každý svůj index. `makeHandlers(3).map(handler => handler())` dá `[0, 1, 2]`. Počet nula dá prázdné pole.",
    hints: ["Proměnnou cyklu deklaruj přes let: každý průchod cyklu pak dostane vlastní vazbu, takže funkce vytvořená uvnitř si pamatuje index toho průchodu, a ne konečnou hodnotu."],
    approach: [
      "Vytvoř prázdné pole pro handlery.",
      "Napiš cyklus for, jehož počítadlo je deklarované přes let a běží od nuly, dokud je menší než počet.",
      "V každém průchodu přidej šipkovou funkci, která vrátí počítadlo — díky let si každá funkce nechá hodnotu ze svého průchodu.",
      "Vrať pole.",
    ],
    testLabels: ["", "", "nula handlerů", "poslední handler si pamatuje poslední index", "další volání dá stejný index"],
  },
  "js-my-map-filter": {
    title: "Napiš myMap a myFilter",
    prompt: "Napiš funkce `myMap(list, fn)` a `myFilter(list, fn)` obyčejnými cykly `for` místo vestavěných `map` a `filter`. `myMap` vrátí nové pole výsledků `fn(item, index)` a `myFilter` vrátí nové pole prvků, pro které je `fn(item, index)` truthy; ani jedna pole nemění. `myMap([1, 2, 3], n => n * 2)` dá `[2, 4, 6]` a `myFilter([1, 2, 3, 4], n => n % 2 === 0)` dá `[2, 4]`.",
    hints: ["Obě jsou cyklus, který volá callback s prvkem a jeho indexem; map přidá, cokoli se vrátí, filter přidá prvek jen tehdy, když je to, co se vrátí, truthy."],
    approach: [
      "Každou funkci začni prázdným výsledným polem.",
      "Projdi pole cyklem s indexem a zavolej callback s prvkem a indexem.",
      "V myMap přidej návratovou hodnotu callbacku; v myFilter přidej původní prvek jen tehdy, když je návratová hodnota truthy.",
      "Vrať výsledek — ze vstupního pole se jen čte.",
    ],
    testLabels: ["", "", "prázdný vstup do myMap", "nic nezůstane", "callback dostane i index", "zachová původní pole beze změny"],
  },
  "js-my-reduce": {
    title: "Napiš myReduce",
    prompt: "Napiš funkci `myReduce(list, fn, initial)` obyčejným cyklem `for` místo vestavěného `reduce`: pro každý prvek zavolej `fn(accumulator, item, index)`, akumulátor začni na `initial` a konečný akumulátor vrať. Když je `initial` `undefined`, stane se počátečním akumulátorem první prvek a cyklus začne od druhého. `myReduce([1, 2, 3], (total, n) => total + n, 0)` dá 6 a prázdné pole s počáteční hodnotou vrátí tu hodnotu.",
    hints: ["Akumulátor drž v proměnné, o tom, kde cyklus začne, rozhodni podle toho, jestli přišla počáteční hodnota, a nech každý průchod nahradit akumulátor výsledkem callbacku."],
    approach: [
      "Počáteční hodnotu dej do proměnné akumulátoru a počítej s tím, že cyklus začne na indexu nula.",
      "Když počáteční hodnota nepřišla, vezmi jako akumulátor první prvek a cyklus začni místo toho na indexu jedna.",
      "Projdi zbývající prvky a akumulátor pokaždé nahraď tím, co callback vrátí pro akumulátor, prvek a index.",
      "Po cyklu akumulátor vrať.",
    ],
    testLabels: ["", "", "prázdné pole vrátí počáteční hodnotu", "bez počáteční hodnoty začne akumulátor prvním prvkem", "callback dostane i index"],
  },
  "js-label-numbers": {
    title: "Označ čísla",
    prompt: "Napiš funkci `labelNumbers(numbers)`, která vrátí nové pole s řetězcem `\"positive\"`, `\"negative\"` nebo `\"zero\"` pro každé číslo, rozhodnutým ternárním operátorem uvnitř callbacku `map`. `labelNumbers([3, -1, 0])` dá `[\"positive\", \"negative\", \"zero\"]`. Prázdné pole dá prázdné pole.",
    hints: ["Ternární operátor je výraz, takže může být celým tělem callbacku map, a druhý ternár v jeho větvi „jinak“ rozhodne třetí štítek."],
    approach: [
      "Projdi čísla přes map a za každé číslo vrať jeden řetězec.",
      "V callbacku použij ternární operátor: větší než nula dá positive, jinak druhý ternár rozhodne mezi negative a zero.",
    ],
    testLabels: ["", "", "prázdný vstup", "nula není ani kladná, ani záporná", "malé záporné desetinné číslo"],
  },
  "js-sum-mixed-values": {
    title: "Součet smíšených hodnot",
    prompt: "Napiš funkci `sumMixed(values)`, která vrátí číselný součet pole, kde se míchají čísla s číselnými řetězci jako `\"4\"` nebo `\"2.5\"`, a každou hodnotu před přičtením převede přes `Number` uvnitř cyklu `for…of`. `sumMixed([1, \"2\", 3])` dá 6, tedy číslo, ne `\"123\"`. Prázdné pole dá 0.",
    hints: ["Plus s řetězcem na jedné straně lepí text dohromady, takže každou hodnotu před přičtením převeď na číslo."],
    approach: [
      "Začni se součtem na nule, což zároveň určí, že výsledek bude číslo.",
      "Projdi hodnoty cyklem for-of a každou před přičtením k součtu převeď přes Number.",
      "Vrať součet.",
    ],
    testLabels: ["", "", "prázdný vstup vrátí 0", "desetinné řetězce", "záporné číslo v řetězci"],
  },
  "js-compact-values": {
    title: "Zhusti pole",
    prompt: "Napiš funkce `compactLoop(values)` a `compactFilter(values)`, které obě vrátí nové pole bez všech falsy hodnot — `false`, `0`, `\"\"`, `null`, `undefined` a `NaN` — a vstup nechají beze změny. První použije cyklus `for…of` s `if` na samotné hodnotě; druhá předá `Boolean` rovnou do `filter`. `compactLoop([0, 1, \"\", \"a\", null])` dá `[1, \"a\"]`.",
    hints: ["Na každou hodnotu se v if dá zeptat přímo, jestli je truthy, a funkce Boolean pokládá tutéž otázku jako callback, takže ji filter může vzít tak, jak je."],
    approach: [
      "V cyklové verzi přidej hodnotu do nového pole jen tehdy, když sama projde testem v if.",
      "Ve verzi s filter předej funkci Boolean rovnou do filter; pro truthy hodnoty vrátí true a pro falsy false.",
      "Ani jedna verze vstup nemění.",
    ],
    testLabels: ["", "", "prázdný vstup", "všechno falsy", "řetězec s nulou, prázdné pole, prázdný objekt i mezera jsou truthy", "zachová původní pole beze změny"],
  },
  "js-count-nested-keys": {
    title: "Spočítej vnořené klíče",
    prompt: "Napiš funkci `countKeys(object)`, která vrátí, kolik klíčů objekt má ve všech úrovních, navštívených přes `for…in`: každý klíč se počítá jednou, a když je jeho hodnotou obyčejný objekt, jeho klíče se počítají stejně. `countKeys({ a: 1, b: { c: 2, d: { e: 3 } } })` dá 5. `null` a pole se počítají jako obyčejné hodnoty a prázdný objekt dá 0.",
    hints: ["for-in navštíví každý klíč, takže za každou návštěvu započítej jedničku, a když je hodnota pod klíčem sama obyčejný objekt, spočítej její klíče stejně — zavoláním své funkce na ni."],
    approach: [
      "Začni s počtem na nule a projdi klíče objektu cyklem for-in.",
      "Za každý navštívený klíč přičti jedničku.",
      "Podívej se na hodnotu pod klíčem: když je to obyčejný objekt — ne null a ne pole — přičti výsledek počítání jeho klíčů toutéž funkcí.",
      "Vrať počet.",
    ],
    testLabels: ["", "", "prázdný objekt nemá žádné klíče", "prázdný vnořený objekt nic nepřidá", "null a pole se počítají jako obyčejné hodnoty", "hluboké vnoření"],
  },
  "js-order-total": {
    title: "Součet s výchozími hodnotami",
    prompt: "Napiš funkci `orderTotal(items)`, která vrátí součet `price` krát `quantity` přes všechny položky, kde chybějící nebo `null` množství znamená 1 — doplněné přes `??` uvnitř cyklu `for…of`. `orderTotal([{ price: 5 }, { price: 2, quantity: 3 }])` dá 11. Množství 0 je skutečné množství a nepřidá nic a prázdná objednávka dá 0.",
    hints: ["Operátor nullish dosadí výchozí hodnotu jen za null a undefined, a přesně proto ho množství nula přežije tam, kde by ho operátor „nebo“ nahradil."],
    approach: [
      "Začni se součtem na nule a projdi položky cyklem for-of.",
      "Množství přečti s nullish náhradou jedna, aby výchozí hodnotu dostalo jen chybějící nebo null množství.",
      "Přičti k součtu cenu krát množství a součet vrať.",
    ],
    testLabels: ["", "", "prázdná objednávka", "množství nula je nula, ne výchozí hodnota", "null množství spadne na jedničku"],
  },
  "js-frequency-map": {
    title: "Četnosti v Map",
    prompt: "Napiš funkci `frequencies(values)`, která vrátí `Map` z každé odlišné hodnoty na počet jejích výskytů, naplněnou přes `for…of` v pořadí prvního výskytu. `frequencies([\"a\", \"b\", \"a\"])` dá Map s `\"a\"` → 2 a `\"b\"` → 1. Klíče si zachovají typ, takže číslo 1 a řetězec `\"1\"` jsou dva různé záznamy, a prázdné pole dá prázdnou Map.",
    hints: ["Aktuální počet přečti přes get, chybějící ber jako nulu a zapiš ho zpět přes set — Map zachová skutečné typy klíčů i pořadí prvního výskytu."],
    approach: [
      "Vytvoř prázdnou Map.",
      "Projdi hodnoty cyklem for-of; u každé si přes get vezmi aktuální počet, spadni na nulu a nastav počet plus jedna.",
      "Vrať samotnou Map.",
    ],
    testLabels: ["", "", "prázdný vstup dá prázdnou Map", "číslo a řetězec zůstanou oddělenými klíči", "jediná hodnota", "vrací Map, ne objekt"],
  },
  "js-map-entries-at-least": {
    title: "Záznamy Map na dvojice",
    prompt: "Napiš funkci `entriesAtLeast(map, min)`, která vrátí pole dvojic `[key, value]` pro každý záznam `Map`, jehož hodnota je aspoň `min`, v pořadí vložení, nasbírané přes `for…of` nad Map s destrukturováním v hlavičce cyklu. Pro `new Map([[\"a\", 1], [\"b\", 5], [\"c\", 3]])` a `min` 3 dá `[[\"b\", 5], [\"c\", 3]]`. Když nic nevyhovuje nebo je Map prázdná, dá prázdné pole, a Map se nemění.",
    hints: ["Map je iterovatelná a každá otočka for-of dá záznam, který jde destrukturovat na klíč a hodnotu; za každý vyhovující přidej nové dvouprvkové pole."],
    approach: [
      "Vytvoř prázdné pole pro dvojice.",
      "Projdi Map cyklem for-of a každý záznam destrukturuj na klíč a hodnotu.",
      "Když je hodnota aspoň rovna hranici, přidej novou dvojici klíč–hodnota, a pole vrať.",
    ],
    testLabels: ["", "", "prázdná Map", "samotná hranice vyhovuje", "nic nevyhovuje", "zachová Map beze změny"],
  },
  "js-chunk-with-loop": {
    title: "Rozděl cyklem",
    prompt: "Napiš funkci `chunkBy(items, size)`, která pole rozdělí do skupin po `size` cyklem `for`, který každý prvek přidá do aktuální skupiny a založí novou, kdykoli se ta stávající naplní — bez `slice`. `chunkBy([1, 2, 3, 4, 5], 2)` dá `[[1, 2], [3, 4], [5]]`. Velikost větší než pole dá jednu skupinu, prázdné pole dá prázdné pole a vstup se nemění.",
    hints: ["Drž si aktuální skupinu, do které prvky přidáváš; jakmile dosáhne velikosti, přesuň ji do výsledku a založ novou, a po cyklu nezapomeň na nedokončenou skupinu."],
    approach: [
      "Vytvoř prázdný výsledek a prázdnou aktuální skupinu.",
      "Projdi prvky cyklem s indexem a každý přidej do aktuální skupiny.",
      "Kdykoli aktuální skupina dosáhne velikosti, přidej ji do výsledku a nahraď ji novým prázdným polem.",
      "Po cyklu přidej aktuální skupinu, když v ní ještě něco je, a výsledek vrať.",
    ],
    testLabels: ["", "", "prázdný vstup", "velikost větší než pole dá jednu skupinu", "velikost jedna", "zachová původní pole beze změny"],
  },
  "js-zip-lists": {
    title: "Spoj dva seznamy",
    prompt: "Napiš funkci `zip(left, right)`, která vrátí pole dvojic `[left[i], right[i]]` sestavené jedním cyklem `for`, jehož index čte obě pole najednou a zastaví se na kratší délce. `zip([1, 2, 3], [\"a\", \"b\", \"c\"])` dá `[[1, \"a\"], [2, \"b\"], [3, \"c\"]]`. Když je jedna strana prázdná, výsledek je prázdný, a žádný vstup se nemění.",
    hints: ["Počet dvojic urči ještě před cyklem — menší z obou délek — a pak jeden index čte obě pole zároveň."],
    approach: [
      "Zjisti kratší délku tak, že vezmeš menší z obou délek.",
      "Projdi indexem od nuly až po tu délku.",
      "Přidej dvouprvkové pole s prvkem z každého seznamu na tom indexu a dvojice vrať.",
    ],
    testLabels: ["", "", "kratší seznam určí délku", "prázdná strana nedá nic", "null je pořád hodnota"],
  },
  "js-rotate-by-n": {
    title: "Otoč o n",
    prompt: "Napiš funkci `rotateBy(list, n)`, která vrátí nové pole, kde se každý prvek posune o `n` míst doprava a ty vytlačené za konec se přetočí na začátek, sestavené cyklem `for` a aritmetikou zbytku po dělení místo `slice`. `rotateBy([1, 2, 3, 4, 5], 2)` dá `[4, 5, 1, 2, 3]`. Záporné `n` otáčí doleva, `n` větší než délka se přetočí dokola, prázdné pole dá prázdné pole a vstup se nemění.",
    hints: ["Posun nejdřív dostaň do rozsahu nula až délka mínus jedna — operátor zbytku plus jedno přičtení navíc zvládne i záporná čísla — a pak jeden cyklus přečte každý prvek z jeho posunuté pozice."],
    approach: [
      "Pro prázdné pole rovnou vrať prázdné pole, protože zbytek po dělení nulou není číslo.",
      "Znormalizuj posun: vezmi zbytek po dělení délkou, přičti délku a vezmi zbytek znovu, aby záporná čísla skončila v rozsahu.",
      "Projdi indexem každou pozici a přidej prvek, který sedí o posun míst dřív, s přetočením přes zbytek.",
      "Vrať nové pole, aniž bys sáhl na vstup.",
    ],
    testLabels: ["", "", "nula nechá pořadí", "posun větší než délka se přetočí dokola", "záporný posun otáčí doleva", "prázdný vstup"],
  },
  "js-run-length-encode": {
    title: "Run-length kódování",
    prompt: "Napiš funkci `runLength(text)`, která vrátí řetězec, kde je každá série stejného znaku nahrazená délkou série a za ní znakem, nalezená jedním cyklem `for`, který počítá, dokud se další znak shoduje. `runLength(\"aaabccdddd\")` dá `\"3a1b2c4d\"`. Série rozlišují velikost písmen, jediný znak dá `\"1\"` a ten znak a prázdný řetězec dá prázdný řetězec.",
    hints: ["Počítej, dokud je další znak stejný jako aktuální, a ve chvíli, kdy se další liší, zapiš počet a znak — konec řetězce se počítá jako odlišný."],
    approach: [
      "Drž si výsledný řetězec a počítadlo aktuální série.",
      "Projdi indexem znaky a v každém kroku přičti k počítadlu jedničku.",
      "Když je další znak jiný — nebo na konci chybí — připoj počet a znak a počítadlo vynuluj.",
      "Vrať výsledek.",
    ],
    testLabels: ["", "", "prázdný řetězec", "jediný znak", "na velikosti písmen záleží", "série delší než devět"],
  },
  "js-pair-with-sum": {
    title: "Dvojice se součtem",
    prompt: "Napiš funkci `pairWithSum(sorted, target)`, která vezme vzestupně seřazené pole a vrátí dvě hodnoty se součtem `target` jako `[menší, větší]`, nalezené jedním indexem postupujícím z každého kraje v cyklu `while`, nebo `null`, když taková dvojice není. `pairWithSum([1, 2, 4, 7, 11], 9)` dá `[2, 7]`. Když vyhovuje víc dvojic, vrať tu s nejmenší první hodnotou; jediná hodnota se nemůže spárovat sama se sebou.",
    hints: ["S jedním indexem na každém kraji seřazeného pole znamená příliš malý součet, že se musí posunout levý index nahoru, a příliš velký, že pravý dolů — dvojice je nalezená, když se trefí do cíle, a chybí, když se indexy překříží."],
    approach: [
      "Začni jedním indexem na prvním prvku a druhým na posledním.",
      "Dokud je levý index pod pravým, sečti oba prvky.",
      "Když součet sedí, vrať dvojici; když je moc malý, posuň levý index nahoru, a když moc velký, pravý dolů.",
      "Když se indexy překříží bez shody, vrať null.",
    ],
    testLabels: ["", "", "žádná dvojice nedá součet", "jediná hodnota se nemůže spárovat sama se sebou", "záporná čísla", "prázdný vstup"],
  },
  "js-binary-search": {
    title: "Binární vyhledávání",
    prompt: "Napiš funkci `binarySearch(sorted, target)`, která vrátí index `target` ve vzestupně seřazeném poli, nebo -1, když chybí, tak, že v cyklu `while` drží dolní a horní index a v každé otočce se podívá na prostřední prvek, takže se prohledávaný rozsah každým krokem půlí. `binarySearch([1, 3, 5, 7, 9], 7)` dá 3. Prázdné pole dá -1 a pole obsahuje různé hodnoty.",
    hints: ["Drž dolní a horní index, podívej se na prvek uprostřed a zahoď polovinu, ve které cíl být nemůže; skonči, když dolní index přeskočí horní."],
    approach: [
      "Začni s dolním indexem na prvním a horním na posledním.",
      "Dokud je dolní index nejvýš roven hornímu, spočítej prostřední index a jeho prvek porovnej s cílem.",
      "Když sedí, vrať prostřední index; jinak posuň dolní index nad střed, když je prvek moc malý, nebo horní pod střed, když je moc velký.",
      "Když je rozsah prázdný, vrať -1.",
    ],
    testLabels: ["", "", "hodnota, která tam není", "prázdný vstup", "jediný prvek", "poslední prvek"],
  },
  "js-sliding-window-max": {
    title: "Maximum v okně",
    prompt: "Napiš funkci `windowMax(numbers, size)`, která vrátí pole s největší hodnotou každého okna `size` po sobě jdoucích čísel zleva doprava, pomocí vnějšího cyklu `for` přes začátky oken a vnitřního, který každé okno projde. `windowMax([1, 3, 2, 5, 4], 3)` dá `[3, 5, 5]`. Okno širší než pole dá prázdné pole a okno stejně široké jako pole dá jedinou hodnotu.",
    hints: ["Vnější cyklus vybírá, kde okno začíná, a skončí, jakmile se celé okno už nevejde; vnitřní cyklus to okno projde a drží si největší nalezenou hodnotu."],
    approach: [
      "Projdi počáteční index od nuly, dokud se celé okno ještě vejde do pole.",
      "Pro každý začátek vezmi první prvek okna jako zatím nejlepší a zbytek okna projdi vnitřním cyklem, nejlepší nahraď, když se objeví větší hodnota.",
      "Po vnitřním cyklu nejlepší hodnotu přidej a nasbíraná maxima vrať.",
    ],
    testLabels: ["", "", "okno široké jako celé pole", "okno širší než pole", "samá záporná čísla", "okno o jednom prvku"],
  },
  "js-matrix-transpose": {
    title: "Transpozice matice",
    prompt: "Napiš funkci `transpose(matrix)`, která vrátí novou matici, jejíž řádky jsou sloupce vstupu, sestavenou cyklem `for` přes sloupce a vnitřním cyklem `for` přes řádky; předpokládej, že všechny řádky mají stejnou délku. `transpose([[1, 2, 3], [4, 5, 6]])` dá `[[1, 4], [2, 5], [3, 6]]`. Prázdná matice dá prázdné pole a vstup se nemění.",
    hints: ["Každý sloupec vstupu se stane řádkem výstupu, takže nech vnější cyklus procházet sloupce a vnitřní sbírat hodnotu toho sloupce z každého řádku."],
    approach: [
      "Pro prázdnou matici vrať prázdné pole, protože není první řádek, který by šlo změřit.",
      "Projdi index sloupce přes šířku prvního řádku; pro každý založ nový řádek.",
      "Vnitřním cyklem přes původní řádky přidej do nového řádku prvek v tom sloupci.",
      "Nový řádek přidej do výsledku a na konci výsledek vrať.",
    ],
    testLabels: ["", "", "prázdná matice", "jediný řádek se stane sloupcem", "jediný sloupec se stane řádkem", "zachová původní matici beze změny"],
  },
};
