// Generated by scripts/port-interview-prepper.mjs from the interview-prepper catalogue.
// Task bodies only: prompts, starters, visible tests, hints. No solutions.
// English is the source of truth; Czech copy lives in the sibling *.cs.ts overlay.

import type { CodingTaskSource } from '../types';

export const JAVASCRIPT_TASKS: CodingTaskSource[] = [
  {
    id: "js-double-numbers",
    legacyId: "j1",
    track: "javascript",
    topic: "javascript",
    level: 6,
    tier: 1,
    focus: ["map"],
    title: "Double numbers",
    prompt: "Write `double(numbers)`, returning a new array with every number multiplied by two. An empty array gives an empty array; negatives, zero and decimals all double normally.",
    starter: `const double = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(double([1,2,3]));
`,
    skeleton: `const double = numbers =>
  numbers.map(item => {
    return /* transformed item */;
  });`,
    hints: ["Map returns one new value for every input value."],
    approach: [
      "Reach for map, since you need exactly one output value for every input value.",
      "In the callback, return the number multiplied by two — map collects the returns into the new array for you.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "double([1,2,3])", expected: [2, 4, 6] },
      { call: "double([5])", expected: [10] },
      { call: "double([])", expected: [], label: "empty input", edge: true },
      { call: "double([-2,0])", expected: [-4, 0], label: "negatives and zero", edge: true },
      { call: "double([1.5])", expected: [3], label: "decimals", edge: true },
    ],
  },
  {
    id: "js-even-numbers",
    legacyId: "j2",
    track: "javascript",
    topic: "javascript",
    level: 7,
    tier: 1,
    focus: ["filter"],
    title: "Even numbers",
    prompt: "Write `evens(numbers)`, returning a new array of only the even values, in their original order. Zero counts as even, negatives are judged the same way, and an array with no even values gives an empty array.",
    starter: `const evens = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(evens([1,2,3,4]));
`,
    skeleton: `const evens = numbers =>
  numbers.filter(item => {
    return /* true to keep this item */;
  });`,
    hints: ["Even numbers have a remainder of 0 when divided by 2."],
    approach: [
      "Reach for filter, since you are keeping some values and dropping others rather than transforming them.",
      "Decide evenness with the remainder operator: a number divided by two leaves a remainder of zero. Watch that zero itself qualifies.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "evens([1,2,3,4])", expected: [2, 4] },
      { call: "evens([2,4])", expected: [2, 4] },
      { call: "evens([])", expected: [], label: "empty input", edge: true },
      { call: "evens([1,3,5])", expected: [], label: "nothing matches", edge: true },
      { call: "evens([0,-2,-3])", expected: [0, -2], label: "zero and negatives", edge: true },
    ],
  },
  {
    id: "js-sum-array",
    legacyId: "j3",
    track: "javascript",
    topic: "javascript",
    level: 8,
    tier: 1,
    focus: ["reduce"],
    title: "Sum array",
    prompt: "Write `sum(numbers)`, returning the total of every value. An empty array totals 0, and negatives and decimals add up like anything else.",
    starter: `const sum = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(sum([2,3,4]));
`,
    skeleton: `const sum = numbers =>
  numbers.reduce((accumulator, item) => {
    return /* next accumulator */;
  }, /* initial value */);`,
    hints: [
      "You are collapsing many values into one, so reach for the method built for exactly that — and give it a starting total, or an empty array has no answer to return.",
    ],
    approach: [
      "Use reduce with an accumulator that carries the running total.",
      "Start the accumulator at zero, which is also what an empty array must return.",
      "Each step returns the running total plus the current number.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "sum([2,3,4])", expected: 9 },
      { call: "sum([5])", expected: 5 },
      { call: "sum([])", expected: 0, label: "empty input returns 0", edge: true },
      { call: "sum([-2,2])", expected: 0, label: "negatives cancel out", edge: true },
      { call: "sum([1.5,2.5])", expected: 4, label: "decimals", edge: true },
    ],
  },
  {
    id: "js-longest-word",
    legacyId: "j4",
    track: "javascript",
    topic: "javascript",
    level: 6,
    tier: 1,
    focus: ["for", "strings"],
    title: "Longest word",
    prompt: "Write `longest(words)`, returning the longest string in the array. When two are equally long, keep the one that comes first; an empty array returns an empty string.",
    starter: `const longest = words => {
  
};

// Scratch pad — change this and press Run.
console.log(longest(["cat","elephant","dog"]));
`,
    skeleton: `const longest = words => {
  const result = /* initial result */;

  for (const item of words) {
    // inspect item and update result
  }

  return result;
};`,
    hints: [
      "Walk the list keeping the best candidate found so far, and replace it only when the new word is strictly longer. That “strictly” is what leaves a tie on the earlier word.",
    ],
    approach: [
      "Track the best candidate seen so far, either in a loop variable or as a reduce accumulator.",
      "Compare lengths as you go and replace the best only when the current word is strictly longer, so a tie keeps the first one.",
      "Decide what an empty list returns before you write the loop — an empty string is the natural answer here.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "longest([\"cat\",\"elephant\",\"dog\"])", expected: "elephant" },
      { call: "longest([\"a\",\"bbb\",\"cc\"])", expected: "bbb" },
      { call: "longest([\"only\"])", expected: "only", label: "single word", edge: true },
      {
        call: "longest([])",
        expected: "",
        label: "empty input returns an empty string",
        edge: true,
      },
      {
        call: "longest([\"aa\",\"bb\"])",
        expected: "aa",
        label: "tie keeps the first",
        edge: true,
      },
    ],
  },
  {
    id: "js-count-vowels",
    legacyId: "j5",
    track: "javascript",
    topic: "javascript",
    level: 6,
    tier: 1,
    focus: ["for-of", "strings"],
    title: "Count vowels",
    prompt: "Write `countVowels(text)`, returning how many vowels (a, e, i, o, u) the string holds. Uppercase vowels count too; a string with none, or an empty string, gives 0.",
    starter: `const countVowels = text => {
  
};

// Scratch pad — change this and press Run.
console.log(countVowels("hello"));
`,
    skeleton: `const countVowels = text => {
  const result = /* initial result */;

  for (const item of text) {
    // inspect item and update result
  }

  return result;
};`,
    hints: ["Loop through lowercase letters and check \"aeiou\"."],
    approach: [
      "Lowercase the text first so uppercase vowels are counted the same way.",
      "Walk the characters and test membership against the five vowels; a string of vowels plus includes is enough.",
      "Return how many matched, not the matches themselves.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "countVowels(\"hello\")", expected: 2 },
      { call: "countVowels(\"aeiou\")", expected: 5 },
      { call: "countVowels(\"\")", expected: 0, label: "empty string", edge: true },
      { call: "countVowels(\"HELLO\")", expected: 2, label: "uppercase counts too", edge: true },
      { call: "countVowels(\"xyz\")", expected: 0, label: "no vowels", edge: true },
    ],
  },
  {
    id: "js-reverse-string",
    legacyId: "j6",
    track: "javascript",
    topic: "javascript",
    level: 2,
    tier: 1,
    focus: ["for", "strings"],
    title: "Reverse string",
    prompt: "Write `reverse(text)`, returning the string with its characters in the opposite order. Spaces are characters like any other, and an empty or single-character string comes back unchanged.",
    starter: `const reverse = text => {
  
};

// Scratch pad — change this and press Run.
console.log(reverse("cat"));
`,
    skeleton: `const reverse = text => {
  const result = /* initial result */;

  for (const item of text) {
    // inspect item and update result
  }

  return result;
};`,
    hints: ["Add each letter to the front of a result string."],
    approach: [
      "Split the string into characters, since strings themselves cannot be reversed in place.",
      "Reverse the character array and join it back into a string.",
      "Check that an empty string and a single character both survive the round trip.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "reverse(\"cat\")", expected: "tac" },
      { call: "reverse(\"hello\")", expected: "olleh" },
      { call: "reverse(\"\")", expected: "", label: "empty string", edge: true },
      { call: "reverse(\"a\")", expected: "a", label: "single character", edge: true },
      { call: "reverse(\"ab cd\")", expected: "dc ba", label: "keeps spaces", edge: true },
    ],
  },
  {
    id: "js-positive-numbers",
    legacyId: "j7",
    track: "javascript",
    topic: "javascript",
    level: 7,
    tier: 1,
    focus: ["filter"],
    title: "Positive numbers",
    prompt: "Write `positives(numbers)`, returning a new array of the values strictly above zero, in order. Zero is not positive, and an array with none gives an empty array.",
    starter: `const positives = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(positives([-1,0,3]));
`,
    skeleton: `const positives = numbers =>
  numbers.filter(item => {
    return /* true to keep this item */;
  });`,
    hints: [
      "A keep-or-drop decision on each value, and the only subtlety is the boundary: zero is not above zero.",
    ],
    approach: [
      "Use filter with a strict greater-than-zero test.",
      "Note that zero is not positive, so it must be dropped along with the negatives.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "positives([-1,0,3])", expected: [3] },
      { call: "positives([1,2])", expected: [1, 2] },
      { call: "positives([])", expected: [], label: "empty input", edge: true },
      { call: "positives([0])", expected: [], label: "zero is not positive", edge: true },
      { call: "positives([-5,-1])", expected: [], label: "nothing matches", edge: true },
    ],
  },
  {
    id: "js-square-numbers",
    legacyId: "j8",
    track: "javascript",
    topic: "javascript",
    level: 6,
    tier: 1,
    focus: ["map"],
    title: "Square numbers",
    prompt: "Write `squares(numbers)`, returning a new array with every number multiplied by itself. A negative squares to a positive; zero and decimals square normally.",
    starter: `const squares = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(squares([2,3]));
`,
    skeleton: `const squares = numbers =>
  numbers.map(item => {
    return /* transformed item */;
  });`,
    hints: [
      "One output for every input, and squaring is just a number multiplied by itself — the same shape as doubling.",
    ],
    approach: [
      "Use map, since every input produces exactly one output.",
      "Multiply each number by itself, or use the exponent operator. Remember a negative input squares to a positive.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "squares([2,3])", expected: [4, 9] },
      { call: "squares([5])", expected: [25] },
      { call: "squares([])", expected: [], label: "empty input", edge: true },
      { call: "squares([-3])", expected: [9], label: "negative squares positive", edge: true },
      { call: "squares([0,1.5])", expected: [0, 2.25], label: "zero and decimals", edge: true },
    ],
  },
  {
    id: "js-largest-number",
    legacyId: "j9",
    track: "javascript",
    topic: "javascript",
    level: 6,
    tier: 1,
    focus: ["for"],
    title: "Largest number",
    prompt: "Write `largest(numbers)`, returning the biggest value in the array. It must still work when every value is negative, and when the maximum appears more than once. Assume at least one number.",
    starter: `const largest = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(largest([4,9,2]));
`,
    skeleton: `const largest = numbers => {
  const result = /* initial result */;

  for (const item of numbers) {
    // inspect item and update result
  }

  return result;
};`,
    hints: ["Compare every value with the largest seen."],
    approach: [
      "Either track the largest seen so far in a loop, or spread the array into Math.max.",
      "Make sure the comparison still works when every value is negative — starting from zero would be wrong.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "largest([4,9,2])", expected: 9 },
      { call: "largest([2,9,9])", expected: 9 },
      { call: "largest([7])", expected: 7, label: "single value", edge: true },
      { call: "largest([-5,-2])", expected: -2, label: "all negative", edge: true },
      { call: "largest([1,1])", expected: 1, label: "duplicates", edge: true },
    ],
  },
  {
    id: "js-fizz-values",
    legacyId: "j10",
    track: "javascript",
    topic: "javascript",
    level: 3,
    tier: 1,
    focus: ["for"],
    title: "Fizz values",
    prompt: "Write `fizz(n)`, returning an array counting 1 to n where every multiple of 3 is replaced by the string `Fizz` — `fizz(5)` gives `[1, 2, “Fizz”, 4, 5]`. `fizz(0)` gives an empty array.",
    starter: `const fizz = n => {
  
};

// Scratch pad — change this and press Run.
console.log(fizz(5));
`,
    skeleton: `const fizz = n => {
  const result = /* initial result */;

  for (const item of n) {
    // inspect item and update result
  }

  return result;
};`,
    hints: [
      "Count from 1 up to n, and for each number decide whether it divides by three before you decide what to put in the array.",
    ],
    approach: [
      "Build the numbers one through n first, then transform them.",
      "For each number, return the word Fizz when it divides evenly by three, and the number itself otherwise.",
      "Check the ends: n of zero produces nothing, and a multiple of three at the end must still be replaced.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "fizz(5)", expected: [1, 2, "Fizz", 4, 5] },
      { call: "fizz(6)", expected: [1, 2, "Fizz", 4, 5, "Fizz"] },
      { call: "fizz(0)", expected: [], label: "zero produces nothing", edge: true },
      { call: "fizz(1)", expected: [1], label: "below the first multiple", edge: true },
      { call: "fizz(3)", expected: [1, 2, "Fizz"], label: "ends on a multiple", edge: true },
    ],
  },
  {
    id: "js-countdown",
    legacyId: "j11",
    track: "javascript",
    topic: "javascript",
    level: 6,
    tier: 1,
    focus: ["while"],
    title: "Countdown",
    prompt: "Write `countDown(n)`, returning an array counting down from n to 1 — `countDown(3)` gives `[3, 2, 1]`. `countDown(0)` gives an empty array.",
    starter: `const countDown = n => {
  
};

// Scratch pad — change this and press Run.
console.log(countDown(3));
`,
    skeleton: `const countDown = n => {
  const result = /* initial result */;

  for (const item of n) {
    // inspect item and update result
  }

  return result;
};`,
    hints: ["Push n, then decrease it while it is positive."],
    approach: [
      "Use a while loop that keeps going while n is still positive.",
      "Push the current value, then decrease it, so the first pushed value is n itself and the last is one.",
      "Confirm that zero produces an empty array rather than looping forever.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "countDown(3)", expected: [3, 2, 1] },
      { call: "countDown(5)", expected: [5, 4, 3, 2, 1] },
      { call: "countDown(1)", expected: [1], label: "single step", edge: true },
      { call: "countDown(0)", expected: [], label: "zero produces nothing", edge: true },
    ],
  },
  {
    id: "js-first-letters",
    legacyId: "j12",
    track: "javascript",
    topic: "javascript",
    level: 2,
    tier: 1,
    focus: ["map", "strings"],
    title: "First letters",
    prompt: "Write `firstLetters(words)`, returning an array of the first character of each word, in order and with its original case.",
    starter: `const firstLetters = words => {
  
};

// Scratch pad — change this and press Run.
console.log(firstLetters(["red","blue"]));
`,
    skeleton: `const firstLetters = words =>
  words.map(item => {
    return /* transformed item */;
  });`,
    hints: [
      "One output per input again: each word becomes only its opening character, and a string can be indexed the way an array can.",
    ],
    approach: [
      "Use map, which gives exactly one letter back for every word in the list.",
      "Index the first character of each word, and keep its original case rather than changing it.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "firstLetters([\"red\",\"blue\"])", expected: ["r", "b"] },
      { call: "firstLetters([\"one\",\"two\",\"three\"])", expected: ["o", "t", "t"] },
      { call: "firstLetters([])", expected: [], label: "empty input", edge: true },
      { call: "firstLetters([\"solo\"])", expected: ["s"], label: "single word", edge: true },
      {
        call: "firstLetters([\"Red\",\"blue\"])",
        expected: ["R", "b"],
        label: "keeps original case",
        edge: true,
      },
    ],
  },
  {
    id: "js-has-adult",
    legacyId: "j13",
    track: "javascript",
    topic: "javascript",
    level: 7,
    tier: 1,
    focus: ["some"],
    title: "Has adult",
    prompt: "Write `hasAdult(ages)`, returning true when at least one age is 18 or more. Exactly 18 counts; an empty array is false.",
    starter: `const hasAdult = ages => {
  
};

// Scratch pad — change this and press Run.
console.log(hasAdult([12,18]));
`,
    skeleton: `const hasAdult = ages =>
  ages.some(item => {
    return /* condition */;
  });`,
    hints: [
      "You only need to know whether any single age qualifies, so the answer is a boolean and the search can stop the moment it finds one.",
    ],
    approach: [
      "Use some, which stops at the first match and hands back a boolean.",
      "The condition is at least eighteen, so eighteen itself must count.",
      "Remember that some over an empty array is false, which is the answer you want.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "hasAdult([12,18])", expected: true },
      { call: "hasAdult([20,10])", expected: true },
      { call: "hasAdult([17])", expected: false },
      { call: "hasAdult([18])", expected: true, label: "18 exactly counts", edge: true },
      { call: "hasAdult([])", expected: false, label: "empty input is false", edge: true },
    ],
  },
  {
    id: "js-all-positive",
    legacyId: "j14",
    track: "javascript",
    topic: "javascript",
    level: 7,
    tier: 1,
    focus: ["every"],
    title: "All positive",
    prompt: "Write `allPositive(numbers)`, returning true only when every value is above zero. Zero makes it false, and an empty array is true.",
    starter: `const allPositive = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(allPositive([1,2,3]));
`,
    skeleton: `const allPositive = numbers =>
  numbers.every(item => {
    return /* condition */;
  });`,
    hints: [
      "The opposite question to the last one: every value has to qualify. Think about what that means for a list with nothing in it to disqualify.",
    ],
    approach: [
      "Use every, which stops at the first failure and hands back a boolean.",
      "The condition is strictly greater than zero, so a zero makes the whole thing false.",
      "Note that every over an empty array is true — that is correct here, not a bug.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "allPositive([1,2,3])", expected: true },
      { call: "allPositive([1,-1])", expected: false },
      {
        call: "allPositive([])",
        expected: true,
        label: "empty input is vacuously true",
        edge: true,
      },
      { call: "allPositive([0])", expected: false, label: "zero is not positive", edge: true },
      { call: "allPositive([5])", expected: true, label: "single value", edge: true },
    ],
  },
  {
    id: "js-total-price",
    legacyId: "j15",
    track: "javascript",
    topic: "javascript",
    level: 8,
    tier: 1,
    focus: ["reduce", "objects"],
    title: "Total price",
    prompt: "Write `total(items)`, returning the sum of every item’s `price`. An empty array totals 0, and decimal prices add up normally.",
    starter: `const total = items => {
  
};

// Scratch pad — change this and press Run.
console.log(total([{price:2},{price:3}]));
`,
    skeleton: `const total = items =>
  items.reduce((accumulator, item) => {
    return /* next accumulator */;
  }, /* initial value */);`,
    hints: [
      "The same collapse-to-one-value shape as summing numbers, except the number you are adding is a property of each object.",
    ],
    approach: [
      "Use reduce with a numeric accumulator starting at zero.",
      "Add the price property of each item rather than the item itself.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "total([{price:2},{price:3}])", expected: 5 },
      { call: "total([{price:10}])", expected: 10 },
      { call: "total([])", expected: 0, label: "empty input returns 0", edge: true },
      { call: "total([{price:0}])", expected: 0, label: "zero price", edge: true },
      {
        call: "total([{price:1.5},{price:2.5}])",
        expected: 4,
        label: "decimal prices",
        edge: true,
      },
    ],
  },
  {
    id: "js-capitalize",
    legacyId: "j16",
    track: "javascript",
    topic: "javascript",
    level: 2,
    tier: 1,
    focus: ["strings"],
    title: "Capitalize",
    prompt: "Write `capitalize(text)`, returning the string with only its first character uppercased and the rest left alone — `hello world` becomes `Hello world`. An empty string comes back empty.",
    starter: `const capitalize = text => {
  
};

// Scratch pad — change this and press Run.
console.log(capitalize("hello"));
`,
    skeleton: `const capitalize = text => {
  // transform or inspect text
  return /* result */;
};`,
    hints: ["Combine the uppercase first character with slice(1)."],
    approach: [
      "Take the first character, uppercase it, and concatenate the rest of the string from index one onwards.",
      "Guard the empty string first, because indexing character zero of an empty string gives undefined.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "capitalize(\"hello\")", expected: "Hello" },
      { call: "capitalize(\"hello world\")", expected: "Hello world" },
      { call: "capitalize(\"\")", expected: "", label: "empty string", edge: true },
      { call: "capitalize(\"a\")", expected: "A", label: "single character", edge: true },
      {
        call: "capitalize(\"HELLO\")",
        expected: "HELLO",
        label: "already capitalised",
        edge: true,
      },
    ],
  },
  {
    id: "js-unique-values",
    legacyId: "j17",
    track: "javascript",
    topic: "javascript",
    level: 23,
    tier: 2,
    focus: ["map-set"],
    title: "Unique values",
    prompt: "Write `unique(values)`, returning a new array with duplicates removed, each value kept at the position it was first seen. It works for strings as well as numbers.",
    starter: `const unique = values => {
  
};

// Scratch pad — change this and press Run.
console.log(unique([1,1,2]));
`,
    skeleton: `const unique = values => {
  const seen = new Set(values);
  return /* the set, back as an array */;
};`,
    hints: ["Create a Set, then spread it into an array."],
    approach: [
      "Put the values into a Set, which discards duplicates and preserves first-seen order.",
      "Spread the Set back into an array so the return type matches the input.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "unique([1,1,2])", expected: [1, 2] },
      { call: "unique([1,2,3])", expected: [1, 2, 3] },
      { call: "unique([])", expected: [], label: "empty input", edge: true },
      { call: "unique([2,1,2,1])", expected: [2, 1], label: "keeps first-seen order", edge: true },
      { call: "unique([\"a\",\"a\"])", expected: ["a"], label: "strings too", edge: true },
    ],
  },
  {
    id: "js-word-count",
    legacyId: "j18",
    track: "javascript",
    topic: "javascript",
    level: 2,
    tier: 1,
    focus: ["split", "strings"],
    title: "Word count",
    prompt: "Write `wordCount(sentence)`, returning how many words the sentence holds. Surrounding whitespace does not count, repeated spaces between words do not create extra ones, and an empty string gives 0.",
    starter: `const wordCount = sentence => {
  
};

// Scratch pad — change this and press Run.
console.log(wordCount("one two three"));
`,
    skeleton: `const wordCount = sentence => {
  // transform or inspect sentence
  return /* result */;
};`,
    hints: [
      "Trim the ends first, then decide what separates one word from the next — and check what happens when two spaces sit next to each other.",
    ],
    approach: [
      "Trim the sentence first so leading and trailing spaces do not create empty words.",
      "Split on one-or-more whitespace rather than a single space, so repeated spaces do not inflate the count.",
      "Handle the empty string explicitly — splitting it yields one empty entry, not zero words.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "wordCount(\"one two three\")", expected: 3 },
      { call: "wordCount(\"a b\")", expected: 2 },
      { call: "wordCount(\"\")", expected: 0, label: "empty string returns 0", edge: true },
      { call: "wordCount(\"  hi  \")", expected: 1, label: "surrounding whitespace", edge: true },
      { call: "wordCount(\"one  two\")", expected: 2, label: "repeated spaces", edge: true },
    ],
  },
  {
    id: "js-find-user",
    legacyId: "j19",
    track: "javascript",
    topic: "javascript",
    level: 7,
    tier: 1,
    focus: ["find", "objects"],
    title: "Find user",
    prompt: "Write `findUser(users, name)`, returning the first user object whose `name` matches. Return `undefined` when nothing matches, or when the list is empty.",
    starter: `const findUser = (users, name) => {
  
};

// Scratch pad — change this and press Run.
console.log(findUser([{name:"Ana"}],"Ana"));
`,
    skeleton: `const findUser = (users, name) =>
  users.find(item => {
    return /* condition */;
  });`,
    hints: [
      "You want the first element that matches, and the array method for that already returns undefined when nothing does — no extra handling needed.",
    ],
    approach: [
      "Use find, which returns the first matching element rather than an array.",
      "Compare the name property of each user against the wanted name.",
      "Say what happens when nothing matches: find returns undefined, and that is the expected answer.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "findUser([{name:\"Ana\"}],\"Ana\")", expected: { name: "Ana" } },
      { call: "findUser([{name:\"Ana\"},{name:\"Bo\"}],\"Bo\")", expected: { name: "Bo" } },
      {
        call: "findUser([{name:\"Ana\"}],\"Bo\")",
        expected: undefined,
        label: "no match returns undefined",
        edge: true,
      },
      { call: "findUser([],\"Ana\")", expected: undefined, label: "empty list", edge: true },
    ],
  },
  {
    id: "js-odd-sum",
    legacyId: "j20",
    track: "javascript",
    topic: "javascript",
    level: 8,
    tier: 2,
    focus: ["filter", "reduce"],
    title: "Odd sum",
    prompt: "Write `oddSum(numbers)`, returning the total of just the odd values. Negative odds count; no odd values, or an empty array, totals 0.",
    starter: `const oddSum = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(oddSum([1,2,3]));
`,
    skeleton: `const oddSum = numbers =>
  numbers
    .filter(item => /* keep this item? */)
    .reduce((total, item) => /* next total */, 0);`,
    hints: [
      "Two steps in sequence: decide which values qualify, then collapse those into a single total that starts from zero.",
    ],
    approach: [
      "Filter to the odd values first, then reduce them to a total.",
      "Test oddness with a non-zero remainder so negative odd numbers are included too.",
      "Start the reduce at zero so an empty result still totals zero.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "oddSum([1,2,3])", expected: 4 },
      { call: "oddSum([1])", expected: 1 },
      { call: "oddSum([])", expected: 0, label: "empty input returns 0", edge: true },
      { call: "oddSum([2,4])", expected: 0, label: "no odd values", edge: true },
      { call: "oddSum([-1,-3])", expected: -4, label: "negative odds count", edge: true },
    ],
  },
  {
    id: "js-repeat-word",
    legacyId: "j21",
    track: "javascript",
    topic: "javascript",
    level: 2,
    tier: 2,
    focus: ["for", "strings"],
    title: "Repeat word",
    prompt: "Write `repeat(word, times)`, returning the word repeated that many times with single spaces between — `repeat(“hi”, 3)` gives `hi hi hi`. Once means no space at all, and zero times gives an empty string.",
    starter: `const repeat = (word, times) => {
  
};

// Scratch pad — change this and press Run.
console.log(repeat("hi",3));
`,
    skeleton: `const repeat = (word, times) => {
  const result = /* initial result */;

  for (const item of word) {
    // inspect item and update result
  }

  return result;
};`,
    hints: [
      "Build the pieces first and let the joining put the separators between them, rather than adding a space each time and trimming one off the end.",
    ],
    approach: [
      "Build a collection of n copies of the word, then join it.",
      "Join with a single space, which puts separators between copies but not around them — so one copy has no space at all.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "repeat(\"hi\",3)", expected: "hi hi hi" },
      { call: "repeat(\"ab\",2)", expected: "ab ab" },
      { call: "repeat(\"a\",1)", expected: "a", label: "once means no space", edge: true },
      { call: "repeat(\"x\",0)", expected: "", label: "zero repeats", edge: true },
    ],
  },
  {
    id: "js-number-range",
    legacyId: "j22",
    track: "javascript",
    topic: "javascript",
    level: 6,
    tier: 2,
    focus: ["for", "push"],
    title: "Number range",
    prompt: "Write `range(start, end)`, returning every integer from start through end, both included. Start may equal end, and a negative start works the same way.",
    starter: `const range = (start, end) => {
  
};

// Scratch pad — change this and press Run.
console.log(range(2,4));
`,
    skeleton: `const range = (start, end) => {
  const result = /* initial result */;

  for (const item of start) {
    // inspect item and update result
  }

  return result;
};`,
    hints: [
      "Count up from start while you have not gone past end. The boundary is the whole exercise, because end is included in the result.",
    ],
    approach: [
      "Work out how many values the range holds before you build it: end minus start, plus one.",
      "Generate values by adding the index to the start, so a negative start works the same way.",
      "Use an inclusive comparison so the end value is part of the result.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "range(2,4)", expected: [2, 3, 4] },
      { call: "range(0,3)", expected: [0, 1, 2, 3] },
      { call: "range(1,1)", expected: [1], label: "start equals end", edge: true },
      { call: "range(-2,0)", expected: [-2, -1, 0], label: "negative start", edge: true },
    ],
  },
  {
    id: "js-average",
    legacyId: "j23",
    track: "javascript",
    topic: "javascript",
    level: 8,
    tier: 2,
    focus: ["reduce"],
    title: "Average",
    prompt: "Write `average(numbers)`, returning the mean of the array. An empty array returns 0 rather than NaN.",
    starter: `const average = numbers => {
  
};

// Scratch pad — change this and press Run.
console.log(average([2,4,6]));
`,
    skeleton: `const average = numbers =>
  numbers.reduce((accumulator, item) => {
    return /* next accumulator */;
  }, /* initial value */);`,
    hints: [
      "A mean is a total divided by a count, so the only real decision here is what to hand back when the count is zero.",
    ],
    approach: [
      "Sum the values with reduce, then divide by how many there are.",
      "Guard the empty array before dividing, since dividing by a length of zero yields NaN.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "average([2,4,6])", expected: 4 },
      { call: "average([1,2])", expected: 1.5 },
      { call: "average([5])", expected: 5, label: "single value", edge: true },
      { call: "average([])", expected: 0, label: "empty input returns 0", edge: true },
      { call: "average([-2,2])", expected: 0, label: "negatives", edge: true },
    ],
  },
  {
    id: "js-short-words",
    legacyId: "j24",
    track: "javascript",
    topic: "javascript",
    level: 7,
    tier: 2,
    focus: ["filter", "strings"],
    title: "Short words",
    prompt: "Write `shortWords(words)`, returning only the words with fewer than five characters. Four characters passes, five does not.",
    starter: `const shortWords = words => {
  
};

// Scratch pad — change this and press Run.
console.log(shortWords(["cat","elephant"]));
`,
    skeleton: `const shortWords = words =>
  words.filter(item => {
    return /* true to keep this item */;
  });`,
    hints: [
      "A keep-or-drop decision on each word using its length. Read the boundary carefully: four characters passes and five does not.",
    ],
    approach: [
      "Use filter, keeping a word only when its length passes the comparison.",
      "The boundary matters: strictly fewer than five characters passes, so a four-letter word is kept and a five-letter word is not.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "shortWords([\"cat\",\"elephant\"])", expected: ["cat"] },
      { call: "shortWords([\"a\",\"bb\"])", expected: ["a", "bb"] },
      { call: "shortWords([])", expected: [], label: "empty input", edge: true },
      {
        call: "shortWords([\"abcd\"])",
        expected: ["abcd"],
        label: "four characters passes",
        edge: true,
      },
      {
        call: "shortWords([\"abcde\"])",
        expected: [],
        label: "five characters is too long",
        edge: true,
      },
    ],
  },
  {
    id: "js-object-keys",
    legacyId: "j25",
    track: "javascript",
    topic: "javascript",
    level: 5,
    tier: 2,
    focus: ["objects"],
    title: "Object keys",
    prompt: "Write `keys(object)`, returning an array of the object’s own key names in insertion order. An empty object gives an empty array.",
    starter: `const keys = object => {
  
};

// Scratch pad — change this and press Run.
console.log(keys({a:1,b:2}));
`,
    skeleton: `const keys = object => {
  // one Object.* call answers this
  return /* result */;
};`,
    hints: [
      "JavaScript hands you an object’s own key names as an array already — the question is which built-in returns the names rather than what is stored under them.",
    ],
    approach: [
      "Object.keys hands back the property names as an array.",
      "Confirm an empty object gives an empty array rather than undefined.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "keys({a:1,b:2})", expected: ["a", "b"] },
      { call: "keys({a:1,b:2,c:3})", expected: ["a", "b", "c"] },
      { call: "keys({})", expected: [], label: "empty object", edge: true },
      { call: "keys({x:1})", expected: ["x"], label: "single key", edge: true },
    ],
  },
  {
    id: "js-object-values",
    legacyId: "j26",
    track: "javascript",
    topic: "javascript",
    level: 5,
    tier: 2,
    focus: ["objects"],
    title: "Object values",
    prompt: "Write `values(object)`, returning an array of the object’s values in insertion order. `null` is a value like any other; an empty object gives an empty array.",
    starter: `const values = object => {
  
};

// Scratch pad — change this and press Run.
console.log(values({a:1,b:2}));
`,
    skeleton: `const values = object => {
  // one Object.* call answers this
  return /* result */;
};`,
    hints: [
      "The same family of built-ins as the previous challenge, but this time you want what is stored rather than what it is stored under.",
    ],
    approach: [
      "Object.values hands back the property values as an array.",
      "Remember null is a real value and must survive into the result.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "values({a:1,b:2})", expected: [1, 2] },
      { call: "values({x:\"s\"})", expected: ["s"] },
      { call: "values({})", expected: [], label: "empty object", edge: true },
      { call: "values({a:null})", expected: [null], label: "null is a value", edge: true },
    ],
  },
  {
    id: "js-activate-user",
    legacyId: "j27",
    track: "javascript",
    topic: "javascript",
    level: 10,
    tier: 2,
    focus: ["spread", "objects"],
    title: "Activate user",
    prompt: "Write `activate(user)`, returning a new object with the same properties plus `active: true`. The original object must not be changed, and an existing `active: false` is overridden.",
    starter: `const activate = user => {
  
};

// Scratch pad — change this and press Run.
console.log(activate({name:"Sam"}));
`,
    skeleton: `const activate = user => {
  // transform or inspect user
  return /* result */;
};`,
    hints: [
      "Build a new object instead of assigning onto the one you were given, and put the flag after the copied properties so it wins when both are present.",
    ],
    approach: [
      "Spread the original object into a new one rather than assigning to the original, so the input is left untouched.",
      "Write the active flag after the spread, so it overrides any existing value instead of being overridden by it.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "activate({name:\"Sam\"})", expected: { name: "Sam", active: true } },
      { call: "activate({age:3})", expected: { age: 3, active: true } },
      { call: "activate({})", expected: { active: true }, label: "empty object", edge: true },
      {
        call: "activate({name:\"A\",active:false})",
        expected: { name: "A", active: true },
        label: "overrides existing active",
        edge: true,
      },
    ],
  },
  {
    id: "js-palindrome",
    legacyId: "j28",
    track: "javascript",
    topic: "javascript",
    level: 2,
    tier: 2,
    focus: ["strings"],
    title: "Palindrome",
    prompt: "Write `isPalindrome(text)`, returning true when the string reads the same backwards. Assume plain lowercase letters; an empty string and a single character are both palindromes.",
    starter: `const isPalindrome = text => {
  
};

// Scratch pad — change this and press Run.
console.log(isPalindrome("level"));
`,
    skeleton: `const isPalindrome = text => {
  // transform or inspect text
  return /* result */;
};`,
    hints: ["Compare the word to its reversed version."],
    approach: [
      "Reverse the word using the same split, reverse, join route as the reverse-string challenge.",
      "Compare the reversed word with the original and return the comparison directly.",
      "Note that an empty string and a single character are both palindromes.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "isPalindrome(\"level\")", expected: true },
      { call: "isPalindrome(\"abba\")", expected: true },
      { call: "isPalindrome(\"abc\")", expected: false },
      {
        call: "isPalindrome(\"\")",
        expected: true,
        label: "empty string is a palindrome",
        edge: true,
      },
      { call: "isPalindrome(\"a\")", expected: true, label: "single character", edge: true },
    ],
  },
  {
    id: "js-letter-counts",
    legacyId: "j29",
    track: "javascript",
    topic: "javascript",
    level: 5,
    tier: 2,
    focus: ["for-of", "objects"],
    title: "Letter counts",
    prompt: "Write `countLetters(text)`, returning an object mapping each character to how many times it appears — `countLetters(“aba”)` gives `{ a: 2, b: 1 }`. An empty string gives an empty object.",
    starter: `const countLetters = text => {
  
};

// Scratch pad — change this and press Run.
console.log(countLetters("aba"));
`,
    skeleton: `const countLetters = text => {
  const result = /* initial result */;

  for (const item of text) {
    // inspect item and update result
  }

  return result;
};`,
    hints: [
      "Walk the characters building an object up as you go, treating a character you have not seen yet as though its count were already zero.",
    ],
    approach: [
      "Build an object as you walk the characters, using reduce or a loop.",
      "For each letter, read the existing count or fall back to zero, then store one more.",
      "The starting value is an empty object, which is also what an empty string returns.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "countLetters(\"aba\")", expected: { a: 2, b: 1 } },
      { call: "countLetters(\"abc\")", expected: { a: 1, b: 1, c: 1 } },
      {
        call: "countLetters(\"\")",
        expected: {},
        label: "empty string gives an empty object",
        edge: true,
      },
      { call: "countLetters(\"a\")", expected: { a: 1 }, label: "single letter", edge: true },
      {
        call: "countLetters(\"aab\")",
        expected: { a: 2, b: 1 },
        label: "repeats accumulate",
        edge: true,
      },
    ],
  },
  {
    id: "js-flatten-arrays",
    legacyId: "j30",
    track: "javascript",
    topic: "javascript",
    level: 8,
    tier: 3,
    focus: ["reduce", "flat"],
    title: "Flatten arrays",
    prompt: "Write `flatten(arrays)`, returning one array holding the items of each inner array, in order. Flatten a single level only, and do it without `Array.prototype.flat`.",
    starter: `const flatten = arrays => {
  
};

// Scratch pad — change this and press Run.
console.log(flatten([[1,2],[3]]));
`,
    skeleton: `const flatten = arrays =>
  arrays.reduce((accumulator, item) => {
    return /* next accumulator */;
  }, /* initial value */);`,
    hints: ["Reduce by concatenating each inner array."],
    approach: [
      "Reduce the outer array into a single result array.",
      "At each step, concatenate the inner array onto the accumulator — spreading it works and keeps the update immutable.",
      "Start from an empty array so both an empty input and an empty inner array behave.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "flatten([[1,2],[3]])", expected: [1, 2, 3] },
      { call: "flatten([[1],[2],[3]])", expected: [1, 2, 3] },
      { call: "flatten([])", expected: [], label: "empty input", edge: true },
      { call: "flatten([[]])", expected: [], label: "empty inner array", edge: true },
      { call: "flatten([[1,2]])", expected: [1, 2], label: "single inner array", edge: true },
    ],
  },
  {
    id: "js-call-once",
    legacyId: "j31",
    track: "javascript",
    topic: "javascript",
    level: 12,
    tier: 3,
    focus: ["closures"],
    title: "Call once",
    prompt: "Write `once(fn)`, returning a wrapped function that runs `fn` at most once. Every later call returns that first result without calling `fn` again — including when the first result is falsy — and each wrapper remembers its own.",
    starter: `const once = fn => {
  
};

// Scratch pad — uncomment once your function returns something.
// const doubleOnce = once(value => value * 2);
// console.log(doubleOnce(5));
// console.log(doubleOnce(9));
`,
    skeleton: `const once = fn => {
  // hold whatever has to survive between calls out here

  return (...args) => {
    // decide what this call does with that state
  };
};`,
    hints: ["Keep a done flag and the first result in the closure."],
    approach: [
      "Keep two pieces of state in the closure: a flag saying whether the call has already happened, and the value it produced.",
      "Check that flag first on every call — only while it is unset do you run the wrapped function and store what came back.",
      "Return the stored value either way, so the second and third callers get the first answer and the work never repeats.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "once(value => value * 2)(5)", expected: 10 },
      {
        call: "once(() => { const greet = once(name => \"hi \" + name); return [greet(\"ana\"), greet(\"bo\")]; })()",
        expected: ["hi ana", "hi ana"],
      },
      {
        call: "once(() => { let runs = 0; const bump = once(() => runs += 1); bump(); bump(); bump(); return runs; })()",
        expected: 1,
      },
      {
        call: "once(() => { const pick = once(value => value); return [pick(0), pick(7)]; })()",
        expected: [0, 0],
        label: "a falsy first result is still remembered",
        edge: true,
      },
      {
        call: "once(() => { const a = once(n => n + 1); const b = once(n => n + 1); return [a(1), b(5)]; })()",
        expected: [2, 6],
        label: "each wrapper has its own memory",
        edge: true,
      },
    ],
  },
  {
    id: "js-counter-object",
    legacyId: "j32",
    track: "javascript",
    topic: "javascript",
    level: 12,
    tier: 3,
    focus: ["closures"],
    title: "Counter object",
    prompt: "Write `makeCounter()`, returning a counter object. `increment` and `reset` change the count and return the counter so calls chain; `value()` returns the current count, starting at 0. Two counters never share a count.",
    starter: `const makeCounter = () => {
  
};

// Scratch pad — uncomment once your function returns something.
// console.log(makeCounter().increment().value());
`,
    skeleton: `const makeCounter = () => {
  // hold whatever has to survive between calls out here

  return (...args) => {
    // decide what this call does with that state
  };
};`,
    hints: ["Hold the count in the closure and return methods that read and change it."],
    approach: [
      "Hold the count in a variable inside the factory, where nothing outside can reach it except through the methods you hand back.",
      "Have increment and reset change that variable and then return the same object, which is what lets the calls chain together.",
      "Let value read the variable at the moment it is asked rather than copying the number in when the object is built.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "makeCounter().increment().value()", expected: 1 },
      { call: "makeCounter().increment().increment().increment().value()", expected: 3 },
      {
        call: "makeCounter().value()",
        expected: 0,
        label: "a fresh counter starts at zero",
        edge: true,
      },
      {
        call: "makeCounter().increment().increment().reset().value()",
        expected: 0,
        label: "reset clears the count",
        edge: true,
      },
      {
        call: "makeCounter().increment().reset().increment().value()",
        expected: 1,
        label: "counting continues after a reset",
        edge: true,
      },
      {
        call: "makeCounter().increment().value() + makeCounter().increment().increment().value()",
        expected: 3,
        label: "each counter keeps its own count",
        edge: true,
      },
    ],
  },
  {
    id: "js-debounce-calls",
    legacyId: "j33",
    track: "javascript",
    topic: "javascript",
    level: 15,
    tier: 4,
    focus: ["timers", "closures"],
    title: "Debounce calls",
    prompt: "Write `debounce(fn, waitMs)`, returning a debounced function. Each call restarts the timer, so only the last call in a burst runs, `waitMs` after it and with that last call’s arguments. Two debounced functions keep separate timers.",
    starter: `const debounce = (fn, waitMs) => {
  
};

// Scratch pad — uncomment once your function returns something.
// const save = debounce(word => console.log(word), 20);
// save("a"); save("b"); save("c");
`,
    skeleton: `const debounce = (fn, waitMs) => {
  let timer;

  return (...args) => {
    // cancel or ignore the pending call, then schedule this one
  };
};`,
    hints: ["Clear the pending timer every time a new call arrives."],
    approach: [
      "Keep the id of the pending timer in the closure, since the next call has to be able to reach it.",
      "Every call cancels the timer that is already waiting and schedules a fresh one, so a burst keeps pushing the run further out.",
      "Schedule the run with the arguments of the call that scheduled it, which is why the last call in a burst is the one that lands.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "debounce(value => value, 10) && (async () => { const log = []; const save = debounce(word => log.push(word), 20); save(\"a\"); save(\"b\"); save(\"c\"); await new Promise(done => setTimeout(done, 80)); return log; })()",
        expected: ["c"],
        async: true,
      },
      {
        call: "debounce(value => value, 10) && (async () => { const wait = ms => new Promise(done => setTimeout(done, ms)); const log = []; const save = debounce(n => log.push(n), 20); save(1); await wait(80); save(2); await wait(80); return log; })()",
        expected: [1, 2],
        async: true,
      },
      {
        call: "debounce(value => value, 10) && (async () => { const log = []; const save = debounce((a, b) => log.push(a + b), 20); save(1, 2); save(10, 20); await new Promise(done => setTimeout(done, 80)); return log; })()",
        expected: [30],
        label: "the last call decides the arguments",
        edge: true,
        async: true,
      },
      {
        call: "debounce(value => value, 10) && (async () => { const log = []; const save = debounce(word => log.push(word), 20); save(\"x\"); const before = log.length; await new Promise(done => setTimeout(done, 80)); return [before, log.length]; })()",
        expected: [0, 1],
        label: "nothing runs while the burst is going",
        edge: true,
        async: true,
      },
      {
        call: "debounce(value => value, 10) && (async () => { const log = []; const slow = debounce(() => log.push(\"slow\"), 40); const quick = debounce(() => log.push(\"quick\"), 5); slow(); quick(); await new Promise(done => setTimeout(done, 100)); return log; })()",
        expected: ["quick", "slow"],
        label: "two debounced functions keep separate timers",
        edge: true,
        async: true,
      },
    ],
  },
  {
    id: "js-throttle-calls",
    legacyId: "j34",
    track: "javascript",
    topic: "javascript",
    level: 15,
    tier: 4,
    focus: ["timers", "closures"],
    title: "Throttle calls",
    prompt: "Write `throttle(fn, waitMs)`, returning a throttled function with a leading edge: the first call runs immediately, and any call made during the next `waitMs` is dropped rather than replayed later. Two throttled functions keep separate windows.",
    starter: `const throttle = (fn, waitMs) => {
  
};

// Scratch pad — uncomment once your function returns something.
// const send = throttle(n => console.log(n), 40);
// send(1); send(2); send(3);
`,
    skeleton: `const throttle = (fn, waitMs) => {
  let timer;

  return (...args) => {
    // cancel or ignore the pending call, then schedule this one
  };
};`,
    hints: ["Remember when the last run happened and compare it with now."],
    approach: [
      "Record the time of the last run in the closure, starting it far enough in the past that the very first call is allowed through.",
      "Compare now against that stamp on each call: run and update it once the window has passed, and otherwise drop the call.",
      "Dropped calls are forgotten rather than queued, so nothing replays them when the window reopens.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "throttle(value => value, 10) && (async () => { const log = []; const save = throttle(n => log.push(n), 40); save(1); save(2); save(3); return log; })()",
        expected: [1],
        async: true,
      },
      {
        call: "throttle(value => value, 10) && (async () => { const log = []; const save = throttle(n => log.push(n), 30); save(1); await new Promise(done => setTimeout(done, 70)); save(2); return log; })()",
        expected: [1, 2],
        async: true,
      },
      {
        call: "throttle(value => value, 10) && (async () => { const log = []; const save = throttle(word => log.push(word), 30); save(\"first\"); save(\"second\"); await new Promise(done => setTimeout(done, 70)); save(\"third\"); return log; })()",
        expected: ["first", "third"],
        label: "a dropped call is never replayed",
        edge: true,
        async: true,
      },
      {
        call: "throttle(value => value, 10) && (async () => { const log = []; const save = throttle(n => log.push(n), 40); const before = log.length; save(9); return [before, log.length]; })()",
        expected: [0, 1],
        label: "the first call runs before any waiting",
        edge: true,
        async: true,
      },
      {
        call: "throttle(value => value, 10) && (async () => { const log = []; const a = throttle(n => log.push(\"a\" + n), 40); const b = throttle(n => log.push(\"b\" + n), 40); a(1); b(1); a(2); return log; })()",
        expected: ["a1", "b1"],
        label: "each throttled function has its own window",
        edge: true,
        async: true,
      },
    ],
  },
  {
    id: "js-sleep",
    legacyId: "j35",
    track: "javascript",
    topic: "javascript",
    level: 21,
    tier: 3,
    focus: ["promises", "timers"],
    title: "Sleep",
    prompt: "Write `sleep(ms)`, returning a promise that resolves after `ms` milliseconds with no value. A zero wait still resolves.",
    starter: `const sleep = ms => {
  
};

// Scratch pad — uncomment once your function returns something.
// sleep(50).then(() => console.log("done waiting"));
`,
    skeleton: `const sleep = async ms => {
  // await the work, and decide what happens when it rejects
  return /* resolved value */;
};`,
    hints: ["Wrap setTimeout in a promise and resolve it from the callback."],
    approach: [
      "Return the promise straight away and hand its resolve function to a timer, so the promise settles when the timer fires.",
      "Nothing is passed to resolve, which is why awaiting it gives you no value back — the waiting itself is the point.",
      "Because the wait sits on a timer, the rest of the program keeps running instead of being blocked.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "sleep(20).then(() => \"awake\")", expected: "awake", async: true },
      {
        call: "sleep(10).then(() => sleep(10)).then(() => \"twice\")",
        expected: "twice",
        async: true,
      },
      {
        call: "sleep(5).then(() => { const order = []; return Promise.all([sleep(60).then(() => order.push(\"slow\")), sleep(5).then(() => order.push(\"fast\"))]).then(() => order); })",
        expected: ["fast", "slow"],
        async: true,
      },
      {
        call: "sleep(0).then(() => 2 + 2)",
        expected: 4,
        label: "a zero wait still resolves",
        edge: true,
        async: true,
      },
      {
        call: "sleep(15).then(result => typeof result)",
        expected: "undefined",
        label: "it resolves with no value",
        edge: true,
        async: true,
      },
    ],
  },
  {
    id: "js-retry-on-failure",
    legacyId: "j36",
    track: "javascript",
    topic: "javascript",
    level: 22,
    tier: 4,
    focus: ["async-await", "promises"],
    title: "Retry on failure",
    prompt: "Write `retry(fn, attempts)`, calling the async `fn` until it resolves or the attempt budget runs out. Resolve with the first success; when every attempt fails, reject with the last error rather than the first.",
    starter: `const retry = (fn, attempts) => {
  
};

// Scratch pad — uncomment once your function returns something.
// retry(async () => "ok", 3).then(result => console.log(result));
`,
    skeleton: `const retry = async (fn, attempts) => {
  // await the work, and decide what happens when it rejects
  return /* resolved value */;
};`,
    hints: ["Loop over the attempts and return as soon as one resolves."],
    approach: [
      "Loop over the attempt budget rather than recursing, and put the call inside a try so a rejection does not escape the loop.",
      "Return the moment an attempt resolves, which leaves the loop and skips the attempts you no longer need.",
      "Hold on to the error from each failure so that, once the budget is spent, you can throw the last one instead of an empty failure.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "retry(async () => \"ok\", 3)", expected: "ok", async: true },
      {
        call: "retry((() => { let runs = 0; return async () => { runs += 1; if (runs < 3) throw new Error(\"flaky\"); return \"ok on \" + runs; }; })(), 5)",
        expected: "ok on 3",
        async: true,
      },
      {
        call: "retry(async () => { throw new Error(\"always down\"); }, 2).catch(error => error.message)",
        expected: "always down",
        async: true,
      },
      {
        call: "retry((() => { let runs = 0; return async () => { runs += 1; throw new Error(\"attempt \" + runs); }; })(), 3).catch(error => error.message)",
        expected: "attempt 3",
        label: "it stops once the attempts run out",
        edge: true,
        async: true,
      },
      {
        call: "retry(async () => 0, 1)",
        expected: 0,
        label: "one attempt is enough when it works",
        edge: true,
        async: true,
      },
    ],
  },
  {
    id: "js-clone-promise-all",
    legacyId: "j37",
    track: "javascript",
    topic: "javascript",
    level: 21,
    tier: 4,
    focus: ["promises"],
    title: "Clone Promise.all",
    prompt: "Write `promiseAll(promises)`, resolving with every value in input order, or rejecting as soon as one input rejects. Plain non-promise values are allowed, an empty array resolves to an empty array, and you may not call `Promise.all`.",
    starter: `const promiseAll = promises => {
  
};

// Scratch pad — uncomment once your function returns something.
// promiseAll([Promise.resolve(1), Promise.resolve(2)]).then(values => console.log(values));
`,
    skeleton: `const promiseAll = async promises => {
  // await the work, and decide what happens when it rejects
  return /* resolved value */;
};`,
    hints: ["Store each value by its index and resolve once they have all arrived."],
    approach: [
      "Return a new promise, and inside it keep an array for the results plus a count of how many have arrived.",
      "Subscribe to each input in turn and write its value into the results at the index it came in at, so the output order matches the input order.",
      "Resolve only once the arrival count reaches the input length, and forward any rejection straight on so the first failure settles everything.",
      "Watch the empty input: with nothing to wait for, the count never moves, so resolve before you start subscribing.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "promiseAll([Promise.resolve(1), Promise.resolve(2)])",
        expected: [1, 2],
        async: true,
      },
      {
        call: "promiseAll([new Promise(done => setTimeout(() => done(\"slow\"), 40)), Promise.resolve(\"fast\")])",
        expected: ["slow", "fast"],
        async: true,
      },
      {
        call: "promiseAll([Promise.resolve(1), (failing => (failing.catch(() => {}), failing))(Promise.reject(new Error(\"bad\")))]).catch(error => error.message)",
        expected: "bad",
        async: true,
      },
      {
        call: "promiseAll([7, Promise.resolve(8)])",
        expected: [7, 8],
        label: "plain values are allowed",
        edge: true,
        async: true,
      },
      {
        call: "promiseAll([])",
        expected: [],
        label: "no promises at all",
        edge: true,
        async: true,
      },
    ],
  },
  {
    id: "js-run-tasks-in-order",
    legacyId: "j38",
    track: "javascript",
    topic: "javascript",
    level: 22,
    tier: 4,
    focus: ["async-await", "promises"],
    title: "Run tasks in order",
    prompt: "Write `runSequentially(tasks)`, calling an array of async functions one after another — never in parallel — and resolving with their results in order. Plain return values and an empty array both work.",
    starter: `const runSequentially = tasks => {
  
};

// Scratch pad — uncomment once your function returns something.
// runSequentially([async () => 1, async () => 2]).then(values => console.log(values));
`,
    skeleton: `const runSequentially = async tasks => {
  // await the work, and decide what happens when it rejects
  return /* resolved value */;
};`,
    hints: ["Await each task inside a loop instead of starting them all at once."],
    approach: [
      "Walk the tasks with an ordinary loop and await each one before moving on, which is what makes them run one at a time.",
      "Collect each awaited value as you go, so the results line up with the order the tasks were given in.",
      "Calling every task up front would start them all at once, so the call itself has to happen inside the loop.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "runSequentially([async () => 1, async () => 2, async () => 3])",
        expected: [1, 2, 3],
        async: true,
      },
      {
        call: "runSequentially((log => [() => new Promise(done => setTimeout(() => { log.push(\"slow\"); done(log.join(\",\")); }, 40)), async () => (log.push(\"fast\"), log.join(\",\"))])([]))",
        expected: ["slow", "slow,fast"],
        async: true,
      },
      {
        call: "runSequentially([() => \"a\", () => \"b\"])",
        expected: ["a", "b"],
        label: "plain return values work too",
        edge: true,
        async: true,
      },
      {
        call: "runSequentially([])",
        expected: [],
        label: "no tasks at all",
        edge: true,
        async: true,
      },
      {
        call: "runSequentially([async () => 0])",
        expected: [0],
        label: "a single task keeps its falsy result",
        edge: true,
        async: true,
      },
    ],
  },
  {
    id: "js-chunk-an-array",
    legacyId: "j39",
    track: "javascript",
    topic: "javascript",
    level: 24,
    tier: 3,
    focus: ["slice", "for"],
    title: "Chunk an array",
    prompt: "Write `chunk(items, size)`, splitting the array into groups of that size. A trailing group may be shorter, a size larger than the array gives one group, and an empty array gives an empty array.",
    starter: `const chunk = (items, size) => {
  
};

// Scratch pad — change this and press Run.
console.log(chunk([1,2,3,4], 2));
`,
    skeleton: `const chunk = (items, size) => {
  // transform or inspect items
  return /* result */;
};`,
    hints: ["Slice a window of the array for every group."],
    approach: [
      "Work out how many groups you need first: the length divided by the size, rounded up.",
      "For each group position, take a slice starting at that position times the size and running for size items.",
      "Slice stops at the end of the array by itself, so an uneven split leaves a short final group and an oversized size gives one group.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "chunk([1,2,3,4], 2)",
        expected: [
          [1, 2],
          [3, 4],
        ],
      },
      {
        call: "chunk([1,2,3,4,5], 2)",
        expected: [
          [1, 2],
          [3, 4],
          [5],
        ],
      },
      { call: "chunk([], 3)", expected: [], label: "empty input", edge: true },
      {
        call: "chunk([1,2], 5)",
        expected: [
          [1, 2],
        ],
        label: "a size larger than the array",
        edge: true,
      },
      {
        call: "chunk([\"a\",\"b\",\"c\"], 1)",
        expected: [
          ["a"],
          ["b"],
          ["c"],
        ],
        label: "a size of one",
        edge: true,
      },
    ],
  },
  {
    id: "js-group-by-key",
    legacyId: "j40",
    track: "javascript",
    topic: "javascript",
    level: 8,
    tier: 3,
    focus: ["reduce", "objects"],
    title: "Group by key",
    prompt: "Write `groupBy(items, keyFn)`, returning an object that groups the items by whatever `keyFn` returns for each. That return becomes an object key — so numbers arrive as strings — and each value is the array of matching items, in order.",
    starter: `const groupBy = (items, keyFn) => {
  
};

// Scratch pad — change this and press Run.
console.log(groupBy([1,2,3,4], n => n % 2 === 0 ? "even" : "odd"));
`,
    skeleton: `const groupBy = (items, keyFn) => {
  // transform or inspect items
  return /* result */;
};`,
    hints: ["Reduce into an object, pushing each item into its key’s array."],
    approach: [
      "Fold over the items and build the result object as you go, starting from an object with no keys at all.",
      "Ask the key function which bucket each item belongs to, create that bucket as an empty array when it is missing, then push the item in.",
      "Object keys are strings, so a number handed back by the key function shows up as its text form in the result.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "groupBy([1,2,3,4], n => n % 2 === 0 ? \"even\" : \"odd\")",
        expected: { odd: [1, 3], even: [2, 4] },
      },
      {
        call: "groupBy([\"ant\",\"bee\",\"cow\"], word => word[0])",
        expected: { a: ["ant"], b: ["bee"], c: ["cow"] },
      },
      {
        call: "groupBy([{name:\"Ana\",team:\"red\"},{name:\"Bo\",team:\"red\"}], person => person.team)",
        expected: {
          red: [
            { name: "Ana", team: "red" },
            { name: "Bo", team: "red" },
          ],
        },
      },
      {
        call: "groupBy([], n => n)",
        expected: {},
        label: "empty input gives an empty object",
        edge: true,
      },
      {
        call: "groupBy([1.2,1.8,2.5], n => Math.floor(n))",
        expected: { "1": [1.2, 1.8], "2": [2.5] },
        label: "keys become strings",
        edge: true,
      },
      {
        call: "groupBy([\"a\",\"b\"], () => \"all\")",
        expected: { all: ["a", "b"] },
        label: "everything in one group",
        edge: true,
      },
    ],
  },
  {
    id: "js-memoize-results",
    legacyId: "j41",
    track: "javascript",
    topic: "javascript",
    level: 12,
    tier: 4,
    focus: ["closures", "map-set"],
    title: "Memoize results",
    prompt: "Write `memoize(fn)`, returning a wrapped function that caches by its first argument, so `fn` runs once per distinct argument. A falsy result is cached too, and each wrapper has its own cache.",
    starter: `const memoize = fn => {
  
};

// Scratch pad — uncomment once your function returns something.
// console.log(memoize(value => value * 3)(4));
`,
    skeleton: `const memoize = fn => {
  // hold whatever has to survive between calls out here

  return (...args) => {
    // decide what this call does with that state
  };
};`,
    hints: [
      "The wrapper needs somewhere to remember past answers between calls. Ask whether the key is present rather than whether the stored value is truthy, or a cached zero looks like a miss.",
    ],
    approach: [
      "Create the cache once, outside the function you return, so every later call shares it — a Map keyed by the argument is enough.",
      "Look the argument up in the cache first and hand back the stored result whenever it is already there.",
      "Only when the argument is missing do you run the wrapped function and store what it gave you.",
      "Test for presence rather than truthiness, or a cached zero or empty string gets recomputed every single time.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      { call: "memoize(value => value * 3)(4)", expected: 12 },
      {
        call: "memoize(() => { let runs = 0; const slow = memoize(n => { runs += 1; return n * 2; }); return [slow(5), slow(5), runs]; })()",
        expected: [10, 10, 1],
      },
      {
        call: "memoize(() => { let runs = 0; const slow = memoize(n => { runs += 1; return n * 2; }); return [slow(2), slow(3), slow(2), runs]; })()",
        expected: [4, 6, 4, 2],
      },
      {
        call: "memoize(() => { let runs = 0; const count = memoize(() => runs++); return [count(), count(), runs]; })()",
        expected: [0, 0, 1],
        label: "a falsy result is cached too",
        edge: true,
      },
      {
        call: "memoize(() => { const a = memoize(n => n + 1); const b = memoize(n => n + 100); return [a(1), b(1)]; })()",
        expected: [2, 101],
        label: "each wrapper has its own cache",
        edge: true,
      },
    ],
  },
  {
    id: "js-event-emitter",
    legacyId: "j42",
    track: "javascript",
    topic: "javascript",
    level: 14,
    tier: 4,
    focus: ["closures", "objects", "callbacks"],
    title: "Event emitter",
    prompt: "Write `createEmitter()`, returning an emitter with `on`, `off` and `emit`. `on` and `off` return the emitter so calls chain; `off(name, listener)` drops that one listener while `off(name)` drops every listener for that event; `emit(name, payload)` calls each listener with the payload and returns their results as an array.",
    starter: `const createEmitter = () => {
  
};

// Scratch pad — uncomment once your function returns something.
// const bus = createEmitter();
// bus.on("greet", name => console.log("hi " + name));
// bus.emit("greet", "ana");
`,
    skeleton: `const createEmitter = () => {
  // hold whatever has to survive between calls out here

  return (...args) => {
    // decide what this call does with that state
  };
};`,
    hints: ["Keep an object of listener arrays, one per event name."],
    approach: [
      "Keep an object in the closure mapping each event name to the array of listeners registered against it.",
      "Registering appends the listener to that name and hands the emitter back, which is what lets registrations chain.",
      "Removal filters the listener out by identity, so the caller has to pass the very same function it registered earlier.",
      "Emitting looks up the array for the name, calls each listener with the payload and collects what they return; an unknown name gives an empty array.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "createEmitter().on(\"greet\", name => \"hi \" + name).emit(\"greet\", \"ana\")",
        expected: ["hi ana"],
      },
      {
        call: "createEmitter().on(\"tick\", n => n + 1).on(\"tick\", n => n * 2).emit(\"tick\", 3)",
        expected: [4, 6],
      },
      {
        call: "createEmitter().on(\"tick\", n => n).on(\"tick\", n => n * 2).off(\"tick\").emit(\"tick\", 4)",
        expected: [],
      },
      {
        call: "createEmitter().on(\"tick\", Number).on(\"tick\", Boolean).off(\"tick\", Number).emit(\"tick\", \"2\")",
        expected: [true],
        label: "off removes only the listener it is given",
        edge: true,
      },
      {
        call: "createEmitter().emit(\"nothing\", 1)",
        expected: [],
        label: "emitting with no listeners",
        edge: true,
      },
      {
        call: "createEmitter().on(\"a\", n => n).emit(\"b\", 2)",
        expected: [],
        label: "listeners only hear their own event",
        edge: true,
      },
    ],
  },
  {
    id: "js-lru-cache",
    legacyId: "j43",
    track: "javascript",
    topic: "javascript",
    level: 23,
    tier: 4,
    focus: ["map-set", "for-of"],
    title: "LRU cache",
    prompt: "Write `LRUCache(strArr)`, taking an array of letters that were accessed in order and returning what is left in a cache holding at most 5, joined with hyphens. Accessing a letter already in the cache moves it to the most recent end rather than adding it again; once the cache is full, the least recently used letter is dropped. `LRUCache([\"A\", \"B\", \"A\", \"C\", \"A\", \"B\"])` gives `\"C-A-B\"`.",
    starter: `const LRUCache = strArr => {
  
};

// Scratch pad — change this and press Run.
console.log(LRUCache(["A","B","C","D","A","E","D","Z"]));
`,
    skeleton: `const LRUCache = strArr => {
  const result = /* initial result */;

  for (const item of strArr) {
    // inspect item and update result
  }

  return result;
};`,
    hints: [
      "Keep the cache as an array with the most recently used letter last. A letter you have seen before is removed from where it was before being pushed back on.",
    ],
    approach: [
      "Decide how the cache is ordered before writing anything: keeping the most recently used at the end means an eviction is just dropping the first element.",
      "Walk the letters in order, and for each one work out whether it is already in the cache.",
      "A letter you have seen before is not added twice — take it out of its old position first, then push it on the end so it counts as the most recent.",
      "After adding, drop from the front while the cache is over the limit — that eviction is the whole exercise — then join what is left with hyphens.",
    ],
    verify: "tests",
    estimatedMinutes: 20,
    tests: [
      {
        call: "LRUCache([\"A\",\"B\",\"C\",\"D\",\"A\",\"E\",\"D\",\"Z\"])",
        expected: "C-A-E-D-Z",
      },
      { call: "LRUCache([\"A\",\"B\",\"A\",\"C\",\"A\",\"B\"])", expected: "C-A-B" },
      {
        call: "LRUCache([\"A\",\"B\",\"C\",\"D\",\"E\",\"D\",\"Q\",\"Z\",\"C\"])",
        expected: "E-D-Q-Z-C",
      },
      {
        call: "LRUCache([\"A\",\"B\",\"C\"])",
        expected: "A-B-C",
        label: "never fills the cache",
        edge: true,
      },
      {
        call: "LRUCache([\"A\",\"A\",\"A\"])",
        expected: "A",
        label: "the same letter over and over",
        edge: true,
      },
      { call: "LRUCache([])", expected: "", label: "nothing accessed at all", edge: true },
      {
        call: "LRUCache([\"A\",\"B\",\"C\",\"D\",\"E\",\"F\"])",
        expected: "B-C-D-E-F",
        label: "the sixth letter evicts the first",
        edge: true,
      },
    ],
  },
];
