// Generated by scripts/port-interview-prepper.mjs from the interview-prepper catalogue.
// Task bodies only: prompts, starters, visible tests, hints. No solutions.
// English is the source of truth; Czech copy lives in the sibling *.cs.ts overlay.

import type { CodingTaskSource } from '../types';

export const TYPESCRIPT_TASKS: CodingTaskSource[] = [
  {
    id: "ts-typed-slug",
    legacyId: "t1",
    track: "typescript",
    topic: "typescript",
    level: 1,
    tier: 1,
    focus: ["annotations", "strings"],
    title: "Typed slug",
    prompt: "Write `toSlug(title: string): string`, turning a title into a URL slug: trimmed, lowercased, with every run of spaces replaced by a single dash. An empty string gives an empty string, and a single word comes back as itself.",
    starter: `const toSlug = (title) => {
  
};

// Scratch pad — change this and press Run.
console.log(toSlug("Hello World"));
`,
    skeleton: `const toSlug = (title: string): string => {
  // build and return the answer
};`,
    hints: [
      "The whole job is three string operations in a row, and the type is the same going in and coming out.",
    ],
    approach: [
      "Annotate the parameter and the return value first, then write the body — the compiler will tell you the moment the two disagree.",
      "Trim the ends before you lowercase, so padding never turns into a leading or trailing dash.",
      "Splitting on one space is not enough when two sit together; split on a run of whitespace, then join the pieces with a dash.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "toSlug(\"Hello World\")", expected: "hello-world" },
      { call: "toSlug(\"Interview Prepper App\")", expected: "interview-prepper-app" },
      { call: "toSlug(\"\")", expected: "", label: "empty string", edge: true },
      {
        call: "toSlug(\"  Padded  Title  \")",
        expected: "padded-title",
        label: "padding and repeated spaces",
        edge: true,
      },
      { call: "toSlug(\"Solo\")", expected: "solo", label: "a single word", edge: true },
    ],
    typeTests: [
      { code: "const __slug: string = toSlug(\"Hello World\");", label: "gives back a string" },
      { code: "toSlug(42);", label: "refuses anything but a string", rejects: true },
      {
        code: "const __count: number = toSlug(\"Hello World\");",
        label: "what it returns is not a number",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-top-three-scores",
    legacyId: "t2",
    track: "typescript",
    topic: "typescript",
    level: 4,
    tier: 1,
    focus: ["annotations", "sort", "slice"],
    title: "Top three scores",
    prompt: "Write `topThree(scores: number[]): number[]`, returning the three highest values, largest first. Fewer than three values gives back all of them in order, and the array you were handed must not be reordered in place.",
    starter: `const topThree = (scores) => {
  
};

// Scratch pad — change this and press Run.
console.log(topThree([5,9,1,7]));
`,
    skeleton: `const topThree = (scores: number[]): number[] => {
  // build and return the answer
};`,
    hints: [
      "Sort reorders the array it is given, so copy first — and without a comparator it orders numbers as if they were words.",
    ],
    approach: [
      "Copy the array before sorting, because sort reorders the array it is given rather than returning a fresh one.",
      "Sort compares values as text unless you hand it a comparator, so pass one that subtracts to get numeric order.",
      "Take the first three off the sorted copy; asking for three when there are fewer simply gives you what there is.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "topThree([5,9,1,7])", expected: [9, 7, 5] },
      { call: "topThree([3,1,2])", expected: [3, 2, 1] },
      { call: "topThree([4])", expected: [4], label: "fewer than three", edge: true },
      { call: "topThree([])", expected: [], label: "empty input", edge: true },
      { call: "topThree([-1,-5,-3])", expected: [-1, -3, -5], label: "all negative", edge: true },
    ],
    typeTests: [
      {
        code: "const __best: number[] = topThree([1, 2, 3]);",
        label: "gives back an array of numbers",
      },
      { code: "topThree([\"9\", \"8\"]);", label: "refuses an array of strings", rejects: true },
      {
        code: "const __words: string[] = topThree([1]);",
        label: "what comes back is not an array of strings",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-greeting-with-a-default",
    legacyId: "t3",
    track: "typescript",
    topic: "typescript",
    level: 3,
    tier: 1,
    focus: ["annotations", "optional"],
    title: "Greeting with a default",
    prompt: "Write `greet(name: string, greeting?: string): string`, returning the greeting, a comma, the name and an exclamation mark — `Hello, Ada!`. The greeting is optional and falls back to `Hello`, but an empty greeting that was actually passed is used as given.",
    starter: `const greet = (name, greeting) => {
  
};

// Scratch pad — change this and press Run.
console.log(greet("Ada"));
`,
    skeleton: `const greet = (name: string, greeting = "Hello"): string => {
  // build and return the answer
};`,
    hints: [
      "A default value in the parameter list is what makes an argument optional — and only a missing one is replaced by it.",
    ],
    approach: [
      "A default value in the parameter list is what makes an argument optional, and the compiler infers its type from that default.",
      "Only a missing argument or an explicit undefined triggers the default, which is why an empty greeting passed on purpose survives.",
      "Build the sentence from the greeting, a comma, the name and an exclamation mark.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "greet(\"Ada\")", expected: "Hello, Ada!" },
      { call: "greet(\"Bo\", \"Hi\")", expected: "Hi, Bo!" },
      {
        call: "greet(\"Cher\", undefined)",
        expected: "Hello, Cher!",
        label: "undefined falls back to the default",
        edge: true,
      },
      {
        call: "greet(\"Dee\", \"\")",
        expected: ", Dee!",
        label: "an empty greeting is used as given",
        edge: true,
      },
    ],
    typeTests: [
      { code: "const __line: string = greet(\"Ada\");", label: "the greeting can be left out" },
      { code: "greet();", label: "the name cannot be left out", rejects: true },
      { code: "greet(\"Ada\", 3);", label: "the greeting has to be text", rejects: true },
    ],
  },
  {
    id: "ts-person-interface",
    legacyId: "t4",
    track: "typescript",
    topic: "typescript",
    level: 6,
    tier: 1,
    focus: ["interfaces"],
    title: "Person interface",
    prompt: "Declare an interface named `Person` with `first` and `last`, both strings, then write `fullName(person: Person): string` joining them with a single space. When either half is empty the space goes too, so no answer ever starts or ends with one.",
    starter: `const fullName = (person) => {
  
};

// Scratch pad — change this and press Run.
console.log(fullName({first:"Ada",last:"Lovelace"}));
`,
    skeleton: `interface Person {
  first: string;
  last: string;
}

const fullName = (person: Person): string => {
  // build and return the answer
};`,
    hints: [
      "An interface is a named shape written once above the function, and then used wherever that shape is expected.",
    ],
    approach: [
      "Write the interface above the function: a name, then one line per property with its type.",
      "Use that name as the parameter type, and the body can read both properties without any further checks.",
      "Join the two halves with a space, but drop the empty ones first, or a missing half leaves a space stranded at one end.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "fullName({first:\"Ada\",last:\"Lovelace\"})", expected: "Ada Lovelace" },
      { call: "fullName({first:\"Bo\",last:\"Ng\"})", expected: "Bo Ng" },
      {
        call: "fullName({first:\"\",last:\"Solo\"})",
        expected: "Solo",
        label: "no first name",
        edge: true,
      },
      {
        call: "fullName({first:\"Cher\",last:\"\"})",
        expected: "Cher",
        label: "no last name",
        edge: true,
      },
      { call: "fullName({first:\"\",last:\"\"})", expected: "", label: "neither half", edge: true },
    ],
    typeTests: [
      {
        code: "const __shown: string = fullName({ first: \"Ada\", last: \"Lovelace\" });",
        label: "gives back a string",
      },
      {
        code: "const __person: Person = { first: \"Ada\", last: \"Lovelace\" };",
        label: "Person is a type you can name",
      },
      { code: "fullName({ first: \"Ada\" });", label: "both halves are required", rejects: true },
    ],
  },
  {
    id: "ts-optional-nickname",
    legacyId: "t5",
    track: "typescript",
    topic: "typescript",
    level: 9,
    tier: 1,
    focus: ["optional", "interfaces"],
    title: "Optional nickname",
    prompt: "Declare an interface named `User` with a required `name` and an optional `nickname`, both strings, then write `displayName(user: User): string` returning the nickname when the property is there and the name when it is not. A nickname that is present but empty still wins.",
    starter: `const displayName = (user) => {
  
};

// Scratch pad — change this and press Run.
console.log(displayName({name:"Ada",nickname:"Addy"}));
`,
    skeleton: `interface User {
  name: string;
  nickname?: string;
}

const displayName = (user: User): string => {
  // build and return the answer
};`,
    hints: [
      "Two fallback operators look interchangeable here and are not: one gives way on any falsy value, the other only on null and undefined.",
    ],
    approach: [
      "Marking a property optional with a question mark means reading it gives you the type or undefined, and the compiler makes you handle both.",
      "Choose the fallback operator that steps in only for null and undefined, not the one that also steps in for an empty string.",
      "Nothing else is needed in the body: the whole challenge is which of those two fallbacks is correct.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "displayName({name:\"Ada\",nickname:\"Addy\"})", expected: "Addy" },
      {
        call: "displayName({name:\"Bo\"})",
        expected: "Bo",
        label: "no nickname at all",
        edge: true,
      },
      {
        call: "displayName({name:\"Cher\",nickname:\"\"})",
        expected: "",
        label: "an empty nickname is still a nickname",
        edge: true,
      },
      {
        call: "displayName({name:\"Dee\",nickname:undefined})",
        expected: "Dee",
        label: "an explicit undefined falls back",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __shown: string = displayName({ name: \"Ada\" });",
        label: "gives back a string",
      },
      { code: "const __user: User = { name: \"Ada\" };", label: "the nickname really is optional" },
      {
        code: "displayName({ nickname: \"Addy\" });",
        label: "the name is not optional",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-padded-id",
    legacyId: "t6",
    track: "typescript",
    topic: "typescript",
    level: 11,
    tier: 2,
    focus: ["narrowing", "unions"],
    title: "Padded id",
    prompt: "Write `idText(id: string | number): string`. A number comes back as text padded with leading zeros to four characters; a string comes back untouched. A number already four characters or longer keeps its own length.",
    starter: `const idText = (id) => {
  
};

// Scratch pad — change this and press Run.
console.log(idText(7));
`,
    skeleton: `const idText = (id: string | number): string => {
  // check which half of the union you have, then handle each
};`,
    hints: [
      "A union has to be split before either half can be used, and a typeof check is what tells the compiler which one it is holding.",
    ],
    approach: [
      "A value typed as one thing or the other cannot be used as either until you have checked which one you are holding.",
      "A typeof check is enough, and inside that branch the compiler treats the value as a number for the rest of the block.",
      "Padding is a string operation, so convert the number first, then ask for a width of four with zero as the filler.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "idText(7)", expected: "0007" },
      { call: "idText(1234)", expected: "1234" },
      { call: "idText(\"a1\")", expected: "a1" },
      {
        call: "idText(12345)",
        expected: "12345",
        label: "longer than four is left alone",
        edge: true,
      },
      {
        call: "idText(\"\")",
        expected: "",
        label: "an empty string is still a string",
        edge: true,
      },
    ],
    typeTests: [
      { code: "const __text: string = idText(7);", label: "a number gives back a string" },
      { code: "const __same: string = idText(\"a1\");", label: "a string does too" },
      { code: "idText(true);", label: "a boolean is not part of the union", rejects: true },
    ],
  },
  {
    id: "ts-shipping-speed",
    legacyId: "t7",
    track: "typescript",
    topic: "typescript",
    level: 8,
    tier: 1,
    focus: ["literal-types"],
    title: "Shipping speed",
    prompt: "Declare a type alias named `Speed` allowing only `standard`, `express` or `overnight`, then write `shippingDays(speed: Speed, weekend: boolean): number` giving 5, 2 and 1 day respectively, with one extra day when the order was placed at the weekend.",
    starter: `const shippingDays = (speed, weekend) => {
  
};

// Scratch pad — change this and press Run.
console.log(shippingDays("standard", false));
`,
    skeleton: `type Speed = "standard" | "express" | "overnight";

const shippingDays = (speed: Speed, weekend: boolean): number => {
  // build and return the answer
};`,
    hints: [
      "A type alias can list the exact strings that are allowed, which turns a typo into a compile error rather than a bug.",
    ],
    approach: [
      "A type alias listing exact string values means only those three spellings ever get through.",
      "Map each allowed value to its number of days, then decide separately whether the weekend adds one.",
      "Comparing against one of the listed values narrows the type, so the last branch needs no check at all.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "shippingDays(\"standard\", false)", expected: 5 },
      { call: "shippingDays(\"express\", false)", expected: 2 },
      { call: "shippingDays(\"overnight\", false)", expected: 1 },
      {
        call: "shippingDays(\"overnight\", true)",
        expected: 2,
        label: "the weekend adds a day",
        edge: true,
      },
      {
        call: "shippingDays(\"standard\", true)",
        expected: 6,
        label: "it adds one to the slowest option too",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __days: number = shippingDays(\"express\", false);",
        label: "gives back a number",
      },
      { code: "const __speed: Speed = \"overnight\";", label: "Speed is a type you can name" },
      {
        code: "shippingDays(\"next-day\", false);",
        label: "an unlisted speed is refused",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-split-a-name",
    legacyId: "t8",
    track: "typescript",
    topic: "typescript",
    level: 4,
    tier: 2,
    focus: ["tuples", "split"],
    title: "Split a name",
    prompt: "Write `splitName(text: string): [string, string]`, returning a tuple of the first word and everything after it. A single word gives an empty second half, an empty string gives two empty halves, and only the first space ever splits.",
    starter: `const splitName = (text) => {
  
};

// Scratch pad — change this and press Run.
console.log(splitName("Ada Lovelace"));
`,
    skeleton: `const splitName = (text: string): [string, string] => {
  // build and return the answer
};`,
    hints: ["A tuple type fixes both how many values come back and what sits at each position."],
    approach: [
      "A tuple type pins down both how many values come back and what each position holds.",
      "Find the first space by index rather than splitting, because splitting would break a three-word name into three pieces.",
      "No space at all is its own case: the whole text is the first half and the second half is empty.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "splitName(\"Ada Lovelace\")", expected: ["Ada", "Lovelace"] },
      {
        call: "splitName(\"Mary Anne Evans\")",
        expected: ["Mary", "Anne Evans"],
        label: "only the first space splits",
        edge: true,
      },
      { call: "splitName(\"Bo\")", expected: ["Bo", ""], label: "one word", edge: true },
      { call: "splitName(\"\")", expected: ["", ""], label: "empty string", edge: true },
    ],
    typeTests: [
      {
        code: "const __pair: [string, string] = splitName(\"Ada Lovelace\");",
        label: "gives back exactly two strings",
      },
      {
        code: "const __first: string = splitName(\"Ada Lovelace\")[0];",
        label: "each position holds a string",
      },
      {
        code: "const __three: [string, string, string] = splitName(\"Ada Lovelace\");",
        label: "two, not three",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-tally-votes",
    legacyId: "t9",
    track: "typescript",
    topic: "typescript",
    level: 20,
    tier: 2,
    focus: ["record", "for-of"],
    title: "Tally votes",
    prompt: "Write `tally(votes: string[]): Record<string, number>`, counting how many times each string appears. The result has one key per distinct vote, and an empty list gives an object with no keys at all.",
    starter: `const tally = (votes) => {
  
};

// Scratch pad — change this and press Run.
console.log(tally(["a","b","a"]));
`,
    skeleton: `const tally = (votes: string[]): Record<string, number> => {
  // build and return the answer
};`,
    hints: [
      "Record describes an object used as a lookup: what the keys are, and what every value stored under them is.",
    ],
    approach: [
      "Record describes an object used as a lookup table: the type of its keys, then the type of every value under them.",
      "Fold the list into an object, reading the count already stored under each vote and adding one to it.",
      "A vote seen for the first time has no count stored yet, so treat a missing entry as zero before adding.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "tally([\"a\",\"b\",\"a\"])", expected: { a: 2, b: 1 } },
      { call: "tally([\"x\"])", expected: { x: 1 } },
      { call: "tally([])", expected: {}, label: "empty input", edge: true },
      {
        call: "tally([\"a\",\"a\",\"a\"])",
        expected: { a: 3 },
        label: "one value, counted three times",
        edge: true,
      },
      {
        call: "tally([\"a\",\"b\",\"c\"])",
        expected: { a: 1, b: 1, c: 1 },
        label: "all distinct",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __counts: Record<string, number> = tally([\"a\"]);",
        label: "gives back a lookup of numbers",
      },
      {
        code: "const __texts: Record<string, string> = tally([\"a\"]);",
        label: "the values are numbers, not strings",
        rejects: true,
      },
      { code: "tally([1, 2]);", label: "the votes are strings", rejects: true },
    ],
  },
  {
    id: "ts-rotate-a-list",
    legacyId: "t10",
    track: "typescript",
    topic: "typescript",
    level: 9,
    tier: 2,
    focus: ["readonly", "slice"],
    title: "Rotate a list",
    prompt: "Write `rotate(items: readonly string[]): string[]`, returning a new array with the first item moved to the end. The parameter is readonly, so the array you were handed comes back unchanged; an empty list and a single item both come back as they are.",
    starter: `const rotate = (items) => {
  
};

// Scratch pad — change this and press Run.
console.log(rotate(["a","b","c"]));
`,
    skeleton: `const rotate = (items: readonly string[]): string[] => {
  // build and return the answer
};`,
    hints: [
      "A readonly array is missing every method that would change it, which is the compiler telling you to build a new one.",
    ],
    approach: [
      "A readonly array type has no push, no splice and no sort, which is the compiler telling you to build a new array.",
      "Take everything after the opening item, then put that opening item on the end of the copy.",
      "An empty list has no opening item to move, so answer that case before the general one.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "rotate([\"a\",\"b\",\"c\"])", expected: ["b", "c", "a"] },
      { call: "rotate([\"a\",\"b\"])", expected: ["b", "a"] },
      { call: "rotate([\"a\"])", expected: ["a"], label: "one item", edge: true },
      { call: "rotate([])", expected: [], label: "empty input", edge: true },
    ],
    typeTests: [
      {
        code: "const __moved: string[] = rotate([\"a\", \"b\"]);",
        label: "gives back a normal array of strings",
      },
      {
        code: "rotate([\"a\", \"b\"] as readonly string[]);",
        label: "a readonly array is accepted",
      },
      { code: "rotate([1, 2]);", label: "numbers are not strings", rejects: true },
    ],
  },
  {
    id: "ts-describe-a-value",
    legacyId: "t11",
    track: "typescript",
    topic: "typescript",
    level: 12,
    tier: 2,
    focus: ["narrowing", "unions"],
    title: "Describe a value",
    prompt: "Write `describeValue(value: unknown): string`, returning `nothing` for null or undefined, `a list` for an array, `text` for a string, `a number` for a number, and `something else` for anything left over.",
    starter: `const describeValue = (value) => {
  
};

// Scratch pad — change this and press Run.
console.log(describeValue("hi"));
`,
    skeleton: `const describeValue = (value: unknown): string => {
  // narrow the value one case at a time before using it
};`,
    hints: [
      "typeof reports null as an object, so ruling out the empty cases first is what stops them taking the wrong branch.",
    ],
    approach: [
      "unknown is the safe opposite of any: anything can be assigned to it, and nothing can be done with it until it is narrowed.",
      "Rule out null and undefined first, because typeof reports one of them as an object and would send it down the wrong branch.",
      "Arrays are objects too, so ask whether it is an array before you fall back to the catch-all answer.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "describeValue(\"hi\")", expected: "text" },
      { call: "describeValue(3)", expected: "a number" },
      { call: "describeValue([1,2])", expected: "a list" },
      { call: "describeValue(null)", expected: "nothing", label: "null", edge: true },
      { call: "describeValue(undefined)", expected: "nothing", label: "undefined", edge: true },
      {
        call: "describeValue({})",
        expected: "something else",
        label: "a plain object",
        edge: true,
      },
    ],
    typeTests: [
      { code: "const __label: string = describeValue(1);", label: "gives back a string" },
      { code: "describeValue(Symbol(\"x\"));", label: "unknown accepts any value at all" },
      {
        code: "const __size: number = describeValue(1);",
        label: "the answer is text, not a number",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-first-item",
    legacyId: "t12",
    track: "typescript",
    topic: "typescript",
    level: 14,
    tier: 2,
    focus: ["generics"],
    title: "First item",
    prompt: "Write `first<T>(items: T[]): T | undefined`, returning the opening item of an array of anything, and `undefined` when there is nothing in it. One type parameter is enough — the caller should get back the type they put in.",
    starter: `const first = (items) => {
  
};

// Scratch pad — change this and press Run.
console.log(first([1,2,3]));
`,
    skeleton: `const first = <T>(items: T[]): T | undefined => {
  // build and return the answer
};`,
    hints: [
      "A type parameter is a type the caller fills in, so the answer keeps whatever went in instead of widening to any.",
    ],
    approach: [
      "Introduce a type parameter in angle brackets before the parameter list, then use it to describe what the array holds.",
      "The return type has to admit that an empty array has no opening item, which is what the union with undefined says.",
      "The body is a single index read; everything interesting here is in the signature.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "first([1,2,3])", expected: 1 },
      { call: "first([\"a\",\"b\"])", expected: "a" },
      { call: "first([])", expected: undefined, label: "empty input", edge: true },
      { call: "first([[1],[2]])", expected: [1], label: "an array of arrays", edge: true },
      {
        call: "first([null,1])",
        expected: null,
        label: "a null first item is still the first item",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __one: number | undefined = first([1, 2]);",
        label: "numbers in, numbers out",
      },
      {
        code: "const __word: string | undefined = first([\"a\"]);",
        label: "strings in, strings out",
      },
      {
        code: "const __sure: number = first([1]);",
        label: "it might be undefined, and the type says so",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-fall-back-to-a-default",
    legacyId: "t13",
    track: "typescript",
    topic: "typescript",
    level: 7,
    tier: 2,
    focus: ["unions", "generics"],
    title: "Fall back to a default",
    prompt: "Write `orDefault<T>(value: T | null | undefined, fallback: T): T`, returning the value unless it is null or undefined, in which case the fallback. Zero, an empty string and false are real values and come back as they are.",
    starter: `const orDefault = (value, fallback) => {
  
};

// Scratch pad — change this and press Run.
console.log(orDefault(null, 5));
`,
    skeleton: `const orDefault = <T>(value: T | null | undefined, fallback: T): T => {
  // build and return the answer
};`,
    hints: [
      "The point of the function is that the answer can no longer be missing, which is why the return type is the plain type.",
    ],
    approach: [
      "The value may be missing but the fallback may not, which is what makes the return type the plain type again.",
      "Both parameters share one type parameter, so a caller cannot pass a fallback of a different type by accident.",
      "Use the fallback operator that steps in only for null and undefined, or a legitimate zero gets replaced.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "orDefault(null, 5)", expected: 5 },
      { call: "orDefault(3, 5)", expected: 3 },
      {
        call: "orDefault(undefined, \"x\")",
        expected: "x",
        label: "undefined falls back",
        edge: true,
      },
      { call: "orDefault(0, 5)", expected: 0, label: "zero is a real value", edge: true },
      {
        call: "orDefault(\"\", \"x\")",
        expected: "",
        label: "an empty string is a real value",
        edge: true,
      },
    ],
    typeTests: [
      { code: "const __sure: number = orDefault(null, 5);", label: "null can never come back out" },
      {
        code: "const __word: string = orDefault(\"a\", \"b\");",
        label: "the type follows what went in",
      },
      {
        code: "const __wrong: string = orDefault(1, 2);",
        label: "numbers in do not give a string out",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-transform-a-list",
    legacyId: "t14",
    track: "typescript",
    topic: "typescript",
    level: 3,
    tier: 2,
    focus: ["generics", "map"],
    title: "Transform a list",
    prompt: "Write `transform<T, R>(items: T[], change: (item: T) => R): R[]`, running the callback over every item and collecting the results. The callback takes one argument, and the type it returns is the element type of the array that comes back.",
    starter: `const transform = (items, change) => {
  
};

// Scratch pad — change this and press Run.
console.log(transform([1,2,3], n => n * 2));
`,
    skeleton: `const transform = <T, R>(items: T[], change: (item: T) => R): R[] => {
  // build and return the answer
};`,
    hints: [
      "Two type parameters, not one: what the list holds and what the callback hands back are allowed to differ.",
    ],
    approach: [
      "Two type parameters are needed: one for what the list holds, one for whatever the callback hands back.",
      "A function type in a parameter list says what the callback receives and what it must return.",
      "Walk the list, call the callback with each item, and collect the answers into a new array.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "transform([1,2,3], n => n * 2)", expected: [2, 4, 6] },
      { call: "transform([\"a\",\"b\"], s => s.toUpperCase())", expected: ["A", "B"] },
      {
        call: "transform([1,2], n => String(n))",
        expected: ["1", "2"],
        label: "the element type can change",
        edge: true,
      },
      { call: "transform([], n => n)", expected: [], label: "empty input", edge: true },
    ],
    typeTests: [
      {
        code: "const __texts: string[] = transform([1], n => String(n));",
        label: "the callback decides what comes back",
      },
      {
        code: "const __sizes: number[] = transform([\"a\"], s => s.length);",
        label: "and it can change the type on the way",
      },
      {
        code: "transform([1], (s: string) => s);",
        label: "the callback must accept what the list holds",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-sort-by-name",
    legacyId: "t15",
    track: "typescript",
    topic: "typescript",
    level: 15,
    tier: 3,
    focus: ["constraints", "sort"],
    title: "Sort by name",
    prompt: "Write `sortByName<T extends { name: string }>(items: T[]): T[]`, returning a new array ordered A to Z by `name`. Anything with a name is allowed in, its other properties survive, and the array handed in is not reordered.",
    starter: `const sortByName = (items) => {
  
};

// Scratch pad — change this and press Run.
console.log(sortByName([{name:"Bo"},{name:"Ada"}]));
`,
    skeleton: `const sortByName = <T extends {name: string}>(items: T[]): T[] => {
  // build and return the answer
};`,
    hints: [
      "Constrain the type parameter to anything carrying a name, and you can read that property while still handing back the caller’s own type.",
    ],
    approach: [
      "A constraint says the type parameter may be anything at all, as long as it has the properties you are about to read.",
      "Returning the constrained type rather than the shape it was constrained to is what keeps the caller’s extra properties visible.",
      "Copy before sorting, and compare the two names as text rather than subtracting them.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      {
        call: "sortByName([{name:\"Bo\"},{name:\"Ada\"}])",
        expected: [
          { name: "Ada" },
          { name: "Bo" },
        ],
      },
      {
        call: "sortByName([{name:\"Bo\",age:9},{name:\"Ada\",age:36}])",
        expected: [
          { name: "Ada", age: 36 },
          { name: "Bo", age: 9 },
        ],
      },
      { call: "sortByName([])", expected: [], label: "empty input", edge: true },
      {
        call: "sortByName([{name:\"Solo\"}])",
        expected: [
          { name: "Solo" },
        ],
        label: "a single item",
        edge: true,
      },
      {
        call: "sortByName([{name:\"Ada\",id:1},{name:\"Ada\",id:2}])",
        expected: [
          { name: "Ada", id: 1 },
          { name: "Ada", id: 2 },
        ],
        label: "equal names keep their original order",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __people: { name: string; age: number }[] = sortByName([{ name: \"Ada\", age: 36 }]);",
        label: "extra properties survive the round trip",
      },
      {
        code: "sortByName([{ title: \"Ada\" }]);",
        label: "something with no name is refused",
        rejects: true,
      },
      {
        code: "const __names: string[] = sortByName([{ name: \"Ada\" }]);",
        label: "whole items come back, not names",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-pluck-a-property",
    legacyId: "t16",
    track: "typescript",
    topic: "typescript",
    level: 16,
    tier: 3,
    focus: ["keyof", "map"],
    title: "Pluck a property",
    prompt: "Write `pluck<T, K extends keyof T>(items: T[], key: K): T[K][]`, collecting one property from every object in the list. The key has to name a property that exists, and what comes back is an array of whatever that property holds.",
    starter: `const pluck = (items, key) => {
  
};

// Scratch pad — change this and press Run.
console.log(pluck([{id:1},{id:2}], "id"));
`,
    skeleton: `const pluck = <T, K extends keyof T>(items: T[], key: K): T[K][] => {
  // build and return the answer
};`,
    hints: [
      "keyof turns an object type into the union of its property names, and an indexed access type looks up what sits under one.",
    ],
    approach: [
      "keyof turns an object type into the union of its property names, which is what the key parameter should be constrained to.",
      "An indexed access type looks up what is stored under that key, and that is the element type of the array you return.",
      "The body is one pass over the list, reading the same property from every item.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "pluck([{id:1},{id:2}], \"id\")", expected: [1, 2] },
      { call: "pluck([{name:\"a\"},{name:\"b\"}], \"name\")", expected: ["a", "b"] },
      {
        call: "pluck([{id:1,name:\"a\"}], \"name\")",
        expected: ["a"],
        label: "only the property that was asked for",
        edge: true,
      },
      { call: "pluck([{id:1}], \"id\")", expected: [1], label: "a single item", edge: true },
    ],
    typeTests: [
      {
        code: "const __ids: number[] = pluck([{ id: 1 }], \"id\");",
        label: "a numeric property gives numbers",
      },
      {
        code: "const __names: string[] = pluck([{ id: 1, name: \"a\" }], \"name\");",
        label: "a string property gives strings",
      },
      {
        code: "pluck([{ id: 1 }], \"missing\");",
        label: "a key that is not there is refused",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-apply-a-patch",
    legacyId: "t17",
    track: "typescript",
    topic: "typescript",
    level: 18,
    tier: 3,
    focus: ["utility-types", "spread"],
    title: "Apply a patch",
    prompt: "Declare an interface named `Settings` with a `theme` string and a `fontSize` number, then write `applyPatch(settings: Settings, patch: Partial<Settings>): Settings`, returning a new settings object with whatever the patch supplies written over the original.",
    starter: `const applyPatch = (settings, patch) => {
  
};

// Scratch pad — change this and press Run.
console.log(applyPatch({theme:"dark",fontSize:14}, {fontSize:16}));
`,
    skeleton: `interface Settings {
  theme: string;
  fontSize: number;
}

const applyPatch = (settings: Settings, patch: Partial<Settings>): Settings => {
  // build and return the answer
};`,
    hints: [
      "Partial takes a type you already have and makes every property optional, which is exactly what a patch is.",
    ],
    approach: [
      "Partial rewrites an existing type with every property optional, so a patch never needs a type of its own.",
      "Spread the original first and the patch second, so anything the patch supplies wins.",
      "Build a new object rather than assigning into the original, or the caller’s settings change under them.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      {
        call: "applyPatch({theme:\"dark\",fontSize:14}, {fontSize:16})",
        expected: { theme: "dark", fontSize: 16 },
      },
      {
        call: "applyPatch({theme:\"dark\",fontSize:14}, {theme:\"light\",fontSize:12})",
        expected: { theme: "light", fontSize: 12 },
      },
      {
        call: "applyPatch({theme:\"dark\",fontSize:14}, {})",
        expected: { theme: "dark", fontSize: 14 },
        label: "an empty patch changes nothing",
        edge: true,
      },
      {
        call: "applyPatch({theme:\"dark\",fontSize:14}, {fontSize:0})",
        expected: { theme: "dark", fontSize: 0 },
        label: "zero still overwrites",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __next: Settings = applyPatch({ theme: \"dark\", fontSize: 14 }, { fontSize: 16 });",
        label: "gives back complete settings",
      },
      { code: "const __empty: Partial<Settings> = {};", label: "a patch may supply nothing" },
      {
        code: "applyPatch({ theme: \"dark\", fontSize: 14 }, { fontSize: \"16\" });",
        label: "a patch still has to have the right types",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-hide-the-password",
    legacyId: "t18",
    track: "typescript",
    topic: "typescript",
    level: 19,
    tier: 3,
    focus: ["utility-types", "destructuring"],
    title: "Hide the password",
    prompt: "Declare an interface named `Account` with a numeric `id` and string `email` and `password`, then write `publicUser(account: Account): Omit<Account, \"password\">`, returning a copy with the password removed rather than blanked.",
    starter: `const publicUser = (account) => {
  
};

// Scratch pad — change this and press Run.
console.log(publicUser({id:1,email:"ada@example.dev",password:"secret"}));
`,
    skeleton: `interface Account {
  id: number;
  email: string;
  password: string;
}

const publicUser = (account: Account): Omit<Account, "password"> => {
  // pull the secret out of the value, and return what is left
};`,
    hints: [
      "Omit builds a new type from an existing one with named properties taken out, and rest destructuring does the same to the value.",
    ],
    approach: [
      "Omit builds a type from one you already have with the named properties taken out.",
      "Rest destructuring does the same job to the value: pull the secret into its own variable and keep whatever is left.",
      "Returning that rest is enough, because the property is genuinely absent rather than set to an empty value.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      {
        call: "publicUser({id:1,email:\"ada@example.dev\",password:\"secret\"})",
        expected: { id: 1, email: "ada@example.dev" },
      },
      {
        call: "publicUser({id:9,email:\"cher@example.dev\",password:\"hunter2\"})",
        expected: { id: 9, email: "cher@example.dev" },
      },
      {
        call: "publicUser({id:2,email:\"bo@example.dev\",password:\"\"})",
        expected: { id: 2, email: "bo@example.dev" },
        label: "an empty password is removed too",
        edge: true,
      },
      {
        call: "publicUser({id:3,email:\"\",password:\"p\"})",
        expected: { id: 3, email: "" },
        label: "everything else is kept exactly as it was",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __safe: Omit<Account, \"password\"> = publicUser({ id: 1, email: \"e\", password: \"p\" });",
        label: "gives back an account without the password",
      },
      {
        code: "publicUser({ id: 1, email: \"e\", password: \"p\" }).password;",
        label: "the password is gone from the type as well",
        rejects: true,
      },
      {
        code: "publicUser({ id: 1, email: \"e\" });",
        label: "an account without a password is not an Account",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-area-of-a-shape",
    legacyId: "t19",
    track: "typescript",
    topic: "typescript",
    level: 12,
    tier: 3,
    focus: ["unions", "narrowing"],
    title: "Area of a shape",
    prompt: "Declare a type alias named `Shape` for a square with a `side`, a rectangle with `width` and `height`, or a triangle with `base` and `height`, each tagged with a `kind`. Then write `area(shape: Shape): number` returning the area of whichever it turns out to be.",
    starter: `const area = (shape) => {
  
};

// Scratch pad — change this and press Run.
console.log(area({kind:"square",side:3}));
`,
    skeleton: `type Shape =
  | {kind: "square"; side: number}
  | {kind: "rectangle"; width: number; height: number}
  | {kind: "triangle"; base: number; height: number};

const area = (shape: Shape): number => {
  // check the tag, then use that member’s own properties
};`,
    hints: [
      "Every member of the union carries the same tag with a different exact value, and checking that tag is what unlocks the rest of the object.",
    ],
    approach: [
      "Give every member of the union the same tag property, each with a different exact string value.",
      "Checking the tag narrows the value to one member, and only then are that member’s own properties readable.",
      "Handle the members one at a time; the last needs no check, because nothing else is left it could be.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "area({kind:\"square\",side:3})", expected: 9 },
      { call: "area({kind:\"rectangle\",width:2,height:5})", expected: 10 },
      { call: "area({kind:\"triangle\",base:4,height:3})", expected: 6 },
      {
        call: "area({kind:\"square\",side:0})",
        expected: 0,
        label: "a shape with no size",
        edge: true,
      },
      {
        call: "area({kind:\"triangle\",base:3,height:3})",
        expected: 4.5,
        label: "the answer need not be whole",
        edge: true,
      },
    ],
    typeTests: [
      {
        code: "const __size: number = area({ kind: \"square\", side: 2 });",
        label: "gives back a number",
      },
      {
        code: "area({ kind: \"circle\", radius: 1 });",
        label: "a shape that is not in the union is refused",
        rejects: true,
      },
      {
        code: "area({ kind: \"square\", width: 2 });",
        label: "a square has a side, not a width",
        rejects: true,
      },
    ],
  },
  {
    id: "ts-only-the-strings",
    legacyId: "t20",
    track: "typescript",
    topic: "typescript",
    level: 12,
    tier: 3,
    focus: ["type-guards", "filter"],
    title: "Only the strings",
    prompt: "Write `isString(value: unknown): value is string`, then use it in `onlyStrings(values: unknown[]): string[]` to keep only the strings from a mixed list, in their original order. Without the predicate on the first, what the second filters out stays unknown to the compiler.",
    starter: `const isString = (value) => {
  
};

const onlyStrings = (values) => {
  
};

// Scratch pad — change this and press Run.
console.log(onlyStrings(["a",1,"b"]));
`,
    skeleton: `const isString = (value: unknown): value is string => /* the check */;

const onlyStrings = (values: unknown[]): string[] => {
  // build and return the answer
};`,
    hints: [
      "A predicate returns a plain boolean at runtime; its return type is what tells the compiler what a true answer proves.",
    ],
    approach: [
      "A type predicate is an ordinary boolean function whose return type tells the compiler what a true answer proves about its argument.",
      "Write the check first, as its own named function, and then hand that function to filter.",
      "Filtering with a plain inline test would leave the result as wide as it started, which is the whole reason the predicate exists.",
    ],
    verify: "tests",
    estimatedMinutes: 10,
    tests: [
      { call: "onlyStrings([\"a\",1,\"b\"])", expected: ["a", "b"] },
      { call: "onlyStrings([\"x\"])", expected: ["x"] },
      { call: "onlyStrings([1,2])", expected: [], label: "nothing matches", edge: true },
      { call: "onlyStrings([])", expected: [], label: "empty input", edge: true },
      {
        call: "onlyStrings([\"a\",null,undefined,\"b\"])",
        expected: ["a", "b"],
        label: "null and undefined are not strings",
        edge: true,
      },
    ],
    typeTests: [
      { code: "const __words: string[] = onlyStrings([\"a\", 1]);", label: "gives back strings" },
      {
        code: "const __one: string = [\"a\", 1].filter(isString)[0];",
        label: "the predicate narrows anything it filters",
      },
      {
        code: "const __sizes: number[] = onlyStrings([\"a\"]);",
        label: "strings come back, not numbers",
        rejects: true,
      },
    ],
  },
];
