// Czech copy for lib/coding/tasks/typescript-loops.ts, keyed by task id. Arrays align by
// index with the English source; the content test enforces parity.

import type { CodingTaskCs } from '../types';

export const TYPESCRIPT_LOOP_TASKS_CS: Record<string, CodingTaskCs> = {
  "ts-inferred-total": {
    title: "Odvozený součet",
    prompt: "Napiš `totalLength(words: string[]): number`, která sečte délky všech slov. Průběžný součet začni na `0` bez typové anotace a nech kompilátor odvodit `number` z počáteční hodnoty, pak v cyklu `for-of` přičítej délku každého slova. `totalLength([\"hi\", \"there\"])` dává 7 a prázdný seznam dává 0.",
    hints: ["Proměnná inicializovaná číslem je od té chvíle číslo, takže do ní cyklus může přičítat bez jakékoli anotace."],
    approach: [
      "Průběžný součet deklaruj pomocí let s počáteční hodnotou 0 a typ nech na kompilátoru.",
      "Projdi slova cyklem for-of a k součtu přičti délku každého z nich.",
      "Vrať součet; deklarovaný návratový typ a odvozený typ součtu se shodují, takže nic dalšího není potřeba.",
    ],
    testLabels: ["", "", "jedno slovo", "prázdný vstup", "prázdná slova nic nepřidají"],
    typeTestLabels: ["vrací číslo", "součet není text", "čísla nemají délku, kterou by šlo sčítat"],
  },
  "ts-take-turns": {
    title: "Střídání ve frontě",
    prompt: "Napiš `takeTurns(waiting: string[], turns: number): string[]`, která obsluhuje lidi z fronty stylem round robin: člověk na začátku je obsloužen a jde na konec, dokud není obslouženo `turns` lidí. Seznam si nejdřív zkopíruj, aby pole volajícího zůstalo, jak bylo. `takeTurns([\"ada\", \"bo\"], 3)` dává `[\"ada\", \"bo\", \"ada\"]` a prázdná fronta dává prázdný seznam bez ohledu na počet kol.",
    hints: ["shift na string[] vrací string | undefined a kompilátor tě donutí undefined vyřešit dřív, než hodnotu někam pošleš."],
    approach: [
      "Zkopíruj čekající pomocí spreadu do typované fronty a založ prázdné string[] pro obsloužené.",
      "Opakuj, dokud je obsloužených méně než kol: pomocí shift vezmi začátek fronty a skonči, když tam nikdo není.",
      "Člověka zapiš a pak ho pomocí push pošli na konec fronty, aby přišel znovu na řadu.",
    ],
    testLabels: ["", "", "jeden člověk je obsluhován pořád dokola", "prázdná fronta nikoho neobslouží", "nula kol"],
    typeTestLabels: ["vrací seznam jmen", "ve frontě jsou řetězce", "počet kol je číslo"],
  },
  "ts-pad-a-readonly-list": {
    title: "Doplň readonly seznam",
    prompt: "Napiš `padScores(scores: readonly number[], size: number): number[]`, která vrátí kopii skóre doplněnou na konci nulami, dokud nemá `size` hodnot. Parametr je readonly, takže `push` na něm není k dispozici a kopii je potřeba nejdřív vytvořit spreadem. `padScores([7, 9], 4)` dává `[7, 9, 0, 0]` a seznam, který už velikost má nebo ji přesahuje, se vrátí jako obyčejná kopie.",
    hints: ["Kompilátor z readonly pole odstraní každou metodu, která ho mění, takže jediné pole, do kterého můžeš pushovat, je to, které si vytvoříš sám."],
    approach: [
      "Rozlož readonly pole spreadem do nového, obyčejného number[]; kopie push má, i když originál ne.",
      "Opakuj, dokud je kopie kratší než požadovaná velikost, a pokaždé pushni nulu.",
      "Vrať kopii; když byl originál už dost dlouhý, cyklus neproběhne a kopie zůstane beze změny.",
    ],
    testLabels: ["", "", "už je dost dlouhé", "prázdný vstup", "není co doplňovat"],
    typeTestLabels: ["vrací obyčejné pole", "readonly pole je přijato", "push na readonly poli neexistuje", "skóre jsou čísla"],
  },
  "ts-lowest-and-highest": {
    title: "Nejmenší a největší",
    prompt: "Napiš `minMax(values: number[]): [number, number]`, která vrátí nejmenší a největší hodnotu jako n-tici, nalezené jediným cyklem `for` přes seznam. `minMax([3, 1, 2])` dává `[1, 3]`, jediná hodnota je oběma konci a prázdný seznam dává `[0, 0]`.",
    hints: ["Oba konce začni na první hodnotě, ne na nule, jinak seznam záporných čísel nahlásí maximum, které nikdy neobsahoval."],
    approach: [
      "Nejdřív vyřeš prázdný seznam, protože bez první hodnoty nic z dalších kroků nefunguje.",
      "Nejmenší i největší nastav na první hodnotu a pak projdi cyklem od druhého indexu do konce.",
      "Každou hodnotu porovnej s oběma konci, nahraď ten, který překoná, a nakonec oba vrať jako n-tici.",
    ],
    testLabels: ["", "", "jedna hodnota je oběma konci", "samá záporná čísla", "prázdný vstup"],
    typeTestLabels: ["vrací přesně dvě čísla", "na každé pozici je číslo", "dvě, ne tři", "hodnoty jsou čísla"],
  },
  "ts-total-expenses": {
    title: "Celkové výdaje",
    prompt: "Deklaruj rozhraní `Expenses` s vlastnostmi `rent`, `food` a `travel`, všechny čísla, a napiš `totalExpenses(expenses: Expenses): number`, která je sečte cyklem `for-in`. Proměnná cyklu je obyčejný `string`, takže objekt indexuj přes ni jako `keyof Expenses`. `totalExpenses({ rent: 800, food: 250, travel: 50 })` dává 1100.",
    hints: ["Klíč z for-in je pro kompilátor jen string a string není důkaz, že vlastnost existuje, dokud nepotvrdíš, že jde o jeden z klíčů rozhraní."],
    approach: [
      "Napiš rozhraní se třemi číselnými vlastnostmi a založ průběžný součet na nule.",
      "Projdi objekt cyklem for-in; proměnná cyklu má typ string a kompilátor odmítne objekt přes ni indexovat.",
      "Uvnitř cyklu klíč přetypuj na keyof Expenses, přičti hodnotu, kterou přečte, a vrať součet.",
    ],
    testLabels: ["", "", "samé nuly", "vratka se odečítá", "desetinná čísla"],
    typeTestLabels: ["vrací číslo", "keyof pojmenuje jednu ze tří vlastností", "každá vlastnost je povinná", "částky jsou čísla"],
  },
  "ts-path-length": {
    title: "Délka cesty",
    prompt: "Deklaruj typový alias `Point` pro objekt s číselnými `x` a `y` a napiš `pathLength(points: Point[]): number`, která cyklem `for` sečte vzdálenosti vzdušnou čarou mezi každým bodem a tím dalším. `pathLength([{ x: 0, y: 0 }, { x: 3, y: 4 }])` dává 5 a méně než dva body dává 0.",
    hints: ["Každý krok cyklu potřebuje aktuální bod a ten před ním, takže index začni na 1, ne na 0."],
    approach: [
      "Alias napiš nad funkci a použij ho jako typ prvku parametru.",
      "Projdi cyklem od indexu 1 do konce, aby měl každý průchod předchozí bod k porovnání.",
      "Přičti vzdálenost z předchozího bodu do aktuálního, spočítanou z rozdílů v x a y, a vrať součet.",
    ],
    testLabels: ["", "", "jediný bod", "prázdný vstup", "stejný bod dvakrát", "záporné souřadnice"],
    typeTestLabels: ["Point je typ, na který se dá odkázat", "vrací číslo", "bod potřebuje obě souřadnice", "dvojice čísel není Point"],
  },
  "ts-mixed-total": {
    title: "Smíšený součet",
    prompt: "Napiš `mixedTotal(values: (string | number)[]): number`, která projde seznam cyklem `for-of` a každé číslo přičte tak, jak je, a každý řetězec jako jeho délku. Čtení `.length` vyžaduje hodnotu nejdřív zúžit na řetězec. `mixedTotal([1, \"abc\", 2])` dává 6 a prázdný seznam dává 0.",
    hints: ["Uvnitř cyklu je hodnota pořád celá unie a teprve kontrola typeof ji rozdělí na dva případy."],
    approach: [
      "Založ součet na nule a projdi hodnoty cyklem for-of.",
      "Uvnitř cyklu zkontroluj typeof: ve větvi pro řetězec ti kompilátor dovolí přečíst length, v druhé větvi je hodnota už číslo.",
      "V každé větvi přičti správnou částku a vrať součet.",
    ],
    testLabels: ["", "", "prázdný vstup", "prázdný řetězec nic nepřidá", "záporné číslo", "desetinná čísla"],
    typeTestLabels: ["vrací číslo", "prázdný seznam je povolený", "boolean do unie nepatří", "součet není text"],
  },
  "ts-only-the-files": {
    title: "Jen soubory",
    prompt: "Deklaruj rozhraní `FileEntry` (`kind: \"file\"`, `name` a číselná `size`) a `FolderEntry` (`kind: \"folder\"` a `name`) plus unii `type Entry = FileEntry | FolderEntry`. Napiš `isFile(entry: Entry): entry is FileEntry` a použij ji v `onlyFiles(entries: Entry[]): FileEntry[]`, která ponechá soubory v původním pořadí. `onlyFiles([{ kind: \"file\", name: \"a.txt\", size: 3 }, { kind: \"folder\", name: \"src\" }])` dává jen ten soubor.",
    hints: ["Návratový typ predikátu je to, díky čemu filter vrátí FileEntry[] místo unie, se kterou jsi začal."],
    approach: [
      "Deklaruj obě rozhraní a unii; každý záznam je označený svým kind.",
      "Napiš strážce jako booleovskou kontrolu kind s návratovým typem entry is FileEntry.",
      "Předej strážce do filter; přetížení, které bere predikát, zúží typ prvku výsledku.",
    ],
    testLabels: ["", "", "jen složky", "prázdný vstup", "prázdný soubor je pořád soubor"],
    typeTestLabels: ["vrací jen soubory", "predikát zúží cokoli, co filtruje", "vrací se soubory, ne složky", "něco bez kind není Entry"],
  },
  "ts-count-a-status": {
    title: "Spočítej stav",
    prompt: "Deklaruj řetězcový enum `Status` s členy `Todo = \"todo\"`, `Doing = \"doing\"` a `Done = \"done\"` a napiš `countStatus(items: Status[], wanted: Status): number`, která pomocí `reduce` spočítá, kolik položek se rovná hledanému členu. `countStatus([Status.Done, Status.Todo, Status.Done], Status.Done)` dává 2 a prázdný seznam dává 0.",
    hints: ["Akumulátor je obyčejné číslo začínající na nule a každý krok buď přičte jedničku, nebo ho pošle dál beze změny."],
    approach: [
      "Enum se třemi řetězcovými členy deklaruj nad funkcí.",
      "Seznam zredukuj s číselným akumulátorem, který začíná na nule.",
      "V každém kroku porovnej položku s hledaným členem a při shodě vrať počet plus jedna, jinak počet tak, jak je.",
    ],
    testLabels: ["", "", "nic neodpovídá", "prázdný vstup", "odpovídá každá položka"],
    typeTestLabels: ["vrací číslo", "Status je typ, na který se dá odkázat", "obyčejný řetězec není členem enumu", "hledaný stav je také člen enumu"],
  },
  "ts-chunk-a-list": {
    title: "Rozděl seznam na skupiny",
    prompt: "Napiš `chunk<T>(items: T[], size: number): T[][]`, která rozdělí seznam na skupiny po `size` položkách cyklem `for`, jenž postupuje po `size` a každou skupinu vyřízne pomocí slice; poslední skupina obsahuje, co zbylo. `chunk([1, 2, 3, 4, 5], 2)` dává `[[1, 2], [3, 4], [5]]` a prázdný seznam dává prázdný seznam. Velikost je vždy alespoň 1.",
    hints: ["Počítadlo cyklu je počáteční index a jeho posun o velikost skupiny při každém průchodu znamená, že každá skupina začíná tam, kde předchozí skončila."],
    approach: [
      "Jeden typový parametr popisuje prvek a výsledek je pole polí tohoto prvku.",
      "Projdi cyklem s počátečním indexem, který začíná na nule a roste o velikost skupiny.",
      "Vyřízni od počátečního indexu po počátek plus velikost a skupinu pushni; slice se na konci seznamu zastaví sám.",
    ],
    testLabels: ["", "", "prázdný vstup", "velikost větší než seznam", "skupiny po jednom"],
    typeTestLabels: ["čísla dovnitř, skupiny čísel ven", "řetězce dovnitř, skupiny řetězců ven", "výsledek je o jednu úroveň vnořený", "velikost je číslo"],
  },
  "ts-zip-two-lists": {
    title: "Spoj dva seznamy",
    prompt: "Napiš `zip<A, B>(left: A[], right: B[]): [A, B][]`, která cyklem `for` spáruje položky na stejném indexu do n-tic a zastaví se u kratšího seznamu. `zip([1, 2], [\"a\", \"b\"])` dává `[[1, \"a\"], [2, \"b\"]]` a když je kterýkoli seznam prázdný, výsledek je prázdný.",
    hints: ["Dva typové parametry drží oba seznamy nezávislé a typ n-tice ve výsledku určuje, který jde první."],
    approach: [
      "Projdi cyklem jen po kratší délku, aby žádný index nepřeběhl konec ani jednoho seznamu.",
      "Z obou položek na aktuálním indexu sestav n-tici a pushni ji do výsledku typovaného jako [A, B][].",
      "Vrať výsledek; se dvěma typovými parametry dostane volající zpět přesně tu dvojici typů, kterou předal.",
    ],
    testLabels: ["", "", "kratší seznam vyhrává", "jeden prázdný seznam", "null je hodnota jako každá jiná"],
    typeTestLabels: ["vrací n-tice ve stejném pořadí", "první pozice si drží typ levého seznamu", "pořadí v n-tici je pevné", "oba seznamy jsou povinné"],
  },
  "ts-group-by-key": {
    title: "Seskup podle klíče",
    prompt: "Napiš `groupBy<T, K extends PropertyKey>(items: T[], keyOf: (item: T) => K): Record<K, T[]>`, která cyklem `for-of` uloží každou položku pod klíč, který jí přidělí callback. Omezení hlídá, že klíč je něco, čím se dá objekt indexovat. `groupBy([1, 2, 3, 4], n => n % 2 === 0 ? \"even\" : \"odd\")` dává `{ odd: [1, 3], even: [2, 4] }` a prázdný seznam dává prázdný objekt.",
    hints: ["PropertyKey je unie všeho, co může pojmenovat vlastnost, a omezení K na ni je to, co dělá Record<K, ...> legálním."],
    approach: [
      "Začni prázdným objektem přetypovaným na návratový typ, protože kompilátor nevidí, že se klíče teprve doplní.",
      "Projdi položky, pro každou si od callbacku vyžádej klíč a při prvním výskytu klíče založ prázdnou skupinu.",
      "Položku pushni do její skupiny a objekt vrať; klíče výsledku jsou přesně ty hodnoty, které callback může vrátit.",
    ],
    testLabels: ["", "", "prázdný vstup", "číselný klíč", "do skupin jdou celé položky"],
    typeTestLabels: ["klíče jsou hodnoty, které callback vrací", "klíčem může být i číslo", "pole klíčem být nemůže", "skupiny obsahují položky, ne klíče"],
  },
  "ts-write-reduce": {
    title: "Napiš si vlastní reduce",
    prompt: "Napiš `myReduce<T, U>(items: T[], step: (acc: U, item: T) => U, initial: U): U`, která obyčejným cyklem `for` složí seznam do jedné hodnoty místo volání `reduce`. Akumulátor začíná jako `initial` a pro každou položku ho nahradí to, co vrátí `step`. `myReduce([1, 2, 3], (acc, n) => acc + n, 0)` dává 6 a prázdný seznam vrací `initial` beze změny.",
    hints: ["Typ položky a typ akumulátoru jsou různé typové parametry, protože součet čísel se dá stejně dobře skládat i do řetězce."],
    approach: [
      "Drž si proměnnou typovanou jako akumulátor, která začíná na počáteční hodnotě.",
      "Projdi položky cyklem přes index, zavolej krok s aktuálním akumulátorem a položkou a ulož, co se vrátí.",
      "Po cyklu vrať akumulátor; bez položek je to pořád počáteční hodnota.",
    ],
    testLabels: ["", "", "prázdný vstup vrací počáteční hodnotu", "akumulátor může mít jiný typ", "jediná položka"],
    typeTestLabels: ["čísla se skládají do čísla", "počáteční hodnota určuje typ výsledku", "číselné skládání nedává řetězec", "krok a počáteční hodnota se musí shodovat"],
  },
  "ts-pluck-all": {
    title: "Vytáhni všechny klíče",
    prompt: "Napiš `pluckAll<T, K extends keyof T>(items: T[], keys: K[]): T[K][][]`, která pro každou položku vrátí jeden řádek s hodnotami požadovaných klíčů v zadaném pořadí, postavený pomocí `map` uvnitř `map`. Typ indexovaného přístupu `T[K]` je to, co tyto vlastnosti obsahují. `pluckAll([{ id: 1, name: \"a\" }], [\"id\", \"name\"])` dává `[[1, \"a\"]]`.",
    hints: ["Omezení klíče na keyof T je to, co kompilátoru dovolí přečíst T[K] a znát typ každé hodnoty, kterou vytáhneš."],
    approach: [
      "Projdi položky pomocí map, aby z každé vznikl jeden řádek.",
      "Uvnitř projdi klíče pomocí map a přečti danou vlastnost z aktuální položky.",
      "Návratový typ je jeden indexovaný přístup, T[K], zabalený do dvou polí: hodnoty v řádku, řádky ve výsledku.",
    ],
    testLabels: ["", "", "prázdný vstup", "žádné klíče dávají prázdné řádky", "pořadí klíčů zůstává"],
    typeTestLabels: ["hodnoty jsou unie toho, co klíče obsahují", "jeden číselný klíč dává číselné řádky", "klíč, který neexistuje, je odmítnut", "vrací se řádky, ne plochý seznam"],
  },
  "ts-apply-patches-in-order": {
    title: "Aplikuj záplaty po řadě",
    prompt: "Deklaruj rozhraní `Profile` s řetězcem `name`, číslem `age` a řetězcem `city` a napiš `applyPatches(profile: Profile, patches: Partial<Profile>[]): Profile`, která aplikuje všechny záplaty po řadě a pokaždé postaví nový objekt, takže předaný profil se nikdy nezmění. `applyPatches({ name: \"Ada\", age: 36, city: \"London\" }, [{ age: 37 }, { city: \"Paris\" }])` dává `{ name: \"Ada\", age: 37, city: \"Paris\" }`.",
    hints: ["Partial<Profile> dovolí záplatě nést libovolnou podmnožinu vlastností a spread záplaty až za aktuální objekt je to, díky čemu pozdější záplata vyhraje."],
    approach: [
      "Drž si proměnnou s aktuálním profilem, která začíná na tom předaném.",
      "Projdi záplaty cyklem for-of a aktuální profil nahraď novým objektem: spread aktuálního a pak spread záplaty.",
      "Vrať aktuální profil; bez záplat je to původní objekt a originál se nikdy nemění.",
    ],
    testLabels: ["", "", "žádné záplaty", "prázdná záplata nic nezmění", "nula také přepisuje"],
    typeTestLabels: ["vrací kompletní profil", "záplata může nést libovolnou podmnožinu", "záplata musí mít správné typy", "výchozí profil je kompletní"],
  },
  "ts-score-by-player": {
    title: "Skóre podle hráče",
    prompt: "Deklaruj rozhraní `Round` s řetězcem `player` a číslem `points` a napiš `scoreByPlayer(rounds: Round[]): Record<string, number>`, která cyklem `for-of` sečte body každého hráče. Hráč viděný poprvé ještě žádný záznam nemá, takže chybějící hodnotu ber jako 0. `scoreByPlayer([{ player: \"ada\", points: 3 }, { player: \"bo\", points: 1 }, { player: \"ada\", points: 2 }])` dává `{ ada: 5, bo: 1 }`.",
    hints: ["Čtení klíče, který v Record<string, number> ještě není, dá za běhu undefined, takže před přičtením spadni na nulu."],
    approach: [
      "Založ prázdný objekt typovaný jako Record<string, number>.",
      "Projdi kola cyklem for-of, přečti dosavadní součet pod jménem hráče a chybějící součet ber jako nulu.",
      "Pod to jméno ulož součet plus body z kola a objekt vrať.",
    ],
    testLabels: ["", "", "prázdný vstup", "nula bodů přesto založí záznam", "záporné body se odečítají"],
    typeTestLabels: ["vrací slovník čísel", "vyhledat lze jakékoli jméno", "kolo potřebuje své body", "hodnoty jsou čísla, ne řetězce"],
  },
  "ts-freeze-a-copy": {
    title: "Zmraz kopii",
    prompt: "Deklaruj mapovaný typ `Frozen<T>`, který zachová každou vlastnost `T` s jejím typem, ale označí ji `readonly`, a napiš `freezeCopy<T extends object>(source: T): Frozen<T>`, která postaví nový objekt z `Object.entries` v cyklu `for-of` a před vrácením ho zmrazí pomocí `Object.freeze`. `freezeCopy({ a: 1 })` dává objekt rovný `{ a: 1 }`, který není tentýž objekt, a přiřazení do jeho `a` je chyba při kompilaci.",
    hints: ["Mapovaný typ projde keyof T a před každou vlastnost, kterou vytvoří, může dát modifikátor; cyklus dělá totéž za běhu, po jednom záznamu."],
    approach: [
      "Napiš mapovaný typ s readonly před výrazem klíče a T[K] jako typem hodnoty.",
      "Vytvoř prázdný objekt přetypovaný na měnitelný tvar a v cyklu for-of do něj zkopíruj každý záznam z Object.entries.",
      "Kopii zmraz a vrať; měnitelný tvar je přiřaditelný do readonly tvaru, takže návratový typ sedí.",
    ],
    testLabels: ["", "kopie je zmrazená", "vrací se jiný objekt", "prázdný vstup", "vnořená hodnota jde s sebou"],
    typeTestLabels: ["vrací zmrazený tvar", "každá vlastnost si drží svůj typ", "do zmrazené vlastnosti nejde přiřadit", "zmrazit lze jen objekty"],
  },
  "ts-values-of-a-type": {
    title: "Hodnoty daného typu",
    prompt: "Deklaruj `type TypeName = \"string\" | \"number\" | \"boolean\"` a podmíněný typ `OfType<N extends TypeName>`, který se pro odpovídající název vyhodnotí na `string`, `number` nebo `boolean`. Pak napiš `ofType<N extends TypeName>(values: unknown[], name: N): OfType<N>[]`, která pomocí `filter` a typového predikátu ponechá v původním pořadí hodnoty, jejichž `typeof` se rovná názvu. `ofType([1, \"a\", 2, true], \"number\")` dává `[1, 2]`.",
    hints: ["Podmíněný typ je řetězec kontrol extends, které vyberou jeden typ pro každý název, a predikát na callbacku filtru je místo, kde výsledek za běhu ten typ dostane."],
    approach: [
      "Podmíněný typ napiš jako řetězec: když N extends název řetězce, dej string, když název čísla, dej number, jinak boolean.",
      "Hodnoty filtruj callbackem, jehož návratový typ je predikát na OfType<N>.",
      "Uvnitř callbacku porovnej typeof value s názvem; predikát provede zúžení a filter vrátí zúžené pole.",
    ],
    testLabels: ["", "", "", "prázdný vstup", "null a undefined neodpovídají ničemu", "číselný řetězec je pořád řetězec"],
    typeTestLabels: ["název určuje typ prvku", "a s názvem se mění", "čísla se nevrací jako řetězce", "povolené jsou jen tři názvy"],
  },
  "ts-memoized-run": {
    title: "Memoizovaný průchod",
    prompt: "Deklaruj `type Output<F> = F extends (arg: number) => infer R ? R : never`, který pomocí `infer` vytáhne návratový typ z typu funkce, a napiš `runMemoized<F extends (arg: number) => unknown>(fn: F, inputs: number[]): Output<F>[]`. Projdi vstupy cyklem s `Map` jako cache, aby už viděný vstup použil uložený výsledek místo dalšího volání `fn`, a vrať výsledky v pořadí vstupů. `runMemoized(n => n * 2, [1, 1, 2])` dává `[2, 2, 4]` a `fn` zavolá dvakrát.",
    hints: ["infer pojmenuje část typu, kterou chceš zachytit, a podmínka se na ni vyhodnotí, kdykoli F odpovídá tvaru funkce."],
    approach: [
      "Podmíněný typ napiš s infer R na místě návratového typu funkce a s R v pravdivé větvi.",
      "Vytvoř Map z čísla na Output<F> a prázdné pole výsledků, pak projdi vstupy cyklem for-of.",
      "Když cache pro vstup nic nemá, zavolej fn a výsledek pod něj ulož; pak pushni hodnotu z cache do výsledků.",
    ],
    testLabels: ["", "", "opakovaný vstup se počítá jen jednou", "prázdný vstup", "funguje jakýkoli návratový typ"],
    typeTestLabels: ["typ výsledku se řídí funkcí", "funkce vracející řetězec dává řetězce", "Output vytáhne návratový typ sám o sobě", "čísla se nevrací jako řetězce"],
  },
  "ts-tag-every-id": {
    title: "Označ každé id",
    prompt: "Deklaruj typ template literalu `Tag<P extends string>` pro řetězce ve tvaru `${P}-${number}` a napiš `tagAll<P extends string>(prefix: P, ids: number[]): Tag<P>[]`, která v cyklu `for-of` postaví jeden tag pro každé id pomocí template stringu. `tagAll(\"user\", [1, 2])` dává `[\"user-1\", \"user-2\"]` a žádná id dávají prázdný seznam.",
    hints: ["Template string složený z P a čísla dostane typ template literalu, když ho místo, kam jde, očekává, takže pole výsledků otypuj dřív, než do něj pushneš."],
    approach: [
      "Alias napiš s parametrem prefixu a number uvnitř typu template literalu.",
      "Založ prázdné pole typované Tag<P>[] a projdi id cyklem for-of.",
      "Pushni template string z prefixu, pomlčky a id; právě otypované pole přiměje kompilátor zachovat literálový typ.",
    ],
    testLabels: ["", "", "žádná id", "nula a dvouciferné číslo", "prázdný prefix"],
    typeTestLabels: ["prefix se propíše do typu", "každý tag je jeden template literal", "jiný prefix je jiný typ", "prefix je řetězec"],
  },
  "ts-pair-with-a-sum": {
    title: "Dvojice se součtem",
    prompt: "Napiš `pairWithSum(sorted: readonly number[], target: number): [number, number] | null`, která ve vzestupně seřazeném seznamu najde dvě hodnoty se součtem rovným cíli pomocí dvou ukazatelů: jeden na každém konci, posouvané dovnitř v cyklu `while` podle toho, zda je aktuální součet příliš malý, nebo příliš velký. Dvojici vrať jako n-tici, nebo `null`, když žádná není. `pairWithSum([1, 2, 3, 4, 6], 6)` dává `[2, 4]`.",
    hints: ["Seznam je seřazený, takže příliš malý součet napraví jen posun levého ukazatele nahoru a příliš velký jen posun pravého dolů."],
    approach: [
      "Jeden index dej na začátek a druhý na konec a opakuj, dokud je levý index pod pravým.",
      "Sečti obě hodnoty: při shodě je vrať jako n-tici, při součtu pod cílem posuň levý index nahoru, jinak posuň pravý dolů.",
      "Když se ukazatele potkají, žádná dvojice nebyla, takže vrať null; návratový typ říká, že volající to musí ošetřit.",
    ],
    testLabels: ["", "", "žádná dvojice nedává součet", "prázdný vstup", "záporné hodnoty", "dvě stejné hodnoty"],
    typeTestLabels: ["vrací dvojici nebo null", "readonly seznam je přijat", "případ null nejde ignorovat", "hodnoty jsou čísla"],
  },
  "ts-binary-search": {
    title: "Binární vyhledávání",
    prompt: "Napiš `binarySearch(sorted: readonly number[], target: number): number`, která vrátí index hledané hodnoty ve vzestupně seřazeném seznamu, nebo -1, když tam není, a to půlením prohledávaného rozsahu v cyklu `while`: porovnej prostřední hodnotu a pokračuj v levé, nebo pravé polovině. `binarySearch([1, 3, 5, 7], 5)` dává 2 a prázdný seznam dává -1.",
    hints: ["Drž si dolní a horní index, které ohraničují hodnoty, jež ještě stojí za prohlédnutí, a skonči, jakmile dolní index přejde přes horní."],
    approach: [
      "Dolní index nastav na 0 a horní na poslední index a opakuj, dokud je dolní nejvýš roven hornímu.",
      "Prostřední index vezmi celočíselným dělením; při shodě ho vrať.",
      "Prostřední hodnota pod cílem posune dolní index za střed, hodnota nad cílem posune horní před něj; když cyklus skončí, vrať -1.",
    ],
    testLabels: ["", "", "hodnota, která tam není", "prázdný vstup", "jediná hodnota", "poslední hodnota"],
    typeTestLabels: ["vrací index", "readonly seznam je přijat", "hodnoty jsou čísla", "vrací se index, ne boolean"],
  },
};
